[2-P박진형] SpringBoot Part1 Weekly Mission 코드리뷰 요청합니다.
prgrms-be-devcourse/springboot-basic pull request #168
Opened 2022-04-07 18:30 UTC by pjh612

## 📌 과제 설명 
Voucher 관리하는 SpringBoot 커맨드라인 애플리케이션을만듭니다.

## 👩‍💻 요구 사항과 구현 내용 
- [x] 스프링 부트 커맨드 라인 애플리케이션으로 만든다.
- [x] 프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
```bash
=== Voucher Program ===
Type **exit** to exit the program.
Type **create** to create a new voucher.
Type **list** to list all vouchers.
```
- [x] create/list 커맨드를 지원한다.
 -  create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
 - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
 - 바우처 정보를 메모리에 관리한다.

- [x] 적절한 로그를 기록하고 logback 설정을해서 에러는 파일로 기록된다.
 - dev 프로파일에서는 콘솔에 로그가 출력되고. prod 프로파일에서는 logs 폴더에 파일로 로그가 저장됩니다.
- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.  기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
 - dev 프로파일에서는 메모리로 동작하고, prod 프로파일에서는 파일 db로 동작합니다.
- [x]  고객 블랙 리스트 명단을 작성한다. - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다
 - blacklist 명령어로 등록된 blacklist를 조회할 수 있습니다.
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.
```yaml
db:
  path: src/main/resources/db
  blacklist:
    db_name: customer_blacklist.csv
  voucher:
    db_name: voucher_db.csv

spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

```
 - profile은 dev와 prod로 나눌 수 있습니다.
 - db 디렉토리의 경로를 지정할 수 있습니다.
 - db 파일명을 지정할 수 있습니다.
 - jar로 실행시 --db.path 로 jar파일 위치 기준 상대 경로로 db 디렉토리를 직접 지정할 수 있습니다.
   - 기본 db 세팅 경로로 main/resources/db의 db 파일들을 사용하려면 jar파일을 voucher-management에 위치하면 됩니다.
 - 테스트 무한루프로 jar파일이 생성이 되지 않습니다 아래 궁금한점에 자세한 내용 써뒀습니다.
   - --exclude-task test로 테스트를 생략하면 jar파일이 생성됩니다.

## ✅ PR 포인트 & 궁금한 점 
- VoucherManager 클래스가 제가 생각하기엔 코드가 많이 지저분한 것 같습니다 개선 방향에 힌트를 주시면 감사하겠습니다!

- 전에도 여쭤봤던 문제인데 VoucherManager의 blacklistCommand(), listCommand() 에서 모두 스트림 + 람다로 output.println()을 통해서 Service layer에서 조회한 데이터를 출력하고자 하고 있습니다.
  - output.println()은 IO Exception이 throw될 수 있는 함수이기때문에 아래와 같이 핸들링 해줘야된다고 나오는데요
![image](https://user-images.githubusercontent.com/62292492/162260942-8795c9a8-c0d1-4f19-91f4-2ae04cafddb6.png)
이럴 경우 말씀드렸다시피 구글링 결과 UncheckedException으로 래핑해서 우회하는 방식이 있지만 과연 이런식으로 우회하는게 옳은 방식인건지 의구심이 듭니다.
  - 해결책을 잠깐 말씀해주셨는데 이해가 잘 안돼서 다시 여쭤봅니다..ㅜ

- CommandLineRunner 인터페이스를 이용해 스프링부트 커맨드라인 애플리케이션을 만들고자 했습니다.
  - 이럴 경우 SpringBootTest를 돌릴 시 VoucherManager의 run()에서의 while문 때문인지 테스트가 진행되지않고 무한루프가 도는 상황이 발생하는것 같은데요.
  - 원인이 이것 때문이 맞는지
  - 맞다면 어떤 방향으로 해결해야될지 힌트 투척해주시면 감사하겠습니다.

- 곰튀김님 강의에서도 메인로직에서 저와 같이 입출력 모듈은 분리를 했는데요 (FileIO, FileInput,FileOutput)
  - 분리하는 근거를 명확히 알고 넘어가고싶어 분리하는 이유에 대해서 생각을 해봤습니다.
  - 단일 책임원칙은 변경의 이유가 단 하나여야한다는 원칙으로 알고 있습니다.
  - Voucher의 변경의 이유는 list, create와 같은 기능의 변경으로 생각했고 입출력 방식의 변경(파일로 입출력, 콘솔로 입출력, 웹에서 입출력 등의 변경) 이라고 생각했습니다.
  - 그렇기 때문에 분리를 하는게 맞다고 생각했는데 이 근거가 맞을까요?

- 로그 레벨을 정하는 스킬이나 로그 메시지를 작성하는 스킬이 좀 많이 미숙했다고 생각했습니다. 
  - 로그를 코드 중간 중간 출력하다보니 코드가 많이 지저분해진 느낌인데 어쩔수 없는 부분인가요?
 
- 커밋 단위는 2주차 과제부터 다시 더 신경 써서 해보겠습니다 ㅜ

회초리 달게 받겠습니다. 지적 많이 해주시면 큰 도움이 될것같습니다 ㅎ_ㅎ..

2022-04-09 17:21 UTC, Jo-GyuHyeon requested changes
`이럴 경우 SpringBootTest를 돌릴 시 VoucherManager의 run()에서의 while문 때문인지 테스트가 진행되지않고 무한루프가 도는 상황이 발생하는것 같은데요.` 

테스트 타겟설정이 잘못되었다고 생각합니다. 각 세부 기능들에 대해 unit 테스트를 하시는 것을 제안드립니다.

```
로그를 코드 중간 중간 출력하다보니 코드가 많이 지저분해진 느낌인데 어쩔수 없는 부분인가요?
```
불필요한 로그가 많았습니다.
모든 데이터를 로그를 기록하기 보다는 호출 되는 정보를 추적 할 수 있는 단위정도를 생각해주시면 될것 같습니다.

네이밍과 가독성을 신경써주시면 좋을것 같습니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/blacklist/BlacklistRepository.java
> +        .forEach(user -> logger.info(user.toString()));
메서드 호출 할때 매번 로그를 찍는것은 성능적으로 좋지 않을 뿐더러 불필요한 부분이라 생각합니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/io/FileIO.java
> +    while ((line = bufferedReader.readLine()) != null) {
구문 사이에 개행을 추가하면 가독성이 높아진다고 생각합니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/utils/VoucherDeserializer.java
> +    return voucherFactory.createVoucher(id, value, type);
this 를 사용해주세요. 
메서드 네이밍에서 create 만 사용하셔도 충분히 이해가 된다고 생각합니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/utils/VoucherFactory.java
> +    return null;
null 이 return 되는 경우는 어떠한 경우인가요?

혹시 null retrun 을 고려하는 것보다는 optional 로써 return 하는 것은 어떨까요?

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/voucher/VoucherFileRepository.java
> +        voucher.getCreatedAt();
converter 를 이용하는 것이 좋을것 같습니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/service/AddVoucherService.java
> +public class AddVoucherService {
기능별로 클래스를 만들기 보다는 클래스에서 여러 기능을 제공하는 것이 알맞습니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/service/AddVoucherService.java
> +    Voucher voucher = new FixedAmountVoucher(UUID.randomUUID(), amount, LocalDateTime.now());
`LocalDateTime.now()`는 Voucher 클래스의 기본 값으로 지정하면 인자의 수를 줄일 수 있습니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/service/BlacklistService.java
> +    foundBlacklist.stream().forEach(user -> logger.info(user.toString()));
불필요한 로깅이라고 생각합니다.

2022-04-09 17:21 UTC, Jo-GyuHyeon commented on voucher-management/src/main/resources/application.yaml
> +  path: src/main/resources/db
파일 경로는 필요하나 resource 이전의 경로는 불필요하다고 생각합니다.
resourceLoader 를 사용하여 resource 로 부터 파일을 참조하세요

2022-04-12 15:24 UTC, pjh612 commented on voucher-management/src/main/java/com/voucher/vouchermanagement/service/AddVoucherService.java
> +    Voucher voucher = new FixedAmountVoucher(UUID.randomUUID(), amount, LocalDateTime.now());
DB에서 값을 읽어올 때는 DB에 저장되어있는 createdAt 데이터를 집어넣어야하기 때문에 불가피하게 3개의 인수를 사용했습니다 혹시 이 보다 좋은 방향이 있을까요?

2022-04-12 15:26 UTC, pjh612 commented on voucher-management/src/main/java/com/voucher/vouchermanagement/service/AddVoucherService.java
> +    Voucher voucher = new FixedAmountVoucher(UUID.randomUUID(), amount, LocalDateTime.now());
db에서 읽어올때는 3개가 필요하지만
일반적으로 생성할땐 2개의 인자가 필요하긴합니다.

id, amount 두개의 인자를 받고 LocalDateTime.now()를 생성자 내부에서 쓰는 생성자 하나
db에서 읽어올때 사용할 createdAt을 인자로 받는 생성자 하나 따로 만드는게 좋을까요?

2022-04-13 02:12 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/service/AddVoucherService.java
> +    Voucher voucher = new FixedAmountVoucher(UUID.randomUUID(), amount, LocalDateTime.now());
지금 보니 해보니 생성할땐 amount 하나만 있으면 될것 같네요.
생성용, 읽기용 생성자를 따로 분리하시되 생성자를 재사용 할 수 있도록 해보시면 어떨까요? 😀

2022-04-13 17:44 UTC, pjh612 commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/voucher/VoucherFileRepository.java
> +        voucher.getCreatedAt();
Converter를 사용하라는게 스프링 코어의 Converter를 구현해서 쓰라는건가요? 
아니면 String.format 또는 StringBuilder 또는 DTO를 만들어서 toString 오버라이딩 또는 메서드를 정의해서 변환하는 방향을 말씀하시는건가요?

2022-04-13 18:08 UTC, pjh612 commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/blacklist/BlacklistRepository.java
> +      @Qualifier("blacklistDeserializer") CsvDeserializer<User> csvDeserializer) {
다시 생각해보니까 굳이 빈으로 관리할 필요가 없는 것 같아서 아래와 같이 수정하는 방안을 생각해 봤습니다.
```java
@Value("${db.blacklist.db_name}")
  private String blackListDbName;
  private final Resource blacklistDb;
  private final FileInput input;
  private final FileOutput output;
  private final CsvDeserializer<User> csvDeserializer = new BlackListDeserializer();
  private final Logger logger = LoggerFactory.getLogger(BlacklistRepository.class);

  public BlacklistRepository(FileInput input, FileOutput output) {
    blacklistDb = new ClassPathResource("db/" + blackListDbName);
    this.input = input;
    this.output = output;
  }
```

2022-04-16 03:27 UTC, Jo-GyuHyeon commented on voucher-management/src/main/java/com/voucher/vouchermanagement/repository/voucher/VoucherFileRepository.java
> +        voucher.getCreatedAt();
스프링 코어의 Converter를 사용하기 하라는 것은 아니였습니다.
dataString 을 보았을때 csv 에 저장하는 위한 포맷으로 변환하는 기능이 필요하다고 하여 convert 라는 용어를 사용하였습니다.
toString 은 로그 혹은 출력을 담당하기에 재정의 하기보다는 별도의 (저장가능한 형식) 변환기능을 추가적으로 구현하는 것을 제안드립니다.

2022-04-16 05:11 UTC, Jo-GyuHyeon requested changes
많은 내용을 코드리뷰는 하지 못하였습니다. ㅠㅠ 
일단 첫번째로 눈에 띄는 부분은 프로젝트가 하나의 폴더를 더 감싸고 있습니다. (voucher-management) 
해당 부분은 한단계 풀어서 commit 하시는 것을 제안드립니다.

두번째로 try catch 를 너무 남발 혹은 전체 범위를 잡는 경향이 있습니다. try catch 의 성능을 논하기 어전에 어떤 부분에서 예외가 발생할지 추적이 힘들수도 있습니다. 적절히 필요한 곳에서만 try catch 를 사용하는 것을 제안 드립니다.

세번째로 repository 안의 io, utils 에 관련된 내용입니다.
해당 패키지의 클래스들은 실은 repository 의 구현체라고 바라볼수 있을 것 같습니다.
repository 를 인터페이스화 하고 해당 구현체들을 fileSystem 으로써 구현체를 제공하는 것이 어떨까요? 그렇다면 추후에는 구현체가 db 로 변경하였을때도 대응이 될 것이라 생각합니다.

지난번에 비해 컨벤션, 네이밍을 고민하는 모습이 느껴집니다. 고생하셨습니다.
하지만 중복 되거나, 불필요하게 길게 작성한 부분은 없을까? 에 대해 한 고민도 해보시면 좋을것 같습니다.

2022-04-18 03:39 UTC, pjh612 commented
남겨주신 피드백 중에서

"세번째로 repository 안의 io, utils 에 관련된 내용입니다.
해당 패키지의 클래스들은 실은 repository 의 구현체라고 바라볼수 있을 것 같습니다.
repository 를 인터페이스화 하고 해당 구현체들을 fileSystem 으로써 구현체를 제공하는 것이 어떨까요? 그렇다면 추후에는 구현체가 db 로 변경하였을때도 대응이 될 것이라 생각합니다."

이 항목이 조금 헷갈리는 부분들이 있어서 질문드립니다! 
첫째로, 수정하기 이전에 이미 VoucherRepository는 구현체가 JdbcRepository로 변경되어도 잘 대응되는 것이 아닌가요?

둘째로, 말씀하신 것 처럼 io와 utils부분을 repository로 인터페이스화 하고 구현체 내에서 직접 구현하는 식으로 수정 해봤는데요 이렇게 하는게 말씀하신 의도가 맞을까요?
맞다면 csvDeserialize() 나 getBufferedReader() getBufferedWriter() 등 몇 가지 부분 로직들을 private 함수로 분리를 해봤습니다. 그런데 여기서, VoucherFileRepository와 BlacklistFileRepository 에서 csvDeserialize() 함수와 같이 역할은 같고, 함수 구현이 조금씩 다른 부분, getBufferedReader(), getBufferedWriter() 와 같이 완전히 똑같은 함수들이 있어 중복이 많이 일어났다는 느낌이 들었습니다. 이 부분을 개선할 여지나 방향성이 있을까요?

또 추가적인 질문으로
VoucherType과 Command 목록들을 출력하는 VoucherManagerConsole.java의  printVoucherType(), printMenu() 함수에서
VoucherType을 출력하는것은 VoucherType enum에서 toString을 오버라이딩해서 바로
"1. FixedAmountVoucher"
"2. PercentDiscountVoucher" 와 Enum values를 출력하도록 했습니다.
```java
VoucherType.enum ->
@Override
    public String toString() {
        return typeNumber + ". " + typeName;
    }
```


Command 목록들을 출력하는 것은
getDescription함수를 CommandType 내부에 구현을 해서 출력할 수 있도록 해봤습니다.

```java
CommandType.enum ->
public String getCommandDescription() {
        return commandDescription;
    }

printMenu() ->
Arrays.stream(CommandType.values())
                .map(CommandType::getCommandDescription)
                .forEach(System.out::println);
```

이 중 어떤 방법을 선택해도 상관없을까요?

2022-04-19 07:52 UTC, whyWhale approved these changes
- 수고하셨습니🥕 . 

`endCodeRevie();`

2022-04-19 07:52 UTC, whyWhale commented on src/main/java/com/voucher/vouchermanagement/repository/voucher/VoucherFileRepository.java
> +    private BufferedReader getBufferedReader(String directory, String target) {
- voucher 랑 black list 두 곳 모두 buffer 사용해 읽어오는 코드가 유사해 보이는데 utils 빼서 공용으로 사용하면 좋을 것 같습니 🥕 .

2022-04-19 07:52 UTC, whyWhale commented on src/main/java/com/voucher/vouchermanagement/repository/voucher/VoucherFileRepository.java
> +    private BufferedReader getBufferedReader(String directory, String target) {
writer도요 !! 🤫

2022-04-19 07:52 UTC, whyWhale commented on src/main/java/com/voucher/vouchermanagement/manager/VoucherManager.java
> +    private void logAndPrintException(Exception exception) {
- print(Exception exception)이 낫지 않을까요?? 나머지는 오오오오오보보보보로로로로오오오오딩 하면 될 것 같습니 🥕

2022-04-19 07:58 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/repository/blacklist/BlacklistFileRepository.java
> +import com.voucher.vouchermanagement.model.customer.Customer;
패키지 컨벤션이라면 어떤 컨벤션을 말씀하시는건가요?😀

2022-04-19 07:59 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/model/voucher/VoucherType.java
> +public enum VoucherType {
정확한 명칭은 모르겠지만 전략패턴이라고 볼 수 있을것 같습니다~

2022-04-19 08:04 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/manager/VoucherManager.java
> +        CommandType commandType = null;
음 저도 null로 설정을 해두는 것이 조금 찝찝했는데 또 사용자 의도와는 무관한 명령어를 기본값으로 두는 것이 맞는가? 싶은 생각도 있었습니다. 이 부분은 같이 얘기 해봐도 좋을 것 같아요

2022-04-19 08:06 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/repository/voucher/VoucherFileRepository.java
> +    private BufferedReader getBufferedReader(String directory, String target) {
동감입니다 원래는 밖으로 뺏었는데 멘토님께서 리뷰해주신 내용이 있어서 일단 이렇게 바꿔봤는데 잘 못 이해한건지 썩 만족스러운 코드 모양새가 안나오네요..

2022-04-19 08:29 UTC, HyoungUkJJang commented on voucher-management/src/main/java/com/voucher/vouchermanagement/manager/VoucherManager.java
> +            this.output.println("=== [Create Voucher] ===");
이 메시지를 CommandType 클래스에 INIT과 같은 키워드로 같이 사용하면  병연님 께서 말씀해 주신 null에서도 방지가 되지 않을까 생각을 해봤는데 진형님 생각은 어떠신가요 !?

2022-04-21 20:29 UTC, pjh612 commented
FileRepository에서 File 입출력 부분과, Deserializer를 다시 분리했는데 해당 클래스들은 FileRepository내부에서 new로 생성을하도록 구현을 했습니다.

근데 이것들이 new로 생성되어야할지 아니면 static 메소드로 변경이 되어야할지 bean으로 등록되어야 할지 혼란이 와서 질문 드립니다.

FileInput FileOutput은 모든 FileRepository에서 사용할 예정이니 bean으로 등록되거나 static 메서드로 변경되는게 맞을까요?
그렇다면 bean, static 둘 중 어느게 맞는지 궁금합니다.
FileInput, FileOutput 내부에 구현된 메서드들은 util성이 강해보이는 편의 메소드라고도 생각이 들어 static이 맞는가 싶으면서도 static 메서드는 남발해서는 안된다 라는 말을 또 들은적이 있어서 bean으로 등록하는게 나은가 싶기도 합니다.

deserializer도 같은 맥락으로 궁금합니다.

두번째로, 처음에는 FileInput, FileOutput을 인터페이스로 만들어 FileIO라는 구현체를 만들어 두 인터페이스를 동시에 구현을 했지만 지금은 그냥 FileInput,FileOutput 이라는 "클래스"로 바로 구현체로 사용했습니다.

사실 FileInput, FileOutput안의 메소드들은 파일 입출력에 관한 메서드들 입니다. 별도의 다른 방식으로 추가적으로 구현될 여지도 없어보이기도합니다. 그렇다면 굳이 인터페이스를 만들어야 되나? 하는 생각에 바꿔봤습니다.
레이어드 아키텍처에서 무작정 service, repository들을 인터페이스를 분리하는 것은 많은 사람들이 흔히 잘못 사용하고 있는 안티패턴이라고 들었습니다. 인터페이스와 구현체가 1:1 대응될것이라면 나눌 필요 없다는 얘기로 이해했습니다.
제가 만든 FileInput, FileOutput에 적용되는 얘기가 맞을까요?

2022-04-21 20:51 UTC, pjh612 commented
FileRepository에서 File 입출력 부분과, Deserializer를 다시 분리했는데 해당 클래스들은 FileRepository내부에서 new로 생성을하도록 구현을 했습니다.

근데 이것들이 new로 생성되어야할지 아니면 static 메소드로 변경이 되어야할지 bean으로 등록되어야 할지 혼란이 와서 질문 드립니다.

FileInput FileOutput은 모든 FileRepository에서 사용할 예정이니 bean으로 등록되거나 static 메서드로 변경되는게 맞을까요?
그렇다면 bean, static 둘 중 어느게 맞는지 궁금합니다.
FileInput, FileOutput 내부에 구현된 메서드들은 util성이 강해보이는 편의 메소드라고도 생각이 들어 static이 맞는가 싶으면서도 static 메서드는 남발해서는 안된다 라는 말을 또 들은적이 있어서 bean으로 등록하는게 나은가 싶기도 합니다.

deserializer도 같은 맥락으로 궁금합니다.

두번째로, 처음에는 FileInput, FileOutput을 인터페이스로 만들어 FileIO라는 구현체를 만들어 두 인터페이스를 동시에 구현을 했지만 지금은 그냥 FileInput,FileOutput 이라는 "클래스"로 바로 구현체로 사용했습니다.

사실 FileInput, FileOutput안의 메소드들은 파일 입출력에 관한 메서드들 입니다. 별도의 다른 방식으로 추가적으로 구현될 여지도 없어보이기도합니다. 그렇다면 굳이 인터페이스를 만들어야 되나? 하는 생각에 바꿔봤습니다.
레이어드 아키텍처에서 무작정 service, repository들을 인터페이스를 분리하는 것은 많은 사람들이 흔히 잘못 사용하고 있는 안티패턴이라고 들었습니다. 인터페이스와 구현체가 1:1 대응될것이라면 나눌 필요 없다는 얘기로 이해했습니다.
제가 만든 FileInput, FileOutput에 적용되는 얘기가 맞을까요?

2022-04-23 08:15 UTC, Jo-GyuHyeon requested changes
고생하셨습니다.
고민 하셨던 내용에 대해 더 자세히 얘기가 필요하다면 커멘트 형식이 아닌 대화로 얘기해봐도 좋을 것 같습니다.

2022-04-23 08:15 UTC, Jo-GyuHyeon commented on src/main/java/com/voucher/vouchermanagement/model/voucher/PercentDiscountVoucher.java
> +            throw new IllegalArgumentException("100%를 초과할 수 없습니다.");
OR 연산자를 사용한다면 코드를 줄일 수 있습니다. :)

2022-04-23 08:15 UTC, Jo-GyuHyeon commented on src/main/java/com/voucher/vouchermanagement/repository/blacklist/BlacklistFileRepository.java
> +    private static final CsvDeserializer<Customer> csvDeserializer = new CustomerDeserializer();
해당 부분이 고민스러워 하시는 부분인것으로 보입니다.
고민 하시는 포인트와 다르게 또다른 생각이 들어서 말씀드릴까 합니다.

`FileInput`, `FileOut` 클래스를 별도로 있어야 될까? 라는 생각도 들기도 합니다. 오히려 해당 시스템의 FileUtil (혹은 다른네이밍) 로 하나 합쳐보면 어떨까? 싶은 생각도 듭니다.

그리고 File 에서 데이터를 읽어 오는 기능에서 제네릭한 메서드를 제공하는 것은 어떨까요? 예를 들면 `file.readAll<Customer>();` 
만일 이렇게 한다면 FileUtil 은 serialize, deserialize 를 이용하면 됩니다. 

serialize, deserialize 은 또한 일종의 Mapper 로써 하나의 클래스로 묶을수 있다고 생각하기도 하며 혹은 FileUtil 에 종속적이기에 private 메서드로써 존재해도 충분하다고도 생각이 듭니다.

[마지막으로 고민하셨던 Spring Bean Vs Static method 에 대한 고민을 하셔서 참고 링크를 드립니다.](http://kwon37xi.egloos.com/4844149?fbclid=IwAR1xFeOpZoEIax-poKhS1Lz5LiYdAoU6p4bRt-HNGyd3vIlNpljvvOomfvM)

2022-04-23 17:38 UTC, closed without merging