[2C-남득윤] 바우처 관리 애플리케이션 루프 템플릿 까지
prgrms-be-devcourse/springboot-basic pull request #169
Opened 2022-04-07 18:43 UTC by ndy2

## 📌 과제 설명
커맨드 라인 바우처 관리 애플리케이션 구현 과제입니다.

## 👩‍💻 요구 사항과 구현 내용
요구 사항은 `exit`, `create`, `list` 명령을 지원하는 바우처 애플리케이션의 구현입니다.
이때 바우처는 `FixedAmountVoucher`, `PercentDiscountVoucher` 두가지가 있습니다.

`create` 커맨드 이후 사용자의 입력에 따라 생성되는 바우처의 타입이 결정되도록 구현할 예정입니다.
`list` 커맨드는 전체 바우처를 조회하는 커맨드입니다.

---
현재 기능 구현은 전혀 하지 않았고 계속해서 메뉴를 출력하고 입력을 받을 수 있는 템플릿 까지 구현하였습니다.

크게 `app`, `order`, `voucher` 세개의 패키지로 구분하였습니다.
- `app` - order과 voucher를 활용한 애플리케이션의 구동
- `order` - 주문 엔티티와 관련된 모든 것
- `voucher` - 바우처 엔티티와 관련된 모든 것

구현시 고려한 사항
- `app` 패키지를 구현할때 지난 미션이었던 계산기 과제에서의 구조를 많이 차용 하였습니다.
- 이번주 학습하다가 테스트 메서드의 이름을 무지막지하게 길게 빼면서 given_when_then식으로 작성하는 테스트 코드를 발견해서 따라해 보았습니다.

---
다음 PR TODO
- 메뉴의 입력 받기 및 메뉴 별 로직 추가
- repository findAll 메서드 구현
- 로깅 추가/entity의 toString추가 - logback

2022-04-07 23:45 UTC, woogiekim requested changes
전체적으로 좋은거같습니다만, 
한가지 아쉬운점이 있습니다.

도메인 > 서비스 > 컨트롤러

이런 순서대로 작업하고 PR을 주면 더 좋을거같습니다

도메인, 서비스, 컨트롤러는 어떤 범위를 이야기 하는것인지는 토요일에 담소 나눠보겠습니다

2022-04-07 23:45 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/order/entity/OrderStatus.java
> +    CANCELLED
상태들이 어떤걸 의미하는지에 대한 주석도 남겨주세요

2022-04-07 23:45 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/order/service/OrderService.java
> +        return createOrder(customerId, orderItems, null);
null을 이렇게 노출해서 쓰는게 어떤 단점이 있을지 생각해보시면 좋을거같습니다

2022-04-07 23:45 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/order/service/OrderService.java
> +        Order order = new Order(customerId, orderItems, voucher);
바우처가 있는 경우 없는 경우 둘은 확실히 차이가 있는 상황이라는 생각이 드는데, 정적 팩토리 메소드를 이용해서 어떤 객체 생성인지 명시해주는건 어떨까요?

2022-04-07 23:45 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/voucher/entity/FixedAmountDiscountVoucher.java
> +        if (beforeDiscountPrice - amount < 0) {
일관성있게 checkArgument 로 바꾸는건 어떨까 싶네요 해당 로직정도는 메소드를 빼지 않아도 충분히 잘 설명이 된다는 생각이듭니다

2022-04-07 23:45 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/voucher/entity/PercentDiscountVoucher.java
> +        return beforeDiscount * (100 - percent) / 100;
정액 할인 바우처에서는

beforeDiscountPrice 라는 이름으로 명명하고 있습니다.

하나의 표현으로 통일시키는게 좋겠습니다

2022-04-07 23:45 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/voucher/repository/MemoryVoucherRepository.java
> +public class MemoryVoucherRepository implements VoucherRepository {
Repository <- MemoryRepository <- MemoryVoucherRepsitory

이런 관계를 가지게 구상해보는건 어떨까요?

2022-04-07 23:45 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/voucher/service/VoucherService.java
> +                .orElseThrow(() -> new RuntimeException(MessageFormat.format("Can not find a voucher for {0}", voucherId)));
IllegalArgumentException 이 더 명확해 보이는데 RuntimeException 으로 한 이유가 있는건가요?

구아바 라이브러리에서 사용하는 유효성검사는 IllegalArgumentException로 throw하고 있는데 갑자기 쌩뚱 맞는 느낌이네요

2022-04-07 23:45 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +            Voucher mockVoucher = mock(Voucher.class);
바우처를 모킹한 이유는 무엇인가요?

2022-04-07 23:45 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +            Order order = new Order(customerId, orderItems, voucher);
주문 아이템이 없어도 주문이 생성되나요?

2022-04-07 23:45 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +class OrderTest {
주문 생성할때 체크하던 유효성에 대한 테스트가 없습니다

2022-04-07 23:45 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/voucher/entity/FixedAmountDiscountVoucherTest.java
> +class FixedAmountDiscountVoucherTest {
성공케이스 > 실패 케이스

이런 순서로 시간 흐름에 맞게 테스트 케이스를 나열해주는 것이 중요합니다

2022-04-08 00:00 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/order/service/OrderService.java
> +        return createOrder(customerId, orderItems, null);
넵!

2022-04-08 00:05 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/voucher/entity/FixedAmountDiscountVoucher.java
> +        if (beforeDiscountPrice - amount < 0) {
넵! 잠시 해당 메서드를 생성자에서만 사용하는 것으로 착각했었습니다.

2022-04-08 00:09 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/voucher/repository/MemoryVoucherRepository.java
> +public class MemoryVoucherRepository implements VoucherRepository {
오.. 한번 구상해 보겠습니다.

2022-04-08 00:11 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/voucher/service/VoucherService.java
> +                .orElseThrow(() -> new RuntimeException(MessageFormat.format("Can not find a voucher for {0}", voucherId)));
해리쌤이 강의때 쓱싹쓱싹 작성하신 코드를 주의깊게 살펴보지 않았습니다 ㅜ.ㅜ

2022-04-08 00:20 UTC, ndy2 commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +            Voucher mockVoucher = mock(Voucher.class);
Voucher의 구현에 관계없이 주문엔티티가 생성된다는 의도로 저런식으로 표현하였습니다.
사실 작성하면서도 해당 경우는 특정 호출에 대해 기대하는 값을 pre-programming하는 mock과는 성격이 다르다고는 생각했었는데 그냥 저런식으로 작성했었습니다 ㅜ.ㅜ

이 경우 어떤방식으로 테스트를 작성하는것이 좋을까요?

2022-04-08 00:21 UTC, ndy2 commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +            Order order = new Order(customerId, orderItems, voucher);
헉! orderItems의 empty검증이 필요하겠네요.

2022-04-08 00:23 UTC, ndy2 commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +class OrderTest {
실패 케이스를 @Nested constructorTest 클래스의 마지막에 추가하겠습니다.

2022-04-08 03:55 UTC, ndy2 commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +            Order order = new Order(customerId, orderItems, voucher);
같은 생성자에서 여러 상황에 대해 IllegalArgumentException을 던지면 예외 메세지까지 검증하는 것이 좋나요?

2022-04-11 05:03 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/order/entity/OrderTest.java
> +            Voucher mockVoucher = mock(Voucher.class);
1. 주문 아이템에게 있어서 바우쳐는 필수인가요? 그것부터 생각해봐야할거같습니다.
2. Fixed와 Percent 바우쳐를 적용시킨 주문 아이템에 대한 테스트 필요하지 않을까요?
3. 1번과 2번 모두 부합하는 상태가 된다면 굳이 모킹해서 주문아이템 생성테스트를 해야할 이유가 없어보입니다.

2022-04-13 11:15 UTC, woogiekim approved these changes
다음 진행을 위해서 일단, 어프로브하겠습니다.

코멘트 확인해주세요.

테스트에서 검증해야할부분들을 많이 놓치고 있는거같습니다.

어떤걸 검증해야하는 건지 고민해보면 좋을거같습니다.

2022-04-13 11:15 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/entity/PercentDiscountVoucher.java
>          checkArgument(percent >= 0 && percent <= 100, "amount must be between 0 and 100 inclusive.");
0, 100

이런 매직넘버를 상수화 해놓는게 더 좋지 않을까요?

2022-04-13 11:15 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepositoryTest.java
> +        return orderItems;
List.of 를 써보는건 어떨까요?

2022-04-13 11:15 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepositoryTest.java
> +        }
두개 테스트로 나누어져 있어야할 이유가 없어보입니다.

2022-04-13 11:15 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepositoryTest.java
> +            ));
Matcher 사용 연습때문에 이렇게 하시는거죠?

사용연습 끝나면, `containsExactly` 로 검사해주는게 더 좋을거같아요

2022-04-13 11:15 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/order/entity/OrderTest.java
> +            assertThat(order).isNotNull();
도메인 객체를 만드는 부분인데,
제대로 세팅되고 있는지 확인해봐야하지않을까요?

2022-04-13 11:15 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/order/entity/OrderTest.java
> +            assertThat(order).isNotNull();
fixed로 잘 들어갔는지 체크 해봐야하지 않을까요?

2022-04-13 11:15 UTC, merged

2022-04-13 11:34 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepository.java
> +            throw new NoIdFieldException("there is no field name [id]", ex);
같은  Member 인스턴스를 두번 insert 하는 경우를 방지하고 싶었습니다.
또한 인스턴스에 아이디가 생성되는 시점을 최초 insert 한 경우로 한정하고 싶었습니다.

NoSuchFieldException  : 개발자가 구현 자체를 잘못 한 경우 (제네릭 Id 타입의 필드 이름 id를 가진 필드가 없는 경우)
checkstate : 삽입을 마쳐 이미 insert가 된 인스턴스를 다시 insert 하는 경우

로 구분하고자 하였습니다.

2022-04-13 11:37 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/order/entity/OrderStatus.java
> +    SETTLED,            //주문 안정 상태
간략히 주문 절차가 취소 없이 마무리 된 경우라고만 코멘트 하였습니다.

위의 주석에 process에 해당하는 설명을 링크 같은 것을 통해 만들 예정이라고 써놓을까 하다가 too much 같아서 뺏습니다...

2022-04-13 11:37 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/order/entity/Order.java
> +    }
넵... 다시 고민해보겠습니다.

2022-04-13 11:41 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepository.java
> +            throw new NoIdFieldException("there is no field name [id]", ex);
쓰고 있는 자료구조가 맵인데 필요한 작업일까 라는 생각이 듭니다.

NoSuchFieldException 이거는 이해가 됩니다.

put 할때 검사해주는 방법도 있을거같습니다

리플렉션으로 강제로 접근제어를 풀어버리고 하는 행동이 필요할까라는 생각이 듭니다.

2022-04-13 11:42 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/order/entity/OrderStatus.java
> +    SETTLED,            //주문 안정 상태
승인이 되고 언제 안정상태로 들어가는거죠?

2022-04-13 11:42 UTC, ndy2 commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepositoryTest.java
> +        }
저는 insert했을때 id가 생성되는 특성을 따로 검증할 필요가 있다고 생각해서 테스트를 구분하였었습니다. 
다시생각해보니 내용이 꽤 겹쳐서 함께 검증하는 것도 좋아보이네요.

2022-04-13 11:45 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepositoryTest.java
> +        }
그것은 아마도 id 설정에 대한 부분에 대한 로직을 많이 작성하셨기 때문에 따로 확인해보고 싶으셨을거같네요...

그렇지만, 굳이 저래야 할 이유는 없어보입니다. 아이디만 확인해보고 싶으셨다면, 아이디 만드는 컴포넌트가 있었다면, 해당 컴포넌트에서 확인하는 작업을 해주는 거였다. 이런거면 괜찮아보입니다.

2022-04-13 12:00 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/order/entity/OrderStatus.java
> +    SETTLED,            //주문 안정 상태
사실 이앱이 뭐하는 앱인지 전혀 생각해 보지 않았습니다...
그래서 각 Enum의 state가 무엇을 의미해야하는지 전혀 고민해보지 않았습니다.

지금 로직 내에서는 주문의 생성단계에서 승인 상태로 생성되고 이 외의 로직에는 주문 상태를 전혀 활용하지 않았습니다. 이부분도 부끄럽지만 강의 코드를 그대로 옮기다 보니 큰 고민없이 활용하다가 생기는 문제점 인거 같습니다.

개발단계는 실질적으로 활용 하고 명세가 정확한 상태코드만을 남겨 혼동을 피하도록 하겠습니다.

2022-04-13 12:12 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepository.java
> +            throw new NoIdFieldException("there is no field name [id]", ex);
SpringData JPA를 활용하여 insert 문을 날릴때 memberRepository.save(member) 이런식으로만 사용하여도 db에 의해 id가 생성되는 경우 member 인스턴스에 id필드가 set 되는 것으로 아는데 그 기능을 흉내내고 싶었습니다. ㅜ.ㅜ