[2기-C]방은혁 SpringBoot Part1 Weekly Mission 코드 리뷰 요청합니다!
prgrms-be-devcourse/springboot-basic pull request #170
Opened 2022-04-08 13:24 UTC by hyuk0309

## 📌 과제 설명

[1주차 미션](https://www.notion.so/backend-devcourse/Part1-3-38f57acca0dd490db11393701417943a)
<br/>
바우처 관리 애플리케이션 만들었습니다. 심화 요구사항 중 YAML 프로퍼티 제외하고 다 구현했습니다. 

<br/>

## 👩‍💻 요구 사항과 구현 내용 

제가 구현하기 위해 나눈 구현 목록입니다. 

- UI
  - [x] Text-IO 이용해 UI 구현하기
    - [x] 메뉴 출력 기능 개발
    - [x] 바우처 생성 커맨드 개발
    - [x] 바우처 조회 커맨드 개발
    - [x] 블랙 리스트 조회 커맨드 개발
- 핵심 로직
  - [x] Voucher 엔티티 만들기
    - [x] FixedAmountVoucher
    - [x] PercentDiscountVoucher
  - [x] MemoryVoucherRepository 만들기
    - [x] Voucher 저장
    - [x] Voucher 전체 조회
  - [x] MemoryVoucherService 만들기
    - [x] Voucher 생성 & 저장
    - [x] Voucher 조회
  - [x] VoucherController 만들기
  - [x] FileVoucherRepository 만들기
    - [x] Voucher 저장
    - [x] Voucher 전체 조회

<br/>

구현 목록 외 설정 관련 수행 내용입니다. 

- [x] 스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
- [x] 적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x] 실행가능한 `jar` 파일을 생성한다.
- [x] 고객 블랙 리스트 명단을 작성한다.
- [x] 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.

<br/>

## ✅ PR 포인트 & 궁금한 점 

FileVoucherRepository에서 파일 입출력 작업을 수행해 예외처리가 필요한 부분이 많았습니다. 이를 깔끔하게 작성하려고 노력했지만 현재 상황에서 어떤 방향으로 개선할지 잘 모르겠습니다. 조언 부탁드립니다!

2022-04-10 06:42 UTC, ksy90101 requested changes
안녕하세요 :) 은혁님
1단게 미션 잘 구현해주셨네요 💯 
간단한 피드백을 남겼으니, 확인해주시면 감사하겠습니다~

2022-04-10 06:42 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +            ;
```suggestion
        while (process());
```

2022-04-10 06:42 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +        }
이렇게 되면, if이 계속 추가 되면서 메서드가 굉장히 커질거 같은데, 전략패턴을 사용할 수 없을까요?

2022-04-10 06:42 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +        logger.info("VoucherController.process() called");
```suggestion
    private boolean process() {
        logger.info("VoucherController.process() called");
```
        이러한 개행하나하나가 가독성을 다르게 만들수 있습니다 :)

2022-04-10 06:42 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/Voucher.java
> +public interface Voucher extends Serializable {
Serializable을 사용한 이유가 무엇일까요?

2022-04-10 06:42 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +    public List<Voucher> findAll() {
1Depth로 줄여보실래요?

2022-04-10 06:42 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +    public void save(Voucher voucher) {
여기도 1pth으로 줄여보시면 좋을거 같습니다.

2022-04-10 06:42 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/view/ConstantString.java
> +public class ConstantString {
이렇게 관리하는게 좋은걸까요?
enum으로 관리하는것과 중복이 되어버린거 같은데, 한번 enum으로 가능한 것들은 enum으로 해보면 어떨까요?

2022-04-10 06:42 UTC, ksy90101 commented on src/test/java/org/prgrms/springbootbasic/repository/FileVoucherRepositoryTest.java
> +        assertAll(
👍

2022-04-10 13:37 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +        }
menu 전략패턴으로 수정했습니다. 
따라서 메뉴가 추가되는 요구사항이 들어와도 if 문을 추가 하는게 아니라, controller 메서드와 Menu의 전략을 추가하면 확장 가능합니다! 

좀 더 보완할 부분이 있을까요?

2022-04-10 14:02 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/Voucher.java
> +public interface Voucher extends Serializable {
Voucher를 구현하는 FixedAmountVoucher, PercentDiscountVoucher를 FileVoucherRepository에서 파일에 저장합니다. 이때 직렬화가 필요해 사용했습니다!

2022-04-10 14:49 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/view/ConstantString.java
> +public class ConstantString {
헉.. 이 부분은 생각하지도 않고 있었어요.. 피드백 감사합니다!

2022-04-10 15:00 UTC, hyuk0309 commented
안녕하세요:)

피드백 수정 완료했습니다. 
아직 부족한 부분 있으면 조언 부탁드립니다! 😃

감사합니다!!

2022-04-16 12:20 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/Voucher.java
> +public interface Voucher extends Serializable {
도메인 자체를 Serializable을 하는게 맞을까요?
차후 이 도메인은 재활용이 힘들것네요.

2022-04-16 12:28 UTC, ksy90101 requested changes
간단한 피드백을 좀 더 남겼으니, 확인해주시면 감사하겠습니다 :)

2022-04-16 12:28 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +        while (process()) {
동작하는 값은 있고, 내부에서 로직이 진행되어야 할거 같은데요.

2022-04-16 12:28 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
과연 interface가 지금상황에서 맞을까요?
상속이 더 어울릴지 한번 고민해보세요.

2022-04-16 12:28 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +        }
https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/ 

이글을 한번 읽어보세요 :)

2022-04-16 12:28 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +        }
```suggestion
        }  catch (EOFException | IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
```

이렇게 사용이 블가할까요?
아래도 동일합니다.

2022-04-16 12:28 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +            readPercentAmountVoucher(vouchers, percentVoucherFileStream);
fixed와 percentVocher는 다른 테이블로 관리해야 하는것일까요?

2022-04-16 12:28 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/MemoryVoucherRepository.java
> +        return new ArrayList<>(storage.values());
굳이 재할당 하는 이유가 무엇일까요?

2022-04-16 12:28 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/service/VoucherService.java
> +    }
createVocher를 했을때, 딱 create가 되어야 하지 않을까 합니다.

2022-04-16 12:28 UTC, ksy90101 commented on src/main/resources/logback.xml
> +      <level>ERROR</level>
과연 File에 Error 레벨 이상만 저장하는게 좋을까요?

2022-04-16 12:28 UTC, ksy90101 commented on src/test/java/org/prgrms/springbootbasic/entity/FixedAmountVoucherTest.java
> +        assertThat(voucher.getAmount()).isEqualTo(amount);
assertAll()이라는 친구가 있는데 한번 알아보면 좋을거 같아요 :)

2022-04-16 12:28 UTC, ksy90101 commented on src/test/java/org/prgrms/springbootbasic/entity/FixedAmountVoucherTest.java
> +    void test() {
테슽 메서드명도 의미있게 지어주세요.

2022-04-16 12:28 UTC, ksy90101 commented on src/test/java/org/prgrms/springbootbasic/entity/PercentDiscountVoucherTest.java
> +    void test() {
여기도 의미잇는 테스트이름을 사용해주세요.

2022-04-16 12:28 UTC, ksy90101 commented on src/test/java/org/prgrms/springbootbasic/repository/FileVoucherRepositoryTest.java
> +    }
한군데에서만 하는게 좋지 않을까요?

2022-04-17 14:33 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +        while (process()) {
이 부분은 조금 더 자세한 설명이 가능할까요? 잘 이해가 안됩니다!

2022-04-17 14:34 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
제가 깊게 고민하지 않았네요. 확실히 상속이 어울리는 것 같습니다! 
수정하겠습니다.

2022-04-17 15:31 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/Voucher.java
> +public interface Voucher extends Serializable {
이 부분은 깊게 생각하지 않았네요. 지금 생각해보니 도메인에 Serializable을 사용하면 도메인이 하나의 레포지토리에 의존하게 되는 것 같아요. 이 부분은 DTO를 활용해 도메인과 File 레포지토리의 결합도를 낮출 수 있을 것 같습니다. 

수정하겠습니다!

2022-04-17 15:34 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +        }
EOFException과 나머지 Exception을 다르게 처리하고 싶어서 분리했습니다. 
EOFException은 파일을 끝까지 읽어서 나오는 예외이기 때문에 이 경우 정상적으로 동작하게하고, 나머지 예외는 문제가 있는 경우이기 때문에 예외를 출력하게 구현했습니다.

어떻게 보면 제가 EOFException에 로깅을 남겨 두면 다른 분이 코드를 볼때 오해하지 않았을 것 같네요. 이 부분에 로깅을 남겨 제 의도를 명확하게 하겠습니다!

2022-04-17 15:36 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +            readPercentAmountVoucher(vouchers, percentVoucherFileStream);
> Serializable을 사용한 이유가 무엇일까요?

이 리뷰에 해답을 찾으려고 엔티티를 저장하는게 아니라, DTO로 변환해 저장했습니다. 그러면서 자연스럽게 해결되었습니다!

2022-04-17 15:44 UTC, hyuk0309 commented on src/main/resources/logback.xml
> +      <level>ERROR</level>
수업에서 Error 레벨만 파일에 저장했습니다. 그래서 이 부분에 대해 고민하지 않고 그대로 사용했던 것 같아요. 

고민해 보니 Error 레벨만 파일에 저장하면 장애 발생 시 어느 부분에 문제가 발생했는지 파악하기 어려울 것 같아요. DEBUG 레벨까지는 파일에 저장하는 게 좋을 것 같다는 생각이 드네요. 
DEBUG 레벨로 수정하겠습니다!

2022-04-17 15:54 UTC, hyuk0309 commented on src/test/java/org/prgrms/springbootbasic/entity/FixedAmountVoucherTest.java
> +        assertThat(voucher.getAmount()).isEqualTo(amount);
저는 assertj와 JUnit5의 assertAll()을 같이 사용하면 안 될 거라고 생각했었어요.  같이 사용하면 좋겠군요!

2022-04-17 16:08 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/repository/MemoryVoucherRepository.java
> +        return new ArrayList<>(storage.values());
values() API 반환 값에 대한 이해가 부족해서 굳이 재할당을 했던 것 같습니다.. ㅎㅎ
수정하겠습니다!

2022-04-17 16:22 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/repository/MemoryVoucherRepository.java
> +        return new ArrayList<>(storage.values());
반환된 값과 맵과 관계를 끊어주기 위해 재할당 했습니다.

2022-04-18 07:25 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
> +        }
좋은 글이네요! 
instanceof 대신에 다형성을 이용하니 훨씬 객체지향적인 코드가 만들어 지는 것 같아요. 😁

2022-04-18 07:31 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/service/VoucherService.java
> +    }
하나의 메서드로 합친 후 if문을 통해 FixedAmountVoucher과 PercentDiscountVoucher을 생성해 Repository에 넘겨 줬습니다. 

Voucher 생성을 if문 분기를 사용하지 않고 하고 싶어, 전략 패턴을 도입할 수 있을까 생각했습니다. 그런데 FixedAmountVoucher을 생성하는데 필요한 매개변수와 PercentDiscountVoucher를 생성하는데 필요한 매개변수가 달라 이를 전략 패턴으로 만드는 건 힘들겠다는 생각이 들었습니다. 혹시 더 좋은 방법이 없을까요?

2022-04-19 10:02 UTC, ksy90101 commented on src/main/resources/logback.xml
> +      <level>ERROR</level>
네 :)

2022-04-19 10:02 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/service/VoucherService.java
> +    }
이건 팀미팅때 질문해주세요!

2022-04-19 10:03 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +        while (process()) {
이것도 팀 미팅때 질문주세요~

2022-04-19 10:04 UTC, ksy90101 commented
이만 머지할게요~ 2주차때 봐요~

2022-04-19 10:04 UTC, merged