[2P-박혜빈] SpringBoot Part1 Weekly Mission 코드리뷰 요청합니다.
prgrms-be-devcourse/springboot-basic pull request #171
Opened 2022-04-08 18:16 UTC by HYEBPARK

## 📌 과제 설명 
(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

   ```bash
   === Voucher Program ===
   Type **exit** to exit the program.
   Type **create** to create a new voucher.
   Type **list** to list all vouchers.
   ```

    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 

![](https://imagedelivery.net/v7-TZByhOiJbNM9RaUdzSA/ed1b2afb-691e-4e17-82ee-9652d703bd00/public)

![](https://imagedelivery.net/v7-TZByhOiJbNM9RaUdzSA/4a0fbd20-ec82-4d30-d6c7-f3184534d500/public)

#### - CommandLineApplication.java
- 프로그램을 run 합니다.
- 사용자의 명령어 입력을 받아 유효성 검사후 해당 명령어 기능을 호출합니다.
#유효성 : 프로그램에서 실행가능한 명령어
   - create : voucher 생성
   - list : voucher 리스트 출력
   - list -b : blacklist 출력 
   - exit : 프로그램 종료
### 📂 voucher
#### 📄 model
- **Voucher (Interface)**
- **FixedAmountVoucher, PercentDiscountVoucher** : Voucher 구현체입니다.
   - 필드 => voucherId, voucherType, value
- **VoucherType (Enum)**
   - voucher 종류 Enum 클래스입니다. 
#### 📄 repository
- **VoucherRepository(Interface)**
   - **insert(UUID voucherId, Voucher voucher)** : repository에 insert 합니다.
   - **getSize()** : repository에 저장된 고객의 수를 return 합니다. repository가 비어있을 경우 에러 메시지를 출력 하기위해서 구현했습니다. 
   - **showAll()** : repository를 출력합니다. 
- **MemoryRepository**
   - Map<UUID, Voucher>  관리합니다.
- **FileRepository**
   - fileDB.csv 파일로 데이터를 관리합니다.
- **FileBuffer**
   - **getBufferedReader(File file)** : 매번 새로운 BufferReader를 반환합니다. 
   - **getBufferWriter(File file)** : 매번 동일한 BufferWriter를 반환합니다.
####  📄 service
   - **VoucherCreateService**
      - **create()** : 사용자의 입력에 맞는 voucher 종류 생성 함수를 호출합니다. 
      - **fixedAmountVoucherCreate()** : 금액을 입력 받아 입력 값의 유효성을 체크하고 FixedAmountVoucher를 생성한 후 repository에 insert 합니다. 
      #유효성 : 입력 값은 숫자이고 0보다 커야 합니다.
      - **percentDiscountVoucherCreate()** : 할인율을 입력받아 입력값의 유효성을 체크하고 PercentDiscountVoucher를 생성한 후 repository에 insert 합니다. 
      #유효성 : 입력 값은 숫자이고 0보다 크고 100보다 작아야 합니다.
      - **isStrNum(String str)** : string이 숫자인지 체크하고 boolean값을 return 합니다. 
### 📂 io
#### - Input 
   - **Input (Interface)**
   - **InputConsole** : Input 구현체입니다.
      - **getUserInput()** : user의 입력을 받습니다.
   - **InputErrorType (Enum)** : 사용자 입력의 에러 타입입니다.
#### - Output
   - **Output(Interface)**
   - **OutputConsole** : Output 구현체입니다.
      - **startMessage()** : 프로그램 실행시 명령어 안내 메세지 출력
      - **inputErrorMessage()** : InputErrorType에 따라 에러 메시지 출력
      - **voucherSelectMessage()** : voucher create시 voucher type 안내 메세지 출력
    - **voucherDiscountMessage()** : VoucherType에 따라 금액or할인율 입력 안내 메시지 출력 
#### 📄 customer : 다음 과제에 필요하다 생각하여 만들었습니다.
- **customer** : customer 모델입니다.
   - 필드 => customerId, customerName, customerType 
- **CustomerType (Enum)** : 고객의 등급? 타입? 입니다.
- **CustomerRepository (Interface)**
- **BlackListRepository** 
   - BlackList 를 customer_blacklist.csv 파일로 관리합니다.
   - 과제 요구사항은 '생성되어있는 파일을 읽기'만 있었는데 다음 과제에서 사용할 수 있을 것 같아서 다른 함수도 구현하였습니다.
   - **insert(UUID customerId, Customer customer)** : 파일에 insert 합니다.
   - **getSize()** : 파일에 저장된 고객의 수를 return 합니다. 파일이 비어있을 경우를 체크하기 위해서 구현했습니다. 
   - **showAll()** : 파일을 읽어서 출력합니다. 

## ✅ PR 포인트 & 궁금한 점 
- 프로젝트가 중간에 꼬여버려 commit을 다시 해서 충분하지 않습니다 ㅠㅠ 이점 양해부탁드립니다 😥 
- (1) 파일로 관리하는 repository의 경우 BufferWriter와 BufferReader를 사용하는게 맞는지, 더 좋은 방법이 있는 건지 궁금합니다. (2) 그리고 BufferWriter의 경우 기존의 입력을 해주기 위해서는 동일한 Writer를 사용해야 한다고 생각했습니다. 그래서 클래스를 따로 만들었는데, 이 방식이 맞는지 궁금합니다.

2022-04-09 16:26 UTC, Jo-GyuHyeon requested changes
gitignore 파일이 있지만 불필요한 파일들이 많이 포함되어 있는 것 같습니다.
다음 커밋에는 불필요한 파일을 제거 해주세요.



```
(1) 파일로 관리하는 repository의 경우 BufferWriter와 BufferReader를 사용하는게 맞는지, 더 좋은 방법이 있는 건지 궁금합니다. 
```
보통 Buffer(reader, writer) 와 비교 대상은 File (reader, writer) 관련 클래스들입니다.
두 클래스간 동작, 성능적인 차이가 존재하지만, 제 생각에는 지금 시점에서는 크게 상관 없다고 생각합니다.


```
(2) 그리고 BufferWriter의 경우 기존의 입력을 해주기 위해서는 동일한 Writer를 사용해야 한다고 생각했습니다. 그래서 클래스를 따로 만들었는데, 이 방식이 맞는지 궁금합니다.
```
제 생각에는 불필요한 클래스라고 생각합니다.

2022-04-09 16:26 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherCreateService.java
> +        }
created 에서는 voucherType 을 파라미터로 받는 것이 좋다고 생각합니다.
voucherType 은 created 이전에서 판변하는 것이 좋다고 생각합니다.

그 이외의 로컬 메서드를 사용하기위해 this 를 작성해주세요.

2022-04-09 16:26 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherCreateService.java
> +        if (isStrNum(inputDiscount)) {
if 구분 전에 개행을 넣어주세요. 
네이밍은 항상 Full Naming 을 고려해주세요.

2022-04-09 16:26 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherCreateService.java
> +    private void fixedAmountVoucherCreate() {
create 관련 메서드는 return 타입을 기대하는 것이 일반적이라 생각합니다. 
혹시 void 로 return 하신 이유가 있을까요?

2022-04-09 16:26 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherCreateService.java
> +            voucherRepository.insert(voucherId, new FixedAmountVoucher(voucherId, Integer.parseInt(inputDiscount)));
Integer.pase 가 의도치 않게 동작 할 수 있다고 생각합니다.
예외가 발생할 수 있는 부분은 상위로 올려서 빨리 노출 시키는 것이 좋다고 생각합니다.

2022-04-09 16:26 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherCreateService.java
> +        if (isStrNum(inputDiscount) && Long.parseLong(inputDiscount) <= 100) {
조건식을 조금더 가독성을 좋게 하기 위해 변수로 미리 빼서 작성하는 것을 고려해주세요.

2022-04-09 16:26 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherCreateService.java
> +        return true;
인덱스를 직접 접근하기 보다 향상된 for 문을 사용해보세요.

2022-04-20 14:48 UTC, pjh612 reviewed
많은 코멘트를 달지는 않았는데 시간이 뚝딱갔네요. 더 자세하게 했다가는 시간이 사라질까봐 깊게는 리뷰 못드렸습니다.

제가 깊이 고민해봤던 문제에 대해서도 언급했습니다. 혜빈님 뿐만아니라 다른 팀원들 모두 같이 고민해보면 좋을것 같아요~😃

2022-04-20 14:48 UTC, pjh612 commented on src/main/java/org/programmers/kdt/weekly/voucher/model/FixedAmountVoucher.java
> +    public VoucherType getVoucherType() {
객체 지향의 특성 중 "캡슐화"라는 특성이 있습니다. 이는 간단히 말해서 객체의 속성과 행위를 그룹화하는 것인데요. 캡슐화와 항상 세트로 딸려오는 것이 있는데 "정보 은닉" 이라는 것입니다. 캡슐화를 통해서 정보 은닉을 이룰 수 있는 것입니다.

그런데 왜 사람들은 캡슐화, 정보은닉을 하고자 한다고 말을 하면서도 정보 은닉이라는 것은 말 그대로 정보를 은닉을 하는것인데 private로 잘 숨겨놓고 왜 getter를 통해서 값 그대로를 노출하며 망쳐버릴까요?

저희는 주입식 교육을 받았다고 생각합니다 그저 "private 접근지정자 설정 getter 사용" = 캡슐화
하지만 진정한 정보 은닉, 캡슐화를 이루기 위해서는 내부의 구현을 알 수 없도록 만들어야 하는것이 아닐까요?

클린코드 6장의 첫부분에서는 이러한 내용을 다루고 있습니다. 나중에 시간나실때 제가 무슨 말을 했는지 이해하시는데 도움이 될 것이라고 생각합니다.

다시 말해서 voucherType이 필드에 들어가 있는것 자체는 문제가 안된다고 생각합니다. 하지만 getVoucherType 함수는 객체가 어떤 구현체로 만들어져 있는지 객체의 구현을 노출한다고 볼 수 있을 것 같습니다. 지금 이 getter는 voucherFileRepository의 insert함수에서 사용하고 있군요 그렇다면 이 함수를 사용하지 않고 원래의 로직을 정상적으로 수행하려면 어떻게 해야할까요?

제가 고민을 해봤었던 문제를 공유 해드렸습니다. getter를 남용하고 있기도 하구요, 제 생각은 이런데 혜빈님과 다른 팀원분들은 어떻게 생각하는지도 궁금하네요.

2022-04-20 15:03 UTC, whyWhale commented on src/main/java/org/programmers/kdt/weekly/customer/repository/BlackListRepository.java
> +                String[] arr = line.split(",");
- array 말고 List 추천합니당!

2022-04-20 15:07 UTC, whyWhale commented on src/main/java/org/programmers/kdt/weekly/customer/repository/BlackListRepository.java
> +        String line;
지역변수라 null이 들어갈 것 같은데 상수형 default를 미리 넣어두는 것이 좋을 것 같습니 🥕 !!

2022-04-20 15:47 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/model/FixedAmountVoucher.java
> +    public VoucherType getVoucherType() {
진형님이 말씀하신 것처럼 기계 마냥 private를 붙이고 getter가 필요하면 만들었어요 😓
생각지도 못했던 부분을 저도 생각해볼 수 있는 기회가 생겼네요 ㅎㅎ
말씀해주신 부분 저도 충분히 생각해보고 대화를 나눠보는 시간을 가지면 좋을 것 같아요 !
다른 리뷰도 잘 생각해보고 반영하겠습니다 !!  
진형님, 병연님 시간 내어 코드 리뷰 해주셔서 감사합니다 😊👍

2022-04-23 07:44 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/CommandLineApplication.java
> +                    if (vouchers.size() > 0) {
이정도는 벨리데이션 메서드를 만드는 것이 좋을까요? 불필요한 메서드가 되지 않을까 싶기도 합니다.

2022-04-23 07:49 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/repository/VoucherFileRepository.java
> +                String[] lineSplitComma = line.split(",");
@pjh612  그것도 좋은 명인것 같습니다. 
가끔 생각해보면 명명에서 어떤 구현체 방법이 노출외어야 하나? 라는 생각이 들때도 있습니다. `**UsingStack`,  `**ByArrrayList` 오히려 구현과 자료 구조보다 어떠한 데이터들인지 나타는것이 더 좋을 수 있습니다.
그래서 (어떠한 기준으로) split 한 데이터들이 무엇인지? 를 나태내는 것이 명확할 수 있다고 봅니다.

2022-04-28 16:34 UTC, closed without merging