[2기-C] 이한주 SpringBoot Part1 Weekly Mission 코드리뷰 요청합니다.
prgrms-be-devcourse/springboot-basic pull request #178
Opened 2022-04-09 19:23 UTC by yanJuicy

## 📌 과제 설명 
바우처 관리 애플리케이션
Command-line Application 형식으로 바우처 관리 프로그램 만들기

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
    - [x]  스프링부트 애플리케이션으로 만든다. 
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type exit to exit the program.
    Type create to create a new voucher.
    Type list to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 메모리에 관리한다.
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
- 콘솔 IO 기능 추가
  - 콘솔을 이용한 Input, Output 기능
 
- 고정 할인 기능 Voucher 생성
  - FixedAmountVoucher 생성 및 discount 메소드 구현 (할인 방법)

- 퍼센트 할인 기능 Voucher 생성
  - PercentAmountVoucher 생성 및 discount 메소드 구현 (할인 방법)

- 메모리에 저장하는 VoucherRepository 생성
  - VoucherRepository 인터페이스와 구현체 MemoryVoucherRepository 생성
  - MemoryVoucherRepository 구현체는 List를 통해 메모리에 Voucher 인스턴스를 저장

- 만들어진 바우처를 조회하는 기능
  - VoucherService를 이용해 VoucherRepository의 getVouchers 메소드 호출
  - CommandLineApplication에서 VoucherRepository가 아닌 VoucherService를 이용해 Voucher 조회

- 만들어진 바우처를 저장하는 기능
  - VoucherService를 이용해 VoucherRepository의 save 메소드 호출
  - CommandLineApplication에서 VoucherRepository가 아닌 VoucherService를 이용해 Voucher 저장

- 컴포넌트 스캔 기능 추가
  - Config 파일에서 @ComponentScan 어노테이션을 이용한 bean 추적

- CommandLineApplication 프로그램 실행 기능 추가
  - 메인 로직이 실행되는 부분

- logback 설정을 해서 에러 파일 기록
  - CommandLineApplicaion 클래스에 logging 기능을 통해 명령어 입력이 잘못 되었을 경우에 대한 로그 기록
  - 잘못된 메뉴 입력에 대한 로그 기록
  - 잘못된 Voucher 타입에 대한 로그 기록

- SpringBoot 애플리케이션 설정
  - 프로젝트를 만들 때 생성된 SpringBootApplicaion 클래스를 이용해 CommandLineApplicaion 클래스 호출

- CommandLineApplication Start, Terminate 로깅 추가
  - CommandLineApplicaion이 시작될 때 프로그램 시작 로깅
  - CommandLineApplicaion이 종료될 때 프로그램 종료 로깅

## ✅ PR 포인트 & 궁금한 점 
다 만들지 못했지만 일단 PR 보내봅니다... ㅠㅠ

1. CommandLineApplicaion에서 입력을 분기하기 위해 enum을 사용했는데 enum의 사용을 적절하게 한 건지 궁금합니다. (VoucherStatus, CommandStatus)

2022-04-11 14:00 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandStatus.java
> +        }
switch문이 아니라, 각 필드를 가지고 있고 stream으로 findFisrt하면 가능하겠네요 :)

2022-04-11 14:00 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/io/Console.java
> +        System.out.println(s);
s보다 더 의미있는 단어를 사용해주세요.

2022-04-11 14:01 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/PercentAmountVoucher.java
> +        return (long) (beforeDiscount - beforeDiscount * ((double) percent / 100));
100은 매직넘버 :)
아울러 지금처럼 계산이 복잡하면 각각 의미하는 단어를 알기가 어려워져요.
변수로 뺴서 한번 의미있게 작성해볼까요?

2022-04-11 14:02 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/FileVoucherRepository.java
> +@Profile("default") // default Profile
주석은 필요 없어보이네요 :)

2022-04-15 08:59 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +        new CommandLineApplication().run();
컨트롤러 클래스를 만들어서 CommandLineApplication을 실행하라는 말씀이신가요??

2022-04-16 12:18 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +        new CommandLineApplication().run();
네 맞아요.

2022-04-17 06:31 UTC, yanJuicy commented
피드백 반영했습니다!

2022-04-17 07:25 UTC, ksy90101 requested changes
테스트 코드가 아예 없네요 :)
테스트 코드 추가해보세요~

2022-04-17 07:25 UTC, ksy90101 commented on HELP.md
> +# Read Me First
여기 아직 피드백 반영 안하셨습니다 :)

2022-04-17 07:25 UTC, ksy90101 commented on .gitignore
> +.idea/**/workspace.xml
여기도 코드리뷰 반영이 안되었네요.
위에 .idea가 잇는데 이제 여기 전체 다 필요 없어보여요.

2022-04-17 07:25 UTC, ksy90101 commented on .gitignore
> +HELP.md
삭제가 안되었어요. 어떻게 삭제할 수 잇을까요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +                        break;
전략패턴으로 변경해보시겟어요? enum을 이용하면 더 쉬울거 같아요.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +                console.output("\n");
개행은 "/n"이것보단 System.lineSparetor를 사용하는게 더 좋을거 같습니다 :)

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +            String cmd = inputCommand(console);
축약어 보단 command라고 명시해주시는게 더 좋을거 같습니다.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +            }
여기도 enum을 이용해봐요~

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +        }
output에 output을 부르는게 아니라 출력 및 입력에 대한 책임은 각 Input과 Output 객체에 위임해보세요.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +    private void createVoucher(ConsoleInput input, ConsoleOutput output, VoucherService voucherService) {
ConsoleInput을 인자로 받는게 아니라 필드로 가지고 잇으면 되지 않을까요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandStatus.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 메뉴 명령어"));
어떤값이 들어왔는데 잘못된 메뉴 명령어인지 작성해두면 디버깅은 더 쉽습니다.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandStatus.java
> +                .filter(e -> e.name().equals(menuCommand.toUpperCase()))
e라는 단어는 a1이랑 다를바 없어 보이네요.
더 의미잇는 변수명으로 작성해주세요.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/SpringBootBasicApplication.java
> +		}
이게 여기있ㄴㄴ게 맞을까요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/SpringBootBasicApplication.java
> +		controller.runCommandLineApp();
main은 단순히 run하는 메서드만 있는게 더 좋을거 같습니다.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/io/Console.java
> +    Scanner scanner = new Scanner(System.in);
private으로 해도 무관할거 같으며, 불변을 유지하는게 어떠신가요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/io/Console.java
> +public class Console implements ConsoleInput, ConsoleOutput {
Input과 Output은 분리해주세요.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/io/Console.java
> +        System.out.println(s);
s보다 더 의미잇는 변수명을 사용해주세요.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/VoucherType.java
> +                .filter(e -> e.name().equals(voucherTypeString.toUpperCase()))
e보다 더 의미있는 변수명을 사용해주세요.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/VoucherType.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 바우처 타입 입력"));
어떤 바우처 타입이 들어왔길래 에러가 발생하는지 작성해주시면 디버깅 할때 더 편할거 같습니다.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/FixedAmountVoucher.java
> +    private final UUID voucherId;
ID가 더 위에 잇는게 좋을거 같네요.

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/PercentAmountVoucher.java
> +        double discountRange = percent / 100;
100은 매직넘버 :)

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/PercentAmountVoucher.java
> +    private final UUID voucherId;
id가 더 위에 잇는게 좋을거 같네요. 아울러 Vocher를 상속으로 만들었는데 어차피 voucherId는 다 공통 필드 아닌가요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/PercentAmountVoucher.java
> +    private final UUID voucherId;
아 이렇게 되면 중복인데요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/FileVoucherRepository.java
> +    private static final Map<UUID, Voucher> vouchers = new HashMap<>();
HashMap보단 동시성에 안전한 Map을 찾아서 구현체로 사용해보시겠어요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/FileVoucherRepository.java
> +            } catch (IOException e) {}
try~catche~resoruce를 사용해보시면 어떨까요?

2022-04-17 07:25 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/MemoryVoucherRepository.java
> +    private static final List<Voucher> voucherList = new ArrayList<>();
과연 Inmemeory DB는 List가 어울릴까요?
Map으로 하는게 더 좋지 않을까요?

2022-04-17 09:11 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +            }
VoucherType이 Enum 클래스인데 switch 문을 없애라는 의미인가요?

2022-04-17 09:12 UTC, yanJuicy commented on .gitignore
> +HELP.md
.gitignore에 넣었는데 적용이 안됐나보네요...

2022-04-17 09:44 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +            }
아니면 이 상태를 service에서 관리하게 해도 좋을거 같네요 :)
이런 이 로직은 Application 보단 서비스가 더 맞는거 같네요 :)

2022-04-17 15:21 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/PercentAmountVoucher.java
> +        double discountRange = percent / 100;
10%, 50% 같은 얼마나 할인을 해주는 것을 구하기 위해 percent / 100을 한건데 100도 변수로 만들어야 하나요? 
아니면 "discount = percent / 100" 이 의미 전달이 잘 안된걸까요?

2022-04-17 19:02 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/SpringBootBasicApplication.java
> +		}
Controller 클래스 내부로 옮겼습니다. main 클래스에서 컨트롤러를 통해 호출하도록 했습니다.

2022-04-17 19:51 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/PercentAmountVoucher.java
> +    private final UUID voucherId;
중복되는 부분은 상위 클래스를 이용하도록 바꿨습니다.

2022-04-17 19:56 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/FileVoucherRepository.java
> +    private static final Map<UUID, Voucher> vouchers = new HashMap<>();
ConcurrentHashMap을 사용했습니다.

2022-04-18 02:11 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/FileVoucherRepository.java
> +            } catch (IOException e) {}
try resource를 강의에서 들었는데 적용할 생각을 안해봤네요.. 적용했습니다!

2022-04-18 02:13 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +                        break;
전략 패턴 적용해보았습니다.

2022-04-18 09:05 UTC, yanJuicy commented
피드백 반영했습니다. 확인 부탁드립니다!

2022-04-19 10:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/model/PercentAmountVoucher.java
> +        double discountRange = percent / 100;
100이 뭘 의미하는지 맨처음에 보시는 분은 이해를 못해요.
아울러 이렇게 하면 100이라는게 계속 메모리에 생성되구요.

2022-04-19 10:10 UTC, ksy90101 commented
이만 머지할게요~ 고생 많으셨어요 :) 2주차떄 봐요!

2022-04-19 10:10 UTC, merged