[2기-C] 강태산 SpringBoot Part1 Weekly Mission 코드리뷰 요청합니다.
prgrms-be-devcourse/springboot-basic pull request #179
Opened 2022-04-09 22:15 UTC by Pawer0223

##  바우처 관리 Command-line Application을 만들어본다.
- 참고: [https://dzone.com/articles/interactive-용console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
- 스프링부트 애플리케이션으로 만든다.
    - Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.

## 요구사항 및 구현내용
- [x] Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.

``` bash
spring init --build maven -j 14 -g com.mountain -a voucherApp -n voucherApp -x voucherApp
```
    
- [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
- [x]  create / list 커맨드를 지원한다.
    - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
    - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
    - 바우처 정보를 메모리에 관리한다.
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
    - 일 별 error로그파일 기록 `logs/error_yyyyMMdd.log`
    - `create, exit, list` 명령어가 아닌 경우 error 로그
    - create에서 amount를 숫자가 아닌 수를 입력한 경우 error 로그 
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 지정 된 디렉터리의 파일을 읽어서 로드하고 조회.
    - 파일에서 읽은 데이터는 모두 FixedVoucher로 생성. (보완 필요)

- [x]  고객 블랙 리스트 명단을 작성한다.
    - `blackList/customer_blacklist.csv` 파일을 읽기 위한 기능 추가

- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.
    - 파일 Repository에서 Dir및 File명을 프로퍼티 설정을 참조하여 처리
    - properties 참조에 따른 테스트코드는 미구현

## 실행 방법
``` bash
git clone https://github.com/Pawer0223/springboot-basic.git;
cd springboot-basic/voucherApp;
mvn package;
java -jar -Dspring.profiles.active=dev target/voucherApp-0.0.1-SNAPSHOT.jar
```

## PR 포인트 & 궁금한 점

1. Create 기능 개선

* 요구 사항의 create 명령에 대해 선택 가능한 바우처의 타입을 선택 후 생성하는 기능으로 이해했습니다.
* 바우처의 종류가 늘어날 수록 코드의 변경사항을 최소화 하고 싶어 타입에 맞는 인스턴스를 Enum에서 Function을 통해 생성하도록 구현해보았는데요 ! 이 경우.. Enum에서 Voucher가 생성되고 있어서 Repository를 File로 관리하는 경우 타입에 맞는 바우처 인스턴스를 생성하기 위해 하드코딩을 피할 수 없었습니다..
* 이런 문제를 효과적으로 해결할 수 있는 전략이 있는지.. 아니면 이러한 변경사항이 불가피한 것인지 판단이 어렵습니다.. 좋은 방안이 있는지 궁금합니다

2. 어플리케이션의 시작

* 콘솔 프로그램의 시작점을 어떠한 구조로 잡으면 좋을까요? 현재는 ExecuteEngine클래스를 만든 후, Bean을 직접 가져와 수행하고 있습니다 !

3. 코드에서 눈에 띄는 안좋은 습관이나, 개선 점에 대해 가감없이 조언주시면 달게받고 개선하겠습니다.

2022-04-10 07:08 UTC, ksy90101 requested changes
안녕하세요 :) 태산님
미션 하시느라 너무 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니 확인해주세요.
참고로 테스트 코드쪽이 아직 정리가 잘 안된거 같아요. 이쪽도 전체적으로 다시 한번 봐주세요~

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +    private final File BLACK_LIST_FILE = new FileSystemResource(FILE_PATH).getFile();
상수로 해도 충분하지 않을까요?

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +            rowScanner.useDelimiter(",");
"," 매직스트링!

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +        List<List<String>> records = new ArrayList<>();
List의 List가 최선이였을까요?

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +            System.out.println("create new file");
log로 관리해보시면 어떨까요?

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/ExecuteEngine.java
> +                console.printWrongInput(command);
전략패턴을 사용해보시면 어떨까요?

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    Function<Long, Voucher> function;
접근제어자를 붙여주시고, final이여야 할거 같네요 :)

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/properties/FileRepositoryProperties.java
> +@ConfigurationProperties(prefix = "file-repository")
getter / setter가 없어도 가능한걸로 알고 있는데요.
한번 불변으로 해서 깔끔하게 만들어 보실까요?

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/FileVoucherRepository.java
> +    // TODO 다양한 바우처의 인스턴스를 생성해야 함
Todo는 구현되었다면 삭제하시는게 좋을거 같습니다 :)

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/MemoryVoucherRepository.java
> +   private final Map<UUID, Voucher> storage = new ConcurrentHashMap<>();
static을 붙이면 어떨까요?

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/main/resources/application.yml
> +  file-name: "list.txt"
```suggestion
  file-name: "list.txt"
  
```

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/test/java/com/mountain/voucherApp/VoucherAppApplicationTests.java
> +//	}
주석할 정도면, 그냥 파일을 삭제하는것도 방법이겠네요!

2022-04-10 07:08 UTC, ksy90101 commented on voucherApp/src/test/java/com/mountain/voucherApp/blacklist/BlackListServiceTest.java
> +    }
asster가 없는데, 이게 과연 테스트 일까요?

2022-04-12 13:43 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +    private final File BLACK_LIST_FILE = new FileSystemResource(FILE_PATH).getFile();
현재 두 문자열 모두 final로 선언하여 상수로 사용하고 있다고 생각했습니다.. ! 제가 상수선언에 대해 이해가 부족한걸까요? 피드백에서 어떠한 점을 개선해야할지 파악이 잘 되지를 않습니다..

2022-04-12 13:47 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +        List<List<String>> records = new ArrayList<>();
List<List<String>> -> List<BlackListFileFormat> 으로 opencsv 라이브러리를 활용해 개선했습니다 !
확실히 클래스 타입을 정의해서 하니 명시적인것 같다는 느낌이드네요..

2022-04-12 13:48 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/ExecuteEngine.java
> +                console.printWrongInput(command);
피드백 주신대로 create, exit, list를 전략패턴으로 개선해보았습니다.. 제가 전략 패턴을 잘 적용한걸까요 ??

2022-04-12 13:48 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    Function<Long, Voucher> function;
이부분도 놓쳤네요 ! private final로 선언했습니다 !

2022-04-12 14:04 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/properties/FileRepositoryProperties.java
> +@ConfigurationProperties(prefix = "file-repository")
setter를 무분별하게 사용했던 것 같네요.. 불변으로 관리되도록 개선 했습니다 !

2022-04-12 14:07 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/MemoryVoucherRepository.java
> +   private final Map<UUID, Voucher> storage = new ConcurrentHashMap<>();
static으로 변경해 주니 전체 테스트를 할 때, size를 확인하는 테스트에서 갯수가 불일치하는 상황이 발생했습니다. 실제로 static으로 구현한 Repository가 있다면 모든 테스트를 수행하기 전에 clear를 처리하도록 고려해야 할까요? 더 효율적인 방법이 있을까요.. ?

2022-04-16 13:21 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +    private final File BLACK_LIST_FILE = new FileSystemResource(FILE_PATH).getFile();
이렇게 되면 변경 가능서잉 있지 않나요?
static final을 이야기 한거였어요.

2022-04-16 13:22 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/MemoryVoucherRepository.java
> +   private final Map<UUID, Voucher> storage = new ConcurrentHashMap<>();
네 테스트 격리를 위해 clear는 기본일거 같아요.

2022-04-16 13:39 UTC, ksy90101 requested changes
간단한 피드백을 좀 더 남겼습니다~
확인해주세요~

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/pom.xml
> +		<java.version>14</java.version>
자바 버전을 11 또는 17을 이용해주세요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +        List<BlackListFileFormat> list = new CsvToBeanBuilder(new FileReader(FILE_PATH))
list라는 단어는 너무 추상적인데요.
더 의미잇는 단어를 사용해주세요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/ExecuteEngine.java
> +    private final Logger log = LoggerFactory.getLogger(ExecuteEngine.class);
static final이 좋을거 같네요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/ExecuteEngine.java
> +                console.printWrongInput();
제가 말하는 방식은 enum을 이용하는 방식을 이야기 한거에요.
그렇게 전략패턴을 구현하라는 의미입니다.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/create/DefaultCreate.java
> +    private final Console console;
과연 이 친구가 Console을 가지고 잇는게 맞을까요?

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/list/DefaultList.java
> +    public void list() {
list는 명사 아닌가요?

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    PERCENT(2, "비율 할인", (amount) -> new PercentDiscountVoucher(amount));
비욜인 경우에는 persent가 더 인자가 맞을거 같은데요?

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    private final int ordinal;
oridinal이 필요한 이유가 있나요?
차후 순서가 변경되면 문제가 되어서요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/io/Console.java
> +public class Console implements Input, Output {
Input과 Output이 같이 잇는게 좋은걸까요?

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/io/Console.java
> +    private final String SELECT_COLOR = "white";
상수 :)

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/FileVoucherRepository.java
> +    private List<Voucher> list = null;
null을 왜 쓰신거죠?

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/FileVoucherRepository.java
> +    private List<Voucher> list = null;
더 의미있는 필드명으로 하시면 어떨까요?
vouchers가 있을거 같네요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/FileVoucherRepository.java
> +                    .append('\n');
System.lineSparate를 한번 알아보시겠어요?

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/utils/DiscountPolicyUtil.java
> +    private static Map<Integer ,DiscountPolicy> map = null;
null로 초기화 하지 마시고, 아울러 final을 이용해서 불변을 유지해주시고, 처음에는 빈 자료구조를 가지고 잇는게 좋을거 같네요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/utils/MenuUtil.java
> +    private static Map<String ,Menu> map = null;
여기도요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/utils/MenuUtil.java
> +
util은 인스턴스 생성을 막는게 더 좋을거 같아요.
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/4_%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%ED%99%94%EB%A5%BC_%EB%A7%89%EC%9C%BC%EB%A0%A4%EA%B1%B0%EB%93%A0_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EA%B9%80%EA%B4%91%ED%9B%88.md

이 글 한번 참고해보세요~

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/FixedAmountVoucher.java
> +    private static final long MAX_VOUCHER_AMOUNT = 10000;
상수를 더 위로 올려주세요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/FixedAmountVoucher.java
> +        if (amount <= 0)
0도 매직넘버 :)

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/PercentDiscountVoucher.java
> +            throw new IllegalArgumentException("Amount should be less than " + MAX_VOUCHER_AMOUNT);
예외메시지를 굳이 영어로 써야 할까요?

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/PercentDiscountVoucher.java
> +            throw new IllegalArgumentException("Amount should be less than " + MAX_VOUCHER_AMOUNT);
validate를 메서드로 분리하면 좋을거 같네요.

2022-04-16 13:39 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/PercentDiscountVoucher.java
> +        double discountAmount = Math.round(percent * 0.01 * beforeDiscount);
0.01은 매직넘버네요 :)

2022-04-16 13:53 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +    private final File BLACK_LIST_FILE = new FileSystemResource(FILE_PATH).getFile();
아 지금 용도로는 static을 붙이는게 더 메모리 효율적인것 같네요.. ! 이부분에 이해가 부족했던것 같습니다.
그런데 현재코드에 final이 존재하는데 static이 존재하지 않는 이유로 변경 가능성이 있을까요 ?
final 키워드로 컴파일타임 또는 인스턴스 생성시에 반드시 초기화 된 후 변경될 수 없다고 이해하고 있는데..

짚어주신 "변경 가능성"이 언제발생할 수 있을까요..?

2022-04-16 13:55 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/blacklist/BlackListService.java
> +    private final File BLACK_LIST_FILE = new FileSystemResource(FILE_PATH).getFile();
아 변경가능성을 이야기 한건 잘못이야기 했네요. 죄송합니다.
변경 가능성은 없지만, static 화를 하지 않으면 인스턴스 생성 마다 저게 생성될 수 있다는이야기를 하고 싶던거에요.

2022-04-16 19:55 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    PERCENT(2, "비율 할인", (amount) -> new PercentDiscountVoucher(amount));
인자를 받지 않는 Voucher를 각 상수별로 생성할 수 있도록 변경해보았습니다 !

2022-04-16 19:57 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    private final int ordinal;
할인 정책이라는 데이터를 별도로 관리하고 싶었는데요. ordinal을 일종의 id와 같은 pk용도로 사용하고 싶었습니다.
새로운 테이블을 만들까 고민하다 우선은 변수 명만 policyId로 변경해보았습니다 !

2022-04-16 20:02 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/FileVoucherRepository.java
> +    private List<Voucher> list = null;
- FileRepsotiroy의 경우 list 명령어가 수행될 때마다 계속 파일을 읽는 로직을 줄이고 싶어서 List를 두었는데요.
- 최초 파일이 없을 경우를 고려해서 초기 값을 null 구분하려했습니다 ! 빈 List를 만들어 놓고 size로 구분하려는 생각을 못했네요..

2022-04-16 20:09 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/repository/FileVoucherRepository.java
> +                    .append('\n');
여러 환경에 대처할 수 있는 방법을 전혀 고민하지 못했네요.. lineSeparator 기억하겠습니다 !
- [참조](https://codechacha.com/ko/java-line-separator/)

2022-04-16 20:19 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/utils/MenuUtil.java
> +
감사히 잘 읽었습니다. 피드백 반영했습니다 !

2022-04-16 20:36 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/io/Console.java
> +public class Console implements Input, Output {
입,출력 부분에 대해서는 크게 고민하지 못했던것 같습니다.. 생각해보니 java.io에서도 Reader와 Writer를 구분해서 활용되는것 같네요..
그래도 Console이라는 객체에서는 입, 출력을 모두 관리해도 괜찮다고 생각도드는데요, 분리하는게 더 괜찮을까요 ??

2022-04-16 20:43 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/PercentDiscountVoucher.java
> +            throw new IllegalArgumentException("Amount should be less than " + MAX_VOUCHER_AMOUNT);
한글은 인코딩 문제가 생길 수 있다고 생각해서.. 방어적인자세로 최대한 영어로 작성하려 애쓴것 같습니다.. 실무에서도 예외메시지를 한글로 처리하는 경우가 많을까요 ??

2022-04-17 05:20 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/io/Console.java
> +public class Console implements Input, Output {
제 의견은 Input과 Output은 서로 다른 책임을 가지고 잇다고 생각이 듭니다.
입력 -> 로직 실행 -> 출력이라고 생각이 드는데요.
그렇게 되면 다른 역할을 하는것이라고 봐야하지 않을까 합니다.
이렇게 된다면 차후 입력과 출력이 너무 결합도를 쎄게 가지고 있을수도 잇구요.

2022-04-17 05:21 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    private final int ordinal;
할인 정책이라는 데이터를 별도로 관리한다는게 테이블을 관리한느것일까요?
순서를 데이터로 저장한다는것인거 같은데, 순서를 저장하면 어떤 단점이 있을까요?
순서가 변경되면 데이터를 모두 마이그레이션을 해야 할거 같은데요.
그래서 JPA에서도 oridnal보단 string으로 저장하는것을 더 권장하고 있어요.

2022-04-17 05:22 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/PercentDiscountVoucher.java
> +            throw new IllegalArgumentException("Amount should be less than " + MAX_VOUCHER_AMOUNT);
문자열은데 왜 인코딩 문제가 발생하죠?
저희는 외국계를 가지 않는 이상 한국인과 협업하고, 한국 서비스를 하게 될 확률이 높을텐데, 그런 경우 한글의 인코딩이 문제면 서비스 자체가 장애가 발생하지 않을까요?

2022-04-17 14:45 UTC, Pawer0223 commented on voucherApp/pom.xml
> +		<java.version>14</java.version>
11버전으로 변경했습니다 !

2022-04-17 14:46 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/ExecuteEngine.java
> +                console.printWrongInput();
Enum활용으로 변경해보았습니다.. 다시한번 피드백부탁드립니다 !

2022-04-17 14:49 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/create/DefaultCreate.java
> +    private final Console console;
현재 create에서는 기능이 수행되기 위해 필요한 입력을 2개 받고있는데요 (할인정책과, 할인금액)
create에서 항상 2개의 입력을 받지 않을수도 있다고 생각해서 console까지 함께 주입받고, create안에서 사용하도록 해보았습니다 !

2022-04-17 14:53 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/enums/DiscountPolicy.java
> +    private final int ordinal;
넵 추후에 테이블로 관리되는 것을 고려하였습니다 ! 순서의 의미보다 auto generate되는 sequence와 같은 용도로 활용하려는 목적이었습니다.
최초에 변수명을 잘못준 것 같습니다 ..

2022-04-17 15:02 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/PercentDiscountVoucher.java
> +            throw new IllegalArgumentException("Amount should be less than " + MAX_VOUCHER_AMOUNT);
원인을 잘 모르고 문제가 생길 수 있다고 걱정해서 영어로했던것 같아요.
영어 표현이 어려운 경우 한글을 사용하는 습관을 가지고, 인코딩 문제를 직면하는 경우 원인을 좀 더 깊이있게 찾아보겠습니다 !

2022-04-17 15:39 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/io/Console.java
> +public class Console implements Input, Output {
Console에 함께있어야 할 이유를 생각해보았는데.. 말씀주신것처럼 책임을 나누는게 훨씬 좋을것 같습니다 !

2022-04-19 10:16 UTC, ksy90101 commented
이만 마무리 하겠습니다 :) 2주차때 봐요~

2022-04-19 10:16 UTC, merged