[2C-박현지] SpringBoot Part1 Weekly Mission 코드리뷰 요청드립니다.
prgrms-be-devcourse/springboot-basic pull request #182
Opened 2022-04-10 06:29 UTC by rioreo22

## 📌 과제 설명 

- SpringBoot Part1 Weekly Mission
    
    (기본) **바우처 관리 애플리케이션**
    
    - [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
    - [x]  바우처 관리 Command-line Application을 만들어본다.
        - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
        - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
        - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
        
        ```bash
        === Voucher Program ===
        Type **exit** to exit the program.
        Type **create** to create a new voucher.
        Type **list** to list all vouchers.
        ```
        
        - [x]  create / list 커맨드를 지원한다.
            - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
            - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
            - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
    - [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
    - [x]  실행가능한 `jar` 파일을 생성한다.
    
    (심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능
    
    - [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
        - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
    - [ ]  고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
    - [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 

## Console
+ InputStream과 PrintStream을 주입받도록 작성했습니다.
+ @Predestroy로 종료 전, Stream을 닫도록 작성했습니다.

## shell
+ CommandLineRunner를 구현하여 애플리케이션 실행시 자동으로 실행되도록 작성했습니다.

## voucher
+ VoucherFactory로 voucher생성하도록 작성했습니다.
+ FileVoucherRepository는 아직 구현하지 않았습니다.

## ✅ 피드백 반영사항  

TODO:
1. SpringbootShell 알아보고 적용해보기
2. Test코드 작성
3. 생성자 내부에서 validate 할 것.
5. 추가 기능 구현 할 것

2022-04-10 07:42 UTC, woogiekim requested changes
제공하는 다양한 종류의 바우쳐에 대한 테스트가 없습니다. 테스트를 추가해주세요!

2022-04-10 07:42 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/configuration/AppConfiguration.java
> +    }
IO Stream일 빈으로 등록해서 사용하면 안됩니다.
그 이유에 대해서 조사해보세요

조사한 후 팀방에 공유 하면 좋을거같습니다

2022-04-10 07:42 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/console/Console.java
> +        }
예외가 발생하면 해당 예외를 무시하고 다음 동작을 하게 될거같은데 어떻게 보시나요?

IOException을 복구할수있을까요?

2022-04-10 07:42 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/shell/CommandLineApplication.java
> +            }
어디는 괄호를 생략하고 어디는 생략하지 않고 하는 기준이 드러나지 않는 코드인거같습니다.

통일성을 지켜주세요

2022-04-10 07:42 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/shell/Command.java
> +    INVALID_COMMAND,
잘못된 커맨드를 정의해놓고 있을 필요성이 있을까요?

2022-04-13 12:16 UTC, woogiekim approved these changes
다음 진행을 위한 어프로브하겠습니다.

코멘트 확인해주시고 다음 작업전에 적용해주세요

2022-04-13 12:16 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/voucher/domain/VoucherType.java
> +    public static Optional<VoucherType> findVoucherType(String type) {
옵셔널로 리턴해야할 이유가 혹시 있나요?

2022-04-13 12:16 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/voucher/repository/MemoryVoucherRepository.java
> +        return voucher;
공백으로 문맥 전환을 표현할수있습니다.

적극적으로 이용해보세요.

2022-04-13 12:16 UTC, woogiekim commented on src/test/java/org/prgrms/vouchermanager/voucher/domain/FixedAmountVoucherTest.java
> +
필요없는 공백은 지워주세요

2022-04-13 12:16 UTC, woogiekim commented on src/test/java/org/prgrms/vouchermanager/voucher/domain/FixedAmountVoucherTest.java
> +    @DisplayName("유효한 할인 금액으로만 생성할 수 있다.")
유효하지 않은 케이스들을 나눠주세요

2022-04-13 12:17 UTC, merged

2022-04-14 06:07 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/voucher/domain/VoucherType.java
> +    public static Optional<VoucherType> findVoucherType(String type) {
Enum에서 static 메소드를 제공하면서 null 처리를 해주고 싶었는데, 생각해보니 꼭 옵셔널로 리턴할 필요는 없는 것 같습니다. 
대신 Enum의 valueOf를 활용하는 방법으로 수정하였습니다! 감사합니다!