[2기-C] 황승한 SpringBoot Part1 Weekly Mission 코드리뷰 요청합니다.
prgrms-be-devcourse/springboot-basic pull request #190
Opened 2022-04-10 15:07 UTC by jk05018

📌 과제 설명
CLI 바우처 관리 애플리케이션 구현 과제
과제 링크 :  [스프링부트 Part1~3 위클리 미션](https://www.notion.so/backend-devcourse/Part1-3-38f57acca0dd490db11393701417943a)

👩‍💻 요구 사항과 구현 내용
요구 사항은 exit, create, list 명령을 지원하는 바우처 애플리케이션의 구현입니다. 

현재 도메인을 구성해본 뒤 VO(Voucher), Repository(MemoryRepository)에 대한 테스트코드와 구현을 작성한 상태입니다.

클래스 다이어그램

![스크린샷 2022-04-10 오후 11 33 47](https://user-images.githubusercontent.com/68465557/162625516-246d67dd-1865-4765-baff-54385b78c6e8.png)

구현시 고려한 사항
* 최대한 테스트 ->  구현의 구조로 개발을 진행해 보려 노력했습니다.
* 테스트를 생각하면서 작성하느라 아직 진도를 많이 빼지 못했습니다! 열심히 해서 다시 PR 보내드리겠습니다!

다음 PR TODO
* Service에서 Create/ list 메서드 테스트 및 구현
* Logback을 이용하여 log 기록 추가 - 에러는 파일로 기록
* Spring Shell을 이용한 CLI(Controller) 추가

2022-04-11 01:47 UTC, jk05018 commented
👩‍💻 요구 사항과 구현 내용 요구 사항은 exit, create, list 명령을 지원하는 바우처 애플리케이션의 구현입니다. 
2번째 PR입니다!
현재 Service의 create/list기능 까지 Test -> 구현 방식으로 해 보았습니다.

다음 PR TODO
* Logback을 이용하여 log 기록 추가 - 에러는 파일로 기록
* Spring Shell을 이용한 CLI(Controller) 추가

감사합니다!

2022-04-11 12:50 UTC, woogiekim requested changes
코멘트 확인해보시고 궁금한점은 DM주세요!

2022-04-11 12:50 UTC, woogiekim commented on .idea/checkstyle-idea.xml
> +<?xml version="1.0" encoding="UTF-8"?>
설정파일이 형상관리에 들어오면 안됩니다 빼주세요

2022-04-11 12:50 UTC, woogiekim commented on pom.xml
> +	</dependency>
사소 할 수도 있지만 이런 정렬 일관성있게 유지해주세요

2022-04-11 12:50 UTC, woogiekim commented on springboot-basic.iml
> +<?xml version="1.0" encoding="UTF-8"?>
이런 설정이 들어오면 클납니다! ㅠㅡㅠ

2022-04-11 12:50 UTC, woogiekim commented on src/main/java/org/prgms/springbootbasic/voucher/io/Console.java
> +		return null;
이건 무엇인가요?

2022-04-11 12:50 UTC, woogiekim commented on src/main/java/org/prgms/springbootbasic/voucher/repository/FileVoucherRepository.java
> +	}
왜 구현을 안한건가요?

2022-04-11 12:50 UTC, woogiekim commented on src/main/java/org/prgms/springbootbasic/voucher/service/VoucherService.java
> +public class VoucherService {
왜 빈이 아닌건가요?

2022-04-11 12:50 UTC, woogiekim commented on src/main/java/org/prgms/springbootbasic/voucher/service/VoucherService.java
> +		output.print(builder.toString());
서비스에서 해야할일인지 다시한번 생각해보면 좋을거같습니다

2022-04-11 12:50 UTC, woogiekim commented on src/main/java/org/prgms/springbootbasic/voucher/service/VoucherService.java
> +			}
왜 트라이캐치하는지 모르겠습니다

2022-04-11 12:50 UTC, woogiekim commented on src/test/java/org/prgms/springbootbasic/voucher/repository/MemoryVoucherRepositoryTest.java
> +		assertEquals(percentVoucher.getVoucherId(), percentStored.getVoucherId());
저장한 걸 토대로 다시 조회해서 검증해주세요

2022-04-11 12:50 UTC, woogiekim commented on src/test/java/org/prgms/springbootbasic/voucher/service/VoucherServiceTest.java
> +		assertEquals(2,voucherRepository.getVoucherListByType().get(PercentDiscountVoucher.class.getSimpleName()).size());
assertJ를 이용해주세요

2022-04-11 12:50 UTC, woogiekim commented on src/test/java/org/prgms/springbootbasic/voucher/service/VoucherTypeTest.java
> +		assertThrows(IllegalArgumentException.class, () -> percentVoucherType.createVoucher(200));
각 케이스별로 메소드가 그냥 있으면 더 간결하고 유지보수하기 좋지 않을까요?

2022-04-11 12:50 UTC, woogiekim commented on src/test/java/org/prgms/springbootbasic/voucher/vo/FixedAmountVoucherTest.java
> +		assertThrows(IllegalArgumentException.class, () -> new FixedAmountVoucher(-1L));
성공과 실패 왜 같이 있나요?

2022-04-11 14:43 UTC, jk05018 commented on src/test/java/org/prgms/springbootbasic/voucher/service/VoucherServiceTest.java
> +		assertEquals(2,voucherRepository.getVoucherListByType().get(PercentDiscountVoucher.class.getSimpleName()).size());
assertJ에 대해서 학습해 보겠습니다!

2022-04-11 14:44 UTC, jk05018 commented on src/test/java/org/prgms/springbootbasic/voucher/service/VoucherTypeTest.java
> +		assertThrows(IllegalArgumentException.class, () -> percentVoucherType.createVoucher(200));
넵 성공 케이스, 실패 케이스 이렇게 구분하지 않고 케이스별로 구분하도록 하겠습니다!

2022-04-11 14:47 UTC, jk05018 commented on src/main/java/org/prgms/springbootbasic/voucher/service/VoucherService.java
> +			}
내부에서 발생한 exception을 언젠가는 한번 처리해야겠지!? 하며 Service에서 처리하려는 의도였던 것 같습니다.
슬랙에 올려주신 내용을 토대로 공부하겠습니다!

2022-04-14 01:11 UTC, jk05018 commented
👩‍💻 요구 사항과 구현 내용 안녕하세요 우기님! 3번째 PR 입니다!
아직 FileVoucherRepository를 구현하지 않았습니다.
MemoryVoucherRepository를 통해 정상적으로 동작하는 지 확인했고
다음 PR때 File까지 구현하겠습니다!

이번에 변경된 내용은
1. .gitignore 파일을 설정해([gitignore.io](http://gitignore.io/) 사이트 이용) 설정 파일들을 원격 레포지토리에서 제거했으며
2. 테스트 코드를 조언해 주셨던대로 케이스 별로 나누어보려고 했으며
3. 언급해 주셨던 Spring Shell에 대해 공부하고 조금이지만 적용해 보았습니다.
4. Logback.xml 파일을 설정해 Error 부분을 파일로 쏘도록 했습니다. 
여쭈어보고 싶은 것이 있었는데 아직 생각정리와 공부가 제대로 된 것 같지 않아서 고민한 뒤 DM으로 여쭈어 보겠습니다!

다음 PR TODO
- FileVoucherRepository 구현

실행 사진
<img width="1297" alt="스크린샷 2022-04-14 오전 9 47 16" src="https://user-images.githubusercontent.com/68465557/163294456-97cb7f41-ac3a-4dee-8824-14cc50b261ed.png">
감사합니다!

2022-04-17 06:36 UTC, merged