[2기 - C] 박상혁 Spring Boot Part1 Weekly mission 코드 리뷰 부탁드립니다
prgrms-be-devcourse/springboot-basic pull request #194
Opened 2022-04-10 18:58 UTC by park0503

## 📌 과제 설명 
Spring Boot Part1 Weekly mission 바우처 관리 프로그램 구현하기를 진행했습니다.
## 👩‍💻 요구 사항과 구현 내용 
일단 심화 요구 사항을 제외한 기본 요구사항만을 우선적으로 구현했습니다.
### (기본) 바우처 관리 애플리케이션
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

### (심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.
## ✅ PR 포인트 & 궁금한 점 
- main method에 로직이 직접 실리는게 거부감이 들어서 VocherManager Class를 이용해 처리했는데 괜찮은 구조일까요?
- Enum 클래스인 VoucherType 클래스를 클래스 다이어그램에 그리려 하다가 VoucherType enum 클래스에 직접 접근하는 클래스가 너무 많은 것을 발견했는데, Enum 타입의 경우도 이렇게 너무 많은 클래스들과 연관이 되버리면 안좋은 점이 있을까요?

2022-04-10 20:50 UTC, park0503 commented
파일로 저장하는 레포지토리를 구현했습니다.
궁금한 점이 File 객체의 method 중 list 나 listFiles같은 method들은 해당 경로에 파일이 없는 경우 null을 출력하더라구요.
2주차 수업때 null은 nullPointerException을 대비해 안쓰는 것이 좋다고 배웠는데 그렇다면 해당 method로부터 나오는 결과를 Optional로 한번 더 싸주는 것이 맞는 것일까요?

force-push 한 점 죄송합니다 중간에 커밋 내용이 꼬여버려가지고 ㅜㅜ 앞으로 조심하겠습니다.

2022-04-11 04:47 UTC, VictoryPark requested changes
상혁님! 
빠른 과제 제출 고생하셨습니다 ㅎㅎ
더 자세한 사항은 코멘트 달아드렸습니다.

1. VoucherManager 클래스로 따로 분리하신것도 좋습니다.
2. Enum 클래스에 직접 접근한다는 것이 무슨 의미인지를 말씀하시는지 정확하게 알 수 없으나, 
Enum은 상수를 관리하고 표현할 수 있는 것을 더 직관적으로 클래스로 구현한 것입니다. 그래서 상수가 쓰이는 모든 곳에 쓰일 수 있는 것이죠.
Enum 클래스는 어디에 속하는 것이 아니라, 상수 자체로 존재하는 것이죠. 이번 과제는 Enum 클래스에 대해서 더 공부하는 시간이 될 수 있을 겁니다.

2022-04-11 04:47 UTC, VictoryPark commented on src/main/java/org/prgrms/part1/engine/FileVoucherRepository.java
> +                    if (type.equals("FixedAmount")) {
이 부분의 코드는 VoucherType에 type 추가가 일어날때마다 else if 문이 추가되는 코드이죠.
이것은 OCP 원칙에 어긋나는 코드 스타일이기도 합니다.
스트링을 코드내에 하드 코딩하는 것도 추천하지 않습니다.
Enum 클래스를 이용하여 구현할 수 있도록 수정해보세요!

2022-04-11 04:47 UTC, VictoryPark commented on src/main/java/org/prgrms/part1/engine/VoucherManager.java
> +                output.printError("Voucher File is Broken. Please Call Developer");
예외 메세지가 이곳에서 정의되고 있는데,
메세지가 어디에 정의되고 관리되는 것이 더 나을지 고민해볼까요?😋

2022-04-11 04:47 UTC, VictoryPark commented on src/main/java/org/prgrms/part1/engine/FixedAmountVoucher.java
> +    }
메소드 명은 getDiscount 인데, 던지는 변수명은 amount 네요?
통일이 필요할 것 같습니다.

2022-04-11 04:47 UTC, VictoryPark commented on src/main/java/org/prgrms/part1/engine/FileVoucherRepository.java
> +    private final List<UUID> vouchers = new ArrayList<>();
List<UUID> 타입의 변수명이 vouchers 인 것도 더 생각해보셔야 할 것 같고,
중요한건, 이 변수는 선언되어있지만 클래스 내에서 쓰임이 없네요???🙄

2022-04-11 04:47 UTC, VictoryPark commented on src/main/java/org/prgrms/part1/engine/VoucherManager.java
> +                        break;
중첩 while 문은 가독성을 떨어뜨립니다.
더군다나 true 라는 조건으로 중첩 반복문이 도는건 더욱 좋지 않죠.
바깥 while 문에서 case 조건에 따라 역할을 달리 주는 클래스를 만들어서 구현해보세요
역할과 책임을 분리하는 연습을 할 수 있을 겁니다!!

안쪽 while 문은 이미 만들어놓으신 VoucherType Enum을 더 잘 사용할 수 있도록 구현 가능할 것 같네요🤗

2022-04-11 04:47 UTC, VictoryPark commented on src/main/java/org/prgrms/part1/engine/VoucherManager.java
> +                        break;
질문 주신 Optional 처리가 된다면,
이 코드가 매우 짧아질 수 있고
더 가독성을 높일 수 있게 됩니다^0^

2022-04-11 19:34 UTC, park0503 commented on src/main/java/org/prgrms/part1/engine/FileVoucherRepository.java
> +    private final List<UUID> vouchers = new ArrayList<>();
진작에 지웠어야 하는 코든데 놓쳤네요! 당장 지우겠습니다!

2022-04-11 19:34 UTC, park0503 commented on src/main/java/org/prgrms/part1/Console.java
> +    public String question(String question) {
넵 알겠습니다!

2022-04-11 21:46 UTC, park0503 commented
혹시 멘토님 pc가 맥 환경이신가요?? 찾아보니 윈도우에서는 path 구분자가 '\'이고 unix/linux 계열에선 구분자가 '/' 라고 하네요. 맥이시라면 아마 제가 path를 역 슬래시를 기반으로 작성해서 계속 empty가 뜨셨던 것 같습니다. 해당 부분 File.separator를 이용해 수정했는데 확인 부탁드립니다!

그리고 개별적으로 리뷰주신 부분들도 수정해 봤습니다.
- Enum class를 활용해 string으로 하드코딩 한 부분들을 수정했습니다.
- while문의 가독성을 위해 각 기능을 여러 클래스로 분할 시켰습니다.
  - VoucherCreator : create 명령 담당
  - VoucherPoster : list 명령 담당
- Error 메시지를 각 throw 문에서 정의되도록 변경했습니다.
- 혼동을 위해 voucher의 구현체들의 메소드 명을 getValue로 변경했습니다.
- FileVoucherRepository 내에 if문의 경우 method로 따로 빼내 책임을 분할했습니다. 같은 역할을 하는 메소드가 VoucherService 내에 존재하나 Repository에서 Service에 의존하면 안된다 생각하여 별도의 메소드를 생성했습니다.

2022-04-11 22:25 UTC, park0503 commented
심화 요구사항이었던 application.yaml 파일 생성을 통한 profile 변경이 가능하도록 구현했습니다.
추가로 Spring Application을 사용하는 Part1Application 클래스도 구현했습니다.

2022-04-12 03:26 UTC, park0503 commented
enum에 대해 좀 더 공부해 봤는데, 제가 모르는 부분이 상당히 많았습니다. 그래서 피드백 주신 내용들을 잘못 이해했었네요.
enum 내부에 field와 method들을 이용해서 코드 대부분의 if / swtich문을 간소화 시켜봤습니다. 맞게 이해했는지 모르겠네요 ㅎㅎ..

VoucherManager 부분은 switch문을 아직 건들지 않았는데, 입력받는 명령어에 대해 Enum을 따로 만들어서 처리하면 역시 switch문을 뺄 수 있을 것 같다고 생각합니다. 다만 걱정되는 부분이 해당 부분을 enum 내에 메소드로 만들면 voucherCreator나 voucherPoster의 run method를 사용하는 방법이 static method로 바꾸는 것 밖에 생각이 나질 않는데 이게 괜찮은 방법일지 의문입니다. 아니면 저 정도 switch문은 사용해도 괜찮은 것일까요?

2022-04-12 04:30 UTC, park0503 commented
csv 파일로부터 유저 블랙리스트 읽어오기를 구현했습니다.
이로써 일단 심화 요구사항까지 1차 구현은 완료했습니다!

2022-04-15 06:20 UTC, julie0005 commented on src/main/java/org/prgrms/part1/engine/VoucherCreator.java
> +            long value = parseValue(inputValue);
maxDiscountAmount 등에 대한 예외 처리는 따로 하지 않으신건가용?

2022-04-15 06:48 UTC, julie0005 reviewed
상혁님 코드리뷰 남겼습니다! 코드 잘 보았습니다. 👍😁

2022-04-15 06:48 UTC, julie0005 commented on src/main/java/org/prgrms/part1/engine/VoucherCreator.java
> +            Voucher voucher = voucherService.createVoucher(voucherType.get().createVoucher(UUID.randomUUID(), value));
maxDiscountAmount 등에 대한 예외 처리는 따로 하지 않으신건가용?

2022-04-15 06:48 UTC, julie0005 commented on src/main/java/org/prgrms/part1/engine/VoucherManager.java
> +    }
VoucherCreator.java 내에서도 selectVoucherType이 있는데 select 부분을 모아도 좋을 것 같다는 생각이 드네요! 크게 보면 모두 input의 일부분이라 input의 select 메소드의 매개변수로 String을 던져주면 내부에서 매개변수 String을 프린트 후 scanner.nextLine()을 호출하는 방법도 있을 것 같네요!

```java
public String select(String prompt){
  sout(prompt);
 return scanner.nextLine();
}
```

2022-04-15 06:48 UTC, julie0005 commented on src/main/java/org/prgrms/part1/engine/VoucherManager.java
> +        final String SELECT_SHOW_BLACKLIST = "black";
Menu 선택지가 점점 많아지면 어떻게 관리하면 좋을까요? 메뉴를 enum으로 관리해보면 어떨까요?!

2022-04-15 06:48 UTC, julie0005 commented on src/main/java/org/prgrms/part1/engine/VoucherPoster.java
> +            output.print("");
output.print("") -> 이건 어떤 의도인지 설명해주실 수 있나요?

2022-04-15 06:48 UTC, julie0005 commented on src/main/java/org/prgrms/part1/engine/MemoryVoucherRepository.java
> +        return storage.values().stream().toList();
Map 관련 함수에 values()를 사용할 수 있었군요! 저는 for each로 순회하며 list에 일일히 추가했는데 잘 배우고 갑니다! Map 관련 메소드를 더 공부해봐야겠군요

2022-04-15 06:48 UTC, julie0005 commented on src/main/resources/logback.xml
> +    </root>
질문) 이렇게 하면 VoucherManager의 info log는 root에 의해서 로그가 access.log에 남게 되는 것이 맞나요?

2022-04-15 06:48 UTC, julie0005 commented on src/main/resources/logback.xml
> +    </appender>
appender에서 access와 error 로그의 디렉토리를 log 내부에서 나누면 더 좋을 것 같아요!
* log/access/access.log
* log/error/error.log

2022-04-15 14:06 UTC, park0503 commented on src/main/java/org/prgrms/part1/engine/VoucherCreator.java
> +            Voucher voucher = voucherService.createVoucher(voucherType.get().createVoucher(UUID.randomUUID(), value));
네 일단은 Voucher 사용 로직에 관한 요구사항은 없어서 이 때는 따로 해주지는 않았는데요,
2주차 과제 시작하고 나서 왠지 모를 변덕으로 PercentDiscountVoucher랑 FixedAmountVoucher 모두 예외 처리를 해줬습니다.

2022-04-15 14:07 UTC, park0503 commented on src/main/java/org/prgrms/part1/engine/VoucherManager.java
> +    }
오 아얘 출력부분을 select 함수에 넣으라는 말씀이시죠? 괜찮은 방법 같습니다!
다만 그렇게 하면 input interface내의 method를 통해 출력이 이루어지기 때문에 차라리 output interface에 method를 따로 만들어 해당 메소드에 몰아 넣는 것도 괜찮을 것 같습니다. 사실 지금도 select 함수 내에서 질문사항을 출력하기 때문에 이 부분도 나중에 수정해야 할 것 같네요,,, 덕분에 좋은 발견 했습니다!

2022-04-15 14:07 UTC, park0503 commented on src/main/java/org/prgrms/part1/engine/VoucherManager.java
> +        final String SELECT_SHOW_BLACKLIST = "black";
넵! 좋은 지적입니다! Vocher 선택 부분을 Enum 처리로 바꾸면서 해당 부분도 바꿀 수 있을 것 같다고 생각은 했는데, 위에 코멘트에 적어 놓았듯이 case 문 내부에서 각자 다른 class의 run 함수를 실행하기에 해당 부분을 이쁘게 처리할 방법을 아직 생각하지 못해 일단 keep해둔 상황입니다. 2주차 강의를 진행하면서 손 볼 예정이니 그 때 다시한번 봐주시면 감사하겠습니다!

2022-04-15 14:07 UTC, park0503 commented on src/main/java/org/prgrms/part1/engine/VoucherPoster.java
> +            output.print("");
평범하게 아웃풋에 출력할 메시지를 전달하는 함수입니다. 사실 그냥 sout 해도 되는데 2주차 baseball 예제 때 곰튀김님이 input output console 이용해서 입출력 처리하신 거 보고 저도 그런식으로 짜고 있습니다 ㅋㅋ. 그래도 장점이 없지는 않은게 만약 output을 console이 아닌 특정 file에게 전달해야 한다고 치면 다른 코드의 수정 없이 VoucherManager에서 output을 Console이 아닌 다른 구현체를 만들어서 주입해주기만 하면 변경이 가능하단 장점이 있다고 생각해 계속 쓰고 있습니다.
2주차 과제 진행 중에는 Voucher에 toString() 메소드를 통해 한번의 print 메소드 호출로 처리하도록 변경했습니다.

2022-04-15 14:07 UTC, park0503 commented on src/main/java/org/prgrms/part1/engine/MemoryVoucherRepository.java
> +        return storage.values().stream().toList();
넵 key 없이 value만 출력해주는 함수가 있더라구요!
근데 조심해야 하는점이 List처럼 입력된 순서를 보장해주는 건 또 아닌 것 같더라구요. 이 점만 조심하면 유용하게 쓸 수 있을 것 같습니다!

2022-04-15 14:07 UTC, park0503 commented on src/main/resources/logback.xml
> +    </root>
네 맞습니다!
근데 이렇게 하니 root에는 너무 많은 로그가 찍혀서 VoucherManager 내에서 찍힌 로그를 찾아보기 힘들더라구요.
그래서 CommandLineApplication에서 발생하는 Log 중 level이 debug 이상인 애들만 따로 로그 파일을 만들어 줄까 생각중입니다.

2022-04-15 14:07 UTC, park0503 commented on src/main/resources/logback.xml
> +    </appender>
오 좋은 것 같습니다! 당장 나눌게요

2022-04-29 10:15 UTC, merged