[2기-C]정경일 SpringBoot-basic week1 코드리뷰 부탁드립니다!
prgrms-be-devcourse/springboot-basic pull request #210
Opened 2022-04-12 15:13 UTC by jki503

## TODO

</br>

> pr이 더 늦어질 것같아 피드백 이후 추가하도록 하겠습니다.

</br>

- logback
- jar
- property

</br>

## diagram

|          간략한 다이어그램          |
| :---------------------------------: |
| ![class diagram](class_diagram.png) |

</br>

## package

- part1
  - configuragtion
    - AppConfiguration.java
  - error
    - member
      - BlackListEmptyException.java : 블랙리스트 멤버 없을 경우
    - voucher
      - FixedAmountException.java : 고정금액 에러
      - PercentErrorException.java : 퍼센트 에러
      - VoucherListEmptyException.java : 바우처 없을 경우
      - VoucherTypeMissingException : 바우처 타입 잘못 입력할 경우
  - io
    - Console.java : Client.java에서 사용할 입출력 기구
    - Input, Output : 콘솔에서 사용할 인터페이스
    - Message.java : 프롬포트에서 사용할 메시지 클래스
  - member
    - entity
      - Member
      - MemberDto.class : csv에서 읽어올 객체
      - MemberType : 과제와 무관
    - repository
      - MemberRepository.java : 제네릭 타입으로 구현한 인터페이스
      - FileMemberRepository.java : csv Read 레포지토리
    - MemberController : ui 계층과 맞닿아 전달만 하는 계층
    - MemberService : 비즈니스 로직 처리 계층
  - order
    - entity
      - Voucher : 인터페이스
      - FixedAmountVoucher
      - PercentAmountVoucher
      - VoucherType : 입출력에서 생성할 경우 판별 할 enum 타입
  - ui
    - client : ui 계층 담당
    - CommandType : 유저가 입력할 명령어 enum 타입

</br>

## **PR 포인트**

</br>

1. 에러 처리가 각 클래스별로 책임을 잘 지고 있는지
2. 수업을 듣고 나서 생각한 것이 개발 순서를 domain
   -> controller와 같이 고수준에서 저수준으로 만들고 테스트 케이스를 만드는것이 적합할지
3. 패키지를 어떻게 나누는 것이 좋을지 궁금합니다!

2022-04-14 06:24 UTC, VictoryPark requested changes
경일님!
온라인 팀 모임에서도 항상 적극적이신 모습 보기좋습니다!
코드에서도 controller 까지 생각하면서 고민이 많이 묻어나 있는 것이 보이네요.
더 자세한 사항은 코멘트 남겼습니다!

1. try-catch의 반복이 아닌 방법으로 한번 고민해보세요!
2. domain model , repository, service 별로 먼저 단위 테스트 후에 보통 controller 테스트를 합니다.
3. 패키지는 전체적으로 괜찮은데, member 와 voucher 는 도메인 모델 개념이니까, domain 패키지를 만든다음에 아래에 넣는게 좋을 것 같네요!!

2022-04-14 06:24 UTC, VictoryPark commented on part1/src/main/java/com/programmers/part1/ui/Client.java
> +                break;
요것도 switch 문에 있어도 되지 않을까용?

2022-04-14 06:24 UTC, VictoryPark commented on part1/src/main/java/com/programmers/part1/ui/Client.java
> +                    }
try-catch 문이 각 case 문마다 반복되고 있는 것 같아요!
반복 코드를 줄 일 수 있는 방법이 뭐가 있을까요?

2022-04-14 06:24 UTC, VictoryPark commented on part1/src/main/java/com/programmers/part1/order/voucher/repository/VoucherRepository.java
> +public interface VoucherRepository<ID, T>{
제네릭 사용하신 방법이 쪼끔 아쉬워요 ㅠㅠ
제네릭은 클래스 외부에서 받은 객체로 성격이 정해지는 건데, ID를 외부에서 받아서 사용하지 않고 있군요 ㅠㅠ

2022-04-14 06:24 UTC, VictoryPark commented on part1/src/main/java/com/programmers/part1/order/voucher/entity/FixedAmountVoucher.java
> +    }
생성자에서 validate 하는 것은 아주 좋은 로직입니다!!
칭찬의 박수 👏👏👏

2022-04-14 06:24 UTC, VictoryPark commented on part1/src/main/java/com/programmers/part1/order/voucher/entity/PercentAmountVoucher.java
> +    }
좀 더 보완하자면,
validate 로직을 가장 코드 위에 넣습니다!
amount 검증이 된 후에 voucherId 를 넣는 것으로 말이죠!!😄

2022-04-14 06:24 UTC, VictoryPark commented on part1/src/main/java/com/programmers/part1/order/voucher/entity/PercentAmountVoucher.java
> +    private final long percent;
percent 가 0 과 100 사이라면 long 은 차지하는 공간이 너무 큰것 같아요 ㅠㅠ

2022-04-14 06:24 UTC, VictoryPark commented on part1/src/main/java/com/programmers/part1/order/voucher/VoucherController.java
> +            voucherService.saveVoucher(voucher);
굳이 if 문 바깥에 voucher를 선언한 이유가 있나요?
voucher 라는 변수 없이도 save 할 수 있지 않나요???

2022-04-14 06:27 UTC, park0503 reviewed
일단 제가 질문한 부분도 있고 바꿔보는게 어떻겠냐고 말한 부분도 있을텐데,
본질적으로는 전부 질문입니다... ㅋㅋㅋ 저도 아직 제가 아는 것에 대한 확신이 없어서요..
경일님의 생각 자유롭게 공유해 주시면 감사하겠습니다!

2022-04-14 06:27 UTC, park0503 commented on part1/src/main/java/com/programmers/part1/order/voucher/VoucherController.java
> +        switch (voucherType){
이왕 enum을 사용하는 김에 switch문을 안쓰고도 해결할 수도 있을 것 같습니다!
enum을 이용해 처리를 하면 추후에 voucher의 type이 늘어날 때 해당 부분의 수정 없이 enum class에만 코드를 추가해도 처리가 가능하지 않을까 생각합니다.
근데 사실 이부분은 저도 이번에 코드리뷰를 받고나서 알게된 거라 제가 이해한게 틀릴 수도 있습니다 ㅎㅎ,, 경일님은 어떻게 생각하시나요?

2022-04-14 06:27 UTC, park0503 commented on part1/src/main/java/com/programmers/part1/ui/CommandType.java
> +        return switch (command) {
string을 통해 enum type을 결정하는 방법은 저도 vocher의 type 을 정할 때 사용했었는데요,
저는 key value 형식으로 들어올 string을 미리 enum class에 field로 정의한 다음 for 문을 통해서 일치하는 string이 있는지 검사했었습니다. 말로 설명하려니 어렵네요... ㅋㅋㅋㅋ
제가 쓴 방법의 경우 enum type이 추가되어도 case문을 추가로 작성하지 않아도 된다는 장점이 있었는데
enum 상수를 추가할 때 vaule 값의 중복을 보장하는 방법을 아직 찾지 못해 안정성은 경일님이 사용하신 방법이 더 좋은 것 같습니다. 경일님도 두 방법 한번 비교해 보시고 의견 나눠주시면 감사하겠습니다!

2022-04-14 06:27 UTC, park0503 commented on part1/src/main/java/com/programmers/part1/ui/Client.java
> +                    } catch (RuntimeException e) {
위에서 부터 4개의 catch가 전부 RuntimeException만을 잡아내고 처리해주는 내용도 같은데 switch문 전체를 try catch로 감싸는 것은 어떨까요?

2022-04-14 06:27 UTC, park0503 commented on part1/src/main/java/com/programmers/part1/error/voucher/PercentErrorException.java
> +
이건 저도 주변에 다른 개발자분 한테 피드백 받은건데,
지금 같은 구조는 넘겨 주는 message로 어디서 발생한 exception인지 알 수 있고 exception별 처리해주는 것도 다르지 않는데 Custom exception을 굳이 여러개로 나누는 이유가 뭐냐는 질문을 받았습니다. 저는 딱히 이유가 없어서 아무말도 못했습니다 ㅋㅋ 경일님은 혹시 다른 이유가 있으신지 궁금합니다!
추가로 그래서 제가 현업에서는 Custom Exception을 최대한 적게 쓰는게 좋은 구현이냐 라고 물어보니 그건 또 아니라고 하더군요. 그때그때 다르게 대처해야 하나봐요. 머리가 너무 아픕니다.

2022-04-14 06:27 UTC, park0503 commented on part1/src/main/java/com/programmers/part1/member/entity/MemberDto.java
> +
제가 DTO에 대해서는 문외한인지라, 언제 써야하고 어떻게 활용하는지 잘 모릅니다. 그래서 완전 초심자의 입장에서 보기로는 현재는 MemberDto가 담고 있는 내용이 Member와 완전히 같아 굳이 MemberDto를 따로 선언하는 것에 대해 이해하기 어렵습니다. 이는 추후 확장성을 위해서인가요? 예를 들면 전송되는 data이 포맷이 변경된다 할 때를 대비한 구조일 수도 있겠네요.
추가로 실제로 data를 전송할 때 Member class같이 entity class로 객체를 만들어서 전송하는 것은 구조적으로 지양되어야 하는 것인가요? member의 데이터 전부를 보내야 하는 경우에도 적용되는지가 궁금합니다!

2022-04-14 06:36 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/member/entity/MemberType.java
> +    };
처음에 멤버 상태를 업데이트 하는 기능도 만들려다 일단 넘겼는데, 삭제하거나 주석으로 명시했어야했는데.. 혼란 드려서 죄송합니다...

2022-04-14 06:37 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/ui/Client.java
> +        VoucherController voucherController = applicationContext.getBean(VoucherController.class);
지역 변수로만 쓰겠다는 의도였는데, 차라리 CommandLineApplication에서 주입하는 것이 더 나았겠네요!

2022-04-14 06:39 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/order/voucher/entity/PercentAmountVoucher.java
> +    private final long percent;
수업 코드를 인용해오는 과정에서 아무 생각없이 타이핑 했던 것같네요... 메모리를 낭비하는 짓이었네요...ㅠㅠ

2022-04-14 06:40 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/order/voucher/VoucherController.java
> +            voucherService.saveVoucher(voucher);
함수 파라미터로 생성을 넘기는 것을 묘하게 꺼리는 경향이 있는데, 참고하고 고치도록 하겠습니다!

2022-04-14 06:45 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/member/MemberController.java
> +    public List<MemberDto> list() throws IOException, BlackListEmptyException {
오 상혁님 아주 좋은 질문이고 사소하지만 서로 의견을 공유하기 좋은 내용인 것같네요!

저도 이 내용을 공부하고 보자마자 적용해본것이긴 한데,
그냥 메소드 정의만 보고도 의도를 전달할 수 있는 것을 선호하는 편이긴 합니다.

큰 차이가 없을 수 있지만... 
그래도 "저것만 보고도 파악할 수 있지 않을까~" 였습니다..ㅎㅎ

2022-04-14 06:45 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/order/voucher/VoucherController.java
> +        switch (voucherType){
이거는 고치도록 하겠습니다... 제가 enum의 장점을 잘 이해 못하고 그냥 쓰는 것같아요!

2022-04-14 07:00 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/ui/Client.java
> +                    } catch (RuntimeException e) {
exception이 다름으로 명시를 하는 쪽으로 가닥을 잡았는데,
코드가 난잡해지느냐.. 명확성 추구냐.. 좀 고민을 해보겠습니다. 좋은 지적 감사합니다!!

2022-04-14 07:03 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/error/voucher/PercentErrorException.java
> +
사실 지금 여러 exception들 내용 모두가 똑같고 매직으로 String을 넣어서 겹치고 있죠ㅋㅋㅋㅋ
저도 그것이 항상 고민인데 일단 맞든 틀리든 오버일 수 있지만 "쪼갤 수 있으면 쪼개보자"라는 마음으로 하고 있습니다.
쪼개본 사람이 합치는 것은 쉬운 일이니까..?

또 이건 제 성향인데 저는 method 이름이나 변수 이름 하나로 의도를 주는 걸 굉장히 좋아해요.
주석이 필요없는..? 
그걸 의도 해서 짰는데 사실 똑같은 클래스가 여러개 있는 거나 다름이 없어서... 쪼오끔 그렇네요..
좋은 방법 찾으시면 꼭 알려주세요!

2022-04-14 07:20 UTC, jki503 commented on part1/src/main/java/com/programmers/part1/member/entity/MemberDto.java
> +
저도 지식이 짧아 도움이 못되는 답변일 수 있습니다.
사실 이번 과제에서는 저렇게까지 안해도 됩니다!ㅋㅋㅋㅋ
문제는 Entity와 DTO의 차이가 문제겠죠?

DTO는 계층 사이에 데이터를 주고 받을때 사용하는 객체입니다.
그러므로 그어떤 로직(행위)가 요구되지 않죠.

반면에 저희가 의도한 Customer를 억지로 entity라고 생각해볼까요?
예를 들면 Customer의 나이는 15살 이상이어야 한다고 가정한다면
Member entity 가 customer 생성의 책임을 지는 로직을 가져야 하죠.
하지만 저희가 애플리케이션 <-> 서비스 <-> 레포지토리간의 데이터를 주고 받을 때
이런 로직이 필요할까요?

아마 와닿지 않거나 조금 개념이 헷갈리신다면,
아직 우리가 구현한 entity class가 요구하는 로직(행위)이 적어서 그럴 수도 있을 것같네요ㅠㅠㅠ
설명이 부족했을 수도 있으니, Notion에 참고자료 올려놓겠습니다!

2022-04-17 20:50 UTC, jki503 reviewed
## package

- part1
  - configuragtion
    - AppConfiguration.java
  - domain
    - Member.java
    - MemberDto.java : csv에서 읽어올 객체
    - Voucher : 인터페이스
    - FixedAmountVoucher
    - PercentAmountVoucher
    - VoucherType : 입출력에서 생성할 경우 판별 할 enum 타입
  - exception
    - member
      - BlackListEmptyException.java : 블랙리스트 멤버 없을 경우
    - voucher
      - FixedAmountException.java : 고정금액 에러
      - PercentErrorException.java : 퍼센트 에러
      - VoucherListEmptyException.java : 바우처 없을 경우
      - VoucherTypeMissingException : 바우처 타입 잘못 입력할 경우
      - CommandTypeMissingException : 명령어가 없을 경우
  - io
    - Console.java : Client.java에서 사용할 입출력 기구
    - Input, Output : 콘솔에서 사용할 인터페이스
    - Message.java : 프롬포트에서 사용할 메시지 클래스
  - member
    - repository
      - MemberRepository.java : 제네릭 타입으로 구현한 인터페이스
      - FileMemberRepository.java : csv Read 레포지토리
    - MemberController : ui 계층과 맞닿아 전달만 하는 계층
    - MemberService : 비즈니스 로직 처리 계층
  - order.voucher
    - repository
      - MemoryVoucherRepository
      - VoucherRepository
    - VoucherController
    - VoucherRepository
  - ui
    - client : ui 계층 담당
    - CommandType : 유저가 입력할 명령어 enum 타입

</br>

## **PR 수정 사항**

</br>

- [x] try - catch 반복 수정
- [x] enum 장점 살려서 refactor
- [x] client 의존성 문제 refactor
- [x] Message.java를 public static으로 변경
- [x] PercentVoucher.java amount 자료형 및 예외처리 수정
- [x] domain 패키지로 관련 바우처와 멤버 이동

## **TODO**

> Generic의 장점을 사용해서 다시 refactor 해보기  
> AOP 적용해서 log 및 Property 세팅은
> PR approve 받고 현재 진행중인 과제에 적용해서 리뷰 받아도 될까요...?

2022-04-20 13:11 UTC, closed without merging