[2기-C] 정다현 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #218
Opened 2022-04-14 04:12 UTC by sdardew

## 📌 과제 설명
바우처 관리 애플리케이션 1주차 과제입니다.

## 👩‍💻 요구 사항과 구현 내용
- [x] 바우처 관리 Command-line Application을 만들어본다.
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x] 적절한 로그를 기록하고 logback 설정을해서 에러는 파일로 기록된다.
- [x] 실행가능한 jar 파일을 생성한다. 

## ✅ PR 포인트 & 궁금한 점
- 이번 과제에서 기본 사항만을 했습니다.
- java 16 버전을 사용했는데 다음에는 java 11 버전으로 과제를 수행하겠습니다!
- commit 단위가 좀 큽니다...
- voucher 패키지를 만들어 voucher 관련 클래스들을 묶고 그 안에서 또 관련된 클래스들을 묶었습니다. 어떻게 묶어야 좋은지 피드백 해주셨으면 좋겠습니다.
- voucher 리스트를 출력할 때 repository에서 모든 리스트들 문자열로 만들어서 리턴하고, 리턴 값을 받아서 터미널에서 출력했습니다. 문자열로 받아도 되는지 아님 그냥 리스트들을 받는게 좋을지 궁금합니다.

2022-04-16 12:36 UTC, ksy90101 requested changes
테스트 코드 추가해주세요.

2022-04-16 12:36 UTC, ksy90101 commented on build.gradle
> +sourceCompatibility = '16'
11또는 17을 사용해주세요.

2022-04-16 12:36 UTC, ksy90101 commented on build.gradle
> +}
이 코드의 목적은 무엇인가요?

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/CommandLineApplication.java
> +public class CommandLineApplication {
```suggestion
import java.util.UUID;

public class CommandLineApplication {
```

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/CommandLineApplication.java
> +  public static void main(String[] args) {
여기에서는 단순히 애플리케이션을 실행하는 run메서드 하나만 넣어주세요.
지금 view와 로직이 엄청 섞여있네요.
view도 모두 다 분리해주세요.

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/voucher/VoucherService.java
> +      .orElseThrow(() -> new RuntimeException(MessageFormat.format("Can not find a voucher for {0}", voucherId)));
과연 RuntimeException이 맞을까요?
좀 더 의미잇는 메서드를 사용해주세요.

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/voucher/VoucherService.java
> +  }
필요없는 메서드는 삭제해주세요.

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/voucher/repository/MemoryVoucherRepository.java
> +      stringBuffer.append(storage.get(voucherId).toString() + "\n");
개행은 System.lineSparate 를 한번 알아보세요.

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/voucher/repository/MemoryVoucherRepository.java
> +    return stringBuffer.toString();
단순히 findAll은 string이 아니라, 자료구조인 List가 나와야 하지 않을까요?

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/voucher/voucher/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
바우처는 상속 관계가 좋을지 한번 고려해보세요.

2022-04-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/voucher/voucher/PercentDiscountVoucher.java
> +    return beforeDiscount * (percent / 100);
100은 매직넘버 :)

2022-04-16 12:36 UTC, ksy90101 commented on src/main/resources/logback.xml
> +             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
에러는 삭제해주세요.

2022-04-17 09:45 UTC, sdardew commented on build.gradle
> +sourceCompatibility = '16'
11로 변경하였습니다 ~ : )

2022-04-17 09:46 UTC, sdardew commented on build.gradle
> +}
gradle에서는 jar 파일을 생성하기 위해서 해당 코드가 필요해서 추가하였습니다.

2022-04-17 09:50 UTC, ksy90101 commented on build.gradle
> +}
없어도 jar 만들어 지지 않나요?

2022-04-18 06:09 UTC, sdardew commented on build.gradle
> +}
없어도 jar 파일이 만들어 지긴 하는데, 제가 의도한 대로 동작하지 않습니다. 제가 따로 콘솔용으로 클래스를 만들고 해당 클래스를 동작시키기 위해 해당 설정을 했습니다. 해당 설정을 통해서 어떤 main 클래스를 사용할 것이고, 그리고 의존하는 라이브러리도 같이 묶어주었습니다.

2022-04-19 13:43 UTC, sdardew commented on src/main/java/org/prgrms/springbootbasic/voucher/VoucherService.java
> +      .orElseThrow(() -> new RuntimeException(MessageFormat.format("Can not find a voucher for {0}", voucherId)));
해당 메서드는 이번 과제에서 사용하는 메서드가 아니라서 삭제했습니다

2022-04-21 05:10 UTC, ksy90101 commented
2주차에서 다시 전체적으로 볼게요. 2단계 진행 해주세요 :)

2022-04-21 05:10 UTC, merged