[2기-P] 김형욱 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #222
Opened 2022-04-14 15:42 UTC by HyoungUkJJang

## 📌 과제 설명 

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

   ```bash
   === Voucher Program ===
   Type **exit** to exit the program.
   Type **create** to create a new voucher.
   Type **list** to list all vouchers.
   ```

    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 

![image](https://user-images.githubusercontent.com/50834204/163425029-8c1f94c0-fe00-4c5a-b018-123f764be521.png)

* Voucher
  * FixedAmountVoucher / PercentAmountVoucher 구현체를 만들었습니다.
  * VoucherType을 추가하여 타입을 비교할 수 있도록 추가하였습니다.
* VoucherRepository
  * MemoryVoucherRepository 구현체를 통해 바우처를 저장하도록 만들었습니다.
  * **추후 심화로 진행할 것을 고려하여 VoucherRepository를 인터페이스로 만들었습니다.**
* InputView
  * 메뉴 입력 / 바우처 생성 등 입력에 관한 기능을 만들었습니다.
  * Menu를 통해 메뉴 리스트가 없을 경우의 상황을 처리하였습니다.
* OutPutView
  * 메뉴 출력 / 바우처 조회 등 출력에 관한 기능을 만들었습니다.
* CommandLineApplication
  * 커맨드라인 바우처 관리 어플을 실행하는 클래스입니다.
  
## ✅ PR 포인트 & 궁금한 점 
* log를 어느곳에서 남기는게 의미가 있는것인지 아직 감이 잘 오지않아 바우처 생성과 error가 날 경우에만 남기도록 하였는데 이부분은 조금 더 고민해 보겠습니다.
* 검증과 예외처리에 대한 부분을 어떤식으로 가져가야 할지 고민을 해보고 있습니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon requested changes
고생하셨습니다.
Enum 클래스를 적극적으로 활용하는 방안으로 고민 해주시길 바랍니다.
네이밍을 사용할때 일반적으로 사용되는 네이밍을 이용하게되면 누구나 쉽게 이해할 수 있는 장점이 있습니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/CommandLineApplication.java
> +public class CommandLineApplication {
해당 클래스를 별도로 나뉜 이유가 있을까요?

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/CommandLineApplication.java
> +        AnnotationConfigApplicationContext ac = new AnnotationConfigApplicationContext(
ac 도 좋겠지만 의미 있게 네이밍을 가져가보세요 :)

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/VoucherController.java
> +        while (true) {
반복문은 반복조건이 있습니다. 현재 반복조건은 무한 루프를 이용하기에 좋다고 생각하지 않습니다.
반복 조건을 명확하게 지정하는 것이 좋습니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/VoucherController.java
> +            execute(InputView.inputTheMenu());
inputTheMenu 라는 네이밍도 좋지만 getCommand 라는 네이밍은 어떤가요?

```
var command = this.InputView.getCommand();
this.excetue(command);
```

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/VoucherController.java
> +    }
Voucher Enum 을 통해서 바우처를 종류에 따라 생성하는 것을 제안 드립니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/VoucherController.java
> +    private final VoucherRepository voucherRepository;
Controller 에서 repository 레이어를 의존하기 보다 service 레이어에 의존하기 바랍니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/VoucherController.java
> +    }
repository 를 이용해서 하나의 기능을 만드고 계신다면 service 의 역할로써 기능을 제공 할 수 있다고 생각합니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/view/InputView.java
> +        validateCount(inputs);
해당 메서드 네이밍을 보았을때 어떠한 수를 검사하는 것으로 느껴집니다. 명확한 네이밍을 고려해보세요.
해당 메서드는 또한 별도로 분리 하기보다 현재는 합쳐도 될것 같습니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/view/Menu.java
> +public enum Menu {
Menu 라는 네이밍 보다는 Command 가 더 적합해 보입니다.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/view/Menu.java
> +    public static Menu findOf(String s) {
findOf 보다 of 로 네이밍을 일반적으로 사용하니다.
s 라는 네이밍을 줄이기 보다 풀네이밍을 작성해주세요.

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +        System.out.println("Type list to list all vouchers.");
현재 기준으로 Mene 라는 Enum 클래스와 함께 변경사항이 적용될것 입니다.
Menu 라는 Enum 을 이용해보면 어떨까요?

2022-04-16 05:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/voucher/repository/VoucherRepository.java
> +    Collection<Voucher> getAll();
Collection 으로 반환 타입을 한 이유가 무엇일까요?

2022-04-23 08:27 UTC, Jo-GyuHyeon requested changes
커멘트 이외에도 저희가 직접얘기한 부분들도 함께 수정하면 좋을 것 같습니다.
다음 Commit 을 하고 리뷰를 대기 하고 있을때 description 이나 comment 를 남겨주신다면 고민 하신부분을 더 자제히 볼 수 있을 것 같습니다. 
고생하셨습니다.

2022-04-23 08:27 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/customer/repository/BlackListCustomerRepository.java
> +        }
파일 관련 부분을 따로 기능을 빼서 사용하면 어떨까요?
Repository 에 다른 기능들이 생겼을때 중복문제도 해결 할 수있을뿐만 아니라 파일에서 일어나느 예외는 파일기능을 하다가 발생해야 된다고 생각도 듭니다.

2022-04-23 08:27 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +    }
실은 이부분은 show 라는 네이밍으로 오버로딩을 사용할 수 있다고 생각합니다.

2022-04-25 05:39 UTC, whyWhale reviewed
👍🏼  
수고하셨습니 🥕 !!

2022-04-25 05:39 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/voucher/model/VoucherType.java
> +public enum VoucherType {
오호라 전략 생성 패턴 👍🏼

2022-04-25 05:39 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/voucher/repository/FileVoucherRepository.java
> +        return read();
body 부분을 따로 read()로 따로 가져가신 이유가 있으신가요?

2022-04-25 05:39 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/voucher/model/PercentDiscountVoucher.java
> +    @Override
this.percent/100에서 long 타입이라 소수점을 버리게되서  버그가 발생할 것 같습니다!

2022-04-25 07:21 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/CommandLineApplication.java
> +public class CommandLineApplication {
커맨드로 실행되는 클래스를 따로 분리하는게 좋을 것 같아 분리를 하였습니다. 이 부분에 대해서 더 고민해보겠습니다 !

2022-04-25 07:29 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/customer/repository/BlackListCustomerRepository.java
> +        }
파일을 읽어오는 작업을 private 메서드로 따로 분리를 해주었는데 멘토님께서 말씀하신 방법이 이 방법이 아니였나 보군요..! 조금 더 방법을 고민해보겠습니다 !

2022-04-25 07:31 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/voucher/repository/FileVoucherRepository.java
> +        return read();
파일을 읽어오는 부분을 따로 분리하기 위해 만들어 주었습니다! 멘토님께서 말씀하신 파일과 관련된 기능을 분리하기 위함으로 메서드를 따로 작성했는데 이 방법이 아닌 것 같네요 😅  더 좋은 방법을 고민해 보겠습니다 !

2022-04-25 07:33 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/voucher/model/PercentDiscountVoucher.java
> +    @Override
이부분을 생각하지 못했네요 ! 수정하도록 하겠습니다 👍🏻

2022-04-25 08:42 UTC, midasWorld reviewed
고생 하셨습니다. 👍

2022-04-25 09:43 UTC, pjh612 reviewed
고생하셨습니다 깰꼼하시군요!

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +    public void makeVoucher(VoucherType voucherMenu, long discountValue) {
취향 차이일 것 같긴 하지만 makeVoucher에서 voucher는 없어도 되는 네이밍이라고도 생각듭니다.
이 함수 사용시 voucherService.makeVoucher() 형식으로 쓸 텐데 이미 "voucherService" 에서 voucher에 관한 문맥을 제공하고 있다고 생각을해요.
voucherRepository에서 saveVoucher()라 네이밍 하지않고 save()로 하는 것처럼이요.

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/voucher/model/PercentDiscountVoucher.java
> +        if (percent < MIN_PERCENT || percent > MAX_PERCENT) {
개인적으로는 0%할인은 말이 안되지만 100%할인은 가능하다고 봅니다!

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +
static 메소드는 범용성이 있는 유틸성 메소드에 적용하는 것이 좋다고 생각듭니다

과연 아래 아래 함수들이 "범용성"이 있는지 의문이 듭니다. Voucher Application에서만 사용할, 더 나아가 VoucherController에서만 사용될 메서드라고 생각이 들기도 합니다..

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +    public static void show(Collection<Voucher> vouchers) {
네이밍에서 조금 직관적이지 않다는 느낌을 받았습니다. show가 어떤것을 show를 해줄지 ide의 도움이나 구현체를 뜯어보지 않고서는 어떤것을 보여주는지 클래스이름이나 메서드 네이밍으로부터 어떠한 문맥도 제공받지 못했다고 생각합니다.

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +    public static void show(List<Customer> customers) {
위와 마찬가지입니다.

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/view/InputView.java
> +    private static final Scanner SC = new Scanner(System.in);
개인적으로는 짧고 명확하지 않은 네이밍보다는 길고 명확한 네이밍이 더 좋다고 생각이 듭니다!

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/customer/repository/BlackListCustomerRepository.java
> +    public List<Customer> findAll() {
read() 함수를 따로 뺀 이유가 궁금합니다.

findAll()은 하나의 함수를 사용하는데 굳이 분리할 필요가 있나 싶은 생각이 듭니다

2022-04-25 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/view/InputView.java
> +    public static String[] inputTheVoucher() throws IllegalArgumentException {
inputs[1] 에는 무조건 숫자가 담겨야될 것 같은데 숫자 외의 문자가 입력 됐을 때에 관련해 예외 처리가 됐나요?

IllegalArgumentException을 던지는 것처럼 보이긴 하는데 받는 쪽에선 어떠한 예외처리도 없어보여서 말씀드립니당

2022-04-25 09:46 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +    public static void show(Collection<Voucher> vouchers) {
쓰고나서 다른 커멘트들을 읽어보니 멘토님은 이 부분에서는 반대 의견이시군요.. 아무튼 제 생각은 이렇습니다 ㅎㅎ.. 오버로딩의 장점은 생각못했네요

2022-04-26 08:44 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/view/VoucherMenu.java
> +    PERCENT("ex_2) percent 15");
처음에 동운님께서 말씀하신 것처럼 하나로 관리를 했었는데 바우처를 생성하는 곳에서 menu 메시지를 보여주는게 맞을까? 생각이 들었습니다! 멘토님과 얘기를 나눠보다가 적당한 아이디어가 떠오르지 않아서 바우처메뉴라는 클래스를 따로 만들어 봤는데 제가 생각해도 깔끔한 방법은 아닌 것 같네요 조금 더 고민해 보겠습니다 :)

2022-04-26 09:28 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/voucher/model/PercentDiscountVoucher.java
> +        return beforeDiscount * (this.percent / 100);
생각하지 못한 부분이네요 통일하도록 하겠습니다 !

2022-04-26 09:29 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +    public void makeVoucher(VoucherType voucherMenu, long discountValue) {
저도 진형님 의견에 동의합니다 :)

2022-04-26 09:32 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +
맞는 말씀이십니다 ! 저는 바우처 컨트롤러같은 경우는 바우처와 관련된 의존성만 주입해주는게 가장 깔끔해 보일 것 같아 입출력 역할을 하는 클래스는 유틸성으로 만들었는데 말 그대로 유틸성의 목적에 맞지 않는 것 같긴 하군요 ㅠ 🤔

2022-04-26 09:35 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +    public static void show(Collection<Voucher> vouchers) {
이 부분이 저도 현재 고민인 것 같습니다 ! 원래 메서드 이름은 더 의도가 분명하도록 작성을 했었는데 단순히 출력을 하는 메서드 이기 때문에 역할은 똑같아서 오버로딩의 장점을 살릴 수 있더라구요 ! 
오버로딩의 장점을 살리면서 적절한 네이밍을 어떻게 짓는게 좋을지 현재 고민해보고 있습니다.  말씀대로 단순 show라는 이름은 어떤것을 보여주는지 설명하기엔 부족한 이름인 것 같아요

2022-04-26 09:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/view/OutPutView.java
> +    public static void show(Collection<Voucher> vouchers) {
제 생각에는 단순히 컬렉션을 출력하는것인데 굳이 함수를 나눌 필요가 있나? 싶기도합니다
메소드의 구현이 같아보이는데 그렇다면 차라리 컬렉션을 출력하는 유틸성 메소드를 제공하는게 좋지 않나? 생각이 듭니다.
public static void showList(List list) 라는 네이밍의 함수로 합칠 수 있지 않을까 생각듭니다.
일반적으로 네이밍에 자료구조를 표현하는 것은 좋지 않다고 할 수 있는데
이 경우 정확히 List 자료구조를 모두 출력하는 유틸성 메소드로 볼 수 있어 적절한 네이밍이 아닐까 싶슴다

2022-04-26 10:33 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/voucher/repository/FileVoucherRepository.java
> +        return read();
File과 관련해서 읽어 들이는게 **File**VoucherRepository의 역할이 맞는 것 같다라는 생각이 듭니다! 그리고 파일 환경에서는 모든 엔티티들이  파일과 관련해서 읽고 쓸때 비슷한 맥락을 가져가는 경우가 있어 이럴 때만 따로 Utils로 빼서 하면 좋을 것 같습니다!

2022-04-28 16:34 UTC, closed without merging