[2기-C] 정해민 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #224
Opened 2022-04-15 06:22 UTC by haemin-jeong

## 📌 과제 설명 
스프링부트 바우처 관리 애플리케이션 1주차 과제입니다😀

## 👩‍💻 요구 사항과 구현 내용
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
- [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
```bash
=== Voucher Program ===
Type exit to exit the program.
Type create to create a new voucher.
Type list to list all vouchers.
Type blacklist to list all black lists
```
- [x]  create / list / blacklist 커맨드를 지원한다.
      - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
      - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
      - blacklist 커맨드를 통해 ustomer_blacklist.csv 파일에 있는 블랙리스트를 조회할 수 있다. 
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.
- [x]  메모리, 파일 두가지 버전의 Repository를 제공하고, Profile에 따라 동작한다.
    - `MemoryRepository`는 `memory`,  `FileRepository`는 `file` Profile에서 동작
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ PR 포인트 & 궁금한 점 
- yaml 파일에 현재는 파일 경로에 관한 정보만 저장하여 사용하고 있습니다. 해당 애플리케이션에서 yaml 파일을 좀 더 활용할 수 있는 부분이 있을지 궁금합니다.
- 지금의 코드 구조로는 Voucher 구현체가 늘어나는 만큼 VoucherType에 변경이 일어나고, VoucherService 클래스의 createVoucher 메서드 내 swith 문의 라인이 계속 늘어나게 됩니다. 만약 Voucher 구현체가 계속해서 늘어날 수 있는 상황이라면, 어떻게 코드를 개선해야 변경을 최소화할 수 있을지 궁금합니다.

테스트 코드는 2주차 PR때 좀 더 보완해서 제출하겠습니다😅 감사합니다 흑구님😀

2022-04-16 03:57 UTC, WooSungHwan requested changes
테스트코드 조금이라도 확실하게 테스트할 수 있는 부분 작성해주시고 코멘트 몇자 적어놨으니 확인부탁드립니다.

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/VoucherManagement.java
> +    private final String CREATE_COMMAND = "create", LIST_COMMAND = "list", EXIT_COMMAND = "exit", BLACK_LIST_COMMAND = "blacklist";
사실 enum으로 됐으면 좀더 좋을 것 같습니다 ㅎㅎ

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/VoucherManagement.java
> +        output.printVoucherList(vouchers);
이거 List인터페이스 컬렉션 타입의 객체 내부를 toString을 호출하는 형태면 printList 메소드로 추상화가 가능할 것 같습니다.

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/VoucherManagement.java
> +        output.printVoucherList(vouchers);
List 내에 어떤 타입의 컬렉션이 들어와도 내부 객체의 오버라이딩된 toString이 호출되겠죠?

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/customer/BlackListRepository.java
> +    private final String BLACK_LIST_FILE_PATH;
properties 주입을 받았는데 이 변수가 꼭 필요할까요?

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/customer/BlackListRepository.java
> +        BLACK_LIST_FILE_PATH = filePathProperties.getBlackListFilePath();
예를 들어 파일패스뿐 아니라 다른 여러 파일관련 설정이 있다면 관련 설정 변수들을 repository에 선언하는 형태로 진행할것 같은데 그부분 보다 적절한 값을 properties에서 호출해서 사용하는 건 어떨까요?

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/customer/BlackListRepository.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(BLACK_LIST_FILE_PATH))) {
여기에 properties의 설정값을 불러올 수 있겠네요.

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/io/Console.java
> +        blackList.forEach(member -> sb.append("- ").append(member.getName()).append("\n"));
사실 이부분은 toString에서 만들어지면 더 좋을 것 같습니다. toString이 이미 다른 용도로 쓰고있다면 다른 용도의 string 타입 리턴 메소드를 정의해서라도 공통화를 해보시기 바랍니다.

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/voucher/VoucherType.java
> +}
enum이 voucher 인스턴스를 생성하게 할 순 없을까요?

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +    private final String VOUCHERS_FILE_PATH;
요기도 동일하네요!

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +        log.info("voucher is saved to file - {}", voucher);
사실 이건 레포지토리보다는 저장되는 트랜잭션이 끝났을 때 (모든 바우처 저장 서비스가 끝날때) 해주는게 맞아요. 레포지토리 레이어는 아직 데이터가 확실하게 저장됐다고 확실할 수 는 없는 단계라서 로그로 남기면 오히려 혼동이 있을 수 있어요.
지금은 별도로 롤백이라는 개념이 없기때문에 보장할 수는 있겠지만요.

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/voucher/service/VoucherService.java
> +    }
스위치문이 아닌 Voucher voucher = voucherType.constructor();

2022-04-16 03:57 UTC, WooSungHwan commented on src/main/java/com/prgrms/vouchermanagement/voucher/service/VoucherService.java
> +    }
근데 이건 제한조건이 있어요. 현재는 switch문이 단순 인스턴스 생성만 하고 있는데요. 나중에 디벨럽하다보면 얘가 결국 타입마다 다른 비즈니스 로직을 갖게될 수도 있을텐데 그부분에서는 어떻게 공통화하기가 매우 힘들어요. 그래서 다른 개발요건이 붙다보면 결국 이 형태를 크게 벗어나지는 않을거에요.

2022-04-16 03:57 UTC, WooSungHwan commented on src/test/java/com/prgrms/vouchermanagement/DemoApplicationTests.java
> +	void contextLoads() {
테스트코드!!!

2022-04-17 13:33 UTC, haemin-jeong commented
안녕하세요 흑구님!! 피드백 주신 내용 반영해봤습니다 ㅎㅎ

### 피드백 반영 내용
- VoucherManagement 클래스에서 메뉴 선택에 사용되는 상수를 COMMAND ENUM으로 분리
- FilePathProperties를 주입 받아 사용하는 BlackListRepository, FileVoucherRepository에서 각 값들을 필드로 저장하여 사용하지 않고, 값이 필요한 곳에서 직접 properties로 부터 값을 가져와 사용하도록 변경
- Customer 출력 시에 toString() 사용하여 출력하도록 변경
- 트랜잭션을 고려하여 VoucherRepository의 save 로그 출력 위치를 VoucherService로 변경
- Voucher 인스턴스를 VoucherType에서 생성하도록 변경

### 궁금한 점
- [여기](https://github.com/prgrms-be-devcourse/springboot-basic/pull/224#discussion_r851581584)에서 흑구님이 말씀하신대로 맞게 수정한 건지 궁금합니다🤔
- `Voucher voucher = voucherType.constructor();`에서 constructor 라는 메서드 이름도 of, getInstance 같이 팩토리 메서드에 많이 사용되는 이름인지 궁금합니다! 만약 그렇다면 보통 어떤 경우에 constructor라는 이름을 사용하는지 궁금합니다 ㅎㅎ
- 흑구님이 의도하신 대로 맞게 수정 한지는 잘 모르겠지만, VoucherType의 constructor 메서드에서 Voucher 인스턴스를 생성하도록 다음과 같이 수정하였습니다.
```java
public Voucher constructor(long amount) throws IllegalArgumentException {
        switch (this) {
            case FIXED_DISCOUNT:
                return FixedAmountVoucher.of(amount);
            case PERCENT_DISCOUNT:
                return PercentDiscountVoucher.of(amount);
            default:
                throw new IllegalArgumentException("일치하는 VoucherType이 없습니다");
        }
}
```
그런데 constructor 메서드는 인스턴스 메서드여서 VoucherType 인스턴스를 통해 호출되게 되고, 그렇기 때문에 switch 문의 default 라인으로 점프가 될 일이 없을  것 같습니다. 이러한 경우에도 위와 같이 그냥 예외를 던져주도록 코드를 작성 해놓는 것이 좋을까요? 

감사합니다😀

2022-04-17 13:58 UTC, haemin-jeong commented
안녕하세요 흑구님!! 피드백 주신 내용 반영해봤습니다 ㅎㅎ

### 피드백 반영 내용
- VoucherManagement 클래스에서 메뉴 선택에 사용되는 상수를 COMMAND ENUM으로 분리
- FilePathProperties를 주입 받아 사용하는 BlackListRepository, FileVoucherRepository에서 각 값들을 필드로 저장하여 사용하지 않고, 값이 필요한 곳에서 직접 properties로 부터 값을 가져와 사용하도록 변경
- Customer 출력 시에 toString() 사용하여 출력하도록 변경
- 트랜잭션을 고려하여 VoucherRepository의 save 로그 출력 위치를 VoucherService로 변경
- Voucher 인스턴스를 VoucherType에서 생성하도록 변경
- Voucher와 Customer List 타입을 출력하는 메서드를 printList() 메서드로 추상화

### 궁금한 점
- [여기](https://github.com/prgrms-be-devcourse/springboot-basic/pull/224#discussion_r851581584)에서 흑구님이 말씀하신대로 맞게 수정한 건지 궁금합니다🤔
- `Voucher voucher = voucherType.constructor();`에서 constructor 라는 메서드 이름도 of, getInstance 같이 팩토리 메서드에 많이 사용되는 이름인지 궁금합니다! 만약 그렇다면 보통 어떤 경우에 constructor라는 이름을 사용하는지 궁금합니다 ㅎㅎ
- 흑구님이 의도하신 대로 맞게 수정 한지는 잘 모르겠지만, VoucherType의 constructor 메서드에서 Voucher 인스턴스를 생성하도록 다음과 같이 수정하였습니다.
```java
public Voucher constructor(long amount) throws IllegalArgumentException {
        switch (this) {
            case FIXED_DISCOUNT:
                return FixedAmountVoucher.of(amount);
            case PERCENT_DISCOUNT:
                return PercentDiscountVoucher.of(amount);
            default:
                throw new IllegalArgumentException("일치하는 VoucherType이 없습니다");
        }
}
```
그런데 constructor 메서드는 인스턴스 메서드여서 VoucherType 인스턴스를 통해 호출되게 되고, 그렇기 때문에 switch 문의 default 라인으로 점프가 될 일이 없을  것 같습니다. 이러한 경우에도 위와 같이 그냥 예외를 던져주도록 코드를 작성 해놓는 것이 좋을까요? 

감사합니다😀

2022-04-20 12:48 UTC, WooSungHwan approved these changes
과제하시느라 고생 많으셨습니다.
추후 리뷰는 2주차에서 이어서 진행하도록 하겠습니다.

2022-04-20 13:22 UTC, merged