[2기-P] 김병연 SpringBoot Part1 Weekly Mission
prgrms-be-devcourse/springboot-basic pull request #225
Opened 2022-04-15 07:10 UTC by whyWhale

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 
- 블랙리스트 구현 x
- 파일 저장 구현 x

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2022-04-18 15:37 UTC, Jo-GyuHyeon requested changes
고생하셨습니다. :) 

코드 리뷰 내용이외에도 패키지 구조에 대해 궁금하여 질문의 남깁니다.
manager 안에 store 패키지가 있는 이유가 궁금합니다.

2022-04-18 15:37 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/FixVoucherManager.java
> +	}
해당 클래스에서 유효성 검사를 해야 될지? 고민 해보면 좋을것 같습니다.
입력에 대한 검증은 입력을 담당하는 쪽에서 처리하는 것이 적합니다.

2022-04-18 15:37 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/PercentVoucherManager.java
> +	}
위와 내용이 동일합니다. 이렇게 되었을때 중복된 로직이 발생하기도 합니다.

2022-04-18 15:37 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/FixVoucherManager.java
> +		while (true) {
반복문은 실행 조건이 필요하다고 생각합니다.

2022-04-18 15:37 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/FixVoucherManager.java
> +			return new FixedAmountVoucher(UUID.randomUUID(), Long.parseLong(fixPrice));
추후 fixPrice 의 파싱 하면서 예외가 생길 가능성이 있습니다.
오류가 발생할 가능성이 있다면 최대한 빨리 발견하는 것이 좋습니다.

2022-04-18 15:37 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/store/FileVoucherStoreManager.java
> +		}
별도의 메서드로 빼는 것을 추천드립니다.

2022-04-18 15:37 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/store/FileVoucherStoreManager.java
> +				return csvMapper.writerFor(Voucher.class).with(schema);
try 문 안에 꼭 이여야 될지? 고민해보면 어떨까요?

2022-04-18 15:44 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
> +		List<Voucher> vouchers1 = voucherStoreManager.getVouchers();
바로 고치겠습니당... ㅠㅠ

2022-04-18 15:46 UTC, whyWhale commented on app/src/main/java/com/programmers/order/dto/VoucherForCsv.java
> +@JsonPropertyOrder({"voucherId", "voucherType", "discountValue", "createdAt"})
순서 보장을 하기 위함이 맞습니다.!
 필드 선언이 중간에 삽입되어 질 경우를 대비하는 차원에 명시를 해주었습니다.!

2022-04-18 15:48 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
> +			}
클라이언트에 대한 오류 파악을 boolean으로 바꾸는 아이디어를 현재 가지고 있습니다.
 이 방법 보다 추천해주실 만한 키워드가 있으신지 궁금합니다 ! 😂

2022-04-18 15:58 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
> +			MenuType menuType = MenuType.of(menu);
이전에 실행 조건을 클라이언트에게 입력을 받는 쪽으로도 생각을 해보았었습니다. 그 방법을 택하지 않은 한가지의 이유는 코드가 깔끔하다고 생각했습니다. 그 이유는 상단에 선언문이 시작되므로 깔끔하지 못하다라고 판단했습니다. 현재 저의 생각은 무한 루프문과 실행조건을 받도록 하는 조건 결국은 'EXIT'이라는 키워드를 받지 못하면 계속 입력받도록 하는 로직은 똑같다고 생각합니다.! hoxy 🤤  우려되는 경우나 혹은 어떠한 이유로 인해 그럴 수 있는지 궁금합니다.😵

2022-04-20 05:38 UTC, whyWhale commented
@Jo-GyuHyeon 멘토니임 해당 부분 업데이트 완료했습니다!
- validation은 너무 도메인에 종속적인 것 같아 다른 대안을 찾아보았는데 아이디어가 될만 한 것이 없습니다.. ㅠㅠ
  - 왜냐하면 도메인 마다 제약조건이 다양하고 받아야 할 파라미터들이 제각각이라고 생각되기 떄문입니다 😞 
  - 결국은 1:1 매칭으로 구현체를 의존해야 할 것 같습니다!
- 예외처리 조언은 다음 2차때 같이 제출하겠습니 🥕 .

2022-04-23 07:41 UTC, Jo-GyuHyeon requested changes
불필요한 반복문을 줄여보세요. 그렇다면 인덴트에 대한 고민이 줄어 들것이라 생각합니다.

2022-04-23 07:41 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
>  	}
반복문이 필요한지 잘 모르겠습니다.
왜 반복문을 사용하였나요?

2022-04-23 07:41 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
>  			}
모든 구간이 try catch 로 잡혀 있습니다. 필요한 구간만 try catch 하도록 변경해보면 어떨까요?
지금 보니 output 클래스와 logger 가 같은 일을 처리 하고 있으니 output 클래스가 logger 를 함께 처리 하는 것은 어떨까요?

2022-04-23 07:41 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/FixVoucherManager.java
> +			isReEnter = false;
위와 마찬가지로 반복할 이유가 없어보입니다.

2022-04-23 07:41 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/FixVoucherManager.java
>  			if (!this.isValidPrice(fixPrice)) {
isValidPrice 같은 경우는 String 보다는 Number 타입으로 변환된 값으로 유효성 검사하는 것이 적절하다고 봅니다.
혹은 유요성 검사를 분리해야 된다고 생각합니다. 파싱 단계와 값으로써 숫자의 유효성을 체크하는 것이 적절하다고 판단됩니다.

2022-04-23 07:41 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/PercentVoucherManager.java
> +			isReEnter = false;
위와 동일한 내용입니다.

2022-04-28 16:34 UTC, closed without merging