[2-C] 문정현 Spring boot 1주차 과제 PR입니다.
prgrms-be-devcourse/springboot-basic pull request #227
Opened 2022-04-15 09:37 UTC by y005

## 📌 과제 설명 
- 바우처를 새로 생성할 수 있다. (Percent discount, Fixed amount discount)
- 생성한 바우처 정보를 조회할 수 있다.
- 바우처 정보들을 파일에 저장하고 불러올 수 있다.
- csv 파일에 저장된 블랙리스트 고객 정보를 조회할 수 있다.

## 👩‍💻 요구 사항과 구현 내용 
- [x] [Commandline Application](https://dzone.com/articles/interactive-console-applications-in-java)
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 사용해서 프로젝트를 만든다.
- [x]  스프링부트 애플리케이션으로 만든다. 
- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository 사용하고 
- [x] 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  YAML 프라퍼티를 만들어 사용한다.
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

## Class Diagram
![Untitled-2022-03-29-1415](https://user-images.githubusercontent.com/37391733/163554718-e6e17079-fd07-4d93-818b-11b76a87146c.png)

## ✅ 피드백 반영사항  
-  commandLineApplication내 command을 입력받고 switch문으로 상황에 맞는 서비스가 동작되도록 리팩토링
- 불필요한 import 제거
- ArrayList 레퍼런스를 List 인터페이스에 저장하는 방식으로 변경 
- concurentMap 사용 
- VoucherType을 별도의 파일로 분리 
- Voucher의 할인 정보에 대한 예외 처리 추가(음수인 경우, 퍼센트 범위가 넘는 경우)

## ✅ PR 포인트 & 궁금한 점 
- repository랑 service의 로직이 거의 비슷한데 이 경우에도 각 클래스에 대한 테스트를 하는 게 맞는 건지 궁금합니다.
- 빈 생성 전에 호출되는 메소드는 사용이 가능한데 소멸 전에 호출되는 메소드는 실제로 동작이 안되는 문제상황이 있음 (소멸 되기 전에 파일에 Voucher 정보를 기록하는 메소드를 호출하도록 했는데 실제로 반영이 안되서 Voucher 정보가 add 될 때마다 파일에 적는 걸로 구동한 상태입니다..)

2022-04-16 04:44 UTC, WooSungHwan requested changes
코멘트 몇자 남겼습니다. 확인부탁드립니다.

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/CommandLineApplication.java
> +			}
로직의 depth가 너무 깊습니다. 별도로 실행로직을 담는 클래스를 정의하시거나 private 메소드로 분리가 필요해보입니다.

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/CommandLineApplication.java
> +			}
create, list, exit 문자열 명령어들의 집합 enum을 정의해서 정리하는건 어떨까요?

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/CommandLineApplication.java
> +			}
float를 사용한 이유는 무엇인가요?

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/Customer.java
> +    }
해당 enum 별도 파일을 가진 클래스로 분리하는 건 어떨까요?

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/Customer.java
> +    }
흠 이부분은 차라리 전체 파라미터를 받는게 좋을 것 같습니다. List로 구성한 이유가 있을까요?
계속 코드가 유지보수 된다고 했을 경우 해당 생성자를 봤을 때 인덱스가 어떤 내용인지 확인하려면 add하는 부분을 그것도 순서도 보고 확인해야 할텐데 너무 비용이 큰 작업입니다.

파라미터가 많은 것이 부담스럽다면 차라리 생성자 오버로딩을 통해서 개선하는게 좋을 것 같습니다.

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/Customer.java
> +        if (o == null || getClass() != o.getClass()) return false;
instanceof 라는 키워드를 사용해보세요 ㅎㅎ

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/FileCustomerRepository.java
> +            //no need to throw exception (it can use empty array list)
당장은 처리할게 없지만 에러났을때 확인할 수 없는 에러는 디버깅하기 힘드니 stacktrace까지는 해놓는건 어떨까요?
상용시스템에서는 기본적으로 모니터링 소프트웨어가 적용된 상태이기 때문에 별도로 stack출력이 필요없을 수 도 있는데요. 현재는 개발중인 상황이고 어떤 에러가 발생할 지 모르기때문에 Exception 타입인걸로 생각이 되는데 우선은 에러내용이 뭔지만 체크는 해놓는게 좋을 것 같아요. 별도로 처리 안하겠다는 로직은 해당 Exception에 대한 catch를 잡고 아무 작업도 안하면 될것 같습니다.

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/exception/CanNotDiscountException.java
> +    }
저는 보통 이렇게 상수로 값을 집어넣는 부분이 있다면 추가적으로 파라미터 msg를 받아서 처리하는 것도 오버로딩처리를 해놓습니다. 언제 어떻게 쓰일지 모르기때문인데요. 생각보다 그때그때 오버로딩 해두면 미래의 정현님이 아주 좋아할거에요 ㅎㅎ

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/exception/ExitException.java
> +}
생성자가 없네요

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/voucher/FileVoucherRepository.java
> +    public FileVoucherRepository(@Value("${voucher_info}") String fileName) {
`@EnableConfigurationProperties`에 대한 적용이 된건 아닌것 같습니다.ㅜㅜ

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/voucher/FileVoucherRepository.java
> +    }
`spring bean destroy` 라는 키워드로 찾아보시겠어요?

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/voucher/Voucher.java
> +            throw new CanNotDiscountException();
왜인지 이유도 알려주면 좋을 것 같아요.

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/voucher/VoucherService.java
> +    }
얘도 io 쪽에서 담당했으면 좋을 것 같습니다. 아니면 getVouchers를 활용하여 io 클래스에 List컬렉션을 파라미터로 받는 printList. 메소드를 정의하여 해당 컬렉션 내의 foreach(o -> o.toString()) 호출을 하여 찍어낼 수도 있을것 같습니다.

2022-04-16 04:44 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/voucher/VoucherType.java
> +            return (currentPrice - amount);
파라미터 유효성 검사가 필요할 것 같습니다. 둘다 필수일것같은데 int, float로 선언해도 좋을 것 같습니다.

2022-04-16 04:44 UTC, WooSungHwan commented on src/test/java/com/kdt/commandLineApp/customer/CustomerServiceTest.java
> +        }
given, when, then 우선 이 세단계를 명확히 표시하는건 어떨까요?
현재 when과 then이 결합된 형태로 보입니다. (assertThat 내에 service 호출하고 있음)

2022-04-16 04:47 UTC, WooSungHwan commented
repository랑 service의 로직이 거의 비슷한데 이 경우에도 각 클래스에 대한 테스트를 하는 게 맞는 건지 궁금합니다.
-> 우선 현재는 필요없습니다. 사실상 프록시처럼 동작하고 있을테니까요. 하지만 repository를 사용하는 service의 비즈니스로직이 커지면 반드시 정리해놓아야합니다. 그러므로 실무에서 사실 두 로직이 완전히 같을일이 거의 없습니다. 따라서 로직 구분을 위해 별도로 정의하는 걸 습관화하시길 추천드립니다.

2022-04-17 05:06 UTC, y005 commented
피드백 주신 float의 경우에는 percent voucher에 대한 매개변수 입력에서 소수점도 받을 수 있다고 생각해서 코드를 작성한 거 같은데 고치면서 제 코드를 살펴보니 0에서 100까지의 수치를 허용하는 걸로 되어있어서 float가 아닌 int로 변경해놓고 percent, fixed voucher 모두 할인 값 속성을 int로 수정했습니다. 그리고 commandLineApplication도 명령어에 따라 수행하는 명령 동작은 MainLogic 클래스의 메소드 내에서 실행되는 걸로 변경시켰습니다.

2022-04-20 12:46 UTC, WooSungHwan approved these changes
과제하시느라 고생하셨습니다. 
추후 리뷰는 2주차 과제에서 이어서 진행할게요~

2022-04-20 12:46 UTC, merged