[2기-C 길근오] SpringBoot Part2 Weekly Mission 코드리뷰 요청
prgrms-be-devcourse/springboot-basic pull request #230
Opened 2022-04-15 14:48 UTC by hymn-fly

## 📌 과제 설명 
해당 주차는 JdbcTemplate을 활용한 Voucher 관리와 Customer 관리 기능을 추가하였습니다.

## 👩‍💻 요구 사항과 구현 내용
JdbcVoucherRepository, JdbcCustomerRepository를 구현하였고 관련하여 테스트 코드들을 작성하였습니다.

## ✅ 피드백 반영사항 

## ✅ PR 포인트 & 궁금한 점

2022-04-15 16:25 UTC, woogiekim requested changes
PR을 피쳐단위로 해주는게 좋긴하겠어요

새로운걸 써보시는건 좋지만 쓰시려면,
통일성있게 쓰는게 어떨까요?

코멘트 확인해주시고 고민하는 시간 갖으면 좋을거같습니다

2022-04-15 16:25 UTC, woogiekim commented on pom.xml
> +    </dependency>
이건 어디에 쓰는 라이브러린가요?

2022-04-15 16:25 UTC, woogiekim commented on src/main/java/org/prgms/customer/Customer.java
>  }
uuid, name, email 모두 null이여도 되고,
name과 email은 공백이여도 만들수 있을거같은데

정상케이스인가? 라는 생각이 드네요

2022-04-15 16:25 UTC, woogiekim commented on src/main/java/org/prgms/voucher/repository/FileVoucherRepository.java
> +                        }
메소드로 분리하는건 어떨까요?

2022-04-15 16:25 UTC, woogiekim commented on src/main/java/org/prgms/voucher/repository/FileVoucherRepository.java
> +            var targetPath = fileStream
var을 쓰실거면 일관성있게 사용하시는게 좋을거같습니다.

2022-04-15 16:25 UTC, woogiekim commented on src/main/java/org/prgms/voucher/repository/JdbcVoucherRepository.java
> +            return new PercentDiscountVoucher(amount, voucherId);
일괄적으로 바우쳐를 가져오는 방법도 있지 않을까요?

2022-04-15 16:25 UTC, woogiekim commented on src/main/java/org/prgms/voucher/service/VoucherService.java
> +        return voucher.get().apply(beforeDiscount);
보통 바우처를 있으면 무조건 적용하나요?

선택사항으로 하지않으려나요

2022-04-15 16:25 UTC, woogiekim commented on src/test/java/org/prgms/voucher/service/VoucherServiceTest.java
> +        var percentDiscountVoucher = new PercentDiscountVoucher(10L, UUID.randomUUID());
val 을 쓰는게 더 좋지 않으려나요?

2022-04-16 03:44 UTC, hymn-fly commented on pom.xml
> +    </dependency>
해당 라이브러리는 테스트 할 때 embedded mysql을 만들어 주는 라이브러리입니다! 조금 무거운거 같긴하더라구요ㅠ 테스트 실행 시 구동하는데 시간이 좀걸려요

2022-04-16 03:45 UTC, hymn-fly commented on src/main/java/org/prgms/voucher/repository/FileVoucherRepository.java
> +                        }
넵 그렇게 하겠습니다! 코드의 가독성을 위해서이지요??

2022-04-16 07:42 UTC, hymn-fly commented on src/main/java/org/prgms/voucher/repository/JdbcVoucherRepository.java
> +            return new PercentDiscountVoucher(amount, voucherId);
멘토님 이부분이 잘 이해가 가지 않는데 혹시 조금 더설명해 주실수있으신가요..!

2022-04-16 14:08 UTC, hymn-fly commented on src/main/java/org/prgms/voucher/service/VoucherService.java
> +        return voucher.get().apply(beforeDiscount);
멘토님 해당 메서드는 바우처를 사용하기 위한 의도로 만들긴 했습니다
로직 상으로 listVoucher를 통해서 사용할 수 있는 바우처를 보여주고 UI상에서 특정 바우처를 선택하면
useVoucher() 메서드를 사용해서 할인된 가격을 보여주도록.. 이렇게 생각을 했는데 혹시 다른 어떤 방법이 있을까요??

2022-04-17 05:16 UTC, merged