[2C-정다현] SpringBoot Part2 Weekly Mission 제출합니다
prgrms-be-devcourse/springboot-basic pull request #246
Opened 2022-04-17 09:43 UTC by sdardew

## 📌 과제 설명
1주차때는 메모리로 바우처를 관리하였다면,
2주차에는 JDBC를 사용하여 바우처를 관리하는 기능을 추가하였습니다.
바우처를 customer에게 발급하는 기능 또한 추가하였습니다.

## 👩‍💻 요구 사항과 구현 내용

### 기본
- [x] 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
- [x] 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
- [x] 바우처 정보를 DB로 관리해보세요.

### 심화
- [x] 특정 고객에게 바우처를 할당할 수 있습니다.
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다. 

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/86591021/163708844-ef7d86f4-0a8c-42fe-ac7c-e9ac2f1689b5.png">
vouchers 테이블입니다.
reduction에는 할인율 또는 할인 금액이 들어갑니다. 해당 값이 할인율인지 할인 금액인지 판단은 voucher_type 데이터를 사용하여 판단할 수 있습니다.  

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/86591021/163708891-ba3093c9-8c8d-4d11-932f-4e17995db374.png">
customers 테이블입니다. 관련 코드들은 수업시간에 작성한 것을 가져왔습니다.  

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/86591021/163708916-da4718a0-4964-40da-903e-adaed7f35a4e.png">
wallet 테이블입니다. voucherid와 customerid가 짝지어서 테이블에 들어갈 수 있습니다. 해당 값은 중복될 수 있습니다. 쿠폰을 여러장 발급받을 수도 있기 때문입니다.  
쿠폰이 발급될때마다 wallet 테이블에 데이터가 저장되는 방식으로 구현하였습니다.

## ✅ PR 포인트 & 궁금한 점
- 테스트의 어떤 부분이 부족한지 말씀해주셨으면 좋겠습니다.
- Voucher관련 클래스들이 많아서 조금 복잡한 것 같아, 어떻게 수정하면 좋은지 피드백 해주셨으면 좋겠습니다
- 테이블 구성을 많이 고민했는데, 보통 어떻게 구성하는지 궁금합니다

2022-04-26 13:28 UTC, ksy90101 requested changes
안녕하세요 다현님 :) 
전체적으로 잘해주셨는데, 한줄로 작성해놓은 코드가 너무 많아요.
한줄로 작성하는 순간 가독성은 완전 안좋다고 생각이 들어요.
한줄 코딩을 모두 가독성이 높게 작성해주세요.

아울러 테스트의 로그가 있는 순간, 그건 자동화 테스트가 아니에요.
테스트의 로그도 모두 제거해주세요 :)

2022-04-26 13:28 UTC, ksy90101 commented on pom.xml
> +		</dependency>
라이브러리를 삭제하는것도 학습해보면 좋을거 같아요.
이걸 삭제하시고 Java의 기본 기능으로 변경해주시면 좋을거 같습니다.

2022-04-26 13:28 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/console/ConsoleInput.java
> +    if(line.length() == 0) return Optional.empty();
한줄 코딩은 가독성을 침해합니다.

2022-04-26 13:28 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ConsoleController.java
> +    }
commend는 enum으로 관리해서 해당 로직들이 실행되도록 하면 어떨까요?

2022-04-26 13:28 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ListController.java
> +    else if(listType.equals("voucher")) output.printList(voucherService.getVoucherList());
한줄 코드는 가독성을 침해합니다.

2022-04-26 13:28 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +  private final String email;
name과 email은 VO로 관리하면 좋을거 같은데요.
한번 VO로 만들어 보실까요?

2022-04-26 13:28 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +  public void login() {
👍

2022-04-26 13:28 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/FixedAmountVoucher.java
> +  private static final long MAX_REDUCTION = 1_000_000L;
이정도 숫자면 long이 아니여도 될거 같은데요?

2022-04-26 13:28 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/FixedAmountVoucher.java
> +    if(MAX_REDUCTION < reduction || reduction <= 0) return false;
한줄 코딩 멈춰!!

2022-04-26 13:28 UTC, ksy90101 commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +  @Order(6)
테스트는 FIRST 원칙이 있습니다.
한번 확인해주시고, Order는 모두 제거해주세요.

2022-04-27 15:10 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +  }
그렇네요 🙊 이름 수정하겠습니다!!

2022-04-27 15:24 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +  }
validate 하는 것은 맨 처음에 생성하는 것이고, validate는 안 하는 것은 db에서 읽어올 때 사용하는 것입니다. 근데 말씀을 들어보니 안 좋은 것 같아서 따로 객체를 만들어 보겠습니다!!

2022-04-27 15:26 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/FixedAmountVoucher.java
> +    if(MAX_REDUCTION < reduction || reduction <= 0) return false;
제가 사실 한 줄 코딩이 깔끔하게 보이는 것 같아서 한 문장일 때는 많이 사용을 하는데, 가독성이 좋지 않은지 몰랐습니다 ;ㅅ; 모두 확인해서 다 수정하겠스빈다!!

2022-04-27 15:47 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/FixedAmountVoucher.java
> +  private static final long MAX_REDUCTION = 1_000_000L;
int로 변경하겠습니다!!

2022-04-29 14:26 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +  }
db의 값을 믿을수 잇을까요?
애플리케이션을 거치지 않고 db에서 직접 데이터를 넣었다고 생각해봅시다 :)

2022-04-30 03:15 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +  }
항상 DB에는 신뢰할 수 있는 값만 있다고 생각을 했는데, DB에 직접 데이터를 넣는 경우도 고려를 해야 하는군요!
수정하겠습니다!!

2022-04-30 04:33 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ConsoleController.java
> +    else if(listType.equals("voucher")) output.printList(voucherService.getVoucherList());
한줄코딩 모두 제거하겠습니다!! 🙊

2022-04-30 04:36 UTC, sdardew commented on src/main/resources/logback.xml
> +
넵!!

2022-04-30 06:23 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +    name.changeName(newName);
새로 Name 인스턴스를 생성해서 할당하는 방식으로 변경하였습니다!!

2022-04-30 06:24 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +    validateName(name);
Name에서 validate를 검사하도록 변경하였습니다!!

2022-04-30 06:25 UTC, sdardew commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +class JdbcCustomerRepositoryTest {
이건 조금만 더 공부해보고 변경하겠습니다!!

2022-04-30 10:11 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/voucher/service/VoucherService.java
> +      customerRepository.findById(customerId).isPresent()) {
exist를 사용하는 메서드를 하나 만들어서 제어했습니다!!

2022-04-30 10:24 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/PercentDiscountVoucher.java
> +    return true;
🙊
한줄 코딩 다 수정했습니다!!

2022-04-30 10:25 UTC, sdardew commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +class JdbcCustomerRepositoryTest {
이건 제가 해봐도 잘 모르겠습니다!! 조금만 더 찾아보겠습니다!!

2022-04-30 10:43 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ConsoleCommand.java
> +  }
제가 멘토님께서 원하신대로 반영한 것인지는 모르겠는데, [블로그 글](https://velog.io/@kyle/Java-Enum-%EC%82%AC%EC%9A%A9-2%ED%83%84#1--%ED%83%80%EC%9E%85%EB%B3%84%EB%A1%9C-%EB%8B%A4%EB%A5%B8-%EC%97%B0%EC%82%B0%EC%8B%9D%EC%9D%84-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EA%B2%BD%EC%9A%B0)을 참조해서 변경해 보았습니다!!

2022-05-01 05:26 UTC, ksy90101 commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +class JdbcCustomerRepositoryTest {
네. 이전에 Repository 테스트 할대 설명드렸던 방법이에요 :)

2022-05-01 05:29 UTC, ksy90101 approved these changes
2주차 미션 하시느라 고생 많으셨습니다 💯 
2주차는 이만 머지할게요~ 3주차 미션에서 봐요~

2022-05-01 05:29 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/config/DBConfig.java
> +      .type(HikariDataSource.class)
이걸 왜 써야 할지 아시나요?

2022-05-01 05:29 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ConsoleCommandV1.java
> +  }
함수형 인터페이스로 깔끔하게 한번 작성해보세요.

2022-05-01 05:29 UTC, merged

2022-05-01 09:36 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ConsoleCommandV1.java
> +  }
아 V2에 함수형 인터페이스가 반영된 것을 확인하실 수 있습니다. 말씀하신 것은 이전의 코드입니다

2022-05-01 10:42 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/config/DBConfig.java
> +      .type(HikariDataSource.class)
실제 데이터베이스 연결을 위해서 따로 설정하는 걸로 알고 있습니다