[2C-남득윤] 바우처 관리 애플리케이션 메뉴 별 출력 및 로직 실행
prgrms-be-devcourse/springboot-basic pull request #251
Opened 2022-04-17 16:44 UTC by ndy2

## ✅ PR 포인트
이벤트 스토밍을 통해 도메인 지식이 통일되는 좋은 경험을 하였습니다. 감사합니다 !!

운이 좋게도(?) 지난 PR 이후 리뷰에 대한 반영외에는 도메인 파트를 진행하지 않아 `app.menu` 패키지를 주로 진행한 PR을 요청하게 되었습니다.

## ✅ 피드백 반영사항
지난 PR은 주로 도메인 영역에 관한 진행이었으며 피드백에 따라 크게 변경된 부분은 
리포지토리별 ID 생성에 서플라이어를 제거하고 메모리 리포지토리는 기본적으로 UUID를 아이디로 하는 맵을 가지고 메모리 리포지토리에서 `UUID.random( )`으로 아이디를 생성하도록 하였습니다.

또한 주문 엔티티의 빌더를 제거하였습니다. 다음 PR 에는 엔티티 자체가 제거될 예정입니다.

## ✅ 메뉴 구현 방식
지난 PR에서 `VoucherApp`이 `VoucherAppRunner`를 가지고 루프에 해당하는 로직을 계속 돌리는 방식 까지 템플릿을 구현하였었습니다.

하위 메뉴들을 구현하면서 `VoucherAppRunner`도 일종의 `Menu`처럼 취급하는 것이 좋을 것 같아 `MainMenu`로 이름을 변경하였습니다. `MainMenu`, `CreateVoucherMenu`는 하위 메뉴를 가지는 메뉴로써 하위 메뉴를 리스트 타입으로 필드에 가집니다. 

메뉴를 일종의 트리처럼 취급하는 방식으로 구현하였습니다.
menu.main 패키지 아래 부터 각 패키지가 하나의 메뉴를 담당하게 하였으며 하위 메뉴를 가지는 경우 Choice (선택)을 enum으로 가지게 하였습니다. enum 으로 메뉴의 타입을 제네릭으로 제한해 두니까 스프링이 기가막히게 `MainMenu`, `CreateVoucherMenu` 에 하위 메뉴에 대한 List 를 주입해주어서 기분이 좋았습니다.

구현에서 찜찜한점이 한가지있습니다.
`MainMenu` 는 상위 메뉴가 없지만 메뉴 추상 클래스를 확장하게 하기 위해 더미 enum으로 써 NoChoice 를 하나 만들어 꼽아주었습니다. 이런식의 구현이 괜찮을까요?

2022-04-19 11:06 UTC, woogiekim requested changes
코멘트 확인해주시고 궁금하신 부분은 DM 주시면 좋을거같습니다.

특히, 메뉴 부분은 어떤 생각이었던건지 조금 궁금해서 이야기를 해보는게 좋을거같습니다.

2022-04-19 11:06 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/app/menu/main/MainMenuTest.java
> +            String input = "나는 Illegal 인풋 ";
invalidInput 이런 이름으로 해주는게 더 좋지 않았을까 생각합니다.

2022-04-19 11:06 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/domain/common/repository/MemoryRepositoryTest.java
> +                    .containsExactlyInAnyOrder(order1.getCustomerId(), order2.getCustomerId());
assertThat 은 extracting 이라는 메소드도 지원을 해주고 있습니다.
조사해보고 적용해보시는건 어떨까요?

2022-04-19 11:17 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/order/entity/Order.java
>      }
앗 이부분은 지난 PR에서 얘기 하신 부분인데 반영하는 것을 깜빡하였습니다.

2022-04-19 11:17 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/order/entity/Order.java
> +    }
아 그러네요... 반영하겠습니다

2022-04-20 09:37 UTC, ndy2 commented
SpringShell을 적용하는 방식으로 View 부분을 변경하였습니다.
Exit, Create, List 명령에 해당하는 세가지 @ShellMethod 를 각각의 @ShellComponent 에 구현하였습니다.

또한 Order 엔티티의 정적 메서드를 수정하고 테스트를 수정하였습니다.

2022-04-20 11:24 UTC, woogiekim approved these changes
바꿔야할 양이 많았을거같은데,

소감이 어땠는지 궁금해지네요

DM 으로 이야기를 좀 해보는게 어떤가 싶네요!

변경전 리뷰내용대로 DIP, Command Pattern 등에 대해서 조사해보셨을거같은데 그 부분도 좀 궁금하네요

2022-04-20 11:25 UTC, merged