[2기-C]방은혁 SpringBoot Part2 Weekly Mission 코드리뷰 요청합니다!
prgrms-be-devcourse/springboot-basic pull request #261
Opened 2022-04-19 15:44 UTC by hyuk0309

안녕하세요 😃

이번 주 미션 코드리뷰 부탁드려요! 열심히 했습니다. 👨‍💻

<br/>

## 📌 과제 설명

첫 번째 미션은 메모리를 이용했다면, 이번 미션은 DB를 이용한 바우처 관리 애플리케이션을 만들었어요.

<br/>

## 👩‍💻 요구 사항과 구현 내용

**(기본)** **바우처 관리 애플리케이션**

- [x] 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
  - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
  - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
  - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요. **(저는 Assertj를 이용했습니다!)**
- [x] 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
  - customers 테이블 정의 및 추가
  - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현 **(저는 회원 저장, 전체 조회 기능을 만들었습니다.)**
- [x] (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
  - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
  - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
  - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x] 특정 고객에게 바우처를 할당할 수 있습니다.
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

**table 설계**

![table](https://user-images.githubusercontent.com/29492667/163669922-74a7bade-48a8-4376-b106-cddd426db935.png)

<br/>

## ✅ PR 포인트 & 궁금한 점 

1. mock 객체를 이용한 상태 검증 테스트를 처음 작성해 봤어요. 그래서 제가 만든 테스트에 대한 피드백을 받고 싶어요.

2. 예외 처리에 대한 고민 끝에 저는 예외를 비니지스 로직에서 발생하는 예외와, 시스템적으로 발생하는 예외를 나눠서 처리했어요. 멘토님께서 이 부분에 대해 어떻게 생각하시나요? 더 좋은 방법이 있을까요?

3. 이번 과제에서 도메인을 크게 customer, voucher로 나눠서 생각했어요. 각 도메인에 필요한 로직은 도메인별로 나눠서 작성하면 해결할 수 있었지만, 복잡한 기능은 도메인이 섞여 어디에 관련 비지니스 로직을 작성해야 하는지 고민했어요. 멘토님께서는 여러 가지 도메인이 섞인 로직을 작성해야 하면 해당 로직을 어디에 작성하시나요? 예를 들어 customer와 voucher 도메인이 협력하는 기능을 멘토님께서는 customer 도메인에 작성하시나요? 아니면 voucher 도메인에 작성하시나요?

4. 이 외에도 부족한 부분이 있으면 피드백 부탁드립니다! 

감사합니다! 🙇

2022-04-21 14:33 UTC, ksy90101 requested changes
남기다 보니 많이 남긴거 같아서, 1차 리뷰정도만 남길게요.
보시면서 수정할게 더 보인다면 더 수정해주셔도 됩니다 :)

2022-04-21 14:33 UTC, ksy90101 commented on HELP.md
> +* The original package name 'org.prgrms.springboot-basic' is invalid and this project uses 'org.prgrms.springbootbasic' instead.
이 파일은 필요 없어보여요 :) 삭제하면 어떨까요?

2022-04-21 14:33 UTC, ksy90101 commented on pom.xml
> +		</dependency>
라이브러리를 제거하는 연습도 해봤으면 좋겠는데요.
혹시 이 라이브러리를 제거하고 기본 Java기능으로 한번 바꿔보시면 어떨까요?

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/aop/LoggingAspect.java
> +    @Around("org.prgrms.springbootbasic.aop.LoggingAspect.allVoucherApplicationMethodPointcut()")
```suggestion
    public void allVoucherApplicationMethodPointcut() {
    }

@Around("org.prgrms.springbootbasic.aop.LoggingAspect.allVoucherApplicationMethodPointcut()")
```

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/aop/LoggingAspect.java
> +public class LoggingAspect {
오 이거 학습에서 나온건가요? 좋은거 만드셧군요!?

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +    private final VoucherService voucherService;
상수와 필드는 분리하는게 어떨까요!? 개행으로요

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +        } while (isProcessed);
👍

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/dto/VoucherDTO.java
> +    public VoucherDTO(Voucher voucher) {
DTO에 voucher를 넘기는 어떤 느낌일까요?
둘이 너무 종속이 되는거 같은데 어떻게 생각하시나요?

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/Customer.java
> +    public void changeName(String newName) {
오호 👍

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/Customer.java
> +    private String name;
email과 name은 각자의 정책을 가지고 있을거 같은데요.
이걸 VO로 만들어서 관리해보면 어떠세요? 정책을 확인하시고 validate같은것들도 해주시구요.

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/FixedAmountVoucher.java
> +    public static final int MAX_RANGE = 100000;
테스트 코드를 위해 접근제어자를 수정하는게 맞을까요?

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/FixedAmountVoucher.java
> +            throw new AmountRangeMaxException();
항상 예외메시지를 작성해주시는게 좋습니다 :)

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    }
이건 왜 있을까요?
뭔가 이상하네요...

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    public Optional<UUID> getCustomerId() {
Optional로 처리하신 이유가 무엇일까요?

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    }
이건 그냥 퀴즈인데요.
이걸 왜 두개 한번에 구현해야 하는지 아시나요?

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/customer/CustomerDBConstString.java
> +    public static final String UPDATE_BY_ID_SQL = "update customers set name = ? where customer_id = UUID_TO_BIN(?)";
너무 좋은걸 사용해주신거 같지만, 이렇게 하면 IDE의 장점을 못느낄거 같아요. 기본적으로 IDE에서 SQL문을 인식하거든요. 근데 이렇게 하면 인식하지 못할거 같아요.
아울러 SQL은 예약어는 대문자로 작성해주셔야 뭔가 가독성이 더 높아질꺼 같아요.

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/customer/JdbcCustomerRepository.java
> +    private final RowMapper<Customer> mapToCustomer = (resultSet, i) -> {
상수와 필드는 분리해주세요~

2022-04-21 14:33 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/repository/customer/JdbcCustomerRepository.java
> +    public UUID changeName(Customer customer) {
updateName이 더 좋지 않을까요!?

2022-04-23 04:59 UTC, hyuk0309 commented on pom.xml
> +		</dependency>
넵! 리펙토링 해보겠습니다!

2022-04-23 07:45 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/aop/LoggingAspect.java
> +public class LoggingAspect {
넵! 강의에서 배운 내용 적용해 봤습니다!

2022-04-23 08:09 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/dto/VoucherDTO.java
> +    public VoucherDTO(Voucher voucher) {
Entity에서 DTO 변환 작업에 대한 책임을 DTO에게 주고 싶어 이렇게 작성했습니다. 
하지만 멘토님의 말씀을 생각해보니 요구사항이 바뀌어 엔티티 변경이 일어나면 관련없는 DTO까지 변경해야 하는 상황이 생기겠군요...😭 
둘을 분리해 보겠습니다!

2022-04-23 08:44 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/Customer.java
> +    private String name;
넵! 객체지향 생활 체조의 '모든 원시값과 문자열을 포장한다' 같네요! 
좋은 피드백 감사합니다~ 🙏

2022-04-23 09:18 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/dto/VoucherDTO.java
> +    public VoucherDTO(Voucher voucher) {
Converter와 같은 것이 있으면 좋을수도 있겠어요 :) 
아니면 Service에서 해줘도 좋구요.ㅎㅎ

2022-04-23 09:24 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/FixedAmountVoucher.java
> +    public static final int MAX_RANGE = 100000;
이 부분은 textIO를 사용하는 View 클래스에서 입력 검증을 위해 public으로 열어 두었어요!

그런데 생각해 보니 View 쪽에서 비지니스 관련 검증을 수행하는 게 좋은 것 같지 않네요! 나중에 비지니스 요구사항이 변하면 View까지 수정해야 할 것 같아요. 이는 private으로 두고 View에서는 형식 관련 검증만 해주는 게 맞는 것 같습니다!

2022-04-23 09:59 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    }
instanceOf 대신 다형성을 이용하기 위해 작성했습니다. 
이 부분은 추상 메서드로 작성할까 했는데, 추상 메서드로 작성하면 PercentDiscountVoucher에 필요없는 isFixed, FixedAmountVoucher에 필요없는 isPercent 메서드를 오버라이드 해야해서 일반 메서드로 정의하고, 필요한 자식에서만 오버라이드 했습니다. 
저도 뭔가 이상하긴 한데, 중복이 일어나도 추상 메서드로 구현하는게 맞을까요? 🙋‍♂️

2022-04-23 10:02 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    public Optional<UUID> getCustomerId() {
Voucher는 customer에게 할당되기 전에는 customerId에 null이 들어가기 때문에, 반환시 null을 반환할 수 있어, Optional로 감싸서 반환했습니다!

2022-04-23 10:04 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    }
Set과 같은 컬렉션을 사용할 때, 내부적으로 객체의 hashCode를 이용해 같은 객체인지 판단하는 과정이 있어 equals 구현시 hashCode를 같이 구현해야 나중에 문제가 생기지 않다고 알고있습니다!

2022-04-23 10:56 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/repository/customer/JdbcCustomerRepository.java
> +    public UUID changeName(Customer customer) {
DB에서 customer가 update 되는 상황이니까 멘토님 의견이 더 좋은 것 같아요! 😀

2022-04-23 11:13 UTC, hyuk0309 commented
1차 피드백 반영했습니다! View 리팩토링 과정이 힘들었어요. ㅎㅎ
리팩토링을 하다 보니 객체간 결합도를 낮추는 게 왜 중요한지 알 것 같아요! 결합도가 높을 수록 확장성이 떨어지고, 테스트 작성도 어려운 것 같아요.

2022-04-23 14:35 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    }
저는 추상이 맞다고 생각이 드네요. :)
지금 형태도 나쁘진 않구요 ㅎㅎ

2022-04-23 14:35 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    public Optional<UUID> getCustomerId() {
null을 반환해도 나쁘지 않다고 생각이 들어요.
지금 같은 경우에서는 null이 반환되는게 이상하지 않다고 생각이 들어서요.

2022-04-23 14:37 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/entity/customer/Customer.java
> +    }
VO는 불변이 중요한데요.
이런 경우에는 새로운 객체를 넘겨주는게 좋을거 같다는 생각이 드네요.

2022-04-26 07:20 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/dto/VoucherDTO.java
> +    public VoucherDTO(Voucher voucher) {
저는 개인적으로 Converter 방식이 마음에 드네요. Converter 방식으로 수정하겠습니다!

2022-04-26 08:52 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
> +    public Optional<UUID> getCustomerId() {
생각해 보니 그런 것 같아요! 
제 생각은 getCustomerId()가 Optional의 기능을 사용하지 않고, null 체크만 해주기 때문에 굳이 비싼 Optional을 사용할 이유가 없어서 멘토님께서 피드백을 주신 것 같습니다. 혹시 멘토님도 동일한 생각이셔서 피드백을 주신 건가요?

2022-04-26 08:59 UTC, hyuk0309 commented on src/main/java/org/prgrms/springbootbasic/entity/customer/Customer.java
> +    }
제가 기본기가 부족했네요.. 😂

2022-04-26 09:08 UTC, hyuk0309 commented
2차 피드백 반영했습니다! 멘토님의 의도를 잘 파악했는지 확인 부탁드립니다!🤔

2022-05-01 05:25 UTC, ksy90101 approved these changes
은혁님도 2주차 미션하시느라 고생 많으셧습니다 💯 
이만 2주차는 머지하고 3주차 미션때 뵐께요~
피드백 남겨둔건 3주차 미션 때 적용해주세요!

2022-05-01 05:25 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherController.java
> +            logger.info("Got service exception");
사실 예외는 자동으로 log가 찍힐꺼에요.
아울러 로그 레벨이 왜 있는지 한번 알아보세요~
이런경우 info로 하는게 맞는지?
아울러 굳이 이 예외를 로그로 찍어야 할지.

2022-05-01 05:25 UTC, ksy90101 commented on src/main/java/org/prgrms/springbootbasic/controller/VoucherType.java
> +    }
toString말고 name()도 한번 알아보세요~

2022-05-01 05:26 UTC, merged