[2-C] 문정현 Spring Boot 2주차 과제 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #262
Opened 2022-04-19 15:52 UTC by y005

## 📌 과제 설명 
**기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 
#### 요구사항
- [x] 고객의 바우처 보유 정보 조회(SELECT)
- [x] 특정 바우처 보유 고객 정보 조회(JOIN)
- [x] 특정 고객에게 바우처 할당 기능(UPDATE)
- [x] 고객 보유 바우처 제거 기능(UPDATE)
#### 구현 내용
- [x] 단위테스트 작성
- [x] Customers 테이블 정의 및 추가
- [x] Vouchers 테이블 정의 및 추가
- [x] VouchersWallet 테이블 정의 및 추가
- [x] JdbcTemplate을 사용한 CustomerRepository
- [x] JdbcTemplate을 사용한 VoucherRepository (CRUD API)
- [x] JdbcTemplate을 사용한 VoucherWalletRepository

#### 실행화면
- give voucher 커맨드를 통해 고객에게 바우처를 부여할수 있다.
    ```
  >>give voucher
  Type custmer id you want to give voucher to.
  >>>90876254-1988-4f45-b296-ebbb6fedd464
  Type voucher id you want to give to customer.
  >>>34c20e5a-15e3-4c1a-a57d-5cd5e5cf3698
  ```
- take voucher 커맨드를 통해 고객이 가지고 있는 바우처를 회수할 수 있다.
    ```
  >>take voucher
  Type custmer id you want to take voucher from.
  >>>90876254-1988-4f45-b296-ebbb6fedd464
  Type voucher id you want to take from customer.
  >>>34c20e5a-15e3-4c1a-a57d-5cd5e5cf3698
    ```

- customer list 커맨드를 통해 동일한 바우처를 가진 고객 정보를 조회할 수 있다.
    ```
  >>customer list
  Type voucher id you want see customer list.
  >>>34c20e5a-15e3-4c1a-a57d-5cd5e5cf3698
  name: moon age: 20 sex: woman
    ```
- voucher list 커맨드를 통해 고객이 가진 바우처 정보를 조회할 수 있다.
  ```
  >>>voucher list
  Type customer id you want see voucher list.
  >>>90876254-1988-4f45-b296-ebbb6fedd464
  id: 34c20e5a-15e3-4c1a-a57d-5cd5e5cf3698
  type: fixed
  amount: 1000
  ```

2022-04-22 11:22 UTC, WooSungHwan requested changes
코멘트 몇자 남겼으니 확인부탁드립니다~!

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/VoucherWalletService.java
> +    VoucherWalletRepository voucherWalletRepository;
접근제어자 지정해주세요.

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/VoucherWalletService.java
> +    @Autowired
di는 하나의 방법만 사용하시는건 어떨까요. 덧붙여서 말하자면 `@Autowired` 방식은 빈 타입으로 주입해주기 때문에 스프링에서 권장하는 방식은 아니에요. 스프링에서는 생성자 주입을 권장하고 있으니 생성자 주입으로 전체 프로젝트 주입 방향을 바꿔보는건 어떠신가요.??

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/VoucherWalletService.java
> +        voucherWalletRepository.giveVoucherToCustomer(UUID.fromString(customerId), UUID.fromString(voucherId));
UUID 타입의 클래스가 빈번하게 사용되는 것 같아요. 디비에서 UUID를 호환하기 매우 힘들텐데 되도록 String 타입으로 id를 전달하고 필요한 부분에서만 UUID 타입을 활용하도록 하는건 어떨까요?

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/Customer.java
> +        return age == customer.age && Objects.equals(name, customer.name) && sex == customer.sex;
기왕 customer의 id를 두셨는데 id를 기준으로 보는건 어떠신가요?

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/Customer.java
> +        return Objects.hash(name, age, sex);
hashcode도 마찬가지로 id로 보는 건 어떨까요?

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/JdbcCustomerRepository.java
> +        }};
더블 브레이스가 안티패턴으로 알고있는데 해당 put메소드를 실행할때마다 별도의 익명클래스를 계속 생성하는걸로 알고있어요. 잘못쓰면 시스템 메모리 누수가 발생할 수 있는 패턴이라고 들었습니다.

https://kukekyakya.tistory.com/entry/double-brace-initialization?category=1022638
해당내용 한번 참조해보시고 되도록 paramMap.put()을 활용하는건 어떨까요?

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/Sex.java
> +    private static final Map<String, Sex> sexHashMap = Stream.of(values()).collect(toMap(Object::toString, (e)-> e));
Map컬렉션 타입으로 private static 변수로 두기보다는 enum의 경우 직접 선언하는 데이터의 양의 한계가 있으니 List를 탐색하는 알고리즘으로 구현하셔도 무방할 것 같습니다.

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/customer/Sex.java
> +    }
저같은 경우는

https://github.com/WooSungHwan/one-two-server/blob/master/src/main/java/com/blackdog/onetwo/domain/common/enums/BaseEnum.java

이런식으로 구현합니다ㅎㅎ

2022-04-22 11:22 UTC, WooSungHwan commented on src/main/java/com/kdt/commandLineApp/voucher/VoucherType.java
> +        }
이런 메소드 오버라이딩 활용 좋습니다 ㅎㅎ

2022-04-22 11:22 UTC, WooSungHwan commented on src/test/java/com/kdt/commandLineApp/customer/CustomerServiceTest.java
> +            var result2 =  customerService.getCustomers().get(1);
당분간 지금은 var 키워드는 피하는건 어떠실까요? 자바의 특징인 강타입이 버전이 올라가면서 다소 완화되었지만 그 부분은 강타입에서 만나는 많은 부분들을 겪고 난 결과일거에요. 지금은 어떤 타입일지 정확히 정해주는 건 어떨까요?

2022-04-23 04:39 UTC, y005 commented
피드백 주신 부분 한 가지 빼고 다 반영해놓은 상태이고 @EnableConfigurationProperties에서 pojo 형태인 프로퍼티 클래스에 프로퍼티값이 주입이 안되서(DI는 잘 되는데 안에 값이 null인 상태입니다..) 이 문제는 주말 동안 한번 찾아 보는 걸로 하겠습니다. 관련된 부분은 AppContextTest에 있습니다.

2022-05-10 04:30 UTC, merged