[2기-C] 강태산 SpringBoot Part2 Weekly Mission 코드리뷰 요청합니다.
prgrms-be-devcourse/springboot-basic pull request #271
Opened 2022-04-20 13:15 UTC by Pawer0223

# SpringBoot Part2 Weekly Mission
    
## 바우처 관리 애플리케이션
    
- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
  - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
  - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
  - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
  - customers 테이블 정의 및 추가
  - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
  - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
  - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
  - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
    
## (심화) 바우처 지갑을 만들어보세요.
    
- [x] 특정 고객에게 바우처를 할당할 수 있습니다.
  - 고객목록 조회 -> 선택
  - 바우처 목록 조회 -> 선택
  - update
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
  - voucherId가 null이 아닌 고객 조회 -> 선택
  - delete
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.
  -  바우처 목록 조회 -> 선택
  - select * from customers where voucherId = :voucherId

## ERD

<img width="541" alt="image" src="https://user-images.githubusercontent.com/26343023/164236685-da285c5d-43a2-4e69-802b-6924b499b4bc.png">

## PR 포인트 & 궁금한 점

1. Vouchers 테이블의 Discount_Policy_Id 컬럼의 값은 소스 코드의 `DiscountPolicy` Enum 에서 관리되고 있습니다. 할인 정책에 따라 Voucher가 결정되기 때문에 테이블이 아닌 Enum으로 관리하게 하였는데요.. 테이블로 분리하는 것이 더 좋을까요?

2. 행위검증에 대한 필요성을 못느껴서 대부분 테스트코드를 상태검증으로 작성했습니다.. 행위 검증을 적용하면 좋았을 만한 포인트가 있을까요 ??

3. 코드에서 눈에 띄는 안좋은 습관이나, 개선 점에 대해 가감없이 조언주시면 달게받고 개선하겠습니다. 감사합니다 !

2022-04-21 14:47 UTC, ksy90101 requested changes
패키지 구조에 대해서 조금 고민해봣으면 좋겠습니다.
https://rutgo-letsgo.tistory.com/327?category=786689
이글을 한번 읽어보시면 좋을거 같아요.
패키지 구조가 변경되면 전체적으로 많이 변경될거 같으니 간단하게 피드백 남겼습니다 💯

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/pom.xml
>  			<groupId>org.beryx</groupId>
라이브러리를 삭제하는것도 한번 해볼까요!?
삭제하고 Java 기본 기능으로 한번 바꿔보시죠~

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Field.java
> +}
```suggestion
    public static final String DISCOUNT_POLICY_ID_CAMEL = "discountPolicyId";
}
```

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Field.java
> +public class Field {
너무 잘 관리해주셨는데요.
이렇게 하면 도메인이 100개가 되면 여기에 다 넣으면 엄청 거대해질꺼 같은데요.
저는 이걸 enum으로 관리하는게 더 좋을수도 있다고 생각해요. (개인적으로 enum 약쟁이 같네요 ㅋㅋㅋ)

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Message.java
>  public class Message {
이것도 너무 한쪽에 몰려있다 보니, 분리해보면 어떠세요?

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/customer/Customer.java
> +        this.voucherId = voucherId;
setter라는 단어보다는 update나 change가 더 좋을거 같아요!

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/engine/MenuStrategy.java
> +            }
고드만 읽어도 이해가 되는데요 주석은 필요 없어보여요 :)

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/voucher/repository/FileVoucherRepository.java
> +                .filter((e) -> (e.getDiscountPolicyId() == discountPolicyId) && (e.getDiscountAmount() == discountAmount))
e라는 단어보다 더 의미잇는 단어를 사용해볼까요?

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/test/java/com/mountain/voucherApp/customer/CustomerNamedJdbcRepositoryTest.java
> +    }
assertAll을 한번 공부해볼까요?

2022-04-21 14:47 UTC, ksy90101 commented on voucherApp/src/test/java/com/mountain/voucherApp/utils/MenuUtilTest.java
> +    public void 타입_확인함수_테스트(int ordinal, boolean expected1)
여긴 DisplayName을 사용하지 않았군요!?

2022-04-24 19:25 UTC, Pawer0223 commented on voucherApp/pom.xml
>  			<groupId>org.beryx</groupId>
아직 AOP의 필요성을 못느껴서 의존성만 추가하고 적용한 코드가 존재하지 않습니다.
추후 AOP적용시 라이브러리를 사용하지 않고 적용해보겠습니다 !

2022-04-24 19:26 UTC, Pawer0223 commented on voucherApp/pom.xml
>  			<groupId>org.beryx</groupId>
아직 AOP의 필요성을 못느껴서 의존성만 추가하고 적용한 코드가 존재하지 않습니다.
추후 AOP적용시 라이브러리를 사용하지 않고 적용해보겠습니다 !

2022-04-24 19:35 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Field.java
> +public class Field {
말씀처럼 Enum이 더 깔끔하고 좋을것 같습니다. 변경했습니다. 피드백 감사합니다 !

2022-04-24 19:42 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Message.java
>  public class Message {
콘솔에 출력되는 ProgramMessage와 에러에 관한 ErrorMessage 2개로 분리해보았습니다 !

2022-04-24 19:44 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/customer/Customer.java
> +    private final String email;
email의 경우 매핑 테이블의 unique key로 설정되어 있기 때문에 별도 validate를 수행하지 않았습니다.
name의 경우 CustomerName이름의 VO로 만들어서 변경해보았습니다 !

2022-04-24 19:46 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/customer/Customer.java
> +        this.voucherId = voucherId;
해당 메서드는 로직이 조금 변경되면서 사용되지 않아 제거했습니다. 추후 네이밍룰에 한번 더 신경쓰겠습니다

2022-04-24 20:00 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Number.java
>  public class Number {
중복되서 사용될 수 있다고 생각되는 의미의 숫자를 상수화해서 사용하려고 했습니다. 
-1과 같이 특정 로직에서만 의미를 부여한 값은 NOT_EXIST와 같이 구분했고 
0이나 0.01은 범용적으로 사용될 수 있다고 생각하여 ZERO와 같이 네이밍을 붙였습니다.
불필요한 분리일까요 ?

2022-04-24 20:07 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Query.java
> +public class Query {
상수화 하지 않았을 때 Java코드에서 예약어가 구분되어 가독성이 좋아지는것 같습니다 !
혹시 가독성 이외에 또 다른 이점이 있을까요 ?

2022-04-24 20:28 UTC, Pawer0223 commented on voucherApp/src/test/java/com/mountain/voucherApp/customer/CustomerNamedJdbcRepositoryTest.java
> +    }
여러개의 테스트를 하나로 인식해서 처리할 수 있고, 에러 발생시 더 명시적으로 메시지가 출력되어 유용한것 같습니다.
앞으로도 assertAll을 적절히 활용해보겠습니다. 감사합니다 !
- [참조](https://stackoverflow.com/questions/40796756/assertall-vs-multiple-assertions-in-junit5)

2022-04-25 14:46 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Query.java
> +public class Query {
아뇨 가독성이라긴 보단, 예약어 구분이 중요한거였어요.
어차피 Bean이기 떄문에 SQL 정도는 괜찮을꺼에요 :)

2022-04-25 14:48 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/customer/Customer.java
> +    private final String email;
email의 unique key가 문제가 아니라, ks1@na 이런식으로 이메일이 들어오면 잘못된거 아닌가요?ㅋㅋ

2022-04-25 14:48 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Number.java
>  public class Number {
상수화를 하는건 좋지만, 각 필요한 곳에 넣는것이 더 의미있을수 있을거 같아요.
각 객체에 따라 0, 1 같은 값들은 다른 의미로 쓰일수 있으니깐요

2022-04-25 17:25 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/constants/Number.java
>  public class Number {
그럴수 있겠네요.. 피드백 감사합니다 !
상수관리하는 클래스를 JdbcResult와 VoucherConstant로 분리해서 보완해보았습니다 !

2022-05-01 08:26 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/adapter/in/console/ConsoleController.java
> +    private final InputConsole inputConsole;
```suggestion
    private static final Logger log = LoggerFactory.getLogger(ConsoleController.class);
    private static final int NOT_EXIST_DATA_NUMBER = -1;
    
    private final InputConsole inputConsole;
```

개행으로 상수와 필드를 구분하면 더 좋습니다 :)

2022-05-01 08:27 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/adapter/in/console/ConsoleController.java
> +    public void create() throws NumberFormatException {
NumberFormatExcpetion은 Catch해서 예외를 던져주세요.

2022-05-01 08:27 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/adapter/in/console/ConsoleController.java
> +    public void showVoucherList() {
```suggestion
        }
    }
    
    @Override
    public void showVoucherList() {
```

2022-05-01 08:33 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/adapter/out/persistence/customer/CustomerNamedJdbcRepository.java
> +                    "select * from customers WHERE email = :email",
예약어는 대문자로 사용하는게 좋을거 같아요 :)

2022-05-01 08:33 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/adapter/out/persistence/voucher/FileVoucherRepository.java
> +    public Optional<VoucherEntity> findByPolicyIdAndDiscountAmount(int discountPolicyId, long discountAmount) {
```suggestion
    }

    @Override
    public Optional<VoucherEntity> findByPolicyIdAndDiscountAmount(int discountPolicyId, long discountAmount) {
```

2022-05-01 08:34 UTC, ksy90101 commented on voucherApp/src/main/java/com/mountain/voucherApp/domain/vo/CustomerName.java
> +        }
validate는 따로 메서드로 빼는게 좋을거 같아요.
아울러 Runtime이 아니라 더 의미있는 예외를 사용해주세요.

2022-05-01 08:35 UTC, ksy90101 approved these changes
3주차때 5layer로 바꿔주시면 좋으럭 같아요.
3주차때 뵐께요~

2022-05-01 08:35 UTC, merged

2022-05-07 21:19 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/adapter/in/console/ConsoleController.java
> +    public void create() throws NumberFormatException {
try-catch로 변경했습니다 !

2022-05-07 21:20 UTC, Pawer0223 commented on voucherApp/src/main/java/com/mountain/voucherApp/domain/vo/CustomerName.java
> +        }
vo에서 validate 메서드 분리 후, Exception도 명시적으로 변경했습니다 !