[2기-C] SpringBootWeek2 과제 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #296
Opened 2022-04-22 11:44 UTC by wisehero

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
        - voucher_id, voucher_Type, discount_amount, discount_percent
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.
## ✅ 피드백 반영사항  

- 불필요한 공백을 제거하고 접근 제어자를 빼먹은 것을 추가했습니다.
- if문 조건 분기가 많은 것을 전략패턴으로 전환하였습니다.
- Repository 테스트코드를 추가했습니다. 
- 매직넘버를 제거했습니다.

## ✅ PR 포인트 & 궁금한 점 

전략패턴을 Map으로 구현했는데 이렇게 해도 맞는 방식인지 궁금합니다.!

2022-04-27 13:59 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/Console.java
> +public class Console implements Input, Output {
Input과 Output을 분리해볼까요?

2022-04-27 13:59 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/CreateCommandStrategy.java
> +    private final Scanner scanner = new Scanner(System.in);
입력은 Input 객체에 있어야 하지 않을까요?

2022-04-27 14:00 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/CreateCommandStrategy.java
> +    private final CustomerRepository customerRepository;
Repository가 여기 있는게 맞을까요?

2022-04-27 14:00 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/user/Customer.java
> +    private final String email;
name과 Email을 한번 VO로 만드는 연습을 해볼까요?

2022-04-27 14:00 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/voucher/FixedAmountVoucher.java
> +    private final int amount;
```suggestion
public class FixedAmountVoucher extends Voucher {

    private final int amount;
```

2022-04-28 12:36 UTC, wisehero commented on src/main/java/org/programmers/kdtspring/ConsoleIO/Console.java
> +public class Console implements Input, Output {
@ksy90101 콘솔이 2개의 인터페이스를 구현하지말고 각각 구현하라는 말씀으로 이해한게 맞을까용??

2022-04-28 12:37 UTC, wisehero commented on src/main/java/org/programmers/kdtspring/repository/voucher/FileVoucherRepository.java
> +//public class FileVoucherRepository implements VoucherRepository {
@ksy90101 exception 처리때문에 잠시 주석처리했었다가 풀었는데 깜빡했네요 피드백 주신내용 수정하고 다시 보낼 때 풀겠습니다!

2022-04-29 06:46 UTC, wisehero commented on src/main/java/org/programmers/kdtspring/ConsoleIO/ListCommandStrategy.java
> +        System.out.println("===== 바우처 리스트 ======");
@ksy90101  맞습니다!

2022-04-29 14:27 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/Console.java
> +public class Console implements Input, Output {
네네 맞아요.

2022-04-29 14:49 UTC, ksy90101 requested changes
간단한 피드백 남겼으니 확인해주세요~

2022-04-29 14:49 UTC, ksy90101 commented on .gitignore
> +/.idea/
gitignore에 이 파일만 필요할까요?

2022-04-29 14:49 UTC, ksy90101 commented on HELP.md
> +# Read Me First
ㅇㅣ 파일은 필요 없습니다 :)

2022-04-29 14:49 UTC, ksy90101 commented on pom.xml
> +        <dependency>
```suggestion
        </dependency>

        <dependency>
```

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/CommandType.java
> +    EXIT,
```suggestion
package org.programmers.kdtspring.ConsoleIO;

public enum CommandType {
    EXIT,
```

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/Console.java
> +
```suggestion
        this.voucherRepository = voucherRepository;
        this.blackListUserRepository = blackListUserRepository;
    }

    private final Scanner scanner = new Scanner(System.in);

```

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/ConsoleInput.java
> +public class ConsoleInput implements Input {
Input은 View라고 생각하셔야 합니다.
여기에는 단순히 입력을 받는것만 있어야 하는거에요.
로직이 들어가면 안되는거죠.
프론트엔드라고 생각해보세요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/ConsoleOutput.java
> +    }
Controller에서 인자로 받아서 List로 foreach를 돌려야 할꺼 같아요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/ConsoleOutput.java
> +    }
필요없는거 같은데요?

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/ConsoleIO/ListVoucherForCustomer.java
> +    private final CustomerService customerService;
```suggestion
public class ListVoucherForCustomer implements CommandStrategy {

    private final CustomerService customerService;
```

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/VoucherManagement.java
> +    private Map<String, CommandStrategy> commandStrategy = new HashMap<>();
어차피 상태가 없으니깐 static fianl로 하고, static {}을 사용해서 초기화 하면 되지 않을까요?

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/VoucherManagement.java
> +        commandStrategy.put("listForCustomer", new ListVoucherForCustomer(input, output, customerService));
enum으로 관리하는것도 방법이겠네요. key를

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/user/BlackListedUser.java
> +    private final String userName;
그러면 여기서 동일하게 Vo로 Name을 사용하면 되지 않을까요?

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/user/Customer.java
> +    private Name name;
validateName(name);를 Vo에서 하라는 이야기입니다.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/user/Customer.java
> +        this.lastLoginAt = lastLoginAt;
이 값은 무조건 있어야 하겠는데요?
차라리 기본값으로 현재 시간을 넣어두는것도 좋을거 같아요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/user/Email.java
> +    private final String email;
email도 validate가 필요하겟는데요?
marco@gr 이렇게 들어오면 이메일이 아니지 않나요?

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/voucher/PercentDiscountVoucher.java
> +    private final String voucherType;
```suggestion
    private static final int HUNDRED = 100;
    
    private final int percent;
    private final String voucherType;
```

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/entity/voucher/PercentDiscountVoucher.java
> +        return this.percent;
```suggestion
        return percent;
```

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/repository/user/CustomerJdbcRepository.java
> +    public Customer save(Customer customer) {
save라는 단어는 insert와 update가 둘다될때 많이 사용합니다.
지금은 insert 단어가 더 어울릴거 같아요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/repository/user/CustomerJdbcRepository.java
> +            throw new RuntimeException("Noting was inserted");
더 의미잇는 걸 사용해보면 어떨까요?

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/repository/user/CustomerJdbcRepository.java
> +        return jdbcTemplate.query("select * from customers", customerRowMapper);
예약어은 최대한 대문자로 쓰는게 가독성 더 높은거 같습니다.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/repository/voucher/FileVoucherRepository.java
> +    }
구현해주세요!!
아니면 예외를 던져주세요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/repository/voucher/MemoryVoucherRepository.java
> +    private static final Logger logger = LoggerFactory.getLogger(MemoryVoucherRepository.class);
상수는 무조건 위에 써주세요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/repository/voucher/MemoryVoucherRepository.java
> +    }
이거 다 구현가능할거 같아요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/repository/voucher/SQLString.java
> +public class SQLString {
이렇게 하는게 의미가 없어요.

2022-04-29 14:49 UTC, ksy90101 commented on src/main/java/org/programmers/kdtspring/service/CustomerService.java
> +    public List<Customer> getAllCustomers() {
@Transaction(readOnly=true)라는 키워드를 찾아보셔서 적용해주세요.

2022-05-07 17:22 UTC, merged