[2기-C]이한주 SpringBoot Part2 Weekly Mission 코드리뷰 요청합니다.
prgrms-be-devcourse/springboot-basic pull request #307
Opened 2022-04-22 20:19 UTC by yanJuicy

## 📌 과제 설명 
- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

## 👩‍💻 요구 사항과 구현 내용 
1. Console Output Customer List 파라미터 출력 기능 추가
-> ConsoleOutput 인터페이스와 구현체에 List<Customer> 파라미터를 출력하는 메소드 추가

2. JdbcTemplate을 활용한 customer 관리
-> Customer 모델, Customer 서비스, Jdbc Template을 이용한 CustomerRepository 추가

3. Customer 관련 명령어에 대한 전략 추가
-> CommnadType Enum 클래스에 Customer 관련 명령어 추가 및 Customer 명령 관련 Command 클래스 추가

4. Customer 관련 명령 실행 코드 추가
-> CommandLineApplicaion 클래스 내에 Customer 관련 명령 분기 추가

5. Voucher 클래스 관련 CRUD 기능을 가진 JdbcRepository 추가
-> JdbcTemplate을 이용해 Voucher를 저장하는 Repository 클래스 추가

## ✅ PR 포인트 & 궁금한 점 
1. 테스트 코드가 부족합니다. 공부하고 계속 추가하겠습니다.
2. 콘솔에서 명령 입력을 전략 패턴을 이용해서 만들어봤는데, 한 명령에 한 클래스씩 만들어서 클래스 수가 많아졌는데, 괜찮은건가요?

![image](https://user-images.githubusercontent.com/43159295/164787500-a93d169f-2df6-4a06-ad82-0df6f55f6b37.png)

3. 저는 fixed_voucher, percent_voucher 따로 테이블을 만들었는데 하나로 합치는게 더 좋을까요?
![image](https://user-images.githubusercontent.com/43159295/164787156-f6eddf82-3c4b-4a3e-bb6e-f163a729801b.png)
![image](https://user-images.githubusercontent.com/43159295/164787186-b7139dca-8591-4f9c-a04e-60d66cc5e0c7.png)

2022-04-23 09:09 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니, 확인해주시면 감사하겠습니다 :)
고생 많으셨어요~ 💯

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/ApplicationController.java
> +        }
이 로직이 여기 있는게 맞을까요?
따로 객체를 만들어서 처리하면 어떨까요?

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +                break;
enum에서 각 Strategy에 대한 객체를 내려주게 하면 되지 않을까요?

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +    }
이건 output에 있어야 할 로직이네요 :)

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/customer/CustomerFindAllCommand.java
> +    private final ConsoleOutput consoleOutput = new Out();
차후 확장성이 떨어질거 같아요. IoC와 DI를 왜 쓰는지 한번 알아볼까요?

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/voucher/CreateVoucherCommand.java
> +    private final JdbcVoucherService voucherService;
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(CommandStrategy.class);
    
    private final ConsoleInput console = new In();
    private final JdbcVoucherService voucherService;

```

상수와 필드는 개행으로 구분해주는게 가독성이 더 높습니다.

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/config/AppConfig.java
> +public class AppConfig {
여기서 Bean을 관리하는것도 방법이겟네요?

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/model/Customer.java
> +    private final String email;
name와 email은 validate가 있을거 같은데요.해당 부분을 VO로 뺴서 해보면 어떨까요?

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/repository/JdbcTemplateCustomerRepository.java
> +                "insert into customers(customer_id, name, email, last_login_at, created_at) " +
SQL의 예약어는 대문자로 작성하면 더 가독성이 높아질거 같아요 :

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/service/CustomerService.java
> +    public Customer insert(Customer customer) {
이건 제 개인적인 취향인데요. insert보단 create를 많이 사용하는 편이에요.
create가 더 직관적인 단어같다는 생각이 들어서요 ㅎㅎ

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/VoucherType.java
> +        }
이렇게 하는게 아니라 FIXED, PERCENT에 인자로 줘서 내려주게 하는게 더 좋지 않을까요?

2022-04-23 09:09 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/FileVoucherRepository.java
> +    private static Map<UUID, Voucher> vouchers = new ConcurrentHashMap<>();
final로 불변을 유지하는게 어떨까요?

2022-04-23 09:09 UTC, ksy90101 commented on src/test/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/JdbcTemplateVoucherRepositoryTest.java
> +class JdbcTemplateVoucherRepositoryTest {
👍

2022-04-25 19:45 UTC, yanJuicy commented
피드백 반영했습니다.

2022-04-29 14:40 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/CommandLineApplication.java
> +                break;
enum에서 객체를 내려주도록 바꿔봤습니다.

2022-05-01 05:19 UTC, ksy90101 approved these changes
한주님 2주차 미션도 고생 많으셨습니다 💯 
간단한 피드백을 좀 더 남겼는데, 이건 3주차 미션에 적용해주세요~
3주차 미션때 봐요~

2022-05-01 05:19 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/config/JdbcConfig.java
> +        datasource.setMinimumIdle(100);
이 두개의 의미를 아시나요?

2022-05-01 05:19 UTC, merged

2022-05-03 08:11 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/config/JdbcConfig.java
> +        datasource.setMinimumIdle(100);
커넥션 풀에 최대 커넥션 1000개를 가질 수 있고, 커넥션 100개를 최소 유지한다는 의미입니다.