2p/#2 midas
prgrms-be-devcourse/springboot-basic pull request #309
Opened 2022-04-23 08:30 UTC by midasWorld

# [과제] 스프링 Part2

## 📌 과제 설명

## SpringBoot Part2 Weekly Mission

### (기본) 바우처 관리 애플리케이션

- 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요. - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요. - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현) - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
- 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.

### (심화) 바우처 지갑을 만들어보세요.

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용

- CommandLineRunner에서 구현하고 필요한 클래스만 생성만하고, 단위테스트와 심화과정 제외하고 작성하였습니다.
- Customer 변경
    - 고객 등급(CustomerGrade)을 추가하였습니다.
    - 기존 BlackListCustomer → Customer 이름 변경, 블랙리스트 조회용 메서드를 따로 추가했습니다.
    - CustomerRepository Interface를 생성하고, JdbcCustomerRepository 를 추가하였습니다.
- CommandLineRunner
    - Application에서 VoucherService, CustomerService 빈을 주입받도록 변경하였습니다.(생성자 변경)
    - 각 command 구문을 메서드로 분리하였습니다.
    - while문의 command - switch 문을 람다식으로 변경하였습니다.
- Voucher 변경
    - update, delete 기능을 추가하였습니다.
- 그 외
    - main 클래스에 `@SpringBootApplication`를 추가했습니다.
    - schema.sql 생성 → customer, voucher 테이블 정의 및 샘플 데이터 Insert 구문 추가
    - Jdbc, mysql 라이브러리 추가 → 빈 등록 & application.yml에 데이터베이스 설정 정보 추가

## ✅ PR 포인트 & 궁금한 점
- 구조만 올리라고 말씀하신게 이게 맞는건지 궁금합니다. (Jdbc, mysql 설정부분들은 모두 제외하고 올리는게 맞을까요?)
- 1주차 때 말씀해 주신부분들 중에 하나를 제외하고 수정을 나름 하긴 했는데, while문의 조건식 부분에서 이렇게 하는 게 맞는건지 궁급합니다.
(try-catch 부분은 좋은 방법이 생각이 나지 않아서, 더 찾아보고 한번 더 생각해보겠습니다. 😭)

2022-04-23 09:27 UTC, Jo-GyuHyeon requested changes
고생하셨습니다. 
구조뿐만아니라 1주차 내용도 함께 변경을 하셨군요? 주로 네이밍 위주로 한번더 고민 해주시면 좋을 것 같습니다.

```
구조적으로만 등록할때는 Jdbc 빈이나 schema.sql 과 같은 이런 설정부분들도 제외를 하는게 맞는건지 잘 모르겠습니다.. 😢
```
* 설정관련은 함께 포함해도 괜찮은 같습니다. :) 

```
1주차 때 말씀해 주신부분들 중에 하나를 제외하고 수정을 나름 하긴 했는데, while문의 조건식 부분에서 이렇게 하는 게 맞는건지 궁급합니다.
```
* 기본적으로 무한루프를 탈출 하셨군요? 넵!! 좋습니다. 

```
(try-catch 부분은 좋은 방법이 생각이 나지 않아서, 더 찾아보고 한번 더 생각해보겠습니다. 😭)
```
* 넵 조금 고민이 필요해 보입니다. 모든 영역이 try 로 감싸져 있을 필요가 없습니다.

2022-04-23 09:27 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/io/OutputConsole.java
> +                "Type black-list to list all customer in black-list."
Command 가 늘어남에따라 OuputConsole 이 영향이 많이 가고 있습니다.
여기에 대해 어떻게 생각하시나요?

2022-04-23 09:27 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/model/customer/CustomerGrade.java
> +}
Customer 의 내부 로 옮기는 건 어떻게 생각하나요??

2022-04-23 09:27 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/service/voucher/VoucherService.java
> +    public void deleteVoucher(UUID voucherId) {
이미 바우처 서비스이기에 메서드 네이밍에서는 바우처를 빼도 괜찮지 않을까요?
persion.personName 이라고 하지 않는것 처럼 VoucherService.delete() 라고 표현해도 충분히 이해가 될것 같습니다.

2022-04-23 09:27 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/io/Output.java
> +    void printVoucherDeleteSuccess();
print 의 기능이 새롭게 달라지지 않는다고 생각합니다. 이련 경우에 외부로 부터 출력 할 내용을 주입 받는 것이 적절하다고 생각이 듭니다.

2022-04-23 09:27 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/CommandLineRunner.java
> +        while (commandType != CommandType.EXIT) {
command.isRunnable() 과 같은 방식은 어떠할까요?

2022-04-23 19:04 UTC, midasWorld commented
## 📝 코드리뷰 목록

- [x] 전체 로직이 Try로 감쌀 필요가 있을까 생각이 듭니다.
  - 🦉 : Optional로 리턴할 수 있는 부분은 변경 → 받는쪽에서 체크구문 추가, service단 오류만 try-catch로 사용되도록 해보았습니다.
    - VoucherType → getVoucherType() : Optional로 반환으로 변경했습니다.
    - UUID로 변환하는 부분도 숫자나 이모지 입력시에 `변환실패 exception` 발생해서,
      Input에 변환 후 Optional로 반환하는 메서드를 추가하였습니다.
- [x] Command 가 늘어남에따라 OuputConsole 이 영향이 많이 가고 있습니다.
      여기에 대해 어떻게 생각하시나요?
  - 🦉 : CommandType이 변경되더라도 유연하게 모든 메뉴얼 출력되도록 수정했습니다.
    (Command 추가/삭제할때마다 Output을 또 수정하지 않아서 정말 좋은것 같습니다! 👍 )
    → CommandType - 각각 Command에 manual을 추가하고 모든 메뉴얼을 가져오는 함수를 추가했습니다.
    → Output - 메뉴얼 출력을 외부에서 주입받도록 수정했습니다.
- [x] Customer 의 내부 로 옮기는 건 어떻게 생각하나요??
  - 🦉 : 아.. 이거를 깜빡 했네요 😓.. 바로 수정 했습니다.
- [x] 이미 바우처 서비스이기에 메서드 네이밍에서는 바우처를 빼도 괜찮지 않을까요?
      persion.personName 이라고 하지 않는것 처럼 VoucherService.delete() 라고 표현해도 충분히 이해가 될것 같습니다.
  - 🦉 : 중복되는 이름 제거하였습니다.
- [x] print 의 기능이 새롭게 달라지지 않는다고 생각합니다. 이련 경우에 외부로 부터 출력 할 내용을 주입 받는 것이 적절하다고 생각이 듭니다.
  - 🦉 : 중복되는 메서드 다 삭제하고 사용하는 쪽에서 메시지를 넘겨주도록 수정했습니다.
- [x] command.isRunnable() 과 같은 방식은 어떠할까요?
  - 🦉 : 말씀해주신대로 수정해놓으니까, run() 메서드에 맞게 가독성이 훨씬 더 좋아진것 같습니다. 👍

## ✅ 궁금한 점

- try-catch 부분을 나름대로 수정을 해보았는데.. 로직이 생각보다 더 길어진것 같아서 이게 맞는지 잘 모르겠습니다. 😭
- 이제 내부 로직도 한번 진행해봐도 될까요?? 👀

2022-04-24 16:34 UTC, Jo-GyuHyeon commented
먼저 궁금한 점에 대해 저의 의견을 살짝 말해보려고 합니다.
입력에 대한 예외와, 서비스 로직에 대한 예외는 그대로 예외를 발생하는 것이 맞다고 생각하였습니다.

다만 예외를 catch 를 한것은 시스템이 멈추지 않고 계속 실행시키기 위함으로 이해 하고 있습니다.
다르게 표현한다면그렇다면 command 를 다시 선택해야 되는 상황을 유도하게 된다고 생각이 듭니다.
그렇다면 모든 예외를 최 상위에서 관리 하여 다시 command 를 선택하도록 하면 어떨까요?

2022-04-24 17:17 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/io/InputConsole.java
> +    }
입력에 대한 부분은 데이터를 찾는 것이 아니기에 잘못되었다면 예외가 발생하는 것이 자연스럽다고 생각이 드는데 어떠하신가요?

2022-04-24 17:17 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/model/customer/Customer.java
> +    public Customer(UUID customerId, String name, CustomerGrade customerGrade) {
CustomerGrade 보다는 고객이 어떤 유형의 고객인지를 표현 하는 것이 더 자연스럽지 않나? 라고 생각이 듭니다. type 은 어떠하신가요?

2022-04-24 17:49 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/model/customer/Customer.java
> +    public Customer(UUID customerId, String name, CustomerGrade customerGrade) {
등급과 유형 두고 고민을 했었는데.. 듣고보니 말씀해주시는 게 맞는거 같네요. 👍

2022-04-24 18:01 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/CommandLineRunner.java
> +        if (voucherType == null) {
.get() 메서드를 피하려고만 한게 독이 된것 같네요.. 😭
좀더 optional, stream 스럽게 사용할 수 있도록 생각해보고 연습도 해보겠습니다!

2022-04-24 18:06 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/CommandLineRunner.java
>              output.printMessage(e.getMessage());
로그 기록하는것과 오류메시지 출력 하는건 행하는게 다르니까, 따로 쓰는게 낫다고 생각했었는데...
같은 내용을 담고 있다라는 것과 같이 생각을 해보니 제 생각이 틀린것 같네요.
말씀하신대로 한번 적용해 보겠습니다. 😁

2022-04-24 18:09 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/io/InputConsole.java
> +    }
확실히 예외 발생이 더 자연스러운것 같습니다.

2022-04-24 18:14 UTC, midasWorld commented
## 📝 코드 수정

- try-catch 부분을 최상단으로 이동하고 로그를 단계별로 처리하도록 수정했습니다.
  - 기존 CommandLineRunner의 각 메서드에 있는 try-catch 구문은 삭제하였습니다.
  - 기존에 Optional로 반환하는 부분을 다시 exception 발생되도록 수정하였습니다.
- 위의 것과 이어서 ouput에서 로그 기록과 오류 메시지 담당을 하도록 메서드를 추가하였습니다.
- CustomerGrade → CustomerType으로 이름을 변경하였습니다.

2022-04-25 02:20 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/CommandLineRunner.java
>              output.printMessage(e.getMessage());
@midasWorld  님의 생각이 틀리다고 생각하지 않습니다.
다만 로그를 남기는 쪽이 꼭 해당 계층이나 해당 메서드가 담당해야 할까? 에대해서 고민해보고 같이 얘기해봤으면 해서 말씀드렸습니다. :)

2022-04-25 02:22 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/model/customer/Customer.java
> +    public Customer(UUID customerId, String name, CustomerGrade customerGrade) {
등급에 대한 개념이 존재하려면 등급을 측정하는 단위도 있으면 어떨까? 라는 생각이 드는것 같습니다. 혹시 더 좋은 네이밍과 개념이 있다면 변경하셔도 좋습니다. :)

2022-04-25 04:18 UTC, Jo-GyuHyeon requested changes

2022-04-25 04:18 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/service/customer/CustomerService.java
>      }
`findAllBlackList()` 의 네이밍을 보았을때 이미 타입이 지정이 되어야 된다고 생각합니다.
혹은 타입을 받을 예정이라면 메서드 네이밍을 다시 고려해주세요 :)

2022-04-25 14:21 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/CommandLineRunner.java
> +                    case EXIT -> exitCommandRunner();
메서드 분리 때문에 전역으로 뺀거였는데, 그런 방법이 있었군요. 😳
`변수는 사용되는 스코프 내에서`도 기억해둬야 겠네요. 👍
이거 다시 작성을 해보니 위에서 이미 commandType에 EXIT가 이미 들어가 있는데, 다시 넣는 불필요한 구문이었네요. 😱
수정했습니다...

2022-04-25 14:24 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/io/Output.java
>      void printShutDownSystem();
확실히 불필요한 메서드였네요..
그리고 메시지를 상수로 한다면 네이밍의 고민으로 또 이어져서.. 이건 네이밍과 함께 고민해보겠습니다.

2022-04-25 14:25 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/customer/CsvCustomerRepository.java
>                  }
네이밍이 참 어렵네요.. ㅎㅎ
고민해서 한번.. 아래와 같이 수정해보았습니다.
```java
String readCustomerType = readData.get(CSV_HEADER[2]);
CustomerType compareType = CustomerType.valueOf(readCustomerType);
if (compareType != customerType) {
    continue;
}
```

2022-04-25 14:36 UTC, midasWorld commented
- [x] commandType 을 전역으로 사용 하기 보다 run 스코프내에서만 사용된다고 생각합니다.
      run() 메서드 이외에서는 사용 될 일이 없기도 합니다.
      exitCommandRunner() 이란 메서드를 따로 빼셨다면 return 된 값을 받아서 commandType 를 다시 재 할당 시켜 주면 어떨까요?
  - 🦉 [75b0ed2](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/75b0ed2c51793124a7aa0362cdede46a5b9b46d5) → 분리된 메서드 삭제하고 바로 switch문 case에서 메서드 사용되도록 변경하였습니다.
- [x] 해당부분에 개행이 있다면 구분감을 줘서 가독성이 좋아 질것이라 기대하고 있습니다. 혹시 어떻게 생각하실까요?
  - 🦉 [bb0049c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/bb0049c4b299c02d238320181db2bf14536ce32a) → 구분 되도록 개행 처리하였습니다.
- [x] 출력하고 싶은 메시지를 외부로 부터 주입받는 형식은 어떨까요?
      그렇게 되면 메시지는 상수로써 다로 관리를 할 수 있을 것 같습니다. ( 메시지는 꼭 상수는 아닙니다.)
  - 🦉 [488e594](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/488e5944cb68f53d21a5c02787181f4fe35c4143), [75b0ed2](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/75b0ed2c51793124a7aa0362cdede46a5b9b46d5) → 메시지 부분은 모두 외부로 주입되도록 변경해보았습니다.
- [x] 해당 값은 외부 리소스이기에 yml 으로 빼는 것이 더 적합하다고 생각합니다. (주입)
      외부 리소스에 대한 정보를 찾기도 힘들 수 있습니다.
  - 🦉 [a55897b](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/a55897b85bb85070d9b187487916fd376fa0a1f2) → yml 파일에 정의해서 사용되도록 수정하였습니다.
- [x] 해당 라인만 보게된다면 어떠한 로직인지 파악하기 힘들수도 있다고 생각합니다. (가독성)
      필터링을 하는 로직으로 파악이 되고 있습니다.
      readData.get(CSV_HEADER[2]) 를 따로 변수로 빼는 것도 가독성을 높일 수 있습니다. CSV_HEADER[2] 은 어떤 헤더인지 알기 쉽지 않습니다.
  - 🦉 [2652a74](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/2652a7470a4a435c7a6f1103b42894a145c74845) → 가독성을 위해 수정하였습니다.
- [x] findAllBlackList() 의 네이밍을 보았을때 이미 타입이 지정이 되어야 된다고 생각합니다.
      혹은 타입을 받을 예정이라면 메서드 네이밍을 다시 고려해주세요 :)
  - 🦉 [dd0e01a](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/dd0e01ad969689b0ed08176475319dda0531e825) → 네이밍 수정하였습니다!

## ✅ 추가 반영사항

- 🦉 [cf91c77](https://github.com/prgrms-be-devcourse/springboot-basic/pull/309/commits/cf91c77069dcdf051b1c84099a6c40c9072230db) → `@SpringBootApplication` 애노테이션 사용함으로 JdbcTemplate 빈은 자동으로 만들어주는데, 중복 정의한 부분 삭제하였습니다.

2022-04-28 14:25 UTC, midasWorld commented
## ⛏ 아래의 작업

- [x] Customer, Voucher → csv file → DB로 전환
  - JdbcRepository, Service 단 내부 로직 구현

## 🧐 궁금한 점

- **기능 요구사항에 없는, 오로지 테스트 코드를 작성하기 위한 편의 메서드를 만드는 것이 맞을까요? 🤔**

  (조회 기능 밖에 없는) CustomerService 테스트 코드를 작성 하려니, 데이터가 있어야 될것 같아 schema.sql 파일을 가져다 사용했습니다.
  그런데 단위 테스트는 독립적이어야 한다고 알고 있는데, schema.sql에 의존적이라는 생각이 들었습니다.
  이걸 위해서는 Customer 에 insert 기능을 만들어야 될 것 같은데..

  **저는 유지보수를 위해서는 테스트 코드의 중요성은 매우 높다고 생각하고, 편의 메서드를 만들어야 된다고 생각합니다.**

  하지만 Service 단이라는 것이 비지니스 로직을 담당하는 곳이라고 생각하고 있습니다.
  그럼 요구사항에도 없는 오로지 테스트를 위한 이 편의 메서드를 여기에 만드는게 맞는 것인가?
  만들어야 한다면 Repository 단에 만들어서 활용하는 것이 맞지 않을까? 라는 생각을 하게 되었습니다.

  제 생각이 맞는건지, 아니면 틀에 갇힌 생각을 가진건지, 이것도 아니라면 모든게 잘못된 생각인건지 궁금합니다!

2022-04-29 01:34 UTC, midasWorld commented
## ⛏ 위의 작업

- [x] Customer, Voucher → csv file → DB로 전환
  - JdbcRepository, Service 단 내부 로직 구현

## 🧐 궁금한 점

- **기능 요구사항에 없는, 오로지 테스트 코드를 작성하기 위한 편의 메서드를 만드는 것이 맞을까요? 🤔**

  (조회 기능 밖에 없는) CustomerService 테스트 코드를 작성 하려니, 데이터가 있어야 될것 같아 schema.sql 파일을 가져다 사용했습니다.
  그런데 단위 테스트는 독립적이어야 한다고 알고 있는데, schema.sql에 의존적이라는 생각이 들었습니다.
  이걸 위해서는 Customer 에 insert 기능을 만들어야 될 것 같은데..

  **저는 일단 유지보수를 위해서는 테스트 코드의 중요성이 매우 높다고 생각하고, 편의 메서드를 만들어야 된다고 생각합니다.**

  하지만 Service 단이라는 것이 비지니스 로직을 담당하는 곳이라고 생각하고 있는데요.
  그럼 요구사항에도 없는 오로지 테스트를 위한 이 편의 메서드를 여기에 만드는게 맞는 것인가?
  만들어야 한다면 Repository 단에 만들어서 Service와 같이 테스트로 활용하는 것이 맞지 않을까? 라는 생각을 하게 되었습니다.
  (CustomerServiceTest → CustomerRepository(: insert나 deleteAll 활용), CustomerService(: 실제 비지니스 로직 테스트))

  제 생각이 맞는건지, 아니면 틀에 갇힌 생각을 가진건지, 이것도 아니라면 모든게 잘못된 생각인건지 궁금합니다!

2022-04-29 08:45 UTC, midasWorld commented
## ⛏ 위의 작업

- [x] Customer, Voucher → csv file → DB로 전환
  - JdbcRepository, Service 단 내부 로직 구현
- [x] 단위 테스트 작성

## 🧐 궁금한 점

- **기능 요구사항에 없는, 오로지 테스트 코드를 작성하기 위한 편의 메서드를 만드는 것이 맞을까요? 🤔**

  (조회 기능 밖에 없는) CustomerService 테스트 코드를 작성 하려니, 데이터가 있어야 될것 같아 schema.sql 파일을 가져다 사용했습니다.
  그런데 단위 테스트는 독립적이어야 한다고 알고 있는데, schema.sql에 의존적이라는 생각이 들었습니다.
  이걸 위해서는 Customer 에 insert 기능을 만들어야 될 것 같은데..

  **저는 일단 유지보수를 위해서는 테스트 코드의 중요성이 매우 높다고 생각하고, 편의 메서드를 만들어야 된다고 생각합니다.**

  하지만 Service 단이라는 것이 비지니스 로직을 담당하는 곳이라고 생각하고 있는데요.
  그럼 요구사항에도 없는 오로지 테스트를 위한 이 편의 메서드를 여기에 만드는게 맞는 것인가?
  만들어야 한다면 Repository 단에 만들어서 Service와 같이 테스트로 활용하는 것이 맞지 않을까? 라는 생각을 하게 되었습니다.
  (CustomerServiceTest → CustomerRepository(: insert나 deleteAll 활용), CustomerService(: 실제 비지니스 로직 테스트))

  제 생각이 맞는건지, 아니면 틀에 갇힌 생각을 가진건지, 이것도 아니라면 모든게 잘못된 생각인건지 궁금합니다!

2022-05-05 12:43 UTC, Jo-GyuHyeon approved these changes
`기능 요구사항에 없는, 오로지 테스트 코드를 작성하기 위한 편의 메서드를 만드는 것이 맞을까요? 🤔`
* 제가 생각했을때는 테스트의 편의 기능을 제공하기 위해 메서드를 만들수 있다고 생각합니다. 다만 비지니스 로직이나 도메인에 편의 메서드를 추가 하는 것이 아닌 테스트 코드내에서 테스트의 편의에 대한 기능은 만들어도 괜찮다고 생각해요. 

예를 들어 Mock 데이터를 생성 해준다던지, 다른 테스트를 독립성을 유지하기 위해 기존 테스트로 인해 저장된 데이터를 제거 해주는 기능을 비지니스로직에 영향을 주지 않으니 필요하다면 추가 해도 무당하다고 생각합니다.

2022-05-05 12:43 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/model/voucher/FixedAmountVoucher.java
> +        return beforeDiscount - amount < 0 ? 0 : beforeDiscount - amount;
`beforeDiscount - amount` 부분을 따로 변수로 빼보는 건 어떨까요?
성능상에 크게 이슈는 없겠지만 2번 계산을 하고 있고 실수로 이어질 수도 있다고 생각이 듭니다.

변수로 빼는 이유는 가독성도 생각하고 있습니다.
혹은 `if` 문을 사용해서 음수로 결과가 나올때 빠른 반환을 사용해보는건 어떨까요?

동운님의 의견이 궁금합니다.

2022-05-05 12:43 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/customer/JdbcCustomerRepository.java
> +import java.util.*;
intellij 설정을 하시면 와일드 카드 import 를 자동으로 해주는 설정을 변경 할 수 있습니다.

2022-05-05 12:43 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +        }
해당 코드를 보았을때 존재 하지 않는 voucherId 를 삭제하는 경우도 해당 예외가 발생 할 수 있다고 생각합니다.

저는 리턴 타입이 void 라고 보았을때 어떠한 결과가 일어 나던 상관하지 않아도 된다고 생각하였습니다.
하지만 이렇게 삭제가 되지 않는 상황을 예외로 바라봐야 하나? 라는 의문이 생기기도 합니다.
오히려 애초에 존재 하지 않았으니, 결과는 삭제를 한것과 동일 하다고 생각해도 되지 않을까??? 라는 생각이 드는데 동운님은 어떻게 생각하시나요?

2022-05-06 01:28 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/customer/JdbcCustomerRepository.java
> +import java.util.*;
아.. 꿀팁감사합니다. 바로 적용해보겠습니다. 👍

2022-05-06 02:00 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/model/voucher/FixedAmountVoucher.java
> +        return beforeDiscount - amount < 0 ? 0 : beforeDiscount - amount;
변수로 빼는 부분은 계속을 말씀을 해주셨는데.. 제 불찰입니다.. 😓... 한번 더 확인해보겠습니다!
(코드량 줄이기 위해  계산을 2번하는건 확실히 아닌것 같습니다.)

계산을 하고 변수 하나로 경우에 따라서 리턴하는 거라면 if문 보다는 
삼항연산자가 더 직관적으로 가독성이 좋은것 같아서 계산 후에 이걸로 사용해보겠습니다!

2022-05-08 14:18 UTC, pjh612 reviewed
동운님께서 나름대로의 생각을 가지고 코드를 짜신게 눈에 보이는것 같슴다!
그저 같이 배우는 입장에서의 개인적인 생각을 담았을뿐 제가 정답이라고 말씀드리는건 아니니까 가볍게 읽어보시죠!

2022-05-08 14:18 UTC, pjh612 commented on src/test/java/org/prgrms/kdt/service/voucher/VoucherServiceTest.java
> +    @DisplayName("바우처가 삭제 실패한다.")
null을 넣었을 때 존재하지않는 것과 UUID를 넣었는데 존재하지 않았을때는 엄연히 다른 케이스라고 생각이 드는데요! 그렇다면 케이스를 분리하는건 어떨까? 생각이듭니다.

2022-05-08 14:18 UTC, pjh612 commented on src/test/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepositoryTest.java
> +        assertThat(deletedVoucher.isEmpty(), is(true));
비어 있지 않은지 확인하는 것 뿐만아니라, 안에 내용도 정확히일치하는지 확인해야되지 않을까? 생각이듭니다.

2022-05-08 16:33 UTC, HYEBPARK reviewed
동운님 열심히 작성하신 코드에 도움이 되는 리뷰를 남기고 싶은데 
여전히 어렵네요 😓 처음 보는 기능이 많아서 배우고 갑니당 
다음번 코드 리뷰엔 강해져서 돌아오겠습니다 !! 수고 많으셨습니다 👍⭐😊

2022-05-08 16:33 UTC, HYEBPARK commented on src/main/java/org/prgrms/kdt/CommandLineRunner.java
> +        output.printMessage(vouchers);
voucher의 목록들이 message 인가 ? 라는 생각이 문득 들었습니당 ㅎ-ㅎ 
동운님은 어떻게 생각하세요 !? 😊

2022-05-08 23:35 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/customer/JdbcCustomerRepository.java
> +    public void deleteAll() {
확실히 위험의 여지가 있는 부분이네요. 🤔
Test 용으로 만들었는데, 다른 방법을 한번 찾아봐야 겠군요. 👀

2022-05-08 23:45 UTC, midasWorld commented on src/test/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepositoryTest.java
> +        assertThat(deletedVoucher.isEmpty(), is(true));
findById() 가 못찾으면 Optional.empty() 를 반환을 하는데, 내용을 체크를 할 수가 있나요?? 🤔

2022-05-08 23:50 UTC, midasWorld commented on src/test/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepositoryTest.java
> +            .orElseThrow(() -> new IllegalArgumentException("Could not found voucher with voucherId=" + fixedVoucher.getVoucherId()));
흠.. 한번 더 생각을 해봐야 겠네요. 🤔
저는 일단 UPDATE 테스트가 주다 보니, 그 외의 것들은 검증이 아니라 예외로 이런 문제가 있다는 메시지를 확실히 보여주는 게 낫지 않을까? 라는 생각입니다.

그런데 그런데 정작 findById 테스트가 없었군요... 😱

2022-05-08 23:57 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/CommandLineRunner.java
> +        output.printMessage(vouchers);
사용자 입장에서는 결국엔 바우처 목록이라는 메시지라고 생각을 했습니다.
그리고 리스트를 보내는 쪽에서 어떻게 보낼건지 정할 수 있어서 이 방식을 사용하게 되었는데요.

그런데 듣고보니 어차피 리스트 그대로 출력 하는거고,
`Ouput`에서 List<?>으로 받아서 일괄 출력할 수 있지 않나? 라는 생각이 드는군요.. 😳
오우.. 의견 감사합니다. 👍

2022-05-09 00:00 UTC, midasWorld commented on src/test/java/org/prgrms/kdt/service/voucher/VoucherServiceTest.java
> +    @DisplayName("바우처가 삭제 실패한다.")
생각을 해보니, 'Service단 메서드의 체크구문에서 걸리느냐' / 'DB까지 가서 예외가 발생하느냐'의 차이가 있네요.
확실히 메시지도 다르게 분리하는 것이 맞는 것 같습니다! 👍

2022-05-09 00:10 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +        }
생각이 굉장히 많아지네요.. 
- 존재하지 않는 Id를 삭제구문의 매개변수로 보냈으니, 결국엔 오류이다?
- 예외처리 하지않고, void가 아닌 boolean 으로 반환을 해야 되는가?

저는 그래도 삭제 요청을 확실하게 수행하지 못한 것이니, 오류가 맞다 라고 생각하는 쪽인것 같습니다. 🤔
근데 void라는 반환값 자체에 큰 의미를 두지 않아서 이렇게 생각하는 건가? 싶네요.

한번 더 찾아보면서 생각 다시 한번 해보겠습니다!

2022-05-11 01:26 UTC, merged