Pjh612/w2
prgrms-be-devcourse/springboot-basic pull request #323
Opened 2022-04-23 20:20 UTC by pjh612

**변경 사항**
feat
- CustomerJdbcRepository, VoucherJdbcRepository, VoucherService, CustomerService 프로토타입을 추가했습니다
  - CustomerService에서는 CustomerJoinRequest DTO가 사용됩니다.
- Jdbc, mySql 사용을 위한 AppConfiguration 내용이 추가되었습니다.

setting
- Jdbc 사용을 위한 의존성이 추가 되었습니다.

refactor
- Customer의 name 도 불변값으로 취급하여 final을 붙여줬습니다.
- FileInput, FileOutput을 FileIOUtils로 병합했습니다.
  - 내부 메소드는 static으로 변경되었습니다.
- CsvDeserializer를 CsvMapper로 변경하고 Serialize 기능도 함께 구현하도록 변경했습니다.
 - FileRepository에서는 CsvMapper는 new로 생성하여 사용합니다.
- BlacklistService는 VoucherService와 같이 service.blacklist.BlacklistService와 같이 위치하도록 변경했습니다.

**PR 중점 사항**
- 말씀하신대로 틀부터 작성했습니다.
일단 강의에서도 레이어드 아키텍처, MVC 기반으로 코드를 작성하고, 추후 과제에서도 MVC로 변경이 될 것이기때문에 Service, Repository 형식을 기본으로 생각하고 필수로 필요하다고 생각되는 클래스, 메서드 프로토타입을 작성했습니다.

- 멘토님께서 전달해주신 Bean, static 관련 링크를 토대로 기존의 FileInput, FileOutput은 FIleIO로 병합을하고, 내부의 메소드는 Static 메소드로 만드는 것이 더욱 적합하다 판단되어 변경했습니다.

  말씀해주신 FileIO에 제네릭을 적용하고 serialize, deserialize를 해당 타입에 맞게 실행할 수 있도록 해보려고 했으나... 잘 안떠올라 현재 방법을 사용했습니다.

  FileIO에 제네릭을 적용하는 것까진 알겠으나, FileIO 내부에서 제네릭 타입별로 직렬화하고 역직렬화 하는 방법은 Voucher, Customer 마다 다 다르기 때문에 다형성이 요구되는 듯 했습니다. 그렇기 때문에 FileIO 내부에서 직렬화 역직렬화 하는 방법을 정의하는 것이 아닌 외부에서 행동을 정의해야 한다고 생각했습니다.

  그 방법으로는
첫째로, Voucher, Customer Entity 클래스에 serialize, deserialize 함수를 구현하는 방법을 생각해봤었고,
두 번째로, FileIO 내부에 빈으로 등록된 CsvMapper를 두고 CsvMapper는 HashMap과 같은 자료구조에 Entity 클래스 타입을 Key로 각 Entity 타입별로 매핑 모듈(직렬화, 역직렬화)을 등록해 resolving 하는 방식을 생각해봤는데 그 마저도 여의치않았습니다 ㅜㅜ..
말씀해주신대로 구현을 해보려고해도 막상 구현해보려고하면 생각대로 잘 안되는게 어렵네요..

2022-04-24 06:18 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/model/customer/Customer.java
> +public class Customer implements Serializable {
어... 요거는 실수로 안지웠나 봅니다... ㅎㅎ

2022-04-24 15:08 UTC, Jo-GyuHyeon requested changes
고생하셨습니다. :) 
Util 패키지는 범용적인 사용할 수 있어야 된다고 생각합니다.
해당 부분에서도 고민을 해보면 좋을것 같습니다.

2022-04-24 15:08 UTC, Jo-GyuHyeon commented on src/main/java/com/voucher/vouchermanagement/utils/deserializer/CustomerCsvMapper.java
> +public class CustomerCsvMapper implements CsvMapper<Customer> {
Mapper 는 제네릭이 늘어 날때마다 구쳔체가 늘어 나기 보다.
제네릭을 조금더 제네릭하게 사용해보면 어떨까요? 범용적으로 사용할 수 있게 고민해보면 좋을것 같습니다.

2022-04-24 15:08 UTC, Jo-GyuHyeon commented on src/main/java/com/voucher/vouchermanagement/utils/file/FileIOUtils.java
> +        }
파일관련 로직을 별도로 빼보는 것은 어떨까요? 예외가 발생하더라도 파일 처리 하다가 예외가 발생했다고 생각합니다. 또한 재사용도 가능하다고 생각합니다.

2022-04-24 16:09 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/service/customer/CustomerService.java
> +    }
네 맞습니다. Repostiory에서 Optional으로 반환 받아 .orElseThrow를 통해 예외를 발생시키려고 합니다. 추가적으로 Entity를 반환하는 대신 Dto를 반환해 Controller 레이어에는 Entity가 넘어오지 않도록 하려고 합니다.

2022-04-24 16:10 UTC, pjh612 commented on src/main/resources/application.yaml
> +      name : voucher_db.csv
모든 db는 하나의 path에 모여있게 할 생각이었습니다.
path를 하나의 데이터 베이스 스키마로 보고 각 파일을 테이블로 보고자 했습니다.
의도는 이랬는데 분리하는게 좋을까요?

2022-04-25 07:08 UTC, Jo-GyuHyeon reviewed
커밋 메시지를 보았을때 작업에 단위보다는 파일 마다 커밋을 하신듯합니다.
그렇기에 커밋단위는 너무 작은 단위로 쪼개져 있기도합니다.
commit 을 하기전에 어디까지 작업을 할 것인지에 대해 한번 고민 해보시면 좋을 것 같습니다.

2022-04-25 07:08 UTC, Jo-GyuHyeon commented on src/main/java/com/voucher/vouchermanagement/service/customer/CustomerService.java
> +    }
findById() 에서 데이터를 찾는 행위와 join() 에서 데이터를 저장하는 행위와 같은 retrun 타입이 나올것이라 기대 하였습니다.
response 모델은 contoller 단 에서 담당할 것이라 생각합니다.
controller 는  라우팅 뿐만아니라 입출력 (in, out | request, respons) 를 담당합니다.

2022-04-25 07:18 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/service/customer/CustomerService.java
> +    }
조회할때는 Customer 전체의 데이터를 반환할 수 있지만, join때 반환하는 데이터는 또한 CustomerDto보다는 더 일부의 데이터만 반환하고싶을 수도 있는 등의 이유로 두개의 메서드가 다른 별개의 DTO를 반환해야된다고 생각했습니다.

하지만
service에서 반환하는 것은 CustomerDto로 통일하되, 각각의 API메소드 마다 어떤 형식으로 데이터를 전달해줄지는 Controller의 담당으로 하는쪽이 더 맞다는 말씀이신가요?

제가 이해한게 맞다면 그냥 애초에 서비스단에서 반환받은 dto를 controller에서 반환해도 되지 않나 싶습니다.
CustomerDto에서 또 다시 데이터를 뽑아내서 다른 Dto를 생성하는 것은 불필요하지 않나? 생각이 들기도 합니다.

2022-04-26 08:32 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/service/customer/CustomerService.java
> +    }
`join때 반환하는 데이터는 또한 CustomerDto보다는 더 일부의 데이터만 반환하고싶을 수도 있는 등의 이유`
라면 id 값만 반환 하는 것은 어떨까요?
-> 넵 id 값만 반환하는 것도 좋을것 같습니다.

`각각의 API메소드 마다 어떤 형식으로 데이터를 전달해줄지는 Controller의 담당으로 하는쪽이 더 맞다는 말씀이신가요?`
넵 맞습니다. Controller 는 입력 뿐 아니라 출력의 책임을 담당하고 있습니다. service 는 response 를 몰라도 상관 없다고 생각합니다.

-> 제 생각에는 service가 model을 뱉게되면 model을 주무를수 있는 범위가 넓어져 유지보수가 힘들어지지 않을까? 하는 생각이 듭니다. 차라리 service가 responseDto를 반환해 model의 사용범위를 줄이고 controller에선 model을 몰라도 되게 하는게 더 낫다고 생각이 드는데 어떻게 생각하시나요? 
controller가 출력의 책임을 담당하고 있다면 controller가 service에서 model을 반환 받아 dto로 변환해주는 것보다 service에서 반환 받은 responseDto를 **"필요시"** 또 다시 정제를 해서 view로 보내는게 낫다고 생각이듭니다!
제 생각은 이런데 멘토님은 어떻게 생각하시나요?

2022-04-26 13:07 UTC, pjh612 commented
- [x] 커밋 메시지를 보았을때 작업에 단위보다는 파일 마다 커밋을 하신듯합니다.
그렇기에 커밋단위는 너무 작은 단위로 쪼개져 있기도합니다.
commit 을 하기전에 어디까지 작업을 할 것인지에 대해 한번 고민 해보시면 좋을 것 같습니다.`
  - Repository 구현 Service 구현 등으로 작업 단위를 산정해 Commit을 해보았습니다.

- [ ] join때 반환하는 데이터는 또한 CustomerDto보다는 더 일부의 데이터만 반환하고싶을 수도 있는 등의 이유
라면 id 값만 반환 하는 것은 어떨까요?

  각각의 API메소드 마다 어떤 형식으로 데이터를 전달해줄지는 Controller의 담당으로 하는쪽이 더 맞다는 말씀이신가요?
넵 맞습니다. Controller 는 입력 뿐 아니라 출력의 책임을 담당하고 있습니다. service 는 response 를 몰라도 상관 없다고 생각합니다.
  - Dto 관련된 내용은 아직 답변을 기다리고 있는 중이어서 일단은 제 생각 토대로 구현했습니다!

* Mapper,FileRepository 관련해서는 말씀 해주신것 처럼 후순위에 두고 차차 구현하도록 하겠습니다.

2022-04-27 06:11 UTC, Jo-GyuHyeon commented on src/main/java/com/voucher/vouchermanagement/service/customer/CustomerService.java
> +    }
@pjh612 님의 의견도 매우 좋습니다. :+1: 
실은 해당영역은 정답은 없다고 생각합니다.

다만 제가 생각했던 부분은 (Client 와 Controller 사이의 DTO) 와 (Controller 와 Service 사이의 DTO) 를 분리 를 생각하였습니다.
Controller 는 Service 를 의존하기에 Service 의 리턴 타입을 알아도 무방하지만 반대로 Service 가 Controller 단의 관여(참조)하는 것은 아닐까? 생각도 하였습니다.

[DTO 관련 참고 링크](https://www.inflearn.com/questions/139564)

2022-04-27 06:27 UTC, pjh612 commented on src/main/java/com/voucher/vouchermanagement/service/customer/CustomerService.java
> +    }
첨부해주신 링크 글을 작년에 Spring을 처음 접했을 때 그때는 너무 초보라 "이게 대체 무슨 소리야?" 하며 읽었던 기억이 납니다. 이제 다시 보니까 어느정도 이해가 되는 듯 합니다.
제가 생각하기에는 규현님과 영한님의 의견이 어느 정도 같은 맥락이라고 생각이 드네요 영한님 의견은 의존 할거면 하나만 의존할 것이고 그 선택은 Entity가 두루두루 전 영역에서 쓰이기 때문에 Entity를 의존하는 것을 고려 해보는게 좋다 라고 이해했습니다.

다만 저는 Entity의 사용 범주를 줄이기 위해 Dto와의 의존을 선택한 것이었으며 사실 상 이 두가지 방법에는 명확한 답은 없고 trade-off라고 이해를 했습니다.

추가적으로 글을 읽다보니 package 배치에 따른 package 의존관계에 대해서는 배제하고 있었는데 이것도 한번 고려해보는 시간을 갖는게 좋다고 느꼈습니다.

의견 공유할 수 있어서 기쁩니다! 잘 고려해서 선택해보도록 하겠습니다.

2022-04-27 08:13 UTC, pjh612 commented
- [x] 규현님이 말씀해주신 DTO 의존성 관련 내용은 지속적으로 고민해볼 예정입니다. 서로간의 장단점이 있다면 지금 당장 수정을 하기보다는 제가 직접 코드를 짜면서 느껴봐야겠다고 생각했습니다.

- [x] Voucher에 관한 Test 코드를 작성했습니다.
 - 테스트 과정에서 필요한 dto에 관한 getter를 추가했습니다.
 - 이 과정에서 테스트를 진행하며 발생한 오류가 몇가지 있었습니다
   - DB와 JAVA LocalDateTime의 정밀도 차이
     - DB에서 캐치 못하는 단위는 제거해주고 insert해주는 방식으로 해결했습니다.
   - DB 삽입 실패 시 애플리케이션이 종료되버리는 문제가 있었습니다
     - Repository에서 예외를 Catch한 후 VoucherManager까지 throw해 VoucherManager에서 예외 처리를 해줬습니다.
     - Repository에서 현재는 Exception을 캐치하고 RuntimeException을 throw하고 있는데 너무 광범위하게 catch하고 throw하고 있지 않나 생각이 들어 이 부분은 조금 더 알아봐야할 것같습니다.

2022-04-28 08:17 UTC, pjh612 commented
feat : Customer 이메일로 조회, 이름으로 조회 기능 추가, 예외 처리 추가 [192f9fe](https://github.com/prgrms-be-devcourse/springboot-basic/pull/323/commits/192f9fe848ef14c2979221b8c2ebe40ce23cb241)
- Customer 이메일, 이름으로 조회 기능 추가하고 예외처리를 추가로 해줬습니다. [3f277b2](https://github.com/prgrms-be-devcourse/springboot-basic/pull/323/commits/3f277b2a125ab35dd9d2893e88bacc98eaa971e5)
- Customer 다중 삽입 기능을 추가했습니다.
  - 강의에서 Transaction 강의를 위한 항목입니다.
- Customer기능 Test를 위한 Respository,Service Test 함수원형을 작성했습니다. [fbd6574](https://github.com/prgrms-be-devcourse/springboot-basic/pull/323/commits/fbd6574c6985b1459c60a82bcd6c271d03d04673)

- PR포인트
  - 다중 삽입시 일반 단일 삽입과는 달리 service로 삽입데이터 전달 시 Dto를 사용할 수 밖에 없는데요.(CustomerJoinRequest)
여기서 고민이었던게, View -> Controller 에서 사용하는 RequestDto와, controller -> service에서 사용하는 Dto를 분리를 해야된다고 했었는데(view-controller-service간 결합도 해소) Dto의 네이밍을 어떻게 할지 잘 모르겠습니다.
둘 다 똑같이 다중삽입을 위한 데이터의 전달용 Object인데 MultiJoinHttpRequest, MultiJoinServiceRequest 이렇게 나누는것도 조금 어색한 것 같고.. 
view -> controller에서는 MultiJoinRequest,  controller-> service에서는 MultiJoinDto가 조금 더 나을까요? 아니면 이러한 부분에 대한 네이밍 팁이 있을까요?


- Service가 Domain을 반환하는것은 아직 고민 중입니다.. 여러 장 단점이있어 선택이 너무 어렵네요 ㅜ.ㅜ
이것저것 찾아보면서 Service가 Domain을 반환하게 만들면 나중에 퍼사드 패턴으로 서비스 계층을 또 하나 추가해서 하위 서비스들을 사용할 때에는 
퍼사드 서비스가 하위 서비스로부터 똑같은 도메인을 반환받으며 사용할 수 있어서 편하다는 장점도 추가적으로 알게 되었습니다.. 이렇게 저렇게 해보면서 3주차 미션 제출할 때에는 확실히 정해보도록 하겠습니다.

2022-04-28 16:22 UTC, pjh612 commented
- fix : DataAccessException을 throw하도록 수정 [caa49f7](https://github.com/prgrms-be-devcourse/springboot-basic/pull/323/commits/caa49f71afef9c9c51268178bf9f574acc5ddd60)
   - DataAccessException도 RuntimeException이므로 try-catch하지 않고 그냥 DataAccessException을 던져주는 것이 더 알맞다고 생각하여 바꿨습니다.


- CustomerTest를 작성했습니다.
  - test : CustomerTest 구현  [1610b60](https://github.com/prgrms-be-devcourse/springboot-basic/pull/323/commits/1610b6015523646a5678812d05935de7da493dc0)
  - test : Customer 삽입 시 이메일 중복 테스트 추가 [033564a](https://github.com/prgrms-be-devcourse/springboot-basic/pull/323/commits/033564a495cbdd3582e9bebc6949ae8aa0ed765d)

2022-05-10 16:54 UTC, merged