최인창 SpringBoot Part2 Weekly Mission 제출
prgrms-be-devcourse/springboot-basic pull request #384
Opened 2022-04-25 08:47 UTC by ICCHOI

# 🗒️ 요구사항
## **(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customer 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

## **(심화)** **바우처 지갑을 만들어보세요.**

- [x]  특정 고객에게 바우처를 할당할 수 있습니다.
- [x]  고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x]  고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x]  특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

# 📽️ 프로젝트 구조

### Main

- Voucher 관리 어플리케이션과 Blacklist를  관리 기능을 분리하기 위하여 콘솔에서는 바우처 관리 어플리케이션만 관리하도록 수정하였습니다.
- CommandType Enum을 추가하여 선택에 따른 서로 다른 동작을 객체로 구분하였습니다.
- io 패키지의  Console 을 Input, Output 인터페이스를 통하여  구현하도록 수정하였습니다.
- wallet을 추가하여 심화 과제의 바우처 id를 통한 고객 조회, 고객 id를 통한 바우처 조회를 구현하였습니다..

### Test

- 계층형으로 단위테스트를 구성하였습니다.
- Repository Test는 강의에서 참고하여 순서대로 실행 되도록 하였습니다.

# ✔️ 피드백 반영 사항 & 부족한 부분

- Wallet의 test case를 작성해야 합니다
- 고객 블랙리스트 조회 기능만 수행하는 스프링 애플리케이션을 만들어야 합니다.
- Blacklist의 test case를 작성해야 합니다.

# ❓ PR 포인트 & 궁금한 점

다음 PR은 빠르게 할 수 있도록 열심히 공부하겠습니다.. 
21일 커밋 부분 부터 1주차 수정 및 2주차 내용이라, 여기부터 확인해주시면 될 것 같습니다 ! :)

- sql문의 예외처리를 RuntimeException으로 처리 하였는데, Custom Exception을 작성하는 게 좋을까요?  아니면 특정 경우에 따라 여러 종류의 exception을 던지도록 분리하는게 나을까요?

2022-04-26 14:40 UTC, SeokRae requested changes
인창님 이번 주도 고생하셨습니다.
우선 테스트 코드가 많이 부족해 보입니다. 
각각의 클래스마다 테스트를 만들어 볼 수는 없는지 고민해보시면 더 좋을 것 같습니다.

그리고 mysql 같이 외부 서버를 사용해야 하는 과제의 경우에는 docker 같은 컨테이너 기술을 통해 테스트 해볼 수 있도록 스크립트 파일을 같이 제공하면 더 좋을 것 같습니다.

그리고 만약에 그러한 방식으로 제공되어야 한다면 README를 통해 순차적으로 어떻게 실행해야 하는 지를 같이 제공하면 더 좋을 것 같습니다.

아직 단순한 데이터 조회 및 삭제의 경우에 대해서 예외처리를 안하신거죠?
일단은 덜 작성된 코드로 보여서 일단은 계속 요구사항과 기본적인 crud에 대해서도 실제 서비스에서는 어떻게 처리 해야 할까 고민해보시면 좋겠습니다.

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/command/CommandType.java
> +public enum CommandType {
어떻게 보면 라우팅을 통해 타입 매핑이 되면 객체가 생성되어 명령어가 수행하는 마스터 키처럼 보일 수도 있지만
이제는 한 번 고민해 볼 때가 되지 않았나 싶습니다.

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/customer/repository/CustomerRepository.java
> +    void deleteById(UUID customerId);
아직 사용하고 있지 않은 기능 명세군요

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/customer/repository/CustomerRepository.java
> +    void deleteAll();
마찬가지로 아직 사용하고 있지 않은 기능 명세군요

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/customer/repository/JdbcCustomerRepository.java
> +    private static UUID toUUID(byte[] bytes) {
toUUID를 만드는 방식은 이렇게 정해져 있는 건가요?

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/customer/repository/JdbcCustomerRepository.java
> +            throw new RuntimeException("Nothing was inserted");
어떠한 경우 customer를 등록 하는데 실패할까요?

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/customer/repository/JdbcCustomerRepository.java
> +    public Optional<Customer> findByName(String name) {
Optional로 처리 한다는 것은 클라이언트 쪽에서 관련 예외까지 처리 해야 하는 것으로 보입니다.
그렇다면 여기서 예외처리를 할 필요없이 null일 수도 있는 값 또는 예외가 발생할 수도 있는 정보를 클라이언트에게 책임을 위임해도 되겠네요.

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/voucher/repository/FileVoucherRepository.java
> +    public File createFile(File file) {
이건 뭘까요?

2022-04-26 14:40 UTC, SeokRae commented on src/main/java/org/programmers/springbootbasic/wallet/repository/JdbcWalletRepository.java
> +    private static final RowMapper<Customer> customerRowMapper = (resultSet, i) -> {
공통적으로 사용하는 코드라면 상수로 빼서 처리하는게 좋을 수도 있긴 하지만 불필요하게 선언한 건 아닌지 고민이 되네요.

2022-04-27 01:00 UTC, ICCHOI commented on src/main/java/org/programmers/springbootbasic/customer/repository/JdbcCustomerRepository.java
> +    private static UUID toUUID(byte[] bytes) {
강의에 나온 방식을 그대로 참고해서 사용하였습니다.

2022-04-27 01:36 UTC, ICCHOI commented on src/main/java/org/programmers/springbootbasic/CommandLineApplication.java
> +	public CommandLineApplication(Console console, ApplicationContext applicationContext) {
Bean으로 등록되지 않은 클래스인 CommandLineApplication에서 voucherService를 주입 받기 위하여 직접 사용하였습니다.

2022-04-27 11:16 UTC, ICCHOI commented on src/main/java/org/programmers/springbootbasic/voucher/repository/FileVoucherRepository.java
> +    public File createFile(File file) {
기존에 file 에 경로를 직접 지정하여 객체를 생성했었는데
yaml 파일에 따로 경로를 설정하고, @Value를 통해 path를 받아 오도록 수정하였습니다.

2022-04-27 11:57 UTC, ICCHOI commented on src/main/java/org/programmers/springbootbasic/VoucherApplication.java
> +        Console console = new Console();
Console 객체를 생성해서 넘긴 이유는 입출력을 Presentation Layer 계층으로 분리하기 위해 주입 해주었습니다.
ApplicationContext는 아래 계층의 Bean 들을 관리하기 위하여 넘겨 주었습니다.

2022-04-29 07:38 UTC, ICCHOI commented on src/main/java/org/programmers/springbootbasic/customer/repository/JdbcCustomerRepository.java
> +            throw new RuntimeException("Nothing was inserted");
예외처리를 추가하겠습니다!

2022-04-29 08:07 UTC, ICCHOI commented
## ✔️ 피드백 반영 사항

- Wallet의 test case를 작성하였습니다.
- Customer의 test case를 작성하였습니다.
- Voucher Service의 test case를 작성하였습니다.
- exception을 추가하였습니다.
- CommandApplication의 while로직을 합쳤습니다.
- 공통적으로 사용하지 않는 코드를 메소드에서 생성하도록 수정하였습니다.

##❓ PR 포인트 & 궁금한 점
- 예외처리에 대해서 공부하면서 진행하였는데, 제가 놓친 부분 또는 추가적으로 생각해봐야할 부분이 있는지 궁금합니다.
- 테스트 케이스를 BDD와 dci 패턴으로 작성하였는데 굳이 필요하지 않은데 과하다는 생각이 들었습니다. 
- 테스트 케이스의 검증을 올바르게 작성하였는지 궁금합니다.
- 3주차도 열심히 해보겠습니다..!

2022-04-30 10:59 UTC, SeokRae commented
금일 말씀드린 내용 수정해서 push 하시면 머지 하도록 하겠습니다. 
드디어 3주차 군요.!

2022-05-01 16:40 UTC, ICCHOI commented
피드백 받은 부분 수정 완료 했습니다! 그런데 하다보니 막힌 부분이 생겼습니다! 
첫번째로는 Service에서 Duplicate Key가 있는 지 확인 하기 위한 private method를 만들었습니다. 
그런데 이 private 메소드 때문에 test case의 mockito를 통한 테스트가 불가능해졌습니다. 
리플렉션을 통한 해결 방법 등을 봤었는데, 리플렉션을 사용해서 테스트 케이스를 작성하는게 좋을지, 아니면 private method를 pubilc으로 변경하면 좋을지 또는 다른 방법이 있을지 궁금합니다.
또, 두번째로는 이렇게 확인 후 만약 서비스 수행이 불가능 하면 Voucher를 반환 해야하는데, 
이 때 null로 반환 하거나 또는 Optional로 수정하여 Optional.empty를 Command로 반환 해야 할 것 같습니다. 
이 경우 Optional.empty를 Command에서 한 번 더 확인해야하는 소요가 생겨, Command에서 exception을 try-catch하는 것과 차이가 없을 거 같은데 그렇다면 service에서 exception을 던지도록 처리해도 괜찮을까요?

2022-05-04 02:24 UTC, SeokRae commented
> 피드백 받은 부분 수정 완료 했습니다! 그런데 하다보니 막힌 부분이 생겼습니다!
> 첫번째로는 Service에서 Duplicate Key가 있는 지 확인 하기 위한 private method를 만들었습니다.
> 그런데 이 private 메소드 때문에 test case의 mockito를 통한 테스트가 불가능해졌습니다.
> 리플렉션을 통한 해결 방법 등을 봤었는데, 리플렉션을 사용해서 테스트 케이스를 작성하는게 좋을지, 아니면 private method를 pubilc으로 변경하면 좋을지 또는 다른 방법이 있을지 궁금합니다.
> 또, 두번째로는 이렇게 확인 후 만약 서비스 수행이 불가능 하면 Voucher를 반환 해야하는데,
> 이 때 null로 반환 하거나 또는 Optional로 수정하여 Optional.empty를 Command로 반환 해야 할 것 같습니다.
> 이 경우 Optional.empty를 Command에서 한 번 더 확인해야하는 소요가 생겨, Command에서 exception을 try-catch하는 것과 차이가 없을 거 같은데 그렇다면 service에서 exception을 던지도록 처리해도 괜찮을까요?

일단 테스트 코드는 최소한 간소하게 작성해야 합니다.
리플렉션을 사용해서 private 메서드를 테스트 해야 하는 상황이 생기게 된다면 불필요한 코드가 작성될 것 같습니다.
게더에서 이야기 나눠보고, 3단계에 적용해 보시죠.

2022-05-04 02:24 UTC, merged