[2기-P] 김병연 SpringBoot Weekly Mission 2 제출
prgrms-be-devcourse/springboot-basic pull request #417
Opened 2022-04-26 10:59 UTC by whyWhale

작업 단위_(체크박스로 체크)
- [x] : vocuher jdbc crud 생성
- [x] : 고객 관리 프로그램, 바우처 프로그램 controller 분할
- [x] : voucher 도메인 테스트 코드

✅  PR 포인트_(고민했던 부분 포함)
- vocuherJdbcRepository에 해당 (고정형 또는 퍼센트)엔티티를 생성해내기 위해 voucherManager를 의존하여 해당 타입에 맞게 resolve 하고 있습니다. Repository에 이런 의존관계를 끊기위해 생각해보았는데 아이디어가 떠오르지 않습니다 ㅠㅠ 제가 시도했던 방식은 repository가 voucherManger에 의존하지 않고  레코드 기반으로 RowMapper를 정적으로 가져가려 했지만 애플리케이션 컨텍스트가 빈들을 스캔하는 것 보다 먼저 static method가 먼저 할당되어 AnnotationAplicationContext를 조작하여 가져오는데 실패 했습니다. 의존관계를 끊어주기 위한 다른 아이디어가 필요한데 힌트를 얻을 키워드가 있는지 궁금합니다!

✅  요구사항_(링크 남기기)
- [과제 요구사항](https://www.notion.so/backend-devcourse/Part1-3-38f57acca0dd490db11393701417943a)
- [현재 진행사항](https://github.com/whyWhale/springboot-basic/tree/yeon/weekly-mission-2)

2022-04-27 12:09 UTC, midasWorld reviewed
고생하셨습니다. 👍

2022-04-27 12:09 UTC, midasWorld commented on app/src/main/java/com/programmers/order/service/CustomerService.java
> +	}
Service단에서 try-catch와 Optional을 사용하기 보다는 오류를 던지고 Controller 에서 처리하는건 어떨까요?
Service단에서 메서드가 계속 늘어나게 되면 할때마다 try-catch 구문과 로깅처리를 해줘야 되고,
Controller 단에서도 Optional로 받은것을 또 검증하고 디캡슐화 해서 사용을 해야되는 것이, 
Service 단과 Controller 둘다 부담을 지우는 일이 아닐까?라는 생각을 해보았습니다. 🤔

2022-04-28 11:02 UTC, whyWhale commented on app/src/main/java/com/programmers/order/domain/FixedAmountVoucher.java
> +				", createdAt=" + createdAt;
toString은 logback에서 기록남기기위해 사용할 목적이였습니다 그 외로 show는 클라이언트에게 보여지는 정보를 보여주기 위해 해당 이름을 사용했습니다! 네이밍이 조금 우색한가🐲?

2022-04-28 11:08 UTC, whyWhale commented on app/src/main/java/com/programmers/order/service/CustomerService.java
> +	}
얼리 리턴을 우선순위로 가졌습니다! 해당 예외를 차례차례 대로 가져가면 컨트롤러 단에 try catch로 가득할 것이며 그에맞는 예외들을 잡기 때문에 코드 길이 또한 예외에 따라 증가하고 로직에 대한 필요 분기가 필요함에 따라  인덴트가 3이 넘어가게 되면서 코드 가독성 측면에서 안좋을 수 있다고 생각했습니다! 디캡슐화에 대한 성능 이슈는 현재로서는 증명할 수 없어 나중에 데이가 많아졌을 후에 고러해야 겠다는 생각이 들어서 이렇게 차리하였습니다!

2022-05-02 05:15 UTC, pjh612 reviewed
정형화된 코드가 아니라 새로웠습니다! 오히려 제가 궁금한 것들이 더 많아지는 리뷰가 된 것 같습니다... 사실 제 말이 옳다기보다는 의문점을 공유한 느낌이니까 같이 생각해보면 좋을 것 같습니다~

2022-05-02 05:15 UTC, pjh612 commented on app/src/main/java/com/programmers/order/domain/Customer.java
> +	public void changeName(CustomerDto.UpdateCustomer updateCustomer) {
매개변수로 dto를 전달받으면 도메인과 dto의 결합이 생기는 것 같습니다. UpdateCustomer가 변경되면 changeName 함수도 바뀌어야 되는군요? 그렇게 하기보다는 changeName을 호출하는 곳에서 기본 타입의 변수로 넘겨주는 것이 더 좋아보입니다.

심지어 UpdateCustomer는 email과 name의 정보를 담고있는데
changeName에서는 email은 필요없어보이는데 맞나요? 그렇다면 오버페칭(사용하지 않을 데이터 까지 가져옴) 아닐까요?

2022-05-02 05:15 UTC, pjh612 commented on app/src/main/java/com/programmers/order/domain/Customer.java
> +			throw new RuntimeException("name should not empty!");
should not be empty 아닐까요ㅎㅎ..(영알못)

2022-05-02 05:24 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/CustomerController.java
> +			CustomerDto.SaveRequestDto requestDto = getSaveRequestDtoConverter().convert(informationBundles);
- jvm 클래스로드에 대한 역할과 loading, linking, initialization 을 한번 보시면 좋을 것 같슴다!
- 저희 팀원들도 해당 주제로 스터디 진행하며 아주 * INFINITE 좋을 것 같슴다!  
  - @Jo-GyuHyeon 멘토님은 어떻게 생각하시나요?

2022-05-02 05:26 UTC, whyWhale commented on app/src/main/java/com/programmers/order/domain/Customer.java
> +			throw new RuntimeException("name should not empty!");
- 이름은 공백이 아니여야만 하다! 이런 뜻이였습 🥕  !

2022-05-02 05:37 UTC, whyWhale commented on app/src/main/java/com/programmers/order/domain/Customer.java
> +	public void changeName(CustomerDto.UpdateCustomer updateCustomer) {
1. 해당 의존성 관련하여 저도 고민이 있는데 다음에 한번 애기 나눠보시면 좋을 것같아요!
  - 제가 생각할 때는 dto가 domain을 알게되는 것(메소드의 파리미터로부터) 서부터 의존 관계가 형성(결합)된다고 할 수 있는지가 개인적으로 궁금했습니다. 제가 생각하는 의존성이라함은 어떤 행위를 동작함에 있어 해당 객체가 아니면 동작할 수 없는 것으로 이해하고 있습니다. 코드 기반으로는 즉 참조를 통해서 의존성이 생긴다고 할 수 있습니다. 그런데 해당 매소드의 파라미터로 인해 결합이 생겨 의존성이 생기는 것인지 저도 의문이 듭니당 ... ㅠㅠ

2. email은 식별자용으로 사용하고 있습니다.!
- 해당 업데이트할 도메인이 무엇인지 먼저 판별하는데 사용하고 있습니다!
- 현제 시점에서는 name 하나만 넘겨주어도 되지만! 이름외에 추가로 확장할 스펙이 있을수도 있다고 생각했습니다.

2022-05-02 06:12 UTC, whyWhale commented on app/src/main/java/com/programmers/order/exception/ServiceException.java
>  public class ServiceException {
### 장점
1. 관리적 측면 장점이 있습니다.
 - 예외를 커스텀함에 따라 비례적으로 패키지 내부안에 소스가 늘어나게 되면서 가시적으로 복잡해질 수 있다고 판단했습니다. 그래서 해당 레이어별 또는 도메인 별로 예외 및 오류를 맞이함에 따라 어디에서 발생되는지 파악하기 용이하다고 판단했습니다!
2. 메모리에 모두 올리지 않는 장점을 동일하게 가져갈 수 있다.
- 해당 nested로 관리함에 용이성을 얻는 것과 동시에 성능에 미치는 영향이 있다면 좀 문제가 될 수 있다고 생각했습니다. 하지만 메모리 성능에 영향을 악 영향을 끼치지 않는 것으로 알고 있습니다.(실제 static이 붙은 모든 것들이 메모리에 올라가진 않습니다. 해당 내용관련하여 class loader의 initalization, loading를 참고하면 좋을 것 같습니다)
3. 오직 한번만 클래스가 로딩됨을 보장할 수 있습니다. 

### 단점
- 단점이라 함은 내부적으로 분리해도 그 안에서 또한 소스들이 증가 할 수 있습니다. 하지만 현재로서는 해당 예외들을 깔끔하게 분리함에 따라 어떤 레이어에서 예외를 맞이했는지 실시간으로 파악하기에도 용이하며 코드 가독성 또한 좋을 것으로 판단했습니다. 
- 잘 사용하지 못하면 치명적인 오류를 맞이 할 우려가 있다는 것입니다. 실제로 서비스를 운영하면서 장애를 맞은 경험은 없지만 현재 제가 알고 있는 로드와 초기화 시점 마다 테스트를 해본 결과 메모리가 중복해서 잡히거나 스레드 세이프의 보장하지 않음에 대한 이슈는 겪어보지를 못했습니다! 이번 내용을 기반으로 T.S 하면 좋을 것 같습니다.!!

2022-05-02 16:22 UTC, HYEBPARK reviewed
병연님 ! 직접 물어보고 대답해주셔서 많이 배웠습니다 !! 수고많으셨습니다 😊👍

2022-05-02 16:22 UTC, HYEBPARK commented on app/src/main/java/com/programmers/order/controller/CustomerController.java
> +		boolean isRenter = true;
isRenter는 isReEnter 라는 뜻일까요 !? ㅎㅎ 
아니면 isRunnable 어떨까요 !? 😊

2022-05-02 16:35 UTC, HyoungUkJJang reviewed
고생하셨습니다 ! 깊게 고민하신 흔적이 보여서 저도 많이 배워가는 것 같습니다 !

2022-05-03 04:22 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/CustomerController.java
> +		boolean isRenter = true;
오호! 👍🏼  감사함당

2022-05-06 03:50 UTC, Jo-GyuHyeon requested changes
고생하셨습니다. 늦게 리뷰를 하느라 오랫동안 기다리셨을 것이라 생각이 듭니다.
한번에 리뷰해야 할 내용이 많아 따로 얘기를 해보는 것이 어떨까 싶어서 많이 남기지 않게 되었습니다.
시간되실때 저랑 함께 전반적인 리뷰를 진행 해보는것을 제안드립니다.

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/domain/Customer.java
> +	public void changeName(CustomerDto.UpdateCustomer updateCustomer) {
[블로그 Effective Java Item 51. 메서드 시그니처를 신중히 설계하라](https://icarus8050.tistory.com/102) 링크 함께 보면 어떨까요?

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/exception/ServiceException.java
>  public class ServiceException {
[Java Custom Exceptions and Best Practices](https://howtodoinjava.com/java/exception-handling/best-practices-for-for-exception-handling/) 해당 링크도 함께 참고하여 TS 로 진행 하면 어떨까요?

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/io/Console.java
>  	}
Message 파라미터가 없는 read() 메서드를 오버로딩으로 제공하는 것은 어떨까요?
message 파라미터가 없는 만큼 기본 메세지를 사용 가능 하다고 생각 합니다.

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/manager/PercentVoucherManager.java
> +				!VoucherConstraint.PERCENT_VOUCHER.isViolate(Long.parseLong(percent));
Manger 클래스의 역할은 무엇인가요? 
Component 어노테이션을 선택한 이유는 무엇인가요?
파싱에 대한 유효성 검사는 상위에서 할 수 있지 않았을까? 라고 생각이 들고 있습니다.

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/repository/customer/CustomerJdbcRepository.java
> +			log.error(LogMessage.ErrorLogMessage.getPrefix(), LogMessage.ErrorLogMessage.NOT_EXECUTE_QUERY);
insert() 구현 로직안에 update 변수명은 오타가 있는듯 합니다.

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/repository/customer/CustomerJdbcRepository.java
> +	}
공통적인 코드가 눈에 보이는 것 같습니다.
혹시 중복 코드를 조금 줄일수 있는 방법은 없을까요?

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/repository/voucher/FileVoucherRepository.java
> +			log.error(LogMessage.ErrorLogMessage.getPrefix(), LogMessage.ErrorLogMessage.NOT_FOUND_FILE);
파일이 없다면 파일을 생성 하는 방법은 어떨까요?

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/service/CustomerService.java
> +	public Optional<Customer> save(CustomerDto.SaveRequestDto saveRequestDto) {
save() 의 기대되는 동작은 데이터를 저장하는 행위라고 생각합니다.
Optional 보다는 제대로 저장이 되지 않았다면 예외를 발생하는 것이 더 적합할것이라 생각합니다.
그렇지 않으면 모든 로직이 Optional 로 처리가 될것이라 생각합니다.

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/service/CustomerService.java
> +					.orElseThrow(() -> new DomainException.NotFoundResource(ErrorMessage.CLIENT_ERROR));
update() 를 하기위해 find() 기능 또한 내부적으로 동작하는 것을 확인하였습니다.
위의 `CustomerDto.SaveRequestDto` 처럼 `toCustomer()` 혹은 `toEntity()` 의 기능을 사용한다면 해당 메서드는 하나의 일만 책임을 지게 될 것이라 생각하는데 병연님 의견이 궁금합니다. :smile:

2022-05-06 03:50 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/service/CustomerService.java
> +	public Optional<UUID> registerVoucher(CustomerDto.RegisterVoucherDto registerVoucherDto) {
voucher 서비스이기에 `registerVoucher()` 뒤에 voucher 라는 네이밍을 빼도 자연스럽다고 생각합니다.

2022-05-17 16:53 UTC, Jo-GyuHyeon requested changes

2022-05-17 16:53 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/service/CustomerService.java
> +		}
924 라인에서 예외가 발생했을때 해당 catch 구문이 잡힐 것이라 예상을 하신것인가요?

2022-05-21 08:53 UTC, Jo-GyuHyeon approved these changes
Manager 에서 명확하게 어떤 행위를 하는 것인지 네이밍을 변경하니 더 좋은것 같습니다.
고생하셨습니다. 해당 PR 에서 더 얘기 하고 싶은 부분이 있을까요?

2022-05-25 14:39 UTC, whyWhale commented
없습니다!!
리뷰 감사합니 🥕 !!

2022-05-25 14:39 UTC, merged