[2기-C 박현지] Product 엔티티 및 리포지토리 구현 코드리뷰 부탁드립니다!
prgrms-be-devcourse/springboot-basic pull request #429
Opened 2022-04-27 12:29 UTC by rioreo22

## 📌 과제 설명 

+ Product-상품
+ Customer-고객
+ Blacklist-블랙리스트
+ Voucher-바우처
+ Wallet-지갑

의 엔티티 및 리포지토리 구현까지 진행했습니다.

## 👩‍💻 요구 사항과 구현 내용 

27일 `e426fdf` 커밋 이후의 내용입니다!

+ Product 상품 - 엔티티 및 리포지토리 구현

## 추가한 내용은 다음과 같습니다
+ Product & Test
+ ProductRepository Interface
+ ProductStatus
    + stock 재고 값에 따라서 status 를 설정하고 바우처 사용 가능 , 불가능 상품 상태를 처리하기 위해 추가하였습니다.
+ JdbcProductRepository & Test

## ✅ 피드백 반영사항  

두런두런 때 피드백 반영하여 전체적으로 코드 수정하였습니다!
+ 패키지 구조 통일
+ 패키지 이름 repository -> persistence 로 변경
+ repository Integerface를 domain 패키지로 이동
+ VoucherFactory -> voucherInterface에 static 메소드 create로 추가
+ 구아바 라이브러리 사용 
등등

## ✅ PR 포인트 & 궁금한 점 
다음 PR때는 서비스 단위로 PR 올리겠습니다. 감사합니다!

2022-04-27 12:39 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/domain/product/domain/Product.java
> +    /*  상품 상태 */
앞 부분 주석 공백 수정하겠습니다!

2022-04-27 13:31 UTC, woogiekim requested changes
파일 개수보고 좌절했는데....
지운 파일에 대한내용이 많았네요 ㅎ

코멘트 남긴거 보시고 조사해보는 시간 가지면 좋겠네요

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/customer/persistence/JdbcCustomerRepository.java
> +        }
반환 결과가 1개 행이 아닌경우가 정상인걸까요? 이걸 복구해서 다른 처리를 또 해주고 그래야할까요?

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/customer/persistence/JdbcCustomerRepository.java
> +            log.error(MessageFormat.format("findByName: {0} 반환 결과가 1개 행이 아닙니다.", name));
이름은 고유한가요? 당연히 여러행 나올수 있지 않을까요?

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/customer/persistence/JdbcCustomerRepository.java
> +            log.error(MessageFormat.format("findByEmail: {0} 반환 결과가 1개 행이 아닙니다.", email));
이메일은 보통 고유하죠. 1개이상 반환결과가 나오는게 정상이라고 할 수 있을까요?

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/product/domain/Product.java
> +    ProductStatus status;
접근 제어가 빠졌네요

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/product/domain/Product.java
> +    }
이거는 필드에 아예 박혀있어도 되지 않나요? 혹시 이렇게 따로 메서드로 뺀 이유가 있을까요?

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/product/domain/Product.java
> +    }
이게 상품이 생성될때만 결정되는 거네요?
stock 개념을 넣으면 만들어야할것들이 더 많이 있을거같은데, 빼는건 어떻게 보나요?

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/voucher/persistence/JdbcVoucherRepository.java
> +        }
이런거는 그냥 구아바 써도 될지 않을까 싶어요

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/domain/wallet/persistence/MemoryWalletRepository.java
> +        checkState(storage.get(wallet.getId()) == null, "이미 존재하는 Wallet 입니다.");
checkNotNull 은 어떤가요?

2022-04-27 13:31 UTC, woogiekim commented on src/main/java/org/prgrms/vouchermanager/infrastructure/shell/VoucherManagerShell.java
>              log.error(e.getMessage());
이거보면 unchecked 예외는 사용자에게 나가는 메시지가 아니라는걸 알수 있죠?

에러 체크만을 위한거면 runtime을 상속해서 쓰는게 어떤 이점이 있어서 그런 선택을 하신건지 궁금하네요

2022-04-27 13:31 UTC, woogiekim commented on src/main/resources/banner.txt
> +                                                                                                             `?8888P
깨알 디테일이군요 ㅎㅎㅎ

2022-04-27 13:31 UTC, woogiekim commented on src/test/java/org/prgrms/vouchermanager/domain/product/persistence/JdbcProductRepositoryTest.java
> +    }
이런 설정 중복이 눈에 보이네요 중복을 제거 해볼수는 없을까요?

2022-04-27 13:31 UTC, woogiekim commented on src/test/resources/test_schema.sql
> +);
이거는 왜 있죠?

2022-04-27 14:19 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/domain/product/domain/Product.java
> +    }
이 부분도 id랑 동일한 이유로 데이터 바인딩할 때 문제가 되어서 뺐습니다!

2022-04-27 14:21 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/domain/product/domain/Product.java
> +    }
아하 넵 그러네요! 제외하겠습니다!

2022-04-28 16:41 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/domain/customer/persistence/JdbcCustomerRepository.java
> +            log.error(MessageFormat.format("findByName: {0} 반환 결과가 1개 행이 아닙니다.", name));
List<Customer> findByName()으로 수정했습니다!

2022-04-28 16:41 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/domain/customer/persistence/JdbcCustomerRepository.java
> +            log.error(MessageFormat.format("findByName: {0} 반환 결과가 1개 행이 아닙니다.", name));
List<Customer> findByName()으로 수정했습니다!

2022-04-28 16:42 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/domain/customer/persistence/JdbcCustomerRepository.java
> +            log.error(MessageFormat.format("findByName: {0} 반환 결과가 1개 행이 아닙니다.", name));
List<Customer> findByName(String name)으로 수정했습니다!

2022-04-28 16:42 UTC, rioreo22 commented on src/main/java/org/prgrms/vouchermanager/domain/customer/persistence/JdbcCustomerRepository.java
> +            log.error(MessageFormat.format("findByName: {0} 반환 결과가 1개 행이 아닙니다.", name));
List<Customer> findByName(String name)으로 수정했습니다!

2022-05-01 23:34 UTC, woogiekim commented on src/test/resources/test_schema.sql
> +);
테스트용으로 따로 DDL 이 필요한가? 라는 물음이었습니다.

2022-11-02 14:51 UTC, closed without merging