[2기-P] 마지영 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #442
Opened 2022-04-28 05:53 UTC by JiyoungMa

## 📌 과제 설명 

### W1 리팩토링

- SpringBoot Basic Application
- Voucher List
- Console Input
- Console Output
- Voucher Controller
- DefaultNotUsedVoucher

### Voucher

- Jdbc Voucher Repository
- Jdbc Voucher Repository Test
- Voucher Service
- Voucher Service Test

### Customer

- Customer
- Customer Repository
- Customer Repository Test
- Customer Service
- Customer Service Test

### Wallet

- Wallet
- Wallet Repository
- Wallet Repository Test
- Wallet Service
- Wallet Service Test

## 👩‍💻 요구 사항과 구현 내용 

- Repository
    - toParamMap() : 객체의 각 field를 sql 파라미터와 맵핑시킬 수 있도록 함
    - voucherRowMapper : sql 쿼리의 결과를 각 타입의 객체로 만드는 역할을 함
    - findById() : Id로 특정 객체를 찾는데, 없어서 EmptyResultDataAccessException이 발생하면  Optional.empty()를 리턴한다.
    - save~~~() : 객체를 DB에 insert하는데, 만약 오류가 나서 insert한 결과가 1이 아니라면 Optional.empty()를 리턴한다. **(PR 쓰면서 생각났는데 try catch로 sql에서 발생할 exception 처리도 추가해야 할 것 같습니다. W3에서 추가하는걸로....ㅠ)**
    - getAll~~~() : table의 모든 객체들을 List<객체 타입>로 리턴
    - Wallet의 경우 find 종류가 여러가지 : voucher id로 wallet들을 찾는 경우, customer id로 wallet들을 찾는 경우, voucher id & customer id로 특정 하나의 wallet을 찾는 경우
- Repository Test
    - DB와의 연결을 확인하는 부분이기 때문에 Config.class를 통해 의존 자동 주입을 받아서 Test 함
    - @BeforeEach : 각 테스트 실행 전에, 테스트들이 서로 독립적으로 실행 될 수 있게, 모든 테이블을 비우고, 초기 데이터를 추가하는 작업을 함
    - Repository의 모든 메소드에 대한 테스트 코드를 작성함

- Service
    - create~ : 입력받은 값을 바탕으로 객체를 만드는 메소드, Voucher의 경우 VoucherList의 getConstructor와 getVoucherType을 사용함
    - checkDuplication : save하기 전에 Repository의 find를 사용해서 이미 해당 객체가 있는지 확인한다. Voucher의 경우 findById, Customer의 경우 findByEmail, Wallet의 경우 findbyCustomerandVoucher를 사용함
    - save~ : checkDuplication을 사용해서 이미 존재하는 객체가 있다면 Optional.empty()를 리턴한다.
    - getAll~ : repository의 getAll~~()을 사용해서 모든 객체를 리스트로 리턴

## ✅ 피드백 반영사항 

### <W1 Refactoring>

- SpringBoot Basic Application : Voucher Controller에서 CustomOutput과 Custom Input을 사용하는 부분을 Spring Boot Basic Application으로 옮기고, Command Enum도 Spring Boot Basic Application으로 옮겨서 Controller가 맡은 일만 하도록 함
- Voucher Controller : Custom Output & Input을 사용하는 부분을 SpringBoot Basic Application으로 넘겼다.
- Voucher List
    - Voucher 종류들도 Enum으로 관리해서 바우처 종류가 추가될 때, Enum에만 추가하고 다른 부분은 최소한으로 수정할 수 있도록 구현
    - getConstructor : 처음 Voucher 객체를 만들때 사용함
    - makeVoucher : 특정한 값을 가진 객체를 만들때 사용함
    - static getVoucherType : 어떤 종류의 바우처인지 VoucherList 타입으로 리턴함
    - static makeVoucherByType : 어떤 종류의 바우처인지 String을 통해 나타내고, 해당 객체의 값들을 넘겨주면, makeVoucher을 통해 특정한 값을 가진 바우처 객체를 리턴함
- Console Input & Output
    - Voucher List를 기반으로 변경함
    - Console Input : getNewVoucherInfo()에서 VoucherList.values()를 이용해서 입력 받은 바우처 종류를 특정함
    - Console Output : printVoucherList()에서 VoucherList.values()를 이용해서 바우처의 종류를 프린트함
- DefaultNotUsedVoucher
    - Voucher가 존재하지 않는 경우를 대비한 null값 대신 사용할 기본 객체

## ✅ PR 포인트 & 궁금한 점 

- 추가적으로 할 수 있는 예외가 있을까요? 예외 생각하기가 제일 어렵습니다.....ㅠ
- service와 repository경우 mock사용 말고 다른 방식으로 테스트를 하는 방법이 있을까요? 굳이 repository까지 주입을 받을 필요는 없어보여서..
- W3에서는 logger도 추가하려고 하는데, logger를 aop로도 많이 사용하나요?

2022-04-30 07:41 UTC, SeokRae requested changes
![image](https://user-images.githubusercontent.com/17922700/166096657-b1de38ea-2d94-4dfc-8247-b435998f5d4e.png)

고생하셨습니다. 지영님

많은 고민을 하신 것이 느껴지는 코드 였습니다. 
커멘트로 남기는 것보다 게더에서 봽고 같이 이야기 하는 것이 더 좋을 것 같습니다.

2022-04-30 07:41 UTC, SeokRae commented on src/main/java/com/prgrms/kdt/springbootbasic/entity/voucher/DefaultNotUsedVoucher.java
> +        super(null, LocalDateTime.now().truncatedTo(ChronoUnit.MILLIS));
.truncatedTo(ChronoUnit.MILLIS)); 
메서드는 어떠한 기능을 하는 api인가요?

2022-04-30 07:41 UTC, SeokRae commented on src/main/java/com/prgrms/kdt/springbootbasic/inputPackage/ConsoleInput.java
> +    public VoucherInfo getNewVoucherInfo() throws IOException {
throws를 던졌을 때는 클라이언트 쪽에서 처리 해야 하는 특별한 이유가 있을 것 같은데 
별도로 처리하는 로직이 없는 것으로 보입니다.
그럼 내부적으로 처리할 수 없을까요?

2022-04-30 07:41 UTC, SeokRae commented on src/main/java/com/prgrms/kdt/springbootbasic/repository/CustomerRepository.java
> +        return jdbcTemplate.query("Select * from customers",customerRowMapper);
문제가 없는 코드이긴 하지만, 데이터 전체 조회라는 기능보다는 페이징이 좋을 것 같습니다.

2022-04-30 15:17 UTC, SeokRae commented
추가적으로 게더에서 이야기 했던 부분까지 리펙토링 되면 머지하도록 하겠습니다.!

2022-05-03 20:37 UTC, JiyoungMa commented
리팩토링 완료하였습니다!

2022-05-04 01:53 UTC, merged