[2C-남득윤] 고객, 바우처와 관련된 기능, 초기 데이터 생성 기능 개발
prgrms-be-devcourse/springboot-basic pull request #452
Opened 2022-04-28 15:14 UTC by ndy2

## 📌 과제 설명 
1. 고객과 바우처의 관계와 관련된 기능에 대한 persistence 레벨의 메서드를 개발
- 바우처의 필드 (엔티티와 db모두)에 customerId 추가
- 고객의 아이디로 바우처를 전체 조회하는 메서드 `VoucherRepository.findByCustomerId` 개발
    - 이를 활용하는 서비스 및 커맨드(컨트롤러) 미구현
 
2. 시스템이 실행할 수 있는 차단 (블랙리스트) 고객 전체 조회 기능 구현 
- `CustomerService.findAllBlocked`

3. 초기 데이터 자동 생성 기능 구현
- `util.initdata` 패키지에서 `@PostConstruct` 를 활용하여 서비스를 주입 받아 데이터 램덤 생성 후 삽입
- `javafaker` , 아파치 커먼스 `RandomUtils` 라는 기능들을 활용하였습니다.
-  초기 데이터로 사용자 100명 (차단 여부 반반)
-  소유자가 있는 바우처 400개, 소유자가 없는 바우처 100개 (fixed, amount 반반)
   - fixed : 1000 ~ 20000, 1000단위 램덤 생성
   - percent : 0~ 100, 10 단위 램덤 생성 

4. 로그인 기능 흉내내는 기능 구현
- `util.security` 패키지에서 초기데이터에서 생성한 사용자중 램덤하게 한명을 선택하여 로그인한 것으로 간주
- `CustomerSelector` 에서 한명 골라서 `CustomerHolder` 에 저장
- `PromptProvider` 에서 선택(로그인)된 고객의 이름 출력 추가

## ✅ 피드백 반영사항
1. 도메인이 담당하던 콘솔 출력 문자열 생성의 책임을 콘솔 패키지로 이동하였습니다.
`Voucher.toDisplayString` -> `view.console.ToStringResolver`

## ✅  ToDo, 다음 PR 예정 사항
- 선택된 고객이 자신의 바우처만 조회하는 기능 추가
- `상품` 엔티티 추가 

## ✅ PR 포인트 & 궁금한 점
`CustomerServiceTest`의
```java
@Test
    void 성공_차단고객_전체조회() {
        //given
        List<Customer> customers = List.of(customer(), customer());
        when(customerRepository.findAllBlocked()).thenReturn(customers);

        //when
        List<Customer> foundCustomers = customerService.findAllBlocked();

        //then
        assertThat(foundCustomers).hasSameElementsAs(customers);
    }

```
테스트에서 사실 서비스의 테스트 대상 메서드는 리포지토리에게 위임하기만 하고 전혀 데이터에 관여하지 않습니다.
사실 이 메서드는 차단된 고객만을 반환받을 것을 기대하고 위임하지만 전달받은 리스트가 차단된 고객만을 가지고 있는지는 관심이 없습니다.

차단 고객만을 반환하는것에 대한 책임 및 검증은 리포지토리 레벨에서 되고 있습니다. 

따라서 차단되지 않은 사용자를 포함한 리스트를 반환하도록 스터빙 하여도 위 테스트는 통과합니다.
이런 테스트도 논리상 문제가 없는 것일까요?

2022-04-30 07:27 UTC, woogiekim requested changes
목은 언제 사용하는건가요?

그게 궁금해지네요

DM 주세요

2022-04-30 07:27 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/domain/Voucher.java
> +    public UUID getId() {
그냥 롬복 사용해주세요.

@Data 같은 무책임한 롬복 사용을 안할거라는걸 잘 알고, 이야기도 했기 때문에 이제는 롬복을 써도 된다고 봅니다.

2022-04-30 07:27 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/persistence/JdbcVoucherRepository.java
> +        Map<String, Object> paramMap = new HashMap<>();
이런 오브젝트 바인딩에 Map을 이용하는 장단점은 무엇이 있을까요?

2022-04-30 07:27 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/persistence/JdbcVoucherRepository.java
> +            paramMap.put("percent", ((PercentDiscountVoucher)voucher).getPercent());
객체 생성의 책임이 과연 JdbcVoucherRepository에게 있는 걸까요?

2022-04-30 07:27 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/persistence/MemoryVoucherRepository.java
> +        return new ArrayList<>(storage.values()).stream()
Stream.of 를 이용해도 괜찮을거같은데 어떤가요?

2022-04-30 07:27 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/util/initdata/InitDataConstructor.java
> + * 초기 데이터 생성자
보통의 경우 초기 데이터 생성을 하는게 일반적이지 않다고 저는 생각하는데,
더 상세한 설명이 있었으면 좋겠어요

2022-04-30 07:27 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/util/security/CustomerHolder.java
> +public class CustomerHolder {
Holder 라고하기에는 이거 상태가 계속 변하는거 아니에요?

2022-04-30 07:27 UTC, woogiekim commented on src/main/java/org/prgrms/deukyun/voucherapp/view/console/ToStringResolver.java
> +public class ToStringResolver {
유틸 성격을 지닌 클래스를 만드는게 과연 좋은선택이었을까 라는 생각이 듭니다.

2022-04-30 07:27 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/view/console/ToStringResolverTest.java
> +class ToStringResolverTest {
화면에 나가는거 까지 테스트할 필요가 있나 싶은 생각이 드네요

2022-04-30 07:27 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/view/command/CreateVoucherCommandTest.java
> +            inOrder.verify(voucherService).insert(any(PercentDiscountVoucher.class));
이게 뭘하는거죠?

2022-04-30 07:27 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/util/security/CustomerSelectorTest.java
> +    void 성공_램덤한_사용자_선택_후_홀더에_담기() {
랜덤을 테스트하는건 조금 무리가 있습니다.

랜덤 알고리즘을 직접 작성한거 아니라면, 안하는게 좋아요

2022-04-30 07:27 UTC, woogiekim commented on src/test/java/org/prgrms/deukyun/voucherapp/util/initdata/VoucherDataTest.java
> +        return argThat(voucher -> voucher.getCustomerId().isPresent());
갑자기 왜 권장하지 않은 검증 방식을 선택하신거죠?

2022-04-30 08:22 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/domain/Voucher.java
> +    public UUID getId() {
넵! `@Getter` 를 적어놓고 명시적인 getter 를 제거하는걸 깜빡했네요

2022-04-30 08:22 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/persistence/JdbcVoucherRepository.java
> +        Map<String, Object> paramMap = new HashMap<>();
Map 을 사용하면 편하지만 정의되지 않은 키, 밸류 타입의 파라미터를 put 하는 것을 제약할수 없을거 같네요 

찾아보니까 스프링 JDBC에서는 `SqlParameterSource`, `SqlParameter`로 각각 맵과 밸류를 추상화 하여 이런 기능들을 제공하는거 같습니다.

2022-04-30 08:26 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/domain/voucher/persistence/JdbcVoucherRepository.java
> +            paramMap.put("percent", ((PercentDiscountVoucher)voucher).getPercent());
앗 이부분은 파라미터 바인딩을 위해 맵을 생성하는 로직 같습니다.

아래 `voucherRowMapper` 에서 resultSet의 필드들을 뽑아네서 바우처 팩토리를 통해 바우처를 생성하도록 하였는데 바인딩 하는 로직도 팩토리로 제거하는 것이 좋을까요?

2022-04-30 09:00 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/view/console/ToStringResolver.java
> +public class ToStringResolver {
음... 주입 받아 인스턴스 메서드로서 사용하는 것이 더 적절한거 같네요

2022-05-05 05:57 UTC, ndy2 commented on src/main/java/org/prgrms/deukyun/voucherapp/view/console/ToStringResolver.java
> +public class ToStringResolver {
음.. dto 를 만드는 것도 더더 적절한거 같네요

2022-11-02 14:50 UTC, closed without merging