[길근오] 바우처 서비스 REST API 기능 & 테스트
prgrms-be-devcourse/springboot-basic pull request #463
Opened 2022-04-30 09:49 UTC by hymn-fly

## 👩‍💻 요구 사항과 구현 내용
- Spring MVC 를 이용하여 JSON, XML를 지원하는 REST API 개발함
  - VoucherRestController
  - dto
    - CreateVoucherRequest
    - DeleteVoucherResponse
    - EmptyJsonResponse

## ✅ PR 포인트 & 궁금한 점
- REST API 개발이라고 적어놓긴 했는데, 사실 REST 가 잘 지켜지지 않은것 같습니다. 혹시 rest를 지키기 위해 좀 더 수정하거나 추가해야할 점들은 어떤점들이 있을까요?

- Empty json을 반환하고 싶어서 EmptyJsonResponse를 만들었는데 ResponseEntity로 반환을 하려면 그 안의 객체가 같은 type이어야 하더라구요. (VoucherRestController.getVoucher() 참고) .. 혹시 Empty json을 반환하려면 어떤 방법이 있을까요?

2022-05-01 23:31 UTC, woogiekim requested changes
엄격하게 REST 를 지켜야한다면, 생각해봐야 할 요소들이 굉장히 많을 것 같습니다.

저는 적절한 기준을 정하고 그 기준에 맞게 잘 작성만 한다면 문제없다고 봅니다.

고생하셨습니다. 코메트 확인해주세요

2022-05-01 23:31 UTC, woogiekim commented on src/main/java/org/prgms/controller/api/VoucherRestController.java
> +    public ResponseEntity<Voucher> createVoucher(@RequestBody CreateVoucherRequest voucherRequest) {
여기는 왜 ResponseEntity 로 반환하는건가요?

2022-05-01 23:31 UTC, woogiekim commented on src/main/java/org/prgms/controller/dto/EmptyJsonResponse.java
> +public class EmptyJsonResponse {
이거는 왜 필요한 건가요?

2022-05-01 23:31 UTC, woogiekim commented on src/test/java/org/prgms/controller/api/VoucherRestControllerTest.java
> +    private VoucherService voucherService;
VoucherService 를 모킹해서 @WebMvcTest 하면
어떤걸 테스트하는 것인가요?

2022-05-01 23:31 UTC, woogiekim commented on src/test/java/org/prgms/repository/VoucherRepositoryTest.java
> +        List<Voucher> vouchers = voucherRepository.findAll();
삭제 대상만 조회해보고 null 이 리턴 되는걸 확인하는게 더 명확하지 않을까요?

2022-05-01 23:31 UTC, woogiekim commented on src/test/java/org/prgms/repository/WalletRepositoryTest.java
> +@ActiveProfiles("test")
중복을 없애는 방법이 있지 않을까요?

2022-05-08 08:17 UTC, hymn-fly commented on src/main/java/org/prgms/controller/api/VoucherRestController.java
> +    public ResponseEntity<Voucher> createVoucher(@RequestBody CreateVoucherRequest voucherRequest) {
해당하는 함수는 특별히 ResponseEntity를 이용할 이유가 없는것 같습니다 수정하겠습니다!

2022-05-08 08:19 UTC, hymn-fly commented on src/main/java/org/prgms/controller/dto/EmptyJsonResponse.java
> +public class EmptyJsonResponse {
빈 json값을 반환하기 위해서 만들었는데 EmptyJson반환이 잘 되지 않더라구요

2022-05-08 08:29 UTC, hymn-fly commented on src/test/java/org/prgms/controller/api/VoucherRestControllerTest.java
> +    private VoucherService voucherService;
WebMvcTest를 이용해서 Controller 테스트를 구성 해보았는데, mocking을 해서 하는 것보다 VoucherService의 로직까지 통합해서 테스트 하는편이 더 좋을 까요??

2022-05-08 08:29 UTC, hymn-fly commented on src/test/java/org/prgms/repository/VoucherRepositoryTest.java
> +        List<Voucher> vouchers = voucherRepository.findAll();
넵!

2022-05-08 08:37 UTC, hymn-fly commented on src/main/java/org/prgms/controller/dto/EmptyJsonResponse.java
> +public class EmptyJsonResponse {
빈 json을 반환하기 위해서는 어떤 방식이 좋은가요??

2022-11-02 14:49 UTC, closed without merging