[2기-C] 정다현 SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #495
Opened 2022-05-08 10:08 UTC by sdardew

## 📌 과제 설명
바우처를 관리하는 웹 애플리케이션과,
바우처 관리를 위한 rest api를 구현했습니다.

## 👩‍💻 요구 사항과 구현 내용
- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
    - [X] thymeleaf 템플릿 적용
- 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [X] 조회페이지
    - [X] 상세페이지
    - [X] 입력페이지
    - [X] 삭제 기능
- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [X] 전체 조회기능
    - [X] 조건별 조회기능
    - [X] 바우처 추가기능
    - [X] 바우처 삭제기능
    - [X] 바우처 아이디로 조회 기능

## ✅ PR 포인트 & 궁금한 점
기능 구현 + 테스트를 묶어서 한 단위로 커밋하는 것과 기능 구현 따로 테스트 따로 구분해서 커밋하는 것 중에 어떤 방식으로 하는 것이 바람직 한지 여쭤보고 싶습니다!
저는 DB에 저장할 때 ENUM 값을 숫자로 변경했었습니다. DB에 저장할 때 ENUM 이름 값을 문자열 그대로 저장하는 것이 좋을 지 혹은 다른 값으로 변경해서 저장하는 것이 좋은지 궁금합니다.

2022-05-11 10:18 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/api/VoucherRestController.java
> +public class VoucherRestController {
@ReuqestMapping("/api/v1/vouchers")
이걸 사용하면 좋을거 같네요.

2022-05-11 10:18 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/api/VoucherRestController.java
> +  @GetMapping("/api/v1/voucher/{voucherId}")
REST API는 무조건 리소스를 복수로 사용합니다.
```suggestion
  @GetMapping("/api/v1/vouchers/{voucherId}")
```

2022-05-11 10:41 UTC, ksy90101 requested changes
피드백 남겼어요~

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/api/VoucherRestController.java
> +  @GetMapping("/api/v1/voucher/{voucherId}")
queryString으로 필터 역할로 getVoucherByVoucherId를 구현해보시겠어요?

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/service/CustomerService.java
> +  public List<Customer> getCustomerList() {
```suggestion
  public List<Customer> getCustomers() {
```

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/JdbcVoucherRepository.java
> +    }
쿼리빼고는 모두 서비스에 로직을 넣어보시겟어요?

2022-05-11 10:41 UTC, ksy90101 commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@jdbcTest로 바꿔서 작성해보세요~

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/VoucherType.java
> +  private VoucherType(int selectedNumber, String simpleClassName) {
enum의 생성자는 디폴트 접근제어자를 사용하고 잇어요!
결론 provate뺴도 됩니다 :)

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/VoucherType.java
> +  }
이 메서드 안쓰이는거 같은데 삭제하면 어떨까요?

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/VoucherType.java
> +    throw new RuntimeException("[VoucherTypeException] 존재하지 않는 클래스입니다");
의미잇는 예외 객체를 사용해부세요.

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ConsoleCommandV2.java
> +  EXIT("exit", job -> {
EXIT("exit", job -> false),

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/console/ConsoleCommandV2.java
> +  private final String command;
이거 안쓰여요~

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/Customer.java
> +  public void login() {
이거 안쓰여요!

2022-05-11 10:41 UTC, ksy90101 commented on src/test/java/org/prgrms/vouchermanagement/customer/wallet/JdbcWalletRepositoryTest.java
> +    }
```suggestion
  @Bean
  public DataSource dataSource() {
    return DataSourceBuilder.create()
      .url("jdbc:mysql://localhost:3306/voucher_mgmt")
      .username("root")
      .password("root1234!")
      .type(HikariDataSource.class)
      .build();
  }
```

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/FixedAmountVoucher.java
> +    return true;
return MAX_REDUCTION < reduction || reduction <= 0

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +  private void mapToCustomer(List<Customer> allCustomers, ResultSet resultSet) throws SQLException {
이것도 안쓰이는거 같아요.

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +    }};
https://stackoverflow.com/questions/1958636/what-is-double-brace-initialization-in-java

이글을 한번 참고해보세요.

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +    return new HashMap<String, Object>(){{
```suggestion
    return new HashMap<>(){{
```

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/JdbcVoucherRepository.java
> +      log.error("No such voucher");
예외를 던져야 할거 같아요.

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/vo/Name.java
> +  }
이건 안쓰이는거 같아요.

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/console/Output.java
> +  void printIssueCustomer();
다 안쓰입니다.

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/console/Output.java
> +  void printList(List list);
List 제네릭 타입 적어주세요.

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/PercentDiscountVoucher.java
> +    return true;
```suggestion
    return MAX_REDUCTION < reduction || reduction <= 0
```

2022-05-11 10:41 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/controller/VoucherController.java
> +  private static final Logger log = LoggerFactory.getLogger(VoucherController.class);
이거 안쓰이네요!

2022-05-11 10:41 UTC, ksy90101 commented
컨플릭트 나네유

2022-05-14 15:13 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/controller/VoucherController.java
> +  private static final Logger log = LoggerFactory.getLogger(VoucherController.class);
지웠숨니다!!

2022-05-15 13:02 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +    }};
double brace 사용하는 모든 부분 수정했습니다!!

2022-05-15 14:48 UTC, sdardew commented on src/main/java/org/prgrms/vouchermanagement/voucher/voucher/VoucherType.java
> +      if(type.getSimpleClassName().equals(voucher.getClass().getSimpleName())) return type.selectedNumber;
isSimpleClassName 메서드를 찾을 수가 없어서 우선 이 부분은 조금 더 생각해보겠습니다!

2022-05-19 02:35 UTC, closed without merging