[2기-C] 이한주 SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #505
Opened 2022-05-10 18:38 UTC by yanJuicy

## 📌 과제 설명 
바우처 관리 REST API 작성

## 👩‍💻 요구 사항과 구현 내용 
- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [x]  조회페이지
    - [x]  상세페이지
    - [x]  입력페이지
    - [x]  삭제기능
- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x]  전체 조회기능
    - [x]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
JDBC로 Repository 개발을 했을 때 Repository 테스트에서 @SpringbootTest 어노테이션 말고 다른 방법으로 어떻게 할 수 있는지 궁금합니다.

2022-05-16 10:08 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/CommandType.java
> +    }
```suggestion
    private Function<AnnotationConfigApplicationContext, CommandStrategy> job;
    
    CommandType(Function<AnnotationConfigApplicationContext, CommandStrategy> job) {
        this.job = job;
    }
```

2022-05-16 10:32 UTC, ksy90101 requested changes
한번더 보시고 수정해주세요~

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/customer/CustomerFindAllCommand.java
> +    ConsoleOutput consoleOutput;
디폴트 생성자로 하신 이유가 있나요?
불변도 안하시구요!
이유가 궁금합니다.

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/customer/CustomerFindByEmailCommand.java
> +    }
Autowired vs 생성자 빈 주입의 차이

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/model/CustomerInfo.java
> +    }
email에 대한 validate도 추가해보면 어떨까요?
형식이요.

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/VoucherType.java
> +    public static Voucher getSpecificVoucher(VoucherType voucherType, ConsoleInput consoleInput) {
createVoucher 메서드와 중복 코드인거 같은데, 이걸로 해당 코드를 바꿔보면 어떨까요?

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/controller/VoucherApiController.java
> +public class VoucherApiController {
@RequestMapping으로 하면 api/vourchers 중복 제거가 가능합니다.

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/controller/VoucherApiController.java
> +    public List<Voucher> getVouchers(@RequestParam(required = false) String type) {
ResponseEntity를 사용하시면 될거 같아요.

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/controller/VoucherApiController.java
> +        return new ResponseEntity<>(voucherService.getVoucherById(voucherId), HttpStatus.OK);
ResonseEntity는 정적메서드로 만들어 주세요.
```suggestion
        return ResponseEntity.ok(voucherService.getVoucherById(voucherId));

```

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/controller/VoucherApiController.java
> +        }
ExceptionHandler로 빼볼까요?

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/dto/VoucherCreateRequestDto.java
> +    private long discountPercent;
validation 추가해보세요.
Spring Validate 사용해보세요.

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/JdbcTemplateVoucherRepository.java
> +        int update = jdbcTemplate.update(
InsertJbcTemplate 키워드로 insert를 해보실래요?

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/MemoryVoucherRepository.java
> +        return voucherList;
```suggestion
        return new ArrayList<>(vouchers.values());
```

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/BlackListCustomer.java
> +    private static final String csvFile = "file:customer_blacklist.csv";
상수 컨벤션은 무엇일까요!?

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/voucher/CreateVoucherCommand.java
> +    private static final Logger logger = LoggerFactory.getLogger(CommandStrategy.class);
getLogger안에는 구현체를 넣는게 좋을거 같아요.

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/model/CustomerInfo.java
> +        validateName(email);
```suggestion
        validateEmail(email);

```

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/service/CustomerService.java
> +        return jdbcTemplateCustomerRepository.findByEmail(email).get();
```suggestion
        return jdbcTemplateCustomerRepository.findByEmail(email)
            .orElseThrow(() -> new IllegalArgumentException("아아아"));

```

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/JdbcTemplateVoucherRepository.java
> +            throw new RuntimeException("Nothing was inserted");
좀 더 의미있는 예외를 사용하셔야 합니다.

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/JdbcTemplateVoucherRepository.java
> +    public JdbcTemplateVoucherRepository(DataSource dataSource, JdbcTemplate jdbcTemplate) {
```suggestion
    public JdbcTemplateVoucherRepository(JdbcTemplate jdbcTemplate) {

```

2022-05-16 10:32 UTC, ksy90101 commented on src/main/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/JdbcTemplateVoucherRepository.java
> +        if (voucher instanceof FixedAmountVoucher)
https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/

2022-05-16 10:32 UTC, ksy90101 commented on src/test/java/me/programmers/springboot/basic/springbootbasic/voucher/repository/MemoryVoucherRepositoryTest.java
> +        assertThat(memoryVoucherList.size(), is(3));
여기 깨지네요.

2022-05-23 08:07 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/customer/CustomerFindByEmailCommand.java
> +    }
Autowired는 순환참조 문제가 발생해도 사전에 알 수 없다는 단점이 있습니다. 
생성자 주입의 경우 bean을 생성하는 시점에 의존성 주입이 돼야 하는데, 서로가 서로를 주입받아야 하는 상태이기 때문에 에러가 발생하지만, Autowired의 경우는 우선 bean이 생성된 후에 field에 의존성을 주입하므로 정상적으로 의존성이 주입되고 비즈니스 로직을 수행하는 과정에서 에러가 발생하게 됩니다

2022-05-30 04:06 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/command/customer/CustomerFindAllCommand.java
> +    ConsoleOutput consoleOutput;
@Autowired를 사용하는게 편해서 생성자 인자로 넣지 않으려고 했습니다. 
생성자 주입 방식으로 바꿨습니다.

2022-05-30 04:51 UTC, yanJuicy commented on src/main/java/me/programmers/springboot/basic/springbootbasic/customer/BlackListCustomer.java
> +    private static final String csvFile = "file:customer_blacklist.csv";
대문자 입니다

2022-11-02 14:49 UTC, closed without merging