2p/#3 midas
prgrms-be-devcourse/springboot-basic pull request #512
Opened 2022-05-14 12:59 UTC by midasWorld

### 🛠 작업 단위
- [x] Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
  - [x] 조회페이지 구현
  - [x] 상세페이지 
  - [x] 입력페이지 
  - [x] 삭제기능
  

- [ ] Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요.
  - [ ] 전체 조회기능 
  - [ ] 조건별 조회기능 (바우처 생성기간 및 특정 할인타입별) 
  - [ ] 바우처 추가기능 
  - [ ] 바우처 삭제기능 
  - [ ] 바우처 아이디로 조회 기능

2022-05-21 10:13 UTC, Jo-GyuHyeon requested changes

2022-05-21 10:13 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/BaseController.java
> +public class BaseController {
Voucher Controller와 함께 사용할 수도 있었는데 Base 로 따로 빼신 이유는 무엇일까요?

2022-05-21 10:13 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/voucher/CreateVoucherRequest.java
> +    }
Request DTO 에서 toString 을 재정의 한 이유는 무엇일까요?

2022-05-21 10:13 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/voucher/CreateVoucherRequest.java
> +public class CreateVoucherRequest {
DTO가 많아 질수록 Controller 클래스를 패키지에서 찾기 힘들 수 있겠다는 생각이 드는데 이러한 경우에는 대비책이 있을까요?

2022-05-21 10:13 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherController.java
> +            .collect(Collectors.toList()));
인자로 넣기전에 변수로 빼게되면 추후에 디버깅하기 편리함과 코드 가독성 `)));` 중첩 부분을 조금 해결 가능하다고 생각이 듭니다.

2022-05-22 05:06 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/BaseController.java
> +public class BaseController {
인덱스용 페이지를 따로 만드는게 좋겠다 싶어서 넣었었는데... ㅎㅎ
그거는 실제로 만들고 해도 됬었겠군요.. 😓

2022-05-22 05:11 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherController.java
> +            .collect(Collectors.toList()));
아 넵! 계속 습관처럼 쓰고 있네요. 주의 하겠습니다.  😱

2022-05-22 05:13 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/CreateVoucherRequest.java
> +public class CreateVoucherRequest {
DTO 부분이 참 어려운 것 같습니다.. 😭
추후 생각은 web - dto 패키지를 하나 더 만들어서 관리하는 쪽이었습니다.

2022-05-22 05:13 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/CreateVoucherRequest.java
> +    }
아.. 그냥 무지성으로 클래스를 정의하면 ToString을 정의하고 있었습니다.
쓴다고 한다면 테스트 코드 정도 밖에 생각이 안나네요.. 🤔

toString 메서드도 사용할 일이 있을 때만 정의를 하는게 맞을까요?

2022-05-23 15:23 UTC, midasWorld commented
# 🛠 작업 단위

Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요.

- [[d55416d] 바우처 조회 기능 구현 (REST API)](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/d55416d3e40ae896795c195412693e0091454c35)
  - 전체 조회 기능 추가
  - 📌 ApiResponse, ApiError 생성 → 반환 정보를 규격화 하였습니다.
- [[9545a56] 전역 예외 처리 클래스(ExceptionHandler) 생성](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/9545a56f4a2084d05cb9b2a9c718df429a9a26fd)
  - ExceptionHandler 생성(`@ControllerAdvice` 사용)
- [[464dec6] 바우처 ID조회, 등록, 수정, 삭제 추가 (REST API)](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/464dec648a9e868ab35cbc1e8f11b2c35af1143e)
  - VoucherRestController → 각각 기능들 추가하였습니다.
- [[26171f3] 바우처 조회 기능(특정 일자, 특정 타입 조회) 추가](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/26171f382ef2bfe7ebfff60c0e791d9f60d3fe80)
  - 시작일자, 종료일자, 바우처타입을 각각 Optional로 받아서 조회되도록 추가하였습니다.
  - Repository에서 각 Optional 값들을 이용해서 동적쿼리를 만들도록 하였습니다.
- [[f97b251] 📌 NotFoundException 생성 및 적용, BAD_REQUEST 로깅 레벨 debug로 변경](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/f97b251a6da171c3cc3c77ed4f7b6f157a235246)
  - NotFoundException을 별도로 생성하였고, 로깅 레벨은 `warn`으로 설정하였습니다.
  - 위와 동시에 bad_request의 경우는 로깅레벨을 `warn` → `debug`로 변경하였습니다.

# 📌 PR포인트 & 🤔 궁금사항

아래와 같이 생각해서 사용을 했는데, 맞는건지 궁금합니다!

## 1. ApiResponse, ApiError 생성 → 반환 정보 규격화

Commit : [[d55416d] 바우처 조회 기능 구현 (REST API)](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/d55416d3e40ae896795c195412693e0091454c35)

시작은 어떤 책에서 이렇게 쓰길래 좋은거 같아서 사용하게 되었습니만,
이렇게 반환 정보를 규격화 하는 것이, 프론트단에서도 통일성 있게 데이터를 사용하게 되는 점에서 이점이 있다고 생각합니다.

```json
// 반환 값
{
  "success": "성공여부(true/false)",
  "response": "반환값",
  "error": {
    "message": "오류메시지",
    "status": "상태코드"
  }
}
```

- success : response가 null값이라도 이 변수로 성공했는지 판단 여부를 알 수 있어서 필요하다고 생각합니다.
- error : error의 경우에는 여러 정보를 포함할 수도 있다고 생각해서 별도로 클래스를 분리하였습니다.

## 2. NotFoundException을 별도로 분리 및 기존 로깅 레벨 조정

Commit : [[f97b251] 📌 NotFoundException 생성 및 적용, BAD_REQUEST 로깅 레벨 debug로 변경](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/f97b251a6da171c3cc3c77ed4f7b6f157a235246)

- NotFoundException 분리
  - HttpStatus: Not_Found
  - logging-level: warn
- IllegalArgumentException
  - logging-level: `debug`로 변경

### 🫥 NotFoundException 생성 이유

NotFoundException의 경우에는 id값 하나로 조회해서 없을 수도 있겠지만,
다른 테이블과 엮여서 여러 id값을 로깅이나 오류 메시지로 넘겨줘야 될수도 있겠다고 생각했고,
도메인마다 쓰일 수 있다고 생각해서 메시지 전달방식을 커스텀해서 사용해야될 필요성을 느꼈습니다.

### 🔖 로깅 레벨 조정

- NotFoundException의 경우에는 데이터 유실로 인해서 일어날수도 있겠다고 생각해서 로깅 레벨을 warn으로 했습니다.
- bad_request의 경우에는 너무 빈번히 일어날 수 있는 일이라 생각해서 debug로 로깅 레벨을 낮췄습니다.

2022-05-23 15:34 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +        }
이 부분을 아무리 고민을 해봐도, 이게 최선인거 같은데.. 혹시 다른 좋은 방법이 있을까요? 👀

2022-05-25 12:47 UTC, Jo-GyuHyeon approved these changes

2022-05-25 12:47 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherRestController.java
> +        @RequestParam(required = false) Optional<VoucherType> type
시작날짜가 마지막 날짜보다 더 느릴경우엔 어떻게 처리가 되나요???

2022-05-25 12:47 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherRestController.java
> +    public ApiResponse<VoucherDto> create(@RequestBody CreateVoucherRequest request) {
request 에 대한 유효성검사는 따로 하지 않아도 될까요????

2022-05-25 12:47 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +        }
줄이는 방법이라기보다는 중복된 코드가 보입니다. 중복코드를 없애면 부수적으로 줄여지는 효과도 있을 것 이라 기대 됩니다.
또 다른 생각으론 Map<String, Object> parmas 와 String sql 을 묶어서 SqlBulider 같은 객체로 만들어서 컨트롤 해보는 건 어떨까요? 

수도 코드 입니다.

var sqlBuilder = SqlBuilder.builder()
.appent(sqlString1, startDate.map{ key pairTo Value })
.appent(sqlString2, endDate.map{ key pairTo Value })
.appent(sqlString3, type.map{ key pairTo Value })
.build()


return jdbcTemplate.query(sqlBuilder.getSql(), sqlBuilder.getParams(), voucherRowMapper);

2022-05-26 13:25 UTC, midasWorld commented
# 🛠 작업 단위

- [[2cab202]](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/2cab202f60573567fecf1754c064cb07b167a096) SqlBuilder 클래스 생성
  - SqlBuilder 클래스를 따로 생성 → VoucherJdbcRepository에 동적쿼리 부분에 적용
- [[811beda]](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/811beda4b25d227011a3e155151037757a92b7f9) VoucherSearch 클래스 생성
  - 검색 옵션들을 모아서 관리할 수 있도록 클래스 분리
  - start-date > end-date 가 될 수 없도록 유효성 검사 추가
- [[cd24754]](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/cd2475403d17f411647b0850c9dbb890ce278847) Request 클래스 생성자 유효성 검사 로직 추가
  - 요청 받은 값을 바로 유효성 검사해서 실패한다면 서비스 레이어까지 가지 않아도 되도록 추가

2022-05-26 13:29 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +        }
덕분에 동적 쿼리 코드 부분 확실히 줄일 수 있었습니다. 👍
[[2cab202]](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/2cab202f60573567fecf1754c064cb07b167a096) → 해당 COMMIT 내역 입니다.

처음에는 작성해주신 그대로 만들었었는데, 
https://araikuma.tistory.com/483 이 블로그 글을 보게 되서 한번 이렇게 만들어봤습니다.

2022-05-26 13:31 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherRestController.java
> +        @RequestParam(required = false) Optional<VoucherType> type
당연히 해야될 부분이었는데, 놓쳤군요.. 😱
[[811beda]](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/811beda4b25d227011a3e155151037757a92b7f9) 별도로 Search 용 클래스를 만들어서 생성자 부분에 유효성 검사 로직을 추가했습니다.

2022-05-26 13:31 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherRestController.java
> +    public ApiResponse<VoucherDto> create(@RequestBody CreateVoucherRequest request) {
확실히 해야된다고 생각합니다! [cd24754](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/cd2475403d17f411647b0850c9dbb890ce278847) 바로 넣었습니다.

2022-05-26 16:53 UTC, Jo-GyuHyeon requested changes

2022-05-26 16:53 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +            .WHERE("voucher_type = :voucherType", "voucherType", type.map(Enum::toString))
이경우에는 Where 빌더를 사용해보시는건 어떨까요? 실제 쿼리 처럼 보여지는 것을 의도하신것 같아 제안드립니다.

2022-05-26 16:53 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +        }
오버로딩을 사용하셨다면 재사용을 고려해보는건 어떨까요?? `Telescoping` 이란 용어도 한번 봐주세요.

2022-05-26 23:30 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +            .WHERE("voucher_type = :voucherType", "voucherType", type.map(Enum::toString))
오...! 가독성 측면에서 그게 훨씬 낫겠네요! 감사합니다. 한번 적용해보겠습니다. 👍

2022-05-26 23:35 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +        }
```java
// 매개변수가 Object이기 때문에, Optional 도 여기로 진행
public Builder WHERE(String condition, String key, Object value) {
    value.ifPresent(o -> this.WHERE(condition, key, o));
    return this;
}

// 결과적으로 사용 안되는 메서드 😱
public Builder WHERE(String condition, String key, Optional<Object> value) {
    value.ifPresent(o -> this.WHERE(condition, key, o));
    return this;
}
```
처음에는 그렇게 작성을 했다가 안쓰이는걸 깨닫고 변경을 했는데, 저 녀석을 안지웠네요.. 😱
일단 저녀석을 지우던지 아니면 재사용을 고려할 수 있는지 한번 더 살펴보겠습니다.

덕분에 `Telescoping` 용어도 잘 배워가겠습니다... ㅎㅎ

2022-05-26 23:36 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/CreateVoucherRequest.java
> +
이곳도 Bean validation으로 한번 적용해보겠습니다!

2022-05-27 07:47 UTC, midasWorld commented
# 🛠 작업 단위

- [[9ce3228]](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/9ce3228e790c2e90afe1b0056f85e47b3477f8a4) SqlBuilder - 사용되지 않는 메서드 삭제
- [[8c414b0]](https://github.com/prgrms-be-devcourse/springboot-basic/pull/512/commits/8c414b09e99506c27748a1b7828f3888d2684ec8) Voucher, Customer - 필드 네이밍 클래스명과 중복되는 부분 수정
  - Voucher 클래스 내에서 voucherId → id 와 같이 클래스명을 제거 했습니다.

2022-05-28 02:42 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/voucher/CreateVoucherRequest.java
> +    }
디버깅 용도도 있습니다. 잘못 사용되었다라기 보다 단순 질문의 의도로 코멘트를 남기게 되었습니다.

TMI 로 저는 모든 클래스가 toString() 을 `항상` 재 정의 되어야 하나? 특히나 Response DTO 같은 경우에도?? 라고 생각한적이 있었던 적이 있네요.

[다른 참고 링크가 있어서 첨부합니다. 한번 같이 읽어 보시면 좋을 듯합니다.](https://hudi.blog/java-correct-purpose-of-tostring/)

2022-05-28 02:42 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +        public Builder WHERE(String condition, String key, Object value) {
```
String condition, String key, Object value
```
해당 파라미터들을 Class 로 묶어 리스트 형식으로 받으면 어떨까요? 그렇게 된다면 더욱 코드가 깔끔해 질것 이라 예상이 됩니다.
그렇게 된다면 `appendWhere()` 메서드도 단순하게 처리가 될 수 있고 필요 없을 수 있다고도 생각이듭니다.

2022-05-28 04:52 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/CreateVoucherRequest.java
> +    }
toString() 관련해서 이렇게 많은 의견들이 있었다니.. 깊이 찾아보지 않아 반성합니다. 🙏
사실 객체 정보를 텍스트화 할 수 있는 메서드이니, 필요한 상황에 따라서 막 써도 괜찮다고 생각을 했었는데...
디버깅 용도로 사용된다고 생각하면, 사용자에게 가공해서 보여줘야 되는 경우에는 getDestination() 과 같은 메서드를 생성하는게 좋다라는 글이 상당히 공감이 되는군요.

저는 글을 보고나서 언제 어떻게 디버깅 용도로 사용될지 모르니 재정의를 하는게 좋겠다로 마음이 기울게 된 것 같습니다!

무지성으로 당연하게 사용하는 것들에 대해서도 한번 생각을 더 해봐야겠네요. 감사합니다! 👍

2022-05-28 05:11 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +        public Builder WHERE(String condition, String key, Object value) {
조언 감사합니다! 한번 해보겠습니다!!

2022-05-29 12:12 UTC, HYEBPARK reviewed
sql builder 를 사용하셔서 타입, 기간 별 조회가 깔끔한 것 같아요 !
동운님 수고하셨습니당 😊

2022-05-29 12:12 UTC, HYEBPARK commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +            if (sql.indexOf("WHERE") >= 0) {
조건문 전에 개행 넣기 일관성 있게 해주면 가독성 부분에서 좋을 것 같아요 ! 😊

2022-05-29 12:32 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/service/voucher/VoucherService.java
>          checkArgument(voucherId != null, "voucherId must be provided.");
Service에서 다른 Service를 호춣하는 경우를 생각하면... 
유효성 검사가 Controller단보다 Service단에서의 검증이 더 중요하다고 생각했습니다. 
(이 부분이 잭슨 리더님 특강에서 나왔던것 같네요.)

2022-05-29 12:33 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/model/voucher/PercentDiscountVoucher.java
>          return beforeDiscount * (percent / 100);
그러네요... 😳
오우.. 크나큰 오류가 있었네요. 감사합니다!

2022-05-29 12:34 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +            if (sql.indexOf("WHERE") >= 0) {
오호.. 그렇겠네요. 감사합니다. 👍

2022-05-29 12:37 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler({InputException.class, IllegalArgumentException.class})
그러네요... 😳
메시지를 커스터마이징 한것도 아니고, IllegalArgumentException 로 충분히 사용할 수 있는 오류인 것 같네요.
애초에 InputException 클래스 자체를 만드는 것 자체가 잘못 됬었던 것 같습니다.
지적 감사합니다! 👍

2022-06-02 10:22 UTC, whyWhale requested changes
동적쿼리 내부 빌더 패턴 매우 인상적이였습니다! :)
수고하셨습니 🥕 !

2022-06-02 10:22 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/model/voucher/PercentDiscountVoucher.java
>          return beforeDiscount * (percent / 100);
percent 에 10이 있으면 (10 / 100 ) 0.1이 나오기를 예상하지만 자동으로 long으로 캐스팅되어 소수점 부분이 잘라 0이될 것 같슴둥

2022-06-02 10:22 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/model/voucher/VoucherType.java
> +    private final TriFunction<UUID, Long, LocalDateTime, Voucher> createVoucher;
처음처럼

2022-06-02 10:22 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +public class SqlBuilder {
내부 빌더 패턴 너무 좋은 방법인것 같슴둥 👍🏼 👍🏼

2022-06-04 03:38 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/SqlBuilder.java
> +        public Builder WHERE(String condition, String key, Object value) {
@midasWorld 아직 안해보신것 같아 기다리고 있습니다. :)

2022-06-04 03:38 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/repository/voucher/JdbcVoucherRepository.java
> +            .WHERE("voucher_type = :voucherType", "voucherType", type.map(Enum::toString))
Where 은 한번만 으러 가시져~

2022-06-08 00:19 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherSearch.java
> +    private Optional<LocalDate> startDate;
경우에 따라서 날짜없이 검색할 수도 있다고 판단해서 Optional로 지정했습니다.
나중에 데이터가 많아진다면... 날짜가 필수로 바뀐다던지 하면.. 그때서야 Optional 빼버리고 필수값으로 지정할 계획이었습니다.

2022-06-08 00:21 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/controller/voucher/VoucherDto.java
> +    public VoucherDto(Voucher voucher) {
mapper나 converter를 만들어서 사용하는게 가장 이상적이긴 한데... 
DTO는 좀더 느슨하게 사용해도 되지않을까 싶어서 이렇게 했었습니다만... 좀 더 고민을 해봐야겠네요. 감사합니다. 👍

2022-06-08 00:21 UTC, midasWorld commented on src/main/java/org/prgrms/kdt/model/voucher/PercentDiscountVoucher.java
>          return beforeDiscount * (percent / 100);
오호..! 테스트 해봐야 겠네요. 감사합니다. 👍

2022-11-02 14:49 UTC, closed without merging