feat: gradle setting
prgrms-be-devcourse/springboot-basic pull request #515
Opened 2022-05-15 23:14 UTC by whyWhale

## 📌 작업단위
- [ ] : 바우처 추가(고정 할인, 정률 할인) - 만료기간 포함
- [ ] : 바우처 수정 : 바우처 타입,할인율,개수, 만료일자
- [ ] : 바우처 단건 조회
- [ ] : 바우처 다건 조회 + (페이징 처리)
- [ ] : 바우처 추가 페이지 + fetch api
- [ ] : 바우처 수정 페이지 + fetch api
- [ ] : 바우처 다건 조회 페이지(메인 페이지) + 페이징 번호 + 삭제버튼
- [ ] : 바우처 단건 조회 페이지 + 수정,삭제 버튼

## 👩‍💻 PR 포인트
- 해당 관련해서 몇가지 이슈를 맞이했습니다.
- 아래 관련해서 따로 가이드 주시면 좋을 것 같습니당.
- [issue_list](https://absorbed-cheek-029.notion.site/3-weekly-issue-e0bea1ef53ca4a2bbcd8cf0a035e2446)

## ✅ 요구사항
-  [요구사항]((https://absorbed-cheek-029.notion.site/3-weekly-issue-e0bea1ef53ca4a2bbcd8cf0a035e2446))

2022-05-21 10:05 UTC, Jo-GyuHyeon requested changes
Provider, Manager를 사용함에 있어서 유연성도 있을 수 있지만 복잡성이 더 크게 느껴진다고 생각이 들기도 합니다. 병연님의 의견을 듣고 싶습니다.

2022-05-21 10:05 UTC, Jo-GyuHyeon commented on app/src/test/java/com/programmers/order/repository/VoucherJdbcRepositoryImplTest.java
> +	@Autowired
개행을 통일 시켜주면 좋을것 같습니다.

2022-05-21 10:05 UTC, Jo-GyuHyeon commented on app/src/test/java/com/programmers/order/repository/VoucherJdbcRepositoryImplTest.java
> +	@Order(10)
인메모리 테스트를 하더라도 테스트가 최대한 순서에 영향을 미치지 않도록 고려해주세요.
테스트 케이스가 많아 진다면 테스트 파일을 분리 해보는 것도 고려해주세요.

2022-05-22 07:15 UTC, whyWhale commented on app/src/test/java/com/programmers/order/repository/VoucherJdbcRepositoryImplTest.java
> +	@Order(10)
넵 알겠슴다!

2022-05-22 07:28 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/dto/PageDto.java
> +			}
원래는 sort 타입으로 아이디별 혹은 생성일자 별, 수정별, 만료일자 별로 가져갈려 했슴다.. 그런데  issue 가 발생해서 현재는 다시 복구중에 있슴당. [issue](https://absorbed-cheek-029.notion.site/back-_-sort-Issue-8972d6ae001448c5b2334f9af71c3272)

제가 만들 view 기능이 이러합니 🥕  !
![image](https://user-images.githubusercontent.com/67587446/169683820-1ef9e502-2be7-45f0-adb5-89903c23c60d.png)

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/provider/VoucherProvider.java
> +public class VoucherProvider {
![스크린샷 2022-05-22 오후 5 50 52](https://user-images.githubusercontent.com/67587446/169686650-23247015-854d-4edc-aa2e-a3b6febec420.png)

 converter나 repository 각각에서 특정 voucher를 생산할 수 있는 구체적인 로직을 알필요가 없다고 생각했기 때문에 특정 voucher를 생성해 낼 수 있는 대표자(provider)로 구성했습니다. 또한 그리고 불특정 다수의 상대에 대한 요청과 내부 요청에 의해 인터페이스로 분리하여 특정 로직에서만 동작할 수 있도록 인터페이스로 분류 했습니다. (인터페이스 분리 원칙)

이렇게 구성함으로써 얻을 수 있는 효과는 중앙 집권 체제 처럼 한곳에서 모아 관리하기 때문에 이곳 저곳 수색하지 않는 편리한 점이 있다고 생각했습니 🥕 ! 

+ 추가 설명
- provider가 중간에 client요청에 의한 객체 생성과 내부(db)에서 가져올 때 특정 voucher를 생성하는 방식이  다르므로 중간에서 필요한 형태의 생성자를 인계할 수 있도록 함에 있어 형식을 구현하였습니다.

2022-05-22 09:29 UTC, whyWhale commented on app/src/test/java/com/programmers/order/repository/VoucherJdbcRepositoryImplTest.java
> +	@Autowired
감삼다! 다시한번 검토하겠습니 🥕 !

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/exception/JdbcException/JdbcException.java
> +package com.programmers.order.exception.JdbcException;
패키지로 따로 됨을 이제 인지하였습니당 .. 패키지 지우겠슴둥...

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/dto/PageDto.java
> +		private void makePageList(Pageable pageable) {
해당 로직이 생성자에 있어 불편하지 않을 까란 생각이 들었는데.. 외부 영향 부분에서 최소하하는게 좋은 것 같슴둥 ! 감삼당 👍🏼

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/api/VoucherRestController.java
> +		return ResponseEntity.ok("삭제가 완료되었습니다.");
현재로서는 단 하나의 String 만 있어서 했는데 확장을 고려한다면 enum을 미리 써도 상관 없을 것 같슴 🥕 ! 감삼당 :)

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/api/VoucherRestController.java
> +	@DeleteMapping("/{voucher_id}")
- 대부분 사이트들이 url들이 소문자로 구성되었어서 그렇게 했슴당...
- 해당 부분 수정하겠슴둥 :)

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
> +		ModelAndView voucherUpdateView = new ModelAndView("voucher-update");
변수 대입하는 관점에서 동일하다고 생각했어서 그렇게 했슴당. 
view 다루는 부분 또한 새로운 라인으로 가져가겠슴당 :) 감삼 🥕 !!

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
> +	@GetMapping("")
넵 감삼당 :)

2022-05-22 09:29 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/VoucherController.java
> +		Page<Voucher> vouchers = voucherService.lookUpVouchers(pageable);
bringTheRange naming은 어떠신가용...?

2022-05-24 18:09 UTC, pjh612 commented on app/src/main/java/com/programmers/order/controller/api/VoucherRestController.java
> +	@PostMapping("")
("")을 빼도 상관 없을 것 같습니다~

2022-05-25 11:33 UTC, pjh612 approved these changes
개인적으로 궁금한건 직접 여쭤볼 수 있었어서 딱히 코멘트달게 없어보입니다!
나름의 규칙을 세우시고 코드를 짜신것같아 건들일 것이 없군요! ㅎㅎ

2022-05-25 11:50 UTC, midasWorld approved these changes
고생하셨습니다!! 클래스 분리나 유효성검사 등등 많이 배워 갑니다. 👍
저도 궁금한 점만 몇자 적었습니다.. ㅎㅎ 

아! 추가로 다른 분들 리뷰에도 작성 했는데, 
`@ControllerAdivce` 전역 예외처리에서 상정한 오류 말고도 전역 예외처리 메서드도 추가하는건 어떨까요?

2022-05-25 11:50 UTC, midasWorld commented on app/src/main/java/com/programmers/order/service/VoucherService.java
> +				.orElseThrow(() -> new ServiceException.NotFoundResource("voucher resource 가 존재하지 않습니다."));
로깅에서 해당 건 관련해서 확인하기 쉽게 에러메시지에 ID값을 넣는건 어떨까요? 🤔

2022-05-25 11:50 UTC, midasWorld commented on app/src/main/java/com/programmers/order/controller/api/VoucherRestController.java
> +public class VoucherRestController {
rest api 설계 때 버전 관리를 위해서 url에 v1 과 같이 추가를 권장하던데.. 혹시 추가하지 않은 이유가 있을까요?? 👀

2022-05-25 11:50 UTC, midasWorld commented on app/src/main/java/com/programmers/order/domain/PercentVoucher.java
> +		VoucherType.PERCENT.checkConstraint(discountValue);
흠.. VoucherType.PERCENT 이 부분을 VoucherType에 클래스를 넘겨주는 걸로 하면 어떨까요? 🤔
사용때마다 갑을 명시해주는 것보다 VoucherType에서 관리하는게 더 편하지 않을까요?
이거는 순수 궁금해서 여쭤봅니다! 병연님 의견이 궁금하네요. 😳

2022-05-25 11:50 UTC, midasWorld commented on app/src/main/java/com/programmers/order/controller/dto/VoucherDto.java
> +			}
아.. where을 마지막이 넣으면 되는군요..! 😳
좋은거 배워 갑니다. 👍

2022-05-25 12:00 UTC, HYEBPARK commented on app/src/main/java/com/programmers/order/exception/RestExceptionHandler.java
> +	@ResponseStatus(code = HttpStatus.BAD_REQUEST)
이런 어노테이션도 있군요 배워갑니당 !!

2022-05-25 12:17 UTC, HyoungUkJJang reviewed
수고하셨습니다 병연님 :)
많이 고민하시고 작성하신 것 같아 컨벤션 외에는 저에게 보이지 않는 것 같습니다 ! 덕분에 좋은 방법 많이 배웠습니다 !

2022-05-25 12:18 UTC, HyoungUkJJang approved these changes

2022-05-26 11:23 UTC, Jo-GyuHyeon requested changes

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/controller/api/CustomerRestController.java
> +@RequestMapping("/customer")
rest api 엔드포인트 작성시 리소스를 대부분 복수형으로 /customers 로 표현하는 것이 좋습니다.

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/controller/api/CustomerRestController.java
> +	@PostMapping("")
빈 매핑이라면 `("")` 부분을 생략해주세요 :smile:

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/controller/dto/VoucherDto.java
> +			}
파라미터에 대한 유효성 검사는 최대한 제일 상단으로 노출시키는 것이 좋습니다. :smile: 
애초에 다름 로직을 탈 필요가 없기때문입니다.

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/controller/dto/VoucherDto.java
> +				}
컨디션들이 더 많아지게 되면 해당 구분이 반복되게 되는 걸까요?????

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/repository/CustomerJdbcRepository.java
> +			throw new JdbcException.NotExecuteQueryException("customer insert query 가 정상적으로 실행되지 않았습니다..");
사소한것이긴 하지만 마침표가 2개 있습니다. :smile:

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/repository/CustomerJdbcRepository.java
> +		);
이럴땐 오히려 한줄로 표현하는것이 더 깔끔할것 같은데 개행을 주신 이유가 있으신가요?

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/service/CustomerService.java
> +@Transactional
아마 클래스레벨의 컨벤션 보다는 해당 클래스에서 create 작업이니 readOnly 를 의도적으로 하지 않으신듯 합니다.
하지만 해당 클래스에서 트랜잭션이 필요한가?? 에 대해서도 의문이 들기는 합니다.

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/test/java/com/programmers/order/repository/CustomerJdbcRepositoryTest.java
> +		MatcherAssert.assertThat(inserted, Matchers.samePropertyValuesAs(customer));
저는 해당 테스트케이스에서 given when then 패턴이 필요한가?? 에 대해 의문을 갖고 있습니다.
통일성을 위해 주석으로 남겨 둔것일까요?

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/test/java/com/programmers/order/repository/VoucherJdbcRepositoryImplTest.java
> +				.build();
딱집어서 얘기 할 순 없지만 이런경우엔 한줄표 표시하는건 어떨까요? 아니면 에초세 체이닝 메서드들은 전부 개행으로 하는 것도 깔끔하다고 생각합니다.

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/test/java/com/programmers/order/repository/VoucherJdbcRepositoryImplTest.java
> +								.build()).limit(60)
여러군대에서 FixedVoucher를 인스턴스화 하고 있습니다. 
혹시 인스턴스화를 해주는 private 메서드를 만들어서 재사용 하는 방법은 어떠할까요?

2022-05-26 11:23 UTC, Jo-GyuHyeon commented on app/src/test/java/com/programmers/order/service/VoucherServiceTest.java
> +		log.info("testCreate -> voucherId : {}", percent.getVoucherId());
테스트 케이스에선 로그가 필요한 이유는 무엇일까요??

2022-05-28 02:12 UTC, Jo-GyuHyeon commented on app/src/main/java/com/programmers/order/provider/VoucherProvider.java
> +public class VoucherProvider {
@whyWhale 그렇다면 해당 클래스는 컴포넌트로써 한번더 감싸준 역할만 한다고 생각합니다.
`converter나 repository 각각에서 특정 voucher를 생산할 수 있는 구체적인 로직을 알필요가 없다고 생각했기 때문` 의 이유라면 인터페이스로 의존관계를 가지기만 하면 충분히 느슨한 관계를 가질 수 있다고 생각합니다.

사용하는 곳도 자세히 살펴보면 외부, 내부 (client, internal)가 나뉘어 져있기 때문에 굳이 provider 가 아닌 각 영역에 대한 인터페이스 (이름을 (internal,external )provider 라고 해도 상관 없습니다.) 만 있어도 상관 없습니다.

그리고 해당 컴포넌트는 결국 Spring Bean 이며, 싱클톤으로 생성되는데 이는 싱클톤 패턴의 무상태 (상태를 나타내는 필드 변수 존재 x) 를 위반하게 됩니다.  (현재 type 이라는 상태 필드 존재)
또한 각 메서드들에서 빈을 return 하고 있는 것이 좋지 않다고 생각합니다.

예를 들면 각 서비스 빈에서 get**Repository() 메서드를 제공하여 다른 서비스 클래스 및 컨트롤러에서 **Repository 를 직접 참조하게 되기도 합니다.  이는 각 빈 들에 대한 의존관계를 무너트리게 됩니다. 의존관계에 대한 책임도 약해진다고 파악하고 있습니다.

사용하는 것을 보았을때 외부 의존 관계가 없으므로 이때는 Static 을 사용하는것이 더 적합해 보이기도 합니다.

[이와 관련해서 코멘트를 남긴적이 있어서 링크 첨부 합니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/515/files/54f626c2642f69289a932d9cbfff1433c45812cc#r878676187)

2022-05-30 16:23 UTC, whyWhale commented on app/src/main/java/com/programmers/order/repository/VoucherJdbcRepositoryImpl.java
> +		;
네! 맞습니다!
수정하겠슴둥 👍🏼

2022-05-30 16:28 UTC, whyWhale commented on app/src/main/java/com/programmers/order/controller/api/VoucherRestController.java
> +public class VoucherRestController {
버젼 분리는 해서 무엇을 얻을 수 있는지 고민해보았을 때, 나중에 사용될 용도가 있지 않을까란 생각밖에 없슴둥 ..  어차피 깃에 스냅샷으로 코드가 남으니 상관 없을 거라 생각 했습니다. 또한 version up에 대한 프론트엔드와 계속 이런 부분을 "v2로 업데이트 했습니다!" 라는 말이 오가면 프론트 개발자들이 귀찮을 것 같슴둥..

2022-05-30 16:30 UTC, whyWhale commented on app/src/main/java/com/programmers/order/domain/PercentVoucher.java
> +		VoucherType.PERCENT.checkConstraint(discountValue);
해당 방법도 고려해보았으나 제약조건에 대한 검증을 voucherType에게 맞기는 것 보다는 특정 구체 voucher에서 유효성 검증을 하는 표현이 더 가독성이 더 좋아 의미있다고 생각했습니다. 그렇기 때문에 생성자 부분에 명시적으로 VoucherType.{특정 타입}.constraint 라고 표현 했슴둥 ‼️

2022-05-31 09:46 UTC, whyWhale commented on app/src/main/java/com/programmers/order/provider/VoucherProvider.java
> +public class VoucherProvider {
- 대화 요청 완료

2022-11-02 14:49 UTC, closed without merging