[2기-P] 김형욱 SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #519
Opened 2022-05-21 07:28 UTC by HyoungUkJJang

### 작업사항
 
* [x] 2주차 코드리뷰 반영
  * [x] voucherId -> id, customderId -> id 네이밍 수정 및 관련 클래스 네이밍 수정
  * [x] BlackListCustomerRepository 매직넘버 제거
  * [x] 테스트클래스 Order 애노테이션 제거
* [x] 바우처 관리 서비스 페이지 만들기
  * [x] 조회페이지
  * [x] 상세페이지
  * [x] 입력(등록)페이지
  * [x] 수정페이지
  * [x] 삭제기능

* 예외처리나 구조에 대해 많이 미흡한 것 같지만 커밋이 많이 쌓이는 것 같아 한번 올리게 되었습니다. 조금 더 고민해보고 개선시켜 보겠습니다.

2022-05-21 11:17 UTC, Jo-GyuHyeon approved these changes
패키지 구조를 보았을때 도메인 별로 나뉘져 있어서 Controller 도 해당 도메인에서 레이어 구조로 갈 것이라 기대 하였습니다. 혹시 의도가 된 부분일까요?

2022-05-23 12:53 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/controller/VoucherWebController.java
> +            .toList();
반영하도록 하겠습니다 !

2022-05-23 12:59 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
> +            }});
반영하겠습니다 !

2022-05-25 14:38 UTC, HyoungUkJJang commented
### 작업사항
 
* [x] 코드리뷰 반영
  * [x] VouchersResponse 에서 of 메서드를 만들기 -> [bfd3947](https://github.com/prgrms-be-devcourse/springboot-basic/pull/519/commits/bfd39475ab89ad4ff818ba9d243dc32d025627f5)
  * [x] update 성공,실패 여부 검증 추가
* [x] 바우처 RestController 작성
  * [x] 조회
  * [x] 상세조회
  * [x] 검색 
  * [x] 등록
  * [x] 수정
  * [x] 삭제

* 검색 기능을 수행하는 동적쿼리 메서드가 분기문이 너무 많아 개선이 필요할 것 같습니다. 현재 진행상황 까지는 반영을 해 두어야 할 것 같아서 푸쉬를 했습니다 :) 동적쿼리 분기문은 더 개선시켜 보겠습니다 !

2022-05-26 07:20 UTC, HYEBPARK commented on src/main/java/org/prgrms/kdt/controller/VoucherRestController.java
> +    @ResponseStatus(HttpStatus.CREATED)
create에만 상태 코드를 넘겨주시는 이유가 있으실까용? 

더 디테일하게 CREATED 코드를 넘겨주셨네요 !
형욱님 덕분에 상태 코드에 대해 한번 더 찾아봤습니당 👍👍

2022-05-26 07:26 UTC, HYEBPARK commented on src/test/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepositoryTest.java
>  @WebMvcTest
해당 어노테이션은 컨트롤러 테스트에서 사용하는 걸로 알고 있는데
Repository 테스트에서 사용하신 이유가 있으실까욤?

2022-05-26 07:31 UTC, HYEBPARK commented on src/main/java/org/prgrms/kdt/customer/repository/JdbcCustomerRepository.java
>          if (update != 1) {
해당 부분 final로 선언 (SUCCESS) 하면 
실패했다는 의미를 더 명확하게 표현할 수 있다는 피드백을 받은 적이 있어 공유합니다 !
(개행이 빠져있어용 !)

2022-05-26 07:42 UTC, HYEBPARK commented on src/main/java/org/prgrms/kdt/customer/service/CustomerService.java
>              .orElseThrow(NoSuchElementException::new);
findById 예외를 voucher만 따로 커스텀을 하셨는데 ,
findById 예외를 통합적으로 하나 커스텀해서 message를 개별로 넣어주는 방향은 어떨까용!?🤔
상황에 따라 더 자세한 메시지를 던져 줄 수 있을 것 같아요 !

2022-05-26 08:53 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/controller/VoucherRestController.java
> +        System.out.println(criteria.getStartDate());
앗 확인해보다가 지우지 못했네요.. 바로 반영하겠습니다 !

2022-05-26 08:56 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/customer/service/CustomerService.java
>              .orElseThrow(NoSuchElementException::new);
좋은 방법인 것 같습니다 ! 피드백 감사드립니다 :)

2022-05-26 09:01 UTC, HyoungUkJJang commented on src/test/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepositoryTest.java
>  @WebMvcTest
TestConfig 클래스를 작성해주었는데 SpringBootTest 애노테이션을 달아주면 적용이 안되는 것 같아 WebMvcTest를 붙이니 동작이 잘 되는 것 같았습니다! 이부분에 대해서는 이유를 찾아보지 않고 넘어간 것 같네요..! 짚어주셔서 감사합니다 ! 이유를 한번 찾아보겠습니다 👍

2022-05-26 10:43 UTC, pjh612 reviewed
201 상태코드를 쓰신것 인상깊게 봤습니다 ~
제가 제안 드린 것은 개인적인 성향이 짙은 제안이므로 필요하다, 괜찮다 생각하신것만 픽픽픽 하시면 될 것 같습니다. 화이팅임다!

2022-05-26 10:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
> +    @Override
함수가 너무 길어지고 복잡해져서 고민이실 것 같아요.
SQL을 만들어주는 빌더를 구현하는 방법도 좋을 것 같습니다.
그리고 SQL 조각들을 변수로 빼는 방법은 어떨까 싶어요 SELECT * FROM VOUCHERS 같은 쿼리 조각은 
String BASE_SQL_SNIPPET(?)와 같이 변수로 뺄수도 있을 것 같고.. 중복되는 created_at between :startDate AND :endDate 또한 별도의 SQL 조각들로 뽑아낼 수 있을 듯합니다.

이런식으로 변수로 뺀다면 나중에 조건문에 따라 쿼리문을 조합할때 변수명으로 어떤 쿼리일지 알아볼 수 있어서 좋을 것 같다는 생각을 했습니다.
각 조건문 또는 일관된 묶음이 하나의 private 함수가 될 수도 있을 것 같습니다.

또한 저는 검색 조건을 Map으로 변환 시켜주는 toCriteriaParamMap을 따로 만들었는데요,
paramMap에는 어떤 값이 들어가 있던 상관없이 jdbcTemplate이 쿼리시 자신의 sql에 사용될 key값을 통해 필요한 데이터만 뽑아낼텐데, 그렇게 된다면 sql만 조건문에 따라 만들어주고, paramMap에 값을 넣어주는것은 굳이 조건문에 따라 paramMap에 fit하게 넣어줄 필요 없이, criteria에 있는 각 항목이 null이 아니라면 다 넣어줘도 상관 없을 것 같습니다. 그렇게되면 조건문에 달려있는 paramMap.put()이 없어질 것 같습니다.

2022-05-26 10:43 UTC, pjh612 commented on src/main/java/org/prgrms/kdt/controller/VoucherRestController.java
> +        if (criteria.getType() != null || criteria.getStartDate() != null || criteria.getEndDate() != null) {
기준에 따른 검색 메서드로 가는 조건문인 것을 효과적으로 표시하기 위해 조건문을 별도의 boolean 함수로 빼내도 좋다고 생각이 드네요!

2022-05-26 10:58 UTC, HyoungUkJJang commented on src/test/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepositoryTest.java
> +        voucherRepository.save(newVoucher);
넵 ! 참고하도록 하겠습니다 ㅎㅎ 👍🏻

2022-05-26 10:59 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
> +                    "select * from vouchers where voucher_id = UUID_TO_BIN(:id)",
저도 가독성 측면에서 키워드는 대문자로 쓰는게 더 좋다고 생각합니다 ! 습관적인 버릇이 코드에 묻어있어서 고쳐야할 부분이 많은 것 같네요 감사합니다 !

2022-05-26 11:02 UTC, Jo-GyuHyeon requested changes

2022-05-26 11:02 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
> +        }
VoucherSearchCriteria 를 사용하면서 코드가 더 복잡해진듯 합니다. if 문을 사용하더라도 중첩 부분을 제거해보는 것에 고민해주세요 :)

2022-05-26 11:02 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
> +        if (update == 0) {
개행을 해주면 더 좋을 것 같습니다. 
}}); 를 연달아 사용하게 되니 오히려 코드 구분하기가 힘들기도 합니다.
개행을 이용하거나 변수로 따로 빼시는걸 추천드립니다.

2022-05-26 11:08 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
> +    @Override
가장 고민하고 있었던 부분이였는데 상세히 많은 방안을 남겨주셔서 감사합니다 ! 저도 SQL 문장을 따로 빼는 고민을 하고 있었는데 paramMap은 생각해보지 못했네요 ! 참고해서 다시 개선시켜 보겠습니다 ㅎㅎ

2022-05-27 17:00 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/controller/VoucherRestController.java
> +    @PutMapping("{id}/update")
넵 참고하도록 하겠습니다 !

2022-05-27 17:04 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdt/controller/dto/CreateVoucherRequest.java
> +    }
유효성 검사 좋은 방법인 것 같습니다 !

타입정보를 커멘드라인 바우처 키워드처럼 생각해서 실수를 한 것 같습니다..! 반영하도록 하겠습니다 ㅎㅎ !

2022-05-27 17:12 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/controller/VoucherRestController.java
> +        return this.voucherService.makeVoucher(VoucherType.of(createVoucher.getType()), createVoucher.getValue())
- VoucherType.of(createVoucher.getType()) 따로 변수를 만들어서 사용하는게 어떠신가요?
- 그러면 가독성이 개인적으로 좋을 것 같습니다!

2022-05-27 17:15 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/controller/dto/VoucherSearchCriteria.java
> +    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS")
- startDate,endDate에 대한 과거 시간 미래시간 validation 처리를 하면 좋을것 같슴둥!

2022-05-27 17:18 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
>              throw new RuntimeException("Noting was inserted"); // 커스텀 예외로 수정해보자
- 커스텀으로 예외처리를 하면 좋을 것 같습니다!

2022-05-27 17:33 UTC, whyWhale commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +        return this.voucherRepository.findAll();
- 데이터가 많을 경우를 고려해서 페이징 처리를 하면 좋을 것 같습니 🥕  !

2022-05-29 17:38 UTC, HyoungUkJJang commented
### 작업사항
 
* [x] 코드리뷰 반영
  * [x] if문 개행 추가하기
  * [x] JdbcRepository 쿼리 실행여부 상수 추가 / 커스텀 예외 추가
  * [x] SQL 검색조건 if문 리팩토링하기 
  * [x] DTO 검증 VALID 추가하기 

* 남겨주신 리뷰를 반영하고 검색 SQL 분기처리 문장을 수정해 보았습니다 !

2022-05-31 14:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdt/controller/VoucherRestController.java
> +            return this.voucherService.searchVouchers(criteria)
`isCriteriaCheck()` 를 해당 클래스가 아닌 `VoucherSearchCriteria` 에서 메서드로써 유효성 혹은 상태를 반환 하는 방법은 어떤가요? 예를 들면 isEmptyCondition() 과 같은 메서드들이 있는것이 Criteria 객체에 대해 책임을 몰아 줄 수 있다고 생각합니다.

2022-11-02 14:46 UTC, closed without merging