Hyebpark weekly rest api
prgrms-be-devcourse/springboot-basic pull request #521
Opened 2022-05-24 14:51 UTC by HYEBPARK

### 🛠 작업 단위
- [x]  voucher Controller 구현 (CRUD) 
- [x] voucher RestController 구현(CRUD, type 조회, 기간 조회) 
- [ ] voucher Controller 테스트 코드 작성
- [ ] 테스트 코드 보충
- [ ] voucher Wallet 구현
 
### 📍  PR 포인트

### 🎈  요구사항
**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [x]  조회페이지
    - [x]  상세페이지
    - [x]  입력페이지
    - [x]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**
- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x]  전체 조회기능
    - [x]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능
   
- [요구 사항 링크](https://www.notion.so/backend-devcourse/Part1-3-38f57acca0dd490db11393701417943a)

2022-05-24 15:21 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/exception/GlobalExceptionHandler.java
> +		StringBuilder bindingErrorMessage = getBindingErrorMessage(bindingResult);
valid 체크의 유효하지 않은 값들의 에러 메시지와 사용자 입력 값을 
읽기 좋게 만들어 넘기기 위한 코드입니다.
프론트에 꼭 넘겨 줘야하는 정보에 대한 개념이 정리되지 않아 이 행위가 불 필요한 건가? 라는 의문이 들었습니다.
프론트에 굳이 필요 없는 정보인지, 로그에도 굳이 남기지 않아도 되는 정보인지 궁금합니다 !

2022-05-24 15:31 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/VoucherDto.java
> +		public static Response from(Voucher voucher) {
**dto에 컨버터 기능을 하는 메서드를 구현하는게 맞는걸까요?**
처음에 coverter 기능을 하는 부분을 따로 class로 빼서 의존성 주입을 받는 코드를 구현했습니다.
하지만 코드를 작성하다 보니 converter 기능을 하는 메서드는 해당 dto에 의존적인? 메서드라는 생각이 들었습니다.
그래서 관리하기에도 dto에 구현을 하는 게 좋을 것 같다는 생각이 들어 dto에 구현을 하였습니다.
이 부분에 대해서 의견이 많이 갈리는 것 같습니다. 어떤 방법이 더 나은 방법인지 궁금합니다 !

2022-05-26 11:31 UTC, Jo-GyuHyeon approved these changes

2022-05-26 11:31 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/VoucherController.java
> +		this.voucherService.save(voucherCreateRequest.voucherType(), voucherCreateRequest.value());
간혹 드는 갱각은 꼭 변수명은 클래스명과 동일해야 하는가?? 에 대해 생각할때가 있습니다.
이땐 createRequest 혹은 간단히 request 라고 해도 혼동되거나 의미를 파악하기 힘들다고 생각이 들진 않는데 케빈님의 생각은 어떠하신가요?

2022-05-26 11:31 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/VoucherController.java
>  	@GetMapping("/voucher/{voucherId}")
이건 개인의 취향이라고  볼수 있는데 개인적으로 단일 리소스 id 라면 `{voucherId}` 보다는 `{id}` 로 표기하는것이 더 깔끔하다고 생각을 합니다. 굳이 구분될 필요도 없기 때문입니다.

2022-05-26 11:31 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/VoucherController.java
>  		this.voucherService.update(voucher);
혹시 해당부분을 컨트롤러가 아닌 서비스에서 묶어버릴순 없었을까요? 오버로딩??

2022-05-26 11:31 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/response/ApiResponse.java
> +	private final HttpStatus httpStatus = HttpStatus.OK;
HttpStatus 가 항상 OK 라는 것은 예외가 나더라도 Netwrok 통신은 정상적이라는 의미일까요?

2022-05-26 11:31 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/converter/VoucherConverter.java
> +		return voucherResponse.type()
개행 스타일이 일치 하지 읂는것 같습니다. 이럴땐 붙여주세요 :)

2022-05-26 12:11 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/response/ApiResponse.java
> +	private final HttpStatus httpStatus = HttpStatus.OK;
예외 발생시의 response는 ErrorResponse로 따로 만들어서 
GlobalExceptionHandler 클래스에서 return 해줬습니다 !

2022-05-26 13:55 UTC, Jo-GyuHyeon requested changes

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/VoucherDto.java
> +		public static Response from(Voucher voucher) {
`++ 병연님 코드 리뷰를 보고 static 메서드로 선언하여 메모리에 비효율적이라는 문제점을 찾았습니다.` 해당 부분을 링크 혹은 부분적으로 알려주시면 감사하겠습니다. 😄 


dto 변환에 대한 여러 링크가 있어 공유 드립니다. 
DTO 에서 어떤 데이터 모델인지가 중요하지 어떤 엔티의 데이터가 필요한지 알아야 되나? 라는 관점도 있으면 조금 도움이 되지 않을까 싶기도합니다. 
느슨한 관계를 유지하기 위해 맵핑을 해주는 역할의 클래스가 필요하다고 생각이 듭니다.

[where,when and how convert DTO to/from Entity](https://stackoverflow.com/a/44885988)
[해당 내용은 댓글을 참고해주세요](https://stackoverflow.com/a/28720522)

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/response/ErrorCode.java
> +	FAILED_EXECUTE_QUERY(HttpStatus.INTERNAL_SERVER_ERROR);
기본적으로 HTTP State 를 어떤 정책으로 사용할 것인지도 정해야 된다고 생각합니다.
기본적으로 200, 500 으로도 나뉠수도 있습니다. 혹은 필요한 상태를 더 추가 할 수도있습니다.
만약 케빈님이 HTTP State 에 대한 정책을 정하셨다면 그다음엔 서버 내부 쿼리의 예외인지? 비지니스 로직으로 인해 해당 쿼리들이 실행이 안되는 것인지를 구분 할 수 있을 것 같습니다.

예를 들어 유니크 옵션이 있는 컬럼에 대해 새로운 데이터를 저장하는 행위는 서버 에러일까요??

 [조금 다른 얘기가 될수도 있지만 잼있어서 첨부합니다.](https://youtu.be/cE11144NEts)

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/restController/VoucherRestController.java
> +@RequestMapping("/api/v1/voucher")
restful 에서 리소스는 복수형을 사용하는 것이 일반적입니다. 😄

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/restController/VoucherRestController.java
> +		return ApiResponse.ok(this.voucherService.getVouchers());
한줄이면 굳이 개행을 하지 않아도 좋다고 생각합니다. 🛩️

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/restController/VoucherRestController.java
> +		}
위에 있던 리뷰가 여기서 처리가 되었군요?? 
컨트롤러에 도착하기전에 DTO 에서 Bean validation 처리 하는 방법은 어떨까요? 
해당 조건 자체가 컨트롤러 이전에 처리가 된다면 컨트롤러는 믿고 다음 로직을 작성하는 것이 역할분리와 코드가 깔끔하다고 생각이 듭니다. 😸

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/restController/VoucherRestController.java
> +	@GetMapping(value = "/period")
해당 API 들의 엔드포인트들을 보았을때 어떤 리소스를 제공할 것인지를 표현 해야 된다고 생각합니다.
기간과 타입은 조건으로 받는다면 쿼리 스트링으로 입력을 받을수 있습니다.

restful 의미로 보았을때 해당 타입, 기간 이라는 데이터를 제공할것이라 예상이 됩니다.

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/exception/GlobalExceptionHandler.java
> +		StringBuilder bindingErrorMessage = getBindingErrorMessage(bindingResult);
지금 현재 로그에 대해서는 자세히 작성하는 것이 좋다고 생각됩니다. 
지금은 개인정보 보호법과 같은 내용은 신경쓰지 않아도 좋을것 같습니다.

비지니스 예외의 경우에는 프론트와 협의해서 에러 메시지를 넘겨주는 것은 오히려 좋은것 같습니다. 명확하게 어떤 에러인지를 알려주어야 프론트에서 사용자에게 자세히 안내해줄수 있다고 봅니다.

다만 서버 내부의 이유는 오히려 알려줄 필요 없이 로그로만 자세히 기록 하면 된다고 생각합니다. 다만 서버의 에러 코드 정도만 표시한다면 추후에 프론트 단 (사용자) 가 어떤 오류가 났는지 제보를 할 수 있기 때문입니다. (구체적이진 않지만, 내부(서버) 에서는 어떤 종류의 예외가 사용자에게 맞닿았는지 제보를 받는 것도 좋습니다.)

2022-05-26 13:55 UTC, Jo-GyuHyeon commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherService.java
> +		var updatedVoucher = voucherRepository.update(foundVoucher);
Optional 을 조금 더 잘 활용 하여 Steam 하게 작성해보면 코드가 더 깔끔해질것입니다.

2022-05-26 16:34 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/service/VoucherService.java
> +		var updatedVoucher = voucherRepository.update(foundVoucher);
그건 더 공부를 해보도록 하겠습니다 ㅠㅠ

2022-05-26 17:07 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/VoucherController.java
> +		this.voucherService.save(createRequest.voucherType(), createRequest.value());
getter를 따로 만들어주지 않아도 되는 점과 코드는 간결하게 객체를 불변으로 만들어준다는 장점이 있었습니다 !

2022-05-26 18:07 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/restController/VoucherRestController.java
> +		}
해당 부분 적용 해보겠습니다 !!

2022-05-26 18:21 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/VoucherDto.java
> +		public static Response from(Voucher voucher) {
![image](https://user-images.githubusercontent.com/35947674/170541348-07e15937-27e6-4108-aea8-e99ab1d4a4fa.png)

넵 ! 해당 링크도 참고하겠습니당

2022-05-27 02:44 UTC, HYEBPARK commented on src/main/java/org/programmers/kdt/weekly/voucher/controller/restController/VoucherRestController.java
> +	@GetMapping(value = "/period")
좋은 자료 감사합니다 멘토님 ! 해당 부분도 수정하도록 하겠습니당 👍😊

2022-06-08 02:17 UTC, closed without merging