[3기-C] 이택승 SpringBoot Part1 입출력 및 exit 구현
prgrms-be-devcourse/springboot-basic pull request #524
Opened 2022-11-03 14:19 UTC by dlxortmd987

## 📌 과제 설명 
- 입출력 및 exit 기능 구현
- 사용자가 콘솔을 통해 문자열을 입력할 때, exit 이면 프로그램 종료

## 👩‍💻 요구 사항과 구현 내용 
- 입력
  - 사용자의 입력을 받는 기능
  - String 형 반환
  - Scanner 사용
- 출력
  - 콘솔로 출력하는 기능
  - String 을 파라미터를 출력
  - System.out.println 사용
- exit
  - 무한 루프를 돌면서 exit 이 나오면 루프 종료
  - 대소문자 구분 없음
  - 사용자가 입력한 문자열을 enum type 으로 변환해 switch로 행동 분기
  - 정해진 command 가 아닐 시 에러 메시지 출력

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- IO로 Console 추상화해서 File 입출력을 하더라도 대응할 수 있게 바꿨는데, 메소드 명을 어떻게 해야 할지 헷갈리는 것 같습니다.

2022-11-03 14:47 UTC, hongbin-dev requested changes
> IO로 Console 추상화해서 File 입출력을 하더라도 대응할 수 있게 바꿨는데, 메소드 명을 어떻게 해야 할지 헷갈리는 것 같습니다.

file 입출력도 고려해보셨군요. 지금 네이밍에서 어떤게 걸리시는 것 같으세요?
 
>> IO 인터페이스의 메소드 이름이 걸리는 것 같아요. file 에서 read, write, console에서 input, output 을 아우르는 이름을 고안하기가 어려운 것 같습니다.😓

2022-11-03 14:47 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/utils/Constant.java
> +    public static final String COMMAND_ERROR_PROMPT = "create, list, exit 중에 입력해주세요.\n";
출력하는 객체가 담당할 순 없을까요?

2022-11-03 14:47 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +                case UNKNOWN -> io.doOutput(COMMAND_ERROR_PROMPT);
swich expressions 좋네요!

신규 ENUM이 추가됐을 때를 방지해, default 로직을 넣어보면 어떨까요?

2022-11-03 14:47 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/model/CommandType.java
> +    );
👍

2022-11-03 14:47 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +public class VoucherManagementController implements CommandLineRunner {
아래 코멘트와 같이 VoucherManagementController가 Constant를 의존하고 있네요.
이 상수는 입출력 객체가 갖고 있는게 좋을 것 같아요.

2022-11-03 14:47 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +            io.doOutput(COMMAND_LIST_PROMPT);
```suggestion
            io.doOutputCommandPrompt();
```
이런식으로 Io객체에 책임을 넘겨보면 어떨까요?

2022-11-03 14:47 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/utils/Constant.java
> +            "Type list to list all vouchers\n";
큰 이슈는 아니지만 `\n`는 특정 운영체제에 의존적인 것 같아요.
`system.lineseparator()` 메서드를 사용해보면 어떨까요?

2022-11-03 14:51 UTC, hongbin-dev commented
추가로 1등 제출이시군요 ㅋ 멋집니다

2022-11-03 14:59 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/utils/Constant.java
> +    public static final String COMMAND_ERROR_PROMPT = "create, list, exit 중에 입력해주세요.\n";
> > IO로 Console 추상화해서 File 입출력을 하더라도 대응할 수 있게 바꿨는데, 메소드 명을 어떻게 해야 할지 헷갈리는 것 같습니다.
> 
> file 입출력도 고려해보셨군요. 지금 네이밍에서 어떤게 걸리시는 것 같으세요?
> IO 인터페이스의 메소드 이름이 걸리는 것 같아요. file 에서 read, write, console에서 input, output 을 아우르는 이름을 고안하기가 어려운 것 같습니다.😓

2022-11-03 16:28 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +        while (true) {
VoucherControllerManager 에서 상태관리를 하도록 변경했습니다!

2022-11-03 16:29 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +                case UNKNOWN -> io.doOutput(COMMAND_ERROR_PROMPT);
default 로직 추가했습니다! 추가로 이 부분 EXIT 에서 상태가 변경되도록 수정했습니다.

2022-11-03 16:30 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +public class VoucherManagementController implements CommandLineRunner {
IO 를 abstract class로 바꾸고 이곳에 옮겼습니다.

2022-11-03 16:34 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +            io.doOutput(COMMAND_LIST_PROMPT);
변경완료했습니다! 
추가로 궁금한 것이 있습니다. 제가 고친 코드로는 특정 상황이 되면 IO에 책임을 넘겨줘야 함으로, 메소드를 새로 만들어야 
하는 상황이 생길 것 같습니다. 새로 메소드를 생성하는 방법 말고 다른 방법이 있을까요?

2022-11-04 01:12 UTC, seung-hun-h reviewed
안녕하세요 택승님, 함승훈입니다.
빠르게 PR 올려주셨네요 Enum을 아주 잘 활용하신 것 같습니다.
리뷰 남겼으니 확인해주세요!

**IO로 Console 추상화해서 File 입출력을 하더라도 대응할 수 있게 바꿨는데, 메소드 명을 어떻게 해야 할지 헷갈리는 것 같습니다.**
- read, write라는 단어를 활용하는 것은 어떤가요?

2022-11-04 01:12 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/model/CommandType.java
> +        return Optional.ofNullable(commandMap.get(command.toLowerCase()))
`command`에 null이 전달되면 NPE(NullPointerException)이 발생할 것 같네요

2022-11-04 01:12 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/VoucherController.java
> +@Configuration
`@Configuration` 애노테이션을 사용하셨는데 이유가 있나요?

어떤 설정을 하는 클래스에 보통 쓰이는 애노테이션인데 `VoucherController`에는 사용하는 것이 맞지 않아 보이네요

2022-11-04 05:35 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/VoucherController.java
> +                case EXIT -> voucherManager.isRunning();
제가 이 부분 메소드를 잘못 입력했네요.. 바로 고쳤습니다!

2022-11-04 05:35 UTC, dlxortmd987 commented
> 안녕하세요 택승님, 함승훈입니다. 빠르게 PR 올려주셨네요 Enum을 아주 잘 활용하신 것 같습니다. 리뷰 남겼으니 확인해주세요!
> 
> **IO로 Console 추상화해서 File 입출력을 하더라도 대응할 수 있게 바꿨는데, 메소드 명을 어떻게 해야 할지 헷갈리는 것 같습니다.**
> 
> * read, write라는 단어를 활용하는 것은 어떤가요?

오 너무 좋은 것 같습니다! 반영해서 고쳐보겠습니다!

2022-11-04 05:37 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/io/IO.java
> +    public static final String COMMAND_ERROR_PROMPT = "create, list, exit 중에 입력해주세요." + System.lineSeparator();
제가 생각한 것은 후자였는데 그럼 이름을 좀 더 구체화되게 변경해야 될 것 같아요!

2022-11-04 05:39 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/model/CommandType.java
> +        return Optional.ofNullable(commandMap.get(command.toLowerCase()))
null 고려해서 한번 고민해보겠습니다!

2022-11-04 05:41 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/VoucherController.java
> +@Configuration
따로 이유는 없습니다. 중간에 클래스 활용이 바뀌어서 애노테이션도 바꿔야 하는 것을 확인하지 못한 것 같아요. 아마 `@Component`로 변경할 것 같습니다!

2022-11-04 09:18 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/VoucherController.java
> +                }
음 제 생각에는 "만약 누군가 enum을 추가하고 switch에는 넣지 않았다면, 이것을 처리할 수 있는 로직이 필요하지 않을까?" 생각해서 넣었습니다!

2022-11-04 16:00 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/utils/Constant.java
> +    public static final String COMMAND_ERROR_PROMPT = "create, list, exit 중에 입력해주세요.\n";
properties에 넣어도 좋을 것 같지만, 지금에서는 조금 과도한 것 같아요..ㅎㅎ

2022-11-04 16:06 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/VoucherManagementController.java
> +            io.doOutput(COMMAND_LIST_PROMPT);
`io.doOutput(COMMAND_LIST_PROMPT);`

새로 메서드가 생기는거에 문제가 있을까요?

두 메서드를 살펴보면, 위는 명령어 텍스트가 바뀌면(COMMAND_LIST_PROMPT) 현재 컨트롤러가 변경되어야하는데요. 

`io.doOutputCommandPrompt();`이 메서드에 메시지가 변경되면 `vouchermanagementcontroller.java`는 변경이 없을 것 같네요 ㅎㅎ

2022-11-04 16:07 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/utils/Constants.java
> +}
Constants를 따로 관리할 필욘 없어도 될 것 같아요. 출력객체에 갖고 있어도 좋아보아요.

2022-11-04 16:08 UTC, hongbin-dev commented
택승님 고생하셨습니다.  리뷰는 다음 스텝에서 적용해주세요.
머지하겠습니다~

2022-11-04 16:08 UTC, merged

2022-11-04 17:32 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/utils/Constants.java
> +}
아하 피드백 감사합니다!