[3기-p]서예원 SpringBoot Part1 Weekly Mission제출합니다.
prgrms-be-devcourse/springboot-basic pull request #525
Opened 2022-11-04 10:56 UTC by yewon9609

## 📌 과제 설명 
- 일단 입출력 및 exit기능만 구현하였습니다.
- springMVC 모델을 도입하지 않았습니다. 
- 아직 테스트 코드 작성을 못했어요. 다음 pr때 함께 올리도록 하겠습니다 

![스크린샷 2022-11-04 오후 7 52 52](https://user-images.githubusercontent.com/99070762/199956295-2f134a9a-cfc0-4297-aaf9-210a6c3c8ffc.png)

## 👩‍💻 요구 사항과 구현 내용 
(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [ ]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [ ]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ PR 포인트 & 궁금한 점 
- springMVC 모델을 도입하지않고 이름을 지었는데 제대로 클래스 역할에 맞게 지었는지 궁금합니다
- Application,VoucherCommandLineRunner,VoucherProcessManager 클래스를 application이라는 폴더 하나에 다 집어넣어도 될까요?

2022-11-05 04:00 UTC, seung-hun-h requested changes
안녕하세요 예원님, 함승훈입니다.
애플리케이션을 객체지향적으로 최대한 잘 설계 하려 하신 것 같네요.
그리고 불필요한 파일들은 제거해주세요
리뷰 남겼으니 확인해주세요.

### springMVC 모델을 도입하지않고 이름을 지었는데 제대로 클래스 역할에 맞게 지었는지 궁금합니다
- 네 이름 잘 지어 주신 것 같네요
### Application,VoucherCommandLineRunner,VoucherProcessManager 클래스를 application이라는 폴더 하나에 다 집어넣어도 될까요?
- 바우처와 관련된 클래스들은 바우처 패키지를 만들어 분리해주고, Application 클래스는 그대로 두면 좋을 것 같네요
- 일반적으로 애플리케이션 실행 클래스는 최상위에 두는 것 같아요

2022-11-05 07:34 UTC, yewon9609 commented on src/main/java/org.prgrms/exception/NoSuchMenuTypeException.java
> +  }
인자로 받을까도 생각해보았는데요 저 exception을 던지는 부분 코드가 불필요하게 길어지는 것같아 저렇게 구현해봤습니다 !

2022-11-05 09:51 UTC, hongbin-dev requested changes
#### springMVC 모델을 도입하지않고 이름을 지었는데 제대로 클래스 역할에 맞게 지었는지 궁금합니다.

잘 지어주신 것 같습니다. 피드백남긴것처럼 VoucherProcessManager와 VoucherCommandLineRunner를 통합해도 좋을 것 같아요.

#### Application,VoucherCommandLineRunner,VoucherProcessManager 클래스를 application이라는 폴더 하나에 다 집어넣어도 될까요?

패키지를 나누는 기준을 더 생각해보면 좋을 것 같습니다. 어떤 의미로 application 폴더에 넣으시려고하셨을까요?

2022-11-05 09:51 UTC, hongbin-dev commented on .gitignore
> +.idea/**/shelf
.idea쪽을 ignore한 것 같은데, 올라간 git에 올라간 파일들이 있네요?
이 부분 확인해주시면 좋을 것 같아요

2022-11-05 09:51 UTC, hongbin-dev commented on pom.xml
> +        <maven.compiler.target>18</maven.compiler.target>
👍

2022-11-05 09:51 UTC, hongbin-dev commented on src/main/java/org.prgrms/VoucherCommandLineRunner.java
> +  private final VoucherProcessManager voucherProcessManager;
VoucherCommandLineRunner는 VoucherProcessManager를 단순 실행시켜주기만 하는걸로 보이는데요.
별도의 객체로 나눌 필요가 없어보입니다.

2022-11-05 09:51 UTC, hongbin-dev commented on src/main/java/org.prgrms/VoucherCommandLineRunner.java
> +    while (true) {
바우처프로그램의 상태를 관리하는 객체를 만들어보면 어떨까요?

```suggestion
    while (voucherBlahblah.isRunnable()) {
```

2022-11-05 09:51 UTC, hongbin-dev commented on src/main/java/org.prgrms/VoucherProcessManager.java
> +      }
switch expressions 👍

2022-11-05 09:51 UTC, hongbin-dev commented on src/main/java/org.prgrms/VoucherProcessManager.java
> +      default -> console.commandNotFound();
VoucherProcessManager의 상위객체에선 catch를 해주고 있는데요. 이 부분도 예외를 던지는게 일관성 있지 않을까요?

2022-11-05 09:51 UTC, hongbin-dev commented on src/main/java/org.prgrms/console/Message.java
> +  }
또 이런 텍스트같은경우는 상수로 관리하면 좋겠네요 ㅎㅎ

2022-11-05 09:51 UTC, hongbin-dev commented on src/main/java/org.prgrms/exception/NoSuchMenuTypeException.java
> +  }
이 예외를 확인하는 개발자는 어떤 키워드인지 알 수 없겠군요~

2022-11-07 14:49 UTC, hongbin-dev approved these changes

2022-11-07 14:49 UTC, merged