[3기-C] 김환 SpringBoot Part1 Weekly Mission제출합니다.
prgrms-be-devcourse/springboot-basic pull request #526
Opened 2022-11-04 14:01 UTC by hwankim123

## 📌 과제 설명 
* 입출력 기능과 메뉴 선택, Exit 기능을 구현하였습니다.

## 👩‍💻 요구 사항과 구현 내용 
(기본) **바우처 관리 애플리케이션**

- [X]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [ ]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [X]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [X]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

   ```bash
   === Voucher Program ===
   Type **exit** to exit the program.
   Type **create** to create a new voucher.
   Type **list** to list all vouchers.
   ```

    - [ ]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.
## ✅ PR 포인트 & 궁금한 점 
* 역할과 책임을 최대한 나눠보려고 했는데, 잘 나뉘었는지 피드백받고 싶습니다.
* String 필드 하나만 넘겨주는 DTO 클래스인 MenuInputResult 클래스를 만들었는데, 너무 과하게 클래스를 만든 것인지, 아니면 적절한 설계인지 궁금합니다.
*  command를 제대로 입력했는지 validation하는 메서드를 MenuInputResult클래스에 추가할지 고민하다가 너무 복잡해져서 일단 MenuHandler에 validate 코드를 포함했는데, 더 좋은 방법이 있을지 궁금합니다.

2022-11-05 04:31 UTC, seung-hun-h requested changes
안녕하세요 김환님, 함승훈입니다.
미션 첫 번째 스텝 잘 구현해주셨네요.
리뷰 남겼으니 확인해주세요!

### 역할과 책임을 최대한 나눠보려고 했는데, 잘 나뉘었는지 피드백받고 싶습니다.
- 
### String 필드 하나만 넘겨주는 DTO 클래스인 MenuInputResult 클래스를 만들었는데, 너무 과하게 클래스를 만든 것인지, 아니면 적절한 설계인지 궁금합니다.
- 단순히 값 하나만 나타낸다면 DTO까지는 만들지 않아도 된다고 생각합니다
- 어떤 행동을 하거나 입력이 두 개 이상이라면 DTO를 만들어도 좋을 것  같네요
### command를 제대로 입력했는지 validation하는 메서드를 MenuInputResult클래스에 추가할지 고민하다가 너무 복잡해져서 일단 MenuHandler에 validate 코드를 포함했는데, 더 좋은 방법이 있을지 궁금합니다.
- command를 validation 하는 부분이 어디에 있을까요?

2022-11-05 04:31 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/SpringbootBasicApplication.java
> +        SpringApplication.run(SpringbootBasicApplication.class, args);
Configuration 클래스를 사용해서 스프링 컨테이너를 생성하고 있으셔서 이 코드랑 `@SpringBootApplication`애너테이션은 아직 필요 없을 것 같아요!

2022-11-05 04:31 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        while (!readyToExit) {
변수명에 부정형이 붙으니 해석하기가 조금 어려울 것 같네요. 이왕 변수로 만드신거 좀 더 이해하기 쉽도록 변경해보는 것은 어떨까요?

2022-11-05 04:31 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/common/config/AppConfiguration.java
> +})
:thumbsup:

2022-11-05 04:31 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/console/Printer.java
> +    private static final String EXIT = "Exit program. Bye.";
- JDK 버전에 따라 다르지만 비교젹 최신 버전에서는 `String`의 `+`연산이 내부적으로 `StringBuilder`를 사용하는 것으로 알고 있습니다. 아마 그래서 IDE에서 추천해준 것 같네요
https://siyoon210.tistory.com/160

- 지금 메뉴 메시지가 `Printer`에서 관리되고 있는데요. 제 생각으로는 이 메시지는 MenuHanlder 같은 메뉴와 관련된 클래스에서 관리되어야 한다고 생각합니다. Printer는 메시지를 출력해주는 역할로 충분할 것 같네요

2022-11-05 04:31 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/handler/menu/CommandType.java
> +    }
👍

2022-11-05 04:31 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +            readyToExit = menuHandler.handleBeforeExit();
VoucherApplication에서 `Menuhandler`의 메서드만 호출해주고 있네요. 그렇다면 `Menuhandler`는 사용자 I/O와 명령까지 처리 해주어야 할 텐데요. 이를 분리해주면 좋을 것 같네요.

2022-11-05 12:21 UTC, hongbin-dev requested changes
환님 고생많으셨어요~!

>> 역할과 책임을 최대한 나눠보려고 했는데, 잘 나뉘었는지 피드백받고 싶습니다.

기본적으로 날 나눠주신 것 같아요. 추가적으로 패키지를 잘 나누면 타인이 프로젝트를 접할 때 식별하기 좋은데요. app과 hanlder의 성격이 조금 겹치는 것 같네요. 패키지 구조도 고민해보면 좋을 것 같아요.

>> String 필드 하나만 넘겨주는 DTO 클래스인 MenuInputResult 클래스를 만들었는데, 너무 과하게 클래스를 만든 것인지, 아니면 적절한 설계인지 궁금합니다.

리뷰에 의견 남겼어요~

>> command를 제대로 입력했는지 validation하는 메서드를 MenuInputResult클래스에 추가할지 고민하다가 너무 복잡해져서 일단 MenuHandler에 validate 코드를 포함했는데, 더 좋은 방법이 있을지 궁금합니다.

현재 `CommandType` 가 검증해주고 있는걸로보이는데요. 그럼 입력객체는 무엇을 검증하면 좋을까요?

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        while (!readyToExit) {
readyToExit처럼 바우처프로그램의 상태를 관리하는 객체를 만들어보는건 어떨까요?

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +            readyToExit = menuHandler.handleBeforeExit();
승훈님이 말씀하신 것 처럼 명령(메뉴 로직 실행)/값 생성(boolean) 두가지 일을 하고 있네요.

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/MenuHandler.java
> +            default -> console.printInvalidMessage(COMMAND_NOT_SUPPORTER);
잘못 된 메시지기 무엇인지 알려줄지 알았는데, 에러 메시지를 알려주고있네요?

전자를 생각하셨다면 아래처럼, 
```suggestion
            default -> console.printInvalidMessage(command);
```

후자라면 출력객체가 책임지는게 좋아보입니다. 
```suggestion
            default -> console.printInvalidMessage();
```

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/MenuHandler.java
> +        switch (command) {
switch expressions 👍

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/MenuHandler.java
> +    public boolean handleBeforeExit() {
메서드명이 길어지는건 어려일을 하는거라고 생각되어요. 이전 코멘트 보고 피드백 반영부탁드려요~

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/dto/MenuInputResult.java
> +public class MenuInputResult {
MenuInput 라는 네이밍으로도 대치가 가능해보여요.

아직 DTO가 불필요하다고 생각하는데요. 조금 과하다는 생각은 드네요.

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/CommandType.java
> +    }
orElseThrow()에서 inputCommand 값까지 함께 예외메시지에 넣어주면 식별하기 좋을 것 같아요~

2022-11-05 12:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/console/Printer.java
> +    // Builder쓴 이유는 상수라 동기화 문제가 없지 않을까 생각돼서입니다.
주석은 최대한 지양해주시고, 이런 PR 관련된 내용은 깃헙에 comment 로 남겨주시면 좋을 것 같아요 ㅎ

2022-11-06 10:23 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/SpringbootBasicApplication.java
> +        SpringApplication.run(SpringbootBasicApplication.class, args);
@seung-hun-h Configuration 클래스를 그대로 사용하고, SpringBootApplication으로 실행되지 않도록 수정하였습니다!

2022-11-06 10:27 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        while (!readyToExit) {
@seung-hun-h @hongbin-dev 두분 의견 반영해서, `ApplicationSataus`라는 앱 상태를 저장하는 클래스를 생성하였고, `Application.isRunning()` 메서드로 while문의 조건을 검사하도록 변경하였습니다!

2022-11-06 10:28 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/console/Printer.java
> +    private static final String EXIT = "Exit program. Bye.";
@seung-hun-h 블로그 내용 확인했습니다! 제 코드의 경우 내부적으로 `StringBuilder`를 사용하네요. `+` 연산자로 String 상수 생성하도록 수정해습니다.

2022-11-06 10:30 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +            readyToExit = menuHandler.handleBeforeExit();
@seung-hun-h @hongbin-dev 확실히 `MenuHandler.handleBeforeExit()`가 두 가지 역할을 한다고 느껴지네요... I/O 처리를 `VoucherApplication`가 하도록 수정하였습니다.

2022-11-06 10:34 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/handler/menu/MenuHandler.java
> +            default -> console.printInvalidMessage(COMMAND_NOT_SUPPORTER);
@hongbin-dev 출력객체에서 COMMAND_NOT_SUPPORTED 문자열을 전달해주고, 출력객체가 해당 문자열을 출력하려는 의도였는데, 출력객체가 COMMAND_NOT_SUPPORTED를 갖고있는게 더 나은 방식인가요?

2022-11-06 10:35 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/console/Printer.java
> +    // Builder쓴 이유는 상수라 동기화 문제가 없지 않을까 생각돼서입니다.
@hongbin-dev 나중에 PR때 같이 물어본다는걸 까먹었네요...ㅠ push하기 전에 확실히 확인해보겠습니다!

2022-11-06 10:36 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/handler/menu/MenuHandler.java
> +    public boolean handleBeforeExit() {
@hongbin-dev 반영했습니다! 메서드명에서도 여러 역할을 맡고있다는게 느껴지네요... 반영했습니다!

2022-11-06 10:42 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/handler/menu/dto/MenuInputResult.java
> +public class MenuInputResult {
@seung-hun-h @hongbin-dev 그당시에는 String을 그대로 return하는 것보다 클래스명으로 데이터를 파악할 수 있도록 DTO로 감싸는 것이 코드를 이해하기 더 좋을 거라고 생각했습니다. 굳이 String 변수 하나를 DTO로 감싸지 않아도 메서드명으로 충분히 의미전달이 된다면 String으로 넘겨주도록 수정하겠습니다!

2022-11-07 05:22 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/handler/menu/CommandType.java
> +    }
@hongbin-dev 확실히 유저 입장에서 봤을 때 더 좋은 방식일 것 같네요. 반영했습니다!

2022-11-07 12:39 UTC, seung-hun-h approved these changes

2022-11-07 15:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/MenuHandler.java
> +            default -> console.printInvalidMessage(COMMAND_NOT_SUPPORTER);
넵 출력 내용이 바뀌면 출력객체가 변경되어야하는데요. `MenuHandler`를 변경해야하는 단점이 있네요.
출력객체의 책임이라고 생각됩니다.

2022-11-07 15:22 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/dto/MenuInputResult.java
> +public class MenuInputResult {
지금단계에서 DTO가 불필요하다고 생각된다고 생각해요.

2022-11-07 15:24 UTC, hongbin-dev approved these changes
환님 피드백 반영 좋네요. 추가 의견있으니 그건 다음단계에서 적용부탁드려요!
고생하셨습니다

2022-11-07 15:24 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/app/ApplicationStatus.java
> +        running = false;
👍 

이 객체는 컴포넌트로 관리할 필요가 없어보이는데요. 

스프링 Bean은 어떤 특성이 있고,어떤 객체를 스프링 Bean으로 관리하면 좋을지 고민해보면 좋을 것 같아요.

2022-11-07 15:24 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/handler/menu/CommandType.java
> +                .orElseThrow(() -> new IllegalArgumentException(
MessageFormat 이라는 친구도 있군요 👍

2022-11-08 01:46 UTC, merged