[3기-C] 김선호 SpringBoot Part1 Weekly Mission 제출합니다.(1차)
prgrms-be-devcourse/springboot-basic pull request #528
Opened 2022-11-04 19:06 UTC by preferKim

안녕하세요! SpringBoot Part(1) 위클리미션 1차 PR합니다!

## 📌 과제 설명

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [ ]  바우처 관리 Command-line Application을 만들어본다.
   
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

   ```bash
   === Voucher Program ===
   Type **exit** to exit the program.
   Type **create** to create a new voucher.
   Type **list** to list all vouchers.
   ```
    - [x]  exit 커맨드를 지원한다.

## 👩‍💻 구현 내용 

- 메뉴 입출력 구현
- exit 커맨드 지원 

## ✅ PR 포인트 & 궁금한 점 

- 스프링 빈이나 의존성 주입에 대해 개념을 익혀가고 있습니다. 이와 관련된 어노테이션을 적절하게 사용했는지 궁금합니다.
- 코드 가독성이 괜찮은지 궁금합니다. 변수명이나 메서드명 등 의미가 불분명하다 싶은 것들을 짚어주시면 감사하겠습니다!

2022-11-05 05:21 UTC, seung-hun-h requested changes
선호님 안녕하세요, 함승훈입니다
Enum도 잘 활용해 주셨고, 테스트도 작성해 주신 점 좋았습니다.
리뷰 남겼으니 확인해주세요!

#### 스프링 빈이나 의존성 주입에 대해 개념을 익혀가고 있습니다. 이와 관련된 어노테이션을 적절하게 사용했는지 궁금합니다.
- `@Configuration` 애노테이션을 사용해서 빈을 등록해 주신점 잘하신 것 같아요
- 스프링 컨테이너에 빈을 등록하고 싶을 떄 보통 `@Bean`이나 `@Component`를 사용해요. 스프링은 왜 두 가지를 만들어 뒀을까요? 두 애노테이션의 용도에 대해서 생각해보면 더 좋을 것 같네요

 #### 코드 가독성이 괜찮은지 궁금합니다. 변수명이나 메서드명 등 의미가 불분명하다 싶은 것들을 짚어주시면 감사하겠습니다!
- 전반적으로 잘 작성해 주신 것 같네요

2022-11-05 05:21 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/config/AppConfig.java
> +    }
`RunningState` 클래스를 빈으로 등록하셨네요! 왜 빈으로 관리하는 것이 좋을 것이라 생각하셨나요?

스프링에서는 빈을 기본적으로 [싱글턴](https://tecoble.techcourse.co.kr/post/2020-11-07-singleton/)으로 관리하고 있습니다. 멀티 스레드 환경에서 싱글턴의 단점을 한 번 알아보는 것도 좋을 것 같네요

2022-11-05 05:21 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/VoucherManagementController.java
> +        if (menuType.equals(MenuType.EXIT)) {
Enum은 기본적으로 싱글턴입니다. Enum의 상수들은 각각이 클래스의 인스턴스에요. 그러니 `equals`를 사용하지 않아도 되죠. `==`으로 비교해 보는 것은 어떨까요?

추가적으로 `menuType.isExit()`처럼 메서드를 호출하는 것도 좋아 보이네요

2022-11-05 05:21 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/MenuType.java
> +                .orElseThrow(NoSuchFieldError::new);
예외를 던질때 메시지도 함께 전달하면 더 좋을 것 같네요

2022-11-05 05:21 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/MenuType.java
> +public enum MenuType {
👍

2022-11-05 05:21 UTC, seung-hun-h commented on src/test/java/prgms/vouchermanagementapp/controller/VoucherManagementControllerTest.java
> +            = new AnnotationConfigApplicationContext(AppConfig.class);
이 코드는 필요한 코드인가요??

2022-11-05 05:21 UTC, seung-hun-h commented on src/test/java/prgms/vouchermanagementapp/controller/VoucherManagementControllerTest.java
> +    void should_throw_exception_for_invalid_menuType() {
테스트도 작성해주셨네요! 테스트 메서드 이름도 잘 작성하신 것 같아요
`@DisplayName`을 사용해보는 것도 좋을 것 같네요

2022-11-05 13:08 UTC, hongbin-dev requested changes
안녕하세요 선호님!
패키지 구조가 잘 되어있네요. 코멘트 확인 부탁드려요~!

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/VoucherManagementApp.java
> +	}
쓰레드를 추가하신 이유가 있을까요?

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/controller/RunningState.java
> +    }
👍👍

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/controller/VoucherManagementController.java
> +        if (menuType.equals(MenuType.EXIT)) {
`menuType.isExit()` 좋네요. 객체에게 메시지를 보내봐요~

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/controller/VoucherManagementController.java
> +            writer.print(MenuType.getMessages());
```suggestion
            writer.printMenuMessage()
```
여기도 마찬가지에요. 객체에게 메시지를 보내봐요

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +    }
제네릭의 <?>는 어떤걸 뜻하는걸까요~?

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +    }
Object는 아니되옵니다..!! 다른사람이 봤을 때, 어떤 객체가 올지 모르게됩니다. 이해하기 어려워져요.

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/message/ExceptionMessage.java
> +
출력하는 객체 메세지를 알고있는게 좋을 것 같아요. 현재 응집되어있지 않고 있어요

2022-11-05 13:08 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/message/ExceptionMessage.java
> +    }
toString을 비즈니스로직으로 오버라이딩하는건 일반적이지 않습니다.
로그의 목적으로 많이 사용하게되는데요. 이 부분에 다른개발자가 혼동이 올 수 있습니다.

2022-11-05 13:09 UTC, hongbin-dev commented
> 코드 가독성이 괜찮은지 궁금합니다. 변수명이나 메서드명 등 의미가 불분명하다 싶은 것들을 짚어주시면 감사하겠습니다!

전반적으로 잘 해주신 거 같습니다! 또 코멘트에 남겼으니 반영해보면 좋을 것 같아요 ㅎㅎ
중간중간 띄어쓰기, 포맷등이 안맞는 부분이 있는데요. 인텔리제이 포매터를 활성화해놓으면 좋을 거 같아요

2022-11-06 16:02 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +    }
@hongbin-dev `어떤 객체가 오든 출력해줄거야` 라는 의도를 갖고 작성했던 메서드인데, 오히려 이게 더욱 이해하기 어려워지는 방향이었군요? 일단 `어떤 객체가 오든 출력해줄거야` 라는 의도를 표현해주기 위해서 코드를 아래와 같이 수정해보았습니다.

```java
public <T> void print(T message) {
    System.out.println(message);
}
```

그런데 이렇게 수정한 코드 역시 이해하기 어려운 코드에 속하는 것 같습니다.

```java
public void print(String message) {
      System.out.println(message);
}
```
최종적으로는 위와같이 수정했는데,  역시 타입을 조금 더 type-safe 하게 작성하는 것이 더 좋다고 생각해서입니다.🤔

위에대한 앨런님의 견해가 궁금합니다..!

2022-11-06 16:06 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +    }
피드백 적용해본 커밋입니다! [Refactor: Writer의 type-safety 하지 않은 파라미터를 분명한 type으로 변경](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528/commits/4ed062130a68ce64c3d94c238ffe4ec53b717877)

2022-11-06 16:09 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/VoucherManagementController.java
> +        if (menuType.equals(MenuType.EXIT)) {
@seung-hun-h @hongbin-dev 
[Refactor: 메뉴 타입을 확인하는 책임을 MenuType이 책임지도록 변경](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528/commits/1e0255504b1fd81d9b72a287560f84727b56078d)

- 기존에 Controller가 갖는 '입력된 메뉴를 확인하는 책임'을 MenuType이 갖도록 변경했습니다. 
- 다만 위 커밋과 같이 작성하는 경우 MenuType이 추가될 때마다 `isMenu()` 메서드를 계속 추가하게되는 구조인데, 어떻게 개선시키면 좋을 지 궁금합니다.

2022-11-06 16:12 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/MenuType.java
> +                .orElseThrow(NoSuchFieldError::new);
[Refactor: 존재하지 않는 MenuType을 입력하는 경우 발생하는 예외에 대한 메시지 추가](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528/commits/29906b566d3d822b23469764377831c909a07f42)

- 피드백 반영하였습니다! 
- (질문) `getMessage()` 처럼 직접 enum의 필드를 가져와서 함께 전달하는 방식은 괜찮을까요..? 승훈님의 의견이 궁금합니다!

2022-11-06 16:15 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/VoucherManagementApp.java
> +	}
@hongbin-dev 

[Refactor: 쓰레드를 사용하지 않고 앱이 실행되게 변경](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528/commits/4a2123eba37144ef35711e15d9f5359c94df95fc)

- 딱히 의도는 없었습니다. 따라서 해당 부분을 삭제하였습니다.
- ➡ 앞으로는 어떤 코드를 작성할 때는 이유가 있는 코드를 작성하도록 해봐야겠습니다.

2022-11-06 16:18 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/VoucherManagementController.java
> +            writer.print(MenuType.getMessages());
@hongbin-dev 

[Refactor: 기존의 Controller가 갖는 '어떤 메시지를 출력할 것인지 정하는 책임'을 Writer에게 위임](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528/commits/f5e1607189c7112c7ad13f2c2222a86e97e039ef)

- 피드백을 적용하여 Controller 객체가 Writer 객체에게 메시지를 보내도록 수정했습니다.
- ❓ 커밋에 작성한 것처럼 수정하다 보면 모든 메뉴 타입에 대응하는 메서드를 하나씩 만들어야 될텐데 이 부분은 '불필요한 코드의 중복' 인지, 아니면 'SRP'를 잘 지키는 방법인지 궁금합니다.
- ❓ 더 나은 방법으로 개선시킨다면 어떤 방법이 있을 지 궁금합니다!

2022-11-06 16:24 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +    }
@hongbin-dev 
[Refactor: Writer의 type-safety 하지 않은 파라미터를 분명한 type으로 변경](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528/commits/4ed062130a68ce64c3d94c238ffe4ec53b717877)

- (답변) 제네릭의 `<?>`  는 와일드 카드 사용시 사용하는 기호로, upper-bound 또는 lower-bound 를 지정하기 위해 사용합니다!
- '`특정한 타입으로만 이루어진 리스트` 를 모두 순회하며 출력한다.' 라는 의도로 작성했는데, 결론적으로는 `어떠한 타입이든 들어갈 수 있는 리스트` 를 사용한 꼴이 되었습니다. 
-  ❓ '`특정한 타입으로만 이루어진 리스트` 를 모두 순회하며 출력한다.' 를 어떻게 구현해야할지 잘 생각이 나지 않습니다. 조언 부탁드려도 될까요?
- ♻ 일단은 커밋 메시지 처럼 String 타입의 리스트만 받을 수 있도록 변경해두었습니다!

2022-11-06 16:27 UTC, preferKim commented
@hongbin-dev @seung-hun-h 

- 우선 OOP와 Java에 관한 부분만 피드백을 적용했습니다!
- Spring에 관련한 부분은 수정하여 2차 PR때 적용해보도록 하겠습니다!

2022-11-06 16:31 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/message/ExceptionMessage.java
> +
@hongbin-dev 

[Refactor: 기존의 Controller가 갖는 '어떤 메시지를 출력할 것인지 정하는 책임'을 Writer에게 위임](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528/commits/f5e1607189c7112c7ad13f2c2222a86e97e039ef)

- ♻ 출력하는 객체 메시지를 Writer 에서 알고있는게 좋을 것 같아 위와 같이 수정해보았습니다. 
- ❓ 혹시 제가 잘못 이해한 걸까요..?

2022-11-06 16:33 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/message/ExceptionMessage.java
> +    }
@hongbin-dev 

😮 생각해보지 못했던 내용입니다..!
- ♻ 비즈니스 로직으로 오버라이딩 되어있던 toString 메서드를 제거하였습니다.

2022-11-06 17:03 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/message/ExceptionMessage.java
> +
[Refactor: Writer가 출력하는 객체 메시지들을 알 수 있게 변경](https://github.com/preferKim/devcourse-springboot-basic/commit/f8cb2b5dc1f3b71940fb5e8eaf1592f1ff238dd7)

- ♻ 현재 PR에 반영되어있진 않지만, 커밋과 같이 Controller 는 실제로 어떤 메시지가 출력되는지는 모르게끔 수정을 해봤습니다. 
-  ❗ 혹시 이것을 말씀하셨던 걸까요!

2022-11-07 12:33 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/VoucherManagementController.java
> +        if (menuType.equals(MenuType.EXIT)) {
흠.. 작성할 코드의 수를 줄이기 위해서는 

```
menuType.is(MenuType.EXIT);
```

같은 메서드를 구현 해볼 수도 있겠네요.

2022-11-07 12:36 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/MenuType.java
> +                .orElseThrow(NoSuchFieldError::new);
개인적인 생각으로는 예외 메시지까지 Enum으로 관리해야 하나 싶기도 합니다.
예외 메시지는 보통 개발자가 보는 메시지니, 알아볼 수 있는 정도로 작성하면 좋을 것 같아요. 그리고 예외 메시지에는 어떤 값이 들어와서 예외가 발생했는지도 같이 보여주면 좋을 것 같습니다

2022-11-07 15:38 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/controller/VoucherManagementController.java
> +            writer.print(MenuType.getMessages());
앗 이 부분은 제가 컨텍스트를 놓쳐 이해를 못했군요. 선호님이 작성해주신 방향으로 가는게 일반적인 것 같습니다.

다만 `MenuType.getMessages()`이 부분이 단순 출력을 위한 메서드가 아닌가? 생각이 들었습니다. print()에 기존에 제공하는`MenuType.values()`를 넘기고 출력객체에서 포맷을 설정하는건 어떨까요?

2022-11-07 15:38 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +    }
지금은 출력할 객체를 toString()을 오버라이딩하여 

`list.forEach(System.out::println);` 이 코드를 사용하려고 하는 것 같은데요. 결국 그 부분이 잘못되엇기때문에, 파라미터도 아무거나 들어올 수 있게 되었네요.

모든걸 다 출력해주려는 메서드보다, 단일책임을 지킬 수 있는 메서드를 만들어보면 어떨까 싶어요. 예를들어

`메뉴를 출력한다`
`정률바우처 정액바우처 선택지를 출력한다`

2022-11-07 15:39 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +    }
`어떤 객체가 오든 출력해줄거야` 지금 하나의 객체(String)만 오지않나요..!? 불필요한 확장성 고려입니다ㅜㅜ
 또 이 부분도 toString()에 출력로직이 들어가서 존재할 수 있는 코드군요

타입 제약이 없는 코드를 작성하는건, 다른사람이 코드를 봤을 때 혼동을 줄 수 있습니다.

2022-11-07 15:42 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/message/ExceptionMessage.java
> +
ExceptionMessage가 불필요하다고 말씀드릴걸 그랬네요! 
여기에 들어가는 코드가 `Writer`에 들어가는게 낫다고 생각했어요.

2022-11-07 15:44 UTC, hongbin-dev approved these changes
선호님! 고생많으셨습니다.
피드백은 다음스텝에 진행해주세요.
또 코멘트에 궁금하신점은 슬랙채널에서 이야기해주셔도 되어요~!

2022-11-07 16:05 UTC, merged

2022-11-10 09:43 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/config/AppConfig.java
> +    }
> `RunningState` 클래스를 빈으로 등록하셨네요! 왜 빈으로 관리하는 것이 좋을 것이라 생각하셨나요?
> 
> 스프링에서는 빈을 기본적으로 [싱글턴](https://tecoble.techcourse.co.kr/post/2020-11-07-singleton/)으로 관리하고 있습니다. 멀티 스레드 환경에서 싱글턴의 단점을 한 번 알아보는 것도 좋을 것 같네요

[Refactor: RunningState 객체를 Bean으로 등록하지 않고, Controller가 직접 생성하도록 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/0efa160929936e82afd47b3c8266daaf43612605)

♻️ Stateful 한 RunningState 클래스를 스프링 빈으로 등록되지 않게 수정하였습니다! 

➡️ 상태를 가지는 객체가 싱글톤으로 등록되면 멀티 스레드 환경에서 의도치 않은 상태 변경이 일어날 수 있기 때문입니다!

2022-11-10 09:52 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/MenuType.java
> +                .orElseThrow(NoSuchFieldError::new);
@seung-hun-h 
> 개인적인 생각으로는 예외 메시지까지 Enum으로 관리해야 하나 싶기도 합니다. 예외 메시지는 보통 개발자가 보는 메시지니, 알아볼 수 있는 정도로 작성하면 좋을 것 같아요. 그리고 예외 메시지에는 어떤 값이 들어와서 예외가 발생했는지도 같이 보여주면 좋을 것 같습니다

♻️ '어떤 값이 들어와서 예외가 발생하는지'를 중점적으로 생각하며 예외처리를 해보았습니다!

[Feat(create): Amount, Ratio 객체 유효성 검증](https://github.com/prgrms-be-devcourse/springboot-basic/commit/cd79d0ddaaa1a0fe99d596e9851cb71d018bb9ae)
[Feat(create): 유효하지 않은 할인 금액, 할인 비율 입력에 대한 예외 처리](https://github.com/prgrms-be-devcourse/springboot-basic/commit/aa19c3718783fc4c3d008673e40bee25e55662a6)
[Feat(exception): 유효하지 않은 커맨드 입력에 대한 예외처리](https://github.com/prgrms-be-devcourse/springboot-basic/commit/c339a77685ab0e70d05bc2e280c34d01436c65e1)
[Feat(exception): 유효하지 않은 바우처 타입 선택에 대한 예외처리](https://github.com/prgrms-be-devcourse/springboot-basic/commit/e08a258981340769d15a511ab872ee14a68afbf6)

❗️ 최대한 '입출력을 하는 객체' 근처에서 예외처리를 하도록 구성했고, 해당 객체가 알면 안될 것 같은 정보 (VouhcerType Enum) 
등은 Controller 성격의 CommandExecutor 클래스에서 예외처리를 해주었습니다.

2022-11-10 09:59 UTC, preferKim commented on src/test/java/prgms/vouchermanagementapp/controller/VoucherManagementControllerTest.java
> +            = new AnnotationConfigApplicationContext(AppConfig.class);
@seung-hun-h 

> 이 코드는 필요한 코드인가요??

♻️ 컴포넌트 스캔과 AutoWired를 이용하여 스프링 빈 등록에 대한 부분을 리팩토링 하였습니다. @SpringBootApplicatoin 이 제공하는 기능을 활용해서 코멘트 남겨주신 코드 부분 또한 다른 방식으로 대체했습니다. 정확한 내부 동작 원리까지는 이해하지 못했지만, 계속해서 공부해가겠습니다!

[Refactor(Configuration): 스프링 빈 대신 컴포넌트 스캔을 이용하여 스프링 컨테이너에 객체 등록](https://github.com/prgrms-be-devcourse/springboot-basic/commit/3e3c2c4e0a94e1134cace9dde37b2a7b294be023)