[3기-C] 권성준 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #530
Opened 2022-11-06 19:48 UTC by Seongjun-Kwon

## 📌 과제 설명 
안녕하세요 마르코님, 명환님! 
스프링부트 1주차 바우처 관리 프로그램 코드 리뷰 부탁드립니다!
잘부탁드립니다. 감사합니다! 

## 👩‍💻 요구 사항과 구현 내용
### 요구 사항
(기본) **바우처 관리 애플리케이션**
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)

- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능
- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

### 클래스 다이어그램
![voucher_uml](https://user-images.githubusercontent.com/82152173/200182636-46f8ae9f-4ece-4a7d-b570-584e90e3f5d8.PNG)

### 주요 클래스 설명
- controller
  - `Command` : 사용자가 입력할 수 있는 create, list, blacklist, exit 명령어들을 관리합니다.
  - `Message` : 프로그램 동작 과정에서 사용자에게 출력하는 메시지를 관리합니다.
  - `VoucherController` : 사용자의 명령에 따른 바우처 관리 프로그램 동작 흐름을 담당합니다.

- domain
  - customer
    - `Customer` : 고객 정보를 가지고 있는 클래스이고, id와 type을 가지고 있습니다.
    - `CustomerType` : 고객 타입을 관리합니다. Normal, Blacklist 2가지 타입으로 관리합니다.
    - `FileCustomerRepository` : 파일로 고객들의 정보를 저장, 조회합니다.  현재는 블랙리스트 타입 고객만 조회하는 기능만 가집니다.
    - `CustomerService` : 고객 관련 서비스를 담당합니다.
  - voucher
    - `FixedDiscountVoucher` : 고정형 할인 바우처입니다.
    - `PercentDiscountVoucher` : 비율형 할인 바우처입니다.
    - `VoucherType` : 바우처 타입을 별도로 관리하는 enum입니다.
    - `FileVoucherRepository` : 파일로 바우처를 저장하고, 파일에서 바우처를 조회합니다. dev, test 프로파일에서 동작합니다.
    - `MemoryVoucherRepository` : 메모리에서 바우처를 저장, 조회합니다. local 프로파일에서 동작합니다.
    - `VoucherService` :  바우처 관련 서비스를 담당합니다.
    - `Validator` : 사용자가 create 명령으로 바우처를 생성할 때, 잘못된 입력값을 넣었는지 검증합니다.
    - `VoucherFactory` : 입력 받은 값에 따라 바우처 구현체를 만들어줍니다. 
- exception
  - `ExceptionMessage` : 예외 발생 시 출력하는 메시지들을 관리합니다.
  - `OutOfPercentRangeException` : PercentDiscountVoucher 생성 시, 할인 비율로 0~100 이외의 값을 넣었을 때 발생합니다.
  - `VoucherNotFoundException` : VoucherRepository 에서 바우처를 조회할 수 없을 경우 발생합니다.
  - `WrongCommandException` : 사용자가 create, list, blacklist, exit 가 아닌 잘못된 명령어를 입력했을 때 발생합니다.
  - `WrongDiscountTypeException` : 할인 입력 값이 숫자가 아닐 경우 발생합니다.
  - `WrongVoucherTypeException` : 생성하고자 하는 바우처 타입을 잘못 입력했을 시 발생합니다.
- io
  - `ConsoleInput` : 콘솔에서의 입력을 담당합니다.
  - `ConsoleOutput` : 콘솔에서의 출력을 담당합니다.

## ✅ PR 포인트 & 궁금한 점
1. 추상화에 신경 써서 변경 사항이 생겼을 때, 코드 수정을 최소화해보고자 했습니다.
객체지향적이지 않거나, 가독성이 떨어지는 부분들을 가감 없이 이야기해주시면 감사하겠습니다!

2. 코드에 대한 질문은 댓글로 남기겠습니다.

2022-11-06 20:01 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/controller/VoucherController.java
> +			}
예외가 발생한 각 지점에서도 로그를 찍어주고 최종적으로 최상단인 Controller 에서도 로그를 찍어줍니다. 저는 예외가 던져지고 처리되는 지점을 알 수 있어 좋지 않을까 생각했습니다.
다만 어차피 같은 예외인데 중복으로 기록하지 않아도 될 것 같다는 생각도 들어서 질문드립니다.
보통 에러 로그는 발생 지점만 기록하는지 아닌지 궁금합니다.

2022-11-06 20:26 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/repository/VoucherRepository.java
> +	void clear();
테스트용으로 clear 메소드를 만들었는데 테스트용으로 메서드를 만드는 것이 좋지 않은 행위일까요?

2022-11-06 20:26 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/repository/FileVoucherRepository.java
> +			}
파일을 한줄마다 읽어서 Voucher 객체 생성에 필요한 id, type, discount를 얻은 뒤 만들어주는 과정입니다.
파일 형식을 미리 알고 있지 못하면 가독성이 떨어지는 코드 같아서 개선할 방법을 생각해봤는데 주석으로 명시해주는 것 말고는 떠오르지가 않습니다 😥
보통 어떤 방식을 사용하는지 궁금합니다.

2022-11-07 23:52 UTC, ksy90101 commented on src/main/java/com/programmers/voucher/controller/VoucherController.java
> +			}
네 발생지점만 기록합니다.

2022-11-07 23:53 UTC, ksy90101 commented on src/main/java/com/programmers/voucher/domain/voucher/repository/VoucherRepository.java
> +	void clear();
clear정돈 괜찮아요.

2022-11-07 23:53 UTC, ksy90101 commented on src/main/java/com/programmers/voucher/domain/voucher/repository/FileVoucherRepository.java
> +			}
정책이 말씀하신 대로이기 때문에, 지금도 충분할듯 해요.

2022-11-08 00:01 UTC, ksy90101 requested changes
안녕하세요 성준님.
고생 많으셨습니다 👍 
간단한 피드백을 남겻는데요. 이번 피드백의 주제는 Buffer~이 친구를 어떻게 관리해야 하는가 (close를 하자.)이며, try~catch~resource라는 키워드까지 한번 공부해보면 좋을듯 합니다.
피드백 적용되면, 스레드로 꼭 남겨주세요.

2022-11-08 00:01 UTC, ksy90101 commented on src/main/java/com/programmers/voucher/exception/OutOfPercentRangeException.java
> +public class OutOfPercentRangeException extends RuntimeException {
커스텀 익셉션을 공부하는 목적도 좋지만, 무조건적인 커스텀 익셉션은 지양해야 한다고 생각합니다.

https://github.com/Meet-Coder-Study/book-effective-java/blob/main/10%EC%9E%A5/72_%ED%91%9C%EC%A4%80_%EC%98%88%EC%99%B8%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EA%B9%80%EC%9E%AC%EC%A4%80.md

이글을 한번 참고해보세요.

2022-11-08 06:14 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/controller/Command.java
> +			.filter(i -> i.command.equals(chosenCommand))
생각하지 못한 부분이었네요😂 다른 의미 없는 변수들도 찾아서 수정했습니다.

2022-11-08 06:41 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/repository/FileCustomerRepository.java
> +	private Logger log = LoggerFactory.getLogger(FileCustomerRepository.class);
static final에 대해 대충 알고 있었던 것 같아요. 이번 기회에 정리해봤습니다.😄

### 상수와 static final

#### 상수는 어떤 것일까?
1. 사용하는 모두에게 같은 값이어야함.
2. 값이 변하지 않아야 함.

#### 왜 상수를 선언할 때 static final 키워드를 붙일까?

- static의 의미
static이 아닌 데이터들은 런타임 시점에 동적으로 메모리에 할당되는데
static 키워드가 붙은 데이터는 컴파일시점에 가비지컬렉터의 관리 밖인 static영역에 할당되므로 실행 직후부터 끝날때까지 쭉 유지됨

- final의 의미
초기화를 한번만 허용한다는 의미. 즉, 한번 초기화되면 더 이상 초기화할 수 없다.
  
- 의문이 생겼던 부분
그럼 final만 붙어도 상수아닌가? 왜 static까지 붙여줘야 하지?
final 만 있으면 `모두에게 같은 값이라는 것을 보장할 수 없다!`
A와 B라는 사용자가 C변수에 final 키워드를 줬다고 해보자. 초기화 후 사용자 각각에게는 C는 변하지 않는 값이겠지만, 각자 다른 값으로 초기화를 했다면?
우리가 생각하는 상수의 의미를 만족시키지 못한다.

- 결론
static final을 함께 사용하여 모두에게 동일하고 변하지 않는 값을 만들자

2022-11-08 09:33 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/repository/FileCustomerRepository.java
> +				String[] customerInfo = line.split(", |: ");
수정했습니다! 상수로 바꿔주니 무엇을 뜻하는지 훨씬 알기 쉬운 것 같습니다😀

2022-11-08 09:35 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/model/PercentDiscountVoucher.java
> +		return beforeDiscount * (percent / 100);
100을 네이밍 하기가 너무 어렵네요😂 HUNDRED는 바꿔주는 의미가 없을 것 같고, PERCENT_TO_RATIO 로 하니  `@Override
	public int discount(int beforeDiscount) {
		return beforeDiscount * (percent / PERCENT_TO_RATIO);`

2022-11-08 09:36 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/model/PercentDiscountVoucher.java
> +		return beforeDiscount * (percent / 100);
100을 네이밍 하기가 너무 어렵네요😂 HUNDRED는 바꿔주는 의미가 없을 것 같고, PERCENT_TO_RATIO 로 하니 @Override public int discount(int beforeDiscount) { return beforeDiscount * (percent / PERCENT_TO_RATIO);

2022-11-08 09:58 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/model/PercentDiscountVoucher.java
> +		return beforeDiscount * (percent / 100);
100을 네이밍 하기가 너무 어렵네요😂 HUNDRED로 하려니 바꿔주는 의미가 없을 것 같고, PERCENT_TO_RATIO 는 100의 의미를 전달하지 못하는 것 같아서 PERCENT_100 으로 바꿔봤습니다

2022-11-08 10:12 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/repository/MemoryVoucherRepository.java
> +	private static final HashMap<UUID, Voucher> repository = new HashMap<>();
수정했습니다!

2022-11-09 07:41 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/repository/FileCustomerRepository.java
> +			BufferedReader reader = new BufferedReader(new FileReader(filePath));
- BufferedReader, BufferedWriter 사용 후 close 해야하는 이유
가비지 컬렉터는 외부에서 객체를 참조하는 변수가 없을 때 가비지로 판단하고 삭제합니다.
메서드가 끝나는 순간 객체를 참조하는 것이 없기에 없애버리기에
가비지 컬렉터에 의해서 bufferedreader가 정리되긴 하지만,
가비지 컬렉터로 정리되기전에 bufferedreader가 연속으로 사용되면 정상적으로 작동안함특히 writer

2022-11-09 07:43 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/repository/FileCustomerRepository.java
> +			BufferedReader reader = new BufferedReader(new FileReader(filePath));
#### BufferedReader, BufferedWriter 사용 후 close 해야하는 이유
가비지 컬렉터는 외부에서 객체를 참조하는 변수가 없을 때 가비지로 판단하고 삭제합니다.
메서드가 끝나는 순간 객체를 참조하는 것이 없기에 없애버리기에
가비지 컬렉터에 의해서 bufferedreader가 정리되긴 하지만,
가비지 컬렉터로 정리되기전에 bufferedreader가 연속으로 사용되면 정상적으로 작동하지 않을 수 있습니다.
특히, BufferedWriter의 경우가 그럴 수 있다고 하는군요.

2022-11-09 08:39 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/exception/OutOfPercentRangeException.java
> +public class OutOfPercentRangeException extends RuntimeException {
WrongCommandException, WrongDiscountTypeException, WrongVoucherTypeException, OutOfPercentRangeException 는 IllegalArgumentException 와 맥락이 비슷하다고 여겨 예외 타입은  IllegalArgumentException을 이용하고 상세한 내용은 예외 메시지로 전달해주는 방식으로 변경했습니다.

2022-11-09 08:49 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/repository/FileCustomerRepository.java
> +			BufferedReader reader = new BufferedReader(new FileReader(filePath));
#### BufferedReader, BufferedWriter close 해야하는 이유
가비지 컬렉터는 외부에서 객체를 참조하는 변수가 없을 때 가비지로 판단하고 삭제합니다.
메서드가 끝나는 순간 객체를 참조하는 것이 없기에 없애버리기에
가비지 컬렉터에 의해서 BufferedReader가 정리되긴 하지만
가비지 컬렉터로 정리되기전에 BufferedReader가 연속으로 사용되면 의도한대로 작동하지 않을 수 있습니다.

try-with-resource 문법을 사용하니 깔끔하게 자원을 해제하기 쉬웠습니다.😁
try() 안에 선언된 객체에 한해서 try 문이 끝나고 그 객체의 close 메서드를 호출해줘 자원을 해제해줍니다.
다만, 모든 객체에 다 해당되는 것은 아니고 AutoClosable 인터페이스를 구현한 객체에 한해서입니다.

2022-11-09 09:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/controller/VoucherController.java
> +						return;
Command enum에 관련된 기능을 넣으면, VoucherController 는 명확하게 사용자의 입출력, 필요한 객체 사용만 하고, Command는 명령어와 관련된 기능을 담당하게 되어서 좋은 것 같습니다.😁
그런데, 현재 VoucherController에 있는 createVoucher(), writeAllVoucher(), writeAllBlacklist() 메서드들이 Input, Output, Validator, VoucherService, CustomerService 같은 많은 인터페이스들을 사용하여서 이 메서드들을 함수형인터페이스로 묶어서 Command enum에 넣기가 애매해져서 고민입니다.😂

2022-11-09 13:15 UTC, samkimuel requested changes
성준님 고생하셨습니다!
전체적으로 잘 구현해주셨네요👏🏻 
간단하게 코멘트 남겼으니 확인해주세요~!

2022-11-09 13:15 UTC, samkimuel commented on src/main/java/com/programmers/voucher/exception/ExceptionMessage.java
> +	IO("IoException 발생");
다른 메시지들처럼 구체적으로 작성해주시면 좋을 것 같아요. 
로그를 볼 때 왜 Exception이 발생했는가에 대해 궁금할 것 같아요

2022-11-09 13:15 UTC, samkimuel commented on src/main/java/com/programmers/voucher/domain/voucher/util/Validator.java
> +			int parsedDiscount = Integer.parseInt(discount);
discount가 int가 아니라면 어떤 에러가 발생할까요?

2022-11-09 13:15 UTC, samkimuel commented on src/test/java/com/programmers/voucher/domain/voucher/repository/MemoryVoucherRepositoryTest.java
> +		Assertions.assertThat(fixedVoucher).isEqualTo(findVoucher);
저장, 조회한 결과를 검증하려고 하는거라면, actual과 expected 자리를 바꿔야할 것 같습니다!

2022-11-09 13:15 UTC, samkimuel commented on src/test/java/com/programmers/voucher/domain/voucher/util/ValidatorTest.java
> +	}
discount의 여러 값의 상황일 때 테스트하고 싶으신거면 ParameterizedTest 로 할 수 있을 것 같아요.
https://www.baeldung.com/parameterized-tests-junit-5 이거 보고 시도 해보시져!

2022-11-10 07:08 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/io/ConsoleInput.java
> +		return input;
다른 IOException 들은 런타임 예외로 전환해서 던져줬는데 ConsoleInput, ConsoleOutput 에도 있는 것을 보지 못했네요 😂
수정했습니다!

2022-11-10 15:14 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/util/Validator.java
> +		if (!(type.equals(VoucherType.FIXED.getType()) || type.equals(VoucherType.PERCENT.getType()))) {
말씀하신 것을 보고 생각해보니 Validator 에서 VoucherType 외의 다른 검증들도 Voucher 의 필드와 관련된 것이기에 Voucher 구현체의 생성자에서 검증한다면 응집도를 높일 수 있을 것 같습니다.
아직 다양한 입력값들이 복합적으로 연관된 검증이 필요 없으므로 Validator 클래스를 따로 분리하는 것이 과도하게 분리한 것 같습니다.
생성자에서 검증하는 방식의 단점이 있을까 생각해보았는데, controller에서 validate 해준다는 명시적인 코드가 없어서 들어온 값이 검증이 된 것인가하는 의문이 생길 수 있을 것 같아요.
혹시 다른 단점들이 있을까요?

2022-11-10 16:13 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/model/CustomerType.java
> +			.orElseThrow();
수정했습니다!

2022-11-10 16:16 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/util/Validator.java
> +			int parsedDiscount = Integer.parseInt(discount);
이 메서드가 호출 되기 전에 int 타입인지 아닌지를 검증하는 로직을 거치고 호출되어서 예외 처리를 해주지 않았었는데 헷갈릴 수 있을 것 같다는 생각이 들어서 수정했습니다!
int 가 아니라 double 인 경우도 고려하여 double 형으로 변경했습니다.

2022-11-10 16:31 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/exception/ExceptionMessage.java
> +	IO("IoException 발생");
수정했습니다!

2022-11-10 19:37 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/voucher/domain/voucher/util/ValidatorTest.java
> +	}
훨씬 간결하게 만들 수 있네요!😁
수정했습니다.

2022-11-10 20:45 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/repository/FileCustomerRepository.java
> +	public List<Customer> findAllBlacklist() {
@PostConstruct 를 사용하여 초기화 후 한번만 파일에 접근하여 모든 Blacklist 를 인메모리에 저장하고, 프로그램 종료 전까지는 findAllBlacklist 호출마다 인메모리에 저장된 데이터를 조회하도록 변경하였습니다.

2022-11-14 15:59 UTC, samkimuel commented on src/main/java/com/programmers/voucher/domain/voucher/util/Validator.java
> +		if (!(type.equals(VoucherType.FIXED.getType()) || type.equals(VoucherType.PERCENT.getType()))) {
명시적인 코드라는 것이 controller에서 보이는 코드를 의미하는 걸까요??
저는 생성자에서 검증하는 방식이 단점이라고 생각하진 않습니다! 말씀하신것처럼 응집도를 더 높이는 방법일 것 같아요. 
꼭 controller가 객체 생성시 검증하는 역할을 포함하고 있어야 하는가에 대해도 의문이 드네요 ㅎㅎ

2022-11-14 16:39 UTC, samkimuel approved these changes
성준님 고생하셨습니다~! 
수정도 잘하신 것 같고 테스트 코드도 더 작성하신 것 같아서 좋네요 ㅎㅎ
저는 여기서 approve 하겠습니다👍

2022-11-14 16:39 UTC, samkimuel commented on src/main/java/com/programmers/voucher/io/ConsoleInput.java
> +		return input;
수정된건가요..?ㅋㅋㅋ

2022-11-14 19:22 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/util/Validator.java
> +		if (!(type.equals(VoucherType.FIXED.getType()) || type.equals(VoucherType.PERCENT.getType()))) {
명시적인 코드라는 것이 controller 에서 보이는 코드를 의미하는 걸까요??
-> controller 가 최상단 계층이니까 프로그램 흐름을 다 표현해야한다고 생각했었네요😂 그러다보니 생성자에서 검증을 하면 controller 에서 "검증되었다" 라는 사실을 전달할 수 없는 것이 단점이지 않을까라고 생각했습니다.

말씀해주신대로 객체 검증의 책임은 객체가 가지고 controller는 사용자와의 상호작용, 로직 호출의 역할에 집중하는 것이 좋은 것 같습니다!

2022-11-14 19:22 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/io/ConsoleInput.java
> +		return input;
아 이런 실수를..해버렸네요 😥 
진짜로 수정했습니다🙂

2022-11-18 11:27 UTC, ksy90101 commented on src/main/java/com/programmers/voucher/domain/voucher/model/Voucher.java
> +	private final double discount;
double로 하신 이유가 있나요?

2022-11-18 11:31 UTC, ksy90101 commented on src/main/java/com/programmers/voucher/domain/voucher/model/Voucher.java
> +	private double validateDiscount(String discount) {
추상 클래스로 한번 구현해보세요.

2022-11-18 11:32 UTC, ksy90101 commented on src/main/java/com/programmers/voucher/domain/voucher/model/VoucherType.java
> +	private final Predicate<Double> OutOfDiscountRangeFilter;
변수 앞에 소문자입니다.

2022-12-11 09:23 UTC, ksy90101 approved these changes
마무리 잘 해주셨네요 💯 
머지하고 2단계에서 뵐게요!

2022-12-11 09:23 UTC, merged