[3기-C] 이수영 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #532
Opened 2022-11-07 15:21 UTC by twotwobread

## 📌 과제 설명 
SpringBoot Weekly Mission 1주차 : 바우처 관리 애플리케이션입니다.  

## 👩‍💻 요구 사항과 구현 내용 
### 🥇 요구 사항
(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - [x]  기존 메모리 레포지토리는 지우지 말기
    - [x]  개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

### 🥈 구현내용
#### 클래스 다이어그램
![image](https://user-images.githubusercontent.com/78334910/200341127-ebf9d160-370b-4578-be83-a3e4120a1c62.png)
1. Application 클래스에서 SpringBoot를 실행함.
2. CommandLineController에서 ConsoleIO를 통해 사용자로부터 값을 입력받아 그에 해당하는 Service Logic을 실행시킴.
3-1. VoucherService는 바우처를 만들고 repository에 바우처를 저장하고 저장된 바우처의 정보를 읽어오는 로직을 수행.
3-2. BlackListService는 BlackList 정보를 읽어오는 로직을 수행.
4. VoucherRepository는 FileVoucherRepository, MemoryVoucherRepository의 추상체이다.
    - 이는 Profile을 이용해서 선택되게 만들었고 application.yaml 파일에 설정했다.
5. 로직의 결과를 ConsoleIO를 통해 출력한다.

#### 언급되지 않은 클래스 추가설명
- 'CommandType' : 사용자로부터 입력되는 command를 명확하게 구별하기 위해 구현했다.
- entity
    - 'Voucher' : FiexedAmountVoucher, PercentDiscountVoucher의 추상체이다.
    - 'FixedAmountVoucher' : 고정된 할인 금액을 제공하는 바우처 타입이다. repository에 저장될 때 사용된다.
    - 'PercentDiscountVoucher' : 할인율을 제공하는 바우처 타입이다. repository에 저장될 때 사용된다.
- voucher
    - 'VoucherFactory' : Voucher를 생성하기 위한 Factory 클래스이다.
    - 'VoucherType' : Voucher의 구현체들을 명확하게 판단하기 위한 Enum 클래스이다. 
    - 'VoucherValidator' : 사용자로부터 들어온 입력이 특정 Voucher를 만들기 위해서 적합한지를 검증한다.

## ✅ PR 포인트 & 궁금한 점 
1. 객체간의 역할을 잘 나눴을까요??
2. 과제들을 지금까지 쭉 하면서 상속을 사용해본적이 없는데 상속을 언제 쓰는 것이 적절하게 사용하는 것인지 잘 모르겠습니다. 제가 제출한 코드에서 상속으로 바꿨을때 적절한 부분이 있을까요?? 코드에 존재하지 않는다면 간단한 예시를 말해주실 수 있을까요?
3. 제가 Service 로직을 제공하는 객체들의 메서드 명으로 getXXX을 사용했는데 제가 생각할 때 get과 같은 네이밍이 repository에 더 어울리지 않을까라는 생각이 들었습니다. Map에서 get과 같은 메서드를 사용해서 더 그런것 같은데 presentation, service, data access 등 layer에 맞는 네이밍이란 것이 있나요??
4. 코드에 관련된 부분은 아래에 남기겠습니다.

2022-11-09 16:59 UTC, samkimuel requested changes
수영님 구현하느라 고생하셨습니다!
소소하게 리뷰했는데 확인해주세요~!

질문사항에 대한 답변을 이전에 팀미팅하면서 얘기했던 부분과 겹치는 부분은 제외하고 해드리면,
1. 저는 객체를 괜찮게 나누셨다고 생각들어요. 사실 나눌 수 있다면 더 나눌 수 있겠지만, 이정도도 괜찮다고 생각합니다. 객체를 나누는 것도 중요한데, 메서드를 더 잘 분리해보시는 것도 좋을 것 같아요.
2. 네이밍 관련해서는 답이 없슴니당... 현재 단순 CRUD만 존재해서 작성하신대로 하셔도 괜찮을 것 같은데, 요구사항이 복잡해지고 메서드를 분리하다보면 다양한 네이밍이 필요하겠죠?ㅎㅎ.. 고민해보시고 역할에 맞는 네이밍을 잘 지으시면 될거같아요.

2022-11-09 16:59 UTC, samkimuel commented on kdt-spring-order/src/main/java/org/prgrms/kdt/io/ConsoleIO.java
> +        return "";
"" 을 계속 return하는데 깔끔해보이지 않네요. 의미없는 값을 return하는 것 같구요.
어떻게 수정해볼 수 있을까요?
catch 부분에서 Exception 던질 수도 있지 않을까요?

2022-11-09 16:59 UTC, samkimuel commented on kdt-spring-order/src/main/java/org/prgrms/kdt/repository/FileVoucherRepository.java
> +    }
이 메서드가 여러 일을 담당하고 있는데, 분리할 수 있을 것 같아요.

2022-11-09 16:59 UTC, samkimuel commented on kdt-spring-order/src/main/java/org/prgrms/kdt/repository/MemoryVoucherRepository.java
> +    }
stream 사용할 수도 있을 것 같네용?

2022-11-09 16:59 UTC, samkimuel commented on kdt-spring-order/src/main/java/org/prgrms/kdt/service/BlackListService.java
> +    }
아래 public 메서드와 위치 순서 바꿔야할 것 같네요

2022-11-09 16:59 UTC, samkimuel commented on kdt-spring-order/src/main/java/org/prgrms/kdt/service/BlackListService.java
> +            while((line = bufferedReader.readLine()) != null) {
코드 중복인데 수정 필요해보여요!

2022-11-09 16:59 UTC, samkimuel commented on kdt-spring-order/src/main/java/org/prgrms/kdt/voucher/VoucherFactory.java
> +        }
```suggestion
            return createPercentDiscountVoucher(discountValue);
        }

        throw new NoSuchElementException("존재하지 않는 Voucher 형식입니다.");
```
else 문 안써도 될 듯합니다. 테스트 해보시죠!

2022-11-11 13:16 UTC, twotwobread commented
명환님께서 주신 피드백 부분을 개선했고 추가적으로 패키지 구조 개선, validate 부분을 Voucher 내부로 넣기, VoucherService, VoucherFactory에서 Voucher의 voucherType 필드 이용하기를 추가했습니다. 그리고 2주차 과제를 하다가 명환님 코드리뷰를 반영하다 보니까 중간중간 Customer와 관련된 부분이 나오는데 이부분은 빼고 봐주셨으면 감사하겠습니다. (오류가 뜰 수 있는 점도 양해부탁드립니다 ㅠㅠ)

2022-11-16 12:28 UTC, ksy90101 commented on pom.xml
> +	</dependencies>
```suggestion
		</dependency>
	</dependencies>
```

개행 의미를 전달하기 위해 사용합니다.

2022-11-16 12:29 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/entity/BlackList.java
> +    private Date birthDate;
final!

2022-11-16 12:29 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/entity/Customer.java
> +    private final LocalDateTime createdAt;
final인 애들과 final이 아닌 애들을 구분하는게 좋아보입니다.

2022-11-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/entity/voucher/FixedAmountVoucher.java
> +    @Override
```suggestion
    }

    @Override
```

개행은 의미전달에 목적으로 사용합니다.

2022-11-16 12:36 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/entity/voucher/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher{
조합이 아닌 추상체에 구현메서드로  하신 이유를 나중에 적어주세요.

2022-11-16 12:42 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/repository/customer/JdbcCustomerRepository.java
> +        return new HashMap<>(){{
쓰면 안되요~ Double Brace Initialization

2022-11-16 12:43 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/repository/voucher/FileVoucherRepository.java
> +    private static final Logger logger = LoggerFactory.getLogger(FileVoucherRepository.class);
삭제!

2022-11-16 12:43 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/repository/voucher/FileVoucherRepository.java
> +        return null;
null 예외 터트리세요.

2022-11-16 12:44 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/repository/voucher/JdbcVoucherRepository.java
> +        return voucher.getOwnedCustomerId().get();
비어잇는지 확인을 하지 않고 get으로 바로 추출하면 어떤 문제 알아보세요.

2022-11-16 12:45 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/repository/voucher/JdbcVoucherRepository.java
> +        return new HashMap<>(){{
Double Brace Initialization 안됩니다!

2022-11-16 12:45 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/repository/voucher/JdbcVoucherRepository.java
> +            throw new RuntimeException("아무것도 삽입되지 않았습니다.");
좀더 의미예외를 사용하세요.

2022-11-16 12:46 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/presentation/controller/CommandLineController.java
> +        while (true) {
스택오버 플로우 발생하기 떄문에, 조건 제대로 넣어주세요.

2022-11-16 12:47 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/presentation/controller/CommandLineController.java
> +                    case CREATE -> {
enum을 구현한것으로 스위치 문을 제거 할수 있어요.
한번 찾아보세요.

2022-11-16 12:48 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/service/BlackListService.java
> +    private final String filePath;
안쓰이네요.

2022-11-16 12:50 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/service/VoucherService.java
> +            return findVoucher;
ealry return

2022-11-16 12:51 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/util/ValidatorUtil.java
> +    public static final Pattern NUMBER_PATTERN = Pattern.compile(NUMBER_REGEX);
private 처리

2022-11-16 12:52 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/util/ValidatorUtil.java
> +        if (number == null || number.isBlank()) {
isBlank() vs isEmpty()

2022-12-11 09:24 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/Application.java
> +        springApplication.setAdditionalProfiles("dev");
지금처럼 하면, 차후에 prd가 생기면 유연성을 가지기가 힘들거 같네요.
어떤 좋은 방법이 있을지 한번 고민해보세요.

2022-12-11 09:25 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/entity/voucher/VoucherType.java
> +    private final String typeNumber;
typeNumber를 가지고 있는 이유가 있나요?

2022-12-11 09:26 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/entity/voucher/VoucherType.java
> +    public static VoucherType of(String str) {
str이라고 하면 어떤 걸 의미하는지 모르니.
typeNumber라는 이름을 명시해주는게 좋을듯 해요.

2022-12-11 09:26 UTC, ksy90101 commented on src/main/java/org/prgrms/kdt/dao/repository/voucher/FileVoucherRepository.java
> +    private final ClassPathResource resource;
상수와 필드는 분리해주시면 좋을거 같아요.

2022-12-11 09:27 UTC, ksy90101 commented on src/test/java/org/prgrms/kdt/service/VoucherServiceTest.java
> +@Component
Test가 Component?

2022-12-11 09:27 UTC, ksy90101 approved these changes
1단계도 고생 많으셨어요 💯 
간단한 피드백을 남겼는데 2단계에서 적용해주세요~
2단계때 봐요!

2022-12-11 09:28 UTC, merged