[3기-C] 김소현 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #534
Opened 2022-11-07 19:45 UTC by thguss

## 📌 과제 설명 
Voucher을 생성 및 조회하는 프로그램
`create` 를 입력하면 가이드에 따라 입력 후 Voucher을 생성합니다.
`list`를 입력하면 이 때까지 생성한 voucher의 이력을 조회합니다.
`exit`을 입력하면 프로그램을 종료합니다.
맨 처음 구동 시 black_list.csv 파일의 내용이 출력됩니다.

## 👩‍💻 요구 사항과 구현 내용 
과제 가이드에 따라 차례로 구현하였습니다.
create: Voucher 생성 (memoryVoucherRepository: 일회성 저장, fileVoucherRepository: 파일에 객체 저장)
list: 생성한 Voucher 조회
exit: 프로그램 종료
그 외 : 프로그램을 시작할 때 black_list.csv 파일의 내용이 출력됩니다.

## ✅ PR 포인트 & 궁금한 점 
과제 및 강의 설명을 보며 최대한 따라 구현했지만 부족한 점이 많은 것 같습니다.
1. 미션에 부합하게 코드가 잘 짜여졌는 지 궁금합니다.
2. 객체 지향적으로 짜여졌는지, 부족한 코드 부분과 개선해야 할 점을 전체적으로 알고 싶습니다 ..!!

감사합니다 :)

2022-11-13 13:39 UTC, samkimuel requested changes
voucher.ser 파일을 읽다가 에러가 나는 것 같아요. 이쪽 부분 수정해주시고,
Fixed, Percent 에 따른 예외 처리가 안되어있는 것 같아요. 이쪽도 어떻게 구분해서 예외 처리를 해야할지 고민해주셔서 반영해주세요!
추가적으로 테스트 코드에 대한 고민을 해보고 추가하면 좋을 것 같습니다. 테스트 코드를 통해서 구현 코드에 대한 신뢰감을 줄 수 있다고 생각해요.

피드백 드린 부분 반영해주시고 재요청 주시면 다시 리뷰하겠습니다 🙂

2022-11-14 02:14 UTC, thguss commented
> voucher.ser 파일을 읽다가 에러가 나는 것 같아요. 이쪽 부분 수정해주시고, Fixed, Percent 에 따른 예외 처리가 안되어있는 것 같아요. 이쪽도 어떻게 구분해서 예외 처리를 해야할지 고민해주셔서 반영해주세요! 추가적으로 테스트 코드에 대한 고민을 해보고 추가하면 좋을 것 같습니다. 테스트 코드를 통해서 구현 코드에 대한 신뢰감을 줄 수 있다고 생각해요.
> 
> 피드백 드린 부분 반영해주시고 재요청 주시면 다시 리뷰하겠습니다 🙂

코멘트 감사합니다! 다만 voucher.ser 파일을 읽다가 에러가 난다고 하셨는데, 제 PC 환경에서는 에러 없이 잘 돌아가는 상황이라 어느 부분부터 에러가 발생하는 지 궁금합니다 ㅠㅠ 프로그램 시작부터 에러가 발생하는 걸까요??

나머지 피드백 빠른 시일 내에 반영해서 다시 PR 올린 후 연락 드리겠습니다. 감사합니다 :)

2022-11-18 11:53 UTC, ksy90101 commented on src/main/java/org/programmers/weekly/mission/CommandLine.java
> +    private Boolean isRunnable = true;
필드가 아닌 변수를 가지고 있어 도 될듯한데요.

2022-11-18 11:55 UTC, ksy90101 commented on src/main/java/org/programmers/weekly/mission/config/AppConfiguration.java
> +@ComponentScan(basePackages = {"org.programmers.kdtspringdemo.voucher", "org.programmers.kdtspringdemo.customer"})
ComponentScan이 없어도 왜 대체 잘 돌까요? 어떻게 해야 없이 잘 돌수 있을까요?
ComponentScan은 대체 뭘까요?

2022-11-18 11:57 UTC, ksy90101 commented on src/main/java/org/programmers/weekly/mission/domain/voucher/model/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher, Serializable {
Serializable 왜 붙인건가요?

2022-11-18 11:57 UTC, ksy90101 commented on src/main/java/org/programmers/weekly/mission/domain/voucher/model/PercentDiscountVoucher.java
> +        return beforeDiscount * (percent / 100);
100은 매직 넘버 네요.

2022-11-18 12:22 UTC, ksy90101 commented on src/main/java/org/programmers/weekly/mission/domain/customer/repository/FileCustomerRepository.java
> +            throw new RuntimeException(ioException);
더 의미 있는 예외를 사용하세요.
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/10%EC%9E%A5/72_%ED%91%9C%EC%A4%80_%EC%98%88%EC%99%B8%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EA%B9%80%EC%9E%AC%EC%A4%80.md

2022-11-18 12:23 UTC, ksy90101 commented on src/main/java/org/programmers/weekly/mission/util/type/OptionType.java
> +        return Optional.empty();
stream으로 변경해보세요.

2022-11-18 12:31 UTC, ksy90101 approved these changes

2022-11-23 10:45 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/domain/voucher/model/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher, Serializable {
객체 직렬화 관련이었습니다!

2022-11-24 07:16 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/CommandLine.java
> +    private Boolean isRunnable = true;
`final` 속성을 빼고 변수로 전환했을 경우 null 관련해서 오류가 발생하는데 어떤 방식으로 변수를 가질 수 있을까요?

2022-11-24 07:26 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/config/AppConfiguration.java
> +@ComponentScan(basePackages = {"org.programmers.kdtspringdemo.voucher", "org.programmers.kdtspringdemo.customer"})
ComponentScan은 빈으로 등록될 준비가 된 클래스들을 스프링 빈으로 등록시켜주는 어노테이션으로 알고 있습니다.
멘토님 말씀대로 ComponentScan을 `AppConfiguration`에서 제거해도 잘 돌아가는 것을 확인하였습니다. 생각해보다가 `CommandLine` 쪽에서 Autowired를 해주어서 ComponentScan 없이 잘 돌아가는 것으로 추측해보았습니다.

2022-12-07 07:33 UTC, samkimuel approved these changes
소현님 늦게 리뷰드려 죄송합니다.
잘 작성해주셨네요. 고생하셨습니다 👍🏻 
코멘트 몇 개 달았으니 확인해주세요~!

2022-12-07 07:33 UTC, samkimuel commented on src/main/java/org/programmers/weekly/mission/CommandLine.java
> +    private Boolean isRunnable = true;
wrapper class를 사용하신 이유가 있을까요?

2022-12-07 07:33 UTC, samkimuel commented on src/main/java/org/programmers/weekly/mission/domain/voucher/model/PercentDiscountVoucher.java
> +    private int TOTAL_PERCENT_NUM = 100;
상수면 static final 붙이는게 어떨까요?

2022-12-07 07:33 UTC, samkimuel commented on src/main/java/org/programmers/weekly/mission/domain/voucher/model/PercentDiscountVoucher.java
> +        }
개인마다 다르겠지만, 저는 validation 하는 부분을 private method로 추출하는 편이에요!
생성자 부분도 깔끔해지기도 해서요 ㅎㅎ

2022-12-11 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/weekly/mission/domain/voucher/repository/FileVoucherRepository.java
> +    private final String voucherFilePath;
상수와 필드는 개행으로 분리해주시면 훨씬 더 좋습니다.

2022-12-11 09:31 UTC, ksy90101 approved these changes
명환님의 리뷰까지 해서 2단계때 같이 적용해주세요 💯 
고생 많으셨어요~
2단계에서 봐요!

2022-12-11 09:31 UTC, merged