[3기-C] 공태현 SpringBoot Part1 Weekly Misson 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #535
Opened 2022-11-08 10:18 UTC by rhdtn311

## 📌 과제 설명 
안녕하세요!
Spring 1주차 미션입니다. 

- create : 바우처를 생성합니다.
- list : 바우처 리스트를 출력합니다.
- blacklist : 블랙리스트를 출력합니다.
- exit : 프로그램을 종료합니다.

<br>

## 👩‍💻 요구 사항과 구현 내용 
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

<br>

## 🎈 주요 클래스 설명
- domain
  - Voucher : 바우처를 정의한 인터페이스입니다. 
  - VoucherType : Voucher에 관련된 정보를 필드로 가지고 있는 enum 클래스입니다. 사용자 입력값(1,2)에 따른 바우처 타입, 바우처가 가질 수 있는 최대 할인률 범위, 바우처 생성자를 필드로 가지고 있습니다. 바우처 검증, 입력값에따른 바우처 찾기, 바우처 생성 기능을 합니다.
  - Customer : 고객을 정의한 인터페이스입니다.
- Repository
  - VoucherRepository : 바우처 저장소의 기능을 정의한 인터페이스입니다.
  - MemoryVoucherRepository : 메모리로 관리되는 저장소로 프로그램 종료 시 초기화됩니다.
  - FileVoucherRepository : csv 파일에 바우처 데이터를 저장하는 저장소입니다. csv 파일로의 입력(저장), 출력(조회) 기능을 합니다.
  - BlackListCustomerRepository : 블랙리스트를 파일로 관리하는 저장소입니다.
- Service
  - VoucherCreateService : 바우처를 생성하는 역할을 하는 클래스입니다.
  - VoucherListFindService : 바우처 리스트를 조회하는 역할을 하는 클래스입니다.
  - BlackListFindService : 블랙리스트를 조회하는 역할을 하는 클래스입니다.
- io
  - Command : 프로그램의 명령어를 관리하는 enum 클래스입니다.
  - Console : 사용자의 입력을 받고 정보를 출력하는 기능을 담당하는 클래스입니다.
  - InputValidator : 사용자의 입력을 검증하는 클래스입니다.  

<br>

## ✅ PR 포인트 & 궁금한 점 
1. `VoucherType` enum 클래스에 바우처 생성, 입력값에 따른 바우처 검증, 입력 문자열과 매칭되는 바우처 찾는 기능을 갖습니다. enum을 잘 활용해보고자 했는데 너무 많은 책임을 갖는 것인지 의문이 듭니다.
2. `FileVoucherRepository` 또한 너무 많은 책임을 갖는 것인지 궁금합니다. 
3. InputValidator는 서로 관련이 없는 3개의 메소드로 구성되어 있는데 응집도가 떨어지는 클래스인가요 ? 그렇다면 어떻게 개선하는 것이 좋을까요 ??

테스트는 직접 여러 번 해보았지만 테스트코드는 Service 메소드만 구현했습니다. 
이번주 강의 듣고 다시 반영하겠습니다!
피드백 주시면 열심히 반영하겠습니다. 감사합니다!!

2022-11-10 15:30 UTC, samkimuel requested changes
태현님 고생하셨습니다~!
잘 구현하셨네요! 저도 배우고 갑니닷!
코멘트 살짝 달았으니 확인해주세요~!

추가적으로 실패에 대한 테스트도 작성하시면 훨씬 더 좋을 것 같아요!

2022-11-14 16:25 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/voucher/domain/VoucherType.java
> +                .findAny()
큰 고민 없이 사용하고 있었습니다..! 감사합니다!

2022-11-14 16:41 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/io/InputValidator.java
> +    }
1. 해당 메소드들은 Console클래스 내부에서만 사용할 것이라 생각되어 접근제한자를 protected로 했습니다.
2. Console 클래스의 코드가 조금이라도 줄어들어서 return 하도록 했습니다. 가독성이 더 떨어져 보일까요 .. ??

2022-11-17 13:34 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/CommandLineApplication.java
> +            try {
switch문을 개선해볼까요?
전략패턴이나 좀더 깔끔하게 개선해주세여.

2022-11-17 13:36 UTC, ksy90101 commented on src/main/java/org/prgrms/vouchermanagement/customer/domain/BlackCustomer.java
> +    private final String name;
customer에도 이름이 있을거 같은데 왜 또 이름을 가지고 있나요?

2022-11-18 02:43 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/CommandLineApplication.java
> +    private final Logger logger = getLogger(CommandLineApplication.class);
static이 있으면 해당 클래스가 클래스 로더에 올라가는 시점에 static 메모리 영역에 하나만 생성되어 프로그램이 종료될 때까지 유지되지만 static이 없으면 클래스의 객체를 생성할 때마다 메모리를 할당 받습니다.

2022-11-18 02:44 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/customer/domain/BlackCustomer.java
> +    private final String name;
깊은 고민이 부족했던 것 같습니다. 감사합니다!

2022-11-18 12:53 UTC, merged