[3기-C] 박세준 SpringBoot Part1 Weekly Misson 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #539
Opened 2022-11-09 04:44 UTC by park-se-jun

## 📌 과제 설명 
바우쳐 관리 프로그램 
- create : 바우처를 생성합니다.
- list : 바우처 리스트를 출력합니다.
- black : 블랙리스트를 출력합니다.
- exit : 프로그램을 종료합니다.

- profile이 dev면 MemoryVoucherRepository를 사용합니다.
- profile이 default면 FileVoucherRepository를 사용합니다.

## 👩‍💻 요구 사항과 구현 내용 

![week1클래스다이어그램](https://user-images.githubusercontent.com/28258648/200738617-351c8090-b797-47d6-bfe4-9a5b3a932529.png)

(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ PR 포인트 & 궁금한 점 
- FileVoucherRepository에서 파일에서 바로바로 읽어오고 쓰는 것, vs Map 에 올려두고 그때그때 반영하는것 어떤 코드가 나을까요?
- CSVReader와 Writer 모두에서 CSVDto를 만듭니다. 근데 CsvDto가 바우쳐가 될 수도 있고, 커스터머가 될수도 있을것 같아서 List<String[]> 이라는 value 하나를 가지고 각각 사용하는 곳에서 (Repository) voucher를 생성하고, customer를 생성하는데요.
이렇게 코드 구성이 되니까 write를 해줄 때 1개만 넣어주더라고 불필요한 list에 감싸서 넣어주어야 하고, CSV 를 목적에 맞게 파싱하는 것에 대한 관심사 분리가 안되고 코드도 난잡해 지는것 같습니다. 그렇다고 CSVReader를 바우쳐 따로 커스터머 따로 두는것도 뭔가 애매한 느낌이 듭니다. 어떻게 해야할까요?
- 예외 처리 handle을 처리해주는 기준같은게 있나요? 지금은 예외가 발생했을때 console로 보여줘야할 것 같아서 대부분의 예외를 throws해 console을 가지고 있는 CommandLineApplication에서 처리합니다.
- 콘솔에 입출력 하는 책임을 서비스 별로 분리하는게 맞을까요(서비스마다 console이 존재) 아니면  하나의 큰 console로 하는게 맞을까요? 지금은 가장 상위에서 하나의 console로 하고 있습니다.
[입출력을 한다 vs 각각의 서비스 도메인 관련된 입출력을 한다]
- 로그를 남길 때 log 설정의 경우 디폴트 설정을 몇개만 바꿔서 적용하는게 실무에서는 일반적으로 어떻게 하나요?

2022-11-11 15:52 UTC, samkimuel requested changes
세준님 과제하시느라 고생하셨어요!

말씀드리고 싶은 게 크게 두 가지가 있습니다. 
1. 작성하신 코드 전반적으로 주석과 사용하지 않는 코드는 제거해주시면 좋을 것 같아요
2. 여러 메서드 시그니처에 예외를 추가해주셨는데, 예외 발생 가능성 때문에 작성하신거겠죠? 그런 예외 처리를 위임하지 않고 최대한 해당 메서드에서 처리하시면 좋을 것 같습니다.

코멘트에도 코멘트도 남겼으니 확인해주세요 😃  궁금한 점 있으면 코멘트나 슬랙에 남겨주세요!

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +    //분기하는 책임
코드로 잘 표현한다면 주석을 남기지 않아도 됩니다 😉
주석을 남기기보다 코드를 잘 작성해보시져!

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +            String myString = console.getInputWithPrompt("");
"" 는 꼭 넘겨주어야 하나요?

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +            String myString = console.getInputWithPrompt("");
myString이라는 변수명의 의미가 불분명하네요. 기능에 맞는 변수명으로 수정하면 좋을 것 같아요!

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +            return null;
return 하는 의미가 있을까요??

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandType.java
> +        }
IllegalArgumentException 을 catch하고 다시 throw 하는데, 이런 중복은 불필요하다고 생각하는데 세준님은 어떻게 생각하시나요?
CommandType을 찾을 수 있는 다른 방법은 없을까요?

2022-11-11 15:52 UTC, samkimuel commented on src/main/resources/application.yml
> +#      "prod":""
안쓰는 코드는 제거해주세요~

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CsvDto.java
> +    public final List<String[]> value;
배열의 리스트로 저장하는 이유가 있을까요? 왜 해당 자료구조를 선택하셨나요??

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/customer/Customer.java
> +        return CsvDto.from(rowDatas);
Customer 속성들을 String 배열로 만들어서 넘겨주고 있네요. 
꼭 변환해서 넘겨주어야 할까요? 인스턴스 자체를 전달해도 되지 않을까요?

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/io/console/Console.java
> +            return MessageFormat.format("  {0}  |  {1}  |  {2} |",argument);
String 배열을 만들지 않고 voucher를 바로 매핑시켜서 메시지 만들어도 괜찮을 것 같네요~

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CSVReader.java
> +        }
try-with-resource 적용해서 수정해볼까요??
https://tecoble.techcourse.co.kr/post/2021-04-26-try-with-resource/

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CSVWriter.java
> +        }
여기도 마찬가지로 try-with-resource 적용해볼 수 있을 것 같네요 ㅎㅎ

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/voucher/VoucherCreator.java
> +        logger.info("바우쳐 생성 성공. 타입 :{} 값 :{}",voucherType.name(),percentOrAmount);
로그 찍기 👍

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/voucher/VoucherService.java
> +                new RuntimeException(MessageFormat.format("Can not find a voucher for{0}", voucherId)));
RuntimeException이 아닌 구체적인 예외를 던지면 좋을 것 같네요.

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/FixedAmountVoucher.java
> +    private boolean voucherAllow(Long amount){
parameter로 Long wrapper 클래스를 사용하신 이유가 있을까요?

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/PercentDiscountVoucher.java
> +        if(value>=0 && value <= 100){
0, 100 이라는 매직넘버를 상수로 만들면 좋을 것 같아요~

2022-11-11 15:52 UTC, samkimuel commented on src/main/java/org/prgrms/kdtspringdemo/voucher/repository/FileVoucherRepository.java
> +        logger.info("파일 append 여부 : {}",append);
해당 로그들을 찍는 이유가 있을까요?

2022-11-13 15:08 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +    //분기하는 책임
알겠습니다!!

2022-11-13 15:08 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +            String myString = console.getInputWithPrompt("");
아무것도 아닌 "" 을 넘겨준 이유는 어플리케이션에 프롬프트 지정해 주기위해 넘겨주는 문자열 입니다.
나중에 요구사항에 따라 변경될 수 도 있다고 생각해 저런 함수를 사용했습니다. 그대로 두거나 다른 값을 전달해도 괜찮을까요?
myString은 변수명을 바꿨

2022-11-13 15:08 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +            return null;
나중에 test 를 할 때 return 값으로 assert를 걸게 될거 같아서 return type을 지정하고 오류가 발생하면 null을 리턴하게 했는데 그냥 return을 void 로 바꾸는게 나을까요?
어떤 함수가 특정한 일을 할때 상위 객체로 리턴값을 줄 필요가 없을때 void를 리턴값으로 주는 것과 그래도 그 일을 수행했을 때 나오는 결과값을 return으로 넘겨주는것중 어떤게 나은가요?

2022-11-13 15:08 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandType.java
> +        }
error를 출력하는 일을 CommandLineApplication의 console에서 에러 메시지를 그대로 출력하는 형식이기 때문에 에러메시지를 다시 throw하는 방식으로 했습니다. error 처리를 Commandline의 console 이라는 io를 담당하는 객체에서 하도록 하기 위해 throw로 던지고, 메시지를 주어서 던지도록 했는데 다른 방식으로 하는게 나을까요?

2022-11-13 15:08 UTC, park-se-jun commented on src/main/resources/application.yml
> +#      "prod":""
넵!

2022-11-13 15:08 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/voucher/VoucherCreator.java
> +        logger.info("바우쳐 생성 성공. 타입 :{} 값 :{}",voucherType.name(),percentOrAmount);
감사합니다.

2022-11-13 15:08 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/voucher/VoucherService.java
> +                new RuntimeException(MessageFormat.format("Can not find a voucher for{0}", voucherId)));
피드백을 듣고 NullPointerException으로 바꾸려다가 Repository에서 Optional쓴 이유가 없어지는건 아닌가 라는 생각이 들었습니다. return을 Optional<Voucher> 로 하고 향후 getVoucher 가 사용되는 곳에서 처리를 해주는게 나을까요?

2022-11-13 15:08 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/FixedAmountVoucher.java
> +    private boolean voucherAllow(Long amount){
별다른 이유는 없었음다..... 바꿨습니다!

2022-11-13 15:09 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/PercentDiscountVoucher.java
> +        if(value>=0 && value <= 100){
변경했습니다!

2022-11-13 15:09 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/voucher/repository/FileVoucherRepository.java
> +        logger.info("파일 append 여부 : {}",append);
파일 입출력이 제대로 되나 확인하려고 찍었었습니다. 삭제했습니다.

2022-11-13 15:19 UTC, park-se-jun commented
error 관련해서 질문사항이 있습니다.
현재 제 코드는 error를 IO 가 담당하는 console 이 있는 최상위로 계속 Throws 를 하고, 최상위 객체에서 showError를 통해 에러 메시지를 출력하게 되어 있습니다.

하지만 명환님의 피드백도 그렇고,얼마전 머쓱이질문에 답변하기에 성준이 형이 남겨준 코멘트를 보면 error를 thorws 하는것 보다 발생되는 지점에서 처리하는 것이 더 좋아보입니다.

그뿐만 아니라 "Error를 로깅하는데 에러가 발생했을 때 꼭 IO 를 담당하는 console 이있는곳까지 올려서 처리를 해야하나? 그냥 발생지점에서 Logger로 처리하면 안되나? logging이랑 에러 출력을 따로하면 2번반복되는데...." 라는 생각이 듦과 동시에," Logger를 출력하는 것을 Application의 동작의 일부로 봐도 괜찮나?" 라는 생각이 들었습니다.

그래서 Error를 다루는 것에 대한 서브멘토님의 생각이 궁금합니다. 명환님이라면 어떻게 하셨을것 같나요??

4줄 요약
1. Error 출력을 를 IO를 맡는 Console에서 하려다 보니 지속적인 Error Throws가 발생함
2. 피드백 + 머쓱이CS 질문으로 보아 Error가 발생한 곳에서 바로 처리하는게 좋아보임
3. 그려면 error는(잘못된 입력같은거 포함) 각 에러가 발생하는 곳에서 촐력 없이 그냥 logger로 로깅만 남겨도 되나? 라는 의문이 생기게 됨
4. 서브멘토님은 error 를 처리할때 어떻게 하셨는지가 궁금합니다.

2022-11-16 13:06 UTC, ksy90101 commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +    private boolean isRunning = true;
이 친구가 필드로 있어야 할까요?

2022-11-16 13:07 UTC, ksy90101 commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +    }
```suggestion
        this.isRunning = false;
    }
```
개행도 의미를 전달하기 위함입니다.

2022-11-16 13:12 UTC, ksy90101 commented on src/main/java/org/prgrms/kdtspringdemo/customer/repository/FileBlackCustomerRepository.java
> +    private final Logger logger = LoggerFactory.getLogger(FileBlackCustomerRepository.class);
상수에 static final을 붙이는데 그 이유가 무엇일까요?

2022-11-16 13:14 UTC, ksy90101 commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CSVWriter.java
> +            throw new RuntimeException(e);
의미있는 예외를 사용해보세요.

2022-11-16 13:15 UTC, ksy90101 commented on src/main/java/org/prgrms/kdtspringdemo/voucher/VoucherCreator.java
> +            case PERCENT -> new PercentDiscountVoucher(UUID.randomUUID(),percentOrAmount);
enum으로 switch를 없애보시죠.

2022-11-16 13:18 UTC, ksy90101 commented on src/main/java/org/prgrms/kdtspringdemo/voucher/repository/FileVoucherRepository.java
> +                                 @Value("${voucher.append}") boolean append) {
value가 아닌 configurationproperties 이걸로 변경해보시겠어요?

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CsvDto.java
> +    public final List<String[]> value;
손가는데로 짜다보니 그렇게 된거 같습니다..?🤔

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/customer/Customer.java
> +        return CsvDto.from(rowDatas);
인스턴스 자체를 전달하는 함수를 추가하여 그렇게 변경했습니다.

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/io/console/Console.java
> +            return MessageFormat.format("  {0}  |  {1}  |  {2} |",argument);
Voucher의 내용이 변경될지도 몰라 향후 수정이 용이하도록 이런식의 코드구성을 했었는데 별로인가요??
아니면 아싸리 Voucher의 toString을 재정의 하는건 어떻게 생각하시나요??

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CSVReader.java
> +        }
적용했습니다!

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CSVWriter.java
> +        }
적용했습니다!

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +    private boolean isRunning = true;
CommandType으로 Exit여부를 판별하도록 변경하였습니다.

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +    }
의미없는 개행을 최대한 줄여보도록 하겠습니다.

2022-11-17 07:13 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/customer/repository/FileBlackCustomerRepository.java
> +    private final Logger logger = LoggerFactory.getLogger(FileBlackCustomerRepository.class);
static이 없으면 해당 클래스가 여러개 생길 경우 각각의 상수가 메모리를 이용하는데 상수는 어차피 처음부터 끝까지 고정된 값이기 때문에 메모리 낭비를 없애기 위해 상수에 static final을 쓰는군요! 수정했습니다.
 그런데 Spring에서 각 클래스는 어차피 싱글톤으로 관리되지 않나요??

2022-11-17 07:14 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/io/file/CSVWriter.java
> +            throw new RuntimeException(e);
IOException이 터졌을 경우 어떤 상황에서 터진지 잘 판단이 안되서 RuntimeException 으로 넘겼었습니다. 일딴 IllgalStateException으로 변경했습니다!

2022-11-17 07:14 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/voucher/VoucherCreator.java
> +            case PERCENT -> new PercentDiscountVoucher(UUID.randomUUID(),percentOrAmount);
Functinal Interface를 이용해 Voucher에 필드로 넘기고 newInstance로 Voucher를 만들도록 변경했습니다!

2022-11-17 08:01 UTC, park-se-jun commented on src/main/java/org/prgrms/kdtspringdemo/voucher/repository/FileVoucherRepository.java
> +                                 @Value("${voucher.append}") boolean append) {
@ConfigurationProperties에 대해 조사한 후 @Value 가 아닌 @ConfigurationProperties로 변경하려고 보니까 

- path를 변경 가능하게 만들고 Setter를 만들어 준뒤 postConstruct에서 path를 사용하는것
- @ConstructorBinding과 함께 사용해 final속성으로 만들어준 후 Constructor로 값을 설정해 주는것

두가지 방안이 있는것 같았습니다.

setter의 사용을 피하기 위해 두번째 방안을 사용하려고 Repository에  @ConstructorBinding과 @ConfigurationProperties를 추가해 주는 식으로 진행하려고 했는데 @ConstructorBinding은 Spring Component에는 못달아 준다면서 오류를 발생했습니다.
찾아보니 ConstructorBinding은 @Component 빈이나 @Bean을 통해 만들어진 빈, @Import를 통해 만들어진 빈에서는 사용할 수 없다고 나옵니다. 다시말해 @Repository와 같이 사용할 수 없는 것인데 그럼 어떻게 사용해야 하는것인지 막혔습니다.

properties클래스를 만든 후 그곳에 해당 설정들을 넣어 놓고 컨테이너에 등록하기엔 사용하는 값들이 너무 적기때문에 오히려 배보다 배꼽이 더 크다는 느낌을 지울수 없습니다.

그렇다고 첫번째 방안을 사용하기에는 path의 불변성이 보장되지 않기때문에 @Value의 방식보다 별로로 느껴졌습니다.

그래서 피드백 주신사항처럼 바꾸는게 맞는가?? 라는 의문이 생기게 되었습니다.

 @ConfigurationPropperties로 변경하는게 @Value를 사용하는 것 보다 나은 이유가 있을까요??

2022-11-18 12:56 UTC, merged