[3기-C] 이택승 SpringBoot Part1 Weekly Misson 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #540
Opened 2022-11-09 06:16 UTC by dlxortmd987

## 📌 과제 설명 
- create 기능 구현
  - 타입과 얼마나 깍을지 입력 후 저장
- list 기능 구현
  - 바우처 타입과 값 출력

## ✅ PR 포인트 & 궁금한 점 
- Voucher를 FixedAmountVoucher와 PercentDiscountVoucher 이렇게 두 개로 쪼개지 않고 진행하였는데, 기능의 확장이나 타입이 더 많이 늘어나는 것을 고려하면 타입마다 클래스를 따로 두는 것이 좋을까요?

2022-11-09 13:11 UTC, seung-hun-h requested changes
안녕하세요 택승님!
애플리케이션 예외처리도 꼼꼼히 하셨고, 설계도 잘 하신 것 같습니다.
나머지는 리뷰 남겼으니 확인해주세요

---

#### Voucher를 FixedAmountVoucher와 PercentDiscountVoucher 이렇게 두 개로 쪼개지 않고 진행하였는데, 기능의 확장이나 타입이 더 많이 늘어나는 것을 고려하면 타입마다 클래스를 따로 두는 것이 좋을까요?

- 넵 추상 클래스를 상속할 수도 있고, 인터페이스를 구현할 수도 있는데 이렇게 하는 것이 좋을 것 같아요
- 바우처 마다 서로 다른 필드를 가질 수도 있고, 바우처가 늘어날 수도 있는데 이렇게 되면 VoucherType이 너무 비대해져서 관리가 어려울 것 같네요

2022-11-09 13:11 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/InMemoryVoucherManager.java
> +    }
`Collections.unmodifiableList()`를 사용해보는 것도 좋겠네요

2022-11-09 13:11 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +    }
`toString`은 호출하지 않아도 될 것 같아요

```suggestion
    @Override
    public String toString() {
        return "[Type]: " + voucherType.getType() + ", [amount]: " + amount;
    }
```

2022-11-09 13:11 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/VoucherAmount.java
> +    }
👍

2022-11-09 13:11 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/VoucherAmount.java
> +public class VoucherAmount {
값 객체에 대해서 `equals`, `hashCode`를 모두 재정의 해주시고, 내부 필드에 대한 변경 지점을 없애 주셨네요 👍 

```
private final Long value;
```
처럼 final을 사용해서 인스턴스 생성시점에 항상 값을 받아올 수 있도록 하면 더 좋을 것 같네요

2022-11-09 13:11 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/utils/VoucherValidator.java
> +    private static final Long PERCENT_DISCOUNT_VOUCHER_MAX_VALUE = 100L;
이러한 데이터는 바우처가 가지고 있어야 하지 않을까요?
지금 설계대로라면 VoucherType이 가지고 있어야할 수도 있겠군요

2022-11-09 13:11 UTC, seung-hun-h commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +class CommandExecutorTest {
테스트도 작성하려 노력하셨네요.
다만, then 절에 검증 로직이 빠진 테스트들이 많이 보이네요.
이렇게 되면 테스트 자동화가 어려울 것 같네요

2022-11-10 14:17 UTC, hongbin-dev requested changes
안녕하세요 택승님! 코드를 깔끔하게 잘 짜주셨네요 👍 
코멘트 몇개 남겼는데, 적용해보시면 더 좋아질 것 같아요 

> Voucher를 FixedAmountVoucher와 PercentDiscountVoucher 이렇게 두 개로 쪼개지 않고 진행하였는데, 기능의 확장이나 타입이 더 많이 늘어나는 것을 고려하면 타입마다 클래스를 따로 두는 것이 좋을까요?

상속과 컴포지션을 선택할때 고민이 많이 되는 것 같아요. 그전에 어떤 장단점이 있는지 알아보셔도 좋을 것 같아요.

이펙티브자바 `상속보다는 컴포지션을 사용하라`를 읽어보시면 좋을 것 같네요.

2022-11-10 14:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/io/ConsoleIO.java
> +    public static final String VOUCHER_AMOUNT_PROMPT = "Enter a value. (fixed - 0~ | percent - 0~100)";
출력객체 + lineSeparator() 👍 

다만 클래스네이밍이 ConsoleIO인데요. (선호도가 갈리지만)단축어라도 카멜케이스를 지켜주면 좋을 것 같아요.
만약 jdbc 기반 dao를 만든다면 JDBCDAO 이런 네이밍이 생길 것 같아요 :scream:

2022-11-10 14:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +    }
덧붙여 생성할때(new)부터 완전한 객체가 생성되면 좋을 것 같아요

2022-11-10 14:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/VoucherAmount.java
> +    }
👍👍

값 객체 활용 좋네요.

2022-11-10 14:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/VoucherManager.java
> +    Voucher save(Voucher voucher);
저장하는객체는 저장만하면 되는데, Voucher를 리턴하는 이유가 있나요?

2022-11-10 14:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/VoucherMetaData.java
> +    private String amount;
DTO를 만들어주셨군요. 지금단계에선 조금 헤비해보여요. 그냥 파라미터로 요청을 넘겨도 무관해보입니다.

2022-11-10 14:17 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +    private VoucherValidator voucherValidator;
mock을 사용하신 이유가 있나요?

2022-11-10 14:17 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +                // then
then이 없네요. 이렇게되면 테스트자동화의 의미가 떨어지긴 합니다 😭

2022-11-10 14:17 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/voucher/utils/VoucherMapperTest.java
> +            public void 값_10() {
테스트코드 이름의 대한 네이밍을 좀 더 고민해보면 좋을 것 같아요. 예를들어

- 메타데이터는,
  - FIXED 타입에서
     -  10의 값을 만들 수 있다
     - 실수를 만들 수 없다.

2022-11-10 14:17 UTC, hongbin-dev commented
@dlxortmd987 택승님 리뷰 남겼습니다!

2022-11-11 06:47 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/command/CommandType.java
> +    }
어제 사실 이 부분에 대해 스터디를 해서.. 좀만 빨리 알아볼 걸 그랬네요..ㅋㅋㅋㅋ 
말씀하신 네이밍 규칙으로 고쳐볼게요!

2022-11-11 06:47 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/InMemoryVoucherManager.java
> +    }
Voucher 구조를 바꾸면서 한번 바꿔볼게용!

2022-11-11 06:47 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/utils/VoucherValidator.java
> +    private static final Long PERCENT_DISCOUNT_VOUCHER_MAX_VALUE = 100L;
이것도 바우처 구조를 바꾸며서 옮겨보겠습니다!

2022-11-11 11:21 UTC, seung-hun-h approved these changes

2022-11-11 11:37 UTC, seung-hun-h commented
@dlxortmd987 리뷰는 다음 PR에 반영해주세요 머지하겠습니다

2022-11-11 11:37 UTC, merged

2022-11-12 13:26 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +    }
제가 생각한 부분은 voucher와 관련된 validation 처리를 VoucherValidator라는 클래스로 역할을 분리하고 싶었습니다. 혹시 이것은 너무 책임을 분리한 것일까요?

2022-11-12 13:27 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/command/CommandType.java
> +    );
Collection 객체로 반환하는 것은 거의 불변성을 보장해서 넘기는게 좋은건가요?

2022-11-12 13:39 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/command/CommandType.java
> +    );
레퍼런스 객체를 반환할 때는 무조건 불변성을 보장하도록 신경써야 하나요?

2022-11-12 13:41 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/command/CommandType.java
> +        return stringBuffer.toString();
혹시 아래와 같이 작성하는 이유가 무엇인가요?

2022-11-12 13:52 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/InMemoryVoucherManager.java
> +    }
혹시 `Collections.unmodifiableList()` 를 사용하는 이유가 set이나 delete로 리스트의 원소를 바꿀 수 있어서 인가요?

2022-11-12 13:54 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +    }
찾아보니 문자열과 객체를 더하거나 객체 자체를 출력하면 `toString` 이 자동으로 호출되네요!

2022-11-12 13:56 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/VoucherAmount.java
> +    }
만약 값보다 작은 것은 것을 판단하고 싶을 때는 `isGreaterThanEqual` 을 `!` (반대) 처리해서 하는 것이 일반적인가요? 아니면 `isLessthan` 을 만드는 것이 일반적인가요?

2022-11-12 13:57 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/VoucherAmount.java
> +public class VoucherAmount {
나중에 값이 변경되는 것을 막는 역할도 하고 값이 예상하지 못한 0이나 null로 채워지는 것을 막는 역할인가요?

2022-11-12 13:58 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/app/VoucherControllerStatus.java
> +    }
null safe하게 바꿔보겠습니다..!

2022-11-12 14:04 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/app/VoucherControllerStatus.java
> +    }
어차피 객체 이름이 `VoucherController`와 강하게 연관되어 있으므로 간결하게 표현해도 괜찮을 것 같아요.
궁금한 것이 있는데요. 만약 `quit()` 과 같이 변수명을 단순하게 짓는다면, 다른 클래스에서도 같은 이름이 나올 수 있다고 생각합니다. 이런 경우는 이 메서드가 속한 클래스의 이름으로 이미 구분이 가능하니 메서드 이름이 동일해도 상관이 없는 걸까요?

2022-11-12 14:07 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/command/CommandType.java
> +            Stream.of(values())
`static final` 로 된 상수는 다음부터 대문자 처리해야 겠군요!

2022-11-12 14:07 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/io/ConsoleIO.java
> +    public static final String VOUCHER_AMOUNT_PROMPT = "Enter a value. (fixed - 0~ | percent - 0~100)";
고민 끝에 ConsoleManager로 변경해했습니다..ㅎㅎ

2022-11-12 14:08 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/VoucherMetaData.java
> +    private String amount;
만약 DTO에서 추가적으로 검증을 한다거나 하면 의미가 있는 DTO가 되는 것일까요?

2022-11-12 14:15 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +    private VoucherValidator voucherValidator;
이미 각 클래스의 단위테스트가 있으니 실제 클래스들을 실행하기 보다는 `CommandExecutor` 에서 저 클래스들의 반환값이 잘 상호작용하는지 테스트해보고 싶었습니다!

2022-11-12 14:17 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +                // then
혹시 then이 테스트의 결과를 확인하는 부분인데 이것을 확인하지 않으니 자동화의 의미가 떨어진다고 하신 것일까요?

2022-11-12 14:18 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/voucher/utils/VoucherMapperTest.java
> +            public void 값_10() {
네이밍을 이렇게 하는 것이였군요! 네이밍 컨벤션을 한번 찾아봐야 할 것 같습니다..

2022-11-12 14:20 UTC, dlxortmd987 commented
@hongbin-dev @hongbin-dev  피드백이 이쪽에 반영되어서 여기다가 멘션 남깁니다!

2022-11-12 14:45 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/app/VoucherControllerStatus.java
> +    }
넵 타입언어를 쓰는 이유이기도 하구요.
Program을 종료하는건 세부사항입니다. 다른 객체에게 제공하는 메서드를 너무 상세하게 제공하고 있어요. 
아래 글을 읽어보시면 좋을듯 합니다.

https://velog.io/@octofox1357/%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5%EC%9D%98-%EC%82%AC%EC%8B%A4%EA%B3%BC-%EC%98%A4%ED%95%B4-05-%EC%B1%85%EC%9E%84%EA%B3%BC-%EB%A9%94%EC%8B%9C%EC%A7%80

2022-11-12 14:46 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/io/ConsoleIO.java
> +    public static final String VOUCHER_AMOUNT_PROMPT = "Enter a value. (fixed - 0~ | percent - 0~100)";
ConsoleIo라는 네이밍으로 변경을 원하긴 했습니다..ㅋㅋ

2022-11-12 14:46 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/VoucherMetaData.java
> +    private String amount;
지금은 도메인객체간의 OOP를 집중했으면해서요~ 아직 DTO가 불필요하다고 생각했어요!

2022-11-12 14:47 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +    private VoucherValidator voucherValidator;
상호작용을 테스트하면서 불편한점은 없으셨나요? 목 테스트의 단점이 어떤게 있을까요?

2022-11-12 14:47 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +                // then
넵, 확인한게 없으니 무조건 pass될거라고 생각했어요.

2022-11-12 14:47 UTC, hongbin-dev commented
@dlxortmd987 여기는 머지되어서 확인이어렵습니다! 다음단계에 반영해주시죠.

2022-11-12 17:22 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/app/VoucherControllerStatus.java
> +    }
지금 객사오를 읽고 있는데 이 부분을 더 고심하면서 읽어보겠습니다...!

2022-11-12 17:25 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/VoucherMetaData.java
> +    private String amount;
그렇군요 답변 감사합니다~

2022-11-12 18:00 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/io/ConsoleIO.java
> +    public static final String VOUCHER_AMOUNT_PROMPT = "Enter a value. (fixed - 0~ | percent - 0~100)";
그렇군요..ㅎㅎ 단축어도 카멜케이스를 지킨다는 정보 감사합니다!

2022-11-12 18:01 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/VoucherMetaData.java
> +    private String amount;
아하 나중에 MVC 진행할 때 DTO를 적극 활용하겠습니다!

2022-11-12 18:06 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +                // then
그렇군요! 답변 감사합니다!

2022-11-12 18:15 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/command/CommandExecutorTest.java
> +    private VoucherValidator voucherValidator;
아무래도 제가 결과를 인위적으로 만드는 것이다 보니 정확히 테스트하는 것이 맞나? 하는 의문이 들었고,
구현이 조금씩 변경될 때마다 테스트 코드를 변경해야 하는 어려움이 있었습니다.

ps. 찾아보니 제가 어려움을 겪은 것이 단점으로 지적되는 것이네요!
- 테스트 코드의 관리가 어려움
- 신뢰도가 떨어짐
- 가독성이 떨어짐
https://medium.com/@chanhyeonglee/mock-%EA%B0%9D%EC%B2%B4-%EB%82%A8%EC%9A%A9%EC%9D%80-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C%EB%A5%BC-%EB%A7%9D%EC%B9%9C%EB%8B%A4-f38129e5d40a