[3기-C] 김영수 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #541
Opened 2022-11-09 06:38 UTC by devYSK

## 📌 과제 설명 

콘솔을 통하여 
FixedVoucher, PecentVoucher를 Create, Read 하고 
BlackList를 Read 할 수 있는 기능을 가진  커맨드라인 애플리케이션을 구현하는 과제입니다.

사용자는 콘솔에 보이는 안내문을 이용하여 명령어를 입력할 수 있고, 올바른 명령어 입력시 요청을 수행하고 결과를 보여줍니다.
올바른 명령어를 입력하지 않았을 시에는 콘솔로 잘못되었다는걸 안내해줍니다.

## 👩‍💻 요구 사항

#### 1. **바우처 관리 애플리케이션**

- [x] Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.

- [x] 바우처 관리 Command-line Application을 만들어본다.

- [x] 스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)

- [x] 프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

  ```bash
  === Voucher Program ===
  Type **exit** to exit the program.
  Type **create** to create a new voucher.
  Type **list** to list all vouchPfiers.
  ```

 - [x] create / list 커맨드를 지원한다.

   - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
   - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
   - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. 

- [x] 적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.

- [x] 실행가능한 `jar` 파일을 생성한다.

<br>

#### 2. 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x] 메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
  - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x] 고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x] YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ `구현 내용`

1. 콘솔을 통한 가이드 메시지 출력 기능
2. 콘솔을 통한 명령어 입력 기능
3. 명령어를 통한 Voucher를 Create, Read 기능
4. 명령어를 통한 BlackList를 Read 기능
5. 잘못된 명령어 입력시 오류 메시지 출력 기능
6. 파일 입출력 기능 
7. local, dev Profile 분리하여 local에는 memory로 데이터 관리, dev 에는 file로 데이터 관리 기능

<br> 

#### `다음은 가이드 메시지의 예 입니다.` 

> === Voucher Program ===
> Type 'exit' to exit the program. 
> Type 'create' to create a new voucher.
> Type 'list' to list all vouchers.
> Type 'black-list' to list all black list customers.

<br>

#### `다음은 명령어 입력을 통한 Voucher Create, Read 기능 예 입니다.`

> === Voucher Program ===
> Type 'exit' to exit the program. 
> Type 'create' to create a new voucher.
> Type 'list' to list all vouchers.
> Type 'black-list' to list all black list customers.
>
> > create
>
> select voucherType 'fixed' or 'percent' : 
>
> > fixed
>
> input discount amount : 
>
> > 100

<br>

#### `다음은 명령어를 통한 BlackList Read 기능 예 입니다.`

* 파일에서 읽어온 데이터입니다.

> === Voucher Program ===
> Type 'exit' to exit the program. 
> Type 'create' to create a new voucher.
> Type 'list' to list all vouchers.
> Type 'black-list' to list all black list customers.
>
>  > black-list
>
> BlockCustomer{blockId=102277a8-9ca1-4035-a0a6-c83881151d17, customerId=834e16c3-1c51-484f-8744-81eb309c447d, registeredAt=2022-11-08T15:04:29.092}
> BlockCustomer{blockId=102271a8-9ca1-4035-a0a6-c83881151d17, customerId=834e16c3-1c51-484f-8744-80eb309c447d, registeredAt=2022-11-08T15:04:29.092}
> BlockCustomer{blockId=102571a8-9ca1-4035-a0a6-c83881151d17, customerId=83ae16c3-1c51-484f-8744-81eb309c447d, registeredAt=2022-11-08T15:04:29.092}
> BlockCustomer{blockId=0ef4e0ab-99d3-4ddd-86c7-aa07e5b01e76, customerId=02289d1f-9bdc-4e94-b87f-dfed28de7ec6, registeredAt=2022-11-08T15:04:33.009}
> BlockCustomer{blockId=0ef4e03b-99d3-4ddd-86c7-aa07e5b01e76, customerId=02230d1f-9bdc-4e94-b87f-d9ed28de9ec6, registeredAt=2022-11-08T15:04:33.009}
> BlockCustomer{blockId=d1b551b6-cc14-4113-a709-c97c945a29a1, customerId=a41138fe-a27b-493b-8ba5-676f65f32fe0, registeredAt=2022-11-08T15:04:38.696}
> BlockCustomer{blockId=d1b571b6-cc14-4113-a709-c97c945a29a1, customerId=a41128fe-a27b-493b-8ba5-606f65f32fe0, registeredAt=2022-11-08T15:04:38.696}
> BlockCustomer{blockId=d1b351b6-cc14-4113-a709-c97c945a29a1, customerId=a41339fe-a27b-493b-8ba5-656f65f32fe0, registeredAt=2022-11-08T15:04:38.696}

<br>

#### `다음은 잘못된 명령어 입력 시 오류 메시지 출력 기능입니다.`

> === Voucher Program ===
> Type 'exit' to exit the program. 
> Type 'create' to create a new voucher.
> Type 'list' to list all vouchers.
> Type 'black-list' to list all black list customers.
>
> > xczvxzv
>
> 잘못된 명령어 입력입니다. input : xczvxzv

---

### 패키지

<img src="https://user-images.githubusercontent.com/41531594/200747397-451ad062-3caa-40a4-ba31-34bb3351d856.png" width=450 height = 700>

## 클래스 설명

* CommandLineApplication  - Appllication Start class. 시작지점인 메인 클래스 입니다.

* AppConfig  - Application Configruation class. Bean 생성 을 담당하도록 따로 만들었습니다.

#### IO
* Command -  명령어를 관리하는 enum 입니다.
* CommandLineController - 명령어를 받아 요청을 전달해주는 클래스 입니다.
* Console - 입출력을 담당하는 클래스 입니다
* Input  -  입력을 담당하는 인터페이스 입니다.
* ConsoleInput - 입력을 담당하는 클래스 입니다. Input을 구현하고 있습니다.
* Output - 출력을 담당하는 인터페이스입니다.
* ConsoleOutput - 출력을 담당하는 클래스입니다. Output을 구현하고 있습니다.  
* ConsoleRunningStatus - 콘솔 애플리케이션의 실행상태를 담당하는 클래스입니다.,  

#### domain
* BlockCustomer - 블랙리스트 유저를 담는 도메인 클래스입니다.
* Voucher - 바우처를 담는 추상 클래스 입니다. 여러 바우처 타입의 공통점을 모아 추상클래스로 만들었습니다.
* VoucherType  - 바우처 타입을 나누는 enum입니다.
* FixedAmountVoucher  - 고정된 금액을 할인할 수 있는 바우처 도메인 클래스 입니다.
* PercentDiscountVoucher - 할인율로 할인할 수 있는 바우처 도메인 클래스 입니다.

#### repository
* BlockCustomerRepository - 블랙리스트 유저를 관리하는 레포지토리 인터페이스입니다. 
* FileBlockCustomerRepository - 블랙리스트 유저를 파일로 관리하는 클래스 입니다. BlockCustomerRepository를 구현합니다.
* MemoryBlockCustomerRepository - 블랙리스트 유저를 메모리로 관리하는 클래스 입니다. BlockCustomerRepository를 구현합니다.

* VoucherRepository - 바우처를 관리하는 레포지토리 인터페이스입니다. 
* MemoryVoucherRepository - 바우처를 메모리로 관리하는 클래스입니다. VoucherRepository를 구현합니다.
* FileVoucherRepository  - 바우처를 파일로 관리하는 클래스입니다. VoucherRepository를 구현합니다.

#### request
* VoucherCreateRequest - 명령어를 바우처 생성요청으로 변환하여 전달하는 클래스 입니다. 

#### service
* BlockCustomerService - 블랙리스트 유저 조회 요청을 레포지토리에서 읽어올 수 있는 서비스 클래스입니다.
* VoucherFactory  - 바우처를 생산하는 책임을 담고있는 팩토리 클래스입니다. static method로 생성합니다.
* VoucherService  - 바우처를 생성하거나 조회하는 로직을 담은 서비스 클래스 입니다. 

#### util
* FileUtil  - 파일을 생성 및 삭제할 수 있는 책임을 가진 유틸 클래스입니다.

#### resources
* application.yml - profile에 따른 설정을 나눌 목적으로 yml 파일입니다.
* logback.xml - 로그를 기록할 방법을 담을 logback 파일입니다.

## ✅ PR 포인트 & 궁금한 점 

1. 테스트코드를  최대한 일어날 수 있는 상황들을 생각하여 작성하였습니다.
  * 놓친 상황들이 없는지 궁금합니다.
  * 엣지케이스 상황이 어디서 있을 수 있는지, 또는 찾을 수 있는 요령이 궁금합니다
  * 테스트가 쉽도록 구현해졌는지, 아니라면 어떤식으로 구성을 바꾸면 되는지 궁금합니다.
  * 단위 테스트만 작성했습니다. 현재구조에서는 어떤방식으로 통합테스트를 가져가면 좋을지 궁금합니다. 
  *  올바른 테스트코드(목적에 맞는지? 더 해야하는 케이스가있는지?)에 대해 피드백 부탁드립니다.

2. 역할과 책임이 잘 분리되었는지 피드백 부탁드립니다.
  * while문의 위치가 애매한거 같습니다. 어디로 옮기면 더 좋을지 궁금합니다. 

3. 이외 다양한 부족한 점이나 개선점 짚어주시길 요청드립니다. 

감사합니다.

2022-11-09 09:41 UTC, WooSungHwan requested changes
영수님 과제하시느라 수고 많으셨습니다. 몇가지 코멘트를 남겼으니 확인부탁드립니다^_^

2022-11-09 09:41 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/controller/CommandLineController.java
> +        while (ConsoleRunningStatus.isRunning()) {
console 프로젝트이므로 while문의 위치까지는 너무 깊게 들여다보진 않았으면 좋겠어요. 지금 layer 구조도 잘 되어있습니다. 이렇게 콘솔로 많이들 개발하지 않아서 정제되고 증명된 표준 개발방법이 없어서 혼동이 오시는걸거에요.

2022-11-09 09:41 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/controller/Console.java
> +public class Console  {
좋네요 ㅎㅎ

2022-11-09 09:41 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/domain/PercentDiscountVoucher.java
> +        return getVoucherId() == that.getVoucherId();
equals 메소드가 BlockCustomer 클래스와 기준이 다른것 같아요.

2022-11-09 09:41 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/domain/VoucherType.java
> +            .filter(voucher -> voucher.type.equals(voucherType.toUpperCase()))
저는 주로 권장하는 방식이
`Objects.equals(voucher.type, voucherType.toUpperCase())`
이걸 더 권장하고 있긴합니다. Object 클래스의 오버라이딩 equals 메소드를 쓰는건 NPE 가능성이 너무 높거든요

2022-11-09 09:41 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/FileVoucherRepository.java
> +        @Value("${file.voucher.stored-extension}") String fileExtension) {
얘네를 raw한 변수들로 주입해야만 할까요? 보기에 더 기분좋은 방법은 없을까요? ㅎㅎ

2022-11-09 09:41 UTC, WooSungHwan commented on src/test/java/org/prgrms/springorder/controller/CommandTest.java
> +class CommandTest {
입력값이 'exit'이면 Command.EXIT 가 생성된다.

이런 류의 테스트는 createCommandSuccessTest 해당 테스트와 다른점이 없는 것 같습니다.

2022-11-09 09:41 UTC, WooSungHwan commented on src/test/java/org/prgrms/springorder/controller/CommandTest.java
> +class CommandTest {
파라미터라이즈 테스트 성공, 실패 두개만으로도 괜찮을 것 같습니다.

2022-11-09 09:41 UTC, WooSungHwan commented on src/test/java/org/prgrms/springorder/controller/ConsoleInputTest.java
> +class ConsoleInputTest {
해당 테스트는 기능을 사용함으로써 많이 테스트가 됐을 것으로 예상됩니다. 

기능이 동작하는 지에 대한 테스트보다는 비즈니스가 예상했던 대로 동작하는지에 대한 테스트 위주로 작성해야 할 것 같아요.

2022-11-09 09:41 UTC, WooSungHwan commented on src/test/java/org/prgrms/springorder/controller/ConsoleOutputTest.java
> +class ConsoleOutputTest {
여기도 input과 동일합니다.

2022-11-09 09:41 UTC, WooSungHwan commented on src/test/java/org/prgrms/springorder/controller/ConsoleRunningStatusTest.java
> +class ConsoleRunningStatusTest {
이 부분도 충분한 통합테스트, 기능테스트 -> 콘솔이므로 프로그램을 돌려본다거나 등등

으로 충분히 테스트가 됐다고 생각되는 부분입니다.

2022-11-09 09:41 UTC, WooSungHwan commented on src/test/java/org/prgrms/springorder/controller/ConsoleTest.java
> +class ConsoleTest {
이부분은 좋네요.

2022-11-09 09:42 UTC, WooSungHwan commented
테스트코드를 최대한 일어날 수 있는 상황들을 생각하여 작성하였습니다. 놓친 상황들이 없는지 궁금합니다.
엣지케이스 상황이 어디서 있을 수 있는지, 또는 찾을 수 있는 요령이 궁금합니다
테스트가 쉽도록 구현해졌는지, 아니라면 어떤식으로 구성을 바꾸면 되는지 궁금합니다.
단위 테스트만 작성했습니다. 현재구조에서는 어떤방식으로 통합테스트를 가져가면 좋을지 궁금합니다.
올바른 테스트코드(목적에 맞는지? 더 해야하는 케이스가있는지?)에 대해 피드백 부탁드립니다.
역할과 책임이 잘 분리되었는지 피드백 부탁드립니다.
while문의 위치가 애매한거 같습니다. 어디로 옮기면 더 좋을지 궁금합니다.
이외 다양한 부족한 점이나 개선점 짚어주시길 요청드립니다.

2022-11-09 09:44 UTC, WooSungHwan commented
흠?

2022-11-09 09:46 UTC, choi1204 reviewed
영수님 수고하셨습니다!
코멘트 확인하시고 학습하시는데 도움되셨으면 좋겠습니다!

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/controller/Console.java
> +    public VoucherCreateRequest getVoucherCreateRequest() {
Console에서 VoucherCreateRequest를 알고 있는게 좋을까요?

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        @Value("${file.block-customer.path}") String path,
@ConfigurationProperties를 활용해서 properties나 yml에서 관리할 정보들은 클래스 단위로 관리해 주면 좋을 것 같아요

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        write(insertData);
실질적으로 동작은 In-memory인 Map storage를 사용하는데 파일 생성마다 파일입력을 하는 것은 별로 좋지 못할 것 같아요.
작업을 묶어서 일정 단위, 또는 서버가 종료될 때 한번에 insert를 해주는 것이 좋아보여요

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/FileVoucherRepository.java
> +        @Value("${file.voucher.path}") String path,
이 부분도 마찬가지로 따로 관리해주는게 더 좋을 것 같아요

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/config/AppConfig.java
> +    @Bean
어떤 클래스는 Bean을 사용하여서 의존성을 주입하였고 다른 클래스의 경우 @Component를 활용해서 의존성을 관리하고 있어요. 어떤 차이를 두고 관리를 하고 있는건가요?
또 어떠한 경우에 @Bean을 사용하고 @Component를 사용하면 좋을지 학습하면 좋을 것 같아요

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/controller/CommandLineController.java
> +                    "created Voucher. : " + voucherService.createVoucher(voucherCreateRequest));
이렇게 하면 바우처의 레퍼런스 값이 나올 것 같은데 의도한 값인가요?

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/controller/CommandLineController.java
> +            case LIST -> console.showMessages(voucherService.findAll().stream()
아래의 BlackList와 하는 동작이 List -> String으로 같은 것같아요. 중복된 코드를 제거하면 좋을 것 같아요

2022-11-09 09:46 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/controller/Console.java
> +    public void showMessages(String... messages) {
가변 인수를 많이 사용하시는 게 보여요.
가변 인수의 경우 파라미터의 개수 체크 및 성능에 별로 좋지 않아서 꼭 필요한 상황일때에만 사용하는 것을 추천드려요

2022-11-09 09:49 UTC, WooSungHwan commented
```
1. 테스트코드를  최대한 일어날 수 있는 상황들을 생각하여 작성하였습니다.
  * 놓친 상황들이 없는지 궁금합니다.
  * 엣지케이스 상황이 어디서 있을 수 있는지, 또는 찾을 수 있는 요령이 궁금합니다
  * 테스트가 쉽도록 구현해졌는지, 아니라면 어떤식으로 구성을 바꾸면 되는지 궁금합니다.
  * 단위 테스트만 작성했습니다. 현재구조에서는 어떤방식으로 통합테스트를 가져가면 좋을지 궁금합니다. 
  *  올바른 테스트코드(목적에 맞는지? 더 해야하는 케이스가있는지?)에 대해 피드백 부탁드립니다.

2. 역할과 책임이 잘 분리되었는지 피드백 부탁드립니다.
  * while문의 위치가 애매한거 같습니다. 어디로 옮기면 더 좋을지 궁금합니다. 

3. 이외 다양한 부족한 점이나 개선점 짚어주시길 요청드립니다. 
```

- 놓친 상황들이 없는지 궁금합니다. -> 제가 다 봐드릴수는 없는 부분입니다.
- 엣지케이스 상황이 어디서 있을 수 있는지, 또는 찾을 수 있는 요령이 궁금합니다 -> 기본적으로 요구사항을 가장 잘 아는 사람이 많은 케이스를 도출하게 됩니다. 이는 연차에 따라서도 개발 실력에 따라서도 아니라 개발자 스스로에 대한 관심이 요령이라면 요령이라고 할 수 있을 것 같습니다.
- 테스트가 쉽도록 구현해졌는지, 아니라면 어떤식으로 구성을 바꾸면 되는지 궁금합니다. -> 사실 애초에 복잡한 비즈니스가 없어서 테스트가 쉽게 나와야 정상입니다 ㅎㅎ
- 단위 테스트만 작성했습니다. 현재구조에서는 어떤방식으로 통합테스트를 가져가면 좋을지 궁금합니다.  -> 통합테스트라고 칭하기 보다는 BDD 를 참조해보면 좋을 것 같습니다.

나머지 답변드리지 않은 부분은 코멘트에서 충분히 들여다 보실 수 있을 것 같습니다. ^_^

2022-11-09 09:54 UTC, devYSK commented on src/main/java/org/prgrms/springorder/config/AppConfig.java
> +    @Bean
@choi1204 

@Bean과 @Component의 차이는 @Bean은 메소드 레벨에서 선언하고 @Component는 클래스 레벨에서 선언하여 사용하는것으로 알고있습니다!.

@Bean은 수동등록, @Component는 정의된 클래스 자체를 자동등록 해주는 차이가 있는걸로 알고있습니다!

일부러 수동으로 등록한 이유는,
ConsoleInput, ConsoleOutput을 테스트하기 위해서 Scanner대신 BufferedReader, BufferedWriter를 사용했습니다.
생성자인자로 받는 Stream을 수동으로 지정해 주기 위해서따로 @Bean으로 빈을 생성해서 의존성을 주입한것입니다!

Stream을 Bean으로 등록할 필요가 없다하여 사용했는데 잘못 사용한 케이스일까요..? 
혹시  지금보다 더 나은 케이스가 있을까요??

리뷰 감사드립니다!

2022-11-09 09:55 UTC, devYSK commented on src/main/java/org/prgrms/springorder/controller/CommandLineController.java
> +                    "created Voucher. : " + voucherService.createVoucher(voucherCreateRequest));
@choi1204 

마땅히 출력값 표준이 정해지지 않아서 제가 임의로 toString()을 override하여 객체 내부 값이 출력하도록 의도하였습니다!!

리뷰 감사드립니다!

2022-11-09 09:56 UTC, devYSK commented on src/main/java/org/prgrms/springorder/controller/CommandLineController.java
> +            case LIST -> console.showMessages(voucherService.findAll().stream()
@choi1204 

맞습니다. 중복 제거할 수 있는 부분이 있을것 같아요. 중복 제거하고 조금 더 나은 방식으로 리팩토링 해보겠습니다!

리뷰 감사드립니다!

2022-11-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/springorder/controller/Console.java
> +    public void showMessages(String... messages) {
@choi1204 

아 가변인수의 경우 파라미터 개수 체크가 선행된다는 점을 모르고 있었습니다 알려주셔서 감사합니다. 

성능을 생각한다면 List보단 Array가 나을거 같은데 제 생각이 맞을까요? 

리뷰 감사드립니다.

2022-11-09 10:00 UTC, devYSK commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        @Value("${file.block-customer.path}") String path,
@choi1204 

말씀해주신점 생각해보니,
@ConfigurationProperties를 활용해서 프로퍼티를 담을 클래스를 구현하고, 빈을 만든다음에 
레포지토리에서 주입받아서 관리하는게 가독성면에서도 더 좋을것 같습니다.

리뷰 감사드립니다!

2022-11-09 10:05 UTC, devYSK commented on src/main/java/org/prgrms/springorder/controller/Console.java
> +    public VoucherCreateRequest getVoucherCreateRequest() {
@choi1204 

하지만 현재 구현한 애플리케이션 상태에서 Console이 입출력을 담당하고있고, 
저 Request를 만드는 과정은 출력 2번, 입력 2번이 필요한 상황입니다. 

Console에 넣어서 만들거나, Controller 에서 따로 만들거나 해야 하는데,
두 방법 중 고민하다가 Console에 넣게 되었습니다. 출력을하거나, 입력을받아 전달하는 용도니까요 

그렇다면 다른 케이스인 Controller에서 Console을 이용하여 Request를 만드는 로직을 만드는게 어떤면에서 좋을까요?
Request를 어디서 만들어야 할지에 대한 마땅한 아이디어가 아직은 떠오르지 않습니다..

리뷰 감사드립니다!

2022-11-09 10:09 UTC, devYSK commented on src/test/java/org/prgrms/springorder/controller/ConsoleRunningStatusTest.java
> +class ConsoleRunningStatusTest {
@WooSungHwan 

아 실행으로도 테스트 가능한 부분은 충분하다고 봐도 되는 부분이군요!!

단순한 로직이여도 테스트가 어렵지 않고, 
테스트 할 수 있어서 한 부분이였는데,
말씀해주신 부분처럼 콘솔이니까 그렇게도 테스트 되는것 같습니다! 

리뷰 감사드립니다!

2022-11-09 10:10 UTC, devYSK commented on src/test/java/org/prgrms/springorder/controller/ConsoleInputTest.java
> +class ConsoleInputTest {
@WooSungHwan 

비즈니스가 예상했던 대로 동작하는지에 대한 테스트 라는건, 통합테스트처럼 쭉 흐르면서 동작되는것을 말씀하시는걸까요!?

리뷰감사드립니다!

2022-11-09 10:11 UTC, devYSK commented on src/test/java/org/prgrms/springorder/controller/CommandTest.java
> +class CommandTest {
@WooSungHwan 

아 그런거같습니다. 지금 같은 테스트에 대한걸 중복으로 하고있었네요!! 

리뷰 감사드립니다!!

2022-11-09 10:14 UTC, devYSK commented on src/main/java/org/prgrms/springorder/domain/PercentDiscountVoucher.java
> +        return getVoucherId() == that.getVoucherId();
@WooSungHwan 

이 부분 수정하여 재 커밋 하도록 하겠습니다! 

리뷰 감사드립니다!

2022-11-09 10:16 UTC, devYSK commented on src/main/java/org/prgrms/springorder/repository/FileVoucherRepository.java
> +        @Value("${file.voucher.stored-extension}") String fileExtension) {
@WooSungHwan 

현웅님이 `@ configurationproperties ` 라는 좋은 아이디어를 주셔서,
이부분 클래스로 깔끔하게 관리되도록 해보겠습니다! 

리뷰 감사드립니다!

2022-11-09 10:23 UTC, devYSK commented on src/main/java/org/prgrms/springorder/domain/VoucherType.java
> +            .filter(voucher -> voucher.type.equals(voucherType.toUpperCase()))
@WooSungHwan 

말씀해주신 내용 보고 Objects.equals()를 좀 찾아보았습니다.

Objects.equals(A, B)는 Object A에 대한 null 체크를 하므로 어느정도 NPE를 방지?시켜주는 부분이 있어 조금 더 안전하다고 볼 수 있는것 같습니다.


String Type인 voucher.type 으로 Equals 비교하는것 보단, 
null 체크를 해주는 Objects.equals()를 사용하는것이 NPE로부터 조금 더 안전하다! 라고 이해한게 맞을까요!?

리뷰 감사드립니다!

2022-11-09 10:28 UTC, devYSK commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        write(insertData);
@choi1204 

말씀을 듣고 좀 생각해봤는데, Map stroage가 1개로 관리되고, storage를 종료될 때 한번에 INSERT를 하게 된다면   중복되는 값이 있을것 같아요! 
그래서 
1. 기존 파일에 있던 데이터를 담는 storage1개
2. 새 데이터를 담고 서버가 종료될 때 wirte할 storage 1개 

2개를 사용해보려고 합니다.
이렇게 구현한다면 find 할 때는 맵 2곳에서 찾아야하는 부분도 있겠네요! 

이렇게 구현한다면 어떨지, 아니면 storage 1개로 동기화 로직을 만드는게 나을지 현웅님의 생각이 궁금합니다!.
 
 리뷰 감사드립니다!

2022-11-09 12:03 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        @Value("${file.block-customer.path}") String path,
영수님 이부분도 태그가 되버렸네요...

2022-11-09 12:06 UTC, devYSK commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        @Value("${file.block-customer.path}") String path,
앗 이런.. 다음부터는 태그 안되도록 조심해서 코멘트 달도록 하겠습니다 번거롭게 해서 죄송합니다

2022-11-09 12:07 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        write(insertData);
2개를 사용해서 만들경우 우려할 점으로 기존파일을 삭제한다면 어떻게 처리해야 할까? 라는 의문이 드네요.
이 점은 동기화의 경우에도 똑같이 고려해야 할 문제입니다.
가장 단순하게 문제를 해결한다면 종료될 때 파일을 동기화 처리하는게 아니라 storage를 바탕으로 새로운 파일로 덮어쓰기 하는 거라고 생각이 들어요.
이 방법 또한 장단점이 뚜렷하기에 여유가 있으시다면 어떻게 효율적으로 동기화를 처리할지 고민해보시는것도 좋을 것 같아요

2022-11-09 12:10 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/controller/Console.java
> +    public VoucherCreateRequest getVoucherCreateRequest() {
OOP의 관점으로 볼때 콘솔이 VoucherCreateRequest를 만들어주는 것은 각자의 책임이 분리된 것 같지 않아요.
차라리 CommanLineController의 내부 메서드로 있는게 더 바람직할 것 같아요

2022-11-09 12:33 UTC, devYSK commented on src/main/java/org/prgrms/springorder/repository/FileBlockCustomerRepository.java
> +        write(insertData);
맞습니다 현재 상황에서 최선의 방법을 선택해서 구현해야겠습니다!

2022-11-09 15:36 UTC, devYSK reviewed
리뷰 내용 반영해서 수정하고 커밋하였습니다.

2022-11-11 06:04 UTC, WooSungHwan approved these changes
안녕하세요! 영수님!
테스트코드와 main 코드와의 비율이 거의 50:50인것 같네요! ㅎㅎ
과제하시느라 고생하셨습니다.

2022-11-13 04:17 UTC, merged