[3기-C] 김환 SpringBoot Part1 Weekly Mission제출합니다.
prgrms-be-devcourse/springboot-basic pull request #543
Opened 2022-11-09 14:53 UTC by hwankim123

## 📌 과제 설명 
* create / list 기능을 구현하였습니다.

## 👩‍💻 요구 사항과 구현 내용 
(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [X]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [X]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

   ```bash
   === Voucher Program ===
   Type **exit** to exit the program.
   Type **create** to create a new voucher.
   Type **list** to list all vouchers.
   ```

    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.
## ✅ 피드백 반영사항  
저번 PR때 다 반영하지 못한 리뷰들의 반영사항을 merge된 리뷰 링크와 함께 알려드립니다.
코드라인 상에 코멘트도 한번 더 남기겠습니다!

* [ApplicationStatus 클래스를 더이상 Bean으로 등록하지 않도록 수정하였습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/526/files#r1015557226)
  - Spring Bean에 상태가 생기면 여러 스레드가 상태 변수에 접근하여 동시성 문제가 생길 수 있음을 확인하였고, 이 클래스는 상태가 필요하기 때문에, Bean으로 등록하지 않았습니다.
* [출력 메세지 상수들을 Console 클래스가 갖고 있도록 수정하였습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/526#discussion_r1015555012)
* [MenuInputResult DTO를 삭제하였습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/526#discussion_r1014627584)
## ✅ PR 포인트 & 궁금한 점 
* 예외 처리 포인트가 많아지면서, 커스텀 예외를 만들고 throw 해주도록 하였습니다. 그런데 커스텀 예외들이 `RuntimeException`을 상속받다보니, **컴파일러가 예외 처리 여부를 검사하지 않습니다.** 이 커스텀 예외들을 처리해야 함을 알리기 위해 `Exception`을 상속하도록 바꿀까 생각해보다가, javadoc을 남기는 것에서 끝냈습니다. **제가 만든 커스텀 예외를 처리해야 한다는 사실을 알리기 위한 좋은 방법이 있을까요?**
* 패키지 구조를 조금 신경써서 바꾸어보았는데, 개선할 점 있을까요? 프로젝트의 enum들을 모두 `common.enums` 패키지를 생성하여 관리할까 생각해보았는데, enum마다 사용 범위가 다 달라서, 가장 관련 있는 패키지 하위에 두기로 하였습니다.

2022-11-09 15:02 UTC, hwankim123 reviewed
저번 PR때 다 반영하지 못한 리뷰들의 반영사항을 merge된 리뷰 링크와 함께 알려드립니다.

2022-11-09 15:02 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/console/Console.java
> +    private static final String CREATE_SUCCESS_MESSAGE = "Voucher ID {0} created successfully!";
@hongbin-dev 

[출력 메세지 상수들을 Console 클래스가 갖고 있도록 수정하였습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/526#discussion_r1015555012)

2022-11-10 13:18 UTC, seung-hun-h requested changes
안녕하세요 환님!
피드백 잘 반영 해주셨네요 고맙습니다. 예외 처리도 꼼꼼히 해주신 것 같아요 👍 
리뷰 남겼으니 확인해주세요

---
예외 처리 포인트가 많아지면서, 커스텀 예외를 만들고 throw 해주도록 하였습니다. 그런데 커스텀 예외들이 RuntimeException을 상속받다보니, 컴파일러가 예외 처리 여부를 검사하지 않습니다. 이 커스텀 예외들을 처리해야 함을 알리기 위해 Exception을 상속하도록 바꿀까 생각해보다가, javadoc을 남기는 것에서 끝냈습니다. 제가 만든 커스텀 예외를 처리해야 한다는 사실을 알리기 위한 좋은 방법이 있을까요?
- 자바 예외에는 크게 Checked Exception과 Unchecked Exception 두 가지가 있습니다. 전자는 반드시 catch 하거나 throws를 해주어야 하고, 후자는 하던 말던 상관하지 않습니다. Exception은 전자에 속하고, RuntimeException은 후자에 속하죠
- 최근에는 Checked Exception을 잘 사용하지 않는 추세입니다. 여기에는 몇 가지 이유가 있는데요, 가장 큰 이유 중 하나로 작성하는 코드 자체가 발생하는 예외 자체에 종속됩니다. 만약 라이브러리를 변경하게 되면 변경 지점이 커져버리게 되죠.
- 지금 내가 작성하는 코드에서 이 예외를 반드시 처리하게끔 Check Exception을 던지는 것이 맞을까 한 번 고민 해보세요. 다양한 아티클이 있을 거에요.


패키지 구조를 조금 신경써서 바꾸어보았는데, 개선할 점 있을까요? 프로젝트의 enum들을 모두 common.enums 패키지를 생성하여 관리할까 생각해보았는데, enum마다 사용 범위가 다 달라서, 가장 관련 있는 패키지 하위에 두기로 하였습니다.
- enum 클래스를 모두 같은 패키지에 두는 것은 좋은 생각이 아닌 것 같습니다. 같은 도메인인데 다른 패키지에 존재할 수도 있으니까요

2022-11-10 13:18 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/console/Console.java
> +        }
VoucherType 두 가지에 해당하지 않는 경우에 대해서도 처리하면 좋을 것 같네요:)

2022-11-10 13:18 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/voucher/VoucherManager.java
> +                .construct(voucherInfo);
`construct`라는 이름은 잘 사용하지 않는 것으로 알고 있어요. `createVoucher` 같은 이름을 사용하는 것이 좋을 것 같아요

2022-11-10 13:18 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/voucher/VoucherManager.java
> +        }
바우처가 하나도 없는 상황이 과연 예외적인 상황인지 생각해 볼  필요가 있는 것 같아요

2022-11-10 13:18 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/voucher/VoucherType.java
> +            throw new NumberFormatException(MessageFormat.format("Your input {0} is not integer.", amountInput));
예외 메시지를 알아보기 쉽게 잘 작성하셨네요 👍

2022-11-10 13:18 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/voucher/domain/FixedAmountVoucher.java
> +    int fixedAmount;
변경되지 않는 값이라면 `private final`을 사용하는 것이 더 좋을 것 같네요

2022-11-10 13:30 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        this.applicationStatus = new ApplicationStatus();
아 ApplicationStatus가 상태를 갖고있는 것 때문에 VoucherApplication까지 상태를 가져버린다고 이해하면 될까요? 그렇다면 ApplicationStatus가 아얘 상태를 갖지 않도록 수정하는게 올바른 방향이 맞을까요?

2022-11-10 13:32 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/app/CommandType.java
> +                .orElseThrow(() -> new InvalidCommandTypeException(
예외들을 주로 `VoucherApplication`에서 처리하는데, `VoucherApplication`에서 똑같은 이름의 예외(IllegalArgumentException)만을 처리하고있다보니, 가독성 면에서 떨어진다고 생각했습니다.

2022-11-10 13:51 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        this.applicationStatus = new ApplicationStatus();
아 아뇨 그런의미가 아니라 VoucherApplication이 싱글턴이니 해당 생성자가 최초에 한 번만 호출될 거라는 의미였습니다. 그러면 ApplicationStatus도 한 번만 생성되어서 공유될 것 같네요. 매번 새로운 인스턴스가 생성될 수 있는 방법을 생각해보면 좋을 것 같아요

2022-11-10 14:02 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        this.applicationStatus = new ApplicationStatus();
음 ApplicationStatus가 상태를 갖고 있으니까 VoucherApplication 생성 시점이 아니라, VoucherApplication이 시작되는 시점(VoucherApplication.runLifecycle()) 마다 Application의 상태가 초기화 혹은 새로운 인스턴스 생성이 필요하다는 말씀이시죠?

2022-11-10 14:35 UTC, hongbin-dev requested changes
@hwankim123 환님 고생하셨습니다! 고민한 포인트들이 코드에서 보이는군요.

> 예외 처리 포인트가 많아지면서, 커스텀 예외를 만들고 throw 해주도록 하였습니다. 그런데 커스텀 예외들이 RuntimeException을 상속받다보니, 컴파일러가 예외 처리 여부를 검사하지 않습니다. 이 커스텀 예외들을 처리해야 함을 알리기 위해 Exception을 상속하도록 바꿀까 생각해보다가, javadoc을 남기는 것에서 끝냈습니다. 제가 만든 커스텀 예외를 처리해야 한다는 사실을 알리기 위한 좋은 방법이 있을까요?
패키지 구조를 조금 신경써서 바꾸어보았는데, 개선할 점 있을까요? 

개인적으로 정답이 없는 부분이라고 생각해요. 하지만 대부분의 Java코드들은 UncheckedException을 선호하는 것 같아요. 이건 언어별로 특성이 다른거같은데요. Checked Exception은 딸려오는 throws의 Exception등이 코드를 더럽히기도하기도하고, 매번 예외처리를 해줘야하는 단점도 있는 것 같아요. 

경험으로는 javadoc을 적는 것 보단, 테스트코드에서 어떤 케이스가 있는지, 어떤 예외를 내는지 작성했습니다. 테스트코드를 문서처럼 생각했었어요. (주석은 최신의 코드를 따라오지못합니다)

> 프로젝트의 enum들을 모두 common.enums 패키지를 생성하여 관리할까 생각해보았는데, enum마다 사용 범위가 다 달라서, 가장 관련 있는 패키지 하위에 두기로 하였습니다.

좋은 것 같습니다. 지금처럼 출력/도메인/application 잘 나눠놓으신 거 같아요.

2022-11-10 14:35 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/domain/Voucher.java
> +    int getDiscountRate();
인터페이스는 객체의 행위에 집중해야합니다. 단순 값을 꺼내는건 인터페이스와 맞지않다고 생각되네요.

https://ocwokocw.tistory.com/177 객체지향생활체조를 발제 부분인거같은데요. 읽어보시면 좋을 것 같네요.

2022-11-10 14:35 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/dto/VoucherInfo.java
> +public class VoucherInfo {
dto는 아직 불필요하다고 생각합니다. 모두 제거해주시면 좋겠네요

2022-11-10 14:35 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/storage/InMemoryVoucherStorage.java
> +    Map<UUID, Voucher> vouchers = new HashMap<>();
```suggestion
    private final Map<UUID, Voucher> vouchers = new HashMap<>();
```

2022-11-10 14:35 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/storage/InMemoryVoucherStorage.java
> +    }
객체를 저장도하고, UUID도 반환하고있는데요. 두가지 일을 하는건 아닐까요?

2022-11-10 14:35 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +            vouchers.forEach(System.out::println);
VoucherResponse의 toString을 출력로직에 사용하고 있군요. 출력메시지가 변경요청이오면 VoucherResponse를 변경해야할까요?

2022-11-10 14:35 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        VoucherType voucherType = null;
null 할당을 피할 방법은 없을까요?

2022-11-11 05:01 UTC, seung-hun-h commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        this.applicationStatus = new ApplicationStatus();
@hwankim123 네 맞습니다. 정확히 초기화는 아니겠네요. 사실 해당 애플리케이션 자체가 여럿이서 동시에 사용할 일이 없긴하죠. 하지만 빈을 싱글턴으로 처리하기 때문에 필요한 부분이라고 생각되네요.

2022-11-11 05:03 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/app/VoucherApplication.java
> +        this.applicationStatus = new ApplicationStatus();
넵 이해했습니다!!!

2022-11-11 06:48 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/voucher/domain/Voucher.java
> +    int getDiscountRate();
@hongbin-dev 이 문제에 대해서 정말 많이 고민해봤습니다.

1. 리뷰주신 대로 현재 Voucher 인터페이스는 의미있는 비즈니스 로직이 없어서, 객체의 행위에 집중해야하는 인터페이스 개념과 맞지 않습니다.
2. 그래서 enum(VoucherType)에서 validate하던 것을 Voucher 생성 시에 validate 하도록 수정해보려고 했습니다.
3.  하지만 여전히 Voucher 종류에 따라 생성자가 다를 뿐 이렇다 할 비즈니스 로직은 없습니다.

여기에서 질문이 있는데, Voucher 종류에 따라 생성자가 하는 동작이 달라지는 것만으로 Voucher를 인터페이스로 유지할 이유가 될까요?

2022-11-11 11:32 UTC, seung-hun-h commented
@hwankim123 리뷰는 다음 PR에 반영해주세요 머지하겠습니다

2022-11-11 11:32 UTC, merged

2022-11-12 05:01 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/domain/Voucher.java
> +    int getDiscountRate();
우선 validate만 존재한다는건, 지금 많은 비즈니스가 VoucherType가 책임지고 있어서 그렇게 보입니다.

또 Type으로 나뉘어져있는데, Fixed, Percent 클래스를 나눌 필요가 없어보입니다. 하나의 Voutcher 객체만 있어도 되지 않을까요?

2022-11-12 05:02 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/dto/VoucherInfo.java
> +public class VoucherInfo {
옳은 방법이다/옳지않은 방법이다는 아니지만, 지금은 도메인객체간의 OOP에 더 집중했으면 함에, 요청드린겁니다~

2022-11-12 05:02 UTC, hongbin-dev commented
@hwankim123 리뷰 답변드렸습니다 ㅎㅎ 고생하셨어요

2022-11-13 09:17 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/voucher/domain/Voucher.java
> +    int getDiscountRate();
최신 PR에 코멘트 남겼습니다!