[3기-C] 김기서 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #544
Opened 2022-11-09 15:42 UTC by rlarltj

멘토님들 안녕하세요
많이 부족한 코드지만 잘 부탁드립니다.
감사합니다!!!!!!!!!

## 📌 과제 설명
사용자가 콘솔에 Exit 명령어를 입력하기 전까지 실행되는 프로그램입니다.
Create, list, Exit을 입력 할 수 있습니다.
`Create`: 바우처를 생성하고 파일 or 메모리에 저장합니다.
`list`: 파일 or 메모리에 저장된 모든 바우처를 출력합니다.
`Exit`: 프로그램을 종료합니다.

입력을 잘못하거나 바우처 금액의 허용범위를 벗어나는 경우 프로그램 종료가 아니라 
명령을 다시 입력받도록 하였습니다.

## 👩‍💻 요구 사항과 구현 내용 

(기본) **바우처 관리 애플리케이션**

- [x]  Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

-------------

profile을 `dev`로 설정하여 파일에 바우처를 관리하도록 하였습니다.
profile을 `test`로 설정할 경우 메모리에 바우처가 관리됩니다.

파일에 저장할 때는 `Wini`라는 라이브러리를 사용하였습니다.

#### 프로젝트 구조
<img width="400" alt="프로젝트구조2" src="https://user-images.githubusercontent.com/81108344/200873706-6faaee49-e5f1-4a81-b22c-1dc14c6268ba.png">

#### 주요 클래스, 인터페이스 소개

`SpringVoucherServiceApplication`: 어플리케이션을 기동하는 클래스입니다.

`view`: 입력과 출력을 담당하는 인터페이스입니다.
`ConsoleView`: view 기능을 콘솔을 사용해 구현한 객체입니다.

`Menu`: 사용자가 선택할 수 있는 메뉴(EXIT, CREATE, LIST)를 관리하는 Enum 클래스입니다.

`Message`: 사용자에게 전달할 메시지들을 관리하는 Enum 클래스입니다.

`CommandLineApplication`: 사용자의 입력을 받고, 입력에 해당하는 메소드를 실행하는 역할입니다.

`VoucherServiceImpl`: `CommandLineApplication`의 명령에 따라 바우처를 생성하거나 `repository`를 통해 바우처를 조회, 저장하는 객체입니다.

`FileVoucherRepository`: 파일로 바우처를 관리하는 리포지토리입니다.
`HashMapVoucherRepository`: 메모리로 바우처를 관리하는 리포지토리입니다.

`FixedAmountVoucher`: 고정 금액 할인 바우처 객체입니다.
`PercentDiscountVoucher`: 정률 할인 바우처 객체입니다.
`VoucherType`: 바우처의 타입(고정, 정률)을 관리하는 Enum 클래스입니다.
`VoucherFactory`: 바우처의 생성을 담당하는 클래스입니다. 
`VoucherValidator`: 바우처를 생성하기 전에 사용자의 입력 값(바우처 타입, 바우처 금액)을 검증하는 객체입니다.

`Config`: 외부 라이브러리인 `Wini` 클래스를 빈으로 수동 등록하였습니다.

## ✅ 피드백 반영사항 

1. 바우처 타입 입력 -> 검증 -> 바우처 금액 입력 -> 검증 순으로 진행하여 로직이 매끄럽지 못했는데, 
타입과 금액의 검증을 한 번에 진행하도록 변경했습니다.

2. `CommandLineApplication`의 책임이 과중하여 바우처 입력값을 검증하고 생성하는 로직을 서비스 계층으로 위임했습니다.
`CREATE` 입력을 받으면 `CommandLineApplication`에서는 String으로 바우처의 타입과 금액을 입력받은 뒤 서비스 계층으로 전달하게끔 변경했습니다.

3. 어플리케이션이 기동될 때 파일의 모든 데이터를 ArrayList에 로딩하였고, 실행 중에 저장되는 데이터도 메모리에 저장한 뒤 어플리케이션이 종료될 때 파일에 한 번 동기화하는 방식으로 변경했습니다. 

4.  `CommandLineApplication`도 빈으로 등록하여,  `SpringVoucherServiceApplication`의 코드를 단순하게 변경했습니다.

5. `Message` Enum 타입에 `toString()` 메소드를 추가하여, `View` 에서 `Message` 타입을 받아서 바로 출력할 수 있도록 변경했습니다.  
 
## ✅ PR 포인트 & 궁금한 점 

1. `CommandLineApplication`을 단순화하려고 시도해보았는데 잘 되었는지 궁금합니다.

2. `FileVoucherRepository`에서 파일을 메모리에 캐싱하고, 마지막에 덤프하는 작업을 구현하였는데, 코드에서 아쉬운 점 말씀해주시면 감사하겠습니다!!

3. `VoucherType` Enum class의 책임을 간소화하기 위해 바우처 생성을 `VoucherFactory`에 위임하는 방식으로 변경했습니다. 잘 변경되었는지 궁금합니다 !!

2022-11-10 10:00 UTC, WooSungHwan requested changes
안녕하세요! 기서님! 과제하시느라 고생 많으셨습니다.
코멘트 몇자 남겼으니 확인해주세요!

2022-11-10 12:03 UTC, rlarltj commented on src/main/java/com/programmers/customer/repository/FileCustomerRepository.java
> +public class FileCustomerRepository {
인터페이스를 두고 구현하는 식으로 수정했습니다!

2022-11-10 12:05 UTC, rlarltj commented on src/main/java/com/programmers/customer/repository/FileCustomerRepository.java
> +            }
private void clear(){} 로 메소드 추출했습니다  :-) 감사합니다.

2022-11-10 12:10 UTC, rlarltj commented on src/main/java/com/programmers/voucher/config/VoucherConfig.java
> +        File file = new File(path);
훨씬 좋은 방법인 것 같습니다 감사합니다~!

2022-11-10 12:11 UTC, rlarltj commented on src/main/java/com/programmers/voucher/voucher/FixedAmountVoucher.java
> +        return (discountedAmount < 0) ? 0 : discountedAmount;
Math.max()를 사용해서 깔끔하게 변경했습니다 감사합니다

2022-11-10 12:20 UTC, rlarltj commented on src/main/java/com/programmers/voucher/voucher/VoucherValidator.java
> +        if (type.equals(PercentDiscount)) {
사용자로부터 type을 입력받으면 `VoucherType` Enum에서 선행으로 타입 검사를 실시합니다(아닐 경우 예외 발생). 
따라서 type에 대해 검사하는 로직을 따로 넣지 않았습니다.,
 
VoucherType에 존재하는 타입인지 검사하고, 검사 후 VoucherType을 리턴하기 때문에 일단 `VoucherType Enum`에 두었는데 `Validator`에 두는 것이 더 바람직한지 고민입니다,,

2022-11-10 12:29 UTC, rlarltj commented on src/test/java/com/programmers/voucher/repository/HashMapVoucherRepositoryTest.java
> +    void 맵에바우처저장() {
아 그렇군요 일단 메소드 네이밍이랑 테스트 수정했습니다 감사합니다.

2022-11-10 13:00 UTC, rlarltj commented on src/test/java/com/programmers/voucher/repository/HashMapVoucherRepositoryTest.java
> +class HashMapVoucherRepositoryTest {
repository의 메소드만 테스트하도록 변경했습니다 감사합니다!!

2022-11-10 13:52 UTC, rlarltj commented on src/main/java/com/programmers/voucher/repository/FileVoucherRepository.java
> +                .filter(memoryVoucher -> memoryVoucher.getVoucherId().equals(voucherId))
Map을 사용해 한방에 찾도록 변경했습니다 !!

2022-11-10 14:01 UTC, rlarltj commented on src/main/java/com/programmers/voucher/repository/FileVoucherRepository.java
> +    private final List<Voucher> dumper;
List를 사용한 이유는 `HashMapRepository`가 따로 있기도 하고, 애플리케이션 `실행중`에 저장되는 바우처를 콘솔에 순서대로 출력하고 싶기도 해서 택했는데요 
아무리 봐도 안좋은 선택인 것 같아서 Map으로 변경했습니다!!!

List가 두개였던 이유는 로딩용, 덤프용을 두어서 파일에 저장할 때 덤프용만 동기화를 진행하도록 할 생각이었습니다.
한개만 사용하면서 저장하려는 키 값이 파일에 이미 존재하는지 체크하는 방식이 더 좋은 것 같아서 변경하였습니다!!
감사합니다.

2022-11-10 14:28 UTC, rlarltj commented on src/main/java/com/programmers/voucher/voucher/VoucherType.java
> +    PercentDiscount(List.of("P", "PercentDiscount")),
파일에 `FixedAmount`, `PercentDiscount` 로 저장이 돼서 최초 메모리로 로딩할 때 `VoucherType`을 쉽게 찾아오려고
만들어봤는데 Enum에서 `FixedAmount`, `PercentDiscount` 를 제거하고 ,
로딩할 때 substring(0,1)를 사용해  `F`, `P`로 검색하는 방식으로 변경했습니다 : ))
감사합니다.

2022-11-10 17:51 UTC, rlarltj commented on src/main/java/com/programmers/voucher/repository/FileVoucherRepository.java
> +    }
해당 리포지토리 테스트를 다른 방식으로 시도해봤습니다..!!
감사합니다.

2022-11-11 08:25 UTC, choi1204 reviewed
기서님 고생하셨습니다. 제가 어제 일정이 있어서 코드리뷰가 늦었네요
코멘트 확인하시고 학습하시는데 도움되셨으면 좋겠습니다!

2022-11-11 08:25 UTC, choi1204 commented on src/main/java/com/programmers/voucher/CommandLineApplication.java
> +package com.programmers.voucher;
이 패키지가 voucher 패키지 안에 있는게 맞을지 고민해보시면 좋을 것 같아요

2022-11-11 08:25 UTC, choi1204 commented on src/main/java/com/programmers/voucher/CommandLineApplication.java
> +import static com.programmers.voucher.menu.Message.*;
개인적인 생각이지만 import static의 경우 대다수가 사용하는 즉 함수명만 보아도 어떠한 클래스의 메서드일지 알 수 있을 때 사용하는게 가독성이 좋다고 생각해요.
개인이 만든 클래스에 한해서 import static의 경우 가독성을 떨어뜨리는 요소라고 생각이 드네요

2022-11-11 08:25 UTC, choi1204 commented on src/main/java/com/programmers/voucher/CommandLineApplication.java
> +                view.printMessage(VOUCHER_TYPE_MESSAGE);
이 부분도 메서드화해서 가독성을 좋게 만들면 더 좋을 것 같아요

2022-11-11 08:25 UTC, choi1204 commented on src/main/java/com/programmers/voucher/voucher/VoucherFactory.java
> +
VoucherType = null 로 들어올경우에도 percentVoucher가 생성이 되는데 이 경우도 처리해주시면 좋을 것 같아요

2022-11-11 08:25 UTC, choi1204 commented on src/main/java/com/programmers/voucher/voucher/VoucherValidator.java
> +    public static final int MAX_DISCOUNT_COST = 200000;
validator를 제외하고는 cost말고 amount를 사용하시는데 이런 변수명은 일치시켜주시는게 좋을 것 같아요

2022-11-11 08:25 UTC, choi1204 commented on src/main/java/com/programmers/voucher/menu/Menu.java
> +    private final String menu;
Enum의 열거형 name과 menu 변수의 값이 같아요. 이럴때 추가적인 변수를 만들필요가 없이 name() 메서드로 사용해도 충분해 보여요.

2022-11-11 09:40 UTC, rlarltj commented on src/main/java/com/programmers/voucher/CommandLineApplication.java
> +package com.programmers.voucher;
앞으로 추가할 기능들을 고려하면 분리하는 것이 옳겠네요 감사합니다 !!!

2022-11-11 09:47 UTC, rlarltj commented on src/main/java/com/programmers/voucher/voucher/VoucherValidator.java
> +    public static final int MAX_DISCOUNT_COST = 200000;
변경했습니다 :) 조언 감사합니다 !!

2022-11-11 09:55 UTC, rlarltj commented on src/main/java/com/programmers/voucher/menu/Menu.java
> +    private final String menu;
아 그렇네요 불필요한 변수였던 것 같습니다! 감사합니다 👍

2022-11-11 10:09 UTC, rlarltj commented on src/main/java/com/programmers/voucher/voucher/VoucherFactory.java
> +
null 값 처리하는 로직을 추가했습니다!! 감사합니다

2022-11-11 10:28 UTC, rlarltj commented on src/main/java/com/programmers/voucher/CommandLineApplication.java
> +import static com.programmers.voucher.menu.Message.*;
제가 작성한 코드라 너무 익숙했던 것 같네요!! 리뷰 감사합니다!!!!!

2022-11-17 08:23 UTC, rlarltj commented
멘토님들 안녕하세요!
리뷰해주신 부분들 수정 완료하였습니다!!
감사합니다 :)

2022-11-17 11:29 UTC, merged