[3기-C] 김선호 SpringBoot Part1 Weekly Mission 제출합니다.(2차)
prgrms-be-devcourse/springboot-basic pull request #546
Opened 2022-11-10 10:21 UTC by preferKim

@seung-hun-h @hongbin-dev 

지난 PR에 더해 create/list 커맨드 기능만 우선적으로 구현하였습니다! 이번 리뷰도 잘 부탁드리겠습니다!

# 👩‍💻 요구 사항과 구현 내용 

![image](https://user-images.githubusercontent.com/65555299/201060999-8568f746-6636-4230-a100-ee92e44ca99e.png)

## 커맨드

- [x] 유효하지 않은 커맨드 입력에 대한 예외처리

### create 커맨드

- 바우처 생성 ✅
- 바우처 메모리에 저장 ✅

<br>

- [x] create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
- [x] 어떤 바우처를 생성할 건지 클라이언트가 선택
    - [x] 바우처 입력 가이드 출력
    - [x] 바우처 입력에 대한 유효성 검증
    - [x] 바우처 입력 예외 처리
- [x] FixedAmountVoucher
    - [x] 고정 할인 금액 입력
    - [x] 할인 금액 유효성 검증 (금액 > 0)
    - [x] 바우처 생성
    - [x] 바우처 저장
- [x] PercentAmountVoucher
    - [x] 고정 할인 비율(%) 입력
    - [x] 할인 비율 유효성 검증 (0 <= 비율 <= 100)
    - [x] 바우처 생성
    - [x] 바우처 저장

### list 커맨드

- [x] list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
    - [x] 모든 바우처 조회

## ✅ 피드백 반영사항  

♻️ [1차 PR](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528)이 머지된 이후 피드백을 적용한 내용입니다!

- [Stateful 한 객체를 스프링 빈으로 등록되지 않도록 설정](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528#discussion_r1018864087)
- [어떤 값이 들어와서 예외가 발생했는지 명시](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528#discussion_r1018879149)
- [불필요한 AnnotationConfigApplicationContext 객체 제거](https://github.com/prgrms-be-devcourse/springboot-basic/pull/528#discussion_r1018892831)

## ✅ PR 포인트 & 궁금한 점 

- 최대한 입출력 하는 곳에서 예외처리를 하고 싶었습니다. 적절하게 예외처리가 이루어졌는지 궁금합니다.
- 객체지향적으로 구현하였는지 궁금합니다. 
    - 실제 비즈니스 로직은 각 객체가 갖는 책임을 줄이는데 집중하였고, 반대로 입출력하는 부분은 의도적으로 책임의 크기를 늘렸습니다. 
    - VoucherManager 는 입출력에 관해서는 '절대' 모르게 하고 싶었습니다. 때문에, CommandExecutor의 부담이 많이 커졌습니다. 
        - 사실 CommandExecutor의 책임을 분담하는 클래스를 구현했었는데, 해당 클래스 역시 입출력에 관한 부분을 알게되다 보니 오히려 전체적으로 로직이 복잡해져 이를 단순화하기 위해 오로지 CommandExecutor 객체 혼자 입출력 요청에 대한 책임을 갖게 되었습니다.  
- VoucherCreationFactory는 Voucher를 생성하는 정적 팩토리 메소드를 갖습니다. 정적 팩토리 메소드의 구현이나 사용 등이 어색하지 않은지, 제 3자가 보았을 때 사용 의도가 명확해 보이는 지 궁금합니다.
- @Bean 을 이용하여 등록했던 스프링 빈을 컴포넌트 스캔을 이용한 방식으로 변경하였습니다. 어노테이션 사용이 적절한지 확인해주시면 감사하겠습니다!

2022-11-10 12:44 UTC, seung-hun-h requested changes
안녕하세요 선호님!
패키지도 잘 분리하시고 객체 지향적으로 잘 설계하신 것 같아요.
리뷰 남겼으니 확인 해주세요

#### 최대한 입출력 하는 곳에서 예외처리를 하고 싶었습니다. 적절하게 예외처리가 이루어졌는지 궁금합니다.
- 입출력은 사용자와 직접 상호작용하는 부분이죠. 사용자 친화적인 인터페이스를 만들기 위해서 예외처리를 해야 합니다.
- 하지만 가장 중요한 곳은 도메인입니다. 도메인 클래스는 핵심 비즈니스 로직을 가지고 있기 때문에 여러 군데에서 사용될 수 있어요. 도메인 클래스에 예외 처리를 꼼꼼히 하는 것이 좋아보이네요. 물론 두 군데 모두 하는 것도 좋겠죠

#### 객체지향적으로 구현하였는지 궁금합니다. 실제 비즈니스 로직은 각 객체가 갖는 책임을 줄이는데 집중하였고, 반대로 입출력하는 부분은 의도적으로 책임의 크기를 늘렸습니다.
- 객체지향적으로 잘 설계하신 것 같습니다.
- 입출력 부분을 의도적으로 책임의 크기를 늘렸다고 하신 부분은 이해가 잘 되지 않네요

#### VoucherCreationFactory는 Voucher를 생성하는 정적 팩토리 메소드를 갖습니다. 정적 팩토리 메소드의 구현이나 사용 등이 어색하지 않은지, 제 3자가 보았을 때 사용 의도가 명확해 보이는 지 궁금합니다.
- 기본 생성자의 호출을 막는 부분은 본인의 의사를 제대로 표현한 것 같습니다

@bean 을 이용하여 등록했던 스프링 빈을 컴포넌트 스캔을 이용한 방식으로 변경하였습니다. 어노테이션 사용이 적절한지 확인해주시면 감사하겠습니다!
- 네 잘하셨습니다

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +    @Autowired
스프링 예전 버전(몇 버전인지는 기억이 나질 않네요)에서는 생성자에 `@Autowired`를 붙여줘야만 자동 주입이 됐지만, 지금은 생성자가 하나만 존재한다면 굳이 사용하지 않아도 됩니다.

변화의 과도기에는 사용해도 무방하지만, 최신 버전의 스프링을 사용하는 입장에서는 굳이 애노테이션을 사용할 필요가 있을까 싶네요. 이제는 스프링을 사용하는 많은 사람들이 애노테이션을 사용하지 않아도 된다는 사실을 알거든요. 선호님 생각은 어떠신가요?

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +            commandType.ifPresent(this::executeCommand);
`ioManager.askCommand()`가 Optional을 반환하고 있어 NPE에 대해 고려하지 않아도 되겠군요 👍 
그렇다면 무의미한 지역 변수를 사용하지 않고 

```suggestion
            ioManager.askCommand()
            		.ifPresent(this::executeCommand);
```
이렇게 작성해보는 것은 어떨까요?

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        }
`CommandType`이 if 문에 걸리지 않는 경우에 대해서도 처리해주면 좋겠네요 :)

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +            String prompt = index.incrementAndGet() + BLANK + voucher.getClass().toString();
`toString()`은 생략해도 좋겠네요.
그리고 바우처가 가진 값들이 출력되지 않아서 아쉬운 것 같습니다. 바우처의 값 들도 함께 표현해주면 좋을 것 같아요

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/voucher/MemoryVouchers.java
> +    }
👍 
`Collections.immutableList()`를 사용해보는 것도 좋겠네요

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/voucher/VoucherCreationFactory.java
> +    }
기본 생성자 호출을 막아두셨네요 💯

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/voucher/VoucherType.java
> +                .orElseThrow(IllegalArgumentException::new);
예외 메시지도 함께 던져주면 좋을 것 같아요

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/voucher/model/FixedAmountVoucher.java
> +    }
`amountBeforeDiscount - this.fixedDiscountAmount.getAmount()`이 음수가 될 수도 있지 않을까요?

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +        AtomicInteger index = new AtomicInteger();
`AtomicInteger`를 사용하신 이유가 있나요?

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        this.runningState = new RunningState();
`CommandExecutor`는 싱글턴으로 관리되어 생성자가 한 번만 호출될 것 같네요. 여전히 상태가 공유되고 있는 것 같습니다.

2022-11-10 12:44 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/IOManager.java
> +        return Long.parseLong(inputNumber);
문자열이나 소수 입력에 관한 예외처리가 필요해 보이네요

2022-11-10 15:27 UTC, hongbin-dev requested changes
@preferKim 
안녕하세요 선호님!
미션 구현 잘 해주셨군요..! 패키지나 객체등을 보니, 설계 고민하신부분이 많이 보입니다!

급한대로 우선 코드리뷰부터 남겨드릴께요!

2022-11-10 15:27 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/model/Amount.java
> +        }
throws를 쓰신 이유가 있을까요?

2022-11-10 15:27 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/model/Amount.java
> +    private final long amount;
Amount와 Ratio 객체 좋네요 👍  값 객체에 대해 알아보시면 좋을 것 같아요..ㅎㅎ

2022-11-10 15:27 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/voucher/MemoryVouchers.java
> +    }
👍

2022-11-10 15:27 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/voucher/VoucherManager.java
> +    }
요기도 @Autowired가 들어갔네요. 스프링의 의존성 주입 다른 방법은 없을까요?

2022-11-10 15:27 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/voucher/model/FixedAmountVoucher.java
> +    }
중요한 로직인 만큼 테스트가 있으면 좋겠네요.

2022-11-10 15:27 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/IOManager.java
> +        }
매번 객체를 throw하고, catch한 다음 Optional로 포장하고 있는데요.

`CommandType.of(command)` 이 객체에서 처음부터 Optional을 반환하면, 이런 불필요한 과정이 없어지지않을까요?

2022-11-10 15:27 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        }
이 부분은 controller의 책임일까요? 도메인에서 이런 역할을 해줄 순 없을까요?

2022-11-11 09:50 UTC, seung-hun-h commented
@preferKim 리뷰 내용은 다음 PR에 반영해주세요 머지하겠습니다

2022-11-11 09:50 UTC, merged

2022-11-14 12:40 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +    @Autowired
[Refactor: 불필요한 Autowired 제거](https://github.com/prgrms-be-devcourse/springboot-basic/commit/c180b94e1d3875c9bd5dd294ac197af4e3cbd2da)

♻️ 생성자를 통해 의존관계를 주입받는 것이 자명하기에, 불필요한 Autowired 어노테이션을 제거하였습니다!

찾아보니 스프링 4.3 부터 Autowired 어노테이션을 사용하지 않아도 됨을 알게되었습니다.
또한, 순환참조를 방지하고 테스트 코드 작성이나 불변성등을 보장 받기 때문에 수정자나 필드 주입보다 생성자 주입이 권장되는 것을 알게되었습니다.

➡️ 코드를 작성함에 있어 메서드 명이나 어노테이션 사용 등 조금 더 관용적인 표현에 대해서 찾아보고, 적용해야겠다는 생각이듭니다. 일반적인 프로그래밍 원칙에 벗어나게되면, 아무래도 해당 코드를 읽는 추가적인 리소스가 들어갈 수밖에 없으니까요!

2022-11-14 12:54 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +            commandType.ifPresent(this::executeCommand);
[Refactor(command): 커맨드 입력 예외처리 로직 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/e760ad99892b68bb35fa913890a68d7ad710bd6d)
[Refactor(command): 커맨드 입력을 요청하고 실행하는 로직을 간략화](https://github.com/prgrms-be-devcourse/springboot-basic/commit/4078b608a1dc0fb6ef16c43cb0cb0253096e3550)

 `한 줄에 점을 하나만 찍는다`를 지키고, 코드 한 줄에 하나의 작업만 이루어지는 것이 가독성 면에서 더 좋겠다고 생각하여 의도적으로 개행처리를 하였습니다. 그런데 추천해주신 suggestion을 보니 오히려 이 쪽이 더 자연스럽게 읽히는 것 같아 suggestion처럼 리팩터링하였습니다!
 
또한 `한 줄에 점을 하나만 찍는다` 를 지키는 것과 관련된 `디미터의 법칙`을 찾아보고, 이것이 다른 객체가 가지고 있는 값을 직접참조하는 것을 방지하고 `메시지를 통해 객체가 협력`하기 위한 방법이라고 이해하였습니다. 따라서, 경우에 따라 점을 하나 이상 찍을 수도 있음을 알게되었습니다❗️

2022-11-14 12:59 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        }
[Refactor(command): switch문을 이용하여 커맨드를 실행하도록 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/46ccef2bc0cd2a511aefb8071b6076260d553247)

♻️ 향상된 switch 문을 이용하여 커맨드를 실행하도록 변경하였습니다.

if, switch 문을 사용하는 것 외에,
CommandType Enum의 각 열거 상수들이 어떤 행동을 취해야 할지를 정의한 함수형 인터페이스 필드를 갖게할까도 고려해보았습니다.
그러나 CommandExecutor 객체에서 각 커맨드에 따라 행동을 분기하는 것이 맞다고 판단하여, 우선적으로 switch문을 이용하여 분기하도록 변경하였습니다.

2022-11-14 17:00 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/voucher/VoucherType.java
> +                .orElseThrow(IllegalArgumentException::new);
[Refactor(exception): 잘못된 바우처 타입 입력에 대한 예외처리 로직 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/2e7b9de9f3e54bba8c2629cdeb881b47f6005cd2)

♻️ 커스텀 예외를 이용하여 예외 메시지도 함께 던져주는 방식으로 수정해봤습니다! 
- try catch 문을 사용하지 않기 위해 리턴타입을 Optional로 반환하도록 변경하였는데, 리턴 받는 쪽에서 Optional.isEmpty() 를 사용하여 Optional 객체 안에 값이 없으면 입출력 객체에게 예외가 발생했다고 알려주는 식으로 했습니다. 다만 이렇게 변경하고 나니까 오히려 try catch가 가독성이 더 좋아 보이네요😂
- ❓예외를 VoucherType Enum 에서 발생시키는 편이 좋았을지 궁금합니다!

2022-11-14 17:59 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/voucher/model/FixedAmountVoucher.java
> +    }
[Refactor(exception): 할인 이전의 금액이 금액이 고정 할인 금액보다 작은 경우 예외 추가](https://github.com/prgrms-be-devcourse/springboot-basic/commit/46fb35935e658ca208c4b83ee5eaaf710785eec2)

♻️ 매개변수가 유효하지 않으면 `IllegalStateException` 을 발생시키는 쪽으로 수정해봤습니다!

➡️ `IllegalArgumentException` 과 `IllegalStateException`에 대해서 더 찾아본 결과, 지금과 같이 부적절한 인수를 전달 받은 경우는 `IllegalArgumentException` 이 맞겠네요. 이 부분은 추후에 변경하도록 하겠습니다!

2022-11-14 18:03 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        if (commandType.is(CommandType.EXIT)) {
https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021497745
해당 코멘트에 피드백 적용사항 남겨두었습니다!

2022-11-14 18:03 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        }
https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021497745
해당 코멘트에 피드백 적용사항 남겨두었습니다!

2022-11-14 18:12 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        ioManager.notifyVouchers(vouchers);
[Rename(io): 바우처 정보를 출력하는 메서드의 이름을 더 분명하게 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/bc2f86b6c7a00e9ba6b4c39442fbe102c1c16a42)

♻️ 더 명확한 메서드명을 갖도록 변경하였습니다. 
기존의 IOManager 에 정의된 메서드명의 스타일과 맞추기 위해서 약간 억지로 맞춘 느낌이었는데, 역시 직관적인 이름이 좋군요? 🤔

2022-11-14 18:14 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/model/Amount.java
> +        }
[Refactor: 불필요한 throw문 삭제](https://github.com/prgrms-be-devcourse/springboot-basic/commit/4ee445603ff5326f365b21b990f6b0d5fb017345)

중간에 문법을 헷갈렸습니다... 🥲

2022-11-14 18:17 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/model/Amount.java
> +    private final long amount;
[Refactor: VO를 만족시키기 위한 equals&hashCode 오버라이딩](https://github.com/prgrms-be-devcourse/springboot-basic/commit/55e1a44609002ba907456bcef7cbc6998b8f5cbb)

♻️ VO에 대해 찾아보고, 논리적 동등성을 만족시키기 위해 equals 와 hashCode 메서드를 오버라이딩하였습니다!

2022-11-14 18:18 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/voucher/VoucherManager.java
> +    }
https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021476936

해당 코멘트로 남겼습니다!

2022-11-14 18:20 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/voucher/model/FixedAmountVoucher.java
> +    }
https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021888793

해당 코멘트로 남겼습니다!

2022-11-14 18:29 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/io/IOManager.java
> +        }
[Refactor(command): 커맨드 입력 예외처리 로직 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/e760ad99892b68bb35fa913890a68d7ad710bd6d)
[Refactor(command): 커맨드 입력을 요청하고 실행하는 로직을 간략화](https://github.com/prgrms-be-devcourse/springboot-basic/commit/4078b608a1dc0fb6ef16c43cb0cb0253096e3550)

♻️ `CommandType.of(command)` 에서 Optional을 반환하고, 입력 커맨드를 `CommandType` 으로 변경하는 과정에서 예외 발생시 별도의 커스텀 예외를 통해 처리하도록 하였습니다. 
- 부득이하게 try catch 를 두 번 사용하여 예외처리를 했는데, 적절하게 처리가 이루어졌는지 모르겠습니다. 
- 사용자 관점에서 '잘못된 커맨드를 입력해도 프로그램이 계속 유지'되도록 하려했습니다.
-  단순히 `CommandType.of(command)` 에서 예외를 던지고 해당 메서드를 호출하는 곳에서 try-catch 를 사용하여 처리하는 편이 좋았을까요❓

2022-11-14 18:48 UTC, preferKim commented
@seung-hun-h @hongbin-dev 

세심한 리뷰 너무 감사드립니다 😭😭😭
피드백 적용하여 현재 PR에 피드백 적용한 커밋과 함께 코멘트로 남겼습니다. 확인해주시면 감사하겠습니다!

2022-11-17 15:31 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +        ioManager.notifyVouchers(vouchers);
notifyVouchers를 보니 알림을 보내는건가? 이런 생각이 들었어요.
개인적으로 변경하니 더 이해하기 좋은 것 같아요.

2022-11-17 15:34 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/IOManager.java
> +        }
`사용자 관점에서 '잘못된 커맨드를 입력해도 프로그램이 계속 유지'되도록 하려했습니다.`

catch부분은 이해가지만, 현재 메서드가 not null을 확정하는데, 다시 optional으로 반환하는게 어색하긴하네요.

코드내에서 nullable은 빠르게 제거하는게 좋습니다.

2022-11-17 15:35 UTC, hongbin-dev commented
@preferKim 선호님! 코멘트 남겨봤어요