[3기-C] 장영지 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #554
Opened 2022-11-11 04:48 UTC by youngjijang

## 📌 과제 설명 

- create : 바우처를 생성합니다.
- list : 바우처 리스트를 출력합니다.
- blacklist : 블랙리스트를 출력합니다.
- exit : 프로그램을 종료합니다.

## 👩‍💻 요구 사항과 구현 내용 

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

<br>

## ✅ 피드백 반영사항 

남겨주신 피드백 중심으로 수정하였습니다!

**1. getbeen이 아닌 생성자 주입으로 호출
2. findAll 메소드는 Map이 아닌 List로 가공하여 리턴
3. enum의 역할 줄이기 -> voucherCreate 메소드 분리
4. blacklist 메소드 Vouchercontroller에서 CustomerService로 분리
5. Repository, Contoller 역활 구분을 위해 Component 어노테이션으로 변경후 이름 명시**

테스트 코드는 아직 완성이 덜 되었습니다.😅 완성되는대로 다시 코멘트 남기겠습니다!

## ✅ PR 포인트 & 궁금한 점 

리뷰해주신 내용을 제가 올바르게 이해하고 수정한 것인지 궁금합니다🙂

VoucherTyper enum의 역할을 분리하기 위해 voucherCreate 메소드를 Service단에서 구현하려고 하였으나, 그럴경우 FileVoucherRepository와 순환참조가 발생하여 VoucherProduction이라는 바우처 생산을 위한 Class를 따로 구현하였습니다! 억지스럽게 Class를 나눈것 같은 느낌이 들어 다른 구현 방법이 있을지 궁금합니다..!

(merge가 꼬여서 commit 이력이 날라갔습니다..😅)

2022-11-11 05:24 UTC, WooSungHwan requested changes
안녕하세요! 영지님! 과제하시느라 고생 많으셨습니다.
못다한 테스트코드는 마저 작성해주시고 코멘트 몇자 남겼으니 해당 내용도 확인부탁드립니다!

2022-11-11 05:24 UTC, WooSungHwan commented on src/main/java/com/program/voucher/VoucherController.java
> +    private final Output output;
이 두가지 기능이 아직 하나의 인터페이스로 추상화가 되지 않았네요.

2022-11-11 05:24 UTC, WooSungHwan commented on src/main/java/com/program/voucher/VoucherController.java
> +public class VoucherController implements Runnable {
근데 사실 이게 VoucherController라면...
VoucherService만 의존하고 있어야하지 않을까요??

지금 Menu도 Voucher라는 Controller에 있다고 보기에도 애매하고

여기서 개념을 위로 확장을 해보면
일반 스프링에서 XXXController이러한 컨트롤러에 접근하기전에 FrontController라고 불리는 DispatcherServlert이라는 과정을 통해 uri handlermapping을 진행하게 됩니다. 

사용자의 http 요청을 적절한 controller로 쏴주는건데

menu라는 command를 받은게 적절한 controller로 보내주어야 하는 과정이라고 봤을때

해당 클래스는 SystemController 의 이름이 적절할 것이고 아래의 createVoucher, viewVoucherList, viewBlackListCustomer
private 메소드들은 VoucherController에 선언되어 각자의 service를 주입받는 형태가 되는게 조금더 자연스러웠던 것 같습니다.

이 부분 어려울수도 있으니 이해가 안된다면 디엠주세요. 그리고 이 내용은 영지님꺼 리뷰할때 막 느낀 부분이라서 다른분들께도 공유해주세요 ^_^

2022-11-11 05:24 UTC, WooSungHwan commented on src/main/java/com/program/voucher/model/Console.java
> +public class Console implements Input, Output {
이거 조금 바뀌어야될 부분이..
Console이라는 Interface가 있고 Console 구현체 안에 Input과 Output을 사용하는 구조로 바꿔보시겠어요?
게다가 scanner라는 것을 외부 라이브러리 생각했을 때 별도의 다른 입출력을 사용하게 된다면 변화에 매우 취약하기 때문에

interface Console -> 콘솔 기능 명세
class ScannerConsole implements Console -> scanner 콘솔 기능 구현
interface Input -> 입력 기능 명세
interface Output -> 출력 기능 명세
class ScannerInput implements Input -> scanner를 이용한 입력기능 구현
class ScannerOutput implements Output -> 출력 기능 구현.

가장 이상적인 것은 위의 클래스 구조가 생각이 납니다. 한번 적용해보시겠어요?

2022-11-11 05:24 UTC, WooSungHwan commented on src/main/java/com/program/voucher/model/VoucherType.java
> +                .filter(type -> type.inputType.equals(symbol) || type.stringType.equals(symbol))
저는 항상 추천드리는게
Objects.equals 메소드의 사용을 권장드립니다. 명확히 어떤 컬럼과 어떤 컬럼을 비교하는지 보이기도 하고 NPE에 취약하지도 않기때문입니다.

2022-11-11 05:24 UTC, WooSungHwan commented on src/main/java/com/program/voucher/service/VoucherProduction.java
> +public class VoucherProduction {
얘가 팩토리였군요. 보통 통상적으로 xxxFactory라는 이름을 씁니다.
팩토리 어쩌구 디자인 패턴하고는 동명이인이니 헷갈리지는 마시고용.

2022-11-11 05:24 UTC, WooSungHwan commented on src/main/java/com/program/voucher/service/VoucherProduction.java
> +        System.out.println(voucherType);
remove plz.

2022-11-11 05:24 UTC, WooSungHwan commented on src/main/java/com/program/voucher/service/VoucherService.java
> +        this.voucherProduction = voucherProduction;
팩토리를 주입해주는 모습 보기 좋네요 ㅎㅎ 어떤가요? 조금은 voucher라는 모듈의 응집도가 올라간 느낌이 들지 않으시나요?? 역할과 로직의 분리가 가장 잘 되어있는 것 같습니다.

2022-11-11 05:24 UTC, WooSungHwan commented on src/test/java/com/program/voucher/model/FixedAmountVoucherTest.java
> +                () -> assertThrows(IllegalArgumentException.class, () -> new FixedAmountVoucher(UUID.randomUUID(), 10000000)));
이거 3개를 제외한 나머지 테스트는 필요없어보입니다. 일반적으로 테스트코드는 비즈니스로직에 의한 테스트코드와 기능이 잘 돌아가는지에 대한 테스트코드가 있는데요. 우선은 비즈니스 로직에 대한 테스트코드를 완성하고 의심이 되는 부분에 한에서 기능에 대한 테스트 코드를 작성하게 될 가능성이 매우 높습니다.

따라서 지금은 Fixed에 대한 비즈니스 로직에 대한 테스트만 의미가 있습니다.

2022-11-11 05:24 UTC, WooSungHwan commented on src/test/java/com/program/voucher/model/PercentDiscountVoucherTest.java
> +        assertAll("FixedAmountVoucher creation",
위의 fix 테스트와 일치하는 내용입니다.

2022-11-11 05:24 UTC, WooSungHwan commented on src/test/java/com/program/voucher/repository/FileVoucherRepositoryTest.java
> +class FileVoucherRepositoryTest {
이건뭔가요?

2022-11-11 05:24 UTC, WooSungHwan commented on src/test/java/com/program/voucher/repository/MemoryVoucherRepositoryTest.java
> +class MemoryVoucherRepositoryTest {
이건 뭔가용?

2022-11-11 08:50 UTC, choi1204 reviewed
영지님 과제하시느라 고생하셨습니다.
의도하지는 않았지만 코멘트 내용이 전부 코드스타일 관련 내용이네요. 코드스타일도 신경쓰시면 더 좋으실 것 같아요

2022-11-11 08:50 UTC, choi1204 commented on src/main/java/com/program/voucher/VoucherController.java
> +        while (true) {
while (종료조건) 으로 변경하시면 더 좋으실 것 같아요

2022-11-11 08:50 UTC, choi1204 commented on src/main/java/com/program/voucher/service/CustomerService.java
> +        var resource = applicationContext.getResource(blackListFilePath);
이 부분에만 var를 적용한 이유가 있을까요?

2022-11-15 13:54 UTC, youngjijang commented on src/main/java/com/program/voucher/service/CustomerService.java
> +        var resource = applicationContext.getResource(blackListFilePath);
앗 특별히 없습니다ㅎㅎ 테스트 코드에서만 var로 통일해 봤습니다!

2022-11-15 14:04 UTC, youngjijang commented
SpringBoot Part1 2차 리뷰 요청드립니다❗️

1. Controller 클래스를 SystemController 변경하여 각각의 controller를 주입 받도록 수정하였습니다! 팀 미팅때 console부분도 SystemController에서 제외되면 좋을 것 같다고 피드백 주셨는데 그 부분까지는 반영하지 못했습니다. service별 io부분은 각각의 controller로 옮길 수 있을 것같은데 메뉴에 대한 io를 어떤 식으로 처리해야될지 잘모르겠네요🥲

2. 중복이 없는 선에서 테스트 코드를 짜봤는데 부족한 부분이 있다면 다시 말씀해주시면 감사하겠습니다~!
![image](https://user-images.githubusercontent.com/100327413/201938866-49dcc305-2319-419b-9117-c430df89cd2d.png)

2022-11-18 03:02 UTC, merged