[3기-C] 정찬미 SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #560
Opened 2022-11-11 13:06 UTC by tinajeong

리뷰 잘 부탁드립니다 감사합니다! :)

## 📌 과제 설명 
사용자의 콘솔 입력 기반으로 실행되는 어플리케이션입니다.
4가지 명령어가 있으며, 프로파일(local, dev)에 따라 바우처 레포지토리가 분리되어 있습니다.

```shell
=== Voucher Program ===
Type exit to exit the program.
Type create to create a new voucher.
Type list to list all vouchers.
Type blacklist to list all blacklisted customer
```

## 👩‍💻 요구 사항과 구현 내용 
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)

- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ 피드백 반영사항  
- [x] 어플리케이션 실행시 `getBean` 호출 방식 제거하기
- [x] Voucher 추상 클래스로 변경하고 메소드는 자식 클래스에서 구현하도록 변경하기. 
- [x] `private boolean isAppRunning;`은 제거하고 지역변수로 사용하기. 
- [x] domain 클래스에서는 로거 사용하지 않기. (필요하다면 Service에서).
- [x] RuntimeException이 아닌 Custom Exception 사용하기.
- [x] property 사용시 `@ConfigurationProperties` 클래스 정의해 사용하기.
- [x] `VoucherService`의 `createVoucher`에서 객체 early return 하는 방식으로 변경하기.

## ✅ PR 포인트 & 궁금한 점 
- stop 액션을 강제하기 위해 `CommandLineIO` 인터페이스로 `Input`과 `Output` 클래스를 묶었는데 해당 활용이 적절한지
- 지나치게 책임이 과중하거나, 복잡도가 높은 코드가 없는지
- `VoucherChoiceDTO`를 받아들일때, 보여줄 때 모두 사용했는데 DTO가 받아들일 때도 사용되는 경우가 있는지..?

2022-11-11 13:11 UTC, tinajeong commented on src/main/java/org/prgms/springbootbasic/domain/VoucherChoiceDTO.java
> +public class VoucherChoiceDTO {
`config` 패키지에서 record를 사용했으니 일관성있게 record로 변경하는 것이 좋을까요?

2022-11-11 13:12 UTC, tinajeong commented on src/main/java/org/prgms/springbootbasic/repository/FileVoucherRepository.java
> +                bufferedWriter.write(voucher.getUuid()+","+voucher.getVoucherType()+","+voucher.getAmount()+"\n");
`write` 할때 이런식으로 append해서 넣어주는 것이 적절할지 궁금합니다!

2022-11-15 01:49 UTC, WooSungHwan requested changes
찬미님 과제하시느라 고생하셨습니다! 
리뷰가 많이 늦어져서 죄송합니다 ㅠㅠ 코멘트 몇자 남겼으니 확인 부탁드립니다!

2022-11-15 01:49 UTC, WooSungHwan commented on src/main/java/org/prgms/springbootbasic/app/CommandLineApplication.java
> +        }
이 부분이 이제 어제 말한 내용인데

CommandLineApplication 자체는 유저의 Command만 해석해서 Voucher든 Customer든 적절한 Controller로 전달해주면 될 것 같습니다 ㅎㅎ

2022-11-15 01:49 UTC, WooSungHwan commented on src/main/java/org/prgms/springbootbasic/config/FileBlackListConfig.java
> +public record FileBlackListConfig(String fileName){
오!! record가 어떻게 컴파일되는지도 한번 보시면 좋을 것 같아요~

2022-11-15 01:49 UTC, WooSungHwan commented on src/main/java/org/prgms/springbootbasic/domain/VoucherChoiceDTO.java
> +public class VoucherChoiceDTO {
dto 같은 애들이 record로 처리하기 좋아요~

2022-11-15 01:49 UTC, WooSungHwan commented on src/main/java/org/prgms/springbootbasic/repository/FileVoucherRepository.java
> +                bufferedWriter.write(voucher.getUuid()+","+voucher.getVoucherType()+","+voucher.getAmount()+"\n");
적절한것 같습니다만. 이 클래스에서는 나무보다 숲을 봐야합니다.

2022-11-15 01:49 UTC, WooSungHwan commented on src/main/java/org/prgms/springbootbasic/repository/FileVoucherRepository.java
> +public class FileVoucherRepository implements FileRepository, VoucherRepository {
전체적으로 FileVoucherRepository를 봤을때,
현재 VoucherRepository, FileRepository를 둘다 구현하는 부분이 기능구현에 너무 초점이 맞춰져 있다고 생각이 들어요.

사실 initFile이란 메소드가 이 클래스 내의 생성자에서 실행되기 위해서 FileVoucherConfig 요것도 주입하게 되었잖아요?
repository는 데이터 엑세스 layer일 뿐이지 데이터를 직접 불러올 수 있을만한 책임을 가졌다고 생각하면 안될것 같아요.
우리가 JPA repository 하나 실행했다고 db전체를 접근할 수 있는건 아니잖아요? 유기적으로 연결된 프레임워크 내에서만 동작하고 있을 뿐이죠. 헷갈리면 안되는게 이 repository는 data access Layer일 뿐이지 직접 데이터를 불러들이는 곳은 아니라는거..!

그렇기에 불필요한 FileVoucherConfig의 주입이 필요했고 그 책임을 다른 클래스로 분리한다면? 어떨까요?

예를 들어, preDestory와 init을 분리해보면 좋을 것 같아요!

2022-11-15 01:49 UTC, WooSungHwan commented on src/main/java/org/prgms/springbootbasic/service/VoucherService.java
> +        if(voucherChoiceDTO.getVoucherType().equals(VoucherType.PERCENT)) {
enum은 굳이 equals 비교하지 않아도 싱글톤이기 때문에 == 비교를 해도 됩니다.

2022-11-15 01:49 UTC, WooSungHwan commented on src/main/java/org/prgms/springbootbasic/service/VoucherService.java
> +        if(voucherChoiceDTO.getVoucherType().equals(VoucherType.PERCENT)) {
근데 이부분은 if-else보다는 switch가 더 나을 것 같네요.

2022-11-15 05:50 UTC, tinajeong commented on src/main/java/org/prgms/springbootbasic/config/FileBlackListConfig.java
> +public record FileBlackListConfig(String fileName){
javap 명령어를 통해 확인해보니, record가 final인 data class로 자동변환되는 모습을 볼 수 있었습니다!
1. 생성자가 내부적으로 만들어지고
2. getter는 필드이름으로, 
3. Object의 equals(), hashCode(), toString() 메소드를 상속받는 걸 눈으로 보니 더 이해가 확실해지네요 :) 

```java
public final class RecordSample extends java.lang.Record {
  public RecordSample(java.lang.String);
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Record."<init>":()V
       4: aload_0
       5: aload_1
       6: putfield      #7                  // Field name:Ljava/lang/String;
       9: return

  public final java.lang.String toString();
    Code:
       0: aload_0
       1: invokedynamic #13,  0             // InvokeDynamic #0:toString:(LRecordSample;)Ljava/lang/String;
       6: areturn

  public final int hashCode();
    Code:
       0: aload_0
       1: invokedynamic #17,  0             // InvokeDynamic #0:hashCode:(LRecordSample;)I
       6: ireturn

  public final boolean equals(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: invokedynamic #21,  0             // InvokeDynamic #0:equals:(LRecordSample;Ljava/lang/Object;)Z
       7: ireturn

  public java.lang.String name();
    Code:
       0: aload_0
       1: getfield      #7                  // Field name:Ljava/lang/String;
       4: areturn
}
```

2022-11-15 05:58 UTC, tinajeong commented on src/main/java/org/prgms/springbootbasic/domain/VoucherChoiceDTO.java
> +public class VoucherChoiceDTO {
감사합니다 수정했습니다 ~

2022-11-15 05:59 UTC, tinajeong commented on src/main/java/org/prgms/springbootbasic/repository/FileVoucherRepository.java
> +                bufferedWriter.write(voucher.getUuid()+","+voucher.getVoucherType()+","+voucher.getAmount()+"\n");
밑에서 말씀하신 것처럼 Repository 기능분리가 필요할 것 같네요! 🧐

2022-11-15 06:02 UTC, tinajeong commented on src/main/java/org/prgms/springbootbasic/service/VoucherService.java
> +        if(voucherChoiceDTO.getVoucherType().equals(VoucherType.PERCENT)) {
덕분에 enum을 통한 싱글톤 구현방식이 리플렉션을 통한 생성을 막아주고, 직렬화가 간편하다는 측면세 좋다는 것도 알았네요 ! 수정했습니다 :)

2022-11-15 08:42 UTC, tinajeong commented on src/main/java/org/prgms/springbootbasic/repository/FileVoucherRepository.java
> +public class FileVoucherRepository implements FileRepository, VoucherRepository {
그렇네요! 사실 과제하면서도 파일유틸을 따로 빼야하나 고민을 많이했습니다. FileManipulator 클래스를 만들어 파일 직접 접근하는 책임을 분리하도록 수정했습니다 :) repository 클래스가 훨씬 깔끔해져서 좋습니다

2022-11-19 03:55 UTC, choi1204 reviewed
찬미님 수고하셨습니다.
저번주부터 제가 정신이 없어서 코드리뷰가 늦어져서 죄송합니다
코멘트 확인해보시고 관련 내용 학습하시고 도움되시면 좋겠습니다

2022-11-19 03:55 UTC, choi1204 commented on src/main/java/org/prgms/springbootbasic/service/VoucherService.java
> +        if(voucherChoiceDTO.voucherType() == VoucherType.PERCENT) {
똑같은 값을 비교할때는 if보다는 switch가 더 적절할 것 같아요.
if 와 switch의 차이도 학습해보시면 좋을 것 같습니다.

2022-11-19 03:55 UTC, choi1204 commented on src/main/java/org/prgms/springbootbasic/cli/Command.java
> +    EXIT("exit"),
enum의 command값과 name의 값이 비슷해서 name의 값을 바로 쓰셔도 좋을 것 같아요

2022-11-19 03:55 UTC, choi1204 commented on src/main/java/org/prgms/springbootbasic/cli/CommandLine.java
> +        if (voucherType.equals(VoucherType.FIXED)) {
Enum의 경우 equlas 보다 == 비교를 선호하시는 개발자 분들이 많습니다.
두가지의 방법은 코드스타일의 차이여서 크게 상관은없습니다.
다만 equals를 사용할 때는 VoucherType.FIXED.equals(voucherType)과 같이 상수를 앞쪽으로 두어야 NPE를 방지하기에 더 좋을 것 같습니다
그리고 이 부분도 switch를 적용하는게 더 좋을 것 같네요

2022-11-19 03:55 UTC, choi1204 commented on src/main/java/org/prgms/springbootbasic/service/VoucherService.java
> +        if(voucherChoiceDTO.voucherType() == VoucherType.PERCENT) {
이 부분은 팩토리 클래스를 만들어도 좋을 것 같아요

2022-11-21 01:04 UTC, merged