[3기-C] 서예원 SpringBoot Part1 Weekly Mission제출합니다.
prgrms-be-devcourse/springboot-basic pull request #563
Opened 2022-11-13 12:18 UTC by yewon9609

## 📌 과제 설명 
- Pofile(dev, local) 설정 
- 회원 블랙리스트 조회 기능 구현
- 요구사항에서는 블랙리스트 조회만 써져있어서 CustomerBlackListFileMemory 가 Memory 를 implement하지 않았습니다 

## 👩‍💻 요구 사항과 구현 내용
(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ PR 포인트 & 궁금한 점 
안녕하세요 앨런님 승훈님 ! 이번 pr도 잘 부탁드립니당 !☺️
- springMVC모델은 언제쯤 도입하면 될까요?
- 가독성이 좀 떨어지거나 한 클래스에서 너무 많은 역할을 하는 클래스가 있을까요?
이번 pr도 잘 부탁드립니당 !☺️

2022-11-14 15:30 UTC, hongbin-dev requested changes
> springMVC모델은 언제쯤 도입하면 될까요?

어떤 문제때문에 그럴까요?! 네이밍 짓기가 어려울까요?

>가독성이 좀 떨어지거나 한 클래스에서 너무 많은 역할을 하는 클래스가 있을까요?

코멘트로 남겨봤습니다!

2022-11-14 15:30 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerBlackListFileMemory.java
> +      reader.close();
FileReader도 닫아야하지않을까요!?

try with resources를 활용해볼까요?
https://www.baeldung.com/java-try-with-resources

2022-11-14 15:30 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/VoucherFileMemory.java
> +    writer.write(voucher.toString());
toString()의 목적이 무엇일까요?

https://velog.io/@ozragwort/toString-%EB%B9%84%EC%A6%88%EB%8B%88%EC%8A%A4-%EB%A1%9C%EC%A7%81%EA%B3%BC-UI-%EB%A1%9C%EC%A7%81%EC%9D%98-%EB%B6%84%EB%A6%AC

한번 읽어보시면 좋을 것 같아요!
-> 값을 꺼내서 저장하면 좋을 것 같아요.

2022-11-14 15:30 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/Memory.java
> +}
인터페이스가 변경됐군요! 그대로 유지할 순 없었을까요?

2022-11-14 15:30 UTC, hongbin-dev commented on src/main/resources/application.yml
> +    file-path: src/voucher_memory.csv
dev 프로파일 환경에서는 데이터를 인메모리에 저장하는걸로 보이는데요. (VoucherInMemory)

파일관련된 정보는 없어도 되지않을까요? (file-path... ) 이런

2022-11-14 15:30 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/VoucherFileMemory.java
> +
throws로 계속 던지게되어, 개인적으로 코드가 더러워지고 있다고 생각하는데요. 
IOException을 unchecked exception으로 전환해보는건 어떨까요?

2022-11-15 03:28 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/CustomerBlackListFileMemory.java
> +      reader.close();
앗 fileReader닫아줄 생각을 못했네요

2022-11-15 03:30 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/VoucherFileMemory.java
> +    writer.write(voucher.toString());
앗 toString()을 View에 쓰기위해 사용하지 말자라고 하셨었는데 ㅠㅠㅠㅠ 저도모르게 그냥 편하게 가려고 했더니 이런..결과가... 
수정하겠습니다!!!

2022-11-15 03:35 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/Memory.java
> +}
사실 원래 List<Voucher>였는데요 나중에 CustomerMemory를 만들었을 때 이 interface를 재사용할지 말지 고민하다가 일단 String으로 변경했었는데요 (Voucher도 Customer도 String으로 저장이 가능하니까요! )... 다시살펴보니 save도 voucher타입이니 Voucher Memory용 인터페이스, CustomerMemory용 인터페이스를 따로 납둬야겠군요..

2022-11-15 03:37 UTC, yewon9609 commented on src/main/resources/application.yml
> +    file-path: src/voucher_memory.csv
앗...처음엔 그렇게 했었는데 이상하게 콘솔이 안떠서 저 정보를 local환경과 똑같이 넣어주니까 또 돌아가더라구요...ㅠㅠ
아마 제가 뭔가 설정을 잘못했나봅니다 찾아서 수정할게요 !

2022-11-15 03:46 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/VoucherFileMemory.java
> +
앗 그런방법이 있었네요 ! 해보겠습니다 ✍🏻

2022-11-15 05:10 UTC, yewon9609 commented on src/main/resources/application.yml
> +    file-path: src/voucher_memory.csv
이유를 찾았습니다! 수정하겠습니닷 ~!

2022-11-15 07:07 UTC, seung-hun-h reviewed
안녕하세요 예원님 리뷰 간단하게 남겼으니 확인해주세요!

2022-11-15 07:07 UTC, seung-hun-h commented on src/main/java/org.prgrms/console/Console.java
> +  public void printVoucherList(List<String> voucherList) {
`List<Voucher>`에서 `List<String>`으로 타입을 변경한 이유가 있나요?

2022-11-15 07:07 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/CustomerBlackListFileMemory.java
> +  public CustomerBlackListFileMemory(@Value("${file.customer.file-path}") String filePath) {
생성자로 `filePath`를 주입 받는거 좋네요 👍

2022-11-15 07:07 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/VoucherInMemory.java
> +    voucherMemory.put(voucher.getVoucherId(), voucher.toString());
바우처의 `toString` 값을 저장하신 이유가 있나요?

2022-11-15 07:36 UTC, yewon9609 commented on src/main/java/org.prgrms/console/Console.java
> +  public void printVoucherList(List<String> voucherList) {
csv파일이  '몇 가지 필드를 쉼표(,)로 구분한 텍스트 데이터 및 텍스트 파일'을 의미하는지 모르고
애초에 저장을 보기 좋게하겠다고 Id : ~~~~, Amount:~~~이런형식으로 저장하다보니 
꺼낼때 쉽지가 않아서 String으로 변경했었습니다. 하지만 나중에 update기능을 생각해보면 voucher타입으로 변경하는게 맞겠네요..!
수정하겠습니다!

2022-11-15 07:36 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/Memory.java
> +}
csv파일이  '몇 가지 필드를 쉼표(,)로 구분한 텍스트 데이터 및 텍스트 파일'을 의미하는지 모르고
애초에 저장을 보기 좋게하겠다고 Id : ~~~~, Amount:~~~이런형식으로 저장하다보니 
꺼낼때 쉽지가 않아서 String으로 변경했었습니다. 하지만 나중에 update기능을 생각해보면 voucher타입으로 변경하는게 맞겠네요..!
수정하겠습니다!

2022-11-15 07:39 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/VoucherInMemory.java
> +    voucherMemory.put(voucher.getVoucherId(), voucher.toString());
toString 포맷을 클라이언트입장에서 보기좋게 해놔서 toString()을 써줬었던 거였는데 toString()의 사용법에도 맞지 않을 뿐더러 나중에 update할때 쉽지 않겠네요.. 수정하겠습니다 !

2022-11-15 10:02 UTC, seung-hun-h commented on src/main/java/org.prgrms/console/Console.java
> +  public void printVoucherList(List<String> voucherList) {
넵 `String`보다는 바우처를 출력하겠다는 의미로 `Voucher`를 명시하는 것이 좋아보이네요.
그리고 출력 메서드 안에서 본인이 원하는 형식으로 Voucher의 값을 꺼내서 출력하면 되지 않을까요?

2022-11-16 14:45 UTC, hongbin-dev approved these changes
예원님 고생하셨습니다! 
요기까지 마무리할게요~ @yewon9609

2022-11-16 14:45 UTC, hongbin-dev commented on src/main/resources/logback.xml
> +    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
👍

2022-11-16 14:45 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/VoucherFileMemory.java
> +          + voucher.getVoucherAmount().getValue() + System.lineSeparator());
바우처 이름 필드가 추가되어서 "신규, 기존 회원 할인" 이라는 값이 들어가면 문제가 발생할 수도 있겠네요.

이 부분은 지금 반영하지 않으셔도 되고, 고민해보시면 좋을 듯 합니다.

2022-11-16 14:57 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/VoucherFileMemory.java
> +  public Voucher extractVoucherFromFile(String[] lineArray) {
LIst<String>으로 수정하겠습니당 !

2022-11-17 07:33 UTC, merged