feat: 기능 개발
prgrms-be-devcourse/springboot-basic pull request #567
Opened 2022-11-13 17:47 UTC by dlxortmd987

## 📌 과제 설명 
- 파일에 저장하는 기능 구현
- 블랙리스트 조회 기능 구현

## ✅ PR 포인트 & 궁금한 점 
- file에서 stream으로 list를 가져오는데, 이 부분을 맞게 짰는지 궁금합니다!

2022-11-15 04:17 UTC, hongbin-dev requested changes
택승님 수고하셨습니다!

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    private static Logger logger = LoggerFactory.getLogger(FileVoucherManager.class);
요기도 final 붙으면 좋겠군요 ㅎㅎ

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
파일을 상태로 갖으면 멀티쓰레드 환경에서 문제가 발생할 수 있지않을까요?

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
try-with-resources 👍

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +@Repository
개인적으로는 profile을 하나를 더 관리하는것보단, default active profile를 local로 쓰는편이긴 해요 ㅎㅎ (profile이 늘어나면 관리할 포인트가 많아집니다.)

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static final String FILE_PATH = "src/main/resources/vouchers.csv";
여기도 final 붙일 수 있겠네요.

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static void write(Voucher voucher, File file) {
요기 static으로 하신 이유가 있나요?

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    }
인터페이스와 구현 잘 해주셨네요!

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +        }
re-throw와 log를 같이사용하는건 안티패턴입니다. 소나큐브 참고링크 올릴게요!

https://rules.sonarsource.com/java/RSPEC-2139

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/resources/application.yml
> +    active: local
기본은 local profile을 사용하는군요 👍

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/resources/customer_blacklist.csv
> +4, 연가시
😱

2022-11-15 04:17 UTC, hongbin-dev commented on src/main/resources/logback.xml
> +        </filter>
이렇게되면 ERROR도 저장이 될까요?

2022-11-15 04:17 UTC, hongbin-dev commented
> file에서 stream으로 list를 가져오는데, 이 부분을 맞게 짰는지 궁금합니다!

맞는코드라는 말은 참 어렵지만, 잘 작성해주신 거 같아요 ㅎㅎ

2022-11-15 07:02 UTC, seung-hun-h reviewed
안녕하세요 택승님 코드가 많이 개선되었네요!
리뷰 남겼으니 확인해주세요

2022-11-15 07:02 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +            throw new RuntimeException("File Read Error");
보통 Exception 클래스들은 생성자에 메시지와 함께 `Throwable` 타입의 인스턴스를 받을 수 있도록 해놨어요.
예외가 발생했을 때 생성자에 메시지만 넘기는 것과 `Throwable` 타입의 인스턴스를 함께 넘길때 로그가 어떻게 남는지 한 번 확인 해보면 좋겠네요

- e 보다는 의미있는 이름을 지어주면 좋을 것 같아요

```suggestion
            throw new RuntimeException("File Read Error", exception);
```

2022-11-15 07:40 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    private static Logger logger = LoggerFactory.getLogger(FileVoucherManager.class);
아이고.. 여기를 확인하지 못했네요ㅜㅜ

2022-11-15 07:46 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
아하! BufferedReader와 BufferedWriter에서 lines나 append을 할 때 안에서 각각 readLine과 write을 호출하는데요. 여기서 synchronized가 있어서 멀티쓰레드 환경에서 thread-safe 하다고 생각을 했는데, 일단 이게 어떻게 사용될 지 모르니 갖고있는게 좋지 않을까요?
아니면 별개로 싱글톤 객체인데 상태를 갖고 있으니 문제가 발생한다고 말씀하신 걸까요?

2022-11-15 07:47 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
찾아보니 AutoClosable 을 상속받은 거는 try-with-resources를 사용할 수 있더군요...!

2022-11-15 07:49 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +@Repository
음 그렇군요.. 저도 default 와 local의 사용처가 비슷하다고 생각해서 조언대로 따르는게 좋아보입니다!

2022-11-15 07:53 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static final String FILE_PATH = "src/main/resources/vouchers.csv";
다음엔 더 확인하고 올리겠습니다...!

2022-11-15 07:54 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    }
감사합니다!

2022-11-15 07:55 UTC, dlxortmd987 commented on src/main/resources/customer_blacklist.csv
> +4, 연가시
벌레 잡다가 썼습니다..ㅎㅎ

2022-11-15 07:55 UTC, dlxortmd987 commented on src/main/resources/application.yml
> +    active: local
말 그대로 로컬에서 작업하는 과정이라 local 프로파일을 활성화 시켰습니다!

2022-11-15 08:15 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +        }
음.. 제가 정확히 이해한 건지는 모르겠지만, 로그를 남기면서 re-throw를 할 경우 layer가 지날 때 마다 catch를 해서 로그를 남길 수 있어서 메시지가 중첩적으로 쌓일 수 있군요. 
그리고 멀티 쓰레드 환경에서는 또한 로그가 중복으로 남게 되니, 나중에 로그를 가지고 디버깅을 하기 힘든 문제가 있나 보네요. 
그래서 다 같이 중첩되게 로그를 남기지 않도록, anti-pattern 으로 정의해 놓은 것이군요!

2022-11-15 08:20 UTC, dlxortmd987 commented on src/main/resources/logback.xml
> +        </filter>
warn과 error도 저장되는 것 같습니다! 찾아보니, 지정된 로그 레벨보다 같거나 높은 레벨은 저장이 되는 것 같습니다!
https://logback.qos.ch/manual/filters.html

2022-11-15 08:21 UTC, dlxortmd987 commented
> > file에서 stream으로 list를 가져오는데, 이 부분을 맞게 짰는지 궁금합니다!
> 
> 맞는코드라는 말은 참 어렵지만, 잘 작성해주신 거 같아요 ㅎㅎ

맞는 코드라고 제가 표현을 했네요..ㅎㅎ 너무 하드 코딩 식으로 짠게 아닌가 해서 여쭤봤습니다! ㅋㅋㅋ

2022-11-15 08:22 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
음 저도 이 부분에 대해 고민했는데 그냥 create 부분만 메서드로 빼도 괜찮을까요?

2022-11-15 08:43 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +            throw new RuntimeException("File Read Error");
Throwable을 넣어주면, catch를 하는 곳에서 Throwable 를 쓸 수 있겠네요! 
만약에 넣어주지 않으면 메시지만 조회할 수 있겠네요...
음 그럼 대안으로 알려주신 exception을 써보려고 하는데 이것은 어떤가요?

2022-11-15 08:44 UTC, dlxortmd987 commented
@hongbin-dev @seung-hun-h 답변 남겼으니 확인 한번 부탁드립니다!

2022-11-15 08:45 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static void write(Voucher voucher, File file) {
사실 인텔리제이에서 자동으로 메서드를 추출해 줬습니다..ㅎㅎ
예상 되는 바로는 생성자를 호출하기 전에 이미 스택에 담아놓기 위해서 그런 것 아닐까 생각중입니다!

2022-11-15 09:05 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FixedAmountVoucher.java
> +    private static final String TYPE = "FIXED";
Voucher에도 이렇게 Type을 가지고 있어도 될까요?
다형성을 이용하려면 결국 객체 자신이 어떤 타입인지 알아야 할 것 같은데, `Object.getClass()` 메서드로 해결하는게 좋을까요??

2022-11-15 09:53 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
> 음 저도 이 부분에 대해 고민했는데 그냥 create 부분만 메서드로 빼도 괜찮을까요?

넵! 저는 그게 더 좋아보이네요

2022-11-15 09:56 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +            throw new RuntimeException("File Read Error");
> Throwable을 넣어주면, catch를 하는 곳에서 Throwable 를 쓸 수 있겠네요! 만약에 넣어주지 않으면 메시지만 조회할 수 있겠네요... 음 그럼 대안으로 알려주신 exception을 써보려고 하는데 이것은 어떤가요?

대안은 아니고 `RuntimeException`을 따라 올라가다보면 `Throwable`이 나올거에요. 그러니 지금 `RuntimeException`을 인자로 넘겨도 아무런 지정이 없습니다!

사실 제가 의도한 이야기는 만약 예외가 발생했을 때 `Throwable`을 넘겨주지 않으면 예외 로그가 누적되지 않아서 어디서부터 예외가 발생했는지 보이질 않아요. 이거는 말로 설명드리기 어려우니 나중이 직접 보여 드릴 시간을 가지면 좋을 것 같긴 하네요

2022-11-15 14:29 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
오. BufferedReader와 BufferedWriter에 sync가 달려있군요? 이 부분은 제가 몰랐습니다.
최근에는 서버를 컨테이너화해서 서버 자체를 N대를 실행시킵니다. 이러면 문제가 발생할 수도 있겠죠?

이런 부분에서 최대한 상태를 안갖는게 좋긴할거에요.

2022-11-15 14:39 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static void write(Voucher voucher, File file) {
`vouchersCsv`를 멤버변수로 갖고있는데요. 이러면 static에서 활용하기 어렵지않을까요?

2022-11-15 15:16 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
음 그렇게 되면 문제가 생길 수 있겠네요! 상태를 안가지도록 처리해볼게요!

2022-11-15 15:17 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    }
음 명쾌하지 않았던 부분인데 감사합니다!

2022-11-15 15:20 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +            throw new RuntimeException("File Read Error");
음 그렇군요🤔 throwable이 누적되서 나중에 디버깅을 쉽게 할 때 사용하나 보네요.. 나중에 게더에서 찾아뵙겠습니다...!

2022-11-16 03:01 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/FixedAmountVoucher.java
> +    private static final String TYPE = "FIXED";
흠 저는 가져도 괜찮을 것 같아요. 어떤점에서 Type 가지는 것에 대해 애매하게 생각하는지 궁금하네요
그리고 String 값이 아니고 VocherType을 이미 작성하셨는데, 이를 사용하지 않는 이유가 있을까요?

2022-11-16 06:37 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FixedAmountVoucher.java
> +    private static final String TYPE = "FIXED";
클래스 이름에서 이미 Fixed 라고 타입이 명시되어 있어서 여기에 상수로 선언해주는게 어색하지는 않을까 생각했습니다.
VoucherType을 까먹고 있었네요..! 이것을 이용하면 더 좋을 것 같습니다!

2022-11-16 06:40 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static void write(Voucher voucher, File file) {
음 파일 필드가 static이 아닌데 static 메소드인 write에서 잘 활용하기 어려울거라는 말씀이시죠?
맞는 것 같습니다. 아마 file을 필드에서 제거하면 자연스럽게 바뀌게 될 것 같아요..!

2022-11-16 13:14 UTC, seung-hun-h reviewed
택승님 리뷰 남겼습니다 확인해주세요

2022-11-16 14:47 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static void write(Voucher voucher, File file) {
```java
private static void write(Voucher voucher) {
  try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(vouchersCsv, true))) {
            bufferedWriter.append(voucher.getType());
            bufferedWriter.append(", ");
            bufferedWriter.append(voucher.getAmount());
            bufferedWriter.append(System.lineSeparator());
...
}
```
이렇게 작성할 수 있지 않을까? 했습니다.

2022-11-16 14:54 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/io/ConsoleManager.java
> +        );
toString()을 비즈니스 목적(출력)으로 사용하고 계시군요?

관계상으로는 로그를 남길 때, 객체를 식별할때 주로 사용되는데요. 아래 링크를 참고해보면 좋을듯합니다.

https://velog.io/@ozragwort/toString-%EB%B9%84%EC%A6%88%EB%8B%88%EC%8A%A4-%EB%A1%9C%EC%A7%81%EA%B3%BC-UI-%EB%A1%9C%EC%A7%81%EC%9D%98-%EB%B6%84%EB%A6%AC

2022-11-16 14:54 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            bufferedWriter.append(", ");
`", "`를 상수로 포장해보면 좋을듯합니다!

\+ 나중에 바우처이름이라는 필드가 추가됐는데, `"기존회원, 기회원 전용 바우처"`라는 이름이 들어가면 문제가 발생할 수도 있겠네요.
이 부분은 반영하지않고, 고민해보면 좋을듯합니다!

2022-11-16 14:54 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            return Voucher.newInstance(VoucherType.of(t[0]), new VoucherAmount(t[1]));
메서드의 목적이 get 인가요? 뭔갈 만들어내고 있는 것 같네요

2022-11-16 14:54 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/FixedAmountVoucher.java
> +    }
이 친구는 왜 String으로 반환하나요?

2022-11-16 14:54 UTC, hongbin-dev commented
@dlxortmd987 택승님 추가 리뷰 남겨봤습니다!

2022-11-17 06:36 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +    private static void write(Voucher voucher, File file) {
아하 그렇군요.. 필드가 static이 아니니까 write도 static이 아니어야 활용을 할 수 있겠군요!

2022-11-17 06:41 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
>              throw new RuntimeException("Cannot create file. Please check file name or path.", exception);
음 그렇군요! 메시지에 path를 추가해보겠습니다!
`RuntimaException` 보다는 `IllegalArgumentException` 으로 바꿔봐야 겠네요!

2022-11-17 07:09 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
>          }
음 사실 파일이 없는 상태에서 `list`(파일에서 바우처 읽어오기) 명령을 실행했을 때 에러가 날 수 있다고 생각했습니다. 
음 실험해보니, 승훈님 말씀처럼 파일이 존재하는지 굳이 확인하지 않아도 똑같이 작동하네요.
로그로 남기는 거 좋은 것 같습니다! 이렇게 봐꿔보는건 어떨까요?
``` java
try {
        File file = new File(filePath);
        if (file.createNewFile()) {
                logger.info("file created. [FILE PATH]: " + filePath);
            }
        } catch (IOException exception) {
            throw new IllegalArgumentException("Cannot find file. Please check there is file those name is " + file.getName() + ".[File Path]: " + filePath, exception);
}
```

2022-11-17 07:25 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
>                      .map(line -> line.split(", "))
음 t 보다 `token` 이 좋을 것 같긴 하네요!

2022-11-17 07:40 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            bufferedWriter.append(", ");
음 저도 필드가 추가됐을 때, 원래 있는 코드를 변경해야 하는 문제가 생길 것 같아서 고민했었는데
어떻게 해결해야 할지 더 고민해봐야겠네요..
상수로 변경하는 것 좋은 것 같아요!

2022-11-17 07:41 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            return Voucher.newInstance(VoucherType.of(t[0]), new VoucherAmount(t[1]));
음 이 부분 수정해야 할 것 같네요! 지금 상황에서는 createVoucher가 좋아보이네요!

2022-11-17 08:01 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FixedAmountVoucher.java
> +    }
밖에서 가공하는 것 보다 안에서 가공해서 내보내는게 객체가 변경될 가능성이 없다고 생각했습니다.
근데 여기서 어차피 VoucherAmount를 final로 선언해서 변경될 가능성이 없으니 setter만 정의하지 않으면 되겠네요.
VoucherAmount 타입으로 반환해서 이것을 사용하는 곳에서 가공하도록 해야겠네요!

2022-11-17 08:07 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/io/ConsoleManager.java
> +        );
음 toString을 이용해서 원하는 View를 만드는 것이 문제가 되는 것이네요. toString을 통해 하는 것이 아니라 printBlackList 메소드 내에서 Customer을 가공해서 String으로 변경해야 겠네요!

2022-11-17 08:40 UTC, dlxortmd987 commented
@hongbin-dev @hongbin-dev  리뷰 내용 바탕으로 고쳐봤습니다!

2022-11-17 15:57 UTC, hongbin-dev approved these changes
택승님 고생많으셨습니다!
테스트도 많이 작성해주셨네요 💯 
다음 미션으로 진행하시죠! @dlxortmd987

2022-11-17 15:57 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    public static final String DELIMITER = ", ";
요놈은 private으로 바꾸면 좋겠네요

2022-11-17 15:57 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +    }
값을 단순 꺼내는걸까요? create()라는 이름이 더 어울릴 것 같아요~

2022-11-17 15:57 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/command/VoucherExecutorTest.java
> +                    });
then이 조금 어렵네요. 테스트코드도 가독성이 중요하다고 생각하는데요. 
반복문없이 assert을 해보면 좋겠네요.

2022-11-17 15:57 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/customer/BlackCustomerManagerTest.java
> +        );
테스트용 파일(혹은 데이터) 쓰면 더 편하지않을까요?

2022-11-18 02:37 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/customer/BlackCustomerManagerTest.java
> +        );
이것도 테스트용 파일을 쓰도록 고려해보겠습니다!

2022-11-18 02:39 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +    }
그렇군요! 원하는 상태를 가진 객체를 반환한다 가 제가 생각하는 행동인데 이름 짓는게 어렵네요..

2022-11-18 02:39 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    public static final String DELIMITER = ", ";
아! private으로 바꿔야겠네요!

2022-11-18 02:39 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/command/VoucherExecutorTest.java
> +                    });
음 한번 다시 생각해봐야 겠네요

> 택승님 고생많으셨습니다! 테스트도 많이 작성해주셨네요 💯 다음 미션으로 진행하시죠! @dlxortmd987

넵 알겠습니다!

2022-11-18 02:47 UTC, merged