[3기-C] 김선호 SpringBoot Part1 Weekly Mission 제출합니다.(4차)
prgrms-be-devcourse/springboot-basic pull request #570
Opened 2022-11-14 18:42 UTC by preferKim

@hongbin-dev @seung-hun-h 

## 📌 과제 설명 

- csv 파일로 생성된 바우처 내역을 저장합니다.
- csv 파일로 저장된 블랙리스트 명단을 조회합니다.
- yaml 프로퍼티를 통해 블랙리스트와 바우처 파일의 파일 경로를 지정하였습니다.

## 👩‍💻 요구 사항과 구현 내용 

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ 피드백 반영사항  

- [생성자를 통해 의존관계를 주입받는 것이 자명하기에, 불필요한 Autowired 어노테이션을 제거하였습니다!](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021476936)
- [디미터의 법칙을 알아보고, 이를 코드에 반영했습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021490244)
- [향상된 switch 문을 이용하여 커맨드를 실행하도록 변경하였습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021497745)
- [커스텀 예외를 이용하여 예외 메시지도 함께 던져주는 방식으로 수정하였습니다](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021826928)
- [바우처의 할인 기능에 대한 예외와 테스트 코드를 작성하였습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021888793)
- [CommandType.of(command) 에서 Optional을 반환하고, 입력 커맨드를 CommandType 으로 변경하는 과정에서 예외 발생시 별도의 커스텀 예외를 통해 처리하도록 하였습니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1021918602)

## ✅ PR 포인트 & 궁금한 점 

- `이 객체가 여기서 이 예외처리를 해도 되는지`, `이런 예외처리는 관용적이지 않은데..` 하는 부분을 짚어주시면 감사하겠습니다.
- 미처 반영하지 못한 피드백은 앞으로도 꾸준히 적용하며 리팩터링해나가겠습니다!

2022-11-15 04:55 UTC, hongbin-dev requested changes
선호님 고생하셨습니다!
구조의 관련된 코멘트 남겼는데 확인부탁드려요!

2022-11-15 04:55 UTC, hongbin-dev commented on build.gradle
> +sourceCompatibility = '17'
👍

2022-11-15 04:55 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/configuration/FileConfig.java
> +    private final String voucherRecord;
설정파일 객체를 만들어보셨군요 👍

2022-11-15 04:55 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/FileManager.java
> +    }
혹시 실행해보지 못했는데, ApplicationContext를 생성자 주입으로 받을 수 있나요..?

2022-11-15 04:55 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/FileManager.java
> +    }
모든 예외를 RuntimeException로 날리고있는데, 다른 표준예외를 사용해보시는게 좋을 것 같아요.
RuntimeException은 어떤 의미인지 모를 것 같아요.

2022-11-15 04:55 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/io/Writer.java
> +
콘솔에 파일까지 넘어오는군요. 출력입장에서는 동일한 voucher 객체를 받아서, 기존 로직과 동일하게 사용할 순 없을까요?

2022-11-15 04:55 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/voucher/warehouse/VoucherContentsConverter.java
> +
바우처를 텍스트로 변경해주는 객체로 보이는데요. 이 객체를 스프링 빈에 등록할 필요가 있을까요?

2022-11-15 04:55 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/voucher/warehouse/VoucherWarehouse.java
> +public interface VoucherWarehouse {
VoucherWarehouse라고함은 너무 큰 의미로 보이는데요.

Vouchers, VoucherStorage 정도의 이름은 어떨까요?

2022-11-15 04:55 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/voucher/warehouse/FileVouchersTest.java
> +@Profile("release")
일반적으로 테스트는 별도의 profile을 가져갑니다. release 프로파일 없이 테스트할 방법은 없을까요?

2022-11-15 07:29 UTC, seung-hun-h reviewed
안녕하세요 선호님, 리뷰 남겼으니 확인해주세요

2022-11-15 07:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/configuration/FileConfig.java
> +    private final String voucherRecord;
생성자 주입으로 불변 객체를 만든 것도 좋네요 👍

2022-11-15 07:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +            } catch (IllegalCommandException e) {
`e` 보다는 의미있는 이름을 지어주는 것이 좋겠네요

2022-11-15 07:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +                throw new RuntimeException();
그냥 예외만 던져줘도 좋을 것 같아요

2022-11-15 07:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/FileManager.java
> +    }
주입된다 하더라도 `AppicationContext`를 직접 사용하는 것 보다는 다른 방법을 생각해보는 것이 좋을 것 같네요

2022-11-15 07:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/io/FileManager.java
> +            throw new RuntimeException(e);
메시지도 함께 던져주면 좋겠네요

2022-11-20 18:38 UTC, preferKim commented
@hongbin-dev @seung-hun-h 
다음 미션 PR을 위해 우선 해당 PR은 머지하도록 하겠습니다😭
피드백 반영사항은 다음 PR에 코멘트로 남겨두도록 하겠습니다!

2022-11-20 18:38 UTC, merged