[3기-C] 김기서 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #577
Opened 2022-11-17 15:05 UTC by rlarltj

멘토님들 안녕하세요!!
이번에도 잘 부탁드립니다!!!!!
감사합니다 :)

## 📌 과제 설명 
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x]  특정 고객에게 바우처를 할당할 수 있습니다.
- [x]  고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x]  고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x]  특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 

- `NamedParameterJdbcTemplate`을 이용하여 DB로 엔티티를 관리하였습니다.
- `DbCustomerRepository`: 회원 가입, 회원 조회 기능을 구현했습니다.
- `DbVoucherRepository`: 바우처 조회, 등록, 삭제 기능을 구현했습니다.
- `DbWalletRepository`: 특정 회원에게 바우처 할당, 특정 회원의 바우처 목록 조회, 특정 바우처를 보유한 회원 조회,
 특정 회원의 특정 바우처 삭제 기능을 구현했습니다.
- `CommandLineApplication`: 각 컨트롤러를 주입받으며, 사용자의 명령어 입력에 따라 각 컨트롤러의 메소드를 호출합니다.  

### 패키지 구조
<img height="650" alt="패키지구조" src="https://user-images.githubusercontent.com/81108344/202480477-c627a9bb-5f93-4c5d-b0d8-4bc73e1031ce.png">

### ERD
![erd](https://user-images.githubusercontent.com/81108344/202469714-6d66cce2-e212-4e1d-a267-bc398cc5ee9d.png)

## ✅ PR 포인트 & 궁금한 점 

1. 디스크와 메모리의 데이터 정합성을 맞추는 부분이 어려웠습니다. 
`Customer` 클래스에 `List<Voucher> wallet` 필드를 두어 메모리 상에서 바우처 지갑으로 사용했습니다. 
따라서 `CustomerRepository`의 `findById()` 메소드가 회원을 DB에서 단순 조회하는 기능이지만 
`Customer - wallet - Voucher - Voucher_rule` 테이블을 조인해서 바우처 정보까지 가져온 뒤 회원의 메모리 지갑에도 바인딩 하였는데요, 과정이 많이 복잡한 것 같습니다. 이것이 불필요한 작업인지? 아니면 테이블 구조를 개선해야 하는 것인지? 그냥 단순히 `Customer`만 조회하는 기능을 추가하는 것이 좋을지? 등 멘토님들의 의견이 궁금합니다. 
   
2. 객체 간 역할이 잘 나누어졌는지 궁금합니다 : -) 

3. 코드에서 리팩토링이나 개선이 필요한 부분 말씀해주시면 정말 감사드리겠습니다!!!!!!!!

2022-11-19 15:14 UTC, choi1204 reviewed
기서님 과제하시느라 고생하셨습니다.
코멘트 확인해주시고 학습에 도움되시면 좋겠습니다.
추가적으로 현재 Wallet을 도메인으로 만들지 않고 Customer와 Voucher를 사용하시는 모습이 보여요. 
이런 방식보다 Wallet의 도메인을 만드시고 만든 Wallet을 활용하시는게 보다 유연하고 확장가능한 설계가 될 것같아요

2022-11-19 15:14 UTC, choi1204 commented on src/main/java/com/programmers/voucher/controller/VoucherController.java
> +        view.printMessage(VOUCHER_TYPE_MESSAGE);
출력 형식이 Message의 Enum을 넘길때가 있고 그냥 String으로 변환해서 넘길때가 잇어요 이 부분을 통일하시면 더 좋을 것 같아요

2022-11-21 01:52 UTC, WooSungHwan requested changes
안녕하세요. 기서님 과제하시느라 수고 많으셨습니다.
리뷰몇자 남겼는데 확인부탁드려요!

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/customer/controller/CustomerController.java
> +        customerService.join(name, email);
흐름이 깔끔하네요 ㅎㅎ 저런 출력까지 join의 controller가 담당해야 할 것 같긴하네요.

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/customer/controller/CustomerController.java
> +    }
메소드명이 조금 애매한게 join밖에 없어서 validateInput이라고 할 수도 있지만 validateForJoin이라던가 특정 규칙을 만들어서 메소드명을 포함시키도록 하는건 어떨까요?

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/customer/controller/CustomerController.java
> +        }
View가 List를 받고 List타입이 뭐든지 안쪽 toString을 출력하면 좀더 목록에 유연한 출력문이 나올것 같아요.

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/customer/repository/DbCustomerRepository.java
> +    public final static String LAST_LOGIN_AT = "lastLoginAt";
https://stackoverflow.com/questions/11219556/difference-between-final-static-and-static-final

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/customer/repository/DbCustomerRepository.java
>      }
double brace를 활용해서 hashmap을 인스턴스화했는데
제가 여기에 왜 리뷰를 달았는지 찾아보시면 좋을 것 같습니다.

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/wallet/controller/WalletController.java
> +@Controller
현재 콘솔프로그램인데 Controller가 붙게되면 불필요한 작업이 하나 들어갈거에요. 지금은 org.springframework.stereotype.Controller 는 쓰일 이유가 전혀 없습니다.

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/wallet/repository/DbWalletRepository.java
> +        if (count != 1) {
이런 update 후 int 리턴받아서 1이 아닌 경우에 처리하곤 하시는데 이렇게 처리하시는 이유가 뭔가요??

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/wallet/repository/DbWalletRepository.java
> +            return List.of();
throw를 다시 전이해서 전역적인 예외 핸들러 쪽에서 쿼리에러가 발생했을때 적절한 에러를 전달했으면 좋겠습니다. 무언가 empty 한 value를  repository에서 리턴해주는건 좀 생각해봐야겠네요.

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/wallet/service/WalletServiceImpl.java
> +    }
이 두개는 wallet에 있을 필요가 없지 않나요?? 게다가 메소드명도 각각의 customer와  voucher에 있는게 좀더 자연스러워 보입니다.
구조가 잘못된건지 wallet에 대한 개념이 잘못잡힌건지 체크해보셔요.

2022-11-21 01:52 UTC, WooSungHwan commented on src/main/java/com/programmers/wallet/service/WalletServiceImpl.java
> +    }
요기도 그르넹

2022-11-21 05:40 UTC, rlarltj commented on src/main/java/com/programmers/wallet/service/WalletServiceImpl.java
> +        Voucher voucher = voucherOptional.orElseThrow(() -> new RuntimeException(VOUCHER_ID_NOT_FOUND.getMessage()));
Voucher의 Optional을 받아 처리하는 부분을 삭제해서 Customer와 같은 스타일로 변경했습니다!!
private getCustomer(), getVoucher() 메소드로 만들어서 재사용하도록 변경했습니다.
리뷰 감사합니다!!!

2022-11-21 05:51 UTC, rlarltj commented on src/main/java/com/programmers/voucher/controller/VoucherController.java
> +        view.printMessage(VOUCHER_TYPE_MESSAGE);
넵 전부 다 Message 타입을 넘기는 것으로 통일했습니다!
감사합니다

2022-11-21 06:00 UTC, rlarltj commented on src/main/java/com/programmers/customer/controller/CustomerController.java
> +    }
의견 감사합니다!! 다른 기능들이 추가되면 validateInput이라는 이름은 규칙을 갖고 변경되어야 하겠네요

2022-11-21 06:06 UTC, rlarltj commented on src/main/java/com/programmers/customer/controller/CustomerController.java
> +        }
View에 List 타입을 받는 메소드를 생성해서 고객 리스트, 바우처 리스트를 출력할 때 사용하도록 변경했습니다!!

2022-11-21 06:20 UTC, rlarltj commented on src/main/java/com/programmers/customer/repository/DbCustomerRepository.java
> +    public final static String LAST_LOGIN_AT = "lastLoginAt";
final static, static final 둘의 차이는 없지만, 관습을 따라서 가독성을 챙기는 것이 더 좋다..로 이해했습니다!!
참고하겠습니다!!!!

2022-11-21 09:05 UTC, rlarltj commented on src/main/java/com/programmers/wallet/repository/DbWalletRepository.java
> +        if (count != 1) {
row 수가 1이 아닌 상황이라면 쿼리문이 잘못 동작한 것이라 판단되어 이렇게 작성했는데,
다른 메소드처럼 try{} catch{}로 예외 되던지기 하는 편이 더 나을 것 같습니다.!!!

2022-11-25 23:10 UTC, WooSungHwan commented on src/main/java/com/programmers/customer/repository/DbCustomerRepository.java
> +    public final static String LAST_LOGIN_AT = "lastLoginAt";
@rlarltj 되도록 관습을 맞춰주는게 후배가 가져가면 좋은 예의인 것 같기도 해요 ㅎㅎ 여기저기 static final , final static 난발되어있다면 기준이 없어지기도 하고요

2022-11-25 23:11 UTC, WooSungHwan commented on src/main/java/com/programmers/customer/repository/DbCustomerRepository.java
> +    public final static String LAST_LOGIN_AT = "lastLoginAt";
여기서 기준이 꼭 필요한가 라고 느낀다면 그건 다시생각해봐야합니다 ㅎㅎ 혹시몰라서..

2022-11-25 23:12 UTC, WooSungHwan commented on src/main/java/com/programmers/wallet/repository/DbWalletRepository.java
> +        if (count != 1) {
노노노 좋은 접근이라서 이유가 궁금해서 그랬어요.
낙관적 Lock을 알아보시면 그 시초가 되는 행위여서 그래요

2023-06-05 18:40 UTC, closed without merging