[3기-C] 김소현 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #581
Opened 2022-11-18 13:42 UTC by thguss

## 📌 과제 설명 
JdbcTemplate를 활용하여 DB를 연결한 CRUD를 만들고, 테스트 코드를 작성합니다.

**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - [x]  가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - [x]  엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - [x]  Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - [x]  customers 테이블 정의 및 추가
    - [x]  CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - [x]  바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - [x]  바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - [x]  기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x]  특정 고객에게 바우처를 할당할 수 있습니다.
- [x]  고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x]  고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x]  특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/55437339/202717884-65e6c341-4a04-4d2f-8a8d-5eaa0be64906.png">

## ✅ PR 포인트 & 궁금한 점 
테스트 코드가 아직 손에 익지 않아서, 어떤 코드가 좋은 코드인 지 아직 모르는 상태인 것 같습니다. 테스트 코드에 대한 코드리뷰를 꼼꼼하게 해주시면 감사하겠습니다 :)

객체지향 절차가 잘 지켜졌는 지 궁금합니다..!!

DB 테이블 분리가 잘 되었는 지, SQL 문법이 효율적으로 잘 짜여졌는 지도 궁금합니다!

2022-11-25 09:43 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/CommandLine.java
> +        walletService.deleteVoucherCustomerHave(customerId);
wallet을 지우는것(바우쳐와 커스터머 사이의 관계 끊기)이 아니라 voucher를 지우는거는 voucher 서비스에서 하는게 맞을 않을까 라는 생각이 듭니다.
voucherRepository에서 join으로 wallet의  customerId를 가져와서 하는 방식으로??

2022-11-25 09:58 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletService.java
> +    }
customer와 voucher사이의 관계를 끊는 기능은 제공해 주지 않나요❓

2022-11-25 09:58 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +        jdbcTemplate.update("DELETE FROM vouchers WHERE voucher_id in (SELECT voucher_id FROM wallet WHERE customer_id = UUID_TO_BIN(:customerId))",
서브 쿼리를 사용한 이유가 있나요??(진짜 몰라서 물어봄 써본적도 없는듯)

2022-11-25 10:04 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +            put("walletId", wallet.getWalletId().toString().getBytes());
이거 ID getBytes() 안하고 그냥 string으로 넘겨줘도 UUID_TO_BIN에서 잘 알아먹던가 같더라

2022-11-25 10:10 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +    private final RowMapper<Voucher> voucherRowMapper = (resultSet, i) -> {
RowMapper 시리즈가 로직의 변화 없이 여러곳에서 사용되는데 util로 뺀다던가?

2022-11-25 10:12 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +    private UUID toUUID(byte[] bytes) {
toUUID도 여러곳에서 쓰이는데 util로 뺴는건 어떻게 생각합니까 짱소현님

2022-11-25 10:28 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/CommandLine.java
> +            throw new RuntimeException(Message.INPUT_ERROR_MESSAGE.getMessage());
이거 에러 던지는 것들은 처리를 따로 안해주는지 궁금함니다. 오타나면 바로 프로그램 종료??

2022-11-25 10:38 UTC, park-se-jun commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletService.java
> +    public void deleteVoucherCustomerHave(UUID customerId) {
고객이 보유한 바우쳐를 개개별로 제거하는 기능은 없나요?

2022-11-25 10:44 UTC, park-se-jun reviewed
코드리뷰 너무 어렵다~~~난 잘 모르겠다~~ㅠㅠㅠㅠ 
내 빈약한 머리로는 뭘 더 어떻게 해야할지 모르겠음 퓨ㅠㅠㅠㅠ
개발 고수 김소현 화이팅~~~

2022-11-25 10:51 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/CommandLine.java
> +        walletService.deleteVoucherCustomerHave(customerId);
아앗 wallets 테이블에서 관련 데이터를 지우는 로직이 맞는 것 같네요 좋은 지적 감삼다~

2022-11-25 10:53 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletService.java
> +    }
wallets 테이블에서 관련 데이터를 지우는 행위 자체가 customer 과 voucher 사이의 특정 관계를 끊어주는 로직이라고 생각했슴다!

2022-11-25 10:56 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +        jdbcTemplate.update("DELETE FROM vouchers WHERE voucher_id in (SELECT voucher_id FROM wallet WHERE customer_id = UUID_TO_BIN(:customerId))",
vouchers 테이블에는 보유한 고객 id를 찾을 수 없어서 wallets 에서 관계 데이터를 확인하기 위해 서브쿼리 썼어요!

2022-11-25 10:56 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +            put("walletId", wallet.getWalletId().toString().getBytes());
오 그런 똑똑한 방식이,,, 감삼다

2022-11-25 10:57 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +    private final RowMapper<Voucher> voucherRowMapper = (resultSet, i) -> {
성준오빠 코드 보고 배워야겠다고 생각했지비 감사룽 ~.~

2022-11-25 10:57 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletRepository.java
> +    private UUID toUUID(byte[] bytes) {
좋은 지적입니다 짱세준님

2022-11-25 10:58 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/CommandLine.java
> +            throw new RuntimeException(Message.INPUT_ERROR_MESSAGE.getMessage());
초기에는 예외처리 했다가 너무 복잡시러워서 바로 프로그램 종료 처리로 하긴했는데,, 에러 핸들링 어렵네요 엉엉

2022-11-25 10:59 UTC, thguss commented on src/main/java/org/programmers/weekly/mission/domain/wallet/WalletService.java
> +    public void deleteVoucherCustomerHave(UUID customerId) {
고객이 보유한 바우처를 지우는 행위 자체가 개개별로 제거하는 기능이라고 생각했는데 다른 개개별로 제거하는 방법도 있을까요?! ㅇ0ㅇ !?

2022-11-25 11:00 UTC, thguss commented
@park-se-jun 좋은 코드리뷰 너무 감사드립니다!! 짱짱맨

2022-12-10 04:03 UTC, samkimuel commented
현재 예외가 발생하면 프로그램이 무조건 종료되는데, 예외 처리에 더 신경써볼까요??
프로그램 사용자 입장에서 생각해보면서 개발하면 좋겠어요!

2022-12-11 16:04 UTC, samkimuel requested changes
소현님 고생하셨습니다~👍
코멘트 달았으니 확인해주세요!

질문 주신 것에 대한 답변 드리자면, 
1. 테스트 코드가 아직 손에 익지 않아서, 어떤 코드가 좋은 코드인 지 아직 모르는 상태인 것 같습니다. 테스트 코드에 대한 코드리뷰를 꼼꼼하게 해주시면 감사하겠습니다 :)
-> voucher model 테스트에 예외 케이스도 잘 작성해주셨더라구요. 다른 테스트에서도 예외 케이스에 대해서 작성하면 좋을 것 같아요. 다른 도메인은 repository 테스트만 진행하신 것 같은데 domain, service 테스트는 작성하지 않은 이유가 있을까요?

2. 객체지향 절차가 잘 지켜졌는 지 궁금합니다..!!
-> 코드에 코멘트 달았으니 확인해주세요🙂

3. DB 테이블 분리가 잘 되었는 지, SQL 문법이 효율적으로 잘 짜여졌는 지도 궁금합니다!
-> 저는 괜찮다고 생각합니다. 복잡한 쿼리가 없는 것 같아서요ㅎ..

2023-06-05 18:40 UTC, closed without merging