[3기-C] 서예원 SpringBoot Part2 Weekly Mission(1차) 제출합니다
prgrms-be-devcourse/springboot-basic pull request #583
Opened 2022-11-18 14:46 UTC by yewon9609

(기본) 바우처 관리 애플리케이션
* 		  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    * 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    * 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    * Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
* 		  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    * customers 테이블 정의 및 추가
    * CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
* 		  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    * 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    * 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    * 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
👩‍💻 요구 사항과 구현 내용
* 중간에 logback설정 오류를 고치다가 브랜치를 새로파게되고.. 여러 과정을 거치게 되다보니 커밋메세지가 더러울 수 있습니다 🥺 죄송해요..
* Jdbc템플릿을 사용할때에는 profile("jdbc")로 설정해주시면 되고, 테스트는 embedded로 하였으나 app실행은 mysql을 다운받아 켜야합니다 (테이블 설정은 schema.sql에 있습니다)
* customer 관련기능, voucherDB관련 기능 CRUD를 구현하였습니다 (Test코드를 돌려서 확인하시면 편하실 것 같아요)
* 과정에서 voucher(fixed, percent) 필드내에 바우처타입 을 추가하였습니다
✅ PR 포인트 & 궁금한 점
* 더 추가해야할 예외케이스들이 있을까요?
* 예외처리가 잘못되어있는 부분이 있을까요?

2022-11-18 14:54 UTC, yewon9609 commented on src/customer_blacklist.csv
>  customer_name: Irving Hessel DVM
console에서 black을 입력받았을때 보여주는 용도로 만든거라서 크게 신경안쓰셔도 될것같습니다!

2022-11-19 05:55 UTC, seung-hun-h requested changes
예원님 리뷰 남겼습니다. 확인해주세요

> 더 추가해야할 예외케이스들이 있을까요?
- 지금으로써는 보이지 않네요. 잘 작성하신 것 같습니다
> 예외처리가 잘못되어있는 부분이 있을까요?
- 리뷰 남겼습니다
> 현재 Memory로만 구현을 해서 service를 생성해줘야할까요? 아니면 Part3부터 MVC모델 도입할때 수정해도 되는걸까요?
- 그때 가서 해도 될 것 같아요

2022-11-19 05:55 UTC, seung-hun-h commented on src/main/java/customer/Customer.java
> +@Component
컴포넌트로 등록하신 이유가 있나요?

2022-11-19 05:55 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    }
다른 이유에 의해서 `DataAccessException`이 발생해도 `DuplicateKeyException`으로 전환될 것 같네요. 
그리고 예외 전환 시, 발생한 예외도 같이 넘겨주세요.

customerId를 메시지에 보여준 것은 좋네요 :)

2022-11-19 05:55 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +import static org.prgrms.query.CustomerSQL.*;
query는 memory에 종속적인 패키지 같아서 memory 내부로 옮기는 것이 좋다고 생각하는데, 예원님은 어떻게 생각하시나요?

2022-11-19 05:55 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    }
`Customer`를 DB에서 조회한 다음 삭제하는 이유가 있나요?
데이터를 삭제하려고 했는데, 이미 없으면 그대로도 좋을 것 같아서요

2022-11-19 05:55 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/VoucherDBMemory.java
> +@Profile("jdbc")
`CustomerDBMemory`도  `JdbcTemplate`를 사용하는데 이것만 프로파일을 설정해주신 이유가 있을까요?

2022-11-19 05:55 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/VoucherDBMemory.java
> +    return Optional.ofNullable(voucher);
`Voucher`를 밖에다 선언할 필요가 없을 것 같네요

```suggestion
    try {
      Voucher voucher = jdbcTemplate.queryForObject(FIND_BY_ID.getSql(), voucherRowMapper,
          String.valueOf(id));
      return Optional.ofNullable(voucher)
    } catch (DataAccessException e) {
      return Optional.empty();
    }
```

2022-11-19 05:55 UTC, seung-hun-h commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +  CustomerDBMemory customerMemory;
private을 붙여주는 것이 좋겠네요

2022-11-19 05:55 UTC, seung-hun-h commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +class CustomerDBMemoryTest extends JdbcBase{
`JdbcBase`에 데이터베이스 관련 설정을 해두고 테스트 클래스에서 확장(extends)하는 구조네요.
지금 이 테스트 클래스 구조가 좋을 지는 생각을 조금 해봐야겠네요.

`Datasource`와 `JdbcTemplate` 설정 클래스를 따로 분리해서 여기서 import하고,
embbeded mysql 설정은 여기서 해도 될 것 같은데 예원님은 어떻게 생각하시나요?

데이터 접근 계층 테스트를 할 때 JdbcBase를 확장 해야만 하는 구조라 조금 개선해보는 것이 좋을 것 같아서요!

2022-11-19 05:55 UTC, seung-hun-h commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +    assertThat(customer).usingRecursiveComparison().isEqualTo(foundCustomer.get());
`usingRecursiveComparison()`은 처음 보네요. 하나 알아갑니다 👍

2022-11-19 05:55 UTC, seung-hun-h commented on src/test/java/org/prgrms/memory/JdbcBase.java
> +  DataSource dataSource;
datasource는 어디서 사용하나요?

2022-11-19 05:55 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/VoucherDBMemory.java
> +  }
바우처를 삭제하고, 바우처를 다시 반환하는 이유가 있나요?

2022-11-19 17:12 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +import static org.prgrms.query.CustomerSQL.*;
말씀하신대로 종속적인 패키지라서 memory내부로 옮기는게 더 좋을 것 같습니다! 수정하겠습니다 ☺️

2022-11-19 17:17 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    }
앗 불필요하게 쿼리를 한번 더 보내는 코드가 되었버렸네요 delete 카운트가 0인지 아닌지 검사하는 코드로 수정하겠습니다

2022-11-19 17:26 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    }
로직상 delete했을 경우 지운 voucher를 리턴하게 짜보았는데요, DB에서 조회했을 때 존재하지 않는다면 굳이 delete쿼리를 날릴 필요없이 empty를 리턴하는게 더 좋지않을까? 라고 생각했습니다

2022-11-19 17:28 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/VoucherDBMemory.java
> +@Profile("jdbc")
customer관련 로직들은 설정된 profile이 없는 반면, voucher같은 경우에는 profile이 local, dev 로 나뉘어져 있기 때문에 따로 설정해주었습니다!

2022-11-19 18:04 UTC, yewon9609 commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +class CustomerDBMemoryTest extends JdbcBase{
단순히 공통으로 쓰이는 설정들을 파일로 빼서 상속시켰던 거였는데,
말씀하신대로 이 테스트 클래스 구조에대해서 좀 더 생각해봐야할 것같습니다!
Datasource, JdbcTemplate / embbeded설정 으로 나눠보도록하겠습니다!

2022-11-19 18:04 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/VoucherDBMemory.java
> +  }
삭제한 바우처의 정보를 보여주기 위함입니다!

2022-11-20 05:27 UTC, hongbin-dev reviewed
예원님 수고하셨습니다!

전체 테스트시 깨지는부분이 있는데, 이 부분 체크해주시면 좋겠습니다.

2022-11-20 05:27 UTC, hongbin-dev commented on src/main/java/org.prgrms/customer/Customer.java
> +  }
불변 좋네요 👍👍

2022-11-20 05:27 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +          customer.getName());
update, insert시 파라미터가 순차적으로 들어가는데요.
쿼리의 순서가 바뀌거나, 값이 제거되는 등 변경이 일어나면 문제가 발생할 가능성이 있어요.

- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/namedparam/NamedParameterJdbcTemplate.html

요 친구를 적용해볼까요?

2022-11-20 05:27 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    return customer;
```suggestion
    try {
      return jdbcTemplate.update(INSERT.getSql(), String.valueOf(customer.getId()),
          customer.getName());
    } catch (DataAccessException e) {
      throw new DataAccessException(
          "please check id *current id: " + customer.getId(), e) {
      };
    }
```

이렇게 바꿀 수도 있겠네요

2022-11-20 05:27 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +
삭제한 객체를 굳이 return 할 필요는 없을 것 같아요

2022-11-20 05:27 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    }
👍 

다만 0의 의미를 모를 수 있어, 이름을 붙여보면 좋겠네요

2022-11-20 05:27 UTC, hongbin-dev commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +@TestInstance(Lifecycle.PER_CLASS)
```suggestion
@SpringJUnitConfig
@TestInstance(Lifecycle.PER_CLASS)
```

이 두 annotiaion은 처음보는데, 어떤 역할을 하는걸까요?

2022-11-20 05:27 UTC, hongbin-dev commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +    assertEquals(customer, saved);
오우 노우.. 동일한 객체를 반환하고 있군요.

```java
Customer 예원 = new Customer(UUID.randomUUID(), "예오닝");

Customer 저장된_예원 = customerMemory.save(customer);

예원.setName("홍빈")

Customer 저장된홍빈 = customerMemory.save(예원);

print(저장된_예원) // ????
```
이런경우 혼란이 생길 수 있습니다. 같은객체를 리턴할때는 새 객체를 만들어내는게 혼란을 줄일 수 있어요

2022-11-20 05:27 UTC, hongbin-dev commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +    assertEquals(2, all.size());
size검사 후, id도 검증하면 좋겠네요

2022-11-20 05:27 UTC, hongbin-dev commented on src/test/java/org/prgrms/memory/JdbcBase.java
> +@TestInstance(Lifecycle.PER_CLASS)
@TestInstance(Lifecycle.PER_CLASS) 로 설정하신 이유가 있나요?

2022-11-20 05:29 UTC, hongbin-dev commented
> 더 추가해야할 예외케이스들이 있을까요?

꼼꼼하게 잘 작성해주신 거 같습니다!

> 예외처리가 잘못되어있는 부분이 있을까요?

이 부분은 코멘트 남겼습니다.

> 현재 Memory로만 구현을 해서 service를 생성해줘야할까요? 아니면 Part3부터 MVC모델 도입할때 수정해도 되는걸까요?
->update기능을 빼먹었네요 추가하겠습니다 !

시간남으시면 구현해보시죠!

2022-11-20 10:12 UTC, yewon9609 commented on src/main/java/customer/Customer.java
> +@Component
앗 처음에 콘솔창프로그램에 추가해야하는 줄알고 습관적으로 달아놨습니다 수정했습니다!

2022-11-21 09:50 UTC, yewon9609 commented on src/test/java/org/prgrms/memory/JdbcBase.java
> +  DataSource dataSource;
앗 지우는걸 깜박했네요 수정하겠습니다 !

2022-11-21 09:50 UTC, yewon9609 commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +@TestInstance(Lifecycle.PER_CLASS)
앗 jdbcBase 에설정해줬어야 했는데 제가 잘못 달아놨네요 
@SpringJUnitConfig 는 Test class 내부에 자체적으로 Configuration을 설정하고 이를 자동 주입받을 때 사용하는 어노테이션이구, @TestInstance 는 모든 테스트 메서드를 동일한 인스턴스 환경에서 동작시키고 싶을 때 사용한다고 합니다..!

2022-11-21 09:50 UTC, yewon9609 commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +    assertEquals(customer, saved);
넵 ! 수정하겠습니다 !

2022-11-21 09:56 UTC, yewon9609 commented on src/test/java/org/prgrms/memory/JdbcBase.java
> +@TestInstance(Lifecycle.PER_CLASS)
BeforeAll을 스테틱으로 선언하지않고 사용하기 위해서 설정했습니당 ..!

2022-11-21 10:10 UTC, yewon9609 commented
피드백 적용했습니당 ✨ 확인 부탁드려요 ☺️

2022-11-21 15:18 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    return customer;
아..! 그럼 
```

try {
	      jdbcTemplate.update(INSERT.getSql(), String.valueOf(customer.getId()),
	          customer.getName());
	     return customer
	    } catch (DataAccessException e) {
	      throw new DataAccessException(
	          "please check id *current id: " + customer.getId(), e) {
	      };
	    }

```
이렇게 해보셔도 되겠네요. (새 객체를 리턴하면 좋겠네요)

2022-11-21 15:22 UTC, hongbin-dev commented on src/test/java/org/prgrms/memory/JdbcBase.java
> +@TestInstance(Lifecycle.PER_CLASS)
embeddedMysql를 Bean으로 지정해볼 수 있지않을까요?

2022-11-21 15:25 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +            put("name", customer.getName());
`{{}}` double brace init은 안티패턴입니다.

https://www.baeldung.com/java-double-brace-initialization

요 글을 읽어보시면 좋겠네요.

2022-11-21 15:26 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +            return Optional.ofNullable(customer);
queryForObject는 null safe한데요.

`return Optional.of(customer);` of를 사용하여 null safe하다는걸 보장해주는게 좋을 거 같아요.

2022-11-21 15:32 UTC, hongbin-dev reviewed
예원님 리뷰 잘 반영해주셨군요! 추가 코멘트 남겨봤어요!

2022-11-21 15:32 UTC, hongbin-dev commented on src/main/java/org.prgrms/memory/query/VoucherSQL.java
> +    UPDATE("UPDATE voucher SET type = :voucherType , amount = :amountValue WHERE id = :id ");
💯

2022-11-21 15:32 UTC, hongbin-dev commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +        assertThat(customer).usingRecursiveComparison().isEqualTo(saved);
assertThat(customer).isEqualTo(saved);

를 사용하지 않는 이유가 있나요?

2022-11-21 15:32 UTC, hongbin-dev commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +        assertThat(all.get(1).getId()).isEqualTo(customer2.getId());
테스트가 조금 복잡하네요.
then 부분에는 로직없이 결과만 검증할 수도 있도록 작성해보면 좋을 거같아요.

```java
var actual = ....
assertThat(actual).isEqualTo(결과값)
```

결과값은 값을 꺼내는거보다 (`customer1.getId()`) > `"에오니"` 이터럴로 표현하는게 가독성이 더 좋더라구요.

2022-11-21 17:01 UTC, yewon9609 commented on src/test/java/org/prgrms/memory/CustomerDBMemoryTest.java
> +        assertThat(customer).usingRecursiveComparison().isEqualTo(saved);
이퀄스와 해시코드가 재정의 되어있지않아서 테스트가 깨지더라구요..! 
usingRecursiveComparison() 을 사용하면 동등성만 비교해서 사용하게 되었습니다

2022-11-22 10:09 UTC, seung-hun-h approved these changes
예원님 리뷰남겼습니다. 반영은 다음 PR에 해주세요

2022-11-22 10:09 UTC, seung-hun-h commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    private final int NO_RESULT = 0;
상수라면 static이 빠진 것 같네요

2022-11-22 10:29 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/VoucherDBMemory.java
> +            voucher.getVoucherAmount().getValue());
오..! 정말 확실히 보기 쉬워졌네용 ! 수정하겠습니다 ☺️

2022-11-22 10:37 UTC, yewon9609 commented on src/main/java/org.prgrms/memory/CustomerDBMemory.java
> +    private final int NO_RESULT = 0;
제가 상수에대해서 잘 모르고있었나봅니다 final을 붙여줬는데 static을 왜 또 붙여줘야할까? 싶어 찾아보았더니  https://jwdeveloper.tistory.com/179 
![스크린샷 2022-11-22 오후 7 36 59](https://user-images.githubusercontent.com/99070762/203292623-ef2e7d47-5894-40ee-bf0c-e5ea232db259.png)
이런 뜻이 있었군요..!

2022-11-23 04:35 UTC, merged