[3기-C] 이택승 SpringBoot Part2 Weekly Mission(1차) 제출합니다
prgrms-be-devcourse/springboot-basic pull request #586
Opened 2022-11-19 05:12 UTC by dlxortmd987

## 📌 과제 설명 
### (**기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

## 👩‍💻 요구 사항과 구현 내용 
- 고객 repository CRUD 구현
- 바우처 repository CRUD 구현
- 테스트 코드 작성

## ✅ 피드백 반영사항  
- 테스트 코드 가독성을 개선하려고 바꿔봤습니다.
  - assertj 에 Optional을 테스트하는 방법이 있어서 변경해봤습니다
- Voucher 객체를 반환하는 메소드 이름 변경(getInstance -> from) 

## ✅ PR 포인트 & 궁금한 점 
- Repository에서 exception 처리를 제대로 하고 있는지 궁금합니다. 
  - `DataAcecssException`  을 캐치하지 않고 re-throw를 안했는데 이것도 처리하는 것이 좋을까요?
- 테스트의 가독성이나 `@DisplayName`의 이름이 제대로 지어졌는지 궁금합니다.

2022-11-19 06:35 UTC, seung-hun-h requested changes
> Repository에서 exception 처리를 제대로 하고 있는지 궁금합니다.
> DataAcecssException 을 캐치하지 않고 re-throw를 안했는데 이것도 처리하는 것이 좋을까요?
- Repository를 어떻게 설계하고 구현했냐에 따라 다른 것 같네요. `DataAccessException`을 catch해서 어떤 일을 하고 싶다면, 해도 된다고 생각합니다
- 반드시 'DataAccessException`을 catch할 필요는 없을 것 같아요. 해당 예외는 JDBC API를 다룰 때 발생하는 Checked Exception을 스프링이 변환 해준 Unchecked Exception 이거든요.

> 테스트의 가독성이나 @DisplayName의 이름이 제대로 지어졌는지 궁금합니다.
- 대부분 가독성도 좋고 이름도 잘 작성된 것 같아요
- `VoucherManager`를 테스트할 때 데이터베이스에 저장된다는 것을 명시해야 할까 싶네요. 데이터베이스나 파일이나 메모리에 저장된다는 사실 자체는 인터페이스가 아니라 구체적이 구현체에 해당하는 이야기인 것 같아서요. 그냥 '바우처가 저장된다' 정도면 될 것 같아요

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    private static final String filePath = "src/main/resources/customer_blacklist.csv";
네이밍 변경하신 이유가 있나요?

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +    private final SimpleJdbcInsert simpleJdbcInsert;
👍

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +                .usingGeneratedKeyColumns("customer_id");
키를 애플리케이션 로직에서 생성하지 않고 DB에서 생성하는 방식의 장단점을 생각해보는 것도 좋을 것 같네요 👍

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +            throw new RuntimeException("Nothing was updated");
`RuntimeException`말고 의미 있는 예외를 던져주는 것이 좋겠네요

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +    };
필드는 위로 옮겨주는 것이 좋을 것 같아요

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            throw new IllegalArgumentException("Cannot find file. Please check there is file those name is " + file.getName(), exception);
예외 메시지를 알기 쉽게 잘 작성하셨네요 👍 
그런데 파일을 찾을 수 없을 때만 `IOException`이 발생하나요?

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/InMemoryVoucherManager.java
> +        vouchers.put(VoucherId.increase(), voucher);
`VoucherId`는 바우처의 ID를 생성해주는 클래스인가 보네요.
`VoucherId`는 애플리케이션이 종료됐다 다시 실행되면 항상 0부터 ID를 생성하겠네요. 그러면 `InMemoryVoucherManager`에 한정적인 클래스라고도 볼 수 있을 것 같아요. File이나 DB에서 사용한다면 Dup Key 문제가 발생할 수도 있겠네요. 다른 사람이 `VoucherId`를 사용할 때는 이런점을 알아차리기 어려울 수도 있겠네요

택승님은 이러한 문제를 어떻게 해결 할 수 있을 것 같나요?

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/JdbcVoucherManager.java
> +            logger.error("Got Empty Result", exception);
바우처가 존재하지 않을 때 로그 레벨을 `error`로 설정하신 이유가 있나요?

2022-11-19 06:35 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +            case PERCENT -> new PercentDiscountVoucher(amount);
VoucherType이 FIXED, PERCENT에 해당 하지 않는 경우에 대해서도 처리 해주면 좋겠네요

2022-11-19 06:35 UTC, seung-hun-h commented on src/test/java/org/prgrms/kdt/customer/JdbcCustomerManagerTest.java
> +class JdbcCustomerManagerTest extends JdbcBase {
`JdbcBase`를 상속한 구조를 생각하신 이유가 있을까요?

그리고 예외적인 경우에 대해서 테스트를 작성해 보는 것도 좋을 것 같아요

2022-11-19 06:35 UTC, seung-hun-h commented on src/test/java/org/prgrms/kdt/voucher/FileVoucherManagerTest.java
> +    })
`@CsvSource`를 활용해서 매핑되는 값에 대한 테스트 코드를 간략하게 작성하셨네요 👍

2022-11-19 06:35 UTC, seung-hun-h commented on src/test/java/org/prgrms/kdt/voucher/FileVoucherManagerTest.java
> +                .isTrue();
`when`구를 분리 해주면 좋을 것 같아요.
`when`에는 테스트 하고자하는 대상이 위치하기 때문에 중요한 부분이라고 생각합니다

참고로 테스트 대상을 보통 SUT(System Under Test)라고도 합니다

2022-11-20 08:05 UTC, hongbin-dev reviewed
택승님 수고하셨습니다! 
리뷰 남겨봤어요~! @dlxortmd987

2022-11-20 08:05 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/JdbcBase.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
클래스기반으로 설정하신 이유가 있나요?

2022-11-20 08:05 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/customer/JdbcCustomerManagerTest.java
> +                .isTrue();
then이 너무 어렵습니다..!
```suggestion
        var customer = customerManager.findById(savedCustomer.getId())
                .get()
        assertThat(customer).isNotNull()
```

이런형태가 더 읽기좋지않을까요?

2022-11-20 08:05 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/customer/JdbcCustomerManagerTest.java
> +
여기도 테스트가 조금 어렵습니다..!

```suggestion
        var customer = customerManager.findById(updatedCustomer.getId())
                        .get();
        var actual = customer.getName();

        // then
        assertThat(actual).is("update")
```

요런방식은 어떠세요?

2022-11-20 08:08 UTC, hongbin-dev commented
> Repository에서 exception 처리를 제대로 하고 있는지 궁금합니다.
DataAcecssException 을 캐치하지 않고 re-throw를 안했는데 이것도 처리하는 것이 좋을까요?

보통은 checked exception이라면 unchecked로 변환해주긴하는데, 지금은 필요성을 못느낀다면 그대로 두어도 될 것 같아요.
예외를 분류해서, 별도의 처리를하고싶은경우에 Custom예외로 가도 좋을 것 같아요. 

> 테스트의 가독성이나 @DisplayName의 이름이 제대로 지어졌는지 궁금합니다.

디스플레이네임은 잘 지어주신거같고, 관련해서 코멘트남겼어요.

2022-11-20 19:22 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/BlackCustomerManager.java
> +    private static final String filePath = "src/main/resources/customer_blacklist.csv";
다른거 바꾸다가 실수로 바뀐 것 같네요.. 다시 변경하겠습니다!

2022-11-20 19:59 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +    };
앗.. 감사합니다!

2022-11-21 15:37 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +        params.put("name", customer.getName());
저 궁금한 것이 있는데요. 자세한 내용은 슬랙에 올렸습니다!
https://greppkdt-backend.slack.com/archives/C04BDRGUE73/p1669044757081289

2022-11-21 15:47 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +            ));
공식문서를 확인해보니, sql 문이 null일 경우 `queryForObject` 가 null을 반환한다고 되어 있는데 혹시 제가 잘못 찾았을 수 있으니 링크 남깁니다!
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html#queryForObject(java.lang.String,java.lang.Object%5B%5D,int%5B%5D,java.lang.Class)

2022-11-21 15:49 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +        );
좋은 것 같아요! `NamedParameterJdbcTemplate` 으로 한번 적용해볼게요!

2022-11-21 15:50 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +    }
update 반환값으로 진짜 지워졌는지 확인을 해야겠네요.. 수정하겠습니다!

2022-11-21 16:03 UTC, dlxortmd987 commented on src/main/resources/schema.sql
> +drop table if exists customers CASCADE;
조언 감사드립니다! 이 부분을 하기 위해서 각 환경마다 sql 파일을 만든 다음 각 프로파일마다 원하는 sql 문을 설정하는 건 어떤가요?
사실 이 스키마를 테스트 환경에서만 사용해서 test/resources 에 넣어야 하는데 잘못 넣은 것 같습니다😰 이 부분은 리팩토링을 진행해서 원래 넣어야 하는 곳에 넣겠습니다!

2022-11-22 03:46 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +                .usingGeneratedKeyColumns("customer_id");
UUID와 autoincrement의 장단점을 알아보는 것으로 충분할까요? 한번 찾아보겠습니다! 감사합니다.

2022-11-22 03:47 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +            throw new RuntimeException("Nothing was updated");
`IllegalargumentException` 을 써봐야겠네요!

2022-11-22 03:55 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            throw new IllegalArgumentException("Cannot find file. Please check there is file those name is " + file.getName(), exception);
BufferedReader 가 close 됐는데, BufferedReader의 메소드에 접근할 때 발생하는 것 같네요. 이 경우에는 BufferedReader가 종료돼서 읽어올 수 없다고 날리는게 좋을까요?

2022-11-22 03:56 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/InMemoryVoucherManager.java
> +        vouchers.put(VoucherId.increase(), voucher);
게더에서 말씀해 주신 것처럼, 일단 final 클래스로 만들고, `@Componenet`를 제거하도록 바꿔보았습니다. 그리고 이름을 명확하게 `VoucherId` -> `InMemoryVoucherId` 이렇게 변경해보려고 합니다!

2022-11-22 04:06 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/JdbcVoucherManager.java
> +            logger.error("Got Empty Result", exception);
뭔가 요청을 처리하는 중 문제가 발생한 것 같은 느낌이라고 생각해서 error로 설정은 해놨습니다. 아직 `warn` 이랑 `error` 가 헷갈리네요..

2022-11-22 04:13 UTC, hongbin-dev commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +            return Optional.empty();
사용자에게 알려주는건 뷰에서 처리하기 어려울까요?

2022-11-22 04:42 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/Voucher.java
> +            case PERCENT -> new PercentDiscountVoucher(amount);
넵 알겠습니다!

2022-11-22 05:02 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/customer/JdbcCustomerManagerTest.java
> +class JdbcCustomerManagerTest extends JdbcBase {
설정이 똑같아서 설정을 공유하도록 하고 싶었습니다!
예외적인 상황도 테스트 케이스에 넣어보겠습니다!

2022-11-22 05:03 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/voucher/FileVoucherManagerTest.java
> +                .isTrue();
when을 분리해서 써보겠습니다!

2022-11-22 05:06 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
> +            return Optional.empty();
음 확실히 여기서 메시지를 보여주는건 이 객체의 책임이 아니네요! 메시지를 남기는 것은 뷰로 옮겨야 할 것 같아요

2022-11-22 06:25 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/JdbcBase.java
> +    static class Config {
테스트 코드에서는 저것을 이용하는군요.. 감사합니다!

2022-11-22 06:27 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/JdbcBase.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
EmbeddedMysql 인스턴스를 각 클래스마다 공유해야 한다고 생각해서 클래스 단위로 설정했습니다!

2022-11-22 06:28 UTC, dlxortmd987 commented on src/test/java/org/prgrms/kdt/customer/JdbcCustomerManagerTest.java
> +                .isTrue();
optional 안의 값이 null 일 수도 있다고 생각해서 조금 복잡하게 된 것 같습니다. 테스트 코드에서는 가독성을 위해서 optional 값을 바로 빼는 것이 좋을까요?

2022-11-22 10:43 UTC, seung-hun-h commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            throw new IllegalArgumentException("Cannot find file. Please check there is file those name is " + file.getName(), exception);
그런 경우에는 `IllegalArgumentException`이 의미상 맞을까 싶긴하네요. `IllegalStateException` 같은 것들이 더 맞을 수도 있을 것 같은데, 한 번 고민해보시고 적절한 것을 선택해서 던지면 될 것 같아요

2022-11-22 10:45 UTC, seung-hun-h approved these changes

2022-11-22 11:00 UTC, dlxortmd987 commented on src/main/java/org/prgrms/kdt/voucher/FileVoucherManager.java
> +            throw new IllegalArgumentException("Cannot find file. Please check there is file those name is " + file.getName(), exception);
음 그렇네요. 좀 더 고민해보겠습니다! 감사합니다.

2022-11-22 12:00 UTC, dlxortmd987 commented
> 안녕하세요 택승님, 리뷰 남겼으니 확인해주세요
> 
> > Repository에서 exception 처리를 제대로 하고 있는지 궁금합니다.
> > DataAcecssException 을 캐치하지 않고 re-throw를 안했는데 이것도 처리하는 것이 좋을까요?
> 
> * Repository를 어떻게 설계하고 구현했냐에 따라 다른 것 같네요. `DataAccessException`을 catch해서 어떤 일을 하고 싶다면, 해도 된다고 생각합니다
> * 반드시 'DataAccessException`을 catch할 필요는 없을 것 같아요. 해당 예외는 JDBC API를 다룰 때 발생하는 Checked Exception을 스프링이 변환 해준 Unchecked Exception 이거든요.
> 
> > 테스트의 가독성이나 @DisplayName의 이름이 제대로 지어졌는지 궁금합니다.
> 
> * 대부분 가독성도 좋고 이름도 잘 작성된 것 같아요
> * 예외적인 부분에 대한 테스트도 하면 좋을 것 같아요

의견 감사합니다!

2022-11-22 12:02 UTC, dlxortmd987 commented
> > Repository에서 exception 처리를 제대로 하고 있는지 궁금합니다.
> > DataAcecssException 을 캐치하지 않고 re-throw를 안했는데 이것도 처리하는 것이 좋을까요?
> 
> 보통은 checked exception이라면 unchecked로 변환해주긴하는데, 지금은 필요성을 못느낀다면 그대로 두어도 될 것 같아요. 예외를 분류해서, 별도의 처리를하고싶은경우에 Custom예외로 가도 좋을 것 같아요.
> 
> > 테스트의 가독성이나 @DisplayName의 이름이 제대로 지어졌는지 궁금합니다.
> 
> 디스플레이네임은 잘 지어주신거같고, 관련해서 코멘트남겼어요.

의견 감사합니다!

2022-11-23 04:36 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/customer/JdbcCustomerManagerTest.java
> +                .isTrue();
확정적으로 null이 아니라면, 꺼내서(`get()`) 검증하려는거에 집중하고 있습니다. (개인적인 선호도입니다 ㅎㅎ)

2022-11-23 04:39 UTC, hongbin-dev approved these changes
수고하셨습니다 택승님!

2022-11-23 04:39 UTC, hongbin-dev commented on src/test/java/org/prgrms/kdt/voucher/JdbcVoucherManagerTest.java
> +
설정이 매번 반복되네요 🧐 이 부분 제거할 수 있을지 고민해보면 좋을 거 같습니다

2022-11-23 04:39 UTC, merged