[3기-C] 김환 SpringBoot Part2 Weekly Mission(1차) 제출합니다
prgrms-be-devcourse/springboot-basic pull request #587
Opened 2022-11-19 09:09 UTC by hwankim123

## 📌 과제 설명 
* 단위 테스트 작성
* Voucher CRUD 구현
* Customer CRUD 구현
## 👩‍💻 요구 사항과 구현 내용 
- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

## ✅ 피드백 반영사항  
코드라인에 이전 코드리뷰와 함께 코멘트 남기겠습니다!

## ✅ PR 포인트 & 궁금한 점 
* 테스트코드를 제대로 작성해본 것이 거의 처음이라. 전반적으로 피드백 받고싶습니다.
* 서로 다른 여러 클래스의 메서드들만을 호출하는 클래스는 어떻게 단위테스트를 해야 할까요?
* MySQL의 auto increment와 같은 기능을 사용하면 고민할 내용이 아닙니다. 그런데, 현재 코드 상 UUID를 직접 생성해줘서 DB에 쿼리를 날려야 하는 상황에 있습니. 이런 경우에는 ID를 생성하는 책임을 엔티티 객체(Voucher, Customer 등)에 둬야 할지, 아니면 Repository 계층에 둬야 할지 고민입니다.

2022-11-20 15:44 UTC, hongbin-dev requested changes
환님 미션하시느라 수고하셨습니다  
Jdbc부분을 잘 작성해주셨네요 💯💯
함께보면 좋을 피드백 남겼으니 확인부탁드려요.

2022-11-20 15:44 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +    }
enum으로 관리하는 이유가 있을까요?

2022-11-20 15:44 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +                customer.getName(),
update, insert시 파라미터가 순차적으로 들어가는데요.
쿼리의 순서가 바뀌거나, 값이 제거되는 등 변경이 일어나면 문제가 발생할 가능성이 있어요.

- [https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/namedparam/NamedParameterJdbcTemplate.html](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/namedparam/NamedParameterJdbcTemplate.html)

요 친구를 적용해볼까요?

2022-11-20 15:44 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +        }
👍

0에 뜻을 상수로 포장해서 뜻을 부여하면 좋을 것 같아요.

2022-11-20 15:44 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +        }
💯💯

2022-11-20 15:44 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +                id.toString()));
```suggestion
        return Optional.of(jdbcTemplate.queryForObject(
                CustomerQuery.FIND_BY_ID.query,
                ROW_MAPPER,
                id.toString()));
```
queryForObject null safety한걸로 알고있는데요. 확정적인 of를 쓰는게 더 좋을 거 같아요.

2022-11-20 15:44 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/domain/FixedAmountVoucher.java
> +    }
```suggestion
    public FixedAmountVoucher(int fixedAmount, VoucherType voucherType) {
        this(null, fixedAmount....
    }
```
생성자 오버로딩을 해보면 좋을 것 같아요. 동일한 비즈니스를 타야 validate같은 메서드가 누락되는걸 방지할 수 있습니다.

2022-11-20 15:44 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/storage/JdbcVoucherRepository.java
> +    }
전반적으로 잘 작성해주셨네요 👍

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +    }
글자제약이 db 컬럼에 걸려있나보군요?

도메인규칙에는 이름길이제한이 없는데요. 이러면 db에 의존적인 코드가 작성될 것 같아요. 
애플리케이션에서 알 수 없는일이 DB에서 일어나서 혼란이 있을수도 있겠네요

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +                .isEqualTo(customer);
usingRecursiveComparison를 사용하는 이유가 있을까요?

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +                .isEqualTo(customer);
```suggestion
        var actual = jdbcCustomerRepository.findById(customer.getId())
                .get()

        //then
        assertThat(actual).isEqualTo(customer);
```
이쪽이 더 읽기 편한 것 같아요

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +        customerList.forEach(jdbcCustomerRepository::save);
테스트코드 내에 조건이나 반복이 들어가면 읽기가 어렵습니다.  (글이 읽히도록 작성해보면 좋을 것 같아요,.)
너무 많지않다면 풀어쓰는게 가독성이 더 좋을 수 있을 것 같아요.

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +        assertThat(customerList.size()).isEqualTo(foundCustomers.size());
```suggestion
        var actual = jdbcCustomerRepository.findAll().size();
        assertThat(actual).isEqualTo(3);
```

- assertThat 첫번째인자는 실제 값이 들어가고(파라미터 힌트 참고), 뒤에들어가는 값은 예상하는 값을 적습니다.
- 또 실제값에 로직이 들어가면 읽기가 어려워요.
- 예상값(expected)은 변수 말고, 값으로 표현하면 읽기 좋더라구요. 환님은 어떠세요?

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +        assertThat(foundAfterDelete.size()).isEqualTo(foundBeforeDelete.size() - 1);
여기도 조금 복잡해요. 예상값에 로직을 넣지 말아주세요.

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/voucher/VoucherTypeTest.java
> +    void findCommandByInputValue(String voucherTypeInput, String expectedVoucherType) {
```suggestion
    void findCommandByInputValue(String voucherTypeInput, VoucherType expectedVoucherType) {
```
이렇게해도 파라미터가 매핑될거에요 ㅎㅎ

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/FileVoucherStorageTest.java
> +    public void openFile() {
Order 없이 테스트할 순 없을까요?

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/InMemoryVoucherStorageTest.java
> +    List<Voucher> voucherList;
```suggestion
    @Mock
    private List<Voucher> voucherList;
```

2022-11-20 15:44 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@ActiveProfiles("prod")로 하신 이유가 있을까요?
일반적으로 테스트프로파일은 "test"로 많이 사용하는편입니다.

2022-11-20 15:54 UTC, hongbin-dev commented
> 서로 다른 여러 클래스의 메서드들만을 호출하는 클래스는 어떻게 단위테스트를 해야 할까요?

이 부분 잘 이해가 안갔는데요. 코드블럭을 잡고 코멘트 남겨주시면 더 좋을 것 같아요!

> MySQL의 auto increment와 같은 기능을 사용하면 고민할 내용이 아닙니다. 그런데, 현재 코드 상 UUID를 직접 생성해줘서 DB에 쿼리를 날려야 하는 상황에 있습니. 이런 경우에는 ID를 생성하는 책임을 엔티티 객체(Voucher, Customer 등)에 둬야 할지, 아니면 Repository 계층에 둬야 할지 고민입니다.

환님은 누구의 책임이라고 생각했나요? 이 부분은 객체지향사실과 오해를 읽어보면 좋을 거 같긴하네요 ㅎㅎ

2022-11-21 05:38 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +    }
원래 별도의 enum 클래스로 뺐다가 다시 넣었는데, 지금 생각해보니까 이렇게 할거면 그냥 String 상수로 하는게 더 나을 것 같아요!

2022-11-21 05:47 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +                customer.getName(),
NamedParameterJdbcTemplate 한번 사용해보겠습니다!

2022-11-21 06:00 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/FileVoucherStorageTest.java
> +    public void openFile() {
파일로 관리되는 Storage다보니까 파일이 열려야 다른 테스트도 가능할 거라 생각해서 Order를 지정해주었습니다. 

이에 대한 엘런님 의견이 궁금합니다!

2022-11-21 06:11 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +                id.toString()));
IDE가 추천해주길래 그런갑다 했는데,,, null safety하군요! 
queryForObject 코드를 보니까 element가 하나일때만 정상값을 반환하고 그 이외에는 예외를 던지는 것 같아요. 이런 예외처리때문에 null safety하다고 하신거죠?

2022-11-21 07:58 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +    }
듣고 보니 글자 수 제약이 도메인 객체에는 전혀 걸려있지 않고, DB에만 걸려있네요... 생성자에 validate 추가하겠습니다!!

2022-11-21 08:06 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +                .isEqualTo(customer);
`jdbcCustomerRepository.save()`로 넘겨준 결과를 확인하기 위해서 저장을 위한 객체인`customer`와 저장 후 조회하여 가져온 객체인 `foundCustomer` 을 비교하고 싶었습니다!

2022-11-21 08:12 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +                .isEqualTo(customer);
엇 근데 isEqualTo로 객체의 값을 비교하려면 equals()와 hashCode()를 재정의 해야하지 않나요? 😭

2022-11-21 08:28 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +        assertThat(customerList.size()).isEqualTo(foundCustomers.size());
제가 실제값이랑 예측값이랑 매번 콘솔을 봐도 햇갈렸던 이유가 이거였을까요? 🤣 기준 없이 실제 값과 예상값을 집어넣기만 했네요!

`예상값(expected)은 변수 말고, 값으로 표현하면 읽기 좋더라구요.` 에 대해서는, 사실 위에 리뷰와 같이 생각했을 때, 코드상에 foreach를 쓰지 않고 풀어쓴다음, 예상 값에 값(3)으로 표현하는게 테스트로서 가동성이 더 좋아질 것 같습니다!

2022-11-21 08:37 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/voucher/VoucherTypeTest.java
> +    void findCommandByInputValue(String voucherTypeInput, String expectedVoucherType) {
오우 진짜네요! 😄 내부적으로 파라미터로 넘긴 enum class의 valueOf를 호출하나...? 신기하군요 감사합니다!!

2022-11-21 08:39 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
일단 테스트가 돌아가는지 해보려고 prod로 했던 것 같습니다. 테스트 환경만의 profile 설정해보겠습니다!

2022-11-21 09:06 UTC, hwankim123 reviewed
첫 번째 질문이 이해하는데 어려움이 있다고 하셔서 코드라인에 코멘트 남겼습니다!

2022-11-22 04:21 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/storage/JdbcCustomerRepository.java
> +                id.toString()));
네 제가 생각한부분과 맞습니다. 근데 왜 Nullable 어노테이션이 달려있는지 🧐

2022-11-22 04:22 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +    }
좋습니다!

2022-11-22 04:22 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +                .isEqualTo(customer);
equals, hashcode 오버라이딩하여 동일성을 보장해주면 안될까요?

2022-11-22 04:23 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +                .isEqualTo(customer);
equals(), hashCode() 재정의를 안하신 이유가 있을까요?

2022-11-22 04:25 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/FileVoucherStorageTest.java
> +    public void openFile() {
메서드마다 파일을 열고, 닫아볼 수 있지않을까요? 
그럼 순서의 의존적이지 않는 테스트를 짜볼 수 있을 거 같아요. (나중에 병렬로도 돌릴 수 있고)

2022-11-22 04:26 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
별도로 돌리려면 java 런타임에 옵션을 줘서 실행시키는걸 추천드립니다 ㅎㅎ

2022-11-22 04:34 UTC, hongbin-dev approved these changes
환님 수고하셨습니다!
마이너한 코멘트만남아 머지해도 좋을 거 같아요. 수고하셨습니다!

2022-11-22 04:34 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/domain/Customer.java
> +    private static final Logger logger = LoggerFactory.getLogger(FixedAmountVoucher.class);
FixedAmountVoucher 요기 Customer 로거가 들어가야겠죠?

2022-11-22 04:34 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/customer/domain/Customer.java
> +        }
👍

2022-11-22 04:34 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/VoucherManager.java
>          voucherStorage.save(voucher);
`각 객체의 메서드들을 호출하기만 합니다.` 이게 테스트해봐야할 친구가 아닐까 싶었어요! 

- A타입으로 A바우처로 만들 수 있다.
- B타입으로 B바우처로 만들 수 있다.
- 바우처를 저장할 수 있다.

이 세개로 테스트해볼 수 있지않을까요?

2022-11-22 04:51 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/customer/domain/Customer.java
> +    private static final Logger logger = LoggerFactory.getLogger(FixedAmountVoucher.class);
아이코,,, 복붙을 막했네요...ㅠㅠ 고치겠습니다

2022-11-22 04:58 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +                .isEqualTo(customer);
아... 듣고 보니 그렇네요... 재정의 하지 말아야할 이유도 없을 듯 싶네요. 이펙티브 자바 읽어보고 적용해보겠슴다!!

2022-11-22 05:00 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/FileVoucherStorageTest.java
> +    public void openFile() {
음 이부분이 더 좋은 거 같네요. 처음에는 파일을 여는 것과 파일 IO와는 다른 기능이라고 생각했는데, 어차피 파일 IO를 하려면 파일을 열어야 하니까...

2022-11-22 05:01 UTC, hwankim123 commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
테스트할때에만 java 런타임에 옵션을 주는 식으로 "개발 프로파일"에는 영향을 미치지 않게 하려는 의도인가요?

2022-11-22 05:02 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/voucher/VoucherManager.java
>          voucherStorage.save(voucher);
🤔 음... mock 객체를 이용해서 해볼 수 있겠네요! 좋은 것 같습니다.

2022-11-22 10:39 UTC, seung-hun-h reviewed
환님 리뷰 남겼습니다. 확인해주세요.
앨런이 리뷰를 잘해줘서 많이 남기진 않았습니다

2022-11-22 10:39 UTC, seung-hun-h commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +    @Configuration
```suggestion
    @TestConfiguration
```
로 변경하는 것이 좋을 것 같아요

2022-11-22 10:39 UTC, seung-hun-h commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +    DataSource dataSource;
private을 붙여주세요

2022-11-22 10:39 UTC, seung-hun-h commented on src/test/java/com/prgrms/springbootbasic/customer/storage/CustomerRepositoryTest.java
> +        customer.update(newName);
이 부분은 given으로 이동하는 것이 좋겠네요

2022-11-23 04:43 UTC, hongbin-dev commented on src/test/java/com/prgrms/springbootbasic/voucher/storage/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
아뇨! (보통은)기본설정은 local, 테스트는 test로 기본으로 지정하는편인데요.
별도의 환경으로 실행하는경우는 Run시점에 프로파일을 준다는 의미였습니다. 

기본설정은 모든사람이 프로젝트를 동일한 환경으로 실행되어야하기 때문에 변경하지않습니다

2022-11-23 04:43 UTC, hongbin-dev commented on src/main/java/com/prgrms/springbootbasic/voucher/VoucherManager.java
>          voucherStorage.save(voucher);
mock을 쓸 필욘 없지않나요?

2022-11-23 04:44 UTC, hongbin-dev approved these changes
수고하셨습니다 환님!

2022-11-23 04:44 UTC, merged

2022-11-23 09:04 UTC, hwankim123 commented on src/main/java/com/prgrms/springbootbasic/voucher/VoucherManager.java
>          voucherStorage.save(voucher);
아아 단위테스트를 하려면 mock를 써야할 것 같아서 였습니다!