[3기-C] 이수영 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #588
Opened 2022-11-19 13:16 UTC by twotwobread

## 📌 과제 설명 
콘솔을 이용한 바우처 관리 애플리케이션입니다.

## 👩‍💻 요구 사항과 구현 내용 
## 🥇 요구 사항
- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x]  특정 고객에게 바우처를 할당할 수 있습니다.
- [x]  고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x]  고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x]  특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 🥈 구현내용
![image](https://user-images.githubusercontent.com/78334910/202852118-8c221412-91da-4906-8328-35f8b09c476f.png)
- ` Application` : springboot를 실행하는 클래스
- `CommandLineController` : 사용자로 부터 입력받은 Command에 따라 그에 맞는 로직 수행을 위한 클래스
- `CommandType` : Command가 수행할 로직과 특정 Command에서 출력할 메시지를 가지고 있는 Enum 클래스
- `ConsoleIO` : 사용자로부터 입출력을 하기 위한 클래스
- `ValidatorUtil` : 검증을 위한 유틸 클래스
- `VoucherService` : Voucher 조회, 생성 그리고 VoucherWallet과 관련된 로직을 수행하는 서비스 클래스
- `CustomerService` : Customer 조회, 검색과 관련된 로직을 수행하는 서비스 클래스
- `VoucherRepository` : Voucher 저장을 위한 Repository 인터페이스 , 구현체 : 파일, 메모리, JDBC
- `CustomerRepository` : Customer 저장을 위한 Repository 인터페이스, 구현체 : JDBC
- `Voucher` : Voucher에 관한 상태, 기능을 가진 추상 클래스
- `FixedAmountVoucher` : 고정된 할인 금액을 가진 Voucher 하위 클래스
- `PercentDiscountVoucher` : 할인율을 가진 Voucher 하위 클래스
- `VoucherBuilder` : Voucher 생성을 위한 빌더 클래스
- `VoucherType` : Voucher에 관한 Enum 클래스
- `Customer` : Customer에 관한 상태, 기능을 가진 클래스

## ✅ PR 포인트 & 궁금한 점 
- VoucherBuilder 를 사용했는데 UUID를 넣으면서도 만들고 싶고 인자로 안넣으면서도 만들고 싶은데 그런 식으로 구현하려면 너무 많은 생성자 오버로딩이 필요하여 이를 사용했습니다. 옳게 사용한 걸까요??
- Test를 나름대로 짜봤는데 커버리지가 부족한 부분이나 질적으로 부족한 부분이 있을까요?

2022-11-25 10:47 UTC, Seongjun-Kwon commented on src/main/java/org/prgrms/kdt/customer/CustomerService.java
> +                    .orElseThrow(() -> new NotPresentInRepositoryException("입력된 customer ID가 존재하지 않습니다."));
customerRepository.findById 안에서 값이 없으면 NotPresentInRepositoryException 예외를 던져주게 되어 있는데, 여기서도 .orElseThrow 를 할 필요가 없지 않을까요?

2022-11-25 10:47 UTC, Seongjun-Kwon commented on src/main/java/org/prgrms/kdt/model/customer/Customer.java
> +    private final boolean isBlacklist;
고객을 블랙리스트로 변경하지 못하는 것인가요?

2022-11-25 10:47 UTC, Seongjun-Kwon commented on src/main/java/org/prgrms/kdt/model/voucher/Voucher.java
> +        this.discountAmount = Double.parseDouble(discountAmount);
validate 메서드 안에서 string 타입의 discountAmount 를 double 형으로 변환하는 로직이 있던데, validate 메서드의 반환값을 double 로 하면 이곳에서 한번 더 변환해주지 않아도 될 것같아요!

2022-11-25 10:47 UTC, Seongjun-Kwon commented on src/main/java/org/prgrms/kdt/model/voucher/Voucher.java
> +    private final String voucherType;
VoucherType 을 enum 으로 따로 정의해주셨는데, String 으로 관리하는 이유가 궁금합니다!

2022-11-25 10:47 UTC, Seongjun-Kwon commented on src/main/java/org/prgrms/kdt/model/voucher/VoucherBuilder.java
> +    private LocalDateTime createdAt;
Builder 가 바우처 관련 정보를 가지고 있지 않아도 될 것 같아요! 바우처 정보를 가지고 그것을 바탕으로 바우처를 만들면 새로운 바우처를 생성할 때마다 새로운 VoucherBuilder 를 생성해줘야하지않나요?

2022-11-25 10:47 UTC, Seongjun-Kwon commented on src/main/java/org/prgrms/kdt/voucher/JdbcVoucherRepository.java
> +    }
repository 마다 사용되니까 따로 분리해보는 것은 어떨까요?

2022-12-07 04:41 UTC, twotwobread commented
Docker 환경설정 방법을 README와 PR에 적었습니다. 만약 안되는 부분이 있다면 말해주시면 감사하겠습니다!!

2022-12-07 16:13 UTC, samkimuel requested changes
고생하셨어요 수형님👍
코멘트 달았으니 확인해주세요!

1. VoucherBuilder 를 사용했는데 UUID를 넣으면서도 만들고 싶고 인자로 안넣으면서도 만들고 싶은데 그런 식으로 구현하려면 너무 많은 생성자 오버로딩이 필요하여 이를 사용했습니다. 옳게 사용한 걸까요??
-> 역으로 질문드리고 싶은게 있습니다 ㅎㅎ 많은 생성자를 만드는 게 왜 좋아보이지 않다고 생각하시나요? 또, builder 패턴을 시도해보신 것 같은데 https://johngrib.github.io/wiki/pattern/builder 요기 참고해보시면 좋을 것 같아요!
2. Test를 나름대로 짜봤는데 커버리지가 부족한 부분이나 질적으로 부족한 부분이 있을까요?
-> 도메인에 대한 테스트를 작성해주시면 좋을 것 같습니다. 그리고 예외 케이스에 대한 테스트도 추가하면 아주 좋습니다.
3. VoucherService나 CustomerService에서 블랙리스트 조회하는 로직, 특정 손님이 보유한 바우처 조회하는 로직 등과 같은 부분에서 존재하는 모든 바우처, 손님을 찾는 로직을 이용해 filter를 통해 걸러냈는데 최대한 존재하는 로직을 이용해서 짜고 싶었고 이런 SQL 하나하나 메서드로 만들면 너무 방대해질것 같다는 생각이 들어서 이렇게 짰습니다. 이런 경우 성능이 많이 떨어질까요? Repository에서 이런 기능을 위해 데이터를 가져오는 메서드를 따로 만드는것이 더 나을까요?
-> 100만건의 데이터를 가져온다고 가정하면 어떻게 하시겠어요?? 팀원분들이랑 같이 고민해보시고 댓글로 달아주시져🙂

2022-12-07 16:13 UTC, samkimuel commented on src/test/java/org/prgrms/kdt/service/CustomerServiceTest.java
> +        Assertions.assertThat(allBlacklist).filteredOn(Customer::isBlacklist);
.filteredOn() 이후 검증부가 필요합니다!

2022-12-11 06:08 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/customer/CustomerService.java
> +                    .orElseThrow(() -> new NotPresentInRepositoryException("입력된 customer ID가 존재하지 않습니다."));
아하 수정하겠습니다!!

2022-12-11 06:12 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/model/customer/Customer.java
> +    private final boolean isBlacklist;
요구사항에 블랙리스트 관리에 관한 부분이 없어서 현재 해당하는 로직이 존재하지 않습니다.

2022-12-11 06:18 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/model/voucher/Voucher.java
> +    private final String voucherType;
String으로 관리하는게 DB에 저장하거나 가져올 때 더 쉽지 않을까? 생각했는데 지금 생각하면 아닌것 같고 개선해보겠습니다!!

2022-12-11 06:25 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/voucher/JdbcVoucherRepository.java
> +    }
repository의 역할이 아니라고 생각이 됩니다!! 바꿔보겠습니다아!!

2022-12-11 06:55 UTC, twotwobread commented
> 고생하셨어요 수형님👍 코멘트 달았으니 확인해주세요!
> 
> 1. VoucherBuilder 를 사용했는데 UUID를 넣으면서도 만들고 싶고 인자로 안넣으면서도 만들고 싶은데 그런 식으로 구현하려면 너무 많은 생성자 오버로딩이 필요하여 이를 사용했습니다. 옳게 사용한 걸까요??
>    -> 역으로 질문드리고 싶은게 있습니다 ㅎㅎ 많은 생성자를 만드는 게 왜 좋아보이지 않다고 생각하시나요? 또, builder 패턴을 시도해보신 것 같은데 https://johngrib.github.io/wiki/pattern/builder 요기 참고해보시면 좋을 것 같아요!
> 2. Test를 나름대로 짜봤는데 커버리지가 부족한 부분이나 질적으로 부족한 부분이 있을까요?
>    -> 도메인에 대한 테스트를 작성해주시면 좋을 것 같습니다. 그리고 예외 케이스에 대한 테스트도 추가하면 아주 좋습니다.
> 3. VoucherService나 CustomerService에서 블랙리스트 조회하는 로직, 특정 손님이 보유한 바우처 조회하는 로직 등과 같은 부분에서 존재하는 모든 바우처, 손님을 찾는 로직을 이용해 filter를 통해 걸러냈는데 최대한 존재하는 로직을 이용해서 짜고 싶었고 이런 SQL 하나하나 메서드로 만들면 너무 방대해질것 같다는 생각이 들어서 이렇게 짰습니다. 이런 경우 성능이 많이 떨어질까요? Repository에서 이런 기능을 위해 데이터를 가져오는 메서드를 따로 만드는것이 더 나을까요?
>    -> 100만건의 데이터를 가져온다고 가정하면 어떻게 하시겠어요?? 팀원분들이랑 같이 고민해보시고 댓글로 달아주시져🙂

1. 많은 생성자를 만드는 게 좋지 않다고 생각한 이유는 지저분해 보인다고 느꼈고 또 3개의 인자를 받는 생성자가 있는데 2개를 받으면서 인스턴스를 생성하고 싶다라고 생각하면 생성자를 하나 더 만들어야 하는게 별로다라고 느껴서 빌더를 이용하면 내가 원하는 필드만을 받으면서 더 유연성 있게 만들 수 있지 않을까 생각했습니다.
2. 도메인에 대한 테스트라 함은 도메인이 가진 기능들을 테스트하면 될까요?? 예를 들면, 특정 도메인을 만들데 validate가 도메인 객체 내부에 메서드를 가지고 있다면 이를 테스트하면 될까요??
3. 팀원들과 얘기해본 결과 현재처럼 작은 프로젝트에서는 똑같겠지만 데이터가 많아질수록 큰 차이가 날 것 같다는 얘기가 나왔습니다. JPA가 쿼리를 만들어주는 것처럼 JDBC에서도 어떤 기능을 구현해야한다면 쿼리를 만드는 것이 맞는 것 같다고 느꼈습니다!!

2022-12-12 17:00 UTC, Seongjun-Kwon approved these changes

2022-12-27 10:22 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/customer/CustomerService.java
> +                .collect(Collectors.toList());
JDK 16 버전부터 이 기능이 생겼군요!! 참고하겠습니다아!!

2022-12-27 10:32 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/customer/CustomerService.java
> +        } catch (IllegalArgumentException e) {
bytes를 uuid로 바꾸는 부분을 유틸 클래스로 떼냈는데 그것처럼 유틸 클래스에 String을 uuid로 바꾸는 메서드도 따로 만들어서 예외를 잡게 만들었습니다.

2022-12-27 10:34 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/presentation/controller/CommandType.java
> +    private final static String CUSTOMER = "Customer";
컨벤션을 많이 실수했네요 ㅠㅠ

2022-12-27 10:38 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerRepository.java
> +    private Map<String, Object> toParamMap(Customer customer) {
명환님께서는 함께 이용되는 메서드가 근처에 존재하는 것보다 메서드가 접근지정자에 따라서 배열되는 방법을 더 선호하시나요??

2022-12-27 10:43 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerRepository.java
> +        jdbcTemplate.update("TRUNCATE FROM customers", Collections.emptyMap());
delete를 이용해서 모든 데이터를 삭제하는 거보다 truncate가 더 빠르니까 이걸로 클리어해야겠다고 생각했습니다. 하지만 truncate는 ddl이고 delete는 dml 이란 차이가 있고 truncate를 이용하면 트랜잭션에서 관리되지 않아서 롤백이 불가능하다는 점이 있으면 만약 soft하게 삭제를 해도 truncate는 데이터가 그냥 삭제되겠지만 delete는 soft 삭제가 가능하겠다는 생각이 들었습니다. 감사합니다아!!

2022-12-27 10:44 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/presentation/io/exception/WrongOutputDataException.java
> +    public WrongOutputDataException(String messge, IOException e) {
아이고 ㅠㅠ 죄송합니다 미처 확인못했네요,,, ㅠㅠㅠㅠ

2022-12-27 10:44 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/presentation/io/ConsoleIO.java
> +            throw new WrongInputDataException("Id Input 작업이 실패했습니다.", e);
stackTrace에 같이 담겼으면 해서 이런식으로 예외를 처리했습니다

2022-12-27 10:46 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/model/voucher/FixedAmountVoucher.java
> +            Double discountValue = Double.parseDouble(discountAmount);
이유가 없었던 것 같습니다,,, 고쳐보겠습니다아!!

2022-12-27 10:52 UTC, twotwobread commented on src/main/java/org/prgrms/kdt/voucher/VoucherService.java
> +            return voucherRepository.update(voucherById);
setter를 사용하는 것 자체가 캡슐화를 깨뜨린다는 생각이 듭니다. 그래서 voucher 내부에 ownedCustomerId를 삭제할 수 있는 메서드를 하나 따로 만들고 해당 메서드를 통해서 값을 바꾸는 것이 옳다는 생각이 듭니다.

2022-12-28 18:33 UTC, Seongjun-Kwon commented on src/main/java/org/prgrms/kdt/model/voucher/Voucher.java
> +        this.discountAmount = Double.parseDouble(discountAmount);
validate 가 double 을 반환해도 될 지 고민이라는 말씀이실까요? 아니면 validate 내에 변환 로직을 넣어도 될 지 고민이라는 말씀이실까요?

전자라면 저는 현재 로직에서는 double 을 반환해서 중복되는 변환 로직을 없애는 것이 낫다고 생각합니다. double 로 반환한다 하더라도 현재처럼 void 를 반환할 때보다 책임의 관점에서 크게 달라지는 것이 없다고 생각됩니다. 요구사항에서 discountAmount 타입이 int 로 바뀐다고 했을 때, 어차피 validate 내에 변환 로직이 있기 때문에 validate 코드를 수정해줘야하기 때문입니다.

후자라면, 위에서 설명한 이유때문에 validate 코드 내에 변환 로직이 있는 것이 좋지 않다고 생각합니다. validate 가 현재는 discountAmount 를 String 으로 받고 있는데 이를 DiscountAmount 라는 클래스를 만들어서 받고 변환 로직을 Voucher 를 생성하는 사용 코드 쪽으로 넘기면, validate 내에서 변환 로직을 없애면서 discountAmount 의 타입이 변경되더라도 DiscountAmount 클래스만 변경해주면 될 것 같습니다.

2023-01-01 08:30 UTC, samkimuel commented on src/main/java/org/prgrms/kdt/customer/JdbcCustomerRepository.java
> +    private Map<String, Object> toParamMap(Customer customer) {
저는 그런 것 같은데, 컨벤션에 따라 갈리겠군요.(제 욕심을 섞은 리뷰인 것 같네요🥲)
이후 팀프로젝트 하시면서 컨벤션 만드셔서 컨벤션에 맞게 진행하면 될 것 같습니다.👍

2023-01-02 10:51 UTC, twotwobread commented on src/test/java/org/prgrms/kdt/dao/repository/customer/JdbcCustomerRepositoryTest.java
> +        assertThat(insertCustomer.getCustomerId(), is(customer.getCustomerId()));
맞습니다. 그게 더 옳은 방법인 것 같습니다!!

2023-06-05 18:40 UTC, closed without merging