[3기-C] 박세준 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #589
Opened 2022-11-20 04:30 UTC by park-se-jun

## 📌 과제 설명 

application-db 로 springboot의 datasorce를 설정해 줘야 합니다.
schema.sql을 실행시켜야 합니다.
profile은 db로 설정해줘야 합니다.
DB : MySQL 8.0
Java: java 17
## 👩‍💻 요구 사항과 구현 내용 
- [ ]  voucher
  - [ ] db로 관리하는 VoucherNamedJdbcRepository 생성  (create, read, delete)
  - [ ]  voucherRepository Test 코드 작성
- [ ] customer
  - [ ]  customer model 수정
      - [ ]  customer 에 createdAt과 LoginAt, isBlackCustomer 추가
      - [ ] (기존에는 blackList 만 고려했음, blackList를 고려한 customer는 별개의 모델로 뺐음)
  -  [ ] db로 관리하는 CustomeNamedJdbcrRepository 생성(create, read, update, delete)
  -  [ ] CustomerRepository Test코드 작성
- [ ]  BlackCustomer
  - [ ] blackCustomer 모델 생성
  - [ ] blackCustomer를 다루는 BlackListRepository를 인터페이스로 만듦
  - [ ] db로 관리하는 BlackLIstJdbcRepository 생성(read)
- [ ]  wallet
  - [ ]  customer와 voucher 사이의 관계를 나타내는 wallet 모델 생성
  - [ ] wallet을 다루는 WalletRepository 인터페이스를 생성
  - [ ] db로 wallet을 다루는 WalletNamedJdbcRepository 생성 (create, read, delete)
  - [ ] WalletNamedJdbcRepository 생성
- [ ]  패키지 정리 
  - [ ] voucher, customer, blacklist, wallet 과 같은 domain 코드를 domain 패키지의 하위로 이동
- [ ] 더미데이터를 넣는 SQL문 생성

console application에 repository를 다루는 service를 추가하라는 요구사항은 없었기때문에 해당 내용(Service)에 대한 구현사항은 없습니다. (프로그램을 실행시키고 customer를 추가하거나 , wallet을 추가, 조회할 수 없습니다.)
db erd
![바우쳐 관리 프로그램 erd](https://user-images.githubusercontent.com/28258648/202885347-d2c1a90b-8045-4462-a75a-cdb992af36da.png)

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 학습 질문 채널에도 올렸던 내용인데, custoemer ID로 voucher를 조회하는 기능을 할 때 wallet Repository에서 voucherId를 주는것과 voucher를 주는것중 어떤게 더 나은 방안인가요?
- Wallet의 네이밍이 조금 애매한것 같습니다. voucher와 Customer의 관계를 나타내는 테이블을 다루는 객체인데, table 명도 현재 wallet인 상태입니다. N:M 관계에서 관계형 테이블의 이름은 보통 관계를 맺는 두 테이블의 이름을 이어서 voucher_customer 정도로 한다고 하는데 그럼 그 테이블의 엔티티는 VoucherCustomer가 되는건가요?

2022-11-25 09:34 UTC, rhdtn311 commented on src/main/java/org/prgrms/kdtspringdemo/commandline_application/CommandLineApplication.java
> +    //    private final CustomerService customerService;
사용하지 않는 주석은 제거해주세요.

2022-11-25 09:46 UTC, rhdtn311 commented on src/main/java/org/prgrms/kdtspringdemo/domain/voucher/model/PercentDiscountVoucher.java
> +    private boolean voucherAllow(Long value) {
메소드 이름만 봤을 때 어떤 역할을 하는지 잘 모르겠습니다.

2022-11-25 09:47 UTC, rhdtn311 commented on src/main/java/org/prgrms/kdtspringdemo/domain/voucher/repository/VoucherNamedJdbcRepository.java
> +    //    private static final String UPDATE_SQL = "";
사용하지 않는 주석 제거 해주세요.

2022-11-25 09:48 UTC, rhdtn311 commented on src/main/java/org/prgrms/kdtspringdemo/domain/voucher/repository/VoucherRepository.java
> +//    Voucher update(Voucher voucher);
사용하지 않은 주석 제거해주세요.

2022-11-25 09:57 UTC, rhdtn311 commented on src/main/java/org/prgrms/kdtspringdemo/domain/voucher/VoucherService.java
> +        }
1) Optional을 더 활용하여 if문을 줄일 수 있을 것 같습니다.
2) null을 반환하는 것은 위험하지 않을까요 ?

2022-11-25 10:23 UTC, rhdtn311 commented on src/main/java/org/prgrms/kdtspringdemo/domain/voucher/repository/VoucherNamedJdbcRepository.java
> +            logger.error("중복되는 ID 입니다.", e);
단순 궁금한건데 DB를 조작하다 발생한 예외를 DB에서 받아서 처리하는 것이 좋을까요 아니면 로직으로 미리 확인하는 것이 좋을까요? 같이 얘기해보면 좋을 것 같아요.

2022-12-28 09:14 UTC, samkimuel requested changes
세준님 고생하셨습니다. 늦게 리뷰드려 죄송합니다 ㅠㅠ
코멘트 달았으니 확인해주세요!

- 학습 질문 채널에도 올렸던 내용인데, custoemer ID로 voucher를 조회하는 기능을 할 때 wallet Repository에서 voucherId를 주는것과 voucher를 주는것중 어떤게 더 나은 방안인가요?
-> 어떤 목적으로 정보를 조회하냐에 따라 다를 것 같네요!
- Wallet의 네이밍이 조금 애매한것 같습니다. voucher와 Customer의 관계를 나타내는 테이블을 다루는 객체인데, table 명도 현재 wallet인 상태입니다. N:M 관계에서 관계형 테이블의 이름은 보통 관계를 맺는 두 테이블의 이름을 이어서 voucher_customer 정도로 한다고 하는데 그럼 그 테이블의 엔티티는 VoucherCustomer가 되는건가요?
-> 네이밍에 정답은 없고, 도메인에 따라 네이밍이 바뀔 수 있을 것 같아요.

2022-12-28 09:14 UTC, samkimuel commented on src/test/java/org/prgrms/kdtspringdemo/customer/repository/CustomerRepositoryTest.java
> +    }
여긴 아직 완성이 안된건가요??

2023-06-05 18:40 UTC, closed without merging