V2
prgrms-be-devcourse/springboot-basic pull request #590
Opened 2022-11-20 09:04 UTC by rhdtn311

## 📌 과제 설명 
Spring 2주차 미션입니다.

- 명령어
  - `create` : 바우처를 생성합니다.
  - `list` : 모든 바우처 리스트를 출력합니다.
  - `customer vouchers list` : 입력한 이메일의 Customer가 가지고 있는 모든 바우처를 출력합니다.
  - `create customer` : Customer를 생성합니다.
  - `show customers` : 모든 Customer를 출력합니다.
  - `delete` : 입력한 이메일의 Customer가 가지고 있는 모든 바우처를 제거합니다.
  - `voucher owner` : 입력한 바우처ID를 가지고 있는 Customer를 조회합니다.
  - `exit` : 프로그램을 종료합니다.
  - `blacklist` : 블랙리스트를 출력합니다.
 
- 기본 profile 적용 시 jdbcVoucherRepository가 적용됩니다.

- DataSource는 `DatabaseConfiguration` 클래스에서 설정할 수 있습니다.
- `Customer`, `Voucher`를 DB에 저장하는데 사용될 테이블 생성 SQL 문은 test/src/resources/schema에 작성되어 있습니다. (Customer와 Voucher를 1:N 관계로 생각하여 작성하였습니다.)

## 👩‍💻 요구 사항과 구현 내용
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x]  특정 고객에게 바우처를 할당할 수 있습니다.
- [x]  고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x]  고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x]  특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

![image](https://user-images.githubusercontent.com/68289543/202890687-f1548c3f-bc74-4697-94c1-947ae73afd71.png)

## ✅ PR 포인트 & 궁금한 점 
- `CustomerService`처럼 `Customer`와 관련된 서비스를 하나의 클래스로 묶는 것과 `VoucherService`처럼 기능 별로 세분화를 하는 것 중 일반적으로 어떻게 하는지 궁금합니다. (저는 바우처 관리 애플리케이션이기 때문에 `Voucher`와 관련된 기능이 많이 추가될 것 같아서 `VoucherService`는 기능별로 세분화 했습니다.)

2022-11-25 09:39 UTC, twotwobread commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +    @Autowired
생성자가 하나일 때 @Autowired 어노테이션을 붙이지 않아도 DI가 된다고 합니다.

2022-11-25 09:41 UTC, twotwobread commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +        return jdbcTemplate.queryForObject(COUNT_SAME_EMAIL_SQL, Map.of("email", email), countRowMapper) > 0;
customer가 존재하는지 여부를 확인하기 위해서 customerId가 아니라 email로 확인을 하는 특별한 이유가 있는지 궁금합니다.

2022-11-25 09:50 UTC, twotwobread commented on src/main/java/org/prgrms/vouchermanagement/io/Console.java
> +    public void printCustomers(List<Customer> customers) {
Customer랑 Voucher의 출력 로직이 다르지 않다면 제너릭을 이용해서 하나의 메서드로 합치는 것도 괜찮을 것 같습니다.

2022-11-25 09:55 UTC, twotwobread commented on src/main/java/org/prgrms/vouchermanagement/io/InputValidator.java
> +        if (!customerName.matches(RegexConstant.NAME_REGEX)) {
생성 비용이 비싼 객체는 캐싱을 통한 재사용을 하는 것이 더 좋을 것 같습니다.
https://developer-hm.tistory.com/99

2022-11-25 10:10 UTC, twotwobread commented on src/main/java/org/prgrms/vouchermanagement/voucher/domain/Voucher.java
>  public interface Voucher {
Voucher를 인터페이스로 구현한 이유가 있을까요? 내부적으로 구현체들이 같은 상태와 메서드를 가지고 있다는 생각이 들어서 인터페이스를 통해서 구현을 반복하는 것보다 상속을 이용해서 반복적인 코드를 줄이는 것도 괜찮지 않을까라는 생각이 들었습니다.

2022-11-25 10:23 UTC, twotwobread commented on src/main/java/org/prgrms/vouchermanagement/voucher/domain/VoucherType.java
>      public static boolean isCorrectVoucherType(String voucherTypeInput) {
isMatchVoucherType과 같이 클래스 내부적으로만 사용되는 메서드는 private로 두는 것이 좋을 것 같고 취향에 따라 다르겠지만 검증하는 메서드는 외부로 하나만 드러나고 해당 메서드에 값을 넣으면 알아서 검증해준다는 느낌으로 외부에 드러나는 검증 메서드가 단일화되는 것도 좋을 것 같습니다.

2022-11-25 10:27 UTC, twotwobread commented on src/main/java/org/prgrms/vouchermanagement/CommandLineApplication.java
>      void run() {
의도한 부분이 아니라면 public을 붙이는 것도 좋을 것 같습니다.

2022-11-25 10:28 UTC, twotwobread commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/BlackListFileRepositoryTest.java
> +    private final String path = "src/test/resources/test_customer_blacklist.csv";
상수로의 표현이라면 static을 붙이는 것도 좋아보입니다.

2022-11-25 10:34 UTC, twotwobread reviewed
태현이형 과제한다고 고생했어!!ㅠㅠ

2022-12-20 17:55 UTC, samkimuel requested changes
태현님 수고많으셨어요!
코멘트 확인해주세요!

- CustomerService처럼 Customer와 관련된 서비스를 하나의 클래스로 묶는 것과 VoucherService처럼 기능 별로 세분화를 하는 것 중 일반적으로 어떻게 하는지 궁금합니다. (저는 바우처 관리 애플리케이션이기 때문에 Voucher와 관련된 기능이 많이 추가될 것 같아서 VoucherService는 기능별로 세분화 했습니다.)
-> 지금은 단순해서 하나로 묶어도 상관없을 것 같은데, 생각하신 것처럼 기능이 많이 추가되면 분리하셔도 됩니다.(자유) 저는 다 분리하진 않고 CUD/R 정도로 분리해요. 분리할 때 구조를 잘 생각하시는게 좋아요.(순환참조 문제 조심!)

2022-12-20 17:55 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/domain/VoucherType.java
> +    private final TriFunction<UUID, Integer, UUID, Voucher> voucherConstructor;
함수형 인터페이스 정의👍

2022-12-20 17:55 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +                            VoucherVO.of(UUID.fromString(infoArr[0]), infoArr[1], Integer.parseInt(infoArr[2]), UUID.fromString(infoArr[3]))));
변환, 매핑 작업을 서로 다른 객체에서 해주려고 하니까 복잡해진 것 같아요.
stream map을 사용하면 더 간결해질 것 같네요!

2022-12-20 17:55 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +        try (BufferedWriter writer = new BufferedWriter(new FileWriter(new File(path), true))) {
```suggestion
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(path, true))) {
```
fileName을 파라미터로 바로 받을 수 있네요

2022-12-20 17:55 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +                    .map(voucherInfo -> createVoucher(voucherInfo.split(",")))
split(",")이 자주 보이네요 ㅎㅎ
반복을 줄여보시죠!

2022-12-20 17:55 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +                    .forEach(voucherInfo -> voucherListTemp.append(voucherInfo).append("\n"));
위에서는 lineSeperator() 쓰신 것 같은데 통일하시면 좋을 것 같아요

2022-12-20 17:55 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +                    .filter(voucherInfo -> !voucherInfo.split(",")[3].equals(customerId.toString()))
매직넘버가 계속 보이네요. 상수로 정의하는 게 어떨까요?

2022-12-20 17:55 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/JdbcVoucherRepository.java
> +            System.out.println("존재하지 않는 바우처입니다.");
exception처리나 로그로 남기는 게 좋을 것 같아요~

2022-12-20 17:55 UTC, samkimuel commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/BlackListFileRepositoryTest.java
> +            for (int i = 0; i < blackCustomers.size(); i++) {
foreach문으로 수정해도 되겠네요.
https://jaehun2841.github.io/2019/02/28/effective-java-item58/

2022-12-20 17:55 UTC, samkimuel commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +    @DisplayName("찾는 아이디가 없는 경우")
이메일로 찾는거로 보이네요!

2022-12-20 17:55 UTC, samkimuel commented on src/test/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +    void updateName() {
이 테스트는 ParameterizedTest를 이용해서 테스트해볼까요?

2022-12-20 17:55 UTC, samkimuel commented on src/test/java/org/prgrms/vouchermanagement/io/CommandTest.java
> +    void correctInputMatch() {
여기도 ParameterizedTest 로 테스트해보시죠!

2022-12-22 08:19 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/io/InputValidator.java
> +        return customerEmail;
제 기억상 `Console` 클래스에서 `inputValidator.validateEmail(scanner.nextLine())` 으로 한번에 반환해주기 위함이었던 것 같습니다. 그런데 검증 메소드의 반환 타입이 검증했던 문자열인게 조금 이상한 것 같기도 합니다. `boolean` 타입이나 `void`로 아무것도 반환하지 않는게 더 좋은 방법일까요 ?

2022-12-22 08:57 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +            return Optional.of(jdbcTemplate.queryForObject(FIND_BY_ID_SQL, Map.of("customerId", customerId.toString().getBytes()), customerRowMapper));
> Optional.of 와 Optional.ofNullable의 차이가 뭔지 아실까요?? 쿼리 수행 결과로 아무것도 없을 때 어떻게 되나요??

`Optional.of()`는 입력값이 `null`이면 `NullPointerException`을 일으키고, `Optional.ofNullable()`은 입력값이 `null`이어도 값이 받아집니다. (empty) 

이 코드에서 Jdbc의 `queryForObject()` 메소드는 DB에서 값을 조회했을 때 아무것도 조회되지 않는다면 `null`이 아닌 EmptyResultDataAccessException이 발생한다고 하여 `ofNullable()`로 처리해주지 않았습니다!

2022-12-22 14:08 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/io/InputValidator.java
> +        return customerEmail;
if문에 걸리면 throw 해주고 있으니까 굳이 boolean을 반환하지 않고 void로도 충분할 것 같아요

2022-12-22 19:17 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +                            VoucherVO.of(UUID.fromString(infoArr[0]), infoArr[1], Integer.parseInt(infoArr[2]), UUID.fromString(infoArr[3]))));
> 변환, 매핑 작업을 서로 다른 객체에서 해주려고 하니까 복잡해진 것 같아요. stream map을 사용하면 더 간결해질 것 같네요!

`infoArr`을 `stream.map`을 사용하여 `VoucherVO`를 만들 수 있다고 말씀 하신걸로 이해하면 될까요 ??

2022-12-23 07:12 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +        return jdbcTemplate.queryForObject(COUNT_SAME_EMAIL_SQL, Map.of("email", email), countRowMapper) > 0;
> customer가 존재하는지 여부를 확인하기 위해서 customerId가 아니라 email로 확인을 하는 특별한 이유가 있는지 궁금합니다.

사용자 입장에서 customer를 검색할 때 uuid 보다 email 을 입력하는 것이 더 편리할 것 같다고 생각했습니다 !

2022-12-23 08:30 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/voucher/domain/VoucherType.java
>      public static boolean isCorrectVoucherType(String voucherTypeInput) {
> isMatchVoucherType과 같이 클래스 내부적으로만 사용되는 메서드는 private로 두는 것이 좋을 것 같고 취향에 따라 다르겠지만 검증하는 메서드는 외부로 하나만 드러나고 해당 메서드에 값을 넣으면 알아서 검증해준다는 느낌으로 외부에 드러나는 검증 메서드가 단일화되는 것도 좋을 것 같습니다.

혹시 VoucherValidator 같은 클래스를 만들어서 검증하는 것이 좋다고 하신 걸까요 ??

2022-12-23 08:33 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/CommandLineApplication.java
>      void run() {
> 의도한 부분이 아니라면 public을 붙이는 것도 좋을 것 같습니다.

어떤 이유 때문인가요 ?? 궁금합니다 !!

2022-12-26 16:23 UTC, samkimuel commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +                            VoucherVO.of(UUID.fromString(infoArr[0]), infoArr[1], Integer.parseInt(infoArr[2]), UUID.fromString(infoArr[3]))));
39라인 vouchers 에서 처리하면 어떨까 생각해봤어요.
그리고 VoucherVO 클래스는 꼭 필요한건가요??

2022-12-26 20:00 UTC, rhdtn311 commented on src/main/java/org/prgrms/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +                            VoucherVO.of(UUID.fromString(infoArr[0]), infoArr[1], Integer.parseInt(infoArr[2]), UUID.fromString(infoArr[3]))));
> 39라인 vouchers 에서 처리하면 어떨까 생각해봤어요. 그리고 VoucherVO 클래스는 꼭 필요한건가요??

createVoucher()에 인자가 4개인게 가독성이 떨어질 것 같아서 만들었는데 말씀 듣고 생각해보니 오히려 복잡도만 증가한 것 같습니다. 수정하겠습니다!

2023-06-05 18:40 UTC, closed without merging