[3기-C] 김선호 SpringBoot Part2 Weekly Mission 제출합니다. (1차)
prgrms-be-devcourse/springboot-basic pull request #595
Opened 2022-11-20 20:00 UTC by preferKim

## 📌 과제 설명 
- 단위 테스트 작성
- Customer 에 대한 Create, Read 구현
- Voucher CRUD 구현

## 👩‍💻 요구 사항과 구현 내용 

### 단위 테스트

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - [ ] 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - [x] 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.

### Customer

- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - [x] customers 테이블 정의 및 추가
        - [x] (콘솔) customer의 name을 입력
        - [x] 입력 받은 name을 DB에서 조회
            - [x] name 이 DB에 존재하지 않으면 자동으로 생성
    - [x] CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
        - [x] 입력받은 name 저장 (primary key 는 auto generated key를 사용)

### 바우처를 DB로 관리

- [x]  (1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - [x]  바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - [x]  바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - [x]  기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
        - [x]  Create: 바우처를 DB에 저장
        - [x]  Read: 저장된 모든 바우처 조회
        - [x]  Update: 바우처의 할인 금액 또는 비율 수정
            - [x] 고정 금액 할인 바우처의 금액 수정
            - [x] 고정 비율 할인 바우처의 비율 수정
        - [x]  Delete: 저장된 모든 바우처 삭제

## ✅ 피드백 반영사항  

- 이전 PR의 피드백 반영사항을 코멘트로 남기겠습니다!
- 패키지 구조를 자주 변경하다 보니 file changed 수가 너무 많네요..😭 더 작은 단위의 PR이 될 수 있게 유의하겠습니다!

## ✅ PR 포인트 & 궁금한 점 

- 테스트 코드에서의 어노테이션 활용이나 테스트 코드 작성 방식에 대해 전반적으로 피드백 받고 싶습니다!
- 어떤 클래스의 특정 기능을 테스트 하고 싶다면, 해당 클래스의 테스트 클래스에서만 테스트 하는 것이 일반적인 것인지 궁금합니다.
  -  예) Foo.class 의 foo() 기능을 테스트하고 싶다면, 해당 기능을 FooTest.class 에서만 테스트 코드를 작성

2022-11-20 20:54 UTC, preferKim reviewed
@hongbin-dev  @seung-hun-h 

이전 PR에서의 반영했던 피드백과 궁금한 점을 코멘트로 남겼습니다. 확인해주시면 감사하겠습니다!
미처 반영하지 못했던 리뷰도 꾸준히 적용하며 개선시켜나가겠습니다.☺️

2022-11-20 20:54 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/view/FileManager.java
> +            );
[다른 표준 예외를 사용해보기](https://github.com/prgrms-be-devcourse/springboot-basic/pull/570#discussion_r1022315162) 에 대한 피드백을 적용해봤습니다.
FileWriter 객체를 생성하는 과정에서 체크 예외로 IOException을 catch하지만, 근본적으로 파라미터로 받는 file에 문제가 있어 해당 예외가 발생한다고 판단하여 IllegalArgumentException을 날리도록 처리해주었습니다. 이런 방식으로 처리해도 괜찮을까요?

2022-11-20 20:54 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/repository/util/VoucherContentsConverter.java
> +    public static String toContents(Voucher voucher, String messageFormat) {
[스프링 빈으로 등록해야하는가](https://github.com/prgrms-be-devcourse/springboot-basic/pull/570#discussion_r1022316447) 에 대한 피드백을 적용해봤습니다. 
- 단순히 바우처 객체를 텍스트로 변경해주는 역할만 하기 때문에, static 메서드로 수정하여 유틸 클래스처럼 사용하도록 하였습니다. 
- 스프링 빈으로 등록해야 하는 객체는 `의존관계 주입이 필요한 객체` 라고 생각하는데 그럼 `의존관계 주입이 필요한 객체`의 범위는 어디까지인지도 그 기준을 정하는 것도 애매한 것 같습니다. 
- 우선 상태를 가지는 객체는 무조건적으로 싱글톤으로 관리하지 않게 하려고는 하고 있는데, 멘토님들께서 생각하시는 '이건 스프링 빈으로 등록되어야해', '이건 스프링 빈으로 등록되면 안되지' 라고 할만한 기준이 따로 있을까요?

2022-11-20 20:54 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +            } catch (IllegalCommandException illegalCommandException) {
[`e` 보다 의미있는 변수명 지어보기](https://github.com/prgrms-be-devcourse/springboot-basic/pull/570#discussion_r1022421856) 에 대한 피드백을 적용해봤습니다.
- 기존에는 ItelliJ의 try catch 자동완성에 의해 단순히 `e` 로 사용하고 있었습니다. 
- 더 의미있는 이름으로 변경하기 위해 고민하다 우선 catch한 예외 클래스 타입을 나타내는 방식으로 작성해두었는데 멘토님들께서 보시기에는 어떤지 궁금합니다. 보통 위와 같은 경우에는 어떤 방식으로 네이밍을 하시나요?

2022-11-20 20:54 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +                );
[의미가 중복되는 로그는 삭제](https://github.com/prgrms-be-devcourse/springboot-basic/pull/570#discussion_r1022423514) 피드백을 적용해봤습니다.

- 예외를 위처럼 명시적으로 발생시키는 코드에서는 굳이 로그로 나타내지 않는게 좋을까요?
- 로그는 개발자들끼리 보기 위해 사용하는 걸로 알고있습니다. 멘토님들은 요새 어느 용도로 로깅을 남기시는지 궁금합니다.

2022-11-20 20:54 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/domain/VoucherEntity.java
> +    public VoucherEntity(String id, String type, Long amount, Long ratio, String customerName) {
FixedAmountVoucher, PercentDiscountVoucher 각각이 엔티티가 되는 것보다 이를 통합하여 하나의 엔티티로 만들면 관리가 편할 것이라 생각하여 새롭게 VoucherEntity 를 만들었습니다. 
- 도메인 그 자체(FixedAmountVoucher, PercentDiscountVoucher)가 엔티티가 되는 편이 좋았을까요?

2022-11-20 20:54 UTC, preferKim commented on src/test/java/prgms/vouchermanagementapp/domain/value/RatioTest.java
> +    }
ValueSource를 이용하여 값을 주고 있어 given-when-then 패턴의 `given`을 생략하였습니다. 
또한 특정한 예외가 발생하기를 바라는 테스트이다보니, when과 then을 한 번에 작성하게 되었습니다.
- 명시적으로 given을 사용하는 편이 가독성 측면에서 더 좋았을까요?
- given-when-then 패턴에 사고가 갇힌 느낌이 있습니다. 멘토님들께서는 따로 사용하시는 패턴이나 즐겨 사용하는 어노테이션이 있는지 궁금합니다!

2022-11-20 20:54 UTC, preferKim commented on src/test/java/prgms/vouchermanagementapp/service/CustomerManagerTest.java
> +    }
save() 기능이 동작하는 것을 확인했으므로, 같은 Customer에 대해 findCustomerByName() 을 실행하면 무조건 결과값이 있음을 단언하기 위해 `assert optionalCustomer.isPresent();` 처럼 사용했습니다. 
- 보통 테스트 코드에서도 assert 를 사용하는지 궁금합니다! 위 테스트 코드에서의 사용이 자연스러운가요? 
- public 메서드가 아닌, 공개되지 않은 메서드에서 파라미터의 값 등의 유효성을 검사하기 위해 assert를 사용(`아이템 49. 매개변수의 유효성을 검사하라`) 하는 것으로 알고있습니다. assert 문을 보통 어떻게 활용하고 계신지 궁금합니다!

2022-11-20 20:54 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +
[상태를 갖는 RunningState 객체를 싱글턴으로 관리되지 않게 하기](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#discussion_r1019051680) 피드백을 적용해봤습니다.
- run() 메서드에서 주입받는 runningState 인스턴스는 해당 메서드를 호출하는 [MainController](https://github.com/prgrms-be-devcourse/springboot-basic/pull/595/files#diff-7377bb463bf8090131528b7e0bc6a398d5ae20cdb57018f8afa1ddd8dbbd215d) 에서 주입해주는 방식으로 변경했습니다. 
- 이전 리뷰의 '여전히 상태가 공유된다' 라는 의미를 조금은 이해하게 된 것 같습니다. 지역 변수 등 '각 스레드에서만 유일하게 접근 가능한 객체를 생성' 하게 되면 조금 더 thread-safe 해지는 코드가 되는 거였군요!

2022-11-22 04:56 UTC, hongbin-dev requested changes
선호님 코드 잘 작성해주셨군요 👍 
피드백 남겼으니 확인해주세요!

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +                );
https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels

 이 부분을 읽어보시면 좋을 거 같아요.
 주로 info와 error를 많이 사용하는데, error같은경우는 저희가 예상하지못한(Exception e) 예외를 보내 장애알림을 받도록 합니다

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/domain/VoucherEntity.java
> +    public VoucherEntity(String id, String type, Long amount, Long ratio, String customerName) {
관리가 정말 편할까요 🤔 어떤 장단점이 있을까요?

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/repository/Customers.java
> +    private final SimpleJdbcInsert jdbcInsert;
👍

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/repository/JdbcVouchers.java
> +@Profile("release | test")
이거 동작하나요..? 
```suggestion
@Profile({"release", test"})
```

이렇게 작성해주셔야할 거 같습니다. 커맨드 + P로 파라미터 힌트를 봐보세요 ㅎㅎ

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/repository/JdbcVouchers.java
> +        }
DataAccessException는 어떨때 발생하나요?

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/repository/JdbcVouchers.java
> +            return template.query(sql, param, voucherEntityRowMapper());
`Map.of()` 불변 좋네요 👍

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/repository/JdbcVouchers.java
> +        template.update(sql, param);
이렇게 되면 실패해도 메서드는 성공하겠네요??

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/repository/util/EntityMapper.java
> +        }
https://stackoverflow.com/a/57432342

swtich를 적용해볼 수 있을 거 같아요.

2022-11-22 04:56 UTC, hongbin-dev commented on src/main/java/prgms/vouchermanagementapp/repository/JdbcVouchers.java
> +public class JdbcVouchers {
이 친구는 왜 인터페이스를 구현안할까요?

2022-11-22 04:56 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/domain/value/RatioTest.java
> +    }
기본적으로 given-when-then 형태로 작성하고 있습니다. 주석은 쓰지않고 개행으로만 컨텍스트를 나누고 있습니다.
최근에는 bdd기반 테스트를 많이 작성하는 거 같더라구요

2022-11-22 04:56 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/domain/value/RatioTest.java
> +    void should_throw_exception_for_invalid_range(Long number) {
👍 

IllegalArgumentException가 발생한다보단, `예외가 발생한다` 라는 텍스트를 선호해요.
예외가 변경되면 DisplayName은 따라오지못하거든요.

2022-11-22 04:56 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/domain/value/AmountTest.java
> +    @MethodSource("providePositiveIntegers")
MethodSource는 메서드를 한번 타러가야해서 가독성이 떨어진다고 생각해요. (연습으로 하셨다면 나두셔도 됩니다!)
value source로 해결가능해보이네요.

2022-11-22 04:56 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/repository/JdbcVouchersTest.java
> +        jdbcVouchers.updateFixedAmountVoucherById(originalVoucherEntity.getId(), changedAmount);
`jdbcVouchers.updateFixedAmountVoucherById(originalVoucherEntity.getId(), changedAmount);`
이 친구만 when에 해당하겠네요.

2022-11-22 04:56 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/repository/JdbcVouchersTest.java
> +        assertThat(foundVoucherEntity.get().getAmount()).isEqualTo(changedAmount);
여기 테스트가 조금 복잡하네요.
결과값은 미리 추출해서 assert문에서는 

```suggestion
        assertThat(actual).isEqualTo(2000);
```
이런식으로 표현하는게 읽기 좋더라구요.

2022-11-22 04:56 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/service/CustomerManagerTest.java
> +        System.out.println(savedCustomer.getCustomerName());
```suggestion
```

2022-11-22 04:56 UTC, hongbin-dev commented on src/test/java/prgms/vouchermanagementapp/service/CustomerManagerTest.java
> +    }
파라미터 검증은 assert가 아닌, 검증코드를 별도로 작성해서 (if 후 throw)  잘 모르겠습니다.

테스트같은경우 null safe하다고 판단되면, optional에서 검증없이 get()하고 꺼내서 사용하는편입니다. (이건 개인적인 선호도 입니다)

2022-11-22 04:57 UTC, hongbin-dev commented
못다한 답변은 오늘중으로 남겨드릴게요.

2022-11-22 10:29 UTC, seung-hun-h reviewed
선호님 리뷰 남겼습니다. 확인해주세요!

2022-11-22 10:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
> +            } catch (IllegalCommandException illegalCommandException) {
저도 보통 저런식으로 네이밍하는 것 같아요!

2022-11-22 10:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/domain/VoucherEntity.java
> +    public VoucherEntity(String id, String type, Long amount, Long ratio, String customerName) {
확실히 이 부분은 장단점을 잘 생각할 필요가 있을 것 같습니다.
비슷한 내용이 이펙티브 자바 아이템23에 있어요

2022-11-22 10:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/repository/util/VoucherContentsConverter.java
> +    public static String toContents(Voucher voucher, String messageFormat) {
질문을 듣고보니 어떤 것을 빈으로 등록하고, 빈으로 등록하지 않고에 대한 명확한 기준을 설명 드리기 어렵긴하네요.

일단 한 요청을 기준으로 각각의 독립된 데이터가 필요하다 싶으면 일반적인 클래스를 만들 것 같습니다. 여기서는 `Customer` 같은 것들이 되겠죠

그리고 요청에 상관 없이 항상 같은 동작을 해야하는 것들은 빈으로 등록할 것 같아요. 어떤 클래스를 빈으로 등록하고 로직을 작성하다 보면 단순히 데이터를 받아서 계산하거나, 변환하는 반복적인 로직들이 있는데 이런 부분들이 공통적으로 많이 생긴다면 유틸성 클래스로 빼기도 하는 것 같네요

2022-11-22 10:29 UTC, seung-hun-h commented on src/main/java/prgms/vouchermanagementapp/view/FileManager.java
> +            );
넵 검사 예외를 비검사 예외로 전환하는 방식은 많이 사용하는 것으로 알고있습니다.
단, `IllegalArgumentException`을 던져야하는 것인지, 다른 예외를 던져야하는 것인지는 고민을 해봐야할 것 같네요.
잘못됐다는 것이 아니라 여러가지 상황이 있을 수도 있을 것 같아서요. 인자는 제대로 들어왔는데, 파일 시스템 자체가 문제일 수도 있지 않을까 하는 생각이 들긴 하네요

2022-11-22 10:29 UTC, seung-hun-h commented on src/test/java/prgms/vouchermanagementapp/domain/FixedAmountVoucherTest.java
> +        Voucher voucher = VoucherCreationFactory.createVoucher(fixedDiscountAmount);
이 부분은 given에 해당하는 것 같네요

2022-11-22 10:29 UTC, seung-hun-h commented on src/test/java/prgms/vouchermanagementapp/repository/JdbcVouchersTest.java
> +        assert foundVoucherEntity.isPresent();
when 구에는 테스트 하고자하는 대상만 위치하는 것이 좋을 것 같아요.
그 외 실행을 위한 데이터는 given, 검증 부분은 then으로 이동하는 것이 좋겠네요

2022-11-23 05:09 UTC, preferKim commented on src/main/java/prgms/vouchermanagementapp/repository/JdbcVouchers.java
> +public class JdbcVouchers {
- JdbcVouchers가 Vouchers 인터페이스를 구현하게 되는데, 그렇게 되면 당장 큰 리팩토링이 필요할 것 같아 우선 독립적인 클래스로 두었습니다. 
- 지금 생각해보니 일단 implement 하고 파일 바우처나 메모리 바우처에서 지원하지 않는 기능을 `UnsupportedOperationException` 등으로 처리해도 괜찮았을 것 같네요!

2022-11-27 15:10 UTC, preferKim commented
@seung-hun-h  @hongbin-dev 

다음 미션 제출을 위해 해당 PR은 머지하고,  다음 PR에 피드백 반영사항을 코멘트로 남겨두겠습니다!
 리뷰 감사드립니다☺️

2022-11-27 15:10 UTC, merged