[3기-C] 장영지 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #598
Opened 2022-11-21 09:25 UTC by youngjijang

항상 감사합니다 🥺
## 📌 과제 설명 
SpringBoot Part2 미션입니다.

## 👩‍💻 요구 사항과 구현 내용 
- SpringBoot Part2 Weekly Mission(~11/18)
    
    **(기본)** **바우처 관리 애플리케이션**
    
    - [X]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
        - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
        - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
        - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
    - [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
        - customers 테이블 정의 및 추가
        - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
    - [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
        - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
        - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
        - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
    
    **(심화)** **바우처 지갑을 만들어보세요.**
    
    - [x] 특정 고객에게 바우처를 할당할 수 있습니다.
    - [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
    - [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
    - [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## ✅ PR 포인트 & 궁금한 점 
- 바우처 지갑에 관해서 controller나 service를 어떻게 분리 해야하나 고민하였는데, VoucherRopository와 CustomerRepository 둘다 주입받아야할것 같아서 Service는 따로 두지 않고 Controller만 구현하였습니다..! service를 호출하는 역할로 봤을때는 controller가 맞는 것 같은데 기능면에서는 voucherContoller에 포함되어도 될거같아서 고민되네요..!
- 우선 오류가 없고 성공적으로 동작하는데 의미를 둬서 효율성 면에서 부족한 부분이 있을 것같아요! 스스로 더 찾아보고 개선하려고 노력해보겠지만 혹시 더 주의 깊게 봤으면 하는 부분이 있다면 말씀해주시면 감사하겠습니다!!
- 테스트 코드를 작성할때 어느 테스트에서 stub을 사용하고 어느 테스트에서 mock을 사용해야하는지 아직 헷갈리네요ㅠ

2022-11-21 15:25 UTC, WooSungHwan requested changes
안녕하세요. 영지님!
과제작성하시느라 고생 많으셨습니다. 코드가 확실히 많이 좋아지셨네요 ㅎㅎ
코멘트 몇자 남겼으니 확인 부탁드립니다!

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/controller/VoucherController.java
> +        console.successMessageView("바우처가 정상적으로 생성되었습니다. ");
```
String voucherType = console.input("생성할 바우처 타입을 입력하세요?   1.Fixed Amount   2.percent discount : ");
        String discount = console.input("바우처의 할인 금액(혹은 퍼센트)을 입력하세요 : ");
        
        voucherService.createVoucher(InputData.of(voucherType, discount));
        console.successMessageView("바우처가 정상적으로 생성되었습니다. ");
```

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/controller/VoucherController.java
> +        console.successMessageView("바우처가 정상적으로 생성되었습니다. ");
이런식으로 불필요하다고 보겠지만 pasrInt같은 행위를 InputData안쪽으로 숨겨놓는다면 겉으로 드러나는 코드 자체는 좋아질것 같아요.

저렇게 모아놓고 유효성 검사를 할수도 있고용.

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/controller/CustomerController.java
> +    private final String regularType = "regular";
`static final String REGULAL_TYPE = "regular"`
요렇게 바꾸면 어떨까요?

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/controller/CustomerController.java
> +    }
Y N을 문자열을 바로 박아넣기보다는 변수화하거나 enum화 하는게 좋을듯.
여기서 한가지 짚어보자면 Y / N 두 문자만 입력 가능하다는 유효성과 deleteAll 메소드 호출의 흐름제어를 동시에 하려는 욕심을 보이는 것 같음.
 따라서 if문으로 처리하되 Y/N에 대한 유효성을 가지는게 좋을듯.

물론 콘솔이라는 점이 코드를 불필요하게 많이 쓰게 만들어서 귀찮겠지만 코드의 목적을 하나만 생각하게 하는 연습이 필요해보여요.

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/controller/CustomerController.java
> +    }
그런고로 if 문이 조금 더 나을듯 싶습니다!

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/controller/CustomerController.java
> +    }
근데 input이 boolean을 리턴한다는 생각으로 확장해보면 어때요?

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/controller/VoucherWalletController.java
> +                customerService.getCustomerByName(customerName).getCustomerId());
이렇게 메소드 두개를 중첩해서 쓰기보다는 엔터로 구분을 해놓고 주석으로 로직을 표기하거나 코드의 흐름을 명확하게 보여주는게 좋을듯.

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/repository/VoucherJdbcRepository.java
> +    }
update 같은 경우는 어떤 행위를 할때마다 그 용도가 매우 다양함.
예를 들어, 유저의 경우 닉네임을 바꾸는 경우와 password를 바꾸는 경우 두개의 update가 각각 다른 생김새로 쳐짐
`update user set password = 'changed' where id = 'blackdog' and password = 'before'`
`update user set nickname = 'changed' where id = 'blacodkg' and nickname = 'before'`
각각 이런식으로 update 구문이 실행되어야 할 것 같은데 지금은 공용적으로 쓰는 이름처럼 보여서 이 update 라는 repository 메소드가 어떤 비즈니스적인 쿼리를 실행할지 전혀 감이 안잡힙니다.

각 목적에 맞는 쿼리가 발생하고 그 쿼리를 실행하는 적절한 이름을 주어야 할것같아요.

2022-11-21 15:25 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/repository/VoucherJdbcRepository.java
> +    public List<Voucher> findByAssignedCustomer(UUID customerId) {
select는 적절하게 유추가 가능합니다.

2022-11-24 07:15 UTC, youngjijang commented on src/main/java/com/program/commandLine/controller/CustomerController.java
> +    }
넵!! 전체 삭제전에 한번 더 체크하는게 좋을 것 같아 아무 생각없이 추가하였네요..! enum type을 통해 유효성 검사해주고 console에서 recheckInput을 받아 boolean 타입으로 반환해 주도록 변경해봤습닏! 코드가 훨씬 깔끔해졌어요. 감사합니다!

2022-11-24 08:39 UTC, choi1204 approved these changes
영지님 과제하시느라 수고하셨습니다. 리뷰가 늦었네요 코멘트 확인해 보시고 학습에 도움되셨으면 합니다.

2022-11-24 08:39 UTC, choi1204 commented on src/main/java/com/program/commandLine/controller/SystemController.java
> +    private void customerServiceRun() {
customerServiceRun이나 voucherServiceRun() 같은 메서드들은 SystemController에 있는 것 보다 각각의 controller안에 있고 SystemController가 실행시키는게 더 맞는것 같아요

2022-11-24 08:39 UTC, choi1204 commented on src/main/java/com/program/commandLine/voucher/FixedAmountVoucher.java
> +    private UUID assignedCustomerId;
저희는 oop를 추구하는 개발답게 테이블에 맞추어서 연관관계 테이블 pk를 가지고 있는 것보다 참조로 연관관계를 맺어주시는게 더 맞는 oop 설계 인것같아요

2022-11-24 08:39 UTC, choi1204 commented on src/main/java/com/program/commandLine/controller/VoucherWalletController.java
> +    private final VoucherService voucherService;
Wallet에 관련한 Controller라면 각각의 Service를 가져오는 것보다 wallet의 기능만 정의한 WalletService를 분리하여서 사용하는게 더 좋아보여요

2022-11-24 08:39 UTC, choi1204 commented on src/main/java/com/program/commandLine/controller/VoucherWalletController.java
> +        List<Voucher> allVoucher = voucherService.getAssignedVouchersByCustomer(null);
null을 넣으신 이유는 무엇인가요?

2022-11-24 08:39 UTC, choi1204 commented on src/main/java/com/program/commandLine/controller/VoucherWalletController.java
> +    private final VoucherService voucherService;
또한 현재 요구사항에 맞쳐서 Wallet기능에 초점을 두고 Customer와 Vocher에 관련하여 동작하게만 설계가 되어있어요.
좀 더 객체스럽고 확장에 유연한 설계를 위해서는 Wallet을 클래스 단위로 관리해주시는게 더 좋을 것 같아요

2022-11-24 08:39 UTC, choi1204 commented on src/main/java/com/program/commandLine/io/ScannerConsole.java
>          if (vouchers.size() == 0) {
개인적으로 list의 size가 0인 체크는 가독성 측면에서 isEmpty()를 선호합니다.

2022-11-24 08:39 UTC, choi1204 commented on src/main/java/com/program/commandLine/service/CustomerService.java
> +    @Value("${customer.black_list.path}")
BlackList의 경우에는 @Valut를 필드주입으로 하셨는데 FileVoucherRepository에서는 생성자 주입으로 되어 있어요 코드 스타일을 일치 시켜주세요

2022-11-25 17:41 UTC, youngjijang commented on src/main/java/com/program/commandLine/controller/VoucherWalletController.java
> +        List<Voucher> allVoucher = voucherService.getAssignedVouchersByCustomer(null);
할당되지 않은 바우처의 리스트만 사용자에게 보여주려고 null을 사용하였었습니다! Wallet 테이블을 분리하면서 별도의 메소드getNotAssignedVoucher()로 변경하였습니다 🙂

2022-11-25 17:41 UTC, youngjijang commented on src/main/java/com/program/commandLine/io/ScannerConsole.java
>          if (vouchers.size() == 0) {
감사합니다!

2022-11-25 17:44 UTC, youngjijang commented on src/main/java/com/program/commandLine/controller/SystemController.java
> +    private void customerServiceRun() {
앗 고민했던 부분인데 감사합니다!

2022-11-25 23:08 UTC, WooSungHwan commented on src/main/java/com/program/commandLine/io/ScannerConsole.java
>          if (vouchers.size() == 0) {
이건 라이브러리가 있긴한데
isEmpty도 마냥 안전한게 아니라 혹여나 list가 null로 넘어오는 경우 고려해보시고
list != null && list.size() == 0 을 static으로 빼서 컬렉션 empty를 검사하시거나 아파치 라이브러리를 쓰시면 좋을 것 같습니다.
실무에서 많이 쓰거등요.

https://jihyehwang09.github.io/2020/04/13/java-list-null-check/
여긴 시간복잡도를 고려하고도 있네요.

2022-11-26 09:19 UTC, youngjijang commented on src/main/java/com/program/commandLine/voucher/FixedAmountVoucher.java
> +    private UUID assignedCustomerId;
CustomerId가 아닌 Customer 객체 주소를 가지고 있는게 낫다는 말씀이시죠?! 감사합니다!

2022-11-26 15:56 UTC, youngjijang commented on src/main/java/com/program/commandLine/controller/VoucherWalletController.java
> +    private final VoucherService voucherService;
감사합니다! VoucherWallet 관련 service를 따로 구축해보긴했는데 commandLine으로 선택을 받다보니 VoucherWalletController안에서 voucherService와 customerService를 따로 제거하진 못하였습니다ㅜ 분리하는 방식에 대해 좀더 조언해주실수 있을까요?!

2022-11-27 19:01 UTC, youngjijang commented on src/main/java/com/program/commandLine/io/ScannerConsole.java
>          if (vouchers.size() == 0) {
null 체크도 신경써줘야 겠네요..🤣 감사합니다!

2022-11-27 19:11 UTC, youngjijang commented
<!--
  템플릿은 아직 PR 작성이 익숙하지 않으신 분들을 위해서 제공하는 가이드입니다!
  리뷰어 또는 이 PR을 보게 될 다른 사람들이 이 PR을 보는데 참고할 수 있는 내용이 있다면 포함해서 작성해주시면 됩니다.
-->
<!--
  템플릿은 아직 PR 작성이 익숙하지 않으신 분들을 위해서 제공하는 가이드입니다!
  리뷰어 또는 이 PR을 보게 될 다른 사람들이 이 PR을 보는데 참고할 수 있는 내용이 있다면 포함해서 작성해주시면 됩니다.
-->
잘 부탁드립니다~~!
## 📌 과제 설명 <!-- 어떤 걸 만들었는지 대략적으로 설명해주세요 -->
SpringBoot Part3 미션입니다.

## 👩‍💻 요구 사항과 구현 내용 <!-- 기능을 Commit 별로 잘개 쪼개고, Commit 별로 설명해주세요 -->
- SpringBoot Part3 Weekly Mission(~11/25)
    
    **(기본) 바우처 서비스 관리페이지 개발하기**
    
    - Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
    - 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
        - [x]  조회페이지
        - [x]  상세페이지
        - [x]  입력페이지
        - [x]  삭제기능
    
    **(기본) 바우처 서비스의 API 개발하기**
    
    - Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
        - [x]  전체 조회기능
        - [x]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
        - [x]  바우처 추가기능
        - [x]  바우처 삭제기능
        - [x]  바우처 아이디로 조회 기능
        
    
    [ ]**(보너스) 바우처 지갑용 관리페이지를 만들어보세요.**
  

## ✅ PR 포인트 & 궁금한 점 <!-- 리뷰어 분들이 집중적으로 보셨으면 하는 내용을 적어주세요 -->
- 보너스 과제는 구현하지 못하였습니다.
- 피드백을 받아 VoucherInputData를 만들었는데 커멘드로 지원했던 프로젝트가 페이지를 제공하면서 InputData가 DTO 역할을 하는것인가 궁금합니다! DTO에 대한 개념과 parameter 타입 변형(?)같은 동작이 어느 계층에서 일어나야하는지 아직 헷갈리네요. 과제하느라 재대로 찾아보지 못했어서 좀 더 공부해보도록 하겠습니다!

2023-06-05 18:40 UTC, closed without merging