[3기-C] 권성준 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #602
Opened 2022-11-21 12:48 UTC by Seongjun-Kwon

마르코님, 명환님 안녕하세요! 이번에도 리뷰 잘 부탁드립니다😀
감사합니다😄

## 📌 요구 사항

**(기본)** **바우처 관리 애플리케이션**

- 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - [x] 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - [x] 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - [x] Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요. -> AssertJ 로 대신하였습니다.
- 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - [x] customers 테이블 정의 및 추가
    - [x] CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - [x] 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - [x] 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - [x] 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x] 특정 고객에게 바우처를 할당할 수 있습니다.
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다. - [x]고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 📌 클래스 다이어그램

![voucher_w2_uml](https://user-images.githubusercontent.com/82152173/203047408-0aec6d93-5c28-42ae-aed9-5cc4831972a4.PNG)

## 📌 ERD

![voucher_w2_erd](https://user-images.githubusercontent.com/82152173/203057234-396bc221-7a8d-49e7-9fba-14d1a7044701.PNG)

## 📌 주요 클래스 설명

- console
    - io
        - `ConsoleInput` : 콘솔에서의 입력을 담당합니다.
        - `ConsoleOutput` : 콘솔에서의 출력을 담당합니다.
        - `Input` : 입력의 인터페이스입니다.
        - `Output` : 출력의 인터페이스입니다.
    - run
        - `AppPower` : 프로그램이 계속 실행되도 되는지 여부를 판별하는 역할, 프로그램 종료 요청 역할을 가집니다.
        - `Command` : 사용자가 콘솔에 입력할 수 있는 명령어들을 관리합니다.
        - `Message` : 프로그램 동작 과정에서 사용자에게 출력하는 메시지를 관리합니다.
        - `PentaConsumer` : Command 클래스에서 사용하는 함수형 인터페이스로 사용자의 입력 명령에 따른 동작을 실행합니다.
    - `ConsoleVoucherApp` : 사용자의 명령에 따른 바우처 관리 프로그램 동작 흐름을 담당합니다.

- core
    - exception
        - `DataUpdateException` : 저장, 수정, 삭제 같은 데이터 갱신에 실패했을지 발생하는 예외입니다.
        - `EmptyBufferException` : BufferedReader, BufferedWriter 사용 시 처리해야하는 IOException 을 구체적으로 전환하는 예외입니다.
        - `ExceptionMessage` : 예외 발생 시 출력하는 메시지들을 관리합니다.
        - `NotFoundException` : 처리하고자하는 데이터가 없을 때 발생하는 예외입니다.
    - util
        - `JdbcTemplateUtil` : JdbcTemplate 를 사용하여 DB 작업 중 필요한 매핑 작업들을 관리합니다.

- domain
    - customer
        - model
            - `Customer` : 고객 정보를 가지고 있는 클래스이고, id, 타입, 생성시간, 최종 수정시간을 가지고 있습니다.
            - `CustomerType` : 고객 타입을 관리합니다. NORMAL, BLACKLIST 2가지 타입으로 관리합니다.
        - repository
            - `CustomerRepository` : 고객 저장소의 인터페이스입니다.
            - `CustomerSQL` : JdbcCustomerRepository 에서 필요한 SQL 문을 관리합니다.
            - `FileCustomerRepository` : 파일로 고객들의 정보를 관리합니다. file 프로파일에서 동작합니다.
            - `JdbcCustomerRepository` : JDBC 를 이용하여 RDBMS 으로 고객 정보를 관리합니다. MySQL 을 이용합니다. jdbc, test 프로파일에서 동작합니다.
        - service
            - `CustomerService` : 고객 관련 서비스를 담당합니다.
    - voucher
        - model
            - `FixedDiscountVoucher` : 고정형 할인 바우처입니다.
            - `PercentDiscountVoucher` : 비율형 할인 바우처입니다.
            - `Voucher` : 바우처들의 정보를 가지고 있는 클래스입니다. 추상 클래스이며 타입에 따라 확장 가능합니다.
            - `VoucherType` : 바우처 타입을 관리하는 enum 입니다.
        - repository
            - `FileVoucherRepository` : 파일로 바우처 정보를 관리합니다. file 프로파일에서 동작합니다.
            - `JdbcVoucherRepository` : JDBC 를 이용하여 RDBMS 으로 바우처 정보를 관리합니다. MySQL 을 이용합니다. jdbc, test 프로파일에서 동작합니다.
            - `MemoryVoucherRepository` : 메모리에서 바우처 정보를 관리합니다. local 프로파일에서 동작합니다.
            - `VoucherRepository` : 바우처 저장소의 인터페이스입니다.
            - `VoucherSQL` : JdbcVoucherRepository 에서 필요한 SQL 문을 관리합니다.
        - service
            - `VoucherService` :  바우처 관련 서비스를 담당합니다.
        - util
            - `VoucherFactory` : 사용자의 입력 받은 값에 따라 바우처 구현체를 만들어줍니다.
    - wallet
        - model
            - `Wallet` : 고객에게 할당된 바우처 정보를 관리합니다.
        - repository
            - `JdbcWalletRepository` : JDBC 를 이용하여 RDBMS 으로 바우처 지갑 정보를 관리합니다. MySQL 을 이용합니다. jdbc, test 프로파일에서 동작합니다.
            - `WalletRepository` : 바우처 지갑 저장소의 인터페이스입니다.
            - `WalletSQL` : JdbcWalletRepository 에서 필요한 SQL 문을 관리합니다.
        - service
            - `WalletService` : 바우처 지갑 관련 서비스를 담당합니다.

## ✅ PR 포인트 & 궁금한 점
- Command 클래스가 너무 지저분해져서 아쉽습니다. 개선할 수 있는 좋은 방법이 있을까요?
지금 형태에서는 반복되는 코드도 많고, 새로운 기능이 추가될 때마다 함수형 인터페이스도 계속 수정이 생깁니다.
명령어마다 사용하는 컨트롤러를 만들어서 매핑해주고자 시도해봤는데, 컨트롤러를 만들려고해도 DI를 해줘야해서 매핑도 쉽지 않더라고요. 개선할 수 있는 좋은 방법이 있을까요?

2022-11-25 10:16 UTC, thguss reviewed
과제 수고하셨습니다!! 여러모로 배울 점도 많았네요,, 잘 보고 리뷰 몇개 남기고 갑니다 ㅎㅅㅎ

2022-11-25 10:16 UTC, thguss commented on src/main/java/com/programmers/voucher/domain/voucher/model/FixedDiscountVoucher.java
> +	protected double validateDiscount(String discount) {
예외처리 꼼꼼하네요 ㅇㅁㅇ !! 짱짱

2022-11-25 10:16 UTC, thguss commented on src/main/java/com/programmers/voucher/domain/voucher/repository/JdbcVoucherRepository.java
> +	public Voucher findById(UUID voucherId) {
저는 Optional 타입으로 반환했는데 바로 Voucher 타입으로 내보내는 방법도 있네용 신기

2022-11-25 10:16 UTC, thguss commented on src/main/java/com/programmers/voucher/domain/voucher/repository/VoucherSQL.java
> +public enum VoucherSQL {
오호 찾아보니까 enum 도 인터페이스 구현이 된대요! SQL 관련 인터페이스 만들어서 CustomerSQL 이랑 VoucherSQL 에서 implements 해와도 깔끔할 듯 하네욤

2022-11-25 10:16 UTC, thguss commented on src/main/java/com/programmers/voucher/domain/voucher/util/VoucherFactory.java
> +		return new PercentDiscountVoucher(UUID.randomUUID(), discount, voucherType, LocalDateTime.now());
나중에 유지보수성을 생각해서 switch 를 활용해봐도 좋을 듯 합니다! fixed 아니면 냅다 percent로 생성하는 것이 조금 아쉬워요!

2022-11-25 10:16 UTC, thguss commented on src/main/resources/application.yaml
> +    voucher: "src/main/resources/voucher.csv"
파일 경로를 application.yaml 에 저장하는 거 저번에 보고 잘 배워서 잘 써먹었읍니다 체고체고 *^!^*

2022-11-25 10:16 UTC, thguss commented on src/test/java/com/programmers/voucher/domain/customer/repository/JdbcCustomerRepositoryTest.java
> +		assertThat(createdCustomer).isEqualTo(customer);
우왕 isEqualTo 를 쓰는 방법도 있군요 배워갑니다,,

2022-11-25 10:16 UTC, thguss commented on src/test/java/com/programmers/voucher/domain/customer/repository/JdbcCustomerRepositoryTest.java
> +class JdbcCustomerRepositoryTest {
좋네요! 다만 저는 강의를 보고 Order 을 적극적으로 사용하고 있는데, 전체적인 플로우를 보기 좋더라구요! Order 사용도 추천드립니다 ㅎㅎ

2022-11-25 10:16 UTC, thguss commented on src/test/java/com/programmers/voucher/domain/voucher/repository/MemoryVoucherRepositoryTest.java
> +		Assertions.assertThat(afterSize).isEqualTo(beforeSize + 2);
size로 비교하는 거 신기하네용,, 배워갑니다22

2022-11-25 10:16 UTC, thguss commented on src/test/resources/application.yaml
> +spring:
별 건 아닌데 나중에 파일 이름으로 충돌 방지해서 application-test.yaml 과 같이 테스트 파일임을 나타낼 수 있는 이름으로 파일명을 명명해도 좋을 것 같아요~

2022-12-21 17:07 UTC, samkimuel requested changes
성준님 고생하셨습니다!
코멘트 달았으니 확인해주세요~

- Command 클래스가 가지고 있던 Command 별 동작을 CommandProcessor 로 분리했습니다.
처음에는 명령어마다 사용하는 컨트롤러를 만들어서 매핑해주고자 시도해봤는데, 컨트롤러를 만들려고해도 DI를 해줘야해서 매핑도 쉽지 않더라고요. 해결할 수 있는 좋은 방법이 있을까요?
-> 입력을 한꺼번에 받는 건 어떨까요?? 매 단계에서 입력을 받아야하니 DI를 해줘야하는 것 같아요. 관심사 분리도 잘 안되는 것 같아 보이구요. 코멘트에도 달았지만, MVC 패턴에 대해 공부해보시고 고민해보시고 혹시 어렵거나 계속 고민이 된다면 편하게 DM주세요🙂

2022-12-23 12:44 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/console/run/AppPower.java
> +	public static boolean isRunning() {
getter 를 이용해서 runStatus 를 가져온다면 극단적으로 말해서 runStatus 필드가 사라지거나 변했을 때, getter 를 사용하는 객체의 코드도 수정해줘야하므로 변경에 더 취약할 것 같습니다.
사용하는 객체는 runStatus 상태를 달라고 AppPower 에게 호출하고 관련 runStatus 를 얻는 로직은 AppPower 내에 두는 것이 더 나을 것 같습니다.

2022-12-23 12:45 UTC, thguss commented on src/main/java/com/programmers/voucher/console/run/AppPower.java
> +	public static boolean isRunning() {
성준 오빠와 명환님께서 주신 자료를 읽고 얘기해본 결과, 이 경우에서는 getter을 사용하는 것보다 캡슐화를 사용해서 하는 것이 유지보수 측면에도 좋다는 것에 동의합니다 :)

2022-12-23 12:46 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/console/run/AppPower.java
> +	private AppPower() {
AppPower 객체가 여러 개가 있으면 안되므로 생성을 막기위해서입니다.

2022-12-23 12:47 UTC, thguss commented on src/test/java/com/programmers/voucher/domain/customer/repository/JdbcCustomerRepositoryTest.java
> +class JdbcCustomerRepositoryTest {
@samkimuel 

듣고 보니 Order의 문제점도 알게 되었어요! 독립적인 테스트 방향으로 테스트 코드를 짜는 방법을 고안해보겠습니다. 감사합니다 :)

2022-12-23 13:38 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/console/run/CommandProcessor.java
> +	private void allocateVoucher(Input input, Output output) {
수정했습니다! 네이밍하기가 어려웠네요..

2022-12-23 13:40 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/core/exception/EmptyBufferException.java
> +public class EmptyBufferException extends RuntimeException {
unchecked exception 으로 관리해주기 위해 RuntimeException 을 상속해주었습니다.

2022-12-23 18:05 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/customer/repository/CustomerRepository.java
> +	void clear();
저도 그렇게 느껴서 수정했습니다!

2022-12-23 18:19 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/voucher/domain/voucher/util/VoucherFactory.java
> +		return new PercentDiscountVoucher(UUID.randomUUID(), discount, voucherType, LocalDateTime.now());
수정하였습니다~!

2023-06-05 18:40 UTC, closed without merging