[3기-C] 이건우 SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #604
Opened 2022-11-21 15:02 UTC by geonwoo0215

리뷰해주셔서 감사합니다

📌 과제 설명
SpringBoot Part2 미션입니다.
jdbc를 활용하여 DB를 사용합니다.

👩‍💻 요구 사항과 구현 내용
SpringBoot Part2 Weekly Mission(~11/18)

(기본) 바우처 관리 애플리케이션

바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
customers 테이블 정의 및 추가
CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
(1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
(심화) 바우처 지갑을 만들어보세요.

특정 고객에게 바우처를 할당할 수 있습니다.
고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
고객이 보유한 바우처를 제거할 수 있어야 합니다.
특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.
ERD
erd

✅ PR 포인트 & 궁금한 점
Jdbc 테스트 코드를 작성하지 못했습니다. PR 올린 후에 계속 작성하겠습니다. 😢
코드에 불필요한 부분, 비효율적인 부분을 말씀해주세요!
감사합니다!

2022-11-24 07:37 UTC, WooSungHwan requested changes
건우님 안녕하세요! 과제하시느라 고생많으셨습니다.
코멘트 몇자 남기오니 확인부탁드립니다!!

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/controller/CommandLineApp.java
> +		switch (menu) {
요 execute 메소드가 이렇게 큰 크기로 바뀌게 된다면
io를 사용하는 부분을 현재 클래스에서 해야하나? 라고 고민을 해볼 것 같습니다.

적절한 command를 파싱해서 적절한 controller로 보내주는 것과 io를 통해 Input을 받는 부분이 이 클래스에는 동시에 가지고 있다보니 이렇게 뚱뚱해진 것 같아요.

프록시 패턴을 활용해보면 좋을 것 같아요. 혹은 데코레이터 패턴일 수도 있습니다. 건우님이 어떤 의도로 접근한지에 따라 달리니 고민해보셔도 좋을 것 같아요.

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/controller/CommandLineApp.java
> +				Customer customer = new Customer(customerId,name,email, LocalDateTime.now(), NORMAL);
직접 customer라는 객체를 쓰기보다는 CustomerJoin이라던지 CustomerJoinParam이라던지 특정 목적의 객체를 정의해보시는건 어떠세요?

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/customer/CustomerJdbcRepository.java
> +	}
update 쿼리같은 경우는 그 목적이 매우 다양하기 때문에 목적에 맞는 메소드 네이밍이 필요해보입니다.
당장 지금이야 다 변경하는 put 형태이어서 그렇겠지만 통상 패스워드 변경이라던가 이메일 변경이라던가 이렇게 patch 형태로 수정을 하게 되는 경우에 이렇게 공통으로 처리되는 쿼리를 동일하게 수행하지는 않습니다.

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +		}};
double brace

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +				Collections.singletonMap("voucherId", voucherId.toString().getBytes()), customerRowMapper));
이 쿼리 실제로 돌려보셨나요??
customerRowMapper 해당 로우매퍼에서는 필요한 컬럼이 5개정도로 생각되는데..
아마 customer인것 같습니다만 불필요한 컬럼이 select 되지는 않는지 확인해보시겠어요?

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +					+ "WHERE voucher.customer_id = UUID_TO_BIN(:customerId)",
여기도 마찬가지입니다. voucher list이지만 customer 관련 컬럼이 같이 select 될 것으로 예상됩니다. 쿼리 결과를 jdbcTemplate이 실행해서 필요한것만 빼서 쿼리를 날리는게 아니니 실제 sql에 집중해보시면 좋을 것 같습니다.

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +					+ "WHERE voucher.customer_id = UUID_TO_BIN(:customerId) AND voucher_id = UUID_TO_BIN(:voucherId)",
delete 쿼리와 select가 필요한 쿼리는 분리하는게 좋을 것 같습니다.

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +public class WalletRepository {
전반적으로 Wallet에 대한 개념이 많이 모호합니다.
현재 구조로는 wallet에 대한 다양한 요구사항을 만족할 수 없습니다.
예를 하나 들어드릴게요. 

하나의 voucher 혹은 여러 voucher로 구성된 그룹이 생성되었고 voucher(단품, 그룹) 를 2인 이상의 유저(customer)가 공유해서 사용하는 시스템을 개발해야한다면 어떻게 해야할까요?

1. voucher에 customer_id를 n개 만든다.
2. voucher에 customer_id의 기존체제를 유지한채 하나더 컬럼을 만들어서 공동소유하는 경우 해당 컬럼을 바라보게 한다. (1,2) 이런식으로 저장된다.
3. voucher에 customer_id 배열을 만든다.(pg의 경우임.)
4. voucher와 customer 사이에 N:M 매핑 테이블을만든다. -> 기존 customer_id는 마이그레이션 한다.

이정도가 될것 같습니다.

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +public class WalletRepository {
제가 말씀드리고 싶은 부분은 wallet이라는 개념은 논리적 개념이고 물리적 저장소인 데이터베이스에는 wallet이라는 테이블을 모릅니다. 따라서 쿼리가 어려워지고 ANSI의 형태가 아닌 dbms 고유의 기술을 사용해서 처리할 수 밖에 없는 상황에 마주치기도 합니다.

그런데 제가 항상 했던 말은 기본입니다.

wallet을 구현할때는 이러한 기본보다 응용에 가까운 구현방법을 택하신 것 같습니다. 물리적으로 없는 존재를 논리적으로 표현하고자 하니 실제 데이터 저장소에 sql을 던질때는 없던 정보가 클래스로 구현하기는 굉장히 어렵습니다.
이는 실제 현업 개발자분들도 이러한 물리적 정보가 없는 데이터를 논리적으로 구현하는 방법은 되도록 택하지 않는 편이며 앞으로 jpa를 학습하게 되실텐데 entity라는 개념과도 많이 괴리가 멀어지게 될겁니다. 엔티티는 db 테이블 하나를 가리키는 java object가 될거거든요. 그렇게되면 자바 코드도 이러한 물리-논리의 불일치를 메꾸려는 시도를 해야되고 건우님이 아닌 제3자가 봤을때, 과연 리뷰없이 이해할 수 있을까? 라는 고민을 하게 될겁니다.

2022-11-24 07:37 UTC, WooSungHwan commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +public class WalletRepository {
여기서 유지보수의 어려움을 생각해야합니다.
아직은 기능을 구현하고 개발해나가는 목적에만 사로잡혀 있을 수 밖에 없을겁니다. 제가 위에서 했던 텍스트들도 건우님께 잘 전달될지는 모르겠지만 개발함과 동시에 유지보수 해야한다고 생각하면 좀더 쉬운 길을 선택하게 될겁니다.

테이블 하나 덜만들고 클래스 하나 덜만든다고 해서 유지보수성이 좋아지는 건 아닙니다. 단지 개발 총량이 적어지는 것일 뿐이고 내가 단순히 시스템 하나 개발하고 이 시스템에서 영영 빠지는 개발자가 아니라면(그런 역할을 하는 개발자라도 사실 그러면 직업윤리적으로 안되겠지만..) 1달후 혹은 1년후의 자신이 해야할 유지보수라고 생각하고 고려해야합니다.

2022-11-24 09:21 UTC, choi1204 reviewed
건우님 과제하시느라 수고하셨습니다. 코멘트 확인해주시고 학습에 도움되시면 좋을 것 같아요

2022-11-24 09:21 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/customer/FileBlackListRepository.java
> +public class FileBlackListRepository {
다른 Repository는 interface를 구현하는 형식인데 FileBlackList만 class로 직접 하신 이유가 있으실까요?

2022-11-24 09:21 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/voucher/VoucherJdbcRepository.java
> +	// private static UUID toUUID(byte[] bytes) {
사용되지 않을 코드인 주석이라면 제거해주시고, 나중에 구현할 코드이면 TODO: 와 함게 간략한 설명을 기재해주세요

2022-11-24 09:21 UTC, choi1204 commented on src/test/java/org/prgrms/springorder/service/VoucherServiceTest.java
> +		Assertions.assertNotNull(vouchers);
Junit의 Assertions의 같은 경우 static import를 추천드려요

2022-11-24 09:21 UTC, choi1204 commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +public class WalletRepository {
이 부분도 다른 Repository처럼 interface를 구현하게 해서 각각의 Profile에 맞게 동작하는 형식으로 맞춰주셔야할 것같아요

2022-11-28 05:29 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +public class WalletRepository {
walletRepository는 jdbc 이외에 요구사항에 없어서 따로 인터페이스를 만들지 않았는데 너무 요구사항에 맞춰서만 구현하려고 했습니다.
Interface를 만들어 수정하였습니다
감사합니다.

2022-11-28 05:31 UTC, geonwoo0215 commented on src/test/java/org/prgrms/springorder/service/VoucherServiceTest.java
> +		Assertions.assertNotNull(vouchers);
예전에 static import를 하다가 어떤 라이브러리에 있는지 기억이 안 난 경우가 있어서 따로 하지 않았습니다.
Assertions는 많이 사용해 봤으니 static import를 해야겠네요.
수정하였습니다.
감사합니다.

2022-11-28 05:38 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/voucher/VoucherJdbcRepository.java
> +	// private static UUID toUUID(byte[] bytes) {
제가 더 꼼꼼했어야 했는데...
삭제하였습니다.
감사합니다.

2022-11-28 05:40 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/customer/FileBlackListRepository.java
> +public class FileBlackListRepository {
요구사항에서 리스트 출력만 있어서 따로 인터페이스를 구현하거나 기능을 만들지 않았는데 제가 너무 요구사항에서만 해결할려고 했네요.
CustomerRepository를 구현하게 하였습니다.
감사합니다.

2022-11-28 06:20 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +					+ "WHERE voucher.customer_id = UUID_TO_BIN(:customerId) AND voucher_id = UUID_TO_BIN(:voucherId)",
수정하였습니다.
Wallet 테이블을 사용하기 전의 쿼리인데 복잡하네요
Wallet 테이블을 추가하고 삭제할 때는 Wallet Id를 통해 삭제하였습니다.

2022-11-28 06:31 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +				Collections.singletonMap("voucherId", voucherId.toString().getBytes()), customerRowMapper));
불필요한 Select에 대해 고민해 보지 않고 무작정 *를 사용하였네요.
필요한 컴럼만 select 하도록 수정하였습니다.
감사합니다.

2022-11-28 06:32 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +					+ "WHERE voucher.customer_id = UUID_TO_BIN(:customerId)",
위의 리뷰와 같이 수정하였습니다.
감사합니다.

2022-11-28 06:33 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/voucher/WalletRepository.java
> +		}};
다른 부분은 고쳤는데 이 부분을 놓쳤네요.
수정하였습니다.

2022-11-28 06:39 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/repository/customer/CustomerJdbcRepository.java
> +	}
멘토님의 예시를 보니 저의 네이밍은 너무 추상적이네요.
수정하였습니다.
다른 부분의 네이밍도 보고 추가적으로 수정하겠습니다.
감사합니다.

2022-11-28 07:25 UTC, geonwoo0215 commented on src/main/java/org/prgrms/springorder/controller/CommandLineApp.java
> +				Customer customer = new Customer(customerId,name,email, LocalDateTime.now(), NORMAL);
DTO 와 VO 등을 고민해서 적용해야겠네요!
CustomerReaquestDto를 만들어 수정하였습니다.
DTO , VO 등을 더 학습하고 사용 범위에 대해 고민 해봐야겠네요
감사합니다.

2022-11-28 08:26 UTC, geonwoo0215 commented
리뷰해주셔서 감사합니다

📌 과제 설명
SpringBoot Part3 미션입니다.
Thymeleaf 템플릿을 사용하여 페이지를 만들었습니다.
RestApi를 만들었습니다.

**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [X]  조회페이지
    - [X]  상세페이지
    - [X]  입력페이지
    - [X]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [X]  전체 조회기능
    - [ ]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [X]  바우처 추가기능
    - [X]  바우처 삭제기능
    - [X]  바우처 아이디로 조회 기능

✅ PR 포인트 & 궁금한 점
mock 테스트를 작성하고 mockMvc 테스트도 조금 작성해 보았습니다.
저번에 리뷰해 주신 내용으로 wallet 테이블을 추가하였습니다.

2023-06-05 18:40 UTC, closed without merging