[3기-C] 서예원 SpringBoot Part3 Weekly Mission(2차) 제출합니다
prgrms-be-devcourse/springboot-basic pull request #632
Opened 2022-12-05 13:17 UTC by yewon9609

안녕하세요 앨런님, 승훈님! 2차 pr이 많이 늦었네요..🥺 이번 pr도 잘 부탁드립니다 ☺️

## 📌 과제 설명 
**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x]  전체 조회기능
    - [x]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능

## ✅ PR 포인트 & 궁금한 점 
- exceptionHandler를 도입해봤는데 잘 사용한건지 궁금합니다 
- transactional어노테이션을 제대로 사용한건지 궁금합니다
 (어떻게 해야 잘 사용할 수 있는건지 잘 모르겠습니다, 일단 추가나 삭제 또는 수정이 있는 작업에만 붙여놓았습니다! ) 
![스크린샷 2022-12-05 오후 10 16 18](https://user-images.githubusercontent.com/99070762/205646430-1fcaa4af-33f0-4dee-94bb-98cf3b888d50.png)
![스크린샷 2022-12-05 오후 10 16 09](https://user-images.githubusercontent.com/99070762/205646437-1098881a-fb0a-4f56-a5b9-028685f94a7f.png)
![스크린샷 2022-12-05 오후 10 17 05](https://user-images.githubusercontent.com/99070762/205646568-f5ce71db-04a0-4dc7-9a0f-a4f7a143ae81.png)

2022-12-06 12:38 UTC, seung-hun-h requested changes
안녕하세요 예원님 리뷰 남겼으니 확인해주세요!

`@Transactional`에 대해 질문 남겨주셨는데 한 부분을 제외하고는 잘 사용하셨습니다.
트랜잭션은 어떤 작업을 원자적으로 실행하기 위해 사용합니다. readOnly 옵션은 해당 트랜잭션에서 데이터를 읽기만 하고 수정 하지 않을 때 사용합니다. 기술적인 지원은 스프링에서 해줍니다. 성능적인 부분이라던가, readOnly인데 데이터를 수정하면 예외를 던지는 것들이요.

일단 데이터베이스 트랜잭션에 대해서 알아보시고 난 후 스프링 트랜잭션을 알아보시면 좋을 것 같아요.
https://coding-factory.tistory.com/226
https://goddaehee.tistory.com/167

2022-12-06 12:38 UTC, seung-hun-h commented on src/main/java/org.prgrms/exception/GlobalExceptionHandler.java
> +    }
예외를 잘 잡아서 처리하셨네요 👍 
그런데 `NotFoundVoucherException`외 다른 예외는 약속해둔 응답 형식이 없을까요?
이대로라면 스프링의 기본 예외 응답이 전달될 것 같네요

2022-12-06 12:38 UTC, seung-hun-h commented on src/test/java/org/prgrms/controller/VoucherRestControllerTest.java
> +    MockMvc mockMvc;
private 붙여주세요~

2022-12-06 12:38 UTC, seung-hun-h commented on src/main/java/org.prgrms/dto/VoucherDTO.java
> +public record VoucherDTO(@NotNull String type, @NotNull long amount) { }
10E+20 값을 입력하면 예외가 그대로 보여지네요~

2022-12-06 12:38 UTC, seung-hun-h commented on src/test/java/org/prgrms/controller/VoucherRestControllerTest.java
> +    }
바우처들이 모든 테스트에 공유되고 있네요.
바우처 인터페이스에 값을 변경하는 API가 있는데, 이러면 테스트 순서에 따라 결과가 달라질 수도 있겠네요?

2022-12-06 12:38 UTC, seung-hun-h commented on src/test/java/org/prgrms/controller/VoucherRestControllerTest.java
> +    @Test
`@DisplayName`을 사용하지 않은 이유가 있나요?

2022-12-06 12:38 UTC, seung-hun-h commented on src/main/java/org.prgrms/service/VoucherService.java
> +    @Transactional
클래스 레벨에서 `@Transactional(readOnly=true)`를 해주셔서 이 부분은 지워도 될 것 같네요

2022-12-06 12:39 UTC, hongbin-dev reviewed
수고하셨습니다~ 예원님

2022-12-06 12:39 UTC, hongbin-dev commented on src/main/java/org.prgrms/controller/VoucherRestController.java
> +    }
restful한 API에서는 `/rest/vouchers`라는 path가 자연스러운 것 같습니다.

period도 필터의 한 종류 아닐까요?

https://itstory.tk/entry/%EB%8D%94-%EB%82%98%EC%9D%80-RESTful-API%EB%A5%BC-%EC%84%A4%EA%B3%84%ED%95%98%EA%B8%B0-%EC%9C%84%ED%95%9C-%EC%B5%9C%EA%B3%A0%EC%9D%98-10%EA%B0%80%EC%A7%80-%EC%97%B0%EC%8A%B5%EB%B0%A9%EB%B2%95

2022-12-06 12:39 UTC, hongbin-dev commented on src/main/java/org.prgrms/controller/VoucherRestController.java
> +    }
ResponseEntity를 이용하면 `ResponseStatus`를 사용하지않고, 응답 상태를 지정할 수 있어요.

2022-12-06 12:39 UTC, hongbin-dev commented on pom.xml
> +    </dependency>
롬복은 미션에서 사용하지 않았으면 좋겠군요 🥲 record 클래스를 적극 사용해봐요

https://greppkdt-backend.slack.com/archives/C0450ER6V43/p1666191899817749

2022-12-09 15:08 UTC, yewon9609 commented on src/main/java/org.prgrms/controller/VoucherController.java
> +                "해당 id를 가진 바우처를 조회할 수 없습니다 *id:" + voucherId.toString()));
exceptionHandler를 구현하면서 exceptionhandler가 컨트롤러에서 발생한예외를 잡아준다라는 글을 읽었는데 이부분을 제가 잘못이해한 것 같습니다😢

2022-12-09 15:11 UTC, yewon9609 commented on src/main/java/org.prgrms/controller/VoucherRestController.java
> +    }
![스크린샷 2022-12-10 오전 12 10 37](https://user-images.githubusercontent.com/99070762/206732818-884b957e-4083-4454-8075-20a6c0699b27.png)
이 글을 보니 제가 제대로 알지 못한상태에서 사용한것같습니다! 수정하겠습니다 감사합니다 ☺️

2022-12-09 15:12 UTC, yewon9609 commented on src/main/java/org.prgrms/controller/VoucherRestController.java
> +    @ResponseStatus(HttpStatus.CREATED)
요청이 성공했을경우 HttpStatus.ok인 200이 전달되는 것으로 알고있습니다!

2023-06-05 18:40 UTC, closed without merging