[4기 - 박은지]
prgrms-be-devcourse/springboot-basic pull request #652
Opened 2023-06-22 14:59 UTC by 1o18z

## 📌 과제 설명 
<img width="794" alt="스크린샷 2023-06-22 오후 10 50 08" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/66556716/ff170864-46fd-4c90-a850-df8e0bd7de92">
<img width="542" alt="스크린샷 2023-06-22 오후 10 49 38" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/66556716/37c6f7a9-c4e9-4047-a9ca-2e74b88237be">

## ✅ PR 포인트 & 궁금한 점

2023-06-22 16:55 UTC, dojinyou reviewed
전체적인 구조는 괜찮은 것 같아요!

2023-06-22 16:55 UTC, dojinyou commented on .gitignore
> +.idea/**/workspace.xml
[nit]
`.idea`는 인텔리제이라는 IDE로 작업하게 되면 생생이 되는 데 개인적으로 이런 코드작업용 응용프로그램에 의한 데이터들은 git에서 관리되지 않아야 한다고 생각해요!
인텔리제이로 프로젝트 만들면 생기는 `Help.me`, mac os의 `.DS_Store` 폴더나 vscode의 `.vscode` 폴더도 동일하게 생각해요!

2023-06-22 16:55 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
> +    return price - price * (discountValue / 100);
매직 넘버!

2023-06-22 16:55 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +public interface Voucher {
다양한 선택지가 있었을 텐데 인터페이스로 하신 이유가 있나요?

2023-06-22 16:55 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  }
`checkType`메서드 대신 내부의 `valueOf `메서드를 활용하면 더 좋을 것 같아요

2023-06-22 16:55 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  PERCENT("percent");
`type`이 그냥 name의 lowerCase라면 불필요한 거 같아요

2023-06-22 16:55 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +public enum VoucherType {
`VoucherType` 자체는 도메인이 전혀 모르는 클래스인 것 같은데 도메인에 포함되어야 하는 지 의문이 듭니다!

2023-06-22 16:55 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
실패에 대한 테스트도 있어야 할 것 같아요

2023-06-22 16:55 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  @DisplayName("FixedAmountVoucher 할인 성공 테스트 코드")
실패에 대한 테스트일 것 같아요. 그리고 어떤 실패 요인에 대한 테스트인지 드러나야 할 것 같아요

2023-06-22 16:55 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  }
`@ParemeterizedTest`로 여러 값을 테스트 해보면 좋을 것 같아요.

2023-06-22 16:55 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  long getDiscountValue();
`getter`가 꼭 필요했을 까요?

2023-06-22 23:46 UTC, seung-hun-h requested changes
은지님 리뷰남겼습니다.
다이어그램 구조는 잘 짜신 것 같습니다. 질문은 아래에 남겼으니 확인해주세요.
그리고 테스트 메서드 이름도 camel case로 작성해주세요

<img width="333" alt="Screenshot 2023-06-23 at 8 42 20 AM" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/60502370/508cd8b2-d0cb-4d91-9cd2-ff7d223ab410">

각 바우처들이 `VoucherType`을 구현하고 있는 것 같은데 의도하신게 맞을까요?


<img width="447" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/60502370/e343d5cc-9621-4305-8e77-eb7332685f4f">

VoucherService가 Voucher, VoucherRepository에 대한 직간접 참조를 할 것으로 예상이 되는데 방향이 반대가 되어야하는게 아닐까요?

<img width="125" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/60502370/77c2babc-3178-40c4-ac5d-c8c9462ca05b">

화살표가 다른데 이유가 있는걸까요?

2023-06-22 23:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
voucherId가 null 혹은 discountValue가 음수인 경우는 정상적인 경우인가요?
그렇지 않다면 검증 로직이 필요해 보입니다.

2023-06-22 23:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +            .findFirst()
`findAny()`도 있는데 `findFirst()`를 사용하신 이유가 있을까요?

2023-06-22 23:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +            .filter(voucher -> voucher.getType().equals(voucherType))
case sensitive한 로직인데 의도하신건가요?

2023-06-22 23:46 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucherTest.java
> +    System.out.println("percentDiscountVoucher = " + percentDiscountVoucher.discount(price));
불필요한 코드는 제거해주세요

2023-06-22 23:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  long discount(long price);
바우처가 `할인 가격`을 반환해야 할 지, `할인된 제품의 가격`을 반환해야할 지는 생각해봐야 할 것 같네요.
현재는 `할인된 제품의 가격`을 반환하고 있는데 이유가 있을까요?

2023-06-23 02:43 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
> +    return price - price * (discountValue / 100);
028a3a2

2023-06-23 05:49 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  PERCENT("percent");
commit b0536d4a32d25293dd5c65a14b6336a992ba274d

2023-06-23 08:47 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  long discount(long price);
제가 정확히 이해를 하지 못한 것 같아요🥺 가능하시다면 조금 더 설명을 해주면 감사하겠습니다,,!! 변수명이 명확하지 못한 것 같아서 변수명은 수정해두었습니다!

2023-06-23 08:50 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +public interface Voucher {
Voucher의 구현체 둘 다 같은 공통 기능을 수행하고 있어서 인터페이스를 사용했습니다! 더 좋은 방법이 있다면 피드백 남겨주시면 참고해서 개선하겠습니다!!🤩

2023-06-23 09:01 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +            .findFirst()
병렬처리를 할 때는 findAny가 findFirst 보다 성능이 좋지만 제가 작성한 코드에서는 둘 중 어떤 걸 써도 무방하다고 생각이 되어서 findFirst를 사용했습니다! 제가 잘못 알고있는 부분이 있거나 더 좋은 방법이 있다면 피드백 남겨주시면 참고해서 반영하겠습니다!🤩

2023-06-23 10:39 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  long discount(long price);
`할인 가격`이란 `1000원`, `2000원`과 같은 할인되는 가격을 말한 것입니다. 그리고 `할인된 제품의 가격`이란 10000원의 제품이 1000원 할인을 받아 `9000원`이 된 것을 말한 것이었습니다.

현재는 할인된 제품의 가격을 반환하고 있는 것 같아서 이러한 부분을 고려하고 작성하신 건지 궁금해 드린 질문이었습니다.

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +public interface Voucher {
공통 기능을 수행할 수 있는 다른 방법엔 어떤 것이 있나요?

2023-06-23 14:39 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +            .filter(voucher -> voucher.getType().equals(voucherType))
그 부분을 생각하지 못했습니다..! 피드백 반영하여 대소문자를 처리하였습니다 !🤩

2023-06-23 18:07 UTC, 1o18z commented
## ✅ ToDo
- [ ] getter 최소화
- [ ] 검증 로직 분리
- [ ] 바우처 생성 로직 구현
- [ ] 바우처 조회 로직 구현

## ✅ PR 포인트 & 궁금한 점 <!-- 리뷰어 분들이 집중적으로 보셨으면 하는 내용을 적어주세요 -->
- 아직은 getter를 대체할 만한 좋은 방법을 찾지 못해서 일단은 사용했지만, 계속 고민하면서 여러 방법을 시도 중입니다 !
- 다이어그램에 관한 피드백을 참고하여 수정해서 다시 올려두었습니다 !
- 피드백 반영한 커밋들을 중 실수로 refactor을 feat로 잘못 표기한 부분들이 있습니다🥺 주의해서 작성하겠습니다 !
- 삭제했다가 다시 추가하는 등의 불필요한 커밋들이 늘어나는 것 같아서 조금더 신중히 고려한 후 커밋을 작성하려고 합니다 !

2023-06-23 18:11 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  long discount(long price);
감사합니다 말씀해주신 부분 이해했습니다!😆 이 부분에 대해선 더 고민해보겠습니다!

2023-06-23 18:38 UTC, 1o18z commented on .gitignore
> +.idea/**/workspace.xml
[ab69169](https://github.com/prgrms-be-devcourse/springboot-basic/pull/652/commits/ab691693994bfc1a0531c1250574299cbe829832)

2023-06-23 18:38 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +            .filter(voucher -> voucher.getType().equals(voucherType))
[ca0c042](https://github.com/prgrms-be-devcourse/springboot-basic/pull/652/commits/ca0c042974bffe40666f8edbb709722b41a317bd)

2023-06-23 18:39 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
[59f856a](https://github.com/prgrms-be-devcourse/springboot-basic/pull/652/commits/59f856a6a1f16b3d6173099bdb1e3cfbbc910f8a)

2023-06-23 18:40 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  @DisplayName("FixedAmountVoucher 할인 성공 테스트 코드")
[b27a950](https://github.com/prgrms-be-devcourse/springboot-basic/pull/652/commits/b27a9508b51ca00c57688ad859434f283f39e620)

2023-06-23 18:40 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  }
[b27a950](https://github.com/prgrms-be-devcourse/springboot-basic/pull/652/commits/b27a9508b51ca00c57688ad859434f283f39e620)

2023-06-23 18:42 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  PERCENT("percent");
[b0536d4](https://github.com/prgrms-be-devcourse/springboot-basic/pull/652/commits/b0536d4a32d25293dd5c65a14b6336a992ba274d)

2023-06-24 08:07 UTC, 1o18z commented
## ✅ PR 포인트 & 궁금한 점
피드백 참고하며 수정하다보니 전체적으로 조금씩 바뀌게 되었습니다 !
반영한 피드백과 수정된 부분은 아래 ToDo에 요약해서 정리해두었습니다 !

## ✅ ToDo
- [X] 인터페이스를 추상클래스로 변경
	- 인터페이스와 추상클래스 중 많은 고민을 했지만, 인터페이스는 공통 기능을 모든 구현클래스에서 오버라이딩 하여 재정의해야 한다는 점과 추상클래스의 기능 확장이 가능하다는 점을 고려하여 현재 상황에서는 추상클래스가 좀 더 적합한 것 같다고 생각이 되어서 변경하여 다시 작성해보았습니다!
- [X] VoucherType(enum) 제거
	- 기존 VoucherType에서는 입력받는 타입이 존재하는 타입인지 검증한 후 해당 바우처를 생성하는 책임을 가지고 있었습니다. 하지만 VoucherType에서 생성의 책임을 가지는 것이 적절하지 않다고 생각이 들었고, 적절한 책임을 분리하다 보니 VoucherType을 굳이 사용하지 않아도 될 것 같다고 판단되어 제거를 하였습니다 ! 이 부분에 대해서 피드백을 받거나 추후에 필요하다고 판단이 되면 다시 추가할 예정입니다 !
- [X] 테스트코드 수정
	- 오타와 메소드명을 수정하고, @ParemeterizedTest를 사용하여 여러 값을 테스트하도록 수정하였습니다 !
	- 수정된 클래스들에 맞춰 테스트코드도 수정하였습니다 !
- [X] voucherId와 discountAmount 검증 로직 추가
	- voucherId가 null일 때와 discountAmount가 유효하지 않은 범위일 경우의 검증 로직을 추가했습니다 !
- [X] voucher type 대소문자 검증
	- 입력받는 타입을 LowerCase로 바꾼 후 타입을 체크해서 대문자로 입력받더라도 타입 구분이 가능하도록 수정하였습니다 !
- [X] 불필요한 코드 및 매직넘버 제거
- [X] .gitignore 수정
	- gitignore 파일에 Help.me와 .DS_Store를 추가하였습니다 !

2023-06-24 08:25 UTC, dojinyou commented on .gitignore
> +.idea/**/workspace.xml
이렇게 추가해도 이미 tracking 되고 있는 file들에는 ignore가 적용되지 않아요! 
이런 문제는 어떻게 해결할 수 있는 지 알아보세요!

2023-06-24 08:27 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
> +    return price - price * (discountValue / 100);
커밋도 같이 남겨주세요!

2023-06-24 08:40 UTC, dojinyou reviewed
코드 작성하실 때 조금만 더 집중을 해보시면 좋을 것 같아요! 
간단한 실수나 로직이 정확하지 않는 듯 문제가 있어보여요

2023-06-24 08:40 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +}
```suggestion
package com.prgrms.commandLineApplication.repository;

public class MemoryVoucherRepository {
}
```

2023-06-24 08:40 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
```suggestion
  public double discount(double price) {
    validateDiscountAmount(price);
    return price - getDiscountAmount();
  }
```
로직이 제대로 작성되지 않은 것 같아요. 그리고 멤버 변수에 대한 접근을 getter로 할 필요가 있을까요?

2023-06-24 08:40 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +    if (price < getDiscountAmount() || getDiscountAmount() < 0) {
매직넘버

2023-06-24 08:40 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +    if (price < getDiscountAmount() || getDiscountAmount() < 0) {
그리고 discountAmount가 왜 price보다 크면 안되나요?

2023-06-24 08:40 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  }
계산 실패하는 이유가 적혀있어야 할 것 같아요. 할인 결과가 불일치하는 건 테스트로서 의미가 있는 지 모르겠어요

2023-06-24 08:40 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  @DisplayName("FixedAmountVoucher 할인 계산 결과 일치 테스트")
CsvSource 좋은 것 같아요 👍

2023-06-24 08:40 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  }
이 메서드는 어디서 사용 되나요?

2023-06-24 08:40 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  }
해당 생성자를 퍼블릭으로 만든 이유가 궁금해요

2023-06-24 08:40 UTC, dojinyou requested changes
코드 작성하실 때 조금만 더 집중을 해보시면 좋을 것 같아요! 
간단한 실수나 로직이 정확하지 않는 듯 문제가 있어보여요

2023-06-24 08:41 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +public interface Voucher {
추상클래스를 사용할 수도 있고 클래스 안에 또 다른 클래스를 넣어서 처리하는 것도 가능할 것 같습니다!🤩

2023-06-24 08:43 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
이렇게 되면 실제로 voucherType에 어떤 값이 들어와도 문제가 안될 것 같은 데 적절한 동작 방식이 맞을까요?

2023-06-24 08:44 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +}
그리고 VoucherRepository의 implements 가 안된 것 같은데 맞나요?

2023-06-24 08:44 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/service/VoucherService.java
불필요해 보이는 데 미리 클래스를 만든 이유가 있나요?

2023-06-24 09:05 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +}
헉 voucher 패키지 내의 클래스들만 커밋을 하고 푸시했는데 나머지 repository와 service 등이 왜 올라간지 모르겠습니다,,,!! 잘 확인하겠습니다 죄송합니다🥺

2023-06-24 09:07 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/service/VoucherService.java
이 부분도 커밋할 때 체크하지 않았는데 지금 보니까 올라가 있네요..... 죄송합니다 주의해서 올리겠습니다! 🥲

2023-06-24 12:46 UTC, seung-hun-h requested changes
예외 상황에 대한 테스트도 잘 작성해주셨네요.
다른 사람이 테스트 코드를 읽는다고 생각하고 좀 더 읽기 쉽게 작성하면 더 좋을 것 같습니다.

2023-06-24 12:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
이 부분은 discountAmount가 `Voucher`의 인스턴스 변수이고, private으로 설정되어 있어 그런 것 같습니다. 
`price`가 아닌 `discountAmount`에 대한 유효성 검증 로직인 것 같아요.  `discount()`에 있을 것이 아니라 `FixedAmountVoucher`에 있어야 할 로직인 것 같네요

2023-06-24 12:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
```suggestion
  public FixedAmountVoucher(String voucherType, double discountAmount) {
    validateDiscountAmount(discountAmount);
    super(voucherType, discountAmount);
  }

  public double discount(double price) {
    return price - getDiscountAmount();
  }
```

2023-06-24 12:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
자바의 double 형은 정확한 연산 결과를 반환하지 못합니다. 다른 데이터 형을 사용할 필요가 있을 것 같네요.
소수가 계산이 정말 필요한지, 소수를 double 말고 다른 방식으로 계산할 수는 없을 지 고민해보세요

- https://jerry92k.tistory.com/6

2023-06-24 12:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  }
그리고 현재 사용하지 않는 getter 들도 제거해주세요

2023-06-24 12:46 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucherTest.java
> +  }
```suggestion
  void percentDiscountVoucher_계산_성공(double discountValue, double expected) {
    String voucherType = "percent";
    percentDiscountVoucher = new PercentDiscountVoucher(voucherType, discountValue);
    
    double result = percentDiscountVoucher.discount(100000);
    
    assertThat(result).isEqualTo(expected);
  }
```
이렇게 작성하면 더 읽기 편한 것 같아요.

2023-06-24 12:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
동의 합니다 단순 String 타입 보다는 다른 타입을 정의해주는 것이 좋아 보이네요

2023-06-25 09:31 UTC, 1o18z commented on .gitignore
> +.idea/**/workspace.xml
헉 그렇군요...!! 찾아보고 해결해보겠습니다!🤩

2023-06-25 09:47 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
뒤에서 구현할 클래스에서 받는 타입을 검증하는 메소드를 생성하려고 String으로 받도록 해두었었습니다 ! 더 좋은 방법을 고민해보겠습니다 !🤩🍀

2023-06-25 09:59 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +    if (price < getDiscountAmount() || getDiscountAmount() < 0) {
할인할 가격이 구매할 제품의 가격보다 크지 않아야 한다고 생각하고 작성하였습니다 ! 할인 가격이 제품 가격보다 크다는 상황도 고려하고 작성하는 것이 더 좋을까요 ?!☀️

2023-06-25 10:15 UTC, merged

2023-06-25 10:24 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  }
현재 Voucher에 있는 getter들이 다른 클래스에서 사용되어서 작성해두었습니다 ! getter를 대신할 수 있는 다른 방법을 찾아서 적용하겠습니다 !!🤩🔥

2023-06-25 10:36 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucherTest.java
> +  }
😲 훨씬 눈에 잘 들어옵니다!! 이런 부분도 고려해가며 테스트 코드 작성하겠습니다!🤩

2023-06-26 00:11 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
네!! 자료 참고하여 더 나은 방법으로 수정하겠습니다! 감사합니다☀️

2023-06-26 12:37 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
2caab08459e818932edaca263413daf7a4a43df3

2023-06-26 12:39 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
커밋 후 추가되지 않은 부분이 있어서 'commit —amend -m' 으로 추가했더니 아직 구현하지 않은 다른 클래스들도 같이 올라가버렸습니다🥺 이전 피드백 반영할 때도 이런 상황이 생겼었는데 이유를 이제야 알게되었습니다 주의하겠습니다🥲🥲☀️

2023-06-26 12:40 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +    if (price < getDiscountAmount() || getDiscountAmount() < 0) {
19c0a4f93a17a095c19c98b17d2160adb5e8ad84

2023-06-26 12:41 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  }
548b7c72752081e1caca0d1e386914ca3b94c79f

2023-06-26 12:42 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  }
실패 이유를 좀 더 명확하게 작성하고 예외 테스트도 추가하였습니다 !!🌟

2023-06-26 12:43 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  }
286b01d022386cf62f9ce2f9e6c88125638cec63

2023-06-26 12:45 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +  }
9494104083af074a477b5d0a059610709dc06b8e

2023-06-26 12:47 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucherTest.java
> +  }
15990a6431fb73f3a39b18aaee2a4f91aafc2d93