Weonest/week1
prgrms-be-devcourse/springboot-basic pull request #655
Opened 2023-06-22 16:06 UTC by weonest

## 📌 과제 설명 
바우처 설계 및 바우처 개발을 진행하였습니다.

팀내 PR 규칙을 정하기 이전에 사용자 입력부분을 미리 구현을 해두었기 때문에 같이 사용자 입력 부분도 PR에 올라가게 되었습니다.

객체지향 생활체조를 최대한 지켜보려고 노력했으며, 항상 Test코드를 짜지 않고 기능만 구현했던 안 좋은 습관을 고치기 위해 틈틈이 단위 테스트도 진행해보았습니다!

## 👩‍💻 바우처 클래스 다이어그램
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/98159941/d3a1929e-4c1f-4bd8-a922-e58e5fd87228)

## ✅ ToDo
- [x] 바우처 생성 로직 및 조회 로직

## ✅ PR 포인트 & 궁금한 점 
- 원시값을 포장해야 한다는 생각으로 FixedAmountVoucher와 PercentDiscountVoucher에 사용되는 `long amount` 를 각각 DiscontAmount, DiscountPercent 객체로 감싸보았는데, 이런식으로 하면 되는 것인지 궁금합니다!
- 주차별로 진행되는 것이 아니다보니 후에 있을 콘솔에서 웹으로의 전환을 생각해서 패키지 구조도 변경해보았습니다. `console`패키지 내부에는 console로 동작할 때에 필요한 객체들만 모았는데, 전환하려면 시간이 꽤 남았음에도 불구하고 너무 빨리 패키지 구조를 변경한 것 같아 이부분에 대한 의견을 듣고싶습니다!

2023-06-23 00:22 UTC, seung-hun-h requested changes
console 관련 로직을 패키지로 분리한 점은 좋은 것 같습니다.
값 객체도 잘 활용 하셨지만, 조금 부족한 부분이 있는 것 같아서 리뷰 남겼습니다.

DiscountAmount, DiscountPercent도 추상화 해볼 수 있을 것 같다는 생각이 드네요. 코드를 보면 각각 정액 할인 바우처, 비율 할인 바우처에 종속적인 클래스인데 다이어그램에는 표현이 안되어 있는 것 같네요

커스텀 예외 클래스도 작성하셨는데 현재 코드를 보면 RuntimeException의 하위 예외들과 크게 다르지 않다는 생각이 드네요. 정의하신 이유가 있을까요?

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/DiscountAmount.java
> +        validateDiscountAmount(amount);
👍

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/DiscountAmount.java
> +    private final long MAX_AMOUNT = Integer.MAX_VALUE;
`Integer.MAX_VALUE`가 비즈니스적으로 의미가 있는건가요?
그렇지 않다면 건희님이 정책을 만들어 max value를 지정해주는 것도 좋아보여요

그리고 상수는 `static final`을 사용하는데요 왜 상수에 `static`을 사용하는 지 생각해보시면 좋을 것 같아요

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/DiscountAmount.java
> +    }
값 객체를 만들어 사용하셨는데, long 타입을 사용하지 않고 `DiscountAmount`를 사용할 수 있을 것 같아요.
```suggestion
    public DiscountAmount discount(DiscountAmount beforeDiscount) {
        return new DiscountAmount(beforeDiscount.amount - amount);
    }
```

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/FixedAmountVoucher.java
> +        if (beforeDiscount > discountAmount.getAmount()) {
discount가 가능한지 확인하는 로직도 `DiscountAmount`에 작성해주면 좋겠네요.
그렇게 되면 getter도 사라지겠네요

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/FixedAmountVoucher.java
> +    private final LocalDateTime createdDate = LocalDateTime.now();
이 코드는 통제할 수 없는 코드입니다. 테스트하기 어려울 수 있겠네요.
예를 들어 바우처의 유효기간 만기 테스트를 작성할 때 실제로 생성된지 7일 후에 테스트가 통과할 수 있을 것 같아요.
통제할 수 없는 코드는 외부에서 주입 받도록 하면 좋겠네요

https://jojoldu.tistory.com/676

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/Voucher.java
> +    Integer expirationDate();
이 메시지들은 내부 구현에 해당한다고 생각하는데요. 정의하신 이유가 있을까요?

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/FixedAmountVoucher.java
> +        if (beforeDiscount > discountAmount.getAmount()) {
discount하기 전 사용가능한 바우처인지 확인 해야할 것 같네요

2023-06-23 00:22 UTC, seung-hun-h commented on src/test/java/com/programmers/domain/uitl/MenuTypeTest.java
> +    }
유효하지 않은 메뉴에 대한 테스트인것 같은데요.
테스트 이름과 displayname에 그러한 내용이 포함되어야 할 것 같아요

https://hilucky.tistory.com/216

2023-06-23 00:22 UTC, seung-hun-h commented on src/test/java/com/programmers/domain/voucher/FixedAmountVoucherTest.java
> +        var fixedAmountVoucher = new FixedAmountVoucher(UUID.randomUUID(), amount);
`var`를 사용하셨는데요, 코드 일관성을 위해서 타입을 사용하거나 `var`를 사용하거나 하나만 선택 해서 사용해주시면 좋을 것 같아요

2023-06-23 00:22 UTC, seung-hun-h commented on src/main/java/com/programmers/domain/voucher/VoucherPolicy.java
이 클래스도 console에 있어야할 것 같은데 아닌가요?

2023-06-23 04:13 UTC, weonest commented on src/main/java/com/programmers/domain/voucher/DiscountAmount.java
> +    private final long MAX_AMOUNT = Integer.MAX_VALUE;
39f4d1af3580b34c101d899ca36b7ddafad25bc5

2023-06-23 04:31 UTC, weonest commented on src/main/java/com/programmers/domain/voucher/FixedAmountVoucher.java
> +        if (beforeDiscount > discountAmount.getAmount()) {
828fca068ee7bf96a83fc4a628de0fc204acdd5f
계산 가능 여부를 확인하는 discountable 메서드를 만들어 반영하였습니다!

2023-06-23 05:13 UTC, weonest commented on src/main/java/com/programmers/domain/voucher/FixedAmountVoucher.java
> +    private final LocalDateTime createdDate = LocalDateTime.now();
f33cf8938c3b55039371007dc2437be9e19eb0e0
첨부해주신 블로그 참조하여 유효기간에 대해서 통제 가능하도록 코드를 작성해보았습니다! 외부에서 생성날짜를 입력받도록 하였으며, Integer로 변환했던 부분에 대해서 LocalDate를 그대로 이용할 수 있도록 변경하였습니다.

2023-06-23 05:13 UTC, weonest commented on src/main/java/com/programmers/domain/voucher/Voucher.java
> +    Integer expirationDate();
이 부분에 대해서는 잘 살펴보지 못했던 것 같습니다! 유효기간에 대한 리팩토링과 함께 수정하였습니다.

2023-06-23 05:21 UTC, weonest commented on src/main/java/com/programmers/domain/voucher/FixedAmountVoucher.java
> +        if (beforeDiscount > discountAmount.getAmount()) {
be36ccece8aee0339548426432fe117b53c8b8da
말씀하신대로 DiscountAmount 객체 내에서는 가격에 대한 검증을 진행하였고, Voucher 구현체 내부에서는 해당 Voucher가 사용가능한 Voucher인지 확인하도록 수정하였습니다!

2023-06-23 05:24 UTC, weonest commented on src/main/java/com/programmers/domain/voucher/VoucherPolicy.java
오늘 구현해야 하는 바우처 생성 로직과 관련해서 해당 클래스 내부에서 Voucher 를 생성하는 함수형 인터페이스를 정의하려고 하였습니다!

2023-06-23 08:27 UTC, weonest commented on src/test/java/com/programmers/domain/voucher/FixedAmountVoucherTest.java
> +        var fixedAmountVoucher = new FixedAmountVoucher(UUID.randomUUID(), amount);
`var`를 사용하지 않는 쪽으로 통일해보겠습니다!

2023-06-23 08:27 UTC, weonest commented on src/test/java/com/programmers/domain/uitl/MenuTypeTest.java
> +    }
해당 내용 참고하여 테스트 코드 작성토록 하겠씁니다!

2023-06-23 20:13 UTC, dojinyou reviewed
pr에 작업 내용이 섞여서 리뷰하기가 힘들었어요. 다음 부터는 조금 더 신경 써주시길 바래요.
추가로 1차 pr이 설계 작업이 완료되지 않은 상태에서 구현을 하는 건 리뷰로 인해 설계가 변경된다면 다시 작업을 해야 하기 때문에 조금은 비효율적일 수 있을 것 같아요!

2023-06-23 20:13 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/PercentDiscountVoucherTest.java
> +    }
이 테스트는 10일 뒤에 돌려도 통과할까요?

2023-06-23 20:13 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    @DisplayName("VoucherService 바우처 생성 및 조회 테스트")
하나의 테스트에서는 하나의 로직만 검증하는 것이 일반적이에요!

2023-06-23 20:13 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +        System.out.println(voucherService.findVouchers());
검증 로직이 누락된 것 같아요

2023-06-23 20:13 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    VoucherService voucherService = new VoucherService(voucherRepository);
Repository 상태에 따른 테스트 영향을 받지 않게 초기화 작업이 매 테스트 이전 혹은 이후에 진행되어야 할 것 같아요

2023-06-23 20:13 UTC, dojinyou requested changes
pr에 작업 내용이 섞여서 리뷰하기가 힘들었어요. 다음 부터는 조금 더 신경 써주시길 바래요.
추가로 1차 pr이 설계 작업이 완료되지 않은 상태에서 구현을 하는 건 리뷰로 인해 설계가 변경된다면 다시 작업을 해야 하기 때문에 조금은 비효율적일 수 있을 것 같아요!

2023-06-24 10:30 UTC, weonest commented on pom.xml
> +        <version>3.0.7</version>
가장 최신 버전을 사용하는 경우 외부 라이브러리 의존성을 주입할 때 버전이 맞지 않아 작동하지 않았던 기억이 있어서 항상 최신 버전의 바로 이전 버전을 사용하고 있습니다!

2023-06-24 10:31 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/VoucherRepository.java
> +
확인했습니다!

2023-06-24 10:37 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/VoucherRepository.java
> +    List<VoucherResponseDto> findAll();
원본 Entity를 사용자에게 그대로 반환하는 것보다는 `VoucherRequestDto`와 같이 DTO 객체에 담아서 전달하는 것이 안전하다고 생각하여 사용하였습니다.

2023-06-24 10:49 UTC, weonest commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +public class VoucherService {
`service`의 경우에는 인터페이를 통한 다형성을 활용하게 될 일이 없을 것이라 생각했습니다. 현재로서는 `service`의 기능이 ` PercentDiscount, FixedAmount`에 따라 변하는 것도 아니기 때문에 interface를 생각해보지 않았습니다. 제가 놓친 부분이 있다면 피드백 해주시면 감사드리겠습니다!

2023-06-24 10:50 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
유효기간을 년, 월, 일로만 판단하고 싶었기 때문에 LocalDate를 사용하였습니다. LocalDate 이외에 다른 방법이 있는지 공부해보도록 하겠습니다!

2023-06-24 10:57 UTC, weonest commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +    private final TriFunction<UUID, Long, LocalDate, Voucher> constructor;
이 부분에 대해서는 생각해보지 못했습니다.. 말씀해주신 대로 다양한 형태의 생성자가 존재하게 될 경우 `TriFunction`만으로는 처리하지 못하기에, 이러한 방식보다는 `Builder`패턴을 구현해야 하는 것이 맞지 않을까 생각하는데 도진님의 의견을 듣고싶습니다!

2023-06-24 11:02 UTC, weonest commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +public enum VoucherPolicy {
`Voucher`를 어떠한 타입으로 생성할 것인지를 결정하는 정책?이라고 생각하였는데, 말씀대로 오히려 어떤 객체를 생성할 것인가를 다루기에 `factory`에 가까운 것 같습니다. 

바로 위의 `TriFunction` 부분과 관련하여 도진님의 의견을 들은 뒤 해당 클래스를 수정해도 될까요?

2023-06-24 11:02 UTC, weonest commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +
확인했습니다!

2023-06-24 11:03 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
> +    private final String arrow = "> ";
검토 도중 발견하여 수정하였습니다!

2023-06-24 11:08 UTC, weonest commented on src/main/java/com/programmers/console/view/OutputView.java
> +
확인했습니다!

2023-06-24 11:11 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
> +    }
``` java
@Override
    public String inputMenu() {
        println(ConsoleMessage.COMMAND_MESSAGE.getMessage());
        print(arrow);
        return userInput();
    }

    @Override
    public String inputVoucherMenu() {
        println(ConsoleMessage.CREATE_VOUCHER_TYPE_MESSAGE.getMessage());
        print(arrow);
        return userInput();
    }

    @Override
    public String inputVoucherDiscountValue() {
        println(ConsoleMessage.VOUCHER_DISCOUNT_VALUE_MESSAGE.getMessage());
        print(arrow);
        return userInput();
    }
```
PR이 겹치지 않도록 코드로 첨부합니다 (죄송합니다)! 
이와 같은 식으로 변경해보았습니다!

2023-06-24 11:14 UTC, weonest commented on src/main/java/com/programmers/exception/AmountValueException.java
> +package com.programmers.exception;
코드를 짤 때 신경쓰지 못했던 부분인 것 같습니다. 웹으로 전환되더라도 유효한 예외들이기 때문에 global 형태로 다뤄도 괜찮을까요?

2023-06-24 11:32 UTC, weonest commented on src/main/java/com/programmers/voucher/dto/VoucherRequestDto.java
> +public class VoucherRequestDto {
이 부분에 대해서는 무지하여 사용하지 않았었습니다. 이를 계기로 `record`에 대해 조사해보니 `compact constructor`를 제공해주기도 하고 암시적으로 불변객체이기 때문에 `DTO`로 활용하기에 적합한 클래스임을 알게 되었습니다. 제약 사항으로는 `static` 선언이 아닌 인스턴스는 허용치 않고 다른 클래스를 상속 받을 수 없다는 점이 있는데 해당 사항은 `DTO`로 활용할 때에는 제약이 없는 것 같습니다!

2023-06-24 11:35 UTC, weonest commented on src/main/java/com/programmers/voucher/dto/VoucherRequestDto.java
> +    private long discountAmount;
e780e954d5be8e64c278681b6ccc80157aedf59a
`record` 클래스로 변경하였습니다.

2023-06-24 11:57 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/DiscountAmount.java
> +    }
놓쳤던 부분입니다 수정했습니다!
248abb0cbe1225ee8b5be0ec6f4b319ae7423fc9

2023-06-24 11:57 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    private final String TYPE = "FixedAmountVoucher";
`getSimpleName()` 을 생각지 못하고 있었습니다. 이를 적용하여 수정하였씁니다.
248abb0cbe1225ee8b5be0ec6f4b319ae7423fc9

2023-06-24 11:58 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    }
매직넘버 적용하였습니다.
248abb0cbe1225ee8b5be0ec6f4b319ae7423fc9

2023-06-24 12:13 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +public class PercentDiscountVoucher implements Voucher {
여기서의 코드가 거의 비슷함은 `FixedAmountVoucher`와 `PercentDiscountVoucher`를 말씀하시는 걸까요? 
우선 이 부분이라고 생각하고 답변을 드리겠습니다! 해당 부분에 대해서 고민이 많았는데, 이름만 다를뿐 내부 동작은 거의 동일하며 동작 자체도 전략 패턴과 비슷하게 `Discount`의 구현체가 무엇인지에 따라 `discount()` 의 동작이 바뀌기 때문에 바우처를 구분짓지 않고 하나의 바우처로 관리할까 고민을 하였었습니다. 그런데 이러한 방법으로 관리하게 되면 후에 다양한 종류의 바우처를 추가하게 되는 경우 하나의 `Voucher` 객체에 너무 많은 책임이 몰릴 것이라 생각하여 우선은 변경하지 않았는데 이에대한 도진님 의견을 듣고싶습니다!

2023-06-24 12:18 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        return Collections.emptyList();
ba6ebd89d63ec281464c9bfe34058b7cf2676000
`storage.values().stream().map(VoucherResponseDto::new).collect(Collectors.toList());`
이와 같은 식으로 변경하였습니다!

2023-06-24 12:20 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        return Optional.empty();
넵! PR을 받으며 변하는 부분이 생길 것이라고 생각하여 아직 구현하지 않았습니다.

2023-06-24 12:20 UTC, weonest commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +
적용하였습니다!

2023-06-24 12:22 UTC, weonest commented on src/test/java/com/programmers/voucher/VoucherApplicationTests.java
> +}
사용하지 않는 Test이기에 삭제하였습니다!

2023-06-24 12:26 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/DiscountAmountTest.java
> +            , "342345"
`" "` 내부에서 shit + enter로 탈출하고 `,`를 찍는게 편해서 이런식으로 작성하였습니다

2023-06-24 12:28 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +        LocalDate localDate = LocalDate.of(2023,6, 23);
90f84b37d0b22c3b023a9fe8d1b163e836e10874
바우처 생성을 항항상 유효하도록 변경하였습니다!

2023-06-24 12:31 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/PercentDiscountVoucherTest.java
> +    }
83b3ab99b0f1f1a8ea12608a5a23626c96687234
유효한 경우와 그렇지 않은 경우의 테스트를 나누어 진행하도록 변경하였습니다!

2023-06-24 12:51 UTC, weonest commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +        System.out.println(voucherService.findVouchers());
450de3dca97da6081fcb005ab226977910e129d6
피드백 반영하였습니다.!

2023-06-24 12:51 UTC, weonest commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    VoucherService voucherService = new VoucherService(voucherRepository);
450de3dca97da6081fcb005ab226977910e129d6
@BeforeEach 를 통해 초기화를 시켜주었습니다!

2023-06-24 12:52 UTC, weonest commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    @DisplayName("VoucherService 바우처 생성 및 조회 테스트")
450de3dca97da6081fcb005ab226977910e129d6
바우처 타입과 값에 대한 생성 테스트만 진행토록 변경하였습니다!

2023-06-24 13:17 UTC, dojinyou commented on pom.xml
> +        <version>3.0.7</version>
해당 과제에서 어떤 외부 라이브러리의 의존성을 고려하셨나요?

2023-06-24 13:17 UTC, dojinyou commented on src/main/java/com/programmers/voucher/repository/VoucherRepository.java
> +    List<VoucherResponseDto> findAll();
그렇다면 다른 메서드들은 왜 Voucher를 그대로 반환하나요?

2023-06-24 13:18 UTC, dojinyou commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +public class VoucherService {
테스트를 위해서 별도의 구현 객체를 만들어야 할 때는 어떻게 하실 생각이신가요?

2023-06-24 13:21 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
유효 기간이 아닌 생성일자는 년,월,일만 기록한 이유가 있나요? 그것이 더 많은 시간 데이터를 기록하는 것보다 나은 점이 무엇인가요?

2023-06-24 13:22 UTC, dojinyou commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +public enum VoucherPolicy {
factory는 util에 가깝다고 생각하시나요?

2023-06-24 13:26 UTC, dojinyou commented on src/main/java/com/programmers/exception/AmountValueException.java
> +package com.programmers.exception;
console package에 있는 것들도 웹으로 변경되었을 때 입력으로 들어오는 값들에 대한 validation 과정에서 발생 될 수도 있을 것 같은 데 어떻게 생각하시나요?

2023-06-24 13:27 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +public class PercentDiscountVoucher implements Voucher {
다양한 종류의 바우처라고 하는 건 어떤 것이 있을까요?

2023-06-24 13:29 UTC, weonest commented on pom.xml
> +        <version>3.0.7</version>
해당 과제에서는 `assertj` 이외에는 고려하지 않았습니다.

2023-06-24 13:29 UTC, dojinyou commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        return Collections.emptyList();
`.collect(Collectors.toList())` 이 친구 말고 `.toList()`는 없나요? 있다면 둘의 차이를 한번 찾아보시면 좋을 것 같아요!

2023-06-24 13:31 UTC, weonest commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +public class VoucherService {
해당 부분에 대해서는 생각치 못했습니다. `ServiceImpl` 을 구현토록 해보겠습니다.

2023-06-24 13:31 UTC, dojinyou commented on pom.xml
> +        <version>3.0.7</version>
그렇다면 최신 버전을 안 쓸 다른 이유가 있나요?

2023-06-24 13:34 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
기간에 대한 구분자가 적기 때문에 관리하기 좀 더 편할 것이라고 생각했습니다.

2023-06-24 13:36 UTC, weonest commented on pom.xml
> +        <version>3.0.7</version>
후에 다른 의존성을 추가하게 될 경우 최신 버전에서 작동하지 않을 경우를 대비하는 것 이외에는 없습니다.

2023-06-24 13:41 UTC, dojinyou reviewed
코멘트 확인 부탁 드립니다!
파일에 개행 문자체크도 해주세요!

2023-06-24 13:41 UTC, dojinyou commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    private Command getRequest() {
[nit]
`getCommand`?

2023-06-24 13:41 UTC, dojinyou commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    }
`public`으로 설계한 이유가 있나요?

2023-06-24 13:41 UTC, dojinyou commented on src/main/java/com/programmers/console/util/Command.java
> +    private final String command;
Command.command라는 네이밍이 자연스럽지 않은 것 같아요!
그리고 단순히 `name` 필드의 lowerCase라면 별도로 저장하고 있어야 하는 이유가 있나요?

2023-06-24 13:41 UTC, dojinyou commented on src/main/java/com/programmers/console/view/OutputView.java
> +
따로 불필요한 개행이 삭제 안된 것 같은데 어떤 것을 확인하셨나요?

2023-06-24 13:42 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/VoucherRepository.java
> +    List<VoucherResponseDto> findAll();
save() 메서드에 대해서는 바우처를 반환할지 바우처 Id를 반환할지 고민 중에 있었습니다.  `voucherId`를 반환하도록 변경하겠습니다!

2023-06-24 13:43 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
구분자가 적어서 관리가 편하다는 게 어떤 부분인지 조금 더 자세히 설명해주실 수 있나요?

2023-06-24 13:44 UTC, dojinyou commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +    private final TriFunction<UUID, Long, LocalDate, Voucher> constructor;
다양한 방법이 있을 것 같아요! 말씀해주신 빌더 패턴도 좋을 수 있고 따로 객체를 만들어서 관리할 수도 있을 것 같구요! 
다양하게 고민해보시면 좋을 것 같아요

2023-06-24 13:51 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +public class PercentDiscountVoucher implements Voucher {
고정값, 퍼센트와는 다른 `Discount` 구현체가 여러 개 생긴다면 어떻게 될까 라는 가정이었기 때문에 구체적으로 생각해본적은 없습니다.

2023-06-24 13:55 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        return Collections.emptyList();
`toList()`는 반환한 List에 대해서 변경이 불가능한 `UnmodifiableList`로 구현된다는 사실을 알게 되었습니다. 감사합니다!

2023-06-24 14:00 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
`LocalDateTime` 을 사용한다면 시간, 분, 초, 미리세컨드 등을 포함하게 되기 때문에 날짜에 관한 테스트를 작성할 때 구분자가 좀 더 적은 `LocalDate`가 편할 것이라고 생각했습니다!

2023-06-24 14:03 UTC, weonest commented on src/main/java/com/programmers/exception/AmountValueException.java
> +package com.programmers.exception;
모든 예외를 global로 관리하려고 하였습니다!

2023-06-24 14:06 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/DiscountAmountTest.java
> +    }
bbde18f727060f3c50040d0bad72133ea4e6a2c0
DisplayName의 추가와 함께 메서드 명을 변경하였습니다!

2023-06-24 14:10 UTC, weonest commented on src/main/java/com/programmers/console/util/Command.java
> +    private final String command;
나중에 유저 프로그램의 추가가 있는 것으로 아는데 그때에 더 많은 Command를 다루게 될 것이라고 생각하여 Enum으로 관리해보았씁니다!

2023-06-24 14:16 UTC, seung-hun-h requested changes
건희님 리뷰남겼습니다.
코드를 일관성있게 짜도록 노력해보세요.

2023-06-24 14:16 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/dto/VoucherRequestDto.java
> +}
record라서 getter, 기본 생성자 전부 필요 없는 코드인 것 같아요.

```suggestion
public record VoucherRequestDto(String voucherType, long discountAmount) {
}
```

2023-06-24 14:16 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/dto/VoucherResponseDto.java
> +        }
```suggestion
       if (voucher instanceof PercentDiscountVoucher percentDiscountVoucher) {
            this.type = percentDiscountVoucher.getClass().getSimpleName();
            return;
        }
        
        if (voucher instanceof FixedAmountVoucher fixedAmountVoucher) {
            this.type = fixedAmountVoucher.getClass().getSimpleName();
        }
```

이렇게 변경되어야 할 것 같네요.

2023-06-24 14:16 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
그리고 이렇게 접근자에 대한 메시지를 정의하다보면 필드가 추가될 때마다 계속해서 늘어날 거 같은데 수정이 필요해 보입니다.

2023-06-24 14:16 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        return Optional.empty();
구현이 아직 안된 것이라면 
```suggestion
	throw new UnsupportedOperationException(...);
```
이렇게 해주는 것이 좋아 보이네요

2023-06-24 14:16 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
console의 의존성이 도메인까지 와 있어서 수정이 필요해보입니다.

2023-06-24 14:16 UTC, seung-hun-h commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +
불필요한 공백도 제거해주세요

2023-06-24 14:16 UTC, seung-hun-h commented on src/test/java/com/programmers/voucher/domain/VoucherPolicyTest.java
> +    public void createVoucherTest(String command) {
```suggestion
    void createVoucherTest(String command) {
```

2023-06-24 14:16 UTC, seung-hun-h commented on src/main/java/com/programmers/console/util/Menu.java
> +            "Type **list** to list all vouchers."),
```suggestion
    COMMAND_MESSAGE("""
		=== Voucher Program ===
		Type **exit** to exit the program.
		Type **create** to create a new voucher.
		Type **list** to list all vouchers.
		"""),
```

2023-06-24 15:11 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
> +    private final static Scanner scanner = new Scanner(System.in);
db787c2a12ad57e5c96ce33fa8801055c7519d2b
모두 수정하였습니다!

2023-06-24 15:12 UTC, weonest commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +    }
d7f6b591da126fc8a8ee9e720ea7e27290e6fe49
적용하였습니다!

2023-06-24 15:13 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/DiscountAmount.java
> +    private static final long MAX_AMOUNT = 1000000;
변경하였습니다! 언더바를 잊고 있었네요!

2023-06-24 15:14 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/DiscountAmount.java
> +    }
91293947269d5dad421833d0d83885546a4a71f6
메서드 작성 후에 놓쳤던 부분이었습니다! 감사합니다!

2023-06-24 15:16 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/DiscountPercent.java
> +    private static final double HUNDRED = 100.0;
퍼센트 연산 부분에서 강의 내용을 바탕으로 코드를 작성하다보니 `beforeDiscount` * `(percent / 100)` 연산을 하게 되는 경우 소수점 아래가 모두 날아가기 때문에 항상 0을 반환하는 문제가 있었습니다. `double`을 이용하면 이러한 부분을 해결할 수 있었기 때문에 적용하였는데, 연산식을 바꾸는 것이 나았을까요?

2023-06-24 15:18 UTC, weonest commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
여기서 console의 의존성이 어떤 부분인지 알려주실 수 있을까요..!?

2023-06-24 15:19 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +
0b7a6f2cf577747a13f3e8b4e006569b00256a95
적용하였습니다!

2023-06-24 15:34 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
죄송합니다..ㅠㅜ 많은 고민을 해봤지만 접근자 없이 `ResponseDto`를 어떤 방식으로 만들면 좋을지 잘 모르겠습니다..

2023-06-24 15:55 UTC, weonest commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +    private final TriFunction<UUID, Long, LocalDate, Voucher> constructor;
e14b7a02e20fac832717595fc28628bb57a99027
바우처 생성을 팩토리 클래스를 통해 가능토록 해보았습니다!

2023-06-24 15:55 UTC, weonest commented on src/main/java/com/programmers/console/util/VoucherPolicy.java
> +public enum VoucherPolicy {
e14b7a02e20fac832717595fc28628bb57a99027
바우처 생성과 연관된 만큼 `domain`패키지로 이동하였습니다!

2023-06-24 15:56 UTC, weonest commented on src/main/java/com/programmers/console/view/OutputView.java
> +
죄송합니다! 확실하게 다시 반영하였습니다!

2023-06-24 16:00 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        return Optional.empty();
e14b7a02e20fac832717595fc28628bb57a99027
승훈님 의견 반영하였습니다!

2023-06-24 16:01 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +    @DisplayName("유요한 바우처 할인 테스트")
반영하였습니다!

2023-06-24 16:06 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +        this.expirationDate = expirationDate();
4991e302557c9f4606859c768168206f9e1a9821
우선은 위 코드를 반영하였습니다. 
만료일에 대한 값을 갖는 객체를 만들고 그 객체와 바우처의 생성일을 비교하는 방식으로 진행하는 것이 좋을까요?

2023-06-24 16:10 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +        this.voucherId = validateVoucherId(voucherId);
85174be4942c307509121da86449345cc75e7465
메서드가 검증만 하도록 변경하였습니다

2023-06-24 16:11 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    }
혹시나 나중에 외부에서 유효한 바우처인지 확인해야 하는 경우가 생길 수도 있지 않을까 하여 `public`으로 지정하였었습니다.

2023-06-24 16:13 UTC, weonest commented on src/main/java/com/programmers/voucher/dto/VoucherRequestDto.java
> +}
07bfe5da2a22a6995e6463a469291431383b6767
해당 사항 반영하였습니다!

2023-06-24 16:15 UTC, weonest commented on src/main/java/com/programmers/voucher/dto/VoucherResponseDto.java
> +        }
87cb44614932827f3906b8ab6f9232e1b415be8d
반영하였습니다!

2023-06-24 16:16 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/VoucherPolicyTest.java
> +    public void createVoucherTest(String command) {
피드백 사항에 대해서 반영을 했었지만, 생성 로직이 변경되면서 해당 클래스가 삭제되었습니다!

2023-06-24 16:17 UTC, weonest commented on src/main/java/com/programmers/console/util/Menu.java
> +            "Type **list** to list all vouchers."),
6175ff401aa2fe412ce81f06507a8ef0e42d3336
해당 피드백 반영 완료하였습니다! 알고있던 방법인데 까먹고 있었네요 감사합니닿ㅎ!

2023-06-24 16:18 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    private Command getRequest() {
반영하였습니다!

2023-06-24 16:18 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    }
`private`으로 변경 완료하였습니다!
6175ff401aa2fe412ce81f06507a8ef0e42d3336

2023-06-25 01:57 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
클래스 상위에서 import를 확인해보시면 될 것 같아요!
<img width="568" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/60502370/63545fc5-57ed-492f-94ae-c2046c7e367b">

2023-06-25 01:59 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/DiscountPercent.java
> +    private static final double HUNDRED = 100.0;
long을고 캐스팅하면 소숫점 아래가 사라지는 것 아닌가요?

2023-06-25 02:00 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +        this.expirationDate = expirationDate();
`바우처를 사용할 수 있는 기간`을 나타내는 값 객체를 만들어봐도 좋을 것 같다는 생각이 드네요.

2023-06-25 02:01 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    }
접근 제어자는 항상 보수적으로 가져가는 것이 좋을 것 같아요. 명확한 이유가 없다면 private으로 만들고 나중에 public으로 전환해도 좋다고 생각합니다. public 으로 리팩토링하면서 문제가 발생할 수 있다고 예상되는 코드는 작성하지 않는 방향으로 하면서요.

2023-06-25 03:31 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/DiscountPercent.java
> +    private static final double HUNDRED = 100.0;
`percent / 100` 부분에서 100이 `double`이 아닌 경우 무조건 0으로 계산 되기 때문에 항상 0을 반환했습니다!

2023-06-25 03:35 UTC, weonest commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
해당 부분 팩토리 클래스 생성으로 console 관련 의존성 없애도록 하였습니다. 감사합니다!
https://github.com/prgrms-be-devcourse/springboot-basic/commit/e14b7a02e20fac832717595fc28628bb57a99027

2023-06-25 04:15 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/DiscountAmountTest.java
c0967eb445dae8b3b2860cf92cf10aeb497fd24b
해당 테스트 추가하였습니다!

2023-06-25 04:28 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    }
`항상 보수적으로 가져간다`를 명심하도록 하겠습니다!
e07133b9dd1a61fd0afb82bc1a66bd4c51973fa0

2023-06-25 04:29 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +        this.expirationDate = expirationDate();
기간을 갖는 값 객체를 외부에 두고 외부에서 비교를 한다로 이해하면 될까요?

2023-06-25 04:32 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +        assertEquals(beforeDiscount - amount, fixedAmountVoucher.discount(beforeDiscount));
`LocalDate localDate = LocalDate.of(2023,6, 13)`
혹시 이 부분에서 `localDate` 변수명을 `notAvailableDate' 와 같은식으로 변경하는 것도 해결책인가요?

2023-06-25 04:42 UTC, weonest commented on src/main/java/com/programmers/console/util/Command.java
> +    private final String command;
1ad7c28cb128617d1bd161ed8b551afa38e1d682
우선 네이밍 변경하여 적용하였습니다!

2023-06-25 05:39 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +        this.expirationDate = expirationDate();
외부에서 createDate, expirationDate를 받고 내부적으로 값 객체를 사용하면 유효 기간 관련 로직이 분리될 수 있을 것 같아요

2023-06-25 06:12 UTC, seung-hun-h reviewed
건희님 리뷰 남겼습니다.

2023-06-25 06:12 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/dto/VoucherResponseDto.java
> +    }
```suggestion
    private VoucherResponseDto(PercentDiscountVoucher percentDiscountVoucher) {
        this.voucherID = percentDiscountVoucher.getVoucherId();
        this.discount = percentDiscountVoucher.getDiscount();
        this.createdDate = percentDiscountVoucher.getCreatedDate();
        this.expirationDate = percentDiscountVoucher.getExpirationDate();
        this.type = percentDiscountVoucher.getClass().getSimpleName();
    }

    private VoucherResponseDto(FixedAmountVoucher fixedAmountVoucher) {
        this.voucherID = fixedAmountVoucher.getVoucherId();
        this.discount = fixedAmountVoucher.getDiscount();
        this.createdDate = fixedAmountVoucher.getCreatedDate();
        this.expirationDate = fixedAmountVoucher.getExpirationDate();
        this.type = fixedAmountVoucher.getClass().getSimpleName();
    }

    public static VoucherResponseDto of(Voucher voucher) {
        if (voucher instanceof PercentDiscountVoucher percentDiscountVoucher) {
            return new VoucherResponseDto(percentDiscountVoucher);
        }

        if (voucher instanceof FixedAmountVoucher fixedAmountVoucher) {
            return new VoucherResponseDto(fixedAmountVoucher);
        }

        throw new IllegalStateException("Cannot instantiate. voucher=" + voucher);
    }
```

지금 상태로는 이렇게도 작성해 볼 수 있을 것 같아요.
이렇게 되면 Voucher 인터페이스의 getter는 사라지겠네요.

그리고 type을 클래스 이름으로 지정하면 클래스 이름이 변경될 때마다 type도 변경될 것 같네요

2023-06-25 06:12 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/VoucherRepository.java
> +    List<VoucherResponseDto> findAll();
영속성 레이어에서 dto를 사용했을 때 장단점을 고려해보시면 좋을 것 같네요. 잘 못 되었다는 것은 아니고 고려해 보아야 한다는 것입니다.  단적인 예로, Voucher에 필드가 추가될 때 마다 dto 필드도 함께 추가 해주어야 다른 클라이언트 코드에서도 범용적으로 사용할 수 있을 것 같아요.

그리고 findById에서는 Voucher를 반환하는 이유가 있을까요?

2023-06-25 06:12 UTC, seung-hun-h commented on src/test/java/com/programmers/voucher/uitl/CommandTest.java
> +    }
불필요한 코드는 제거해주세요

2023-06-25 06:31 UTC, dojinyou commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    private Command getRequest() {
관련 커밋 남겨주세요

2023-06-25 06:34 UTC, dojinyou commented on src/main/java/com/programmers/console/util/Command.java
> +    private final String command;
단순히 name 필드의 lowerCase가 command라면 별도로 저장하고 있어야 하는 이유가 있나요?

2023-06-25 06:52 UTC, dojinyou reviewed
파일 마지막에 개행문자 신경 써주세요!

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountAmountTest.java
> +    public void maxAndMinPercentTest(long percent) {
`@ValueSource`안에 `strings` 말고 다른 타입에 대한 값을 source로 주입해줄 수 있는 데, String으로 하는 이유가 있을까요?

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountAmountTest.java
> +    public void maxAndMinPercentTest(long percent) {
그리고 현재 테스트 케이스들이 어떤 의미를 가지고 있는 지 잘 이해가 안되는 것 같아요

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountAmountTest.java
> +}
개행 문자 추가해주세요

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountTest.java
> +        assertEquals(itemPrice - amount, discountAmount.discount(itemPrice));
테스트 코드의 가독성을 떨어지는 것 같아요!

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +        assertEquals(itemPrice - amount, fixedAmountVoucher.discount(itemPrice));
운 없게 30번째 라인이 23시 59분 59초 99에 동작하고 31번째 라인이 다음날 0시 0분 0초 0에 실행되면 테스트가 깨질 것 같은데 아닌가요?

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/PercentDiscountVoucherTest.java
> +    @CsvSource(value = {"100, 90", "50, 2", "5, 3", "126346, 100", "1235123511, 14353", "100, 99"})
expire에 대한 테스트인데 itemPrice와 amount를 다양하게 넣는 것이 어떤 의미를 가지는 지 잘 모르겠어요

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +        voucherService = new VoucherServiceImpl(voucherRepository, new VoucherFactory());
팩토리를 매번 생성할 필요가 있나요?

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    VoucherServiceImpl voucherService;
default 접근제어자로 열어준 이유가 있나요?

2023-06-25 06:52 UTC, dojinyou commented on src/test/java/com/programmers/voucher/uitl/CommandTest.java
> +    }
유효한 값들도 있는 것 같은데 모든 케이스가 다 통과되나요? 
그리고 CommandType 관련 customException을 만들었는 데 RuntimeException을 체크하는 이유가 있을까요?

2023-06-25 06:52 UTC, dojinyou reviewed
파일 마지막에 개행문자 신경 써주세요!

2023-06-25 06:54 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
>LocalDateTime 을 사용한다면 시간, 분, 초, 미리세컨드 등을 포함하게 되기 때문에 날짜에 관한 테스트를 작성할 때 구분자가 좀 더 적은 LocalDate가 편할 것이라고 생각했습니다!

테스트 코드를 위해서 엔티티 타입을 결정하는 건 의존관계가 잘못된 것 같아요!

2023-06-25 06:59 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    LocalDate getExpirationDate();
>인터페이스에서 접근자 메서드를 없애고 구현체에서만 정의하는 것도 해결 방법이 될까요 ..,?
이 부분에 대해서는 어떤 방식으로 값들을 가져와 responseDto를 만들어야 하는지 아직 잘 모르겠습니다ㅜㅜ

지금 설계대로라면 구현체에 정의하고 구현체를 식별해서 사용해야될 것 같아요!

2023-06-25 13:07 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +                CommandType command = getCommand();
반영했습니다!

2023-06-25 13:07 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
> +    private static final Scanner scanner = new Scanner(System.in);
ARROW로 변경하였습니다.

2023-06-25 13:11 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/DiscountPercent.java
> +    private static final double HUNDRED = 100.0;
`itemPrice - (itemPrice * percent / MAX_AMOUNT)` 불필요한 형변환이 없도록 이와 같이 적용하였습니다!

2023-06-26 01:59 UTC, merged