[4기] 주홍석 도메인 객체 구현 - Voucher
prgrms-be-devcourse/springboot-basic pull request #656
Opened 2023-06-22 16:27 UTC by Juhongseok

## 📌 과제 설명 
Merge 후에 온 리뷰 관련된 반영 사항입니다

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  
1. 바우처 타입 검증 로직 추가 ([feat: 타입 검증 로직 추가](https://github.com/prgrms-be-devcourse/springboot-basic/commit/e54f09e13ba7580cd5f7508b42cebcd07eaee0a6))
2. Money 생성 시 조건 처리 변경 ([feat: 남은 금액 0 미만일 경우 처리 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/b3b570178bd20c037303a3e54f7916dab4c94e81))
3. PercentDiscountVoucher.discount() 로직 수정([fix: 계산식 오류 해결](https://github.com/prgrms-be-devcourse/springboot-basic/commit/cdb69e074eafb6b13b180cb8195e4a3e0c35b966))
4. 비지니스 로직이 아니라 판단 Voucher.getId() 제거 ([feat: 불필요한 로직 제거](https://github.com/prgrms-be-devcourse/springboot-basic/commit/e106a6653f46079bff5861e6ba4fc95f4c4d8ca1))

## ✅ PR 포인트 & 궁금한 점 
리뷰어 선택해두고 Merge를 먼저해서 죄송합니다..ㅠ😭😭
확인을 했어야 했는데 실수한 것 같습니다

2023-06-23 13:06 UTC, ICCHOI requested changes
홍석님 수고하셨습니다!
중복되는 리뷰는 하나만 코멘트 했어요!
전체적으로 중첩된 추상 클래스를 사용하고 있어 코드를 한 눈에 파악하기가 어려워요.
또한 상위 클래스의 변경으로 해당 클래스를 상속 받아 사용하는 클래스에 강한 영향을 끼칠 수 있어 보여요!
추상 클래스는 반복되는 코드를 줄일 수 있다는 장점이 있지만, 클래스 간의 결합도를 높이고, 응집도를 낮추는 단점이 있다고 생각해요. 
상속이 아니어도 다형성의 장점을 살릴 수 있는 방법들이 많으니 한 번 고민해보셔도 좋을 것 같아요.

2023-06-23 13:06 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/FixedAmountVoucher.java
> +        return originPrice.amount() - amount.getAmount();
```suggestion
        return originPrice.amount() - this.amount;
```
이래도 괜찮을 것 같아요.

2023-06-23 13:06 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +    }
discountVoucher()가 public인 이유가 궁금해요!

2023-06-23 14:48 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/VoucherAmount.java
> +    }
setAmount라고 네이밍을 지은 이유는 내부에서만 사용하도록 private으로 막아놨으니 괜찮다고 생각을 했는데 차라리 `retrieveValidatedAmount`로 해도 의도가 들어날 수도 있겠네요

2023-06-23 14:50 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +    }
기존에 `discountVoucher`만 만들어 뒀다가 `of`를 만들면서 변경을 하지 못했네요..

2023-06-23 14:52 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/FixedAmountVoucher.java
> +        return originPrice.amount() - amount.getAmount();
this.amount가 amount를 가진 VoucherAmount객체이기 때문에 값을 받아와야돼요
차라리 변수로 추출해서 의미를 보여줘야 겠네요

2023-06-23 15:00 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +        };
null일 경우는 없어요
사용자에게 String 값으로 받아오면 VoucherType에서 찾아올 때 일치하지 않는 type명을 보내면 에러를 반환 할 예정입니다 아직 구현이 안되있었네요

2023-06-23 15:01 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/FixedAmount.java
> +    }
정한다는걸 깜빡했네요🤣

2023-06-23 15:06 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    protected final VoucherAmount amount;
음.. voucherAmount가 없는게 있을까요?? 만약 사용자 입력이 없다면 생성 시 0을 지정해주면 될 거같아요

2023-06-23 18:21 UTC, devcourse-ray requested changes

2023-06-23 18:21 UTC, devcourse-ray commented on src/main/java/org/devcourse/voucher/domain/voucher/Money.java
> +        throw new RuntimeException("금액이 0 미만일 수 없습니다");
요기는 이렇게 순서를 정한 기준은 어떻게 잡으셨나요??

2023-06-23 18:21 UTC, devcourse-ray commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/VoucherAmount.java
> +        this.amount = setAmount(amount);
보통 setter 안에서 `this.amount = amount` 와 같은 액션이 일어나기 때문에 다시 정리를 해주면 좋겠네요
메소드 분리를 하면서 더 복잡해지는건 아닌지도 고민 해봐야해요

2023-06-23 18:21 UTC, devcourse-ray commented on src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
> +        return Money.of(amount);
Money 라는 타입을 정의했는데 amount가 밖에서 돌아다닐 필요가 있을까요?

2023-06-23 18:21 UTC, devcourse-ray commented on src/main/java/org/devcourse/voucher/domain/voucher/PercentDiscountVoucher.java
> +        return originPrice.amount() * (100 - percent) / 100;
discount는 할인이라는 의미로 쓰셨을 것 같아요
위 리뷰 내용과도 연결되는 부분이지만 할인은 보통 돈(Money)에 쓰이는 단어인데 Money를 정의했는데도 int 가 돌아다니는건 오히려 복잡해지지 않을까 해요

2023-06-23 23:36 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/PercentDiscountVoucher.java
> +        return originPrice.amount() * (100 - percent) / 100;
객체 내부에서 계산이 되도록 변경을 해야겠군요

2023-06-23 23:38 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/Money.java
> +        throw new RuntimeException("금액이 0 미만일 수 없습니다");
습관적으로 true인 부분을 먼저 쓰게 되는 데, return 문이 밖으로 하는게 의도가 좀 더 확실하게 보이겠네요

2023-06-23 23:39 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/VoucherAmount.java
> +        this.amount = setAmount(amount);
차라리 검증 로직만 따로 분리를 할까도 고민중이에요

2023-06-24 06:01 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    protected final VoucherAmount amount;
1 + 1 처럼, 재화를 하나 더 주는 바우처도 있을 수 있겠네요.
바우처라는 개념이 굉장히 큰 범위에서 사용 될 수 있어서 할인에만 초점을 맞추는 건 확장성을 떨어뜨릴 수 있다고 생각이 들어요.

2023-06-24 06:16 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +        };
그렇군요? 그렇다면 VoucherFactory는 VoucherType의 검증에 강하게 의존하게 되겠네요!
어떻게 생각하시나요??

2023-06-25 09:55 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/VoucherAmount.java
> +    }
setAmount를 없애고 생성자에서 할당전에 validation을 진행하는 방식으로 변경했어요
나중에 검증 로직이 추가가 된다하더라도 해당 메소드만 변경하면 되기도하고 여러 조건들을 묶어서 사용도 가능할 것 같아요

2023-06-25 09:59 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    protected final VoucherAmount amount;
그래서 할인을 해주는 바우처(DiscountVoucher) 상위로 Voucher라는 객체를 만들어 뒀어요 만약 1+1 혹은 포인트를 제공하는 바우처처럼 다른 방식을 가진 것들이 생겨난다면 PointVoucher, PlusOneMoreVoucher와 같이 하위로 확장을 시키고 VoucherAmount에는 남은 포인트, 혹은 추가로 제공이 가능한 수량과 같은 것들을 저장해두면 될거라고 생각을 했어요 

지금 당장은 DisountVoucher에 `discount()`메소드가 있지만 다른 것들에 `decreasePoint()`, `추가 상품 제공()`과 같은 메소드를 생성하고 그에 맞게 VoucherAmount를 상속받은 객체들을 생성한다면 괜찮지 않을까요???

2023-06-25 10:54 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +        };
아 그러겠네요 VoucherFactory에서는 무조건적으로 VoucherType의 검증이 성공이 되야한다는 조건이 있으니까요 
두가지 방법을 생각해 봤는데
1. VoucherType.find를 통해 일치하는 값이 없을 경우 null을 반환한다
2. VoucherType.find에서 Optional로 감싸서 전달한다

2번 방법에 대해서는 Optional을 인자로 전달하지 말라는 글을 본 적이 있어요 파라미터의 값이 null, value가 null인 Optional, value가 null이 아닌 Optional 3가지로 전달되어 오히려 더 복잡해질 수 있기 때문이에요
그러면 결국 VoucherType에서 찾고 VoucherFactory로 넘기기 전에 Optional을 확인하는 과정이 있어야 한다는 것인데 그럼 현재 로직과 차이가 없다고 생각이 들어요

그럼 1번 방법을 사용을 해야한다는 것인데 null을 반환하게 되면 나중에 해당 메소드를 사용하는 모든 곳에서 null체크를 해줘야 한다는 단점이 있어요
아니면 null을 위한 VoucherType객체를 할당을 해두는 방식은 어떨까요?

2023-06-25 10:55 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    protected final VoucherAmount amount;
수량(quantity)과 포인트(point)는 amount와는 다르다고 생각하는데, 구조로 인해서 필드명이 제한 될 수도 있겠다는 생각이 들어요. 
하지만 아래의 바우처 마다 맞는 메소드를 생성하고, 상속받는 객체를 생성하는 건 괜찮게 보여요!

2023-06-25 10:56 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/PercentDiscountVoucher.java
> +        return originPrice.amount() * (100 - percent) / 100;
Money 객체 내부에서 계산을 하고 Money객체를 반환해주도록 했어요

추가적으로 이렇게 진행을 하니 위 리뷰에서 있었던 `postProcessMoney` 메소드가 제거 되고 amount를 처리하는 과정을 제거했어요

2023-06-25 11:13 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    protected final VoucherAmount amount;
음.. DiscountVoucher쪽으로 amount를 내리고 다른 타입의 바우처가 확장이 된다면 그에 맞는 필드를 제공을 해주는 것이 좋겠네요
그러면 각 목적에 맞는 필드명도 제공을 해줄 수 있겠어요

2023-06-26 01:18 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +        };
말씀하신 내용들 때문에, 다른 방법을 사용하는 편이 좋다고 생각이 들어요.
VoucherType에서 수행하는 검증 외로, VoucherFactory에서도 검증에 관한 책임을 가지는 건 어떠신가요?

2023-06-26 01:52 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +        };
switch문에 default 란을 추가해서 현재 지원하지 않는 타입에 대해서는 에러를 발생시킬 생각이에요
switch문 밖에서 추가로 null값도 확인을 해야겠네요

2023-06-26 07:51 UTC, ICCHOI reviewed
홍석님 안녕하세용!
또 코멘트 남겼습니다.. 추가로 궁금한 점이 있는데요

VoucherAmount와 DiscountVoucher를 분리함으로써 얻을 수 있는 장점이 무엇이 있나요?

2023-06-26 07:51 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
> +                .orElse(NO_TYPE);
NO_TYPE을 반환함으로써 얻을 수 있는 장점이 무엇이 있을까요?

2023-06-26 07:51 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
>      }
현재 Voucher Class에서는 amount를 사용하지 않고 있는데, 
모든 Voucher 클래스의 생성을 담당하는 Factory에서 amount를 필수 입력값으로 받아야 하는 걸까요?

2023-06-26 07:51 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/FixedAmount.java
> +        return 0 > amount || amount > 100_000;
이건 제 취향일수도 있는데 보통 상수와 변수를 비교할때는 변수를 왼쪽에 두는 것 같아요.
```suggestion
        return amount < 0 || amount > 100_000;
```

2023-06-26 07:51 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/Money.java
>      }
음수가 입력값으로 들어오게 되면 어떻게 되나요?

2023-06-26 07:51 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/VoucherAmount.java
>          };
코드 전체적으로 비슷한 switch 문이 너무 많이 반복된다고 생각이 들어요.

2023-06-26 08:03 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/VoucherAmount.java
>          };
> VoucherAmount와 DiscountVoucher를 분리함으로써 얻을 수 있는 장점이 무엇이 있나요?

이 질문과 같이 답을 하자면 너무 과하게 분리한 것 같습니다..
지금 다시 보니 amount 검증 하는 것만 있고 추가적으로 필요한 이유를 알지 못하겠네요

차라리 제거하고 int값으로 넘기는 것이 괜찮아 보이네요

2023-06-26 08:04 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/amount/VoucherAmount.java
>          };
넵 결국 (Percent, Fixed) VoucherAmount는 validation만 수행하고 있고,
 각각의 Voucher와 강하게 결합되어 있다는 걸 생각해본다면, 다른 클래스로 분리하는 건 오히려 응집도를 떨어뜨리는 행위라고 생각이 들어요.

2023-06-26 08:13 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
>      }
Voucher타입을 반환 하는 것이 아니라 DiscountVoucher 타입을 반환하도록 변경하면 인자 값을 그대로 사용할 수 있겠어요
메소드 네이밍도 discountVoucher로 만들고요

그러면 정적 팩토리 메소드의 장점인 메소드에 이름을 가지게한다 라는 것도 사용이 가능하겠네요

2023-06-26 08:34 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherFactory.java
> +            case FIX -> new DiscountVoucher(id, type, amount, originPrice -> originPrice.minus(Money.of(amount)));
Factory 클래스에 DiscountPolicy의 핵심 로직이 있는 건 조금 어색하게 느껴져요.

2023-06-26 08:35 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
> +                .orElse(NO_TYPE);
VoucherType에 잘못된 값이 들어오는 근본적인 이유가 뭘까용?

2023-06-26 08:38 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
> +                .orElse(NO_TYPE);
사용자가 잘못된 값을 넘겨주어서??..

아 굳이 NO_TYPE으로 넘겨서 뒤에서 처리를 할 필요없이 에러 던지면 되겠네요
입력 값이 있는지 판단은 VoucherType이 하는거니까요

2023-06-26 17:41 UTC, ICCHOI requested changes
뭔가 더 복잡해지는 것 같기도 한데요 😢

2023-06-26 17:41 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
>      }
DiscountPolicy의 로직이 selectPolicy()에 모두 드러나 있어서, 굳이 다른 클래스로 분리 해야할까? 생각이 들어요

2023-06-26 17:41 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
> +    }
validateAmount 내의 switch에서 여러 로직을 동시에 검증하고 있어서, 어디서 오류가 발생했는지 파악하기 어려워 보여요.

2023-06-26 23:42 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    public abstract int getProvidedAmount();
두개의 방법을 먼저 생각중에 있었는데
1. 상위 Voucher에 Amount 필드를 올려서 getter를 사용한다
2. 하위 구체 Voucher에 getter를 사용한다

1번 방식처럼 하게 되면 문제가 없긴 하지만 만일 다른 타입의 바우처(1+1, 포인트 등)가 생길 경우 amount라는 의미가 적합하지 않고 동작하게 될 방식 또한 다르다고 생각되어 구체 클래스에 유지하도록 했어요

2번 방식을 사용하게 된다면 Repo에 저장을 하는 것이나 사용자에게 결과 값을 반환을 하는 것을 Voucher타입으로 넘겨지게 되는데 amount는 제공을 해 줄 수 있는 값이라고 판단을 하였고 getter를 사용하기 위해서는 instancof, 다운캐스팅을 사용하게 될 텐데 이러면 다형성을 위반하는 행위라고 생각해서 공통으로 가질 수 있는 추상 메소드를 선언했어요

그럼 아예 Voucher하나만 가지면 안되나도 생각을 해봤는데 이는 1번에 관련된 답에서 `amount라는 의미가 적합하지 않고`와 비슷한 이유로 적용하지 않았어요

2023-06-26 23:57 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
>      }
람다를 사용해서 코드 작성을 좀 줄이고자 사용한 것인데 이러면 그냥 Function 함수형 인터페이스를 사용해도 되겠네요

2023-06-27 03:47 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
> +    }
amount를 검증하는 것도 결국 discountPolicy 의 역할이라고 생각이 드는데요(정책이 생성될 때 어느 정도 할인을 해줄지 결정을 하니까요) 그러면 생성 시점에서 policy에서 검증을 먼저 진행하고 바우처를 생성을 하는 것은 어떤가요??

이 방법의 장점은 각 특화된 정책에서 관리를 할 수 있어 응집도가 있다고 생각하지만 단점으로는 생성자에서 정책을 먼저  선택을 해주어야 한다는 강제성이 있어서 단점이라고 생각해요

2023-06-27 13:23 UTC, ICCHOI reviewed
수고하셨습니다. 코멘트 확인해주세요

2023-06-27 13:23 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/policy/Policy.java
> +            case FIX -> new PercentDiscountPolicy(providedAmount);
거꾸로 되어 있는데요?

2023-06-27 13:23 UTC, ICCHOI commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +        validateType(type);
validateType()을 두 번 검증하고 있네요.

2023-06-27 13:28 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/policy/Policy.java
> +            case FIX -> new PercentDiscountPolicy(providedAmount);
변경 완료했습니다

2023-06-27 13:29 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +        validateType(type);
제거했어요😊

2023-06-27 13:29 UTC, ICCHOI approved these changes

2023-06-27 14:26 UTC, devcourse-ray commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    private final Policy policy;
1:1 매칭이 되지 않는 경우 버그

2023-06-27 16:20 UTC, Juhongseok commented on src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
> +    private final Policy policy;
- VoucherType(Enum)을 통해서 Policy 생성 ([feat: policy - voucherType 관계 기반 생성 기능 변경](https://github.com/prgrms-be-devcourse/springboot-basic/pull/656/commits/ae687b0d18a6bcfb0695e7bb19cd3a9c6b94a6be))

2023-06-27 16:34 UTC, devcourse-ray approved these changes
🌵 
오늘 이야기한 구조 외에도 다른 방법도 또 계속 고민해보세요.
그리고 지금 구조가 과연 다른 곳에 부적절한 영향을 끼치지는 않을지도 의심해보는 것도 중요합니다.

2023-06-27 16:38 UTC, merged