[4기 - 유명한] 기능 단위 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #657
Opened 2023-06-22 16:54 UTC by yumyeonghan

## 📌 과제 설명
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/75025163/dc9f8893-925d-4ea3-bf49-60bae1b91e6d)

**프로젝트 클래스 다이어그램입니다.**

## 👩‍💻 요구 사항과 구현 내용
#### 우선 미션에 대한 팀 미팅 전에 이미 2번에 해당하는 미션을 수행하고 있어서 해당 요구 사항까지 구현하고 PR을 보내는 점 양해 부탁 드립니다.
1. 바우처 설계 및 바우처 개발(~6/22)
2. 바우처 생성 로직 및 조회 로직(~6/23)

- [x]  바우처 설계 및 개발
  - 바우처는 FixedAmountVoucher, PercentDiscountVoucher로 구성된다.
- [x] 바우처 생성 및 조회 로직 개발
  - 바우처를 생성하고 저장할 수 있다.
  - 만들어진 바우처를 조회할 수 있다.
  - 이러한 바우처 정보를 메모리에 관리한다.
 
## ✅ PR 포인트 & 궁금한 점
1. 제가 다음과 같이 프로젝트의 패키지 구조를 설계하고자 하는데, 적합한지 궁금합니다.
- controller: VoucherController를 두어 사용자의 요청을 처리 한 후 결과를 출력 객체에 넘겨주는 역할을 합니다.
- domain: 다양한 Voucher 엔티티들이 들어있습니다. 
- enums: 바우처에서 사용할 enum 타입들이 정의되어있습니다.
- exception: 애플리케이션에서 발생할 수 있는 예외를 관리하는 클래스들이 정의되어있습니다.
- io: 입,출력에 대한 클래스들이 정의되어있습니다.
- repository: 데이터를 저장하고 불러오는 로직을 담당하는 클래스들이 정의되어있습니다.
- request: 바우처 생성 요청과 같은 dto 개념으로 사용하고 있습니다.
- service: repository를 이용해 비즈니스 로직을 담당하는 역할을 합니다.

2. 제가 작성한 테스트 코드에 대한 피드백을 듣고 싶습니다.

2023-06-23 00:43 UTC, seung-hun-h requested changes
테스트 코드를 잘 작성해주셨습니다.
하지만 실제로 할인을 수행하는 바우처에 대한 테스트가 부족한 것 같아요.

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    }
`VoucherCreationRequest`는 컨트롤러에서 부터 여기까지 의존성이 전달되고 있네요. 도메인 객체에서는 의존성을 끊어주는 것이 좋아보여요

voucherId, amount에 대한 검증 로직도 추가해주는 것이 좋아보이네요. null, 음수, 최대값에 대한 검증이요

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    PERCENT("percent", (a, b) -> new PercentDiscountVoucher(a, b));
말고 의미있는 이름을 지어주세요.
람다로 작성하셨는데 메서드 참조 형식으로도 변경될 수 있긴 합니다.
http://www.tcpschool.com/java/java_lambda_reference

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    private final BiFunction<UUID, VoucherCreationRequest, Voucher> biFunction;
이것도 의미있는 이름을 지어주세요

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/exception/VoucherException.java
커스텀 예외 클래스를 작성하신 이유가 있을까요?
그리고 예외 이름이 범용적인 것 같습니다. 좀 더 구체적인 이름을 지어줄 필요가 있을 것 같아요

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    private static final Map<UUID, Voucher> store = new ConcurrentHashMap<>();
상수로 사용하시면 상수 네이밍 규칙을 지켜주세요.

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    }
👍

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    }
테스트용으로 작성하신 것 같은데요.
`MemoryVoucherRepository`가 테스트용 클래스가 아니라면 조금 위험한 메서드이긴 합니다.

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/request/VoucherCreationRequest.java
> +    private long amount;
변경되지 않는다면  final을 사용해주세요

2023-06-23 00:43 UTC, seung-hun-h commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +    Voucher voucher;
외부에서 사용할 것이 아니라면 접근 제어자를 추가해주세요

2023-06-23 00:43 UTC, seung-hun-h commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
예외 상황에 대한 테스트도 필요해보이네요

2023-06-23 00:43 UTC, seung-hun-h commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    }
검증 로직이 없어서 추가해줄 필요가 있을 것 같습니다.

2023-06-23 00:43 UTC, seung-hun-h commented on .idea/.gitignore
.idea 폴더도 .gitignore에 추가해주세요

2023-06-23 00:43 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
enum들을 한 곳에 모아두는 것은 좋지 않아보이네요.
console의 영역이라면 console 패키지에, domain의 영역이라면 domain에 있는 것이 좋을 것 같아요.

2023-06-23 03:02 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    }
- 도메인 객체(FixedAmountVoucher, PercentDiscountVoucher)에서 VoucherCreationRequest 의존성을 끊기
- voucherId, amount에 대한 검증 로직도 추가
  - null, 음수는 VoucherCreationRequest에서 검증
  - 최대값은 VoucherType에서 검증

## 위에서부터 차례로 반영할때마다 커멘트 바로 달겠습니다!

2023-06-23 13:25 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    PERCENT("percent", (a, b) -> new PercentDiscountVoucher(a, b));
좀더 이름을 구체적으로 지었고, 람다식도 메서드 참조 형식으로 변경했습니다!
7d4093367cb7f23f107f1eccb6b2dcd91c3d65a0

2023-06-23 13:33 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    private final BiFunction<UUID, VoucherCreationRequest, Voucher> biFunction;
반영했습니다.!
1c59ccf1512ae49d5fe6d587d82c6cc171005267ㅇㅁ

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +    }
매직 넘버!

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +}
다양한 형태로 Voucher를 구성할 수 있었을 것 같은데 인터페이스를 이용해서 하신 이유가 뭘까요?

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    }
불필요한 메서드인 것 같아요. type이 단순히 Enum의 name을 lowerCase로 구성할 거라면 `valueOf` 메서드를 활용하는 게 좋을 것 같아요!

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    }
VoucherType이 단순히 타입 뿐만 아니라 Factory 역할도 하는 것 같은데 어떻게 생각하시나요?

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    }
VoucherType이 validator 역할도 하고 있는 것 같아요.
Voucher들의 구현체들은 max / min amount 값을 몰라도 될까요?

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/exception/VoucherErrorCode.java
> +    EXCEED_MAXIMUM_DISCOUNT_AMOUNT("바우처의 최대 할인 양을 초과하였습니다.");
에러 코드를 별도로 관리하는 건 좋은 것 같아요!

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/exception/VoucherErrorCode.java
> +    EXCEED_MAXIMUM_DISCOUNT_AMOUNT("바우처의 최대 할인 양을 초과하였습니다.");
[nit]

```suggestion
public enum VoucherErrorCode {
    NOT_SUPPORTED_TYPE("지원하지 않는 바우처 타입입니다."),
    INVALID_VOUCHER_CREATION_REQUEST("올바르지 않은 바우처 생성 요청입니다."),
    EXCEED_MAXIMUM_DISCOUNT_AMOUNT("바우처의 최대 할인 양을 초과하였습니다.");
```

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +import java.util.concurrent.ConcurrentHashMap;
import 할 때 * 는 지양해주세요!
그리고 만약 쓴다고하면 concurrentHashMap은 *이랑 같이 있을 필요는 없을 것 같아요!

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/request/VoucherCreationRequest.java
> +public class VoucherCreationRequest {
dto 객체 같은 데 record type을 쓰지 않은 이유가 있을까요?

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +public class VoucherService {
repository와 다르게 interface를 쓰지 않은 이유가 있나요?

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
void로 반환하는 이유가 있나요?

2023-06-23 13:37 UTC, dojinyou commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
Voucher라는 도메인 객체 반환하면 컨트롤러에서도 로직이 실행되거나 도메인 객체의 변경이 발생할 수 있을 것 같은데 어떻게 생각하시나요?

2023-06-23 13:37 UTC, dojinyou commented on src/test/java/com/programmers/voucher/VoucherApplicationTests.java
> +}
어떤 걸 테스트 하는 테스트일까요?

2023-06-23 13:37 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +}
마지막 개행 라인 추가해주세요!

2023-06-23 13:37 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +    void 초기화() {
여기만 한글 메서드명을 쓴 이유가 있나요?

2023-06-23 13:37 UTC, dojinyou commented on src/test/java/com/programmers/voucher/repository/MemoryVoucherRepositoryTest.java
> +        voucherRepository.save(voucher2);
given에 속하는 것 같아요.

2023-06-23 13:37 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    }
@BeforeAll과 @BeforeEach의 차이를 알아보시면 좋을 것 같아요!
그리고 필요하다면 TestClass의 LifeCycle에 대해서도 알아보시면 조항요!

2023-06-23 14:22 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/exception/VoucherException.java
바우처 애플리케이션에서 발생할 수 있는 예외 상황(필요한 메세지)들을 한곳에서 관리를 할 수 있어서 편리하다고 판단이 되어 VoucherErrorCode를 생성했고, 

이를 활용한 RuntimeException을 상속받은 VoucherException을 두어 
예외 발생 시 예외 처리를 용이하게 하기위해서 작성했습니다!!

다시 생각해보니깐 에러 메세지만 사용하는 상황이라면 굳이 커스텀 예외보단 자바의 표준 예외를 사용하는 것이 가독성이 더 좋을 것이라 판단이 되어 수정했습니다.
8b7d6c73c208d654adf87dd0652f71ef63280a9c

2023-06-23 14:24 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    private static final Map<UUID, Voucher> store = new ConcurrentHashMap<>();
적용했습니다!
d7ca48999ec87290dd6ffc16925e14d0f8bb9d55

2023-06-23 14:37 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +    Voucher voucher;
테스트 코드라 신경 안쓰고 작성했던것 같습니다! 앞으로 신경쓰겠습니다.
4d1f1585de5b5a09f88767df8ae3b05d290f3e9c

2023-06-23 14:44 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/request/VoucherCreationRequest.java
> +    private long amount;
반영 했습니다!
dfcec95f5d497483870b94ebd47c61c4d57cca8a

2023-06-23 14:51 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    }
넵! 검증 기능 추가하면서 같이 테스트 코드도 작성했습니다.
fad6890681e0ce1560a9a574732c3163035b30d3

2023-06-23 14:57 UTC, yumyeonghan commented on .idea/.gitignore
넵 추가했습니다!

2023-06-23 14:59 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
기존 enums 패키지에 있던 VoucherType을 관련있는 domain 패키지로 옮겼습니다.

2023-06-23 15:00 UTC, yumyeonghan commented on .idea/.gitignore
넵 ignore에 추가해서 반영했씁니다!

2023-06-23 15:03 UTC, yumyeonghan commented on build.gradle
> +	annotationProcessor 'org.projectlombok:lombok'
아.. 처음 스프링부트 프로젝트 생성할 때 생각없이 롬복을 추가했던거 같습니다. 바로 지우겠습니다!

2023-06-23 23:57 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/VoucherApplicationTests.java
> +}
스프링 프로젝트를 만들 때 기본으로 생성되었던거 같습니다!
삭제하겠습니다.

2023-06-23 23:58 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +    void 초기화() {
영어로 표현하면 가독성이 떨어질 부분들은 한글과 병해해서 표기했습니다.
혹시 영어나 혹은 한글로 통일해야할까요?

2023-06-24 00:00 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/repository/MemoryVoucherRepositoryTest.java
> +        voucherRepository.save(voucher2);
넵!! 다시 구분 해놓겠습니다.

2023-06-24 00:16 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +import java.util.concurrent.ConcurrentHashMap;
넵! 반영하겠습니다.

2023-06-24 00:20 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +public class VoucherService {
repository는 추후에 JdbcVoucherRepository 설계를 하기 위해서 인터페이스를 사용했는데, VoucherService는 해당 비즈니스 로직이 새롭게 정의되어야 하는 상황이 없을거라 판단이 되어서 인터페이스를 사용하지 않았습니다!

2023-06-24 00:26 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    }
넵 차이점을 알아보고 적절하게 사용하겠습니다!

2023-06-24 00:40 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +}
넵 마지막 개행 라인 추가했습니다!

2023-06-24 01:12 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +    }
필드 이름을 좀 더 가독성 있게 수정하고, discount() 로직에 괄호를 사용해서 명확하게 기능을 나타냈습니다! 
181198ad3c685ac75c0635e44604a48b79e33216

2023-06-24 01:45 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +}
처음에는 Voucher을 단순히 공통된 기능을 갖은 추상화 객체라고 생각이 돼서 인터페이스를 이용했습니다.

다시 생각해보니 uuid 나 discountAmount 등 단순 기능만이 아닌 상태들도  갖을 수 있기때문에 abstract class를 이용하는게 좀 더 적합하다고 생각이 돼서 다시 작성합니다! 
ed37a4f19f23aacc32b903d38984936013047d01

2023-06-24 02:50 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    }
VoucherType에 너무 많은 역할이 주어진거 같아 VoucherFactory를 domian 영역에 생성했습니다!

b69b1f9a88733a0db46478ab464117d0ea812e37

2023-06-24 02:51 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    }
불필요한 메서드를 없애고 Enum의 valueOf 메서드를 활용해서 구분했습니다.!
b69b1f9a88733a0db46478ab464117d0ea812e37

2023-06-24 04:06 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/enums/VoucherType.java
> +    }
마찬가지로 VoucherType에서 validator 역할을 지우고, 

Voucher 구현체 생성에 대한 유효성 검사는 생성 시점 이전에 이루어져야 한다고 생각이 되어서, 구현체에 유효성 검사 로직을 구현했습니다.
dce9db57fd03d2c834fc70a55799eb266e0022b4

2023-06-24 06:10 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/request/VoucherCreationRequest.java
> +public class VoucherCreationRequest {
record type 사용이 습관화 되지 않아서 생각을 못했던것 같습니다.

record type으로 바꾸니깐 getter()를 사용하지 않아도 되고, 기존 필드들이 불변성을 갖게 되어 코드가 좀 더 깔끔해졌습니다. record type을 잘 활용해보겠습니다.

0dadaf1bed3b23759e45f83ce40e3f07ca75951b

2023-06-24 06:21 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
처음에 바우처 생성 메서드는 바우처 생성만 하면 될줄 알았습니다.
다시 생각해보니 사용자가 만약 생성된 바우처 정보를 알고 싶거나 하는 요구사항이 생기면, 이를 확인할 수 있는 방법이 없기 때문에 

UUID 를 반환해서 이를 활용하게끔 수정했습니다!
fb47a55269fa92f3c9abd6f5d2bc4236c70ab277

2023-06-24 06:35 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    }
저도 그럴수 있다고 생각이 됩니다.
그래서 해당 로직에서 도메인 객체 반환이 아닌, VoucherInfoResponse(dto) 반환을 해주도록 수정했습니다!
81de61de83c56bce8a1a2d96bb0dafebf6336cff

2023-06-25 07:05 UTC, yumyeonghan commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
테스트 케이스 추가해주었습니다!
6e233f2dbe656085402147a45c6633f516157fab

2023-06-25 07:10 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +    }
중요한 매직넘버에 대한 수정이 없는 것 같아요

2023-06-25 07:15 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/VoucherFactory.java
> +        VoucherType voucherType = VoucherType.valueOf(voucherCreationRequest.voucherType());
[nit]
```suggestion
        String requestVoucherType = voucherCreationRequest.voucherType().toUpperCase();
        VoucherType voucherType = VoucherType.valueOf(requestVoucherType);
```
가독성 + 디버깅할 때 값 체크? + UpperCase 처리해주기?(valueOf는 caseSensitive!)

2023-06-25 07:15 UTC, dojinyou commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +import java.util.concurrent.ConcurrentHashMap;
반영이 안된 것 같아요! 확인 부탁 드립니다!

2023-06-25 07:15 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +    }
아.. 정신없이 수정하다가 놓친것 같습니다.
100이란 숫자를 MAX_PERCENT 같이 상수를 사용해서 의도를 나타내겠습니다.

2023-06-25 07:16 UTC, dojinyou commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +public class VoucherService {
컨트롤러쪽 테스트를 위해 테스트용 Service로 격리 해야 할 때는 어떻게 대응할 수 있을까요?

2023-06-25 07:18 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +import java.util.concurrent.ConcurrentHashMap;
확인하고 바로 반영하겠습니다!

2023-06-25 07:19 UTC, dojinyou commented on src/main/java/com/programmers/voucher/dto/request/VoucherCreationRequest.java
> +}
개행 체크해주세요!

2023-06-25 07:19 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +    void 초기화() {
메서드명은 가능하면 통일하는 게 좋다고 생각해요!

2023-06-25 07:43 UTC, yumyeonghan commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +public class VoucherService {
음.. 테스트용 service는 생각을 못했습니다.
추후 발생할 여러 상황들에 대비해서 service 도 인터페이스를 사용하는게 좋을것 같습니다!

다음 기능 구현할때 반영해서 작성하겠습니다.

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/AppConfiguration.java
> +}
`@Componet`를 상속한 `Anotation`을 활용하지 않고 `Configuration`에서 메서드로 `Bean` 객체를 정의하는 이유가 무엇일까요?

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    private final UUID voucherId;
id값이 null이 아닌 지 체크해주는 로직이 없는 것 같아요!

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/VoucherFactory.java
> +        };
👍

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/dto/request/VoucherCreationRequest.java
> +        if (Objects.isNull(voucherType) || discountAmount == 0) {
매직넘버!

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    private static final Map<UUID, Voucher> STORE = new ConcurrentHashMap<>();
👍

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        return Optional.of(STORE.get(voucherId));
STORE.get(voucherId)의 결과가 null일 경우 어떻게 될까요?

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +                .map(voucher -> new VoucherInfoResponse(voucher.getVoucherId(), voucher.getDiscountAmount()))
정적 팩토리 메서드로 개선할 수 있을 것 같은데 어떻게 생각하시나요?

2023-06-25 07:49 UTC, dojinyou commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +                .toList();
👍

2023-06-25 07:49 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
> +    }
[nit]
```suggestion
    void discount(long voucherAmount, long originalPrice, long expectedPrice) {
        Voucher voucher = FixedAmountVoucher.of(UUID.randomUUID(), voucherAmount);

        long discountedPrice = voucher.discount(originalPrice);

        assertThat(discountedPrice).isEqualTo(expectedPrice);
    }
```

2023-06-25 07:49 UTC, dojinyou commented on src/test/java/com/programmers/voucher/repository/MemoryVoucherRepositoryTest.java
> +        voucherRepository = new MemoryVoucherRepository();
clear만 하면 어떤 문제가 있나요?

2023-06-25 07:49 UTC, dojinyou commented on src/test/java/com/programmers/voucher/repository/MemoryVoucherRepositoryTest.java
> +        Assertions.assertThat(voucherList.size()).isEqualTo(2);
매직넘버!

2023-06-25 07:49 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    }
검증 로직이 빠진 것 같아요!

2023-06-25 07:49 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    @NullSource
```suggestion
    @NullAndEmptySource
```

2023-06-25 07:49 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +    }
[super nit]
```suggestion
    @EnumSource(VoucherType.class)
    void input0VoucherDiscountAmount(VoucherType voucherType) {
        final long discountAmount = 0;
        String requestVoucherType = voucherType.name()
        Assertions.assertThatThrownBy(() -> new VoucherCreationRequest(requestVoucherType , discountAmount))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("바우처 타입과 할인양을 입력해주세요.");
    }
```
EnumSource도 알려드리기 위한 코드!

2023-06-25 07:49 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +        Assertions.assertThat(voucherList.size()).isEqualTo(2);
매직 버

2023-06-25 13:08 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    public Voucher(UUID voucherId, long discountAmount) {
```suggestion
    protected Voucher(UUID voucherId, long discountAmount) {
```

2023-06-25 13:08 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    }
이렇게 되면 구현 클래스가 정액 할인 바우처이면 할인 금액이 반환되고, 정률 할인 바우처이면 퍼센테이지가 반환이 될 텐데 조금 이상하게 느껴지네요.

```java
Voucher voucher1 = PercentDiscountVoucher.of(id, 10);
Voucher voucher2 = FixedDiscountVoucher.of(id, 1000);
```

그렇다면 결국엔 클라이언트에서는 `Voucher`가 어떤 타입인지 실질적으로 아는 상황에서 사용해야할 것 같은데요. 그렇다면 `Voucher`로 추상화하는 이유도 애매해지겠네요. `Voucher`를 다시 설계할 필요가 있을 것 같아요.

2023-06-25 13:08 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    }
이 메서드는 왜 static 이죠?

2023-06-25 13:08 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +            throw new IllegalArgumentException("1 ~ 100 범위의 바우처 할인양을 입력해주세요");
실제로 어떤 값이 들어왔는지도 알려주면 좋을 것 같네요. 예외 메시지에 들어가는 범위 값도 만들어 놓은 상수를 이용하면 범위가 변경됐을 때 예외 메시지의 범위도 같이 변경되어 좋을 것 같아요.

2023-06-25 13:32 UTC, merged