[4기 - 나영경] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #659
Opened 2023-06-22 17:50 UTC by na-yk

## 📌 과제 설명 
- [ ] Voucher 설계 / Voucher 개발
## 👩‍💻 요구 사항과 구현 내용 
#### Voucher 설계
![voucher전체](https://github.com/prgrms-be-devcourse/springboot-basic/assets/102007066/d04dbba2-332c-41bd-acd1-6489b93fb5fa)

## ✅ PR 포인트 & 궁금한 점 
- Java Spring 프로젝트 구조가 아직 완전히 이해가 되지 않아서, Main을 따로 두어도 되는지 궁금합니다.
- 현재 상태처럼 클래스만 구현한 경우에 일반적으로 테스트코드가 어떤 것을 테스트해야 하는지 궁금합니다. 

부족한 점이 많아서 계속 고민해보겠습니다!

2023-06-23 06:47 UTC, seung-hun-h requested changes
제가 변경된 코드를 제시하긴 했지만, 사용자의 입력을 받고 처리하는 로직이 Main 클래스에서 진행될 것 같은데요. 그렇다면 의존성 방향이 Main -> VoucherService가 될 것 같습니다. 그리고 VoucherService는 VoucherRepository와 Voucher를 직간접적으로 참조하게 될 것 같은데요, 이 경우에는 VoucherService -> VoucherRepository, VoucherService -> Voucher 처럼 다이어그램이 변경되어야 할 것 같네요.

테스트는 보통 클래스라기 보다는 클래스의 메시지 혹은 행위에 대해 테스트를 수행합니다. FixedAmountVoucher 가 정상적으로 생성되는 경우, 생성될 수 없는 경우 그리고 discount를 할 수 있는 경우 없는 경우를 나눌 수 있고. 비정상적인 경우에는 어떤 예외가 발생할 지, 정상적인 경우에는 반환된 값을 검증할 수 있습니다.

테스트를 작성할 때 최근에는 given, when, then 구조를 많이 사용합니다. https://brunch.co.kr/@springboot/292

참고해서 작성해보시면 좋을 것 같네요.

2023-06-23 06:47 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/CommandLineApplication.java
> +}
```suggestion
@SpringBootApplication
public class CommandLineApplication {
	public static void main(String[] args) {
		SpringApplication.run(org.devcourse.voucher.CommandLineApplication.class, args);
	}
}
```

2023-06-23 06:47 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/Main.java
> +}
```suggestion
@Component
public class Main implements ApplicationRunner {
    @Override
    public void run(ApplicationArguments args) throws Exception {
        Console console = new Console();
        console.printMenu();
        String option = console.getOption();
        System.out.println(option);
    }
}
```
`ApplicationRunner`를 활용하면 깔끔해질 것 같네요. 그리고 Main 클래스도 Console 애플리케이션과 관련된 것이라 패키지 이동이 필요해보입니다. 클래스 이름도 명확하게 지어주세요
- https://www.daleseo.com/spring-boot-runners/

2023-06-23 06:47 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/FixedAmountVoucher.java
> +    }
null, 유효 범위 등 검증 로직이 필요해 보이네요

2023-06-23 06:47 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/FixedAmountVoucher.java
> +    }
- 바우처가 할인 금액을 반환할 지, 할인된 금액을 반환할 지 고민해봐야할 문제라고 생각합니다. 할인된 금액을 반환한 이유가 있을까요?
- beforeDiscount는 음수여도 상관이 없을까요?

2023-06-23 06:47 UTC, seung-hun-h commented on voucher/src/test/java/org/devcourse/voucher/domain/FixedAmountVoucherTest.java
> +    }
바우처 생성에 관한 테스트라기 보다는 할인과 관련된 테스트인 것 같아요.
테스트 메서드 이름과 DisplayName을 좀 더 명확히 작성해주세요

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/main/java/org/devcourse/voucher/console/Console.java
> +    public static final String EXIT = "exit";
아마 명령에 대한 문자열 정보인 것 같은 데 Console 객체가 알고 관리하는 게 맞는 지 의문이 들어요!

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/main/java/org/devcourse/voucher/console/Console.java
> +    public static final String EXIT = "exit";
```suggestion
    public static final String CREATE_COMMAND_STRING = "create";
    public static final String LIST_COMMAND_STRING = "list";
    public static final String EXIT_COMMADN_STRING = "exit";
```
정답은 없지만 제가 제시한 예시처럼 조금 더 의미 있는 변수명을 사용하면 좋을 것 같아요!

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/main/java/org/devcourse/voucher/console/Console.java
> +        System.out.print("== Voucher Program ==\nType exit to exit the program.\nType create to create a new voucher.\nType list ot list all vouchers.\n>> ");
명령어에 대한 정보가 상수로 관리되고 있는 데 여기에 사용 안되는 게 아쉬워요!

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/main/java/org/devcourse/voucher/console/Console.java
> +        System.out.print("== Voucher Program ==\nType exit to exit the program.\nType create to create a new voucher.\nType list ot list all vouchers.\n>> ");
```suggestion
        String menuString = """
            == Voucher Program ==
            Type exit to exit the program.
            Type create to create a new voucher.
            Type list ot list all vouchers.
        """.trim();
        System.out.print(menuString);
```
텍스트 블록을 사용할 수도 있고 다른 방법으로도 해당 문자열을 더 가독성 있게 표현해낼 수 있을 것 같아서 고민해보시면 좋을 것 같아요

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/main/java/org/devcourse/voucher/domain/Voucher.java
> +}
Voucher를 표현할 수 있는 다양한 방법이 있었을 것 같은 데 인터페이스가 가장 적절했다고 생각하는 이유가 뭘까요?

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/test/java/org/devcourse/voucher/CommandLineApplicationTest.java
> +}
무슨 클래스 일까요? 
그리고 마지막 개행 문자 추가 해주세요!

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/test/java/org/devcourse/voucher/DemoApplicationTests.java
> +}
어떤 것을 테스트 하는 걸까요?

2023-06-23 17:48 UTC, dojinyou commented on voucher/src/test/java/org/devcourse/voucher/domain/FixedAmountVoucherTest.java
> +class FixedAmountVoucherTest {
다양한 실패 케이스에 대해서도 테스트가 되어야할 것 같아요

2023-06-27 04:16 UTC, na-yk commented on voucher/src/main/java/org/devcourse/voucher/CommandLineApplication.java
> +}
이 애플리케이션을 구동하는 VoucherApplication파일을 두고 CommandLineApplication 파일을 console 패키지에 두어 `Console` 객체를 실행하도록 변경해보았는데 이런 방식은 어떤지 궁금합니다! 
기존 Main의 역할을 보고 의미 있는 클래스 이름을 생각해보다가 CommandLineApplication이 적절하다고 생각했습니다.

19a842b54528f9c98d0f86b7e37e277727ac3250
aa66a0d338d745938e37fc70e835c1fc0420ef43

2023-06-27 04:17 UTC, na-yk commented on voucher/src/main/java/org/devcourse/voucher/domain/FixedAmountVoucher.java
> +    }
반영해보았습니다!
0ebc250d3aa884465a7dab757cfd020338154743

2023-06-27 04:18 UTC, na-yk commented on voucher/src/test/java/org/devcourse/voucher/domain/FixedAmountVoucherTest.java
> +    }
56c91983f43fe7ce6bbb06d03e720af5a1301f25

반영해 보았습니다!

2023-06-27 07:57 UTC, na-yk commented on voucher/src/main/java/org/devcourse/voucher/domain/Voucher.java
> +}
두 바우처에 중복되는 멤버들이 있다고 생각해서 추상클래스로 변경해 보았습니다!

9d677b77c57554f5c653910cf023b7b1bc84c885
0ebc250d3aa884465a7dab757cfd020338154743

2023-06-27 07:58 UTC, na-yk commented on voucher/src/test/java/org/devcourse/voucher/domain/FixedAmountVoucherTest.java
> +class FixedAmountVoucherTest {
리뷰 반영해 보았습니다!

909906f9f843febaeff206bacb1db82eea51b5da

2023-06-27 11:20 UTC, dojinyou reviewed
코멘트 확인해주세요! 
코멘트 한 부분 외에도 동일한 사항 적용되면 좋을 것 같아요!

2023-06-27 11:20 UTC, dojinyou commented on voucher/src/test/java/org/devcourse/voucher/console/CommandLineApplicationTest.java
> +}
개행 문자

2023-06-27 11:20 UTC, dojinyou commented on voucher/src/test/java/org/devcourse/voucher/domain/FixedAmountVoucherTest.java
> +        assertNotEquals(5000,fixedAmountVoucher.discount(100000));
매직 넘버보다 변수명을 이용해주세요

2023-06-27 13:36 UTC, seung-hun-h requested changes

2023-06-27 13:36 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/console/CommandLineApplication.java
> +                System.out.println("Create Voucher");
출력에 대한 책임은 `Output`이 가지는 것이 좋아보여요

2023-06-27 13:36 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/FixedAmountVoucher.java
> +        return beforeDiscount - discountAmount;
beforeDiscount가 discountAmount보다 크면 음수가 나오겠는데요

2023-06-27 13:36 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/Voucher.java
> +    public abstract long discount(long beforeDiscount) throws IllegalArgumentException;
`IllegalArgumentException`을 명시적으로 throw하신 이유가 있을까요?

2023-06-27 13:36 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/Voucher.java
> +    public abstract String getType();
타입을 읽어오는 것이 인터페이스 메시지로 적합 할까요?
메시지는 보통 의미있는 행위에 대해서 추상화를 합니다!

2023-06-27 13:36 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/Voucher.java
> +    Voucher() {
```suggestion
    protected Voucher() {
```

2023-06-27 13:36 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/FixedAmountVoucher.java
> +    private final String TYPE = "FIXED";
type을 String 말고 Enum, Class 를 활용해서 정의해보면 좋을 것 같아요

2023-06-27 13:36 UTC, seung-hun-h commented on voucher/src/main/java/org/devcourse/voucher/domain/PercentDiscountVoucher.java
> +        this.discountPercent = discountPercent;
percent에 대한 유효성 검증 로직이 필요해보이네요. 0 이나 음수가 되면 안될 것 같아요

2023-06-30 04:13 UTC, merged