[4기 - 박상민] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #660
Opened 2023-06-22 17:52 UTC by smart-sangmin

## 📌 과제 설명 및 요구 사항과 구현 내용
#### 바우처 관리 어플리케이션
- [x] 바우처 설계
- [x] 바우처 개발

## ✅ PR 포인트 & 궁금한 점 

1. `Voucher` 를 interface가 아닌 class로 구현했고 `Voucher` 를 상속 받아서 `FixAmountVoucher` 와 `PercentDiscountVoucher` 를 만들었습니다.  상속보다 조합이나 인터페이스를 사용하는 것이 좋다고 들었지만, 조합을 사용하기엔 애매하고 인터페이스를 사용하기엔 `FixAmountVoucher` 와 `PercentDiscountVoucher` 가 겹치는 부분이 너무 많아서 상속을 사용하지 않을 이유가 없다고 생각해서 상속으로 구현했습니다. 혹시 더 좋은 방법이 있다면 말씀 부탁드립니다!
2. 좀 더 많이 배우고 이것저것 해보고 싶은 마음에 사용조건(`condition`) 이나 유효기간(`expirationDate`) 를 넣어봤습니다.

2023-06-23 07:00 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
state를 반환하는 메서드에서 변경까지 이뤄지고 있습니다. 이와 같은 side-effect를 가진 메서드가 많아지면 버그가 많아질 수 있습니다. 따라서 변경 로직은 분리하는 것이 좋아보여요

2023-06-23 07:07 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
```suggestion
    protected boolean isExpiration() {
        LocalDateTime now = LocalDateTime.now();
        return now.isAfter(expirationDate);
    }
```
- 부정문 보다는 긍정문이 이해하기 쉽습니다.
- 바우처가 만료되었는지 테스트한다고 생각하면 `now` 같은 통제할 수 없는 코드가 있다면 쉽지 않을 것 같아요. 테스트 코드에서 expirationDate를 2023년 01월 01일로 설정한다고 생각해볼게요. 그러면 now가 2022년 12월 10일인 경우와 now가 2023년 06월 01인 경우 반환값이 달라질 거에요.
 
https://jojoldu.tistory.com/676

2023-06-23 07:13 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
추상 클래스(extends)와 인터페이스(implements) 모두 다형성을 구현하기 위해 자바에서 제공하는 방법입니다. 상속은 보통 타입을 계층화 하거나 공통 행위를 공유하기 위해 사용합니다. 인터페이스는 계층화되지 않는 타입을 정의하는데 많이 사용됩니다.

단순히 공통된 부분이 많으니 추상 클래스를 사용하는 것이 올바른 선택 기준이라고 보기는 어렵습니다. 추상 클래스를 사용하면 캡슐화가 깨질 위험이 있기 때문입니다. 따라서 추상 클래스를 사용할 때는 꼼꼼하게 설계 해야하죠.

추상 클래스와 인터페이스의 차이를 공부하는 것이 도움될 것 같네요.

2023-06-23 07:13 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
불필요한 getter는 제거해주세요

2023-06-23 07:15 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    private final Long condition;
`condition`은 어떤 역할을 하는거죠?

2023-06-23 07:16 UTC, seung-hun-h commented on src/test/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucherTest.java
> +        Long expectedPrice = Math.round(price * ((100 - percent) / 100d) / 10) * 10;
기대하는 값을 연산하기 보다는 값을 그대로 적어주는 것이 테스트를 이해하는데 도움이 될 것 같습니다.
이러한 식을 테스트에 작성한다는 것 자체가 클래스의 내부 구현을 드러내는 것과 동일하다고 생각합니다.

2023-06-23 09:59 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    private final Long condition;
보통 쿠폰이 `얼마`이상 구매 시 사용 가능 이라는 부분이 있더라구요
거기서 `얼마` 인지에 대한 인스턴스 변수입니다

2023-06-23 10:04 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
> +    }
어떤 말씀인지 잘 이해가 되지 않습니다ㅜㅜ

제가 의도한 것은 discount 메서드는 반환값이 "할인 금액"이 아닌 "할인이 적용된 금액"을 반환하는 메서드입니다!
또, 일원 단위를 제거하기 위해 round를 적용했습니다.

2023-06-23 10:34 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
> +    }
priceBeforeDiscount = 1000
percent = 10

`return priceBeforeDiscount - priceBeforeDiscount * percent / 100`

1000 - 1000 * 10 / 100 = 900

처럼 계산식이 단순해질 수 있다는 의미였습니다.

2023-06-23 10:35 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    private final Long condition;
바우처를 사용할 수 있는 최소 금액을 말씀하시는 것 같네요.
그렇다면 최소 금액을 나타낼 수 있는 이름을 지어주는 것이 좋아보여요.

2023-06-23 11:41 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
넵 변경 로직은 Service에서 구현해보겠습니다!

2023-06-23 15:37 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        if (priceBeforeDiscount - amount <= 0) {
수정했습니다.

[38cf549](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/38cf549dc50f9bd46de8a756b35c02568a743ca1)

2023-06-23 15:38 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucherTest.java
> +        Long expectedPrice = Math.round(price * ((100 - percent) / 100d) / 10) * 10;
제가 테스트를 중복으로 작성했더라구요ㅎㅎ
나머지 말씀 주신 부분의 테스트는 삭제했습니다.

[252e725](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/252e72584292c465254f5c84c25e1b0bdcdaf055)

2023-06-23 15:41 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
수정했습니다.

[51c0990](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/51c0990168e2535f3a55d7bcbb8a703c1b1ee4d0)

2023-06-23 15:49 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    private final Long condition;
정보를 좀 더 담아서 변수명
condition -> minimumPrice -> minimumPriceCondition 으로 최종 변경하였습니다.

[61a3991](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/61a39910118dc868a97c39c49eaee18bbb71e62a)

[8ba5c1e](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/8ba5c1ed8cc917a82554b9a64608973e8700be7d)

2023-06-23 15:50 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
> +    }
식 좀 더 단순한 방식으로 직관적으로 변경하였습니다.

[3b738fe](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/3b738fecf6b36618ff9ce2398a3ad8c759345f3c)

2023-06-23 15:50 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        this.amount = amount;
amout에 대한 검증 로직 및 percent에 대한 검증 로직 구현했습니다.

[e012827](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/e0128274345e82309268edcaa85f8ca39c0cf6d4)

2023-06-23 18:25 UTC, dojinyou reviewed
설계도를 다이어그램과 같은 시각적인 자료로 함께 보여주시면 좋을 것 같습니다.
유효 조건이나 컨디션 등 추가한 요구 사항을 정리해서 같이 추가해주시면 좋을 것 같아요

2023-06-23 18:25 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherState.java
> +    private final String state;
`VoucherState.state`라는 네이밍보다는 조금 더 좋은 이름을 고민해보시면 좋을 것 같아요!

2023-06-23 18:25 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
사용 가능한 지 여부를 체크하는 로직이 필요할 것 같아요!

2023-06-23 18:25 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
개인적인 생각으로는 `use`라는 메서드와 `discount`라는 메서드가 같은 역할이라고 생각하는 데 어떻게 생각하시나요?

2023-06-23 18:25 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        int MAX_AMOUNT = 10_000_000;
static 하게 상수로 저장하면 좋을 것 같아요!

2023-06-23 18:25 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        this.amount = amount;
다른 필드들도 검증이 함께 되면 좋을 것 같아요!

지금 생각으로는 `expirationDate`는 과거 데이터가 들어오면 안될 것 같아요!
ID도 null 체크가 필요할 거 같구요!

2023-06-23 18:25 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
> +        return Math.round((priceBeforeDiscount - (priceBeforeDiscount * percent / 100d)) / 10) * 10;
가독성이 안 좋은 것 같아요! 변수를 적절하게 사용하시는 게 좋아 보입니다!

2023-06-24 09:03 UTC, smart-sangmin commented on build.gradle
> +}
이후 버젼을 학습 해본 적이 없어 가장 익숙한 11버젼을 사용했습니다

2023-06-24 09:04 UTC, smart-sangmin commented on build.gradle
> +    id 'org.springframework.boot' version '2.7.12'
3버전 부터는 java 17이상부터 지원하기 떄문에 익숙한 java11버전을 사용하기 위해 2.7버전을 사용했습니다.

2023-06-24 09:06 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/SpringbootBasicApplicationTests.java
> +}
Spring 프로젝트 생성 시 자동으로 설정된 부분인 것 같습니다.
삭제하는 것이 좋을까요?

2023-06-24 09:13 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
> +}
wow 파일 끝에는 항상 개행 문제를 추가해야 되는 것 처음 알았습니다.

2023-06-24 09:29 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
> +    void discount(Long price, Long amount, Long expectedPrice) {
테스트 네이밍을 찾아봤고

given_when_then 으로 변경했습니다!
근데 잘 작성한지는 모르겠습니다ㅜㅜ

[5bc6242](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/5bc6242c6c01869d93e7c94695da2b4fc95601ca)

2023-06-24 09:40 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherState.java
> +    private final String state;
state -> stateName으로 변경했습니다.

[0c17579](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/0c17579eb5d237c9cdd3dbc2edbcf2b608bcd87e)

2023-06-24 09:55 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
getDiscountPrice: 할인 금액 반환
discount: 실제 voucher 사용 행위
use: 메소드 삭제

위 처럼 refacotring 했습니다.

[8160e81](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/8160e81b69536d7f76899e0167db44cb06f54c38)

2023-06-24 09:59 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        int MAX_AMOUNT = 10_000_000;
처음에 기계적으로 그렇게 구현했었는데, 생각해보니 저 변수들을 사용하는 부분이 `isInvalidateAmount` 밖에 없다고 생각했습니다.

미미하겠지만 메모리 측면에서 그럼 지역변수로 두면 쪼오끔은 낫겟다 싶어서 그렇게 구현습니다.

그냥 static으로 두는게 나은건가요? 낫다면 어떤 측면에서 나은건가요?

2023-06-24 10:09 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
> +        return Math.round((priceBeforeDiscount - (priceBeforeDiscount * percent / 100d)) / 10) * 10;
수정했습니다.

[efa6a19](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/efa6a19fd733a8ae56aaf31624e2175fea48134d)

2023-06-24 13:59 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        this.amount = amount;
`voucherId` ,`name`, `expirationDate` 에 대한 검증로직 구현했습니다!

[324dd4c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/324dd4c72233996ab7a55660f586c578db3f4e9b)

2023-06-24 16:31 UTC, dojinyou commented on build.gradle
> +    id 'org.springframework.boot' version '2.7.12'
신입이니까 회사에서 제일 트렌디한 사람이 본인이라고 생각하시고 그런 회사에 간다고 생각하시면 됩니다.
회사에서 제일 트렌디한 사람이 java 11이랑 2.7을 좋아하는 회사보단 17이랑 3를 좋아하는 회사가 더 좋지 않을까요?

2023-06-24 16:31 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        int MAX_AMOUNT = 10_000_000;
정책적인 값이라고 생각했고 그런 값을 보통 static하게 관리되기 때문에 그 위치에 있을 때 다른 사람들이 읽기 좋다고 생각했습니다.

2023-06-24 16:31 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
> +}
개행 추가해주세요

2023-06-24 16:31 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
> +        return Math.round((discountedPrice) / 10) * 10;
매직 넘버를 지양해주세요

2023-06-24 16:31 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
parameter valid가 필요하면 해당 목적의 메서드를 만들어서 한번 호출하는 건 어떨까요?
내부에서 필요한 검증을 하면 중복을 줄이고 새로운 검증이 추가되었을 때, 해당 메서드에만 추가하면 될 것 같아요

2023-06-24 16:31 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +        return name == null || name.isEmpty();
```suggestion
        return name == null || name.isBlank();
```

2023-06-24 16:31 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/SpringbootBasicApplicationTests.java
> +}
필요 없다면 삭제하고 필요하다면 남겨주세요!

2023-06-24 16:31 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
> +        assertThat(fixedAmountVoucher.getName()).isEqualTo(name);
생성 성공 테스트의 검증 값이 `name`인 이유가 있나요?

2023-06-25 02:28 UTC, seung-hun-h requested changes

2023-06-25 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
```suggestion
    protected Voucher(UUID voucherId, String name, LocalDateTime expirationDate) {
        this(voucherId, name, null, expirationDate);
    }

    protected Voucher(UUID voucherId, String name, Long minimumPriceCondition, LocalDateTime expirationDate) {
        if (isInvalidVoucherId(voucherId)) {
            throw new IllegalArgumentException("잘못된 아이디 값. voucherId=" + voucherId);
        }
        this.voucherId = voucherId;
        if (isInvalidName(name)) {
            throw new IllegalArgumentException("잘못된 이름. name="+name);
        }
        this.name = name;
        this.minimumPriceCondition = minimumPriceCondition;
        if (isInvalidExpirationDate(expirationDate)) {
            throw new IllegalArgumentException("잘못된 유효기간. expirationDate="+expirationDate);
        }
        this.expirationDate = expirationDate;
    }
```
추가적으로 이렇게 작성해주면 코드 중복이 줄어들 것 같네요.
그리고 예외 메시지를 구체적으로 작성해주면 좋을 것 같아요.

2023-06-25 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        int MAX_AMOUNT = 10_000_000;
- true, false만 반환하므로 `boolean`을 반환해줘도 좋을 것 같아요.
- 지역 변수는 카멜 케이스로 작성해주세요

2023-06-25 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    protected abstract Long discount(Long priceBeforeDiscount);
`discount`는 할인 금액을 반환하고 바우처의 상태를 변경하는 것 같은데 추상 메서드가 아니라  부모 클래스에서 기본 구현을 제공하는 방식이 나을 것 같다는 생각이 드네요

```suggestion
    public Long discount(Long priceBeforeDiscount) {
        this.state = VoucherState.USED;
        return getDiscountPrice(priceBeforeDiscount);
    }

    protected abstract Long getDiscountPrice(Long priceBeforeDiscount);
```

2023-06-26 08:03 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
수정했습니다.

[5098c15](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/5098c151803e9a37631edb56677dd44335cb5f42)

2023-06-26 08:03 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +        return name == null || name.isEmpty();
수정했습니다.

[bd7e6a5](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/bd7e6a5c800c7979832a49b28a0dd19a52b8d2b3)

2023-06-26 08:05 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
> +        assertThat(fixedAmountVoucher.getName()).isEqualTo(name);
딱히 이유는 없고 내부값 중에 하나 골랐습니다.
찾아보니 사람들마다 테스트하는 방식이 다양하던데
도진님께서 생각하는 혹시 좋은 방법이 있을까요?

2023-06-26 08:06 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        int MAX_AMOUNT = 10_000_000;
수정했습니다

[86035f8](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/86035f892c36f7378172b6805d584cf79b669711)
[5098c15](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/5098c151803e9a37631edb56677dd44335cb5f42)

2023-06-26 08:07 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    protected abstract Long discount(Long priceBeforeDiscount);
discount 부모클래스에서 구현했습니다.

[d79ba90](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/d79ba904c07e7a10a6ebd56d96e60980f1f4ad28)

2023-06-26 08:08 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
생성자 중복부분, 예외메세지 말씀 주신 방법으로 변경했습니다.


[22d2a24](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/22d2a24ce11d4b2599d018304b86b4b14a6f3434)

2023-06-26 10:36 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
좋아요! 별도로 사용하기 전에 사용할 수 있는 지 체크하는 로직이 필요해 보여요!

2023-06-26 11:48 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +        this.expirationDate = expirationDate;
validation 코드를 모아서 하나의 메서드를 만드는 것도 좋을 것 같아요!

2023-06-26 11:48 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
> +        assertThat(fixedAmountVoucher.getName()).isEqualTo(name);
어떤 걸 찾아 봤는 데 사람 마다 다양한가요?
테스트 목적인 생성 여부라면 생성 여부를 확인 해야 되지 않을까요?

2023-06-26 11:48 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
> +                .hasMessage("잘못된 할인 금액");
에러 메세지가 수정되었을 때 여기도 수정을 한번 더 해줘야할 것 같은데 테스트에서 불필요한 관리 포인트가 늘어나는 것 같은 데 어떻게 생각하시나요?

2023-06-26 11:48 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/VoucherTest.java
fixedAmountVoucherTest와 어떻게 다를까요?

2023-06-26 11:48 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/VoucherTest.java
> +}
개행 문자 ㅎㅎ 같은 코멘트가 여러 번 나오는 것 같아요

2023-06-26 13:08 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        }
예외 메시지가 좀 더 친절하면 좋겠네요. 그대로 작성하는 것을 요청한 것은 아니였습니다. 범위가 얼마인데 현재 값은 얼마가 들어 왔다 정도로 작성해주세요.

2023-06-26 13:08 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
now는 통제할 수 없는 값입니다. 현 시점에서 작성한 테스트 코드가 성공해도 나중에는 실패할 수도 있을 것 같아요. 유효기간은 외부에서 주입 받도록하는 것이 좋아보이네요.

2023-06-26 17:29 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +    static int MAX_AMOUNT = 10_000_000;
final 수정했습니다.

[6484f29](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/6484f293ac6c3bc5203862186c3f86837f317035)

2023-06-26 17:33 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +        this.expirationDate = expirationDate;
통합해서 에러 발생시키는 메서드 생성했습니다.

따른 코드 고민하다가 한 커밋에 많은 액션이 들어갔습니다.

주의하겠습니다.

[683a03f](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/683a03fb9bd16bd78f18cb38d56fa1ba6c31680f)

2023-06-26 17:35 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/VoucherTest.java
`FixedAmountVoucherTest` 는 amount 값에 대한 테스트이고

`VoucherTest` 는 그 외 id, name, 유효기간 에 관한 테스트입니다.

2023-06-26 17:36 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/VoucherTest.java
> +}
앗......

인텔리제이에서 자동설정해 주는 기능이 있어서 설정은 해뒀는데

동작을 안 할때가 있나보네요

확인 잘 하겠슴다

2023-06-26 17:37 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        }
좀 더 친절하게 메세지 작성했습니다.

여러가지를 한꺼번에 고민하다가 커밋에 액션이 좀 많이 들어갔습니다.

주의하겠습니다

[683a03f](https://github.com/prgrms-be-devcourse/springboot-basic/pull/660/commits/683a03fb9bd16bd78f18cb38d56fa1ba6c31680f)

2023-06-26 17:41 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
`createdDate` 라는 변수를 통해 생성시간을 주입받게 했습니다.

이후 값들은 `createdDate` 와 `expirationDate` 를 비교해서 에러 반환했습니다.

Voucher 사용 시 `use` 메서드를 사용하는데

수정 전에는 `할인 전 금액` 만 파라미터로 받았지만, 수정 후에는 `할인 전 금액` 과 `특정 시간` 을 파라미터로 받아서

"특정시간에 쿠폰을 사용하는 메서드" 로 변경 하였습니다.

2023-06-27 10:52 UTC, dojinyou commented on build.gradle
> +}
자바 17버전을 학습해보시는 게 좋을 것 같아요!

2023-06-27 10:58 UTC, dojinyou approved these changes

2023-06-27 14:43 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +    static final int MAX_AMOUNT = 10_000_000;
접근 제어자가 default인 이유가 있을까요?

2023-06-27 14:47 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
> +    }
바우처 사용 할 때 사용 가능한 바우처인지 검증하고 사용하는 메서드로 만들었습니다.

가격 반환하는 것은 getDiscountPrice로 반환합니다!

미팅 때 말씀하신 CQS를 지키려고 하다보니

use 메서드는 command로 인스턴스 변수 값을 변경, getDiscountPrice는 query로 할인 값을 가져온다라고 생각했습니다.

2023-06-27 14:50 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +            );
넵 인지하고 있겠습니다.

2023-06-28 00:11 UTC, seung-hun-h approved these changes

2023-06-28 02:42 UTC, merged