[4기] 오세한 SpringBoot Part1 Weekly Mission제출합니다.
prgrms-be-devcourse/springboot-basic pull request #666
Opened 2023-06-23 12:52 UTC by 2jie0516

## 📌 과제 설명 

(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌   파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
**클래스 다이어그램**

![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/102570281/4875b8cd-3325-4eb9-b343-11f03d1830a8)

**클래스 설명**

FixedAmountVoucher.java
- 고정 할인가 바우처에 대한 구현 클래스입니다.

PercentDiscountVoucher.java
- 할인률 적용 바우처에 대한 구현 클래스입니다.

Voucher.java
- 바우처에 대한 추상 클래스입니다.

MemoryVoucherRepository.java
- 리스트로 바우처 목록을 저장하는 저장소 구현 클래스입니다.

VoucherRepository.java
- 바우처 저장소 인터페이스입니다.

VoucherService.java
- 바우처에 대한 비즈니스 로직을 담당하는 클래스입니다. 

Console.java
- 입력값과 출력값을 처리하는 구현체입니다.

Input.java
- 입력 값을 처리하기 위한 인터페이스입니다.

Output.java
- 출력 값을  처리하기 위한 인터페이스입니다.

Menu.java
- 메뉴에 대한 타입이 설정되어 있는 enum 클래스입니다.

CommandLine.java
- 커맨드 입력 처리를  담당합니다.

VoucherApplication.java
- 프로그램을 실행하면 가장 먼저 실행되는 클래스입니다.

## ✅ PR 포인트 & 궁금한 점 

1. 출력에 관한 부분은 무조건 ouput 에서 인터페이스로 구현하도록 했는데 너무 엄격하게 구분지을 필요는 없을까요 ?
2. input 과 output 인터페이스에서 추상메소드를 용도에 맞게 여러개 만들었습니다. 근데 기능이 같은 메소드들은 하나로 통일하는 편이 
    나을까요?
3. 고정 할인과 할인률 바우처는 같은 속성 값을 공유하고 여러 클래스를 상속받지 않기에 추상 클래스를  상속받도록 하였습니다.
    올바른 선택이었을까요?

2023-06-24 03:17 UTC, HyoungUkJJang reviewed
안녕하세요 세한님 PR 올리시느라 고생하셨습니다 :) 

**설계도 그려주신거 잘 봤습니다 ! 설계도에 각 클래스의 관계(화살표)가 더 잘 드러나도록 표현해주시면 더 좋을 것 같아요 ~!**

**코드는 컨벤션 위주로 간단하게 남겼는데 참고해주시고 세한님도 편하게 의견 말씀해주시면 좋을 것 같아요 ☺️**

### 궁금한 점
1 .출력에 관한 부분은 무조건 ouput 에서 인터페이스로 구현하도록 했는데 너무 엄격하게 구분지을 필요는 없을까요 ?
* 내용이 추가될 때마다 메서드가 추가되어야 할텐데 유지보수 측면에서 약간 고민이 생기는 것 같습니다. 내용들을 상수로 관리하고 재활용 하는 방법도 고려해보시면 좋을 것 같습니다 :) 

2. input 과 output 인터페이스에서 추상메소드를 용도에 맞게 여러개 만들었습니다. 근데 기능이 같은 메소드들은 하나로 통일하는 편이 나을까요?
* 상황에 따라 다르겠지만 입력을 받는 경우는 많지 않을 너무 추상적인 메서드 보다는 의미있는 메서드 네이밍으로 구분지어주는것도 저는 괜찮은 것 같습니다. 
3. 고정 할인과 할인률 바우처는 같은 속성 값을 공유하고 여러 클래스를 상속받지 않기에 추상 클래스를 상속받도록 하였습니다. 올바른 선택이었을까요?
* 먼저 고민을 해보고 추성클래스를 도입하신 부분 너무 좋은 것 같습니다. 추상클래스가 공통적인 데이터가 많은 경우에도 사용될 수 있겠지만 꼭 한가지 이유만으로 추상클래스를 도입하는 것은 적절하지 않을 수도 있을 것 같아요 같이 추상클래스와 인터페이스의 사용용도에 대해 더 이야기해보고 고민해보는 시간을 같이 가져보면 좋을 것 같아요 👍🏻

2023-06-24 16:20 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +
넵 알겠습니다 !
자바 컨벤션도 아직 많이 부족해서 이번 기회에 많이 알아보고 코드에 적용해보겠습니다.
현재 코드들은 모두 수정하였습니다

2023-06-24 16:22 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +            String selectOption = null;
아마 매번 입력때마다 입력값을 초기화해준다... 라는 생각으로 했던 것 같습니다.
근데 지금 생각해보면 굳이 그럴 이유가 없던것 같아요 

해당 코드는 현재 수정하였습니다 !

2023-06-24 16:23 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        else return insertFixedAmountVoucher();
자바로 알고리즘 풀때 저렇게 하는게 익숙해서 안좋은 습관이 생긴것 같습니다 ㅠ
공유해주신 자료 꼼꼼히 읽어보겠습니다 

현재 코드에 있는 실행문들 모두 중괄호 처리하였습니다 !

2023-06-24 16:24 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +import java.util.*;
그 부분까지 미처 신경 못쓴것 같습니다
다음 pr때는 import문도 정리해서 올리겠습니다 .. !!

현재 해당 코드들은 모두 수정하였습니다 !

2023-06-24 16:25 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +    }
앗 .. 요즘 강의 복습하면서 optinal을 공부하다보니까 무의식적으로 감싼 것 같습니다 .. ㅠㅠ

코드는 현재 수정하였고 optional 이 언제 쓰이는 지에 대해서도 다시 알아보겠습니다 !

2023-06-24 16:26 UTC, 2jie0516 commented on spring_week1/src/test/java/prgms/spring_week1/VoucherApplicationTests.java
> +}
음 .. 제가 실수로 테스트를 하나 생성한 것 같습니다 

해당 테스트 코드는 지웠으며 테스트 코드는 곧 추가해서 pr 올리겠습니다 !

2023-06-24 16:30 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/io/Console.java
> +    }
저번 계산기 과제에서 상수 클래스는 지양하는 편이 좋다고 리뷰를 받아서 이번에는 그냥 출력을 해보았습니다 !
클래스는 만들지 않고 console에서 private final String 으로 해주면 될까요 ??

2023-06-24 16:31 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/model/impl/FixedAmountVoucher.java
> +    }
형욱 멘토님의 얘기를 들어보니 toString으로 출력을 하는 건 비효율적이라는 생각이듭니다 ..
toString으로 하기보다는 따로 바우처 출력 메소드를 만들어서 각자 클래스의 책임을 확실히 해보겠습니다 !

2023-06-24 16:33 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +        }
저게 좀 가독성이 좋아보인다고 생각을 하여서 괄호로 묶었습니당 .. 
근데 다른 분들이 보시기엔 약간 의아한 느낌이 들수도 있다고 생각하여서 코드 수정하였습니다 !

2023-06-24 16:34 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/model/impl/FixedAmountVoucher.java
> +        super(voucherId, voucherType, discount);
validation 처리 클래스를 만들어서 말씀해주신 부분을 보완해보겠습니다 !

좋은 리뷰 남겨주셔서 정말 감사드립니다 !!

2023-06-25 17:23 UTC, Jo-GyuHyeon requested changes
안녕하세요 세한님. 첫번째 PR 이네요. 
형욱님이 코드리뷰를 먼저 잘 해주셔서 저는 간단하게 코멘트를 남겨 두었어요.
코멘트들이 생각보다 많이 있기에 피드백 반영을 먼저 진행하시게 될것 같네요.
고생하셨습니다. 👍

2023-06-25 17:23 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        boolean IS_VALID = true;
insert 내부에서 입력 값을 받고 있는것 같아요. 외부로 부터 입력 값을 받을 수 있도록 변경 해보는것은 어떨까요?

2023-06-25 17:23 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/validation/impl/DiscountAmountValidation.java
> +@Component
import 구분 사이에는 개행을 추가해주세요.

2023-06-25 17:23 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/validation/impl/PercentDiscountValidation.java
> +public class PercentDiscountValidation implements DiscountValueValidation {
Validation 을 따로 분리해서 만드신 이유가 궁금해요.
설명해주실수 있을까요?

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final boolean IS_RUNNING = true;
e52b4b51db6bf092a36b23100327e953d09031cc 커밋 피드백 반영

- IS_RUNNING에서 final 키워드를 제거하였습니다 !

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +        }
c7f6fa01f02f9f2f1fedc6f02641e7a88f5ba57f 커밋 피드백 반영
- findAll()을 한번만 수행하도록 변경하였습니다 !

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
In과 Out 클래스 간에는 의존관계가 느슨한 것이 좋다고 생각합니다 .. 
혹시 In과 Out간의 서로 참조하고 있는 메소드가 많은 것이 문제일까요 ?

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +@Repository
9d5a51e7244c35d670c2da30b89b50510755a140 커밋 피드백 반영
- 넵 개행문자 추가하였습니다.

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +            BufferedReader br = new BufferedReader(new FileReader(new File("/home/osh/Downloads/java_week1/spring_week1/src/main/resources/BlackListCsv.csv")));
b32eda327105d3817c6078056f7725c8f082be8c 커밋 피드백 반영
- 넵 리소스 경로로 설정하고 yaml 파일에 넣었습니다 !

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +        return new ArrayList<>(blackListRepository.getBlackConsumerList());
https://velog.io/@injoon2019/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-50.-%EC%A0%81%EC%8B%9C%EC%97%90-%EB%B0%A9%EC%96%B4%EC%A0%81-%EB%B3%B5%EC%82%AC%EB%B3%B8%EC%9D%84-%EB%A7%8C%EB%93%A4%EB%9D%BC

해당 블로그 글을 참조하여 방어적 프로그래밍을 하려고 했습니다 !
혹시 부적절한 방법이었을까요 .. ??

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +    private final Input input;
11616b7c48aa508e4e7db208a981949287dfa39e 커밋 피드백 적용
- 넵 기존 서비스에서 in,out을 받는 게 아닌 모두 커맨드라인 클래스에서 수행하도록 하였습니다 !

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        }
11616b7c48aa508e4e7db208a981949287dfa39e 커밋 피드백 반영
- 넵 else 키워드를 제거하였습니다 !

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +                .orElseThrow(() -> new NoSuchVoucherType("해당 바우처 타입이 존재하지 않습니다.")));
d09b115ab9e0d684cadd903e06d6da290d7d11e6
a91bb17193004d98216c2ff37b5a8af5db378d7f
커밋 피드백 반영

- 넵 해당 블로그 글 참고하여서 코드 변경했습니다 .. !!

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        boolean IS_VALID = true;
앗 .. 혹시 
```
voucherRepository.insert(new FixedAmountVoucher(UUID.randomUUID(),VoucherType.FIXED,discountAmount)); 
```
코드가 문제가 되는 것일까요 ??

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/validation/impl/DiscountAmountValidation.java
> +@Component
넵 추가하였습니다 !

2023-06-28 03:16 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/validation/impl/PercentDiscountValidation.java
> +public class PercentDiscountValidation implements DiscountValueValidation {
8a4c48c382e98b73954e259273ce2d4ef2894130 커밋 피드백 반영

- Validation 만 담당하는 클래스가 있으면 좋을 것 같다는 생각이 들어서 따로 만들어 보았습니다.
- 결과적으로 해당 클래스는 리팩토링 과정에서 제거하였습니다 ! 굳이 따로 둘 필요가 없을 것 같다고 생각합니다

2023-06-28 06:02 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final boolean IS_RUNNING = true;
@2jie0516 단순히 final 을 제거 하기 보다 종료 되는 상태로도 변경이 되어야 될것 같아요.

2023-06-28 06:07 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
@2jie0516 무조건 느슨한 관계가 좋은 관계 일까요??
in,out 이 느슨하면 어떤 부분이 좋을까요??? 조금더 구체적으로 알려주실 수 있을까요?

2023-06-28 06:11 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/validation/impl/PercentDiscountValidation.java
> +public class PercentDiscountValidation implements DiscountValueValidation {
@2jie0516 커밋 메시지를 보았을때는 어떠한 작업을 하셨는지 유추하기 어려운것 같아요.
커밋 메시지에 더 신경을 써주시면 좋을것 같아요.
커밋 메시지만 목록 전체를 보고 어떠한 작업들을 하셨는지 파악이 되면 좋을것 같아요.

2023-06-28 06:17 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +                .orElseThrow(() -> new NoSuchVoucherType("해당 바우처 타입이 존재하지 않습니다.")));
@2jie0516 다시 피드백을 하기 위해서 Resolve 처리 할게요.

2023-06-28 06:19 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        }
@2jie0516 커밋 단위와 커밋메시지를 보았을때 이해하기 힘든것 같아요.
커밋 단위와 메시지에 신경써주시면 좋을것 같아요.
해당 코멘트는 resolve 처리 후 다시 리뷰 할게요.

2023-06-28 06:24 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +    private final Input input;
@2jie0516 실제 커밋에서는 ouput, input 이 제거 되는 내용이 있지 않아 리뷰하기 쉽지 않은것 같아요.
커밋단위를 잘게 나누고 메시지에도 신경을 쓰시면 좋을것 같아요

2023-06-28 06:28 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        boolean IS_VALID = true;
@2jie0516 코드 리뷰 당시 service 내에서 input 을 사용하기에 핵심 로직과 입출력을 분리 하라는 의미였어요.

2023-06-28 06:38 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +        return new ArrayList<>(blackListRepository.getBlackConsumerList());
@2jie0516 현재 구조는 csv 파일에서 매번 값을 읽고 오고 있는 것으로 파악 하고 있어요.
언급해주신 블로그의 내용은 이해하였지만 지금 세한님의 경우랑 다른것 같다고 생각해요.

2023-06-28 06:58 UTC, Jo-GyuHyeon requested changes
안녕하세요 세한님 😄 

이번 리뷰는 코드 정렬이 안되어서 있어서 예시로 몇개반 리뷰 남겨 보았어요. 
(전체 확인 해보시면 좋을것 같아요)
코드 정렬은 가독성과 연결이 될 수도 있는데요.
흔히 아버지가 방에 들어 가신다. -> 아버지 가방에 들어 가신다. 라는 것을 들어 보셨을까요?
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/20269425/268a2c5b-7876-4a8a-9c84-3248d827dbbd)
그만큼 별개 아닐수 있지만 실은 중요한 포인트로 생각을 하고 있어요.

만약 정렬에 대한 도움을 받고 싶으시다면 해당 IDE 에서 자동정렬 기능을 이용하는 것도 좋아요.
(Intellij 기준 MacOS -> Cmd + option + L , Windows -> ctr + alt + L)
[jetbrains.com/help/idea/reformat-and-rearrange-code.html](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)

**전체 코드 정렬을 신경 쓴 후에 다시 리뷰를 진행 하면 좋을것 같아요.**

----

형상관리 함에 있어서 불필요한 파일을 .gitignore 파일에 등록 해주시면 좋을것 같아요.
ex) 로그파일

spring_week1 이라는 디렉터리 구조로 한번더 감싼 형태로 형상 관리가 되고 있는 것 같아요.
확인 부탁 드려요.

현재 폴더 구조
<img width="298" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/20269425/af5311a5-1d41-4965-a17c-120ef8d16479">

기대 하는 폴더 구조
<img width="286" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/20269425/cacbf055-9daa-499c-b6b6-ebf1afe63354">

2023-06-28 06:58 UTC, Jo-GyuHyeon commented on spring_week1/errorLogs/log
> +17:34:54.374 [main] INFO  p.spring_week1.VoucherApplication17:34:54.376 [main] INFO  p.spring_week1.VoucherApplication17:34:54.796 [main] INFO  p.spring_week1.VoucherApplication17:38:33.586 [main] IN
형상 관리에 불필요한 파일은 git ignore 처리 부탁 드려요.

2023-06-28 06:58 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +public class CommandLine implements Runnable{
코드 정렬 (띄어씌기)가 적용 되어 있지 않은것 같아요.
아래의 코드를 제안 드려보았어요.
```suggestion
public class CommandLine implements Runnable {
```

2023-06-28 06:58 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +        }
코드 정렬 (띄어씌기)가 적용 되어 있지 않은것 같아요.
아래의 코드를 제안 드려보았어요.


```suggestion
            }
        }
    }
```

2023-06-28 06:58 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +        }catch (NoSuchOptionValue e){
코드 정렬 (띄어씌기)가 적용 되어 있지 않은것 같아요.
아래의 코드를 제안 드려보았어요.

```suggestion
    private Menu findMenuName(String inputText) {
        try {
            Menu selectMenu = Menu.findMenuType(inputText);
            return selectMenu;
        } catch (NoSuchOptionValue e) {
```

2023-06-28 06:58 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private void selectVoucherType(){
코드 정렬 (띄어씌기)가 적용 되어 있지 않은것 같아요.
아래의 코드를 제안 드려보았어요.

```suggestion
    private void selectVoucherType() {
```

2023-06-29 03:15 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private void selectVoucherType(){
3ab7b9ee4d9c07b86b449be66511aebc4bf7f6d1 커밋 피드백 반영
- 멘토님의 피드백을 참고하여 전체 코드 정렬하였습니다 .
- 정렬 하나하나마다 커밋을 남기는 건 불필요하다고 생각해서 전체 코드 정렬 커밋으로 통합하였습니다.

앞으로는 코드의 정렬 , 가독성까지 신경쓰겠습니다 ... !

2023-06-29 03:17 UTC, 2jie0516 commented
d6673c2016aaf9efe1c3a7f2f7222617beac8b72 커밋 피드백 반영
- 비효율적인 디렉토리 구조를 개선하였습니다 !

이번 계기로 코드의 성능 뿐만 아니라 디렉토리 구조 , 정렬 , 가독성까지 신경써야겠다고 생각하는 계기가 되었습니다.

앞으로 pr을 올릴 때는 해당 부분 더 확인해보고 올리겠습니다 !

2023-06-29 03:18 UTC, 2jie0516 commented on spring_week1/errorLogs/log
> +17:34:54.374 [main] INFO  p.spring_week1.VoucherApplication17:34:54.376 [main] INFO  p.spring_week1.VoucherApplication17:34:54.796 [main] INFO  p.spring_week1.VoucherApplication17:38:33.586 [main] IN
1dce474370efa01bf1f1e401599ca47458ed398a 커밋 피드백 반영
- 넵 해당 파일 git ignore에 추가하였습니다 !
- pr 올릴 때 불필요한 파일은 없는지 주기적으로 검토하겠습니다

2023-06-29 03:47 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/io/Console.java
> +    }
c1365a5bf0a143cc57bb4d5738a27a0aa1797525 커밋 피드백 반영
- """ 코드 블럭 빛 메세지 상수화 진행하였습니다 !

2023-06-29 03:50 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final boolean IS_RUNNING = true;
c4578c46cb3e5f237710568600ebdbe6e8e5c131 커밋 피드백 반영
- 프로그램을 종료할 때 기존에는 System.exit를 사용했지만 IS_RUNNING을 false 로 변경하도록 하였습니다 !
- 혹시 이 의미가 맞으실까요 ..??

2023-06-29 04:43 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
객체지향에 대한 개념이 아직은 부족하지만 , 저의 생각에는

"느슨한 의존관계는 클래스간 의존성을 줄일 수 있다."
그 결과 의존성을 줄임으로써 객체지향을 지킬 수 있다고 생각합니다.

하지만 "이렇게 객체지향을 지키게 되면 지금 코드에서 어떤 점이 좋은가?" 라고 스스로에게 되물어보면 아직 명확한 답을 찾기 어렵습니다.

다만 제 생각에는 클래스간 의존성이 생기면 가독성이나 추후 확장에 있어서 안좋다고 생각합니다.

클래스간 의존성이 유리하게 작용하는 경우는 조금 더 알아보겠습니다..

이 관점에서 제 코드를 보면,

In,Out 클래스가 서로 의존하고 있다고 생각합니다.

예를 들어 어떤 코드는 
input에 대해 오류가 발생하면 CommandLine 클래스를 거치지 않고 바로 Output 클래스의 오류 출력 메소드로 넘어갑니다.

사실 이 부분이 의존관계 , 객체지향을 해치는 건지는 아직 확실하지 않고 체감이 되지 않습니다.

코딩을 할때 의아한 부분이 있었지만 크게 문제가 되지 않는다고 생각하였습니다.

이 부분에 대한 멘토님의 의견을 여쭤보고 싶습니다 !

commandLine 에서 받아서 i를 받아서 o를 내보내주는 방식으로 리팩토링 해야한다고 생각하는데 맞을까요 ?

2023-06-29 04:48 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +        return new ArrayList<>(blackListRepository.getBlackConsumerList());
e1bbe7248ba03293be6dfe7a4d2659bfa7166d7f 커밋 피드백 반영
- 멘토님의 말을 들어보니 csv 파일을 읽어올 때는 굳이 새로운 리스트를 생성할 필요가 없는 것 같습니다.
- 해당 코드 수정하였습니다 !

2023-06-30 13:22 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final boolean IS_RUNNING = true;
@2jie0516 넵 피드백을 잘 반영 해주신것 같아요. System.exit 와 어떤 차이가 있을까요? 세한님의 생각을 듣고 싶어요.

2023-06-30 13:35 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
@2jie0516 in,out 에 대한 서로 참조가 일어 난다는 것은 커플링이 있다고 인지하고 있는것 같아요. 그렇다면 in,out 둘 사이에는 서로 참조 하지 않도록 해야 될것 같아요.
제가 얘기 하고 싶은 부분은 CommandLine 에서 in,out 에 의존하여야 하는가? 에 대한 질문을 드리고 싶었어요.
또한 in, out 이 확장에 용이해야 하는가?에 대한 부분을 고민 해보셨으면 좋겠어요.

다른 예시로는 사람의 머리,몸,다리 에 대해 생각 해보면 좋을것 같아요.

2023-06-30 19:45 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final boolean IS_RUNNING = true;
사실 System.exit 가 정확히 어떤 기능을 하는 지 모르고 단순히 프로그램 종료 메소드로 알고 있었습니다.
이번에 알아보니 System.exit을 사용하게 되면 프로세스가 즉시 파괴되기에 그 이후 코드들이 실행되지 않고 멀티쓰레드에서의 문제 또한 생길 수 있다는 것을 알았습니다.

비록 지금은 별 문제가 없을 지 몰라도 해당 기능을 사용하기 보단 return을 통해 프로그램을 정상적으로 종료시키는 게 바람직하다는 생각을 가지게 되었습니다.

앞으로 해당 코드의 사용은 지양하도록 하겠습니다 !

2023-06-30 19:50 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
멘토님의 두가지 질문에 대해 정리해보았습니다 !

1. in,out은 확장에 용이해야 하는가?
현재는 커맨드 라인으로 입력,출력을 하고 있지만 향후에는(비록 계획이 없을지라도) CLI,웹 등으로 확장 가능성을 생각해보았을 때는 확장에 용이한 방식으로 하는 것이 맞다고 생각합니다.

2. CommandLine 에서 in,out 에 의존하여야 하는가?
이 부분도 위와 같은 맥락인데 만약 입출력 방식이 변경되어서 다른 구현체를 사용한다고 하면 스프링 빈만 변경해주면 되기 때문에 확장에 있어서 용이하다고 생각합니다.

만약 CommandLine이 i,o 인터페이스에 의존적이지 않다면 구현 클래스에 의존하게 되므로 i,o에 대한 요구사항이나 기능이 바뀔 때마다 코드의 많은 수정이 있을 것으로 예상됩니다 !

2023-06-30 19:52 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
0132cd0781ae2ed7057d365fbc53b77b4a2f7695
de00846ba10912b96e6e94bdbf7cea416944360c
370f750c3b07933d3c35cade51e6197d9bbf1c29
dbaa83ab546245ea5898ead7ae54e53752c4d098
추가로 해당 커밋들에서 input, ouput 간의 커플링 문제를 개선하는 방식으로 리팩토링 하였습니다 !

2023-07-01 03:59 UTC, HyoungUkJJang reviewed
세한님 리뷰 반영이 다 된 것 같아서 추가 코멘트 남겼습니다 ~ 
PR 리뷰가 다 완료된 경우에 어떻게 반영했는지, 추가 구현사항은 어떻게 되는지, + 궁금한 점을 다시 코멘트로 정리해 주시면서 슬랙에 노티 한번 해주시면 좋을 것 같아요 ! 👍🏻

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +import java.io.*;
import 정리가 안된 것 같습니당 

아마 인텔리제이에서 특정 개수가 넘어가면 자동으로 와일드 카드로 변경하게 되는데요 아래 글을 참조해서 설정을 변경하시면 좋을 것 같습니다.
[와일드카드 설정 변경하기](https://velog.io/@eora21/Intellij%EC%97%90%EC%84%9C-%EC%99%80%EC%9D%BC%EB%93%9C%EC%B9%B4%EB%93%9C-%EC%9E%84%ED%8F%AC%ED%8A%B8-%EC%84%A4%EC%A0%95-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0)

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +
개행처리는 한번만 해주시면 좋을 것 같습니당

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +import java.util.*;
import !

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +        return voucehrList;
코드의 길이가 좀 있을 때 return 전에는 개행처리를 한번 해주시면 좋을 것 같아요

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +        }
사용자 관점에서 비어있는 경우 예외를 터트리는게 맞을까요?

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +    }
VoucherType의 책임으로 만들어줄 수 있을 것 같아요

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/io/Console.java
> +
개행처리 맞춰주세요 :) !

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/exception/NoSuchVoucherType.java
> +public class NoSuchVoucherType extends RuntimeException {
네이밍으로 보았을 때 예외처럼 보이지 않을 것 같아요 :) 세한님의 생각은 어떠신가요 ~?

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/exception/NoSuchOptionValue.java
> +public class NoSuchOptionValue extends RuntimeException {
네이밍으로 보았을 때 예외처럼 보이지 않을 것 같아요 :) 세한님의 생각은 어떠신가요 ~?

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    private static final Logger log = LoggerFactory.getLogger(CommandLine.class);
상수는 필드 가장 위에 배치하는건 어떻게 생각하시나요? 상수, 필드의 구분감을 위해 개행처리도 한번 해주시면 좋을 것 같아요

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    PERCENT("PercentDiscountVoucher");
상수의 이름 만으로도 타입을 구분할 수 있을 것 같은데 FixedAmountVoucher, PercentDiscountVoucher의 값을 만드신 이유가 있으실까요?

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +package prgms.spring_week1.domain.customer.repository.impl;
impl 패키지를 따로 만드신 이유가 있으실까용?

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +        }
예외가 발생한 이후에 null을 반환해도 괜찮을까요?

2023-07-01 03:59 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
slelectVoucherType이 많은 일을 하고 있는 것 같은데 세한님 의견은 어떠신가요?

2023-07-01 09:29 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +import java.io.*;
5d5d92b6d965e31b2ad192d3c3bb243328cf232d 커밋 피드백 반영
- 넵 공유해주신 자료 보고 와일드 카드 설정 변경하였습니다 !

2023-07-01 09:31 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +
6cddd57f8a52c70b04107531583e98ae6ecb65ef 커밋 피드백 반영
- 개행처리 수정하였습니다 !
- 앞으로도 개행 처리에 대해 좀 더 신경쓰도록 하겠습니다.

2023-07-01 09:32 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +import java.util.*;
5d5d92b6d965e31b2ad192d3c3bb243328cf232d 커밋 피드백 반영
- 넵 반영하였습니다 !

2023-07-01 09:32 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +        return voucehrList;
e2368362d518a2607a82a00c9dae2c1b5cd304ea 커밋 피드백 반영
- 해당 코드 외에도 수정 사항이 없는 지 확인하고 반영하였습니다 !

2023-07-01 09:36 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +        }
c6227d274ae00d7247a30e9527980d3a647a76a1 커밋 피드백 반영
- 형욱 멘토님의 리뷰를 보고 생각을 해보니, 단순히 비어있는 리스트를 조회하는 게 예외 사항이 되지 않는 것 같습니다 !
- 해당 예외 클래스는 제거하였습니다 !

2023-07-01 09:41 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +package prgms.spring_week1.domain.customer.repository.impl;
impl 패키지를 따로 만든 이유는 크게 두가지가 있습니다.

1. 데브코스 이전에 스프링 강의를 들었을 때 강사님이 impl 패키지를 따로 만드셔서 모방(?) 적으로 만들었습니다.

2. 그리고 현재는 구현체가 하나뿐이지만 추후 확장 가능성을 고려해보았을 때 구현체들이 추상체들과 같은 패키지에 있으면 디렉토리 가독성이 떨어질 것이라고 판단해서 해당 디렉토리를 만들었습니다.

만약 추후 확장 가능성을 고려하지 않고 Csv 저장소 하나만 있다고 가정해보았을 때는 굳이 impl 패키지가 없어도 된다고 생각합니다 !

하지만 지금은 배우는 단계이기에 확장 가능성이 있다고 가정하고 구현체 패키지를 따로 만들어보았습니다.

2023-07-01 09:55 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +        }
5738c3ea354d732b90827e0fbc8c984fb194eb08
63226b9b6ae6b2508330894ba1ed0f6675cab0ab
c5352dda553a44562f194dc27147f6c12982b703 
커밋 피드백 반영

- null을 리턴하게 된다면 npe의 위험이 있다는 것을 알게되었습니다.
- 해당 코드 수정하였으며 언급해주신 코드 외에 null을 반환하던 코드도 수정하였습니다 !

2023-07-01 09:58 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
93236bba65c53f2f6d5c79c4d8c1cce2ac77dd7b 커밋 피드백 반영
- 해당 메소드를 검토해본 결과 "select" 라는 이름에 맞지 않게 "insert"의 기능도 수행하고 있는 문제를 발견하였습니다.
- 해당 메소드에서는 select 의 기능만 수행하고 insert 기능들은 따로 빼주었습니다 !

2023-07-01 10:00 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +    }
dc5231d87e4fb3950f4c6c2378e513db25b19d95 커밋 피드백 반영
- 바우처 타입에서 조회하도록 변경하였습니다!

2023-07-01 10:00 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Console.java
> +
a9e5673ee0040e350aeada487ac609213e53accc 커밋 피드백 반영
- 넵 수정하였습니다 !

2023-07-01 10:01 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/exception/NoSuchVoucherType.java
> +public class NoSuchVoucherType extends RuntimeException {
a9e5673ee0040e350aeada487ac609213e53accc 커밋 피드백 반영
- 커스텀 예외 이름을 붙이는 데 조금 미숙했던 것 같습니다.
- Exception 을 붙여주었습니다 !

2023-07-01 10:02 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/exception/NoSuchOptionValue.java
> +public class NoSuchOptionValue extends RuntimeException {
a9e5673ee0040e350aeada487ac609213e53accc 커밋 피드백 반영

- 커스텀 예외 이름을 붙이는 데 조금 미숙했던 것 같습니다.
- Exception 을 붙여주었습니다 !

2023-07-01 10:02 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    private static final Logger log = LoggerFactory.getLogger(CommandLine.class);
c96ae88b47f702fc6191d99f3fb6b33ef861daf9 커밋 피드백 반영
- 말씀해주신 대로 수정하였습니다 !

2023-07-01 10:04 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    PERCENT("PercentDiscountVoucher");
사용자로부터 입력을 받으면 해당 value 값으로 매칭이 되도록 하였습니다.
혹시 바람직 하지 못한 방법일까요 ?

2023-07-01 23:15 UTC, 2jie0516 commented
멘토님들이 주신 리뷰를 보면서 추가적으로 리팩토링을 진행하였습니다 !

추가적으로 구현한 기능은 없으며 커밋 변경 사항은 해당 리뷰에 남겨놓았습니다 !

이번 미션을 진행하면서 몇가지 궁금증이 생겨서 질문 남겨드립니다.

1.
기존에 null을 반환하던 몇몇 메소드들이 있어서 리팩토링을 진행하였습니다.

리팩토링을 진행하면서 한 블로그(https://dundung.tistory.com/187)를 보았습니다.

해당 블로그는 Optinal을 사용하라고 되어있지만 여러 이유로 Optional을 사용하지 않았습니다.

Optinal을 사용하지 않은 이유는

1. 지금 반환해주는 값만으로 충분히 validation이 가능하다.
2. 오히려 Optional을 사용하게 되면 empty()를 검증하는 추가 로직이 들어간다.

해당 이유로 빈 String이나 유효하지 않은 정수값을 반환해주었는데 바람직한 선택이었을까요 ?

2. 
직관적인 예외 처리를 위해 커스텀 예외를 구현하였습니다.
예를 들어 선택한 옵션값이 없거나 바우처 리스트가 비어있을 경우를 구현했는데 자바 기본 예외를 사용하는 것도 괜찮았을까요 ?
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/ 를 참고했습니다.

2023-07-01 23:23 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
e9e85855ebf66f740bed6d79a42a102d780654c1 c77050b2e20db3be0a9ff6405f7dee769aa7bd5b 0a21136d2c61c0d01efab345da684770a02893dc ac9d0e0fde93638ce7601def46f6a5ab0a1053c8 a71f59abcb323785ccbf31d4cd381ef5aa825883
커밋 피드백 반영

- 어제 멘토님이 해주신 말씀을 듣고 Input,Output을 인터페이스에서 클래스로 변경하였습니다.

- 추후 확장 가능성을 고려해 입출력을 한 클래스에 넣는 것이 아닌 Input,Output 클래스로 분류하였습니다.

- 이렇게 함으로써 추후 입력 혹은 출력 형식이 변경되어도 유연하게 변경할 수 있을 거라고 생각됩니다 !

2023-07-02 10:34 UTC, HyoungUkJJang reviewed
세한님 추가 코멘트 남겼습니다 :) 
전반적으로 매직넘버가 많이 보이는데 최대한 지양해보시면 좋을 것 같아요 👍🏻🙂

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    PERCENT("PercentDiscountVoucher");
@2jie0516 

사용자 관점에서 fixed, percent만 입력할 수 있게 하는게 오히려 간편하지 않을까요? 
fixed, percent만 해도 괜찮으시다면 enum의 name() 메서드도 한번 고려해보시면 좋을 것 같습니다.

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    }
1. orElseThrow()를 고려해보시면 이 두 메서드를 적절히 가져가면서 코드의 길이도 줄일 수 있을 것 같아요
2. 예외를 던질 때 아무런 메시지가 없는게 아쉬운 것 같아요

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +
두 줄 개행 맞춰주시면 좋을 것 같습니당 :)

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
-1로 할당을 한 후 반복을 도는게 조금은 어색해 보이네요 다른 방법은 없을까요?

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/config/AppConfiguration.java
> +}
어떤 Configuration 일까요? 사용하지 않는다면 지워주시는게 좋을 것 같습니다 ~!

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/io/Input.java
> +public class Input {
전체적으로 Input 클래스에서 예외가 발생할 경우 리턴되는 값들이 정확히 어떤 의미를 가지는지 모르겠어요
매직넘버를 최대한 없애보는건 어떨까요?

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    private boolean IS_RUNNING = true;
IS_RUNNING이 여기 있어야 하는 이유는 뭘까요? 그리고 사용하는 느낌이 상수는 아닌 것 같아요

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +        return voucehrList;
```java
return voucherList.values().stream()
       .toList();
```

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/io/Input.java
> +    }
동작하는 코드는 결과적으로 완전히 동일한데 범용적으로 사용할 순 없을까요?

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/io/Output.java
> +public class Output {
사용자에게 보여줘야 할 값이 생길 때 마다 메서드가 불어나는게 맞을지 의문이 들어요 유지보수 측면에서 재사용성을 고려하는것도 나쁘지 않다고 생각합니다.
차라리 사용자에게 보여질 메시지들을 따로 관리하는 클래스가 별도로 존재하는건 어떻게 생각하시나요?

2023-07-02 10:34 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/io/Output.java
> +    }
View의 역할을 하는 곳에서 도메인을 의존해도 되는가? 의문이 조금 드는 것 같아요

2023-07-02 14:58 UTC, Jo-GyuHyeon commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
비슷한 커밋들은 스쿼시로 합쳐버리는게 좋을것 같아요.
관련 피드백은 반영하셨기에 resovle 처리 할게요.

추가적인 리뷰가 필요해서 새로운 코멘트로 처리 할게요

2023-07-02 15:56 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    PERCENT("PercentDiscountVoucher");
b989505fe9892e2085be0dfe24cf90e43646fc4e 커밋 피드백 반영
- 넵 멘토님 말씀대로 피드백 반영하였습니다 !
- 다만 name 메소드를 알아보았는데 적절한 활용 방법이 생각나지 않아 일단은 Fixed , Percent 로 입력을 받을 수 있게 하였습니다 !

2023-07-02 15:57 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    }
a163702851a104bc409f4a31797598e2a7ecf914 0978e3e7df98f94e9e6d2381c81a4ce44812a77a
- 넵 피드백 반영하였습니다 !

2023-07-02 15:58 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +
ce383104e1e9c25ebd4af9747043b1b595eed696 피드백 반영
- 앗 .. 수정하였습니다 !

2023-07-02 15:59 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
6543a6257442103750e2583e1bcd190416dda2b8 커밋 피드백 반영
- 피드백 반영하였습니다 !
- 어떻게 하면 처음부터 while 문을 돌릴 수 있을까 고민하였는데 중간에 입력만을 담당하는 함수를 만들어서 해결하였습니다 !

2023-07-02 15:59 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/config/AppConfiguration.java
> +}
71850fd7dea80ab78a93a5537e5b63d338a46097 커밋 피드백 반영
- 넵 제거하였습니다 !

2023-07-02 16:01 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Input.java
> +public class Input {
051f89679fd915c8edce405d22253b2f37b25a1f 커밋 피드백 반영
- Buffered Reader 를 사용하면 Checked Exception을 해줘야하기 때문에 예외발생 시 return 값에 처리가 곤란해져서 일단 scanner 로 받도록 하였습니다 !

2023-07-02 16:02 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    private boolean IS_RUNNING = true;
5bd00e7407521b03759d75b989794aa4d373835e 커밋 피드백 반영
- 해당 상수는 입력이 끝나고 프로그램이 종료되지 않도록 while문을 위한 상수입니다 !
- 멘토님의 피드백을 듣고 위치가 적절하지 않다고 판단되어서 함수 안으로 넣어주었습니다.

2023-07-02 16:03 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepository.java
> +        return voucehrList;
66fdef7a9e6fc4c1339d91b6ca2f4e9993c83635 커밋 피드백 반영
- 객체지향 생활체조 5번 .. ! 꼭 지키겠습니다 !!

2023-07-02 16:04 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Input.java
> +    }
1b69e402f4adc797f394696fb79706af19426515 커밋 피드백 반영
- input 메소드 하나로 통일하였습니다 !
- 저도 해당 부분에서는 고민이 많았는데 앞으로는 통일하는 방식으로 진행하겠습니다

2023-07-02 16:05 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Output.java
> +public class Output {
19eeb93c525907b6026a0205860dd51e16cc7b59 c2fbfd871edb13a17a2704bc21b9f53896d895c7 커밋 피드백 반영
- 메세지를 관리하는 클래스와 ouput 에서 단순히 출력을 담당하는 메소드들을 하나로 통합하였습니다 !

2023-07-02 16:07 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Output.java
> +    }
6cfa99fba2d77337ded2ec9141b9d5d07fdbcb6e 커밋 피드백 반영
- 출력 클래스가 아닌 CommandLine에서 바우처를 분류하도록 하였습니다 !

2023-07-02 16:09 UTC, 2jie0516 commented
리뷰에 남겨주신 피드백 사항들 모두 반영 완료하였습니다 !

게더타운에서 질문사항들에 구두로 얘기하면 좋겠다고 하셨는데, 가능하신 시간과 날짜 알려주시면 감사하겠습니다 !

2023-07-02 18:04 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    PERCENT("PercentDiscountVoucher");
voucherType이 enum 의 name 과 동일하다면, voucherType 필드가 필요 할까요? enum 의 name() 메서드가 어떤 결과를 보여주는지 학습하시면 좋을것 같아요.

2023-07-02 18:06 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    }
커밋 스쿼시 기능을 이용하면 좋을것 같아요.
해당 피드백은 반영되어 있으나, 추가적으로 코멘트를 남기게 될것 같아요.

2023-07-02 18:08 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
커밋메시지를 더 구체적으로 작성 해주시면 좋을것 같아요.

2023-07-03 13:07 UTC, HyoungUkJJang reviewed
추가 코멘트 남겼습니다 세한님 한번 더 참고해주세요 🙂

2023-07-03 13:07 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/io/message/ConsoleOutputMessage.java
> +public class ConsoleOutputMessage {
유틸리티 성격을 지니고 있으니 private 생성자를 통해 외부에서 생성을 못하도록 막아주면 어떨까요?

2023-07-03 13:07 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        boolean IS_RUNNING = true;
사용하는 용도가 상수 느낌이 아닌 것 같아요 상수란 무엇일까요?

2023-07-03 13:07 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
전체적인 설계에 대해서 이야기를 해보는것도 좋겠지만 클린코드 3장에 내려가기 규칙이라는 내용이 나오는데 정리된 글을 한번 읽어보면 어떨까요?

[클린코드 3장 찍먹하러가기](https://data-make.tistory.com/633)

2023-07-03 16:36 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/CommandLine.java
> +    private final Output output;
넵 알겠습니다 !

2023-07-03 16:36 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +    private final Input input;
넵 커밋 단위에도 신경 쓰도록 하겠습니다 !

2023-07-03 16:37 UTC, 2jie0516 commented on spring_week1/src/main/java/prgms/spring_week1/domain/voucher/service/validation/impl/PercentDiscountValidation.java
> +public class PercentDiscountValidation implements DiscountValueValidation {
넵 알겠습니다 !

2023-07-03 16:38 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    PERCENT("PercentDiscountVoucher");
@Jo-GyuHyeon 넵 해당 부분 학습 진행 후 리팩토링 진행하겠습니다 !

2023-07-03 16:39 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    }
@Jo-GyuHyeon 넵 알겠습니다 !

2023-07-03 16:40 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
@Jo-GyuHyeon 넵 커밋 메세지에도 신경 쓰도록 하겠습니다 !

2023-07-04 13:33 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +    private final String CsvFilePath;
4c563ab6e9de0f1811625ee0022b73e3b5384091 커밋 피드백 반영
- 앞 글자를 소문자로 변경하였습니다 !

2023-07-04 13:34 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +    public List<BlackConsumer> blackConsumerList() {
06fac0beabab5f17119808b95373519dfa94a878 커밋 피드백 반영
- 카멜 케이스로 작성 , 동사/전치사로 시작한다는 점을 참고하여 네이밍을 변경하였습니다 !

2023-07-04 13:35 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    PERCENT("Percent");
8650638859b656f5a9cb4d3a7feca692be7a9da2 커밋 피드백 반영
- voucherType 필드를 지우고 name 메소드를 적용하였습니다 !

2023-07-04 13:37 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/model/type/VoucherType.java
> +    }
635d27b42d1b4ffa49dc03bae09353e0b4a0e27e 커밋 피드백 반영
- 넵 해당 함수 두개를 하나로 통합하였습니다.
- 객체지향 생활 체조 5번 "One Dot Per Line" 에 대해 추가로 학습하고 올바른 상황에 적용할 수 있도록 노력하겠습니다 !

2023-07-04 13:38 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +    }
7b867b3f2ffaac18e3c2a93bc3ea1b5a19eaaa28 커밋 피드백 반영
- 파라미터 변수명을 수정하였습니다 !

2023-07-04 13:39 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Input.java
> +    private static final Logger log = LoggerFactory.getLogger(Input.class);
b0ca10047fc9f747bbf719b2f3f137be3dc60751 커밋 피드백 반영
- 사용하지 않는 로그 메소드를 제거하였습니다 !

2023-07-04 13:42 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Output.java
> +    }
87fadad1a7f7b731bc1af712c928bfcae7e6999a 커밋 피드백 반영
- Output 클래스에서 바우처 출력을 할 때 할인 정보만 넘겨주는 방식으로 변경하였습니다 !

2023-07-04 13:43 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/menu/Menu.java
> +public enum Menu {
0959e64c7ef1496b46d37fd4db195440b5f6f43c 커밋 피드백 반영
- 넵 VoucherType과 동일하게 name 메소드를 적용하고 필드를 제거하였습니다.

2023-07-04 13:44 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/message/ConsoleOutputMessage.java
> +public class ConsoleOutputMessage {
21bf905830290e362105726958f26e67a9a516db 커밋 피드백 반영
- 넵 private 생성자를 만들었으며 , final 키워드도 붙여주었습니다 !
- 앞으로 상수 메세지 관리 클래스를 만들 때 해당 방식으로 만들겠습니다.

2023-07-04 13:45 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        boolean IS_RUNNING = true;
796ff66d2bf9cd29e0d1263643db2d675aceef65 커밋 피드백 반영
- 초반에 상수로 만들었다가 변수로 변경하여서 네이밍에서 실수를 한 것 같습니다
- isRunning 으로 변경하였습니다 !

2023-07-04 13:48 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
2dca67cba6feb5fd55b014cf00f8d2ec72944e14 커밋 피드백 반영
- "내려가기" 규칙에 맞게 코드를 재정렬 하였습니다.
- 읽기 좋은 코드를 위해서는 아래 방향으로 추상화 단계가 낮아져야 하며 , TO 문단 읽듯이 읽혀져야 한다는 것을 알게되었습니다.

2023-07-04 13:57 UTC, 2jie0516 commented
멘토님들의 피드백을 수용하여 리팩토링 진행하였습니다 !

추가 및 수정한 기능은 다음과 같습니다

1. 주요 로직에 대한 테스트 코드 작성(입력/출력/조회/추가)

2. 바우처 조회 시에 기존엔 CommandLine에서 직접 Repository에 접근하였는데,리팩토링을 통하여 Service 클래스를 통해서 조회하도록 하였습니다.

좋은 피드백 남겨주셔서 감사드립니다 !

2023-07-05 20:23 UTC, Jo-GyuHyeon requested changes

2023-07-06 11:09 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Output.java
> +public class Output {
3d9265284bca88886e8720959395da2a61f76f08 커밋 피드백 반영
- 어제 온라인 코드 리뷰에서 Ouput 클래스를 빈으로 등록해도 큰 이점이 없다는 것을 알았습니다.
- util 클래스는 빈이 아닌 생성자로 인스턴스를 생성하는 게 더 낫다고 판단하여서 코드 수정하였습니다 !

커밋을 push 할 때 commit 이름을 잘못 적었습니다 .. 
커밋 이름과 무관하게 Output , Input 빈 설정을 제거하는 코드를 포함하고 있습니다 !

2023-07-06 11:09 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +    }
25ffba08b8b11b472091ef88c82364b5b6e28e16 커밋 피드백 반영
- 해당 코드에 대해 다시 생각해본 결과 어차피 Fixed 와 Percent 로직은 나뉘어져 있어서 굳이 외부에서 타입을 주입 받을 필요가 없다고 생각되었습니다 .
- 바우처를 추가할 때 내부에서 uuid 와 타입을 받을 수 있도록 하였습니다 !

2023-07-06 11:12 UTC, 2jie0516 commented
피드백 해주신 대로 코드 반영 완료하였습니다 !

이번에 새로 적용한 사항은 다음과 같습니다.
1. CommandLineRunner 적용
    - 메인 클래스에서 구현체에 대한 의존성을 줄이기 위해 적용하였습니다.
    - a8554e15e1bffed9a4fedb89ae65de670c9469bc
2. 인터페이스에 @Repository 어노테이션을 붙여서 구현체에 대한 의존성을 줄였습니다. 
    - 4be13aa1cc050b299e7700b8f5dd4383d913acad
 3. Readme 파일에 클래스 구성도 및 각 객체의 역할을 첨부했습니다.

2023-07-07 05:16 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 남겨두었어요.
비지니스 로직을 다루는 것과, 분기 (라우팅) 하는 역활 책임을 한번 고민 해보시면 좋을것 같아요.
고생하셨어요. 🙇 
(간단히 피드백 반영 해볼까요?)

2023-07-07 05:16 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
바우처 생성 로직이 여기서 결정 되어야 할까요?

추가)
너무 잘개 나뉘지 않았나 고민 해보시면 좋을것 같아요.
discountPercent, discountAmount 의 범위의 책임이 어디가 좋을지 고민 해보시면 좋을것 같아요.

2023-07-09 07:24 UTC, 2jie0516 commented
멘토님들의 주신 피드백을 보고 리팩토링 진행 완료하였습니다 !

변경 사항은 다음과 같습니다.

**입출력**
- 원래 output에서 모든 출력을 담당하였는데 이제는 input 클래스에서 입력값에 대한 안내문을 출력합니다.

**switch 문**
- switch 를 이용한 enum 열거형 분리 처리를 최소화하였습니다
- switch 문에서 default를 제거하고 switch 이전에 null 에 대한 체크를 진행하도록 하였습니다.

**바우처 등록 예외**
- 만약 바우처 등록 시에 예외가 발생한다면 통합적으로 예외를 catch 하여서 프로그램이 처음부터 실행되도록 하였습니다.
- 더 이상 바우처타입의 static 함수에서 입력값 validation을 진행하지 않습니다.

2023-07-09 07:27 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +                default -> output.outputMessage(ConsoleOutputMessage.INVALID_MENU_MESSAGE);
b6e743fa1036102c9c920ed76de6dac1406bcdf0 커밋 피드백 반영
- 넵 switch에서 default을 사용할 시 , 컴파일러의 도움을 받을 수 없고 이는 곧 의도치 않은 실행으로 이어질 수 있다는 것을 알게되었습니다 !
- switch 이전에 null 에 대한 검증을 하고 switch 분기처리를 하도록 하였습니다.

2023-07-09 07:36 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        }
8eb46c7f121ad0a7b5830959645facd9a81e5960 커밋 피드백 반영
- 넵 원래는 바우처 종류에 따라 함수를 다르게 하였지만 리팩토링 과정을 통해 통합하였습니다.
- 이 과정에서 할인 정보값이 100이하인 바우처는 할인율 바우처로 분류하여 퍼센트 값으로 분류하였습니다 !

2023-07-09 07:37 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +                case CREATE -> selectVoucherType();
- 넵 해당 메소드명을 createVoucher 로 변경하였습니다 !

2023-07-09 07:40 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +            switch (findMenuName(selectOption)) {
9c9dc91e9efd712d4925314f554bb22f033d3d1c 커밋 피드백 반영
- 넵 input에서 입력값을 받은 체 그대로 반환하는 것은 의미가 없다고 생각하여서 , input 클래스에서 메뉴타입을 찾고 반환하는 식으로 변경하였습니다 !

2023-07-09 07:43 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
9c9dc91e9efd712d4925314f554bb22f033d3d1c 커밋 피드백 반영
- 넵 어제 새벽에 코드 리뷰를 통해 불필요한 코드 제거 및 메소드 통합을 진행하였습니다.
- 또한 바우처 등록 시에 생기는 예외들을 한 곳에서 catch 해줌으로써 프로그램이 다시 실행되도록 하였습니다.

2023-07-09 07:51 UTC, Jo-GyuHyeon reviewed
마무리가 되어가는것 같아요.
간단하게 리뷰 남겼어요.

2023-07-09 07:51 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/io/Output.java
> +        }
분기 처리가 필요 할까요?? 불필요해 보여요

2023-07-09 07:51 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        Voucher voucher = new Voucher(voucherType, discountAmount);
도메인 모델의 책임으로 위임할 수 있을것 같아요.
비지니스의 인자 조건에 대한 규칙으로 이해 할 수 있지만, 바우처 타입이 증가 되게 되면 어떤 일이 생길까요?

2023-07-09 07:51 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +            return blackConsumerList;
전체 문자열을 받는것과, BlackConsumer 인스턴스화 하는 부분을 나눌수 있을까요? (메서드 분리 x)

2023-07-09 09:44 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/io/Output.java
> +        }
fbd68009fe5e46fc208e544a142c5921c5d3ee34 커밋 피드백 적용
- 넵 바우처 정보를 출력할 때 '할인정보' 로 일괄 출력되도록 하였습니다 !

2023-07-09 09:46 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/service/VoucherService.java
> +        Voucher voucher = new Voucher(voucherType, discountAmount);
253663e763b99ad5c28d415cfdc7acaeef9a7066 커밋 피드백 적용
- 해당 부분도 고민해보았는데 프로그램에서는 0 이상의 수만 validation 을 진행하고 퍼센트나 할인 금액에 대해서는 프로그램에서 직접 검증하는 것이 아닌, 바우처 등록 안내 메세지를 구체화하는 방식으로 리팩토링 하였습니다 !

2023-07-09 09:49 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +            return blackConsumerList;
86399a83c8b89f6dfd41df6f644dddbcd6c1ca2d 커밋 피드백 적용
- try 내에 너무 많은 코드가 있다고 생각을 하여 Buffered Reader에 해당하는 코드만 감싸주었습니다.
- 나머지 코드는 buffered Reader 에서 받아온 리스트를 통하여 BlackConsumer 객체를 인스턴스화 해주었습니다 !

2023-07-09 09:51 UTC, 2jie0516 commented
피드백 참고하여 리팩토링 진행하였습니다 !

피드백 반영 사항들은 리뷰 코멘트에 커밋 id로 남겨드렸습니다.

리뷰 남겨주셔서 감사드립니다 !

2023-07-09 12:43 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/CsvRepository.java
> +            return blackConsumerList;
@2jie0516 분리를 함으로써 책임, 가독성, 필요 부분만 try catch 하셔서 좋은것 같아요.
`List<String> csvList = null;`  null 을 할당하는 부분이 아쉬운것 같아요. catch 에서 return 을 하기에 문제가 생기지 않을거라는것은 알아요.
고민 해보시면 좋을것 같아요.

(더 수정하지 않으셔도 되요)

2023-07-09 12:49 UTC, Jo-GyuHyeon approved these changes
고생하셨어요. 🙇 
일정상 심화는 생략 하는것을 추천드리고 싶어요.
2주차 과제도 화이팅 하시고 잘 하실거라 생각해요.
고생 많으셨어요.

2023-07-09 12:49 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
" 지금 반영하지 않으셔도 되요."

**내려가기 규칙 이라는걸 소개 해드리고 싶어요.**

코드는 위에서 아래로 이야기처럼 읽혀야 좋은것 같아요.
한 함수 다음에는 추상화 수준이 한 단계 낮아지는 것이 좋은것 같아요.

--- 
개행도 지워주시면 좋은것 같아요.

2023-07-09 12:59 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
형욱 멘토님이 내려가기 규칙 관련해서 피드백을 주셨었는데 이번에 미처 신경을 못 쓴 것 같습니다 ! 
2주차 과제에선 개행 문자 처리 , 내려가기 규칙 같은 규범들도 잘 준수해서 pr 올리겠습니다.

1주차 과제에서 좋은 리뷰 많이 남겨주셔서 감사합니다 !!

2023-07-09 13:00 UTC, merged