[4기 - 박혜성] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #670
Opened 2023-06-23 17:09 UTC by hseong3243

## 📌 과제 설명
- 바우처 관리 애플리케이션을 작성하였습니다. 현재 심화 부분을 제외한 기본 사항 부분의 구현을 완료하였다고 생각되어 첫번째 PR을 제출합니다!
- `create`, `list`, `help`, `exit` 입력에 따라 기능을 제공하는 콘솔 애플리케이션을 구현하였습니다.
```bash
=== Voucher Program ===
Type exit to exit the program.
Type create to create a new voucher.
Type list to list all vouchers.
Type help to list command set.
```
- `create`
  ```bash
   create
  1. [fixed | percent]: fixed
  2. [amount]: 10
  Created new voucher. VoucherID: f4903dfe-00b3-43c4-a3eb-17a001d410b3
  ```
  - 바우처의 타입을 선택하고 할인량(률)을 입력하면 바우처가 생성됩니다.
- `list`
  ```bash
   list
  
  VoucherID: 53a4dbad-5cef-4908-a3c5-0964ab44f558, discount: 10%
  VoucherID: f4903dfe-00b3-43c4-a3eb-17a001d410b3, discount: 10$
  ```
  - 생성한 바우처 목록을 출력합니다.
- `help`
  - 명령어 목록을 출력합니다.
- `exit`
  - 콘솔 애플리케이션을 종료합니다.

- 예외 처리를 수행하는 지점들에 대해 warn 레벨 로그 메시지를 추가하였습니다.
- logback-spring.xml을 추가하여 로그 레벨에 따라(info, error) 서로 다른 로그 파일을 생성하여 기록되도록 하였습니다.

## 👩‍💻 요구 사항과 구현 내용 
- SpringBoot Part1 Weekly Mission(~11/11)

  (기본) **바우처 관리 애플리케이션**

    - [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
    - [x]  바우처 관리 Command-line Application을 만들어본다.
        - 참고: https://dzone.com/articles/interactive-console-applications-in-java
        - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
        - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

       ```bash
       === Voucher Program ===
       Type **exit** to exit the program.
       Type **create** to create a new voucher.
       Type **list** to list all vouchers.
       ```

        - [x]  create / list 커맨드를 지원한다.
            - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
            - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
            - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
    - [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
    - [x]  실행가능한 `jar` 파일을 생성한다.
      - `gradle bootjar`을 통해 실행가능한 jar 파일이 생성되는 것을 확인하였습니다.
      - 현재 `gradle build`시에 모든 테스트가 실패하는 문제가 있습니다. 인텔리제이 테스트 시에는 성공하고 있으나 gradle 테스트시에 실패하는 것을 확인하였습니다. 해당 부분에 대해서 해결할 예정입니다.

  (심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

    - [ ]  메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
        - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
    - [ ]  고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
    - [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ PR 포인트 & 궁금한 점 
- 적절한 지점에 로그를 남겼는지 궁금합니다! 현재 warn 로그의 경우 예외를 던지는 지점, try-catch로 예외 처리를 하는 지점에 대해서 남겼습니다. info 로그의 경우 콘솔 커맨드에 따라 작업이 시작, 종료되는 부분과 바우처가 새롭게 생성되는 지점에 남겼습니다.
- 현재 프로젝트의 설계가 적절한지 궁금합니다! 현재 사용자 입력을 받는 콘솔(ConsoleMenu) -> 서비스(VoucherService) -> 리포지토리(VoucherMemoryRepository) 3개의 계층으로 나누어져있습니다.
- 제가 enum을 적절하게 활용하고 있는지 궁금합니다! 현재 `VoucherType` enum은 바우처 인스턴스 생성, 입력된 할인값(률)에 대한 검증, 검증 실패시 적절한 에러 메시지 출력을 담당하고 있습니다. 올바르게 사용하고 있는걸까요?

2023-06-24 15:50 UTC, JoosungKwon reviewed
안녕하세요 혜성님! 과제하시느라 고생하셨습니다~!! 😄
정말 잘하신 것 같습니다 👍 시간이 남으시면 심화과제까지 해보셔도 좋을 것 같아요!
다음주 과제에서 요구사항이 변경되는 것으로 알고 있습니다. 한번 변경해보시면서 변경에 취약하지 않게 하려면 어떻게 하면 좋을지 생각해보시면 좋겠습니다! 화이팅입니다!! 💪

질문 주신 내용에 답변을 드리자면
> 적절한 지점에 로그를 남겼는지 궁금합니다! 현재 warn 로그의 경우 예외를 던지는 지점, try-catch로 예외 처리를 하는 지점에 대해서 남겼습니다. info 로그의 경우 콘솔 커맨드에 따라 작업이 시작, 종료되는 부분과 바우처가 새롭게 생성되는 지점에 남겼습니다.

- 그전에 혜성님은 어떤 목적을 가지고 로그를 남기고 계신가요? 또, 어떤 상황에서 로그를 확인해야 할까요?  로그는 많이 남기면 남길수록 좋다고 생각하시나요~?

- 사람마다 혹은 목적마다 다양한 전략을 택할 수 있다고 생각합니다! 로그에 목적에 대해 생각해보시고 현재 남긴 로그를 적절하게 활용하고 있는지 확인해 보시면 좋을 것 같습니다!!! 

- 참고해보시면 좋을 것 같습니다! (https://jojoldu.tistory.com/712) 

> 현재 프로젝트의 설계가 적절한지 궁금합니다! 현재 사용자 입력을 받는 콘솔(ConsoleMenu) -> 서비스(VoucherService) -> 리포지토리(VoucherMemoryRepository) 3개의 계층으로 나누어져있습니다.

- `ConsoleMenu`가 여러가지 일을 하고 있는 것 같아보이네요! 그 외에는 큰 문제는 없어보입니다!

> 제가 enum을 적절하게 활용하고 있는지 궁금합니다! 현재 VoucherType enum은 바우처 인스턴스 생성, 입력된 할인값(률)에 대한 검증, 검증 실패시 적절한 에러 메시지 출력을 담당하고 있습니다. 올바르게 사용하고 있는걸까요?

- 제가 보기엔 큰 문제는 없어보입니다! 잘 사용하신 것 같아요~!

2023-06-24 15:50 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/request/VoucherCreateRequest.java
> +    private int amount;
이곳에는 `final` 이 없는 이유가 무엇인가요~? 😢

2023-06-24 15:50 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/service/VoucherService.java
> +    private final static Logger log = LoggerFactory.getLogger(VoucherService.class);
일반적으로 `static`이 `final` 보다 [앞에 옵니다](https://johngrib.github.io/wiki/java-modifier-order-with-jls-suggestion/)!

2023-06-24 15:50 UTC, JoosungKwon commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +@ExtendWith(MockitoExtension.class)
LGTM 👍

2023-06-24 15:50 UTC, JoosungKwon commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +
일부러 비워두신건가요?

2023-06-24 15:50 UTC, JoosungKwon commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +        //then
무엇을 테스트하려고 하신 거죠?

2023-06-24 15:50 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +    public void validateAmount(Integer amount) {
여기서만 `amount`를 `Integer`로 하신 이유가 있나요?

2023-06-24 15:50 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +            (amount) -> amount >= 0 && amount <= 100,
매개변수 명을 `percent`로 해도 되지 않나요?

2023-06-25 01:05 UTC, graygreat requested changes
안녕하세요 혜성님~~

코드 잘 작성해주셨군요 💯 
몇가지 리뷰 남겨뒀으니 확인 부탁드립니다!

추가로 궁금하신 점에 대해서 답변을 남겨보자면
> 적절한 지점에 로그를 남겼는지 궁금합니다! 현재 warn 로그의 경우 예외를 던지는 지점, try-catch로 예외 처리를 하는 지점에 대해서 남겼습니다. info 로그의 경우 콘솔 커맨드에 따라 작업이 시작, 종료되는 부분과 바우처가 새롭게 생성되는 지점에 남겼습니다.

제 생각에는 의미 없는 log가 많다고 생각이 들어요. 우리가 로그를 남겨서 어디다 쓰지? 어떤 사용자의 로그인지 어떻게 식별할 수 있지? 등,,, 로그의 사용성에 대해서 한번 생각해보시면 좋을 것 같아요.

> 현재 프로젝트의 설계가 적절한지 궁금합니다! 현재 사용자 입력을 받는 콘솔(ConsoleMenu) -> 서비스(VoucherService) -> 리포지토리(VoucherMemoryRepository) 3개의 계층으로 나누어져있습니다.

이와 같은 3계층으로 나누신 이유가 궁금합니다 :0

> 제가 enum을 적절하게 활용하고 있는지 궁금합니다! 현재 VoucherType enum은 바우처 인스턴스 생성, 입력된 할인값(률)에 대한 검증, 검증 실패시 적절한 에러 메시지 출력을 담당하고 있습니다. 올바르게 사용하고 있는걸까요?

이건 코드 자체에 리뷰를 남긴 것이 있으니 확인 부탁드려요 :)

2023-06-25 01:05 UTC, graygreat commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +@ExtendWith(MockitoExtension.class)
Mock을 사용한 테스트의 장단점은 무엇이 있을까요?
Mock 사용하신 이유가 궁금하네요 ㅎ

2023-06-25 16:17 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +    VoucherType(String value,
`VoucherType`에서 할인값 입력에 대한 검증 로직을 `VoucherValidationStrategy`인터페이스를 구현하는 로직이 담당하도록 분리하였습니다. 
기존에 검증 로직을 위한 인스턴스 변수인 `discountRange`와 `validAmountMesssage`를 제거하고 `VoucherValidationStrategy` 타입의 `voucherValidate`를 인스턴스 변수로 추가하였습니다. 
`VoucherType`의 인스턴스 변수가 여전히 3개이긴 하나 switch 분기를 타서 해결하는 것보다 `VoucherType`이 검증 요청을 받아서 필요한 로직을 실행하도록 하는게 좀 더 좋은 방법일 것이라 생각하여 이렇게 작업하였습니다. 아예 입력 값에 대한 검증 요청을 `VoucherType`으로부터 분리하는 편이 더 좋을까요?

2023-06-25 16:17 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
다형성이라는 이점을 가집니다.
`Voucher`를 상속받은 클래스 인스턴스들을 `Voucher` 타입의 변수로 다루면서 하나의 배열로 다루거나 하나의 메서드에서 이를 상속받은 여러 클래스의 인스턴스를 받을 수 있게 됩니다.
현재 제 프로젝트에서는 바우처를 저장하고 반환하는데 `Voucher` 타입의 변수로 객체를 받아서 다형성의 이점을 누리고 있습니다.

2023-06-25 16:17 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/ConsoleMenu.java
> +                String rawVoucherType = console.input("1. [fixed | percent]");
`consoleMenu`가 `console`에게 바우처 생성 정보를 요청하도록 변경하였습니다.

2023-06-25 16:17 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +            (amount) -> amount >= 0 && amount <= 100,
입력값에 대한 검증 로직에서 사용되는 변수 이름을 `percent`로 변경하였습니다.

2023-06-25 16:17 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/request/VoucherCreateRequest.java
> +    private int amount;
깜빡하고 놓친것 같습니다.😢
해당 필드에 `final`을 추가하였습니다.

2023-06-25 16:17 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +                            .append(" Current input: ")
에러 메시지를 별도의 유틸 클래스에서 관리하도록 변경하였습니다.
이 부분에 관하여 궁금한 것이 있습니다. 제 코드의 모든 곳에서 에러 메시지를 사용하는 경우 "Current input: "이라는 문자열을 붙여서 사용하고 있습니다. 이 경우 에러 메시지를 `String message = "Voucher type is invalid. Current input: "`처럼 관리해도 괜찮을까요?

2023-06-25 16:18 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/io/TextIoConsole.java
> +    public void printCommandSet() {
커맨드 설명에 대한 반복적인 로직을 `printCommand`라는 별도의 메서드로 추출하여 반복을 제거하였습니다.

2023-06-25 16:18 UTC, hseong3243 commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +    public void commandTypeCreate() {
test에 `@DisplayName`을 추가하였습니다.

2023-06-25 16:18 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
> +    public String toString() {
사용자에게 유의미한 문자열을 반환해주고자 사용하였습니다. `toString`은 주로 로그를 찍을 때 사용되고 객체의 모든 정보를 반환하여 사용자에게 보여주기 위한 용도로는 적절하지 않을 거라 생각했습니다. 따라서 `fullInfoString` 이라는 메서드를 별도의 정의하게 되었습니다.

2023-06-26 12:24 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/ConsoleCommandType.java
> +                    log.warn("Invalid command type: {}", sb);
바우처가 생성되거나 명령어 입력으로부터 특정 작업이 시작되면 이를 기록하기 위해 info 레벨이 적절하다 생각했습니다. 사용자의 입력값이 정해진 입력값의 범위를 벗어났을 때 레벨을 warn으로 정했습니다. 추후 파일 저장소를 추가하는 경우 파일 입출력 예외가 발생하여 정상적으로 기록이 되지 않는 경우를 error 레벨로 생각하고 있었습니다.

2023-06-26 12:25 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/ConsoleMenu.java
> +    public boolean runClient() {
`runClient()` 메서드에서 `commandType`에 따른 로직을 메서드 추출로 분리하였습니다.

2023-06-26 12:25 UTC, hseong3243 commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +
메서드가 정상적인 흐름으로 진행될 경우를 표현해야 하는데 부족함이 있었습니다.
정상 흐름대로 진행되는 경우 `then(console).should().inputInitialCommand();`와 같이 행위에 대한 검증을 수행하도록 변경하였습니다.

2023-06-26 12:25 UTC, hseong3243 commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +        //then
위에서 지적하신 부분과 동일하게 정상 흐름에 대한 테스트라는 것을 표현하는데 부족함이 있었습니다.
정상 흐름대로 로직이 실행되고 종료되는 경우를 검증하기 위한 `BDDMocito.then()`을 이용하여 행위에 대한 검증을 추가하였습니다.

2023-06-26 12:26 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +    public void validateAmount(Integer amount) {
해당 메서드의 파라미터 타입을 `Integer`에서 `int`로 변경하였습니다.
`TextIO`가 숫자에 대한 입력을 `Integer`로 반환하고 있었고 콘솔에 입력되자 마자 곧바로 검증이 이루어지기에 언박싱이 이루어지는 순간을 늦추면 좋지 않을까란 생각에 파라미터 타입을 `Integer`로 선언하였습니다.
그러나 지적해주신 부분을 고민해보니 특정 라이브러리에 대한 의존과 절차지향적인 코딩 방식이라 생각되고 올바르지 않았기에 파라미터 타입을 `int`로 변경하였습니다.

2023-06-26 12:27 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/ConsoleMenu.java
> +        log.info("Started Voucher Console Application.");
넵, 유념하겠습니다.

2023-06-26 15:32 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/ConsoleMenu.java
> +    private final static Logger log = LoggerFactory.getLogger(ConsoleMenu.class);
대문자로 변경하였습니다!

2023-06-26 15:52 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/ConsoleMenu.java
> +public class ConsoleMenu {
`ConsoleMenu`가 콘솔 애플리케이션 실행과 컨트롤러 2개의 역할을 한다는 문제점이 있었던 것 같습니다! 따라서 컨트롤러의 역할을 `VoucherController`로 별도로 분리하였습니다!

2023-06-28 14:58 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    private final UUID voucherId;
UUID를 사용에 대해서는 고민을 거치지 않고 사용하였습니다. 그러나 특별한 경우가 아니라면 장점보단 단점이 더 돋보인다는 것을 인지하였습니다. 좀 더 고민하면서 사용하도록 하겠습니다...!
`UUID`는 `auto increment`와 비교했을 때는 보안성이라는 장점을 가집니다. 사용자는 다른 엔터티가 가진 UUID에 대해서 쉽게 예측할 수 없습니다. 그러나 알아보기 어렵고 정렬이 되지 않는다는 단점을 가지고 있습니다.

2023-06-28 14:58 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/ConsoleMenu.java
> +    @EventListener(ApplicationReadyEvent.class)
`EventListener`는 이벤트에 기반한 애플리케이션을 만들 때 사용됩니다. 이를 사용하게 된 이유는 `ApplicationReadyEvent`를 사용하면 단순히 애플리케이션의 초기화가 종료된 다음에 실행된다는 것에서 콘솔 애플리케이션을 만드는데 적절할 것 같다고 생각했었습니다. `EventListener`에 대해선 좀 더 공부를 해보겠습니다!
해당 부분은 `CommandLineRunner`를 사용해서 구현하는 것으로 개선하였습니다!

2023-06-28 14:58 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/ConsoleMenu.java
> +public class ConsoleMenu {
컨트롤러 로직을 개별 컨트롤러로 분리시켰습니다!
콘솔을 실행하고 입력된 명령어에 따른 컨트롤러 로직을 가지고 있어 확장에도 문제가 있는 구조였다고 생각합니다!

2023-06-28 14:58 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/ConsoleCommandType.java
> +                            .append(input);
저 부분을 만들 때는 이렇게 하면 좀 더 가독성이 좋아지지 않을까란 생각을 하고 만들었습니다. 가독성에 대해서 유념하면서 진행하겠습니다!

2023-06-28 14:58 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +                            .append(" Current input: ")
관련된 메시지를 별도의 유틸 클래스에서 관리하도록 개선했습니다!

2023-06-28 14:58 UTC, hseong3243 commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +@ExtendWith(MockitoExtension.class)
mock을 사용하게 되면 대역을 통해서 계층별로 독립적인 테스트를 진행할 수 있다는 장점이 있습니다. 단점으로는 테스트 대상 객체의 코드가 변경되는 경우 테스트가 쉽게 깨져 버릴수 있다는 점, 복잡한 로직의 경우 읽기 어려운 복잡한 스터빙이 동반된다는 점이 있습니다.
제간 mock을 사용한 이유는 스터빙을 통해 계층별 단위 테스트를 진행하기 위해서였습니다. 다만, 강의를 수강하다보니 행위에 대한 테스트라는 개념에 대해서 부족했다고 느꼈습니다.
mock 을 비롯한 다른 대역과 테스트 방법에 대해서도 좀 더 공부해보겠습니다!

2023-06-28 14:59 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    public FixedAmountVoucher(UUID voucherId, VoucherCreateRequest request) {
계층간의 격리성이 저하되어 강하게 결합되니 서비스 계층의 단위 테스트를 진행하는데도 표현 계층의 객체를 필요로 하는 불필요한 과정을 거쳐 테스트를 진행하였습니다. 또한, 상위 레이어에 의존적인 객체를 만들다 보니 다른 필요한 곳에서 해당 객체를 사용하려 할 때도 쉽게 손댈수 없는 상황이 발생했습니다.
각 계층의 객체들이 독립적으로 동작할 수 있도록 개선을 진행했습니다. 계층형 아키텍처에 대해서는 계속해서 학습하겠습니다.

2023-06-28 14:59 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/VoucherType.java
> +    VoucherType(String value,
`VoucherType`으로부터 입력된 할인값에 대해 검증하는 로직과 인스턴스 변수를 제거했습니다.
다른 부분에 대해서도 객체 지향 설계원칙에 대해 유념하면서 개선을 진행했습니다.

2023-06-28 14:59 UTC, hseong3243 commented
## 추가 작업 사항
- [x] 바우처를 파일로 관리하는 파일 저장소를 추가하였습니다.
- [x] 블랙리스트 고객을 관리하는 도메인 customer를 추가하였습니다.
  - 블랙리스트 목록은 파일로 관리합니다.
  - 블랙리스트 목록을 읽어오기만 하는 기능을 가집니다.
- [x] 파일 저장소에 접근하기 위한 경로 정보는 `application.yml`을 통해 관리합니다. 
## 코드 리뷰 반영 사항
- 프로덕션 코드
  - 바우처
    - `Voucher`를 인터페이스에서 추상 클래스로 변경하였습니다. 바우처라는 하나의 분류에 인터페이스는 적절하지 않다 판단하였습니다.
    - `VoucherType`으로부터 할인값 검증에 관한 책임을 분리했습니다. 
  - 콘솔
    - 콘솔 애플리케이션 실행을 위해 기존에 `ApplicationReadyEvent`를 이용하던 것에서 `CommandLineRunner`를 구현하도록 변경했습니다.
    - `ConsoleMenu`로부터 컨트롤러 로직을 분리했습니다. `ConsoleMenu`는 입력한 명령어에 따라 적절한 컨트롤러에 실행을 요청합니다.
    - 너무 긴 메서드, 중복이 많은 코드를 개선하였습니다.
    - 코드 스타일을 개선했습니다.
  - 공통
    - 하위 레이어가 상위 레이어를 의존하지 않도록 변경했습니다. 느슨한 결합을 유지하여 원활한 단위 테스트를 수행할 수 있도록 했습니다.
    - 모든 상수를 대문자로 변경하였습니다.
    - 의미 있는 문자열을 적절한 유틸 클래스에서 관리하도록 변경하였습니다.
    - 문자열을 만드는데 좀 더 가독성이 높은 방향으로 수정하였습니다.
    - log를 남기는 지점을 개선했습니다.
- 테스트
  - 테스트 케이스에 `@DisplayName`을 추가하였습니다.
  - 성공이라는 행위에 검증을 수행하지 않던 테스트 케이스에 대하여 `then()`을 이용하여 검증을 수행하도록 변경하였습니다.

2023-06-28 23:34 UTC, graygreat commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +@ExtendWith(MockitoExtension.class)
> 강의를 수강하다보니 행위에 대한 테스트라는 개념에 대해서 부족했다고 느꼈습니다.

어떤 부분이 부족하다고 느꼈는지 공유해주실 수 있나요 ㅎㅎ

2023-06-28 23:35 UTC, graygreat commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +public interface Voucher {
저같은 경우는 설계의 목적에서는 인터페이스를 사용하고 확장의 목적에서는 추상 클래스를 사용한다고 생각하면서 개발하고 있어요.
이렇게 나름의 정의를 좀 세워두니 고민하는 시간이 줄어드는 것 같더라고요 ㅎ
혜성님도 자신만의 정의를 세워보시죠!

2023-06-29 05:01 UTC, hseong3243 commented on src/test/java/com/programmers/voucher/ConsoleMenuTest.java
> +@ExtendWith(MockitoExtension.class)
기존에는 테스트 케이스 작성시 반환값의 상태를 검증하는 테스트에 대해서만 작성을 했습니다.
```java
//given, when
...
Member findMember = memberService.findMember(...);
//then
assertThat(findMember.memberId).isEqualTo(memberId);
```
반환값이 존재하지 않는 테스트의 정상 흐름을 검증하는 경우 1. 반환값에 대한 테스트를 진행하기 어렵거나 2. 반환값이 없는 경우에 대한 검증을 따로 수행하지 않았습니다.
```java
//given
...
//when, then
memberService.deleteMember(...);
```
강의를 수강하며 단위 테스트 수행시 Stub을 이용해 상태에 대한 검증을 수행할 수 있고,  Mock을 이용해 행위에 대한 검증을 수행할 수 있음을 이해했습니다. 이에 따라 기존에 정상 흐름을 검증하고자 하는 테스트의 경우 다음과 같이 메서드 호출 여부에 대한 검증을 추가하였습니다.
```java
//given
...
//when
memberService.deleteMember(...);
//then
then(memberRepository).should().findMember(...);

2023-06-29 07:21 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
> +    private final UUID voucherId;
그 외에도 분산 환경이나 동시성을 고려해야 하는 상황에서도 사용을 고려해보아도 좋습니다!

참고: [UUID 사용이유](https://www.inflearn.com/questions/195134/uuid-%EC%82%AC%EC%9A%A9-%EC%9D%B4%EC%9C%A0)

2023-06-29 07:24 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/enumtype/ConsoleCommandType.java
> +                            .append(input);
정답은 없습니다~! 혜성님 만의 주관이 있다면 괜찮다고 생각합니다. 가독성 같은 부분은 팀원들과 합의를 이루면 됩니다~!

2023-06-29 07:35 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/enumtype/ConsoleCommandType.java
> +                    log.warn("Invalid command type: {}", sb);
본인의 기준이 있다는 점이 좋은 것 같습니다!! 😄

그러면 로그 관련해서 질문을 드리고 싶네요..ㅎ

- 로그의 목적이 무엇이라고 생각하시나요?
- 로그는 많이 남길 수록 좋을까요?
- 혜성님은 로그를 어떻게 활용하고 있나요?

2023-06-29 09:20 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/enumtype/ConsoleCommandType.java
> +                    log.warn("Invalid command type: {}", sb);
- 애플리케이션에서 발생한 예외 상황을 빠르게 캐치한다는 데 목적이 있다고 생각합니다. 또한, 비즈니스에 있어 의미있는 정보를 남겨 재해 발생시 활용하는 목적도 있다고 생각합니다.
- 정말로 필요한 부분이 어딘지에 대해서 고민하는 과정이 필요합니다. 여러 정보가 복잡하게 혼재되어 있으면 필요한 정보를 구분하는데 시간이 소요됩니다.
- 예외 발생 이유를 파악하기 위해 사용해본 적은 있으나 구체적으로 활용을 해본 적은 아직 없습니다.

2023-06-30 10:41 UTC, JoosungKwon reviewed
혜성님 고생하셨습니다!! 
전반적으로 잘하신 것 같아요~~😄 다음 과제로 넘어가도 좋을 것 같습니다!!!
간단한 리뷰 남겼으니 참고만 해주세요~

2023-06-30 10:41 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/domain/voucher/domain/PercentDiscountVoucher.java
> +        this.percent = percent;
범위에 대한 검증이 있으면 더 좋을 것 같아요~

2023-06-30 10:41 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/domain/voucher/domain/VoucherType.java
> +            new FixedAmountVoucherFactory()),
직접 `Voucher`를 생성하지 않고 `VoucherFactory`를 생성하신 의도가 궁금합니다~!

2023-06-30 10:41 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/global/util/CommonErrorMessages.java
> +public interface CommonErrorMessages {
`interface`를 사용하신 의도가 궁금합니다!

2023-06-30 10:41 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/domain/voucher/repository/VoucherFileRepository.java
> +            String errorMessage = CommonErrorMessages.addFilePath(CANNOT_ACCESS_FILE, file.getPath());
`CANNOT_ACCESS_FILE`를 포맷화된 문자로 두어도 좋을 것 같아요~
ex) "Unable to access the file. path: { }"

2023-06-30 14:36 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/domain/customer/controller/CustomerController.java
> +                .reduce("", (a, b) -> a + "\n" + b);
콘솔이 리스트를 출력하는 방법에 대해서 알고 컨트롤러는 리스트를 인수로 넘겨주는 것으로 개선해보겠습니다!

2023-06-30 14:36 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/domain/voucher/domain/VoucherType.java
> +            new FixedAmountVoucherFactory()),
`VoucherType`이 어떤 바우처를 만들어줘야 할지 알고 있어서 여기에 적절한 바우처 생성을 요청하는 편이 좀 더 좋지 않을까? 라고 생각했습니다.
이전에는 `BiFunction`으로 생성했었는데 만약에 요구사항이 확장된다면 그것만으로는 부족할 것 같아 팩토리 클래스를 별도로 만들어서 `VoucherType`이 해당하는 팩토리를 가지고 있도록 했습니다.

2023-06-30 14:36 UTC, hseong3243 commented on src/main/java/com/programmers/voucher/global/util/CommonErrorMessages.java
> +public interface CommonErrorMessages {
상수와 정적 메서드를 제공하는데 `interface`를 이용해서 유틸 클래스를 만들면 충분하지 않을까? 라고 생각했습니다.
그러나 개발자가 이를 구현하는 것을 막을 수 없기 때문에 부족했던 부분이었습니다..! `final class`로 변경하고 생성자를 `private`으로 변경하여 개선하였습니다.

2023-06-30 15:14 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/domain/voucher/domain/VoucherType.java
> +            new FixedAmountVoucherFactory()),
만약 `VoucherType`이 여러개로 늘어나면 각 타입당 2개의 객체가 만들어지게 될 것 같아요..!!
정답은 없지만 현재와 같은 방식은 하나의 `Voucher`에서 계층적으로 변경이 잦을 때 효과가 있을 것 같네요.

2023-06-30 15:18 UTC, JoosungKwon commented on src/main/java/com/programmers/voucher/global/util/CommonErrorMessages.java
> +public interface CommonErrorMessages {
[이펙티브자바에서 아이템 22번 인터페이스는 타입을 재정의하는 용도로만 사용하라](https://jackjeong.tistory.com/entry/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94-3%ED%8C%90-ITEM22-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EB%8A%94-%ED%83%80%EC%9E%85%EC%9D%84-%EC%A0%95%EC%9D%98%ED%95%98%EB%8A%94-%EC%9A%A9%EB%8F%84%EB%A1%9C%EB%A7%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)를 알아보시면 좋을 것 같아요~

2023-07-05 17:22 UTC, merged