[4기 - 배준일] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #671
Opened 2023-06-23 17:20 UTC by bjo6300

## 📌 과제 설명 

- [ ]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [ ]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [ ]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [ ]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [ ]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌   파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
1. 리뉴얼전 과제에서 springboot 애플리케이션으로 변경하는 요구사항이 있어서 commandLineApplication에 CommandLineRunner를 구현해 springboot 시작 시 콘솔 기능이 실행되도록 구현했습니다.

2. VoucherFactory 클래스를 만들어 객체의 생성을 담당하게 했습니다.

3. create / list 기능을 구현했습니다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 각 클래스마다 적절한 책임이 할당됐는지 궁금합니다. 객체지향적으로 코드를 짰는지 궁금합니다.
- 구현하지 못한 logback과 심화 기능은 빠른 시일 내에 구현하겠습니다!

2023-06-24 16:36 UTC, JoosungKwon reviewed
안녕하세요 준일님 과제하시느라 고생 많으십니다~! 👍 
간단하게 리뷰 남겨드렸습니다~! 확인 부탁드립니다~~ 😄

> 각 클래스마다 적절한 책임이 할당됐는지 궁금합니다. 객체지향적으로 코드를 짰는지 궁금합니다.

- 전반적으로 적절하게 책임이 할당되도록 노력하신게 보입니다! 잘 나누신 것 같아요!

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/CommandLineApplication.java
> +    voucherController.run();
직접 생성하셔서 사용하시는 이유가 궁금하네요~~ `VoucherService` 같은 경우는 `Bean`으로 등록도 하셨네요!

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +@Configuration
`VoucherFactory`에 `Configuration`은 적절하지 않아 보이는데 어떻게 생각하시나요?

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +        log.error("잘못된 바우처 유형입니다.");
준일님은 로그 레벨을 어떤 기준으로 나누고 계신가요?

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherService.java
> +    }
저는 `VoucherService`에서 출력의 역할까지 담당하는건 좋지 않다고 생각합니다~ 준일님은 어떻게 생각하시나요?

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +    while (true) {
단순 `true` 보다는 실행 중임을 알아볼수 있는 변수로 나타내면 어떨까요?

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Command.java
> +        .filter(command -> command.getLowerCaseCommand().equals(inputCommand))
`equals` 대신 `equalsIgnoreCase`를 사용하는게 좀 더 유연할 것 같은데 어떻게 생각하시나요~?

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +  public void run() {
예외 처리 동작은 없나요~?

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +  public Voucher toVoucher(VoucherType voucherType, UUID voucherId, long amount) {
`amount` 값에 대한 검증 로직이 있으면 좋을 것 같습니다~!

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/PercentDiscountVoucher.java
> +  private final UUID voucherId;
`UUID`는 어떤 상황에 적합하다고 생각하시나요?

2023-06-24 16:36 UTC, JoosungKwon commented on springboot-basic/src/test/java/com/example/springbootbasic/commandLineApplicationTests.java
> +class commandLineApplicationTests {
테스트 코드가 추가된다면 금상첨화일것 같네요~ㅎㅎㅎ

2023-06-24 16:44 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/PercentDiscountVoucher.java
> +    return price * (discountPercent / FULL_PERCENT);
몫만 추출되고 소수점 이하는 사라지게 됩니다. 기본적인 내용을 놓쳤네요...! 수정하겠습니다!

2023-06-24 17:13 UTC, JoosungKwon reviewed
@bjo6300 
마지막 질문 주신 내용을 방금 확인해보았습니다!
제가 실행시켜본 결과 로그 파일에 기록되고 있는것 같습니다. 로그 설정을 springframework에서 로그파일로 기록되도록 설정하셔서 그런것 같네요~! 
![스크린샷 2023-06-25 오전 2 15 02](https://github.com/prgrms-be-devcourse/springboot-basic/assets/99165624/22188245-c464-41b6-9b65-f15ec820e261)

2023-06-25 02:42 UTC, graygreat requested changes
안녕하세요 준일님!

코드 깔끔하게 잘 짜주셨네요 💯 
추가로 몇가지 리뷰 남겼으니 확인 부탁드립니다.

질문 주신 사항에 대해 답변을 해보자면,
> 각 클래스마다 적절한 책임이 할당됐는지 궁금합니다. 객체지향적으로 코드를 짰는지 궁금합니다.

잘 짜주신 것 같아요. 다만 리뷰에 남긴 몇가지 부분만 수정되면 조금 더 좋을 것 같네요.

> 기존에 orelsethrow() 문으로 오류를 잡았습니다. logback.xml 설정 이후 발생하던 에러 메세지가 콘솔창에 보이지 않는 상황입니다.

현재 발생한 예외에 대해 logging이 되지 않은 것 같아서 그런거 같네요.

2023-06-25 02:42 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/VoucherType.java
> +        .filter(voucher -> voucher.getLowerCaseVoucherType().equals(inputVoucherType))
저라면 이 로직도 메소드로 따로 빼서 가독성을 높일 것 같네요 :)

2023-06-25 02:42 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/MemoryVoucherRepository.java
> +@Repository
VoucherRepository 에도 @Repository가 정의 되어 있는데, 두 번 정의하신 이유가 있으실까요?

2023-06-25 02:42 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/MemoryVoucherRepository.java
> +  private final Map<UUID, Voucher> storage = new ConcurrentHashMap<>();
ConcurrentHashMap, HashMap 차이가 무엇인가요?
ConcurrentHashMap을 사용하신 이유가 궁금합니다 :)

2023-06-25 02:42 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/MemoryVoucherRepository.java
> +  public Optional<Voucher> findById(UUID voucherId) {
Optional의 장단점은 어떤게 있을까요?

2023-06-25 02:42 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +  private final static Logger log = LoggerFactory.getLogger(VoucherFactory.class);
log 또한 상수로 선언되어 있으니 대문자로 해주면 좋지 않을까요?

2023-06-25 02:42 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +    switch (voucherType) {
분기문을 사용하지 않고 어떻게 구현해볼 수 있지 고민해보시면 좋을 것 같아요.

2023-06-26 12:18 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/Voucher.java
> +public interface Voucher {
상속받는 클래스 혹은 구현하는 인터페이스 안에 있는 추상 메소드를 구현해야 합니다. `Interface`는 추상 메소드의 구현을 강제하는데 이는 구현 객체의 같은 동작을 보장하기 때문입니다. FixedAmountVoucher와 PercentDiscountVoucher에서 `discountedPrice()`는 서로 다른 동작을 하므로 `Abstract Class`를 사용하는게 좋아보입니다!

2023-06-26 12:26 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +@Configuration
`Configuration`은 내장 클래스를 Bean으로 등록하고자 할 경우 사용하기 때문에 적절하지 않아보입니다. 개발자가 직접 작성한 클래스를 Bean으로 등록하고자 할 경우 사용하는 Component로 변경하겠습니다!

2023-06-26 12:28 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherService.java
> +    }
history 기능을 서비스에서 하기보다 Output에서 출력 기능을 담당하고 history 함수에서 호출하는 형식으로 변경하는 방식이 더 좋다고 생각합니다!

2023-06-26 12:33 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Command.java
> +        .filter(command -> command.getLowerCaseCommand().equals(inputCommand))
`equalsIgnoreCase`를 사용하면 'eXIt' 같은 입력값도 같다고 판별해서 `equals`를 사용했습니다. 유연하게 사용하기 위해 생각한 방법은 `toUpperCase`와 `toLowerCase`로 모두 대문자이거나 소문자일 경우에 filter에 통과시키는 방법이 좋다고 생각합니다! 주성님 생각은 어떠신가요?

2023-06-26 12:35 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/PercentDiscountVoucher.java
> +  private final UUID voucherId;
UUID(Universally Unique IDentifier)는 고유성이 보장되는 id를 만들기 위해 존재하는 표준 규약입니다. 고유한 식별자가 필요한 상황에 적합하다고 생각합니다!

2023-06-26 12:40 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/MemoryVoucherRepository.java
> +@Repository
불필요한 어노테이션이라고 생각합니다. 구현체인 `MemoryVoucherRepository`에만 @Repository를 사용하겠습니다!

2023-06-26 13:20 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/MemoryVoucherRepository.java
> +  private final Map<UUID, Voucher> storage = new ConcurrentHashMap<>();
`HashMap`은 여러 쓰레드가 동시에 접근할 경우 데이터 일관성 문제가 발생할 수 있습니다.
`ConcurrentHashMap`은 동기화를 제공하기 때문에 thread-safe 합니다. 여러 사용자가 동시에 storage에 접근할 경우 데이터의 일관성이 깨질 수 있어서 채택했습니다!

2023-06-26 13:28 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/MemoryVoucherRepository.java
> +  public Optional<Voucher> findById(UUID voucherId) {
`Optional`의 장점은 Null-Safe하고 가독성이 좋습니다. 단점은 Optional 객체 자체를 저장하기 위한 메모리가 추가로 필요하기 때문에 오버헤드가 증가합니다.

2023-06-26 15:14 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +        log.error("잘못된 바우처 유형입니다.");
명확한 기준을 정립하진 않았지만 error 레벨은 `프로그램 동작에 큰 문제가 발생했다는 것으로 즉시 문제를 조사해야 함`인 것 같아요. 이 상황에서는 `warn`이 어울려 보이네요!

2023-06-28 14:22 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +  private final static Logger log = LoggerFactory.getLogger(VoucherFactory.class);
수정했습니다! 
018ab645f2ed3c2eacb98f6b19a5d1d3c7878fb5

2023-06-28 15:31 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Output.java
> +public class Output {
싱글톤으로 만드는 방식으로 수정했습니다!
da48635c175bdbd4119408af9cf662ece467bf9e

2023-06-28 15:42 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +    while (true) {
변수화시켰습니다!
216b71dcdbedea044f5da9cb634ccfcef9333e6b

2023-06-28 15:48 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +  public void run() {
예외처리 추가했습니다!
bb9b4e50790add567bb0e153d32eda668a9b2921

2023-06-28 18:05 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +  public Voucher toVoucher(VoucherType voucherType, UUID voucherId, long amount) {
추가했습니다!
28a9a152c6a3a19c6c69244fb6a54d722cc1f991

2023-06-29 07:40 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +        log.error("잘못된 바우처 유형입니다.");
로그 레벨에 대한 기준은 정답은 없습니다! 로그의 목적과 어떻게 활용할 것인가에 대해 고민해보시고 기준을 정해보시면 좋을 것 같습니다.!!

[효율적으로 로그 모니터링하기 - 로그 레벨 구분하기](https://jojoldu.tistory.com/712)

2023-06-29 07:43 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Command.java
> +        .filter(command -> command.getLowerCaseCommand().equals(inputCommand))
오! 그런 생각이였군요!! 준일님 생각도 좋습니다~😄 저는 최대한 유연하게 입력받을 수 있는게 사용자 입장에서 편하지 않을까? 라는 생각이었습니다~

2023-06-29 07:48 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/PercentDiscountVoucher.java
> +  private final UUID voucherId;
고유한 식별자가 필요한 상황이라면 구체적으로 어떤 상황이 있을까요? 그리고 `UUID`의 장단점에 대해 아시나요~?

2023-06-30 05:49 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/PercentDiscountVoucher.java
> +  private final UUID voucherId;
`MemoryVoucherRepository`에서 기록을 저장하는 상황에 고유 식별자가 필요합니다. 
UUID의 장점은 중복되지 않는 키 값으로 설정할 수 있습니다. 그러므로 데이터에 대한 정보를 노출하지 않기 때문에 보안상 안전합니다. 
단점은 UUID는 128비트로 상대적으로 메모리를 많이 사용합니다.

2023-06-30 06:34 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +          voucherService.insert(voucher);
Input과 Output을 인터페이스로 만들고 Console을 생성해서 인스턴스 변수를 줄였습니다!
또한 기능별 메소드로 분리했습니다.

e6b4abf9a851f193e5d76da2a1bc1af130c1b35e

2023-06-30 06:38 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +  private final VoucherService voucherService;
Input과 Output을 인터페이스로 만들고 Console을 생성해서 인스턴스 변수를 줄였습니다.
또한 기능 별 메소드로 분리했습니다.

```
private final MemoryVoucherRepository memoryVoucherRepository;
private final Console console;
private final VoucherFactory voucherFactory;
```
현재 VoucherService에서 인스턴스 변수를 4개에서 3개로 줄였습니다. 3개 미만으로 줄이는 방향으로 고민했지만 방향성을 모르겠습니다..! 

e6b4abf9a851f193e5d76da2a1bc1af130c1b35e

2023-07-02 06:43 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +  private final VoucherService voucherService;
`VoucherService`에 `Console`이 반드시 필요한가요?

2023-07-03 16:49 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +  private final VoucherService voucherService;
`VoucherService`에서는 생성 기능을 담당하게 하고 `VoucherController`에서 입출력을 담당하게 했습니다!
7df2e846dfe2f57a1e64fd8d6028e1d377b65986

2023-07-10 07:38 UTC, merged