[4기 - 김민정] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다
prgrms-be-devcourse/springboot-basic pull request #673
Opened 2023-06-23 18:15 UTC by pushedrumex

## 📌 과제 설명 
(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌   파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
### 동작 과정
<img width="587" alt="스크린샷 2023-06-24 오전 3 12 49" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/97938489/bda514b4-45f4-45e2-adcd-90174ae53b37">
asic/assets/97938489/0f5ca39c-cb51-4b34-b8c0-055483d525a3">

### 설계
<img width="551" alt="스크린샷 2023-06-24 오전 3 01 49" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/97938489/e4f6d130-0f08-4e94-8ec6-cb4f04c36d4d">

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
1. repository에서 findById의 반환을 Optional로 리턴한하는데, 어느 레이어(service, controller)에서 optional에 대한 get과 예외처리를 해야하는지 궁금합니다.
2. fixedAmountVoucher는 amount필드를 갖고, percentDiscountVoucher는 percentage필드를 갖습니다. 현재는 요구사항에 따라 Voucher인터페이스로 추상화하여 같은 저장소인 HashMap에 저장하였는데, 실제 db에 저장할 때는 이 두 종류의 바우처가 갖는 필드가 다르므로 각자 다른 테이블에 저장해야하는지 궁금합니다. 또한 실제 서비스에서는 바우처의 종류가 다양한데, 어떤식으로 바우처를 관리하는지 궁금합니다.
3. 각각의 객체들의 책임이 잘 분리 되었는지 궁금합니다.

2023-06-24 18:14 UTC, JoosungKwon reviewed
안녕하세요 민정님 과제하시느라 고생 많으셨습니다~! 😄
간단한 그림으로 uml 다이어그램을 그리신 것이 상당히 인상깊네요~!! 정말 좋은 습관인 것 같습니다 👍
한가지 이야기 드리고 싶은 부분은 모든 객체를 인터페이스를 사용하셔서 구현하셨는데 꼭 인터페이스가 필요한지 한번 고민해보셨으면 좋겠습니다. (인터페이스를 잘못 사용하면 사용안한것만 못하답니다!!)

질문 주신 내용에 답변드리자면

> repository에서 findById의 반환을 Optional로 하는데, 어느 레이어(service, controller)에서 Optional에 있는 값을 꺼내고 예외처리를 해야하는지 궁금합니다.

- 저는 `service` 레이어에서 처리하면 될 것 같다고 생각합니다! 어느 레이어에서 얼만큼 책임을 가져갈지에 대해서는 사람마다 의견이 약간은 갈리는 편이긴 합니다. 보통은 service에서 처리하긴 합니다. 민정님 생각도 궁금합니다!

> fixedAmountVoucher는 amount필드를 갖고, percentDiscountVoucher는 percentage필드를 갖습니다. 현재는 Voucher인터페이스로 추상화하여 같은 저장소인 HashMap에 저장하였는데, 실제 db에 저장할 때는 이 두 종류의 바우처가 갖는 필드가 다르므로 각자 다른 테이블에 저장해야하는지 궁금합니다.

- 어떻게 구현하냐에 따라 다를 것 같습니다..! 저라면 `percentage`나 `amount`나 동일한 데이터 타입이기 때문에 type 필드를 추가로 두어 하나의 테이블로 관리했을 것 같습니다.. (사람마다 생각이 다를 것 같아요! 예전에 프로젝트에서도 비슷한 고민을 했던적이 있습니다...ㅎㅎ)

> 또한 실제 서비스에서는 바우처의 종류가 다양한데, 어떤식으로 바우처를 관리하는지 궁금합니다.

- 이부분은 제가 답하긴 약간 어렵네요! 멘토님이 답변해주실 것 같습니다. 그렇지만 개인적인 생각은 회사마다 달라서 정해진 방식은 없지 않을까요..? 😅 (저라면 종류의 가지 수에 따라 다르겠지만 Enum으로 관리할 것 같습니다.. )

> 각각의 객체들의 책임이 잘 분리 되었는지 궁금합니다.

- 중간 중간 애매하다고 생각이 드는 부분에 리뷰 남겼습니다~!

2023-06-25 03:36 UTC, graygreat requested changes
안녕하세요 민정님 :)

요구사항도 잘 정의 해주시고 설계도 잘해주셔서 코드 읽기 수월했던 것 같아요 💯 
조금 보충했으면 좋겠다고 생각이 드는 것은 로그를 "왜" 사용해야할까에 대해서 한번 생각해보시면 좋을 것 같아요 ㅎㅎ
리뷰도 남겨놓았으니 확인 부탁드립니다!

> repository에서 findById의 반환을 Optional로 하는데, 어느 레이어(service, controller)에서 Optional에 있는 값을 꺼내고 예외처리를 해야하는지 궁금합니다.

이건 service layer와 controller layer의 역할에 대해서 알아보시면 좋을 것 같네요.
Controller는 주로 요청을 처리하고 응답을 반환하는 역할을 하죠?
그렇다면 여기서 Optional에 대한 값을 직접 다루는건 적절하지 않다고 생각이 들어요 ^^

> fixedAmountVoucher는 amount필드를 갖고, percentDiscountVoucher는 percentage필드를 갖습니다. 현재는 Voucher인터페이스로 추상화하여 같은 저장소인 HashMap에 저장하였는데, 실제 db에 저장할 때는 이 두 종류의 바우처가 갖는 필드가 다르므로 각자 다른 테이블에 저장해야하는지 궁금합니다. 또한 실제 서비스에서는 바우처의 종류가 다양한데, 어떤식으로 바우처를 관리하는지 궁금합니다.

이건 주성님이 잘 말씀해주셨네요 👍 

> 각각의 객체들의 책임이 잘 분리 되었는지 궁금합니다.

이건 리뷰를 통해 확인해보시면 좋을 것 같습니다!

2023-06-25 03:36 UTC, graygreat commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +                        System.exit(0);
System 함수를 사용해서 프로그램을 종료시키면 어떠한 문제점이 있을까요?

2023-06-25 03:36 UTC, graygreat commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +        log.info("create voucher : {}", voucherPolicy);
해당 로그를 남김으로서 민정님은 어떠한 걸 얻을 수 있나요?

2023-06-25 03:36 UTC, graygreat commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +        switch (voucherPolicy) {
새로운 policy가 생긴다면 policy를 새롭게 정의 해주고 해당 switch 문에도 추가해줘야겠네요 ㅠ
그럼 관리 포인트가 여러개 생길 것 같은데, 어떻게 해볼 수 있을까요?

2023-06-25 03:36 UTC, graygreat commented on src/main/java/org/prgms/voucher/repository/MemoryVoucherRepository.java
> +    public Optional<Voucher> findById(long id) {
Optional 장단점에 대해서 알고 계실까요?

2023-06-25 03:36 UTC, graygreat commented on src/main/java/org/prgms/voucher/view/ConsoleVoucherView.java
> +    private final String[] options = {"exit", "create", "list"};
String 배열로 관리하는 것 vs List로 관리하는 것 어떠한 차이가 있나요?

2023-06-25 03:36 UTC, graygreat commented on src/main/java/org/prgms/voucher/view/VoucherPolicy.java
> +public enum VoucherPolicy {
해당 클래스가 view 패키지에 들어있는 이유가 있을까요,,,?

2023-06-25 14:11 UTC, pushedrumex commented
> 안녕하세요 민정님 과제하시느라 고생 많으셨습니다~! 😄 간단한 그림으로 uml 다이어그램을 그리신 것이 상당히 인상깊네요~!! 정말 좋은 습관인 것 같습니다 👍 한가지 이야기 드리고 싶은 부분은 모든 객체를 인터페이스를 사용하셔서 구현하셨는데 꼭 인터페이스가 필요한지 한번 고민해보셨으면 좋겠습니다. (인터페이스를 잘못 사용하면 사용안한것만 못하답니다!!)
> 
> 질문 주신 내용에 답변드리자면
> 
> > repository에서 findById의 반환을 Optional로 하는데, 어느 레이어(service, controller)에서 Optional에 있는 값을 꺼내고 예외처리를 해야하는지 궁금합니다.
> 
> * 저는 `service` 레이어에서 처리하면 될 것 같다고 생각합니다! 어느 레이어에서 얼만큼 책임을 가져갈지에 대해서는 사람마다 의견이 약간은 갈리는 편이긴 합니다. 보통은 service에서 처리하긴 합니다. 민정님 생각도 궁금합니다!
> 
> > fixedAmountVoucher는 amount필드를 갖고, percentDiscountVoucher는 percentage필드를 갖습니다. 현재는 Voucher인터페이스로 추상화하여 같은 저장소인 HashMap에 저장하였는데, 실제 db에 저장할 때는 이 두 종류의 바우처가 갖는 필드가 다르므로 각자 다른 테이블에 저장해야하는지 궁금합니다.
> 
> * 어떻게 구현하냐에 따라 다를 것 같습니다..! 저라면 `percentage`나 `amount`나 동일한 데이터 타입이기 때문에 type 필드를 추가로 두어 하나의 테이블로 관리했을 것 같습니다.. (사람마다 생각이 다를 것 같아요! 예전에 프로젝트에서도 비슷한 고민을 했던적이 있습니다...ㅎㅎ)
> 
> > 또한 실제 서비스에서는 바우처의 종류가 다양한데, 어떤식으로 바우처를 관리하는지 궁금합니다.
> 
> * 이부분은 제가 답하긴 약간 어렵네요! 멘토님이 답변해주실 것 같습니다. 그렇지만 개인적인 생각은 회사마다 달라서 정해진 방식은 없지 않을까요..? 😅 (저라면 종류의 가지 수에 따라 다르겠지만 Enum으로 관리할 것 같습니다.. )
> 
> > 각각의 객체들의 책임이 잘 분리 되었는지 궁금합니다.
> 
> * 중간 중간 애매하다고 생각이 드는 부분에 리뷰 남겼습니다~!

안녕하세요 주성님! 자세한 리뷰 감사합니다😊
확장성과 재사용성을 위해서 인터페이스를 사용하고자 하였지만, 생각해보니 현재 만들어야하는 바우처는 service나 controller는 굳이 인터페이스로 추상화하지 않아도 될 것 같습니다..! 수정해보도록 하겠습니다!
저도 controller는 요청에 대한 라우터 + 응답 역할을 한다고 생각하므로 service에서 Optional을 처리해야한다고 생각합니다!

2023-06-25 14:15 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/controller/VoucherController.java
> +public interface VoucherController {
확장성을 위해 interface를 두었지만, 생각해보니 현재 만들어야하는 서비스는 controller까지 추상화할 필요가 없는것 같습니다. 수정해보도록 하겠습니다:)

2023-06-25 14:19 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/controller/VoucherController.java
> +    void run();
현재 Controller에서 view의 역할과 controller의 역할을 모두 하고있으므로 VoucherRunner로 명하는게 더 적절한 것 같습니다:)

2023-06-25 14:21 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +                        log.info("create");
어플리케이션의 동작을 기록하고 디버깅하기 위해 사용했습니다!

2023-06-25 14:22 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +    private void createVoucher() {
바우처의 추가/삭제에 따라 바우처 종류의 정보와 관계 없는 VoucherController의 코드를 수정해야하므로 따로 분리하는게 좋을 것 같습니다!

2023-06-25 14:26 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/voucher/PercentDiscountVoucher.java
> +    private UUID id;
바우처의 고유 식별자를 repository레이어에서 생성하기 위해 final을 하지 않았습니다. 하지만 생각해보니 UUID는 바우처의 일련번호?와 같은 역할을 할 것 같습니다. final로 해서 바우처를 생상하는 객체에서 UUID를 생성하도록 수정하겠습니다!

2023-06-25 14:27 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/voucher/FixedAmountVoucher.java
> +        return Math.max(0, price - amount);
최종 결제 금액이 0원입니다!

2023-06-25 14:29 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/repository/MemoryVoucherRepository.java
> +    private Map<UUID, Voucher> store = new HashMap<>();
HashMap을 사용할 경우 thread-safe하지않아 race condition이 발생할 가능성이 있습니다. ConcurrentHashMap을 사용해보도록 하겠습니다:)

2023-06-25 14:30 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/repository/MemoryVoucherRepository.java
> +        return null;
voucher를 반환해야하는데 잘못적었습니다. 수정하겠습니다!

2023-06-25 14:33 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/service/VoucherServiceImpl.java
> +    public List<Voucher> list() {
클래스명이 VoucherService라 단순하게 list라고 명명하였는데, 모호할 수도 있을 것 같습니다!

2023-06-25 14:39 UTC, pushedrumex commented
> 안녕하세요 민정님 :)
> 
> 요구사항도 잘 정의 해주시고 설계도 잘해주셔서 코드 읽기 수월했던 것 같아요 💯 조금 보충했으면 좋겠다고 생각이 드는 것은 로그를 "왜" 사용해야할까에 대해서 한번 생각해보시면 좋을 것 같아요 ㅎㅎ 리뷰도 남겨놓았으니 확인 부탁드립니다!
> 
> > repository에서 findById의 반환을 Optional로 하는데, 어느 레이어(service, controller)에서 Optional에 있는 값을 꺼내고 예외처리를 해야하는지 궁금합니다.
> 
> 이건 service layer와 controller layer의 역할에 대해서 알아보시면 좋을 것 같네요. Controller는 주로 요청을 처리하고 응답을 반환하는 역할을 하죠? 그렇다면 여기서 Optional에 대한 값을 직접 다루는건 적절하지 않다고 생각이 들어요 ^^
> 
> > fixedAmountVoucher는 amount필드를 갖고, percentDiscountVoucher는 percentage필드를 갖습니다. 현재는 Voucher인터페이스로 추상화하여 같은 저장소인 HashMap에 저장하였는데, 실제 db에 저장할 때는 이 두 종류의 바우처가 갖는 필드가 다르므로 각자 다른 테이블에 저장해야하는지 궁금합니다. 또한 실제 서비스에서는 바우처의 종류가 다양한데, 어떤식으로 바우처를 관리하는지 궁금합니다.
> 
> 이건 주성님이 잘 말씀해주셨네요 👍
> 
> > 각각의 객체들의 책임이 잘 분리 되었는지 궁금합니다.
> 
> 이건 리뷰를 통해 확인해보시면 좋을 것 같습니다!

안녕하세요 네이비님 :) 자세한 리뷰 감사합니다😊 로깅이 필요한 이유에 대해서 다시한번 생각해보고 적용해보도록 하겠습니다!

2023-06-25 14:48 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +                        System.exit(0);
프로그램이 비정상적으로 종료되어 리소스 정리 등의 처리가 정상적으로 실행되지 않아 예상치 못한 문제가 발생할 수도 있습니다. return을 하는게 좋을 것 같습니다!

2023-06-25 14:50 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +        switch (voucherPolicy) {
바우처를 생성하는 역할을하는 객체로 분리하면 될 것 같습니다!

2023-06-25 14:54 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/repository/MemoryVoucherRepository.java
> +    public Optional<Voucher> findById(long id) {
Optional을 사용하므로써, NPE을 방지하여 코드의 안정성을 높일 수 있습니다. 메서드 체이닝을 통해 값을 유연하게 처리할 수 있게 해줍니다. 단점은 추가적으로 Optional 인스턴스를 생성하는 것이므로 오버헤드가 발생할 수 있습니다.

2023-06-25 15:05 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/view/ConsoleVoucherView.java
> +    private final String[] options = {"exit", "create", "list"};
String배열은 크기가 고정되어 있고 메모리에 연속적으로 할당되기 때문에 메모리 할당과 요소 접근에 대한 오버헤드가 적습니다. List는 메모리에 불연속적으로 할당되고 포인터를 위한 추가적인 메모리를 필요로합니다.
따라서 배열은 크기가 고정되어 있고, 추가적인 삽입 삭제가 일어 나지 않으며 검색을 필요로 할 때 유리하고, 리스트는 데이터의 크기가 고정되어있지 않고 삽입 삭제가 많이 일어나며 검색이 적은 경우 유리합니다.

2023-06-26 07:13 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/voucher/Voucher.java
> +public interface Voucher {
공통적으로 구현할 메서드가 있는 경우 `Abstract Class`를 사용하고 없는 경우 `Interface`를 사용해야한다고 생각합니다. 현재 두개의 바우처는 getId()를 공통으로 갖고 있으므로 `Abstract Class`를 사용하는게 적절할 것 같습니다

2023-06-27 04:45 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/VoucherApplication.java
> +    }
CommandLineRunner를 사용하면 스프링부트가 실행될 때 자동으로 실행되어서 저는 main과 비슷하게 동작한다고 생각하는데, 혹시 CommadLineRunner를 사용함으로써 갖게되는 장점이 있는건가요...?!🤔

2023-06-27 05:37 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/voucher/Voucher.java
> +public interface Voucher {
추상 클래스는 **자신의 기능들을 하위로 확장**시키는 것이고, 인터페이스는 인터페이스에 정의된 메서드를 **각 클래스의 목적에 맞게 동일한 기능으로 구현**하는 것입니다. 현재 Voucher마다 할인해주는 계산 방법이 다르기 때문에 목적에 맞게 동일하 기능 구현을 강제하는 interface를 사용하였습니다!

2023-06-29 08:07 UTC, JoosungKwon commented on src/main/java/org/prgms/voucher/VoucherApplication.java
> +    }
흠.. 굉장히 좋은 질문인 것 같습니다~!!! 저도 크게 생각하지 않았던 부분이네요.. (반성합니다,,😂)

제가 알고 있는 지식 선에서 이야기 하자면 
일단은 동작에서는 큰 차이나 장점이 있지는 않습니다.

그러면 왜 CommandLineRunner를 권장해드렸나면 

일반적으로 Main에서 applicationContext의 특정 빈을 호출해서 run하는 방식을 잘 사용하지 않습니다!
반면에 CommandLineRunner의 존재 목적 자체가 스프링이 로드될때 특정 코드를 실행할 수 있도록 하기 위함이니 목적에 맞게 사용하는게 좋지 않을까 라는 생각으로 권장드렸습니다!

일반적인 것이 좋냐고 물으시면 꼭 그런 것은 아닙니다! 다만, 일반적이고 본래 목적에 맞게 사용할 수록 코드가 좀 더 쉽게 이해가 되는 것 같습니다!

2023-06-29 08:15 UTC, JoosungKwon commented on src/main/java/org/prgms/voucher/voucher/Voucher.java
> +public interface Voucher {
음.. 약간은 아쉬운 답변인 것 같습니다! ( `interface`를 사용하신 것이 틀리거나 잘못되었다는 이야기는 절대 아닙니다. 다만, 사용 이유가 약간은 아쉽다는 이야기 입니다!)

`Abstract Class`도 추상 메서드가 있기 때문에 목적에 맞게 동일한 기능 구현을 강제할 수 있긴 합니다! `Interface`와 `Abstract Class`를 어떤 상황에 사용하면 좋을지 공부해보시면 좋을 것 같아요!

2023-06-30 11:26 UTC, JoosungKwon reviewed
민정님 고생하셨습니다!! 전반적으로 잘하셨습니다~ 😄
멘토님께 이야기 드리고 Merge후에 다음 과제 PR로 넘어가도 될 것 같습니다 👍
간단한 리뷰 남겼으니 참고만 해주세요~😊

2023-06-30 11:26 UTC, JoosungKwon commented on src/main/java/org/prgms/voucher/voucher/VoucherFactory.java
> +    private final long MIN_FIXED_AMOUNT = 0;
상수라면 static을 사용하는게 보다 명확할 것 같습니다!

2023-06-30 11:26 UTC, JoosungKwon commented on src/main/java/org/prgms/voucher/voucher/VoucherFactory.java
> +public class VoucherFactory {
`VoucherFactory`를 `Component`로 볼수도 있고 `Util` 클래스로도 생각해 볼 수 있을 것 같은데 민정님은 어떻게 생각하시나요?

2023-06-30 11:26 UTC, JoosungKwon commented on src/main/java/org/prgms/voucher/view/ConsoleVoucherView.java
> +                        .map(voucher -> MessageFormat.format("id: {0}, voucher policy: {1}, amount: {2}", voucher.getId(), voucher.getVoucherPolicy(), voucher.getAmount()))
`Voucher`에서 `toString`을 재정의하는 것은 어떤가요?

2023-06-30 11:26 UTC, JoosungKwon commented on src/main/java/org/prgms/voucher/service/VoucherService.java
> +        return this.voucherRepository.save(voucher);
`this`는 일부러 사용하신 건가요..?

2023-06-30 14:27 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/service/VoucherService.java
> +        return this.voucherRepository.save(voucher);
아뇨...ㅎㅎ 수정하겠습니당

2023-06-30 14:33 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/view/ConsoleVoucherView.java
> +                        .map(voucher -> MessageFormat.format("id: {0}, voucher policy: {1}, amount: {2}", voucher.getId(), voucher.getVoucherPolicy(), voucher.getAmount()))
dto에서 toString을 재정의하면 좋을 것 같습니다! 출력해야하는 필드가 많아질 경우, 하나하나 꺼내서 포메팅하지 않아도 될 것 같네요!

2023-06-30 14:34 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/view/ConsoleVoucherView.java
> +                        .map(voucher -> MessageFormat.format("id: {0}, voucher policy: {1}, amount: {2}", voucher.getId(), voucher.getVoucherPolicy(), voucher.getAmount()))
dto에서 toString을 재정의해서 view에서는 dto의 내용을 알 필요 없이 출력기능만하도록하면 좋을 것 같습니다!

2023-06-30 14:37 UTC, pushedrumex commented
> 민정님 고생하셨습니다!! 전반적으로 잘하셨습니다~ 😄 멘토님께 이야기 드리고 Merge후에 다음 과제 PR로 넘어가도 될 것 같습니다 👍 간단한 리뷰 남겼으니 참고만 해주세요~😊

알겠습니다 감사합니다 😊😊 머지하기 전에 한가지 질문이 있습니다..!

file repositor를 도입하면서, repository layer에서 checkedException을 처리해야하는데, 이 곳에서 발생하는 에러를 어느 레이어에서 catch를 해야하는지 궁금합니다.

2023-06-30 14:44 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/voucher/VoucherFactory.java
> +public class VoucherFactory {
저도 종속성이 없는 view와 factory는 유틸로 분리하는게 더 좋아보입니다!

2023-06-30 14:51 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/dto/BlackCustomerResponseDto.java
> +    private String name;
저도 final로 해서 변수의 불변성을 최대한 보장하도록하는게 좋아보입니다!

2023-06-30 14:51 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/voucher/VoucherFactory.java
> +public class VoucherFactory {
종속성이 없는 factory같은 경우는 static 메소드로 정의해서 사용하는게 좋겠네요!

2023-06-30 15:10 UTC, pushedrumex commented on src/main/java/org/prgms/voucher/controller/VoucherControllerImpl.java
> +                        log.info("create");
debug는 개발 단계에서 구현한 기능들이 잘 작동하는지 확인하기 위해 사용하고 info는 프로그램의 진행 상태를 확인하기 위해 사용합니다. 
또한, warn은 언제든지 발생할 수 있는 오류가 발생했을 때 사용하며 error는 심각한 오류나 개발자의 조치가 시급할 때 사용합니다.

2023-07-02 06:47 UTC, JoosungKwon commented on src/main/java/org/prgms/voucher/voucher/VoucherFactory.java
> +public class VoucherFactory {
사실 `Util` 클래스는 안티 패턴이라 그렇게 권장되지는 않습니다!! 민정님의 생각이 중요하지요!!

2023-07-02 06:59 UTC, JoosungKwon commented
> 알겠습니다 감사합니다 😊😊 머지하기 전에 한가지 질문이 있습니다..!
> 
> file repositor를 도입하면서, repository layer에서 checkedException을 처리해야하는데, 이 곳에서 발생하는 에러를 어느 레이어에서 catch를 해야하는지 궁금합니다.

- 제 생각에는 checkedException 은 `repository layer`에서 처리하는게 좋다고 생각합니다! 예외가 다른 레이어로 전파되는 것 자체가 의존하게 되는 형태라고 생각이 되네요! 그리고 예외는 발생하는 지점에서 멀리 처리하게 될수록 추적하기 어려워 진다고 생각합니다. 

따라서, 예외를 catch하고 다른 uncheckedException 으로 변경하던가, 원하는 방향으로 로직을 진행하게 될 것 같습니다~! 민정님은 어떻게 생각하시나요~?

2023-07-03 12:01 UTC, pushedrumex commented
> 

repository에서 발생하는 checkedException을 다른 레이어로 미뤄버리면 메서드 시그니처를 변경해야해서 다른 구현체들에게 영향을 준다고 생각합니다. 뿐만 아니라, 주성님이 말씀하신것 처럼 예외가 다른 레이어로 전파되는 것도 하나의 불필요한 의존이라고 생각이 드네요..!

2023-07-04 10:53 UTC, merged