[4기 - 김주] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #674
Opened 2023-06-23 19:34 UTC by JuwoongKim

## 📌 과제 설명 

(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

   ```bash
   === Voucher Program ===
   Type **exit** to exit the program.
   Type **create** to create a new voucher.
   Type **list** to list all vouchers.
   ```

    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌   파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
**클래스 다이어그램** (이미지 파일이 잘 보이지 않을 시 프로젝트의 doc 디렉토리 참고)

![diagram](https://github.com/prgrms-be-devcourse/springboot-basic/assets/62009283/2b243843-e1e6-4726-8687-82d5dadd7c36)

1. [링크](https://www.nextree.co.kr/p6753/)의 클래스 다이어그램 표기법을 참고하여 설계도를 작성했습니다.

2. 클래스 설명

    - VoucherApplication
      - SpringBoot Application을 실행하는 클래스입니다.
    
        
    - AppConfiguration
      - Application에 사용되는 Bean을 생성하고, 생성자 의존성 주입 패턴으로 의존성을 설정하는 클래스입니다.
    
    
     - CommandLineApplication
       - Console 객체와 VoucherService 빈을 사용해 Application의 실행 흐름을 담당한다.
     
    
    - Console
      - Application의 입출력을 담당한다.
    
    
    - ModeType
      - 사용자가 Application에서 선택할 수 있는 기능을 표현하기 위해 사용된다.
    
    
    - VoucherService
      - Application의 기능 수행을 담당한다.
      - Voucher 생성, Voucher 전체 조회 
    
    
    - Voucher
      - Voucher 엔티티의 기능을 정의한 인터페이스이다.
      - 엔티티라는 용어는 데브코스 강의를 수강하며 학습한 도메인 주도 설계의 용어를 사용했다.
      - 개방패쇄 원칙을 지키며 Voucher의 다형성을 보장할 수 있다.
    
    
    - FixedAmountVoucher
      - Voucher 인터페이스의 구현체이다.
      - 고정된 금액만큼 할인하는 voucher이다.
    
    
    - PercentDiscountVoucher
      - Voucher 인터페이스의 구현체이다.
      - 특정 비율만큼 할인하는 voucher이다.
    
    
    - VoucherType
        - Voucher의 종률를 표현하기 위해 사용된다.
    
        
    - VoucherRepository 
      - 생성된 voucher 정보를 저장하기 위해 사용하는 인터페이스이다.
      - 개방패쇄 원칙을 지키며 Repository의 다형성을 보장할 수 있다.
    
    
    - MemoryVoucherRepository 
      - VoucherRepository의 구현체이다.
      - Map 자료구조를 사용하여 Voucher 정보를 저장하는 인메모리 저장소이다.
    
    
    - FileVoucherRepository 
      - VoucherRepository의 구현체이다.
      - 파일을 사용하여 Voucher 정보를 저장하는 저장소이다.
    
    
    - FieldExtractor
      - 객체의 멤버변수에 대한 정보를 Object 배열로 변환한다.
    
    
    - LineAggregator 
      - FieldExtractor 로부터 반환된 Object 배열을 문자열로 바꿔주는 인터페이스이다.
      - 개방패쇄 원칙을 지키며 LineAggregator의 다형성을 보장할 수 있다.
    
    
    - SpaceLineAggregator
      - LineAggregator의 구현체이다.
      - 필드값 사이를 공백문자로 구분하여 문자열을 생성한다. 
    
        
    - LineTokenizer
        - 문자열을 파씽하는 기능을 수행하는 인터페이스이다.
    
    
    - SpaceLineTokenizer
      - LineTokenizer의 구현체이다.
      - 공백을 기준으로 문자열을 파씽하는 기능을 수행한다.
    
        
    - FieldSetMapper
        - 파씽된 문자열을 바탕으로 인스턴스를 생성한다.
        - File로 부터 저장된 Voucher 정보를 객체로 불러올때 사용한다.
    
        
    - LineMapper
        - LineTokenizer와 FieldSetMapper를 사용해 문자열을 객체로 변환하는 기능을 수행한다.

3. 프로그램을 구현하는 도중 설계도를 먼저 작성하여 PR 보냅니다. 프로그램이 동작하긴하지만, 입력값 검증 및 예외처리가 되지 않았습니다. 피드백 받고 개선하겠습니다. 

4. 다른 요구사항을 모두 충족한 뒤 FileRepository 관련 내용을 구현할 예정입니다.

## ✅ PR 포인트 & 궁금한 점 

1. 멤버변수는 어떻게 초기화 해주는 것이 좋을까요? 예를 들어 MemoryVoucherRepository 내부에 Map을 멤버변수로 선언할 때 선언과 동시에 초기화해야하는지, 생성자를 통해 초기화해야할지 고밉입니다. 현재는 불변을 위해 final을 사용한다는 점에서 선언과 동시에 초기화를 수행합니다.
   
2. Entity 클래스에 식별자 getter를 쓰면 안되는 것인가요? 데이터 저장만 하더라도 필드값을 꺼내욜 필요가 있는데, 식별자를 getter로 꺼내온다는 것 자체가 불안하긴 합니다.

3. repository에서 save 기능을 수행할 때 어떤 것을 반환해야할까?? 또한 저장이 안된다면 어떻게 즉시 판단할 수 있는 코드를 작성할까요?

4. commandLineApplication클래스의 메서드에 대한 테스트 코드를 수행하고 싶었으나, 메서드 내부의 입출력으로 Junit등의 테스트 도구로 테스트할 수 없었습니다. 구조를 잘못 잡은 것이겠죠? 어떻게 접근해야할까요?

3. 입출력 관련된 모든 정보를 Console 객체에 static 메서드로만 구현한다는 것이 불안합니다. 괜찮은 방법이 있을까요?

2023-06-26 12:53 UTC, HyoungUkJJang reviewed
안녕하세요 주웅님 코드 잘 봤습니다. 
간단히 리뷰 몇개 남겼는데 참고해주시면 좋을 것 같아요 ~  주웅님도 의견을 편하게 말씀해주시면 좋을 것 같아요 ㅎㅎ 고생하셨어요 🙂👍🏻

### 궁금한점
1. 멤버변수는 어떻게 초기화 해주는 것이 좋을까요? 예를 들어 MemoryVoucherRepository 내부에 Map을 멤버변수로 선언할 때 선언과 동시에 초기화해야하는지, 생성자를 통해 초기화해야할지 고밉입니다. 현재는 불변을 위해 final을 사용한다는 점에서 선언과 동시에 초기화를 수행합니다.
* 변경될 여지가 없다면 명시적으로 초기화 해주는 것도 가독성 측면에서 저는 괜찮은 것 같습니다.

2. Entity 클래스에 식별자 getter를 쓰면 안되는 것인가요? 데이터 저장만 하더라도 필드값을 꺼내욜 필요가 있는데, 식별자를 getter로 꺼내온다는 것 자체가 불안하긴 합니다.
* 무분별한 `getter`를 사용하는 것은 좋은 방법은 아니라고 생각합니다. 하지만 `getter` 자체만으로 유의미한 정보를 제공해주는 것도 있다고 생각합니다. 

3. repository에서 save 기능을 수행할 때 어떤 것을 반환해야할까?? 또한 저장이 안된다면 어떻게 즉시 판단할 수 있는 코드를 작성할까요?
* 주웅님의 판단에 따라 다를 것 같습니다. 식별자 정도를 반환할 수도 있고 저장된 도메인을 반환하게 될 수도 있을 것 같습니다. 저장이 안되거나 이미 존재하는 경우는 검증하는 코드를 더 추가해야하지 않을까 싶습니다.

4. commandLineApplication클래스의 메서드에 대한 테스트 코드를 수행하고 싶었으나, 메서드 내부의 입출력으로 Junit등의 테스트 도구로 테스트할 수 없었습니다. 구조를 잘못 잡은 것이겠죠? 어떻게 접근해야할까요?
* Console 클래스를 추상화를 하는 방법도 있을 것 같고 그 안에 로직들을 더 작은 단위의 메서드로 분할해서 테스트하는 방법도 있을 것 같고 더 다양한 방법이 있을 것 같은데 조금 더 고민해보시면 좋을 것 같습니다. 현재 구조에 대해서도 한번 생각해 보시면 좋을 것 같습니다.

2023-06-26 12:53 UTC, HyoungUkJJang commented on voucher/src/main/java/com/example/voucher/repository/MemoryVoucherRepository.java
> +		return map.get(voucherId).getVoucherId();
return 전에는 가독성 측면에서 개행처리를 한번 해주는것은 어떻게 생각하시나요?

2023-06-26 12:53 UTC, HyoungUkJJang commented on voucher/src/main/java/com/example/voucher/domain/PercentDiscountVoucher.java
> +		return beforeAmount * (percent / 100);
매직넘버 사용을 최대한 안하는 방향으로 코드를 작성해보시는건 어떨까요?
그리고 beforeAmount에 0이 들어오면 어떻게 될까요?

2023-06-26 13:18 UTC, Jo-GyuHyeon requested changes
안녕하세요 주용님 😄  
첫번째 PR 하시느라 고생 많으셨습니다.
간단히 코멘트 남겼는데 생각 해보시면 좋을것 같아요.
기능 구현에 대해 더 진행 하기 보다 피드백 반영 먼저 진행 한 후에 다시 얘기 해보시면 어떨까 해요.
고생 하셨습니다. 🙇

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +				case FixedAmount:
들여쓰기 (인덴트) 가 깊어지는것 같아요.
입력 값중 voucherType 이 올바르지 않을 경우만 반복 구문을 이용해도 될것 같아요.

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +			VoucherType voucherType = VoucherType.getVouchersType(Console.readVoucherType());
함수 호출과 전달은 한가지만 하는 것이 좋습니다.
getVouchersType() 의 인자값으로 Console.readVoucherType() 함수를 호출 하고 있습니다.

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +					isSatisfied = true;
isSatisfied 를 없앨수도 있을것 같아요. 위의 코멘트를 바탕으로 고민 해보시면 좋을것 같아요.

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/config/AppConfiguration.java
> +}
Configuration 을 활용하시는 이유를 설명 해주실 수 있을까요?
어떠한 장점이 있을까요?

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/domain/FixedAmountVoucher.java
> +	}
toString() 과 유사하다고 생각하는데 차이점은 어떤 부분이 있을까요?
view 를 위한 로직이라면 view 에서 조합 해도 좋을것 같은데 어떻게 생각 하시나요?

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/domain/enums/VoucherType.java
> +	Null("Null");
NULL 타입은 언제 사용하나요? null 을 다루는 좋은 방법은 어떠한 것이 있을까요?

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/domain/enums/VoucherType.java
> +		}
1,2 번이 각각 FixedAmount, PercentDiscount 를 보장 하나요???

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/io/ModeType.java
> +		}
위의 코멘트와 유사합니다. 같이 고민 답을 해주시면 좋을것 같아요.

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/repository/MemoryVoucherRepository.java
> +	private final Map<UUID, Voucher> map = new ConcurrentHashMap<>();
자료구조 네이밍을 사용하기 보다 보다 더 의미있는 네이밍을 사용 하는 것을 추천 드려요.

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/service/VoucherService.java
> +
JDK 17 을 사용하신 만큼 swith patter matching expression 을 사용 해보시는 건 어떨까요?

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/utils/FieldExtractor.java
> +		return objects;
return 구문전에는 개행 추가 해주세요.

2023-06-26 13:18 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/utils/FieldExtractor.java
> +		List<Object> objects = new ArrayList<>();
Object 타입을 사용하지 않을 수있을까요?

2023-06-28 15:13 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +	}
VoucherService는 바뀔 필요가 없다고 생각해서 클래스로 구현했습니다. 혹시 바뀔 필요가 없는데 생성자를 통해 주입 받도록 구현해서 그런 것일 까요?? 제가 의도를 정확히 파악하지 못할 것 같은데 한번 설명해주실 수 있을까요?? 😅😅

2023-06-28 15:15 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +			}
네!! pattern Matching을 사용해 리펙토링 해보겠습니다!!

2023-06-28 15:21 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +	}
pattern Matching을 사용해 리펙토링 해보겠습니다!!

2023-06-28 15:41 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +	}
메서드 분리를 통해 진행해보겠습니다!

2023-06-28 16:05 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +			Voucher voucher = null;
switch case 문 내부 로직에 따라 다른 바우처 값을 받고 외부에서 다시 사용하려고 임시 초기화 용도로 사용했습니다. 
한 단계 들여쓰기 작업을 위해 메서드 분리 작업을 수행하고 반환값을 받게 함으로써 해결해보려 합니다!

2023-06-28 16:15 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +		while (!isSatisfied) {
while 내부의 switch case 구문에서 voucher를 생성해서 조건을 만족할 때 까지 반복하기 위한 목적으로 구현했습니다.     
createVoucher 메서드 전체를 리펙토링하면서 해당 부분도 참고하여 고쳐보겠습니다.

2023-06-28 17:35 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/FixedAmountVoucher.java
> +	private final long amount;
말씀을 듣고 보니 가독성을 떨어뜨리는 부분이 여러가지가 있는 것 같습니다. 
이에 대한 제 추측은 다음과 같습니다.
1. 중간에 VoucherType Enum값이 있고 분리가 되어있지 않다는 점 
2. 또한 VoucherTypeEnum에만 초기화를 해서 더욱 지저분해 보입니다. 

해당 부분이 맞다면 수정하도록 하겠습니다. 

다만 멤버 변수 순서는 필드값을 reflection을 통해 문자열로 변경이 될까하는 Test를 수행하는 과정에서발생했습니다. 현재는 불필요한 내용임으로 순서는 변경할 예정입니다.

"VoucherType에는 default로" 라는 의미가 선언과 동시에 초기화한 것을 말하는 것 일까요? 

해당 부분이 맞다면 다음과 같은 생각으로 구현했습니다.
초기화 해도 문제가 없을 것 같고, 오히려 구분하기 편할 것이라고 생각했었습니다. 

다시 생각해보니깐 타입을 입력값으로 받는다는 점에서 직접 초기화하는게 비효류적이라는 생각이 드네요.

말씀 해주신 피드백과 제가 생각하는 부분이 일치한다면 이에 맞게 수정을 진행하겠습니다.

2023-06-28 18:19 UTC, JuwoongKim commented on voucher/src/test/java/com/example/voucher/utils/lineAggregator/SpaceLineAggregatorTest.java
> +	}
File기반 메모리 관련 작업을 수행하는 클래스 동작을 확인하는 과정에서 확인을 위해 작성했던 코드입니다. 다음부터는 선별해서 올리도록 하겠습니다. 

또한 현제 심화 부분보다 우선순위가 높은 작업이 남았다는 점에서 보류 또는 삭제 해도 괜찮을까요??

2023-06-28 18:21 UTC, JuwoongKim commented on voucher/src/test/java/com/example/voucher/VoucherApplicationTests.java
> +}
기본적으로 제공하는 테스트 또는, 제가 잘 못 설정하여 발생한 테스트라고 생각합니다.
다음부터는 주의해서 선별하고 올리도록하겠습니다!!

2023-06-28 18:22 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/repository/MemoryVoucherRepository.java
> +		return map.get(voucherId).getVoucherId();
가독성 측면에서 현재보다 좋다고 생각합니다. 반영해보도록 하겠습니다.

2023-06-28 19:28 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/PercentDiscountVoucher.java
> +		return beforeAmount * (percent / 100);
매직넘버는 불변 상수를 통해 대체하려 합니다.
값 검증에 대한 부분을 생각해야겠습니다. 값 검증에 대한 부분을 어떻게 구성할지 생각해보고 반영해보겠습니다.

2023-06-28 19:45 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/PercentDiscountVoucher.java
> +		return beforeAmount * (percent / 100);
값 검증에 대한 처리는 코드 재사용적인 관점에서 VoucherValidator라는 클래스로 묶고, 필요한 기능을 static 메서드로 제공하는 방식으로 하려합니다.

2023-06-29 04:50 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +			Voucher voucher = null;
[224742c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/224742c2362a272a3361df01fe9cb4323ac86068)

2023-06-29 04:53 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +		while (!isSatisfied) {
[224742c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/224742c2362a272a3361df01fe9cb4323ac86068) 
리펙토링 하는 과정에서 불필요하다 판단하여 삭제했습니다.

2023-06-29 04:55 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +					break;
[224742c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/224742c2362a272a3361df01fe9cb4323ac86068) 
switch expression을 사용하면서 중복되는 부분을 줄여봤습니다.

2023-06-29 04:58 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/FixedAmountVoucher.java
> +	private final long amount;
[72ad41e](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/72ad41e7b5697dbf7f06e01d8c6cefa80679bf49)
우선 순서를 변경해봤습니다.
공백은 import 문을 작성할 때 분리하는 것처럼 나눠봤습니다.

2023-06-29 05:00 UTC, JuwoongKim commented on voucher/src/test/java/com/example/voucher/repository/MemoryVoucherServiceTest.java
> +	@DisplayName("save 메서드 동작확인")
[a8b6c01](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/a8b6c01eec733f4d8508b64676feccf8c9c71342)
유닛테스트 메서드 네이밍 자료를 참고하여 given when then 느낌으로 구체화해봤습니다.

2023-06-29 05:10 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/repository/MemoryVoucherRepository.java
> +		return map.get(voucherId).getVoucherId();
[6ffa89b](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/6ffa89bd3e3aa6039de7a01ec449d82e74c85381)
반영했습니다!!

2023-06-29 05:12 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/PercentDiscountVoucher.java
> +		return beforeAmount * (percent / 100);
[f922731](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/f922731d2089e045009d135039af79549f74cb88)
불변 상수를 사용해 멤버변수를 대체했습니다.

2023-06-29 05:13 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +	}
[e64e7f7](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/e64e7f7d6c4f68bd469e6ba64ec88b67b8dcc463)
멤버 변수에 final 키워드를 추가했습니다.

2023-06-29 05:49 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +				case FixedAmount:
[224742c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/224742c2362a272a3361df01fe9cb4323ac86068)
위의 내용과 동일하게 리펙토링하는 과정에서 함께 수정했습니다.

2023-06-29 05:50 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +					isSatisfied = true;
[224742c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/674/commits/224742c2362a272a3361df01fe9cb4323ac86068)
반영했습니다!

2023-06-29 07:06 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/config/AppConfiguration.java
> +}
애플리케이션에서 필요한 객체 생성과 의존성 설정을 한 곳에서 관리할 수 있다는 점이 좋아서 Configuration을 사용했습니다.
또한 코드로 직접 의존성을 설정해줄 필요없이 AppicationContext에서 CommandLineApplicaTion만 꺼내와 실행시키면 된다는 점이 편했습니다.

2023-06-30 13:42 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/config/AppConfiguration.java
> +}
@JuwoongKim 객체들이 추가 하게 되면 Configuration 에 계속 추가 하게 되겠군요?
Bean 을 추가 하는 다른 방식은 없었을까요? 다른 방식에 비해 해당 방식은 어떠한 장점이 있나요?

2023-07-01 02:59 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/CommandLineApplication.java
> +			Voucher voucher = null;
224742c 커밋 피드백 반영 
- switch expression을 사용해 null 초기화 문제를 해결해봤습니다.

2023-07-01 02:59 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/PercentDiscountVoucher.java
> +		return beforeAmount * (percent / 100);
666f24bd505ac43a2f1040e78bc9f4a64f0137c4 커밋 피드백 반영 
- Validator 클래스르 만들고 메서드에 적용했습니다.

2023-07-01 02:59 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/enums/VoucherType.java
> +	Null("Null");
e278aa4 커밋 피드백 반영 
- Enum에섯 제공하는 메서드를 통해 값을 찾고, 값의 부재시 Optional을 통해 감싸는 방법으로 접근했습니다.

2023-07-01 03:51 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/config/AppConfiguration.java
> +}
빈으로 등록할 클래스를 어노테이션으로 명시한 뒤 컴포넌트 스캔을 통해 자동으로 빈을 등록하는 방법이 있습니다. 

해당 방식의 장점에 대한 생각은 다음과 같습니다.
1. 자동화를 통해 빈 등록에 대한 추가적인 코드 작성을 방지할 수 있습니다. 
2. 가동성이 높아집니다.
    - 사용자가 애너테니션을 보고 해당 객체가 빈으로 사용될 것이라는 것을 인지할 수 있습니다.
    - 스테레오 타입 애너테이션으로 역할도 쉽게 추 할 수 있습니다

애너테이션과 컴포넌트 스캔을 사용하는 방법으로 변경해보겠습니다!

2023-07-01 04:25 UTC, HyoungUkJJang commented on voucher/src/test/java/com/example/voucher/utils/lineAggregator/SpaceLineAggregatorTest.java
> +	}
@JuwoongKim 

단순히 확인 용도이지 테스트는 아닌 것 같아요 형상에 반영될 때 해당 부분은 포함되지 않아도 될 것 같은데 주웅님은 어떻게 생각하시나용 ?

2023-07-01 04:30 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/config/AppConfiguration.java
> +}
c2b134b922b544cd5e22c77b7f7df9dc3048d3bb 커밋 피드백 반영 
- 빈 설정 방식을 애너테니션 + 컴포넌트 스캔 기반으로  변경했습니다.

2023-07-01 04:33 UTC, JuwoongKim commented on voucher/src/test/java/com/example/voucher/utils/lineAggregator/SpaceLineAggregatorTest.java
> +	}
동일하게 생각합니다. 우선 해당 파일 삭제를 형상관리에 반영한 뒤 다음부터는 형상관리에 더욱 신경쓰도록 하겠습니다. 죄송합니다!

2023-07-01 04:37 UTC, JuwoongKim commented on voucher/src/test/java/com/example/voucher/utils/lineAggregator/SpaceLineAggregatorTest.java
> +	}
bec5d826059c330b4a45174ce2e4d45b50f5f1be 커밋 피드백 반영 
- 해당 파일을 삭제했습니다.

2023-07-01 04:44 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/utils/FieldExtractor.java
> +		return objects;
92f1674612591803db9164044dbdad981a6335f1 커밋 피드백 반영 
- 반영했습니다.

2023-07-02 10:36 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/enums/VoucherType.java
> +	Null("Null");
f0aee1750689689796f42c9e762106bad1e2c246 커밋 피드백 반영 (2차)
- .orElseThrow 메서드를 적용하여 Null 처리를 간소화 했습니다.

2023-07-02 10:38 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/domain/enums/VoucherType.java
> +		}
f0aee1750689689796f42c9e762106bad1e2c246 커밋 피드백 반영 (3차)
- 위의 내용과 동일합니다.
- .orElseThrow 메서드를 적용하여 Null 처리를 간소화 했습니다.

2023-07-02 10:39 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/io/ModeType.java
> +		}
fdd2e16cc7f09c78eede4b0e67993d6bc4382ffb 커밋 피드백 반영 (3차)
- VoucherType 내용과 유사합니다.
- .orElseThrow 메서드를 적용하여 Null 처리를 간소화 했습니다.

2023-07-02 10:43 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/repository/MemoryVoucherRepository.java
> +	private final Map<UUID, Voucher> map = new ConcurrentHashMap<>();
3987854703de81b4fd587789abd7f1e7a0a56dcb 커밋 피드백 반영 (2차)
- 명칭을 재변경 했습니다. voucherMap -> InMemoryDatabase

2023-07-02 10:56 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/config/AppConfiguration.java
> +}
0f72148e0d3f20ff14c9fa29e3ece937277abf74 커밋 피드백 반영 (2차)
- 애플리케이션 시작을 PostConstructor 에서  CommandLine Interface 적용으로 바꿨습니다.

2023-07-02 11:06 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/service/VoucherService.java
> +
49a24817e41ee86e7f86fdd4123d53edcc778197 커밋 피드백 반영 (2차)
- 1차에서 사용한 yield 키워드 삭제

2023-07-02 14:29 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/config/AppConfiguration.java
> +}
c61b597a0235a2968d706674465a57498c8733c6 커밋 피드백 반영 (3차)
- ComponetScan 애너테이션 삭제 -> SpringBootApplication이 해당 기능을 포함함
- 주석 처리한 설정파일 삭제
- Configuration 애너테이션의 올바른 사용방법에 대해 학습하고 정리하도록 하겠습니다.

2023-07-02 15:45 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/domain/enums/VoucherType.java
> +		}
@JuwoongKim 리뷰 의도를 잘못 파악 하신것 같아요. 1,2 숫자가 각 타입과 매핑을 보장할 수 없다고 보여요. 사람이 눈으로 확인 하여야 확인이 가능 한 구조라고 말씀드리고 싶었어요.

2023-07-02 15:45 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/io/ModeType.java
> +		}
위의 코멘트와 유사해요.

2023-07-02 17:02 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/io/ModeType.java
> +		}
0a195673d547f18895f434109d178bc542e91087 커밋 피드백 반영 (4차)
- 열거형의 불필요한 멤버변수를 삭제했습니다.
- 기존 멤버의 기능은 .name().toLowerCase()를 사용했습니다.

2023-07-02 17:20 UTC, JuwoongKim commented on voucher/src/main/java/com/example/voucher/utils/FieldExtractor.java
> +		List<Object> objects = new ArrayList<>();
2a4cc881756262874d0efa94dd654feb387fb01f 커밋 피드백 반영 
-  제네릭을 타입 안정성과 형변환의 안정성을 보장할 수 있음으로 Object를 대체함

2023-07-02 17:37 UTC, JuwoongKim commented
- PR 리뷰 반영 완료 했습니다.  

- 추가 구현사항은 다음과 같습니다.
  - 추가 기능사항으로 logback 설정 및 적용하였습니다. 
  - 예외처리를 수행했습니다. 
  - 커밋 범위 
    -  시작 : 1ac97a8 - feat : logback 사용을 위한 설정 파일 작성  
    - 끝 :  ac489f6 - [feat : create 명령어 수행 시 발생하는 예외 처리 및 에러 로그 기록

- 늦게 올리게 되어 죄송합니다!

2023-07-04 14:20 UTC, JuwoongKim commented
- 피드백 반영 및 추가 개선사항입니다.
  - 프로젝트 폴더 구조를 적용했습니다.
  - 멤버 변수 순서 변경 및 들여쓰기를 4 whliespace로 변경했습니다.
  - Enum 상수값 네이밍 및 반환로직을 valueOF() 메서드를 사용해 재 변경헀습니다, 
  - 커밋범위 

- 인터페이스 애너테이션 적용은 아직 반영하지 못했습니다.

2023-07-04 17:13 UTC, Jo-GyuHyeon commented on voucher/src/main/java/com/example/voucher/io/Console.java
> +public class Console {
해당 질문은 저와 함께 구두로 논의 하였기에 resolve 처리 할게요.

2023-07-06 16:36 UTC, Jo-GyuHyeon requested changes

2023-07-07 07:23 UTC, JuwoongKim commented on src/main/java/com/example/voucher/CommandLineApplication.java
> +        while (isOn) {
186434f48cf5526a9aebdcbc880c9b7a02842179 커밋 피드백 반영
- 불필요한 메서드 호출을 제거했습니다.

2023-07-07 07:26 UTC, JuwoongKim commented on src/main/java/com/example/voucher/CommandLineApplication.java
> +    public void createVoucherDetail() {
d526985451862202bc73ed80402a5c09cc6922df 커밋 피드백 반영 
- 접근지정자를 private으로 바꿨습니다.
- 접근지정자에 대해 깊게 생각하지 않고 사용했습니다. 고려하며  사용하도록 하겠습니다.

2023-07-07 07:28 UTC, JuwoongKim commented on src/main/java/com/example/voucher/CommandLineApplication.java
> +    public Voucher processVoucherType(VoucherType voucherType) {
d526985451862202bc73ed80402a5c09cc6922df 커밋 피드백 반영 
- 위의 내용과 동일합니다

2023-07-07 07:29 UTC, JuwoongKim commented on src/main/java/com/example/voucher/CommandLineApplication.java
> +    public void getVouchers() {
d526985451862202bc73ed80402a5c09cc6922df 커밋 피드백 반영 
- 위의 내용과 동일합니다

2023-07-07 07:29 UTC, JuwoongKim commented on src/main/java/com/example/voucher/CommandLineApplication.java
> +    public void createVoucher() {
d526985451862202bc73ed80402a5c09cc6922df 커밋 피드백 반영 
- 위의 내용과 동일합니다

2023-07-07 07:33 UTC, JuwoongKim commented on src/main/java/com/example/voucher/constant/ModeType.java
> +    public static ModeType getTypeMode(String typeName) {
25a35fb7bc5e214caad2be109d723ebc30e6cd46 커밋 피드백 반영 
- 네이밍을 변경했습니다. 신경쓰도록 하겠습니다.

2023-07-07 07:36 UTC, JuwoongKim commented on src/main/java/com/example/voucher/CommandLineApplication.java
> +        }
7a8d8d48ada5f28df093fd65beba19a10e81bc90 d526985451862202bc73ed80402a5c09cc6922df 커밋피드백 반영
- 불필요한 예외 메세지를 줄였습니다.
- 예외 처리를 담당하는 ExceptionHandler를 생성했습니다.

2023-07-07 07:37 UTC, JuwoongKim commented on src/main/java/com/example/voucher/CommandLineApplication.java
> +    public void processMode(ModeType mode) {
d526985451862202bc73ed80402a5c09cc6922df 커밋 피드백 반영 
- 접근지정자를 private으로 바꿨습니다.
- 외부 사용이 없는 클래스이기 때문에 private으로 접근을 막는 것이 적절하다 생각합니다.  
- 접근지정자에 대해 깊게 생각하지 않고 사용했습니다. 고려하며  사용하도록 하겠습니다.

2023-07-07 07:46 UTC, JuwoongKim commented
- PR 리뷰 반영 완료 했습니다.  

- 추가 구현사항은 다음과 같습니다.
  - 프로젝트의 전체 구조를 수정했습니다. 
  - 기존 VoucherController가 담당하는 흐름제어 역할을 ApplicaionConroller가 담당하도록 했습니다.
  - ApplicaionConroller는 모드 타입을 받고 모드 실행만 담당합니다.
  - ApplicaionConroller에서 사용자 입력값을 다 받고 VoucherController에게 데이터를 전달하기 위한 request용 래코드를 생성했습니다.
  - VoucherController는 바우처 타입별 분기를 주어 바우처를 생성하고, 전체 조회를 요청을 담당하도록 했습니다.
  - 기존 Console의 읽기 쓰기 기능을 Reader와 Writer로 분리하고, Console은 조건에 따라 요청하도록 했습니다.
  - Validator, ExceptionHandler 유틸 클래스를 추가했습니다.

  - 커밋 범위 
    -  시작 : d526985451862202bc73ed80402a5c09cc6922df 전체 프로그램을 제어하는 ApplicationController 생성 
    - 끝 :  186434f48cf5526a9aebdcbc880c9b7a02842179 ApplicaionController에서 불필요한 메서드 호출 제거

2023-07-08 01:08 UTC, Jo-GyuHyeon requested changes
간단히 리뷰 남겼어요.
고생하셨어요. 😄

2023-07-08 01:08 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/io/Console.java
> +    }
단순히 writer 기능을 감싸기만 하고 있다면 writer 를 사용 해도 되지 않을까요???

2023-07-08 01:08 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/io/Console.java
> +    }
위와 동일 한 내용인것 같아요. reader 를 단순히 감싸기만 한다면 해당 메서드들이 존재 하는 이유는 무엇일까요?

2023-07-08 01:08 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/utils/ExceptionHandler.java
> +    }
두가지 조건 문에서 동일하게 처리 하는데, 조건을 나뉠 필요가 있을까요?

2023-07-08 01:08 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/utils/lineAggregator/SpaceLineAggregator.java
> +}
현재 사용 되는 곳이 없는것 같아요. 확인 부탁 드려요.

2023-07-08 01:08 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/utils/FieldExtractor.java
> +}
FieldExtractor 는 SpaceLineAggregator 이외 사용되지 않는것 같아요. 
SpaceLineAggregator 는 현재 사용되지 않는것 같은데 확인 부탁 드려요.

2023-07-08 02:42 UTC, HyoungUkJJang requested changes
안녕하세요 주웅님 리뷰 반영하느라 고생이 많으시네요 :) 

먼저 규현 멘토님께서 추가 코멘트를 잘 남겨주셔서 저는 몇개 남길게 없네요 ㅎㅎ 그래도 참고 부탁드려요 ~👍🏻

+ 개인적인 의견으로 컨벤션이 좋아진 것 같지만 개행처리가 과한 느낌도 있습니다 이부분에 대해서 한번 더 생각해보시면 좋을 것 같아요 ! 다음에 구두로 게더에서 이야기 나눠봐도 좋을 것 같습니당 ☺️

2023-07-08 02:42 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/ApplicationController.java
> +    private boolean isOn = true;
여기에 있어야 하는 이유가 있을까요?

2023-07-08 02:42 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/ApplicationController.java
> +            return null;
ModeType에 다른 의미 있는 값을 부여해주는건 어떻게 생각하시나요?

2023-07-08 02:42 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/ApplicationController.java
> +            ModeType selectedModeType = Validator.validateModeTypeMatch(input);
문자열의 input 값이 `validateModeTypeMatch()` 메서드에서 검증을 하고 ModeType을 반환까지 하는 것 같아요 
책임이 두개처럼 느껴지는데 주웅님의 생각은 어떠신가요?

2023-07-08 02:42 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/ApplicationController.java
> +    }
과한 개행처리도 좋은 건 아닌 것 같아요 :) 한번 더 생각해보시면 좋을 것 같습니다 ~

2023-07-08 02:42 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/controller/VoucherController.java
> +            .collect(Collectors.toList());
`toLost()`를 사용하면 어떤 차이점이 있을까요?

2023-07-08 02:42 UTC, HyoungUkJJang commented on src/test/java/com/example/voucher/repository/MemoryVoucherServiceTest.java
> +	}
어떤 테스트일까요?

2023-07-08 16:07 UTC, JuwoongKim commented on src/test/java/com/example/voucher/repository/MemoryVoucherServiceTest.java
> +	}
a33e7687ff50cccfc7adbcc8d5d75f474e4d2df9 커밋 피드백 반영 
- 불필요한 테스트임으로 삭제했습니다. 주의하겠습니다.

2023-07-08 16:08 UTC, JuwoongKim commented on src/main/java/com/example/voucher/ApplicationController.java
> +    }
f7f6c02797a5830bb764d047fba5c267f7a9166c 커밋 피드백 반영 
- 불필요한 개행처리 삭제했습니다.

2023-07-08 16:11 UTC, JuwoongKim commented on src/main/java/com/example/voucher/ApplicationController.java
> +            ModeType selectedModeType = Validator.validateModeTypeMatch(input);
f7f6c02797a5830bb764d047fba5c267f7a9166c 커밋 피드백 반영
- 입력값은 콘솔에게, 타입검증은 ModeType에게 책임을 할당하는 방법으로 수정했습니다.

2023-07-08 16:13 UTC, JuwoongKim commented on src/main/java/com/example/voucher/ApplicationController.java
> +    private boolean isOn = true;
f7f6c02797a5830bb764d047fba5c267f7a9166c 커밋 피드백 반영
- 멤버변수 사용시 원하지 않는 방법으로 사용될 경우가 있다고 생각합니다. 해당 변수를 지역변수로 변경했습니다.

2023-07-08 16:20 UTC, JuwoongKim commented on src/main/java/com/example/voucher/ApplicationController.java
> +            return null;
1b7e5d4af786b78942e9e2de031ba9a853b09d81 커밋 피드백 반영 
- NONE 상수를 추가해 예외 발생 시 반환하도록 했습니다.
- 의미전달이나, 요청과 응답 측면에서 의미 있는 값을 부여해주는게 좋다고 생각했습니다.

2023-07-08 16:28 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/VoucherController.java
> +            .collect(Collectors.toList());
8d85d942bc60f9a782f8379c841441a14f3df59c 커밋 피드백 반영 
- JAVA16에 도입된 동일 기능을 제공 메서드입니다.
- 훨씬 간결하다고 생각햐어 수정했습니다.
- 기존에 제공하는 메서드를 좀 더 신중히 살펴보도록 하겠습니다.

2023-07-08 16:29 UTC, JuwoongKim commented on src/main/java/com/example/voucher/utils/FieldExtractor.java
> +}
b38d72c5b7f01789c22daacccb122fe9986846ae 커밋 피드백 반영 
- 불필요한 파일 삭제했습니다.

2023-07-08 16:29 UTC, JuwoongKim commented on src/main/java/com/example/voucher/utils/lineAggregator/SpaceLineAggregator.java
> +}
b38d72c5b7f01789c22daacccb122fe9986846ae 커밋 피드백 반영 
- 불필요한 파일 삭제했습니다.

2023-07-08 16:34 UTC, JuwoongKim commented on src/main/java/com/example/voucher/utils/ExceptionHandler.java
> +    }
b38d72c5b7f01789c22daacccb122fe9986846ae 커밋피드백 반영 
- 하나의 Exception으로 통일했습니다.
- ExceptionHandler를 삭제하고 객체의 책임에 범위에 맞게 예외처리를 적용했습니다.

2023-07-08 16:36 UTC, JuwoongKim commented on src/main/java/com/example/voucher/io/Console.java
> +    }
f7f6c02797a5830bb764d047fba5c267f7a9166c 커밋 피드백 반영 
- Console에게 입력값을 만족시켜 제공한다는 책임을 할당하도록 수정했습니다.

2023-07-08 16:37 UTC, JuwoongKim commented on src/main/java/com/example/voucher/io/Console.java
> +    }
c533659a79227b267b8c86beec07afb3ef9bdb1b 커밋 피드백 반영 
- 불필요한 메서드를 삭제하고 writer를 사용하도록 했습니다.

2023-07-08 16:48 UTC, JuwoongKim commented on src/main/java/com/example/voucher/domain/FixedAmountVoucher.java
> +    public long discount(long beforeAmount) {
8b705b08b93c36712276156baa8f691de1aafa22
- 원래 값이라는 측면에서 originalAmount로 수정했습니다.

2023-07-08 16:53 UTC, JuwoongKim commented on src/main/java/com/example/voucher/domain/FixedAmountVoucher.java
> +    VoucherType voucherType = VoucherType.FIXED_AMOUNT_DISCOUNT;
10842df6d783aec8d46be63395ce82c18fc61f1a 커밋 피드백 반영 
- 객체 상태에 직접 접근하지 못하도록 접근제어자를 private으로 변경했습니다.
- 앞으로 접근제어자 신중히 고려하여 사용하곘습니다.

2023-07-08 16:56 UTC, JuwoongKim commented on src/main/java/com/example/voucher/io/Writer.java
> +    }
9d66382ede3b79c11079301d41eb2d662327d0dc 커밋 피드백 반영 
- 동일하다는 점에서 하나의 메서드로 통일했습니다.
- 변화에 대한 요소는 VoucherType 입력값으로 구분하고록 했습니다.
- 또한 파라미터 입력에 대한 안정성을 위해 String대신 상수를 사용하도록 했습니다.

2023-07-08 17:18 UTC, JuwoongKim commented on src/main/java/com/example/voucher/utils/lineAggregator/LineAggregator.java
> +package com.example.voucher.utils.lineAggregator;
b38d72c5b7f01789c22daacccb122fe9986846ae 커밋 피드백 반영 
- 신경쓰도록 하겠습니다.
- 불필요한 패키지는 삭제헸습니다.

2023-07-08 17:21 UTC, JuwoongKim commented on src/main/java/com/example/voucher/constant/VoucherType.java
> +    private final Integer inputNum;
b8b7ba08861f7a71f6703a08bec925025dc76a42 커밋 피드백 반영 
- 크게 고려하지 않고 사용했습니다.
- 앞으로 Wrapper 클래스의 기능이 불필요할 시 원시타입을 사용해 효율적으로 사용하도록 하겠습니다.
- 주의해서 사용하도록 하겠습니다.

2023-07-08 17:22 UTC, JuwoongKim commented on src/main/java/com/example/voucher/ApplicationController.java
> +        }
f7f6c02797a5830bb764d047fba5c267f7a9166c 커밋 피드백 반영
- 멤버변수 사용시 원하지 않는 방법으로 사용될 경우가 있다고 생각합니다. 해당 변수를 지역변수로 변경했습니다.

2023-07-08 22:58 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/VoucherController.java
> +        }
a2a5ecbb1ae70a8dad5329cb59c052b7b5d43865 커밋 피드백 반영 
- 바우처 생성 요청에 대한 예외처리 책임을 ApplicaionController에 할당했습니다.
- 예외 종류에 따른 분기가 이뤄지지 않기때문에 Exception으로 받도록 했습니다.

2023-07-08 23:10 UTC, JuwoongKim commented
- PR 리뷰 반영 완료 했습니다.  

- 추가 구현사항은 없습니다.

감사합니다.

2023-07-09 05:23 UTC, JuwoongKim commented
- PR 리뷰 반영 완료 했습니다.
  -  22dde0cd2df10b9a30841b129fb0fcfad86de1d8
  -  기존 Console에서 판단하는 행위는 역할에 맞지 않고, 불필요하기때문에 삭제했습니다.

- 추가 내용 
  - 콘솔은 입력값을 제공하는 책임, VoucherController는 바우처 기능에 대한 값을 제공하는 책임을 
   할당했기 때문에 예외처리를 해당 객체에서 하도록했습니다. 

  - 또한 예외처리가 필요한 부분에 Logger를 사용해 기록하도록 했습니다.
   
  - ApplicationController는 입값값, 바우처기능 결과값을 받고 분기처리하는 책임을 할당했습니다. 

  - 예외도 하나의 응답이라고 생각해 무조건 ApplicationController에서 tryCatch를 사용했으나 
   책임이 있는 곳에서 처리하고 특정 값을 반환하는게 깔끔하다고 생각해 위의 방식으로 구현했습니다.

- 추가 구현사항은 없습니다!

2023-07-09 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            console.displayVoucherCreationError();
console.getDiscountValue() 내부에서 console.displayVoucherCreationError() 로직과 중복되기에 해당 라인은 제거 해도 될것 같아요.

2023-07-09 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            console.displayVoucherCreationError();
console.getVoucherType() 내부에서 console.displayVoucherCreationError() 로직과 중복되기에 해당 라인은 제거 해도 될것 같아요.

2023-07-09 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/controller/VoucherController.java
> +
개행 신경 써주세요.

2023-07-09 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/io/Console.java
> +
개행 신경 써주세요.

2023-07-09 06:04 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            console.displayVoucherCreationError();
61614a042449056fb51cd9aaac1bafa969538e0b 커밋피드백 반영 
- 해당 메서드를 제거했습니다.

2023-07-09 06:04 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            console.displayVoucherCreationError();
61614a042449056fb51cd9aaac1bafa969538e0b 커밋피드백 반영 
- 해당 메서드를 제거했습니다.

2023-07-09 06:05 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/VoucherController.java
> +
61614a042449056fb51cd9aaac1bafa969538e0b 커밋피드백 반영 
- 불필요한 개행 삭제했습니다.

2023-07-09 06:05 UTC, JuwoongKim commented on src/main/java/com/example/voucher/io/Console.java
> +
61614a042449056fb51cd9aaac1bafa969538e0b 커밋피드백 반영 
- 불필요한 개행 삭제했습니다.

2023-07-09 06:06 UTC, JuwoongKim commented
- PR 리뷰 반영 완료 했습니다.
- 추가 구현 기능 없습니다.

2023-07-09 06:12 UTC, Jo-GyuHyeon approved these changes
바우처 위클리 1 미션 하시느라 고생 많으셨어요.
심화는 일정상 생략을 권유 드리고 싶어요.
위클리 2 미션도 잘 해내시리라 생각해요.
고생 많으셨어요. 🙇

2023-07-09 07:43 UTC, JuwoongKim commented
부족한 점이 많은데 기다려주시고 많은 부분을 생각해보게 해주셔서 감사합니다. 
학습한 점을 바탕으로 더욱 발전하고 잘하도록 하겠습니다.
정말 감사드립니다!!  🙇🙇🙇

2023-07-09 13:24 UTC, merged