[4기 - 전선희] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다!
prgrms-be-devcourse/springboot-basic pull request #677
Opened 2023-06-24 11:48 UTC by funnysunny08

## 📌 과제 설명 
4주차 강의에서 배운 내용들을 활용하여 Voucher Service 구현하였습니다! <br>
아직 로그와 jar 단계는 수행하지 않았습니다! 빠르게 해서 다시 올리겠습니다!
## 👩‍💻 요구 사항과 구현 내용 

- [X]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 
- [X]  바우처 관리 Command-line Application을  만들어본다.
   
    - [X]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌   파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
제가 클래스를 잘 분리하고 Controller, service,.. 이러한 역할을 잘 부여한 건지 궁금합니다! <br>
Bean 설정은 적절하게 한건지 궁금합니다!

2023-06-25 07:40 UTC, JoosungKwon reviewed
안녕하세요 선희님! 과제하시느라 고생많으셨습니다~~ 👍
간단하게 리뷰 남겨드렸습니다~! 확인 부탁드립니다~~ 😄

질문 주신 내용에 답변을 드리자면

> 제가 클래스를 잘 분리하고 Controller, service,.. 이러한 역할을 잘 부여한 건지 궁금합니다!

- 아직 부족한 점이 있는 것 같아요.. 😂 각 레이어의 역할과 목적에 대해 조금 더 공부해보시면 좋을 것 같습니다!! 

> Bean 설정은 적절하게 한건지 궁금합니다!

- 이 질문은 의도를 정확하게 모르겠습니다.. 😅 Spring의 Bean 등록하는 방법을 다시 공부해보시면 좋을 것 같아요.

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/domain/voucher/Voucher.java
> +public interface Voucher {
왜 Voucher를 `Interface`로 하셨는지 궁금합니다~! `Interface`와 `Abstract Class`를 각각 어떤 상황에 사용해야 한다고 생각하시나요?

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/domain/voucher/FixedAmountVoucher.java
> +    }
다른 곳은 `Getter`를 사용하셨던데 여기는 사용하지 않으시는 이유가 있나요? 일관성을 지키면 좋을 것 같습니다~!!

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@AllArgsConstructor
`AllArgsConstructor` 와 `RequiredArgsConstructor` 차이점을 아시나요~?

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@Controller
`AppRunner`를 `Controller`로 보기에는 적절하지 않은 것 같습니다. 선희님은 어떻게 생각하세요~?

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/domain/voucher/FixedAmountVoucher.java
> +    }
정적 팩토리 메소드를 사용하신 이유가 궁금합니다~!

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +        List<Voucher> voucherList = new ArrayList<>(vouchers.values());
처음부터 `voucherList = new ArrayList<>(vouchers.values())`를 반환하는게 나을 것 같은데 어떻게 생각하시나요? `voucherRepository`에서 `Map`을 반환하시고 계신 특별한 이유가 있나요?

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +            }
각 `Voucher` 객체의 `@toString` 을 재정의해서 사용하시는건 어떠신가요?

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +        }
`VoucherType`에서 생성하거나 혹은 팩터리를 만들어도 좋을 것 같아요~

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +    public void createVoucher() {
흐름을 읽기 약간 어려운 것 같아요! 😢 메서드 혹은 클래스로 적절하게 분할하거나 가독성을 높일 수 있는 방안을 고민해보시면 좋을 것 같습니다!

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/AppRunner.java
> +    public void run() {
예외를 처리하는 곳은 없나요~?

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/domain/voucher/FixedAmountVoucher.java
> +    private final long discount;
`discount`의 값의 범위를 검증할 필요가 있을 것 같네요~~

2023-06-25 07:40 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +        System.out.println("\n정상적으로 바우처가 등록되었습니다.\n");
`Controller`에서 `View`를 분리할 필요가 있어보입니다!

2023-06-25 23:47 UTC, graygreat requested changes
안녕하세요 선희님~~
과제 진행하시느라 고생하셨습니다 👍 

리뷰 남겨놨으니 확인 부탁드려요~

> 제가 클래스를 잘 분리하고 Controller, service,.. 이러한 역할을 잘 부여한 건지 궁금합니다!

잘하고 계십니다! 하지만 아직 훈련이 조금 더 필요한 것 같아요.
역할, 책임을 부여할 때, 내가 이 프로젝트의 서브 팀원이라면 처음 이 기능을 리팩토링 해야한다고 가정할 때, 어떤 파일을 먼저 볼까? 라는 생각을 하곤 합니다. 그 파일에 있을 것 같다는 추측은 그 파일에서 해당 역할을 하고 있을거라고 생각하고 있기 때문이죠. 선희님도 코드를 많이 짜보시고 책도 많이 읽으셔서 나름의 방식을 터득하시면 좋을 것 같아요.

> Bean 설정은 적절하게 한건지 궁금합니다!

저도 해당 질문의 의도를 정확히 모르겠네요 (__)

2023-06-25 23:47 UTC, graygreat commented on src/main/java/com/prgrms/spring/AppRunner.java
> +                System.out.println(mt.getName() + " -> " + mt.getExplain());
만약 선희님이 이 프로젝트를 기획자들과 함께 한다고 가정하면, 기획자가 menu 보여줄 때, "->" 가 아니라 "==>"으로 바꿔달라고 하면 어떤 파일을 젤 먼저 열어보실 것 같으신가요?

2023-06-25 23:47 UTC, graygreat commented on src/main/java/com/prgrms/spring/domain/voucher/VoucherType.java
> +                .orElseThrow(IllegalStateException::new);
예외 메시지도 같이 던져주면 더 명확하겠네요 :)

2023-06-25 23:47 UTC, graygreat commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +        } else if (type == VoucherType.PERCENT_DISCOUNT) {
분기문을 사용하지 않고 어떻게 구현할 수 있을지 한번 생각해보시면 좋을 것 같아요!

2023-06-30 05:56 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/infrastructure/voucher/MemoryVoucherRepository.java
> +package com.prgrms.spring.infrastructure.voucher;
특별한 이유는 없구.. 그전에 해 온 자바 프로젝트에서 infrastructure라는 패키지에 repository 파일들을 보관해서 사용하였습니다! 😅

2023-06-30 05:56 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +    private VoucherRepository voucherRepository;
까먹었습니다...!🥲

2023-06-30 05:58 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/config/AppConfiguration.java
> +}
혹시 직접적으로 Bean 등록할 클래스가 있지 않을까 해서 초반에 만들어 놓았습니다.. 삭제했습니다!!

2023-06-30 06:04 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/domain/voucher/Voucher.java
> +public interface Voucher {
음.. `interface`는 해당 메서드를 각 클래스의 목적에 맞게 기능을 구현하는 느낌이고, `abstract class`는 기능을 확장시켜 가는 느낌이라고 알고는 있습니다..! 
근데 사실 강의에서 interface를 사용하기도 했고 보편적으로 많이 쓰는 것 같아서 저도 interface를 사용한 거지 아직은 명확하게 구분 짓기 힘든 것 같아요ㅠㅠ

2023-06-30 06:06 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/domain/voucher/FixedAmountVoucher.java
> +    }
`FixedAmountVoucher`에 Getter를 사용하면 `Voucher.getVoucherId()`가 불가능하더라구요.. 그래서 직접 정의하였습니다🥲

2023-06-30 06:07 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@AllArgsConstructor
`AllArgsConstructor`는 모든 필드가 포함된 생성자, `RequiredArgsConstructor`는 필수로 들어가야 하는 필드 (final, notnull,..)가 포함된 생성자를 만드는 것으로 알고있습니다!

2023-06-30 06:08 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@Controller
저도 `Controller`는 조금 억지인 것 같다는 생각이 드네요..`@Component`로 바꿨는데 어떨까요..?!

2023-06-30 06:10 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/domain/voucher/FixedAmountVoucher.java
> +    }
객체 생성 캡슐화를 할 수 있는 것으로 알고있습니다! 스프링 공부하면서 이것저것 적용해봤습니다.....!ㅎ

2023-06-30 06:12 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +        List<Voucher> voucherList = new ArrayList<>(vouchers.values());
`controller` 단보다 `service`단에서 데이터를 가공하는 것이 더 좋지 않을까~ 혼자 생각해봤습니다..ㅎ

2023-06-30 06:22 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/config/AppConfiguration.java
> +public class AppConfiguration {
혹시 직접적으로 Bean 등록할 클래스가 있지 않을까 해서 초반에 만들어 놓았습니다.. 삭제했습니다!!

2023-06-30 06:24 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/AppRunner.java
> +                System.out.println(mt.getName() + " -> " + mt.getExplain());
menu 관련 파일이나 console,output 관련 파일을 가장 먼저 열어볼 것 같습니당..!

2023-06-30 06:24 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +        System.out.println("\n정상적으로 바우처가 등록되었습니다.\n");
넵!! 리뷰 확인했습니다 감사합니다!!!😽

2023-06-30 06:24 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +        } else if (type == VoucherType.PERCENT_DISCOUNT) {
넵!! 리뷰 모두 확인했습니다 감사합니다!!!😽

2023-06-30 11:28 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/infrastructure/voucher/MemoryVoucherRepository.java
> +package com.prgrms.spring.infrastructure.voucher;
패키지 명에 정답은 없지만 보편적일수록 알아보기 쉽고 팀원들과 합의를 이루기 편합니다~!!

2023-06-30 11:33 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/domain/voucher/Voucher.java
> +public interface Voucher {
무엇이 정답이다라고 구분짓기 모호한 편이긴합니다..😅 `Voucher`의 경우도 `interface`로 하셔도 되고` abstract class`로 하셔도 됩니다. 다만, 중요한 것은 본인의 주관과 근거입니다.!! 그리고 해당 내용은 면접에서도 자주 나오는 질문입니다! 
따라서, 추가적으로 좀 더 공부해보시면 좋을 것 같아요~[Interface와 Abstract class 의 차이](https://www.inflearn.com/questions/236439/interface%EC%99%80-abstract-class-%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90)

2023-06-30 11:35 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@AllArgsConstructor
해당 클래스에서는 `RequiredArgsConstructor`가 더 적절하다고 생각하는데 어떻게 생각하시나요~?

2023-06-30 11:35 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@Controller
@Component가 더 적절한 것 같습니다~!

2023-07-24 10:08 UTC, merged