[4기-황준호] 도메인 객체 생성 및 컨트롤러, view 구조 생성
prgrms-be-devcourse/springboot-basic pull request #684
Opened 2023-06-25 01:20 UTC by juno-junho

## 📌 과제 설명

도메인 객체 생성
- Voucher 인터페이스를 구현한 FixedAmountVoucher 생성 및 테스트
- Voucher 인터페이스를 구현한 PercentDiscountVoucher 생성 및 테스트
- Currency 값 객체 생성 및 테스트
- view 및 controller 구조 생성

## 👩‍💻 요구 사항과 구현 내용 
- 먼저 README.md에 기능목록을 작성하고 도메인 객체를 생성했습니다.
- 각 입력 값에 대해서 예외 처리를 해 주고 테스트를 작성했습니다.
- view를 interface를 통해 윤곽을 잡았고, Controller 에서 주입을 다음과 같이 받음으로서 구조를 잡았습니다.
- 도메인 객체들은 불변 객체들로 만들었습니다.
- `Currency` 클래스에서는 가독성과 추후 확장성을 고려하여 정적 팩토리 메서드를 사용하였습니다.
- view로 Voucher list를 넘길 경우 String list로 변환하여 넘길 예정입니다. (view에서는 domain 객체를 의존하는게 잘못된 방법이라 생각하여 변환할 생각입니다.)

## ✅ 피드백 반영사항  
- 추후 업데이트 예정

## ✅ PR 포인트 & 궁금한 점
- FixedAmountVoucher와 PercentDiscountVoucher가 각각 할인율이나 할인 금액이 같더라도 다른 voucher임을 보장하기 위해서 상태값으로 id를 추가했습니다. 나중 DB랑 연결까지 고려한다면 id값이 있는것이 좋을것 같아 추가했습니다.
하지만 궁금한 점이 이번주차 강의에서는 강사님이 id를 식별하기 위해서 UUID를 사용하시던데, 저는 UUID를 사용하는 것은 데이터베이스에서 UUID를 PK로 설정을 통해 인덱스를 설정할때 메모리 소비가 일반 long 타입에 비해서 훨씬 클것 같아 지양했습니다. 사실 사용하는 이유가 명확하지 않아 사용하지 않았습니다.
이 UUID를 통해 ID 값을 관리하는 것에 대해서 사실 어떠한 이점이 있는지 잘 모르겠습니다.

- 테스트를 꼼꼼하게 작성하려 노력했습니다. DisplayName을 작성해 가독성을 높혔는데, 테스트 메서드 이름을 어떻게 작성하는게 좋을지 여쭤보고 싶습니다. 한글로 `_`를 통해서 짓는것 같은데 이것이 junit4때의 관습이라고 들었습니다. 현업에서의 테스트 작성 방법이 궁금합니다!

- given / when / then 을 명시하는 것이 좋은지 궁금합니다. given when then을 명시하는 것 보다 줄을 한칸 띄움으로서 구분지었는데 given when then을 명시하면 코드블록이 커지는 단점때문에 명시하지 않았는데 명시하는 것이 필수적이며 좋은지 (이것도 현업에서는 어떻게 사용하는지) 궁금합니다.

2023-06-25 07:40 UTC, devcourse-ray requested changes
고생하셨습니다.
이전 PR 먼저 확인 후 여기 PR 리뷰 확인해주세요.



- FixedAmountVoucher와 PercentDiscountVoucher가 각각 할인율이나 할인 금액이 같더라도 다른 voucher임을 보장하기 위해서 상태값으로 id를 추가했습니다. 나중 DB랑 연결까지 고려한다면 id값이 있는것이 좋을것 같아 추가했습니다.
하지만 궁금한 점이 이번주차 강의에서는 강사님이 id를 식별하기 위해서 UUID를 사용하시던데, 저는 UUID를 사용하는 것은 데이터베이스에서 UUID를 PK로 설정을 통해 인덱스를 설정할때 메모리 소비가 일반 long 타입에 비해서 훨씬 클것 같아 지양했습니다. 사실 사용하는 이유가 명확하지 않아 사용하지 않았습니다.
이 UUID를 통해 ID 값을 관리하는 것에 대해서 사실 어떠한 이점이 있는지 잘 모르겠습니다.
> UUID는 long 타입으로 커버가 되지 않는 범위에서는 사용을 해야하는 상황이 있습니다.
예를들어 유저를 저장한다 라고 하면 전세계 인구가 70억인데 이 서비스를 전세계인이 다 사용한다해도 70억 정도의 유저가 나오겠죠?
이런 경우에는 굳이 UUID는 필요가 없겠네요.
테이블의 sequential한 pk 값이 endpoint 혹은 query string에 노출되는 경우가 많을텐데 이 경우에 다른 row의 id를 유추할 수도 있어서 보안상의 이유로 UUID를 쓰기도 합니다.
또, 말씀하신대로 UUID는 랜덤으로 생성되면 DB 인덱스와 관련해서 성능 문제가 생길 수 있습니다.
이걸 잘 고려한다면 조회에 비해 저장이 일어나는 횟수가 현저히 적은경우에 사용할 수 있겠네요.
물론 UUID도 여러 버전들이 있어서 각 버전마다 성능의 차이는 있습니다.
어떤 UUID들이 있고 각 버전별로 어떤식으로 생성이 되는지, 어떤걸 사용해야 유리한지도 같이 고민해봐야 할 문제라고 생각합니다.

- 테스트를 꼼꼼하게 작성하려 노력했습니다. DisplayName을 작성해 가독성을 높혔는데, 테스트 메서드 이름을 어떻게 작성하는게 좋을지 여쭤보고 싶습니다. 한글로 _를 통해서 짓는것 같은데 이것이 junit4때의 관습이라고 들었습니다. 현업에서의 테스트 작성 방법이 궁금합니다!
> 제가 현업에서는 코틀린을 쓰다보니 kotest 라는 프레임워크를 사용합니다.
거기서 제공하는 기능 덕분에 이런 고민을 한적이 없고, 현업에서 실제 사용중인 예시를 들어드리긴 애매하지만 정해진 건 없습니다.
테스트는 누가봐도 명확하게 어떤 행위에 대한 어떤 결과가 나온다고 표현되어있는게 좋습니다.
어떤 방식으로 작성하더라도 테스트 내용만 잘 표현된다면 저는 괜찮다고 봅니다.
이러한 방식들은 팀의 컨벤션에 따라 달라질 수 있기 때문에 지금은 준호님만의 하나의 규칙을 가지고 작성을 해보시고 나중에 입사하게 되면 팀에서 맞춘 컨벤션에 따라 작성하시는게 가장 좋을 것 같아요.

- given / when / then 을 명시하는 것이 좋은지 궁금합니다. given when then을 명시하는 것 보다 줄을 한칸 띄움으로서 구분지었는데 given when then을 명시하면 코드블록이 커지는 단점때문에 명시하지 않았는데 명시하는 것이 필수적이며 좋은지 (이것도 현업에서는 어떻게 사용하는지) 궁금합니다.
> 이것도 마찬가지로 어느 팀에 가냐에 따라 컨벤션이 나뉘겠지만 저는 개인적으로는 표현해주면 가독성은 좀 더 올라간다고 생각합니다.
정확히 어디까지가 사전 조건이고 어디가 테스트를 해야하는 핵심 부분이고 어디가 결과비교인지 한 눈에 보인다는 장점이 라인 수가 늘어난다는 단점을 충분히 커버한다고 생각해서 작성하는게 좋다는 입장입니다.
[제가 주로 사용하는 테스트 프레임워크](https://kotest.io/docs/framework/testing-styles.html)에는 다양한 방법으로 테스트를 표현하도록 제공하는데 다른 언어긴 하지만 테스트를 어떤 흐름으로 검증하는지는 예시로 볼만해서 링크 하나 첨부드립니다.
언어나 프레임워크를 공부하라는건 아닙니다.
이런 테스트 스타일들이 있구나 정도로만 보시면 좋을 것 같네요.

2023-06-25 07:40 UTC, devcourse-ray commented on voucher/src/main/java/com/ray/junho/voucher/domain/Currency.java
> +    }
currency가 어떤 voucher가 있는지 알아야할까요?

2023-06-25 07:40 UTC, devcourse-ray commented on voucher/src/main/java/com/ray/junho/voucher/domain/FixedAmountVoucher.java
> +    }
할인에 대한 로직을 바우처가 아니라 Currency가 가지게 되면 어떤 부수효과들이 생길까요?

2023-06-25 07:40 UTC, devcourse-ray commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        }
예외 메시지랑 조건이 다르네요

2023-06-25 07:40 UTC, devcourse-ray commented on voucher/src/test/java/com/ray/junho/voucher/domain/PercentDiscountVoucherTest.java
> +    }
0인 경우와 100인 경우가 성공/실패가 갈리는 이유가 있나요?

2023-06-25 10:48 UTC, ICCHOI reviewed
준호님 수고하셨습니다..! 
간단하게 코멘트 남겼으니 확인 부탁드려요!

2023-06-26 14:53 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/controller/CommandLineController.java
> +    private final VoucherRepository voucherRepository;
아 넵 service에서만 repository를 의존하도록 수정하겠습니다!
생각없이 controller를 만든 것 같네요.

2023-06-26 14:54 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/Currency.java
> +    }
currency의 책임에 대해서 다시 한번 생각해 보겠습니다.
discount에 대한 비즈니스 로직은 currency가 아닌 voucher 객체가 가지고 있는게 더 맞는것 같네요 👍

2023-06-26 14:56 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        }
넵 수정하겠습니다!

2023-06-26 14:58 UTC, juno-junho commented on voucher/src/test/java/com/ray/junho/voucher/domain/PercentDiscountVoucherTest.java
> +    }
제가 생각하기에 `PercentDiscountVoucher` 는 할인을 해주는 기능이 있어야 한다고 생각했습니다.
따라서 그럼 할인율의 범위는 어떻게 될까 생각해보니, 100퍼센트 할인권(바우처)는 발급 가능하며 사용가능하지만
0퍼센트 할인권(바우처)는 발급이 무의미해 발급을 막아야 겠다는 생각을 했습니다.
따라서 할인 비율의 범위를 0 초과, 100 이하로 설정한 것입니다.

2023-06-26 15:32 UTC, juno-junho commented on voucher/src/test/java/com/ray/junho/voucher/domain/PercentDiscountVoucherTest.java
> +    }
UUID에 대해서 정리를 하자면
1. Long 타입 범위 (약 920경) 을 초과하는 수의 id 발급이 필요할 경우 사용한다
2. pk 값이 사용자에게 보여지는 쿼리 파라미터를 통해 보여지는 일이 많을것이기에 보안상으로 사용한다.
3. 데이터베이스 부하가 커 조회(read) 보다 생성(write)이 현저히 적게 일어날 경우 사용하는 것이 적합하다.
라고 정리할 수 있겠네요.

UUID에 대해서 잘 몰랐는데 이번기회를 통해 한번 찾아 보았습니다.
### UUID
- UUID(Universally Unique Identifier)는 범용 고유 식별자를 의미하며 중복되지 않는 유일한 값을 구성하고자할때 주로 사용된다.
- 주로 세션 식별자, 쿠키 값, 무작위 데이터 베이스 키 등에 사용이 된다 (말씀해 주신 보안상의 이유와 상통하는 것 같습니다)
- UUID의 길이는 36자리이며 4개의 `-` 와 32개의 16진수 문자열로 구성되어 있습니다.
- UUID의 버전에는 총 5개의 버전이 존재합니다.
    - version1: 타임스탬프와 랜덤한MAC 주소를 기준으로 생성하는 방식 -> 유일성 보장되지만 보안에 취약하다.
    - version2:  POSIX (Portable Operating System Interface) (운영체제간 호환성 유지하기 위한 표준)의 UID(User ID)를 version1과 함께 사용하는 방식입니다.
    - version3: "MD5 해시"(해시함수) 를 기반으로 이름과 네임스페이스에 대한 조합으로 생성하는 방식 -> 보안문제 있어 사용 X
    - version4: 랜덤한 값을 기반으로 생성되는 방식
    - version5: "SHA-1 해시"(해시함수) 를 사용하여 생성하는 방식  -> 보안문제 (충돌현상) 있어 사용 X

정리하자면 어떤 것을 그럼 사용해야 하는지 찾아보았습니다.
그냥 unique ID가 필요하다면 versoin1이나 version 4를 사용하라고 권장하는 것을 학습했습니다.
version1은 mac주소가 있기에 같은 기계에서 생성된 UUID임을 추론할 수 있는 장점이 있지만 민감하다면 사용을 권장하지는 않습니다.
하지만 version4는 정말 랜덤으로 생성하기에 빠르고 무작위적으로 생성하기에 주로 사용되는 방식임을 알았고 보통 자바에서 `UUID.randomUUID()`로 사용하는 이유가 이 때문임을 알았습니다.
version2는 아무래도 운영체제 정보를 조회하다 보니 clock-tick(타이머 인터럽트) rate이 매우 느려서 대략 7초마다 유니크한 id를 생성하도록 제한하기에 굳이 사용하지 않는것 같아 보입니다.

2023-06-26 15:34 UTC, juno-junho commented on voucher/src/test/java/com/ray/junho/voucher/domain/PercentDiscountVoucherTest.java
> +    }
출처 : 
- https://stackoverflow.com/questions/20342058/which-uuid-version-to-use#:~:text=Version%201%3A%20UUIDs%20using%20a,SHA1%20hash%20of%20some%20data.
- https://en.wikipedia.org/wiki/Universally_unique_identifier
- https://adjh54.tistory.com/142
(혹시나 해서 남깁니다 :) )

2023-06-26 15:35 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        this.discountRate = discountRate;
넵 수정하겠습니다!

2023-06-26 15:36 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/VoucherType.java
> +    private final int code;
음.. 나중에 controller에서 입력값에 따라 사용하려고 만들어 둔 것인데, 나중 controller에서 사용할때 의미를 보고 그때 수정해도 괜찮을까요?
사실 지금 시점에서는 알맞은 이름이 딱히 떠오르지 않는것 같습니다 😅

2023-06-26 15:36 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/Currency.java
> +    }
voucher에서 가지고 있는게 맞는것 같아 수정하겠습니다!

2023-06-26 15:59 UTC, ICCHOI commented on voucher/src/main/java/com/ray/junho/voucher/domain/VoucherType.java
> +    private final int code;
넵! 괜찮아 보여요
컨트롤러 코드와 같이 push 됐다면 더 좋았을 수도 있었겠네요..! 😆

2023-06-26 16:22 UTC, juno-junho commented
UUID에 대해서 정리를 하자면
1. Long 타입 범위 (약 920경) 을 초과하는 수의 id 발급이 필요할 경우 사용한다
2. pk 값이 사용자에게 보여지는 쿼리 파라미터를 통해 보여지는 일이 많을것이기에 보안상으로 사용한다.
3. 데이터베이스 부하가 커 조회(read) 보다 생성(write)이 현저히 적게 일어날 경우 사용하는 것이 적합하다.
라고 정리할 수 있겠네요.

UUID에 대해서 잘 몰랐는데 이번기회를 통해 한번 찾아 보았습니다.
### UUID
- UUID(Universally Unique Identifier)는 범용 고유 식별자를 의미하며 중복되지 않는 유일한 값을 구성하고자할때 주로 사용된다.
- 주로 세션 식별자, 쿠키 값, 무작위 데이터 베이스 키 등에 사용이 된다 (말씀해 주신 보안상의 이유와 상통하는 것 같습니다)
- UUID의 길이는 36자리이며 4개의 `-` 와 32개의 16진수 문자열로 구성되어 있습니다.
- UUID의 버전에는 총 5개의 버전이 존재합니다.
    - version1: 타임스탬프와 랜덤한MAC 주소를 기준으로 생성하는 방식 -> 유일성 보장되지만 보안에 취약하다.
    - version2:  POSIX (Portable Operating System Interface) (운영체제간 호환성 유지하기 위한 표준)의 UID(User ID)를 version1과 함께 사용하는 방식입니다.
    - version3: "MD5 해시"(해시함수) 를 기반으로 이름과 네임스페이스에 대한 조합으로 생성하는 방식 -> 보안문제 있어 사용 X
    - version4: 랜덤한 값을 기반으로 생성되는 방식
    - version5: "SHA-1 해시"(해시함수) 를 사용하여 생성하는 방식  -> 보안문제 (충돌현상) 있어 사용 X

정리하자면 어떤 것을 그럼 사용해야 하는지 찾아보았습니다.
그냥 unique ID가 필요하다면 versoin1이나 version 4를 사용하라고 권장하는 것을 학습했습니다.
version1은 mac주소가 있기에 같은 기계에서 생성된 UUID임을 추론할 수 있는 장점이 있지만 민감하다면 사용을 권장하지는 않습니다.
하지만 version4는 정말 랜덤으로 생성하기에 빠르고 무작위적으로 생성하기에 주로 사용되는 방식임을 알았고 보통 자바에서 `UUID.randomUUID()`로 사용하는 이유가 이 때문임을 알았습니다.
version2는 아무래도 운영체제 정보를 조회하다 보니 clock-tick(타이머 인터럽트) rate이 매우 느려서 대략 7초마다 유니크한 id를 생성하도록 제한하기에 굳이 사용하지 않는것 같아 보입니다.

출처 : 
- https://stackoverflow.com/questions/20342058/which-uuid-version-to-use#:~:text=Version%201%3A%20UUIDs%20using%20a,SHA1%20hash%20of%20some%20data.
- https://en.wikipedia.org/wiki/Universally_unique_identifier
- https://adjh54.tistory.com/142
(혹시나 해서 남깁니다 :) )

2023-06-26 16:59 UTC, juno-junho commented
책임을 명확하게 분리하려 했습니다.
Currency 객체에 메세지를 보내는 방식으로 getter를 사용하지 않고 객체지향 적으로 작성하려 노력하였습니다.
테스트에 given, when, then 주석을 명시하였고 메서드 명 같은 경우 한국어로 작성하면 인텔리제이 노란줄이 생기길래 영어로 괜찮은 컨벤션이 있길래 적용시켰습니다.
`When_StateUnderTest_Expect_ExpectedBehavior`
출처 : https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea

2023-06-26 18:05 UTC, ICCHOI approved these changes
고생 하셨습니다 준호님!
테스트 케이스도 컨벤션 따라 잘 짜주신 것 같아요 👍

2023-06-27 03:21 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        long discountedValue = beforeDiscount.multiply((double) discountRate / 100);
discountRate인 할인율은 int범위 (정수 범위)일 텐데 double로 캐스팅을 해주지 않으면 값이 소수 범위를 커버하지 못하기 때문에 해 주었습니다 :)

2023-06-27 03:23 UTC, juno-junho commented on voucher/src/test/java/com/ray/junho/voucher/domain/CurrencyTest.java
multiply에 대한 테스트 작성이 누락되었네요! 추가하겠습니다 :)

2023-06-27 04:55 UTC, ICCHOI commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        long discountedValue = beforeDiscount.multiply((double) discountRate / 100);
그럼 discountedValue가 long인 이유는 무엇인가요?

2023-06-27 06:02 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        long discountedValue = beforeDiscount.multiply((double) discountRate / 100);
아 그러고 보니 그렇네요 long으로 변환시켜 줄 필요가 없는것 같습니다.
[README](https://github.com/prgrms-be-devcourse/springboot-basic/pull/684/files#diff-51bcedbbcfb5052c68bbec7afd1c6fdbe4a82e78bb810b67f76a13d7414afe18R40)의 기능목록에도 기입 해 놓았으나, 값의 범위에 대한 부분은 어떻게 처리하면 좋을지 조금 더 고민해 보겠습니다..!

인창님 생각은 어떠신가요? 뭔가 돈과 관련한 것이다 보니 BigDecimal 사용도 고려해 볼 수 있을 것 같은데 어떻게 생각하시나요?

2023-06-27 07:16 UTC, ICCHOI commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        long discountedValue = beforeDiscount.multiply((double) discountRate / 100);
타당한 이유가 있다면 BigDecimal도 좋아보이고요, 근거가 있다면 long도 괜찮아 보입니다 :)

2023-06-27 08:08 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/PercentDiscountVoucher.java
> +        long discountedValue = beforeDiscount.multiply((double) discountRate / 100);
넵 알겠습니다..! 어떤게 더 나은 방법인지 고민해 보고 다음 pr에 반영하겠습니다 :)

2023-06-27 08:39 UTC, ICCHOI commented on voucher/src/main/java/com/ray/junho/voucher/domain/FixedAmountVoucher.java
> +        validateDiscountValue(discountValue);
```suggestion
        validateDiscountValue(discountValue);
        this.id = id;
        this.discountValue = discountValue;
```
검증 후 통과하면 set을 진행하는게 좀 더 괜찮아보여요!

2023-07-02 07:28 UTC, juno-junho commented
제가 목요일 모임 이후 금요일, 토요일 컨디션이 좋지 않아 미션 수행이 많이 늦어졌습니다.

정상적으로 미션 수행 할 수 있도록 더욱 분발하겠습니다! 감사합니다 :)

2023-07-02 08:32 UTC, ICCHOI commented on voucher/src/main/java/com/ray/junho/voucher/domain/Currency.java
> +        return Currency.of((long) (this.value * value));
double로 받는 값을 long으로 캐스팅 하는 이유가 무엇인가요?

2023-07-02 09:59 UTC, juno-junho commented on voucher/src/main/java/com/ray/junho/voucher/domain/Currency.java
> +        return Currency.of((long) (this.value * value));
제가 생각하기에 할인율은 1% ~ 100% 까지 가능한 것으로 생각했습니다. 그래서 그렇게 validation도 작성했고요.
그런데 할인율을 계산하는 과정에서 value * 할인율 / 100 으로 계산하면 예를들어 36퍼센트나 30퍼센트나 할인되는 금액이 같더라고요.
그래서 double로 고정 시키는게 맞다고 생각했고, 할인된 금액을 원가에서 뺄때는 long으로 바꿔 소수점 자리는 버리는게 맞겠다는 생각이 들어 그렇게 코드를 작성했습니다.

2023-07-03 13:58 UTC, devcourse-ray approved these changes
🌵

2023-07-03 14:00 UTC, merged