[4기-신범철] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #685
Opened 2023-06-25 04:19 UTC by beombu

## 📌 과제 설명 
(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을  만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 

### 클래스 다이어그램
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/84673536/704ffaf4-6733-40aa-a7d6-59bf9e5da322)

### 클래스 설명
- `CommandLineApplication` : View와 Model 사이에서 Controller 역할을 하는 클래스입니다.
- `VoucherConsole` : 바우처에 관련된 입출력을 모두 구현해 놓은 클래스입니다.
- `Input`, `ScannerInput`, `Output`, `PrintOutput` : 입력과 출력을 정의하는 클래스와 인터페이스입니다.
- `(Enum) CommandType` : 바우처의 생성, 조회 기능이 열거된 Enum 입니다.
- `(Enum) VoucherType` : 바우처의 고정 금액 할인, 퍼센트 할인 기능이 열거된 Enum 입니다.
- `FixedAmountVoucher` : 바우처의 고정 금액 할인 기능을 구현한 구현체입니다.
- `PercentAmountVoucher` : 바우처의 퍼센트 할인 기능을 구현한 구현체입니다.
- `Voucher` : 바우처의 할인 기능을 담당하는 인터페이스입니다.
- `MemoryVoucherRepository` : `VoucherRepository`의 구현체로 메모리에 바우처를 저장하는 클래스입니다.
- `VoucherServiceImpl` : `VoucherService`의 구현체로 생성과 조회 기능을 구현한 클래스입니다.

## ✅ PR 포인트 & 궁금한 점 
- `(interface) Voucher`가 VO이면서 Entity라고 생각하였습니다. 그래서 `VoucherVO`를 통해 분리해주려고 하였으나 Entity의 부분 집합이라고 생각하여 삭제하였습니다. 맞는 판단이었나요?

2023-06-27 01:50 UTC, Jo-GyuHyeon requested changes
안녕하세요. 범철님 😄 
첫번째 PR 작성하시느라 고생 하셨습니다. 🙇 
간단히 코멘트를 남겼는데, 더 진행 하기 보다 피드백 반영 후에 같이 얘기 해보면 더 좋을것 같아요.
고생하셨습니다. 🙇

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +    }
spring framework 4.3 부터는 @Autowired  없이 생성자만으로 빈 주입을 할 수 있어요.
https://spring.io/blog/2016/03/04/core-container-refinements-in-spring-framework-4-3

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        while (!userCommand.equals(CommandType.EXIT.name())) {
인자에 인자 깊이가 (함수 호출 및) 깊어 질 수록 가독성이 떨어지는 것 같아요.
userCommand 를 String 비교가 아닌 열거형을 잘 활용해보면 어떨까요?

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +            userCommand = voucherConsole.InputCommand().toUpperCase();
InputCommand() 는 메서드인데 대문자로 시작 하는 것 같아요. 
java 명명 규칙을 참고 해보면 좋을것 같아요.
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +                String userVoucherType = voucherConsole.ChooseVoucherType().toUpperCase();
ChooseVoucherType() 는 메서드인데 대문자로 시작 하는 것 같아요.
java 명명 규칙을 참고 해보면 좋을것 같아요.
[oracle.com/java/technologies/javase/codeconventions-namingconventions.html](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +                Long discount = voucherConsole.InputDiscountByVoucher();
InputDiscountByVoucher() 는 메서드인데 대문자로 시작 하는 것 같아요.
java 명명 규칙을 참고 해보면 좋을것 같아요.
[oracle.com/java/technologies/javase/codeconventions-namingconventions.html](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/KdtSpringDemoApplication.java
> +        applicationContext.getBean(CommandLineApplication.class).run();
CommandLineApplication 를 직접 인스턴스화 하지 않고 applicationContext 에서 빈을 이용하는 이유는 무엇 일까요?

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +public class VoucherConsole {
콘솔을 담당하는 객체를 Component 로 선언하는 이유는 무엇인가요???
Component 는 언제 사용하는 것이 좋을까요?

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +    }
위의 코멘트에도 남겨 두었듯이 네이밍 컨벤션을 확인 해주세요.
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/input/ScannerInput.java
> +}
Input 인터페이스를 따로 두면 어떠한 이점이 있을까요?
Input 객체가 Component 로 선언하는 것은 어떠한 이점이 있을까요?

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/output/PrintOutput.java
> +}
Output 인터페이스를 따로 두면 어떠한 이점이 있을까요?
Input 객체가 Component 로 선언하는 것은 어떠한 이점이 있을까요?

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/FixedAmountVoucher.java
> +    }
toString()을 재정의 하였을때 voucherId 를 확인 못하는 경우가 생길것 같아요.
이런 경우라면 View 쪽에서 출력폼을 담당하는 것은 어떨까요?

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/FixedAmountVoucher.java
> +        return discount;
구문 사이에는 개행을 추가하는 것이 가독성이 좋은것 같아요.

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucher.java
> +    }
validateDiscount() 는 생성시에만 체크하게 되는 것 같아요. 
executeDiscount() 실행시에는 체크가 필요 하진 않을까요?

2023-06-27 01:50 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +                return voucherRepository.save(new PercentAmountVoucher(UUID.randomUUID(), voucherType, discount));
함수 호출과 전달은 한가지만 하는 것이 좋습니다.
인자가 깊어질수록 가독성이 떨어지기도 하는 것 같아요.

2023-06-27 04:52 UTC, HyoungUkJJang reviewed
범철님 코드 잘봤습니다 ~ 
멘토님이 먼저 코멘트를 잘 남겨주셔서 저도 간단히 몇개 남겨봤어요
범철님도 편하게 의견을 말씀해주시면 좋을 것 같습니다 ! 고생하셨어요 👍

Entity와 VO는 게더에서 한번 이야기 나눠보면 좋을 것 같습니다 ~

2023-06-28 23:18 UTC, beombu reviewed
리뷰 수정을 늦게 해서 죄송합니다ㅠㅠ
Dto을 추가해 계층 별로의 역할을 조금 더 나눠보았습니다.
섬세한 리뷰 감사합니다🙇‍♂️🙇‍♂️🙇‍♂️

2023-06-28 23:18 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/FixedAmountVoucher.java
> +    }
toString을 재정의해서 사용한 이유가 View에서 분기를 나누지 않고 편하게 사용하기 위함이었습니다...
형욱 멘토님이 남겨주신 질문을 보고 도메인과 뷰가 연관성을 가지는 것에 대해 생각해볼 수 있었습니다.
계층 별로 연관을 가지지 않고 View -> Domain으로만 흐르도록 설계하고 구현하도록 노력하겠습니다❗❗❗

2023-06-28 23:18 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/MemoryVoucherRepository.java
> +        return new ArrayList<>(storage.values());
반환 받은 값을 불변하게 유지할 수 있습니다.
알려주셔서 감사합니다❗❗❗

2023-06-28 23:18 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherService.java
> +    Voucher createVoucher(VoucherType voucherType, long discount);
클래스 이름이 VoucherService여서 충분히 `create()`만으로 의미 전달이 가능할 것 같습니다!!
감사합니다🙇‍♂️🙇‍♂️

2023-06-28 23:18 UTC, beombu commented on src/test/java/org/prgrms/kdtspringdemo/KdtSpringDemoApplicationTests.java
> +}
무의미한 파일이 들어갔습니다.. 삭제하겠습니다!!

2023-06-28 23:18 UTC, beombu commented on src/test/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucherTest.java
> +    void _할인금액이_0퍼센트_이하_일_경우_예외() {
테스트 메서드 이름을 한글로도 작성할 수 있다는 것을 알게 되어서 DisplayName()은 불필요하다고 판단하였습니다!

2023-06-28 23:41 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucher.java
> +    }
당장 해결하지 못했습니다..
어떤 체크가 필요한지 다시 생각해보겠습니다❗❗❗

2023-06-29 01:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/KdtSpringDemoApplication.java
> +        applicationContext.getBean(CommandLineApplication.class).run();
@beombu 현재 CommandLineApplication 라는 클래스를 직접 빈으로 찾고 실행 하고 있는데, 혹시 다른 방식으로 실행 할 수있을까요?

2023-06-29 06:40 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/KdtSpringDemoApplication.java
> +        applicationContext.getBean(CommandLineApplication.class).run();
감사합니다❗❗
`CommandLineRunner`를 통해서 String boot 실행 후에 직접 빈을 찾아서 실행하지 않아도 `CommandLineApplication`이 실행되도록 구현하였습니다🙇‍♂️🙇‍♂️🙇‍♂️

### 변경
- [e786b01](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/e786b017941b1dc1145ee6b729acf20c15a077d9) 피드백 반영

2023-06-30 14:22 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/input/ScannerInput.java
> +}
@beombu 피드백 반영 하셔서 Resolve 처리 할게요.
input.output 이 확장될 필요가 있는지 고민 해보시면 좋을것 같아요.
인터페이스를 사용하지 않는다면 책임이 없을까요???

2023-06-30 14:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucher.java
> +    }
@beombu 저도 따로 체크가 필요하다고 생각하지 않는다고 생각해요. 범철님의 생각을 듣고 싶었어요. 👍 
beforeDiscount 네이밍만 한번더 고민해보시면 좋을것 같아요.

2023-06-30 17:18 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        while (!userCommand.equals(CommandType.EXIT.name())) {
말씀하신 의도를 하나도 캐치하지 못했었네요😅😅
Enum은 싱글톤으로 하나의 인스턴스를 보장하기 때문에 `==`으로 비교할 수 있다는 것을 알게 되었습니다!
`==` 비교를 통해 `NullPointException`을 발생하지 않는 점과 컴파일 타임에 타입 호환성 검사를 하는 장점을 알게 되었습니다!!
잊지 않고 Enum을 자체를 비교할 경우에 `==`을 사용하도록 노력하겠습니다!! 감사합니다🙇‍♂️🙇‍♂️

### 변경

2023-06-30 17:18 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucher.java
> +    }
감사합니다.🪄🪄
항상 예외 처리에 대한 생각을 깊게 하지 않았었는데
예외 처리에 대한 고민을 다양하게 해볼 수 있었습니다!

### 변경

> long beforeDiscount  -> long originPrice

2023-07-01 03:04 UTC, HyoungUkJJang reviewed
추가 코멘트 남겼습니다 범철님 :) 고생하셨어요 !

2023-07-01 03:04 UTC, HyoungUkJJang commented on src/test/java/org/prgrms/kdtspringdemo/voucher/ropository/VoucherRepositoryTest.java
> +    void 바우처_저장_테스트() {
실패에 대한 테스트도 있으면 좋을 것 같아요 :)

2023-07-01 03:04 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        return Long.parseLong(input.read());
숫자 입력이 아닌 경우 예외는 처리 안해도 괜찮을까요?

2023-07-02 18:08 UTC, beombu reviewed
리뷰 감사합니다🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

- 추가 구현사항
  - logback 설정 [8ba2360](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/8ba2360debf06af013f0005f274ccacda0e8eb25)

늦게 올려서 죄송합니다..!!

2023-07-02 18:21 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/view/console/input/ScannerInput.java
> +}
멘토님 감사합니다.
그동안 인터페이스를 통해 확장을 잘한다면 좋은 코드인 줄만 알았는데 모든 기술에는 트레이드 오프가 있고 상황에 맞게 사용해야 한다는 것을 다시 한번 깨닫는 시간이었습니다.
이번 상황은 이해했으나 아직 저 스스로가 확장에 대한 기준을 세우지 못한 상황인 것 같습니다ㅠㅠ..
해당 리뷰는 제가 조금 더 준비해서 다시 한번 이야기 하고 싶습니다!!!

2023-07-03 12:44 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +            }
@beombu 

커밋 메시지를 조금 더 잘 작성해보면 어떨까요? 어떤 코드의 중복 제거인지도 나왔으면 좋을 것 같아요 ! 
리뷰는 반영된 것 같아 resolve 하겠습니다 ~ 참고만 해주세요 !

2023-07-03 12:48 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/dto/VoucherDto.java
> +    }
@beombu 

정적 메서드는 처음에 괜찮다고 생각했는데 필드가 두개면 단순히 풀어서 넘겨주면 도메인에 의존도 하지 않고 괜찮지 않을까요? 꼭 파라미터에 바우처를 넘겨야 하는 이유가 있을까요?

2023-07-03 21:22 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/view/console/input/ScannerInput.java
> +}
### 변경
- [2a577ef](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/2a577efcadb6fbe06279761449709e7333430875) Refactor : 콘솔 input, output 삭제
- Console을 단일 클래스로 변경하였습니다.

2023-07-03 21:26 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +                .map(v -> new VoucherDto(v.getVoucherType(), v.getDiscount()))
아닙니다!!
제가 코드를 이상하게 짜셔 그렇습니다🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️
매서드 래퍼런드에 대해서 알아가는 정말 소중한 시간이었습니다❗❗
감사합니다!!!

### 변경
[f8dd65c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/f8dd65cc640371f3b523693f729d767ce75165c2) Refactor : VoucherDto에서 도메인 의존하는 문제 수정

2023-07-03 21:34 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/dto/VoucherDto.java
> +    }
DTO에서는 다른 객체를 의존하지 않고 내부 상태로만 구현되어야 하는데 바우처를 생각없이 사용한 것 같습니다.
의존 관계에 더욱 더 신경써서 구현하겠습니다!

### 변경
[f8dd65c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/f8dd65cc640371f3b523693f729d767ce75165c2) Refactor : VoucherDto에서 도메인 의존하는 문제 수정

2023-07-04 04:29 UTC, beombu commented
리뷰 감사드립니다❤️❤️
피드백 수정하였습니다❗❗❗

### 변경 사항
[f8dd65c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/f8dd65cc640371f3b523693f729d767ce75165c2) Refactor : VoucherDto에서 도메인 의존하는 문제 수정
- `toDto` 메서드를 정적으로 바꾸고, 도메인을 의존했던 문제를 해결하였습니다.

[2a577ef](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/2a577efcadb6fbe06279761449709e7333430875) Refactor : 콘솔 input, output 삭제
- Console을 input와 output으로 확장하지 않고 단일 클래스로 수정하였습니다.

### 추가 구현 사항
없습니다!

2023-07-05 02:25 UTC, Jo-GyuHyeon requested changes
안녕하세요 범철님 간단히 리뷰 남겨두었어요.
1주차 마지막 코드리뷰가 될것 같아요.
그동안 고생 많으셨어요.
관련된 내용은 온라인으로 진행 해볼까 해요.
간단한 리뷰들을 수정 한 후에 알려주시면 감사해요.
(곧!! 2주차 시작 해볼수 있을것 같아요)
고생 많으셨어요. 🙇

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        while (userCommand != CommandType.EXIT) {
CommandType 에서 상태를 알려주는 메서드를 제공 해보는건 어떨까요?
예를 들면 command.isExit() 혹은 다른 상태, 네이밍이 되어도 좋을것 같아요.

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +            userCommand = CommandType.findCommandType(voucherConsole.inputCommand().toUpperCase());
대문자로 비교 해야 한다는건 CommandLineApplication 에서 CommandType.findCommandType() 내부 까지 파악을 하고 사용해야 되는것 같아요.
비교에 대한 책임을 findCommandType() 로 위임 시키면 어떨까요?

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +                VoucherDto voucher = createVoucher(userVoucherType);
28번 라인의 코드리뷰와 동일 하니 참고 부탁 드려요.

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +                vouchers.forEach(voucherConsole::printCreatedVoucher);
단순히 순회만 한다면 stream 보다 향상된 for 문 (for each loop) 를 사용해보면 어떨까요?
stream 의 foreach 와 비교 하여 어떠한 차이가 있을까요?

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +    }
printInitMessage(), printSystemShutdown() 는 메시지를 인자로 받는건 어떤것 같아요???
범철님의 생각이 궁금해요.

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +            }
Tpye 과 ID 전략은 외부로 주입받지 않아도 될것 같은데 어떻게 생각 하시나요?

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +            }
열거 타입에 대한 분기 처리가 아니라, 열거 종류가 없다면 예외처리는 VoucherType 로 위임 시키 어떨까요?
VoucherType 으로 예외 처리 위임 하게 된다면 관련되어서 범철님의 생각을 알고 싶어요.

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +                .collect(Collectors.toUnmodifiableList());
toUnmodifiableList() 👍

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/VoucherRepository.java
> +    Optional<Voucher> findById(UUID voucherId);
현재 사용 되지 않는 기능인것 같아요. 확인 부탁 드려요.

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucher.java
> +            logger.error("원인 : {} -> 에러 메시지 : {}", amount, OUT_OF_RANGE_AMOUNT);
log 👍 error 레벨이 적절한지 고민 해보면 좋을것 같아요.

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/dto/VoucherDto.java
> +        );
개인의 취향이라고 생각해요. 
저는 인자가 2개 정도이고 한 라인에 대한 컬럼 수를 넘지 않는다면 인라인으로 표현 해도 좋은것 같아요.

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
VoucherType 에게 생태를 알려 달라고 하는 건 어떨까요?

2023-07-05 02:25 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
분기 처리 하는 것은 결국 사용자에게 안내 메시지를 별도로 가져가기 위함 이라고 생각해요.
분기 처리 하지 않을수 있을것 같아요. 간단히 풀어 낼수 있을것 같아요.
inputAmountEachVoucher() 메서드도 추출(분리)하지 않고 합칠수(인라인으로 변경 할 수) 있을것 같아요.

2023-07-06 08:53 UTC, beombu reviewed
소중한 리뷰 감사합니다❤️❤️❤️

- 추가 변경사항
  - X

2023-07-06 08:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
감사합니다!
if문 나열을 통해 분기를 제거하였습니다.
분기(else if)로 처리하는 경우는 메인 if의 조건이 거짓이고(&&) 분기의 조건이 참일 때 사용하는 것이고
독립적인 경우 if를 나열해서 사용하는 것으로 이해했으나 명확하게 이해가 되지 않았습니다..
혹시 참고할만한 키워드 추천해주실 수 있나요...?

### 변경
- [46326ef](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/46326ef1080c0f5f22d50515a6e925c7e7317240) Refactor : 바우처 타입 비교 분기 제거

2023-07-06 08:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucher.java
> +            logger.error("원인 : {} -> 에러 메시지 : {}", amount, OUT_OF_RANGE_AMOUNT);
감사합니다!!
- ERROR : 어떠한 요청을 처리하는 중 문제가 발생한 상태를 나타낸다. 프로그램 동작에 큰 문제가 발생했다는 것으로 즉시 문제를 조사해야 하는 것들을 처리
- WARN : 프로그램의 실행에는 문제가 없지만, 향후 시스템 에러의 원인이 될 수 있는 경고성 메시지를 나타낸다.(명확한 문제나 잠재적 문제에서는 종료 발생)

해당 레벨은 WARN이 더 맞다고 판단 됩니다.
log level을 info, debug, error 정도만 사용해보았는데 더 상세하게 구현하도록 노력하겠습니다🙇‍♂️🙇‍♂️

### 변경
- [48ab3fa](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/48ab3fae8749430ed320ffc36fefa94ef7b9fced) Refactor : log level 수정

2023-07-06 08:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/VoucherRepository.java
> +    Optional<Voucher> findById(UUID voucherId);
테스트를 구현할 당시에 사용하고 있습니다.(VoucherRepositoryTest.java)
실질적 구현에서는 사용하지 않는데 지우는게 맞는지 궁금합니다❗❗❗

### 변경
X

2023-07-06 08:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +            }
헉.. 감사합니다!🙇‍♂️🙇‍♂️
Voucher의 구현체가 나눠지기 때문에 불필요한 외부 주입이었습니다!! 수정하였습니다🪄🪄

### 변경
- [0babc2c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/0babc2c9929638c7fc7343d5c1c362eeb189ee37) Refactor : Voucher의 불필요한 외부 주입 변경(id, type)

2023-07-06 08:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +            }
감사합니다!!
Voucher가 바우처의 책임을 다하는 것 같습니다.
분기에서 default를 지양하라고는 들었는데 항상 사용했던 것 같습니다!
알려주신 방법으로 else, default를 안쓰도록 잘 사용하겠습니다.🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

### 변경
- [122bcdf](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/122bcdf98a5897992ea1ef766096ad8feaf6ad2a) Refactor : Service layer에 존재하는 바우처 타입 예외처리 VoucherType로 위임

2023-07-06 08:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +                VoucherDto voucher = createVoucher(userVoucherType);
### 변경
- [6960483](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/696048307e0cacf5a0900c884448bf8028650d31) Refactor : CommandType에서 대문자 책임 위임

2023-07-06 16:38 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        while (userCommand != CommandType.EXIT) {
정적 메서드가 아닌 (CommandType   isNotExit) 객체 메서드로 userCommand.isExit() 를 지안 드렸던것 같아요.
네이밍을 command.isExit() 으로 해서 헷갈리셨을까요?

2023-07-06 16:42 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/VoucherRepository.java
> +    Optional<Voucher> findById(UUID voucherId);
결국 테스트는 실제 기능을 위해 존재 해야 한다고 생각해요. (역전이 되면 안됀다고 생각해요)

2023-07-06 16:45 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
https://github.com/prgrms-be-devcourse/springboot-basic/pull/685#discussion_r1254680826 코멘트와 연관되었길래 함께 처리 반영 드려요.

2023-07-06 16:45 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
https://github.com/prgrms-be-devcourse/springboot-basic/pull/685#discussion_r1254680826 코멘트와 연관되었길래 함께 처리 반영 드려요.

2023-07-07 04:20 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +            }
@beombu switch 의 default 제거와 if 문 변경은 리뷰 내용과 다른것 같아요! 다시 확인 부탁 드려요.

2023-07-07 05:24 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        while (userCommand != CommandType.EXIT) {
멘토님이 남겨주신 리뷰(상태 확인 로직을 CommandType에서 구현) 이해했습니다! Enum에 대한 이해도가 낮았던 것 같습니다.

### 변경
- [2f4c6f1](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/2f4c6f14fc9849a09e65689ad87d04b848ce0b4a) Refactor : Enum 정적 메서드 -> 객체 메서드로 변경

2023-07-07 05:24 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/VoucherRepository.java
> +    Optional<Voucher> findById(UUID voucherId);
감사합니다🙇‍♂️🙇‍♂️
역전이라는 말이 정말 많이 와닿았습니다!!

### 변경
- [acbe5f5](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/acbe5f5e8bd88f02d6b3a4b17a829ac250b4fc6d) Refactor : repository findById 삭제

2023-07-07 05:24 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
멘토님이 남겨주신 리뷰(상태 확인 로직을 CommandType에서 구현) 이해했습니다! Enum에 대한 이해도가 낮았던 것 같습니다.

### 변경
- [2f4c6f1](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/2f4c6f14fc9849a09e65689ad87d04b848ce0b4a) Refactor : Enum 정적 메서드 -> 객체 메서드로 변경

2023-07-07 05:24 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
멘토님이 남겨주신 리뷰(상태 확인 로직을 CommandType에서 구현) 이해했습니다! Enum에 대한 이해도가 낮았던 것 같습니다.

### 변경
- [2f4c6f1](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/2f4c6f14fc9849a09e65689ad87d04b848ce0b4a) Refactor : Enum 정적 메서드 -> 객체 메서드로 변경

2023-07-07 05:25 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +            }
### 변경
-  [02e8df0](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/02e8df0dd3c130042c2b35bc1e1b5334c9dcc6f3) Refactor : ServiceImpl switch문 복구
  - default에 어떤 책임이 들어가야 하는지 모르겠습니다. VoucherType이 없는 경우에 책임을 VoucherType 내부로 위임했기 떄문에 switch의 default는 사용할 이유가 없는 것 같습니다.

2023-07-07 05:25 UTC, beombu commented
소중한 리뷰 감사합니다🙇‍♂️🙇‍♂️

- 추가 변경사항
  - X

2023-07-07 19:45 UTC, Jo-GyuHyeon reviewed
간단하게 리뷰 남겼어요.
관련 내용 이외는 온라인으로 얘기 나눠보면 좋을것 같아요.

2023-07-07 19:45 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +            }
default 를 사용하면 열거 형 타입이 추가 되더라도 컴파일러의 도움을 받기 힘들고 지정하고 한것이 무엇인지 구분 하기가 어려워요.
switch 문을 사용한다면 default 케이스가 없는 경우에 사용하는 것이 좋은것 같아요.

default 구문 없이도 의도하신대로 코드 구현이 가능 할 것 같아요.

2023-07-07 19:45 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        while (!userCommand.isExit()) {
NONE 타입은 실제로 사용되지 않는 것 같아요.
NONE 타입없이도 반복 조건문을 수행 할 수 있을것이라 생각해요.

2023-07-07 19:45 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
굳이 분리 하지 않아도 될것 같다는 생각이 들어요.
(아래도 유사해요)

2023-07-08 18:15 UTC, beombu reviewed
소중한 리뷰 감사합니다🪄🪄🪄
모든 리뷰 수정 완료하였습니다!

- 추가 구현사항
  - X

2023-07-08 18:15 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        while (!userCommand.isExit()) {
맞습니다!
초기값을 위해 사용했는데 삭제가 맞습니다!

### 변경
- [7de9b35](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/7de9b35909f25a9163aee411b1d606b003d4e354) Refactor : CommandType.NONE 삭제
  - do-while을 사용해 NONE 삭제

2023-07-08 18:15 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/constant/CommandType.java
> +    NONE,
맞습니다!
초기값을 위해 사용했는데 삭제가 맞습니다!

### 변경
- [7de9b35](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/7de9b35909f25a9163aee411b1d606b003d4e354) Refactor : CommandType.NONE 삭제
  - do-while을 사용해 NONE 삭제

2023-07-08 18:15 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
> +        }
다시 생각해보니 독립적으로 if을 나열할 이유가 없는 것 같습니다!
감사합니다🙇‍♂️🙇‍♂️🙇‍♂️

### 변경
- [64d90f2](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/64d90f266d70d3718acc9489c3977a3526b7773f) Refactor : if문 나열 병합
  - else if 사용

2023-07-08 18:15 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +            }
감사합니다❗❗❗❗
알려주신 Switch Expression을 통해 default 케이스가 없는 경우 처리하는 방법을 알게 되었습니다!

### 변경
[2fa8d71](https://github.com/prgrms-be-devcourse/springboot-basic/pull/685/commits/2fa8d71aa8c734e4c54221d2608cc62bcc774860) Refactor : Switch Expression을 사용해 default문 삭제

2023-07-09 14:10 UTC, Jo-GyuHyeon approved these changes
범철님 고생 많으셨어요. 🙇 
심화 과정은 일정상 생략을 제안 드리고 싶어요.
바우처 2 미션도 잘 하시길 바래요.
고생 많으셨어요.

2023-07-09 15:39 UTC, merged