[4기-이성주] SpringBoot Part1 Weekly Mission 제출입니다.
prgrms-be-devcourse/springboot-basic pull request #686
Opened 2023-06-25 07:14 UTC by Seongju-Lee

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 
**I/O:** 입출력 장치의 변경을 대비하여 인터페이스로 선언하고 MenuType, VoucherType이 반환되도록 입력을 선언하였습니다.
**menu:** 선택한 메뉴에 따라 각각의 실행을 하기 위해 별도의 인터페이스로 선언하였습니다. (구현: Voucher 생성, Voucher History 출력)
**validator:** 여러가지 검증부 구현을 위해 따로 validator를 선언하였습니다.
**config:** 서비스 로직에서 Map<String, Voucher> voucherBeanMap을 통해 여러가지 Voucher 구현체를 주입합니다.
이때, 어떠한 Voucher들이 주입되는 지 편리하게 관리하기 위해 수동으로 빈 등록을 하였습니다.

## ✅ PR 포인트 & 궁금한 점

1.  VoucherService에서 구현한 것처럼  Enum에 Bean(인터페이스 구현체)이름을 설정하고, runBeanMapByMenu를 통해 적절한 Bean을 매핑하도록 하였습니다.
이렇게 Enum에 Bean이름을 설정하는 것이 올바른 방식은 아니라고 생각이 들어서,, **동적으로 적절한 Bean을 선택하는 과정에서 어떠한 로직이 적절한 지 여쭤보고 싶습니다..!!**

2023-06-25 09:43 UTC, JoosungKwon reviewed
안녕하세요 성주님 과제하시느라 고생많았습니다! 😄

일단 전반적으로 다소 복잡한 것 같아요! 의존성을 낮추기 위함으로 기능별 로직에 맞춰서 객체를 만드신 것 같다고 봤는데 맞나요..? 제가 생각하기엔 약간 과한 측면도 있고, Spring을 적절하게 활용하고 있는 것 같진 않습니다..😅 (구조가 일반적이지 않아 구조를 알아보기 어렵습니다,,,)

- 좀 더 공부하시면서 확장에 유연할 수 있는 구조인지, 남들이 보기에 이해하기 수월한지 생각해보시면 좋을 것 같습니다~!

질문 주신 내용에 답변 드리자면 

> VoucherService에서 구현한 것처럼 Enum에 Bean(인터페이스 구현체)이름을 설정하고, runBeanMapByMenu를 통해 적절한 Bean을 매핑하도록 하였습니다.
이렇게 Enum에 Bean이름을 설정하는 것이 올바른 방식은 아니라고 생각이 들어서,, 동적으로 적절한 Bean을 선택하는 과정에서 어떠한 로직이 적절한 지 여쭤보고 싶습니다..!!

- 일단 Voucher를 Bean으로 등록하시려는 이유가 궁금합니다!! Voucher가 Bean으로 등록되어야 하는 이유가 있나요..? ([Bean의 의미](https://engineerinsight.tistory.com/44)에 대해서도 공부해보시면 좋을 것 같네요~)

2023-06-25 09:43 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/voucher/VoucherService.java
> +        runByMenu.run();
Menu를 Bean으로 등록하셔서 사용하는 방식으로 로직을 짜신 이유가 궁금합니다..!!

2023-06-25 09:43 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/SpringBasicApplication.java
> +			voucherApplication.run();
[CommandLineRunner](https://www.baeldung.com/spring-boot-console-app)를 사용해보는 것은 어떠신가요~?

2023-06-25 09:43 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/VoucherApplication.java
> +
비워두시는 이유가 있나요..?

2023-06-25 09:43 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/voucher/VoucherService.java
> +public class VoucherService {
`VoucherService`라는 이름과 걸맞는 동작이 없는 것 같아요!

2023-06-25 09:43 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/menu/RunByCreatesMenu.java
> +public class RunByCreatesMenu implements RunByMenu {
`RunByCreatesMenu`를 별개의 `Controller`와 유사한 역할을 한다고 생각하면 되나요..?

2023-06-25 09:51 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/voucher/repository/FileVoucherRepository.java
> +        return findAll().stream().filter(voucher -> voucher.getVoucherId() == voucherId)
CSV 파일에 접근하여 매칭되는 Id를 찾아야하는 과정이여서 애플리케이션 단에서 로직을 수행했습니다!!
파일 접근하는 과정에서 바로 불러올 수 있는 부분을 고민해보겠습니다 :)

2023-06-25 09:53 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/voucher/repository/FileVoucherRepository.java
> +        return new ArrayList<>();
앗 생각 못해본 부분이네요..ㅎㅎ
감사합니다!!!

2023-06-25 10:00 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/config/VoucherConfig.java
> +
Voucher를 생성하는 로직인 RunByCreatesMenu에서 어떤 Voucher를 생성할 지를 결정하기 위해
각 Voucher가 Map을 통해 주입 받도록 하였습니다.

그 과정에서 어떤 Bean들이 Map에 주입되는 지 관리하기 편하도록 별도의 "수동 빈 등록"에 대한 설정파일을 만들었습니다!!

2023-06-25 10:01 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/config/VoucherConfig.java
> +    }
> Voucher를 생성하는 로직인 RunByCreatesMenu에서 어떤 Voucher를 생성할 지를 결정하기 위해
각 Voucher가 Map을 통해 주입 받도록 하였습니다.

여기서, Bean을 통해 각 Voucher에 동적으로 접근하기 위해 Bean으로 등록하였습니다..!

2023-06-25 10:03 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/validator/MenuValidator.java
> +    }
앗 처음에 Integer or String 타입이 들어오는 것을 대비하기 위해 제네릭으로 선언했었는데,
지금 보니 필요가 없군요..!! 감사합니다 :)

2023-06-25 10:04 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/util/RegexPattern.java
> +public class RegexPattern {
감사합니다!!! :)

2023-06-25 10:09 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/voucher/VoucherBean.java
> +public enum VoucherBean {
앗.. VoucherType에서 Bean이름을 사용하는데,
Bean이름을 가져오기 위해서 별도의 enum으로 만들었습니다..

2023-06-26 01:41 UTC, graygreat requested changes
안녕하세요 성주님~~
고민을 많이 하신게 코드에 많이 보여서 좋네요 💯 
리뷰 몇 개 남겨놨으니 확인 부탁드려요!

질문에 대한 답변을 해보자면,
> VoucherService에서 구현한 것처럼 Enum에 Bean(인터페이스 구현체)이름을 설정하고, runBeanMapByMenu를 통해 적절한 Bean을 매핑하도록 하였습니다.
이렇게 Enum에 Bean이름을 설정하는 것이 올바른 방식은 아니라고 생각이 들어서,, 동적으로 적절한 Bean을 선택하는 과정에서 어떠한 로직이 적절한 지 여쭤보고 싶습니다..!!

현재 로직을 보면 로직이 스프링에 너무 의존하고 있는 것 같아요.
예를 들어, VoucherType이 Bean에 대한 정보를 알고 있을 필요가 있을까요?
의존 관계를 끊는거에 대해 생각해보면 성주님이 질문하신 내용에 조금 도움이 될 것 같아요 ㅎㅎ

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/VoucherApplication.java
> +                System.out.println(e.getMessage());
예외를 출력해주는 로직도 결국 io 패키지에 있어야 하는게 아닐까요?

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/VoucherApplication.java
> +        } while (menu != MenuType.EXIT);
MenuType에게 EXIT인지 물어보는게 더 객체지향적일 것 같네요!

https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/io/IODevice.java
> +public interface IODevice {
인터페이스로 만들어주신 이유가 있으실까요?
결국 "console이 아닌 웹으로 구현해주세요" 라는 새로운 요구사항이 나오면 IODevice와 ConsoleDevice 둘 다 수정해야할 것 같은데요.

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/menu/RunLogicBean.java
> +public enum RunLogicBean {
해당 클래스의 목적을 모르겠어요ㅠ
추가로 네이밍의 뜻도 잘 모르겠네요 ㅠ

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/menu/MenuType.java
> +
불필요한 개행이 너무 많은 것 같아요.

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/menu/RunByCreatesMenu.java
> +    private final Map<String, Voucher> voucherBeanMap;
[객체지향 생활 체조 원칙](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)을 보면 **"규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다."** 라는 원칙이 있어요!

이에 맞춰서 리팩토링 한번 해보시죠

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/menu/RunByCreatesMenu.java
> +    private static final Logger logger = LoggerFactory.getLogger(RunByCreatesMenu.class);
상수 선언을 생각하신 것 같은데, logger도 대문자로 해주면 좋지 않을까요?

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/voucher/VoucherType.java
> +    public String getBeanName() {
VoucherType이 getBeanName 메소드를 가지고 있다는건,, 특정 객체가 Bean 즉, 스프링을 의존하고 있는거죠?
이 구조에 대해서 어떻게 생각하시나요?

2023-06-26 01:41 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/menu/RunByCreatesMenu.java
> +        } else if (voucherBean instanceof PercentDiscountVoucher) {
[객체지향 생활 체조 원칙 ](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)보시고 else if도 줄여보시죠!

2023-06-26 04:23 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/SpringBasicApplication.java
> +			e.printStackTrace();
앗.. 처음에 오류 메시지가 뜨지 않아서, 디버깅 용도로 출력했었습니다..!!

2023-06-26 04:25 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/VoucherApplication.java
> +                System.out.println(e.getMessage());
그게 맞는 것 같습니다..ㅎㅎ 감사합니다 :)

2023-06-26 04:27 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/VoucherApplication.java
> +        } while (menu != MenuType.EXIT);
오 생각해보지 못한 부분이네요.. 바로 적용해보겠습니다!!
감사합니다 :)

2023-06-26 05:00 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/io/IODevice.java
> +public interface IODevice {
지금 살펴보니, main에서 이미 ConsolveDevice로 구현체를 받아버리기 때문에
멘토님께서 말씀하신대로 둘 다 수정해야 하는 상황인 것 같다고 생각이 들었는데 그런 의미가 맞을까요..? 
많이 부족하지만 저의 의도는 아래와 같았습니다!!!


**표현계층-응용계층**을 분리하고 싶었습니다.

말씀 해주신 요구사항처럼
> "console이 아닌 웹으로 구현해주세요"

**위와같은 경우에 컨트롤러(표현계층)에서 IODevice에만 의존하여 입력을 받고,
WebDevice라는 구현체를 하나만을 만듦으로써 OCP원칙을 준수하고 싶었습니다.**

2023-06-26 05:01 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/menu/RunByCreatesMenu.java
> +    private final Map<String, Voucher> voucherBeanMap;
오.. 수정해보겠습니다!! 감사합니다 :)

2023-06-26 05:03 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/voucher/VoucherType.java
> +    public String getBeanName() {
"너무 스프링에 의존적이다"라는 말씀이 와닿는 부분이네요..ㅠㅠ
고민하고 수정해보겠습니다!!

2023-06-26 21:07 UTC, Seongju-Lee commented
> 안녕하세요 성주님 과제하시느라 고생많았습니다! 😄
> 
> 일단 전반적으로 다소 복잡한 것 같아요! 의존성을 낮추기 위함으로 기능별 로직에 맞춰서 객체를 만드신 것 같다고 봤는데 맞나요..? 제가 생각하기엔 약간 과한 측면도 있고, Spring을 적절하게 활용하고 있는 것 같진 않습니다..😅 (구조가 일반적이지 않아 구조를 알아보기 어렵습니다,,,)
> 
> * 좀 더 공부하시면서 확장에 유연할 수 있는 구조인지, 남들이 보기에 이해하기 수월한지 생각해보시면 좋을 것 같습니다~!
> 
> 질문 주신 내용에 답변 드리자면
> 
> > VoucherService에서 구현한 것처럼 Enum에 Bean(인터페이스 구현체)이름을 설정하고, runBeanMapByMenu를 통해 적절한 Bean을 매핑하도록 하였습니다.
> > 이렇게 Enum에 Bean이름을 설정하는 것이 올바른 방식은 아니라고 생각이 들어서,, 동적으로 적절한 Bean을 선택하는 과정에서 어떠한 로직이 적절한 지 여쭤보고 싶습니다..!!
> 
> * 일단 Voucher를 Bean으로 등록하시려는 이유가 궁금합니다!! Voucher가 Bean으로 등록되어야 하는 이유가 있나요..? ([Bean의 의미](https://engineerinsight.tistory.com/44)에 대해서도 공부해보시면 좋을 것 같네요~)

2023-06-27 13:28 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/io/IODevice.java
> +public interface IODevice {
IODevice를 추상화 시켜두었지만, 사실 아래와 같은 로직들이 들어 있어서 추상화 됐다고 보기 어려울 것 같아요
```java=

    default void outputMenus() {

        TextIO textIO = TextIoFactory.getTextIO();
        TextTerminal<?> terminal = textIO.getTextTerminal();

        terminal.printf("\n\n=== Voucher Program ===\n" +
                "아래 메뉴 중 하나를 입력하세요.\n" +
                "1. exit (프로그램 종료)\n" +
                "2. create (새로운 바우처 생성)\n" +
                "3. list (모든 바우처 확인)\n");
    }

    default void outputVoucherMenus() {

        TextIO textIO = TextIoFactory.getTextIO();
        TextTerminal<?> terminal = textIO.getTextTerminal();

        terminal.printf(
                "\n(바우처 선택) 아래 메뉴 중 하나를 입력하세요.\n" +
                "1. Fixed amount voucher\n" +
                "2. Percent discount voucher\n");
    }
```

웹으로 구현해달라는 요구사항이 있으면 이 로직들은 다 지워야하지 않을까요?

2023-06-27 14:02 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/io/IODevice.java
> +public interface IODevice {
앗 네넵!! 추상화가 됐다고 보기 어렵겠네요..ㅠㅠ
제 의도와는 다르게 간과한 점이 있었네요.. 수정 해보겠습니다!!
구체적인 피드백 감사드립니다!!! 😁

2023-06-29 08:21 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/voucher/repository/FileVoucherRepository.java
> +        return findAll().stream().filter(voucher -> voucher.getVoucherId() == voucherId)
파일에 데이터가 많으면 OOME(Out Of Memory Error)가 발생할 수 있습니다 😂

2023-06-29 08:24 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/config/VoucherConfig.java
> +    }
스프링에서는 Bean은 싱글톤으로 관리합니다! 그러면 하나의 Voucher가 생성되는데 이를 어디에 사용하시려는 것인지 저는 잘 이해가 가지 않습니다~!

2023-06-29 08:26 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/config/VoucherConfig.java
> +
"어떤 Voucher를 생성할 지를 결정하기 위해 각 Voucher가 Map을 통해 주입" 이부분이 약간 이해가 잘 안되네요..😂

어떤 Voucher를 생성할 지를 결정하기 위해 Voucher 가 주입이 되어야 하나요..? If나 분기문을 제거하고자 하신건가요..?

2023-06-29 08:29 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/config/VoucherConfig.java
> +
내부 코드는 두가지 타입의 Voucher를 Bean으로 등록할 뿐인 것 같은데,, 이를 Voucher에 관한 설정이라고 볼 수 있을까요?

2023-06-29 08:31 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/config/VoucherConfig.java
> +
네..ㅎㅎ 처음에 접근할 때는
> 어떤 Voucher를 생성할 지를 결정하기 위해 Voucher 가 주입이 되어야 하나요..? If나 분기문을 제거하고자 하신건가요..?

위 의도로 작성하긴 했는데, 주성님의 피드백을 받고나서 Voucher가 Bean으로 등록될 필요가 전혀 없음을 깨닫고
Simple Factory 방식으로 if문을 제거하였습니다..!!! 😃

2023-06-30 12:39 UTC, JoosungKwon reviewed
성주님 고생하셨습니다~ 😄 멘토님께 이야기 드리고 Merge후에 다음 과제 PR로 넘어가도 좋습니다
간단한 리뷰 남겼으니 참고 부탁드립니다~!!

2023-06-30 12:39 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/voucher/PercentDiscountVoucher.java
> +    }
`long` 타입을 `long` 타입으로 나누게 되면 어떻게 되나요?

2023-06-30 12:39 UTC, JoosungKwon commented on src/main/java/org/devcourse/springbasic/validator/VoucherMenuValidator.java
> +    }
```suggestion
public class VoucherMenuValidator implements Validator<String> {

    @Override
    public boolean validate(String valueToVerify) {
        Matcher matcher = RegexPattern.NOT_INPUT_MENU_PATTERN
            .matcher(valueToVerify);
        return matcher.find();
    }
}

```
이렇게 사용하는게 보다 올바를 것 같습니다~!

2023-07-02 07:31 UTC, JoosungKwon commented
@Seongju-Lee 질문이 있었는데 제가 확인을 못했네요!! 😅

답변드리자면

> 의존관계를 끊는 것을 목적으로 작성해봤는데 적절하게 분리된 것인지 궁금합니다..!!

- 사실, 약간은 복잡하고 일반적인 형태는 아니라는 생각이 듭니다! 다만, 제 개인적인 생각은 다양한 시도 자체가 좋은 경험이라고 생각합니다. 저 또한 정답이 절대 아니기 때문에 스스로 이런 저런 시도를 해보는 것은 좋다고 생각합니다. 과제는 시험이 아닌 연습입니다. 다음 주차 과제로 이어가시면서 많은 깨달음을 얻을 수 있으면 좋겠습니다!! 👍

> 스프링에 의존적이게 되면 어떠한 불리함이 있을 지에 대해 생각해보는 계기가 되었습니다.
이번 피드백에서 "왜 Bean으로 등록 했는 지"에 대한 질문을 받았는데요, 편리하게 Map을 통해 자동으로 주입받아 Bean이름을 통해서 구현체를 선택하고자 하는 의도였습니다... 근데, 왜 마구잡이로 등록하면 안되는 지에 대해 생각해봤을 때
제가 들었던 느낌은 예상치 못한 곳에서 의존관계가 꼬이고 명확하게 분리되지 않아 찾기 어렵다는 생각이 들었습니다.
=> 스프링에 의존적이게 되면 어떤 불리함이 있는 지 멘토님들께 한번 여쭤보고 싶습니다..!!

- 일단, 스프링에 의존적이면 안좋은 이유는 여러가지가 있습니다. 성주님은 왜 의존성을 제거하셨나요? 보통, 의존성을 제거하는 이유는 유지 보수의 용이함 때문인 경우가 많습니다. 스프링에 의존적이면 좋지 않은 이유도 비슷할 수 있겠네요. 다만, 현재 상황은 의존에 문제라고 보여지기 보다는 다른 문제인 것 같습니다.

- 제 추측이 틀릴 수도 있습니다만, 네이비 멘토님이 말씀하신 스프링에 의존적인 형태이다의 의미는 스프링을 억지로 사용하려고 하는 모습이 보이기 때문이 아닌가 싶습니다. 제 생각에는 Bean이 가지고 있는 의미를 잘 모르고 활용하고 있다고 보여집니다. Bean의 용도는 Component 라고 볼 수 있습니다. Voucher를 Component라고 볼 수 있을까요? 그리고 Bean으로 등록된 객체는 싱글턴으로 관리가 됩니다. 어떤 의도였는지 잘 모르겠지만 쿠폰 발행 서비스에서 쿠폰이 하나의 객체로 표현되어야 하는 이유가 있나요?

- 그리고 성주님이 `왜 마구잡이로 등록하면 안되는 지에 대해 생각해봤을 때 예상치 못한 곳에서 의존관계가 꼬이고 명확하게 분리되지 않아 찾기 어렵다` 고 말씀하셨는데 맞는 말입니다. 잘 모르는 상태로 마구 사용하면 언제 어디서 어떻게 문제가 발생할지 모르게 되고 유지 보수 하기도 쉽지가 않습니다. 

- 잔소리가 길어서 죄송합니다. 결론을 말씀 드리면 제 생각은 스프링을 제대로(적재적소에) 활용하고 있지 않는 것이 문제라고 보여집니다. 

> Spring Layer를 표현계층(presentation)-서비스계층(service)-데이터 접근계층(data access)으로 나뉘었을 때, 보통 각 계층의 예외를 각 계층마다 따로 처리하는 지 궁금합니다..!! 아니면 데이터계층과 서비스 계층에서 발생한 예외를 표현계층으로 올려서 예외처리를 진행하는 지 궁금합니다!!

- 저라면, 예외에 따라 다른 동작이 필요하다면 해당 레이어에서 처리하고 아니라면, 최상단에 통합적으로 처리할 것 같네요! 다만, 예외가 다른 레이어로 전파되는 것 자체가 의존하게 되는 형태라면 문제가 될 수 있다고 생각이 되네요! 그리고 예외는 발생하는 지점에서 멀리 처리하게 될수록 추적하기 어려워 진다고 생각합니다. 성주님의 생각도 궁금하네요!

2023-07-08 10:38 UTC, merged