[4기] 고범준 3차 사용자의 콘솔 입력, 출력 구현
prgrms-be-devcourse/springboot-basic pull request #694
Opened 2023-06-26 07:47 UTC by K-jun98

## 📌 과제 설명 

### 2차 PR 2차 리뷰 반영
### 사용자의 콘솔 입력, 출력 구현

## ✅ 피드백 반영사항 
예외테스트를 진행할때 예외메시지의 내용은 검증하지 않음
바우처 ID를 검증하는 방법으로 변경
바우처 팩토리를 멤버변수로 변경
바우처 ID를 바우처 팩토리에서 생성함
null 검증 중복 메서드 제거
바우처를 조회할때 ID도 함께 조회함
팩토리 메서드 네이밍 변경
바우처 타입 반환 로직변경

## ✅ PR 포인트 & 궁금한 점 

### 2차 PR 리뷰에서 궁금한 점
- 현재는 커스텀 예외가 아닌 표준 예외를 사용하고 있습니다. 예외메시지를 검증하지 않으면 표준 예외이기 때문에 정확한 검증이라고 할 수 있을까? 라는 의문이 들었는데 리뷰어분들의 의견이 궁금합니다.
- 리뷰반영의 대해서는 Squash Merge를 사용해봤는데.. 오히려 보기 불편하신지 궁금합니다.
-

2023-06-26 16:21 UTC, dojinyou reviewed
전체적으로 깔끔한 것 같아요!

2023-06-26 16:21 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/CommandLineApplication.java
> +        viewManager.showMessage(voucher.toString());
```suggestion
        UUID voucherId = voucherController.createVoucher(request);
        viewManager.showMessage(voucherId.toString());
```

2023-06-26 16:21 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/voucher/service/VoucherService.java
> +                .collect(toUnmodifiableList());
repository에서 unmodifiableList로 반환하는 건 어떨까요?

2023-06-26 18:50 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/CommandLineApplication.java
> +        }
저도 break;가 동작하면서 while을 벗어나길 기대했는데. `Expression, block or throw statement expected` 오류가 발생하더라고요.. 결국 중괄호로 감싸면 while 문을 벗어나지 않아서 제대로 동작하지 않아서 위에처럼 변경했는데.. 조금 더 가독성이 올라갈 방법을 고민해 보겠습니다!

2023-06-26 18:50 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/CommandLineApplication.java
> +        viewManager.showMessage(voucher.toString());
변경했습니다! 감사합니다
[996b119](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/996b119c8ccf3b1181e68b69ee8425fabcbbd766)

2023-06-26 18:51 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/voucher/service/VoucherService.java
> +                .collect(toUnmodifiableList());
변경했습니다! 감사합니다!
[e6b19dd](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/e6b19dde3333cd37dc9941398e9c8a0c1dbb4366)

2023-06-26 21:50 UTC, seung-hun-h requested changes
>현재는 커스텀 예외가 아닌 표준 예외를 사용하고 있습니다. 예외메시지를 검증하지 않으면 표준 예외이기 때문에 정확한 검증이라고 할 수 있을까? 라는 의문이 들었습니다. 예외메시지를 검증하지 않고 커스텀 예외를 만들어 검증하는 것도 고려해봐도 될까요?

커스텀 예외를 관리하는 것도 비용이 들어가요. 확실하게 커스텀 예외가 필요할 때 사용하는 것이 좋다고 개인적으로 생각합니다. 예외 구조화를 잘 해서 사용한다면 좋을 것 같아요.

예외 메시지 검증은 저도 예전에 고민한 적이 있습니다. 결론적으로는 내부 구현을 검증하는 것이라 판단해서 하지 않고 있어요. 깨지기 쉬운 테스트가 되어 버린다고 생각했거든요. 개인차가 조금 있는 것 같아요. 

> DTO 역할을 하는 VoucherDetailsResponse,VoucherCreateRequest 클래스가 서비스, 컨트롤러,콘솔애플리케이션 모두에 사용되고 있습니다. DTO를 분리하는 것이 좋다고 생각되지만 그렇게 되면 현재 프로젝트 크기에 비해 너무 많은 DTO가 생성된다고 생각합니다. 어떻게 생각하시는지 궁금합니다.

dto를 결국 어디에서 관리하는지가 문제인 것 같습니다. 컨트롤러에서 관리하는 경우에는 서비스에서 사용하면 안될 것이고, 서비스에서 관리하면 컨트롤러에서 사용해도 괜찮겠죠. 모든 레이어에서 서로 다른 dto를 생성할 필요는 없는 것 같아요.

2023-06-26 21:50 UTC, seung-hun-h commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +            "Type list to list all vouchers.\n";
```suggestion
    private static final String INPUT_COMMAND_MESSAGE = """=== Voucher Program ===
            Type exit to exit the program.
            Type create to create a new voucher.
            Type list to list all vouchers.""";
```

2023-06-26 21:50 UTC, seung-hun-h commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +            "Type percent {1 ~ 100}\n";
1, 100은 도메인 정보 같네요. PercentDiscountVoucher에서 가져오는게 좋아보이네요.

2023-06-26 21:50 UTC, seung-hun-h commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +    }
raw은 위험합니다. 어떤 타입도 가능하기 때문이죠. 제네릭을 사용할 수 있도록 수정해주세요.

https://dahye-jeong.gitbook.io/java/java/effective_java/2021-05-19-generic-dont-use-raw-type

2023-06-26 21:50 UTC, seung-hun-h commented on src/test/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepositoryTest.java
>      private final VoucherRepository voucherRepository = new InMemoryVoucherRepository();
테스트가 여러개 작성되면 다른 테스트에 영향을 미칠 수 있지 않을까요?

2023-06-27 01:41 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/CommandLineApplication.java
> +        }
아 여기서 핵심은 별도로 readCommand 함수를 2번 호출하지 말고 1번만 호출하면 된다는 거에요!

2023-06-27 02:20 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/CommandLineApplication.java
> +        }
```suggestion
        Command command;
        while ((command = viewManager.readCommand()) != EXIT) {
            switch (command) {
                case CREATE -> createVoucher();
                case LIST -> showAllVouchers();
            }
        }
```
이렇게 해도 될 거 같아요!

2023-06-27 03:29 UTC, dojinyou reviewed
특별히 코멘트 드릴 게 없을 것 같습니다! 
지금 달려있는 코멘트만 체크해주세요!

2023-06-27 03:29 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/view/Command.java
> +
[super nit]
```suggestion

    CREATE,
    LIST,
    EXIT,
    ;

```
아주 nit한 거지만 요렇게 해주시면 나중에 새로운 값이 추가되거나 지워졌을 때 git에서 체크하는 변경 사항이 실제 변경된 부분만 볼 수 있어서 좋습니다!

2023-06-27 03:29 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/view/Command.java
> +    private static final String INVALID_COMMAND_MESSAGE = "는(은) 실행할 수 없는 명령입니다.";
[nit]
이 케이스 큰 문제가 아니지만 + 연산보다는 String format을 활용하면 더 가독성이 좋을 때도 있어서 참고하시면 좋을 것 같아요!

2023-06-27 03:29 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +    private static final String SPACE = " ";
`SPACE`보다 `SEPERATOR`가 조금 더 나아보이는 데 어떠신가요?

2023-06-27 03:29 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepository.java
> +    public Collection<Voucher> getAllVouchers() {
질문) Collection을 사용하시는 이유가 뭐에요?!

2023-06-27 07:16 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepository.java
> +    public Collection<Voucher> getAllVouchers() {
getAllVouchers를 사용하는 곳에 순서나 중복성의 대한 정보를 전달하지 않아 추가적인 요구사항이 존재한다면 직접 처리해야한다는 의미를 갖는다고 생각합니다. 현재 요구사항에는 순서를 유지해야거나 중복을 제거해야한다는 사항이 없어서 조금 더 유연성을 가진 Collection을 갖도록 했는데. 레포지토리에서 특정 타입을 리턴하는게 좋을지 궁금합니다.

2023-06-27 07:16 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/CommandLineApplication.java
> +        }
감사합니다! 반영했습니다!
[9f188ef](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/9f188ef1f8acd050932fdb24baca014cf05f13d7)

2023-06-27 07:17 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +            "Type list to list all vouchers.\n";
감사합니다! 반영했습니다
[c14f0eb](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/c14f0eb454887850d65c281839778c1855137f17)

2023-06-27 07:18 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +            "Type percent {1 ~ 100}\n";
감사합니다. 처음에는 뷰에서 도메인 정보에 접근하는게 변경에 유연하지 못하다고 생각했는데. 이 부분은 변경된다면 같이 변경되는게 맞다고 생각이 들어 변경했습니다. 그리고 VoucherType에서 관리하는게 더 좋아보여 이 부분도 같이 변경했습니다.
[a1988aa](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/a1988aa1c14472adf199c0bcaa335e0588ca9ec3)

2023-06-27 07:18 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +    }
감사합니다! 반영했습니다
[5c07949](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/5c07949b348c96fd5251eef7d0b8f73506b22835)

2023-06-27 07:19 UTC, K-jun98 commented on src/test/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepositoryTest.java
>      private final VoucherRepository voucherRepository = new InMemoryVoucherRepository();
넵 이 부분은 현재 반영이 된건지..? 제 코드에는 보이지 않아서 따로 처리하지 않았습니다! 감사합니다

2023-06-27 07:19 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/Command.java
> +
오.. 꿀팁 감사합니다! 반영했습니다!
[d599980](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/d599980dbb74530f7244490ce2501ce4aca756b0)

2023-06-27 07:20 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/Command.java
> +    private static final String INVALID_COMMAND_MESSAGE = "는(은) 실행할 수 없는 명령입니다.";
감사합니다! 변경했습니다! 추가로 ViewManager에도 적용했습니다.
[86cf724](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/86cf724d1ebc0a6bfa98c838105a6624e1cf8abb)

2023-06-27 07:21 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +    private static final String SPACE = " ";
변경했습니다! `SEPERATOR` 는 다만 ',' , '|' 같은 것들 모두 될 수 있다고 생각해서 SPACE_ SEPERATOR로 변경했습니다. 감사합니다! [166fd38](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/166fd3802cf08dc2c271d09b26504ff5fa2dd6d7)

2023-06-27 10:36 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +    private static final String SPACE = " ";
오히려 `SPACE`라는 걸 안 적는 게 저는 중요하다고 생각했어요! 구체적인 형태보다는 이 친구가 하는 역할을 드러내서 설계만 담고 값은 굳이!?

2023-06-27 10:39 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepository.java
> +    public Collection<Voucher> getAllVouchers() {
꼭 그럴 필욘 없을 것 같아요! 이유가 있으면 된거죠!

2023-06-27 10:49 UTC, dojinyou commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +                , PERCENT.getMinimumAmount(), PERCENT.getMaximumAmount()));
```
 private static final String VOUCHER_TYPE_MESSAGE = """
            === Voucher Type Choice ===
            %s
            """;
```

요렇게 하고 `VoucherType.getDisplayMessage()` 같은 걸로 가져와서 넣는 건 어떨까요?
`VoucherType.getDisplayMessage()` 메서드는 `values()`로 순회하면서 개별 VoucherType의 메세지들을 가져와서 합치고 하나의 스트링으로 반환?

2023-06-27 10:51 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +    private static final String SPACE = " ";
오.. 그럴 수 있겠군요 좋은 의견 감사합니다!

2023-06-27 10:53 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +                , PERCENT.getMinimumAmount(), PERCENT.getMaximumAmount()));
오오.. 아 이 부분이 조금 지저분 하다고 생각하긴 했는데 좋은거같습니다! 감사합니다!!

2023-06-27 11:27 UTC, K-jun98 commented on src/main/java/com/dev/bootbasic/view/ViewManager.java
> +                , PERCENT.getMinimumAmount(), PERCENT.getMaximumAmount()));
이 부분은 바로 변경해서 적용해봤습니다. " ", "~" 같은 자주 사용되는 구분자는 Constant 클래스를 만들어서 관리하기 위해 분리했습니다.
[f936f55](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694/commits/f936f559749bdc354d43602f22400fed8364b7bc)

2023-06-27 13:43 UTC, seung-hun-h commented on src/main/java/com/dev/bootbasic/voucher/domain/VoucherType.java
> +    }
화면에 보여주기 위한 메시지는 view에서 만들면 좋을 것 같아요.
view에서는 VoucherType의 정보를 가지고 화면에 보여줄 텍스트를 만들면 되겠죠.

2023-06-28 07:41 UTC, merged