Weonest/week2
prgrms-be-devcourse/springboot-basic pull request #696
Opened 2023-06-26 08:55 UTC by weonest

![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/98159941/3c34ac07-067e-4cfd-bc9c-b463690db20c)

## 📌 과제 설명 
- 기존의 `Interface` 방식으로 구현했던 `Voucher` 클래스를 `Discount`의 다형성을 이용하여 단순 클래스만으로도 기능이 가능토록 변경하였습니다.
 

## ✅ 피드백 반영사항   
- 상수 네이밍 규칙 적용
- 파일 마지막 개행 
- 불필요한 코드 삭제
- 퍼센트 연산 불필요했던 형변환 수정
- 유효기간 값 객체 생성
- 테스트 코드 가독성 수정

## ✅ PR 포인트 & 궁금한 점 
- DTO, Domain Obejct, Entity Obejct에 관한 설명을 들은 이후 다른 멘티분과의 대화 도중 `Mapper`를 적용하면 편하겠다 생각하였고 이를 적용해보고자 하여 `VoucherMapper`도 구현하여 사용해보았는데 올바르게 사용했는지 궁금합니다!
-  유효기간을 `Voucher`내에서 갖지 않도록 하기 위해서 `ExpirationDate` 클래스를 생성하여 비교만 하는 식으로 구성해보았습니다. 이 `ExpirationDate`내에서 유효기간에 대한 값을 가져야 할지 지금처럼 인자로만 비교를 해야할지 잘 모르겠습니다.
- Console 부분 관련하여 입력값에 Test 코드를 어떤식으로 가져가면 좋을지 잘 모르겠습니다.

2023-06-26 12:18 UTC, dojinyou requested changes
reviewer 등록 해주시고 앞서 pr에 comment 확인하시길 바랍니다.

2023-06-26 12:18 UTC, dojinyou commented on src/main/java/com/programmers/console/util/Command.java
> +    }
[전에 코멘트](https://github.com/prgrms-be-devcourse/springboot-basic/pull/655#discussion_r1241053351) 한 것 같은 데, type 필드가 불필요한 거 같은데 왜 자꾸 생성하시나요?
단순히 name 필드의 lowerCase가 command라면 별도로 저장하고 있어야 하는 이유가 있나요

2023-06-26 12:18 UTC, dojinyou commented on src/main/java/com/programmers/console/view/OutputView.java
> +    void print(String message);
위 2가지 메서드와 아래 2가지 메서드의 추상화 레벨이 다르게 느껴져요.

2023-06-26 12:18 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    private final LocalDateTime createdDate;
타입과 변수명이 불일치 하는것 같아요

2023-06-26 12:18 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/VoucherType.java
> +    private final String command;
ordinal과 다른 가요?

2023-06-26 12:18 UTC, dojinyou commented on src/main/java/com/programmers/voucher/dto/VoucherResponseDto.java
> +public class VoucherResponseDto {
record 안 쓰신 이유가 있나요?

2023-06-26 12:18 UTC, dojinyou commented on src/main/java/com/programmers/voucher/util/ExpirationDate.java
> +public class ExpirationDate {
클래스 자체가 필요한 지 잘 모르겠어요

2023-06-26 12:18 UTC, dojinyou commented on src/test/java/com/programmers/console/view/ConsoleTest.java
> +}
?

2023-06-26 12:18 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountTest.java
> +        if (expected < 0 ) expected = 0;
expected도 source에 넣고 parameter로 받는 게 좋을 것 같아요

2023-06-26 12:18 UTC, dojinyou commented on src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
> +        VoucherRequestDto requestDto = new VoucherRequestDto(id, discount);
불필요한 개행으로 가독성이 떨어지는 것 같아요

2023-06-26 13:35 UTC, seung-hun-h requested changes

2023-06-26 13:35 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/VoucherMapper.java
> +    public static Voucher requestDtoToDomain(VoucherRequestDto requestDto) {
메서드는 동사 혹은 동사구로 작성해주세요

2023-06-26 13:35 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Discount.java
> +        throw new IllegalArgumentException("");
예외 메시지는 왜 없나요?

2023-06-26 13:35 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/entity/VoucherEntity.java
> +public class VoucherEntity {
Voucher와 차이가 뭔가요?

2023-06-26 13:35 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    private static final Map<UUID, VoucherEntity> storage = new ConcurrentHashMap<>();
상수 네이밍 규칙을 지켜주세요

2023-06-26 13:35 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        }
아무것도 저장되어 있지 않는 것이 예외 상황이라고 생각하신 이유가 뭔가요?

2023-06-26 13:35 UTC, seung-hun-h commented on src/main/java/com/programmers/global/exception/DiscountValueException.java
커스텀 예외를 만들어서 사용하고 계시는데요, 이유가 있을까요?
catch 해서 예외를 따로 처리하고 있지 않은 것 같아서요.

2023-06-27 14:12 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +        Discount discount = Discount.of(voucherType, inputDiscountInfo());
21d5ff0fd1607e6afae9ddbe447c6ebb81f8440e
통일된 구조로 변경하였습니다!

2023-06-27 14:14 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +        while (true) {
사용자 편의를 생각해서 입력 값이 틀린 경우에 초기 메뉴 선택 화면으로 돌아가는 것이 아니라 올바른 값을 다시 입력받로록 구현하기 위함이었습니다. 
누군가 고의로 해당 반복문 내에서 오류를 무한히 반복하게 되는 경우를 생각하면 이런 구조는 지양하는 것이 좋을까요?

2023-06-27 14:35 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +            }
불필요한 반복문 및 `try`문을 제거하며 삭제하였습니다. 해당 부분도 위와 마찬가지로 반복문 내부에 동작들의 연관관계를 제대로 인지하지 못하고 작성하여 불필요한 예외를 처리했던 것 같습니다.
aba0da4

2023-06-27 14:44 UTC, weonest commented on src/main/java/com/programmers/console/util/Command.java
> +    }
970ca39b933d1366222cd3b33beaae669e22599c
enum에 대한 이해가 부족했던 것 같습니다. 전에 코멘트 해주셨던 부분 제대로 확인 못한 점 죄송합니다! 내부에 불필요한 type을 없애고 `valueOf`로 해당 enum을 가져올 수 있도록 변경하였습니다!

2023-06-27 14:58 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/DiscountTest.java
> +        if (expected < 0 ) expected = 0;
c62e2f0703a03745b52f559193aff2eb2ad6aed6
적용하였습니다!

2023-06-27 15:04 UTC, weonest commented on src/main/java/com/programmers/voucher/util/ExpirationDate.java
> +public class ExpirationDate {
후에 서비스 로직에서 바우처를 사용하려고 할 때 해당 클래스를 통해 유효기간을 비교하려고 하는데 방법이 잘못된 것 일까요?

2023-06-27 16:02 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/VoucherMapper.java
> +    public static Voucher requestDtoToDomain(VoucherRequestDto requestDto) {
98f8866623c85f00b7a9d0c2211eb662163dfcfe
동사구로 적용 완료하였습니다!

2023-06-27 16:21 UTC, weonest commented on src/main/java/com/programmers/voucher/entity/VoucherEntity.java
> +public class VoucherEntity {
`VoucherEntity`는 도메인 로직이 들어있지 않은 순수 데이터 객체로 구현하였습니다.

2023-06-27 16:25 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    private static final Map<UUID, VoucherEntity> storage = new ConcurrentHashMap<>();
0d68e058e37b75c02935f613284adc77339f76e7
적용하였습니다!

2023-06-28 04:20 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +        }
6b7256365267f2a94195054c9b3f5a76a61b81e2
팀 미팅때 이야기 하신 대로 페이지에 게시글이 비어있더라도 예외가 아닌 것처럼 예외를 처리하지 않도록 변경하였습니다.

2023-06-28 04:46 UTC, weonest commented on src/main/java/com/programmers/global/exception/DiscountValueException.java
053557b5f07f1671710b721f73b167219bc54d4a
팀 미팅 이후 필요치 않은 커스텀 예외를 모두 삭제하고 기본 예외들을 적용하였습니다.

2023-06-28 04:49 UTC, weonest commented on src/main/java/com/programmers/console/view/OutputView.java
> +    void print(String message);
94cee8bea2c9d4c4f61f0d6562e9b3fc1c315f28
피드백 남겨주신 부분에 대한 이해가 부족하여 우선은 다음과 같이 변경하였습니다. 여기서 말하는 추상화 레벨이 무엇인지 궁금합니다!

2023-06-28 04:53 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
> +        print(ARROW);
점점 수정을 하다보니 이와 같은 구조가 되었는데 굳이 인터페이스 구현을 하지 않고 `Console` 단일 객체로 변경해도 될까요?

2023-06-28 04:54 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    private final LocalDateTime createdDate;
죄송합니다ㅜㅡ 세 가지 변수 중 어떤 부분을 말씀해 주신 건지 잘 모르겠습니다.

2023-06-28 05:06 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/VoucherType.java
> +    private final String command;
e143cc609ac29c61e679d0ae9a0d8bfeb04a08d6
`ordinal()`을 알게되어 적용해보았습니다!

2023-06-28 05:15 UTC, weonest commented on src/test/java/com/programmers/console/view/ConsoleTest.java
> +}
fa52fcdbad067fa006b3c9010c9646fb6c21c936
불필요한 코드 삭제하였습니다.

2023-06-28 05:29 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    }
e8e96948f7944fba709876dcfb3fd1de411fb994
책임을 분리해보았는데 올바르게 변경한 것인지 궁금합니다!

2023-06-28 11:55 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/entity/VoucherEntity.java
> +public class VoucherEntity {
VoucherResponseDto로 dto는 통일하고, VoucherEntity를 Storage에 저장하고 있는데 그건 Voucher로 일단 해보면 좋을 것 같아요.

2023-06-28 12:13 UTC, seung-hun-h commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    }
이건 메서드로 분리하신 이유가 있을까요?

2023-06-28 12:13 UTC, seung-hun-h commented on src/main/java/com/programmers/console/view/Console.java
> +    public <T> void print(T message) {
제네릭으로 변경하신 이유가 있을까요?

2023-06-28 12:13 UTC, seung-hun-h commented on src/main/java/com/programmers/console/view/Console.java
> +    }
새로운 Discount 타입이 생기고, 여기를 수정하지 않으면 잘못된 정보를 사용자에게 줄 수 있을 것 같아요.

2023-06-28 12:13 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Discount.java
> +    private final long value;
`value`를 여기서 가지고 있는 이유가 있나요?

2023-06-28 12:13 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    private final LocalDateTime createdDate;
`createdDate`인 것 같아요

2023-06-28 12:13 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/VoucherType.java
> +                .filter(voucherType -> voucherType.ordinal() == Integer.parseInt(command) - FOR_INDEX)
ordinal은 자바 내부에서만 사용하는 거라, 우리는 사용하면 안됩니다!

https://kukim.tistory.com/69

2023-06-28 12:13 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/util/ExpirationDate.java
> +public class ExpirationDate {
바우처 유효기간은 바우처에서 검증하는게 좋지 않을까요?

2023-06-28 14:34 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    private final LocalDateTime createdDate;
b6578bba5773e2958ee6613f4ecd86e79d6378a7
변경 완료하였습니다!

2023-06-29 02:51 UTC, dojinyou commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    }
저라면 create()라는 메서드는 그냥 주고 입력, 생성, 출력을 구분해서 3개의 메서드로 처리했을 것 같아요!
아니면 다 풀어서 처리?
```java
    private void createCommand() {
        VoucherRequestDto request = createRequestByUserInput();
        VoucherResponseDto createdVoucherResponse = createVoucher(request);
        printVoucher(createdVoucherResponse);
    }
    
    private VoucherRequestDto createRequestByUserInput() {
        VoucherType voucherType = inputVoucherInfo();
        long discountInfo = inputDiscountInfo();
	    Discount discount = Discount.of(voucherType, discountInfo);
        VoucherRequestDto requestDto = new VoucherRequestDto(UUID.randomUUID(), discount);
    }

    private VoucherResponseDto createVoucher(VoucherRequestDto request) {
    	return voucherController.create(request);
    }
    
    private void printVoucher(VoucherResponseDto reponse) {
        console.printVoucher(reponse);
    }
```

2023-06-29 02:54 UTC, dojinyou commented on src/main/java/com/programmers/voucher/util/ExpirationDate.java
> +public class ExpirationDate {
승훈님 말씀처럼, 기본 타입을 활용하고 필요한 로직은 바우처 내부에 가지고 있는 게 더 좋다고 생각해요!
아무래도 시간을 나타내는 기본적인 타입들이 제공되니까요!

2023-06-29 04:08 UTC, dojinyou reviewed
코멘트 확인해주세요!

2023-06-29 04:08 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountValueTest.java
> +            0,
🔪

2023-06-29 04:37 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    }
ae69e80c37b3076d39df1fa8affad67001fbf322
피드백 주신 부분들을 참고하여 반영하였습니다!

2023-06-29 04:46 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +                e.getStackTrace();
피드백 반영 중 잘못 입력했던 것 같습니다! 수정하였습니다.

2023-06-29 04:48 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    }
ae69e80c37b3076d39df1fa8affad67001fbf322
도진님도 같은 부분에 대한 피드백을 주셔서 다음과 같이 변경하였습니다.

2023-06-29 04:51 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
> +    public <T> void print(T message) {
```java
 void printVouchers(List<VoucherResponseDto> vouchers);

    void printVoucher(VoucherResponseDto responseDto);

    void println(String message);

   void print(String message);


```
이전에 도진님이 위의 두 메서드와 아래의 두 메서드의 추상화 레벨이 다른 것 같다고 말씀하셨었는데, 추상화 레벨이 다르다는 부분을 잘 모르겠어서 우선은 제네릭으로 바꾸는 건가? 하고 변경했었습니다. 피드백 주시면 감사하겠습니다!

2023-06-29 05:55 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
> +    }
98bbddfd741e4450c1b234c41a94ca0573548549
잘못된 정보를 넘겨주지 않도록 수정하였습니다.

2023-06-29 05:57 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +    private final Console console;
56d3c151d085cdb6de37dd0d4a08d08906eaabce
이 부분에 대해서 은근 고민이 많았었는데 피드백 해주셔서 너무 감사드립니다!

2023-06-29 05:58 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Discount.java
> +    private final long value;
98bbddfd741e4450c1b234c41a94ca0573548549
지난 밤에 승훈님께서 말씀해 주신대로 수정하였습니다!

2023-06-29 06:04 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/VoucherType.java
> +                .filter(voucherType -> voucherType.ordinal() == Integer.parseInt(command) - FOR_INDEX)
596ab03788aaf9a1949f3205b64cfb65fb04ae3f
해당 부분 반영하였습니다!

2023-06-29 06:10 UTC, weonest commented on src/main/java/com/programmers/console/util/ConsoleMessage.java
> +            """),
61d6671c3545204830d2f5d161b29f7a8c84a4c3
적용 완료하였습니다.!

2023-06-29 06:13 UTC, weonest commented on src/main/java/com/programmers/console/view/Console.java
>          return scanner.nextLine().trim().toLowerCase();
소문자 대문자와 관계없이 올바른 스펠링이 들어왔다면 정상적이라고 판단하기 위해서 모두 소문자로 치환해주었습니다.

2023-06-29 06:14 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/DiscountValueTest.java
> +            0,
5da55fa7f8ccd00c7e1db9370e730f3d6976943b
0에 대한 테스트가 겹치므로 삭제하였습니다!

2023-06-29 06:36 UTC, weonest commented on src/main/java/com/programmers/voucher/entity/VoucherEntity.java
> +public class VoucherEntity {
7eac62108d201b0b96b3943514e6d9099f130ff9
`VoucherEntity`를 적용하지 않고 `Voucher`를 적용할 수 있도록 변경하였습니다.

2023-06-29 07:35 UTC, weonest commented on src/main/java/com/programmers/voucher/util/ExpirationDate.java
> +public class ExpirationDate {
909b8e10d6981490cf9bfd66fd2ac345cca83923
바우처 내부에서 유효기간에 관련된 처리를 할 수 있도록 변경하고 테스트를 추가하였습니다!

2023-06-29 08:31 UTC, dojinyou reviewed
다음번 pr에 반영해주세요!

2023-06-29 08:31 UTC, dojinyou commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +                Command command = Command.of(console.inputMenu());
한 줄이 하나의 행위만 하는 것이 좋을 것 같아요!
```suggestion
                String inputMenuText = console.inputMenu()
                Command command = Command.of(inputMenuText);
```

2023-06-29 08:31 UTC, dojinyou commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +                Command command = Command.of(console.inputMenu());
이러니 뭔가 어색해보이는 거 같은 데 어떠세요?

2023-06-29 08:31 UTC, dojinyou commented on src/main/java/com/programmers/console/view/Console.java
> +    public <T> void print(T message) {
요기서 제가 코멘트한 건 `print/println`은 직접적인 출력 메서드이고고 `printVoucher`는 이러한 출력을 활용한 도메인에 의존적인 메서드라고 생각했어요. 그래서 메서드 간의 추상화가 안 맞다고 생각했어요. 그래서 한쪽으로 정리하면 좋을 것 같다고 생각했어요.

그래서 제가 원한 방향은 아래와 같아요.
1. 직접적인 출력 메서드를 노출하고 외부에서 형태를 String으로 만들어서 넣어준다.
2. 도메인에 의존적인 메서드만 만들거 내부에서 출력 메서드를 이용한다.

2023-06-29 08:31 UTC, dojinyou commented on src/main/java/com/programmers/console/view/Console.java
> +        if (discount instanceof FixedDiscount fixedDiscount) {
인스턴스 확인보다 추상화 메서드 getAmount를 선언하고 (필드 선언x) 그에 맞는 필드를 적절하게 구현체에서 반환해주는 건 어떠신가요?

2023-06-29 08:31 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountValueTest.java
> +            -1,
[nit]
개인적으로 int나 long 타입을 쓰면 맥스 민 밸류에 대해서도 테스트를 하는 편이에요!

2023-06-30 01:42 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/controller/VoucherController.java
> +        return voucherService.findVouchers().stream().map(VoucherMapper::convertDomainToResponseDto).toList();
```suggestion
        return voucherService.findVouchers().stream()
		        .map(VoucherMapper::convertDomainToResponseDto)
		        .toList();
```
별건 아니지만 스트림을 사용할 때는 이렇게 작성하는 편이 가독성이 좋은 것 같아요

2023-06-30 01:42 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Discount.java
> +    private final VoucherType voucherType;
이거는 고민해보고 수정해주세요. Voucher가 Discount를 사용하고 있는데, Discount가 Voucher의 정보를 알고 있는 것 같아서요.

2023-06-30 01:42 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    private final LocalDateTime expiration;
```suggestion
    private final LocalDateTime expiredAt;
```
는 어떤가요?

2023-06-30 01:42 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +    }
```suggestion
    public long discountWith(long itemPrice, LocatDateTime usedAt) {
        checkVoucherExpiration(usedAt);
        return discount.applyDiscount(itemPrice);
    }
```

바우처의 유효기간을 검증한다고 생각해볼게요. 내부에 `now()`를 호출하는 것 처럼 제어할 수 없는 값이 존재하면 검증하기 어려울 것 같아요. 예전에는 만료되지 않았던 테스트 코드가 시간이 지나서 만료될 수도 있을 것 같아요.

2023-07-03 08:18 UTC, merged