[4기 - 박은지] 2차 바우처 생성 및 조회 로직 구현
prgrms-be-devcourse/springboot-basic pull request #701
Opened 2023-06-26 15:37 UTC by 1o18z

## 📌 과제 설명 
이전 PR의 피드백을 반영 후 바우처를 생성, 조회하는 로직을 구현했습니다 ! 🚀
구현 하다보니 설계가 변경되어 다이어그램도 수정하여 올렸습니다 ! ☀️

## ✅ 설계도
<img width="650" alt="스크린샷 2023-06-26 오후 4 15 31" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/66556716/691b2360-ba07-4b42-a43a-3b29c685302f">

## ✅ 피드백 반영사항  
- [X] 검증 로직 추가 및 분리
- [X] 정적 팩토리 메소드 추가
- [X] 매직넘버 제거
- [X] 테스트코드 설명 추가 및 예외 테스트 추가
- [X] 접근 제어자 수정
- [X] 연산 로직 수정

## ✅ PR 포인트 & 궁금한 점 
- 별 의미가 있지 않은 테스트 코드를 작성해왔던 것 같아서 의미있는 테스트 코드를 작성하려고 노력했습니다 !
- VoucherFactory 클래스에서 팩토리 메소드를 사용해 입력받는 타입 검증을 하고, 두 타입을 경우를 나눠 아래 처럼 작성하려고 하였지만 테스트 코드가 제대로 동작하지 않았고, default를 작성하지 않은게 원인이란 걸 알았고 default를 추가했지만 작성하고 보니 이 상황에서 switch문을 사용하는 것이 적절한 지 의문이 들었습니다. 이 부분에 대해서도 피드백 주시면 감사하겠습니다 !☀️🍀
```
case "fixed" ->  . . .
case "percent" ->  . . .
```

2023-06-26 16:06 UTC, dojinyou reviewed
코멘트 확인 부탁 드려요!

2023-06-26 16:06 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/service/VoucherServiceTest.java
> +  VoucherService voucherService = new VoucherService(new MemoryVoucherRepository());
private final?

2023-06-26 16:06 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/service/VoucherServiceTest.java
> +  }
에러 메세지가 하드코딩되어 있어서 관리가 어려울 것 같아요

2023-06-26 16:06 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +    int result = createdFixedVoucher.discount(100000);
매직 넘버

2023-06-26 16:06 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
>      String voucherType = "fixed";
하드코딩

2023-06-26 21:29 UTC, seung-hun-h requested changes

2023-06-26 21:29 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +public class VoucherValidation {
클래스 이름은 VoucherValidator 정도가 좋을 것 같네요.
그리고 Validator가 도메인 정보를 가지고 있어서 수정이 필요해 보입니다. 각 Voucher들의 상수를 여기서 가져와서 사용하거나 메서드 자체를 범용적으로 설계하면 좋을 것 같아요.

2023-06-26 21:29 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +      return voucherType;
voucherType이 null이면 안 될 것 같네요. null check 로직이 필요해 보입니다.
https://www.baeldung.com/java-avoid-null-check

2023-06-26 21:29 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +
MAX 값은 요구사항에 없지만 은지님이 자체적으로 정해주면 좋을 것 같아요.

2023-06-26 21:31 UTC, seung-hun-h reviewed
> VoucherFactory 클래스에서 팩토리 메소드를 사용해 입력받는 타입 검증을 하고, 두 타입을 경우를 나눠 아래 처럼 작성하려고 하였지만 테스트 코드가 제대로 동작하지 않았고, default를 작성하지 않은게 원인이란 걸 알았고 default를 추가했지만 작성하고 보니 이 상황에서 switch문을 사용하는 것이 적절한 지 의문이 들었습니다. 이 부분에 대해서도 피드백 주시면 감사하겠습니다 !

코드가 제대로 동작하지 않은 원인에 대해서 조금 더 생각해보면 좋겠네요. String은 범용적으로 사용될 수 있는 타입이므로 바우처 유형을 나타낼 수 있는 타입을 만드는 것이 더 좋아보이네요.

2023-06-26 21:34 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +  public static String checkType(String voucherType) {
다른 메서드처럼 메서드 이름에 'check'가 들어가는데 일관성있게 어떤 값을 반환하는 것이 아니라 validation check 정도만 해주면 좋을 것 같네요.

2023-06-27 03:48 UTC, 1o18z commented on .idea/misc.xml
바로 반영했습니다 !!🔥🔥🔥

2023-06-27 05:05 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +    int result = price - getDiscountAmount();
discountAmount가 Voucher 추상 클래스에서 private final로 되어 있어서 getDiscountAmount로 가져와 사용하고 있었습니다 !!

2023-06-27 05:20 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +    int result = price - getDiscountAmount();
Voucher 추상클래스에서 discountAmount가 private final로 되어 있어서 getDiscountAmount로 가져와서 사용하고 있었습니다 !!

2023-06-27 07:58 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +      return voucherType;
감사합니다 !!🍀 자료 참고하여 null 체크하는 방법 대해 공부하겠습니다 !!🤩

2023-06-27 16:49 UTC, 1o18z commented on .idea/misc.xml
b79992c

2023-06-27 16:49 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/VoucherRepository.java
> +  Map<UUID, Voucher> findAll();
f1cc173

2023-06-27 16:49 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/service/VoucherService.java
> +  }
f1cc173

2023-06-27 16:49 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +  }
ed9952d

2023-06-27 16:49 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +
2c2c367

2023-06-27 16:49 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
> +    int result = price - getDiscountAmount();
2c2c367

2023-06-27 16:50 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +public class VoucherValidation {
1649d43
default 로 수정하였습니다 !! 🔥

2023-06-27 16:50 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherFactory.java
> +      default -> PercentDiscountVoucher.of(UUID.randomUUID(), voucherType, discountAmount);
ed9952d

2023-06-27 16:50 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/service/VoucherServiceTest.java
> +  VoucherService voucherService = new VoucherService(new MemoryVoucherRepository());
e79a3f0

2023-06-27 16:50 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/service/VoucherServiceTest.java
> +  }
e79a3f0

2023-06-27 16:50 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +    int result = createdFixedVoucher.discount(100000);
e79a3f0

2023-06-27 16:50 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
>      String voucherType = "fixed";
e79a3f0

2023-06-27 16:50 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +public class VoucherValidation {
591af1f

2023-06-27 16:50 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +      return voucherType;
ed9952d

2023-06-27 16:50 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +
591af1f

2023-06-27 16:50 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validation/VoucherValidation.java
> +  public static String checkType(String voucherType) {
기존에 있던 checkType을 제거하고 Enum에서 체크하도록 수정하였습니다 !!☀️
ed9952d

2023-06-27 17:11 UTC, 1o18z commented
## ✅ 피드백 반영사항  <!-- 지난 코드리뷰에서 고친 사항을 적어주세요. 재PR 시에만 사용해 주세요! (재PR 아닌 경우 삭제) -->
- [X] gitignore 처리 완료
- [X] 조회 반환 타입 변경
- [X] 변수명, 메소드명, 클래스명 수정
- [X] VoucherType enum 구현
- [X] 접근제어자 수정
- [X] 매직넘버 및 하드코딩 제거
- [X] 바우처타입 체크 로직 수정
- [X] FixedAmountVoucher 범위 지정


## ✅ 추가
- 피드백을 반영하다 보니 상속과 접근제어자에 대한 공부와 null 처리에 대한 공부가 많이 필요하다고 느꼈고 이 부분에 대해서 공부해 가며 앞으로 코드를 작성할 때도 주의하여 적절하게 적용하려 노력하려고 합니다 ! 💪🏻
- 현재 Voucher에 존재하는 getter들은 다른 클래스에서 사용 중입니다 !
    - 올려주신 getter/setter에 대한 영상 참고하여 getter 제거에 도전 중입니다 ! 🔥

2023-06-28 00:21 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +  protected final String voucherType;
접근 제어자를 protected로 변경하기 보다는 미팅 시간에 이야기 했던 것을 적용해보아도 좋을 것 같아요.

2023-06-28 00:21 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
> +    return result;
```suggestion
    return price - (price * discountAmount / PERCENT_RATE_BASE);
```

2023-06-28 00:21 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +            .orElseThrow(() -> new IllegalArgumentException(ERROR_MESSAGE));
어떤 `type`이 들어왔는지도 함께 메시지에 보여주면 좋을 것 같아요

2023-06-28 00:21 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  }
기본 생성자는 제거해도 되지 않을까요?

2023-06-28 00:43 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
> +    return result;
헉 바로 수정하겠습니다 !!!!!!

2023-06-28 00:44 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  }
바로 수정하겠습니다 !!!!🔥

2023-06-28 01:15 UTC, dojinyou reviewed
코멘트 확인 부탁 드려요!

2023-06-28 01:15 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  private static final Map<String, VoucherType> voucherTypes = new ConcurrentHashMap<>();
혹시 이 데이터가 왜 필요할까요??
그리고 `ConcurrentHashMap` 타입을 쓰신 이유가 있나요??

2023-06-28 02:03 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  private static final Map<String, VoucherType> voucherTypes = new ConcurrentHashMap<>();
enum에 대해 공부하다가 캐싱 방법을 사용하면 더 속도가 빠르다는 것을 알게되어 입력받은 타입을 체크할 때 적용해보았습니다 !

2023-06-28 02:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  private static final Map<String, VoucherType> voucherTypes = new ConcurrentHashMap<>();
혹시 이 데이터가 왜 필요할까요??
- enum에 대해 공부하다가 직접 체크하는 것보다 map에 저장해 두었다가 꺼내서 사용하면 더 속도가 빠르다는 것을 알게 되어 입력받은 타입을 체크할 때 적용했습니다 ! 현재는 타입이 두 종료밖에 있지 않아 성능상 차이가 별로 없을 수도 있을 것 같지만, 알아두면 나중에 유용하게 쓰일 것 같아서 적용해 보았습니다 !

그리고 ConcurrentHashMap 타입을 쓰신 이유가 있나요??
- 처음엔 HashMap을 사용하려 했었는데 HashMap은 null을 허용하기 때문에 null을 허용하지 않는 ConcurrentHashMap을 사용했습니다 !

잘못 알고 있는 부분이 있거나 더 좋은 방법이 있다면 피드백 주시면 적극 반영하겠습니다 !🤩

2023-06-29 04:21 UTC, merged

2023-06-29 17:03 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
> +    return result;
6644696

2023-06-29 17:08 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  }
6644696

2023-06-29 17:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  private static final Map<String, VoucherType> voucherTypes = new ConcurrentHashMap<>();
0a09d13