[4기] 유명한 사용자 입, 출력 기능 구현(콘솔)
prgrms-be-devcourse/springboot-basic pull request #707
Opened 2023-06-27 08:40 UTC by yumyeonghan

## 📌 과제 설명
- 사용자 입력 기능 구현입니다.
- 프론트 컨트롤러 패턴을 적용해서 전체적인 사용자 요청을 처리합니다.

## ✅ 피드백 반영사항
- 예외 메세지 형태 수정
  - 예외 메시지에 들어가는 범위 값에 상수 사용
  - 사용자가 입력한 잘못된 값도 같이 출력
- 매직 넘버 제거
- 개행 체크
- VoucherService 인터페이스 추가
- VoucherServiceImpl createVoucher() 반환타입 void -> UUID로 수정
- @Component 사용
- DTO 생성하는 정적 팩토리 메서드 패턴 적용
- MemoryVoucherRepository findByVoucherId() 저장소에 값이 비어있을 경우 빈 Optional 반환 추가
- Voucher 구현체에 voucherId 검증 로직 추가
- import java.util.* 지양
- VoucherFactory를 통해 클라이언트에서 바우처 생성시 구현체를 모르게 함

## ✅ 궁금한 점

- Console 클래스는 다른 스프링 빈들과 다르게 자바 라이브러리인 BufferReader나 BufferWriter를  생성자 주입을 하지않고, 직접 객체를 등록해 줬습니다. 이런식으로 사용해도 될까요? 아니면 직접 @Configuration 과 @Bean을 사용해서 다른 스프링 빈들처럼 객체를 자동 주입되게 해야할까요?

2023-06-27 11:17 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/command/Command.java
> +            case EXIT -> System.exit(1);
System 종료보다는 실행을 멈추는 방향으로 코드를 짜는 게 좋을 것 같아요

2023-06-27 11:17 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +public class CreateVoucherExecution implements VoucherExecution{
빈으로 등록 안한 이유가 있나요??

2023-06-27 11:17 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +    private static final String BLANK_STRING = " ";
`SEPARATOR` 같은 이름이 더 좋지 않을까요?

2023-06-27 11:17 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +        VoucherCreationRequest voucherCreationRequest = RequestFactory.createVoucherCreationRequest(typeAndAmount[TYPE_INDEX], Long.parseLong(typeAndAmount[AMOUNT_INDEX]));
```suggestion
        String[] typeAndAmount = io.read().split(BLANK_STRING);
        String type = typeAndAmount[TYPE_INDEX];
        long amount = Long.parseLong(typeAndAmount[AMOUNT_INDEX])
        validateType(type);
        validateAmount(amount);
        VoucherCreationRequest voucherCreationRequest = RequestFactory.createVoucherCreationRequest(type, amount);
```

2023-06-27 11:17 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/voucher/PercentDiscountVoucher.java
> +    }
discountAmount를 꼭 getter를 써야할까요?

2023-06-27 11:17 UTC, dojinyou commented on src/main/java/com/programmers/application/service/VoucherServiceImpl.java
> +        }
바우처가 없는 경우가 왜 예외라고 생각하셨나요?

2023-06-27 11:17 UTC, dojinyou commented on src/test/java/com/programmers/application/service/VoucherServiceImplTest.java
> +        Assertions.assertThat(voucherList.size()).isEqualTo(EXPECTED_COUNT);
EXPECTED_COUNT가 테스트 코드에서 체크가 어려운 것 같아요!

2023-06-27 11:17 UTC, dojinyou commented on src/test/java/com/programmers/application/repository/MemoryVoucherRepositoryTest.java
> +        voucherRepository.save(voucher2);
반복되는 코드는 메서드로 뺴도 될 것 같아요

2023-06-28 00:07 UTC, seung-hun-h requested changes
명한님 리뷰남겼습니다. 구조를 잘 잡아주신 것 같아요.

---

> Console 클래스는 다른 스프링 빈들과 다르게 자바 라이브러리인 BufferReader나 BufferWriter를 생성자 주입을 하지않고, 직접 객체를 등록해 줬습니다. 이런식으로 사용해도 될까요? 아니면 직접 @configuration 과 @bean을 사용해서 다른 스프링 빈들처럼 객체를 자동 주입되게 해야할까요?

클래스 이름 자체가 `Console`이라서 cli 관련한 일을 하는 것 같아 괜찮을 것 같긴해요. 하지만 나중에 사용자 입력대신 테스트 파일을 만들어 놓고 검증을 하는 등 Console을 테스트하고 싶다면 어려울 수 있겠죠.

2023-06-28 00:07 UTC, seung-hun-h commented on src/main/java/com/programmers/application/repository/MemoryVoucherRepository.java
> +        return Optional.of(store.get(voucherId));
```suggestion
        return Optional.ofNullable(store.get(voucherId));
```

2023-06-28 13:25 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +    private static final String BLANK_STRING = " ";
반영했습니다!
cc1a5d383b2e7ec22330ec7075ee17f7e22fade6

2023-06-28 14:24 UTC, yumyeonghan commented on src/test/java/com/programmers/application/service/VoucherServiceImplTest.java
> +        Assertions.assertThat(voucherList.size()).isEqualTo(EXPECTED_COUNT);
EXPECTED_COUNT를 상수로 사용하지 않고, 내부에서 변수 사용으로 변경했습니다. 또한 몇가지 검증을 추가했습니다.
416fde436598d447e00291e75d5024c15932216e

2023-06-28 14:33 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +        VoucherCreationRequest voucherCreationRequest = RequestFactory.createVoucherCreationRequest(typeAndAmount[TYPE_INDEX], Long.parseLong(typeAndAmount[AMOUNT_INDEX]));
반영했습니다!

2023-06-28 14:37 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +        printOption(io);
반영했습니다!
f8752d63215116ae999f6a29a599502588e520af

2023-06-29 04:30 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/command/Command.java
Command와 Execution이 도메인과 관련된 이벤트(명령에 따른 기능)라는 도메인적인 요소를 갖고 있다고 생각이 되어서 넣어두었습니다. 하지만 이들의 역할은 사용자의 요청을 받은 Controller로부터 호출되어 적절한 Service를 호출하는 역할을 하고 있기 때문에 Controller 계층에 있어야 한다는 결론을 내려서 변경을 했습니다..!
d1fd68be4a409208dcf27f7f9bd8acd68b1a191e

2023-06-29 05:09 UTC, yumyeonghan commented on src/test/java/com/programmers/application/repository/MemoryVoucherRepositoryTest.java
> +        voucherRepository.save(voucher2);
반영했습니다!
eaa1495012bfc4c971718ce4713221d3054e61a1

2023-06-29 05:29 UTC, yumyeonghan commented on src/main/java/com/programmers/application/service/VoucherServiceImpl.java
> +        }
잘못생각했습니다.
실제 고객이 갖고 있어야 할 바우처를 조회했을 때 비어있으면 예외가 될수 있지만,
단순히 전체 바우처의 목록을 조회했을때 없는 경우는 예외가 아니라고 생각되어서 수정했습니다.!
047c7b1b7293aa85ddbb30271e66663090d8f3f9

2023-06-29 06:28 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/command/Command.java
> +            case EXIT -> System.exit(1);
전체 시스템 종료 대신 바우처 서비스만 종료하는 방향으로 코드를 작성했습니다.
따라서 바우처 서비스에서 exit 명령어가 들어오면 다시 처음부터 애플리케이션이 실행됩니다!
8cf5b17b2321e007de4a12ced5a1410e5e457811

2023-06-29 07:06 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +public class CreateVoucherExecution implements VoucherExecution{
해당 클래스를 enum 타입인 Command에서만 사용을 하고, 만약 **CreateVoucherExecution** 이것을 빈으로 등록하고 Command에서 이를 사용할 때 
1. 생성자 주입을 사용할 수 없어 대신 필드 주입을 사용해야 하는 점
2. DI를 해주는 클래스를 만들어 Enum의 필드들에 setter()을 사용해서 주입하는 점

이러한 방법으로 빈을 이용해서 구현하는 것보단 
직접 Command 안에서 new로 생성하는것이 더 낫다는 판단(?)을 해서 빈으로 등록을 안했습니다.

2023-06-29 07:29 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/voucher/PercentDiscountVoucher.java
> +    }
Voucher 재설계 했습니다.!
1. Voucher 추상 클래스에서 구현체에 따라 의미가 달라지는 discountAmount 상태 제거
2. Voucher의 실제 구현체들에 discountAmount 상태 추가
3. Voucher의 실제 구현체에서 discountAmount getter() 사용 제거

f7bb48bcb7f76be9d5aee8003f857d1faeae464d

2023-06-29 07:50 UTC, yumyeonghan commented on src/main/java/com/programmers/application/VoucherApplication.java
> +		}
ApplicationRunner 구현해서 분리했습니다.!
97d91c48366b00364ef865c37a65bb568b692d62

2023-06-29 08:03 UTC, yumyeonghan commented on src/main/java/com/programmers/application/controller/FrontController.java
> +public class FrontController implements Controller {
처음에는 단순하게 FrontController도 Controller 인터페이스의 추상 메서드를 구현하는 구현체라고 생각을 했습니다.

하지만 인터페이스의 사용 이유는 다형성인데, 
다형성을 유지하기 위한 VoucherController같은 여러 컨트롤러들과는 다르게

FrontController는 사용자의 모든 요청을 받는 고유한 역할을 수행하는 딱 하나의 객체만을 사용하기 때문에 다형성을 유지할 필요가 없다고 판단이 되어 다시 수정했습니다!
ca233d5dc33e93078517e5ace388ae396b94929f

2023-06-29 13:09 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/command/execution/CreateVoucherExecution.java
> +public class CreateVoucherExecution implements VoucherExecution{
그런 관점이라면 아래 2가지 질문은 어떻게 생각하시나요?

public 접근 제어자가 클래스에 적절한 지?
왜 enum에서 해당 클래스를 사용해야 하는 지?

2023-06-29 13:42 UTC, dojinyou reviewed
💯

2023-06-29 13:42 UTC, dojinyou commented on src/main/java/com/programmers/application/controller/command/execution/VoucherExecution.java
> +public interface VoucherExecution {
`@Functionalnterface`?

2023-06-29 13:42 UTC, dojinyou commented on src/main/java/com/programmers/application/controller/command/execution/VoucherExecution.java
> +    void run() throws IOException;
[nit]
```suggestion
    void execute() throws IOException;
```

2023-06-29 13:42 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/voucher/FixedAmountVoucher.java
> +            throw new IllegalArgumentException(MIN_DISCOUNT_AMOUNT + " ~ " + MAX_DISCOUNT_AMOUNT + " 범위의 바우처 할인양을 입력해주세요. " + "입력값: " + discountAmount);
[nit]
StringFormat 활용을 해보셔도 좋을 것 같아요!

2023-06-29 13:42 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/voucher/VoucherType.java
> +}
[nit] 
```suggestion
public enum VoucherType {
    FIXED, 
    PERCENT,
    ;
}
```
이렇게 하면 나중에 변경사항 발생했을 때 git에서 깔끔하게 보여서 좋아요 ㅎㅎ

2023-06-29 13:42 UTC, dojinyou commented on src/main/java/com/programmers/application/dto/request/VoucherCreationRequest.java
> +        if (Objects.isNull(voucherType) || voucherType.equals(EMPTY_STRING) || discountAmount == NO_DISCOUNT_AMOUNT) {
```suggestion
        if (Objects.isNull(voucherType) || voucherType.isBlank() || discountAmount == NO_DISCOUNT_AMOUNT) {
```

2023-06-29 13:42 UTC, dojinyou commented on src/test/java/com/programmers/application/domain/FixedAmountVoucherTest.java
> +        assertThat(voucher.discount(originalPrice)).isEqualTo(expectedPrice);
[nit] 
```suggestion
        VoucherCreationRequest voucherCreationRequest = RequestFactory.createVoucherCreationRequest(VOUCHER_TYPE, discountAmount);
        Voucher voucher = VoucherFactory.createVoucher(voucherCreationRequest);
        
        int discountPrice = voucher.discount(originalPrice);
        
        assertThat(discountPrice).isEqualTo(expectedPrice);
```
요게 좀 더 가독성 좋은 것 같아요!

2023-06-30 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/CLIVoucherApplicationRunner.java
> +    }
```suggestion
    private final FrontController frontController;

    public CLIVoucherApplicationRunner(FrontController frontController) {
        this.frontController = frontController;
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        while (true) {
            frontController.process();
        }
    }
```

무겁게 애플리케이션 컨텍스트를 들고있을 필요 없이, FrontController만 주입받으면 될 것 같아요.

2023-06-30 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/controller/FrontController.java
> +    }
```suggestion
    private final Map<ServiceCommand, Controller> controllerMap = new EnumMap<>(ServiceCommand.class);
    private final VoucherController voucherController;
    private final ExitController exitController;
    private final IO io;

    //추후 고객, 지갑 컨트롤러 추가
    public FrontController(VoucherController voucherController, ExitController exitController, IO io) {
        this.voucherController = voucherController;
        this.exitController = exitController;
        this.io = io;
    }

    public void process() throws IOException {
        try {
            printMenu();
            ServiceCommand serviceCommand = ServiceCommand.valueOf(io.read().toUpperCase());
            Controller controller = controllerMap.get(serviceCommand);
            controller.process();
        } catch (RuntimeException runtimeException) {
            io.write(runtimeException.getMessage());
        } catch (IOException ioException) {
            io.write(ioException.getMessage());
        }
    }

    private void printMenu() throws IOException {
        io.write("=== Program ===");
        io.write("Enter a voucher to use the voucher program");
        io.write("Enter a customer to use the customer program");
        io.write("Enter a wallet to use the wallet program");
        io.write("Enter a exit to exit the program.");

    }

    @PostConstruct
    private void initControllerMap() {
        controllerMap.put(ServiceCommand.VOUCHER, voucherController);
        controllerMap.put(ServiceCommand.EXIT, exitController);
    }
```

이렇게도 해볼 수 있겠네요

2023-06-30 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/controller/command/execution/CreateVoucherExecution.java
> +    }
```suggestion
    private static void validateType(String type) {
        if (Objects.isNull(type) || type.isBlank()) {
            throw new IllegalArgumentException("옳바른 타입을 입력해 주세요. 입력값: " + type);
        }
    }
```

<img width="606" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/60502370/6ccddfb7-fb66-4e38-9aae-e7bd6e10e3de">

isBlank는 isEmpty를 포함하고 있어요

2023-06-30 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/controller/command/execution/CreateVoucherExecution.java
> +        if (!amount.matches("[0-9]+")) {
Pattern 객체를 상수로 만들면 좋을 것 같네요.

https://velog.io/@edwin/JAVA-%EC%A0%95%EA%B7%9C%EC%8B%9D-%EC%84%B1%EB%8A%A5%EC%97%90-%EB%8C%80%ED%95%B4-Pattern.matcher-VS-String.matches

2023-06-30 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/controller/command/execution/ListVoucherExecution.java
> +            io.write(voucherInfoResponse.toString());
`toString`을 직접 호출하지 않도록 변경하는 것도 좋아 보이네요

https://hudi.blog/java-correct-purpose-of-tostring/

2023-06-30 02:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/domain/voucher/FixedAmountVoucher.java
> +        if (Objects.isNull(voucherId)) {
틀린것은 아니구요. `Objects.isNull`이 왜 생겨났는지는 알아두면 좋을 것 같네요
https://stackoverflow.com/questions/37972859/java-util-objects-isnull-vs-object-null

2023-06-30 02:28 UTC, seung-hun-h commented on src/test/java/com/programmers/application/service/VoucherServiceImplTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
`createVoucher` 테스트에서는 given-when-then을 작성해주셨는데 여기서부터는 안하신 이유가 있을까요?

2023-06-30 02:28 UTC, seung-hun-h commented on src/test/java/com/programmers/application/service/VoucherServiceImplTest.java
> +    @DisplayName("잘못된 바우처 타입 입력시 예외 발생 테스트")
```suggestion
    @DisplayName("잘못된 바우처 타입 입력시 예외가 발생한다.")
```

테스트 이름은 하나의 문장으로 작성해주면 좋습니다. `가정-행위-결과` 로요.

2023-07-03 01:12 UTC, merged