[4기 - 김예슬] SpringBoot Part1 Weekly Mission 제출합니다
prgrms-be-devcourse/springboot-basic pull request #710
Opened 2023-06-27 13:37 UTC by kys0411

## 📌 과제 설명 
바우처를 생성하고 저장하는 바우처 관리 어플리케이션입니다.

## 👩‍💻 요구 사항과 구현 내용 

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을 만들어본다.
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - 바우처 정보를 매모리에 관리한다. 
- [ ]  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

<설계도> 

<img width="1025" alt="스크린샷 2023-06-27 오후 9 59 23" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/62236238/a7c2ebfe-e75b-46d8-943e-c62fb1efc5ba">

클래스 설명
VoucherController : 뷰와 서비스를 연결하는 컨트롤러 클래스입니다.

VoucherService : 바우처에 대한 서비스 로직을 구현한 클래스입니다.

VoucherRepository : 바우처의 저장소 기능을 가진 인터페이스
MemoryVoucherRepository : VoucherRepository의 구현체로, 저장 기능과 getAll 기능을 구현합니다.

Input : 입력을 담당하는 클래스입니다.
Output : 출력을 담당하는 클래스입니다.
VoucherConsole : input과 output을 가지며 voucher에 대한 입출력을 담당하는 클래스입니다.

Voucher : 바우처의 할인 기능을 가진 인터페이스
FixedAmountVoucher : voucher를 구현한 고정 할인 기능을 가진 클래스입니다.
PercentDiscountVoucher : voucher를 구현한 퍼센트 할인 기능을 가진 클래스입니다.

## ✅ PR 포인트 & 궁금한 점 
VoucherController 클래스에서 유효하지 않은 커맨드가 입력될 경우 if 문을 사용해서 체크를 했는데, 
그 이후에 switch 문에서도 따로 default문으로 예외처리를 해줘야 하는지 궁금합니다..! 리뷰 미리 감사합니다!😄😄

2023-06-27 20:15 UTC, Jo-GyuHyeon requested changes
안녕하세요 예슬님 😄 
첫번째 PR 작성하시느라 고생하어요. 🙇 
간단하게 리뷰를 남겨 보았는데요. 기능 추가 하기전에 피드백 반영을 먼저 제안 드리고 싶어요.
피드백 반영 후, 저의 코멘트에 Commit id 와 함께 답글을 달아주시면 좋을것 같아요.
고생하셨어요. 😄

2023-06-27 20:15 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +            switch (command.get()) {
Optional 을 장점을 살려 더 잘 활용하는 방향으로 고민 해보시면 좋을것 같아요.

2023-06-27 20:15 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        while(true) {
무한 루프에서 return 을 사용하기보다 종료 조건을 이용하는 것은 어떨까요?

2023-06-27 20:15 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +    private final VoucherConsole voucherConsole;
VoucherConsole 을 생성하지 (인스턴스화) 않고 빈주입으로 받게 됨으로써 이점은 어떤것이 있을까요?

2023-06-27 20:15 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/exception/ErrorMessage.java
> +    private final String errorMessage;
네이밍을 간단하게 message 는 어떠한가요?
```suggestion
    private final String message;
```

2023-06-27 20:15 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +                saveVoucher(new PercentDiscountVoucher(UUID.randomUUID(), discount));
함수 호출과 전달은 한가지만 하는 것이 좋습니다.
인자에 인자 깊이가 (함수 호출 및) 깊어 질 수록 가독성이 떨어지는 것 같아요.

2023-06-27 20:15 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/VoucherApplication.java
> +		applicationContext.getBean(VoucherController.class).run();
VoucherApplication 를 직접 인스턴스화 하지 않고 applicationContext 에서 빈을 이용하는 이유는 무엇 일까요?

2023-06-27 20:15 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/config/AppConfig.java
> +}
VoucherConsole 에서 @Component 어노테이션을 사용하지 않고 @Configuration 로 빈 등록 하는 이유는 무엇인가요?
VoucherConsole 는 Bean 으로 등록하면 어떠한 이점이 있을까요?

2023-06-28 00:54 UTC, HyoungUkJJang reviewed
예슬님 코드 잘 봤습니다. 과제 진행하느라 고생하셨어요 ~

멘토님이 코멘트를 먼저 잘 남겨주셔서 저도 간단히 몇개 남겨봤습니다. 예슬님도 편하게 의견을 남겨주시면 좋을 것 같아요 !

2023-06-28 00:54 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/exception/ErrorMessage.java
> +public enum ErrorMessage {
에러 메시지 좋은 것 같아요 👍

2023-06-30 03:50 UTC, kys0411 commented on src/main/java/programmers/org/voucher/exception/ErrorMessage.java
> +    private final String errorMessage;
1ac1e90 커밋 피드백 반영
저도 message가 더 간결하고 좋은 것 같습니다! 수정하였습니다😉

2023-06-30 03:54 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        while(true) {
c2705d4 커밋 피드백 반영
- 무한 루프 대신 종료 조건을 추가했습니다!

2023-06-30 04:29 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +                saveVoucher(new PercentDiscountVoucher(UUID.randomUUID(), discount));
3cbf0e1 커밋 피드백 반영
- 함수 호출과 전달을 분리하도록 수정했습니다 감사합니다!

2023-06-30 04:30 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/VoucherType.java
> +    FIXED("fixed"), PERCENT("percent");
0c52d3e 커밋 피드백 반영
- 컨벤션 통일하도록 수정했습니다! 감사합니다

2023-06-30 04:32 UTC, kys0411 commented on src/main/java/programmers/org/voucher/domain/FixedAmountVoucher.java
> +    }
e4609d5 커밋 피드백 반영
- discount의 값을 검증하는 validate() 메서드를 추가했습니다.!

2023-06-30 04:34 UTC, kys0411 commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +                "Type list to list all vouchers.");
자바 15부터 사용할 수 있는 것 같습니다,,ㅜㅜ 곧 17로 바꿔보겠습니다🥲

2023-06-30 05:20 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/MemoryVoucherRepository.java
> +        return new ArrayList<>(voucherStorage.values());
1eab9f1 커밋 피드백 반영
- 반환하는 곳에서 List를 변경할 수 없도록 List.copyOf 메서드를 사용해 리턴하도록 수정했습니다..!

2023-06-30 05:21 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/MemoryVoucherRepository.java
> +import java.util.*;
c985e6a 커밋 피드백 반영
- 수정하였습니다! 감사합니다:)

2023-06-30 05:33 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/Command.java
> +    }
5e47606 커밋 피드백 반영
- findAny()와 findFirst()는 스트림을 직렬로 처리할 때는 결과의 차이점이 없다고 생각했고, findFirst()를 사용해 항상 첫 번째 요소를 반환할 필요는 없다고 느꼈습니다🥲
- orElseThrow()를 사용하는 것이 알아보기도 쉽고 간편한 것 같습니다! 수정하였습니다

2023-06-30 05:35 UTC, kys0411 commented on src/main/java/programmers/org/voucher/exception/ErrorMessage.java
> +public enum ErrorMessage {
감사합니다ㅎㅎ😉

2023-06-30 05:40 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/Command.java
> +    private final String commandString;
b233bc0 커밋 피드백 반영
- 'type'이라는 네이밍으로 수정했습니다!

2023-06-30 06:17 UTC, kys0411 commented on src/main/java/programmers/org/voucher/config/AppConfig.java
> +}
- 현재는 AppConfig 파일이 필요하지 않다고 생각해 삭제하였습니다!
- @Configuration으로 빈 등록을 한 이유는 스프링 빈으로 등록한 객체를 싱글톤으로 반환해주기 때문입니다,, @Component를 붙이면 매번 인스턴스로 생성된다고 알고있습니다
- VoucherConsole을 빈으로 등록했을 때의 이점은 필요한 곳에 직접 주입해주지 않아도 되서 간편하다고 생각했습니다.
- 그런데 VoucherConsole은 뷰와 관련된 클래스라서 스프링에서 관리하는게 맞지 않다고 생각해 삭제하게 되었습니다..!

2023-06-30 07:34 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +    private final VoucherConsole voucherConsole;
a0a6c88 
- VoucherConsole을 직접 주입해주지 않아도 되어서 편리하다는 생각으로만 빈 주입을 받았습니다ㅜ
- 현재는 VoucherConsole을 생성자에서 인스턴스화 하도록 변경했습니다. 뷰와 관련된 클래스라 스프링 컨테이너에서 빈으로 관리하는게 맞지 않다고 생각했습니다..
- 그치만 이 방법도 결합도가 너무 높아져서 좋은 방식이 아닌것 같아 고민이 됩니다,,

2023-06-30 07:50 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        if (findVoucherType.isEmpty()) {
ff9dda8 
- Optional을 사용했을 때 좀더 나은 방법을 계속 고민하다가 명확한 답을 찾지 못했습니다ㅜ
- 현재는 find 메서드에서 orElseThrow()를 사용해 요소가 없을 경우 예외를 던지는 식으로 수정했습니다.

2023-06-30 10:35 UTC, kys0411 commented on src/main/java/programmers/org/voucher/VoucherApplication.java
> +		applicationContext.getBean(VoucherController.class).run();
018c1d2
- 직접 인스턴스화 하는 것보다 applicationContext에서 빈으로 관리되는 것이 IoC를 적용할 수 있다는 부분에서 더 좋다고 생각했습니다.
- applicationContext에서 빈으로 가져오지 않고 바로 VoucherController의 run() 메서드를 실행하는 방식으로 수정하였습니다.!

2023-06-30 13:51 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        if (findVoucherType.isEmpty()) {
@kys0411 형욱님이 주신 https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/ 링크를 꼼꼼히 보시면 힌트가 될수 있을것 같아요.

현제 피드백 반영한 커밋을 보았을땐 Optional 을 사용하지 않는다면 null 혹은 비슷한 개념을 활용 하는것도 방법이 될수도 있을것 같아요.

2023-06-30 14:05 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +    private final VoucherConsole voucherConsole;
@kys0411 결합도가 높은것은 무조건 안좋은 것일까요??

2023-06-30 14:09 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +                saveVoucher(new PercentDiscountVoucher(UUID.randomUUID(), discount));
@kys0411 변수 네이밍을 구체적으로 작성하시면 좋을것 같아요.

2023-06-30 14:10 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/VoucherApplication.java
> +		applicationContext.getBean(VoucherController.class).run();
@kys0411 다른 기능이 확장되더라도 Application 클래스에 변경이 생기지 않겠군요? 피드백 잘 반영 해주신것 같아요. 👍

2023-06-30 15:47 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        if (findVoucherType.isEmpty()) {
넵 한번더 꼼꼼히 읽어보겠습니다! 감사합니다

2023-07-02 15:36 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        if (findVoucherType.isEmpty()) {
2dadc22 커밋 피드백 반영
- find 메서드의 반환 값을 Optional로 하고, 호출하는 쪽에서 isEmpty() - get() 이 아닌 orElseThrow()를 사용했습니다.
- 이 방법이 Optional을 잘 활용한 것인지는 의문이 남는데, 멘토님은 어떻게 생각하실까요..?.?

2023-07-02 17:57 UTC, Jo-GyuHyeon requested changes
간단하게 코멘트를 남겼어요.
관련 코멘트는 빠르게 처리될것이라 기대를 하고 있어요.
해당 리뷰를 반영한 후에 다음 피처에 대해 얘기 해보면 좋을것 같아요.

2023-07-02 17:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/constant/Command.java
> +    private final String type;
소문자로 type 을 명시 하지 않고, enum 의 name 을 사용 할 수 있을것 같아요.
혹시 별도의 type 을 사용하시는 이유가 있었을까요?

2023-07-02 17:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        run();
메서드 추출 해야 했을까요?

2023-07-02 17:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        while (!isExit) {
부정 네이밍 보다 긍정 네이밍을 활용하면 이해하기 쉬울것 같아요.

2023-07-02 17:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +                    .orElseThrow(() -> new NoSuchElementException(COMMAND_ERROR_MESSAGE.getMessage()));
예외 발생을 Controller에서 처리 하는 것보다 Command 에서 처리 하면 어떠한 이점이 있다고 생각 하시나요?

2023-07-02 17:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +                .orElseThrow(() -> new NoSuchElementException(VOUCHER_ERROR_MESSAGE.getMessage()));
위의 코멘트와 동일 해요.

2023-07-02 17:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +    }
해당 클래스는 input, output 을 묶어주는 역할만 있다고 생각해요. 혹시 다른 역할도 있을까요?

2023-07-02 17:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/io/Output.java
> +    }
단순히 sout (System.out.println) 을 감싸기만 하는 것 같아요. 그렇다면 굳이 감쌀필요가 있을까요?

2023-07-03 10:11 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/Command.java
> +    private final String type;
60a0ea3 커밋 피드백 반영
- type이라는 필드는 불필요했던 것 같고, enum의 name을 사용하는게 훨씬 깔끔한 것 같습니다. name()이라는 메서드를 잘 사용안하다보니 잊고 있었습니다ㅜ

2023-07-03 10:13 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        run();
f5f0bf4 커밋 피드백 반영
- 가독성도 좋지 않고 메서드 추출할 필요가 전혀 없는 것 같습니다. 수정하였습니다

2023-07-03 10:15 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        while (!isExit) {
a0d49a5 커밋 피드백 반영
- 앞으로 네이밍에 더 신경쓰겠습니다😉 수정하였습니다

2023-07-03 10:16 UTC, kys0411 commented on src/main/java/programmers/org/voucher/io/Output.java
> +    }
dbb4e00 커밋 피드백 반영
- 생각해보니 감쌀 필요가 없는 것 같습니다 ㅜ println() 메서드로 대체하였습니다

2023-07-03 13:53 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +                    .orElseThrow(() -> new NoSuchElementException(COMMAND_ERROR_MESSAGE.getMessage()));
3fb3f45 리뷰 피드백 반영
- Command에서 예외를 발생시키면 메서드를 호출하는 컨트롤러 쪽에서 알맞은 처리를 할 수 있을 것 같습니다.. 
- 현재는 Command와 VoucherType에서 예외를 던지도록 수정했습니다.

2023-07-03 14:24 UTC, kys0411 commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +    }
22396a5
- Input과 Output을 가지고 있어 바우처에 대한 콘솔 입출력의 역할을 한다고 생각했습니다.
- 그렇지만 입출력에 대한 한 줄 짜리 메서드 분리를 한 것이 전부이고, 현재는 콘솔을 제외한 다른 방법의 입출력을 사용하지 않기 때문에 굳이 없어도 되겠다고 판단해서 input과 output 클래스를 삭제했습니다.

2023-07-04 17:10 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        if (findVoucherType.isEmpty()) {
isEmpty() - get() 를 지양하는 의도이긴 하였지만, orElseThrow() 을 꼭 외부, 즉 VoucherType. find() 를 Optional 타입으로 리턴 받을 필요는 없다고도 생각해요.
단순히 isEmpty() - get() 를 지양이 목적이긴 하였어요.
해당 피드백을 반영하셨기에 resolver처리 하도록 할게요.

2023-07-05 01:58 UTC, Jo-GyuHyeon approved these changes
1주차 위클리미션 하시느라 고생하셨어요. 해당 PR 은 어푸 (Approve) 처리 할게요.
2주차로 새로운 PR 로 진행 해주시면 좋을것 같아요.
1주차 관련해서는 온라인으로 소통 하면 좋을것 같아요. 
고생 많으셨어요. 🙇

2023-07-05 01:58 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +                Voucher voucher = new PercentDiscountVoucher(UUID.randomUUID(), discount);
ID 전략은 외부로 주입받지 않아도 될것 같은데 어떻게 생각 하시나요?

2023-07-05 01:58 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/VoucherRepository.java
> +public interface VoucherRepository {
빈 의존, 주입이 가능한 것으로 명시적으로 @Repository 어노테이션 붙여 볼까요?

2023-07-06 05:54 UTC, merged