[4기 - 장수연] SpringBoot Part1 Weekly Mission 첫번째 PR 제출합니다
prgrms-be-devcourse/springboot-basic pull request #711
Opened 2023-06-27 18:45 UTC by sujjangOvO

## 📌 과제 설명 
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/89267864/fbd6fd01-842f-4828-aae4-1640aadaaca7)

[구현]
- VoucherType : 바우처 종류인 고정할인 / 퍼센트할인 으로 나누기 위해 enum 클래스 사용
- Console : Input, Oupt OOP적으로 구상하여 구현
- VoucherApp : 전체적으로 애플리케이션이 실행되는 시작 부분

[에러]
- voucherType 이 1,2 가 아니라면 exception 처리 필요
- PercentDiscountVoucher가 Repository에 저장되지 않는 issue존재.. 그러나 뭐가 문젠지 도저히 모르겠음

## 👩‍💻 요구 사항과 구현 내용 
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을  만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
    
- [ ]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
- [ ]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## ✅ PR 포인트 & 궁금한 점 
- 서버 구동하지 않고 애플리케이션에서 실행하는 것이 요구사항이었는데 이것이 Spring boot Application을 run하는 의미인지 아니면 제가 한 것처럼 다른 클래스 main으로 실행하는 것인지 궁금합니다. 

- voucher service, repository, app 지역 변수 private final로 둘 때 기준이 뭔지 궁금합니다. 항상 이 문제때문에 인텔리제이 alt + enter 기능을 사용해왔는데 어떤 때 사용해야 하는지 잘 모르곘습니다.

2023-06-27 20:59 UTC, Jo-GyuHyeon requested changes
안녕하세요 수연님 😄 
첫번째 PR 작성하시느라 고생 많으셨어요. 🙇 

이번 리뷰 코멘트가 많은것은 코드 정렬 때문이에요. 코드 정렬은 가독성과 연결이 될 수도 있는데요.
흔히 아버지가 방에 들어 가신다. -> 아버지 가방에 들어 가신다. 라는 것을 들어 보셨을까요?
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/20269425/268a2c5b-7876-4a8a-9c84-3248d827dbbd)

리뷰 내용이 많은것 만큼 기능 추가 하기전에 피드백 반영을 먼저 제안 드리고 싶어요.
피드백 반영 후, 저의 코멘트에 Commit id 와 함께 답글을 달아주시면 좋을것 같아요.
고생하셨어요. 😄

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
PR 설명에서 보여주셨던 설계와 다른 것 같아요.
APP  은 Service 만 의존하도록 설계 하셨지만, 실제로는 Repository 도 함께 의존 하고 있기에 다시 확인 해주시면 좋을것 같아요.
<img width="928" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/20269425/c901a2bc-eaae-4998-b1e4-a8af55eb3b39">

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
무한 루프에서 return 을 사용하기보다 종료 조건을 이용하는 것은 어떨까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherProjectApplication.java
> +    private final Console console = new Console();
Console 객체는 사용하지 않는 것 같아요. 
혹시 실수로 지우지 못하셨을까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    }
입력 관련 예외 처리는 입력 로직만 try catch 구문을 감싸면 된다고 생각해요. 
올바른 입력을 이용하여 바우처를 생성 하는 로직으로 변경 해보시면 좋을것 같아요.

--- 
추가 적으로 create 내의 로직은 priavte 메서드로 별도 분리 하면 어떨것 같나요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    break;
JDK 17 을 사용하신다면 switch 문을 아래 처럼 패턴 매칭 (Pattern Matching) 으로 사용 할 수 있어요.
[docs.oracle.com/en/java/javase/17/language/pattern-matching-switch-expressions-and-statements.html#GUID-E69EEA63-E204-41B4-AA7F-D58B26A3B232](https://docs.oracle.com/en/java/javase/17/language/pattern-matching-switch-expressions-and-statements.html#GUID-E69EEA63-E204-41B4-AA7F-D58B26A3B232)

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                case "exit":
메뉴를 String 으로 된 하드코딩 방식이 아닌 열거 타입을 사용해보는것은 어떨까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    if(voucherType != null){
if 문 전후로는 개행을 추가하는 것이 가독성이 증가 된다고 생각해요.

---

띄어쓰기가 빠져있어서 코드 제안 드렸어요.
```suggestion
                    if (voucherType != null) {
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
VoucherApp 애서 main() 메서드가 존재 하는 이유는 무엇일까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/config/AppConfiguration.java
> +}
사용하지 않는 파일은 제거 하는 것이 좋을것 같아요. 🤔

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +
개행은 규칙적으로 1줄이면 좋을것 같아요.

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/PercentDiscountVoucher.java
> +        return beforeDiscount * (percent/100);
산술 연산자 전후로 띄어쓰기가 안되어 있어요. 확인 부탁 드릴게요.

```suggestion
        return beforeDiscount * (percent / 100);
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +        return "| UUID:" + getVoucherId() + " | VoucherType: FixedVoucher | amount:" + amount +" |";
띄어쓰기가 빠져있어서 코드 제안 드려보았어요.
```suggestion
        return "| UUID:" + getVoucherId() + "  | VoucherType: PercentVoucher | percent:" + percent + " |";
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +        while(true){
띄어쓰기가 빠져있어서 코드 제안 드렸어요.
```suggestion
        while (true) {
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +            switch (console.inputCommand().toLowerCase()){
띄어쓰기가 빠져있어서 코드 제안 드렸어요.
```suggestion
            switch (console.inputCommand().toLowerCase()) {
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                        catch (Exception e){ //TODO: 잘못된 VoucherType 입력 시 예외처리 안됨
띄어쓰기가 빠져있어서 코드 제안 드렸어요.
불필요한 주석은 제거 하는 것이 좋을것 같아요.

```suggestion
                        try {
                            voucherService.create(voucherType);
                        } catch (Exception e) {
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher{
띄어쓰기가 빠져있어서 코드 제안 드렸어요.
```suggestion
public class FixedAmountVoucher implements Voucher {
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/PercentDiscountVoucher.java
> +        return "| UUID:" + getVoucherId() + "  | VoucherType: PercentVoucher | percent:" + percent +" |";
띄어쓰기가 빠져있어서 코드 제안 드렸어요.
```suggestion
        return "| UUID:" + getVoucherId() + "  | VoucherType: PercentVoucher | percent:" + percent + " |";
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/VoucherType.java
> +        this.voucherType = i;
파라미터 네이밍을 의미있게 하셨으면 좋을것 같아요.
고민이 되신다면 간단하게 필드 명과 동일 하게 가도 좋을것 같아요.

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/VoucherType.java
> +                return null; //TODO: null없애고 싶은데 default를 없애면 return 오류가 남
1 값이 FIXED 를 보장 할 수는 없는것 같아요. 2 도 마찬가지로 PERCENT 를 보장 할 수 없는것 같아요.
사람이 보기에 현재 기준으로 위의 코드를보고 판단한다고 생각해요. enum을 더 잘 활용하는 방법을 고민 해보면 좋을것 같아요.

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +public class Console implements Input, Output{
@HyoungUkJJang  형욱님과 함께 팀 전체 대상으로 전달 한 내용이 있어요.
해당 내용은 롬복을 지양해보자 인데요. 
이번 기회에 간단한 코드 정도는 직접 만들어 보시는걸 추천드려요


---

Input, Output 을 인터페이스로 분리 하면 어떠한 이점이 있을까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/MemoryVoucherRepository.java
> +        storage.put(voucher.getVoucherId(), voucher);
id 에 대한 Getter 는 메서드명을 간결하게 유지해도 의미가 있다고 생각해요.
```suggestion
        storage.put(voucher.getId(), voucher);
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/MemoryVoucherRepository.java
> +    public ArrayList<Voucher> findAll() {
return 타입이 ArrayList 타입으로 하신 이유가 궁금해요.
말씀해주실 수 있을까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/MemoryVoucherRepository.java
> +        return new ArrayList<Voucher>(storage.values());
제네릭 타입은 생략 해도 괜찮을것 같아요.
```suggestion
        return new ArrayList<>(storage.values());
```

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/VoucherRepository.java
> +
규칙적으로 개행을 1줄만 사용하여 통일 감을 주면 좋을 것 같아요.

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/VoucherRepository.java
> +
불필요한 주석은 제거 한는 것이 좋을것 같아요.
아래의 규칙에 맞춰 메서드 선언 후 개행을 추가 하는 것이 가독성이 좋다고 생각해요.

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                Voucher fixedAmountVoucher = new FixedAmountVoucher(UUID.randomUUID(), discount);
if 문 전후로는 개행을 추가 하는 것이 가독성이 더 좋다고 생각해요.

---

discount 할인 값에 대한 검증 책임은 Service 가 가지고 있어야 될까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        if(voucherArrayList.size() == 0) {
`size() == 0` 을 사용 하기보다 isEmpty() 메서드를 사용 하면 어떨까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        ArrayList<Voucher> voucherArrayList = voucherRepository.findAll();
리턴타입을 상위 타입으로 받는다면 조금더 유연하게 사용 할 수 있을것이라 생각해요.
Spring 이 interface 타입에 의존하는 것과 함께 생각해보시면 좋을것 같아요.

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                console.printMsg("고정 할인 금액을 입력하세요. (1이상)");
메시지 내용을 따로 상수로 정의 해보면 어떨까요?

2023-06-27 20:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                voucherRepository.save(percentDiscountVoucher); //TODO : percentVoucher는 save 안 되는 문제 (UUID도 null로 들어감)
위의 FIXED 와 유사한 리뷰이기에 생략할게요. 
불필요한 주석은 제거하는 것이 좋을것 같아요.

2023-06-27 21:00 UTC, Jo-GyuHyeon requested changes
안녕하세요 수연님 😄 
첫번째 PR 작성하시느라 고생 많으셨어요. 🙇 

이번 리뷰 코멘트가 많은것은 코드 정렬 때문이에요. 코드 정렬은 가독성과 연결이 될 수도 있는데요.
흔히 아버지가 방에 들어 가신다. -> 아버지 가방에 들어 가신다. 라는 것을 들어 보셨을까요?
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/20269425/268a2c5b-7876-4a8a-9c84-3248d827dbbd)
그만큼 별개 아닐수 있지만 실은 중요한 포인트로 생각을 하고 있어요.

만약 정렬에 대한 도움을 받고 싶으시다면 해당 IDE 에서 자동정렬 기능을 이용하는 것도 좋아요.
(Intellij 기준 MacOS -> Cmd + option + L , Windows -> ctr + alt + L)
[jetbrains.com/help/idea/reformat-and-rearrange-code.html](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)


리뷰 내용이 많은것 만큼 기능 추가 하기전에 피드백 반영을 먼저 제안 드리고 싶어요.
피드백 반영 후, 저의 코멘트에 Commit id 와 함께 답글을 달아주시면 좋을것 같아요.
고생하셨어요. 😄

2023-06-30 05:49 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
[ce710af](https://github.com/prgrms-be-devcourse/springboot-basic/pull/711/commits/ce710af8810b4826eddbe0c75fe75ceb9f98da1c) 커밋 피드백 반영
- VoucherApp에서 VoucherRepository에 대한 의존성을 제거하였습니다
- VoucherRepository를 구현한 MemoryVoucherRepository에 @Repository를 적용하였습니다

2023-06-30 07:44 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherProjectApplication.java
> +    private final Console console = new Console();
확인하고 지웠습니다!

2023-06-30 07:47 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야 한다는 조건이 있어 VoucherProjectApplication이 아닌 VoucherApp에서 작동하기 위해 main 함수를 사용하여 프로젝트를 시작하였습니다.

2023-06-30 07:48 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    if(voucherType != null){
주기적인 코드 리포맷팅으로 해당 오류사항 줄이도록 하겠습니다.

2023-06-30 08:35 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +public class Console implements Input, Output{
- @NoArgsConstructor는 기본 생성자를 만들어주는 역할을 합니다. 따라서 롬복을 지우고 기본 생성자를 직접 생성하도록 하겠습니다!
- 초반 강의에 Input, Output을 인터페이스로 만든 후 Console에 구현하는 방식으로 진행하길래 객체지향적 방법이라고 생각해서 그렇게 하고 있습니다! 이점은 입력을 받는 부분과 출력을 하는 부분을 정확하게 구분할 수 있고 또한, 출력 메시지를 수정하고자 할 때 각 클래스의 콘솔 출력부분을 직접 다 고칠 필요 없이 Console Class에서 고치면 다 적용되는 점이라고 생각힙낟.

2023-06-30 08:42 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/MemoryVoucherRepository.java
> +    public ArrayList<Voucher> findAll() {
- Mpa으로 전달 할 필요 없이 Voucher에 대한 정보만 담으면 UUID와 Type, 할인 적용 값을 알 수 있다고 생각했고 그에 대해 생각난 타입이 ArrayList였습니다. ArrayList에 데이터를 쭉 나열하고 출력하는 방식을 생각했습니다

2023-06-30 14:08 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                case "exit":
[51a85cd](https://github.com/prgrms-be-devcourse/springboot-basic/pull/711/commits/51a85cddb4fcfc0b706dd9528ab3358e377b5115) 커밋 피드백 반영
- String으로 비교하지 않고 MenuType을 사용하여 커맨드를 구분하였습니다
- 종료 조건 EXIT_NUM을 주어 exit을 입력할시 해당 변수의 값이 종료조건이 되도록 설정하였습니다
-  잘못된 명령어를 입력할 시 MenuType에서검증하도록 하였씁니다

2023-06-30 14:10 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/VoucherType.java
> +                return null; //TODO: null없애고 싶은데 default를 없애면 return 오류가 남
07dd2de48b5f19d80e98b7877a1416ea7f7ca7ae 커밋 피드백 반영
- getSelectedVoucherType 메소드에서 1, 2로 VoucherType을 구분하지 않고 stream을 통해 구별하도록 하였습니다.
- 사람이 보기에 라는 말씀의 의미가 해당 코드를 보는 개발자인가요??

2023-06-30 14:11 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        ArrayList<Voucher> voucherArrayList = voucherRepository.findAll();
list 인터페이스의 확장성을 고려하여 voucherArrayList 타입을 List로 변경하였스빈다!!

2023-06-30 14:23 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                Voucher fixedAmountVoucher = new FixedAmountVoucher(UUID.randomUUID(), discount);
184d740047635d10edf4eff7e8b72fc6657d588e 커밋 피드백 반영
- discount 할인 값에 대한 검증 책임은 Voucher 객체의 생성자 부분에 넣어주었고 Service부분에선 삭제하였습니다. 이렇게 하는게 맞을까요??

2023-06-30 14:58 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
51a85cddb4fcfc0b706dd9528ab3358e377b5115 커밋 피드백 반영
- EXIT_NUM 변수를 통해 종료 조건을 주었습니다.
- 생각나는 방법이 변수의 값을 통해 종료조건을 주는 것이었는데 더 효율적인 방안이 있나요??

2023-06-30 14:59 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    break;
해당 부분은 아직 적용 방법을 좀 더 고민해보고 있습니다 ㅠ

2023-06-30 15:00 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/VoucherType.java
> +        this.voucherType = i;
07dd2de48b5f19d80e98b7877a1416ea7f7ca7ae 커밋 피드백 반영
- i에서 voucherNum으로 변경하였습니다. 앞으로 파라미터 네이밍은 의미가 있게 작성하도록 하겠습니다!

2023-06-30 15:02 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                console.printMsg("고정 할인 금액을 입력하세요. (1이상)");
389517c47785b350eafca4cbcc8f320418a6e091 커밋 피드백 반영
- 메시지 내용을 String 타입의 상수로 변환하였습니다.
- if문 사이 개행을 넣었습니다.
- 불필요한 주석을 삭제하였습니다.

2023-06-30 16:48 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    break;
e38e5be7385227d6e4960d43122f475dfb49fe9c 커밋 피드백 반영
- 패턴 매칭 방식으로 swtich문을 개선해 보았습니다!
- 해당 방식을 처음 알게되어 감회가 새롭습니다!!

2023-06-30 17:48 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
@sujjangOvO EXIT_NUM 를 0, -1 을 두 수를 사용하시고 계신데, 2가지 상태를 나타낼수 있는 자료형이 있을것 같아요.

2023-07-01 13:11 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
b466fc4ca669c8fb8ed199056b3324da97a69006 커밋 피드백 반영
- boolean 타입을 생각하지 못했던거 같습니다 !! boolean 타입의 변수로 종료 조건을 나타내도록 변경했습니다!

2023-07-01 13:13 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
혹시 이 부분에 대해 고민이 해결되지 않아서 여쭙고 싶은 부분이 있는데
- VoucherApp에서 구현할 것이 아니라 VoucherProjectApplication에서 spring boot로 시작했어야 하는건지 의문이 듭니다..

2023-07-01 13:16 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +public class Console implements Input, Output{
1c9e0ac639db49634c7e9012f950100e66241cd0 커밋 피드백 반영 
- 롬복을 삭제하고 기본 생성자를 직접 구현하였습니다

2023-07-01 13:18 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        if(voucherArrayList.size() == 0) {
389517c47785b350eafca4cbcc8f320418a6e091 커밋 피드백 반영
- size() == 0에서 isEmpty 메서드로 변경하였습니다! 앞으로는 size값이 0인 경우를 조건으로 걸어야 할때는 isEmpty 메서드로 사용하겠습니다!!

2023-07-01 16:10 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/MemoryVoucherRepository.java
> +    public ArrayList<Voucher> findAll() {
4466956c0df1e9dfbbb4ae548282f9b1548cb139 커밋 피드백 반영

말씀해주신 해당 내용을 고민해보았습니다!
- List 타입으로 주었을 때는 ArrayList가 아닌 다른 List타입으로 변경하는 경우 변경에 유연해집니다.
- 단, 제가 한 방법처럼 ArrayList로 선언한다면 나중에 데이터의 용도가 바뀌어 LinkedList으로 바꾸어야 할때 모든 부분을 바꾸어야 한다는 불편한 점이 생기게 됩니다.
- 즉 변경에 용이해집니다.
- List로 선언하면 List에서 제공하는 메소드까지 사용 가능합니다.
- 앞으로는 상위 타입의 인터페이스를 선언하도록 하겠습니다!

2023-07-02 03:06 UTC, HyoungUkJJang reviewed
안녕하세요 수연님 PR 올리구 리뷰 반영까지 열심히 하시는 모습 보기 좋습니다 !
먼저 멘토님이 리뷰를 너무 잘 해주셨네요 !

저도 추가적인 코멘트를 몇개 남겨놨어요 ~! 수연님도 의견을 편하게 말씀해주시면 좋을 것 같습니다 ! (참고로 비슷한 리뷰는 생략했어요!)
+ 개인적으로 가장 먼저 눈에 띄는 부분은 코드에 컨벤션이 여기저기 조금 달라보였어요 ! 이 부분을 먼저 고쳐보시면 좋을 것 같습니다 ☺️

고생하셨어요 👍🏻☺️

2023-07-02 13:34 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
해당 부분은 구두로 진행 하였기에 Resolve 처리 하도록 할게요.

2023-07-02 13:36 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
부정 단어 보다는 긍정 단어가 한번에 이해 하기 쉬운것 같아요 (가독성) 
피드백 반영 하였기에 resolve 처리 할게요.

2023-07-02 13:37 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
SpringApplication 에서 main() 메서드가 이미 존재하였기에 해당 main() 메서드로 VaoucherApp 을 실행 할 수 있도록 반영 해보시면 좋을것 같아요.

2023-07-02 17:19 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
19ce07a156967652ae857e501f253d21345d45ca 커밋 피드백 반영
- 앞으로 조건에 대한 변수 이름은 긍정단어로 사용하겠습니다!!

2023-07-02 17:25 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
이게 코드라인이 인텔리제이에서 깃허브 표시같은 것들 때문에 밀려서 자꾸 확인을 못하게 되는 것 같습니다 ㅠㅠ 유의하겠습니다

2023-07-02 17:28 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    String menuName;
헉 간과한것 같습니다. 메서드 지역변수로 변경했습니다. 여기에서 궁금한점이 있는데요! 혹시 메서드 내부의 지역변수로 만들어줄때 초기값을 어떻게 주는 것이 가장 좋은 방법인지 궁금합니다!

2023-07-02 17:30 UTC, sujjangOvO commented on src/test/java/com/prgms/voucher/voucherproject/VoucherProjectApplicationTests.java
> +}
앗 ㅠㅠ 자동으로 생성된 파일인것 같은데 이런 경우에도 커밋올리기 전 삭제하는게 좋을까요?

2023-07-02 17:41 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/MemoryVoucherRepository.java
> +import java.util.*;
헉 왜 이러는지 이유가 궁금했는데 이런 이유때문이었군요 ㅠㅠ
그런데 저는 어떤 이유에선지 적용이 안되어서 .. 추후에 더 찾아보고 다시 적용해보겠습니다 왜이럴까욥 ㅠㅠㅠ
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/89267864/966a7a78-b490-4dc5-8456-a7d84fb06d11)

2023-07-02 17:56 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
2a61ba5c8516f5effd04fe44a193317cc1d4eb0b 커밋 피드백 반영
- 상수와 필드를 주석을 통해 구분해 주었습니다.
- 주석을 통해 구분하는 방법말고 좀 더 효율적인 방법이 있을까요?

2023-07-02 17:57 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    String menuName;
2a61ba5c8516f5effd04fe44a193317cc1d4eb0b 커밋 피드백 반영
- 헉 간과한것 같습니다. 메서드 지역변수로 변경했습니다. 
- 여기에서 궁금한점이 있는데요! 혹시 메서드 내부의 지역변수로 만들어줄때 초기값을 어떻게 주는 것이 가장 좋은 방법인지 궁금합니다!

2023-07-02 18:00 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherProjectApplication.java
> +
fc86dfef9985eb8bb15f8246130df35880c294ea 커밋 피드백 반영
- 이게 코드라인이 인텔리제이에서 깃허브 표시같은 것들 때문에 밀려서 자꾸 확인을 못하게 되는 것 같습니다 ㅠㅠ 유의하겠습니다

2023-07-02 18:01 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    EXIT(1, "exit"), CREATE(2, "create"), LIST(3, "list");
b8be86c602349739d33eb921c2857e39f836ff2c 커밋 피드백 반영
- 가로로 나열하는 것 보다 세로로 나열하는 것이 가독성이 더 좋은 것 같습니다!!

2023-07-02 18:02 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    }
b8be86c602349739d33eb921c2857e39f836ff2c 커밋 피드백 반영
- 의미있는 파라미터 네이밍을 짓도록 하겠습니다!

2023-07-02 18:03 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +        System.out.println("Type **list** to list all vouchers.");
891f3ebeaba78f898d94e0b5d86a7511360827b4 커밋 피드백 반영
- 훨씬 가독성이 좋아지고 긴 문자열을 나타내는데 좋은 것 같습니다 감사합니다!!!!

2023-07-02 19:06 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +        if(amount <= 0){
6fdaf74d6ad6931e06a453c9114278f542522326 커밋 피드백 반영
- 사용자가 입력하는 값에 대해서만 매직넘버 처리를 하면 되는 줄 알았는데 이런 값 검증에도 사용할 수 있는 것을 처음 알게되었습니다 감사합니다!!!!!!!
- 다만 가장 어려운게 상수 네이밍인 것 같습니다 ㅠㅠ 제가 상수 이름에 뜻을 제대로 녹여낸게 맞는지 의아합니다.

2023-07-02 19:19 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                console.printMsg(voucher.toString());
제가 toString을 호출한 이유는 바우처 list를 사용자에게 출력해줄 때PercentDiscount, FixedAmount Voucher를 구별해서 출력해주기 위함이었습니다! 
voucherList에는 Voucher 인터페이스를 구현한 구현체 2개가 구분 없이 들어가있습니다. 따라서 각 Voucher 객체에 대해 toString을 정의하면 PercentDiscount에 맞는 toString으로 출력해줄 수 있고 FixedAmount에 맞는 toString으로 출력해줄 수 있다고 생각했기 때문입니다.

그래서 다른 방식으로는 생각해보지 못한것 같습니다. 😥😥

2023-07-02 19:37 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    }
6db3f19493544c19d5334d95e931a43181fcaf08 커밋 피드백 반영
- 해당 부분을 생각하고 구글링한 결과로 MenuGroup이라는 것을 만들어보았습니다,, 제가 생각한 방향이 맞을까요 !?!?

2023-07-03 12:01 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +    }
3cdff8229744a453bfa40d4185a710cfcb387969 커밋 피드백 반영
- 강의에 나온것처럼 VoucherApp을 애노테이션이 아닌 VoucherConfiguration에 bean으로 등록하였습니다.
- VoucherApp에 CommandLineRunner를 구현하여 run 함수를 통해 실행시켜주었습니다.
- CommandLineRunner를 사용하여 스프링 애플리케이션이 구동된 이후 실행되어야 하는 빈을 정의하였습니다. VoucherApp Bean은 VoucherConfiguration에서 정의되고 Bean이 등록되면 애플리케이션 구동후 VoucherApp의 run 메소드가 자동으로 실행됩니다.

2023-07-03 12:32 UTC, HyoungUkJJang commented on src/test/java/com/prgms/voucher/voucherproject/VoucherProjectApplicationTests.java
> +}
@sujjangOvO 
의미있는 테스트가 아니라면 형상에는 올라오지 않아도 될 것 같아요 :) !

2023-07-03 12:33 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                console.printMsg(voucher.toString());
@sujjangOvO 

이렇게 한다면 어떻게 될까요?
```java
console.printMsg(voucher);
```

2023-07-03 12:34 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/repository/MemoryVoucherRepository.java
> +import java.util.*;
@sujjangOvO 

게더에 계실 때 같이 한번 봐요 :) ~!!

2023-07-03 12:36 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +        System.out.println("Type **list** to list all vouchers.");
@sujjangOvO 

print 안에 하드코딩 되어있는 문자열을 또 상수로 만들어주면 어떨까요?

2023-07-04 20:12 UTC, sujjangOvO commented on src/test/java/com/prgms/voucher/voucherproject/VoucherProjectApplicationTests.java
> +}
6c2fa21 커밋 피드백 반영
- 현재 사용하지 않는 테스트 코드이므로 형상에서 삭제하였습니다!

2023-07-04 20:14 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +        System.out.println("Type **list** to list all vouchers.");
2049960 커밋 피드백 반영
- static class인 Contant를 정의하여 출력에 필요한 상수들을 모아두었습니다 !
- 말씀해주신 Console의 printMsg를 통해 인자를 받아 출력하는 방식으로 변경하였습니다 !

2023-07-04 20:16 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    }
9d76ae8 커밋 피드백 반영
- 상관없는 MenuGroup을 삭제하고 enum을 활용하는 방안으로 변경하였습니다!
- enum의 매핑을 다 지우고 values메소드와 name메소드를 통해 문자열 비교(equals)를 진행하였습니다!

2023-07-04 20:17 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
840d5f5 커밋 피드백 반영
- 상수와 필드를 개행으로 구분하는 방식으로 변경하였습니다
- run 메소드 안에서만 사용하는 exit 변수를 메소드 멤버변수로 변경하였고 네이밍 규칙을 변경하였습니다.

2023-07-04 20:33 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +                console.printMsg(voucher.toString());
c94ccf6cf2b368c9067f6422eb5fdeed097b5aaa 커밋 피드백 반영
- domain은 출력 의존성을 가지면 안된다 !!! 오버라이딩한 toString 메소드를 삭제하였습니다
- 콘솔에 Voucher의 정보를 주입하여 출력하는 방식으로 변경하였습니다

2023-07-05 01:34 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 남겼어요. 😄 
리뷰 내용 적용 하시고 이후는 간단히 온라인으로 진행 해보시면 어떨까 해요.

2023-07-05 01:34 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    private int menuType;
숫자형 타입인 menuType 는 사용되지 않는것 같아요.
문자형 타입인 menuName 는 열거형 네이밍과 동일 한것 같아요. (동일한 이름인데 필요 했을까요?)

2023-07-05 01:34 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    private int menuType;
숫자형 타입인 menuType 는 사용되지 않는것 같아요.
문자형 타입인 menuName 는 열거형 네이밍과 동일 한것 같아요. (동일한 이름인데 필요 했을까요?)

2023-07-05 01:34 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +            case "list" -> LIST;
"exit" 이 EXIT 라고 판단하는건 사람인것 같아요. 로직적으로 판단하면 좋을것 같아요.

2023-07-05 01:34 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +            }
들여쓰기 (인덴트)가 깊은것 같아요. 줄일 수 있는 방법을 없을까요?
InputMismatchException 에 대한 예외처리가 정말 필요한 범위에 적용되어 있는지, 중복 되지 않는지 고민 해보시면 좋을것 같아요.

2023-07-05 04:23 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuGroup.java
> +public enum MenuGroup {
9d76ae87091f788c97febcf13f71c088bb05c74e 커밋 피드백 반영
- 형욱 멘토님이 이미 지적해주신 부분이어서 커밋올렸습니다 !
- 메뉴 그룹은 제가 하고자하는 방향과는 완전히 다른 것 같아서 삭제하였습니다. 제가 enum에 대해 잘 접하지 않아 생겼던 문제인 것 같습니다.

2023-07-05 04:24 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuGroup.java
> +    private List<MenuType> menuTypeList;
마찬가지로 현재 MenuGroup 파일은 삭제하였습니다!

2023-07-05 04:25 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    private int menuType;
9d76ae87091f788c97febcf13f71c088bb05c74e 커밋 피드백 반영
- 제가 enum의 name 메소드를 활용하지 못해 생긴 문제점인 것 같습니다! 
- MentuType의 사용하지 않는 매핑값을 전부 삭제하였고, switch문도 변경하였습니다!

2023-07-05 04:26 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +    private int menuType;
9d76ae87091f788c97febcf13f71c088bb05c74e 커밋 피드백 반영
- 제가 enum의 name 메소드를 활용하지 못해 생긴 문제점인 것 같습니다! 
- MentuType의 사용하지 않는 매핑값을 전부 삭제하였고, switch문도 변경하였습니다!

2023-07-05 04:27 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +            case "list" -> LIST;
9d76ae87091f788c97febcf13f71c088bb05c74e 커밋 피드백 반영
- 위와 똑같은 커밋입니다! Stream과 name 메소드를 이용하여 enum 멤버의 이름과 비교하는 방식으로 변경하였습니다.

2023-07-05 04:38 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        console.printMsg(CREATE_FIXED_MSG);
45d724b8190f1c8778d65d53695c2b292f32083f 커밋 피드백 반영
- CREATE_FIXED_MSG의 네이밍을 말씀하시는게 맞으실까요!? 
- 네이밍을 좀 더 길게 변경해 보았습니다.

2023-07-05 05:29 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +            }
@Jo-GyuHyeon 
- 인텔리제이에서 인덴트 깊이를 조절하면 된다는 말씀이실까요 !?
- 잘못된 메뉴 입력시 예외처리가  아닌 다른 방식으로 처리해보라고 하시는 의미일까요?

2023-07-06 08:15 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +            }
- 바우처 타입에 숫자가 아닌 문자열을 입력시 프로그램이 죽어버리는 현상이 있었는데 이를 수정하였습니다

2023-07-06 08:33 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +            }
0f457200a8bfaeca091121668b32a0e2d739650a  커밋 피드백 반영
- try/catch문은 딱 예외가 발생하는 지점에만 씌워주도록 하였습니다. 
- 따라서 깊어지는 코드 레벨을 수정하였습니다
- 바우처 타입에 숫자가 아닌 문자열을 입력시 프로그램이 죽어버리는 현상이 있었는데 이를 selectNum의 변수 타입을 String으로 변경하여 해당 현상을 수정하였습니다

2023-07-07 05:30 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        console.printMsg(CREATE_FIXED_MSG);
반영하지 않아도 되는 리뷰였긴 했는데. 
**printMsg()가 포인트였던것 같아요.**


CREATE_FIXED_MSG 에 대한 네이밍을 간단히 제안을 드려 보면 `CREATE_FIXTED_VOUCHER` 는 어떤가요?

2023-07-07 07:18 UTC, Jo-GyuHyeon requested changes
간단히 리뷰 남겼어요.
고생하셨어요. 🙇 
조금만 더 하시면 마무리가 될것 같아요.
끝까지 화이팅이에요. 👍

2023-07-07 07:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        }
else 구문을 없앰으로써 들여쓰기 (인덴트)를 줄일 수 있을것 같아요.

2023-07-07 07:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +    private final Console console = new Console();
Service 는 핵심 비지니스 로직을 다루기에 입출력에 연관이 있으면 안될것 같아요.
수연님의 설계와도 차이가 있으니 확인 부탁드려요.
<img width="834" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/20269425/ff08b41d-e923-4e41-97ab-934e8219ae6b">

2023-07-07 07:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +            }
반복적이고 공통된 로직을 처리 하는 방법에 고민 해보시면 좋을것 같아요.
try catch 구문 필요 여부도 고민 해보시면 어떨까요?

2023-07-07 07:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +    }
사용하지 않는 기능인것 같아요.
그렇다면 제거가 필요해 보이는데 확인 부탁 드려요.

2023-07-07 07:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +        }
instanceof 을 사용하지 않을 수 있을것 같아요.
고민 해보시면 좋을것 같아요.

리뷰 내용과 동일 하지 않지만, 가볍게 보시면 좋을것 같아요.
https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/

2023-07-07 07:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    }
try catch 를 없애도 괜찮지 않을까요??

2023-07-07 07:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
입력에 대한 책임으로 주면 어떨까요??? 수연님의 의견이 궁금해요.

2023-07-07 12:35 UTC, HyoungUkJJang reviewed
수연님 추가 코멘트 남겼습니다 :) 리뷰 반영하시느라 고생하셨어용

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +                .filter(menuType -> Objects.equals(menuType.name().toLowerCase(), menuName))
문자열 비교라면 equalsIgnoreCase()도 한번 참고해보시면 어떨까요?

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/domain/VoucherType.java
> +    private String voucherNum;
숫자로 입력을 받아도 괜찮지 않을까요 ~? 아래는 수연님께서 생각하신 의도일 수 있지만 한번 읽어보면 좋을 것 같아서 링크를 남겨드려요 :)

[ordinal 메서드 대신 필드를 사용하장](https://rutgo-letsgo.tistory.com/279)

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +
컨벤션이 안맞는 것 같아요 !

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
컨벤션이 안맞는 것 같아요 !

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +        VoucherType voucherType = null;
null 말고 다른 방법은 없을까요 ~?

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +        while (!exit) {
! 부정 연산자는 한번 더 생각하게 하는 효과를 가지고 오는 것 같아요 :)

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    } catch (Exception e) {
이곳은 최상위 Exception으로 하신 이유가 있으실까요 ?

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +    private final static long MIN_AMOUNT = 0;
보통 private static final 형태로 많이 사용합니당 :)

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
수연님은 this를 붙이는 컨벤션은 어떻게 생각하시나요 ~? 현재는 생성자에만 this 키워드가 존재하고 있어요 !

일반 메서드에도 this 키워드를 붙인다면 코드를 파악하기 더 수월할 것 같은데 수연님의 생각은 어떠신가요 !?

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +    public long discount(long beforeDiscount) {
beforeDiscount = 1500, amount = 1000 

현재 로직으로는 -500이 리턴되겠군요? 그럼 손님은 500원을 오히려 받아야할까요?!!!

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +
한 줄 개행처리 안해도 될 것 같아요 :)

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +    public Console(){}
기본 생성자를 명시하신 이유가 있으실까요?

2023-07-07 12:35 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +    }
코드에 구분감이 조금 생기면 좋을 것 같아요 ! 중간중간 개행처리를 한번 해주면 어떨까요 ~?

2023-07-07 17:25 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        console.printMsg(CREATE_FIXED_MSG);
4cc7dc666cf977a40bc2cd61351c75ce4a1c6592 커밋 피드백 반영
- 멘토님이 제안하신 상수 네이밍이 더 적절한 것 같아 변경하였습니다!

2023-07-10 10:46 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +        }
7aab414b79a665bc91796b73d8652aa356a2115e 커밋 피드백 반영
- voucherList가 비어있다면 예외가 발생할 것이라고 생각했는데 아니었단걸 알게되었습니다.
- 해당 리스트가 비어있다면 그저 print하지 않고 지나갑니다

2023-07-10 10:51 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +            }
7aab414b79a665bc91796b73d8652aa356a2115e 커밋 피드백 반영
- exception에 대한 공통된 로직은 exceptionCatch 메소드로 분리했습니다
- 굳이 create의 swtich문에서 try-catch문을 하지 않고 각 메소드가 호출된 부분에서 try-catch문을 하도록 하였습니다
- 여기서 질문이 있는데 try문에는 예외가 발생하는 부분만 넣어야 한다는 것을 알지만 try문 안에서 초기화된 voucher 객체이기 떄문에 catch문 뒤에서 repository에 save하는 부분을 처리한다면,  save 메소드의 인자 voucher로 넣어주기 위해선 try문 바깥에서 지역변수 Voucher percentDiscountVoucher = null으로 초기화 해줘서 null 값이 save 될수도 있다고 생각하는데 이를 해결하기 위해서는 어떻게 해야 할까요?

2023-07-10 10:52 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +    }
7aab414b79a665bc91796b73d8652aa356a2115e 커밋 피드백 반영
- getVoucher를 현재 사용하지 않아 형상관리에서 제거되어야 한다고 생각해서 삭제했습니다

2023-07-10 10:56 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +        }
9db8e50b5f3c34f25c4c78376f8ad5e262650ea1 커밋 피드백 반영
- 캡슐화와 유지보수성을 보존하기 위해 instanceof의 사용을 지양해야 하는 점을 알게되었습니다
- 각 voucher 구현체에서 `static 메소드`로 객체를 확인할 수 있게 되었습니다
- 여기서 궁금하나 점이, static 메소드로 선언하여 해당 메소드를 사용하고 있는데 이렇게 하는 방법이 합당한지 궁금합니다
- 저는 객체의 상태를 바꾸는 것도 아닌 단지 voucher의 구현 타입을 확인하는 것이기 때문에 딱히 인스턴스화 하여 메소드를 호출할 필요가 없다고 생각하여 static으로 선언하였습니다

2023-07-10 10:59 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +
@Jo-GyuHyeon 
Console의 inputCommand 메소드에서 입력 검증을 받도록 하라는 의미가 맞는지 궁금합니다!

2023-07-10 11:02 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/MenuType.java
> +                .filter(menuType -> Objects.equals(menuType.name().toLowerCase(), menuName))
9a86536597217c6b1fb93c2a4bfce2d23625903d 커밋 피드백 반영
- 대소문자 신경을 쓰지 않는 equalsIgnoreCase 메소드가 좀 더 나은 선택인 것 같습니다. 감사합니다 !! 굳이, toLowerCase 메소드를 사용 할 이유가 없던 것 같습니다.

2023-07-10 11:03 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/VoucherType.java
> +    private String voucherNum;
c58a87f4330c251f99c187ccc4afb2a0ee464eff 커밋 피드백 반영
- 이렇게 하면 문제가 int 형이 아닌 String을 입력받게 되면 또 다른 예외가 발생하고 또 이를 catch하면서 return값으로 잘못된 값이 넘어가게 되는데 어떻게 해결해야 할지 의문이 생깁니다 ..

2023-07-10 11:06 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +        VoucherType voucherType = null;
enum 클래스 객체를 초기화하는 방법을 찾아보았는데 생각이 아직 안 납니다. 혹시 힌트를 주실 수 있을까요 ..?

2023-07-10 11:06 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +        while (!exit) {
599f7decd08e855be42aa36ca69bea5d31affa14 커밋 피드백 반영
- 변수의 이름을 부정형으로 바꾸면서 반복문의 조건에 ! 연산자를 제거 하였습니다

2023-07-10 11:07 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    } catch (Exception e) {
해당 부분을 지금 고민중 입니당,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 좀 더 고민해보고 말씀드리겠습니다 ,,

2023-07-10 11:08 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
72d1bed20d209e9b0baa84087a7a6e3b6283d3b4 커밋 피드백 반영
- this 키워드를 이용해서 해당 객체의 자원임을 더 쉽게 알아볼 수 있게 되었습니다 !

2023-07-10 11:09 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/FixedAmountVoucher.java
> +    public long discount(long beforeDiscount) {
72d1bed20d209e9b0baa84087a7a6e3b6283d3b4 커밋 피드백 반영
- 삼항연산자를 이용하여 적절한 discountedAmount이 오지않는다면 0을 리턴하도록 변경하였습니다 !

2023-07-10 11:11 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +    public Console(){}
3e5a2cae307a17d9113bcee291d7c72f8bae6a11 커밋 피드백 반영
- Console을 초기에 구상할 떄 인자가 포함된 생성자를 작성하다보니 기본 생성자가 정의되어야 한다고 해서 롬복 NoArgsConsructor을 통해 생성하였다가 롬복 사용을 지양하자는 말씀을 듣고 교체했던 것 같습니다.
- 현재는 삭제하였습니다 !

2023-07-10 18:51 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +    }
7aab414b79a665bc91796b73d8652aa356a2115e 커밋 피드백 반영
- 멘토님의 피드백에 따라 해당 부분으로 try-catch문을 변경하였습니다!

2023-07-10 18:55 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +        while (!exit) {
26911da9feea38b83b329c44df95e3a7b2249900 커밋 피드백 반영
- notExit보다 isRunning이 더 가독성 좋은 것 같습니다 !!!

2023-07-12 05:32 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
> +    private final Console console = new Console();
bfc7904ac2e2e080919f3d99ce593cf2bda7dcb6 커밋 피드백 반영
- 멘토님이 새벽에 반영해주신 피드백을 커밋올렸습니다!
- service부분에 콘솔과의 의존성을 없앰으로써 출력 의존성을 제거하게 되었습니다.

2023-07-12 05:34 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/domain/VoucherType.java
> +    private String voucherNum;
bfc7904ac2e2e080919f3d99ce593cf2bda7dcb6 커밋 피드백 반영
- VoucherService에서 int형이 아닌 다른 값을 받게되면 null을 넘기게 함으로써 입력에 대한 예외를 처리하였습니다

2023-07-12 05:37 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +        VoucherType voucherType = null;
inputDiscountAmount 커밋 피드백 반영
- console에서 바로 해당 MenuType, VoucherType을 return하도록 수정한 후 null로 초기화하는 필드 변수를 삭제하였습니다

2023-07-12 05:39 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/VoucherApp.java
> +                    } catch (Exception e) {
bfc7904ac2e2e080919f3d99ce593cf2bda7dcb6 커밋 피드백 반영
- 멘토님 피드백에 따라 VoucherApp과 Service에서 출련 의존도를 없애고 메소드를 호출하는 방식으로 변경하였습니다

2023-07-12 08:54 UTC, Jo-GyuHyeon approved these changes
고생 많으셨어요.
처음과 비교 하였을때 많은 변화가 있었던것 같아요.
위클리 2에는 속도감 있게 빠르게 진행 하길 기대 해볼게요.
다시 한번 고생 많으셨어요. 🙇

2023-07-12 08:54 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +    }
msg 처럼 축약을 사용하면 나중에 어떤 축약인지 기억 하기 쉽지않고, 가독성이 떨어지는 경우가 많기에 습관적으로 풀네이밍을 사용하는것을 권유드리고 싶어요.

2023-07-12 09:20 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/io/Console.java
> +    }
cd0609f21107274949f6833f19fc5895b9a159b2 커밋 피드백 반영
- 축약 네이밍보다 풀네이밍을 사용하도록 유의하고 신경쓰도록 하겠습니다!

2023-07-13 06:34 UTC, merged