[4기 - 박세영] SpringBoot Part1 Weekly Mission PR입니다
prgrms-be-devcourse/springboot-basic pull request #716
Opened 2023-06-28 15:18 UTC by SY97P

# SpringBoot Basic Weekly Mission

## 📌 과제 설명 
* `SpringbootApplication` : Main
* `Platform`              : 유틸 클래스
* `InvalidDataException`  : 예외 클래스
* `Message`               : 메시지 레코드 클래스
* `Menu`                  : 종료 / 생성 / 출력 메뉴 enum
* `ListMenu`              : 바우처 / 블랙고객 출력 메뉴 enum
* `VoucherType`           : 고정값 / 비율값 바우처 타입 enum
* `DiscountValue` : 할인값 입력 Dto
* `VoucherDto` : 바우처 Dto
* `VoucheMap` : 바우처 메모리 일급 컬렉션 클래스
* `InputConsole`          : 입력 클래스
* `OutputConsole`         : 출력 클래스
* `CustomerService`: 고객 서비스 클래스
* `CustomerRepository` : 고객 서비스 레포지토리 클래스
* `VoucherService`        : 바우처 서비스 클래스
* `VoucherRepository`     : 바우처 레포지토리 인터페이스
* `MemoryVoucherRepository`: 메모리 저장 바우처 레포지토리 클래스 (dev 프로퍼티)
* `FileVoucherRepository` : 파일 저장 바우처 레포지토리 클래스 (default 프로퍼티)
* `YamlProperty`          : Yaml 파일 속성 클래스
* `VoucherFactory`        : Voucher 클래스 생성 인터페이스
* `FixedVoucherFactory`   : 고정값 바우처 클래스 생성 클래스
* `PercentVoucherFactory` : 비율값 바우처 클래스 생성 클래스
* `Voucher`               : 바우처 인터페이스
* `FixedAmountVoucher`    : 고정값 바우처 클래스
* `PercentDiscountVoucher`: 비율값 바우처 클래스
* `CommandLineTemplate` : 사용자 입출력 템플릿 클래스
* `CreateVoucherTemplate` : 바우처 생성 템플릿 클래스
* `ListMenuTemplate` : 출력 메뉴 템플릿 클래스

## ✅ PR 포인트 & 궁금한 점 

* 테스트 코드 작성 시 IllegalStateError가 발생합니다
  * 특히 `CustomeRepositoryTest`, `FileVoucherRepository` 클래스처럼 `YamlProperties` 를 DI 받아야 하는 클래스의 경우 테스트 하는 방법을 찾기가 어려웠습니다.
  * 검색해보니 빈을 찾지 못하는게 이유라고 하는데 이 문제를 해결하는 노하우가 있다면 알고 싶습니다.
* 템플릿을 적용했습니다.
  * `Platform` 클래스에서 입출력 템플릿을 통해 각각 생성 템플릿, 출력 템플릿으로 연결되도록 수정했습니다.
  * 피드백 의도에 맞게 수정이 된건지 확인해주셨으면 좋겠습니다.

## 👩‍💻 요구 사항과 구현 내용 
- #### 기능 구현
- [x] Gradle 프로젝트 생성
  - [x] Spring Boot CLI로 생성
- [x] Command-Line-Application 입출력
  -> 서버 기능 없이 콘솔로 동작
  - [x] exit(0) 명령 입력
  - [x] create(1) 명령 입력
  - [x] list(2) 명령 입력
- [x] 종료
- [x] 생성
  - [x] 고정값 바우처 생성
  - [x] 비율값 바우처 생성
  - [x] 메모리 저장 (dev 프로퍼티일 때)
  - [x] 파일 저장 (default 프로퍼티일 때)
- [x] 조회
  - [x] 바우처 조회
  - [x] 블랙고객 조회
- [x] YAML 프로퍼티 적용
  - [x] 버전
  - [x] 바우처 조회 파일 경로
  - [x] 블랙고객 파일 경로
- [x] 로그
- [x] jar 파일 추출
  - [x] gradle 방식

## ✅ 피드백 반영사항  
- @Autowired 사용 ✅
  - ‘필드 삽입은 권장되지 않는다’의 이유
  - bean 객체들을 주입할 때 현재는 권장되지 않는다.
  - 생성자 주입을 하는 필드의 후보를 선별하기 위해서 스프링 컨테이너가 필드의 상태를 체크한다. 이것에 대해 알아보자
  - 찾아본 거
    - 생성자 주입 방식의 더 큰 이점
      ◦ 초기화 시 필요한 모든 의존 관계 형성 → 안전성 확보
      ◦ 잘못된 패턴 찾기 가능 → 안전성 확보
      ◦ 테스트 쉬워짐 → 등록되지 않은 Bean에 의한 비정상 종료 방지
      ◦ 불변성 확보 → 멀티스레드 환경에서 thread-safety 보장
    - 필드 주입 방식의 단점
      ◦ 의존성 파악이 모호해지는 경향 → 순환참조 가능성 증가
      ◦ 스프링 IoC 컨테이너에서 빈을 일치시켜 충족할 수 있는 의존성이 가장 많은 생성자가 선택

      → 해당 과정에서 불필요한 오버헤드 발생.

- DTO 활용 ✅
  - 재료는 늘어나지만 파라미터는 늘어나지 않도록 하는 방법
  - DTO 를 사용하면 늘어난 파라미터를 하나로 정리해서 넘겨줄 수 있다.
    - 객체지향생활체조 준수 방법 중 하나
  - Spring MVC (Controller, Service, Repository 간 데이터 전달 과정에서 layer로써 유용)
  - DTO는 주로 Client ↔ Contoller ↔ Service 구간에서 자주 사용함
  - Record 클래스 혹은 Enum 클래스로 구현하면 좋다
  - data
    1. user input data(spring request parameter)
    2. entity → (db 혹은 persist layer)
    3. response, result
    - Service → response, entity
    - Controller → requeest, param
    - Repository → entity
- 커스텀 예외 클래스 ✅
  - throwable cause도 같이 넘겨주면 디버깅할 때 좋다.
    - 예외가 다른 예외를 발생시킬 수 있기 때문 `Chained Exception`
    - 큰 분류의 예외로 묶어서 다루기 위해서
    - 상속관계를 무시하고 사용하고 싶어서
      - 부모를 공유하는 두 자식 예외가 부모 예외를 기준으로 catch하게 된다면 정확한 원인을 알 수 없게됨
      - cause를 사용하므로써 상속관계를 무시하고 정확한 원인을 알 수 있다.
    - checked 예외를 unchecked 예외로 바꿀 수 있어서
      - 반드시 예외처리를 해줘야 하는 checked 예외를 상위 예외 클래스로 감싼다면 더이상 예외처리가 강제되지 않음
      - checked 예외가 unchecked 예외로 바뀌는 거임
  - 정적인 것(메시지)와 분리해줘야 한다.
    - 매번 예외 객체가 생성되기 때문
    - error message(정적 String 모음)와 exception 클래스의 분리 필요
- Script 식 코드 줄이기✅
  - Platform 클래스 Switch Case 내부 로직
  - 해야할 일을 순서대로 나열한 코드는 객체지향적이지 않다.
- 향상된 switch 문 ✅
  - 한 case 문에 여러 조건 가능 (쉼표로 구분)
  - break 문 필요없음
  - : 말고 → 사용
  - switch에서 값 리턴 가능
    - 값 리턴하는 경우에는 반드시 default 가 있어야 함
  - yield 키워드
    - 스위치 표현식/문장에서 값을 명시적으로 리턴하기 위한 키워드
    - 코드 블록 {} 내에서만 사용 가능
    - 코드 블록 내 계산된 값을 반환
    - return 키워드와 함께 쓸 수 없음 → level을 다르게 해서 써야함.return
      - return : switch 구문 내에서 값을 반환 후 switch 문 종료
      - yield: switch 구문 내에서 계산한 결과를 switch 표현식의 결과로 반환
- private 메소드로 뺀 건 좋은 시도✅
- template을 생각해보자. ✅
  - command line을 프린트하는 역할과 데이터 처리를 분리해서 생각해 볼 필요가 있다.
  - list menu template, createMenuTemplate , command line print이 따로 존재 & 파이프라인이 있다고 생각하고 짜도 좋을 것
- factory는 더 거시적으로 잘 보이도록!✅
  - enum이 하는 일과 using Enum이 하는 일을 생각해보자.  → 가독성, 유지보수성을 위해서
  - Using Enum 구간에서 Factory를 사용하면 더 쉽게 사용접근이 가능할 것
- 제네릭 (profile에 따라서 파일저장과 메모리저장)✅
  - standard Interface를 기준으로 구현
    - interface가 기준
    - 상속받은 클래스는 interface의 형태를 따라가야함
    - 이게 standard interface
  - <T> 이런 코드는 지양하는게 좋다고 함..
      - 왜인지는 모르겠음. 범용적이면 좋은거 아닌가? 타입 안정성이 필요한 것도 아닌데…
  - 찾아본거
    - 제너릭 한정자
      - <? extends T> : T 타입 포함한 하위타입인 제네릭
      - <? super T> : T 타입 포함한 상위타입인 제너릭
- 추상클래스 vs 인터페이스✅
  - 추상클래스 : 실체가 명확할때
    - 조금이라도 value를 가질 것 같으면 추상클래스
  - 인터페이스 : 추상의 끝판왕
- 주석, 로그는 필요한 곳에만✅
  - Ex) menu 입력시 에러 발생하는 경우
  - Exception에서 로그 작성하는 것이 아니라 예외 터진 후에 로그 메시지를 받아와서 작성하는 것이 좋다.
  - output 과 logger를 분리하려는 목적
- 단위테스트는 테스트 대상과 이름이 공통되는 편이 좋음✅

### Git Commit Convention
* feat : 기능
* fix  : 버그 수정
* docs : 문서 작업
* style: 포맷팅, ;추가
* refactor : 리팩토링 (기능 변경 X)
* test : 테스트 코드 추가
* chore : 유지 (빌드 작업, 패키지 메니저 작업)

2023-06-29 02:33 UTC, WooSungHwan requested changes
제가 던진 질문들이 많은데요! 

우선 코드가 어려워서 코드를 인텔리제이에 다운받았고 하나하나 로직을 따라가지 않는 이상 쉽다고 느껴지지는 않았어요.  그말은 즉, 클래스 하나만 놓고봤을때 결국 여러가지 일을 한꺼번에 하는건 여전히 잔재하다는 걸로 볼 수 있어요.

저와의 그리고 스스로 돌아보는 코드리뷰 말고도 동일한 시점의 동료들에게도 보여주고 쉬운코드인가에 대한 피드백을 받아보셨으면 좋겠습니다.

고생 많으셨습니다.

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/constant/YamlProperties.java
> +public class YamlProperties implements InitializingBean {
해당 인터페이스를 구현해서만 afterPropertiesSet에서 하는 로깅을 구현할 수 있는건지??

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/constant/YamlProperties.java
> +@Configuration
이 프로퍼티즈가 설정클래스인지?
이런 어노테이션 붙이는 곳은 어디인지?

2023-06-29 02:33 UTC, WooSungHwan commented on src/test/java/com/devcourse/springbootbasic/application/repository/customer/CustomerRepositoryTest.java
> +@SpringJUnitConfig
https://www.baeldung.com/spring-5-junit-config

2023-06-29 02:33 UTC, WooSungHwan commented on src/test/java/com/devcourse/springbootbasic/application/repository/customer/CustomerRepositoryTest.java
> +@SpringJUnitConfig
해당 내용을 보고 이 테스트를 실행할때 빈이 있을 수 있는 구조인가 고민해보세요.

2023-06-29 02:33 UTC, WooSungHwan commented on src/test/java/com/devcourse/springbootbasic/application/repository/customer/CustomerRepositoryTest.java
> +    }
이렇게 쓴다는건 SpringBootTest와는 뭐가다른건지??

2023-06-29 02:33 UTC, WooSungHwan commented on src/test/java/com/devcourse/springbootbasic/application/repository/customer/CustomerRepositoryTest.java
> +}
전반적으로 해당 클래스는 테스트 목적에는 소홀하고 스프링 프레임워크의 동작에만 의존하여 처리하고싶은 목적이 많이 느껴지는 부분입니다.
해당 클래스의 테스트 목적에 대해서 다시한번 생각해보고 어떻게하면 쉽게 테스트코드 작성할 수있을지 고민해보세요.

@TestConfiguration

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
얘네 들은 각 템플릿으로 넘어가도 되지 않나요?

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
얘한테도 뭔가의 role을 부여하면 좋을 것 같은데요.

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/constant/Message.java
> +public record Message() {
이 클래스가 record가 맞는지 고민해보기

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
yield 로 반환되는 true/false값을 표현할 수 있을만한 메소드명으로 만들기.

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
저게 반환되면 저걸로 뭘한다는지 알 수 없음. 개발한사람밖에 모르니 팀원들한테 이 메소드만 딱 보여주고

`"이거 boolean 반환 이후에 뭘할 것 같아?"` 물어보고 다 맞출 수 있을 때까지 개선하세요.

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    }
to String을 추상에서 제공하는게 맞는지?

2023-06-29 02:33 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    }
굳이 추상에서 구현까지 필요한건지?
불필요한 데이터까지 추상에서 보관하는건 아닌지?

2023-06-29 07:28 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +            if (getUserMenuInput()) {
게임 종료에 관한 부울 리턴값을 나타내기 위해 isEndGame() 으로 메소드 이름 바꿨습니다.

2023-06-29 07:37 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/constant/YamlProperties.java
> +public class YamlProperties implements InitializingBean {
@PostConstruct 어노테이션 이용한 방식도 사용할 수 있습니다.
저는 클래스 초입부에서 확인하고 싶어서 인터페이스 구현 방식을 썼습니다.

2023-06-29 07:57 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/constant/Message.java
> +public record Message() {
record일 필요 없다고 생각해 enum 클래스로 변경했습니다.

2023-06-29 08:04 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    }
구상체로 옮겼습니다.

2023-06-29 08:06 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    }
공통부분이라고 생각해서 추상클래스에서 관리하도록 했습니다.
위 코드는 getter이지만 굳이 구상체까지 가지 않아도 얻을 수 있는 공통정보라고 생각해서 추상체에서 값을 받고 싶었습니다.

위 정보까지 추상체에서 가지지 않는다면 Voucher 클래스는 추상클래스보다 인터페이스가 더 적합할 것 같습니다.

2023-06-29 09:51 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/repository/customer/CustomerRepositoryTest.java
> +    }
SpringBootTest는 전체 어플리케이션을 실행해서 테스트하는 어노테이션입니다. 
applicationContext를 가지고 테스트를 수행할 수 있다고 이해했습니다. 

반면에 SpringJUnitConfig 어노테이션은 전체 applicationContext를 가지고 시작하는 것이 아니라, 필요한 빈을 가지고 테스트할 수 있습니다.

위 코드는 테스트용 설정파일을 만들고 시작하는 겁니다.
다만, 컴포넌트 스캔 범위가 전체이므로 SpringBoottest와 기능 차이는 없을것 같습니다.

2023-06-29 09:54 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/constant/YamlProperties.java
> +@Configuration
설정클래스에 붙는 어노테이션인걸로 알고 있습니다.
어플리케이션에서 IoC를 통해 빈으로 생성되는, 그러니까 컴포넌트 스캔이 되는 요소들을 설정해주는 어노테이션입니다.

프로퍼티 클래스에서 필요하지는 않다고 생각하지만, 왜인지 어노테이션을 빼면 컴파일 에러가 발생합니다.
이유에 대해서는 계속 찾아보겠습니다.

2023-06-29 14:59 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/constant/YamlProperties.java
> +        logger.debug(MessageFormat.format("This Version of Voucher Application : {0}", version));
로깅을 afterPropertiesSet에서 남기신 이유가 궁금합니다. 
애플리케이션이 시작되면서 바우처 버전을 로깅하시려는 용도이실까요?

2023-06-29 15:02 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/constant/YamlProperties.java
> +@ConfigurationProperties(prefix = "settings")
바우처 관련된 property들을 객체로 관리하려는 용도이신거같아요! 

만약 yaml property들을 한 객체에서만 관리하고 해당 property를 이용하려는 모든 객체들에게 주입을 시키게 되었을 때, 
이 객체가 어떤 변화가 생긴다면 전파가 많이 될것 같아요. 
나눠보는것은 어떻게 생각하세요?
그렇다면, YamlProperties보다 더 명확한 이름을 지어주는건 어떨까요?

2023-06-29 15:05 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/constant/Message.java
> +
1 예외 메시지 - 예외 관련
2 출력 메시지 - 출력 관련
를 관리하는 Enum이네요. 

1, 2 둘을 한곳에서 관리하면 어떤 문제가 있을 수 있을까요? 

출력용 메시지를 외부 리소스 에서 관리할수도 있습니다.

2023-06-29 15:13 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
각자 책임 분해해서 템플릿 안으로 넣었습니다. 

CommandLineTemplate 클래스 안에 CreateVoucherTemplate, ListMenuTemplate 클래스를 주입해서
파이프라인처럼 사용할 수 있도록 했습니다.

A(커멘드 템플릿) -> B(기능 템플릿) -> A 이런식이라 파이프라인이라고 부를 수 있는지 모르겠습니다.

2023-06-29 15:14 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/SpringbootBasicApplication.java
> +@EnableConfigurationProperties
@EnableConfigurationProperties 어노테이션은 
따로 Configuration 클래스를 생성하여 해당 클래스로 관리할 수도 있습니다.. 
테스트시, Enable되지 않을경우, @ConfigurationProperties가 활성화 되지 않을 수 있습니다. 

https://csy7792.tistory.com/335

2023-06-29 15:17 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +        this.commandLineTemplate = new CommandLineTemplate(input, output);
CommandLineTemplate은 @Component인데 왜 new로 생성하셨는지 궁금합니다.
CommandLineTemplate을 주입받으면
InputConsole, OutputConsole도 받을 필요가 없지 않을까요?

2023-06-29 15:18 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/template/CreateMenuTemplate.java
> +public class CreateMenuTemplate {
Template은 어떤 의미인지, 왜 이렇게 네이밍 하셨는지 궁금합니다.

2023-06-29 15:23 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/service/VoucherService.java
> +    private Voucher convertDtoToDomain(VoucherDto voucherDto) {
Service는 어떤 역할을 하는 계층일까요? 
convertDtoToDomain가 service 라는 객체에서 컨버팅하는 책임을 가져야할까요?

dto가 늘어나서, SuperVoucherDto, FakeVoucherDto, MoneyDto 등이 생겨날때마다 서비스 코드가 늘어날 수 있겠네요  

적절한 책임을 가진 다른 객체가 convert하는건 어떨까요?

2023-06-29 15:24 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/VoucherRepository.java
> +    Optional<Voucher> insert(Voucher voucher);
insert될땐 Voucher,

find할땐 String

Voucher를 find해서 어떤 비즈니스 요구사항에 맞는 로직을 구현할때 부수적인 일들이 많이 늘어날 것 같습니다.

2023-06-29 15:27 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/FileVoucherRepository.java
> +        List<String> voucherRecord = new ArrayList<>();
Record라는 이름을 보면, record 키워드가 생각나기도 해요 

또한 Record라는 책임을 가진 다른 도메인이나, 객체가 있다면 헷갈릴수도 있을것 같아요

변수 이름은 코드의 가독성을 높이고 의도를 명확하게 전달하는 데 도움이 되어야 합니다. 따라서, 변수 이름을 개선하는 것이 좋아요. 

복수형으로 s를 붙이는 일이 잦습니다.

2023-06-29 15:27 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/FileVoucherRepository.java
> +            return Optional.of(voucher);
혹시 왜 insert하고 Optional로 반환하시는건지 궁금합니다.

2023-06-29 15:30 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/io/OutputConsole.java
> +public class OutputConsole {
이름은 OutputConsole이지만, Voucher에 종속되어있네요.

2023-06-29 15:32 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/factory/VoucherFactory.java
> +    Voucher create(double voucherDiscount);
요구사항이 바뀌어 double타입이 아닌 long이나 Integer로 바뀌면 해당 인터페이스를 구현하는 모든 구현체도 변경의 영향이 있겠네요.

원시값 포장 이라는 키워드로 찾아보시면 좋을것 같습니다.

2023-06-29 15:36 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/factory/PercentVoucherFactory.java
> +                UUID.randomUUID(),
가령, Voucher의 id가 00000000-0000-0000-0000-000000000000 인 경우, 100% 할인 + 100억 보상금 당첨 이벤트를 해야하는 요구사항이 생긴 경우

이 코드는, 테스트를 할수가 없겠네요. 

어떤 좋은 방법이 있을까요? 

키워드 : DIP, 랜덤값 테스트

2023-06-29 15:36 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/factory/FixedVoucherFactory.java
> +        return new FixedAmountVoucher(
PercentVoucherFactory와 동일한 의견입니다.

2023-06-29 15:39 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/service/VoucherService.java
> +        if (voucherDto.voucherType().equals(VoucherType.FIXED_AMOUNT)) {
enum은 ==(동일성) 비교가 가능합니다. 

enum이 왜 == 비교가 가능한지, 동일성과 동등성에 대해 알아보시겠어요?

2023-06-29 15:41 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/service/VoucherService.java
> +            return new FixedVoucherFactory().create(voucherDto.discountValue());
결국 이런식으로 서비스에서 enum을 비교해서 해당 팩토리를 생성하고, 다시 바우처를 생성하는것은 책임을 미루고 코드량이 늘어나고 복잡도가 올라가는 결과를 가져온거 같아요.

Factory는 공장, 재료를 가지고 무언가를 만들어 낼 수 있어요. 
enum이랑 속성들이란 재료로 공장한테 일을 시켜보는건 어떨까요?

2023-06-29 15:43 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/factory/VoucherFactory.java
> +public interface VoucherFactory {
Factory는 객체지향과 디자인 패턴에서 어떤 의미로 사용될까요?

바우처 종류가 늘어날때마다 팩토리도 늘어나겠네요

2023-06-29 15:44 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    public VoucherType getVoucherType() {
이 책임은 서브클래스델에게 넘기는건 어떻게 생각하세요?

2023-06-29 15:45 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    UUID voucherId;
어디어디에서 접근가능할까요? 수정도 막 가능해 보여요.

access modifier에 대해 설명해주세요.

왜 access modifier를 지정할까요?

2023-06-29 15:47 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/dto/Menu.java
> +                    logger.error("Menu Error - {} : {}", menuString, Message.INVALID_MENU);
예외에 INVALID_MENU.getMessageText()라는 메시지를 넘겨주네요.
저는 이 로그를 여기가 두는건 좀 부적절해보여요.

혹시, 어떤곳이 적당하다고 생각하세요?

2023-06-29 15:48 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/dto/VoucherType.java
> +                    logger.error("Menu Error - {} : {}", voucherTypeString, Message.INVALID_VOUCHER_TYPE);
Menu

2023-06-29 15:49 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/io/OutputConsole.java
> +    public void printError(Exception e) {
좋네요!

2023-06-29 15:50 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/MemoryVoucherRepository.java
> +    public Optional<Voucher> insert(Voucher voucher) {
FileVoucherRepository

2023-06-29 15:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/domain/VoucherMap.java
> +    public List<String> getAllVouchers() {
String으로 변환하시는 이유가 궁금해요

2023-06-29 15:51 UTC, devYSK commented on src/main/resources/application.properties
> +
사용안하면 제거해주세요

2023-06-29 15:51 UTC, devYSK commented on src/main/resources/banner.txt
> +| |  / /___  __  _______/ /_  ___  _____   /   |  ____  ____
LGTM

2023-06-29 15:54 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/domain/PercentDiscountVoucher.java
> +        super(uuid, voucherType, percent);
percent가 -가 된다면?

방어적인 코드를 작성해볼까요?

2023-06-29 15:54 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/domain/FixedAmountVoucher.java
> +    public FixedAmountVoucher(UUID uuid, VoucherType voucherType, double amount) {
amount가 -가 된다면?

방어적인 코드를 작성해볼까요?

2023-06-29 15:55 UTC, devYSK commented on src/test/java/com/devcourse/springbootbasic/application/factory/FixedVoucherFactoryTest.java
> +        var voucher = new FixedVoucherFactory().create(0.1);
250퍼센트 할인할 수 있을것 같아요

2023-06-29 16:05 UTC, devYSK commented on src/test/java/com/devcourse/springbootbasic/application/repository/voucher/MemoryVoucherRepositoryTest.java
> +    void insert(Voucher voucher) {
given / when / then 패턴에 대해 알아보세요!

2023-06-29 16:07 UTC, devYSK commented on src/test/java/com/devcourse/springbootbasic/application/factory/PercentVoucherFactoryTest.java
> +        var voucher = new PercentVoucherFactory().create(0.1);
domain의 PercentVoucher 테스트랑 같은거 같아요. 

CreateService의 리뷰를 봐주시고 여기도 다시 한번 봐주시겠어요

2023-06-30 05:23 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    }
구상체로 옮기면서 각 구현체별로 세부적인 String이 반환되도록 했습니다.

2023-06-30 05:24 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
메소드 이름을 변경하면서 느낀 점인데 메소드도 최대한 역할을 분리시켜야 이름 짓기가 좋은 것 같습니다.

2023-06-30 05:28 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
`private boolean isEndGame() {
        try {
            return commandLineTemplate.isExitMenuBranch();
        } catch (InvalidDataException e) {
            commandLineTemplate.errorTask(e);
            logger.error(e.getMessage(), e.getCause());
        }
        return false;
    }`

2023-06-30 05:34 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
CreateVoucherTemplate은 VoucherService를 이용해서 바우처를 생성하는 템플릿 역할만 수행,
ListMenuTemplate은 VoucherService, CustomerService를 이용해 리스트를 반환하는 역할만 수행하도록 했습니다.

두 개의 템플릿을 호출하고, 활용하는 위의 원본 코드를 CommandLineTemplate으로 이동시켰습니다.
CommandLineTemplate에 너무 많은 책임이 부여된 것 같아 걱정됩니다.

2023-06-30 05:39 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/repository/customer/CustomerRepositoryTest.java
> +    }
SpringJUnitConfig는 단위테스트, SpringBootTest는 통합테스트에 적합하다고 들었습니다. 
저는 단위테스트에 활용하고 싶었기 때문에 SpringJUnitConfig를 사용했습니다.

테스트 코드를 작성하면서 ApplicationContext를 찾을 수 없다는 IllegalStateException이 자꾸 발생해,
컴포넌트 스캔 범위를 최대한 넓게 잡아두고, 설정파일에 빈을 넣어보려고 했습니다.

그 번뇌의 과정에서 발생한 코드입니다 ㅠ

2023-06-30 07:27 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/constant/Message.java
> +
분리하는게 좋다고 생각합니다.
출력 메시지를 외부 리소스로 관리할 생각은 못 했는데 좋은 방법인 것 같습니다. 
적용해보겠습니다.

2023-06-30 07:29 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +        this.commandLineTemplate = new CommandLineTemplate(input, output);
맞습니다.

템플릿 클래스 리팩토링하면서 이제 Platform 클래스에서는 CommandLineTemplate 만 DI 받으면 되도록 수정했습니다.

2023-06-30 07:32 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/template/CreateMenuTemplate.java
> +public class CreateMenuTemplate {
Template는 반복적인 일을 할 때 유용하게 사용할 수 있는 도구라는 뜻으로 사용했습니다. 

ListMenuTemplate은 리스트 메뉴와 관련된 반복 작업에 사용하라는 의미였습니다.
CreateMenuTemplate은 바우처 생성 관련된 반복 작업에 사용하라는 의미로 이름을 지었는데, 의미 전달이 안 되는 것 같습니다. 

CreateVoucherTemplate 으로 변경하겠습니다.

2023-06-30 07:34 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/service/VoucherService.java
> +    private Voucher convertDtoToDomain(VoucherDto voucherDto) {
Converter 클래스를 만들어
DTO -> Domain 으로 전환하는 역할로 분리하겠습니다.

2023-06-30 07:46 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/FileVoucherRepository.java
> +        List<String> voucherRecord = new ArrayList<>();
vouchers 로 수정했습니다.

2023-06-30 07:51 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/FileVoucherRepository.java
> +            return Optional.of(voucher);
불필요하다고 생각해서 Voucher 반환하도록 수정했습니다.

2023-06-30 07:56 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/io/OutputConsole.java
> +public class OutputConsole {
종속되지 않도록 메소드 제거했습니다.

2023-06-30 07:56 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/io/InputConsole.java
> +public class InputConsole {
종속되지 않도록 구조 변경했습니다.

2023-07-01 07:06 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/factory/VoucherFactory.java
> +    Voucher create(double voucherDiscount);
DiscountValue 라는 VO 클래스로 원시값을 포장했습니다.

2023-07-01 07:07 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/PercentDiscountVoucher.java
> +        super(uuid, voucherType, percent);
원시값 포장하면서 유효성 판단하도록 수정했습니다.

2023-07-01 07:18 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/FixedAmountVoucher.java
> +    public FixedAmountVoucher(UUID uuid, VoucherType voucherType, double amount) {
DiscountValue VO로 원시값 매핑하면서 유효성 검사를 하도록 수정했습니다.

2023-07-01 07:20 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/dto/Menu.java
> +                    logger.error("Menu Error - {} : {}", menuString, Message.INVALID_MENU);
모든 예외를 Platform까지 전파시켜서 한번에 잡도록 하려고 합니다.
Logger는 최대한 Platform 클래스에서만 사용하도록 해보겠습니다.

2023-07-01 07:44 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/VoucherMap.java
> +    public List<String> getAllVouchers() {
메모리와 파일 두 곳에서 도메인 정보를 가져오기 때문입니다.
<T> 타입 지정자를 사용하지 않고 명확하게 타입 선언을 하기 위해서는 도메인에서 toString을 재정의해서 String 리스트로 가져오는게 더 낫다고 생각했습니다.

2023-07-01 09:28 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/template/CreateMenuTemplate.java
> +public class CreateMenuTemplate {
구조 변경하면서 템플릿 클래스를 모두 제거했습니다
공연히 돌아가는 느낌이 들더라구요

컨트롤러 서비스 레포지토리 구조로 다시 만들고
템플릿에서 하려던 역할은 컨트롤러와 사용자 입력에서 처리하겠습니다

2023-07-01 09:44 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/service/VoucherService.java
> +    private Voucher convertDtoToDomain(VoucherDto voucherDto) {
Dto가 서비스 단에서 노출되는게 안 좋다는 글을 봤습니다

컨트롤러 레벨에서 converter 클래스 이용해서 dto에서 도메인으로 변환하고

서비스에서는 도메인만 이용하도록 수정했습니다

2023-07-01 09:48 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/VoucherRepository.java
> +    Optional<Voucher> insert(Voucher voucher);
코멘트 내용이 맞다고 생각해 서비스와 레포지토리 레벨에서는 도메인 만을 이용하도록 수정했습니다

다만 레포지토리에서 파일로 저장된 바우처 문자열을 바우처 클래스로 변환하고

사용자에게 출력할 때는 다시 문자열로 변환하게 됩니다

이런 연산이 생기는 비용보다 단계별로 통일성 있는 데이터 전달이 더 이득이 많아서 코멘트 주신게 맞나요?

2023-07-01 09:50 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/factory/VoucherFactory.java
> +    Voucher create(double voucherDiscount);
다시 알아보니 할인값이 vo일 필요는 없는것 같습니다

동등성은 만족하지 않는 원시값 포장으로 구현하겠습니다

2023-07-01 10:01 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/factory/PercentVoucherFactory.java
> +                UUID.randomUUID(),
구조 변경하면서 팩토리 클래스를 제거했습니다

사용자 입력이 컨트롤러를 통해 서비스로 전달되기 전 converter클래스 이용해 바우처 객체가 생성되도록 수정했습니다

테스트는 랜덤값 처리가 어려울 것 같아
바우처 생성하는 함수에 uuid를 파라미터로 넣도록 해서 제어할 수 있는 값으로 테스트 가능토록 수정했습니다

2023-07-01 10:01 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/factory/FixedVoucherFactory.java
> +        return new FixedAmountVoucher(
같은 방식으로 처리했습니다

2023-07-01 10:21 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/service/VoucherService.java
> +        if (voucherDto.voucherType().equals(VoucherType.FIXED_AMOUNT)) {
슬랙에 올려주신 내용에 답이 있네요

Enum은 클래스 로드 시 하나의 객체를 만들어 메모리에 적재하고 공유한다고 합니다

== 으로 주소값을 비교한다고하니 동등성 보장이 되는거죠

게다가 컴파일 타임에 타입체크를 하면서 npe도 피하게 해줘서 동등성 비교를 추천한다고 해요

앞으로 enum 자주 쓸텐데 지금 알아서 다행입니다

2023-07-01 10:23 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/service/VoucherService.java
> +            return new FixedVoucherFactory().create(voucherDto.discountValue());
팩토리 클래스 제거,
바우처 도메인 생성 책임 컨트롤러 이전 

이 두 수정으로 해결해보고자 합니다

2023-07-01 10:25 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/factory/VoucherFactory.java
> +public interface VoucherFactory {
팩토리 패턴을 착각했던 것 같아요

수정했습니다

2023-07-01 14:02 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/domain/FixedAmountVoucherTest.java
> +
바우처 할인률이 적용된 결과를 반환하는 메소드입니다.

도메인은 어플리케이션의 주된 데이터입니다.
aop에서 말하는 종단 관심사라고 생각합니다.

해당 로직을 테스트하는 코드를 추가했습니다.

2023-07-01 14:03 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/domain/FixedAmountVoucherTest.java
> +    void 고정값할인바우처생성테스트() {
외국인!

팀원들과 상의해봐야겠습니다.

2023-07-01 14:04 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/repository/voucher/MemoryVoucherRepositoryTest.java
> +    void insert(Voucher voucher) {
테스트 메소드 파라미터로 테스트 소스가 제공된다면 그것도 given이라고 봐도 되나요?

2023-07-01 14:04 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/repository/voucher/MemoryVoucherRepositoryTest.java
> +    void findAll() {
팀원들과 상의해보겠습니다.

2023-07-01 14:05 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/repository/voucher/FileVoucherRepositoryTest.java
> +    void test() {
테스트 실패한 코드입니다 ㅠ

방법을 찾아보겠습니다.

2023-07-01 14:06 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/factory/PercentVoucherFactoryTest.java
> +        var voucher = new PercentVoucherFactory().create(0.1);
구조 변경하면서 중복되는 테스트를 줄여보도록 하겠습니다.

2023-07-01 15:10 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/factory/FixedVoucherFactoryTest.java
> +        var voucher = new FixedVoucherFactory().create(0.1);
팩토리 클래스 제거했습니다.

2023-07-01 15:13 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +            if (getUserMenuInput()) {
반환값과 역할이 서로 맞지 않는 것 같아서 바꿨습니다. 
이제 부울값을 반환하는 것이 아니라, isRunning이라는 전역변수를 이용해서 어플리케이션을 종료하도록 했습니다. 
덕분에 메소드 이름을 branchByMenu 로 표현했습니다.

2023-07-01 15:15 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
템플릿 클래스 제거했습니다.

컨트롤러에서 원하는 서비스를 호출할 수 있도록 구조 변경했습니다.

2023-07-01 15:18 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
템플릿 클래스 제거했습니다.

위 메소드는 역할과 반환값이 서로 어울리지 않는다고 생각해 수정했습니다.

```java
public void run() {
        while (isRunning) {
            try {
                Menu menu = consoleManager.consoleMenu();
                branchByMenu(menu);
            } catch (InvalidDataException exception) {
                logger.error(exception.getMessage(), exception.getCause());
                consoleManager.consoleError(exception);
            }
        }
    }

    private void branchByMenu(Menu menu) {
        switch (menu) {
            case EXIT -> {
                isRunning = false;
            }
            case CREATE -> {
                Voucher voucher = VoucherConverter.convertDtoToVoucher(
                        consoleManager.getVoucherDto(), UUID.randomUUID()
                );
                voucherService.createVoucher(voucher);
            }
            case LIST -> {
                var listMenu = consoleManager.consoleListMenu();
                branchByListMenu(listMenu);
            }
        }
    }
```

2023-07-01 15:18 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/constant/Message.java
> +public record Message() {
에러 메시지 enum 클래스, 출력 메시지 enum 클래스로 분리했습니다.

2023-07-01 15:19 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +    }
메소드명 변경하면서 yield 키워드를 이용하는 코드를 제거했습니다.

2023-07-01 15:21 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    }
잘 못 생각했던 것 같습니다. 

프로그램 내에서 인스턴스화 되어 사용하는 건 구상체인데, 

추상체의 필드를 가져다 쓰려고 하는건 이상한 것 같습니다.

구현체에서 해당 메소드를 구현하도록 수정했습니다.

2023-07-01 15:24 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/Platform.java
> +        this.commandLineTemplate = new CommandLineTemplate(input, output);
템플릿 클래스 제거했습니다. 

CommandLineTemplate 클래스와 비슷한 역할을 하는 클래스 ConsoleManager 클래스를 만들었습니다. 

ConsoleManager 클래스에서는 가급적 
사용자 입력을 Controller에서 사용하는 Dto로 만드는 역할, 
어플리케이션을 통해 연산된 값을 출력하는 역할만 담당하도록 구현했습니다.

2023-07-01 15:32 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    abstract double discountedPrice(long originalPrice);
구현체에서 originalPrice와 DiscountValue 연산 결과를 가지고 유효성 검사를 하도록 했습니다. 

연산 결과가 0 미만이 되는 경우 예외를 던지도록 수정했습니다.

2023-07-01 15:33 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    public VoucherType getVoucherType() {
코멘트 반영했습니다.

생각해보니 서브 클래스에서 하는게 맞겠더라구요

2023-07-01 15:35 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/Voucher.java
> +    UUID voucherId;
원하는 위치에서만 접근이 가능토록 하기 위해 접근지정자를 쓰는 것으로 알고 있습니다. 
OOP 중에서 캡슐화를 지원하는 기능입니다. 
정보은닉 효과를 얻을 수 있습니다.

서브클래스에서 활용할 수 있도록 protected 지정자로 선언했습니다.

2023-07-01 15:38 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/dto/ListMenu.java
> +                    logger.error("Menu Error - {} : {}", input, Message.INVALID_LIST_MENU);
Dto에서의 로그 출력을 모두 제거했습니다.

2023-07-01 15:39 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/dto/VoucherType.java
> +                    logger.error("Menu Error - {} : {}", voucherTypeString, Message.INVALID_VOUCHER_TYPE);
Dto에서의 로그 출력을 모두 제거했습니다.

2023-07-01 15:39 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/io/OutputConsole.java
> +    public void printError(Exception e) {
감사합니다!

2023-07-01 15:39 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/MemoryVoucherRepository.java
> +    public Optional<Voucher> insert(Voucher voucher) {
옵셔널 제거했습니다.

2023-07-01 15:40 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/VoucherMap.java
> +    public List<String> getAllVouchers() {
서비스, 레포지토리에서는 도메인 타입만 가지고 동작할 수 있도록 수정했습니다.

2023-07-01 15:40 UTC, SY97P commented on src/main/resources/application.properties
> +
네 알겠습니다.

2023-07-01 15:41 UTC, SY97P commented on src/main/resources/banner.txt
> +| |  / /___  __  _______/ /_  ___  _____   /   |  ____  ____
Feel So Good

2023-07-01 15:53 UTC, SY97P commented on src/main/resources/voucher_record.txt
> +FIXED_AMOUNT -> id:e8a33fcb-a886-49ea-abd7-c5cc0a5d99e4, discountAmount:1.0
빌드에 추가되지 않도록 수정했습니다.

이번에 gradle 빌드 제외 파일을 지정하는 방법을 배웠네요

2023-07-01 15:53 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/PercentDiscountVoucher.java
> +    public double discountedPrice(long originalPrice) {
수정했습니다.

2023-07-02 04:12 UTC, WooSungHwan approved these changes
세영님 과제하시느라 고생 많으셨습니다!
리뷰 몇자 남겼으니 참고하시고 다음 과제 진행해주세요!

2023-07-02 04:12 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/controller/PlatformController.java
> +        this.isRunning = true;
왠만하면  상태로 컨트롤하지 않고 return으로 상태를 받아와서 처리할 수 있도록 해봅시다. 자칫하다간 웹개발할때 실수해요.

2023-07-02 04:12 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/converter/CustomerConverter.java
> +    }
static이어야만 할까? 한번 판단해보기

2023-07-02 04:12 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/domain/voucher/Voucher.java
> +    protected DiscountValue discountValue;
Voucher가 fixed인지 percent인지는 voucherType에 오로지 의존할 수도 있을 것 같은데 그러면 해당 구현클래스들이 모두 필요없어질 것 같지 않나요?? 여기서 의심을 한번 해보셨으면 좋겠습니다.
예를 들어, discountValue가 voucherType이 fixed이냐 percent에 따라서 아래 discountedPrice 메소드 내에서 구현이 달라질 수 있다는건데 그게 구현 클래스 안에서 이루어지기보다 Voucher 클래스를 추상에서 구현으로 바꾸고 단순 voucherType으로만 제어할 수도 있지 않느냐 이거죠.

2023-07-03 02:48 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/controller/PlatformController.java
> +        this.isRunning = true;
상태를 return 받아서 사용하도록 수정했습니다. 

수정 전 방식인데, 메소드 이름 짓는게 어려워지는 것 같습니다.

2023-07-03 02:55 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/converter/CustomerConverter.java
> +    }
static 메소드로 구현했던 이유입니다. 

1. 해당 클래스에 멤버 변수가 필요 없습니다.
2. 컨버터 클래스를 사용하는 클래스가 3개입니다. 3개의 클래스에서 컨버터 클래스를 DI하게 하는 방식이 비합리적이라고 생각했습니다.

static을 쓸 수록 메모리 효율이 떨어진다고 알고 있지만,
어플리케이션 전반에 걸쳐서 필요한 작업이기 때문에 static 메소드 방식도 나쁘지 않다고 생각합니다.

혹시 이것외에 제가 놓친 부분이 있을까요?

2023-07-03 03:39 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/domain/voucher/Voucher.java
> +    protected DiscountValue discountValue;
오... 맞습니다.

Voucher 클래스를 구현 클래스로 변경했습니다.

2023-07-03 10:18 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/repository/voucher/VoucherRepository.java
> +    Optional<Voucher> insert(Voucher voucher);
레포지토리에서는 도메인에 대한 정보를 가지고 있는게 맞다고 하더라구요.

그리고 DB랑 작업을 한다고 하더라도 도메인 혹은 엔터티로 가져올테니 데이터를 통일하라는 의미보다는, 도메인을 이용해서 처리하는게 맞다고 이해했습니다.

2023-07-04 02:24 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/dto/DiscountValue.java
> +    }
패키지가 dto인지는 고민해보시는게 좋을거같아요.

또한 voucherType이 null이면 어떻게 될까요?

Objects.equals()에 대해서도 알아보세요

2023-07-04 02:24 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/dto/ListMenu.java
> +                .filter(l -> l.listMenuOrdinal.equals(input))
l보다 명확한 이름은 업승ㄹ까요?

2023-07-04 02:27 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/controller/PlatformController.java
> +public class PlatformController implements Runnable {
p2;

컨트롤러가 콘솔을 이용하여 입력을 받아와야 할지, 콘솔로부터 받은 입력을 컨트롤러로 넘겨야 할지 구조에 대해 고민해보세요

2023-07-04 02:27 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/converter/CustomerConverter.java
> +public class CustomerConverter {
p2;

상속받을일이 없다면 final 키워드도 좋습니다.

2023-07-04 02:30 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/repository/customer/CustomerRepository.java
> +        System.out.println(filepath);
p2;

지우셔도 될거같은데요!?

2023-07-04 02:30 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/converter/CustomerConverter.java
> +    }
어제 이야기 했던 부분인듯

2023-07-04 02:30 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/domain/voucher/Voucher.java
> +    protected DiscountValue discountValue;
굿. 방향을 결정했으면 우선 그길로 쭉 가보는 거에요.

2023-07-04 02:31 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/dto/DiscountValue.java
> +    }
왠만하면 equals비교할때 type.equals 하기보다
Objects.equals(type, a);
이렇게 하는 습관 들여보세요. 다 맞는 상황은 아니겠지만 적어도 NPE는 피하자라는 느낌으루다가..

2023-07-04 02:32 UTC, devYSK commented on src/test/java/com/devcourse/springbootbasic/application/converter/VoucherConverterTest.java
> +        var result = VoucherConverter.convertToStringList(vouchers);
p2;

가독성에서 조금 생각해볼 수 있는 내용인데요, 

처음 코드를 펼쳐본다면 테스트 코드가 먼저 보이고, 해당 MethodSource들의 적합한 위치에 대해 고민해보시면 좋을거같아요

2023-07-04 02:33 UTC, devYSK approved these changes

2023-07-04 04:05 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/dto/DiscountValue.java
> +    }
오 알겠습니다. 

어쩐지 코드 포맷팅할때 Objects.equals() 로 자동 포맷되더라구요

2023-07-04 04:50 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/dto/ListMenu.java
> +                .filter(l -> l.listMenuOrdinal.equals(input))
list 로 변경하겠습니다.

2023-07-04 05:14 UTC, merged