[4기 - 문희조] SpringBoot Part1 Weekly Mission 첫 PR입니다
prgrms-be-devcourse/springboot-basic pull request #717
Opened 2023-06-28 20:17 UTC by Hejow

## 📌 과제 설명 
### 애플리케이션 구조
현재 설계하는 구조입니다! 구현을 하면서 변경될 수 있을 것 같습니다.
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/81742959/e99e2145-dc5d-4c78-8181-30840e818177)

## 👩‍💻 요구 사항과 구현 내용 

#### feat: voucher (9ce50a6) 
핵심이 되는 도메인을 구현했습니다.
유효기간과 할인 전략을 두었고,
상태를 boolean 대신 enum으로 관리하려고 합니다.
enum이 훨씬 직관적이고 추가될 확률이 높은 상태를 잘 대응할 수 있는 방법이라고 판단하였습니다.

구현하다보니 자연스럽게 검증이 떠올라서 validator를 구현해주었습니다.
validator를 따로 두고 모든 검증 로직을 몰아주었습니다. 절차지향적이나 응집도가 훨씬 높다고 판단하였습니다.

커스텀 예외나 예외 메시지는 조금 더 고민을 해보고 구현할 생각입니다.

---

#### feat: voucherRepository (598e37f)
저장소를 요구사항에 맞게 `save()`와 `findAll()`을 구현했습니다.
단순히 조회를 한다면 데이터가 수정할 일이 없다고 판단해서 `List.copyOf()`를 사용했습니다.

---

#### chore: change packages (b450f95)
계층형에 맞게끔 패키지 구조를 변경하려고 했습니다.

---

#### feat: VoucherMapper, VoucherType (da2dc2e)
Mapper와 그에 대응하는 DTO, VoucherType을 구현했습니다.
Mapper를 만들고 서비스와 같은 계층에 두었습니다.
의존성이 순환하는 일을 방지하고 DTO 혹은 도메인 객체가 변환의 책임을 가지지 않도록 했습니다.

DTO는 레코드로 구현해서 불변성과 적은 코드양 모두 챙겼습니다.

요청에 맞게끔 mapper가 voucher을 생성할 수 있게 기준점을 VoucherType로 두었습니다.
최대한 단순하게 만들려고 하였습니다.

---

#### feat: VoucherService (a3d0214)
VoucherService를 구현하고, 테스트 코드의 문제점을 발견했습니다.
테스트 코드가 독립적이지 않아 발생했던 문제였고, 저장소를 비우는 메서드를 추가해서 해결했습니다.

---

#### test: add mapperTest (2c197fe)
미처 작성하지 못한 테스트 코드들을 모두 구현했습니다.
`DisplayName()`이 조금 직관적이지 않은 것 같은 곳도 모두 수정했습니다.

## ✅ PR 포인트 & 궁금한 점 
1. 평소에 제가 코드를 짜거나 설계하는 방식 그대로 해보았는데 멘토님들께서 보이시는 문제점이 궁금합니다!
2. 제가 짠 방식에서 서비스가 DTO를 알게되버리는데 이상하다고 생각했는데 멘토님들의 의견이 궁금합니다!
3. 코드의 가독성을 최대한 좋게 가져가려고 했는데 어떤지 궁금합니다!
4. 불필요하거나 의미를 없는 클래스는 최대한 구현을 지양했는데 멘토님들이 생각이 궁금합니다!

구현하지 못한 부분은 최대한 빨리 구현하겠습니다!

2023-06-30 05:27 UTC, Jo-GyuHyeon commented
@Hejow 해당 PR 은 코멘트 보다 구두로 진행 해보면 어떨까 해요. 👍 
CC. @HyoungUkJJang

2023-07-01 03:51 UTC, HyoungUkJJang commented
> @Hejow 해당 PR 은 코멘트 보다 구두로 진행 해보면 어떨까 해요. 👍 CC. @HyoungUkJJang

2023-07-03 20:22 UTC, Hejow commented
@Jo-GyuHyeon, @HyoungUkJJang 말씀해주신 내용을 최대한 녹여보았습니다!
감사합니다!

2023-07-03 20:45 UTC, Hejow commented
@Jo-GyuHyeon, @HyoungUkJJang 말씀해주신 내용을 최대한 녹여보았습니다!
매운 피드백 부탁드리겠습니다!!

2023-07-06 06:54 UTC, Jo-GyuHyeon requested changes
안녕하세요 희조님. 😄 
간단히 코드 리뷰 남겼어요.
피드백 반영후 코멘트로 알려주시면 좋을것 같아요.
고생 많으셨어요. 🙇

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/configuration/AppConfig.java
> +}
MemoryVoucherRepository 를 `@Component` 어노테이션을 이용하여 빈등록 해보면 좋을것 같아요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
wrapping 을 한 이유가 적절한지 고민 해보면 좋을것 같아요. 😄

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +            power = response.power();
응답에 power 는 조금 어색한 감이 있어요.
데이터의 흐름상 이해가 되지만, 네이밍으로 보았을때 어떤 의미일지 생각하게 되는것 같아요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +                voucherService.create((CreateVoucherRequest) request.payload());
ApplicationRequest 파라미터 대신 command 와 payload 를 받는건 어떨까요?

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +    public ApplicationResponse generateResponse(ApplicationRequest request) {
결과로써 응답이 생기는 것은 이해 하지만, 실제로 응답을 만드는 행위는 아닌것 같아요. 네이밍을 고민 해보시면 좋을것 같아요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/domain/VoucherType.java
> +
Voucher 의 inner class 로 옮겨 보는건 어떻게 생각 하시나요?

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/domain/VoucherType.java
> +            return Enum.valueOf(VoucherType.class, input.toUpperCase());
혹시 다른 방식으로 VoucherType 을 찾을 수 있을까요?

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/application/VoucherMapper.java
> +        VoucherType voucherType = request.type();
CreateVoucherRequest 가 아닌 필요한 데이터 타입만 파라미터로 받는건 어떨까요?

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
코드 복잡성을 줄이려고 노력하셨을까요? 
가끔은 코드 라인수를 제한 하게 됨으로써 깔끔해 보일수 있지만, 불필요하게 나누지 않았을까라는 생각도 들어요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +        }
Command 의 종류가 많아지게 고민 할 수 있는 부분이 있을까요? 희조님 의견이 궁금해요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
다른 방식은 없었을까요? 제네릭을 적절하게 사용 되었는지 고민 해보시면 좋을것 같아요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
필요하다면 별도의 Parser 객체를 분리 하는 것은 어떨까요?

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
read 의 오버로딩을 적용 할 수 있지 않을까 생각 해보았어요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +        return createVoucherRequest(stringBuilder.toString());
CreateVoucherRequest 에 필요한 인자를 직접 할당 받는 것은 어떨까 생각 해보았어요.

예) 
```
var type = read(VOUCHER_TYPE_GUIDE);
var discount = read(DISCOUNT_INT_GUIDE);
var expiredAt = read(EXPIRATION_DATE_GUIDE);
```

혹은 한번에 필요한 인자를 다 받을 수도 있을것 같은데 고민 해보시면 좋을것 같아요.

2023-07-06 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +public class Console implements Reader<String>, Writer {
Console 쪽을 고민 해보시면 좋을것 같아요.
제네릭, 메서드, 네이밍 3가지 키워드를 고민 해보셨으면 좋겠어요.

2023-07-10 06:20 UTC, Hejow commented on src/main/java/com/devcourse/voucher/domain/VoucherType.java
> +
[098929f](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/098929f627591ff7ef37933986f19896d3860920) 피드백 반영했습니다.
inner class 형태로 반영하게 되면서 불필요한 클래스와 메서드를 삭제했습니다.

2023-07-10 06:28 UTC, Hejow commented on src/main/java/com/devcourse/voucher/domain/VoucherType.java
> +            return Enum.valueOf(VoucherType.class, input.toUpperCase());
저번 과제 면담 때 말씀해주셨던 내용과 `다른 방식으로 Type을 찾는다`라는 내용이 같은 것인지 모르겠습니다.
`input`이 `null`이라서 NPE이 발생하는 경우라면, 다음과 같이 열거형의 name을 기준으로 찾도록할 것 같습니다!
```
Arrays.stream(Command.values())
    .filter(command -> command.name().equals(input))
    .findFirst()
    .orElseThrow(IllegalArgumentException::new);
```

2023-07-10 06:29 UTC, Hejow commented on src/main/java/com/devcourse/global/configuration/AppConfig.java
> +}
[11d1214](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/11d1214e3a2833f10cf92c09f4ec40187aa6417f)로 피드백 반영하였습니다!

2023-07-10 06:30 UTC, Hejow commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +            power = response.power();
[f921b18](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/f921b18fa20ed57d434e45686d37f33588d35fef)에 피드백 반영하였습니다!
한참을 고민하다가 아이디어가 없어서 자주 사용되는 status로 적용하였는데 이것도 딱히 적절하지 않은 것 같아서 멘토님의 조언을 받아보고 싶습니다!

2023-07-10 06:30 UTC, Hejow commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +                voucherService.create((CreateVoucherRequest) request.payload());
[f921b18](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/f921b18fa20ed57d434e45686d37f33588d35fef)에 피드백 반영하였습니다!

2023-07-10 06:35 UTC, Hejow commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +    public ApplicationResponse generateResponse(ApplicationRequest request) {
[f921b18](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/f921b18fa20ed57d434e45686d37f33588d35fef)에 피드백 반영하였습니다!
여러번 지적을 받은만큼 많이 고민을 해봤는데 도저히 좋은 이름이 떠오르지 않았습니다..
알맞는 서비스를 고른 후 응답을 생산하는 것을 `mapServiceToCreateResponse`라고 그대로 하기에는 무리다고 생각해서 `toResponse`로 마무리 하였습니다.

2023-07-10 06:37 UTC, Hejow commented on src/main/java/com/devcourse/voucher/application/VoucherMapper.java
> +        VoucherType voucherType = request.type();
전체적인 코드에서 필요한 파라미터만 받도록 수정하였습니다!

2023-07-10 06:39 UTC, Hejow commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
[538f939](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/538f939eee91273ab6d2f4fffed8187217e99f9f)로 피드백 반영하였습니다.
console을 하나의 퍼사드라고 생각하고 구현했는데, 저도 고민을 계속 해보니 필요없다고 판단하였습니다.
Console이 I/O에 책임을 담당하되 복잡하지 않도록 많은 코드를 줄여냈습니다.

2023-07-10 06:42 UTC, Hejow commented on src/main/java/com/devcourse/global/console/Console.java
> +        }
`종류가 많아지게 고민할 수 있는 부분`이 어떤 뜻인지 이해하지 못했습니다 🥹
`Command가 많아질 때 어떻게 유연하게 처리할 수 있을까?`를 의미하는 것 같아서 의도를 여쭙기 전에 고민을 해보았습니다.
열거형은 열거형으로 그대로 두고 사용하는 부분에서 switch로 분기처리할 것 같습니다.
단, 변화가 생기면 변화할 수 있는 곳을 한 곳만 위치시키려고 할 것 같습니다.

멘토님의 좋은 의견이 궁금합니다!!!! 🥹

2023-07-10 06:44 UTC, Hejow commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
이 부분을 정말 오래 고민했습니다.
좋은 아이디어가 나오지 않아서 멘토님의 조언을 구해야할 것 같습니다 🥹

2023-07-10 06:47 UTC, Hejow commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
[538f939](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/538f939eee91273ab6d2f4fffed8187217e99f9f)로 피드백 반영했습니다.
모든 parsing을 몰아주었습니다.

2023-07-10 06:47 UTC, Hejow commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
[538f939](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/538f939eee91273ab6d2f4fffed8187217e99f9f)로 피드백 반영했습니다!

2023-07-10 06:51 UTC, Hejow commented on src/main/java/com/devcourse/global/console/Console.java
> +        return createVoucherRequest(stringBuilder.toString());
[538f939](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/538f939eee91273ab6d2f4fffed8187217e99f9f)로 피드백 반영했습니다.

반영하고 나니 다음과 같은 형태가 나옵니다.
```
private CreateVoucherRequest readCreationRequest() {
    String inputType = read(VOUCHER_TYPE_GUIDE);
    Voucher.Type type = parser.parseVoucherType(inputType);

    String inputDiscount = read(DISCOUNT_INT_GUIDE);
    int discount = parser.parseDiscount(inputDiscount);

    String inputExpiredAt = read(EXPIRATION_DATE_GUIDE);
    LocalDateTime expiredAt = parser.parseExpiration(inputExpiredAt);

    return new CreateVoucherRequest(discount, expiredAt, type);
}
```

한번에 다 받자니 과정도 결과도 크게 차이가 없어보였습니다.
그렇다고 이렇게 두자니 중복되는 형태가 보여서 너무 눈엣가시입니다
어떻게 하면 조금 더 깔끔한 형태로 나타낼 수 있을까요? 메서드를 분리해버리는게 더 나은 형태일지 궁금합니다.

2023-07-11 06:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +        return createVoucherRequest(stringBuilder.toString());
변경이 가능한 범위를 최소한으로 두는것이 안전한 방향이라고 생각해요.
기존에 있는 readInformation 는 void 로 리턴 하지만, 데이터에 영향을 미치고 있어요. (사이드 이펙트)
행위에 의한 결과가 있다면 return 을 활용하는 것이 좋을것 같아요.

2023-07-11 06:40 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +            power = response.power();
정답은 없지만 power 보다는 status 가 조금더 자연스럽게 느껴지네요.

2023-07-11 06:42 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +    public ApplicationResponse generateResponse(ApplicationRequest request) {
toResponse 는 관례적으로 Response 로 (모델)변경을 하는 행위인데, 실제로 응답 종류가 Response 일뿐, 행위는 그러지 않은것 같아요.
네이밍에 고민을 해보실 필요가 있는것 같아요.

2023-07-11 06:43 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/domain/VoucherType.java
> +            return Enum.valueOf(VoucherType.class, input.toUpperCase());
넵 좋아요. 꼭 반영을 해야 하는것은 아니네요. 애초에 null 을 어디에서 다룰지 규칙을 정하면 되는 문제라고도 생각해요.

2023-07-11 06:54 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +        }
오타가 있었네요. Command 종류(열거) 가 많아질때 상황을 고려 해라는 의미였어요.
현재 readRequest() 는 모든 Command 를 대상으로 하는것 같아요.
특정 행위에 대한 요청을 제한 하는건 어떨까 싶어요.
하나의 요청에 대한 책임을 가져야 할지? 가질 필요가 없을지? 고민해보면 좋을것 같아요.

2023-07-11 06:55 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +    }
분리 보다는 제네릭 적용이 포인트였던것 같아요. 
분리는 꼭 분리가 필요한 시점, 이유에 대해 스스로 고민해보면 좋을것 같아요.

2023-07-11 07:05 UTC, Jo-GyuHyeon reviewed
간단하게 리뷰 남겨두었어요.
커밋 메시지와 단위가 아쉬움이 많이 남는것 같아요.
코드 레벨 뿐만 아니라 커밋 관련해서도 동료들과 함께 이해 해야한다고 생각하시면 조금더 도움이 될것 같아요.
고생 하셨어요. 🙇

2023-07-11 07:05 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +    }
테스트를 위한 메서드는 지양하는 것이 좋아요.
테스트는 현재 로직을 검증 하기 위한 용도 인데, 역전이 된것 같아요.

2023-07-11 07:05 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +                .toList();
vouchers 를 변수로 빼지 않고 스트림으로 이어 나갈 수 있을것 같아요.

2023-07-11 07:05 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/console/Console.java
> +
```
private <T> void print(Collection<T> input) {
```
이미 해당 기능을 제공하고 있기에 isCollection() 는 과하다고 생각해요.
모든 케이스를 커버하는 것이 마냥 좋다고 생각하지 않아요. 실제로 커버가 되지 않는 부분도 있기에 사용자 책임으로 맡겨야 될때도 있다고 생각해요.

2023-07-11 07:32 UTC, Hejow commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +                .toList();
안 빼두면 과하게 길어질 것 같다고 생각했는데 그게 아니군요! 
수정해두겠습니다!

2023-07-11 07:33 UTC, Hejow commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +    }
사실.. 사용되는 것을 염두하고 다 구현해둔건데 3주차까지 봐도 사용하는 부분이 없더라구요 🥹
과감하게 다 지워버리도록 하겠습니다!

2023-07-12 10:29 UTC, Hejow commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +                .toList();
[c01e6d6](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/c01e6d68994512bc7c1c42aa435d181cb2f07649)로 피드백 반영하였습니다!

2023-07-12 10:30 UTC, Hejow commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +    }
[c01e6d6](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/c01e6d68994512bc7c1c42aa435d181cb2f07649)로 피드백 반영하였습니다!

2023-07-12 10:31 UTC, Hejow commented on src/main/java/com/devcourse/global/console/Console.java
> +
[448ea8d](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/448ea8da6f6394977e302242daa4f2f71cd0a123)로 피드백 반영하였습니다.

제가 생각해도 그렇게 활용도가 높지 않은데 굳이 하나에 몰릴 필요가 없다고 판단하였고,
제네릭을 제네릭 답게 못 쓰면서 억지로 쓴 것 같아서 수정하였습니다.
여기를 수정하고보니 컨트롤러 쪽에서도 변화가 필요할 것 같아서 사용자 책임에 맞게 사용하도록 수정하였습니다!

2023-07-12 10:32 UTC, Hejow commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +    public ApplicationResponse generateResponse(ApplicationRequest request) {
[448ea8d](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/448ea8da6f6394977e302242daa4f2f71cd0a123)로 피드백 반영하였습니다.
굳이 필요한 메서드인가? 그리고 굳이 파라미터로 넘겨줘야하나? 판단하면서
DTO를 제거하고 해당 메서드를 없앴습니다.

2023-07-12 10:33 UTC, Hejow commented on src/main/java/com/devcourse/voucher/presentation/VoucherController.java
> +                voucherService.create((CreateVoucherRequest) request.payload());
[448ea8d](https://github.com/prgrms-be-devcourse/springboot-basic/pull/717/commits/448ea8da6f6394977e302242daa4f2f71cd0a123)로 피드백 반영하였습니다.

DTO를 삭제하고 컨트롤러 메서드를 수정하면서 타입캐스팅을 없애버렸습니다!
오히려 코드가 전보다 깔끔해진 것 같습니다 😋

2023-07-13 07:49 UTC, Jo-GyuHyeon approved these changes
고생 많으셨어요. 🙇 
일정상 심화 과정은 생략하고 위클리 2 미션으로 빠르게 진행 하는것으로 제안 드리고 싶어요.
네이밍, 커밋 단위, 메시지가 아쉬움이 많이 남아요.
간단하게 고민 해보시면 좋을것 같은 코멘트를 하나 남겨 두었어요.
이번 미션은 여기서 마무리 하고 어푸 드릴게요.
위클리 2 화이팅!

2023-07-13 07:49 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +        validateRequest(request);
요청에 대한 책임은 어디에 둘지 고민 해보시는 것도 좋을것 같아요.

2023-07-13 08:15 UTC, Hejow commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +        validateRequest(request);
멘토님 부족한 멘티의 코드 보신다고 너무 고생 많으셨습니다!!
다음 미션2에서는 말씀해주신 부분 잘 다듬어 보겠습니다!

이 피드백을 보고 궁금한 점이 생겼습니다.
말씀하시는 요청이 `검증에 대한 요청`인지 `생성에 대한 요청`인지 아니면 모두인지 잘 이해가 가지 않습니다🥹

2023-07-13 09:07 UTC, merged