[4기 - 박상민] SpringBoot Part1 Weekly Mission 두 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #725
Opened 2023-06-29 14:56 UTC by smart-sangmin

## 📌 과제 설명 
![Spring-basic drawio](https://github.com/prgrms-be-devcourse/springboot-basic/assets/70051888/1d5127a1-5d60-493d-835a-449ae6fb1ea6)

- [x] 바우처 생성 로직
- [x] 바우처 조회 로직

## 👩‍💻 요구 사항과 구현 내용 

## ✅ PR 포인트 & 궁금한 점

2023-06-29 15:03 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +    private static final int MAX_AMOUNT = 10_000_000;
[nit]
```suggestion
    private static final int MIN_AMOUNT = 10;
    private static final int MAX_AMOUNT = 10_000_000;
    
    private final int amount;
```
개인적으로 상수, 불변 멤버변수, 변수 순서로  선은 하는 것을 선호합니다.

2023-06-29 15:04 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +    public FixedAmountVoucher(UUID voucherId, String name, Long minimumPriceCondition, LocalDateTime createdDate, LocalDateTime expirationDate, int amount) {
minimumPriceCondition의 타입이 primitive type이 아닌 이유가 있나요?

2023-06-29 15:10 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +
🔪

2023-06-29 15:27 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/service/VoucherService.java
> +        VoucherType voucherType = VoucherType.from(type);
해당 메서드에 책임이 아닌 것 같아 보여요! 적절한 클래스에게 넘겨주시면 좋을 것 같습니다.

2023-06-29 15:28 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/service/VoucherService.java
> +        VoucherType voucherType = VoucherType.from(type);
그리고 type이라는 변수명을 조금 더 구체적으로 적어주세요

2023-06-29 15:41 UTC, dojinyou requested changes
코멘트 확인 부탁 드립니다.

2023-06-29 15:41 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/service/VoucherService.java
> +        VoucherType voucherType = VoucherType.from(type);
그리고 type이라는 변수명을 조금 더 구체적으로 적어주세요

2023-06-29 15:41 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/service/VoucherService.java
> +    public List<Voucher> list() {
Voucher 타입이 컨트롤러까지 노출되어도 될까요? 저는 조금 위험할 수 있다는 생각이 듭니다.

2023-06-29 15:41 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +    void Voucher생성_save_성공() {
`@ParameterizedTest`로 Fix 타입과 Percent 타입을 모두 검증하면 좋을 것 같아요

2023-06-29 15:41 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +        assertThat(all.get(0)).isEqualTo(voucher);
구체적인 객체의 동등성을 체크하는 것이 해당 테스트의 목적에 부합할까요?

2023-06-29 15:41 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/VoucherTypeTest.java
> +        String type = "정률 할인";
이거 하드 코딩 되어 있어서 이 값이 변경될 때 관리 포인트가 될 것 같은데 어떻게 생각하시나요?

2023-06-30 01:50 UTC, seung-hun-h requested changes

2023-06-30 01:50 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepository.java
> +        return List.copyOf(storage.values());
👍

2023-06-30 01:50 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +            default -> throw new IllegalArgumentException("잘못된 쿠폰 종류 입력");
입력된 VoucherType이 무엇인지 알려주면 좋을 것 같아요~

2023-06-30 01:50 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +
이 부분은 VoucherFactory를 유틸 클래스로 만드셔서, 인스턴스화 그리고 상속을 막으려고 작성하신 것 같네요

2023-06-30 01:50 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +    public static Voucher from(VoucherType voucherType, String name, Long minimumPriceCondition, LocalDateTime createdDate, LocalDateTime expirationDate, int discount) {
메서드 파라미터가 많아서 클래스로 묶어도 좋을 것 같아요

2023-06-30 01:50 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherRepository.java
> +    void deleteAll();
메서드가 조금 위험해 보이네요. 테스트만을 위한 것이라면 다른 방법을 생각해보시면 좋을 것 같아요

2023-06-30 01:50 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherType.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 쿠폰 유형"));
어떤 type이 입력되었는지 보여주면 좋겠네요

2023-06-30 01:50 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherType.java
> +                .filter(o -> type.equals(o.voucherType))
`o` 말고 의미있는 이름을 부여해주세요

2023-07-01 08:52 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +    public FixedAmountVoucher(UUID voucherId, String name, Long minimumPriceCondition, LocalDateTime createdDate, LocalDateTime expirationDate, int amount) {
최소 금액이 없는 경우도 있기 때문에 minimumPriceCondition은 입력이 안 들어수 있다 생각해서 Long으로 했습니다.

2023-07-01 15:54 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/service/VoucherService.java
> +        VoucherType voucherType = VoucherType.from(type);
type -> voucherType 로 변수명 변경하긴 했는데

"Voucher"Service 메서드이기 때문에 voucherType 라는 이름을 염두해두고 저에게 말씀하신 건 아닐 것 같은데, 구체적인 변수명이 뭐가 있을까요...?

2023-07-02 05:28 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +    void Voucher생성_save_성공() {
Voucher class를 생성하는 걸 알리기 위해, save 라는 메서드를 테스트 한다는 걸 알리기 위해 혼용해서 사용했습니다.

2023-07-04 20:51 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +    private static final int MAX_AMOUNT = 10_000_000;
`[5342e6c](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/5342e6c313a4713573e43bb6e4d68b7ac581dcb9)`

2023-07-04 20:52 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
> +        this(voucherId, name, 0L, createdDate, expirationDate, amount);
상수 위치 변경 및 매직넘버, 예외 메세지 상수로 변경 했습니다.

[`5342e6c`](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/5342e6c313a4713573e43bb6e4d68b7ac581dcb9)

2023-07-04 20:53 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherType.java
> +    private final String voucherType;
RATE -> PERCENT로 변경했습니다.

[`c2ad9b7`](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/c2ad9b77d8018f4af986636fb529fe48dbbdb0c4)

2023-07-04 20:53 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +            case RATE -> {
변경했습니다.

[`d33b329`](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/d33b3295cbc1061b5d712b56dbca19745518b03c)

2023-07-04 20:55 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +                if (minimumPriceCondition == null || minimumPriceCondition == 0) {
변경했습니다.

[d33b329](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/d33b3295cbc1061b5d712b56dbca19745518b03c)

2023-07-04 20:55 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +    public static Voucher from(VoucherType voucherType, String name, Long minimumPriceCondition, LocalDateTime createdDate, LocalDateTime expirationDate, int discount) {
변경했습니다.

[d33b329](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/d33b3295cbc1061b5d712b56dbca19745518b03c)

2023-07-04 20:56 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/service/VoucherFactory.java
> +            default -> throw new IllegalArgumentException("잘못된 쿠폰 종류 입력");
변경했습니다.

[`e0ddfd7`](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/e0ddfd74732e30cf51d0dc692ad7267e4b3555da)

2023-07-04 20:58 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/service/VoucherService.java
> +    VoucherRepository voucherRepository;
private final 로 변경했습니다.

 

[`c22aeb1`](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/c22aeb18ef1c2aa38a816b84eccfabddc23093c8)

2023-07-05 05:44 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/service/VoucherService.java
> +    public List<Voucher> list() {
dto 생성했습니다.

[`8ffaa5b`](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/8ffaa5b0fe3bdf45791274089283d0f9d69d6fce)

2023-07-05 05:46 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +        voucherRepository.deleteAll();
몰랐던 Test instance life cycle에 대해 숙지했고 deleteAll 메서드 삭제했습니다.

2023-07-05 05:46 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +        LocalDateTime expirationDate = LocalDateTime.now().plusMonths(3);
변경했습니다

2023-07-05 05:47 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +    void Voucher생성_save_성공() {
EnumSource로 변경해서 Fix, Percent 모두 테스트했습니다

2023-07-05 05:49 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +        assertThat(all.get(0)).isEqualTo(voucher);
변경했습니다

[f086673](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/f08667300ee111cd1248310cc57e3869da80c7f5)

2023-07-05 05:50 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/VoucherTypeTest.java
> +        String type = "정률 할인";
변경했습니다.

[c93810d](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/c93810d04b748f6212855bc6988d3c302b4a6393)

2023-07-05 05:52 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherRepository.java
> +    void deleteAll();
Test instance life cycle에 대해 학습해서 해당 부분 삭제했습니다.

2023-07-05 05:54 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherType.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 쿠폰 유형"));
변경했습니다

[e0ddfd7](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/e0ddfd74732e30cf51d0dc692ad7267e4b3555da)

2023-07-05 05:55 UTC, smart-sangmin commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherType.java
> +                .filter(o -> type.equals(o.voucherType))
enumerate로 변경했습니다.

[4b3def6](https://github.com/prgrms-be-devcourse/springboot-basic/pull/725/commits/4b3def68ddb8d57dd8c73fe5ff7ec9aa867f9962)

2023-07-05 10:34 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherDate.java
> +    }
null 체크도 해주어야 할 것 같네요

2023-07-05 10:49 UTC, seung-hun-h commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherDate.java
> +    }
```suggestion
    public boolean isExpired(LocalDateTime at) {
        return at.isAfter(expirationDate);
    }
```
이게 더 자연스러운 이름인거 같네요

2023-07-05 10:59 UTC, seung-hun-h commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +        };
전체 로직을 보니까 Fixed 바우처, Percent 바우처 생성 로직이 전부 분리되어 있네요. 
이렇게되면 굳이 두 개의 바우처를 추상 클래스를 사용해서 구현할 필요가 있을까요?

2023-07-05 13:04 UTC, smart-sangmin commented on src/test/java/com/programmers/springbootbasic/domain/voucher/MemoryVoucherRepositoryTest.java
> +        };
공통으로 관리되는 부분이 많아서 Voucher class에서 공통된 부분을 통합해서 관리하면 좋을 것 같아서 그렇게 구현했습니다.

상속이 계층구조가 깊어지면 관리가 힘들다는 단점이 있는데 이 경우 계층 구조가 넓어질 순 있지만 깊어지는 경우는 없다고 판단했습니다.

2023-07-06 15:08 UTC, dojinyou commented on src/main/java/com/programmers/springbootbasic/domain/voucher/VoucherDate.java
> +    private final LocalDateTime expirationDate;
타입과 변수명이 조금 다른 것 같은데 어떻게 생각하시나요?

2023-07-06 15:08 UTC, dojinyou commented on src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
> +        VoucherDate voucherDate = new VoucherDate(createdDate, expirationDate);
given으로 올라가도 될 것 같아요

2023-07-11 08:02 UTC, merged