[4기 - 박은지] 3차 바우처 사용자 입출력 구현
prgrms-be-devcourse/springboot-basic pull request #727
Opened 2023-06-29 16:42 UTC by 1o18z

## 📌 과제 설명 
사용자 입/출력 기능 구현했습니다 !

## ✅ 피드백 반영사항  
- [X] 에러메세지 변경
- [X] Discount 분리
- [X] 인라인 반영

## ✅ PR 포인트 & 궁금한 점

2023-06-30 01:47 UTC, dojinyou reviewed
코멘트 남겼습니다!

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +        switch (MenuType.valueOfType(console.readMenu())) {
여러 함수 호출을 한 줄에서 하는 것보다 분리하고 적절한 변수명을 통해 가독성을 높여주세요.

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +            console.printError();
향상된 switch문을 사용해서 fall through이 발생하지 않도록 처리하면 코드가 더 깔끔할 것 같아요

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +              "\nVoucher : " + voucher.getDiscount().getVoucherType() + " , " + voucher.supplyDiscountAmount());
StringFormat을 활용해봐도 좋을 것 같아요

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    System.out.println("Enter the type you want to create");
메세지 변수 처리?

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +  }
퍼블릭인 이유가 있나요?

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/MenuType.java
> +  private static final Map<String, MenuType> MENU_TYPES = new HashMap<>();
이걸 만드시는 이유가 있나요?

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +  }
데이터가 존재하지 않을 경우에는 null값이 반한되나요?

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherFactory.java
> +      case PERCENT -> new Voucher(UUID.randomUUID(), PercentDiscount.of(discountAmount));
타입에 의해서 discount의 결정된다면 Discount의 구현체 결정 로직에만 사용하고 결정된 객체를 이용해서 생성자는 한번만 호출해도 될 거 같아요!

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
> +  private static final Map<String, VoucherType> VOUCHER_TYPES = new HashMap<>();
요것도 동일하게 왜 있어야 할까요?

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/Discount.java
> +  protected final VoucherType voucherType;
이건 구현체마다 다르니까 구현체에서 가지고 있어야 할 것 같아요!

2023-06-30 01:47 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/FixedDiscount.java
> +  public static final int MAXIMUM_VALUE = 10_000;
[nit]
```suggestion
  public static final int MINIMUM_VALUE = 0;
  public static final int MAXIMUM_VALUE = 10_000;
  
  private final int discountAmount;
```
상수, 불변 멤버변수, 멤버변수 순으로 선언하는 걸 선호해요!

2023-06-30 01:59 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/MenuType.java
> +  private static final Map<String, MenuType> MENU_TYPES = new HashMap<>();
map에 저장해 두었다가 꺼내서 사용하면 더 속도가 훨씬 빠르다는 것을 알게 되어 입력받은 타입을 체크할 때 적용했습니다 ! 현재는 타입이 두 종류밖에 있지 않아 성능 상 차이가 별로 없지만, 알아두면 나중에 유용하게 쓰일 것 같아서 사용해 보았습니다 !

2023-06-30 02:02 UTC, seung-hun-h requested changes

2023-06-30 02:02 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/Discount.java
> +  protected final VoucherType voucherType;
그리고 Discount가 VoucherType을 알고 있는게 맞는지 의문이네요
VoucherType -> DiscountType 일 수도 있고, Voucher가 VoucherType을 알고 있어야할 수도 있을 것 같아요.

2023-06-30 09:19 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validator/Validator.java
검증 로직을 분리하는 것을 고민하다가 너무 잘게 나누는 게 아닐까 하고 한 곳에 모아뒀었는데,
멘토님 말씀대로 추가하거나 수정을 하게 되는 경우 여러 검증 로직들이 섞여서 관리가 어려울 것 같아 변경하였습니다 !☀️

2023-06-30 09:31 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +  }
voucherStorage에서 바우처를 가져오기 전에 id를 검증하여 null을 반환하지 않도록 수정하였습니다 !☀️

2023-06-30 10:28 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +              "\nVoucher : " + voucher.getDiscount().getVoucherType() + " , " + voucher.supplyDiscountAmount());
60adb30

2023-06-30 10:28 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +            console.printError();
ba4cb44

2023-06-30 10:29 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +        switch (MenuType.valueOfType(console.readMenu())) {
ba4cb44

2023-06-30 10:30 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    System.out.println("Enter the type you want to create");
60adb30

2023-06-30 10:31 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +  }
private이 적절하다고 생각되어 private으로 변경하였습니다 ! 
063d881

2023-06-30 10:31 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +  }
96a0f73

2023-06-30 10:31 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/VoucherFactory.java
> +      case PERCENT -> new Voucher(UUID.randomUUID(), PercentDiscount.of(discountAmount));
8f46b87

2023-06-30 10:32 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/Discount.java
> +  protected final VoucherType voucherType;
abfb330

2023-06-30 10:32 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/FixedDiscount.java
> +  public static final int MAXIMUM_VALUE = 10_000;
abfb330

2023-06-30 10:33 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +        System.out.println(e.getMessage());
60adb30

2023-06-30 10:33 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
> +    this.discount = discount;
b069c1c

2023-06-30 10:34 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/validator/Validator.java
d9cc140

2023-06-30 11:10 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/MenuType.java
> +  private static final Map<String, MenuType> MENU_TYPES = new HashMap<>();
기존에 `valueOf`를 사용한다면 어떻게 동작하나요?

2023-06-30 11:49 UTC, dojinyou requested changes
구두로 코멘트 드린 `StringFormat`과 `Enum ``valueOf`를 사용해주세요!

2023-06-30 14:36 UTC, seung-hun-h reviewed
은지님 코멘트 남겼습니다~

2023-06-30 14:36 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/FixedDiscount.java
> +  }
price가 discountAmount보다 작으면 어떻게 되나요??

2023-06-30 14:36 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/Discount.java
> +  public abstract int getDiscountAmount();
내부 필드을 조회하기 위해서 메시지를 정의하는 것은 비용이 많이 든다고 생각합니다. 필드가 늘어날때마다 메시지를 추가해주고 구현체들도 모두 메시지를 구현해야할 것 같아요.

2023-06-30 14:36 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/Discount.java
> +public abstract class Discount {
인터페이스를 사용하지 않으시는 이유가 있을까요?

2023-07-04 07:24 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/FixedDiscount.java
> +  }
price가 더 작아서 계산값이 음수가 나올 경우 0 을 반환하도록 수정하였습니다 !

2023-07-04 07:36 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/Discount.java
> +public abstract class Discount {
추상 클래스는 일반 변수를 사용할 수 있다는 점에서 추상 클래스를 사용했습니다 !

2023-07-04 07:44 UTC, merged