[4기 - 윤영운] SpringBoot Part1 Weekly Mission PR입니다
prgrms-be-devcourse/springboot-basic pull request #729
Opened 2023-06-29 19:53 UTC by young970

## 📌 과제 설명
**list 입력**
- 현재까지 생성된 바우처 종류들을 출력합니다.

**create 입력**
- 생성할 바우처 종류를 입력받습니다.
- 입력받은 바우처 종류로 바우처를 생성하고 저장합니다.

**blacklist 입력**
- 블랙리스트들을 조회하여 출력합니다.

## 👩‍💻 요구 사항과 구현 내용
(기본) **바우처 관리 애플리케이션**

- [x]  바우처 관리 Command-line Application을  만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.

  ```bash
  === Voucher Program ===
  Type **exit** to exit the program.
  Type **create** to create a new voucher.
  Type **list** to list all vouchers.
  ```

    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)

- [x]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
- customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.
## ✅ 피드백 반영사항 
- getBean을 통해 실행시키던 어플리케이션을 CommandLineRunner의 run() 메서드를 오버라이딩 하여 실행시키는 방식으로 변경하였습니다.
- Controller에서 조건이 만족할 때 까지 루프를 돌던 방식에서 CommandLineRunner에서 처리하는 방식으로 변경하였습니다.
- Checked Exception 발생 시 Unchecked Exception으로 변환하여 처리하였습니다.
- exception과 errorMessage를 구분하여 관리하는 방식으로 변경하였습니다.
- FileRepository: 어플리케이션 부팅 시 한 번, 어플리케이션 종료 시 한 번 각각 한 번씩만 파일을 읽고 쓰는 방식으로 변경하였습니다.
- 테스트 코드를 작성하였습니다.
- 유틸성 클래스의 생성자를 호출하지 못하게 막았습니다.

## ✅ PR 포인트 & 궁금한 점 
- 현재 Console객체를 유틸성으로 static하게 사용하고 있어 Controller의 테스트 코드를 작성하기 힘듭니다. 이런 상황에서 오로지 테스트를 위해 Console객체를 주입받아 사용하는 방식으로 변경하는것이 올바른 방법인지 궁금합니다.

2023-06-30 05:56 UTC, WooSungHwan requested changes
영운님 과제하시느라 수고많으셨습니다!
좀더 보완할 부분이 있으면 좋을 것 같아서 request changes 드리겠습니다.
전반적으로 Controller 부분에 콘솔의 영향이 있는데요.
패키지를 분리했는데 console 관련 내용이 도메인 패키지에 계속 침투하는걸 확인할 수 있었습니다. 이 부분도 전반적으로 고려를 해보면 좋을것 같습니다. member, voucher 같은 단독 패키지 하위의 내용은 단순히 해당 도메인만 처리하고 일련의 화면로직은 제거해보시는게 좋을 것 같습니다.

자세한 내용은 리뷰내용에 기재해놨으니 참고하시면 될 것 같습니다.

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +    public void run(String... args) throws Exception {
`예외 'java.lang.Exception'은(는) 메서드에서 한 번도 던져지지 않습니다 `
인텔리제이는 위에처럼 말하는군요 ㅎㅎ

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +    public void run(String... args) throws Exception {
아래 보면 Exception catch 하고 있는데 수정해보세용

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +    }
1. 흐름을 핸들링한다.
2. isRunning을 결정한다.

하나의 Menu 기준으로 한 메소드에서 두개의 기능을 처리하려다보니 
결과와 메소드명이 맞지 않음.
메소드 구현내용과 리턴타입이 맞지 않음.
두가지 미스매치가 발생한 것 같습니다.

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/commendLine/ConsoleInput.java
> +                "번호를 선택하세요:");
그냥 println 쓰면 될법한데..!

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherController.java
> +    }
이게 무슨느낌이냐면
Web 과 개발하는 API 기준으로 봤을때,
RequestParam으로 데이터를 받는게 아니라 그냥 어디선가 데이터가 다른 파이프라인으로 꽂히는 느낌이에요.
Controller라면 어디선가 데이터를 받아다가 처리해야하는데
여기에 있는 Controller는 자기가 스스로 데이터를 생성해서 서비스에 전달하는 느낌이라는거죠.
어떻게 개선해야할지 이해가 되셨으면 좋겠습니다 ㅎㅎ

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +    }
이 하나의 로직에서 Optional을 써야하는 이유가 안보입니다.
어떤 결과로써 Optional을 받아서 처리하는 경우라면 이해가 가지만 여기서 만들고 여기서 소비하는데 Optional로 초기화할 필요가 있나 싶습니다.

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +    }
어차피 userVoucher.get()으로 있는지 없는지 예외처리도 하진 않고 있기도 하고요.
오히려 너무 단언하는게 아닌가 싶습니다. 그러느니 타입을 Optional 안에 가둘 필요가 사라지지요

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/util/Loader.java
> +public final class Loader {
이 Loader 클래스는 전반적으로 FileRepository 쪽에서 의존하고 있을 것 같은데 선언은 모두 static으로 되어있네요?
마치 file에서만 쓰일게 아니라 여러군데에서 이걸 쓸거같이 느껴져요.

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/util/Converter.java
> +    }
미사용 메소드인것 같네요~

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/util/ErrorMessage.java
> +}
에러메시지는
- 특정 도메인에서 쓰이는 메시지
- 전역으로 공통적으로 시스템 전반에서 쓰이는 메시지
두가지가 있을텐데 구분해서 패키지안에 적절히 분리해보세요.

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/member/repository/FileMemberRepository.java
> +    }
생성자에서 하지 않은 이유가 있나요?

2023-06-30 05:56 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/member/repository/FileMemberRepository.java
> +    }
여기서 loadFileToMemoryMember 메소드 리턴타입과 storage 의 타입이 일치하지 않는데 방법은 두가지일 것 같아요.
1. Loader의 리턴타입을 Map으로 맞춘다. -> 근데 어차피 List에서 Map으로 변경해줘야할듯.
2. 어차피 List -> Map의 변형이 필요하므로 특정 adapter에서 List -> Map으로 변경해준다.
지금 24번 라인은 어댑터처럼 동작하는데 마치 비즈니스처럼 한줄의 구성코드로  쓰이네요. 이부분 한번 생각해보세용

2023-06-30 07:33 UTC, young970 commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +    }
말씀하신대로 해당 메소드에서 두가지의 기능을 한번에 처리하려다 보니 발생한 문제인거 같습니다.
executeAction() 메서드에서 isRunning을 판단하는 부분을 제거하고 해당 기능을 담당하는 새로운 메서드를 만들어 처리해보도록 하겠습니다!!

2023-06-30 07:39 UTC, young970 commented on src/main/java/org/prgrms/kdt/commendLine/ConsoleInput.java
> +                "번호를 선택하세요:");
println() 메서드를 두 번 호출하기보다 한번의 호출로 처리하는 것이 성능에 더 좋은 영향을 끼칠 것이라 생각하여 초기에System.out.print("1. FixedAmountVoucher 2. PercentDiscountVoucher\n 번호를 선택하세요:");
이런 형태의 코드를 작성하였고, 코드의 가독성을 위해 **번호를 선택하세요:** 이 부분의 코드를 개행 처리하며 인텔리제이에서 자동 변환되어 발생한 코드 형태인거 같습니다.
하지만 말씀하신 println() 사용하는 방식이랑 성능 차이가 미비할 것 같아 그냥 그냥 println()을 써도 될 것 같습니다!!

2023-06-30 07:51 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherController.java
> +    }
말씀하신 내용 이해하였습니다. 
테스트 코드를 작성하는 과정에서도 Controller 부분이 테스트하기 힘들었는데 Controller가 데이터를 파라미터로 받는 방식으로 수정하면 테스트하기에도 용이해질 것 같습니다!!
해당 내용 개선하여 반영하도록 하겠습니다!!

2023-06-30 07:57 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +    }
말씀하신대로 해당 부분은 Optional이 사용될 이유가 없는것 같습니다.
Optional이 만들어진 이유와 올바른 사용법에 대해 깊이 생각하지 않고 단순히 null을 대체하기 위해 코드를 작성한 결과인 것 같습니다...
수정하도록 하겠습니다!!

2023-06-30 07:59 UTC, young970 commented on src/main/java/org/prgrms/kdt/util/Converter.java
> +    }
해당 미사용 메소드 제거하도록 하겠습니다!!

2023-06-30 08:27 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/repository/FileMemberRepository.java
> +    }
초기에 생성자를 통해 load를 시도하였으나 필드의 filePath를 @Value 어노테이션을 통해 주입받는 시점이 FileVoucherRepository 클래스가 스프링에 의해 생성되는 과정보다 늦어, NullPointerException이 발생하는 문제가 있어 @PostConstruct를 사용하는 방식으로 구현하였습니다.
하지만 현재 팀원에게 생성자 파라미터에 @Value 어노테이션을 적용하는 방법을 듣게 되어 생성자를 통해 load를 하는 방식을 적용할 수 있을 것 같습니다!!

2023-06-30 08:30 UTC, young970 commented on src/main/java/org/prgrms/kdt/util/ErrorMessage.java
> +}
말씀하신 내용 고민하여 분리해보도록 하겠습니다!!

2023-06-30 08:44 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/repository/FileMemberRepository.java
> +    }
두번째 내용인 23번, 24번 라인의 내용에 대해선 해당 클래스 필드인 storage를 final 키워드를 통해 불변으로 유지시키고 싶다보니 발생했던 결과물이였습니다. 하지만 위에서 언급한 내용처럼 생성자를 통해 load를 하면 해결될 것으로 생각됩니다!!

2023-06-30 08:59 UTC, young970 commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +    public void run(String... args) throws Exception {
제가 놓친 부분인 것 같습니다... 해당 내용 수정하겠습니다!!

2023-06-30 09:06 UTC, young970 commented on src/main/java/org/prgrms/kdt/util/Loader.java
> +public final class Loader {
FileRepository에서 Loader를 주입 받아 사용하는 방식으로 적용해보겠습니다!!

2023-07-01 05:35 UTC, devYSK commented on src/main/java/org/prgrms/kdt/commendLine/ConsoleInput.java
> +        throw new RuntimeException("생성 안돼!!");
!?

2023-07-01 05:39 UTC, devYSK commented on src/main/java/org/prgrms/kdt/util/Loader.java
> +        }
중복된 Member에 대해서 상관없이 파일로 저장을 의도하신걸까요?

2023-07-01 05:40 UTC, devYSK commented on src/main/java/org/prgrms/kdt/util/Menu.java
> +    private final String menuString;
descripton 등으로도 네이밍을 대체할 수 있을것 같아요

2023-07-01 05:41 UTC, devYSK commented on src/main/java/org/prgrms/kdt/util/Menu.java
> +                .findFirst()
```java
.filter((e) -> e.menuString.equals(str)) 
-> .filter(e -> e.menuString.equals(str))
```
----- 
만약, EMPTY(null)이 추가가 된다면 NPE가 발생할수도 있을것같아요. 
Objects.equals()에 대해 알아보세요

2023-07-01 05:43 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherController.java
> +    }
바우처를 반환해주고, 다른곳에서 출력할 수 있지 않을까요?

API를 사용해주는 웹 환경으로 변화가 되면 이 Controller는 수정할 부분이 많아질거같아요.

2023-07-01 05:44 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/domain/Voucher.java
> +    public abstract double discount(double beforeDiscount);
요구사항이 바뀌어 double타입이 아닌 long이나 Integer로 바뀌면 해당 인터페이스를 구현하는 모든 구현체도 변경의 영향이 있겠네요.

원시값 포장 이라는 키워드로 찾아보시면 좋을것 같습니다.

2023-07-01 05:44 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/domain/Voucher.java
> +    protected final double amount = 20;
왜 amount만 고정이에요?

2023-07-01 05:46 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/domain/PercentDiscountVoucher.java
> +        return VoucherType.PERCENT.getName();
VoucherType.PERCENT enum을 이렇게 사용하면 유연함이 떨어질수도 있을거같아요. 

VoucherType.PERCENT는 PercentDiscountVoucher는 '속성' 혹은 '상태' 인거같아요 
다른 Voucher가 생성될때마다 매번 이렇게 작성해야 할까요?

2023-07-01 06:26 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/repository/FileVoucherRepository.java
> +        Loader.saveMemoryVoucherToFile(storage, filePath);
흑구님과 의견이 동일합니다.

2023-07-01 06:29 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/repository/MemoryVoucherRepository.java
> +    }
List.copyOf는 Immutable Collection으로 생성해줘요. 

의도하신걸까요?

2023-07-01 06:29 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +    }
```java
public List<Voucher> findAll() {
    return voucherRepository.findAll();
}
```

2023-07-01 06:30 UTC, devYSK commented on src/main/resources/application.properties
> +
사용하지 않는 파일은 지워주세요

2023-07-01 06:32 UTC, devYSK commented on src/main/resources/TestVoucher.csv
> +228c0110-7b65-492f-b605-07003fe7433b,FixedAmountVoucher,20
이 파일들은 데이터를 저장하는 파일이잖아요? 

1. 애플리케이션이 build되면 어떤 파일들이 만들어질 수 있을까요? 
2. 애플리케이션이 build 되면 이 csv 파일들은 어떻게 될까요? 
3. 어떻게 접근할 수 있을까요?

2023-07-01 06:32 UTC, devYSK commented on src/main/resources/Voucher.csv
> +ecd2418f-279e-40e8-8c07-c184dad2d5bd,PercentDiscountVoucher,20
이 파일들은 데이터를 저장하는 파일이잖아요? 

1. 애플리케이션이 build되면 어떤 파일들이 만들어질 수 있을까요? 
2. 애플리케이션이 build 되면 이 csv 파일들은 어떻게 될까요? 
3. 어떻게 접근할 수 있을까요?

2023-07-01 06:32 UTC, devYSK commented on src/main/resources/customer_blacklist.csv
> +a5b5a660-cb51-4445-9c6b-84c7a9e2131b,James
이 파일들은 데이터를 저장하는 파일이잖아요? 

1. 애플리케이션이 build되면 어떤 파일들이 만들어질 수 있을까요? 
2. 애플리케이션이 build 되면 이 csv 파일들은 어떻게 될까요? 
3. 어떻게 접근할 수 있을까요?

2023-07-01 06:32 UTC, devYSK commented on src/main/resources/test_customer_blacklist.csv
> +0d7837a8-be24-4c52-b559-c9b55560f09a,hoho
이 파일들은 데이터를 저장하는 파일이잖아요? 

1. 애플리케이션이 build되면 어떤 파일들이 만들어질 수 있을까요? 
2. 애플리케이션이 build 되면 이 csv 파일들은 어떻게 될까요? 
3. 어떻게 접근할 수 있을까요?

2023-07-01 06:33 UTC, devYSK commented on src/main/resources/logback.xml
> +    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
이 코드는 어떤것을 의미하나요?

2023-07-01 06:34 UTC, devYSK commented on src/test/java/org/prgrms/kdt/member/repository/FileMemberRepositoryTest.java
> +
fileWrite()가 정상적으로 동작하나요?

2023-07-01 06:34 UTC, devYSK commented on src/test/java/org/prgrms/kdt/util/ConverterTest.java
> +    @Test
`@dDisplayName` 이라는 어노테이션이 있습니다.

2023-07-01 06:35 UTC, devYSK commented on src/test/java/org/prgrms/kdt/util/ConverterTest.java
> +import static org.hamcrest.Matchers.is;
org.junit.jupiter.assertions 
vs
org.assertj.core.api.assertions
vs 
org.hamcrest.MatcherAssert

많은 검증 도구들에 대해 알아보세요

2023-07-01 06:36 UTC, devYSK commented on src/test/java/org/prgrms/kdt/util/LoaderTest.java
> +    public String TestBlackListFilePath = "src/main/resources/test_customer_blacklist.csv";
왜 public 인가요? 이유가 궁금합니다.

2023-07-01 06:37 UTC, devYSK commented on src/test/java/org/prgrms/kdt/util/LoaderTest.java
> +        assertThat(foundMembers.size(), is(2));
`@MothodSouce`를 사용해 복잡한 인수들을 파라미터로 넘길 수 있습니다

given부가 조금 깔끔해질 수 있지 않을까요?

2023-07-01 06:38 UTC, devYSK commented on src/test/java/org/prgrms/kdt/util/LoaderTest.java
> +    public String TestBlackListFilePath = "src/main/resources/test_customer_blacklist.csv";
테스트 시 나오는 파일들이, Production 코드 영역에 저장되어야할까요?

2023-07-01 06:39 UTC, devYSK commented on src/test/java/org/prgrms/kdt/voucher/repository/FileVoucherRepositoryTest.java
> +    public FileVoucherRepository fileVoucherRepository;
public?

2023-07-01 06:39 UTC, devYSK commented on src/test/java/org/prgrms/kdt/voucher/repository/FileVoucherRepositoryTest.java
> +    void findAll() {
메서드 명 통일성을 맞춰주세요~

2023-07-01 06:41 UTC, devYSK commented on src/test/java/org/prgrms/kdt/voucher/service/VoucherServiceTest.java
> +        when(mockVoucherRepository.insert(fixedAmountVoucher)).thenReturn(fixedAmountVoucher);
vs BDDMokcito.given()

2023-07-01 06:47 UTC, devYSK reviewed
안녕하세요 영운님 과제하시느냐 고생 많으셨습니다.


\- 현재 Console객체를 유틸성으로 static하게 사용하고 있어 Controller의 테스트 코드를 작성하기 힘듭니다. 이런 상황에서 서비스 로직이 아닌 Controller의 테스트 코드를 위해 Console객체를 주입받아 사용하는 방식으로 변경하는 것이 올바른 방법인지 궁금합니다.

Console 객체가 static 이여 햐는지 다시 고민해보시면 좋을거같아요
말씀하신대로 static은 테스트 하기 어려움이 있어요. static 하지 않아도 구현할 수 있습니다.

또한 Controller가 어떤 역할을 하고 어떤 책임이 있는지 다시한번 공부해보시면 좋을거같아요.
`Controller가 콘솔을 가져야 할까?`
`콘솔은 무슨 역햘을 할까? 입출력하는 일을 하네? `
`컨트롤러는 어떤 일을 하지? `
`그러면 이 둘의 관계는? `

테스트 코드를 위해 프로덕션 코드의 구조를 바꾸는것은 올바르지 않다고 생각합니다. 
실제 동작하는 코드는 프로덕션 코드입니다. 테스트 코드를 위해 프로덕션 코드를 바꾸어야 한다면, 설계가 잘못되었을 수도 있습니다.

2023-07-01 15:47 UTC, young970 commented on src/main/java/org/prgrms/kdt/util/Loader.java
> +        }
의도한 것은 아닙니다. 다만 현재 요구사항에 BlackList를 추가적으로 insert하는 요구사항은 없어 BlackListMember들의 중복에 대해선 크게 신경쓰지 않았습니다...

2023-07-01 15:50 UTC, young970 commented on src/main/java/org/prgrms/kdt/util/Menu.java
> +    private final String menuString;
말씀해주신 descripton이 통상적으로 쓰이는 네이밍으로 훨씬 가독성이 좋을 것 같습니다!!
네이밍 수정하도록 하겠습니다!!

2023-07-01 15:54 UTC, young970 commented on src/main/java/org/prgrms/kdt/util/Menu.java
> +                .findFirst()
말씀해주신대로 기존의 로직으론 EMPTY(null)이 추가되면 NPE가 발생하는 것을 테스트를 통해 확인하였습니다.
Objects.equals()에 대해 알아보고 수정하도록 하겠습니다!!

2023-07-01 16:00 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherController.java
> +    }
맞습니다. 기존의 Controller의 로직은 web환경의 Controller에는 적용되기 힘든 로직이므로 수정이 필요하다고 생각합니다!!
입출력에 해당하는 의존성을 상위 레이어로 넘겨 파라미터와 리턴값을 통해 데이터를 넘겨주는 방식으로 수정해보겠습니다!!

2023-07-01 16:01 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/domain/Voucher.java
> +    public abstract double discount(double beforeDiscount);
언급해주신 키워드를 통해 공부 후 적용해보도록 하겠습니다!!

2023-07-01 16:06 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/domain/Voucher.java
> +    protected final double amount = 20;
voucherId에 final키워드를 빼먹었습니다... 해당 내용 바로 수정하도록 하겠습니다

2023-07-01 16:12 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/domain/PercentDiscountVoucher.java
> +        return VoucherType.PERCENT.getName();
말씀하신 대로 VoucherType을 필드의 속성으로 사용하는 방식이 좀 더 효과적일 것 같습니다.
해당 내용 수정하겠습니다!!

2023-07-01 16:18 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/repository/MemoryVoucherRepository.java
> +    }
네 맞습니다!! 
필드의 Collection객체를 그대로 반환해줄 시 외부에서 해당 Collection에 변화를 주게 되면 원본의 Collection객체에도 영향을 줄 수 있으므로 List.copyOf를 이용하였습니다.

2023-07-01 16:20 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
> +    }
수정하겠습니다!!

2023-07-01 16:21 UTC, young970 commented on src/main/resources/application.properties
> +
지우도록 하겠습니다!!

2023-07-01 16:59 UTC, young970 commented on src/main/resources/logback.xml
> +    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
스프링부트에서 지원하는 디폴트 로그설정파일을 불러오는 것이라고 이해하여
스프링부트에서 디폴트로 지원하는 console출력 양식을 사용하기 위해 해당 내용을 추가하여 사용하였습니다.

2023-07-01 17:11 UTC, young970 commented on src/test/java/org/prgrms/kdt/member/repository/FileMemberRepositoryTest.java
> +
스프링부트 애플리케이션에선 동작하지만, 
제 테스트코드 환경에선 스프링의 컨테이너 기술을 사용하고 있지 않기 때문에 테스트에선 fileWrite()는 동작하지 않습니다.
하지만 fileWrite()는 Loder에 전적으로 의존하는 부분이므로 분리하여 테스트해야 한다고 생각하여, LoderTest에서 따로 
테스트 코드를 작성하였습니다.

2023-07-01 17:12 UTC, young970 commented on src/test/java/org/prgrms/kdt/util/ConverterTest.java
> +    @Test
해당 어노테이션을 적용해보겠습니다!!

2023-07-01 17:17 UTC, young970 commented on src/test/java/org/prgrms/kdt/util/ConverterTest.java
> +import static org.hamcrest.Matchers.is;
강의에서 해리님이 hamcrest라이브러리를 사용하여 테스트를 작성해보라고 하셔서 해당 라이브러리로 테스트를 작성하였으나, 말씀해주신 도구들도 알아보겠습니다!!!

2023-07-01 17:50 UTC, young970 commented on src/test/java/org/prgrms/kdt/util/LoaderTest.java
> +    public String TestBlackListFilePath = "src/main/resources/test_customer_blacklist.csv";
습관적으로 public으로 해당 필드를 작성했던 것 같습니다...
테스트용 파일들은 Production 코드 영역에 저장되면 안될 것 같습니다. 수정하도록 하겠습니다!!

2023-07-01 17:50 UTC, young970 commented on src/test/java/org/prgrms/kdt/util/LoaderTest.java
> +        assertThat(foundMembers.size(), is(2));
해당 어노테이션을 알아보고 적용해보도록 하겠습니다!!

2023-07-01 17:51 UTC, young970 commented on src/test/java/org/prgrms/kdt/voucher/repository/FileVoucherRepositoryTest.java
> +    void findAll() {
맞추도록 하겠습니다!!

2023-07-01 17:52 UTC, young970 commented on src/test/java/org/prgrms/kdt/voucher/service/VoucherServiceTest.java
> +        when(mockVoucherRepository.insert(fixedAmountVoucher)).thenReturn(fixedAmountVoucher);
좋은 키워드 감사합니다!!

2023-07-04 02:35 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/commendLine/ConsoleInput.java
> +                "번호를 선택하세요:");
sysout 찍는 게 목적인 프로그램에 성능을 이야기하긴 좀 과한부분이 있으니 가볍게 생각하고 넘기되 다른 부분에 집중하는게 좋죠!
수고하셨습니다!

2023-07-08 18:31 UTC, merged