[4기 - 안재영] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다
prgrms-be-devcourse/springboot-basic pull request #730
Opened 2023-06-30 06:39 UTC by JaeyoungAhn

## 📌 과제 설명 
- SpringBoot Part1 Weekly Mission(~6/30)
    
    (기본) **바우처 관리 애플리케이션**
    
    - [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
    - [x]  바우처 관리 Command-line Application을  만들어본다.
        - 참고: https://dzone.com/articles/interactive-console-applications-in-java
        - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
        - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
        
        ```bash
        === Voucher Program ===
        Type **exit** to exit the program.
        Type **create** to create a new voucher.
        Type **list** to list all vouchers.
        ```
        
        - [x]  create / list 커맨드를 지원한다.
            - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
            - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
            - this바우처 정보를 매모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
    - [x]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
    - [x]  실행가능한 `jar` 파일을 생성한다.
    
    (심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능
    
    - [x]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
        - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
    - [x]  고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
    - [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
[init : 프로젝트 생성 및 구조 설계](https://github.com/prgrms-be-devcourse/springboot-basic/commit/05b7c60ce2db35000185ad1f820430320868919b)

[feat : ConsoleService 기능 구현](https://github.com/prgrms-be-devcourse/springboot-basic/commit/504f8ffa48c2c20bae3dca1ec0a2e78ca069c71a)

[feat : VoucherService 기능 구현](https://github.com/prgrms-be-devcourse/springboot-basic/commit/ed61d39edaa4dec4570b554f2359a408cebb0bd6)

[feat : logging 및 jar 파일 배포](https://github.com/prgrms-be-devcourse/springboot-basic/commit/1b910923737839455df52a480a0ecdb757c9eec4)

[refactor : MVC 및 3-tier 아키텍쳐로 리팩토링](https://github.com/prgrms-be-devcourse/springboot-basic/commit/d91d851741d4a9316af96ef6d9eaa5abdfe957fa)

[refactor : database 레이어 추가 및 repository 통합](https://github.com/prgrms-be-devcourse/springboot-basic/commit/3bcad4002417adf86746285cc8218fbe6ef0bddd)

[feat : 파일 관리 데이터베이스, 블랙리스트 관리, YAML 활용 추가](https://github.com/prgrms-be-devcourse/springboot-basic/commit/aa4c7046ba9cf3e8ff8cad1230b685833ca1f36d)

[refactor : voucher 생성 메소드를 하나로 합치기](https://github.com/prgrms-be-devcourse/springboot-basic/commit/d9067fa44e6404868016e33900ab3600a2a69791)

[refactor : yaml 주입 방식 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/c4b0db0811b8b3b48e09bdf2b70df4ec4a106e6c)

[refactor : Enum class 용도에 따른 분리](https://github.com/prgrms-be-devcourse/springboot-basic/commit/27601d3aba344a1b11874c8cc175dd11b3e1d7a8)

[refactor : 에러 처리, 로깅, 이름 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/f4cf12262688d3ffc893f850998bf2613476527d)

[refactor : Console과 Writer 역할 분리 및 가독성 향상](https://github.com/prgrms-be-devcourse/springboot-basic/commit/2f63e47387ccc1a86c8e5446168486a5f85250bb)

[feat : 커스텀 익셉션 클래스 생성](https://github.com/prgrms-be-devcourse/springboot-basic/commit/1cadca3cd04b3d4e4f211d2387810d93873da989)

[test : 바우처 테스트 코드 작성](https://github.com/prgrms-be-devcourse/springboot-basic/commit/f8e1cc8d4f0415ce49862307bd9b2eac3a5dc1bc)
## ✅ 피드백 반영사항  
- Console에서 Writer의 책임을 분리시키기
- yaml properties를 setting class로 분리한 후 annotation을 이용하여 주입
- web 환경에서 post로 파라미터로 받았다고 생각하고 하나의 메소드로 통일
- cache 대신 범용적인 용어 사용하기
- 파생 파일의 디렉토리 분리하기
- if else가 깊은 곳 가독성 향상을 위해 리팩토링 하기
- 예외 처리 하기
- Enum class 용도에 따른 분리
- 테스트 코드 작성 (진행 중...)
## ✅ PR 포인트 & 궁금한 점 
피드백 반영하는 것에 생각보다 많은 시간이 걸려서 테스트 코드는 아직 완전히 작성하지 못했습니다.
저 때문에 멘토님의 일정에 차질이 생기지 않을까 싶어 일단 PR를 하는 것이 좋지 않을까 생각했습니다.
테스트 코드는 작성 중에 있으며 지속적으로 commit하여 PR 업데이트 하겠습니다.
피드백 주신 부분을 수정하려고 노력하였는데 잘 되었는지 궁금합니다.
그리고 전체적인 관점에서 추가적으로 고려해야할 부분들이 있을지 궁금합니다.

2023-07-01 02:51 UTC, WooSungHwan requested changes
재영님 과제하시느라 수고 많으셨습니다.
리뷰 몇자 남겼으니 확인부탁드립니다~

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/VoucherApplication.java
> +    }
여기서 스프링부트를 켜는 run과

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/VoucherApplication.java
> +    }
이 두가지 run 은 충분히 분리될 수 있지 않을까요?!

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +    private final VoucherProperties voucherProperties;
전반적으로 이 두 클래스가 여기에서 과연 주입받아야만 했는가가 궁금합니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +    private final InputHandler inputHandler = new InputHandler();
이 두 클래스는 과연 new를 찍어야만 했는가가 궁금합니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +            }
해당 로직을 따로 private으로 두거나 depth를 아껴봐야 할것같습니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +    private void selectVoucher() {
제가 말한것 중에 클래스로 따로 뺄만한 요소들을 정리해드렸었습니다.
1. logic (object가 데이터를 저리하는 곳)
2. data (object의 처리 대상)
3. object (data를 처리하는 행위가 있는 곳 -> 주로 명사화)

이 세가지중 한군데로 추상화해서 빼낼 수 있는 부분이 이 메소드 말고 여러군데가 있을 것 같습니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +    private void voucherCreation(ConsoleViewVoucherCreationEnum consoleViewVoucherCreationEnum) throws WrongRangeFormatException {
해당 메소드도 마찬가지로 바우처를 만드는 로직이 담겨있으므로 따로 분리를 해보시기 바랍니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/setting/VoucherProperties.java
> +public class VoucherProperties {
해당 클래스가 정말로 필요한 클래스에 주입해서 쓰시기 바랍니다.
해당 클래스의 속성으로 어떤 로직제어가 분명히 필요한 장소는 어찌됐든 ConsoleView는 아닙니다. 얘는 뭔가 파라미터로 전달해서 처리할 녀석은 아닙니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/setting/BlacklistProperties.java
> +public class BlacklistProperties {
해당 클래스가 정말로 필요한 클래스에 주입해서 쓰시기 바랍니다.
해당 클래스의 속성으로 어떤 로직제어가 분명히 필요한 장소는 어찌됐든 ConsoleView는 아닙니다. 얘는 뭔가 파라미터로 전달해서 처리할 녀석은 아닙니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +            UUID uuid = voucherController.createVoucher(value, consoleViewVoucherCreationEnum);
해당 부분은 long, enum타입을 어딘가에다 담아서 전달해보세요. 여기만 하지 마시고 전반적으로 모든 부분을 그렇게 진행해보세요.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/service/VoucherService.java
> +        throw re;
if문 보다는 switch문이 더 적합한 코드인 것 같습니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/BlacklistRepository.java
> +@Repository
레포지토리 어노테이션을 쓴 이유가 있을까요?
해당 어노테이션이 적용된다면 무슨 행위가 있는지 알려주세요~

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/model/PercentDiscountVoucher.java
> +    private final long percent;
요 percent는 어디 외부에 노출마시고
discount에서 할인하는 로직에만 쓰여야합니다. 지금 너무 많은곳에 노출되어 있습니다. 이 percent가 다른 곳에 노출되지 않기 위해서는 어떻게 진행되어야할지 고민해봅시다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/model/FixedAmountVoucher.java
> +    private final long amount;
이 amount도 percent와 동일합니다. 어디 노출되면 안됩니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/util/InputHandler.java
> +public class InputHandler {
이름을 다시 지어보시는게 어떤가요..?ㅠㅠ

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/exception/WrongRangeFormatException.java
> +}
해당 예외 클래스 RuntimeException 을 상속받은 예외인데 throws 처리가 너무 많이 되어있습니다. checkedException과  UncheckedException을 처리할 때의 상황을 잘 살펴보시기 바랍니다.

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleViewOptionEnum.java
> +    UNEXPECTED_INPUT;
이거 정의가 반드시 필요한지??

2023-07-01 02:51 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/view/ConsoleViewVoucherCreationEnum.java
> +    UNEXPECTED_INPUT;
이거 정의가 반드시 필요한지??

2023-07-01 02:53 UTC, WooSungHwan commented
추가적으로 재영님은 다른분들과의 코드리뷰가 많이 필요해보입니다. 여러분들끼리의 리뷰를 많이 강조했었던건 개인마다 나가는 리뷰가 매우 다르고 개인마다 주목하는 리뷰내용이 다르기 때문에 다른 동료의 시선으로 재영님의 코드를 많이들 봐주셔야 합니다. 그러한 상황에 많이 노출되어야 재영님도 이 데브코스를 통해서 얻어가실 수 있는 부분이 확실히 있으니 저의 리뷰를 토대로 뭔가 결과물이 완성된다면 반드시 다른분들의 리뷰도 꼭 받아오셨으면 좋겠습니다.

2023-07-01 07:29 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/VoucherApplication.java
> +    }
분리하겠습니다!!

2023-07-01 07:31 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +    private final VoucherProperties voucherProperties;
해당 속성을 사용하는 당사자가 있는 레이어까지 이동시켜보겠습니다!!

2023-07-01 07:34 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +    private final InputHandler inputHandler = new InputHandler();
확장이 되어 동일한 인터페이스의 다른 빈들이 상속될 수 있는 것을 고려한다면 주입을 받는 것이 나을 것 같습니다!

2023-07-01 07:37 UTC, devYSK commented on src/main/csv/blacklist.csv
> +"ec40d957-f4fe-4830-ae76-d554595ea074","mercy"
application이 build되면 어떤 파일들이 포함되며 어떤 파일들이 만들어질까요?

데이터를 저장하는 파일의 위치가 이곳은 부적절해 보입니다.

2023-07-01 07:38 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/database/FileBlacklistDatabase.java
> +
개행 하나만 해도 될거같아요

2023-07-01 07:38 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/database/FileBlacklistDatabase.java
> +            reader.readNext();  // Skip header
주석 대신 메소드로 빼보는것은 어떨까요

2023-07-01 07:39 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/database/FileVoucherDatabase.java
> +            if(voucher instanceof FixedAmountVoucher fixedAmountVoucher) {
```java
if ()
```

2023-07-01 07:40 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/database/FileVoucherDatabase.java
> +            if(voucher instanceof PercentDiscountVoucher percentDiscountVoucher) {
VoucherType은 Voucher의 속성일지 아닐지 고민해보세요.

2023-07-01 07:40 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/database/FileVoucherDatabase.java
> +                if("fixed".equals(code)) {
fixed, percent 상수로 관리할 수 있을거 같습니다.

2023-07-01 07:41 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/database/InMemoryVoucherDatabase.java
> +    public void store(UUID voucherId, Voucher voucher, String filePath) {
VoucherId는 Voucher의 속성이 아닌가요?

2023-07-01 07:41 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/database/VoucherDatabase.java
> +}
space가 너무 많이 띄워진거같아요

2023-07-01 07:42 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/model/FixedAmountVoucher.java
> +    public long discount(long beforeDiscount) {
개행!

2023-07-01 07:43 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/model/Voucher.java
> +    long discount(long beforeDiscount);
요구사항이 바뀌어, long 타입이 아닌 double이나 Integer 등으로 바뀌어야 한다고 생각해봅시다.

그렇다면 이 인터페이스와 인터페이스룰 구현하는 모든 클래스에 변경에 영향이 가겠네요. 다 바꿔야 하니까요.

또한 long 보다는 객체로 명확하게 표현할 수 있지 않을지 고민해봅시다.
Vo, 원시값 포장이란 키워드를 찾아보세요

2023-07-01 07:44 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/model/FixedAmountVoucher.java
> +    }
amount가 음수로 들어온다면 어떻게 될까요? 방어적인 코드를 작성해보세요

2023-07-01 07:45 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/repository/BlacklistRepository.java
> +    private static final String FILEPATH = "src/main/csv/blacklist.csv";
상수는 FILE_PATH로 언더스코어를 사용하는것이 관례입니다.

2023-07-01 07:45 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/repository/VoucherRepository.java
> +}
가독성을 위해서라도 개행을 맞춰주세요

2023-07-01 07:46 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/repository/VoucherRepository.java
> +    Map<UUID, Voucher> findAll();
Map 자료구조는 어떤 장단점이 있을까요? 
대체할 수 있는 자료구조는 무엇이 있을까요?

2023-07-01 07:48 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/repository/VoucherRepositoryImpl.java
> +    private static final String FILEPATH = "src/main/csv/vouchers.csv";
Impl보다 명확한 네이밍을 고민해봐도 좋을거같아요.
현재는 File이고,
Jdbc, MyBatis, JPA, Monggo 등 다른 DB Access 기술이 사용되었을때는 네이밍을 어떻게 하면 좋을까요?

2023-07-01 07:50 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/service/VoucherService.java
> +    }
```java
logger.error("unexpected error occurred: unexpected voucher type");
throw new RuntimeException("unexpected voucher type");
```

2023-07-01 07:52 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/util/InputHandler.java
> +    }
이 코드가 여기에 있는것이 적절한지 다시 고민해보셔도 좋을거같아요.

바우처의 책임으로 둘지, 애플리케이션 전체 공통적으로 사용되는 검증 로직일지

2023-07-01 07:55 UTC, devYSK commented on src/test/java/com/prgmrs/voucher/database/FileBlacklistDatabaseTest.java
> +
로딩이 실패하는 테스트는 어떨까요

2023-07-01 07:57 UTC, devYSK commented on src/test/java/com/prgmrs/voucher/model/PercentDiscountVoucherTest.java
> +    @DisplayName("주어진 UUID와 바우처 UUID가 같은 경우")
given-when-then 패턴이 무엇인지, 어떤 장단점이 있고 어떤때 쓰면 좋을지 알아보시면 좋을거 같아요.

2023-07-01 07:58 UTC, devYSK commented on src/test/java/com/prgmrs/voucher/model/PercentDiscountVoucherTest.java
> +    }
테스트시 sout은 필요 없습니다 . 확인후 지워주세요. 

할인율에 따라서 기존 금액을 할인한다. 등의 설명이 더 명확할거같아요

2023-07-01 07:58 UTC, devYSK commented on src/test/java/com/prgmrs/voucher/model/PercentDiscountVoucherTest.java
> +
입력으로 들어온 할인율이 100이 넘으면 예외가 발생한다.

2023-07-01 08:02 UTC, devYSK requested changes
안녕하세요 재영님. 과제하시느냐 고생 많으셨습니다.
흑구님과 제 리뷰를 보시고 고민해서 리팩토링 해보면 좋을거 같아요. 
또한 다른분들의 코드를 보면서 왜 저렇게 했는지 근거를 찾아보면서 좋은 코드는 흡수하시면 좋을것 같습니다. 팀원분들과 서로의 코드를 한번씩 보시는것도 좋을거 같아요 그리고 토론하면서 서로 좋은 코드를 만들어보세요

2023-07-04 13:30 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/VoucherRepository.java
> +    Map<UUID, Voucher> findAll();
Map 자료구조는 uuid와 같은 정보를 key로 두고 O(1) 시간에 접근할 수 있다는 장점이 있습니다. 단점으로는 순서를 보장할 수 없다는 점이 있습니다. List나 Set 등은 key를 두고 탐색하는게 아니기에 retrieve 할 때 더 많은 time complexity가 요구되어 적절해 보이지 않습니다. SpringBoot가 멀티스레딩 환경에서 동작할 것을 고려해 ConcurrentHashMap을 사용하면 좋을 것 같습니다.

2023-07-04 13:37 UTC, JaeyoungAhn commented on src/main/csv/blacklist.csv
> +"ec40d957-f4fe-4830-ae76-d554595ea074","mercy"
application이 빌드시 src 디렉토리 내에 모든 것들이 jar나 war로 압축되고 이후에는 정적으로 압축 파일 내 데이터들을 이용해서 프로그램을 동작시키는데, 동적으로 데이터가 변할 수 있는 .csv 파일이 이 내부에 포함되는 것은 적절하지 않습니다.  src 디렉토리 밖으로 빼내야 합니다.

2023-07-04 13:44 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/BlacklistRepository.java
> +    private static final String FILEPATH = "src/main/csv/blacklist.csv";
언더스코어로 수정하곘습니다!!

2023-07-04 17:07 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +            }
depth가 깊어지지 않도록 각 단계를 나누는 ~Phase라는 이름의 private 메소드들을 추가하였는데, depth가 줄어드는 대신 전체 한 클래스의 길이가 점점 늘어나는 것 같습니다. 클래스의 길이가 길어져도 괜찮을지 궁금합니다..!

2023-07-04 17:08 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/exception/WrongRangeFormatException.java
> +}
굳이 예외로 처리를 하지 않아도 되는 문제인 것 같아 리턴 값을 이용하여 처리하도록 변경하였습니다!

2023-07-04 17:28 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/BlacklistRepository.java
> +@Repository
해당 어노테이션은 벤더사에 의존하는 데이터베이스 에러들을 추상화하여 스프링 프레임워크가 이 에러를 잡아 다시 DataAccessException 에러로 던지는 기능을 요청해 일관성있는 에러처리를 하게 해주고 Spring Data 사용 시 JpaRepository를 구현한 repository 인터페이스와 해당 어노테이션만으로 spring data가 런타임에 자동적으로 crud 메소드를 담고있는 구상체를 구현하도록 합니다. 그렇기에 데이터베이스를 사용 중이지 않은 지금 프로그램에서는 적절하지 않아보입니다만 클래스에 역할을 좀 더 알기 쉽도록 하기 위해 그리고 나중에 확장 될 것을 고려하기 위해 사용하였습니다.

2023-07-04 17:32 UTC, JaeyoungAhn commented on src/test/java/com/prgmrs/voucher/model/PercentDiscountVoucherTest.java
> +
1-100프로만 입력되도록해서 1%~100% 할인율의 바우처만 가능하게 변경하겠습니다.

2023-07-04 17:35 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/util/InputHandler.java
> +    }
코드 상에 바우처 관련 내용이 많은 것 같아서 바우처 디렉토리로 옮기는 것이 나아 보입니다!

2023-07-04 17:37 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/service/VoucherService.java
> +    }
해당 표현으로 변경하겠습니다!

2023-07-04 17:41 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/VoucherRepositoryImpl.java
> +    private static final String FILEPATH = "src/main/csv/vouchers.csv";
FileVoucherRepository로 변경하고 추후 JDBC가 추가된다면 JdbcVoucherRepository를 하나 새로 만들면 좋을 것 같습니다.

2023-07-04 17:47 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/model/FixedAmountVoucher.java
> +    }
생성자에서 검사를하고 조건에 어긋나는 경우 런타임 익셉션을 발생시키는 방식으로 개선하겠습니다.

2023-07-04 17:52 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/model/Voucher.java
> +    long discount(long beforeDiscount);
해당 키워드로 공부해서 개선해보겠습니다!

2023-07-04 17:57 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/database/InMemoryVoucherDatabase.java
> +    public void store(UUID voucherId, Voucher voucher, String filePath) {
id를 파라미터로 넘겨받을 필요 것은 불필요한 과정입니다. 수정하겠습니다!

2023-07-04 18:03 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/database/FileVoucherDatabase.java
> +                if("fixed".equals(code)) {
따로 상수로 분리하겠습니다.

2023-07-04 18:12 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/util/InputHandler.java
> +public class InputHandler {
바우처 관련 책임을 맡고 있는 듯 하여 VoucherValidator로 이름을 변경하고 디렉토리도 변경했습니다.

2023-07-05 14:59 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/setting/BlacklistProperties.java
> +public class BlacklistProperties {
필요로하는 곳에 최대한 뺐습니다! 하지만 해당 파일의 52번 라인에 ConsoleView에서 처음 메뉴를 고르는 과정에서 블랙리스트를 보여줄지 안줄지를 해당 속성을 이용해서 break를 하거나 하지않는 식으로 진행이 되는데 이 부분은 이렇게 놔둬도 괜찮을지, 따로 메서드로 뺀다면 아래에 있는 controller.findAll() 메소드가 순서상 주로 string 출력만 담당하는 consoleViewIO라는 클래스에 같이 들어가게 되는데 괜찮을지 궁금합니다.

2023-07-05 15:00 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/service/VoucherService.java
> +        throw re;
switch문으로 변경하니 확실히 가독성이 증가한 것을 확인할 수 있었습니다.

2023-07-05 16:39 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/model/PercentDiscountVoucher.java
> +    private final long percent;
Tell, Don't Ask 원칙에 입각해서 getter의 사용을 제한하라는 말씀으로 이해했는데 정확히 이해했는지 모르겠습니다. 해당 클래스에서 vocuherId와 percent는 getter가 존재하는데 voucherId과 percent의 getter는 차례대로 각각 7회 4회 사용 되는 것으로 확인이 됩니다. 콘솔에 다양한 형태로 여러번 출력을 하거나 파일에 해당 값을 저장한다면 getter류의 메서드가 사용이 되어야 할 것 같은데 만약 toString()과 같은 메서드로 오버라이딩 한다하더라도 여러 다른 형태로 값을 출력 해야할 필요가 있어서 해법이 될 수는 없을 것 같습니다. 이를 위해 어떤 접근을 해야 할지 방법을 잘 모르겠습니다. VO, DTO와 같은 것을 고려하라는 의미셨을지도 궁금합니다. VO로 한번 감싼 형태를 getter로 돌려주는건 괜찮은 것인지, DTO의 사용의 경우 주로 repository단에서는 잘 사용되지 않는다고 하는데 코드상 파일 기반 repository(database) 레이어에서 getter를 통해 값을 저장하게 되면 DTO 사용이 애매해 지는데 이를 어떻게 처리 해야할지도 고민이 됩니다. repository가 추후에 데이타베이스가 도입이 되면 Voucher 통째로 저장을 해 repository 단에서 getter를 사용할 필요가 없어진다면, 나머지 레이어들의 getter를 대체하기 DTO를 이용하는 것이 가장 좋은 해법이 될 것 같은데 적절한 생각일지 궁금합니다.

2023-07-05 16:45 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/ConsoleView.java
> +            UUID uuid = voucherController.createVoucher(value, consoleViewVoucherCreationEnum);
DTO가 사용되기 좋은 예시인 것 같습니다. 한번 적용해보도록 하겠습니다!!

2023-07-05 17:11 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/ConsoleViewVoucherCreationEnum.java
> +    UNEXPECTED_INPUT;
UNEXPECTED_INPUT이 꼭 필요한 것인지를 물으신 것으로 이해가 됩니다. 반드시 어느 하나의 ENUM 값이 리턴되는 것을 원했고 입력받은 string이 어떠한 것도 해당되지 않는다면 UNEXPECTED_INPUT을 리턴하고 이를 호출한 곳에서 에러 발생 대신 입력을 다시 받는 것으로 프로그램을 지속시키는 것을 생각했었습니다만 null을 대체하는 Optional을 이용할 수 있을 것 같습니다.

2023-07-08 11:48 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/dto/VoucherResponse.java
> +public class VoucherResponse {
Java 17 버전을 사용하시는데, `record`로 대체될 수 있을것 같아요

2023-07-08 13:08 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/dto/VoucherResponse.java
> +public class VoucherResponse {
네 record로 고치도록 하겠습니다!

2023-07-08 17:59 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/VoucherRepository.java
> +    Map<UUID, Voucher> findAll();
다시 생각해보니 데이터를 받아와서 순회하면서 출력을 한다면 시간 복잡도는 자료구조와 관계 없이 동일하고 UUID가 Voucher 내 속성이고 추후 정렬된 상태의 배열들을 가지고 있을 경우를 고려하면 인메모리 자료구조에서 지속적으로 데이터를 retrieve하는 경우가 아니라면 꼭 Map을 사용해야 할 이유는 없어 보입니다.

2023-07-10 07:00 UTC, merged