[4기] 원건희 4차 PR 입니다.
prgrms-be-devcourse/springboot-basic pull request #746
Opened 2023-07-03 08:33 UTC by weonest

## ✅ 피드백 반영사항  
- 323cc9640d3020502501e2969113c4df30cc6c34 한 줄에 하나의 행위만 하도록 반영
- 485e143e56dd33c2fbaabbb1d19e6d55030b4b1b 바우처 추상화 메서드를 통한 콘솔 출력
- 4c285239dc392d53df465564685f1c3c4028078a 최소값과 최대값에 대한 테스트 반영
- 18179df2e28df59dce9dbc1ff2b34d13ecf0b74e 컨트롤러 가독성 및 만료일 `expiredAt`으로 변경
- 63704d732c43a5835ded77212b8d49f6f087fdd4 바우처 유효기간을 제어할 수 있도록 변경
- d0ec4173daf3ef305c560e7048b3c2164eb993e5 추상화 레벨 수정 반영 

## ✅ PR 포인트 & 궁금한 점 
- 기존에 도진님께서 말씀하셨던 추상화 레벨이 맞지 않은 부분에 대한 반영을 `ResponseConverter` 라는 유틸 클래스를 두어 이곳에서 객체에 대한 출력 값을 `String`으로 만들어 출력하는 쪽에 전달하도록 만들었는데 이러한 방식에 대해서 어떻게 생각하시는지 궁금합니다!
- 주석으로도 남겼지만 로깅을 적용하는 과정에서 AOP를 적용해보고자 하였는데 `private`메서드에는 AOP가 적용되지 않는 점과 `@AfterThrowing` 을 통해 예외에 대한 로그를 남기는 것 역시 적용되지 않아 다양한 해결법을 찾아보던 중 `Aspectj`의 `CTW`를 통한 AOP 적용에 대해서 알게 되었고 이를 적용해보고자 하였는데, 이것 역시 제대로 적용되지 않았습니다. 적용 과정에서 어떠한 점이 잘못되었는지 알고 싶습니다!

2023-07-03 10:19 UTC, dojinyou requested changes
브랜치 바꾸지 말고 기존 브랜치에 작업해주세요. fileschanged가 너무 요

2023-07-04 00:17 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/domain/Customer.java
> +        this.modifiedAt = null;
```suggestion
        this(customerId, name, createdAt, null);
```
- 이렇게 하면 코드 중복이 줄어들겠네요!

- `modifiedAt`이 있는 생성자와 없는 생성자는 어떤 차이가 있는걸까요?

2023-07-04 00:17 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +        this.expiredAt = applyExpiration();
`applyExpiration()`은 메서드로 빼지 않아도 될 거 같은데 어떻게 생각하세요?

2023-07-04 00:17 UTC, seung-hun-h commented on src/main/resources/logback.xml
> +    </logger>
`info` 레벨을 콘솔 출력하는 이유가 있을까요?

2023-07-04 00:17 UTC, seung-hun-h commented on src/main/resources/logback.xml
> +    </logger>
level을 공백으로 두면 어떻게 되나요?

2023-07-04 00:17 UTC, seung-hun-h commented on src/main/resources/logback.xml
> +        </rollingPolicy>
로그 파일의 크기와 개수는 관리하지 않아도 되는걸까요?

2023-07-04 00:17 UTC, seung-hun-h commented
질문에 대한 답변은 어제 게더에서 한 이야기로 대신할게요~

2023-07-04 04:27 UTC, dojinyou requested changes

2023-07-04 04:27 UTC, dojinyou commented on src/main/java/com/programmers/customer/service/CustomerService.java
> +    void deleteCustomerById(UUID customerID);
Domain 객체가 외부로 노출되는 것 같은데 이 부분에 대해서 어떻게 생각하시나요?

2023-07-04 04:27 UTC, dojinyou commented on src/main/java/com/programmers/global/aop/LoggingAspect.java
> +// 로깅을 AOP 적용하여 처리하고 싶었는데, private 메서드에는 동작하지 않는다는 것을 알게 됐습니다.
로깅을 AOP로 처리 하시려는 이유가 뭘까요?

2023-07-04 04:27 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Discount.java
> +    // 이를 DiscountType으로 변수명을 변경하면 어떨지 고민입니다.
저는 DiscoutType이라는 네이밍이 더 좋아 보여요!

2023-07-04 04:27 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
>      }
expiredAt을 외부에 노출해주는 이유가 있을까요?

2023-07-04 04:27 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/VoucherTest.java
> +        assertThat(createdAt.plusDays(7)).isEqualTo(createdVoucher.getExpiredAt());
정책적인 요소(`기본 만료일은 7일`)에 의존적인 테스트는 변수로 처리한 뒤에 하는 게 관리에 더 용의할 것 같은 데 어떻게 생각하시나요?

2023-07-04 04:27 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/VoucherTest.java
>  }
파일 마지막 개행 추가

2023-07-05 12:54 UTC, weonest commented on pom.xml
> +<!--        </dependency>-->
2d411631a345dd868e2df544fdb9e16c8869ba53
적용하였습니다!

2023-07-05 12:56 UTC, weonest commented on src/main/java/com/programmers/console/util/ResponseConverter.java
> +public class ResponseConverter {
a2b88c6696df45ac12a5d85a2967dd94a1a35048
`Mapper` 클래스에도 동일하게 적용하였습니다!

2023-07-05 13:42 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
> +        this.expiredAt = applyExpiration();
e8b2a72a3673ef27d8e62de8d7da808f296d7d33
말씀하신대로 코드 길이도 길지 않고 행위도 간단하기 때문에 굳이 메서드로 빼지 않아도 되는 것 같습니다!

2023-07-05 14:24 UTC, weonest commented on src/main/resources/logback.xml
> +        </rollingPolicy>
3a693d979a153c691c85d480aef70be5bbbcc8de
바로 적용하였습니다!

2023-07-05 14:26 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
> +        printVouchers(voucherController.findAll());
99b0b2cfea76e7f3b35dac3a9fa67251b85bcb0e
적용하였습니다!

2023-07-05 14:27 UTC, weonest commented on src/main/java/com/programmers/console/CommandLineApplication.java
>      }
잘 이해를 하지 못하였는데, `printVouchers` 메서드보다 `printVoucehr`메서드가 더 많이 호출되고 있는 부분을 말씀하시는 걸까요?

2023-07-05 15:06 UTC, weonest commented on src/main/java/com/programmers/global/aop/LoggingAspect.java
> +// 로깅을 AOP 적용하여 처리하고 싶었는데, private 메서드에는 동작하지 않는다는 것을 알게 됐습니다.
AOP를 적용하면 기존에 작성한 코드의 수정 없이 로깅을 일괄적으로 적용할 수 있다는 점에서 편리하다고 생각하여 적용하려고 하였습니다. 
이후 승훈 멘토님과 이야기를 나누다보니 오히려 현재 프로젝트의 경우 AOP를 적용하는 것이 직접 로그를 남기는 것보다 리소스가 많이 들기도 하며 (대상 객체들을 프록시 객체로 동적 생성을 해야하기 때문인 것 같습니다) 예외를 처리하기 위해서는 다시 예외를 던져야 하는 Re Throw? 형태가 되기 때문에 비효율적이다고 판단하여 직접 로그를 남기는 방식으로 변경하였습니다!

2023-07-05 15:08 UTC, weonest commented on src/main/java/com/programmers/voucher/domain/Voucher.java
>      }
추후에 DB에 바우처를 저장할 때 유효기간 정보도 남기기 위해서는 필요할 것이라고 생각하였습니다!

2023-07-05 15:11 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/VoucherTest.java
> +        assertThat(createdAt.plusDays(7)).isEqualTo(createdVoucher.getExpiredAt());
fefc5c81ffb6019971a2f490e7c80f68a8cc3cfe
해당 피드백 적용하였습니다!

2023-07-05 15:11 UTC, weonest commented on src/test/java/com/programmers/voucher/domain/VoucherTest.java
>  }
fefc5c81ffb6019971a2f490e7c80f68a8cc3cfe
적용하였습니다!

2023-07-06 15:10 UTC, dojinyou commented on src/main/java/com/programmers/console/CommandLineApplication.java
>      }
출력해야하는 스트링을 모아서 한번에 출력하는 건 안되나요?

2023-07-06 15:13 UTC, dojinyou commented on src/main/java/com/programmers/voucher/domain/Voucher.java
>      }
그렇다면 지금은 노출할 필요 없지 않을까요?

2023-07-06 15:14 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/VoucherTest.java
> +        assertThat(createdAt.plusDays(7)).isEqualTo(createdVoucher.getExpiredAt());
음... 이후에 14일로 기본 만료일이 수정되었을 때 한 곳에서만 수정되면 좋을 것 같아요!

2023-07-06 15:25 UTC, dojinyou commented on src/main/java/com/programmers/console/util/VoucherStringSerializer.java
> +                discountType, voucherId, discountValueFormat(discount), createdAt);
줄바꿈을 해야한다면 한 줄에 인자 하나만 넣는 게 나중에 변경사항 발생했을 때도 확인하기 좋은 것 같아용!

2023-07-06 15:26 UTC, dojinyou commented on src/main/java/com/programmers/customer/repository/CustomerRepository.java
> +    Customer findById(UUID customerId);
id에 대응되는 고객이 없을 땐 null이 반환되나요?

2023-07-06 15:32 UTC, dojinyou commented on src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
> +    private final Map<UUID, Voucher> STORAGE = new ConcurrentHashMap<>();
상수가 아니라 불변 멤버 변수라면 변수명이 카멜 케이스로 해주세요

2023-07-06 15:32 UTC, dojinyou commented on src/test/java/com/programmers/voucher/domain/DiscountTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
👍

2023-07-07 00:14 UTC, seung-hun-h commented on src/main/resources/logback.xml
> +    <root level="error">
error에 대해서만 로그를 남기는 이유가 있을까요?

2023-07-07 05:32 UTC, merged