[4기] 유명한 4차 PR 입니다.
prgrms-be-devcourse/springboot-basic pull request #751
Opened 2023-07-04 04:15 UTC by yumyeonghan

## 📌 과제 설명
1. 로깅 설정
2. 고객 엔티티
3. 고객 레포지토리

## ✅ 피드백 반영사항
- 2936439e01a88309e260f547925a8dfd3028161b:  VoucherExecution 함수형 인터페이스 설정
- 5df9266fe2b83b65127780fea2d858b3c333405d: 에러 메세지에 StringFormat 활용
- 2f3843f58b7e501348b1735e81a2d28891d094a4: voucherType.equals("") 대신 voucherType.isBlank() 사용
- 0db836c3dcdb5975de463002ac4db6158130a34b: 무거운 ApplicationContext 말고, 바로 FrontController 주입
- 8eda70fe4a637a48d60fe742d4af2f3de9bc7156: ExitController 생성
- b0aceccc95f4663a52f479b741d9e655a49b7981: Patterns 생성
- 776b5304abb187ebcb75f9309d45511ba092f6e2: toString() 직접 호출 지양
- 2a686194c785416c7ed7753ef00516c03813d1ce: 테스트 이름은 하나의 문장으로 작성하고, given-when-then 통일

2023-07-04 04:54 UTC, dojinyou requested changes
테스트 코드가 전체적으로 가도성이 좋아진것 같아요! 고생하셨습니다

2023-07-04 04:54 UTC, dojinyou commented on src/main/java/com/programmers/application/controller/command/Command.java
> +                VoucherExecution voucherExecution = new VoucherExecution() {
클래스 구현을 Enum 내부로 넣은 이유가 있을까요?

2023-07-04 04:54 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +    private final LocalDateTime createdAt;
[nit]
불변 멤버변수와 일반 멤버변수를 분리해주면 좋을 것 같아요!

2023-07-04 04:54 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +    }
정적 팩토리 메서드를 만든 이유가 뭘까요?

2023-07-04 04:54 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +        }
👍

2023-07-04 04:54 UTC, dojinyou commented on src/main/java/com/programmers/application/domain/voucher/VoucherType.java
> +    ;
❤️

2023-07-04 04:54 UTC, dojinyou commented on src/main/java/com/programmers/application/repository/customer/CustomerRepository.java
> +    int count();
이 메서드는 어떤 의미일까요?

2023-07-04 04:54 UTC, dojinyou commented on src/test/java/com/programmers/application/domain/customer/CustomerTest.java
> +                .isBefore(LocalDateTime.now().plusSeconds(1));
[nit]
사실 엄청 빨라서 문제가 되지 않을 테지만 저라면 `prevLastLoginAt`이라는 이름으로 변수를 만들고 이것이후 시간대로 바꼈는 지만 체크할 것 같아요!

2023-07-04 21:25 UTC, seung-hun-h reviewed
명한님 코멘트 남겼습니다. logback 설정은 안하셨나요?

2023-07-04 21:25 UTC, seung-hun-h commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +        }
고객을 생성할 때는 검증 로직이 필요없나요? 
고객 이름은 나중에 입력할 수 있다는 정책을 만드신건지 해서요

2023-07-04 21:25 UTC, seung-hun-h commented on src/main/java/com/programmers/application/repository/customer/CustomerRepository.java
> +    Optional<Customer> findByName(String name);
동명이인은 허용하지 않는건가요?

2023-07-05 03:28 UTC, yumyeonghan commented on src/main/java/com/programmers/application/controller/command/Command.java
> +                VoucherExecution voucherExecution = new VoucherExecution() {
음.. 처음에 스프링 빈 등록없이 직접 객체 생성으로 하다가, 함수형 인터페이스 특징이 보여서 익명 클래스로 직접 작성해주었습니다.
하지만 VoucherExecution 구현체들은 상태가 없고, 싱글톤으로 동작을 하는게 맞기 때문에 다시 스프링 빈으로 등록해서 동작하게끔 수정해봤습니다.
8c856f8a50a273e237017710c69ab881a3b6dac5

2023-07-05 04:32 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +    private final LocalDateTime createdAt;
넵 반영했습니다!

2023-07-05 05:24 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +    }
처음에는 외부에서 무분별한 Customer 생성자 호출을 막고, 생성이란 명확한 목적이 있을 때 of()로 생성할 수 있게끔 하기위해 만들었습니다.

하지만 정적 팩토리 메서드를 사용하는 이유는 
Voucher 클래스와 같이 다형성을 구현할 때 하위 타입 객체로 반환을 할  수 있는 점과

객체 내부 상태를 나타내는 파라미터로 인해 상태들을 외부로 노출시키는 직접 생성자 호출과 달리 객체 상태를 숨기고 생성자를 호출할 수 있는 점이라고 생각합니다.

따라서 Customer의 of()는 이러한 이유에 해당하지 않기 때문에 굳이 정적 팩토리 메서드를 사용하지 않고, 생성자를 사용해서 호출하는 방향으로 수정했습니다.

2023-07-06 13:31 UTC, yumyeonghan commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +        }
고객을 생성하기 위해 반드시 컨트롤러에 입력 되어야 할 이름 Null 값 또는 빈값 검증 같은 것은 dto에서 검증하게 끔 설계를 계획중이고,

고객 이름 변경같은 비즈니스 도메인적인 부분에 대한 검증은 엔티티에서 하려합니다.
그래서 우선은 dto에서 검증할 것들은 엔티티에서는 따로 추가하지 않았는데,

혹시 엔티티와 dto에서 모두 검증하도록 로직을 추가할까요?

2023-07-06 13:53 UTC, yumyeonghan commented on src/main/java/com/programmers/application/repository/customer/CustomerRepository.java
> +    int count();
count() 메서드명이 너무 명확하지 않았던 것 같습니다.
해당 메서드는 '모든 고객수 카운트하기' 의 의미를 갖고 있어서,
count() => countAllCustomers() 로 변경을 했습니다..!

e0aef5e2e2c0be0223a9246e6c95628d4297df25

2023-07-06 14:03 UTC, yumyeonghan commented on src/test/java/com/programmers/application/domain/customer/CustomerTest.java
> +                .isBefore(LocalDateTime.now().plusSeconds(1));
반영했습니다!
3b8665b11f042b947411110674a37ebefabccf46

2023-07-06 14:09 UTC, yumyeonghan commented on src/main/java/com/programmers/application/repository/customer/CustomerRepository.java
> +    Optional<Customer> findByName(String name);
이름으로 고객을 찾으려면 동명이인을 허용하지 않게 되는 문제가 생기기 때문에 findByName() 메서드를 삭제했습니다. 따라서 고객은 중복으로 등록되지 않을 customerId와 email로만 찾을수 있게끔 했습니다.!

2a405db28c35447c5a1fc5515cd408105694dede

2023-07-06 17:35 UTC, yumyeonghan commented
로그백 설정 했습니다.!

010b8aeb33ee15373e597fc309456c012b17ee4e

2023-07-07 00:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/controller/voucher/command/VoucherExecutionDependencyInjector.java
> +            if (command.equals(Command.CREATE)) {
```suggestion
            if (command == Command.CREATE) {
```

Enum인 싱글턴이라 일반적으로 `==`을 사용해 동일성 비교를 합니다.
동등성 비교와 동일성 비교에 대해서 알아보는 것도 좋겠네요

2023-07-07 00:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/domain/customer/Customer.java
> +        }
도메인에서 검증이 먼저 되어야 한다고 생각합니다

2023-07-07 00:28 UTC, seung-hun-h commented on src/main/java/com/programmers/application/repository/customer/CustomerRepository.java
> +    int countAllCustomers();
count 인터페이스를 추가하신 이유가 있을까요?

2023-07-07 02:05 UTC, dojinyou commented on src/main/java/com/programmers/application/controller/command/Command.java
> +                VoucherExecution voucherExecution = new VoucherExecution() {
enum이 적절한 실행 객체를 찾아 주는 역할을 하는 게 맞는 지 의문이 드네요!
적절한 실행 객체를 찾아주는 역할을 하는 친구를 분리하고 그 역할을 가진 친구가 enum을 인자로 받아서 적절한 객체를 반환하거나 혹은 실행시켜주는 건 어떨까요?

2023-07-07 02:27 UTC, dojinyou commented on src/main/java/com/programmers/application/controller/FrontController.java
> +    private final ExitController exitController;
이렇게 되면 Controller가 추가될 때 마다 코드가 수정되어야 할 것 같은데 다른 방법은 없을까요?

2023-07-07 02:27 UTC, dojinyou commented on src/test/java/com/programmers/application/domain/customer/CustomerTest.java
> +    @DisplayName("옳바른 인자들로 of()를 실행하면 Customer가 생성된다.")
of 메서드가 사라진 것 같아요!

2023-07-07 02:38 UTC, merged