[4기 - 박은지] 4차 로깅, 고객, 고객 레포지토리 구현
prgrms-be-devcourse/springboot-basic pull request #752
Opened 2023-07-04 08:29 UTC by 1o18z

## ✅ 피드백 반영사항  
- [X] String.format 수정
- [X] Enum valueOf 사용
- [X] 의미있는 변수 사용
- [X] discount 범위 수정
- [] Discount의 getter 수정 중
## ✅ PR 포인트 
- VoucherValidator와 CustomerValidator에 모두 Id가 검증 로직이 들어있는데 이 부분도 공통으로 사용할 수 있도록 하는 것이 더 좋은 방법일 지 궁금합니다 !

2023-07-04 15:15 UTC, dojinyou requested changes

2023-07-04 15:15 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    System.out.println(("FIXED" + " | " + "PERCENT\n" + ENTER_CREATE_TYPE));
괄호 1개만쓰기?

2023-07-04 15:15 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    return "FIXED".equals(discountType.name()) ? "₩" : "%";
이런 정보라면 `discountType`에 들어가도 되지 않을까요?

2023-07-04 15:15 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/io/MenuType.java
> +      LOGGER.error("Menu Error Message => {}", MENU_TYPE_ERROR);
logging 레벨이 `error`이면 조금 과한 것 같은데 어떻게 생각하시나요?

2023-07-04 15:15 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/FixedDiscount.java
> +    return (price - discountAmount) >= 0 ? (price - discountAmount) : 0;
```suggestion
    return Math.max(price-discountAmount, 0);
```

2023-07-04 21:56 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/customer/validator/CustomerValidator.java
> +      throw new IllegalArgumentException(INVALID_ID_ERROR);
로그와 예외를 함께 던지고, 최상위에서 예외에 대한 로그를 남기는 로직이 있다고 가정할 때 같은 예외에 대해서 여러번 로그가 남을 것 같아요. 예외만 던져주는 것이 좋아 보이네요

2023-07-04 21:56 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/customer/validator/CustomerValidator.java
> +    if (isEmailNull(email) || !isValidEmailFormat(email)) {
```suggestion
    if (email == null || !isValidEmailFormat(email)) {
```
이렇게만 작성해도 가독성면에서는 문제없을 것 같아요

2023-07-04 21:56 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    return "FIXED".equals(discountType.name()) ? "₩" : "%";
```suggestion
    return DiscountType.FIXED == discountType ? "₩" : "%"
```
그리고 String 보다는 DiscountType을 사용해서 이렇게 비교하는 것이 좋아보이네요

2023-07-04 21:56 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/repository/CustomerRepository.java
> +  Optional<Customer> findByName(String name);
동명이인은 허용하지 않는건가요?

2023-07-04 21:56 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +            .orElseThrow(() -> new IllegalArgumentException(NO_EXIST_VOUCHER));
어떤 id 값이 들어왔는지도 알려주면 좋을 것 같아요!

2023-07-04 21:56 UTC, seung-hun-h commented on src/main/resources/logback.xml
> +    </logger>
다른 레벨에 대해서는 로그를 남기지 않는건가요?

2023-07-04 21:56 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/customer/CustomerTest.java
> +  @DisplayName("올바른 형식의 이메일과 이름을 작성했을 경우 customer 생성 성공")
```suggestion
  @DisplayName("올바른 형식의 이메일과 이름을 작성했을 경우 고객이 생성된다")
```

테스트 메서드나 DisplayName은 `가정-행위-결과`의 완전한 문장으로 작성해주는 편이 가독성이 좋아요

2023-07-04 22:31 UTC, seung-hun-h commented
> VoucherValidator와 CustomerValidator에 모두 Id가 검증 로직이 들어있는데 이 부분도 공통으로 사용할 수 있도록 하는 것이 더 좋은 방법일 지 궁금합니다 !

서로 다른 객체의 ID에 대한 검증이라서 공통으로 하지 않아도 될 것 같아요

2023-07-06 06:58 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/MenuType.java
> +      LOGGER.error("Menu Error Message => {}", MENU_TYPE_ERROR);
해당 상황에는 error보다 warn이 더 적절할 것 같다고 생각되어 수정하였습니다 !

2023-07-06 07:00 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/CustomerRepository.java
> +  Optional<Customer> findByName(String name);
동명이인도 받을 수 있도록 findByName을 제거하고 id와 email로 찾을 수 있도록 수정하였습니다 !

2023-07-06 07:01 UTC, 1o18z commented on src/main/resources/logback.xml
> +    </logger>
warn과 info에 대해서도 로그를 남기면 좋을 것 같다고 생각이 들어 수정하였습니다 !

2023-07-06 07:37 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/customer/Customer.java
> +    this.lastLoginAt = lastLoginAt;
'마지막으로 로그인 했을 때의 시간'인데, 불필요하다고 생각이 되어서 제거하였습니다 !

2023-07-07 09:20 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/customer/Customer.java
> +    this.lastLoginAt = lastLoginAt;
6f45d5c

2023-07-07 09:21 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/customer/validator/CustomerValidator.java
> +    return isValid;
31dcdfd

2023-07-07 09:21 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/customer/validator/CustomerValidator.java
> +  private static boolean isValidEmailFormat(String email) {
31dcdfd

2023-07-07 09:21 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    System.out.println(("FIXED" + " | " + "PERCENT\n" + ENTER_CREATE_TYPE));
5734e79

2023-07-07 09:22 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    return "FIXED".equals(discountType.name()) ? "₩" : "%";
803a76b5

2023-07-07 09:22 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/MenuType.java
> +      LOGGER.error("Menu Error Message => {}", MENU_TYPE_ERROR);
392f28066be

2023-07-07 09:23 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/FixedDiscount.java
> +    return (price - discountAmount) >= 0 ? (price - discountAmount) : 0;
b77c180d32006f8dcfee1ba17d1bd4f8100773f1

2023-07-07 09:23 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/customer/validator/CustomerValidator.java
> +      throw new IllegalArgumentException(INVALID_ID_ERROR);
392f28066be77e742c2e815860cbf21ddbc16e99 [392f280]

2023-07-07 09:24 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/customer/validator/CustomerValidator.java
> +    if (isEmailNull(email) || !isValidEmailFormat(email)) {
31dcdfd25e0d1542a1b88f2056b7cbf6b5a4af7c

2023-07-07 09:24 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +    return "FIXED".equals(discountType.name()) ? "₩" : "%";
803a76b5c8af7f66592ec7cfaa16f95a33116dae

2023-07-07 09:24 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/CustomerRepository.java
> +  Optional<Customer> findByName(String name);
2cbb91dac584d5d7b2bafea439e96cace4a3c67e

2023-07-07 09:25 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
> +            .orElseThrow(() -> new IllegalArgumentException(NO_EXIST_VOUCHER));
7a9c2afdc8999480b545ddea375d6910223afd29

2023-07-07 09:25 UTC, 1o18z commented on src/main/resources/logback.xml
> +    </logger>
392f28066be77e742

2023-07-07 09:25 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/customer/CustomerTest.java
> +  @DisplayName("올바른 형식의 이메일과 이름을 작성했을 경우 customer 생성 성공")
07a4baf4442776cfe9a50694b9fec38966e41fe3

2023-07-07 14:07 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +      System.out.println(String.format("- %s VOUCHER : %s%s", discountType, voucher.supplyDiscountAmount(), printUnit(discountType)));
```suggestion
      System.out.println(String.format("- %s VOUCHER : %s%s", discountType, voucher.supplyDiscountAmount(), discountType.getUnit()));
```
이런식이면 좋을것 같아요

2023-07-07 14:07 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
> +  void fixedAmountRange_ErrorSuccess(int discountAmount) {
```suggestion
  void fixedAmountRange_ThrowException(int discountAmount) {
```
이런식이 낫지 않을까요?
에러와 성공 단어가 같이 있어서 어떤케이스를 테스트했는지 헷갈리네요

2023-07-08 09:32 UTC, merged