[4기 - 전선희] SpringBoot Part2 Weekly Mission 첫 번째 PR 제출합니다!
prgrms-be-devcourse/springboot-basic pull request #764
Opened 2023-07-06 06:58 UTC by funnysunny08

## 📌 과제 설명 
5주차 강의에서 배운 내용들을 활용하여 Voucher와 Customer의 db 연동, 테스트 코드를 작성하였습니다!<br>
(7/4 커밋부터 2차 과제입니다!)

## 👩‍💻 요구 사항과 구현 내용 
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
테스트 코드가 아직 익숙치 않아 많이 작성하지 못했습니다..! 추후에 더 작성하여 올리겠습니다😭

2023-07-06 10:24 UTC, JoosungKwon commented on src/test/java/com/prgrms/spring/VoucherRepositoryTest.java
> +                    .url("jdbc:mysql://localhost/voucher_system")
로컬 DB를 테스트 용도로 사용했을때 어떤 문제가 발생할 수 있을까요?

2023-07-06 12:56 UTC, JoosungKwon reviewed
선희님 2주차 과제도 고생하셨습니다~!! 😄

1주차가 마무리 되었다면 멘토님께 이야기 드려서 Merge 부탁드려요~ 
1주차에서 한번 밖에 리뷰하지 않은 것 같아서 리뷰가 늘어났네요..😅 간단하게 참고만 해주세요~!!

리팩터링이랑 테스트 코드 마무리 까지 화이팅하시길 바랍니다~~ 👍

p.s 테스트 코드 작성이 어렵다면 동료들의 도움을 받아보는 것은 어떨까요~?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/resources/application.properties
> +spring.datasource.password=0828
보안 정보나 개인 정보를 깃허브에 올리면 유출될 위험이 있습니다!! 암호화하는 방법에 대해 알아보시면 좋겠네요~

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/resources/logFiles/log.2023-07-06.log
> +15:20:48.186 [main] ERROR c.p.s.r.v.JdbcVoucherRepository - Got empty result
log파일도 올리지 않는게 좋을 것 같아요~

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +    }
조회(Read)에 트랜잭션이 필요할까요? [readonly](https://junhyunny.github.io/spring-boot/jpa/junit/transactional-readonly/)기능에 대해서도 알아보면 좋을 것 같아요~

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +    public Collection<Voucher> getAllVoucher() {
`Collection`을 리턴하는 이유가 궁금합니다!!

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +        }
`if-eles if`를 사용하지 않는 방법은 없을까요? 그리고 만약, 누군가 `VoucherType`을 추가한 후에 해당 메서드에 업데이트 해주지 않았다면 `NPE`의 위험이 있을 수 있겠네요! 그렇다면 어떻게 하는 것이 좋을까요?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/customer/CustomerService.java
> +                .orElseThrow(() -> new RuntimeException("고객 조회 실패"));
`RuntimeException` 보다 좀 더 명확한 상황을 알릴 수 있는 예외가 좋다고 생각하는데 어떻게 생각하시나요?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/service/customer/CustomerService.java
> +        var newCustomer = Customer.newInstance(UUID.randomUUID(), customerCreateRequestDto.getName(), customerCreateRequestDto.getEmail(), LocalDateTime.now());
한줄이 길어지면 내리는게 가독성에 더 좋을 것 같습니다!! 그리고 `var`를 사용하셨는데 선희님은 `var`에 대해서 어떤 생각을 가지고 계신가요? 혹시 다른 팀원들이랑 `var`에 대해 이야기 나눠보셨나요~?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/repository/voucher/MemoryVoucherRepository.java
> +        return null;
지원하지 않는 메서드라면 `UnsupportedOperationException`를 사용해서 명확한 상황을 나타내는 것이 좋습니다!!

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/repository/voucher/JdbcVoucherRepository.java
> +@AllArgsConstructor(access = AccessLevel.PROTECTED)
`PROTECTED`로 하신 이유가 궁금하네요~~

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/repository/voucher/JdbcVoucherRepository.java
> +        if (update != 1) {
`1`보다 의미를 알 수 있는 변수를 사용해보는 것은 어떤가요~?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/repository/voucher/JdbcVoucherRepository.java
> +        }
바우처의 타입이 늘어날 수록 변경해야하는 곳이 많은 것 같아 보이네요~ 변경에 의한 전파가 많으면 객체지향적이라고 볼 수 있을까요?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/repository/customer/JdbcCustomerRepository.java
> +            logger.error("Got empty result", e);
선희님은 어떤 기준으로 로그 레벨을 나누시나요?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/repository/customer/JdbcCustomerRepository.java
> +    public void deleteAll() {
전체 삭제 기능이 요구사항에 있었나요? 고객 데이터를 전부 삭제해야하는 기능을 제공할 필요가 있을까요?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/io/Output.java
> +    void showGetName();
의미를 두고 구분하신거라면, 주석으로 의미를 남겨 주시면 더 파악하기 수월해질 것 같아요~

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/AppRunner.java
> +    public void run(String... args) throws Exception {
한 메서드에서 너무 많은 기능이 혼재되어 있다고 보여집니다~! 분리해보는 것은 어떨까요?

2023-07-06 12:56 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/AppRunner.java
> +            switch (menuType) {
`switch` 내부에서 발생할 수 있는 에러에 대해서는 일부러 처리 하지 않는 건가요?

2023-07-07 02:41 UTC, graygreat requested changes
안녕하세요 선희님 :)

미션 잘 진행 해주셨네요!
각 객체에 대한 테스트 코드까지 있으면 더욱 완벽 해질 것 같아요 👍 

리뷰 남겼으니 확인 부탁드려요~

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/AppRunner.java
> +            logger.info("프로그램 시작.");
"프로그램 시작"이라는 로그로 어떠한 이점을 가질 수 있을까요?

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/AppRunner.java
> +            }
해당 로직을 분리해보면 depth를 줄일 수 있겠네요!

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/AppRunner.java
> +            switch (menuType) {
선희님은 switch와 else if를 사용할 때, 어떠한 기준으로 선택하시나요?

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@AllArgsConstructor
@AllArgsConstructor를 붙이신 이유는 무엇인가요?
@RequiredArgsConstructor와의 차이점을 알고 있으신지 궁금합니다.

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +        consoleView.showSuccessMsg(Success.CREATE_VOUCHER_SUCCESS);
해당 로직도 메소드를 분리해서 조금 더 의미있는 이름들을 줄 수 있겠네요!

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +        if (voucher == null) {
null을 검증할 수 있는 역할을 VoucherController가 아닌 도메인에서 하는게 더 의미있지 않을까요?

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +            logger.error("바우처 생성 실패");
만약 선희님이 지금 만드신 서비스를 **운영**하고 있다고 가정해볼게요.
만약 서비스 장애가 생겨서 로그를 본다면 어떠한 정보들이 있으면 좋을 것 같으세요?
저는 "바우처 생성 실패"라고만 되어 있으면 어떠한 정보들이 잘못 들어와서 장애가 낫고 어떠한 부분을 고쳐야할 지 모를 것 같네요.

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +            return;
return을 하는 것 보다 예외를 던지는게 맞지 않을까요?

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +
출력을 위한 로직이니까 consoleView 로직에 넣는게 더 좋을 것 같네요!

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/domain/menu/MenuType.java
> +                .orElseThrow(() -> new IllegalStateException(String.valueOf(Error.VALIDATION_WRONG_TYPE)));
IllegalStateException와 IllegalArgumentException는 어떠한 차이가 있나요?

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/domain/customer/Customer.java
> +    }
해당 디자인 패턴을 사용하신 이유가 있으실까요?

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/domain/voucher/FixedAmountVoucher.java
> +        if (discount <= 0) throw new IllegalArgumentException("유효하지 않은 할인 금액");
검증하는 로직의 메소드를 따로 분리해볼 수 있겠네요

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/io/Output.java
> +    void showMenu();
CusomerRepository는 개행을 하셨는데, 여긴 개행이 없네요 ㅎ
개행을 하실 때, 기준이 있으실까요?

2023-07-07 02:41 UTC, graygreat commented on src/main/java/com/prgrms/spring/repository/customer/JdbcCustomerRepository.java
> +    private static final Logger logger = LoggerFactory.getLogger(JdbcCustomerRepository.class);
log는 어떤 layer에서 남겨야된다고 생각하시나요?

2023-07-07 02:41 UTC, graygreat commented on src/test/java/com/prgrms/spring/ApplicationTests.java
> +class ApplicationTests {
해당 테스트 코드는 필요 없지 않을까요 ㅎ

2023-07-07 02:41 UTC, graygreat commented on src/test/java/com/prgrms/spring/VoucherRepositoryTest.java
> +    private static final Logger logger = LoggerFactory.getLogger(VoucherRepositoryTest.class);
테스트 코드를 로깅 하는 이유가 있으실까요?
선희님이 로깅을 하는 목적을 잘 생각해보시고 말씀해주세요!

2023-07-12 15:33 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +    public Collection<Voucher> getAllVoucher() {
결과값을 스트링으로 변환해서 리턴하고 있는데 당시에는 이 작업을 controller단에서 하는 게 적합하다고 생각을 했었어요..! 근데 지금 다시 보니깐 데이터 가공(?)은 서비스단에서 끝내는 게 좀 더 적절하지 않나라는 생각이 드네요..!😢

2023-07-12 16:04 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/service/voucher/VoucherService.java
> +        }
저도 사실 코드를 짜면서 양심이 조금 찔리긴 했어요,, 방법을 좀 더 강구해보겠습니다!😅

2023-07-13 00:35 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/service/customer/CustomerService.java
> +                .orElseThrow(() -> new RuntimeException("고객 조회 실패"));
custom 예외를 만들어봤습니다..!

2023-07-13 00:41 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/service/customer/CustomerService.java
> +        var newCustomer = Customer.newInstance(UUID.randomUUID(), customerCreateRequestDto.getName(), customerCreateRequestDto.getEmail(), LocalDateTime.now());
넵!
`var` 는 좀 더 편하고 유연하게 코드를 짤 수 있지만 정확성, 명확성이 떨어진다고 생각합니다..!

2023-07-13 01:32 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/repository/customer/JdbcCustomerRepository.java
> +            logger.error("Got empty result", e);
사실 로그를 처음 사용해봐서 아직 저만의 기준은 없긴한데, 즉시 해결해야 하는 상황을 error 레벨로 봤습니당!

2023-07-13 01:34 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/controller/CustomerController.java
> +        consoleView.showAllCustomers(outputList);
저도 동의합니다..! 서비스 단에서 처리하는 게 좋을 것 같아욤

2023-07-13 03:01 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/controller/CustomerController.java
> +        var request = CustomerCreateRequestDto.of(name, email);
그게 좋을 것 같아요!!

2023-07-13 03:19 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/domain/voucher/FixedAmountVoucher.java
> +    }
피드백과 좋은 자료 정말 감사합니다! 제가 아직 많이 부족한 건지 보내주신 아티클이 잘 이해가 안 가는 것 같아요..!ㅠ😭 시간 갖고 더 공부해보도록 하겠습니다!!

2023-07-13 03:20 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/AppRunner.java
> +            logger.info("프로그램 시작.");
무의미한 로그 같습니다,,!

2023-07-13 03:26 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/AppRunner.java
> +            switch (menuType) {
else if는 범위를 체크하거나 (<, >), 체크해야 할 조건이 여러개 있을 때, case가 적을 때 주로 사용하는 것 같습니다.
switch는 그 외에 사용하는 것 같아요!

2023-07-13 03:35 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/AppRunner.java
> +@AllArgsConstructor
`@AllArgsConstructor`는 모든 필드에 대해, `@RequiredArgsConstructor`는 초기화 되지 않은 final이나 notnull과 같은 필수 필드에 대한 생성자를 만들어줍니다!
음 근데 이 상황에서는 All이나 Required나 상관이 없을 것 같아욤..!

2023-07-13 04:38 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/controller/voucher/VoucherController.java
> +            logger.error("바우처 생성 실패");
지금 프로젝트로 본다면 어디서 에러가 났는지, 입력값이 무엇이었는지가 궁금할 것 같아요!

2023-07-13 05:06 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/domain/menu/MenuType.java
> +                .orElseThrow(() -> new IllegalStateException(String.valueOf(Error.VALIDATION_WRONG_TYPE)));
`IllegalStatementException`는 부적절한 때에 메서드가 불려 간 것을 나타내고
`IllegalArgumentException`는 부절절한 인수를 줬을 때를 나타낸다고 하네요! 
여기서는 `IllegalArgumentException`가 적절할 것 같아요!

2023-07-13 05:18 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/domain/customer/Customer.java
> +    }
빌더패턴은 선택적 매개변수가 많을 때 유용하다고 알고 있습니다! 그래서 여기서는 정적 팩토리 메소드로도 충분하다는 생각이 들어 사용하였습니다...!🤔

2023-07-13 05:25 UTC, funnysunny08 commented on src/main/java/com/prgrms/spring/io/Output.java
> +    void showMenu();
아뇨,, 개행까진 고려하지 못했습니다..! 이런 것들도 신경써야 하군요..!!💡👍

2023-07-13 05:27 UTC, funnysunny08 commented on src/test/java/com/prgrms/spring/VoucherRepositoryTest.java
> +    private static final Logger logger = LoggerFactory.getLogger(VoucherRepositoryTest.class);
서비스를 배포하고 운영했을 때 발생하는 오류를 해결하고 유지보수하기 위함인 것 같아요!
테스트 코드에서는 필요없을 것 같습니다 !ㅎ.ㅎ

2023-07-14 09:37 UTC, JoosungKwon commented on src/main/java/com/prgrms/spring/repository/customer/JdbcCustomerRepository.java
> +            logger.error("Got empty result", e);
https://jojoldu.tistory.com/712 참고하시면 도움될 것 같아요!

2023-07-24 10:08 UTC, merged