[4기 - 김예슬] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #766
Opened 2023-07-06 15:43 UTC by kys0411

## 📌 과제 설명 
바우처 관리 어플리케이션 2주차 과제

### 1. 설계
![스크린샷 2023-07-06 오후 3.08.35.png](https://github.com/kys0411/dfsdfsdf/assets/62236238/965eb4b8-e0b0-4518-968e-41e509ad618a)

### 2. 객체 역할 & 책임
- VoucherController & CustomerController는 각각 바우처, 고객과 관련된 요청을 다루는 역할이고, 적절한 서비스 기능을 호출할 책임을 가진다.<br>
- VoucherService & CustomerService는 각각 바우처, 고객의 비즈니스 로직 역할이다.<br>
- VoucherRespository & CustomerRepository는 각각 바우처, 고객의 저장소 역할이다.<br>
- Console은 View의 역할이고, 입력과 출력의 책임을 가진다.<br>
- VoucherManagement는 전체 애플리케이션을 구동하는 역할이고, Console의 input으로 들어온 입력을 Voucher or Customer controller로 전달할 책임과, View에 나타낼 값이 있을 때 Console로 출력 값을 전달할 책임을 가진다.<br>

### 3. 요구사항
- [ ]  바우처 관리 애플리케이션에 단위테스트 작성
    - 가능한 많은 단위 테스트코드를 작성
    - 엣지 케이스(예외 케이스)를 고려해서 작성
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해지기
- [ ]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [ ]  바우처 정보를 DB로 관리
    - 바우처에 엔터티에 해당하는 vouchers 테이블 정의
    - 바우처 레포지토리를 만들기 (JdbcTemplate을 사용해서 구현)
    - Vouchers 테이블을 통해서 CRUD 구현

(심화)
- 특정 고객에게 바우처를 할당할 수 있다.
  - 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있다.
  - 고객이 보유한 바우처를 제거할 수 있다.
  - 특정 바우처를 보유한 고객을 조회할 수 있다.

<br>

### --작업할 순서 목록--
- JDBC를 사용한 Voucher Repository 추가
- Voucher Service에 CRUD 구현
- Voucher 관련 테스트코드 작성
- Customer entity 추가
- JDBC를 사용한 Customer Repository 추가
- Customer 관련 기능 추가
- Customer 테스트코드 작성

2023-07-12 02:01 UTC, HyoungUkJJang reviewed
안녕하세요 예슬님 ~ 설계 그려주신거 잘 봤습니다 :)

적절하게 잘 나눠주신 것 같습니다 ! 좋은 것 같아요 !
+ 멘토님이 피드백을 주시면 저는 지금 설계대로 2주차 진행하셔도 좋을 것 같습니다 :)

2023-07-12 07:46 UTC, Jo-GyuHyeon commented
@kys0411 안녕하세요 예슬님 설계 및 소개를 잘 해주셨군요. 👍 

하지만 현재 시간이 많이 지체된 관계로, customer 관련 기능은 제외를 하는 쪽으로 제안 드리고 싶어요.
voucher 관련 먼저 jdbc 로 교체 한 후에 시간이 남는다면 그때 반영 해보는건 어떠한가요? 🤔 
(괜찮으시다면 바로 구현 해주시면 될것 같아요.)

(Repository 관련) 작업 목록을 조금더 작게 나눠보시면 좋을것 같아요. 생각보다 크다고 생각이 들어요. 
조금만 더  짧은 고민해보세요.
그럼 화이팅!! 😃

2023-07-15 08:46 UTC, HyoungUkJJang reviewed
예슬님 코드 잘 봤습니다 ~ 2주차 진행하시느라 고생하셨어요 :) 

먼저 짧은 피드백을 계속 가져가고 싶어서 이번에도 간단한 것 위주로 먼저 리뷰를 남겨봤습니다 ! 
멘토님께서 더 잘 남겨주시겠지만 한번 참고해 보시고 예슬님도 의견을 남겨주시면 좋을 것 같아요 !

+ 추가적으로 예슬님 현재 자바 11을 사용하고 계신 것 같은데  버전을 올리시는건 어떨까요?

2023-07-15 08:46 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/dto/VoucherResponse.java
> +    public VoucherResponse(Voucher voucher) {
DTO가 도메인에 의존해도 괜찮을까요? 필드의 개수가 몇 개 안되는 것 같은데 직접 값을 넘겨줘도 괜찮을 것 같은데 예슬님의 생각은 어떠신가용?

2023-07-15 08:46 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +public class JdbcVoucherRepository implements VoucherRepository {
개인적으로 sql을 쿼리를 직접 작성하시는 경우에 키워드 같은 부분들은 대문자로 적어주는게 가독성이 더 좋을 것 같아요 에슬님의 의견은 어떠신가요?

2023-07-15 08:46 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/constant/VoucherType.java
> +    FIXED((amount) -> amount > 0),
MAX값도 한번 고려해보면 어떨까요?

2023-07-15 08:46 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +    public long inputVoucherId() {
입력에 대한 validation은 필요가 없을까요?

2023-07-15 08:46 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/constant/VoucherType.java
>  public enum VoucherType {
Voucher는 VoucerType을 가지고 있는 것 같은데 패키지의 위치가  적절한지 여쭤보고 싶어요

2023-07-15 08:46 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +        String sql = "insert into customers(name, email) values(?, ?)";
sql에 대해서 개선하기 전에 먼저 상수로 관리해보는건 어떻게 생각하시나요?

2023-07-15 09:05 UTC, kys0411 commented on src/main/java/programmers/org/voucher/exception/ErrorMessage.java
> +    NOT_FOUND_VOUCHER("해당 바우처가 존재하지 않습니다.");
네이밍 다시한번 생각해보겠습니다!!

2023-07-15 09:28 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 남겼습니다.
코멘트를 안남겨서 pending 되어 있었네요ㅠㅠ 간단히게 리뷰 보시고 더 얘기 해보시면 좋을것 같아요.

2023-07-15 19:42 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +        String sql = "insert into customers(name, email) values(?, ?)";
5c732e7 커밋 피드백 반영
- 수정했습니다!

2023-07-15 19:42 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +public class JdbcVoucherRepository implements VoucherRepository {
5c732e7 커밋 피드백 반영
- 수정했습니다!

2023-07-15 19:45 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        int discountAmount = voucherConsole.inputVoucherInfo();
앗 두 가지 데이터가 따로 필요한 경우도 있는데 하나로 합쳐야 할까요?.?

2023-07-15 19:48 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/Command.java
> +                .filter(command -> command.name().equals(type.toUpperCase()))
e6b3efa 커밋 피드백 반영
- 가독성도 그렇고 불필요한 작업을 해주지 않아도 되서 좋은 것 같습니다👍🏻👍🏻

2023-07-15 19:49 UTC, kys0411 commented on src/main/java/programmers/org/voucher/exception/ErrorMessage.java
> +    NOT_FOUND_VOUCHER("해당 바우처가 존재하지 않습니다.");
a620c79 커밋 피드백 반영
- 네이밍 변경했습니다!

2023-07-15 19:54 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
eb2c2e3
- id 값을 이용해 DB에 바우처가 존재하는지 먼저 검증하고 싶었습니다..!
- 현재는 메서드 이름을 바꿨는데 이 부분에 대해서 고민이 많아서 얘기 나눠보고 싶습니다

2023-07-15 19:55 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/MemoryVoucherRepository.java
> +        return Optional.of(voucherStorage.get(id));
725bf7d 커밋 피드백 반영
- 수정했습니다 감사합니다!

2023-07-15 20:00 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/VoucherType.java
> +    private final Predicate<Integer> validation;
d6ec78a 커밋 피드백 반영
- 바우처에서 validation을 수행하도록 수정했습니다.!

2023-07-15 20:02 UTC, kys0411 commented on src/main/java/programmers/org/voucher/dto/VoucherRequest.java
> +    }
e0f6456 커밋 피드백 반영
- dto에서 voucher를 의존하지 않도록 수정했습니다.
- 해당 로직을 voucher service에 두었는데 괜찮을 지 궁금합니다.!

2023-07-15 20:03 UTC, kys0411 commented on src/main/java/programmers/org/voucher/dto/VoucherResponse.java
> +    public VoucherResponse(Voucher voucher) {
e0f6456 커밋 피드백 반영
- dto에서 voucher를 의존하지 않고 값을 직접 넘기는 것으로 수정했습니다.!

2023-07-15 20:04 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/VoucherType.java
>  public enum VoucherType {
f68d1e2 커밋 피드백 반영
- 패키지의 위치를 바우처가 있는 domain의 constant로 변경했는데 괜찮을까요?

2023-07-15 20:08 UTC, kys0411 commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        VoucherRequest request = new VoucherRequest(discountAmount, null);
85a297a 커밋 피드백 반영
- 제가 생각이 짧았던 것 같습니다 ㅜ
- discountAmount만 필요로하는 생성자를 추가했습니다.!

2023-07-15 20:10 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/VoucherType.java
> +    FIXED((amount) -> amount > 0),
d6ec78a 커밋 피드백 반영
- max 값 추가했습니다! 감사합니다👍🏻

2023-07-15 20:15 UTC, kys0411 commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +    public long inputVoucherId() {
앗 혹시 숫자가 아닌 값이 입력되거나 할 때 말씀이신가요?.?

2023-07-16 09:09 UTC, Jo-GyuHyeon requested changes
쿼리문에 대한 리뷰를 남겨 보았어요. 2단계로 나눠서 리뷰를 드리고 싶어요. (추후)

2023-07-16 09:09 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +        jdbcTemplate.update(UPDATE, request.getDiscountAmount(), id);
SQL 문을 상수로 빼니 해당 메서드에서 어떤 행위가 일어나는지 잘 파악이 안되는것 같아요.
상수로 빼는것 만큼 이점이 많을지 고민 해보시면 좋을것 같아요.
2단계로 나눠서 리뷰드리고 싶은데 지금은 1단계로 메서드 내로 쿼리 문은 옮겨 보는 것은 어떨까요?

2023-07-16 16:26 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
네이밍을 바꾸시기를 바랬던건 아니였어요. 어떤 고민이신지 알수 있을까요??
검증 하신 부분은 저도 좋게 생각해요. 다만 어떤 이유인지 궁금했을 뿐더러 검증을 하셨던다면 검증된 voucher 의 활용도 궁금한것 같아요.

2023-07-16 16:28 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/dto/VoucherRequest.java
> +    }
넵 괜찮은것 같아요. 다만 toEntity는 별도의 메서드를 분리 하기 보다 create 메서드내의 인라인으로 로직이 있으면 더 자연스러울것 같아요.

2023-07-17 05:41 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
get 메서드에서는 검증된 Voucher를 사용해 response로 반환하지만, update와 delete 메서드에서는 사실 Voucher 객체가 필요하지 않아서 get, update, delete가 같은 메서드(validateVoucherExist)를 사용해도 되는지 고민이었습니다 ㅜㅜ 메서드를 따로 만들기에는 로직이 너무 같아서 애매한 부분이 있는 것 같습니다..

2023-07-17 05:46 UTC, kys0411 commented on src/main/java/programmers/org/voucher/dto/VoucherRequest.java
> +    }
38232fd 커밋 피드백 반영
- 정말 create 메서드 안에 있는 것이 의미 전달도 쉽고 더 자연스러운 것 같습니다👍🏻👍🏻 
- 수정하였습니다! 감사합니다

2023-07-17 05:48 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +        String sql = "insert into customers(name, email) values(?, ?)";
@Jo-GyuHyeon 형욱님께 DM으로 한번 여쭤봤었는데 납득이 가는 이유라 반영했던 것 같습니다🥲 다시 수정하겠읍니다!.!

2023-07-17 05:57 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +        jdbcTemplate.update(UPDATE, request.getDiscountAmount(), id);
3b675aa 커밋 피드백 반영
- 메서드 단위로 봤을 때 sql 문이 메서드 내에 있는 것이 로직을 파악하기에 좋은 것 같습니다!
- 수정하였습니다 감사합니다👍🏻

2023-07-17 11:27 UTC, HyoungUkJJang reviewed
간단히 추가 코멘트 남겼습니다 ~ 참고해주시면 좋을 것 같아요 !

2023-07-17 11:27 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +    public long inputVoucherId() {
@kys0411  넵 안해도 충분히 안전할까용? 콘솔 에서도 기본적인 데이터에 대한 검증이 있는건 어떻게 생각하시는지 여쭤보고 싶었어용

2023-07-17 11:27 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +        String sql = "INSERT INTO vouchers(discount_amount, type) VALUES (?, ?)";
이 문자열 수준의 sql을 빌더 형태로 만들어서 더 깔끔하고 휴먼 에러를 방지할 수 있도록 만들어 보시는건 어떨까요?

2023-07-17 11:27 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/controller/VoucherController.java
> +        int discountAmount = voucherConsole.inputVoucherInfo();
음 VoucherRequest로 받아 볼 수 있지 않을까 라는 생각을 한번 해봤어요 따로 필요한 경우가 있다면 지금 형태도 괜찮은 것 같네용

2023-07-17 11:27 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/domain/Customer.java
> +
이건 사실 개인 취향일 것 같지만 저는 필드 마다 개행처리 까지 해줄 필요는 없다고 생각을 하고있습니다. 관련있는 것 끼리 구분감만 지어줘도 저는 충분할 것 같은데 예슬님의 생각은 어떠신가요?

2023-07-17 11:27 UTC, HyoungUkJJang commented on src/main/java/programmers/org/voucher/constant/Command.java
>      EXIT;
아래 형태가 데이터를 추가하고 삭제하는데 관리하기 편하실 거에요 :) 

```suggestion
    FIND,
    UPDATE,
    DELETE,
    EXIT
    ;
```

2023-07-17 20:32 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
2가지 정도 말씀드릴수 있을것 같아요. void 이기에 검증하지 않아도 무방하다고도 생각해요.
애초에 존재 하지 않는 데이터 이기에 수정, 삭제를 하지 않게 될거에요.

하지만 사용자에게 친절하게 할려주신다면 존재여부를 보고 예외를 발생시켜도 좋다고도 생각해요.

exit 가 아닌 find 를 사용하셨는데 (중요하지 않아요.) return 이 있는 메서드인 만큼 리턴 값을 받고 해당 객체를 이용하시는건 어떨까 생각해요. 무조건 적용해라라기 보다 관련해서 얘기를 나누고 싶은 마음에 리뷰를 남기게 되었어요.
(지금 처럼 같은 파라미터를 사용하셔도 무방하긴 해요)

2023-07-18 01:24 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 드렸어요.
쿼리 빌더를 만들어 보시는것도 좋고, try catch 를 사용하지 않고 단건 조회 기능을 완성 해보시는것도 좋을것 같아요.
고생하셨어요. 🙇

2023-07-18 01:24 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +        }
try catch 를 사용하지 않는 방법으로 로직을 완성 할 수 있을것 같아요. 
queryForObject() 내부를 보시면 힌트가 될 것 같아요.

2023-07-18 13:08 UTC, kys0411 commented on src/main/java/programmers/org/voucher/constant/Command.java
>      EXIT;
36da880 커밋 피드백 반영
- 수정하였습니다 감사합니다!

2023-07-18 13:22 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +        }
d81d273 커밋 피드백 반영
- 수정하였습니다..!

2023-07-18 13:46 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +        String sql = "INSERT INTO vouchers(discount_amount, type) VALUES (?, ?)";
e76d160 커밋 피드백 반영
- 쿼리 빌더를 만들어보았는데 감이 잘 안와서 이렇게 하는게 맞을지 모르겠습니다,,

2023-07-18 14:41 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
멘토님 말씀해주신 것처럼 리턴된 voucher 객체를 이용하고 싶어서 방법을 생각해보았지만 수정, 삭제에서의 용도가 정말 생각이 나지 않아서 코드에서 변경된 점은 없습니다ㅜ!
사용자에게 해당 id의 바우처 존재 여부는 알려주고 싶어서 검증 로직은 그대로 두고 싶습니다.!

2023-07-19 18:25 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
존재 여부 알려주는 부분은 저도 좋아요.
exit 이나 valid 가 아닌 find 이니 return 으로 voucher 를 받고 voucher 를 이용하여 아래의 로직을 수행 할 수 있다라는 의견이였어요.
```
var voucher = findVoucherById(id);
voucherRepository.update(voucher.getId(), request);
```

2023-07-20 03:34 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 드렸어요.
중복되는 내용이 있을 수 있지만, 각 라인마다 달진 않았어요.
쿼리 빌더 같은 경우에 각각 Root 레벨로 쪼개서 각 빌더를 만들어 보시는것을 제안 드리고 싶어요. 
고생하셨어요.

2023-07-20 03:34 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +            return -1;
-1 을 리턴하기 보다 의미 있는 상수를 사용 하는건 어떨까요???
예외를 발생 시켜도 좋을수도 있을것 같아요.

2023-07-20 03:34 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/util/QueryGenerator.java
> +        }
table 을 String 이 아니라 다른 타입으로 받으면 어떨까요?
타입언어의 장점을 이용하여 컴파일러의 도움을 받아 볼까요?
String 은 타입이 없는 것 처럼 보든 값이 들어 갈 수 있다고 생각해요.

2023-07-20 03:34 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/util/QueryGenerator.java
> +        }
Where 도 별도의 Builder 를 만들어 볼까요? 여러 조건들이 많이 생길 수 있을것이라 생각해요.

2023-07-20 03:34 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +    public void create(VoucherRequest request) {
Request 를 받기 보다는 필요한 인자들만 받는건 어떨까요?
서비스단에서 Request를 받을 수도 있지만, 한편으로는 하위 계층이 상위를 의존 하고 있지 않을까요?
하위 계층은 사용을 하고 있으니 알수 밖에 없는데, 상위는 모르는게 자연스럽다고 생각해요.
또한 그런 관계들과 상관없이 파라미터 수가 적어서 풀어서 나열해도 좋을것 같아요

2023-07-20 03:34 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +    }
위와 동일해요.

2023-07-22 09:46 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
엇 멘토님 그렇다면 update메서드의 파라미터로 받는 id와 voucher.getId가 같은데 굳이 voucher.getId로 써도 ㄱ

2023-07-22 09:49 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
엇 멘토님 그렇다면 update메서드의 파라미터로 받는 id와 voucher.getId가 같은데 voucher 객체를 사용하기 위해 getId를 사용한다는 말씀이신거 맞을까요?.?

2023-07-22 11:04 UTC, kys0411 commented on src/main/java/programmers/org/voucher/io/VoucherConsole.java
> +            return -1;
412847f 커밋 피드백 반영
- 예외를 발생시키도록 수정했습니다!.!

2023-07-22 11:07 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +    public void create(VoucherRequest request) {
f7f1dce 커밋 피드백 반영
- dto를 사용하지 않고 직접 넘겨주도록 수정하였습니다!

2023-07-22 11:07 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +    }
f7f1dce 커밋 피드백 반영
- dto를 사용하지 않고 직접 넘겨주도록 수정하였습니다!

2023-07-22 11:08 UTC, kys0411 commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +    public void create(VoucherRequest request) {
멘토님 혹시 여기서 말씀하신 상위, 하위 계층이 controller와 service를 말씀하시는 것일까요,,?

2023-07-22 11:10 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/util/QueryGenerator.java
> +        }
979b26b 커밋 피드백 반영
- where 빌더를 만들어 보았습니다,,
- 지금 보니 커밋 단위가 너무 컸던 것 같습니다 죄송합니다 ㅜㅜ

2023-07-22 11:12 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/util/QueryGenerator.java
> +        }
3661fb9 커밋 피드백 반영
- 테이블을 enum 으로 만들어서 입력받도록 수정하였습니다!

2023-07-23 07:53 UTC, HyoungUkJJang approved these changes
고생하셨습니다 예슬님 :) 쿼리빌더 잘 만들어주신 것 같습니다. 👍🏻

멘토님은 추가 피드백이 있으실 수도 있지만 저는 지금도 충분히 많이 고민하시고 잘 만들어주신 것 같습니다 :)  
 
혹시 개인적으로 더 이야기를 나눠보고 싶은 부분이 있으시다면 게더에서 구두로 진행하면 좋을 것 같습니다 !

2023-07-23 08:25 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +    public void create(VoucherRequest request) {
맞아요. 레이어를 말하는 것이였고, 레이어가 아니더라도 의존 관계가 있는 쪽을 하위라고 표현 하게 되는 것 같아요.

2023-07-23 08:26 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/util/QueryGenerator.java
> +        }
관련 내용이 커서 새로운 리뷰로 남기도록 할게요.

2023-07-23 08:55 UTC, Jo-GyuHyeon requested changes
쿼리 빌더를 고민을 많이 하셨네요.
다만 패키지가 너무 많이 나눠져 있지 않은지 생각 해보시면 좋을것 같아요.
~~지금은 쿼리 빌더를 직접 사용하지 않으신것 같아요.
직접 적용 해보시고 다시 코드 리뷰를 받으면 어떨까요?~~

2023-07-23 08:55 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/config/AppConfig.java
> +    }
AppConfig 를 지우고 Component 어노테이션을 사용하는 쪽으로 변경 해볼까요?

2023-07-23 08:55 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/domain/Voucher.java
> +        if (discountAmount <= 0 || discountAmount > 100) {
개인적인 취향으로 숫자 범위는 `최소 < 비교 값 < 최대 ` 형식이 가독성이 좋아 보였어요.
최대한 if 문에 연산식을 사용하지 않도록 해보면 어떨까요?
도메인 규칙 및 여러 사람들에게 커뮤니케이션을 할때, 케이스를 명확이 전달 시켜야 될때가 있을거에요. 그걸 코드에서도 같이 적용 해보면 어떨까요?

2023-07-23 08:55 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/util/statement/Where.java
> +    }
Where 생성에 위험성은 없을까요??
누군가 Where 문을 바로 생성 했을때 이슈는 없을지 고민 해보시면 좋을것 같아요.

2023-07-23 08:55 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/util/statement/Where.java
> +        }
여러 조건의 where 문을 만들수 있을까요??

2023-07-23 17:11 UTC, Jo-GyuHyeon requested changes
적용하신 부분은 지금 발견하였네요. 전반적으로 모든 Repo 에 쿼리 빌더를 적용 해볼 수 있을까요?

2023-07-23 17:11 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +                .build();
Select.Builder() 와 SelectBuilder() 의 차이점은 무엇인가요? 하나로 통일 해도 좋지 않을까요?

2023-07-24 04:21 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/util/statement/Where.java
> +        }
여러 조건이라 하시면 where voucher_id=?, discountAmount=? 이렇게 말고도
숫자 비교나, 다른 연산자(in, not in, llike...)들도 적용할 수 있게끔 하라는 말씀이실까요??

2023-07-25 09:24 UTC, kys0411 commented on src/main/java/programmers/org/voucher/config/AppConfig.java
> +    }
c334aa5 커밋 피드백 반영
- Component 어노테이션 사용하도록 수정했습니다!

2023-07-25 09:25 UTC, kys0411 commented on src/main/java/programmers/org/voucher/domain/Voucher.java
> +        if (discountAmount <= 0 || discountAmount > 100) {
f75b124 커밋 피드백 반영
- if문에 연산자를 쓰지 않도록 수정했습니다!

2023-07-25 09:26 UTC, kys0411 commented on src/main/java/programmers/org/voucher/domain/Customer.java
> +    }
ba576fc 커밋 피드백 반영
- 으악,, 수정했습니다! 감사합니다😭

2023-07-25 09:27 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/util/statement/Where.java
> +    }
ab11614 커밋 피드백 반영
- 생성자를 private으로 변경했습니다!

2023-07-26 05:52 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/util/statement/Where.java
> +        }
ece6dc7 커밋 피드백 반영
- where builder 전체적으로 수정했습니다..!

2023-07-26 05:53 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcVoucherRepository.java
> +                .build();
57bb494 커밋 피드백 반영
- Select builder 하나로 합치고 전체적으로 수정하였습니다..!

2023-07-26 11:57 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/domain/Voucher.java
> +        if (discountAmount <= 0 || discountAmount > 100) {
비교 연산도 제거 해보시면 좋을것 같아요.

2023-07-26 11:58 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/service/VoucherService.java
> +        voucherRepository.deleteById(id);
구두로 진행 하였기에 resolve 처리 할게요.

2023-07-26 11:59 UTC, Jo-GyuHyeon commented
쿼리 빌더 관련해서는 다른 레포에서 개인 리뷰를 진행 하기에 해당 리뷰를 마무리하고 여기에 적용 해보시는걸 제안 드리고 싶어요.

2023-08-07 14:01 UTC, Jo-GyuHyeon approved these changes
쿼리 빌더를 구현 하셨군요. 
고생하셨어요.
간단한 리뷰를 남겨 두었는데 생각 해보시면 좋을것  같아요.
지금 반영 하시기 보다 생각으로만 마무리 되셨으면 좋겠어요.
지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-07 14:01 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +        String sql = insert.getQuery();
sql 보다 의미 있는 네이밍이면 좋을것 같아요.
insertQuery 라고 하면 어떨까요?

2023-08-07 14:01 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +            return statement;
자체적으로 쿼리 빌더를 만들었다면 PreparedStatement 도 좋지만 Statement 도 괜찮겠다는 생각도 해보았어요.
(반영 해야 하기 보다 생각이 들어서 공유를 해보고 싶었어요.)

2023-08-07 14:01 UTC, Jo-GyuHyeon commented on src/main/java/programmers/org/voucher/repository/util/Insert.java
> +            }
인덱스를 지양 하시면 좋을듯해요. bound 관련 예외가 발생 할 수 도 있지만 변경 추척이 어려울 수도 있다고 봐요.
56 번째 라인에서 삼항 연산자의 조건을 파악하기 어려 운것 같아요. 
다른 방식으로 풀어 낼수도 있지만 현재 코드로만 보았을때는 의미 있는 boolean 변수를 사용 하시면 가독성이 더 증가 될것 같아요.
(하지만 다른 방식으로 접근 하실수도 있다고 생각해요)

2023-08-07 16:19 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +        String sql = insert.getQuery();
넵!! 너무 다 sql로 통일한 것 같습니다 ㅜ

2023-08-07 16:21 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/util/Insert.java
> +            }
넵!! 다른 방식도 생각해보겠습니다 감사합니다~!!

2023-08-07 16:23 UTC, kys0411 commented on src/main/java/programmers/org/voucher/repository/JdbcCustomerRepository.java
> +            return statement;
네! 맞습니다!! Statement 사용해서 따로 수정해보겠습니다! 감사합니다

2023-08-07 16:24 UTC, merged