[4기 - 배준일] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #779
Opened 2023-07-08 14:10 UTC by bjo6300

## 👩‍💻 요구 사항과 구현 내용 

- [X] 바우처 관리 애플리케이션 단위테스트 작성
- [X] 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용
  - customers 테이블 정의 및 추가
  - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [X] 바우처 정보를 DB로 관리
  - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
  - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
  - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 

- voucherMapper를 이용해서 DTO 변환 기능을 분리했습니다. 분리해서 사용하니 객체지향 생활 체조 원칙의 "규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다."를 지키지 못했습니다. DTO 변환 기능을 분리하지 말고 필요한 상황만 DTO로 변환하는게 맞는지 궁금합니다!

2023-07-08 19:45 UTC, JoosungKwon reviewed
준일님 2주차 과제도 고생하셨습니다~!! 😄

전반적으로 잘 해주셨네요~~ 👍 리뷰 남겼으니 간단하게 참고만 해주세요~!! 
그리고 1주차가 마무리 되었다면 멘토님께 이야기 드려서 Merge 부탁드려요~ 

리팩터링이랑 테스트 코드 작성 까지 화이팅하시길 바랍니다~~!! 

질문하신 내용에 답변 드리자면

> voucherMapper를 이용해서 DTO 변환 기능을 분리했습니다. 분리해서 사용하니 객체지향 생활 체조 원칙의 "규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다."를 지키지 못했습니다. DTO 변환 기능을 분리하지 말고 필요한 상황만 DTO로 변환하는게 맞는지 궁금합니다!

- 저는 객체지향 체조를 무분별하게 지키는 것 보다 상황에 맞게 사용하는 것이 좋다고 생각합니다! 사실 DTO 변환 기능이랑 7번 원칙이랑 어떤 관련이 있는지 잘 이해하지는 못했습니다..

- 변환 기능 분리랑 필요한 상황에만 DTO 변환하는게 맞는냐는 질문도 잘 이해가 안되네요..😢 DTO가 늘어날 수 있는 상황을 고려해서 Mapper를 만드는 것은 어떻게 생각하느냐에 따라 다를 수 있지만 저는 괜찮다고 봅니다. 그리고 필요한 상황에만 DTO로 변환해야 하는 것도 맞고요.. 

- 제가 혹시 잘못 이해했거나 궁금한 점 있으시면 다시 이야기해주시면 감사하겠습니다!

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/VoucherJdbcRepository.java
> +  private final Logger LOG = LoggerFactory.getLogger(VoucherJdbcRepository.class);
static이어도 괜찮지 않을까요? 일반 인스턴스 변수로 두신 이유가 있나요?

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/FixedAmountVoucher.java
> +  }
왜 메서드를 나누신거죠?

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/PercentDiscountVoucher.java
> +  }
해당 `Voucher`는 할인 기능을 사용하기 전에는 `discountPercent` 변수가 올바른 값인지 검증할 수 없네요.. 그렇다면 올바르지 못한 값을 가진 Voucher가 저장될 가능성이 있어 보입니다~ 어떻게 생각하시나요?

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/request/VoucherCreateRequest.java
> +@Builder
이건 그냥 여담인데 어노테이션 순서에 일관성이 있다면 보기 더 좋을 것 같아요!

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/mapper/VoucherMapper.java
> +  }
`Mapper` 클래스를 사용해서 변환 로직을 외부로 분리하는 것에 대해 어떤 생각을 가지고 계신지 궁금합니다~ 그리고 빌더를 사용하신 의도도 궁금하네요..

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +    int updated = template.update(sql, param);
음.. 뭐가 update 되는 건가요..? 😅

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +            UUID.fromString(resultSet.getString("customer_id")),
속성 명을 상수로 두는 것에 대해 어떻게 생각하시나요?

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +  }
적용이 안된것 같아요~~ 그리고 최소값 뿐만 아니라 최대 값도 검증하면 좋을 것 같습니다!

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +public class VoucherController implements Runnable {
제 개인적으로는 `Controller`가 `실행(run)메서드`를 가지고 있는 것 자체가 부자연스럽다고 생각합니다. `Controller`의 역할은 뭐라고 생각하시나요?

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +            continue;
`break`이 아니고 `continue`를 사용하신 이유가 궁금하네요

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +        return;
예외 메시지는 따로 안남기나요..?

2023-07-08 19:45 UTC, JoosungKwon commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +            voucherService.createVoucher(inputVoucherType, inputDiscount);
3주차에서 웹으로 변경되는데 코드 변경이 최소화 될 수 있는 방향으로 고민해보시면 좋을 것 같아요!

2023-07-09 14:39 UTC, bjo6300 commented on springboot-basic/src/main/resources/application.yml
> +    password: 12345678
로컬 DB를 테스트 용도로 사용하면 개발환경이 변경될 경우 동작하지 않을 수 있습니다. 현재는 개인 프로젝트라 저만 사용하는 상황이라 로컬 DB로 구성했지만, 팀 프로젝트 시 Docker를 이용해 일관된 개발환경을 구성하겠습니다!
295f8aadd98548b138281cad6949b24ebb652e16

2023-07-09 14:40 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Input.java
> +@Component
앗... 수정하겠습니다 🥲

69fceedf90f7290b732f51ea62fbbc96df1f733b

2023-07-09 14:43 UTC, bjo6300 commented on springboot-basic/src/main/resources/schema.sql
> +#     foreign key (customer_id) references customer (customer_id)
2주차 심화부분 설계하다가 기록이 남았네요..! 지우고 기능 구현할 때 다시 적겠습니다!

2023-07-10 00:38 UTC, graygreat requested changes
안녕하세요 준일님 :)

미션하느라 고생 많으셨습니다! 노력의 흔적이 많이 보이네요 👍 
주성님이 리뷰를 잘 해주셔서 저는 추가적으로 궁금한 사항들 몇개 남겨놨습니다 ㅎ
확인 해주시고 답변 부탁드려요!

추가로 준일님 코드를 보면서 든 생각이 통일성이 있으면 더 좋겠다 생각이 들었습니다.
어떤 것은 static final로 되어 있고, 또 다른 것은 final로만 되어 있는 경우도 있고, 변수의 위치, 어노테이션의 위치 등등 코드에 통일성을 더하면 훨씬 더 보는 사람이 이해하기 쉬울 것 같아요!
머리를 써야하는 내용은 아니지만 은근히 귀찮을 수 있는 포인트라 지금부터라도 트레이닝 해나가면 더 좋은 코드가 될 수 있을 것 같아요 :)

> voucherMapper를 이용해서 DTO 변환 기능을 분리했습니다. 분리해서 사용하니 객체지향 생활 체조 원칙의 "규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다."를 지키지 못했습니다. DTO 변환 기능을 분리하지 말고 필요한 상황만 DTO로 변환하는게 맞는지 궁금합니다!

우선 저는 준일님이 mapper를 사용한 이유가 궁금합니다.
저 같은 경우는 dto 자체에서 변환 로직을 구현하고 있는데, 특정 엔티티나 특정 타입을 dto로 변환하는 것은 그 자체의 책임이고 굳이 mapper를 두어서 관리 포인트를 2개로 만들 이유가 없다고 생각하기 때문에 이러한 방법을 선택하고 있습니다.
혹시 준일님은 어떠한 이유 때문에 mapper를 사용하시는지 알려주신다면 한 수 배워가겠습니다 ㅎㅎ

> 테스트 코드 빠른 시일 내에 작성하겠습니다!

넵!
추가로 테스트 코드에 대한 훈련 팁을 드리자면, 현재 모든 기능을 다 작성하시고 테스트 코드를 작성하시는 것 같은데, 이렇게 하면 테스트 코드에 대한 훈련을 하기가 힘들어요.
요구사항을 내가 테스트 할 내용 위주로 작성하고 특정 기능을 구현한 후 테스트 코드를 바로바로 작성하는 훈련을 하는게 많은 도움이 될 것 같습니다 :)

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +package com.example.commandlineapplication.domain.customer.model;
package가 너무 딥한 것 같은 느낌이 있네요.
너무 딥해지면 오히려 패키지 구조에 대해 혼란이 오고 관리가 복잡해질 수 있다는 단점이 있을 것 같아요.
저는 도메인 패키지 내에 각자 도메인 정도만 묶어둡니다 ㅎㅎ

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +  private static final int SUCCESS_EXECUTE = 1;
준일님은 어떤 기준으로 변수 선언 위치를 정하시는지 궁금합니다~

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +      LOG.error("customer가 저장되지 않았습니다.");
해당 로그를 보고 어떤 데이터가 저장되지 않았는지 알 수 있을까요?

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +      throw new RuntimeException("이름은 빈칸이 될 수 없습니다.");
RuntimeException을 상속받고 있는 예외들을 던져주는 것과 RuntimeException을 던져주는 것은 어떠한 차이가 있나요?

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerRepository.java
> +public interface CustomerRepository {
인터페이스 굿~
JPA나 Mybatis 같은 걸로 바꿔도 유연하게 바꿀 수 있는 코드가 되겠네요 💯

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/mapper/VoucherMapper.java
> +public class VoucherMapper {
해당 기능의 목적이 무엇인가요?

도메인을 dto로 변환해주기 위한 목적인 것 같은데, 맞을까요?
그렇다면 mapper를 만드신 이유가 궁금합니다 ㅎ

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/response/VoucherResponse.java
> +  private final long discountAmount;
어떤 클래스는 한칸 띄워져있고, 어떤건 안띄워져있어서 통일성을 가져보면 어떨까 생각이 듭니다 ㅎ

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/FixedAmountVoucher.java
> +  private final long MIN_DISCOUNTED_PRICE = 0L;
변수를 final로 선언해준 것과 static final로 선언해주는 것은 어떠한 차이가 있나요?

기존에 준일님은 static final로 상수화 시켜주신 것 같은데, 이것은 해당되지 않아서 여쭤봅니다.

2023-07-10 00:38 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/VoucherType.java
> +
불필요한 개행

2023-07-10 05:56 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherService.java
> +  private final VoucherJdbcRepository voucherRepository;
인터페이스 주입 방식으로 변경했습니다!
69fceedf90f7290b732f51ea62fbbc96df1f733b

2023-07-10 05:58 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherService.java
> +  }
데이터 관리에 위험할 것 같습니다! 콘솔에서 사용하지 않고, 요구사항에 없으므로 삭제하겠습니다!

2023-07-10 06:06 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/VoucherJdbcRepository.java
> +  private final Logger LOG = LoggerFactory.getLogger(VoucherJdbcRepository.class);
로그는 공통적으로 같은 값을 가지고 있기 때문에 static이어도 괜찮아 보여요! 수정하겠습니다! (참고한 링크 : https://sihus.tistory.com/18)
69fceedf90f7290b732f51ea62fbbc96df1f733b

2023-07-10 07:21 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/FixedAmountVoucher.java
> +  }
검증 로직을 구현하려다가 잊어버렸습니다...🥲 수정하겠습니다!
be34c08a02dc4825be8afe0f63db4085d5830c92

2023-07-10 08:29 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/FixedAmountVoucher.java
> +  private final long MIN_DISCOUNTED_PRICE = 0L;
static이 붙은 변수는 프로그램 실행 시 메모리에 자동으로 생성되고 메모리에서 바로 호출할 수 있기 때문에 인스턴스 변수보다 빠릅니다. 

매직넘버 중 단 한번만 사용하는 변수도 static을 붙여야 하는지 궁금합니다. 
`인스턴스 변수를 한번 생성해서 사용하는 비용 vs static으로 메모리에 올려서 한번 사용` 
조사하다가 의문이 생겨서 여쭤봐요!

2023-07-10 08:38 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/response/VoucherResponse.java
> +  private final long discountAmount;
google java format 플러그인의 자동 정렬 기능은 클래스 시작 시 한 칸 띄워주더라구요! 통일시키겠습니다ㅎㅎ

2023-07-10 08:49 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +package com.example.commandlineapplication.domain.customer.model;
`도메인 패키지 내에 각자 도메인 정도만 묶어둔다.`라는게 customer 패키지 안에 repository, service, entity 모두 넣는다는 말씀이실까요??

2023-07-10 09:18 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherService.java
> +    LOG.info("Voucher가 저장되었습니다.");
현재는 불필요한 로그로 생각이 드네요. 부가적인 로그를 추가해서 활용 범위를 늘렸습니다!
a6eafd52ae8c43bc9fd35829cf7a4affce257a66

2023-07-10 09:29 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/service/VoucherFactory.java
> +        throw new IllegalArgumentException("잘못된 바우처 유형입니다.");
로그는 로그 파일에 기록하는 용도이고, 예외 처리는 사용자에게 알려주기 위해 작성했습니다!

2023-07-10 10:02 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/VoucherJdbcRepository.java
> +      throw new RuntimeException("voucher가 삭제되지 않았습니다.");
수정했습니다!
6398d4b1dd9b0d5879201c0705c6198b032af007

2023-07-10 13:11 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +  private static final int SUCCESS_EXECUTE = 1;
필요한 시점에 순차적으로 생성하다보니 통일성이 없었네요...! 수정하겠습니다!
84937202893cf01a8eb1525dfd7349d4623c772f

2023-07-10 13:11 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/repository/VoucherJdbcRepository.java
> +  private static final int SUCCESS_EXECUTE = 1;
필요한 시점에 순차적으로 생성하다보니 통일성이 없었네요...! 수정하겠습니다!
84937202893cf01a8eb1525dfd7349d4623c772f

2023-07-10 13:18 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +            continue;
CREATE 기능 동작 이후에 DELETE 기능으로 바로 넘어가서 continue를 사용했습니다!

2023-07-10 13:21 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +        return;
헉 가장 중요한걸 빼먹었네요..! 추가했습니다!

2023-07-10 13:42 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/request/VoucherCreateRequest.java
> +@Builder
알파벳 순으로 정렬해서 일관되게 했습니다!
fe3a75117223ca16c63eb4806782d6f01bfb6cc2

멘토님은 어떤 순서로 정렬하시나요??

2023-07-11 00:05 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +package com.example.commandlineapplication.domain.customer.model;
domain/customer 안에 model을 굳이 둘 필요가 있을까 라는 얘기였습니다 ㅎㅎ

2023-07-11 00:10 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/FixedAmountVoucher.java
> +  private final long MIN_DISCOUNTED_PRICE = 0L;
저는 상수화 시키는 변수는 다 붙이는 편인데, 이건 준일님 만의 이유가 있으면 될 것 같아요 ㅎ
선호도의 차이가 좀 있는 것 같긴 하네요.

2023-07-11 00:10 UTC, graygreat commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/VoucherType.java
> +
또 플러그인을 사용하신다면, 그냥 그대로 두는게 나을 것 같네요 ㅎ
보통은 띄우지 않는 것 같아요

2023-07-13 03:41 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/PercentDiscountVoucher.java
> +  }
Voucher 생성 시점에 검증해야겠네요! 수정하겠습니다!

2023-07-13 03:51 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/mapper/VoucherMapper.java
> +  }
기존에는 `service`에서 변환 로직을 관리했다가 변환 로직이 많아지거나 변경이 필요한 경우에 가독성이 떨어지는 것 같아서 mapper로 분리했습니다!

2023-07-13 03:52 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/dto/mapper/VoucherMapper.java
> +public class VoucherMapper {
기존에는 `service`에서 변환 로직을 관리했다가 변환 로직이 많아지거나 변경이 필요한 경우에 가독성이 떨어지는 것 같아서 mapper로 분리했습니다!

2023-07-13 04:32 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/model/FixedAmountVoucher.java
> +  private final long MIN_DISCOUNTED_PRICE = 0L;
FixedAmount가 생성될 때마다 FixedAmount 내부의 인스턴스가 계속 생성되므로 static으로 만드는게 좋을 것 같아요!

`인스턴스 변수를 한번 생성해서 사용하는 비용(MIN_DISCOUNTED_PRICE) vs static으로 메모리에 올려서 한번 사용` 
이건 정해진 답이 있었네요...!

2023-07-13 04:41 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +      LOG.error("customer가 저장되지 않았습니다.");
알 수 없을 것 같습니다! customerId 같은 식별자를 추가하겠습니다!

2023-07-13 05:23 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +package com.example.commandlineapplication.domain.customer.model;
아하 그렇군요! 혹시 한 도메인에 model 파일 개수가 많아지는 경우에도(4~5개 이상) 그렇게 하시나요??

2023-07-13 06:08 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +      throw new RuntimeException("이름은 빈칸이 될 수 없습니다.");
RuntimeException을 던져주면 RuntimeException 중 어떤 예외가 발생했는지 알 수 없습니다. 그러나 RuntimeException을 상속받고 있는 명시적인 예외를 던져준다면 명확한 이유를 알 수 있습니다!

2023-07-13 06:34 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +    int updated = template.update(sql, param);
기능 구현을 잘못 했네요... 😅
수정했습니다! ea03687d262430882bcb3fd20957cc3852b69177

2023-07-13 06:44 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/repository/CustomerJdbcRepository.java
> +            UUID.fromString(resultSet.getString("customer_id")),
속성 명은 변할 가능성이 적고 자주 사용되므로 상수로 두는 것이 좋아보여요!

2023-07-23 13:28 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/voucher/controller/VoucherController.java
> +public class VoucherController implements Runnable {
사용자가 접근한 URL에 따라 사용자의 요청사항을 파악한 후에 그 요청에 맞는 데이터를 Model을 의뢰하고, 데이터를 View에 반영한다고 생각합니다. 1차 미션을 기준으로 구현해서 VoucherController로 이름 지었고, 해당 voucher는 controller가 필요하기 때문에 이름을 수정했습니다! 
56082f9acc7ad5c155d6f3cd176d8ea235130230

2023-07-23 14:44 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Console.java
> +  private final VoucherService voucherService;
첫 번째 PR 리뷰에서 VoucherService에서 출력의 역할까지 담당하는건 좋지 않다 하셔서 console에서 출력을 담당하게 했습니다! 그러나 console에서 출력을 담당하게 하다보니 console이 voucherService에 의존하게 되어 두 번째 PR 리뷰에서 지적받았습니다.
저는 printHistory 기능이 voucherService의 한 기능이라 생각해서 console에서 담당하는 것보다는 voucherService에서 담당하게 만들어 console의 voucherservice 의존을 줄이는게 더 좋다고 생각하는데 멘토님 생각은 어떠신가요??
관련 PR 링크
1차 PR : [https://github.com/prgrms-be-devcourse/springboot-basic/pull/779/files/1bde2059e8fc533b8165046064b337a4f824917f#diff-33ee020f2e9[…]217978e52cbf37236](https://github.com/prgrms-be-devcourse/springboot-basic/pull/779/files/1bde2059e8fc533b8165046064b337a4f824917f#diff-33ee020f2e92fb1497d0c92bf951884760a8a7be071fbf7217978e52cbf37236)
2차 PR : [https://github.com/prgrms-be-devcourse/springboot-basic/pull/779/files/1bde2059e8fc533b8165046064b337a4f824917f#diff-33ee020f2e9[…]217978e52cbf37236](https://github.com/prgrms-be-devcourse/springboot-basic/pull/779/files/1bde2059e8fc533b8165046064b337a4f824917f#diff-33ee020f2e92fb1497d0c92bf951884760a8a7be071fbf7217978e52cbf37236)

2023-07-24 15:44 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Console.java
> +  private final VoucherService voucherService;
Console에서 VoucherService를 의존하는 것 보다 VoucherController에서 Console, VoucherService를 의존하게 하는게 더 좋아보여요! 수정했습니다!

436f361963a57dfb4fb284793224dea6ebb08b67

2023-07-24 16:09 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/global/io/Command.java
> +        .orElseThrow(() -> new IllegalArgumentException("잘못된 명령어입니다." + inputCommand));
자료 이용해서 최적화했습니다!
f09caa553aa6945f8d560b9aca27515e0fb600a5

2023-07-24 16:23 UTC, bjo6300 commented on springboot-basic/src/main/java/com/example/commandlineapplication/domain/customer/model/Customer.java
> +  }
적용했습니다!
37d4de7de66c668b8ed705929088d35a37a2b83c

2023-07-26 09:08 UTC, merged