[4기 - 김별] SpringBoot Part2 Weekly Mission PR입니다
prgrms-be-devcourse/springboot-basic pull request #780
Opened 2023-07-08 16:18 UTC by byeolhaha

## 📌 과제 설명 
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/108210958/f795cd3e-cf0d-48a2-a767-4766b3e19727)
## 👩‍💻 요구 사항과 구현 내용 
- ✅ 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- ✅   바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- ✅   (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
## ✅ 피드백 반영사항   
- 공통적으로 사용하는 Error Message를 클래스로 분리하였습니다.
- `VoucherPolicy`에서 더 직관적인` VoucherType`으로 이름을 수정하였습니다.
- `VoucherType`에서 없는 바우처 정책에 대해서 예외를 호출하는 쪽에서 예외를 던졌는데 역할을 명확하게 나누기 위해서 `VoucherType`에서 던지도록 수정하였습니다.
- Enum에서 상수표기법을 지키도록 수정하였습니다.
-  `VoucherList`라는 일급컬렉션에 view에 해당하는 역할이 들어가 이를 분리하였습니다.
- ` VoucherList`의 클래스명에 자료형이 들어가 `VoucherRegistry`로 수정하였습니다.
- 기존에 id를 내부에서 자동으로 생성해주는 것이 테스트 환경에 용이하지 않아 외부에서 주입할 수 있는 환경으로 수정하였습니다.
- Repository에서 Dto를 반환하도록 되어 있었는데 Dto를 Repository에서 사용되는 것이 지양되어 수정하였습니다.
- Input에서 Menu와 Discount 등 많은 것을 의존하고 있었는데 이를 `ViewManager`로 옮겨 Input을 재사용할 수 있도록 수정하였습니다.
- 기존 테스트 코드는 메소드명, given/when/then 등의 사용이 일관되지 않았는데 이를 고쳐 일관성 있도록 수정하였습니다.
- price인 double에 대해서도 원시값을 포장하여` Price`로 만들어 유효성 검사의 책임을 부여했습니다.
- 할인 인자 `Discount`에 대해서 할인율에 대한 할인 인자` PercentDiscount`와 고정 금액에 대한 할인 인자` FixedDiscount`의 책임이 분리된다고 생각하여  분리하였습니다.
## ✅ PR 포인트 & 궁금한 점 
- 바우처 지갑 부분은 이번 pr 후 추가하겠습니다.
- switch case문을 줄이면서 만났던 문제들
  - Menu
    - Menu(list,exit,create)가 추후 추가될 것을 고려하여 switch case 문을 줄이고 싶었고 커맨드 패턴과 중간에 Command를 생성해 주는 클래스를 넣었습니다. 
     - 이러다 보니 ` Commad`인터페이스를 구현한` 구현체`와 Command 구현체를 생성해주는` CommadFactory` 그리고 `CommandLineApplication` 모두에서 `VoucherController`와 `ViewManager `를 알고 있는 상황인데 너무 많은 클래스에서 VeiwManage와 VoucherController를 알고 있는 상황이라고 생각합니다. 이를 줄이고자 생각해봤는데 방법이 떠오르지 않습니다.
   - Voucher
      -  `VoucherType`이라는 enum 클래스에서` FixedAmountVoucher`와` PercentDiscountVoucher`를 생성하는데 enum 클래스 이런 역할을 가져도 되는건지 의문이 듭니다.

2023-07-09 15:30 UTC, devYSK commented on src/main/java/com/prgrms/model/customer/Customer.java
> +
name이 null이 들어온다면 NPE가 발생하겠네요.

또한 이후에 name에 대한 책임이 많아진다면, 해당 책임을 갖는 객체를 만드는것도 좋을거같아요!

2023-07-09 15:31 UTC, devYSK commented on src/main/java/com/prgrms/model/customer/Customer.java
> +
이 코드는 테스트 못할거같아요.

왜 그럴까요?

2023-07-09 15:36 UTC, devYSK commented on src/main/java/com/prgrms/model/voucher/dto/VoucherResponse.java
> +    }
record로는 사용할 수 없을까요?

2023-07-09 15:42 UTC, devYSK commented on src/main/java/com/prgrms/model/voucher/FixedAmountVoucher.java
> +    public double sale() {
할인하는 객체를 따로 만들었는데, 할인에 대한 연산을 하는것과 Price를 FixedAmountVoucher가 알 필요가 있을까요! 
해당 객체에게 일을 시켜보는것은 어떨까요 

```java
public class FixedDiscount {
    private final Price discountAmount;

    public FixedDiscount(Price discountAmount) {
        this.discountAmount = discountAmount;
    }

    public Price discount(Price originalPrice) {
        return originalPrice.subtract(discountAmount);
    }
}
```

2023-07-09 15:43 UTC, devYSK commented on src/main/java/com/prgrms/model/voucher/Vouchers.java
> +
파라미터 이름을 voucherRegistory로 하신 의도가 궁금합니다.

2023-07-09 15:44 UTC, devYSK commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +
find 했지만, 없어서 빈 값을 반환하는것이 error 인지 고민해보면 좋을거같아요

2023-07-09 15:45 UTC, devYSK commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +
var를 사용하신 이유가 궁금합니다.

2023-07-09 15:52 UTC, devYSK commented on src/main/java/com/prgrms/repository/voucher/JdbcVoucherRepository.java
> +
VoucherRegistory는 없는 클래스네요.

코드를 실행할 수 없는데 실행될 수 있도록 수정해서 올려주세요

2023-07-09 15:54 UTC, devYSK commented on src/main/java/com/prgrms/service/voucher/VoucherService.java
> +        int id = keyGenerator.make();
bean을 주입받고 있는데
static method 인거같아요

2023-07-09 15:55 UTC, devYSK commented on src/test/java/com/prgrms/view/MenuTest.java
> +
given-when-then 위 테스트코드들과 형식을 맞춰주세요

2023-07-09 15:56 UTC, devYSK commented on src/test/java/com/prgrms/view/MenuTest.java
> +    public void FindByMenu_MixedMenu_Equals() {
메서드 이름은 소문자로 시작하는것이 관례입니다

2023-07-09 15:56 UTC, devYSK commented on src/test/java/com/prgrms/view/MenuTest.java
> +    public void FindByMenu_LowerList_Equals() {
테스트 메서드가 public이여야 하는 이유가 있을까요?

2023-07-09 15:57 UTC, devYSK commented on src/test/java/com/prgrms/view/command/ListCommandTest.java
> +
사용하지 않는 코드는 지워주세요

2023-07-09 15:57 UTC, devYSK commented on src/test/java/com/prgrms/view/command/ListCommandTest.java
> +class ListCommandTest {
무엇을 테스트 하고 싶으신걸까요?

2023-07-09 15:57 UTC, devYSK commented on src/test/java/com/prgrms/view/command/ListCommandTest.java
> +    void execute_ON_PowerON() {
displayName이 빠져있어요.
통일성을 맞춰주세요

2023-07-09 15:58 UTC, devYSK commented on src/test/java/com/prgrms/view/command/ExitCommandTest.java
> +    @Test
사용하지 않는 코드같아요

2023-07-09 15:59 UTC, devYSK commented on src/test/java/com/prgrms/view/command/CommandFactoryTest.java
> +class CommandFactoryTest {
여기도 형식을 맞춰주세요

2023-07-09 16:00 UTC, devYSK commented on src/test/java/com/prgrms/service/voucher/VoucherServiceTest.java
given절이 너무 길어 테스트 코드의 가독성을 해치는것 같아요.

@MethodSource 등과 같이 코드의 가독성을 높일 방법을 찾아보세요!

2023-07-09 16:01 UTC, devYSK commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +    @BeforeAll
`@ BeforeEach` 와 `@ BeforeAll` 의 차이는 무엇이 있을까요?

2023-07-09 16:02 UTC, devYSK commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
LifeCycle_PER_CLASS는 어떤 설정인가요?

2023-07-09 16:02 UTC, devYSK commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +
무엇을 테스트 하고 싶으신걸까요?

2023-07-09 16:03 UTC, devYSK commented on src/test/java/com/prgrms/repository/customer/JdbcCustomerRepositoryTest.java
> +
jdbc만을 테스트 하고싶다면 

`@ JdbcTest` 라는 어노테이션에 대해 알아보셔도 좋습니다.

2023-07-09 16:06 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/VoucherTypeTest.java
> +    @DisplayName("없는 할인 정책에 대한 예외 테스트")
policy를 1, 2, 3 이렇게 함으로써,   
VoucherType의 내부를 여러번 들여다보지 않으면 사용하기 어렵고 
테스트코드의 가독성도 함께 해치는것 같아요.
코드 레벨에서는 알기 힘들수도 있겠네요.
다른 대안은 없을까요?

2023-07-09 16:08 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/VoucherRegistryTest.java
> +
VoucherRegistry는 없을 뿐더러 테스트가 실행되지도 않습니다.

테스트도 실행되고, 프로그램도 실행될 수 있도록, 실행도 해보고 코드를 정리해서 올려주세요

2023-07-09 16:10 UTC, devYSK commented on src/test/java/com/prgrms/controller/VoucherControllerTest.java
> +        int voucherId2 = KeyGenerator.make();
이코드도 실행이 되지 않습니다.

2023-07-09 16:12 UTC, devYSK commented on build.gradle
> +    testImplementation 'junit:junit:4.13.1'
junit 4 버전을 사용하시려고 하는 이유가 궁금합니다.

2023-07-09 16:13 UTC, devYSK commented on build.gradle
> +    implementation group: 'com.mysql', name: 'mysql-connector-j', version: '8.0.33'
mysql 을 의존성 추가 하셨는데, 사용 안하시면 빼도 될것같아요

2023-07-09 16:17 UTC, devYSK requested changes
안녕하세요 별님 과제하시느냐 고생 많으셨습니다.

테스트 코드와 프로덕션 코드가 정상 동작하도록 정리해서 pr을 올려주셔야 합니다.


* Voucher
    * VoucherType이라는 enum 클래스에서 FixedAmountVoucher와 PercentDiscountVoucher를 생성하는데 enum 클래스 이런 역할을 가져도 되는건지 의문이 듭니다.


-> VoucherType은 Voucher가 어떤 타입인지 구분하기 위한 상수로 사용하는것으로 보입니다.
Factory의 역할과 책임을 타입 구분하기 위해 VoucherType이 가져도 되나? 라고 생각하면 가져도 되면 안된다고 생각합니다.

2023-07-09 16:28 UTC, devYSK commented on src/main/java/com/prgrms/model/voucher/dto/mapper/DtoConverter.java
> +public class DtoConverter {
Voucher를 dto로 Converter하지만 이름은 그냥 DtoConverter여서 모호해지는거 같습니다.
다른 좋은 이름은 없을까요?

2023-07-09 17:04 UTC, byeolhaha commented
리뷰해주셔서 감사해요 🐣
9일 새벽에 라이브 코드리뷰로 받은 부분을 계속 수정하다 보니
pr의 시점이 모호해져 정상적으로 작동하지 않은 코드로 계속 commit이 올라갔어요😭
불편드려 죄송해요 

현 commit을 기준으로 정상 작동되며 9일 라이브 코딩으로 받은 리뷰는 모두 반영되었어요
- TriFuntion이라는 함수형 인터페이스를 따로 만들었는데 매개변수가 초기화되지 않은 부분이 있어 수정했어요
- 일급컬렉션의 이름을  Vouchers로 수정하였어요 
- 기존에 Menu -> CommandFactory -> Command  의 로직이 논리적으로 부적절해 보여 CommandFactory -> Menu -> Command로 수정하였어요
- 원시값 포장에서 유효성 검사를 하는 메서드에서 boolean  형태의 매개변수를 받는 것은 코드를 쉽게 변경할 수 있는 위험의 요소가 있어서 double형의 변수를 받고 메서드의 역할이 더 잘 드러나도록 수정하였어요
- test 코드에서 부적절했던 대문자이름의 메서드, Given/When/Then 혹은 given/when/then의 통일성 부족, @DisplayName에서 문서화를 고려하여 더 구체적으로 작성하도록 수정하였어요

2023-07-10 11:58 UTC, devYSK requested changes

2023-07-10 11:58 UTC, devYSK commented on src/main/java/com/prgrms/model/customer/Customer.java
> +    }
name에 null이 들어오면 많은 부분에서 버그가 발생할거 같아요! 조금더 방어적이게 해보죠

2023-07-10 11:58 UTC, devYSK commented on src/main/java/com/prgrms/model/voucher/VoucherType.java
> +}
VoucherType이 create하는 책임은 상황에 따라 다를 수 있다고 생각해요.

단일 책임 원칙과, 변경의 영향이 없을지 대해서도 고민해보세요.

 VoucherFactory 클래스를 도입하여 실제로 쿠폰을 생성하는 책임을 VoucherFactory에 위임할 수 도 있겠네요

2023-07-10 11:58 UTC, devYSK commented on src/main/java/com/prgrms/util/KeyGenerator.java
> +}
접근제어자를 이용해서, Bean으로만 등록되고 아무나 생성 못하게 막아보죠!

2023-07-10 11:58 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/VoucherRegistryTest.java
> +        List<Voucher> list = new ArrayList<>();
정책인가요 바우처가 없는건가요!?

2023-07-10 11:58 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/dto/discount/DiscountCreatorTest.java
> +
double만 default 패키지로 두셨는데 이유가 있을까요??

2023-07-10 11:58 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/dto/discount/FixedDiscountTest.java
> +    @DisplayName("음수인 경우 예외를 던지는지 테스트한다.")
바우처의 고정 할인값이 음수가 들어오면 생성할 수 없다

2023-07-10 11:58 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/dto/mapper/DtoConverterTest.java
> +    }
반드시 테스트에 있어야 하는 로직일까요!?

2023-07-10 11:58 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/dto/price/PriceTest.java
> +        //given
displayName이 빠졌어요~ 통일성을 맞춰주세요

2023-07-10 11:58 UTC, devYSK commented on src/test/java/com/prgrms/repository/customer/JdbcCustomerRepositoryTest.java
> +
여기도 왜 id만 private일까요~!

2023-07-10 11:58 UTC, devYSK commented on src/test/java/com/prgrms/view/MenuTest.java
> +
좋네요!

2023-07-10 23:36 UTC, WooSungHwan commented
이러다 보니  Commad인터페이스를 구현한 구현체와 Command 구현체를 생성해주는 CommadFactory 그리고 CommandLineApplication 모두에서 VoucherController와 ViewManager 를 알고 있는 상황인데 너무 많은 클래스에서 VeiwManage와 VoucherController를 알고 있는 상황이라고 생각합니다. 이를 줄이고자 생각해봤는데 방법이 떠오르지 않습니다.

이게 사실 이정도까지가 되면 VoucherController 자체가 분리되고 별도의 자체 CreateVoucherUseCase와 같은 인터페이스를 하나씩 선언해두고 관련된 로직을 모두 분리해주는게 좋습니다. 예컨데 지금이건 controller마다 하나의 클래스로 RequestMapping을 해주고 있는거나 다름없거든요. 여러가지 갈래에서 쪼개져 나와서 하나로 합치자니 많은 의존성들이 겹치게 될 것이고 특정 커맨드는 필요없는 기능을 가진 의존성이 타 커맨드에 주입되고 그랬을거에요. 그런 경우라면 각각의 기능들이 분리된 controller 혹은 service가 등장하게 될 것이고 CreateVoucherUseCase 같은 인터페이스를 구현한 구현 클래스를 주입해주는 형태로 가야겠죠 ㅎㅎ
이 부분은 클린아키텍처라는 책에 나오는 내용이고 추상적인 부분이라 이해가 어려울거라 `클린아키텍처 usecase` 인터페이스로 당장 10분정도 가볍게 서치해보고 어렵다 싶으시면 쪼갠다라고만 생각하셔도 무방합니다. 추후 공부해나가시면 더 좋고요 ㅎㅎ

2023-07-10 23:54 UTC, WooSungHwan requested changes
안녕하세요! 별님! 과제하시느라 수고많으셨습니다!
아직 미구현된 기능들 포함해서 제출해주시고 리뷰 몇자 남겼으니 확인부탁드려요~

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/CommandLineApplication.java
> +                power = command.execute();
요부분은 코멘트 남겼습니다 ㅎㅎ

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/model/voucher/VoucherType.java
> +}
일단은 enum자체의 볼륨이 타입이 늘어날때마다 커질거고 voucher 자체도 어떤식으로 생성자에 필요한 파라미터가 커질지 모르는 시점에서 enum에서 인스턴스화 하는 전략은 상당히 많은 부담을 가지고 갈거에요.
인스턴스화하는 부분을 따로 빼보시죠

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/repository/voucher/JdbcVoucherRepository.java
> +        }
이런거 되게 좋아요!

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/repository/voucher/JdbcVoucherRepository.java
> +        }
그치만 별도로 직접 날리는 예외의 경우는 하나 경우를 만들어주는게 좋을 것 같아요!

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/repository/voucher/JdbcVoucherRepository.java
> +        List<Voucher> vouchers = jdbcTemplate.query("select * from vouchers", voucherRowMapper);
`select *` 을 쓰게되면 불필요한 메타데이터(등록일, 수정일, 등록자, 수정자 등 따위의)도 포함해서 query를 수행하고 rowMapper에서 탈락해서 쓰시겠죠? ㅎㅎ 
직접 필요한 column을 select 해서 쓰면 voucher erd를 직접 까보지 않아도 어떤 컬럼들이 호출될지 보이잖아요 ㅎㅎ

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +}
이 클래스 왠지 JpaRepository 스펙과 비슷하게 구성하려고 하신 것 같은데. 아직 미사용인 컬럼은 인터페이스를 구현하기 위함이신것 같고..
그렇다면 exists쿼리도 한번 구현해보는건 어떤가요?ㅎㅎㅎㅎ 뒤에 붙는건 생각하시는거 아무거나 필요하겠다 싶은거 쓰시구여ㅎㅎ

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +        return jdbcTemplate.queryForObject("select count(*) from customers", Collections.emptyMap(), Integer.class);
count 쿼리 같은 경우는 where 조건이 되게 많이 중요해요.
우선 테이블의 레코드를 읽는 과정중에 table full scan과 그 외의 스캔들이 있는데 적당히 들어있는 대략 10만 이하의 테이블, column숫자와 분포도도 대략 10개 내외의 테이블인 상황에서는 적당한 latency가 나올텐데요..
이게 서비스가 확 커지는 순간 테이블의 용량이 팍 늘어나서 제가 말했던 것처럼 `테이블에 데이터가 많아지면 어떡하지??`의 고민이 드는 순간 이 count 쿼리부터 가장 말썽을 일으킬거에요.

따라서 조건없는 count 쿼리는 상당히 보수적으로 생각해야하고 interface에 기능적으로 있으면 사실 매우 곤란한 부분이긴 합니다. 따라서 별로 사용할 용도가 아니라면 조건이 있는 요구사항에서 필요로 해야하고 지금같은 경우는 기능제공을 하지 않는 것이 좋아보입니다.

2023-07-10 23:54 UTC, WooSungHwan commented on src/main/java/com/prgrms/view/command/Command.java
> +}
근데 사실 이렇게 Command 구조를 가져가신다면 Controller라는 클래스가 필요한가 싶긴 하네요 ㅎㅎ 단순 service 를 호출하는 것 뿐인데ㅎㅎ Controller를 조각내놓은 Command는 아닐지..?
얘가  VoucherCommand는 아닐지? ㅎㅎ

2023-07-11 11:55 UTC, byeolhaha commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +
var를 사용하는 경우 자료형이 바뀌는 경우 유지 보수가 적다 외에는 생각나는 장점이 없네요 
타인이 읽었을 타입을 추론하기 위해서 자료를 다시 뒤져야 하는 비용이 발생하여 가독성이 떨어진다는 생각이 들어
수정하도록 할게요

2023-07-11 12:06 UTC, byeolhaha commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +    @BeforeAll
- `@BeforeAll`은 모든 테스트 메소드가 실행되기 전에 한 번만 실행해요.
    - 이 어노테이션이 붙은 메서드는 반드시 static으로 선언
- '@BeforeEach'는 각 메서드가 실행되기 전에 실행해요
     - static으로 선언 금지

2023-07-11 12:18 UTC, byeolhaha commented on src/main/java/com/prgrms/model/voucher/dto/mapper/DtoConverter.java
> +public class DtoConverter {
기능이 분명하게 드러나도록 VoucherConverter로 수정하도록 할게요

2023-07-11 12:40 UTC, byeolhaha commented on src/main/java/com/prgrms/util/KeyGenerator.java
> +}
처음에는 private으로 생성자가 되어 있으면 빈도 하나의 객체여서 생성할 수 없다고 생각했는데
`BeanUtils`라는 클래스에  `instantiateClass`라는 메서드에 
리플렉션을 이용해서 private 생성자를 접근할 수 있도록 설정되어 있는 것을 확인하게 되었어요 💡

2023-07-11 16:02 UTC, byeolhaha commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
원래 디폴트(LifeCycle_PER_METHOD)는 각 테스트 메소드마다 테스트 클래스의 인스턴스를 새롭게 생성하는데  LifeCycle_PER_CLASS는 새로운 인스턴스를 만들지 않고 
하나만 만들어서 각 테스트 메소드마다 같은 인스턴스를 사용해요 

위 테스트 코드의 경우 
데이터 소스를 읽어서 접근하는데 그 비용이 많이 들기 때문에 한 번만 생성하기 위해서 위 조건을 걸었어요

2023-07-11 16:13 UTC, byeolhaha commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +    @BeforeAll
- `@BeforeAll`
   - 테스트 전체에 한번만 실행되기 원한다면 `@BeforeAll`를 사용해요. 
   - 기본적으로 테스트의 각 메소드를 실행할 때마다 테스트 클래스의 새로운 인스턴스를 생성
   - 따라서 `@BeforeAll`이 붙은 메서드는 static이어야 해요.
   - 단,  `@TestInstance(Lifecycle.PER_CLASS)`는 하나의 인스턴스를 각 메서드마다 재사용하기 때문에 
 `@BeforeAll`에 static이 붙이지 않아도 됩니다.
 - `@BeforeEach`
   - 이 어노테이션이 붙은 메서드는 각 테스트 메서드가 진행될 때마다 실행해요
   - `@TestInstance(Lifecycle.PER_CLASS)`의 경우 하나의 인스턴스를 재사용하기 때문에 인스턴스에 있는 인스턴스 변수를 초기화하는 과정에서 사용될 수도 있어요

2023-07-11 17:46 UTC, byeolhaha commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +
JdbcVoucherRepository test와 관련 없는 단위 테스트인 것으로 보여 분리하거나 삭제하도록 할게요

2023-07-12 06:10 UTC, byeolhaha commented on src/test/java/com/prgrms/repository/customer/JdbcCustomerRepositoryTest.java
> +
`@ JdbcTest`를 이용해서 관련 객체들을 주입받고
`@Import(JdbcCustomerRepository.class)`를 이용해서 일반 빈 객체를 주입받게 수정할게요

2023-07-12 06:56 UTC, byeolhaha commented on src/main/java/com/prgrms/util/KeyGenerator.java
> +}
오랜 시간 고민했는데 private 생성자로 생성하는게 단위 테스트할 수 없는 환경인데 이 클래스의 경우 단위테스트를 진행할 필요가 없어 괜찮다는 결론이 나왔어요 혹시  private이 붙고 Bean인데 비즈니스 로직이 있어 테스트를 진행해야 하는 경우는 없을까요?

2023-07-12 06:58 UTC, byeolhaha commented on src/main/java/com/prgrms/model/voucher/dto/mapper/DtoConverter.java
> +public class DtoConverter {
다시 보니 Voucher 관련 Dto가 추가될 때마다 저 Converter에는 너무 많은 의존성이 생길 것 같은데 dto 자체로 저 역할을 옮기도록 할게요

2023-07-12 07:55 UTC, byeolhaha commented on src/test/java/com/prgrms/model/voucher/VoucherRegistryTest.java
> +        List<Voucher> list = new ArrayList<>();
문서화가 가능하도록 더 세세하게 적도록 할게요

2023-07-12 07:58 UTC, byeolhaha commented on src/test/java/com/prgrms/model/voucher/dto/mapper/DtoConverterTest.java
> +    }
DtoConverter 자체에 비즈니스 로직이나 분기점들이 없어서 테스트 코드가 필요없는 클래스인거 같아요 혹시 맞을까요?

2023-07-12 09:31 UTC, byeolhaha commented on src/test/java/com/prgrms/model/voucher/VoucherTypeTest.java
> +    @DisplayName("없는 할인 정책에 대한 예외 테스트")
```
private final String FIXEDVOUCHER = "1";
private final String PERCENTVOUCER = "2";
private final String STRANGEVOUCHER = "3";
```
이와 같은 방식으로 미리 선언하여 알려주는 방식으로 수정할게요

2023-07-12 11:03 UTC, byeolhaha commented on src/test/java/com/prgrms/view/command/ListCommandTest.java
> +class ListCommandTest {
단위 테스트가 필요한 코드가 아닌 것 같아 삭제하도록 할게요 ✏️

2023-07-12 11:43 UTC, byeolhaha commented on src/main/java/com/prgrms/model/customer/Customer.java
> +
isEmpty()와 isBlank() 모두 NPE를 던지는데 isEmpty()의 경우 " "공백이 있는 문자열은 비어있지 않다고 판단하여 
`if (name == null || name.isBlank()) {`로 수정하도록 할게요

2023-07-12 12:04 UTC, devYSK commented on src/test/java/com/prgrms/repository/voucher/JdbcVoucherRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@byeolhaha 

잘못된 방법은 아니라고 생각해요. 테스트하고자 하는 바가 무엇이고, 적절한가를 생각해봐야할거같아요
만약 앞의 결과에 뒤의 테스트들이 의존하면 적절한거라고 생각해요.

기본적으로 JUnit은 테스트 메소드의 실행 순서를 보장하지 않아서 
@Order는 테스트 메서드의 실행순서를 보장해서, 명시적으로 제어할때 사용해요.

예를 들어,  앞 순서의 어떤 테스트가 뒤의 다른 테스트의 결과에 의존하거나 사용될때요.

또한 조금 더 고민을 해봤을 때 주문이라고 가정하면,  
* 1 결제를 하면 2 주문 상태가 되고 3 배송준비중이 되는지 
* 1 배송 완료를 하면 2 주문이 완료 되는지
등등 순차적으로 시나리오식으로 테스트할때 유용하겠죠
다만, 그런 케이스들이 흔치 않으며, 테스트의 독립성을 유지하는 것이 일반적으로 단위테스트의 우선적인 목표라고 생각해요

별님의 해당 JdbcVoucherRepositoryTest는 단순 CRUD 같은 기능에 대해 테스트 하고 있어요.
테스트 하고자 하는 바에 무엇인지에 따라 방향은 다르겠지만, 다른 테스트의 결과로 인하여 테스트가 불가능해지거나 코드가 복잡해지면 잘못된 테스트를 하고 있는거일수도 있어요. 
그렇게 되버리면 테스트 간에 의존성이 생겨나고 그로 인해 발생하는 이슈를 디버깅하는 것이 매우 어려울 수 있고요!

F.I.R.S.T 원칙에 대해 알아보셔도 좋을거같아요!

2023-07-12 12:08 UTC, devYSK commented on src/main/java/com/prgrms/util/KeyGenerator.java
> +}
@byeolhaha 

맞아요 이 객체의 경우 매 메소드 호출시마다 달라지는 랜덤한 값을 넘겨주는 역할을 하고 있어요. 테스트 할수가 없다고 생각하면 될거같아요. 

private이 붙고 Bean이라면 해당 객체만 주입을 받아 테스트 하는것은 어떨까요?

비즈니스 로직이 있는데 테스트를 안한다는 것은 어떤 코드일까요.

2023-07-12 12:18 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/dto/mapper/DtoConverterTest.java
> +    }
@byeolhaha 
해당 테스트는 실패하네요. 테스트는 몇번을 돌려도 통과해야합니다

또한 해당 코드 정리가 필요해 보여요!   

무엇을 테스트 하고 싶은지 아직도 잘 모르겠어요

처음에 보았을 때, 정렬이 무조건 되어있어야 하는가?를 생각했어요. Comparator를 사용하기에요 
`compare` 가 언제 사용될까요? 
* Comparable, Comparator에 대해 알아보세요

또한 해당 일급컬렉션의 객체가 반드시 정렬이 되야 한다면, 해당 compare는 Vouchers에 정의되거나, 
usingElementCompator에  람다로 정의될 수 있을거 같아요 

정렬이 중요한게 아니고 순서 상관 없이 contains가 되야 한다면 containsExactlyInAnyOrder()를 알아보세요

2023-07-13 11:55 UTC, byeolhaha commented on src/main/java/com/prgrms/repository/voucher/JdbcVoucherRepository.java
> +        }
혹시 이 하나의 경우라면 메서드를 말씀하시는 걸까요? 아니면 CustomException을 말씀하시는 걸까요?

2023-07-14 06:31 UTC, byeolhaha commented on src/main/java/com/prgrms/view/command/Command.java
> +}
controller 삭제하고 Command로 위임하는 방법으로 수정했어요

2023-07-15 10:09 UTC, byeolhaha commented on src/main/java/com/prgrms/repository/voucher/JdbcVoucherRepository.java
> +        }
Custom Exception으로 분리하라는 명확하게 의미를 만들겠습니다 💡

2023-07-15 13:13 UTC, byeolhaha commented
2주차 PR을 반영 완료하였고 바우처 지갑 구현도 완료했어요 
## ✅ 2주차 PR 반영 사항
- `@DisplayName`문서화 가능하도록 구체적으로 작성하였습니다.
-  테스트 코드 통일성 있게 작성하려고 노력하였습니다.
-  `@MethodSource` 사용하여 긴 given 줄이기
- Controller의 역할이 부족하여 삭제하고 Command에 위임하였습니다.
- `@Order` 독립적으로 진행되어야 하는 단위 테스트에서 삭제하였습니다.
- `select *` 보다 명시적으로 필드명 사용하여 비용 줄였습니다.
-  enum에서 생성하는 부분 분리하였습니다.
## 🛠️ 고민한 부분
- ViewManager라는 클래스가 Input과 Output 부분을 모두 관리하였는데 그러다 보니 Menu, Discount, DiscountCount 등 알고 있는 객체들이 너무 많아져서 이를 각 Commad에 배치하였습니다.
- 테스트 클래스의 PER_CLASS를 삭제한 이유가 테스트코드에서 데이터 베이스에 입력하는 부분이 있어 default로 선택하였습니다. 그런 @JdbcTest에서 롤백을 지원하여  다시 PER_CLASS를 사용해도 되는건지 궁금합니다. 
- 흑구 멘토님이 말씀하신 유스케이스 인터페이스에 대해서 찾아봤는데 제가 겪고 있는 문제를 어떻게 해결할 수 있는지 실마리를 얻지 못했습니다.

2023-07-15 15:59 UTC, devYSK approved these changes

2023-07-15 15:59 UTC, devYSK commented on src/main/java/com/prgrms/model/KeyGenerator.java
> +    private static Random rand = new Random();
final 이여도 될거같아요

2023-07-15 15:59 UTC, devYSK commented on src/main/java/com/prgrms/presentation/command/voucher/CreateCommand.java
> +    }
```java
return VoucherType.findByType(option);
```

2023-07-15 15:59 UTC, devYSK commented on src/main/java/com/prgrms/presentation/command/CommandCreator.java
> +    private final VoucherService voucherService;
사용하지 않는 코드는 지워주세요

2023-07-15 15:59 UTC, devYSK commented on src/main/java/com/prgrms/presentation/message/GuideMessage.java
> +    START("=== Voucher Program === \n" +
System.lineSeperator ?

2023-07-15 15:59 UTC, devYSK commented on src/main/java/com/prgrms/CommandLineApplication.java
> +                power = command.execute();
알수없는 에러가 발생해도 프로그램은 죽으면 안될거 같아요! 

```java
@Override
public void run(String... args) {
    Power power = Power.ON;

    while (power.isOn()) {
        try {
            Menu menu = guideStartVoucher();
            Command command = commandCreator.createCommand(menu);
            power = command.execute();
        } catch (IllegalArgumentException e) {
            logger.error("사용자의 잘못,된 입력이 발생하였습니다. {0}", e);
            output.write(e.getMessage());
        } catch (Exception e) {
            logger.error("알 수 없는 error 발생");
       .... 후처리
        }
    }
}
```

2023-07-15 15:59 UTC, devYSK commented on src/test/java/com/prgrms/model/customer/CustomerTest.java
> +    }
```java
Assertions.assertThatIllegalArgumentException()
    .isThrownBy(() -> new Customer(CUSTOMER_ID, EMPTY_NAME, EMAIL, createdAt))
```

2023-07-15 15:59 UTC, devYSK commented on src/test/java/com/prgrms/model/voucher/dto/price/PriceTest.java
> +
getSaledPrice 테스트도 필요할거같아요

2023-07-15 15:59 UTC, devYSK commented on src/test/java/com/prgrms/repository/wallet/JdbcWalletRepositoryTest.java
> +
BDDMockito.given().willReturn()

2023-07-17 07:01 UTC, byeolhaha commented
# 2주차 PR 2차 pr 반영 완료하였습니다
# ✅ 2주차 PR 반영 사항
- 핵심 비즈니스 로직이 있는 부분인 `Service`에서 Mock을 남용하는 부분이 있고 실제로 테스트가 필요한 중요한 로직이라고 판단되어 통합테스트로 구현하였습니다. 
- ` RowMapper` 부분을 따로` DataRowMapper` 클래스로 분리하였다가 이를 재사용하는 클래스는` WalletRepository `뿐이어서 빈으로 등록했던 부분을 취소하고 클래스 자체를 삭제하였습니다.
- 기존에 `Command`를 전략 패턴을 이용해서 생성하였는데 이 부분에서 Bean으로 등록된 `Command` 구현체들을 다시 생성해서 사용하는 부분이 있었는데 이 부분을 다시 생성하지 않도록 수정하였습니다.
# 🛠️ 고민한 부분
## 1. 생성된 빈을 사용하지 않고 new 연산자를 이용하여 생성하는 부분
전략패턴을 이용하여 Command 구현체들을 Mapping하는 부분이 있었습니다.
   코드는 다음과 같습니다.
 ```java
@Component
public class CommandCreator {

    private final Map<Menu, Command> strategies;
    private final WalletService walletService;
    private final VoucherService voucherService;
    private final Input input;
    private final Output output;

    public CommandCreator(WalletService walletService, VoucherService voucherService, Input input, Output output) {
        this.input = input;
        this.output = output;
        strategies = new HashMap<>();
        this.voucherService = voucherService;
        this.walletService = walletService;

        strategies.put(Menu.EXIT, new ExitCommand(this.output));
        strategies.put(Menu.LIST, new ListCommand(this.output, voucherService));
        strategies.put(Menu.CREATE, new CreateCommand(this.input, this.output, voucherService));

        strategies.put(Menu.GIVE_VOUCHER, new GiveVoucherCommand(this.output, this.input, walletService));
        strategies.put(Menu.TAKE_VOUCHER, new TakeVoucherCommand(this.output, this.input, walletService));
        strategies.put(Menu.CUSTOMER_LIST, new CustomerListCommand(this.output, this.input, walletService));
        strategies.put(Menu.VOUCHER_LIST, new VoucherListCommand(this.input, this.output, walletService));
    }

    public Command createCommand(Menu menu) {
        return strategies.get(menu);
    }
 ```
하지만 이 구현체들은 Bean으로 등록된 상태였고 다시 생성하는게 말이 안되는 구조여서 

다음과 같이 수정하였습니다.
### 개선 코드
전체적으로 설명드리면 ApplicationContext에서 이름을 통하여 빈을 주입받는 것인데 그 이름은 Menu의 속성으로 등록되어 있습니다. 결국 사용자가 Menu를 입력하여 그 해당 빈 이름으로 연결될 수 있도록 변경하였습니다.
 - CommandLineApplication
 ```
 @Override
    public void run(String... args) {
        Power power = Power.ON;

        while (power.isOn()) {
            try {
                Menu menu = guideStartVoucher();
                Command strategy = applicationContext.getBean(menu.getBeanName(), Command.class);
                strategy.execute();
 ```
- Menu 
코드를 보면 enum의 속성으로 빈 이름이 그대로 저장되어 있어서 사용자가 버튼을 입력하면 그 버튼에 해당하는 빈 이름을 리턴합니다.
```java
public enum Menu {
    EXIT("exitCommand"),
    CREATE("createCommand"),
    LIST("listCommand"),
    GIVE_VOUCHER("giveVoucherCommand"),
    TAKE_VOUCHER("takeVoucherCommand"),
    CUSTOMER_LIST("customerListCommand"),
    VOUCHER_LIST("voucherListCommand");

    private final String beanName;

    Menu(String beanName) {
        this.beanName = beanName;
    }

    public String getBeanName() {
        return beanName;
    }

    public static Menu findByMenu(String menu) {
        return Arrays.stream(values())
                .filter(m -> m.name().replace("_", " ").equalsIgnoreCase(menu))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException(
                        ErrorMessage.INVALID_SELECTION.getMessage()));
    }

}
```
### 남아있는 문제점
위와 같이 이름으로 직접 빈을 주입받는 것이 권장되지 않는 방법이라고 알고 있습니다.
하지만 위 방법 외에 빈을 생성하지 않고 만들어진 빈을 주입 받을 수 있을까에 대한 해결책을 얻지 못했습니다.

## 2. 테스트 객체  라이프 사이클 PER_CLASS
위 라이프 사이클을 선택한 이유는 테스트마다 DB를 읽는 과정이 무겁다고 생각했기 때문입니다.
하지만 테스트 코드의 경우 insert라는 메서드를 통해서 데이터를 오염시키는 부분이 있어서 다시 default로 바꾸게 되었습니다.

그러나 다시 한번 생각해보니 데이터 베이스가 초기화되는데 굳이 default인 PER_METHOD를 사용할 필요가 있을까 싶었습니다.

DB를 오염시킨다는게 어떤 것을 말하는 것인지 궁금합니다.

## 3. 유스케이스 인터페이스가 어떤 부분에서 내 코드를 개선시킬 수 있을까에 대한 의문점
짧은 유튜브 강의와 github에 올라온 예시 코드를 통해 유스케이스 인터페이스 아키텍처에 대해서 보았는데
어떤 부분에서 제 코드를 개선시킬 수 있을까에 대한 의문점이 해결되지 않았습니다.

2023-07-18 04:40 UTC, WooSungHwan approved these changes
2주차 과제에서 코드가 많이 깔끔해졌네요 ㅎㅎ 
어제 팀미팅에서 이야기했던 부분 적용해보면 정말 좋을 것 같고요. 나머지는 3주차에서 좀더 다뤄봅시다!!
수고하셨씁니다 ㅎㅎ

2023-07-18 04:40 UTC, WooSungHwan commented on src/main/java/com/prgrms/presentation/command/voucher/CreateCommand.java
> +        int id = keyGenerator.make();
근데 이렇게 여기서 int형 키를 만들어버리면 auto increase보다 어떤점이 나아보여서 이런식으로 된건가요??

2023-07-18 04:40 UTC, WooSungHwan commented on src/main/java/com/prgrms/presentation/command/wallet/GiveVoucherCommand.java
> +        int id = keyGenerator.make();
여기도 마찬가지로 어떤점이 auto increase보다 나아보여서 random int값을 리턴하도록 변경한건지?

2023-07-18 04:40 UTC, WooSungHwan commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +    }
미사용 메소드 제거.

2023-07-18 04:40 UTC, WooSungHwan commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +                "SELECT 1 EXISTS(SELECT FROM vouchers WHERE voucher_id = :voucher_id)"
이거 오타난것같은데요 ㅎㅎ 이 쿼리 잘 동작하나요?

2023-07-21 05:16 UTC, byeolhaha commented on src/main/java/com/prgrms/repository/voucher/JdbcVoucherRepository.java
> +        }};
안티패턴으로 고려되는지 몰랐어요 수정하도록 할게요 ✏️

2023-07-21 05:43 UTC, byeolhaha commented on src/main/java/com/prgrms/presentation/command/voucher/CreateCommand.java
> +        int id = keyGenerator.make();
- auto increase는 key를 하나씩 증가시키는 것인데  primary key로 조회하는 중요 로직이 있는 경우 의도하지 않은 사용자가 다음 사람의 primary key를 쉽게 예상할 수 있습니다. 
- 또한 DB에게 Auto Increase를 맡기는 경우 DB의 리소스가 발생하기 때문에 이러한 비용적인 부분을 줄일 수 있습니다.
- 분산 환경에서 primary key 충돌이 발생할 수 있다.

- 하지만 지금과 같이 랜덤으로 사용하는 경우 DB에 들어갈 때마다 재정렬을 해야합니다.

각각의 방법에 Trade-off가 있고 그래서 둘을 섞어서 사용하는 경우도 있습니다.

2023-07-21 05:44 UTC, byeolhaha commented on src/main/java/com/prgrms/repository/customer/JdbcCustomerRepository.java
> +    }
제거하도록 하겠습니다 ✏️

2023-07-21 05:49 UTC, merged