[4기 - 윤영운] SpringBoot Part.2 Weekly Mission PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #782
Opened 2023-07-08 19:01 UTC by young970

## ERD
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/108216455/cdaa673f-f140-43aa-8b2b-2969dad29077)

## 📌 과제 설명 
- PART.2 구현사항
    - 5번 선택 시 새 회원을 만듭니다.
    - 6번 선택 시 모든 회원을 조회합니다.
    - 7번 선택 시 회원에게 바우처를 할당합니다.
    - 8번 선택 시 회원이 보유한 바우처를 조회합니다.
    - 9번 선택 시 회원이 보유한 바우처를 삭제합니다.
    - 10번 선택 시 해당 바우처를 보유한 멤버를 조회합니다.
    - 11번 선택 시 모든 월렛을 조회합니다.
## 👩‍💻 요구 사항과 구현 내용 
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x] 특정 고객에게 바우처를 할당할 수 있습니다.
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## ✅ PR 포인트 & 궁금한 점 
- Wallet 부분을 중점적으로 봐주셨으면 좋겠습니다!!
- JdbcWalletRepository에서 Member / Voucher Repository를 주입받아 사용하면 현재의 지저분한
  RowMapper부분과 쿼리문을 좀 더 간결하게 줄일 수 있을거 같은데 Repository내에서 다른 Repository를
  주입받아 사용하는 것이 구조적으로 괜찮은지 궁금합니다.

2023-07-09 09:58 UTC, devYSK requested changes
안녕하세요 영운님 과제하시느냐 고생 많으셨습니다.



Wallet 부분을 중점적으로 봐주셨으면 좋겠습니다!!
-> Wallet을 Voucher와 Member의 Mapping Table로 생각한건 문제가 있는것 같진 않았습니다.
요구사항을 구현하는 과정에서 요구사항보다 더 확장되거나 다른 방향으로 구현된 기능이 있는데 이부분은 다시 생각해보시면 좋을거 같습니다.
- 특정 바우처를 보유한 고객을 조회한다 -> 바우처가 유니크한지? 특정 바우처를 여러명이 가질 수 있는지?
- 고객이 보유한 바우처를 제거할 수 있어야 한다 -> 지갑id만으로 로우를 제거할지? 특정 고객이 보유한 바우처로 찾아 제거할지?

JdbcWalletRepository에서 Member / Voucher Repository를 주입받아 사용하면 현재의 지저분한 RowMapper부분과 쿼리문을 좀 더 간결하게 줄일 수 있을거 같은데 Repository내에서 다른 Repository를 주입받아 사용하는 것이 구조적으로 괜찮은지 궁금합니다.

-> Repository 클래스에서 다른 Repository클래스에 직접 의존하면 의존성 관리가 복잡해지고 결합도가 높아집니다.
때문에 구조적으로 좋지 않다고 생각합니다.

SRP을 위반하며, 
만약 의존하는 Member나 Voucher 레포지토리가 변경되면 영향을 그대로 WalletRepository도 받기 때문이에요

또한 Repository를 테스트할 때 저부분도 같이 테스트 해줘야 하는 일도 늘어나겠죠? 
이를 위해 서비스 계층을 이용하는것이 더 나은것으로 생각됩니다.

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/member/service/MemberService.java
> +    }
도메인 객체를 캡슐화 하지 않고 외부로 노출시켜 버리면 어떤 문제가 있을 수 있을까요?

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +    }
update가 어디서 사용되나요?

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +    public Optional<Member> findByName(MemberName memberName) {
findByName이 어디서 사용되나요?

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +            logger.error("Got empty result", e);
update insert랑 메시지 통일성을 맞춰주세요!

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +        String sql = "select * from member WHERE status = 'BLACK'";
BLACK이라는 status는 변하지 않는 값인가요?

왜 status를 사용 안하고BLACK 리터럴로 두신건지, 
findByStatus 등과 같은 다른 메소드로 재사용하지 않은건지
이유가 궁금합니다.

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/dao/JdbcVoucherRepository.java
> +            logger.error("Got empty result");
findById를 하였을 때, 데이터가 없다면 error log를 남겨야 하는지 더 고민해보면 좋을것 같습니다.

없는 데이터를 요청하는것이 에러일까요? 

데이터를 요청하는 일이 잦을텐데 를 생각해보면 error라고 판단하기 힘들것 같습니다. 
'error'의 중요도에서 보면 논리적으로 중요도가 낮아 보입니다. 

DB access문제 등의 심각한 문제를 error 로그로 남기는 경우가 있는데
error 로그를 남겨버린다면, 디버깅과 모니터링에서 어려움을 겪을 수 있습니다.

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +
일반적으로 가독성 때문에 필드 순서를 
정적 필드
<공백>
인스턴스 필드 

로 공백으로 구분해서 두기도 합니다!

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +
Member - Wallet - Voucher 로 관계를 맺으신거 같아요.

메소드 기능을 보면 지갑만을 조회하는 기능같은데 테이블에는 어떤 데이터들이 저장 되어있을지 생각해보면 외래키들이 존재할거 같습니다. 

매번 지갑만을 조회하는데 Join을 해야할거 같진 않습니다. 

필요하다면 join이 필요한 다른 기능으로 빼는게 좋을거같아요.

성능상 이슈도 생길 수 있을 뿐더러,
해당 repository를 사용하는 다른 개발자는 wallet 만 있으면 되는데, 의도치 않게 join되어 모든 필드가 나온다면 어떻게 될까요

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +
여기도 마찬가지로 보여요! 

네이밍과 내부적으로 동작하는 일이 다른거 같아요.
호출하는 입장에서 애매할 수 있는 부분은 명확하게 작성해주시면 좋습니다

2023-07-09 09:58 UTC, devYSK commented on src/main/resources/application-test.yaml
> +    password: 12345!
test 디렉토리 밑에 resources 디렉토리를 만들어서 해당 설정파일을 넣을 수 있어요.

프로덕션 코드에 불필요하게 테스트 관련 파일이 있을 필요가 있을까요?

2023-07-09 09:58 UTC, devYSK commented on src/test/TestVoucher.csv
> +76161371-49e8-4ce0-b154-d2d147fd498b,FIXED,30
해당 파일도 test 디렉토리 밑 resources 디렉토리 밑에 두면 어떨까요?

2023-07-09 09:58 UTC, devYSK commented on src/test/java/org/prgrms/kdt/member/dao/BlackListRepositoryTest.java
> +    BlackListRepository blackListRepository;
fileWrite() 메소드는 제대로 동작하나요? 

`@PreDestory` 를 이용해서 중요한 동작을 하는거 같은데 검증된 코드인지 잘 모르겠습니다.

2023-07-09 09:58 UTC, devYSK commented on src/test/java/org/prgrms/kdt/util/ConverterTest.java
변환에 실패하면  어떻게 되나요?

2023-07-09 09:58 UTC, devYSK commented on src/test/java/org/prgrms/kdt/wallet/service/WalletServiceTest.java
> +@SpringBootTest
`@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)`
를 이용하여  web 환경이 아니게 실행할 수 있씁니다.

서비스 계층의 로직을 테스트하기 위한 단위 테스트이므로 Web 환경의 컴포넌트들이 필요 없다면 알아보시고 사용하면 좋을거같아요!

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/service/WalletService.java
> +    public void deleteWalletById(UUID walletId) {
delete는 transaction이 필요 없다고 생각하신 이유가 궁금합니다!

2023-07-09 09:58 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +
요구사항중, 고객이 보유한 바우처를 제거하는 요구사항이 있습니다.
walletId로 해당 row를 지우는거 같아요!
고객이 보유한 바우처를 지울때 이런 프로세스도 생각해보시면 좋을거같습니다.
a라는 고객의 b 바우처를 지운다

2023-07-09 16:32 UTC, young970 commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +@Profile("!test")
SpringBootTest 시 해당 CommendLineRunner의 run()메소드가 자동 실행 되는 문제가 있어 Profile이 test로 설정되면 해당 클래스가 빈으로 등록되지 않게 만들었습니다!!

2023-07-09 17:11 UTC, young970 commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
>          }
제가 초기에 생각한 해당 객체의 역할은 사용자의 콘솔 입력에 맞는 각각의 컨트롤러를 관리하는 역할을 생각하고 해당 클래스 코드를 작성했습니다.
하지만 해당 클래스의 이름을 신경 쓰지 못했고, 또한 말씀하신 것처럼 애플리케이션의 실행을 계속할지 중단할지를 결정하는 역할 또한 맡고 있어 적절한 클래스명으로 분리하는 편이 좋을 것 같습니다.
(TMI로 해당 주석은 처음 자기주도 코드리뷰 때 흑구님이 handler mapping이 생각난다고 남겨주신 것인데 제 부주의로 정리하지 못했습니다... 좀 더 신경 쓰도록 하겠습니다...)

2023-07-09 17:54 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/service/MemberService.java
> +    }
현재 생각나는 문제로는 추후에 멤버 객체의 필드에 password가 추가될 경우 외부에 password가 노출되기에 따로 dto를 만들어 사용하게 될텐데 그로 인해 서비스 레이어 위의 도메인 객체를 반환하는 모든 객체들의 메소드를 전부 변경해야 하는 사항이 생길 것 같습니다. 이 외에도 좀 더 알아보고 dto를 적용해 보도록 하겠습니다!!

2023-07-09 18:00 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +    }
현재는 사용되는 곳이 없으나 추후에 사용되지 않을까 하고 미리 만들어두었습니다. 하지만 지금 생각해보니 필요할 때 만드는 것이 올바른 방법인 것 같습니다... 사용되지 않는 메서드들 정리하겠습니다!!

2023-07-09 18:01 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +            logger.error("Got empty result", e);
해당 사항 수정하겠습니다!!

2023-07-09 18:14 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +        String sql = "select * from member WHERE status = 'BLACK'";
1주차 미션 당시 파일로 관리했던 BlackListRepository 의 findAllBlackMember()를 그대로 가져와서 구현하였기에 
재사용 가능한 더 좋은 방식의 메서드를 구현하지 못했던 것 같습니다...해당 부분 수정하도록 하겠습니다.

2023-07-09 18:19 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/dao/JdbcVoucherRepository.java
> +            logger.error("Got empty result");
말씀하신 대로 해당 사항까지 에러 로그로 관리하게 되면 수많은 불필요한 로그 기록들이 쌓일 것 같습니다.
좋은 말씀 감사합니다!! 해당 부분 수정하겠습니다.

2023-07-09 18:22 UTC, young970 commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +
꿀 같은 좋은 정보 주셔서 정말 감사합니다!! 
해당 부분 수정하도록 하겠습니다.

2023-07-10 23:23 UTC, WooSungHwan requested changes
영운님 과제하시느라 수고 많으셨습니다~
리뷰 몇자 남겼으니 확인부탁드려요 ㅎㅎ

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +            case WALLET_LIST -> console.printAllWallet(walletController.findAllWallet());
이제 command가 이쯤 늘어나니 별도의 view Logic이 추가되어 console을 집어넣고 그쪽에서 createMember 같은 private 메소드에 담겨있는 로직을 위임하는게 어떨까 싶습니다. 클래스가 꽤 긿어졌죠? ㅎㅎ

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/exception/EntityNotFoundException.java
> +    }
`super();`

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/exception/NotUpdateException.java
> +    }
`super();`

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +        }
이런거 좋네요.

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +        String sql = "select * from member";
`select * from table` 같은 쿼리는 테이블의 모든 정보를 가져오기 때문에 불필요한 메타데이터 (등록시간, 수정시간, 등록자 등) 또한 포함해서 가져오고 rowMapper에서 꺼내 쓰지 않는 식으로 동작하게 될겁니다.
따라서 `select column1, column2 from table` 이런식으로 직접 꺼내 쓰는게 좋아요.

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/member/domain/MemberName.java
> +public class MemberName {
해당 클래스 public 떼고 한번 시도 해보시겠어요?ㅎㅎ

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/member/dto/CreateMemberRequest.java
> +}
얘는 CreateVoucherRequest랑 비슷한 용도로 쓰이는데 record로 선언되어있고 CreateVoucherRequest는 class로 선언되어 있군요ㅠㅠ

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/wallet/service/WalletService.java
> +    }
제가 이런거 만들때는 일급컬렉션을 고려해보라고 말씀드렸던 것 같은데 영운님도 컬렉션들 전체 일급컬렉션화 해보시는건 어떠신가요?

2023-07-10 23:23 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/wallet/service/WalletService.java
> +        return walletRepository.insert(new Wallet(UUID.randomUUID(), member, voucher));
@devYSK 수도코드로 간단한 예시를 들어주면 좋을 것 같아요!

2023-07-11 11:53 UTC, devYSK requested changes

2023-07-11 11:53 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/service/WalletService.java
> +        return walletRepository.insert(new Wallet(UUID.randomUUID(), member, voucher));
```java
interface Generator {
  UUID uuid():
}

// hmm.... where is this?
public class Runtime implements Generator {
  @Override
  public UUID uuid() {
    // your code
  } 
}


public class SomeWhere {
  private final Generator generator;
  
  public void some(Card card) {
    new Card(generator.uuid()); 
    //or
    new Card(generator);
  }
}

// hmm.... where is this?
public class TestTime implements Generator {
  
  private UUID uuid;
  
  @Override
  public UUID uuid() {
    return uuid;
  } 
}
```

2023-07-11 15:13 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/domain/Member.java
>      private final MemberStatus status;
맞습니다 수정하도록 하겠습니다!!

2023-07-11 15:26 UTC, young970 commented on src/test/java/org/prgrms/kdt/member/dao/BlackListRepositoryTest.java
> +    BlackListRepository blackListRepository;
말씀하신대로 현재의 코드로는 테스트를 통해 fileWrite()를 검증할 수 없을 것 같습니다. 해당 부분 고민해보도록 하겠습니다!!

2023-07-11 15:48 UTC, young970 commented on src/test/java/org/prgrms/kdt/util/ConverterTest.java
먼저 memberToString()메서드의 변환이 실패하는 경우로는 Member의 필드 값 중 일부가 null인 경우에 NullPointerException이 발생할 것 같습니다.

혹시 NullPointerException이 발생하는 것도 테스트에 추가해야 한다고 이해하면 될까요??...

2023-07-11 16:11 UTC, young970 commented on src/main/java/org/prgrms/kdt/wallet/service/WalletService.java
> +    public void deleteWalletById(UUID walletId) {
단일 쿼리의 경우는 트랜잭션이 필요 없다고 생각했었습니다.
하지만 delete 도중 문제가 생겼을 때 트랜잭션으로 처리하지 않았을 경우 롤백되지 않기에 심각한 문제로 이루어질 것 같습니다. 
트랜잭션에 대해 좀 더 공부해보겠습니다!!

2023-07-11 16:23 UTC, young970 commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +
고객a가 보유한 b바우처를 지우기 위해서는 먼저 해당 고객이 어떤 바우처들을 가지고 있는지 확인하는 작업이 먼저일 것이라고 생각했습니다.

마침 요구사항에 
- 고객이 어떤 바우처를 보유하고 있는지 조회.
- 특정 바우처를 보유한 고객을 조회.

이런 요구사항이 존재 하였고 저 두 조회 다 유저에게 고객네임, 바우처 타입, 할인양과 함께 walletId도 같이 제공하는 방식으로 구현하였기에
 유저에게 memberId와 바우처Id 두가지의 입력값을 받기보다 제공된 walletId를 입력받아 삭제하는 것이 합리적이라고 생각하였습니다.

2023-07-11 18:14 UTC, young970 commented on src/main/java/org/prgrms/kdt/CommendLineRunner.java
> +            case WALLET_LIST -> console.printAllWallet(walletController.findAllWallet());
말씀하신대로 현재 클래스를 분리해야할 것 같습니다. 한번 분리 해보도록 하겠습니다!!

2023-07-11 18:52 UTC, young970 commented on src/main/java/org/prgrms/kdt/exception/EntityNotFoundException.java
> +    }
EntityNotFoundException의 기본 생성자 안에 super()를 통해 부모 클래스의 기본 생성자를 명시적으로 호출하지 않더라도
자바 컴파일러에 의해 부모의 기본생성자를 불러주는 것으로 알고있어 실험을 해 본 결과 정상적으로 호출되는 것을 확인하였습니다.

혹시 관례같은 것일까요??... 아니면 제가 멘토님의 의도를 잘못 파악한 것인지 궁금합니다...

2023-07-11 18:53 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +        }
감사합니다...ㅎㅎ

2023-07-11 18:55 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/dao/JdbcMemberRepository.java
> +        String sql = "select * from member";
말씀하신 내용 반영하도록 하겠습니다!!

2023-07-12 05:11 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/domain/MemberName.java
> +public class MemberName {
public을 떼면 MemberName 클래스의 접근 제한자가  default가 되어 MemberName을 사용하는 JdbcMemberRepository
에 문제가 생기는 것을 확인하였습니다.

혹시 해당 클래스의 위치가 잘못되었다는 뜻일까요??...

2023-07-12 05:12 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/dto/CreateMemberRequest.java
> +}
CreateVoucherRequest도 record로 바꾸도록 하겠습니다!!

2023-07-12 05:13 UTC, young970 commented on src/main/java/org/prgrms/kdt/wallet/service/WalletService.java
> +    }
일급 컬렉션을 도입시켜보겠습니다!!

2023-07-17 04:55 UTC, young970 commented
## ✅ 2주차 PR 반영 사항
- CommendLineRunner의 컨트롤러를 호출과 view에 관련된 로직을 ViewManager로 분리하였습니다.
- 멤버 도메인 객체에서 변할 수 있는 값인 name과 status의 final 키워드를 제거하였습니다.
- Repository에서 엔티티를 찾지 못했을 때 에러 로그로 관리했던 것을 제거하였습니다.
- MemberRepository에서 findAllBlackMember를 제거하고 findByStatus로 대체함으로써 재사용성을 확보하였습니다.
- DTO 및 일급 컬렉션 적용하였습니다.
- Wallet 도메인 객체를 JoinedWallet과 Wallet으로 분리하여 사용하는 방식으로 변경하였습니다.
- WalletService에서 매번 변하는 walletId를 외부에서 주입 받는 방식으로 변경하였습니다.
- SpringBootTest에서 web관련 컴포넌트 제거하고 실행하도록 변경하였습니다.
- JdbcRepository 내의 모든 조회 쿼리문을 select * -> select column1, column2 방식으로 변경하였습니다.
- ConverterTest에서 올바르지 않은 멤버 객체를 스트링으로 변환 시 EntityNotFoundException이 발생하는지 검사하는 테스트를 추가하였습니다.
- BlackListRepositoryTest와 FileVoucherRepositoryTest에서 @PreDestroy 어노테이션이 정상적으로 호출되는지 검증하는 테스트를 추가하였습니다.

2023-07-17 08:06 UTC, devYSK approved these changes

2023-07-17 08:06 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +    }
alias는 A, B, C 보단 W M V 가 나아 보입니다.
p2;

2023-07-17 08:06 UTC, devYSK commented on src/test/java/org/prgrms/kdt/voucher/dao/FileVoucherRepositoryTest.java
> +    AnnotationConfigApplicationContext testContext;
!? ApplicationContext가 왜 필요한거죠?
p2;

2023-07-17 08:06 UTC, devYSK commented on src/test/resources/TestVoucher.csv
> +bc47fec3-060a-48ce-ac60-85cca6501cc4,FIXED,30
test resource 폴더의 용도가 무엇일까요?
p2;

2023-07-17 08:06 UTC, devYSK commented on src/test/java/org/prgrms/kdt/wallet/service/WalletServiceTest.java
> +        setupInsertWallets();
이 위치에는 필요 없는 주석인거 같습니다.
p2;

2023-07-17 08:11 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/controller/MemberController.java
>      }
사실 저 s의 위치에 대해 고민을 했었는데 이것도 팀원들과 이야기하여 정해보겠습니다!!

2023-07-17 08:31 UTC, young970 commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +    }
해당 사항 반영하겠습니다!!

2023-07-17 08:34 UTC, young970 commented on src/test/java/org/prgrms/kdt/wallet/service/WalletServiceTest.java
> +        setupInsertWallets();
사실 다른 개발자가 해당 테스트 코드를 볼 때 setupInsertWallets메서드를 보지 않고 해당 주석만 보고서 바로 파악하길 바라는 마음에 적어두었습니다.

2023-07-17 08:43 UTC, devYSK commented on src/test/java/org/prgrms/kdt/wallet/service/WalletServiceTest.java
> +        setupInsertWallets();
좋네요! 
문구를 좀 더 읽기 쉽게 적어봐도 좋을거 같아요

2023-07-17 08:50 UTC, young970 commented on src/test/java/org/prgrms/kdt/wallet/service/WalletServiceTest.java
> +        setupInsertWallets();
넵 해당 사항 반영해 보겠습니다!!

2023-07-18 03:13 UTC, WooSungHwan approved these changes
영운님 과제하시느라 수고 많으셨습니다 ㅎㅎ

2023-07-18 03:13 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +                "LEFT JOIN voucher C ON A.voucher_id = C.id";
왜 left join인가요~?

2023-07-18 06:43 UTC, young970 commented on src/main/java/org/prgrms/kdt/wallet/dao/JdbcWalletRepository.java
> +                "LEFT JOIN voucher C ON A.voucher_id = C.id";
wallet 테이블의 member_id와 voucher_id가 외래 키 제약조건이 설정되어 있고, 값이 null인 경우가 없다고 생각하여 결론적으로 inner join과 left join 둘 중 아무거나 사용해도 결과는 같을 것이라고 생각하여 깊이 생각하지 않고  left join을 사용했습니다.

하지만 wallet 테이블의 크기가 member와 voucher테이블의 크기보다 훨씬 커질수도 있는 상황에서 구동 테이블을 정해놓는 방식보단 dbms의 옵티마이저를 이용할 수 있는 inner join이 더 좋은 대안으로 보입니다!!
해당 내용 수정하겠습니다!!

2023-07-22 07:31 UTC, merged