W2
prgrms-be-devcourse/springboot-basic pull request #792
Opened 2023-07-10 03:10 UTC by 2jie0516

# 📌 SpringBoot Basic Weekly Mission
스프링부트 basic 위클리미션을 코드리뷰하는 Repository입니다.

# 📌 그림 그리기 & 설명하기
![스크린샷 2023-07-10 00-53-29](https://github.com/prgrms-be-devcourse/springboot-basic/assets/102570281/bc29c381-bc96-4409-85ca-ce02475a0419)

# 📌 요구 사항

**(기본)** **바우처 관리 애플리케이션**

- [ ]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [ ]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [ ]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

# 📌 작업 목록

- [ ]  그림그리기 & 소개하기에 맞게 패키지 구조 수정 및 추가
- [ ]  컨트롤러(commadLine)에서 crud 관련 메뉴 추가 및 메소드 호출 구현
- [ ]  바우처 관련 crud를 jdbc 를 이용하여 구현
- [ ]  바우처 crud 테스트 코드 작성
- [ ]  customer jdbc 테이블 설계
- [ ]  jdbc를 이용하여  customer 관련 crud 구현
- [ ] customer crud jdbc 테스트 코드 작성

2023-07-10 14:52 UTC, HyoungUkJJang reviewed
안녕하세요 세한님 그림 잘 그려주셨네요 ~!

1주차 과제를 진행하면서 규현 멘토님이 피드백을 잘 해주시고 세한님도 반영을 잘 해주셔서 제가 봤을땐  과하지 않고 역할 구분이 적절한 것 같아요 !

한가지 그림에서 궁금한점은 Voucher는 Voucher 타입을 가지고 있는데 그림 상으로 보면 패키지 위치가 서로 달라보이는데 의도가 있으실까요 ~?

그것 외에는 멘토님께서 피드백을 더 주실 수 있겠지만 저는 괜찮은 것 같아요 🙂👍🏻 고생하셨어요 !
+ 멘토님이 피드백으로 ok 사인을 주시면 2주차 바로 진행하셔도 좋을 것 같습니당 ~

2023-07-11 07:54 UTC, 2jie0516 commented
@HyoungUkJJang 
그림 좋게 봐주셔서 감사합니다 ! ㅎㅎ
VoucherType 같은 경우는 패키지 상으로 voucher에 위치해 있는데 그림을 그릴 때 enum 끼리 모아놓을려고 하다 보니까 구조가 잘못  전달된 것 같습니다 ㅠ
다음 pr을 올릴 때는 해당 부분 보완해서 올리겠습니다 !! 👍🏻

2023-07-13 10:40 UTC, 2jie0516 commented
jdbc로 바우처 crud 기능 구현하였습니다 !

추가된 기능은 다음과 같습니다.

- jdbc를 이용해서 바우처를 추가하거나 불러오기 , 삭제 하기등의 작업을 할 수 있습니다.
- 컨트롤러에서 바우처 기능 관련 메뉴를 선택할 수 있도록 바우처 메뉴를 추가하였습니다.

2023-07-15 06:17 UTC, 2jie0516 commented
스프링 2주차 과제 기능 구현 완료하였습니다 !

추가된 기능은 다음과 같습니다.

바우처 관리 기능
1. insert
2. find all
3. find by type
   - 바우처를 타입으로 조회할 수 있습니다.
4. delete all

회원 관리 기능
1. insert
2. find all
3. find by email
   - 회원을 이메일로 조회할 수 있습니다.
4. black
5. update info
   - 회원의 이메일 정보를 변경할 수 있습니다.
6. delete by email
   - 이메일로 회원 조회해 해당 회원 정보를 삭제합니다.
7. delete all

PR 포인트
1. 1주차의 요구사항을 그대로 유지하고 싶어서 블랙리스트를 csv 로 관리하는 방식을 유지하였습니다.
    때문에 csv 저장소 클래스는 더 이상 인터페이스를 구현하지 않고 독립적인 클래스로 바꾸었습니다.

2. SQL 문들을 관리하기 쉽게 상수 메세지 클래스를 만들었습니다.

이 외 클래스 변경 사항 설계도에 반영하였습니다.

감사합니다 !!

2023-07-15 17:18 UTC, Jo-GyuHyeon requested changes
안녕하세요 세한님. 위클리2 과제 하시느라 고생 하셨어요.
간단하게 리뷰 남겨 보았어요.
중복되는 로직들이 존재하여, 왠만하면 단건에 대해서만 리뷰를 남겨 두었어요.
리뷰내용을 보시고 관련된 내용이 있다면 함께 반영 해주시면 좋을것 같아요.

작업 목록과 커밋 메시지가 일치하지 않는것 같아요.
지금 부터라도 작업목록(이라쓰고 미리 커밋메시지 예상하기) 정리 해서 커밋을 작성해보시면 어떨까요?
고생하셨어요.

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +            case FIND_BY_TYPE -> output.printAllVoucher(voucherService.findByType(input.inputVoucherType()));
인자가 너무 깊어지는 것 같아요. 개인적으로 변수로 빼는 방식을 조금 추천 드리고 싶어요.
깊어질수록 인지 하는 수준이 낮아지고 가독성이 떨어지는 것 같아요.

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
해당 로직을 보았을때, 할인 값을 추가 하는 것이 아니라 바우처를 만드는 행위인것 같아요. 메서드 네이밍에 신경 써주시면좋을것 같아요.

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +                }
위의 리뷰와 동일 해요.
메서드 호출과, 인자를 넘겨주는 행위를 분리 하는 것이 좋을것 같아요.
인자가 너무 깊어지는 것 같아요. 개인적으로 변수로 빼는 방식을 조금 추천 드리고 싶어요.
깊어질수록 인지 하는 수준이 낮아지고 가독성이 떨어지는 것 같아요.

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        }
입력값에 대한 책임은 어디에 몰아주는 것이 좋을까요???

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddress(address), "이메일 형식이 올바르지 않습니다.");
checkAddress() 는 어떤행위를 체크 할까요?? 네이밍 만을 보았을때 address 길이도 함께 해줄것이라 기대가 되었던것 같아요.
네이밍 고민과, 별도의 분리 필요성, 혹은 12 번째라인도 인지 하기 좋은 메서드로 분리 해야 될지 여러가지 포인트로 고민 해보시면 좋을것 같아요.

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +    private static final RowMapper<Customer> customerRowMapper = (resultset, i) -> {
static 인 이유는 무엇일까요?

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }};
Map.of() 메서드를 사용 해보면 어떨까요??

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html#of()

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +            return jdbcTemplate.query(CustomerManageSql.findAllCustomerSQL, customerRowMapper);
sql 문만 따로 관리 했을때 어떤 이점이 있고 어떤 단점이 있을까요???
이런 경우라면 변(상)수로 관리 했을때 가독성이 더 있다고 판단 할 수 있을까요???

2023-07-15 17:18 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
예외를 사용하지 않고 empty 값으로 리턴 할 수 있는 방법이 있을것 같아요.

2023-07-16 08:45 UTC, HyoungUkJJang requested changes
세한님 2주차 과제 진행하느라 고생 많으셨습니다 ~

멘토님이 먼저 리뷰를 잘 남겨 주셨는데 저도 간단한 것 위주로 먼저 남겨봤어요
반영 후 계속해서 이야기 하면서 진행하면 좋을 것 같습니다.

고생하셨어요 😊

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/test/java/prgms/spring_week1/domain/voucher/repository/impl/JdbcVoucherRepositoryTest.java
> +}
테스트의 경우 순서에 의존적이지 않도록 수정하면 어떨까요?

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/test/java/prgms/spring_week1/domain/voucher/repository/impl/MemoryVoucherRepositoryTest.java
> +@ExtendWith(MockitoExtension.class)
Mockito를 사용하신 이유를 여쭤보고 싶습니당 ~

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/io/Output.java
> +        if (voucherList.equals(Collections.emptyList())) {
`voucherList.isEmpty()` 에서 `voucherList.equals(Collections.emptyList())` 로 변경하신 이유를 말씀해주세요 !

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/menu/VoucherMenu.java
> +    DELETE_ALL("deleteall");
아래의 형태가 관리하기 더 값을 추가, 삭제하는데 더 편하실 거에요 :) 
```suggestion
    INSERT("insert"),
    FIND_ALL("findall"),
    FIND_BY_TYPE("findbytype"),
    DELETE_ALL("deleteall")
    ;
```

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/menu/CustomerMenu.java
> +    private final String customerMenuType;
`VoucherMenu `의 리뷰와 동일해요 :) 참고해주세요 ~

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/sql/CustomerManageSql.java
> +}
키워드 같은 경우 대문자로 통일해주시면 좋을 것 같습니다.

+ 추가적으로 sql이 단순 String 형태의 관리는 어려움이 많을 것이라고 생각해요 가독성 뿐만 아니라 중간에 오타가 하나 들어가도 휴먼 에러 발생 확률이 높아집니다. 이런 문제점을 해결하기 위해서 빌더의 형태 클래스를 한번 만들어 보는건 어떻게 생각하시나요?

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        if (update != 1) {
1이라는 의미가 "업데이트 되었다" 라고 생각할 수 있을까요? 조금 더 의미를 부여해주시면 좋을 것 같아요

2023-07-16 08:45 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +    }
0과 1의 의미는 세한님만 알고 계실 것 같습니다. 배열로 받는 것 보다는 풀어서 의미 있는 이름의 값으로 받는게 더 좋아보여요

2023-07-17 14:02 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +                }
cfbb6e3984a4886af244b241051062b4a7a6d0a7 커밋 피드백 반영
- 해당 메소드를 분리하였습니다 !
- 또한 메소드를 분리하면서  printCustomerInfo 메소드가 객체를 받도록 변경하였습니다.

2023-07-17 14:04 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        }
10fd8aa398aa01ea8578530b87f5f123870b7f0f 커밋 피드백 반영
- switch 분기문에서 일괄적으로 예외처리를 하는 것은 바람직하지 않다고 생각해 각 계층에서 예외처리를 하도록 수정하고 switch문의 try catch 문을 제거하였습니다.!

2023-07-17 14:06 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddress(address), "이메일 형식이 올바르지 않습니다.");
09c583ed4d51349ffbfc2d4453c006c226d42d6f 커밋 피드백 반영
- 먼저 checkAddress 메소드의 네이밍을 구체화하였습니다. 
- 형식 체크 분리되있는 거에 반해 길이 체크는 분리가 되어있지 않아 통일성을 위해 길이 체크 메소드도 분리해주었습니다 !

2023-07-17 14:07 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +    private static final RowMapper<Customer> customerRowMapper = (resultset, i) -> {
4fb42a3f954365bd5949e250ea7f6a75a25cf69a 커밋 피드백 반영
- 앗 실습 도중 실수로 붙인 것 같습니다..
- static 키워드 제거하였습니다 !

2023-07-17 14:08 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }};
4f5dc1c2fb05db4190d78cebbe24e6a423887b7e 커밋 피드백 반영
- Map.of 메소드를 적용하였습니다.
- 기존 해쉬맵 add 메소드를 사용했을 때 보다 훨씬 가독성이 좋다고 느껴졌습니다.

2023-07-17 14:19 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
7892200168d6e96d431465cad5e13033ee458535 커밋 피드백 반영
- queryForObject 내부를 본 결과 결국 query를 통해 데이터를 조회하고 DataAccessUtils 이라는 라이브러리를 이용해 반환해주고 있다는 것을 알았습니다.
- DataAccessUtils 에 있는 singleResult 메소드를 이용해서 데이터가 없을 시 null을 반환하도록 하였습니다.
- Optional 을 반환하지 않은 이유는 호출되는 쪽에서 무조건 null 검사를 하기 때문에 Optional 로 한번 더 감쌀 이유가 없다고 생각했기 때문입니다 !

2023-07-17 14:23 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/menu/VoucherMenu.java
> +    private final String voucherMenuType;
3d5a4b10617300310c8cd57c3b59a73a0c390b05 커밋 피드백 반영
- enum의 name 메소드를 적용하였습니다 !

2023-07-17 14:26 UTC, 2jie0516 commented on src/test/java/prgms/spring_week1/domain/voucher/repository/impl/JdbcVoucherRepositoryTest.java
> +}
54321529d5af578a127773fa07b88541b969999c 커밋 피드백 반영
- @Order 어노테이션을 제거하였습니다 !

2023-07-17 14:29 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/menu/VoucherMenu.java
> +    DELETE_ALL("deleteall");
5b08cb6ac741e5742f3cd8818e96953321163c2d 커밋 피드백 반영
- 넵 해당 형식으로 수정하였습니다 !

2023-07-17 14:30 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/menu/CustomerMenu.java
> +    private final String customerMenuType;
47224c99d83c9e864b66b76a26da4db39382d095 커밋 피드백 반영
- 넵 메뉴 이름 수정하였습니다 !

2023-07-17 14:31 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/sql/CustomerManageSql.java
> +}
sql 같은 경우는 특히나 오타에 취약하기 때문에 저도 코딩을 하면서 에러를 많이 냈던 것 같습니다.
형욱 멘토님의 말대로 빌더 클래스를 적용해보겠습니다 !

2023-07-17 14:32 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +    }
e9e2220040258387e10296643d069bab6772fbed 커밋 피드백 반영
- 넵 배열을 받기보단 풀어서 하는데 다른 사람이 보기에 더 가독성이 좋다고 생각해서 코드 수정하였습니다 !
- insert 뿐만 아니라 update 메소드도 동일한 로직이 있어 변경하였습니다 !

2023-07-17 14:37 UTC, 2jie0516 commented
피드백 반영, 리팩토링 완료하였습니다 !

다만, sql 빌더 클래스의 경우 추가적인 학습이 필요하다고 생각해 내일 중으로 반영하겠습니다.

피드백 반영 과정에서 생긴 질문 사항들을 면담 혹은 슬랙으로 여쭤보겠습니다 ! 시간 되실 때 답변 주시면 감사하겠습니다 !!

2023-07-17 20:42 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
createVoucher 는 좋았던것 같아요. insertDiscountValue 라는 네이밍을 보고 한 리뷰 였어요.
추가 적으로 다시 리뷰를 남기겠지만 try catch 에 메서드로 빼는 것이 의미가 있을까? 싶어요. 
(private 메서드로 뺏다고 필요한 부분만 되었다고 생각들진 않는것 같아요.)
오히려 인라인으로 변경해서 필요한 부분만 try catch 를 감싸는건 어떨까요?

2023-07-17 20:44 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +                }
기복적으로 인자에는 실행 함수를 시키는것보다 변수를 넘기는 것을 더 선호 하는 편인것 같아요.
실행 행위와, 인자를 넘기는 행위는 나뉘어지는것이 좋고, 디버깅하기에도 수월하다고 생각해요.

2023-07-17 20:46 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddress(address), "이메일 형식이 올바르지 않습니다.");
check** 메서드가 따로 있다면 내부에서 적적한 예외를 발생 시키는 방향은 어떨까요?
(==Assert 를 사용하지 않아도 될것 같아요.)

2023-07-17 20:48 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
잘 반영하셨지만, Util 기능을 사용하지 않을수 있을것 같아요.
직접 로직을 구현 해보시면 어떨까요? 어렵지 않을것 같아요.

2023-07-18 01:40 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 남겼어요. 이번에는 중복되는 리뷰는 따로 남기지 않았어요.
관련 있는 내용 참고 하셔 반영 해주시면 좋을것 같아요.

2023-07-18 01:40 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddressFormat(address), "이메일 형식이 올바르지 않습니다.");
check 메서드가 있으니 Assert 를 사용하지 않을수 있을것 같아요.
위의 리뷰와 별개로 Assert 는 무조건 동작 하게 될까요??  동작하지 않을수도 있을까요?

2023-07-18 01:40 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
에러 메시지가 어색한것 같아요. insert 실패 이유는 다양할 수 있을것 같아요.
다만 회원 정보에 대한 유효성 검사를 진행 하신다면, service 단에서 확인 하는 로직에 의해 해당 예외문구가 발생하는 것이 자연스럽다고 생각해요.
Repository 는 Data 레이어 계층이라 로직이 섞이면 책임이 온전하다고 생각이 들지 않아요.

2023-07-18 01:40 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
try catch 를 사용하지 않는 방법으로 로직을 완성 시킬순 없을까요??

2023-07-18 01:40 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        return DataAccessUtils.singleResult(foundCustomer);
Util 을 사용하지 않아도 될것 같아요. Util 의 기능을 직접 구현하기에 어렵지 않다고 생각이 들어요.

2023-07-18 01:40 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +            logger.error("회원 정보를 찾을 수 없습니다.");
위의 리뷰와 동일해요.

2023-07-18 01:40 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +            logger.error("회원 정보를 찾을 수 없습니다.");
위의 리뷰와 동일해요.

2023-07-19 19:13 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
0c35bce22c0505f2e1f8d9a48f1db9145f8ad674 커밋 피드백 반영
- createVoucher 로 메소드를 통합해주었습니다 !
- try catch 문제 메뉴 검색 입력 메소드 두 개를 넣어주었는데 , 실패시 예외를 반환하기 때문입니다.
- 그 외 메소드는 try 문 밖으로 빼주었습니다.

2023-07-19 19:15 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +                }
876c917db4eeac42097d49882bfcf657a862e282 커밋 피드백 반영
- 넵 해당 형식으로 변경해주었습니다.

2023-07-19 19:17 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddress(address), "이메일 형식이 올바르지 않습니다.");
8342a4481b02b1732ab37d1509cb0dbb3ff8c751 커밋 피드백 반영
- assert 를 사용하지 않고 예외를 던지도록 하였습니다.
- null 체크 , 길이 체크 , 형식 체크 메소드들을 따로 만들어서 적절한 예외 메세지를 던지도록 하였습니다 !

2023-07-19 19:21 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
411f5d36bb3456defe4ee96e4574cdb04a25f56b 커밋 피드백 반영
- util을 사용하지 않고 직접 리스트를 조회해서 넘겨주도록 하였습니다 !
- 해당 메소드의 동작 방식이 0이면 null을 리턴하고 결과값이 2이상이면 예외를 발생시킨다는 것을 확인하였습니다.
- 따라서 쿼리 결과 조회값이 0이나 2이상이면 null을 반환하고 아니면 리스트의 첫번째 인자를 반환하는 식으로 로직을 구성하였습니다 !

2023-07-19 19:25 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddressFormat(address), "이메일 형식이 올바르지 않습니다.");
8342a4481b02b1732ab37d1509cb0dbb3ff8c751 커밋 피드백 반영
- 넵 Assert 를 사용하지 않고 예외를 던지도록 하였습니다.

만약 Assertion 이 동작하지 않는 경우는 해당 Assertion 문까지 도달하기 전에 예외가 발생하는 경우라고 생각합니다 !

2023-07-19 19:26 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }};
2e815469414f8666473d36728d58e88f3a20c012 커밋 피드백 반영
- Map.of 적용하였습니다 !
- 다른 메소드과 통일성을 주기 위해 같은 방식으로 변경하였습니다.

2023-07-19 19:28 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
18730757d377f8437e316089566b3bc75b1bd5a3 커밋 피드백 반영
- 해당 문구가 data 레이어에서 발생하는 게 적절치 못하다고 생각해서 제거해주었습니다.

2023-07-19 19:31 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        return DataAccessUtils.singleResult(foundCustomer);
411f5d36bb3456defe4ee96e4574cdb04a25f56b  커밋 피드백 반영
- 넵 util을 사용하지 않고 기능을 구현하였습니다 !
- 해당 메소드의 동작 방식이 0이면 null을 리턴하고 결과값이 2이상이면 예외를 발생시킨다는 것을 확인하였습니다.
- 따라서 쿼리 결과 조회값이 0이나 2이상이면 null을 반환하고 아니면 리스트의 첫번째 인자를 반환하는 식으로 로직을 구성하였습니다 !

2023-07-19 19:31 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +            logger.error("회원 정보를 찾을 수 없습니다.");
aa432f7901bdadc43e68ec0da75bce88d17acd3b 커밋 피드백 반영
- 위와 같은 방식으로 변경하였습니다 !

2023-07-19 19:32 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +            logger.error("회원 정보를 찾을 수 없습니다.");
aa432f7901bdadc43e68ec0da75bce88d17acd3b 커밋 피드백 반영
- 위와 같은 방식으로 변경하였습니다 !

2023-07-19 19:34 UTC, 2jie0516 commented
피드백 반영완료하였습니다 !

추가로 sql 쿼리 빌더 적용 완료하였습니다.
-> 06c2c2ad02d99628e5f142f81fe103d11f7f533f

좋은 리뷰 남겨주셔서 감사합니다

2023-07-20 01:45 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddress(address), "이메일 형식이 올바르지 않습니다.");
리뷰와 상관 없이 Assert 가 동작 할 수도 안할 수도 있어요. 언제 그렇게 되는지 조사 해보시면 좋을것 같아요.

2023-07-20 03:01 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
잘 하셨습니다. 하지만, 0 으로 비교 하기 보다 isEmpty() 로 비교를 가능 할것 같아요.

또한 1개 이상의 결과가 있을수도 있어요. 
그럴때는 어짜피 0번째 인덱스의 항복을 가져 오니 null 을 반환하는것은 개발단의 오류인것 같아요.
실제 여러 데이터가 있는 경우 쿼리 요청했을때 limi 1 을 요청하는 것과 동일해요.

2023-07-20 03:04 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/io/Output.java
> +        if (voucherList.equals(Collections.emptyList())) {
저는 현재 방식이 더 직관적이지 않다고 보고 있어요. 
그리고 불필요한 객체 생성 뿐만 아니라 해당 객체가 같은것인지? 내용이 같은것인지 헷갈릴수도 있다고 봐요.

2023-07-20 03:15 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddressFormat(address), "이메일 형식이 올바르지 않습니다.");
리뷰와 상관 없이 Assert 가 동작 할 수도 안할 수도 있어요. 언제 그렇게 되는지 조사 해보시면 좋을것 같아요.

2023-07-20 03:16 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
Optional 을 남발 하진 않았을까요??? null 비교로 충분히 emptyList 를 반환 할 수 있을것 같아요.
로컬 스코프에서는 null 에 대한 안정성이 이미 인지되어 있다고 봐요.

2023-07-20 03:17 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        return DataAccessUtils.singleResult(foundCustomer);
잘 하셨습니다. 하지만, 0 으로 비교 하기 보다 isEmpty() 로 비교를 가능 할것 같아요.

또한 1개 이상의 결과가 있을수도 있어요.
그럴때는 어짜피 0번째 인덱스의 항복을 가져 오니 null 을 반환하는것은 개발단의 오류인것 같아요.
실제 여러 데이터가 있는 경우 쿼리 요청했을때 limi 1 을 요청하는 것과 동일해요.

2023-07-20 05:56 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 드렸어요.
중복되는 내용이 있을 수 있지만, 각 라인마다 달진 않았어요.
쿼리 빌더 같은 경우에 각각 Root 레벨로 쪼개서 각 빌더를 만들어 보시는것을 제안 드리고 싶어요.
협력 관계를 이용해보시면서 타입언어의 장점을 잘 살려 컴파일어의 도움을 받을수 있도록 해보시면 좋을것 같아요.
고생하셨어요.

2023-07-20 05:56 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
printCustomerInfo(), printCustomerInfo() 를 불필요하게 나뉜듯해요.
메서드 내의 코드 복잡성에 너무 집착하고 계시진 않을지 생각해보시면 좋을것 같아요.

2023-07-20 05:56 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        if (!(address.length() >= 4 && address.length() <= 50)) {
부정문을 사용하지 않는 방법도 있을거에요. 
하드코딩으로 숫자를 기업하기 보다 상수로 관리 해보세요.
조건이 들어 가는 조건문의 인자는 최대한 연산자를 지양해보세요.

2023-07-20 05:56 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        }
위와 동일하지만 정규식이 어떤 정규식인지 파악하기 어려워요. 
그럴때도 상수로 관리 하시면 어떨까요? 상수명을 보면 이해하기 좋아 가독성이 좋아질거라 생각해요.
또한 상수로 관리하기에 메모리 측면에서도 이점이 있을거라고 생각해요.

2023-07-20 05:56 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/util/SqlBuilder.java
> +    public static class SelectBuilder {
쿼리 빌더 같은 경우에 각각 Root 레벨로 쪼개서 각 빌더를 만들어 보시는것을 제안 드리고 싶어요.

2023-07-20 05:56 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/util/SqlBuilder.java
> +        }
Where 문을 String 으로 받고 있군요.
WhereBuilder 협력 하고 있을 까요?
협력 관계를 이용해보시면서 타입언어의 장점을 잘 살려 컴파일어의 도움을 받을수 있도록 해보시면 좋을것 같아요.

2023-07-21 20:26 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddress(address), "이메일 형식이 올바르지 않습니다.");
넵 알겠습니다 ! 
주말 동안 꼭 조사해보겠습니다

2023-07-21 20:29 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
5e144a9c9734b44a9e13f6290b3bb96c500e869e 커밋 피드백 반영
- isEmpty 메소드를 적용하였습니다.
- 멘토님 말씀대로 2 이상의 경우는 생각할 필요가 없는 것 같습니다 .. !
- 코드 수정하였습니다 !

2023-07-21 20:30 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddressFormat(address), "이메일 형식이 올바르지 않습니다.");
넵 주말 동안 꼭 공부해보겠습니다 ..!

2023-07-21 20:32 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        }
9c30118654ca47d0a35316d89bd1443002af6c0a 커밋 피드백 반영
- 생각해본 결과 EmptyList를 반환하기 보단 검증 로직에서 리스트가 비어있는 경우(isEmpty)를 판단하도록 로직을 변경하였습니다 !

2023-07-21 20:33 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +        return DataAccessUtils.singleResult(foundCustomer);
5e144a9c9734b44a9e13f6290b3bb96c500e869e 커밋 피드백 반영
- isEmpty 메소드를 적용하였습니다.
- 멘토님 말씀대로 2 이상의 경우는 생각할 필요가 없는 것 같습니다 .. !
- 코드 수정하였습니다 !

2023-07-21 20:34 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +    }
917f79426914a54cbd6b5e7a54cd1d9bb766c51d 커밋 피드백 반영
- 해당 부분은 저의 설계 미스인 것 같습니다 .. ! 
- 두 메소드를 통합해주었습니다 !

2023-07-21 20:38 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        if (!(address.length() >= 4 && address.length() <= 50)) {
0cc437485484099d1b28f66cf71d5ebde9bb714b 커밋 피드백 반영
- 매직넘버 상수화 및 조건문 인자에 boolean 변수를 대입해주었습니다 !

2023-07-21 20:39 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        }
0cc437485484099d1b28f66cf71d5ebde9bb714b 커밋 피드백 반영
- 정규 표현식 상수화 진행하였습니다 !

2023-07-21 20:41 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/util/SqlBuilder.java
> +    public static class SelectBuilder {
6731ff7ed53124eef217016b11f8ca014a0aa518 커밋 피드백 반영
- select ,where , from 같은 쿼리들을 각각 쪼개어서 빌더를 만들었습니다 !
- 커밋 메세지를 수정하지 못한 체 푸시를 해버려서 메세지가 부정확한 점 양해 바랍니다 ㅠ

2023-07-21 20:44 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/util/SqlBuilder.java
> +        }
6731ff7ed53124eef217016b11f8ca014a0aa518 커밋 피드백 반영
- Where 빌더를 따로 만들어주었습니다
- delete 다음 from 빌더를 호출하기 않고 where 을 하게 되면 컴파일러에서 오류를 표시하기 때문에 이런 관점에 컴파일러의 도움을 받을 수 있다고 생각합니다 !
- 커밋 메세지를 수정하지 못한 체 푸시를 해버려서 메세지가 부정확한 점 양해 바랍니다 ㅠ

2023-07-21 20:53 UTC, 2jie0516 commented
리뷰 반영 완료하였습니다 !

좋은 피드백 주셔서 감사합니다.

2023-07-22 04:10 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        if (!(address.length() >= 4 && address.length() <= 50)) {
문자열 상수라면 컨벤션에 맞춰 대문자로 표기 하는것이 어떨까요?

2023-07-22 04:10 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        }
문자열 상수라면 컨벤션에 맞춰 대문자로 표기 하는것이 어떨까요?

2023-07-22 05:46 UTC, Jo-GyuHyeon requested changes
간단하게 코드리뷰 남겼어요.
확인 부탁 드려요.

2023-07-22 05:46 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        if (customerIsNull) {
존재 하지 않는다 라는 표현이 더 직관적일것 같아요.
findByEmail 에서 존재 하지 않는 경우 예외를 발생 시켜 예외 핸들링으로 처리 할수  있을것 같아요.

2023-07-22 05:46 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        boolean isInvalidEmailLength = (address.length() < MINIMUM_EMAIL_LENGTH || address.length() > MAXIMUM_EMAIL_LENGTH);
불필요한 괄호 인듯 해요.
숫자 범위를 표현 한다면 개인적으로 `최소 < 비교 < 최대` 처럼 보이면 가독성이 더 좋다고 생각해요.

2023-07-22 05:46 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +                .build();
하드 코딩대신 타입을 사용 해보면 어떨까요?  
문자열은 쉽게 아무 값이나 다 넣을 수 있다고 생각해요. Object 의 toString() 이 있으니 더욱더 타입의 안정성이 떨어 진다고 생각해요.
조금더 타입을 생각하시면서 빌더 인자 타입을 메서드에 알맞게 타입을 사용하면 어떨까요?
그렇다면 컴파일러의 도움 및 휴먼 에러도 줄어들것이라 기대 해요.

2023-07-22 05:46 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/util/SqlBuilder.java
> +    public static class SelectBuilder {
잘 나뉘셨지만 nested class 를 사용하지 말고 Root 레벨로 생성을 의미 했어요.
또한 빌더는 잘 만드셨는데 혹시 빠진 부분이 없는지 확인해주세요.

2023-07-23 07:21 UTC, HyoungUkJJang reviewed
세한님 코드 잘 봤습니다 :) 쿼리 빌더 열심히 만들어주신 것 같네요~

멘토님이 말씀해주신 것처럼 조금 더 수정해보시면 좋을 것 같습니다 !

2023-07-23 07:21 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/model/Customer.java
> +    protected LocalDateTime updatedAt;
```suggestion
    private final UUID customerId;
    private String name;
    private Email email;
    
    protected final LocalDateTime createdAt = LocalDateTime.now();
    protected LocalDateTime updatedAt;
```

2023-07-23 07:21 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        }
차라리 아래가 더 직관적인 것 같아요 

```suggestion
        if (address == null) {
            throw new IllegalArgumentException("이메일은 필수 입력값입니다.");
        }
```

2023-07-23 07:21 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +    }
```suggestion
    public void updateInfo(String beforeUpdateEmail, String afterUpdateEmail) {
        customerRepository.updateInfo(beforeUpdateEmail, afterUpdateEmail);
    }
```

2023-07-23 07:21 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/JdbcVoucherRepository.java
> +
개행 하나 빼주세요 :)

2023-07-23 07:21 UTC, HyoungUkJJang commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/JdbcVoucherRepository.java
> +                    .select("*")
selectAll() 메서드를 하나 제공해보는건 어떨까요?

2023-07-23 18:10 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        if (customerIsNull) {
808a370ae68ccfe8ab7b9f50d9b4bdc0ae60aa2f 커밋 피드백 반영
- findByEmail 메소드에서 예외를 발생시키도록 하였습니다 !

2023-07-23 18:11 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        boolean isInvalidEmailLength = (address.length() < MINIMUM_EMAIL_LENGTH || address.length() > MAXIMUM_EMAIL_LENGTH);
af124e7ea752b29092f83b5252851f0f94a8d04e 커밋 피드백 반영
- 저도 해당 형식이 더 가독성이 좋다고 생각해서 숫자 범위 형식을 변경하였습니다.

2023-07-23 18:14 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +                .build();
c906fa61504d5f69ffef612f99279de970ea9ef0 커밋 피드백 반영
- 빌더 타입에 알맞는 인자를 넣기 위해서 enum 타입을 사용하였습니다.
- from 에는 정해진 customer,voucer  Order 는 asc , desc 를 enum 타입으로 하여서 인자로 받게끔 하였습니다 !

2023-07-23 18:16 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/repository/impl/JdbcCustomerRepository.java
> +                .build();
cf16b2e76d3615680c2c7a790308c1a804d7d6d4 커밋 피드백 반영
- 각 빌더들을 루트 레벨 클래스로 분리하였습니다 !
- where 절에 or과 and 메소드를 추가하였고 OrderBy 빌더를 추가하였습니다.

2023-07-23 18:19 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        input.printConsoleMessage(ConsoleOutputMessage.COMPLETE_VOUCHER_INSERT_MESSAGE);
selectVoucherType 와 insertDiscountValue 메소드에서 발생되는 예외를 catch 위해서 try문에 따로 넣어두었습니다 !

try 문 내부에 해당 예외와 관련없는 로직이 들어가는 것을 지양하기 위해서 그 외 코드들은 빼주었습니다.

2023-07-23 18:20 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/Customer.java
> +    protected LocalDateTime updatedAt;
b79ea94151b16288bcc039a8fd30234313915856 커밋 피드백 반영
- 개행처리 수정하였습니다 !

2023-07-23 18:21 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        }
해당 부분도 고민해보겠습니다 !
조건문 인자에 연산자가 들어가는  것을 지양하기 위해 따로 변수를 만들어서 대입하였습니다.

2023-07-23 18:22 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +    }
7678d3b7c9e0c20e16458a8d02c88ec022a02eb7 커밋 피드백 반영
- 제안해주신 대로 코드 수정하였습니다 !

2023-07-23 18:22 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/JdbcVoucherRepository.java
> +
63bad691fa7071640c6da58ef67a76103bcf4ce4 커밋 피드백 반영
- 넵 수정하였습니다.

2023-07-23 18:23 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/voucher/repository/impl/JdbcVoucherRepository.java
> +                    .select("*")
cf16b2e76d3615680c2c7a790308c1a804d7d6d4 커밋 피드백 반영
- select 빌더를 따로 분리하면서 selectAll 메소드도 추가하였습니다 !
- 기존 코드에 select("*") 코드가 많았는데 selectAll 메소드를 추가해서 이런 코드들을 줄일 수 있어서 좋은 것 같습니다

2023-07-23 18:26 UTC, 2jie0516 commented
남겨주신 리뷰 참고해서 피드백 반영 완료하였습니다 !

이번 리팩토링을 진행하면서 쿼리 빌더를 각각 root 클래스로 분리하고  빌더 인자에 enum 타입을 적용하였습니다.

리뷰 남겨 주셔서 감사합니다 !

2023-07-24 05:35 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        if (customerIsNull) {
예외를 발생 시키는 레이어가 적절 한지 고민 해보시면 좋을것 같아요.
예외를 캐치해서 핸들링 하는 부분에서 적절한 레이어의 예외를 다루는지 고민해볼 수 있을 것 같아요.
다시 고민 해보세요.

2023-07-24 05:36 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddressFormat(address), "이메일 형식이 올바르지 않습니다.");
@2jie0516 주말에 공부 해보셨나요???

2023-07-24 05:40 UTC, Jo-GyuHyeon commented on src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +    }
실제로 인자를 넘겨 주는 부분에서 0, 1 이 무슨 의미인지 모를 수 있어요.
가독성을 위해서라도 변수로 빼는 것은 어떨까요? 
문제가 생기더라도 어느 변수, 코드라인인지 명확하게 확인이 불가능 하다는 점도 있을것 같아요.

```
private void updateCustomerInfo() {
    String[] emailInputs = input.inputUpdateEmailInfo();
    customerService.updateInfo(emailInputs[0],emailInputs[1]);
}
```

2023-07-24 05:45 UTC, Jo-GyuHyeon commented
코멘트에 대한 답변들도 남겨 두었으니 확인 부탁 드려요.
Hidden 에 가려져 있을 수 있으니 꼼꼼히 확인 부탁 드려요.

리뷰를 남기기전에 팀내에서 진행 하는 JDBC 익숙해지기 시리즈 중에서 쿼리 빌더 부분을 따로 리뷰 진행 하고 코드리뷰를 진행 하면 좋을 것 같아요.

2023-07-29 16:01 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        Assert.isTrue(checkAddressFormat(address), "이메일 형식이 올바르지 않습니다.");
넵 멘토님, 리뷰를 받은 주에 Assert 에 관해 대략 알아보았지만 결론을 내지 못하고 이번에 다시 공부를 해보았습니다.
제가 사용한 Assert 는 스프링에서 지원하는 프레임 워크인데 , 유저 이메일에 대해 검증을 하기 위해 사용하였습니다 !

근데 Assert 가 동작하지 않는 구체적인 찾지 못하여서 2가지 관점에서 고민을 해보고 있습니다.
1.  Assert에 들어가는 입력값의 문제
2.  Assert 설계 자체의 결함
 
혹시 제가 고민하고 있는 방향이 맞을까요 ?

Assert에 대해 조사하면서 
https://www.baeldung.com/spring-assert
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/Assert.html

해당 사이트를 참고했습니다 !

멘션 늦게 봐서 죄송합니다 ㅠ

2023-07-29 16:04 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/model/embeddedType/Email.java
> +        }
994a3d4a3798bf45727131dadd885c9124fa59cb 커밋 피드백 반영
- 넵 상수 컨벤션에 맞게 수정하였습니다 !

2023-07-29 16:07 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/CommandLine.java
> +        if (customerIsNull) {
3d04117ad30f414d12a1f4fe793be987e8fa3472 커밋 피드백 반영
- repository 계층에는 null만 반환하고 서비스 계층에서 예외를 발생시키도록 하였습니다 !
- 이렇게 한 이유는 만약 jdbc 외에 다른 저장소가 들어왔을 때도 null을 반환시키게 함으로써 서비스 계층에서 그대로 받을 수 있게 함입니다.
- 서비스 계층에서 예외를 발생시킬 때 직관적인 예외 표현을 위해 NoCustomerFoundException 예외를 새로 만들었습니다.

2023-07-29 16:09 UTC, 2jie0516 commented on src/main/java/prgms/spring_week1/domain/customer/service/CustomerService.java
> +    }
c27133e1358cae49a9b1c0463470c05f1abee0c6 커밋 피드백 반영
- 넵 해당 방식으로 수정하였습니다 !
- 가독성을 위해서 배열 인자를 넘겨주는 방식보단 변수를 넘겨주는 방식을 이용하겠습니다.

2023-07-29 16:16 UTC, 2jie0516 commented
리뷰 피드백 반영 , 쿼리 빌더 보완 완료하였습니다 !

이번 리팩토링을 통해 기존 쿼리 빌더의 구조를 변경하였습니다.
1. 예를 들어 SelectBuilder 를 실행하면 Select 가 나오도록 하였습니다.
2. 각 빌더를 인자로 받도록 하였습니다.

추가로 리뷰 반영 사항 코멘트에 남겨드렸습니다.

감사합니다 !

2023-08-07 14:10 UTC, Jo-GyuHyeon approved these changes
쿼리 빌더를 구현 하셨군요.
고생하셨어요. 
가끔은 너무 과하지 않을까 고민 하시면 좋을것 같아요.
단순함이 주는 이점도 많아요. 
지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-09 06:37 UTC, merged