[4기 원건희] 5차 PR 반영입니다.
prgrms-be-devcourse/springboot-basic pull request #795
Opened 2023-07-10 08:30 UTC by weonest

## 📌 과제 설명 
고객과 바우처에 대한 JDBC 구현

## ✅ 피드백 반영사항  
- 58207ffe0b4e04ae15901c4e5a9817e3f9e522dd `printVouchers` 수정
- 바우처의 `expiredAt`  JDBC에서 사용하므로 기존의 `public`유지
- 55970b42ce75824a63f273e5531b651bfc60e677 해당 부분 피드백은 잘 이해를 하지 못했습니다ㅜㅜ
- cfa5372563f9906b6512916a0312a41e781e4955 사용하지 않는 `aop` 설정 제거
- 35efaf557dfbbe0ae2ec3ee11dfeb82901b8a5d2 정적 변수로 사용하던 변수들 인스턴스로 변경 
- 6cb4edf755ffc846aeeb200140707b01c37abdfb 불필요한 주석 삭제
- `modifiedAt` JDBC 적용으로 `update` 메서드에서 활용
- `id`에 대응하는 값이 없을 경우 -> `list` 조회와 다르게 `id`로 조회하는 경우는 없는 값으로 조회를 하기 때문에 에러를 반환하는 게 맞다고 생각하여 에러를 반환하도록 구현하였습니다.
- 875bf450586eec53cd453ad0e4d3eea7b8f77451 `error`에 대한 로그만 남겼던 이유 -> 에러만 잡아내서 관리하면 되겠다고 생각하였는데, 피드백을 보고 다시 생각해보니 에러가 나기 이전 어떤 경위로 애플리케이션이 동작했는지 알기 위해서는 에러보다 낮은 수준의 로그들도 확인이 필요하겠구나라고 생각하여 수정하였습니다.

## ✅ PR 포인트 & 궁금한 점

2023-07-10 13:14 UTC, seung-hun-h requested changes
건희님 리뷰남겼습니다~

2023-07-10 13:14 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +    }
spring jdbc는 다양한 parameter source를 제공하고 있어요. 참고하면 좋을 것 같아요

https://github.com/benelog/spring-jdbc-tips/blob/master/spring-jdbc-core.md

2023-07-10 13:14 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +    private NamedParameterJdbcTemplate jdbcTemplate;
```suggestion
    private final NamedParameterJdbcTemplate jdbcTemplate;
```

2023-07-10 13:14 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +                " values(:id, :name, :createdAt, :modifiedAt)";
```suggestion
	String sql = """
                insert into customer (id, name, created_at, modified_at)
                values(:id, :name, :createdAt, :modifiedAt)""";
```

2023-07-10 13:14 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/service/CustomerServiceImpl.java
> +    private CustomerRepository customerRepository;
```suggestion
    private final CustomerRepository customerRepository;
```

2023-07-10 13:14 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/service/CustomerServiceImpl.java
> +        Customer oldCustomer = customerRepository.findById(requestDto.customerId());
`findCustomerById `를 활용하는건 어떻게 생각하시나요?

2023-07-10 13:14 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/JdbcVoucherRepository.java
> +@Profile({"jdbc", "test"})
test 프로파일을 지정하신 이유가 있을까요?

2023-07-10 13:14 UTC, seung-hun-h commented on src/test/resources/application-test.yml
파일 이름 끝에 test는 제거해도 될 것 같아요

2023-07-10 13:14 UTC, seung-hun-h commented on src/test/resources/application-test.yml
> +      on-profile: test
이거는 없어도 될 거 같은데 아닌가요?

2023-07-10 13:24 UTC, weonest commented on pom.xml
> +            <groupId>org.testcontainers</groupId>
강의에서 나온 `wix`의 MySQL 경우 윈도우에서는 8버전 이상은 동작하지 않는 문제점이 있었고, H2의 경우 실제 MySQL과 쿼리문 또는 자료구조가 다른 경우가 있기 때문에 다른 대안을 찾던 도중 테스트 컨테이너를 발견하여 사용하였습니다!

2023-07-10 13:31 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/JdbcVoucherRepository.java
> +@Profile({"jdbc", "test"})
테스트 코드에서 test 프로파일을 지정해줌으로써 테스트컨테이너 설정을 가져오기 때문에 본 클래스에서도 지정해주었습니다.

2023-07-10 13:33 UTC, weonest commented on src/main/resources/logback.xml
>          <file>logs/access.log</file>
e0b07b14d0f98e48aa5cf057462b897a3616ebcd
반영하였습니다!

2023-07-10 13:42 UTC, weonest commented on src/main/java/com/programmers/customer/service/CustomerServiceImpl.java
> +    private CustomerRepository customerRepository;
e5bcf545ca7a467c64a32ae31d967cd0cf6ffbc0
반영하였습니다!

2023-07-10 13:42 UTC, weonest commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +                " values(:id, :name, :createdAt, :modifiedAt)";
1ac71768510055e0a51e701a888e917219060cee
반영하였습니다!

2023-07-10 13:55 UTC, weonest commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +    private NamedParameterJdbcTemplate jdbcTemplate;
https://github.com/prgrms-be-devcourse/springboot-basic/commit/1ac71768510055e0a51e701a888e917219060cee
적용하였습니다!

2023-07-10 15:03 UTC, weonest commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +    }
BeanPropertySqlParameterSource 에 객체를 전달해주면 자동으로 getter로 가졍로 수 있는 필드들을 매핑시켜주는 것 같은데 필드가 객체인 경우에는 어떻게 해야 하나요? 찾아봐도 정보가 많지 않네요..ㅜ

2023-07-11 00:41 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/service/CustomerServiceImpl.java
> +        Customer oldCustomer = customerRepository.findById(requestDto.customerId());
Id를 통해 Customer를 조회하는 API가 작성되어 있어서 말씀드렸습니다. `findCustomerById`는 dto를 반환하고 repository는 도메인 클래스를 반환하니 사용성이 조금 다를 수 있기 때문에 분리해서 사용할 수도 있고, 조회 로직이 조금 복잡해지면 중복 코드가 발생할 수 있으니 `findCustomerById`를 사용할 수 있을 것 같아서 말씀드렸습니다. 이 부분을 생각하신 것 같아 그대로 Repository를 사용해도 좋을 것 같습니다.

2023-07-11 01:07 UTC, seung-hun-h commented on src/test/resources/application-test.yml
> +      on-profile: test
`spring.config.activate.on-profile`은 어떠한 프로파일일때 해당 설정을 주입하는 속성으로 알고있는데 아닌가요?
테스트를 실행하면 test 하위의 application.yml이 주입되어서 해당 속성을 작성하지 않아도 될 것 같아서요.

https://stackoverflow.com/questions/73062721/what-is-diff-between-spring-profiles-active-vs-spring-config-activate-on-profile

2023-07-11 01:32 UTC, seung-hun-h commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +    }
저도 많이 사용하진 않아서, `BeanPropertySqlParameterSource`를 사용하기 적합하지 않다면 `MapSqlParameterSource` 사용을 고려해봐도 좋을 것 같아요.

2023-07-11 01:34 UTC, seung-hun-h commented on src/main/java/com/programmers/voucher/repository/JdbcVoucherRepository.java
> +@Profile({"jdbc", "test"})
테스트용으로 만든 클래스가 아니라면, 필요할 때 테스트코드에서 jdbc 프로파일을 설정해주면 될 것 같은데 어떻게 생각하세요?

2023-07-11 01:37 UTC, seung-hun-h commented on src/test/java/com/programmers/voucher/repository/JdbcVoucherRepositoryTest.java
> +    @Configuration
```suggestion
    @TestConfiguration
```

2023-07-11 01:43 UTC, seung-hun-h commented
전체 테스트를 실행해봤는데 실패하는 케이스가 있는 것 같아서 확인해주세요!

<img width="251" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/60502370/e687e247-edee-4ef0-845e-b2d167d40d31">

2023-07-11 06:22 UTC, weonest commented on src/main/java/com/programmers/voucher/repository/JdbcVoucherRepository.java
> +@Profile({"jdbc", "test"})
우선 `@Profile`에 대해서는 `@Primary`가 동작하지 않는 것 같습니다. `jdbc`만을 남기는 경우 테스트 코드에서 `test` 프로파일을 설정하면 해당 클래스의 bean을 가져오지 못하는 문제가 발생하였습니다.
따라서 `jdbc`만을 남겨주되 테스트 환경에서는 해당 클래스를 직접 bean에 등록하여 사용하도록 변경하였습니다.

2023-07-11 06:25 UTC, weonest commented on src/test/resources/application-test.yml
> +      on-profile: test
86b3b76c57d9d8a494fec92e1b4fb4f8c13563f6
말씀하신대로 test 하위의 application.yml이 인식되기 때문에 해당 속성을 작성하지 않아도 정상 작동하였습니다! 감사합니다!

2023-07-11 06:26 UTC, weonest commented on src/test/java/com/programmers/voucher/repository/JdbcVoucherRepositoryTest.java
> +@Transactional
a90c685c8d89e903f76d6dbe9e4edf572c236219
적용하였습니다!

2023-07-11 06:27 UTC, weonest commented on src/test/java/com/programmers/voucher/repository/JdbcVoucherRepositoryTest.java
> +    @Configuration
35535d4ff83d4525673f07b347b845fc8b65b0ff
적용하였습니다!

2023-07-11 14:25 UTC, dojinyou commented on logs/access.log
gitignore 처리가 안된 것 같아요!

2023-07-11 14:25 UTC, dojinyou commented on pom.xml
>          </dependency>
H2 안 쓰시면 지워도 될 것 같아요!

2023-07-11 14:25 UTC, dojinyou commented on src/main/java/com/programmers/customer/controller/CustomerController.java
> +    }
create요청 dto와 update dto를 같이 쓰시는 이유가 있나요?

2023-07-11 14:25 UTC, dojinyou commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +        }
이렇게 되면 멱등성은 보장이 안될 것 같은데 괜찮을까요?

2023-07-11 14:25 UTC, dojinyou commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +        int update = jdbcTemplate.update(sql, Collections.singletonMap("id", customerId.toString()));
혹은 soft delete 아시나요? hard delete하면 cascading 처리가 되어 있을까요?

2023-07-11 14:25 UTC, dojinyou commented on src/main/java/com/programmers/customer/service/CustomerServiceImpl.java
> +@Transactional(readOnly = true)
해당 어노테이션을 적용한 이유가 있나요?

2023-07-11 14:25 UTC, dojinyou commented on src/test/java/com/programmers/customer/repository/JdbcCustomerRepositoryTest.java
> +        jdbcCustomerRepository.save(testCustomer3);
반복문?

2023-07-11 15:54 UTC, weonest commented on logs/access.log
341f2513d2432edb883688eda6eddc8d38434b03
해당 파일 폴더 삭제와 함께 다시 적용하였습니다!

2023-07-11 15:56 UTC, weonest commented on pom.xml
>          </dependency>
개더에서 말씀해주신 것을 참고하여 `@ConditionalOnProperty` 이외의 다양한 애노테이션을 통해서 설정을 해보았는데 정상적으로 동작하지 않았습니다. 아마 어노테이션의 문제 보다는 제가 어디선가 놓치는 부분이 있는 것 같습니다! 해당 부분은 좀 더 알아보고 적용해보도록 하겠습니다!

2023-07-12 05:11 UTC, weonest commented on src/main/java/com/programmers/customer/controller/CustomerController.java
> +    }
create 요청 dto를 update에서 사용해도 동작에는 문제가 없어서 사용을 했었는데, 다시 생각해보니 create 요청과 update 요청의 값이 항상 같을 수는 없기 때문에 update가 단순히 create 요청 dto에만 의존하는 것은 문제가 있다고 판단하여 `CustomerUpdateRequest` 레코드를 추가하였습니다
c409a13b78535f91e0e4eaa3b9d2ca7ca4e96f55

2023-07-12 05:36 UTC, weonest commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +        }
9ff7b547c942d4983073ea21170c483c5c12314e
다음과 같이 변경하였습니다!

2023-07-12 05:39 UTC, weonest commented on src/main/java/com/programmers/customer/service/CustomerServiceImpl.java
> +@Transactional(readOnly = true)
읽기 전용 트랜잭셔널을 사용하면 영속성 컨텍스트가 Entity 변경 감지에 대한 스냅샷을 보관할 필요가 없기 때문에 성능이 올라가는 것으로 알고 있습니다. 현재 서비스에서 대부분의 메서드는 조회 관련 쿼리이기 때문에 전체적으로 읽기 전용 트랜잭셔널을 적용하고, CRUD가 발생하는 메서드에서는 일반적인 트른잭셔널을 적용해 주었습니다!

2023-07-12 05:44 UTC, weonest commented on src/test/java/com/programmers/customer/repository/JdbcCustomerRepositoryTest.java
> +        jdbcCustomerRepository.save(testCustomer3);
d7a5d134267377015fcf427a08d7642ff6e272a8
반복문으로 변경하였습니다!

2023-07-12 06:03 UTC, weonest commented on src/main/java/com/programmers/customer/repository/JdbcCustomerRepository.java
> +        int update = jdbcTemplate.update(sql, Collections.singletonMap("id", customerId.toString()));
제가 생각했을 때 `soft delete` 를 사용하면 얻을 수 있는 장점으로 삭제된 데이터의 복구 및 통계 활용 등에서 장점이 있을 것 같습니다! 또한 다른 예시로 악의적인 행동을 한 후 스스로 탈퇴한 고객 정보가 `hard delete` 되는 경우 추적하기 어렵다는 점 등 `soft delete`와 `hard delete`의 사용 시점에 대한 고민을 해보게 되는 계기가 되었습니다! 
현재 제가 설계한 프로젝트에서는 `지갑` 부분에서 `voucherId`와 `customerId`에 대해 캐스캐이딩 처리를 해주는 식으로  설계를 하기도 했으며, 삭제한 정보를 추후에 활용하게 되는 요구 사항은 없을 것이라 판단하여 `hard delete`를 유지하도록 하였습니다!

2023-07-12 06:07 UTC, merged