[4기 - 박은지] 5차 PR 고객, 바우처 Jdbc 레포지토리 구현
prgrms-be-devcourse/springboot-basic pull request #803
Opened 2023-07-11 16:05 UTC by 1o18z

## 📌 과제 설명 
고객 Jdbc와 바우처 Jdbc 레포지토리를 구현하였습니다 ! 🌙
## ✅ 피드백 반영사항  
- [X] Pattern 수정 224b149ac660094a6b5596f126ad3e62152b3292
- [X] DiscountType이 Unit에 대한 정보를 가지도록 변경 fba2c1ede39f6ebe55e125f89a4c4b4ba97f3815
- [X] 테스트코드 메소드명 수정 89cb78cf3c44b551e0f7878afe3d9d38613e150a

2023-07-12 00:25 UTC, seung-hun-h requested changes

2023-07-12 00:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +          case CREATECUSTOMER -> createCustomer();
```suggestion
          case VOUCHER_LIST -> voucherList();
          case CREATE_VOUCHER -> createVoucher();
          case CUSTOMER_LIST -> customerList();
          case CREATE_CUSTOMER -> createCustomer();
```

2023-07-12 00:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
>        }
`IllegalArgumentException`과 `NoSuchElementException`의 로깅 레벨이 다른 이유가 뭔가요?

2023-07-12 00:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +  }
```suggestion
  private void printCustomers() {
    List<Customer> list = customerService.findAllCustomers();
    console.printAllCustomers(list);
  }
```
메서드는 동사나 동사구로 작성하는 것이 좋아보이네요

2023-07-12 00:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/customer/Customer.java
> +  private String customerName;
customer을 붙여준 이유가 있나요?

2023-07-12 00:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +  }
똑같이 사용자의 입력을 받아오는 것 같은데, 메서드를 분리할 필요가 있었나요?

2023-07-12 00:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/repository/customer/JdbcCustomerRepository.java
> +  }
```suggestion
  @Override
  public void deleteAll() {
    jdbcTemplate.update("DELETE FROM customers", Collections.emptyMap());
  }
```

`Map.of`와 `Collections.emptyMap()`의 차이를 알아보는 것도 좋겠네요

2023-07-12 00:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/repository/customer/JdbcCustomerRepository.java
> +            Map.of("customerId", customerId, "customerName", customerName));
`MapSqlParameterSource`를 사용하지 않은 이유가 있나요?

2023-07-12 00:25 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +@Rollback(value = false)
롤백을 하지 않는 이유가 있나요?

2023-07-12 00:25 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +@SpringBootTest
레포지토리를 테스트하는데 모든 빈들을 등록할 필요는 없을 것 같아요.

```suggestion
@Import(JdbcCustomerRepository.class)
@JdbcTest
```

2023-07-12 00:25 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +  @Order(1)
테스트의 순서를 부여하는 것은 테스트간 종속을 일으킬 수 있다고 생각해요. 순서와 무관하게 모든 테스트가 독립적으로 실행될 수 있도록 수정하는 것이 좋을 것 같아요

2023-07-12 00:25 UTC, seung-hun-h commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +  void findById() {
테스트 메서드 네이밍이 여기만 좀 다른 형식이라 맞춰주는 것이 좋을 것 같아요

2023-07-12 00:49 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
>        }
메뉴와 타입 선택을 잘못 했을 때는 error를 출력하는 건 조금 과하다고 생각이 되어 이런 경우에는 warn으로 하고, 할인값 범위, 잘못된 이메일 형식 등의 예외는 error로 출력하게 하기 위해서 나눴습니다 !

2023-07-12 00:52 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/customer/JdbcCustomerRepository.java
> +            Map.of("customerId", customerId, "customerName", customerName));
2개까지는 Map.of()를 사용해도 괜찮을 것 같다고 생각이 들어 사용했습니다 ! 3개 이상부터는 MapSqlParameterSource나 BeanPropertySqlParameterSource를 사용하였습니다 !

2023-07-12 00:55 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +  @Order(1)
헉 그렇군요...!! 참고하여 수정하겠습니다 !!🤩

2023-07-12 04:14 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/repository/voucher/MemoryVoucherRepository.java
> +    }
find의 결과로 예외가 발생했을 때와 DB 문제로 예외가 발생했을 때를 구분할 수 있을까요?

2023-07-12 04:14 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/repository/voucher/MemoryVoucherRepository.java
> +    }
find 결과가 없는 경우 예외로 처리하는 게 적절할까요?

2023-07-12 04:14 UTC, dojinyou commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/DiscountType.java
> +    }
굳이 static 메서드로 만들 필요가 있나요?

2023-07-12 04:14 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +    assertNotEquals(customer.getCustomerName(), newName);
customer 객체를 그대로 이용하는 게 적절한가요?

2023-07-12 04:28 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/customer/Customer.java
> +  private String customerName;
Customer를 작성할 때 바우처에 name이 있었나 하고 헷갈려 한 적이 있어서 한 번 있어서 변수명만 봐도 명확히 알 수 있도록 수정하였습니다...😅 기존에 했던 name으로 가는 게 더 좋은 방법일까요 ?!

2023-07-12 04:31 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +  }
나누는 것에 집중을 하다보니 너무 과하게 나뉘게 된 것 같습니다..! 하나로 수정하였습니다 !!🤩

2023-07-12 07:02 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/voucher/MemoryVoucherRepository.java
> +    }
피드백을 받고 예외 처리에 대한 여러 자료들을 읽어봤습니다 ! 혹시 모르니까 예외면 다 처리해야겠다고 생각을 하고 모든 예외를 받고 처리를 하려했는데,  멘토님 말씀대로 그렇게 하면 어떤 예외인지도 모르고 예외 메시지만 덩그러니 남아서 어쩌라고식이 된다는 걸 알게 되었습니다 ! find 결과가 없을 경우 빈 Optional을 반환하고 상위에서 예외를 처리하도록 변경하려고 합니다 !
잘못 알고있는 부분이 있다면 피드백 주시면 감사하겠습니다 🙂

2023-07-12 10:36 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
>  public class VoucherController {
'사용자 요청이 오면 그 요청을 어떻게 처리할 건지 결정하는 역할'이라고 생각하고 있습니다 ! 이것저것 추가하다 보니 컨트롤러가 점점 더 많은 일을 수행하고 있는 것 같습니다. 역할을 잘 생각하면서 적절히 나누도록 수정하겠습니다 !

2023-07-12 15:55 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/voucher/MemoryVoucherRepository.java
> +    }
find의 결과로 예외가 발생했을 때와 DB 문제로 예외가 발생했을 때를 구분할 수 있을까요?
- MemoryVoucherRepository와 JdbcVoucherRepository의 find 결과가 예외로 발생할 경우 둘 다 NoSuchElementException를 던지도록 했지만, DB문제로 발생했을 경우에는 예외 정보를 같이 넘겨주어 구분할 수 있도록 수정했습니다 !

find 결과가 없는 경우 예외로 처리하는 게 적절할까요?
- 바우처가 돈과 관련된 부분이기 때문에 이런 상황에서는 예외로 처리하는 게 더 적절하다고 생각이 되어서 예외로 처리를 했습니다 ! 그런데 고민을 좀 더 해보니 이 부분을 처리하는 더 나은 방법이 있는 것 같아서 적용해 보는 중입니다 !

2023-07-12 15:59 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/DiscountType.java
> +    }
static으로 할 필요가 없는 것 같습니다...! 더 고민하면서 수정하겠습니다 !

2023-07-14 04:31 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +@Rollback(value = false)
이것저것 붙여보면서 하다가 지우고 반영하는 것을 깜빡했습니다🥲 수정하겠습니다 !

2023-07-14 07:11 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/DiscountType.java
> +    }
f3c70eef

2023-07-14 07:11 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/voucher/MemoryVoucherRepository.java
> +    }
9921958a

2023-07-14 07:11 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/MenuType.java
> +  CREATECUSTOMER;
936f27d

2023-07-14 07:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
>      }
147d66ad

2023-07-14 07:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
>  public class VoucherController {
61d06a6

2023-07-14 07:12 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +  void findById() {
b54a3728

2023-07-14 07:12 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +  @Order(1)
b54a3728

2023-07-14 07:12 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +@SpringBootTest
b54a3728

2023-07-14 07:12 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +@Rollback(value = false)
b54a3728

2023-07-14 07:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/customer/JdbcCustomerRepository.java
> +  }
어떤 차이가 있고 무엇인지 공부를 한 뒤 이 경우에는 Collections.emptyMap()가 더 적절하다는 걸 알고, 적용하였습니다 !
147d66a

2023-07-14 07:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Console.java
> +  }
147d66a

2023-07-14 07:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +  }
936f27d

2023-07-14 07:12 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
> +          case CREATECUSTOMER -> createCustomer();
936f27d

2023-07-14 07:16 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/io/Output.java
> +  void printAllVouchers(List<Voucher> vouchers);
DTO를 사용해야 하는 이유와 사용 방법 등에 대해 공부한 후 DTO를 만들어 적용하였습니다 !
적절히 사용하려고 고민하며 적용했지만, 잘못된 부분이 있다면 피드백 주시면 반영하겠습니다 !
[ab8766d](https://github.com/prgrms-be-devcourse/springboot-basic/pull/803/commits/ab8766d52e86c7fce6d0cdcdbdab0cdd19a346b4)

2023-07-14 07:17 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +    assertNotEquals(customer.getCustomerName(), newName);
customer를 직접 사용하는 건 적절하지 않다고 생각하여 수정하였습니다 ! [0d8a88d](https://github.com/prgrms-be-devcourse/springboot-basic/pull/803/commits/0d8a88df94e867126fa1f20c8b03d2f55007171b)

2023-07-14 10:25 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/customer/Customer.java
> +  private String customerName;
개인차가 있을 수 있겠지만 Customer 클래스 내부의 name이므로 그대로도 명확한 것 같아요.

2023-07-14 10:46 UTC, seung-hun-h requested changes

2023-07-14 10:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/customer/Customer.java
> +  }
- newName은 유효성 검증이 필요 없나요?
- 값을 그대로 반환하는 이유는 무엇인가요?

2023-07-14 10:46 UTC, seung-hun-h commented on src/main/resources/application.yaml
DB 스키마가 없어서 실행이 안되는데 확인해주세요

2023-07-14 10:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/execute/Execution.java
> +}
추상화 하신 이유가 있을까요?

2023-07-14 10:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/repository/customer/JdbcCustomerRepository.java
> +  }
데이터가 없을 때 예외를 던지는 이유가 있나요?

2023-07-14 10:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/service/CustomerService.java
> +  }
email을 반환하는 이유가 무엇인가요?

2023-07-14 10:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/service/CustomerService.java
> +  }
```suggestion
  public CustomerResponseDto findById(UUID customerId) {
    Customer customer = customerRepository.findById(customerId);
    return customerMapper.mapToResponse(customer);
  }
```

2023-07-14 10:46 UTC, seung-hun-h commented on src/main/java/com/prgrms/commandLineApplication/voucher/discount/DiscountType.java
>    }
`DiscountType` 인스턴스에서 바로 unit을 꺼낼 수 있을 것 같은데요. 이 메서드가 필요한지 의문이드네요

2023-07-14 16:03 UTC, dojinyou commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +    Assertions.assertThat(jdbcCustomerRepository.findAll().size()).isEqualTo(EMPTY);
[nit] 이게 더 좋은 것 같아요
```suggestion
    Assertions.assertThat(jdbcCustomerRepository.findAll()).isEmpty();
```

2023-07-15 05:35 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/controller/VoucherController.java
>  public class VoucherController {
Customer가 추가되면서 VoucherController라는 이름으로는 어울리지 않는 것 같습니다 ! 
적절한 이름으로 수정하겠습니다 !!

2023-07-15 05:45 UTC, merged

2023-07-15 06:05 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/service/CustomerService.java
> +  }
update가 성공적으로 되었다면 해당 email의 이름이 잘 변경되었다고 알려주기 위해 확인차 email을 반환해주는 의도로 하였지만, 이렇게 하려면 그냥 입력받은 email을 보여주면 되었습니다..😅 수정하였습니다 !

2023-07-15 06:13 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/execute/Execution.java
> +}
Customer와 Voucher의 아이디로 조회, 삭제 등을 콘솔에 추가할 때 편하게 하기 위해 인터페이스로 작성하였습니다 !

2023-07-15 07:05 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/customer/JdbcCustomerRepository.java
> +  private static final String UPDATE_NAME_QUERY = "UPDATE customers SET customer_name = :customerName WHERE email = :email ";
사용자 입장에서 계정의 이름을 변경할 때 랜덤으로 출력되는 아이디 보다는 각자의 이메일을 검색해서 변경하는 것이 더 편리할 것 같다고 생각되어 email로 조건을 두었습니다 !

2023-07-15 07:10 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +    System.out.println("customers.size() -> " + customers.size());
여러 번 검토 했는데 이 부분을 확인하지 못했습니다🥲 주의하겠습니다 !!

2023-07-15 07:32 UTC, 1o18z commented on src/test/java/com/prgrms/commandLineApplication/repository/JdbcCustomerRepositoryTest.java
> +    jdbcCustomerRepository.save(customer2);
안 그래도 저 부분을 어떻게 깔끔하게 할 수 있을까 고민하고 있었습니다🤩 
for문으로 만들면 훨씬 깔끔해질 것 같습니다! 반영하여 수정하겠습니다 !!

2023-07-15 23:39 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/execute/Execution.java
> +}
Console과 Execution의 역할을 분리하려다 보니 추상화 한 의미가 없어져서 Execution 인터페이스를 없애는 쪽으로 수정하였습니다 !🌱

2023-07-16 00:56 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/execute/CustomerExecution.java
> +  private final Console console;
Execution은 실행만을 담당하는 클래스인데 출력까지 함께 있는 건 적절하지 않은 것 같습니다 !
적절히 분리하여 수정하겠습니다 ! 🚀

2023-07-16 01:25 UTC, 1o18z commented on src/main/java/com/prgrms/commandLineApplication/repository/customer/CustomerRepository.java
> +  String update(String email, String customerName);
현재 상태에서 변경이 일어나게 되면 연관된 모든 부분이 수정이 일어날 것 같습니다 
DTO를 만들어 받도록 변경하고, void를 반환하도록 변경하였습니다 !