[4기 - 김민희] SpringBoot Part2 Weekly Mission PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #806
Opened 2023-07-11 20:45 UTC by KimMinheee

## 📌 과제 설명 
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - [x] 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - [x] 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - [x] Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - [x] customers 테이블 정의 및 추가
    - [x] CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - [x] 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - [x] 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - [x] 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

## 👩‍💻 요구 사항과 구현 내용 
- 이전 1주차 pr에서 받았던 피드백을 수정하여 머지한 이후에 2주차 기능을 구현했습니다. 

**< 1주차 피드백 이후 수정된 주요 기능 >**
- VoucherFactory 이용하여 Voucher 객체 생성 처리
- PercentVoucher 유효성 검사 위치 수정(console -> PercentVoucher)
- Enum 클래스 내 is~() 비교메소드 삭제 -> switch문으로 변경 등

**< 2주차 구현 내용 >**
- Jdbc 이용하여 Member CRUD 구현 기능 추가
- Jdbc 이용하여 Voucher(Fixed, Percent) CRUD 구현 기능 추가
- Console 내 기능이 늘어나면서 메뉴이름을 입력(insertMember)하는 방식에서 번호(1)를 입력하는 방식으로 변경
- 테스트 코드 작성

## ✅ PR 포인트 & 궁금한 점 

지난 pr과 달리 이번 Service 테스트코드에서 Mock을 이용하여 테스트코드를 작성해보았는데 적절히 작성되었는지 확인 부탁드립니다.
또한 생성 등 void로 결과값이 따로 반환되지 않는 Service의 메소드는 테스트코드는 어떤 방식으로 작성하는 것이 적절할지도 궁금합니다!

Wallet 기능 구현은 빠른 시일내에 마무리하여 2차 PR 올리도록 하겠습니다!

---

2023-07-12 13:15 UTC, devYSK requested changes

2023-07-12 13:15 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/voucher/infrastructure/JdbcVoucherRepository.java
> +
이 두칸의 개행은 의미있는 개행인가요!

2023-07-12 13:15 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/voucher/infrastructure/VoucherRepository.java
> +
javadoc 주석 이란것도 있어요~

2023-07-12 13:15 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/voucher/presentation/VoucherController.java
> +
Javadoc

2023-07-12 13:15 UTC, devYSK commented on src/main/resources/schema.sql
> +drop table if exists member_table;
디렉토리를 구분해서 정리해보면 어떨까요?

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/io/MenuTypeTest.java
> +    @DisplayName("입력값에 따라 MenuType을 반환하는 테스트 - 성공")
입력값에 따라 MenuType을 반환한다.

`@EnumSource`, `@CsvSourec`에 대해 알아보면 좋아요

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/application/MemberServiceTest.java
> +    @DisplayName("회원 정보(status)를 수정할 수 있다. - 성공")
회원 정보를 BLACK으로 수정한다
일반 회원을 블랙리스트 회원으로 수정한다

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/application/MemberServiceTest.java
> +                .stream()
stream()은 생략할 수 있을것 같아요

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/application/MemberServiceTest.java
> +    }
검증부 순서를 정리하여 가독성을 높여보면 어떨까요?

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/domain/MemberStatusTest.java
> +    void from_InputStatus_ThrowIllegalArgumentException() {
잘못된 입력값을 입력하면 생성할수 없다.

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/infrastructure/JdbcMemberRepositoryTest.java
> +
불필요한 코드같아요

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/infrastructure/JdbcMemberRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
이 어노테이션을 사용하면 어떤 일이 일어나나요?

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/infrastructure/JdbcMemberRepositoryTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
Order가 꼭 필요한 테스트 였나요?

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/voucher/application/VoucherServiceTest.java
> +        given(voucherRepository.findById(voucherId)).willReturn(Optional.ofNullable(saveVoucher));
Passing a non-null argument to 'Optional' 

이 무슨 뜻일까요?

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/voucher/domain/DiscountTypeTest.java
> +        assertThatThrownBy(() -> DiscountType.from(input))
여긴 given / when / then이 없네요. 다른 이유가 없다면 통일성을 맞춰주세요

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/voucher/domain/DiscountValueTest.java
> +}
실패하는 경우는 없을까요?

2023-07-12 13:15 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/voucher/infrastructure/JdbcVoucherRepositoryTest.java
> +
필요한 개행인가요?

2023-07-12 13:20 UTC, devYSK commented
안녕하세요 민희님 2주차 과제하시느냐 고생많으셨습니다.
고민 많이하시고 객체 적당하게 잘나눴지만 아직도 아쉬운 부분이 남아있어요!
리뷰에 남겨놨으니 한번 고민해보시길 바랍니다.


Service 테스트코드에서 Mock을 이용하여 테스트코드를 작성해보았는데 적절히 작성되었는지 확인 부탁드립니다.
* 적절히 잘 사용하신거 같습니다. 
* Mocking 후 verify로 호출 여부를 검증 할수도 있습니다. verify에 대해 알아보세요 
* 하지만 항상 주의하셔야 하는것이, MockTest가 Product Code의 Runtime에서의 정확한 행동을 보장하지 않는단걸 꼭 유의하셔야 합니다
* Mockist, Classist에 대해서도 알아보시고, 어떤 상황에 Mock을 사용해야 할까?도 고민해보세요 


또한 생성 등 void로 결과값이 따로 반환되지 않는 Service의 메소드는 테스트코드는 어떤 방식으로 작성하는 것이 적절할지도 궁금합니다!
* 생성이라면 DB를 조회해서 제대로 저장되었는지 검증하면 될것 같아요
* 다른 void 메소드도 내부적으로 행동한거에 대해 찾아 검증하면 될것 같아요

2023-07-13 09:03 UTC, WooSungHwan requested changes
민희님 과제하시느라 고생하셨습니다 ㅎㅎ
아직까진 쿼리나 erd가 매우 단순해서 쉽게쉽게 넘어가신것 같아요~
wallet이 구현되지 않으면 언급할 부분이 많이 없기 때문에 기능이 완성되면 그때 좀더 이야기해보도록 하겠습니다~ 수고하셨습니다!

2023-07-13 09:03 UTC, WooSungHwan commented on src/main/java/org/programmers/VoucherManagement/voucher/infrastructure/JdbcVoucherRepository.java
> +        String sql = "select * from voucher_table";
all(*) 날리는 것보다는 필요한 컬럼 추가해서 조회하도록 해요~

2023-07-15 07:26 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/io/ConsoleMessage.java
> +            "<< 2 >> [updateMember] - 멤버를 수정하려면 2를 입력하세요.\n" +
다른 OS 환경에서 동일하게 개행이 동작할 수 있도록 System.lineSeparator() 사용하는 것으로 수정하도록 하겠습니다

2023-07-15 08:53 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/VoucherManagementRunner.java
현재는 EXIT(10)을 입력받으면 commandExecutor의 execute 함수에서 프로그램을 종료한다는 메시지를 출력하고 있습니다!

2023-07-15 09:10 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/io/MenuType.java
> +    EXIT("exit", 10);
이전 코드에서 콘솔 입력시 사용하던 type이라 현재는 사용하지 않고 있어 정리하도록 하겠습니다!

2023-07-15 09:25 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/member/application/MemberService.java
>  @RequiredArgsConstructor
롬복을 사용한다면 개발자의 의도에서 벗어나게 기능이 작동할 수 있을 것 같습니다. @RequiredArgsConstructor의 경우 자동적으로 생성자가 만들어지기 때문에 꼭 필요한 것이 아니라면 지양해야할 것 같습니다! 이 부분은 롬복을 사용하지 않는 방식으로 수정할 예정입니다!😊

2023-07-15 14:42 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/member/domain/Member.java
> +@EqualsAndHashCode
mutable한 객체에 파라미터로 지정없이 사용한다면 동일한 객체임에도 필드값이 변경되면 hashCode가 변경되면서 정상적으로 비교할 수 없을 것 같습니다! 변경 가능한 객체는 해당 롬복사용을 지양하도록 수정하겠습니다.

2023-07-15 15:22 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/member/dto/UpdateMemberRequest.java
> +public class UpdateMemberRequest {
현재 패키지구조가 도메인별로 나뉘어져 있어 해당 Dto 패키지는 Member만 사용하기에 각각 Create,Get,Update 등으로 시작하는 것이 더 직관적이라 생각했고 추후 api로 바뀔때를 고려하여 위와 같이 작성했습니다!  
record는 공부하면서 적용해보도록 하겠습니다!😊

2023-07-15 15:35 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/member/infrastructure/FileMemberRepository.java
>      private FileMemberRepository(@Value("${app.path.file}") String filePath) {
@Valid로 주입받는 변수를 다른 곳에서 사용할 경우 매번 똑같은 방식으로 yml에 접근하여 값을 얻어오게 됩니다.
ConfigurationProperties를 이용하여 클래스로 바인딩하여 재사용할 수 있도록 코드 수정하겠습니다!

2023-07-17 07:28 UTC, KimMinheee commented
## 📌 과제 설명 <!-- 어떤 걸 만들었는지 대략적으로 설명해주세요 -->
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - [x] 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - [x] 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - [x] Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - [x] customers 테이블 정의 및 추가
    - [x] CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - [x] 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - [x] 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - [x] 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
- [x] (심화)** **바우처 지갑을 만들어보세요.**
    - [x] 특정 고객에게 바우처를 할당할 수 있습니다.
    - [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
    - [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
    - [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 <!-- 기능을 Commit 별로 잘개 쪼개고, Commit 별로 설명해주세요 -->
- wallet 기능을 구현 후 피드백 내용을 반영하여 수정하였습니다. 

**< 2주차 과제 1차 피드백 이후 수정된 주요 기능 >**
-  wallet 기능 구현 및 테스트코드 작성
- 개행 문자 수정
- JdbcRepository 빈 주입 방식 수정
- @RequiredArgsConstructor 어노테이션 삭제 및 생성자 주입으로 수정
- @Value -> @ConfigurationProperties로 클래스 내에서 값 관리하도록 수정
- deleteAll 메소드 삭제
- Repository 테스트 코드 Order 사용하지 않는 방식으로 수정
- 블랙리스트 회원 조회시 memberStatus를 인자로 받아 Status 값을 기준으로 조회하도록 코드를 수정(white 조회시 쓸 수 있도록)

## ✅ PR 포인트 & 궁금한 점 <!-- 리뷰어 분들이 집중적으로 보셨으면 하는 내용을 적어주세요 -->
- Wallet 기능을 구현 했습니다! 
- 다만 저는 Wallet객체 내부에 Voucher객체,Member객체를 가지고 있는 방식으로 구현하여 walletRepository의 Mapper함수에서 각각 voucherRepository, memberRepository에서 find 하여 매핑해주고 있는데 이 방식이 적절할지 고민입니다. 
- 별도의 Mapper 클래스를 따로 둔다면 해당 클래스에서도 동일하게 memberRepository, voucherRepository를 주입받고 사용해야하는데 Mapper 클래스에서 repository를 주입받는게 적절한지 의문이 들어 현재는 walletRepository에서 mapping 하도록 처리했습니다. 
이 부분에 대한 조언을 듣고 싶습니다!

---

2023-07-17 08:25 UTC, devYSK approved these changes

2023-07-17 08:25 UTC, devYSK commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.24.2'
assertj는 
org.springframework.boot:spring-boot-starter-test'에 포함되어 있습니다.
p2;

2023-07-17 08:25 UTC, devYSK commented on build.gradle
> +
이 의존성들도 추가로 선언할 필요가 없어보입니다.
p2;

2023-07-17 08:25 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/VoucherManagementRunner.java
> +@Profile("!test")
왜 !test Profile인가요?
p2;

2023-07-17 08:25 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/VoucherManagementRunner.java
> +            } catch (VoucherException | IllegalArgumentException | MemberException e) {
Voucher, IllegalArgument, Member 이외의 예외가 발생하면 프로그램이 어떻게 될까요?
p2;

2023-07-17 08:25 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/global/file/FileInfo.java
> +}
setter를 사용해야만 할까요!? 다른 방법은 없을까요? 
p2;

2023-07-17 08:25 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/wallet/dto/GetWalletListResponse.java
> +    public List<GetWalletResponse> getGetWalletListRes() {
네이밍이 어색해요~! 
혹시 이부분만 안바꾼걸까요?

2023-07-17 08:25 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/wallet/dto/GetWalletResponse.java
> +}
Wallet을 join을 안하고 가져온다면 어떻게 될까요?
p2;

2023-07-17 08:25 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/member/application/MemberServiceTest.java
> +
application-test.yml에 디비 정보가 있는데 
현재 테스트 코드에서 mock을 쓸 만큼 복잡하거나 어려운거 같진 않아요 .
* 모든 서비스 로직을 Mock을 쓰고 결과를 스스로 조작한다면 정말 정확한 테스트일까?
* 언제 Mock을 써야 할까? 

p2;

2023-07-17 08:25 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/voucher/infrastructure/JdbcVoucherRepositoryTest.java
> +
개행

2023-07-17 08:25 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/wallet/application/WalletServiceTest.java
> +public class WalletServiceTest {
중복되는 코드들을 다 제거할 수 있을것 같습니다.
p2;

2023-07-17 08:25 UTC, devYSK commented on src/test/java/org/programmers/VoucherManagement/wallet/infrastructure/JdbcWalletRepositoryTest.java
> +
?!

2023-07-17 08:36 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/VoucherManagementRunner.java
> +@Profile("!test")
@SpringBootTest시 VoucherManagementRunner 클래스의 run 메소드가 실행되면서 console 관련 코드가 실행되는 것을 막기 위해 VoucherManagementRunner에 위와 같이 작성해두었습니다!

2023-07-17 08:38 UTC, devYSK commented on src/main/java/org/programmers/VoucherManagement/VoucherManagementRunner.java
> +@Profile("!test")
@KimMinheee 
그렇다면, 애플리케이션 실행프로파일 환경과 테스트 프로파일 환경을 나눠보는것은 어떨까요?

2023-07-19 06:02 UTC, KimMinheee commented
## 📌 2주차 과제 3차 PR 설명 <!-- 어떤 걸 만들었는지 대략적으로 설명해주세요 -->
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - [x] 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - [x] 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - [x] Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - [x] customers 테이블 정의 및 추가
    - [x] CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - [x] 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - [x] 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - [x] 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
- [x] (심화)** **바우처 지갑을 만들어보세요.**
    - [x] 특정 고객에게 바우처를 할당할 수 있습니다.
    - [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
    - [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
    - [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 <!-- 기능을 Commit 별로 잘개 쪼개고, Commit 별로 설명해주세요 -->
- wallet 기능을 구현 후 피드백 내용을 반영하여 수정하였습니다. 

**< 2주차 과제 1차 피드백 이후 수정된 주요 기능 >**
-  wallet 기능 구현 및 테스트코드 작성
- 개행 문자 수정
- JdbcRepository 빈 주입 방식 수정
- @RequiredArgsConstructor 어노테이션 삭제 및 생성자 주입으로 수정
- @Value -> @ConfigurationProperties로 클래스 내에서 값 관리하도록 수정
- deleteAll 메소드 삭제
- Repository 테스트 코드 Order 사용하지 않는 방식으로 수정
- 블랙리스트 회원 조회시 memberStatus를 인자로 받아 Status 값을 기준으로 조회하도록 코드를 수정(white 조회시 쓸 수 있도록)

**< 2주차 과제 2차 피드백 이후 수정된 주요 기능 >**
- dto 네이밍 변경 
- MemberService, VoucherService 통합 테스트코드 작성
- repository(member, voucher, wallet) reader와 store로 분리해서 구현
- 테스트코드 작성

## ✅ PR 포인트 & 궁금한 점 <!-- 리뷰어 분들이 집중적으로 보셨으면 하는 내용을 적어주세요 -->
- Wallet 기능을 구현 했습니다! 
- 다만 저는 Wallet객체 내부에 Voucher객체,Member객체를 가지고 있는 방식으로 구현하여 walletRepository의 Mapper함수에서 각각 voucherRepository, memberRepository에서 find 하여 매핑해주고 있는데 이 방식이 적절할지 고민입니다. 
- 별도의 Mapper 클래스를 따로 둔다면 해당 클래스에서도 동일하게 memberRepository, voucherRepository를 주입받고 사용해야하는데 Mapper 클래스에서 repository를 주입받는게 적절한지 의문이 들어 현재는 walletRepository에서 mapping 하도록 처리했습니다. 
이 부분에 대한 조언을 듣고 싶습니다!

---

2023-07-20 06:10 UTC, WooSungHwan approved these changes
민희님 과제하시느라 수고 많으셨습니다!
read랑 store 나누시는거 깔끔하게 나눠진 것 같습니다 ㅎㅎ 인터페이스도 상당히 보기좋게 구성해있기도 하고요!

2023-07-20 06:10 UTC, WooSungHwan commented on src/main/java/org/programmers/VoucherManagement/wallet/domain/Wallet.java
> +    private Member member;
이거 근데 ㅎㅎ voucher는 List인게 맞지 않아요?ㅎㅎ
erd나 테이블 레코드 기준으로 클래스가 고려된 것 같군요 ㅎㅎ

2023-07-20 06:10 UTC, WooSungHwan commented on src/main/java/org/programmers/VoucherManagement/voucher/application/VoucherService.java
>  public class VoucherService {
그러고보니 얘는 `@Service`  안붙였네요?! `@Component`로만 보기엔 좀 아쉬운걸유ㅎㅎ 중요한 비즈니스로직을 담는 service를 뜻하는거 아니었나요?ㅎㅎ

2023-07-20 06:10 UTC, WooSungHwan commented on src/main/java/org/programmers/VoucherManagement/wallet/infrastructure/WalletStoreRepository.java
> +     */
이런 주석 너무 좋아요..

2023-07-20 06:10 UTC, WooSungHwan commented on src/main/java/org/programmers/VoucherManagement/wallet/presentation/WalletController.java
> +    }
제가 지난번에 팀미팅에 이야기했던 부분이 이런 부분이에요 ㅎㅎ
walletCreateRequest는 컨트롤러에서 받는 객체인데 서비스까지 침투해버리니 layer라는 개념이 많이 무색해져 버리게 됩니다. 
너무 이론성이 짙은 개념이긴 한데 짚어드리는게 좋을 것 같아서 코멘트 답니다.

2023-07-20 09:32 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/wallet/dto/GetWalletListResponse.java
> +    public List<GetWalletResponse> getGetWalletListRes() {
동사가 맨 앞에 오는게 어색한 것 같아 말씀해주신 부분 수정해서 3차 pr 올려두었습니다!😁

2023-07-20 09:35 UTC, KimMinheee commented on src/main/java/org/programmers/VoucherManagement/VoucherManagementRunner.java
> +@Profile("!test")
코멘트를 늦게 확인해 2주차 3차 pr에는 반영하지 못했습니다🥲 
개별 클래스마다 어노테이션을 붙이지 않고 별도의 클래스(Configuration)를 두고 그 클래스에서 제외하거나 포함할 수 있도록 컨트롤하는 것으로 이해했습니다! 
이 부분은 다음 pr올릴 때 반영하도록 하겠습니다 감사합니다!

2023-07-25 15:51 UTC, merged