[4기 - 박세영] SpringBoot Part2 Weekly Mission PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #814
Opened 2023-07-12 11:18 UTC by SY97P

# SpringBoot Basic Weekly Mission

## 📌 과제 설명 

### 흐름도
![img](https://github.com/prgrms-be-devcourse/springboot-basic/assets/54990890/60071d90-332a-43b6-8658-e70bc8d18946)

### 클래스 다이어그램
![img_1](https://github.com/prgrms-be-devcourse/springboot-basic/assets/54990890/0f317431-fd8b-4f83-87c5-7d453b92008d)

## ✅ PR 포인트 & 궁금한 점 
- 바우처 지갑 기능을 넣으려고 했는데, 기능 수정이 어려웠습니다.
  - 책임 분리가 덜 되어서 그런건지 확인 부탁드립니다.

## 👩‍💻 요구 사항과 구현 내용 
- [x] 테스트
- [x] Customer
  - [x] 테이블 정의
  - [x] jdbcTemplate
  - [x] crud
- [x] Voucher
  - [x] 테이블 정의
  - [x] jdbcTemplate
  - [x] crud

## ✅ 피드백 반영사항

2023-07-12 16:51 UTC, devYSK requested changes
안녕하세요 세영님 어려운 2주차 과제 하시느냐 고생 많으셨습니다.

전반적으로 문제가 될 수 있는 공통적인 부분이 많은거 같아요. 
공부하시고 세영님의 생각을 남겨주시면 좋을거같아요. 
또한 가독성을 위해 메소드를 사용하거나, 공백을 적절히 사용하는것이 좋을거 같아요. 
팀원이 내 코드를 사용하고, 내가 남의 코드를 봤을때 서로 이해 잘되도록 !  
전체적인 애플리케이션 코드의 통일성도 맞춰주시면 더욱 더 좋을것 같습니다. 

객체들의 책임분리는 적절해 보입니다. 다만 CustomerRepository의 책임은 두가지가 있는것 같아요.
바우처, 사용자, 지갑 이 셋의 관계를 데이터베이스 설계 영역에서  잘 생각해보셔서 구현해보시면 좋을거같습니다.

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/customer/model/Customer.java
> +            throw new InvalidDataException(ErrorMessage.INVALID_PROPERTY.getMessageText());
NPE가 발생할수도 있을거 같아요

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/customer/controller/CustomerDto.java
> +
정적 팩토리 메소드의 단점은 무엇이 있을까요? 

dto에서 추가적인 로직이 필요하다면 어떻게 될까요?

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/customer/repository/CustomerRepository.java
> +
jdbc랑 file이랑 왜 같이 사용하셨는지 이유가 궁금합니다.

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/customer/repository/CustomerRepository.java
> +
어느날, 영속성 관련 프레임워크를 바꿔야 하는 일이 생겼어요.

Repository 계층을 추상화 안하면 어떤 일이 일어날 수 있을까요?

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/customer/repository/CustomerRepository.java
> +
개행이 2번 들어갈 필요는 없다고 생각합니다

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/customer/repository/CustomerRepository.java
> +
어느날 파일 관련 문제가 생겨 파일 관련 로직을 모두 걷어내야 하는 일이 생겼어요. 
이때 다 지워버리면 영향이 많이 갈거 같아요

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/global/model/DomainMenu.java
> +                .orElseThrow(() -> new InvalidDataException(ErrorMessage.INVALID_MENU.getMessageText()));
보통 이렇게 expression이 긴 경우 메소드로 빼는 편입니다. 가독성이 너무 떨어져요

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/global/model/PropertyMenu.java
> +                .findAny()
여기도요

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/global/utils/Utils.java
> +
생성을 아무데서나 할 수 있겠네요. 막아보는건 어떨까요?

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/global/utils/Utils.java
> +        var byteBuffer = ByteBuffer.wrap(bytes);
var가 무엇이죠?

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/voucher/model/DiscountValue.java
> +        }
꼭 static 이여야 하나요? 실패하는 일은 없을까요?

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/voucher/model/Voucher.java
> +            case PERCENT_DISCOUNT -> originalPrice - (1 - discountValue.value() / 100);
연산하는 로직을 Voucher가 모르게 할 순 없을까요?
DiscountVAlue의 책임이진 않을까요?

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/voucher/model/VoucherType.java
> +                .findAny()
여기도 메소드로 빼면 가독성이 좋을거 같아요

2023-07-12 16:51 UTC, devYSK commented on src/main/java/com/devcourse/springbootbasic/application/voucher/repository/JdbcVoucherRepository.java
> +        return new Voucher(voucherId, voucherType, discountValue, customerId);
저는 무슨 타입인지 잘 모르겠어요.

var는 어떤 장단점이 있을까요?

2023-07-12 16:51 UTC, devYSK commented on src/main/resources/application.yaml
> +  description: "어려워잌ㅋ"
?ㅋㅋ

2023-07-12 16:51 UTC, devYSK commented on src/main/resources/application.yaml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
민감정보를 감출수 있는 방법에 대해서도 고민해보아요

2023-07-12 16:51 UTC, devYSK commented on src/test/java/com/devcourse/springbootbasic/application/customer/controller/CustomerControllerTest.java
> +
준비 - 실행 - 검증 으로 과정을 나눠볼까요?

2023-07-12 16:51 UTC, devYSK commented on src/test/java/com/devcourse/springbootbasic/application/customer/controller/CustomerControllerTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
PER_CLASS는 어떤 상태일까요?
장단점은 무엇이 있을까요?
FIRST에 대해 알아보세요

2023-07-12 16:51 UTC, devYSK commented on src/test/java/com/devcourse/springbootbasic/application/customer/controller/CustomerControllerTest.java
> +@SpringBootTest
`@JdbcTest` 라는 어노테이션이 존재합니다

2023-07-13 06:14 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/customer/controller/CustomerDto.java
> +
만약 dto 의 정적 팩토리 메소드 안에서 사용하는 함수의 경우 static 키워가 필요합니다. 
정적 함수에서 사용하는 함수니까요.

정적 팩토리 메소드의 단점은 상속을 통한 기능확장이 불가능하다는 것입니다.
하지만 제 코드에서 CustomerDto, VoucherDto 는 상속이 필요없습니다. 

해당 클래스의 역할은 오로지 사용자 입력을 Dto 객체로 생성하고, Domain으로 매핑하는 역할만 수행하므로
정적 팩토리 메소드의 장점인 객체관리의 이점을 갖습니다. 

가독성 면에서도 매번 new 키워드로 객체를 생성하는 것이 아니라, 간단한 이름의 메소드로 객체 생성이 가능합니다.

또한, 구현부분이 존재하지 않으므로 사용자 입장에서는 정적팩토리 메소드만 활용하면 됩니다. 

정적 팩토리 메소드 특성을 고려했을때 사용하는 것이 더 낫다고 판단해서 사용했습니다.

2023-07-13 06:20 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/customer/model/Customer.java
> +            throw new InvalidDataException(ErrorMessage.INVALID_PROPERTY.getMessageText());
null 값을 체크하도록 수정했습니다.

2023-07-13 06:24 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/voucher/model/DiscountValue.java
> +        }
static으로 선언한 메소드에서 인스턴스 메소드를 호출하려고 하는 경우 실패가 발생합니다.

하지만, DiscountValue 클래스는 이것 이상으로 기능이 추가되지는 않을 것 같아, static 사용의 단점이 크게 부각되지 않는 것 같습니다. 

혹시 static 메소드를 최대한 줄이는 방향으로 수정하는 게 좋을까요?

2023-07-13 06:26 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/voucher/model/Voucher.java
> +            case PERCENT_DISCOUNT -> originalPrice - (1 - discountValue.value() / 100);
도메인에 로직이 있어야 한다는 말을 들어서 Voucher 내에서 로직을 구현했습니다.

사실 구현하면서 유효성 판단도 필요하고, 연산자체도 같이 하는게 맞는가라는 생각을 했습니다.

DiscountValue 클래스는 바우처의 할인값에 대한 원시값 포장이므로, 

계산 결과를 나타내는 Price 원시값 포장 클래스를 따로 만들어 관리하겠습니다.

2023-07-13 07:22 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/voucher/model/DiscountValue.java
> +        }
Price 클래스 추가하면서 왜 static을 지양하는지 체감했습니다.

단순히 상속 확장이 불가능한 것 이외에도 불편한 점이 꽤 있었네요.

static 메소드 모두 제거했습니다.

2023-07-13 07:31 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/voucher/model/VoucherType.java
> +                .findAny()
따로 뺐습니다.

펀-안 해졌습니다.

2023-07-13 07:37 UTC, SY97P commented on src/main/resources/application.yaml
> +  description: "어려워잌ㅋ"
이스터에그입니다.

솔직히 보실 줄 몰랐습니다...ㅎ

2023-07-13 07:38 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/customer/controller/CustomerControllerTest.java
> +
좀 더 신경써서 작성하겠습니다.

2023-07-13 07:39 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/customer/repository/CustomerRepository.java
> +
구현체로만 존재하는 레포지토리 클래스를 모두 수정해야 할 것 같습니다.

만약에 추상화를 통해 구현한다면, 

프로파일로 사용환경을 나눠서 영속성을 적용할 수 있을 것 같습니다.

2023-07-13 07:53 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/customer/repository/CustomerRepository.java
> +
customer 도메인에 관련해서 하나의 레포지토리로 관리하려는 의도였습니다. 

근데 지금은 customer 테이블이 있는데도 따로 파일로 관리하는게 이상하다고 생각합니다.

table에 블랙고객인지 나타내는 컬럼을 추가해서 crud 되도록 해보겠습니다.

2023-07-13 08:26 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/global/utils/Utils.java
> +
생성자를 private 로 막으라는 말씀으로 이해했는데 맞을까요?

2023-07-13 08:28 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/global/utils/Utils.java
> +        var byteBuffer = ByteBuffer.wrap(bytes);
var 지양할 구간

1. 테스트코드
2. 프론트엔드가 볼 수 있는 컨트롤러
3. 핵심 비즈니스 로직
4. 여러 군데에서 활용하는 Util 클래스

2023-07-13 09:04 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/customer/controller/CustomerControllerTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Isolated 속성 위반이네요.

어쩐지 단위테스트 시간이 너무 오래걸린다 싶었는데,

전체적으로 테스트코드 작성하는 방법에 대해서 재고해봐야겠습니다.

2023-07-13 09:21 UTC, WooSungHwan requested changes
영수님이 이전에 나왔던 이야기들을 많이 짚어주셔서.. 제가 할 수 있는 부분은 쿼리나 erd 부분을 짚어드리려고 했는데 우선 wallet이 정의가 안되어 드릴 수 있는 피드백이 없습니다. 저 정도 규모의 테이블은 사실 피드백을 전달하기도 애매해서 wallet이 정의가 되어야 이야기를 나눌수 있는 전제가 될것 같아요.
고생하셨습니다. 지갑 기능 구현하고 만나요~

2023-07-13 09:21 UTC, WooSungHwan commented on src/test/resources/test-schema.sql
> +    customer_id    binary(16)  not null
fk를 제거한 이유가 뭔가요?

2023-07-13 09:21 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/voucher/repository/JdbcVoucherRepository.java
> +        }
스프링이 굳이 추상화해서 던져주는건 확인한것 같은데 이 layer에서 또 처리하는건 이유가 뭔가요?? ㅎㅎ

2023-07-13 09:21 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/voucher/repository/JdbcVoucherRepository.java
> +                            "SELECT * FROM vouchers WHERE voucher_id = UUID_TO_BIN(:voucherId)",
all(*) 키워드보다는 직접 필요한 컬럼을 기재해주는게 좋습니다. 어떤 컬럼이 늘어날지 확실하지 않은 상황에서 all로 조회하지는 않아요.

2023-07-13 09:21 UTC, WooSungHwan commented on src/main/java/com/devcourse/springbootbasic/application/voucher/repository/JdbcVoucherRepository.java
> +        }
queryForObject가 에러를 내뱉는군요... 왜저리 동작하지.. 이건 좀 예외인 것 같네용.

2023-07-14 09:27 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/voucher/repository/JdbcVoucherRepository.java
> +        }
sql 문에 해당하는 결과가 없는 경우에 EmptyREsultDataAccessException이 발생한다고 합니다.

queryForObject 결과가 null인 경우 처리를 위해서 Optional을 사용하도록 했는데 추가적인 조치가 필요하다는 말일까요?

2023-07-14 09:30 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/voucher/repository/JdbcVoucherRepository.java
> +                            "SELECT * FROM vouchers WHERE voucher_id = UUID_TO_BIN(:voucherId)",
팀원들이랑 피드백 공유하면서 공통적으로 받은 피드백이네요.

앞으로 저희 팀 컨벤션으로 정해서 사용해야겠네요

2023-07-14 09:37 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/voucher/repository/JdbcVoucherRepository.java
> +        }
DataAccessException을 InvalidDataException으로 다시 던지게 한 이유를 물으시는거면,

테스트 편의를 위해서였습니다.

코드에서 발생하는 대부분의 예외상황에 대해서 커스텀 예외로 잡을 수 있다면, 
코드 내 문제에 대해서 파악한 척도가 될거라 생각해 이렇게 구현했습니다.

2023-07-14 11:33 UTC, SY97P commented on src/main/resources/application.yaml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
jasypt 이용해서 감췄습니다.

2023-07-14 12:01 UTC, SY97P commented on src/main/java/com/devcourse/springbootbasic/application/global/utils/Utils.java
> +
우연찮게 책을 읽으면서 얻게 된 지식인데, 

util 같은 범용 클래스의 경우에는 정적 메소드 위주로 구성되기 때문에 

객체를 생성할 필요가 없는 경우가 많더라구요.

제가 사용하는 Dto 클래스와 역할은 다르지만, 생성자를 아무데나 사용하면 안 될 것 같아서 함께 처리했습니다.

2023-07-14 12:05 UTC, SY97P commented on src/test/java/com/devcourse/springbootbasic/application/customer/controller/CustomerControllerTest.java
> +@SpringBootTest
확실히 통합테스트로 하는 것보다 엄청 빠르더라구요

덕분에 FIRST 속성을 만족한 것 같아 기분 좋습니다.

2023-07-16 16:19 UTC, devYSK approved these changes

2023-07-16 16:19 UTC, devYSK commented on src/main/java/com/tangerine/voucher_system/application/global/config/JasyptConfiguration.java
> +
ConfigurationProperties 로 관리하는것이 좋아보입니다.
p2;

2023-07-16 16:19 UTC, devYSK commented on src/main/java/com/tangerine/voucher_system/application/voucher/controller/VoucherDto.java
> +
1줄에 1필드만 둬도 될것같은데요!?
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/customer/controller/CustomerControllerTest.java
> +        given(service.findBlackCustomers()).willReturn(blackCustomers);
호출을 검증하기 위해verify() 라는 메소드도 존재합니다
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/customer/controller/CustomerDtoTest.java
> +    @MethodSource("provideValidCustomerDto")
DisplayName을 통일해주세요
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/customer/model/CustomerTest.java
> +
위 Customer에는 예외를 던지는 로직이 있어요.
정상적으로 던지나 확인해볼까요?
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/customer/repository/JdbcCustomerRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
PER_CLASS로 사용해야 할 이유가 있나요?
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/voucher/controller/VoucherDtoTest.java
> +    static List<VoucherDto> voucherDto = List.of(
dto까지 꼼꼼하게 작성하셨네요!

dto를 테스트 하신 의도가 궁금합니다!
dto vs vo vs entity

p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/voucher/model/VoucherTest.java
> +
테스트 코드에 추가적인 로직을 두진 않곤 합니다.
* https://jojoldu.tistory.com/642
p2;

2023-07-16 16:19 UTC, devYSK commented on src/main/java/com/tangerine/voucher_system/application/voucher/model/Voucher.java
> +    private final Optional<UUID> customerId;
필드로 Optional을 두게되면 어떤 단점이 있을까요?

p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/resources/schema.sql
> +create table customers
resources/schema/ 디렉토리 아래에 둬도 될 것 같습니다.
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/voucher/repository/MemoryVoucherRepositoryTest.java
> +    @DisplayName("아이디로 바우처 제거한다.")
이 둘은 `@Order`가 필요한가요!?
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/voucher/repository/VoucherMapTest.java
> +        Assertions.assertThat(voucherMap.getVoucherById(voucher.getVoucherId())).isNull();
여기만 다르네요!
p2;

2023-07-16 16:19 UTC, devYSK commented on src/test/java/com/tangerine/voucher_system/application/wallet/repository/JdbcWalletRepositoryTest.java
> +    @Autowired
`@MethodSource`로 사용되는 값들은 테스트 코드 아래에 둬도 괜찮을것 같아요
p2;

2023-07-17 08:13 UTC, SY97P commented on src/main/java/com/tangerine/voucher_system/application/customer/model/Customer.java
> +    }
String 필드는 굳이 따로 VO를 만들 생각을 안 했는데, 

생각해보니 Name 이라는 VO를 만들면 더 관리하기 쉬울 것 같습니다.

2023-07-17 08:52 UTC, SY97P commented on src/test/java/com/tangerine/voucher_system/application/customer/controller/CustomerControllerTest.java
> +        given(service.findBlackCustomers()).willReturn(blackCustomers);
테스트 대상인 메소드는 반환값이 있어서 verify를 사용하지는 않았습니다. 

void 메소드 테스트를 위해 쓰겠습니다.

2023-07-17 08:54 UTC, SY97P commented on src/test/java/com/tangerine/voucher_system/application/customer/model/CustomerTest.java
> +
customer 클래스에서 수행하던 유효성 검사를 Name 클래스로 책임 이전을 시켰습니다.

이제 customer 클래스 내부에서 발생하는 예외는 없습니다.

2023-07-17 08:55 UTC, SY97P commented on src/test/java/com/tangerine/voucher_system/application/customer/repository/JdbcCustomerRepositoryTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
해당 테스트 클래스를 위해서 datasource를 주입받아야 합니다.

매 테스트 메소드마다 주입받는 것 보다, 클래스 마다 한 번 주입받는게 더 FISRT 속성에 맞다고 생각했습니다.

2023-07-17 08:57 UTC, SY97P commented on src/test/java/com/tangerine/voucher_system/application/voucher/controller/VoucherDtoTest.java
> +    static List<VoucherDto> voucherDto = List.of(
프로그램 특성 상 voucher 관련된 모든 데이터는 voucherDto에서 만들어지고, 변환되도록 작성했습니다. 

따라서 VocherDto 가 제대로 생성, 변환되는지 테스트할 필요가 있다고 판단했습니다.

2023-07-17 08:59 UTC, SY97P commented on src/test/java/com/tangerine/voucher_system/application/voucher/model/VoucherTest.java
> +
오 알겠습니다.
해당 테스트는 테스트 데이터를 구분해서 조건 분기 자체를 없애는 방법으로 수정하겠습니다.

2023-07-17 09:10 UTC, SY97P commented on src/test/resources/schema.sql
> +create table customers
덕분에 yaml로 제가 원하는 내장 디비 설정하는 방법도 알게 되었습니다.

2023-07-17 09:10 UTC, SY97P commented on src/test/java/com/tangerine/voucher_system/application/voucher/repository/MemoryVoucherRepositoryTest.java
> +    @DisplayName("아이디로 바우처 제거한다.")
제거하겠습니다!

2023-07-17 09:12 UTC, SY97P commented on src/test/java/com/tangerine/voucher_system/application/wallet/repository/JdbcWalletRepositoryTest.java
> +    @Autowired
이거 인텔리제이 리포매팅을 사용하면 위로 올라가게 됩니다.

설정을 바꿔야 할까요?

2023-07-17 10:08 UTC, SY97P commented on src/main/java/com/tangerine/voucher_system/application/voucher/model/Voucher.java
> +    private final Optional<UUID> customerId;
아 맞다..

직렬화가 안돼요..

2023-07-18 01:26 UTC, WooSungHwan requested changes
과제하시느라 수고 많으셨습니다! 

전반적으로 voucher에 customer_id가 붙어있다보니까 서로 끈적하게 붙어있고 wallet이란 구체적 객체가 존재하지 않아서 도메인이라는 비즈니스 코드 관점에서 들여다 봤을때,
wallet인데 자꾸 voucher를 조회하게 되니까 wallet에 관한 코드와 voucher에 관한 코드가 서로 구분되지 못하는 것 같습니다. walletRepository이지만 실질적으로는 voucher를 조회하고 있는 부분도 사실 좀 어색하고 어제 말씀드렸다시피 erd설계는 어떻게 요구사항이 변할지 모르기때문에 현재의 요구사항에만 만족해서는 안되고 항상 예상치못한 요구사항을 모두 충족할 수 있어야만 합니다.

그때가되서 wallet 테이블을 만들고 마이그레이션 하면 되기야 되겠지만 애초에 테이블이 정의되어 있고 코드만 살짝 바꾸는 정도와는 비교가 안될거에요. 이 부분은 wallet에 대한 구체적 정의를 동반하여 반드시 수정해보시면 좋을 것 같습니다.

2023-07-18 01:26 UTC, WooSungHwan commented on src/main/java/com/tangerine/voucher_system/application/voucher/service/VoucherService.java
> +    }
저는 이런 안쓰는 코드 있으면 지워버립니다. 테스트에서 필요하다면 테스트 영역이 올라갈떄 테스트빈으로 삭제하는 기능을 가진 객체를 정의해서 주입해다 쓰시면 됩니다.

2023-07-18 08:30 UTC, SY97P commented on src/main/java/com/tangerine/voucher_system/application/voucher/service/VoucherService.java
> +    }
테스트 클래스의 LifeCycle을 PER_METHOD 기본값으로 변경하면서 해당 코드가 필요없어졌습니다.

제거하여 수정했습니다.

2023-07-20 14:03 UTC, WooSungHwan approved these changes
ㅎㅎ 수고 많으셨습니다. 코드가 흩어져 단순화된 모습이 보기 좋네요.
지갑도 좋은 erd가 그려진 것 같습니다. 하지만 erd와 model의 형국이 동일하니 의심하셔야되는 부분일겁니다. service와 repository 영역은 controller와 service영역만큼 가까운 영역이라 erd와 도메인 모델간의 모양이 일치할 순 있습니다만(jpa에서는) 어디까지나 추상화된 해당 기술의 영역이지 여긴 jdbcTemplate으로 직접 구현하였기 때문에 쿼리에 많이 의존했을텐데요. 다음번에서는 이부분에 대해서도 좀더 이야기를 해드릴 수 있을 것 같습니다. ㅎㅎ

그리고 전반적으로 Transactional 어노테이션이 나타나지 않았는데요. 사실 지금 코드전반적으로 없어도 에러가 난다고 했을때 롤백이 안되거나 그러지는 않을것 같아요. 하지만 어노테이션의 역할이 기능뿐만이 아니기에 저는 단일문에서도 붙여주곤 합니다. 이 부분도 3주차에서는 잘 반영이 되었으면 좋겠습니다. 수고하셨습니다~

2023-07-21 05:20 UTC, SY97P commented on src/main/java/com/tangerine/voucher_system/application/wallet/model/Wallet.java
> +}
지금 개인프로젝트를 하고 있는데, 
적용해보고자 했던 부분에 대해서 언급해주시고, 예제 코드까지 주셨네요. 

좀 더 고민해보고, 적용방법이나 구조에 대해서 결론을 내보겠습니다.

2023-07-21 08:37 UTC, merged