[4기-이성주] SpringBoot Part2 Weekly Mission PR 제출입니다.
prgrms-be-devcourse/springboot-basic pull request #815
Opened 2023-07-12 11:57 UTC by Seongju-Lee

## 📌 과제 설명 

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

## ✅ PR 포인트 & 궁금한 점 
1. **DTO-Entity의 변환 위치** 관련해서 멘토님들께 여쭤보고 싶은 내용이 있습니다!!
현재는 Service가 Controller로부터 DTO를 전달 받으면 Entity로 변환하게끔 구현했습니다.
그런데, **"Console, Web 등 다양한 형태의 요청에 따라 Service에 전달하는 DTO를 다양하게 만들어야 하나?"라는 생각에서 비롯되어
"하나의 Controller가 하나의 Service에 의존하는 DTO가 괜찮은건가?" 라는 의문이 들었습니다.**
그렇게 된다면 기능이 많아질수록 중복되는 코드가 많아질 것이라 생각했습니다.
**그래서 하고자 했던 방식이 Controller에 의존적인 DtoMapper / DtoHandler 등 별도의 변환 클래스를 만들어 service로 Entity를 전달**하게끔 해보고자 했는데, 
위 방식으로 해도 괜찮은 방법일까요? 이렇게 의존적인 상황이 발생한다면 실무에서는 어떤 방식으로 이를 해결하는 지 여쭤보고 싶습니다.!!!!

2. @Builder vs 생성자
제가 더 조사해보고 공부해봐야 할 내용이긴 하지만 보통 Builder를 통해 객체를 생성하는 것이 가독성이나 편의성에서 더 편한 이점이 있어서 사용하곤 하는데, 실무에서도 Builder가 자주 사용되곤 하는 지 여쭤보고 싶습니다..ㅎㅎ

2023-07-14 14:09 UTC, JoosungKwon reviewed
@Seongju-Lee 
성주님 과제하시느라 고생하셨습니다!! 바쁘신데도 열심히 잘해주셨네요!! 👍
리뷰 남겼으니 추후에 참고해주세요~ 클론 프로젝트와 3주차 과제 모두 화이팅입니다~!!

질문에 답변하자면
> DTO-Entity의 변환 위치 관련해서 멘토님들께 여쭤보고 싶은 내용이 있습니다!!
현재는 Service가 Controller로부터 DTO를 전달 받으면 Entity로 변환하게끔 구현했습니다.
그런데, "Console, Web 등 다양한 형태의 요청에 따라 Service에 전달하는 DTO를 다양하게 만들어야 하나?"라는 생각에서 비롯되어
"하나의 Controller가 하나의 Service에 의존하는 DTO가 괜찮은건가?" 라는 의문이 들었습니다.
그렇게 된다면 기능이 많아질수록 중복되는 코드가 많아질 것이라 생각했습니다.
그래서 하고자 했던 방식이 Controller에 의존적인 DtoMapper / DtoHandler 등 별도의 변환 클래스를 만들어 service로 Entity를 전달하게끔 해보고자 했는데,
위 방식으로 해도 괜찮은 방법일까요? 이렇게 의존적인 상황이 발생한다면 실무에서는 어떤 방식으로 이를 해결하는 지 여쭤보고 싶습니다.!!!!

- 일단 시도해보시는게 좋을 것 같아요! 틀리면서 혹은 해보면서 배우는 것이 있다고 생각합니다. 그리고 의미를 정확하게 이해하지는 못했습니다..😅 `DtoMapper` 클래스를 만드는 것에 대해 물어보신거라면 저는 사용해도 괜찮다고 생각합니다. 물론, 좋아하지 않는 분들도 있기 때문에 팀원들과 상의해서 정하시면 될 것 같아요! 

- 그리고 보통 요청에 따라 DTO가 다양하게 만들어지기는 합니다! 중복을 이야기 하셨는데 어떤 부분에서 중복이 발생하는건지 정확하게 이해하지 못했습니다..  Dto 생성하는 부분에서 중복되는 부분을 말씀하신게 맞나요..? 그렇다면 Dto 내부에서 Entity를 매개변수로 받아서 변환하는 로직을 둘 수도 있을 것 같아요!

- 제가 만약 잘못 이해한거라면 다시 이야기해주시면 감사하겠습니다. 아니면 라이브때 질문주시면 좋을 것 같아요!

> @builder vs 생성자
제가 더 조사해보고 공부해봐야 할 내용이긴 하지만 보통 Builder를 통해 객체를 생성하는 것이 가독성이나 편의성에서 더 편한 이점이 있어서 사용하곤 하는데, 실무에서도 Builder가 자주 사용되곤 하는 지 여쭤보고 싶습니다..ㅎㅎ

- 저는 파라미터가 많은 경우에는 사용하는 편입니다! 다만, Lombok의 `@Bulider` 경우에는 주의할점이나 활용에 대해서는 알아두시는 게 중요할 것 같습니다! (보통은 `@Bulider`를 클래스 위에 두지 않는 경우가 많습니다. 이유를 모르신다면 알아보면 좋을 것 같아요!!)

2023-07-15 02:21 UTC, graygreat requested changes
안녕하세요 성주님 :)

미션 하시느라 고생 많으셨습니다 👍 
주성님이 리뷰를 잘 달아주셔서 저는 간단한 피드백 정도 남겼습니다 ㅎ
참고 부탁드려요!

> DTO-Entity의 변환 위치 관련해서 멘토님들께 여쭤보고 싶은 내용이 있습니다!!
굉장히 좋은 고민이네요!
우선 Dto-Entity의 변환 위치에 대해서 먼저 얘기를 해보면 저는 변환 로직 자체는 dto의 책임이라고 생각이 들기 때문에 dto 자체에서 변환 해주는 로직을 구현하고 있습니다. layer를 나누는 측면에서 entity는 dto를 알고 있으면 안되기 때문에 dto에서 변환을 해주게 되는거죠. (이 부분은 잘하고 계신듯)

> "Console, Web 등 다양한 형태의 요청에 따라 Service에 전달하는 DTO를 다양하게 만들어야 하나?"라는 생각에서 비롯되어
"하나의 Controller가 하나의 Service에 의존하는 DTO가 괜찮은건가?" 라는 의문이 들었습니다.

Console, web 등 다양한 형태의 요청에 따라 dto를 새롭게 정의합니다. 물론 중복이 많은 것들은 따로 빼서 상속을 받을 수 있겠죠. 이렇게 다양하게 dto를 정의하는 이유는 사실 엄청나게 많이 만들 상황이 없다는 것 같아요. 당장 예를 들어주셨듯이, console, web, ... 또 뭐가 있을까요? 현업에서는 console을 만들지 않으니 web 밖에 없겠죠? 그럼 web에 의존하는 dto는 중복이 어느정도 있더라도 그냥 만들어 사용합니다 

>  Controller에 의존적인 DtoMapper / DtoHandler 등 별도의 변환 클래스를 만들어 service로 Entity를 전달하게끔 해보고자 했는데,
위 방식으로 해도 괜찮은 방법일까요? 이렇게 의존적인 상황이 발생한다면 실무에서는 어떤 방식으로 이를 해결하는 지 여쭤보고 싶습니다.!!!!

좋은 아이디어 인 것 같네요!
하지만 저는 관리 포인트가 늘어나는 걸 최대한 지양하고 싶다는 생각을 가지고 있어요.
아마 대부분 개발자가 그럴거고요.
성주님은 dto를 수정이 해야한다고 가정하면, 젤 처음 어떤 파일을 열어보실 것 같나요?
저는 아마 dto 파일을 열어볼 것 같은데, 변환 로직이 없으면 또 그걸 찾아야겠죠?
주성님이 직접 짠 코드라면 금방 찾을 수 있겠지만, 엄청 큰 프로젝트에 패키지도 100개 가까이 되는 곳에서 다른 사람이 짠 코드에 이러한 것을 찾는건 정말 쉽지 않습니다. 
그렇기 때문에 최대한 관리 포인트를 줄일 수 있는 방법을 생각해보면 좋을 것 같아요.
팀원들이랑도 어떻게 하면 좋을지 한번 얘기를 나눠보시고 좋은 룰을 정하면 될 것 같습니다!

> @builder vs 생성자
제가 더 조사해보고 공부해봐야 할 내용이긴 하지만 보통 Builder를 통해 객체를 생성하는 것이 가독성이나 편의성에서 더 편한 이점이 있어서 사용하곤 하는데, 실무에서도 �Builder가 자주 사용되곤 하는 지 여쭤보고 싶습니다..ㅎㅎ

이건 주성님이 잘 달아주셨네요 ㅎ
저도 파라미터가 많은 경우에 사용합니다! 그 외에는 그냥 생성자를 사용할려고 하는데 사실 빌더가 편해서 빌더를 사용하는 경우가 많은 것 같아요.
한번 장단점을 찾아보시고 공유해주세요~

2023-07-15 02:21 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/VoucherAppController.java
> +            DomainType selectedMenu = input.menu();
DomainType 이라는 네이밍이 무엇을 뜻하는지 모르겠어요.
input에서 menu를 들고 왔는데 domainType?!? 이라는 의문을 가지게 되네요.
불명확한 네이밍은 팀원들이 코드를 보는데 들어가는 뎁스를 깊게할 수 있습니다. (뎁스가 깊으면 시간이 오래걸리고 복잡도가 높아짐)

2023-07-15 02:21 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/domain/DomainType.java
> +                    .filter(domainType -> (domainType.domainNumber == Integer.parseInt(input)))
filter안에 있는 조건문 또한 메소드로 분리하면 가독성이 더 높아질 수 있을 것 같네요!

2023-07-15 02:21 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/domain/DomainType.java
> +
한칸 띄우는 이유가 있으실까요?

2023-07-15 02:21 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/domain/customer/dto/CustomerDto.java
> +
성주님은 어떠한 이유 때문에 Dto를 하나의 묶으실라고 하셨는지 궁금합니다 ㅎ

2023-07-15 02:21 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/domain/customer/controller/CustomerController.java
> +    }
해당 로직은 depth가 3이네요.
[객체지향 생활 체조 원칙](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)을 최대한 지키려고 해보시면 좋을 것 같아요.

2023-07-15 02:21 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/domain/customer/dao/CustomerJdbcRepository.java
> +            return jdbcTemplate.queryForObject(QUERY, paramMap, CUSTOMER_ROW_MAPPER);
주성님 말씀처럼 중복된 이름 검증에 대한 로직은 보이지 않네요 ㅠ

2023-07-15 02:21 UTC, graygreat commented on src/main/java/org/devcourse/springbasic/domain/customer/domain/CustomerMenuType.java
> +        }
else문을 사용하지 않고 그냥 return 해줘도 되겠네요

2023-07-25 07:15 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/VoucherAppController.java
> +    }
해당 메서드 내부에서 입력환경을 받도록 로직을 구현한다는 가정이었습니다!!
현재는 콘솔 환경에서만 작업하기 때문에 "CONSOLE"이라고 명시해둔 상황이었습니다!

2023-07-25 07:22 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/domain/customer/domain/Customer.java
> +    }
this 호출에 대해 아예 생각도 안해보고 있었네요..ㅎㅎ
감사합니다!!! :)

2023-07-25 07:25 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/domain/customer/dto/CustomerDto.java
> +
> DTO가 더 많아지면 한 클래스에 너무 많은 내용이 있게 되어서 오히려 보기 힘들어질수도 있을 것 같은데 이부분은 어떻게 생각하시나요?

저는 이 부분에서 오히려 여러 클래스로 나누면 보기 힘들것 같다고 생각했습니다..!! 그래서, 한 도메인과 관련된 DTO를 하나의 파일에서 관리하고 싶다는 생각에 묶어두긴 했었습니다.

> 이러한 방식으로 사용하시는 걸 싫어하는 분도 있습니다!

이 부분 고려해서 한번 이야기 해보겠습니다!! 감사합니다 :)

2023-07-25 07:26 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/domain/voucher/controller/VoucherController.java
> +    }
**객체지향 생활 체조 원칙** 을 생각해보면서 전반적으로 수정해보겠습니다.!!

2023-07-25 07:28 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/domain/customer/dao/CustomerJdbcRepository.java
> +            return jdbcTemplate.queryForObject(QUERY, paramMap, CUSTOMER_ROW_MAPPER);
검증에 대한 부분을 간과했습니다.ㅠㅠ
검증로직을 전반적으로 추가/수정 해보겠습니다!!

2023-07-25 07:30 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/domain/voucher/domain/FixedAmountVoucher.java
> +    }
고정할인율을 상수로 빼놨습니다.

2023-07-25 07:34 UTC, Seongju-Lee commented on src/main/java/org/devcourse/springbasic/domain/voucher/domain/FixedAmountVoucher.java
> +        voucherValidator.validate(this);
voucher 종류에 상관없이 검증로직에 대한 부분은 동일하기도 하고, 검증로직에 대한 부분을 별도로 분리함으로써 관리 포인트를 명확하게 하고 싶었는데,
이 부분에 대해 어떻게 생각하시는지 주성멘토님의 생각을 여쭤보고 싶습니다!!ㅠㅠ

2023-07-31 06:44 UTC, merged