[4기 - 안재영] SpringBoot Part2 Weekly Mission PR 제출합니다
prgrms-be-devcourse/springboot-basic pull request #818
Opened 2023-07-12 14:59 UTC by JaeyoungAhn

## 📌 과제 설명 및 요구사항  
- SpringBoot Part2 Weekly Mission(~7/7)
    
    **(기본)** **바우처 관리 애플리케이션**
    - [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
        - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
        - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
        - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
    - [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
        - customers 테이블 정의 및 추가
        - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
    - [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
        - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
        - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
        - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
    
    **(심화)** **바우처 지갑을 만들어보세요.**
    - 특정 고객에게 바우처를 할당할 수 있습니다.
    - 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
    - 고객이 보유한 바우처를 제거할 수 있어야 합니다.
    - 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.
## 구조 및 흐름

<img width="289" alt="2023-07-12 23_44_16-프로젝트 진행 흐름" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/39547923/139513b7-47ec-4492-af6a-ce23a163e75c">

![KakaoTalk_20230712_235432868_01](https://github.com/prgrms-be-devcourse/springboot-basic/assets/39547923/7489d5b6-7e1f-4b43-99c9-6e5e805afd82)

## 👩‍💻 구현 내용 !-- 기능을 Commit 별로 잘개 쪼개고, Commit 별로 설명해주세요 -->
[feat : 유저 생성, 이름 기반 바우처 확인 콘솔 뷰 추가](https://github.com/prgrms-be-devcourse/springboot-basic/commit/05ab9e339d83f528f001d31174f92feef655a3f0)

[feat : User 엔티티 관련 레이어 추가](https://github.com/prgrms-be-devcourse/springboot-basic/commit/76f72ee730aa3ac922403edde7ee17b149d430fc)

[refactor : view 내 메소드 파일 위치 변경](https://github.com/prgrms-be-devcourse/springboot-basic/commit/054b420e81187dd57e77c2bbdb7e274fba3994a4)

[refactor : 바우처에 Strategy 패턴 적용](https://github.com/prgrms-be-devcourse/springboot-basic/commit/3464887ac5b527360094daed70cb74df7aa63015)

## ✅ PR 포인트 & 궁금한 점 
전체적으로 구조가 복잡하다고 생각됩니다. 어느 부분을 수정하면 좋을지 궁금합니다.

2023-07-14 02:25 UTC, WooSungHwan requested changes
재영님 과제하시느라 수고 많으셨고
쿼리부분만 좀더 깔끔하게 보강해보시는걸 추천드립니다!
진행해보시고 궁금하신부분 질문주시면 댓글달러 오겠습니다.

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/controller/WalletController.java
> +    public WalletResponse assignVoucher(WalletRequest walletRequest) throws WrongRangeFormatException {
WrongRangeFormatException 요 exception unchecked인데 굳이 다 throws를 기재해줘야 할까요오~

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/controller/WalletController.java
> +    public WalletResponse assignVoucher(WalletRequest walletRequest) throws WrongRangeFormatException {
이거말고도 모든 부분 다 확인해보세요~

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/service/WalletService.java
> +        return new WalletResponse(wallet, username);
이 메소드 이름이 getWalletResponse가 적절할까요?
어떤 결과가 나온걸 WalletResponse라는 걸로 바꿔주는 로직. 이전에
어떤 결과를 도출할것이고 해당 로직. 이전에.
요청 객체 혹은 raw값들을 넘기는 부분의 로직. 이전에.
유효성을 검증하는 로직. 이전에.
각 파라미터들을 해석하는 부분..
작성하신 메소드 내의 모든 로직들을 한글로 해석한건데 getWalletResponse 라는 이름으로 담기엔 조금 너무 많죠ㅎㅎ

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/service/WalletService.java
> +        return new WalletResponse(wallet, username);
isValidNameFormat 와 isValidOrder 의 결과에 따라 boolean 리턴이 아닌 어떤 throw가 되는건 어떤가요?

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/enums/WalletSelectionType.java
> +    FREE_VOUCHER("free"),
이건 무슨 키워드일까요??

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +    }
```
sql = """
                SELECT 
                    DISTINCT u.user_id, u.username 
                FROM `user` u 
                    JOIN wallet w ON u.user_id = w.user_id 
                WHERE w.assigned_time IS NOT NULL 
                    AND w.unassigned_time IS NULL     
            """;
```
java 17을 쓰고 계시므로 좀더 쉽게 쿼리를 쓸 수 있는 이런 방법은 어떤가요?

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +    }
그리고 distinct로 해결하기보다 assigned_time과 같은 부분에서 order by xx_time desc limit 1과 같이 단일 raw를 보장하는 방법은 어떠세요?
사실 어렵지 않은 쿼리인데 distinct가 들어가는게 좋아보이진 않습니다 ㅠ

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +
```
sql = """
            SELECT 
                u.user_id, u.username 
            FROM `user` u 
                JOIN wallet w ON u.user_id = w.user_id 
            WHERE w.voucher_id = :voucher_id
        """;
```
이렇게 alias를 붙이는건 되게 좋은 것 같습니다.

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +
JOIN 보단 명확한 의미인 INNER JOIN 으로 쓰는건 어떤가요??

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/UserRepository.java
> +    User getUserByVoucherId(Voucher voucher);
이름은 VoucherId로 조회하겠다는 의도인데 파라미터는 Voucher를 받는군요?

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +        });
여기서 (rs, rowNum) -> {} 으로 넘어가는 로직이 아래에도 공통적으로 있는 것 같습니다~ 어떻게 해결해야 좋을까요~?

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +    }
여기도 정확히 어떤 목적인지 잘 모르겠죠?
sql로 넘어오는 파라미터는 반드시 유저에 관한건지 뭔지.. 보장할 수 있는 방법이 없는 것 같아요ㅠㅠ

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +    }
`List<User> rows = jdbcTemplate.queryForList(sql, Collections.emptyMap(), User.class);`
이렇게하면 유저로 받을 수 있지 않나요?~

2023-07-14 02:25 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +        String sql = "SELECT DISTINCT v.voucher_id, v.discount_type, v.discount_value " +
이쪽 쿼리도 위에 코멘트처럼 수정해보는건 어떨까요~?

2023-07-14 06:48 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/controller/WalletController.java
> +    public WalletResponse assignVoucher(WalletRequest walletRequest) throws WrongRangeFormatException {
service 레이어와 바로 맞닿아있는 controller 레이어에서 try-catch를 하여 에러를 처리한다면 controller에서 throws 표현을 통해 view까지 exception을 던지지 않아도 될 것 같습니다. exception 처리의 책임을 콘솔 뷰 단이 가지는 것이 아니라 controller가 가지고 controller는 잘못된 입력이라는 커스텀 response를 리턴해주면 될 것 같습니다. 콘솔 뷰 단에서는 잘못된 입력임을 response를 통해 알았다면 적당한 if 문을 통해 재입력을 요구하면 될 것 같습니다. 웹 환경으로 바뀐다면 @ControllerAdvice와 같은 에러 처리 방법도 공부해서 적용해볼 수 있을 것 같습니다.

2023-07-14 07:17 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +
수정하도록 하겠습니다!!

2023-07-14 07:22 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/UserRepository.java
> +    User getUserByVoucherId(Voucher voucher);
굳이 voucher를 넘겨 줄 필요가 없는 것 같습니다. id만 넘겨주도록 수정 하겠습니다!

2023-07-14 07:47 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/enums/WalletSelectionType.java
> +    FREE_VOUCHER("free"),
지갑이라는 곳에 바우처를 집어 넣을지 아니면 이미 들어가있는 바우처를 제거할지에 대한 선택을 하기 위해 사용하였으나 오해의 소지가 있는 용어를 사용한 것 같습니다. 지갑에 기록할때 필요한 클래스이지만 바우처를 다루므로 VoucherAssignmentSelectionType라고 클래스명을 정해주고 ASSIGN_VOUCHER, REMOVE_VOUCHER를 사용하면 괜찮을까요?

2023-07-14 13:26 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/service/WalletService.java
> +        return new WalletResponse(wallet, username);
> 이 메소드 이름이 getWalletResponse가 적절할까요?
인텔리제이 자동기능으로 빼다보니 그렇게 된 것 같습니다 ㅜㅜ 좀 더 적절한 네이밍으로 수정해보겠습니다.

2023-07-14 13:28 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/service/WalletService.java
> +        return new WalletResponse(wallet, username);
> isValidNameFormat 와 isValidOrder 의 결과에 따라 boolean 리턴이 아닌 어떤 throw가 되는건 어떤가요?

말씀해주신 것을 보고 공부를 해보았더니 Unchecked exception의 경우 throws 키워드가 없다하더라도 call stack의 최상단까지 전파한다는 사실을 배웠습니다. 따라서 validation을 담당하는 클래스 내 메소드에서 직접 throw를 하더라도 처리할 수 있다는 것을 배웠습니다. 이 부분은 수정해서 service 레이어 내 메소드에서 직접 throw를 하지 않도록 변경하겠습니다.

2023-07-14 13:30 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/enums/WalletSelectionType.java
> +    FREE_VOUCHER("free"),
클래스명과 키워드가 나타내는 것과 의미 일치가 되지 않는 것 같아서 좀 더 역할을 분명하게 알 수 있도록 이름을 변경해보곘습니다ㅜㅜ

2023-07-15 08:01 UTC, devYSK requested changes
안녕하세요 재영님 과제 하시느냐 고생 많으셨습니다
다음의 내용을 스스로의 코드를 보면서 고민해보시고 개선해나가면 좋겠습니다. 

- 자신이 작성한 코드가 일주일뒤에도 읽힐 수 있을지 고민하며 작성하면 좋을거같습니다. 
    - 협업간에 팀원들이 스스로가 작성한 코드를 읽는데에 문제가 없도록 하는게 좋겠죠.
- 너무 많은 출력이 로직에 섞여 코드의 가독성이 떨어집니다. 
- View쪽에 클래스를 너무 과하게 쪼개  찾기도 힘들뿐더러 구조 파악이 어렵습니다. 같은 책임을 가진 기능들을 적절하게 객체에 묶으면 좋겠습니다.  
    - 절차지향적인 코드이며 대부분 하드코딩입니다.
    - 콘솔 출력이 비즈니스 로직에 섞여 가독성을 해쳤습니다.  
    - 콘솔 출력 기능이 없어진다면 이 코드들은 어떻게 될까요? 
    - 요구사항 변경으로 인해 기능이 바뀌면 View쪽 코드들은 사용할수가 없을것 같네요. 영향이 안가게 작성할 순 없을까요?  
- 중요한 비즈니스 로직들이 눈에 보이지 않아 코드로 어떤 기능을 하는지 파악하기가 어렵습니다.  
- 실제로 테스트도 없습니다. 너무 테스트하기 어려운 코드입니다. 
- Mock을 남용하였다고 볼 수 있습니다. given절이 길어질뿐더러 테스트 코드의 가독성, 관리가 너무 어려울것습니다. Mock을 사용해야 할 부분을 조금 더 고민해보시면 좋을것 같습니다

Spring에서 각 Component (Repository, Service, Controller.. 등등) 들이 어떤 책임과 역할을 갖고 있는지 찾아보시면 좋겠습니다.

또한 Mock을 사용할때는 실제로 테스트하기 어려운 써드파티, 외부 api, 외부 인프라 등에 대해서 사용하면 적절할 때가 있다고 생각합니다.
외부 인프라여도 로컬 및 테스트 서버 환경에서도 레포지토리는 테스트로 어느정도 컨트롤이 가능합니다. 
실제 애플리케이션의 핵심 비즈니스 로직들이 Mocking된다면 런타임때 제대로 동작하는지 알 수 있을까?를 생각해본다면
지금 테스트 코드들은 적절하다고 판단하기 어렵다고 생각합니다

2023-07-15 19:30 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +        });
toRowMapper()라는 메소드를 만들어서 공통되는 부분을 묶어내는 방법으로 해결하도록 하겠습니다!

2023-07-15 19:33 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcUserRepository.java
> +    }
저렇게 간단하게 받으면서 처리할 수 있군요..! 기억해놓겠습니다!

2023-07-15 19:34 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/dto/ResponseDTO.java
> +
정상인 경우와, 비정상인 경우 별개의 클래스로 감싸서 리턴해주는 방식으로 바꿔보겠습니다!

2023-07-15 19:35 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/controller/VoucherController.java
> +        return voucherService.getAssignedVoucherList();
해당 부분도 ResponseDTO를 사용하는 식으로 변경하겠습니다!

2023-07-15 19:35 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/controller/WalletController.java
> +        }
말씀해주신대로 에러랑 일반응답이랑 다른 것으로 취급하는 식으로 controller를 변경하도록 하겠습니다.

2023-07-15 19:37 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/render/ConsoleListView.java
> +    private final VoucherController voucherController;
View라고 되어있는 부분은 전체적으로 눈에 잘 들어 오도록 변경해보겠습니다..!

2023-07-15 19:40 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/render/ConsoleUserCreationView.java
> +    void createUser() {
같은 View를 맡고있지만 서로 다른 여러 클래스로 나눠놓은 상태인데, 현재 view 클래스에서 다른 view 클래스의 private 메소드를 직접 호출하는 것이 불가능하여 private 지정자 없이 사용하려고 했었습니다. 이 부분은 전체적으로 방식을 바꿀때 없애도록 하겠습니다.

2023-07-15 19:43 UTC, JaeyoungAhn commented on src/test/java/com/prgmrs/voucher/service/UserServiceTest.java
> +
@Spy를 선언한 객체에서 사용된 메소드는 원본 메소드로 redirection해주는 기능을 하는 것으로 배웠습니다. 해당 테스트 파일에서 service 레이어 안에서 외부에서 불러와서 사용하는 validation 관련 클래스들이 주입이안되어서 service 내 메소드 실행 도중 에러가 나와서 해결하고자 사용을 했었는데, 아무래도 적합하지 않은 방식 같습니다. 이 부분은 validation 로직을 전체적으로 바꾸면서 없애도록 하겠습니다.

2023-07-15 20:14 UTC, JaeyoungAhn commented on src/test/java/com/prgmrs/voucher/controller/WalletControllerTest.java
> +
컨트롤러 레이어에서 유닛테스팅을 작성할때 서비스 레이어의 동작을 정해주고 그 외 레이어와는 단절시키기 위해 Mock을 사용했습니다. 순수하게 JUnit의 new 키워드를 사용해서 테스트를 작성하는 것은 다른 레이어와 의존성을 가지고 있어서 특정 레이어를 테스트하는데는 적합하지 않다고 생각했습니다. 말씀하신 것 처럼 메소드로 빼보거나 fixture를 만들어보는 방식으로 개선해보겠습니다.

2023-07-20 12:14 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/view/ConsoleApplication.java
> +    private final BlacklistProperties blacklistProperties;
view 패키지에 있는게 어색해요!! 
구동기니까 다른 패키지는 어때요?

2023-07-20 12:14 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/view/io/ManagementType.java
> +        }
NumberFormatException인지 추적 못할거같아요

2023-07-20 12:16 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/view/io/ManagementType.java
> +            throw new WrongRangeFormatException("input must be number");
속성으로 number를 가지면 안될까요? 
//
복잡한 if문은 메소드로 가독성있게 뺴는 편입니다.

2023-07-20 12:18 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/util/UUIDGenerator.java
> +}
compoent인데 static 이네요?

2023-07-20 12:19 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/util/UuidConverter.java
> +}
여기도 마찬가지네요.

2023-07-20 12:20 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/service/UserService.java
> +        UUID uuid = UUIDGenerator.generateUUID();
UUID.randomUUID()랑 다를게 없네요

2023-07-20 12:21 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
깔끔하게 맞춰주세요!

2023-07-20 12:21 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
더 깔끔하게 맞출수는 없을까요?

2023-07-20 12:22 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
서브쿼리의 단점은 무엇이 있을까요?

2023-07-20 12:23 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/model/wrapper/Username.java
> +}
null 또는 ""가 들어온다면?

2023-07-20 12:25 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/enums/DiscountType.java
> +    }
캐스팅 까지 하면서 short를 사용한 의도가 궁금합니다

2023-07-20 12:27 UTC, devYSK commented on src/main/java/com/prgmrs/voucher/controller/WalletController.java
> +}
컨트롤러 밖에서 try-catch 를하거나
디자인 패턴을 이용해서 코드에서 없앨 수 있을것 같아요

2023-07-20 12:28 UTC, devYSK approved these changes
고생하셨습니다 재영님
코드가 많이 깔끔해졌네요. 훨씬 읽기 좋습니다.
다만 반복되는 아쉬운 부분등이 있어 코멘트 남겼습니다.

2023-07-20 14:05 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/controller/WalletController.java
> +}
반복되는 부분은 반드시 공통화를 적용해보도록 해요.

2023-07-20 14:06 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
`LEFT JOIN -> LEFT OUTER JOIN` 으로 명확하게 써주면 좋을듯 합니다.

2023-07-20 14:12 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
이쿼리 왜이렇게 복잡하죠?? 그냥 미할당된 바우처 목록 주면 될것 같은데..

2023-07-20 14:13 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
wallet에서 미할당된 조건 걸고 voucher_id 만 따로 select해서 voucher 목록조회하듯 in으로 넣어보세요.

2023-07-20 14:19 UTC, WooSungHwan commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
```
select
from 바우처
where id in (
  select 바우처아이디
  from wallet
  where 미할당된 바우처 조건
)
```

or 
```
List<String> ids = 
  "select 바우처아이디
  from wallet
  where 미할당된 바우처 조건"

select
from 바우처
where id in (ids)
```

2023-07-21 03:46 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/ConsoleApplication.java
> +    private final BlacklistProperties blacklistProperties;
view 패키지 밖으로 빼내서 바로 볼 수 있도록 하겠습니다!

2023-07-21 03:59 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/io/ManagementType.java
> +            throw new WrongRangeFormatException("input must be number");
private final String value; 대신 private final String message; 로, ManagementType of(String value) 대신 ManagementType of(String orderNumberAsString)으로 바꾸어서 의미를 명확하게 알 수 있도록 하겠습니다. int convertedValue또한 int orderNumber로 하여 if (convertedValue >= 0 && convertedValue < ManagementType.values().length)에 해당하는 if문을 if(isWithinOrderNumberRange(orderNumber))로 별도의 메소드로 빼도록 하겠습니다.

2023-07-21 04:05 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/util/UuidConverter.java
> +}
삭제하겠습니다!

2023-07-21 04:09 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
SELECT
  v.voucher_id, v.discount_type, v.discount_value
FROM `voucher` v
  INNER JOIN `wallet` w ON v.voucher_id = w.voucher_id
  INNER JOIN `user` u ON w.user_id = u.user_id
WHERE  u.username = :username
  AND w.unassigned_time IS NULL
ORDER BY v.created_at

이렇게 수정하겠습니다!

2023-07-21 05:12 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/enums/DiscountType.java
> +    }
데이터베이스에 사용했던 타입이 TINYINT UNSIGNED인데 이것이랑 가장 유사한 데이터 타입이 short이라서 short을 사용하려고 했던 것인데 사실 자바에서 기본적으로 int로 데이터를 처리하기도하고 short이 사용되는 부분이 DB에 직접적으로 들어가는 데이터는 아니기에 가독성을 포기하면서까지 사용을 할 필요는 없을 것 같습니다. 이 부분은 int로 바꿔서 진행해 보겠습니다.

2023-07-21 05:13 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/controller/WalletController.java
> +}
해당 부분은 3주차 json을 이용하는 경우 @ControllerAdvice를 이용해서 반복되는 코드를 없애도록 하겠습니다.

2023-07-21 05:19 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
> 더 깔끔하게 맞출수는 없을까요?

더 깔끔하게 수정해보겠습니다!

2023-07-21 05:20 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
> 서브쿼리의 단점은 무엇이 있을까요?

또 다른 하나의 sql문을 처리해야한다는 점에서 대용량 데이터를 처리할 경우 성능 문제가 발생할 수 있을 것 같습니다.

2023-07-21 05:20 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
> `LEFT JOIN -> LEFT OUTER JOIN` 으로 명확하게 써주면 좋을듯 합니다.

해당 표현으로 수정하겠습니다!

2023-07-21 05:41 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/repository/JdbcVoucherRepository.java
> +
> 이쿼리 왜이렇게 복잡하죠?? 그냥 미할당된 바우처 목록 주면 될것 같은데..

현재 데이터베이스에서 바우처가 한번이라도 할당된 적이 없는 경우 wallet이라는 곳에서 어떠한 정보도 가지고 있지 않음과 동시에 voucher라는 곳에서도 할당 되었는지에 대한 어떠한 정보를 가지고 있지 않습니다. wallet에서는 바우처가 유저에게 할당되는 순간 (voucher Id, user Id, 생성시간) 이렇게 세개를 기준으로 composite primary key로 존재하는 방식입니다. 유저 한명당 wallet을 하나만 가지는 것이 아니고 voucher가 유저에게 할당될 때마다 wallet 테이블에 하나의 row가 생기게 되는데 심지어 유저 한명이 같은 바우처를 여러번 할당 받아 wallet 테이블에 동일한 유저 Id와 바우처 Id를 여러번 받을 수 있습니다(할당=>할당해제=>재할당). 따라서 생성시간까지 이용해서 같은 유저 Id와 바우처 Id를 담을 수 있게 하였습니다.

바우처가 한번이라도 할당된 적이 없는 것을 알기 위해서는 우선 wallet에 LEFT OUTER JOIN을 해서 한번도 할당된적 없는 voucher Id에 해당하는 것과 조인된 wallet에서 w.voucher_id IS NULL인 경우를 통해 할당된 적이 없는 바우처임을 알 수 있습니다. 하지만 추가적으로 바우처가 어떤 유저에게 할당된 적이 있지만 다시 할당이 해제되어 다른 유저에게 할당될 수 있는 상태라면 앞선 방식으로 조인을 한다하더라도 할당된 이력이 있는 경우 w.voucher_id가 존재하게되어 IS NULL 조건에 부합하지 않습니다. 따라서 서브쿼리를 하나 더 사용해서 바우처 Id 별로 전부 이력 조회를 했을때 사용된 적이 있는 경우를 제외하고(is_used=0) unassigned_time이 전부 채워져있는 상태(unassigned_time이 한번도 NULL인 경우가 있으면 안되는 경우)인 경우는 다시 할당할 수 있는 바우처라고 생각했습니다.

하지만 말씀하신 것 처럼 비효율적인 SQL인 것 같아서 (할당=>할당해제=>재할당) 된 바우처의 경우에도 빠른 시간안에 알 수 있기 위해서는 SQL 구조 자체를 변경해서 바우처 자체에서 사용 유무를 판단할 수 있도록 하는 것이 좋을지 궁금합니다.

2023-07-21 05:41 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/model/wrapper/Username.java
> +}
value.length조건에서 255글자 미만 뿐만이 아니라 한글자 이상임을 검사하는 식으로 개선해보겠습니다!

2023-07-21 09:52 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/view/io/ManagementType.java
> +        }
NumberFormatException은 runtime 익셉션이므로 다른 익셉션으로 감싸서 던지는 것 보다 해당 에러 자체로서 다뤄야한다는 의미로 이해했습니다. NumberFormatException으로서 처리하도록 하겠습니다.

2023-07-21 10:10 UTC, JaeyoungAhn commented on src/main/java/com/prgmrs/voucher/service/UserService.java
> +        UUID uuid = UUIDGenerator.generateUUID();
service 레이어 이전에 controller 레이어에서 UUID를 넘기는 것을 생각해봤지만 그럼에도 여전히 테스팅할때 어떠한 이점을 가지지 못하는 것 같아서 따로 Generator를 만들어서 추상화해주는 것을 생각했지만 구체적으로 어떠한 테스팅 이점이 있는지는 잘 몰라서 검색하여 공부를 했습니다. 해당 메소드는 static으로 구현이 되어있어서 mock으로서의 역할을 할 수 없지만 static이 아니었다라고한다면 mock으로서 역할을 대신할 수 있어서 테스팅 시 service 클래스 내 createUser 메소드의 UUIDGenerator.generateUUID()가 원하는 값을 리턴하도록 할 수 있다고 합니다. 따라서 해당 UUIDGenerator.generateUUID()를 static으로서 사용하지 않고 서비스 레이어 내 클래스 내 인스턴스 변수로 주입하여 사용한다면 해결 되는 것으로 이해했습니다. 해당 방향으로 수정해보겠습니다!

2023-07-24 20:47 UTC, merged