[4기 - 장수연] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #823
Opened 2023-07-13 06:50 UTC by sujjangOvO

# SpringBoot Basic Weekly Mission

### 프로젝트 설계도 및 클래스 역할/책임
![image](https://github.com/sujjangOvO/springboot-basic/assets/89267864/a809b214-0ac2-42aa-be37-b62fb27e9645)

---
**(기본)** **바우처 관리 애플리케이션**

- [ ]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [ ]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [ ]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

---
### 작업 순서 List
- [ ] 메모리 바우처 관리 테스트 코드 작성
    - 바우처 메뉴 입력 테스트
    - 바우처 create 테스트
    - 바우처 crate 유효성 테스트
    - 바우처 list 테스트
- [ ] customer 도메인 정의 및 추가
    - customer는 voucher를 가진다 (FK)
- [ ] jdbcVoucherRepository 추가 및 구현
    - id로 voucher 탐색
    - db에 voucher save
    - db의 id에 해당하는 voucher delete
    - db의 모든 voucher findAll
- [ ] mysql db와 연결
    - jdbc template 설정
- [ ] jdbcCustomerRepository 추가 및 구현
    - id로 customer 탐색
    - db에 customer save
    - db의 id에 해당하는 customer delete
    - db의 모든 customer findAll
- [ ] jdbcCustomerRepository 테스트 코드 작성
    - 고객 조회 테스트
    - 고객이 가진 바우처 조회 테스트

## ✅ PR 포인트 & 궁금한 점 
- VoucherApp에서 바로 Voucher, Customer Service를 호출할지 아니면 VoucherApp에 Voucher, Service Controller를 추가 한 다음 Controller가 Service를 호출하게 할지 고민이 됩니다
- 현재는 Controller없이 Service를 바로 호출하도록 하였으나 어떤 선택이 더 나을지 궁금합니다!
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/89267864/25420088-fd41-4a78-bf7e-104e03d20f6a)

2023-07-16 07:49 UTC, HyoungUkJJang requested changes
수연님 2주차 과제 코드 잘 봤습니다 ~ 

리뷰가 조금 많아질 것 같아서 먼저 저는 간단한 것 위주로 남겨봤는데 이거 먼저 반영이 이루어 진 후 다시 남기도록 할게요 😊

+ 코드에 null이 조금 많이 보이는 것 같은데 이 부분에 대해서도 조금 더 깔끔하게 처리할 순 없을지 고민해 보시면 좋을 것 같아요 !

추가적으로 깃 형상에 올리실 때 아래 사항에 대해 조금 더 신경을 써보시면 좋을 것 같아요
1. 컨벤션 맞춤
2. 의미 없는 주석 제거

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +                case DELETE -> System.out.println("delete");
아직 제공되지 않는 기능이라면 없어도 될 것 같습니다 !

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +            if (customerApp == null) continue;
customerApp 이라는 네이밍이 적절할까요?

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +    }
customer를 null로 초기화 > try 안에서 입력을 받는다 > null 체크 > service 호출 순으로 이루어져 있는데 null 체크 정도는 입력 받는 콘솔에서 진행하면 코드가 조금 더 간결해지지 않을까요? 
기본적인 validation 정도는 console 에서 처리해도 저는 괜찮다고 생각합니다.

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/service/CustomerService.java
> +    public List<Customer> list() {
메서드 네이밍은 보통 동사구로 짓는게 규칙으로 사용되고 있어요 아래 글을 한번 읽어볼까요?
[[네이밍 규칙 글 보러가기]](https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/)

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +    }
아직 제공되지 않는 기능이라면 git 형상에는 올라오지 않는게 깔끔할 것 같아요 !

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +        }
비어 있는 경우에 다른 메시지를 출력하는 것 같은데 콘솔의 책임으로 만들어줄 수 있을 것 같아요

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/App/VoucherApp.java
> +    public void voucherRun() throws Exception {
`VoucherService`의 리뷰 중  네이밍 규칙 글을 참조해주세요 ~

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/AppType.java
> +    EXIT;
Enum의 값을 관리할 때는 아래의 형태가 조금 더 값을 추가하고 수정하기 편할거에요 ~
```java
    VOUCHER,
    CUSTOMER,
    EXIT
    ;
```

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/repository/customer/JdbcCustomerRepository.java
> +public class JdbcCustomerRepository implements CustomerRepository {
먼저 전반적으로 메서드에 있는 쿼리를 상수로 관리를 먼저 해보는 것은 어떨까요? 

(아래 리뷰는 바로 반영 안하셔도 괜찮아요 참고만 해주세요 ~)
사실, 단순히 String으로 sql을 작성하면 휴먼 에러가 발생할 확률도 꽤 높아지고 가독성에서도 좋지 않을 것 같아요
이러한 쿼리를 조금 더 깔끔하게 하기 위해서 빌더 같은것을 만들어보면 어떨까요?

2023-07-16 07:49 UTC, HyoungUkJJang commented on src/main/java/com/prgms/voucher/voucherproject/repository/voucher/JdbcVoucherRepository.java
> +        }
매직 넘버를 제거해볼까요?

2023-07-16 07:49 UTC, HyoungUkJJang commented on build.gradle
>  }
현재 롬복은 사용하지 않고 있으니 사용하지 않는 의존성들은 제거하시면 좋을 것 같아요

2023-07-16 18:28 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +    }
f76d723801f52bd8459aa02130d9506564ccab2e 커밋 피드백 반영
- 오로지 customer 인스턴스가 return되었을 때만 db에 save 되도록 console안에서 전부 작성해 보았습니다 .. !!  

```    private void createCustomer() {
        Customer customer = console.inputCreateCustomer();

        if (customer == null) return;

        try {
            customerService.create(customer);
        } catch (DuplicateKeyException e) {
            console.printMessage(Constant.EXITS_EMAIL, true);
        } catch (DuplicateCustomerException e) {
            console.printMessage(e.getLocalizedMessage(), true);
        }
    }
```

```
    public Customer inputCreateCustomer() {
        this.printMessage("등록할 email을 입력하세요: ", false);
        String email =  sc.nextLine().trim();

        if (!validEmail(email)) {
            this.printMessage(Constant.WRONG_EMAIL, true);
            return null;
        }

        this.printMessage("등록할 name을 입력: ", false);
        String name = sc.nextLine().trim();

        try {
            return new Customer(email, name);
        } catch (InputMismatchException e) {
            this.printMessage(e.getLocalizedMessage(), true);
            return null;
        }

    }```

2023-07-16 18:29 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +    }
넵 !! 저도 지우고 올린다는게 또 실수를 해버린 것 같습니다 ㅠㅠ 더더 신경쓰겠습니다 ...!!!

2023-07-16 18:31 UTC, sujjangOvO commented on build.gradle
>  }
8d34e758ae9f06392e22fe198df7170de1c9ba0c 커밋 피드백 반영
- 사용하지 않는 import 문의 패키지 뿐만 아니라 build 파일도 관리하도록 하겠습니다!!

2023-07-16 18:33 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/AppType.java
> +    EXIT;
7219f09aa3560316fd9c011cd27d1239a9d1e792 커밋 피드백 반영
- 세미콜론을 마지막에 배치하도록 하겠습니다!

2023-07-16 18:35 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +            if (customerApp == null) continue;
5f6c4cd716a3187dadef1c8c78bf5aa9de4d902a 커밋 피드백 반영
- 헉 ,, 수정했습니다 !! ㅠㅠ

2023-07-17 05:57 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +        }
ea42ab26ae6de84ab6abe86db11c5e02cae73fce 커밋 피드백 반영
- 리스트의 empty를 확인하고 비어있지 않다면 객체를 출력하는 기능을 Console로 이동했습니다!
- Customer뿐만 아니라 Voucher에도 똑같은 구조가 있어서 변경해 주었습니다!

2023-07-17 06:15 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/voucher/JdbcVoucherRepository.java
> +        }
d4753494a0ec7297fb37953ccd8d9d20406eb64a 커밋 피드백 반영
- JdbcCustomerRepository에도 똑같은 매직넘버가 있어 이를 제거하였습니다
- 상수의 네이밍이 적절한지 궁금합니다 !
- 또한 Autowired를 통해 필드 의존 주입을 삭제하고 생성자 주입으로 변경하였습니다
- 이로 인해, 순환 참조 방지가 가능해지며 final 키워드를 붙여 변경을 방지했습니다

2023-07-17 06:35 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/service/CustomerService.java
> +    public List<Customer> list() {
f67f3470dac32636d5bb9cc353bb4f3c1a2782fa 커밋 피드백 반영
- 메서드는 동사/전치사로 시작하도록 변경하였습니다!
- 무슨 작업을 하는지 명확하게 명시하도록 변경하였습니다!

2023-07-17 06:36 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/VoucherApp.java
> +    public void voucherRun() throws Exception {
f67f3470dac32636d5bb9cc353bb4f3c1a2782fa 커밋 피드백 반영
- 해당 VoucherApp의 voucherRun 메서드는 동사구로 시작하고 무슨 일을 하는지 명시하도록 네이밍을 runVoucherProgram으로 변경하였습니다!

2023-07-17 06:55 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/customer/JdbcCustomerRepository.java
> +public class JdbcCustomerRepository implements CustomerRepository {
158899f0ae5ac6fd51523afc0bc4d921cb7a7de0 커밋 피드백 반영
- static fianl로 SQL을 String 상수로 사용하도록 변경하였습니다
- SQL도 따로 Constant 클래스를 만들어서 관리하도록 하는게 좋을까요?
- 빌더 생성은 JDBC길들이기를 통해 추후에 좀 더 생각해보겠습니다 !

2023-07-17 20:06 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/customer/JdbcCustomerRepository.java
> +public class JdbcCustomerRepository implements CustomerRepository {
가끔씩은 바로 피드백을 반영하기 전에 수연님의 의견도 말씀해주시는 것도 좋을것 같아요.

저는 상수로 관리 하게 되면 오히려 메소드 내에서 어떤 쿼리 문이 실행 되는지 파악하기 힘든 부분이 있는것 같아요.
상수의 이점보다 쉽게 파악되는게 중요한것 같아요.

오히려 기존 처럼 메서드 단위로 봤을 때 sql 문이 메서드 내에 있는 것이 로직을 파악하기에 좋은 것 같아요.

**저는 쿼리 빌더를 바로 구현해보시는건 어떨까 생각이 들어요.**

2023-07-17 20:15 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/voucher/JdbcVoucherRepository.java
> +        }
쿼리가 정상적으로 실행 되었다라는 의미의 네이밍은 어떤가요?

2023-07-18 00:59 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 남겼어요.
확인 부탁 드려요.

2023-07-18 00:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/customer/JdbcCustomerRepository.java
> +        }
try catch 를 사용하지 않을수 있을것 같아요.
queryForObject 내부를 보시면 도움이 될거에요.

2023-07-18 00:59 UTC, Jo-GyuHyeon commented on src/main/java/com/prgms/voucher/voucherproject/repository/voucher/JdbcVoucherRepository.java
> +    }
위의 코멘트와 동일하게 try catch 를 사용하지 않을수도 있을것 같아요.

2023-07-18 09:22 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/voucher/JdbcVoucherRepository.java
> +        }
059b59a48da3ed65b9e82069ab7cc4ddc93d8468 커밋 피드백 반영
- `SUCCESS_QUERY` 으로 네이밍을 변경해 보았습니다 !!

2023-07-18 14:02 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +        }
20a45af3e76fdce33d75fb3fa2e1331910e98970 커밋 피드백 반영
- CustomerApp에서 해당 로직을 수행하지 않고 JdbcCustomerRepository에서 수행하도록 수정하였습니다. 
- CustomerService는 비지니스 로직만 있어야 한다고 생각해서 Service에서 예외를 발생시키지 않고 Repository에서 예외를 발생시키도록 수정하였습니다. 
- 저와 같은 상황엔 Service에서 예외를 발생시키는게 맞는지 Repository에서 예외를 발생시키는게 맞을지 궁금합니다

2023-07-18 19:16 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +        customer.ifPresent(console::printCustomerInfo);
67ddac238c309dc624177278f2f1121e11f7d13f
- map과 orElseThrow를 사용하기엔 console.rpintCustomerInfo가 반환값이 없어(void) 애매하다고 생각했습니다 !
- 따라서 ifPresentOrElse를 이용해 값이 있으면 출력하고 없으면 람다식을 통해 메시지를 띄우도록 하였습니다.

2023-07-18 19:22 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
> +        }
67ddac238c309dc624177278f2f1121e11f7d13f 커밋 피드백 반영
- 구두로 말씀해주신 대로 Repository에는 DB와 연결되므로 쿼리문만 들어가야 하기때문에 Repository에서 삭제하였습니다
- 이메일 형식은 꼭 맞춰야 하는 형식이므로 오류가 발생하지 않게 Console에서 예외를 발생하는 형식으로 피드백 반영하였습니다.
- Console에서 예외를 발생하고 CustomerApp에서 예외를 catch하는 방식으로 변경하였습니다.
- 궁금한 점은 Console의 validEmail 메소드가 형식이 맞다면 true, 맞지 않다면 false를 반환하는데 이때 if문에서 !으로 부정문이 들어가는 것이 좀 걸립니다. 이정도는 상관없어서 그대로 유지해도 좋을지, 아니면  조금 더 생각해보는 게 좋을지 궁금합니다 !

2023-07-18 19:28 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/customer/JdbcCustomerRepository.java
> +        }
6d6f8e7fbeb27d1d5f998db70638a0e76678fa95 커밋 피드백 반영
- 해당 쿼리는 데이터가 있으면 데이터 전달 / 없으면 empty를 전달하는 즉, 예외를 발생시킬 필요가 없는 쿼리입니다.
- 따라서 결과 행의 길이가 0이거나 1초과시에 예외를 발생시키는 queryForObject 대신에 query 메소드를 통해 ResultSet을 list로 받습니다.
- Stream을 이용해 Optional으로 리턴되도록 가공합니다.
- 따라서 예외가 발생하지 않으므로 repository에서 try-catch문이 사라집니다.

2023-07-18 19:31 UTC, sujjangOvO commented on src/main/java/com/prgms/voucher/voucherproject/repository/voucher/JdbcVoucherRepository.java
> +    }
5fa22255d3d18f24b2144f66020fd1cb4dfb631b 커밋 피드백 반영
- 위와 똑같이 예외를 발생시키는 queryForObject 대신 query를 사용하여 예외를 발생시키지 않도록 합니다. 따라서 try-catch문이 사라집니다
- 추가로 enum에서의 추상 메소드를 사용해 swtich를 통해 voucherType을 분기하던 코드를 삭제할 수 있습니다
- rowMapper에도 똑같이 적용할 수 있습니다.

2023-07-20 02:58 UTC, Jo-GyuHyeon commented
하단에 보시면 Conflicting files 있어요. 
`Console`, `MemoryVoucherRepository` 두 파일 해결 해주세요.

2023-08-08 06:13 UTC, Jo-GyuHyeon approved these changes
쿼리 빌더를 구현 하셨군요.
고생하셨어요. 

코드 포맷이 다른 파일들이 있어서 통일 했으면 좋겠어요. 
상위 패키지에서 우측 마우스 클릭 하셔서 Reformat code 기능을 이용하면 하위 파일을이 전체 자동 정렬이 될거에요.

서비스 관련 테스트 코드 작성이 없어서 조금 아쉬움이 남는데 다음에는 테스트들도 작성 해주시면 좋을듯 해요.

지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-08 07:36 UTC, merged