[4기 - 문희조] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #829
Opened 2023-07-13 18:36 UTC by Hejow

## 🎨 그림 그리기 & 소개하기
<img width="997" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/81742959/d042655b-cd79-482e-a622-fa7b3be6f274">

## 🔪 작업 목록

### 🤷‍♂️ 미분류 
- [ ] 미작성한 테스트 코드 작성
- [ ] (마지막) 멘토님 승인하시면 심화 미션 😜

### 👤 유저
- [ ] 유저 생성 구현
- [ ] 유저 수정 구현
- [ ] 특정 유저 삭제 구현
- [ ] 전체 유저 조회 구현
- [ ] 특정 유저 조회 구현

### 🎟️ 바우처
- [ ] 바우처 생성 구현
- [ ] 바우처 수정 구현
- [ ] 특정 바우처 삭제 구현
- [ ] 전체 바우처 조회 구현
- [ ] 특정 바우처 조회 구현

## ✅ PR 포인트 & 궁금한 점 
현재 설계를 구현했습니다.
꼭 Controller와 Service가 필요없을 것 같아서
요구

2023-07-15 06:00 UTC, Hejow commented
문자열로 작성한 쿼리를 어떻게하면 최소한의 반복으로 작성할 수 있을까 고민하다가 빌더를 구현하였습니다.
굳이 이렇게까지 빌더를 구현할 필요는 없었지만 빌더 패턴을 연습하고 컴파일 시점의 안정성에 대해서 고민해보고자 했습니다.

빌더로 어떻게 컴파일 시점에서 쿼리의 안정성을 만들 수 있을까 또 고민했는데 좋은 아이디어가 떠오르지 않았습니다.
컴파일 시점의 안정성에 대한 멘토님들의 의견이 궁금합니다. JdbcTemplate를 사용하는한 가져가야할 trade-off일까요??

2023-07-16 04:02 UTC, Jo-GyuHyeon requested changes
안녕하세요 희조님 
간단하게 리뷰를 먼저 남겨 보았어요.
쿼리 빌더 구현 하셨는데, 관련 한 부분에서 더 세부적으로 나눠보면 어떨까요?

2023-07-16 06:26 UTC, Hejow commented on src/main/java/com/devcourse/global/util/Query.java
> +    public static class Builder {
이렇게 빌더의 종류를 나누면 자연스럽게 특정 빌더 다음에 빌더를 생성해야하니까 컴파일 시점 안전성을 챙길 수 있는군요???
제가 이해한게 맞을까요!?!?!?

2023-07-16 09:09 UTC, HyoungUkJJang reviewed
희조님 2주차 코드 잘 봤습니다 :)

전반적으로 잘 작성해주신 것 같아서 멘토님이 전달해주신 빌더에 관해서 저도 의견을 하나 남겼습니다 참고해주시면 좋을 것 같아요 ~

고생하셨습니다 👍

2023-07-16 09:09 UTC, HyoungUkJJang commented on src/test/java/com/devcourse/global/console/ParserTest.java
> +    @Nested
이너 클래스를 통해 테스트를 하시는 경우라면 각 클래스에도 DisplayName을 적어주시면 어떨까요?

2023-07-16 09:09 UTC, HyoungUkJJang commented on src/main/java/com/devcourse/global/util/Query.java
> +    public static class Builder {
오오 빌더를 만들어 주셨군요 ! 👍 멋쨍이

멘토님의 의견과 일치하는지 모르겠지만 해당 빌더에 sql에 모든 책임이 몰아져 있는 것 같아요
.where() 다음에 select, insertInto 모두 문법적으로 문제 없이 사용이 가능할 것 같은데 이런 것 까지 고려해서 한번 더 탄탄하게 만들어보시면 어떨까요?

2023-07-16 09:15 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/util/Query.java
> +    public static class Builder {
넵 맞습니다. 한번 해보시면 더 느낌이 많이 오실것 같아요.

2023-07-16 09:16 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/util/Query.java
> +    public static class Builder {
@HyoungUkJJang 저와 정확하게 일치하는것 같아요.
조금더 추상적으로 말씀드리고 스스로 생각하길 원하긴 했었습니다.

2023-07-16 09:26 UTC, Hejow commented on src/main/java/com/devcourse/global/util/Query.java
> +    public static class Builder {
[6a831be](https://github.com/prgrms-be-devcourse/springboot-basic/pull/829/commits/6a831bea695f210f5e3c2f03fe1e5d53e773a5ae)로 피드백 반영하였습니다!

말씀해주신거 보자마자 느낌이 빡와서 바로 구현했습니다.
이런게 컴파일 시점의 안정성이군요!!

다음으로 과연이 이 클래스들을 분리하는게 맞을까?에 대해서 고민해봤습니다.
제 생각에는 이 녀석들은 강하게 붙어있을 친구들이라 한 곳에 관리하는게 좋다고 생각은 합니다.
근데, 보기 어렵지 않을까? 라는 생각이 들어서 여쭤보고 싶습니다. 분리해서 관리하는 것에 대해서 어떻게 생각하시나요?

2023-07-16 09:26 UTC, Hejow commented on src/test/java/com/devcourse/global/console/ParserTest.java
> +    @Nested
바로 야무지게 피드백 반영해보겠습니다!!

2023-07-16 09:27 UTC, Hejow commented on src/main/java/com/devcourse/global/util/Query.java
> +    public static class Builder {
다행히도 멘토님 답글보고 후다닥 달려가서 구현해버렸습니다!
뭔가 보는 시야가 넓어지게된 것 같습니다 🥹 감사합니다!!

2023-07-16 09:27 UTC, Hejow commented on src/main/java/com/devcourse/global/util/Query.java
> +                query.append(column).append(EQUAL).append(PARAMETER).append(COMMA);
[6a831be](https://github.com/prgrms-be-devcourse/springboot-basic/pull/829/commits/6a831bea695f210f5e3c2f03fe1e5d53e773a5ae)로 피드백 반영하였습니다!

2023-07-16 16:09 UTC, Jo-GyuHyeon requested changes
쿼리 빌더에 대해 잘 접근 하셨지만 조금더 개선 해볼 수 있을것 같아요.
간단하게 리뷰 남겨 보았어요.

2023-07-16 16:09 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
> +                .build();
빌더를 세부적으로 더 나누길 기대 했던것 같아요. SelectBuilder 를 이용하면 Select sql 문을 만들수 있도록, UpdateBuilder 라면 Update sql 문을 만들어 주길 기대 했던것 같아요. 
저 작은 단위로 나뉘었을때 어떤 이점이 있을까요?

2023-07-16 16:09 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
> +        }
단순히 empty 를 전단하기 위해 try catch 구문을 사용 해야 할까요??

2023-07-17 05:34 UTC, Hejow commented on src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
> +                .build();
작은 단위로 나뉘었을 때 어떤 이점이 있을지 잘 생각나지 않습니다.. 🥹

저는 지금 구조가 충분히 괜찮다고 생각하는 이유는 다음과 같습니다.
1. `builder()`를 시작점으로 알맞는 SQL을 생성할 수 있도록 메서드를 지원한다.
2. 해당 메서드에서 맞는 builder를 체이닝함으로 잘못된 SQL이 생성되는 것을 컴파일 시점에 방지한다.

2023-07-17 05:44 UTC, Hejow commented on src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
> +        }
우선 `queryForObject()`을 내부적으로 타고 들어가보니 `query()`에서 `checked Exception`을 던지고 있길레 잡았습니다.
생각해보니 단순히 잡지말고 잘못된 값을 접근했다는 로그를 찍어주는게 좋을 것 같았습니다!

2023-07-17 05:47 UTC, Hejow commented on src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
> +                .build();
위에 질문에 대한 답인가 싶어서 더 5분 정도만 더 고민해봤습니다!
작은 단위로 나눈다. -> 작은 단위의 클래스로 분리할 수 있다. -> 각 클래스에 응집도가 높아져 관리가 더 수월해진다.
정도로 생각해보았습니다! 혜안 부탁드립니다!! 🥹

2023-07-17 09:51 UTC, Hejow commented on src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
> +        }
[2eb43ad](https://github.com/prgrms-be-devcourse/springboot-basic/pull/829/commits/2eb43adbb8863c15efd3f528bd3e23364841283e)로 피드백 반영했습니다!

내부적으로 확인해보니 `EmptyResultDataAccessException`을 던지는 곳은 따로 있는 것으로 확인했습니다!
그래서 `query()`를 사용하였고 자체적으로 if 문으로 단건이 조회가 안되었을 때 예외를 던질까 생각했다가
그냥 구현되어있는 `DataAccessUtils.singleResult()`를 사용하도록 구현하였습니다!

2023-07-17 20:17 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
> +        }
잘 반영하셨지만, Util 기능을 사용하지 않을수 있을것 같아요.
직접 로직을 구현 해보시면 어떨까요? 어렵지 않을것 같아요.

2023-07-18 01:07 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 남겼어요.
고생하셨어요.

2023-07-18 01:07 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/ApplicationController.java
> +        this.blackListRepository = blackListRepository;
설계 하셨던 의존성이랑 차이가 있는것 같아요.
Controller 에서 Repository 를 의존한다는건 레이어 아키텍쳐를 지키지 않는것 같아요.

2023-07-18 01:07 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +        Voucher voucher = new Voucher(request.discount(), request.expiredAt(), request.type());
서비스 로직에서 입력에 대한 검증을 해야 할지?? 고민을 해보시면 좋을것 같아요.

2023-07-18 01:07 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/global/util/Sql.java
> +        private static final String FROM = " FROM ";
nested class 가 아닌 별도의 root 레벨의 class 로 분리 해보시면 좋을것 같아요. 
(패키지 위치 네이밍도 고민해주세요)

2023-07-18 04:55 UTC, Hejow commented on src/main/java/com/devcourse/global/ApplicationController.java
> +        this.blackListRepository = blackListRepository;
헉 빼먹고 안넣은 부분이 있었습니다! 수정하겠습니다!

현재로는 서비스가 어떤 기능도 하지 않아서 과감하게 제거했습니다.
레이어 아키텍처에서 상위 계층이 하위 계층을 의존하면 된다고 생각했는데,
Controller에서 Repository를 중간 계층이 불필요해서 생략하고 의존하는 것이 레이어 아키텍쳐에 위반하는 것일까요??

2023-07-18 05:37 UTC, Hejow commented on src/test/java/com/devcourse/global/console/ParserTest.java
> +    @Nested
[5e856d1](https://github.com/prgrms-be-devcourse/springboot-basic/pull/829/commits/5e856d1642b61e538650761fa0b3c50ae1cf864c)로 피드백 잘 반영했습니다!!

2023-07-26 08:56 UTC, Hejow commented on src/main/java/com/devcourse/voucher/application/VoucherService.java
> +        Voucher voucher = new Voucher(request.discount(), request.expiredAt(), request.type());
[37be01f](https://github.com/prgrms-be-devcourse/springboot-basic/pull/829/commits/37be01f816cdfc6628c90ed9f67effc00553bc48)로 피드백 반영했습니다!

2023-07-26 08:58 UTC, Hejow commented on src/main/java/com/devcourse/global/ApplicationController.java
> +        this.blackListRepository = blackListRepository;
[e93bfed](https://github.com/prgrms-be-devcourse/springboot-basic/pull/829/commits/e93bfed48f6bfa0f3504766fe5a9182b2c47925f)로 피드백 반영했습니다!

2023-07-26 09:04 UTC, Hejow commented
쿼리 빌더 관련해서는 금일 중에 새롭게 작성해서 피드백 반영하겠습니다!

작업하다가 문득 생긴 궁금증이 있습니다.
"어떤 엔티티를 생성하는데 필요한 값은 어디서 검증해야하는가?"입니다.

제가 생각했을 때 다음과 같은 경우가 존재할 것 같습니다.
1. 생성하기 전에 미리 검증을 끝내놓는다. (Service 아니면 다른 곳에서)
2. new 키워드로 생성될 때 내부적으로 검증한다.
3. 그래도 두번 검증한다 (?)

3번은 굳이 두 번할 필요가 없을 것 같아서 아니라고 생각하고,
1번과 2번 모두 각각 장단점이 있을 것 같은데 제 생각은 또 다음과 같습니다.

1번 
- 장점 : 서비스에서 검증을 한다고 가정하면 비슷한 값에 대해서 또 검증할 수 있다. (재사용)
- 단점 : 서비스에 로직이 과도하게 많아질 수 있다 (분리함으로 해결가능)

2번
- 장점 : 엔티티 자체의 로직으로 챙겨가서 조금 더 객체지향적이다.
- 단점 : 여러 로직을 타고 실제로 검증하려고 봤더니 안되면 리소스 적으로 비효율적이다.

라고 생각이 들었는데 멘토님들의 생각이 궁금합니다!!

2023-08-07 14:13 UTC, Jo-GyuHyeon approved these changes
쿼리 빌더를 구현 하셨군요.
고생하셨어요.
가끔은 너무 과하지 않을지 고민도 하시면서 공학적으로 가치가 있을지도 생각해보시면 좋을것 같아요.
조금더 JDBC 와 친해졌기를 바랄게요.
지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-07 15:53 UTC, merged