[4기 - 신범철] SpringBoot Part2 Weekly Mission 두 번째 PR 제출합니다
prgrms-be-devcourse/springboot-basic pull request #838
Opened 2023-07-15 11:13 UTC by beombu

## ✅ 그림 그리기 및 소개하기
#### 객체의 행동과 상태
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/84673536/8a091d8c-9ed5-447b-940d-6675f86ac3ec)

#### 클래스 다이어그램(역할과 책임)
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/84673536/41a93798-122b-47fb-a9e8-f1ed759e8446)

## ✅ 요구 사항
**(기본)** **바우처 관리 애플리케이션**

- [ ]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [ ]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [ ]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## ✅ 작업 순서 목록
- [X] 2주차 설계도 작성
- [ ] MemoryVoucher findById 기능 구현
- [ ] MemoryVoucher update 기능 구현
- [ ] MemoryVoucher delete 기능 구현
- [ ] MemoryVoucher 테스트 코드 구현
- [ ] JDBC 설정 & DB 설정
- [ ] JdbcVoucher create 기능 구현
- [ ] JdbcVoucher findById 기능 구현
- [ ] JdbcVoucher findAll 기능 구현
- [ ] JdbcVoucher update 기능 구현
- [ ] JdbcVoucher delete 기능 구현
- [ ] jdbcVoucher 테스트 코드 구현
- [ ] Customer 설계 추가
- [ ] 중간 점검(customer 구현 전 멘토님 승인)

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +    }
**[ 이전 코드 리뷰 롤백 ]**

```java
    public VoucherResponseDto findById(UUID voucherId) {
        Voucher voucher = validateExist(voucherRepository.findById(voucherId));
        return VoucherResponseDto.toDto(voucher.getVoucherId(), voucher.getVoucherType(), voucher.getAmount());
    }

    private Voucher validateExist(Voucher voucher) {
        if (voucher == null) {
            throw new NoSuchElementException(NOT_FOUND_VOUCHER);
        }

        return voucher;
    }
```
규 Say : 
해당 메서드가 별도로 존재해야 할지 의문인것 같아요.
서비스의 로직인지, 혹은 불필요하게 감싸져있지 않을지 고민 해보시면 좋을것 같아요.

범 Answer :
바우처의 Id 조회를 실패한 경우의 예외 책임을 Repository가 가져야 한다고 생각합니다. 감사합니다🙇‍♂️🙇‍♂️
그리고 궁금한 점이 하나 있습니다. 일반적으로 findById을 사용하는 경우에 Option<Voucher>를 사용합니다. 이 이유가 프로그램을 끝내는 것이 아닌 실패라는 메세지를 던져주기 위함인가요?

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +        };
**[ 이전 코드 리뷰 롤백 ]**

규 Say :
update 를 하기 위해 Voucher 인스턴스화가 필요 했을까요???

범 Answer : 해결하지 못하였습니다... 이유는 VoucherType을 바꾸는 경우에 해당 Amount를 검증하는 로직이 다르기 때문에 인스턴스화를 필수적이였다고 생각합니다. 그래서 Voucher 자체를 Class로 변경하는 시도를 하였으나 Amount를 검증하는 로직을 나누는 것이 어려웠습니다.🥲

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/MemoryVoucherRepository.java
> +    }
**[ 이전 코드 리뷰 롤백 ]**
```java
//이전 코드    
public Voucher update(Voucher voucher) {
        if (findById(voucher.getVoucherId()) == null) {
            return null;
        }

        storage.put(voucher.getVoucherId(), voucher);

        return voucher;
```
규 Say : 
Map 의 putIfAbsent() 를 활용 해보는건 어떨까요? 아래에 링크 첨부 해보아요.

[https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#putIfAbsent-K-V-](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#putIfAbsent-K-V-)

범 Answer :
감사합니다❗❗❗❗수정 완료했습니다.
Map.putIfAbsent : Key 값이 존재하는 경우 Map의 Value의 값을 반환하고, Key값이 존재하지 않는 경우 Key와 Value를 Map에 저장하고 Null을 반환합니다.
잊지 않고 잘 사용하겠습니다🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +    private static final String DELETE_QUERY = "DELETE FROM voucher WHERE voucher_id = UUID_TO_BIN(:voucher_id)";
**[ 이전 코드 리뷰 롤백 ]**
```java
    //이전 코드
    private static final String SAVE_QUERY = "INSERT INTO voucher(voucher_id, voucher_type, amount) VALUES(UUID_TO_BIN(:voucher_id), :voucher_type, :amount)";
    private static final String FAILED_VOUCHER_SAVE_QUERY_MESSAGE = "바우처 저장 쿼리를 실패 하였습니다.";
    private static final String FIND_BY_ID_QUERY = "SELECT * FROM voucher WHERE voucher_id = UUID_TO_BIN(:voucher_id)";
    private static final String FIND_ALL_QUERY = "SELECT * FROM voucher";
    private static final String UPDATE_QUERY = "UPDATE voucher SET voucher_type = :voucher_type, amount = :amount WHERE voucher_id = UUID_TO_BIN(:voucher_id)";
    private static final String VOUCHER_ID_LOOKUP_FAILED_MESSAGE = "조회된 바우처 ID가 없습니다.";
    private static final String DELETE_QUERY = "DELETE FROM voucher WHERE voucher_id = UUID_TO_BIN(:voucher_id)";
```
규 Say : 
쿼리문을 따로 상수로 관리 하니 단일 메서드에서 파악하기가 어려움이 있는것 같아요.
예외 메시지를 예외 클래스로 따로 관리 해보시면 어떨까요?

범 Answer : 
감사합니다~~!!
바우처와 연관된 모든 예외 메세지를 ExceptionMessage Enum으로 관리하도록 변경하였습니다🙇‍♂️🙇‍♂️

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +        }
**[ 이전 코드 리뷰 롤백 ]**
```java
        //이전 코드
        if (isSaveFailed(savedVoucherRow)) {
            throw new RuntimeException(FAILED_VOUCHER_SAVE_QUERY_MESSAGE);
        }

        return voucher;
    }

    private boolean isSaveFailed(int voucherRow) {
        return voucherRow != SUCCESS_SAVE_QUERY;
    }
```
규 Say : private 메서드이고, 상태만 체크를 한다면 변수로 두는 것은 어떨까요?? **재사용성과, 분리의 의미**를 찾기는 힘든것 같아요.

범 Answer : 감사합니다! 메서드를 삭제하였습니다!

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +        };
**[ 이전 코드 리뷰 롤백 ]**

규 Say : 매번 인스턴스화 할때 분기 처리가 발생하는 것 같아요.
분기처리를 한곳으로 모을수 있는 방법이 있을까요?

범 Answer :

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +    private final RowMapper<Voucher> voucherRowMapper = (resultSet, i) -> {
**[ 이전 코드 리뷰 롤백 ]**

규 Say : 
해당 메서드에 static 키워드를 사용하진 이유가 무엇일까요?

범 Answer : 
생각없이 코드를 구현하였습니다. 죄송합니다!
삭제하였습니다!🙇‍♂️🙇‍♂️

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +        }
**[ 이전 코드 리뷰 롤백 ]**
```java
        //이전 코드
        if (isNotFoundVoucher(updatedVoucherRow)) {
            throw new RuntimeException(VOUCHER_ID_LOOKUP_FAILED_MESSAGE);
        }
```

규 Say : 
존재 여부를 체크 해야 할까요???
존재 하지 않는다면 예외가 발생해야 할까요????
범철님의 의견이 궁금해요.

범 Answer : 
update를 사용하는 객체는 가게 사장이 될 수 있을 것 같습니다. 가게 사장이 업데이트를 할 경우 존재하지 않는다고 예외처리를 할 것 같지 않습니다. 바로 추가해줄 것 같습니다❗❗

2023-07-15 17:55 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +        }
**[ 이전 코드 리뷰 롤백 ]**
```java
        //이전 코드
        if (isNotFoundVoucher(deletedVoucherRow)) {
            throw new RuntimeException(VOUCHER_ID_LOOKUP_FAILED_MESSAGE);
        }
```

규 Say : 
존재 여부를 체크 해야 할까요???
존재 하지 않는다면 예외가 발생해야 할까요????
범철님의 의견이 궁금해요.

범 Answer : 
바우처를 삭제하는 객체는 소비자일 것 같습니다. 소비자가 자신이 소지한 바우처를 삭제할 경우에 없다면 예외 처리가 발생해야 한다고 생각합니다❗❗

2023-07-15 21:56 UTC, beombu commented
이전 PR에서 리뷰 달아주신 내용 백업과 해당 리뷰에 변경 사항을 작성했습니다~~!!

- 추가 구현사항
  - jdbcVoucherRepository의 유닛 테스트 코드 구현
  - Customer 설계 추가
  - JdbcCustomer CRUD 구현
    - create -> 닉네임을 통한 중복 처리
    - findById
    - findByNickname
    - findAll
    - update
    - delete

부족하지만 열심히 노력하겠습니다🙇‍♂️🙇‍♂️🙇‍♂️

2023-07-16 22:02 UTC, beombu commented
이전 피드백에서 올려주신 내용을 추가 수정하였습니다!!

- 변경 사항
  - 예외 처리를 위해 Try, Catch문 사용
 
### 궁금한 점
- 예외 처리를 위해 Try, Catch를 사용했는데 너무 남용했다는 느낌이 들었습니다. 더 좋은 방식이 있었는지 궁금합니다!
- FixedAmountVoucher와 같은 엔티티에 값을 검증하고 예외를 던지는 로직은 어떻게 예외 처리를 해야할 지 모르겠습니다..

2023-07-17 00:04 UTC, beombu commented
이전 피드백에서 올려주신 내용을 추가 수정하였습니다!!

- 변경 사항
  - RumtimeException들 커스텀 예외 로직으로 변환
  - delete 리턴 값 void로 변경

2023-07-17 20:54 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +    }
예외를 처리 할지, 다른 로직을 처리 해야 할지는 비지니스 로직을 담당하는 서비스 계층에서 결정할 문제라고 봐요.
정책에 따라 null 이더라도 예외가 발생하지 않을수도 있다고 생각해요.

2023-07-17 20:58 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +        };
Update 쿼리에 있어서 Data Layer, Repository 에서 엔티티를 넘겨주셔도 좋지만, 필요한 필드 정보만 넘겨주셔도 좋을것 같아요.
만약 정확한 정보를 (리턴) 제공하고 싶다면 다시 쿼리를 날리는 것도 좋고, 불필요하다고 보시면 Update 후에 객체 생성 해주셔도 좋을것 같아요.

2023-07-17 20:59 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/MemoryVoucherRepository.java
> +    }
삼항 연산자로 잘 활용 해주셨네요. 👍

2023-07-17 21:02 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +        }
범철님의 의견에는 저도 동의 해요. 하지만 그것을 판단하는 위치가 Service 레이어 계층이면 더 좋겠다는 생각이 들어요.
Data 레이어 계층에서만 보았을때, 쿼리 실행은 성공적이라고 판단해요. 다만 where 조건 문에 맞는 데이터가 없을뿐이죠.
그런건 비지니즈 로직적으로 체크 하는 부분이기에 Service 레이어에서 체크 해주시는게 더 바람 직하다고 생각이 들어요.

2023-07-17 21:06 UTC, Jo-GyuHyeon requested changes
간단하게 쿼리에 대한 리뷰를 남겨 보았어요.

2023-07-17 21:06 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/customer/constant/CustomerQuery.java
> +    DELETE("DELETE FROM customer WHERE customer_id = UUID_TO_BIN(:customer_id)");
SQL 문을 상수로 빼니 해당 메서드에서 어떤 행위가 일어나는지 잘 파악이 안되는것 같아요.
상수로 빼는것 만큼 이점이 많을지 고민 해보시면 좋을것 같아요.
2단계로 나눠서 리뷰드리고 싶은데 지금은 1단계로 메서드 내로 쿼리 문은 옮겨 보는 것은 어떨까요?
(2단계로써 쿼리 빌더를 만들어 보시면 좋을것 같아요.)

2023-07-18 19:41 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +        };
[ed46d71](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/ed46d71f36525758e71a539db670c4d0475b5956) 피드백 반영
- 감사합니다!! 수정하였습니다.

2023-07-18 19:42 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +        };
[0102e95](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/0102e95847f967013943f4c29e64fefe790dad10) 피드백 반영
- 라이브 코드 리뷰
- Enum에서 추상 메서드로 인스턴스화를 진행하였습니다. 알려주셔서 감사합니다🪄🪄🪄

2023-07-18 19:42 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +        }
[48089c2](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/48089c2208b31091fd1b22d746b44af482221e21) 피드백 반영
- 감사합니다. Repository Layer에서 처리했던 로직을 Service Layer로 위임해주었습니다🙇‍♂️🙇‍♂️

2023-07-18 19:42 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/constant/CustomerQuery.java
> +    DELETE("DELETE FROM customer WHERE customer_id = UUID_TO_BIN(:customer_id)");
[844d5db](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/844d5db3aeb43b6c258e26212dce5d9df8e7d83b) 피드백 반영
- 1단계를 수행하였습니다.
- 2단계 진행 중입니다.

2023-07-18 19:46 UTC, beombu commented
피드백 올려주신 내용을 수정하였습니다!

- 추가 구현사항
  - X
- 특이사항
  - 쿼리 빌더를 아직 구현 중에 있습니다.

2023-07-19 05:37 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/customer/constant/CustomerQuery.java
> +    DELETE("DELETE FROM customer WHERE customer_id = UUID_TO_BIN(:customer_id)");
1단계는 상수를 사용하라는 말이 아니라 메서드내에 하드코딩된 쿼리문으로 작성하는 것을 의미했었어요.

2023-07-19 06:20 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/constant/CustomerQuery.java
> +    DELETE("DELETE FROM customer WHERE customer_id = UUID_TO_BIN(:customer_id)");
[aa169e6](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/aa169e6ea4cf810462358dd3aa0c6ea2e715a920) 피드백 반영
- 아하 잘못 이해하였습니다. 메서드 내로 하드코딩하였습니다!

2023-07-19 06:42 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +    private static final String CUSTOMER_ID_MESSAGE = "소비자 Id를 입력하세요.\n";
[62dc5fa](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/62dc5fad171bb73d788c1109480840c9240fd4a9) 피드백 반영
- 따로 클래스를 만들어 메시지들을 관리하였습니다.
- 근데 해당 메시지들을 다른 곳에서 사용하지 않는데 굳이 따로 관리 해야 하는 의문이 있습니다!! 아니면 제가 멘토님이 말씀하시는 관리법이 아닌가도 궁금합니다.
- 저는 따로 관리하는 이유를 가독성을 위해서 만들었다고 생각하였습니다.

2023-07-19 06:48 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        voucherConsole.printVoucher(PRINT_VOUCHER_INFO_MESSAGE, voucherResponseDto.getVoucherId(), voucherResponseDto.getVoucherType(), voucherResponseDto.getAmount());
[c6b80d1](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/c6b80d160312503cfc3de5ad1cee2b7b16c3fb1c) 피드백 반영

- 맞습니다! 폴더에서도 model/dto로 관리하기 때문에 삭제하는 것이 더 좋을 것 같습니다.✅

2023-07-19 08:19 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/constant/CustomerQuery.java
> +    DELETE("DELETE FROM customer WHERE customer_id = UUID_TO_BIN(:customer_id)");
[dc99141](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/dc99141500ccee08227b4d4458951d636b9177ec) 피드백 반영
- 2단계 쿼리 빌더를 구현하였습니다!

2023-07-19 08:24 UTC, beombu commented
2주차 추가 PR 리뷰 수정 및 쿼리 빌더 완료하였습니다.
- 추가 구현사항
  - X
- 특이사항
  - Customer는 아직 쿼리 빌더를 적용하지 않았습니다. 피드백 후에 수정하고 싶습니다.

2023-07-19 16:10 UTC, HyoungUkJJang requested changes
안녕하세요 범철님 코드 반영하시느라 고생하셨습니다 :)

먼저 제 작은 의견을 조금 남겨 봤는데 참고가 되시면 좋을 것 같습니다 ~ 몇몇개 중복되는 것들은 따로 남기지 않은 것도 있으니 잘 수정해 주시면 좋을 것 같습니다 
추가적인 의견이 있으시다면 편하게 말씀해주세요 ! 고생하셨어요 ☺️ 👍🏻

2023-07-19 16:10 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
> +                .collect(Collectors.toUnmodifiableList());
개인 취향인 것 같지만 stream()의 연산 시작부터 라인 바이 라인으로 적용하는건 어떻게 생각하시나요?
```suggestion
        return customerRepository.findAll().stream()
                .map(v -> new CustomerResponse(v.getCustomerId(), v.getNickname()))
                .collect(Collectors.toUnmodifiableList());
```

2023-07-19 16:10 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
> +    }
클린코드에 내려가기 규칙이 있습니다. 어떤 의미인지 아래의 글을 한번 참조해 보시면 좋을 것 같습니다.
[클린코드 3장 내려가기 규칙](https://medium.com/naver-cloud-platform/%EB%84%A4%EC%9D%B4%EB%B2%84%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-%EA%B0%9C%EB%B0%9C%EC%9E%90-%EC%8A%A4%ED%86%A0%EB%A6%AC-%EC%A2%8B%EC%9D%80-%EC%BD%94%EB%93%9C%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C-%ED%81%B4%EB%A6%B0%EC%BD%94%EB%93%9C-%EC%9D%B4%EC%95%BC%EA%B8%B0-c7811f73a46b)

2023-07-19 16:10 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/util/Query.java
> +public class Query {
오호 쿼리 빌더를 고민해서 만들어 주셨군요 좋습니다 ! 👍🏻
한가지 아쉬운 점은 현재 쿼리는 데이터 저장, 수정, 삭제 등의 작업이 한 곳에 몰려 있어서 sql 문법 상으로는 오류이지만 컴파일 시점에insert 다음에 where나 다른 빌더 메서드를 추가해도 정상으로 판단하고 동작할 것 같아요 조금 더 분리하고 탄탄하게 만들어보는건 어떻게 생각하시나요?

2023-07-19 16:10 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/voucher/constant/VoucherCommand.java
> +    DELETE;
Enum 컨벤션 리뷰를 참고해주세요 ~

2023-07-19 16:10 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/customer/repository/JdbcCustomerRepository.java
> +import java.util.*;
아직 import 설정이 안되어 있으신 것 같네요 :) 아래 글을 참고하구 한번 적용해 보시면 좋을 것 같습니다 ~
[임포트 와일드카드 정리하기](https://velog.io/@eora21/Intellij%EC%97%90%EC%84%9C-%EC%99%80%EC%9D%BC%EB%93%9C%EC%B9%B4%EB%93%9C-%EC%9E%84%ED%8F%AC%ED%8A%B8-%EC%84%A4%EC%A0%95-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0)

2023-07-20 18:26 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        voucherConsole.printVoucher(PRINT_VOUCHER_INFO, voucherResponse.getVoucherId(), voucherResponse.getVoucherType(), voucherResponse.getAmount());
[a572baa](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/a572baa5e76b169db1148365d4209f4f07d02597) 피드백 반영

- 중복으로 발생한 로직을 하나의 메서드로 만들어주어서 매개변수가 단순해져 코드의 가독성이 좋아졌다고 생각합니다.
- 코드를 볼 때 다른 클래스로 찾아가서 보는 것이 아닌 해당 클래스에서 볼 수 있다는 점이 좋았습니다. 감사합니다!🙇‍♂️🙇‍♂️
- 근데 코드가 한 줄이라는 점에서 만들어야 할까라는 의문이 있었습니다 멘토님의 의견이 궁금합니다!

2023-07-20 18:26 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/exception/CustomerExceptionMessage.java
> +    private String message;
[0a71621](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/0a716218cf851815d07f52ad7898020392cfff1e) 피드백 수정

헉,, 감사합니다!!

2023-07-20 18:26 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/exception/CustomerIdNotFoundException.java
> +}
[805095a](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/805095ab44437c53f64e3bfcede6b16ec44d8e4f) 피드백 반영
- 하나의 Exception으로 만들고 Enum에서 예외 종류(상태코드)를 주었습니다.
- 예외 종류를 Exception으로 전달하는 과정에서 막혔습니다.
- 어떻게 전달하는지 모르겠습니다.. 제가 한 방법이 잘못된 것인지도 궁금합니다!!!

2023-07-20 18:27 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/model/dto/CustomerResponse.java
> +    }
ModelMapper와 같은 범용적인 toDto를 구현하는 것으로 이해했는데 맞을까요?
위 내용을 말씀하신 거라고 생각하는데.. 구현하지 못했습니다..

2023-07-20 18:27 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/model/entity/Customer.java
> +    private final UUID customerId;
[87c3df2](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/87c3df23c6179d8d19db463428f758c7ff6aee45) 피드백 반영
- 맞습니다!! Customer 클래스이기 때문에 id는 customer를 가리킬 것 같습니다!
- 코드 단축과 네이밍에 신경쓰겠습니다 감사합니다🙇‍♂️🙇‍♂️🙇‍♂️

2023-07-20 18:28 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
> +        Customer customer = foundCustomer.orElseThrow(() -> new CustomerNicknameNotFoundException(CUSTOMER_NICKNAME_LOOKUP_FAILED));
[76b0b45](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/76b0b451867335d75676040b1318913f4458eaa9) 피드백 적용
- 앗,,, 올려주신 자료에 있던 내용인데 구현하지 못해서 죄송합니다ㅠㅠㅠ
- 다음부터는 절때적으로 사용하겠습니다!

2023-07-20 18:28 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
> +                .collect(Collectors.toUnmodifiableList());
[6007d96](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/6007d96a3b30f10e586cd0da5bf40523ee744a47) 피드백 적용
- 감사합니다! 개행처리를 지움으로써 코드 라인을 줄일 수 있었습니다!!🪄🪄

2023-07-20 18:28 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
> +    }
[76b0b45](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/76b0b451867335d75676040b1318913f4458eaa9) 피드백 적용
- 감사합니다~~ 추상화가 단계가 섞이지 않도록 주의하며 구현하겠습니다!!!!

2023-07-20 18:29 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/repository/JdbcCustomerRepository.java
> +import java.util.*;
[c95051a](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/c95051a56c2a070c98f7805992c5013d14cf32e9) 피드백 반영
- 헉,,, 그 동안 보일 때마다 풀어줬었는데,,, 감사합니다!!!!

2023-07-21 13:27 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/constant/VoucherCommand.java
> +    DELETE;
[a080712](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/a0807125f3585d8d3e3af40a6b7c2340e6059cd9) 피드백 수정

- 해당 방법이 Enum를 추가할 때 편리한 것 같습니다!
- Enum를 사용할 때 컨벤션처럼 준수하여 구현하겠습니다~~👊👊

2023-07-22 05:30 UTC, Jo-GyuHyeon requested changes
간단히 리뷰를 하였어요. 잘못 구현된 부분이 있어서 확인해주시면 좋을것 같아요.
쿼리 빌더는 형욱님이 말씀 해주신 https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/files#r1268297316 부분을 참고 해주시면 좋을것 같아요.

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/constant/VoucherType.java
> +        }
update 가 아니라 생성 아닌가요???? 아래도 동일 해요.

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +
쿼리 빌더를 사용하신다면 Repository 에서 해당 상수를 관리 하지 않아도 될것 같아요.

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +                .build();
실제 Update 쿼리 문과 비슷하게 표현 하면 더 좋을것 같아요.

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +                .where(VOUCHER_ID, VOUCHER_ID)
Where 구문이 가독성이 어떠하신가요?
where 은 where 타입을 사용해보시면 어떨까요?

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/MemoryVoucherRepository.java
> +        return Optional.of(voucher);
Optional 의 ofnullable() 을 사용하면 간결한 코드를 사용할 수 있을것 같아요.

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
>      }
생성자를 사용하지 않는 이유는 무엇인가요?

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +                .orElseGet(() -> voucherRepository.save(type.updateVoucher(id, amount)));
update 기능이 아니라 upsert 기능을 구현 하신듯해요.

2023-07-22 05:30 UTC, Jo-GyuHyeon commented on src/main/java/org/prgrms/kdtspringdemo/util/Query.java
> +        public <T>InsertBuilder values(T ...values) {
제네릭은 지금은 불필요 한것 같아요.

2023-07-23 07:36 UTC, HyoungUkJJang reviewed
멘토님이 먼저 리뷰를 잘 남겨 주셨네요 ! 쿼리 빌더를 조금 더 수정해보시면 좋을 것 같습니다 :) 
고생하셨습니다 범철님 ~

2023-07-23 07:36 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/customer/model/dto/CustomerResponse.java
> +    }
@beombu 

toDto or 생성자 둘 중 하나만 쓰도록 해도 될 것 같다는 뜻이였어요 :) toDto만 사용하는 목적이라면 생성자를 public으로 열어두지 않아도 될 것 같아서요 ~

2023-07-23 07:36 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/view/console/Console.java
> +        validateVoucherId(userVoucherId);
목적에 따라서 개행처리를 해주시면 좋을 것 같아요 ! (개인취향~)
```suggestion
        printMessage(message.getText());
        
        String userVoucherId = scanner.nextLine();
        validateVoucherId(userVoucherId);
```

2023-07-23 07:36 UTC, HyoungUkJJang commented on src/main/java/org/prgrms/kdtspringdemo/util/Query.java
> +public class Query {
Inner 클래스 말고 별도의 클래스로 분리해보면 어떨까요 ~?

2023-07-24 04:33 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
> +        voucherConsole.printCustomer(PRINT_CUSTOMER_INFO, customerResponse.getCustomerId(), customerResponse.getNickname());
[a572baa](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/a572baa5e76b169db1148365d4209f4f07d02597) 피드백 반영
감사합니다!

2023-07-24 05:19 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/customer/model/dto/CustomerResponse.java
> +    }
아하 이해하였습니다!!
두 가지 방법으로 해결할 수 있다고 생각했습니다.
1. 생성자를 public으로 두고 toDto()를 삭제
2. 생성자를 private로 두고 toDto() 사용

두 가지 방법 중 저는 전자가 더 옳다고 생각하였습니다. 이유로는 toDto는 정적으로 선언되어 있고 그 안에서 생성자를 통해 객체를 생성합니다. 이는 자원을 많이 사용하는 작업이라고 생각하였습니다.
저는 후자는 네이밍으로 역할이 명확해진다 정도의 이점밖에 없다고 생각했는데 어떤 이점이 있는지도 궁금합니다!!

2023-07-24 06:48 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/view/console/Console.java
> +        validateVoucherId(userVoucherId);
- [343dbe8](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/343dbe849ebf92cf5501c159082bc1a95bf11eca) 피드백 반영

콘솔에서도 input과 output이라는 목적으로 나눌 수 있네요!!
목적을 세분화하도록 노력하겠습니다!! 감사합니다~~!!

2023-07-24 06:49 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
> +                .orElseGet(() -> voucherRepository.save(type.updateVoucher(id, amount)));
- [87477b6](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/87477b6ff3600acaa43447aece049382c73b6ebb) 피드백 반영

맞습니다..!!
바우처가 있다면 수정하고 없다면 새로 만들도록 구현하였습니다!
네이밍을 수정하였습니다.

2023-07-24 06:49 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
>      }
- [62d6161](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/62d6161ece1e6b3eaeadbf7908336d63934b0b62) 피드백 반영

이전에 매개변수로 Voucher를 받아왔다 수정하였는데 생성자와 동일하기에 삭제했었어야 했는데 매핑 기능을 명시하기 위해서 삭제하지 않았던 것 같습니다.
toDto 내부에서 생성자를 사용하는데 굳이 정적으로 만들어서 사용할 필요가 없다고 생각해서 삭제하였습니다❗❗

2023-07-24 06:49 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/MemoryVoucherRepository.java
> +        return Optional.of(voucher);
[2f24570](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/2f245706311d2c5f50f40d8b6559f4a8d62cefb0) 피드백 반영

- 감사합니다! 코드를 단축할 수 있었습니다..!!! 잊지 않고 사용하겠습니다!!

2023-07-24 06:51 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/constant/VoucherType.java
> +        }
[ef2b7ee](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/ef2b7ee0310b42145fff5d17e6a243b9857fd3b9) 피드백 반영

- 맞습니다. 새로운 바우처를 생성합니다. 네이밍을 변경하고 Equals로 id 동등성을 보장해주었습니다🙇‍♂️🙇‍♂️

2023-07-24 17:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +
[f268429](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/f26842923ec08275666d469c495ee5f5ee6a3988) 피드백 수정

- 맞습니다!
- 쿼리 빌더에서 상수를 관리하도록 하였습니다.

2023-07-24 17:53 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +                .build();
[f268429](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/f26842923ec08275666d469c495ee5f5ee6a3988) 피드백 수정

- 최대한 노력해서 수정하였습니다!!

2023-07-24 17:54 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
> +                .where(VOUCHER_ID, VOUCHER_ID)
[f268429](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/f26842923ec08275666d469c495ee5f5ee6a3988) 피드백 수정

- where 타입을 분리했습니다!!

2023-07-24 17:54 UTC, beombu commented on src/main/java/org/prgrms/kdtspringdemo/util/Query.java
> +        public <T>InsertBuilder values(T ...values) {
[f268429](https://github.com/prgrms-be-devcourse/springboot-basic/pull/838/commits/f26842923ec08275666d469c495ee5f5ee6a3988) 피드백 수정

- 제네릭을 삭제했습니다.
- value의 타입을 받을 때 유연하게 받아야겠다고 생각했는데 실제로 쿼리에서 값을 받지 않기 때문에 삭제하였습니다.

2023-07-26 04:52 UTC, beombu commented
소중한 리뷰 감사합니다!!
PR 리뷰 수정 및 쿼리 빌더 수정 완료하였습니다!

- 추가 구현사항
  - X

2023-08-07 14:20 UTC, Jo-GyuHyeon approved these changes
지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-07 14:37 UTC, merged