[4기 - 민승현] SpringBoot Part2 Weekly Mission 첫 번째 PR 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #840
Opened 2023-07-15 18:26 UTC by seongHyun-Min

## 📌 과제 설명 2주차
###  바우처 관리 Application
- week 2

  ```bash
  === Voucher Program ===
  Type **exit** to exit the program.
  Type **create** to create a new voucher.
  Type **list** to list all vouchers.

  === Service Program ===
  Type 'create' to Create a customer
  Type 'assign' to Delete a customer
  Type 'list' to View all customers
  Type 'findOne' to Find customers by type
  Type 'update' to Find customers by type
  Type 'delete' to Delete a customer
  Type 'exit' to Find customers by type

## 👩‍💻 요구 사항과 구현 내용
## 도메인
### Voucher (JDBC MYSQL 연동)

- [x] 바우처 생성/저장 기능 구현
- [x]  바우처 조회 기능 구현
     - [x] 전체 조회
   
![img.png](img.png)

### Customer (JDBC MYSQL 연동)

- [x]  고객 생성/저장 기능 구현
- [x]  고객에게 바우처 할당 기능 구현
- [x]  고객 조회 기능 구현
     - [x]  전체 고객 조회
     - 타입별 고객 조회 (고객 ID, 고객 이름, 보유한 바우처 ID)
- [x]  고객 이름 수정 기능 구현
- [x] 고객 삭제 기능 구현
     - [x] ID로 단건 삭제 가능
     - [x] 전체 삭제 가능
  
![img_1.png](img_1.png)

## ✅ PR 포인트 & 궁금한 점
- JDBC를 사용해서 CRUD를 구현하는데 익숙하지 않지만 최대한 노력하였습니다.
- 바우처와 고객이 적절하게 매핑이 되었는지 정확하게 구현했는지 궁굼합니다.
- MYSQL에서 UUID 타입을 지원하지 않아 VARCHAR 타입으로 테이블을 생성하여
- UUID인 id값을 String.valueOf를 통해 데이터베이스에 저장하였는데 이로인한 문제가 생기는지 궁굼합니다.
- 전체적으로 코드의 일관성과 가독성이 괜찮은지 여쭤보고 싶습니다.

2023-07-16 19:41 UTC, JoosungKwon reviewed
승현님 과제하시느라 고생하셨습니다!!
리뷰 남겼으니 참고해주세요~ 클론 프로젝트와 3주차 과제 모두 화이팅입니다~!!

질문에 답변하자면
> 바우처와 고객이 적절하게 매핑이 되었는지 정확하게 구현했는지 궁굼합니다.
- 매핑이라면 ERD 설계를 이야기 하시는 건가요? 저는 괜찮다고 생각합니다. 다만, 좀 더  여러 방안을 고려해볼 수는 있을 것 같네요. 2주차에 나오는 지갑(Wallet)처럼 Voucher하고 Customer를 매핑하는 테이블을 중간에 두는 방법도 있을 것 같아요. 그리고 Customer가 삭제 되었을때 연결된 Voucher는 어떻게 할 것인지도 고려해야 할 요소일 것 같네요!
 
> MYSQL에서 UUID 타입을 지원하지 않아 VARCHAR 타입으로 테이블을 생성하여 UUID인 id값을 String.valueOf를 통해 데이터베이스에 저장하였는데 이로인한 문제가 생기는지 궁굼합니다.
- 일단, MySQL도 UUID 타입을 사용하는 방법은 있습니다. 사용하기 좀 복잡해서 그렇지 불가능하지는 않는 것으로 알고 있습니다. 저는 편의성을 고려하면 VARCHAR로 관리해도 괜찮다고 생각합니다. 문제가 있다고 하면 비효율적일 수 있고, 타입이 의미를 정확하게 나타내지 못한다는 점이 있을 것 같네요. 

> 전체적으로 코드의 일관성과 가독성이 괜찮은지 여쭤보고 싶습니다.
- 중간중간에 정리가 안되어 있는 부분이 많다는 느낌이 있긴 했습니다. 제출 전에 전반적으로 확인하는 습관을 가져보면 좋을 것 같네요! 이외의 부분은 리뷰에 남겼으니 확인해주세요

2023-07-16 19:41 UTC, JoosungKwon commented on src/main/java/org/promgrammers/voucher/util/CustomerUtils.java
> +public class CustomerUtils {
보다 명확한 이름이면 좋을 것 같습니다! `Repository`에서만 사용된다면 따로 `Util` 클래스로 둘 필요는 없다고 생각합니다.

2023-07-16 19:41 UTC, JoosungKwon commented on src/main/java/org/promgrammers/voucher/util/VoucherUtils.java
> +
`Util` 클래스라면 `private` 생성자를 두어 의도치 않은 인스턴스화를 방지하는 것이 좋습니다.

2023-07-16 19:41 UTC, JoosungKwon commented on src/main/java/org/promgrammers/voucher/view/CustomerAction.java
> +        }
Enum 값이 늘어난다면 [최적화](https://pjh3749.tistory.com/279)를 고려해보는 것도 좋을 것 같아요~  그리고 `stream API`를 활용해보면 어떨까요?

2023-07-16 19:41 UTC, JoosungKwon commented on src/test/java/org/promgrammers/voucher/repository/MemoryVoucherRepositoryTest.java
> +        // Given
여기는 `@DisplayName` 없네요! 일관성있게 하시면 좋을 것 같아요!

2023-07-16 19:41 UTC, JoosungKwon commented on src/main/java/org/promgrammers/voucher/VoucherApplication.java
> +        Scanner scanner = new Scanner(System.in);
여기서는 `new Scanner(System.in);`를 직접호출하네요! `Console`을 사용하지 않는 이유는 무엇 때문인가요?

2023-07-16 19:41 UTC, JoosungKwon commented on src/main/java/org/promgrammers/voucher/VoucherApplication.java
> +    }
`Application`에 `main`은 진입점에 의미를 두고 있기 때문에 보통은 로직을 담지 않습니다. 따라서, 저는 `CommandLineRunner` 구현하고 `execute` 메서드가 이곳에 있는 것은 적절하다는 생각이 들지 않네요 어떻게 생각하시나요?

2023-07-16 19:41 UTC, JoosungKwon commented on src/main/java/org/promgrammers/voucher/repository/CustomerRepository.java
> +    Optional<Customer> findByVoucherId(UUID voucherId);
반대로 `customerId`로 해당하는 `Voucher`를 찾는 기능이 있어도 괜찮겠네요

2023-07-17 10:39 UTC, graygreat requested changes
안녕하세요 승현님 :)

코드 잘 짜주셨네요 ㅎㅎ
고생 많으셨습니다!

몇 가지 피드백 남겼으니 확인 부탁드립니다.

> 바우처와 고객이 적절하게 매핑이 되었는지 정확하게 구현했는지 궁굼합니다.

이건 주성님이 잘 남겨주셔서 주성님 말씀 참고하시면 될 것 같습니다.

> MYSQL에서 UUID 타입을 지원하지 않아 VARCHAR 타입으로 테이블을 생성하여 UUID인 id값을 String.valueOf를 통해 데이터베이스에 저장하였는데 이로인한 문제가 생기는지 궁굼합니다.

큰 문제는 없을 것 같습니다. 챙겼으면 하는 부분은 검색을 할 때, String의 성능에 대해서 한번 찾아보시면 좋을 것 같아요.

> 전체적으로 코드의 일관성과 가독성이 괜찮은지 여쭤보고 싶습니다.

코드 자체가 정돈되지 않은 느낌이 굉장히 많이 들어요. (불필요한 개행이 너무 많음)
코드를 나만 보는 것이 아닌 다른 그 누군가가 본다고 생각을 하고 작성하면 좋을 것 같아요.
추가로 객체지향 관련 책을 읽어보시는 것을 추천해요.
코드 자체에 객체지향스럽지 않은 부분이 많은 것 같아요.
책 읽고 리팩토링하는 것도 좋은 경험이 될 것 같습니다 :)

추천
---
[객체지향 생활 체조 원칙](https://nesoy.github.io/articles/2018-01/CleanCode-Form)
[객체지향의 사실과 오해](https://www.yes24.com/Product/Goods/18249021)
[오브젝트](https://www.yes24.com/Product/Goods/74219491)

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/VoucherApplication.java
> +        String command = scanner.nextLine().toUpperCase();
주성님이 말씀해주신거에 이어서 Main Application이 출력과, 입력을 해주는 역할을 하는게 맞는지 생각해보면 좋을 것 같아요.

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/view/Console.java
> +
불필요한 개행

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/view/Console.java
> +    }
클린 코드에 나오는 개념인 ["수직 거리"](https://nesoy.github.io/articles/2018-01/CleanCode-Form)에 대해 한번 보시면 좋을 것 같아요.

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/controller/CustomerController.java
> +@Controller
Controller와 RestController의 차이는 무엇일까요?

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/config/AppConfig.java
> +}
AppConfig를 만드신 이유는 무엇인가요?
Console 자체를 Component로 만들어주면 될 것 같은데요.

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/controller/CustomerController.java
> +    public synchronized void userPostController() {
객체지향에서 메소드는 "행위"를 의미하죠.
CustomController에서 userPostController라는 메소드가 적절한 행위를 나타내는지 생각해보시면 좋을 것 같아요.

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/controller/CustomerController.java
> +public class CustomerController {
너무 길어요..ㅋ

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/view/CustomerAction.java
> +package org.promgrammers.voucher.view;
해당 로직을 view에 넣어두신 이유는 무엇인가요?

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/view/CustomerAction.java
> +        }
추가로 depth는 1이 넘지 않도록 노력해보세요~

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/controller/VoucherController.java
> +@Component
여긴 @Controller가 아닌 @Component를 사용하셨는데, @Controller, @Service, @Repository, @Component는 어떠한 차이가 있나요?

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/controller/VoucherController.java
> +        console.print("Voucher 생성. : " + createdVoucher.toString());
출력을 해주는건 view의 역할이 아닐까요?

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/domain/Customer.java
> +    }
도메인에서 검증 👍

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/domain/Voucher.java
> +
불필요한 개행

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/domain/Voucher.java
> +    }
없어도 되지 않을까요?

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/domain/VoucherType.java
> +                log.info("VoucherType.fromType - 값 변환: {} -> 타입: {}", value, type);
해당 로직에 로그를 찍음으로서 어떠한 장점이 있을까요?

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/repository/MemoryVoucherRepository.java
> +    //동시성 문제
굳이 달 필요 없는 주석인 것 같아요 ㅎ

2023-07-17 10:39 UTC, graygreat commented on src/main/java/org/promgrammers/voucher/service/CustomerService.java
> +                .orElseThrow(() -> new NoSuchElementException("해당 바우처를 찾을수 없습니다"));
repository 단에서도 findById에 대한 예외가 있고 해당 로직에서도 예외를 던지게 되는데 둘 다 throw 하는 이유가 있을까요?

2023-08-13 04:20 UTC, merged