[4기 - 김주웅] SpringBoot Part2 Weekly Mission 두 번째 PR 제출
prgrms-be-devcourse/springboot-basic pull request #846
Opened 2023-07-16 12:40 UTC by JuwoongKim

### 바우처 과제 2차

### 1. 그림 그리기 및 소개하기

![바우처설계도_w2n](https://github.com/prgrms-be-devcourse/springboot-basic/assets/62009283/e8a55265-4a13-474f-8f3c-602e7fb484fa)

</br>

### 2. 요구사항

**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.

- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

- [ ]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
   - customers 테이블 정의 및 추가
   - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현

- [ ] **(심화)** **바우처 지갑을 만들어보세요.**
  - 특정 고객에게 바우처를 할당할 수 있습니다.
  - 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
  - 고객이 보유한 바우처를 제거할 수 있어야 합니다.
  - 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

- [ ]  쿼리 빌더 적용 (sql 쿼리)

    
</br>

### 3. 작업 순서 목록

- [x] 바우처 생성 시 DB 저장 기능 구현
- [x] DB에 저장된 바우처 정보 전체 조회 기능 구현
- [x] 바우처 정보 전체 삭제 기능 구현
- [x] 바우처 ID 조건 조회 기능 구현
- [x] 바우처 ID 조건 삭제 기능 구현
- [x] 바우처 ID 조건 수정 기능 구현

#### 추가작업 순서 

- [ ] 쿼리빌더 추가 및 바우처 레포지토리 적용

</br>

- [ ] 바우처, 고객, 지갑 기능을 위해 ApplicationController 분기처리 로직 수정 

</br>

- [ ] 고객 도메인 추가 및 테이블 생성  
- [ ] 고객 생성 기능 추가
- [ ] 고객 전체조회 기능 추가
- [ ] 고객 전체삭제 기능 추가 
- [ ] 고객 ID 조건 조회 기능 추가 
- [ ] 고객 ID 조건 삭제 기능 추가 
- [ ] 고객 ID 조건 수정 기능 추가 

</br>

- [ ] 지갑 도메인 추가 및 테이블 생성 
- [ ] 지갑 생성 기능 추가 
- [ ] 고객 ID 조건 지갑 전체 조회기능 추가
- [ ] 바우처 ID 조건 지갑 전체 조회기능 추가
- [ ] 고객 ID, 바우처 ID 조건 지갑 삭제 기능 추가

</br>

- [ ] 바우처 삭제시 해당 바우처 ID 조건 지갑 삭제 기능 추가
- [ ] 고객 삭제시 해당 고객 ID 조건 지갑 삭제 기능 추가

</br>

- [ ] 바우처 기능 요청 및 응답 객체 생성 및 내부 클래스로 직관적 의미 전달
- [ ] 고객 기능 요청 및 응답 객체 생성 및 내부 클래스로 직관적 의미 전달
- [ ] 지갑 기능 요청 및 응딥 객체 생성 및 내부 클래스로 직관적 의미 전달
- [ ] ApplicationController 콘솔 입력에 대한 분기처리 리펙토링
- [ ] 예외 처리 리펙토링 

</br>

2023-07-16 12:56 UTC, JuwoongKim commented
리뷰 요청 
- 바우처 2차 설계도,  요구사항 , 작업 수행 목록 작성 했습니다. 검토 후 피드백 요청 드리겠습니다.

2023-07-16 15:59 UTC, Jo-GyuHyeon commented
안녕하세요 주웅님 😄 
1. 그림 그리기 및 소개하기 잘 하신것 같아요.
작업 목록은 커밋 단위 (메시지) 라고 생각해보시고 신중힌 한번더 고민 해보시면 좋을것 같아요.
특히 쿼리 빌더 쪽은 더욱 쪼갤 필요가 있어 보여요.

해당 PR 에서는 다른 도메인을 구현 하기 보다 쿼리 빌더 쪽을 먼저 진행 해보시는것을 제안 드려보고 싶어요.
화이팅! 👏

2023-07-16 17:32 UTC, JuwoongKim commented
쿼리빌더에 관한 작업 수행 목록을 세분화 한 뒤 수정해봤습니다.
테스트를 해보며 신중하게 나눠봤으나 개선이 필요하다면 피드백 부탁드립니다. 
쿼리빌더 작업을 수행한 뒤 이후 작업 목록에 대해 신중히 고려해보겠습니다.

2023-07-17 03:56 UTC, JuwoongKim commented
리뷰 요청 
- 쿼리 빌더를 제외한 작업 순서 목록을 새로 수정했습니다. 리뷰 후 피드백 부탁드리겠습니다.

질문 
- customer와 Voucher는요구 사항이 동일하여 enum 추상메서드로 코드 중복을 줄일 수 있었지만, Wallet은 요구사항이 달랐습니다. 에를 들어 조회 조건이 2가지가 있거나, 수정기능을 제공하지 않습니다. 
-  다양한 조건은 내부 분기처리, 제공하지 않는 기능은 출력문을 통해 기능을 제공하지 않는다는 방식으로 접근하려합니다. 적절한 선택인지 궁금합니다.

2023-07-17 12:46 UTC, HyoungUkJJang requested changes
안녕하세요 주웅님 리뷰가 늦어서 죄송합니다 ㅠ 코드 잘 봤습니다 !

간단한 것 위주로 먼저 의견을 조금 남겨봤어요 ! 주웅님도 의견을 편하게 말씀해주시면 좋을 것 같습니다.
고생하셨어요 ☺️ 👍🏻

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/constant/ServiceType.java
> +    Voucher;
Voucher도 대문자로 통일하시면 좋을 것 같습니다. 그리고 enum은 아래와 같은 형태로 하시는게 관리에 더 편하실 거에요 :) 
```suggestion
    EXIT,
    Voucher
    ;
```

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/constant/ServiceType.java
> +            .orElseThrow();
어떤 예외를 던질지 조금 더 구체화 하시면 좋을 것 같습니다 :)

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/constant/VoucherType.java
>  public enum VoucherType {
ENUM에서 바우처를 생성해 주는 부분 괜찮은 것 같습니다 ! 추상 메서드가 2개로 보이는데 굳이 UUID를 외부에서 넘겨 줄 필요가 있을까요?

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            if (selectedServiceType == null) {
이 null 체크는 꼭 필요할까요?

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +        if (selectedModeType == null) {
이 null 체크는 꼭 필요할까요?

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/io/Console.java
> +    }
이 부분은 null에 대해 다시한번 생각해보시면 좋을 것 같습니다.

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +public class QueryBuilder {
고민을 많이 하시고 만들어 주신 것 같아요 :) ! 다만 현재 쿼리 빌더는 select, update, delete가 한 곳에 몰아져 있다 보니까 문법적으로 틀렸음에도 불구하고 올바르게 코드 상으로는 올바르게 인식할 것 같아요 

select, update, delete, where 등등 적절하게 나누면서 더 탄탄하게 만들어보는건 어떨까요?

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/controller/response/Response.java
> +    private List<T> dtoList;
Respons와 Dto 네이밍을 섞어서 사용하기 보다는 차라리 `responses`가 더 간단해 보이는데 주웅님의 생각은 어떠신가요?

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/controller/response/Response.java
> +        this.dtoList.add(dto);
주웅님은 아래의 코드에 대해 어떻게 생각하시나요?
```suggestion
       return new Response(Arrays.asList(dto));
```

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/controller/response/Response.java
> +            resultMessage.deleteCharAt(resultMessage.length() - 2);
매직넘버를 지양해주세요 ~

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +    public QueryBuilder() {
빌더 패턴처럼 static을 고려하는건 어떻게 생각하시나요?

2023-07-17 12:46 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/controller/request/VoucherRequest.java
> +
정적 이너 클래스 내에서도 컨벤션이 통일되면 좋을 것 같아요 ~

2023-07-17 13:30 UTC, JuwoongKim commented on src/main/java/com/example/voucher/constant/ServiceType.java
> +    Voucher;
7398ba51634bec1888a4810d1ccabe1749cbb43a 커밋 피드백 반영 
- 대문자로 써야함을 인지하고 있었으나 꼼꼼함이 부족했던 것 같습니다. 고쳐보겠습니다.
- 세미콜론을 한칸 내리는 표기법이 값에 대한 가독성이 좋다고 판단하여 고쳐봤습니다. 가독성 이외에도 관리면에서 용이한 점이 있을까요??

2023-07-17 13:36 UTC, JuwoongKim commented on src/main/java/com/example/voucher/constant/ServiceType.java
> +            .orElseThrow();
809853d37f0791c36fba9e01a7005500cb071064 커밋 피드백 반영 
- IllegalArgumentException에 예외메세지를 반환하도록 했습니다. 
- 위와 동일한 부주의 문제 주의하도록 하겠습니다.

2023-07-17 13:49 UTC, JuwoongKim commented on src/main/java/com/example/voucher/constant/VoucherType.java
>  public enum VoucherType {
피드백 반영 
- 구두로 피드백을 진행했습니다.

2023-07-17 14:02 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/response/Response.java
> +    private List<T> dtoList;
9e99588192e9860890a734503efb276b0539d4c9 커밋 피드백 반영 
- 생각해보니 Response 객체에 dto 네이밍을 사용하는 것이 어색해 보입니다. dto 관련 네이밍을 responses로 변경했습니다.

2023-07-17 14:15 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/response/Response.java
> +        this.dtoList.add(dto);
2e113b10920e32f30657a4d729b4d641a778b819 커밋 피드백 반영 
- 두 문장을 하나의 문장으로 축약할 수 있다는 점에서 깔끔하다고 생각합니다.
- 좀 더 깔끔하게 코드를 작성할 수 있도록 생각하겠습니다.

2023-07-17 14:16 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/response/Response.java
> +            resultMessage.deleteCharAt(resultMessage.length() - 2);
9e99588192e9860890a734503efb276b0539d4c9 커밋 피드백 반영
- 매직넘버를 불변상수로 변경했습니다. 죄송합니다.

2023-07-17 16:18 UTC, JuwoongKim commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +    public QueryBuilder() {
static 을 고려하라는 말씀이 멤버변수에 클래스 변수로 변경한다는 의미인가요???
해당 부분에 대해 같이 논의해보고 싶습니다!!.

2023-07-17 21:31 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/controller/response/Response.java
> +            resultMessage.deleteCharAt(resultMessage.length() - 2);
resultMessage.length() - 상수 까지 한 변수로 따로 지정한다면 더욱 의미가 강해 질것 같아요.

---
해당 리뷰는 반영 되었기에 Resolve 처리 할게요.
이 리뷰와 별개로 getMessage() 를 할때마다 로직이 수행이 되겠군요?? 🤔

2023-07-17 23:04 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            if (selectedServiceType == null) {
3f92917cdfae87b1e5c833142ef1c2fb457372b3 커밋 피드백 반영 
- switch의 default 메서드에서 처리하는 것을 고려했으나 전체적으로 콘솔에서 예외를 던지고 콘솔 호출부분에서 처리하는 방식으 변경했습니다.

2023-07-17 23:04 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +        if (selectedModeType == null) {
3f92917cdfae87b1e5c833142ef1c2fb457372b3 커밋 피드백 반영 
- 위의 방식과 동일한 접근으로 변경했습니다.

2023-07-17 23:07 UTC, JuwoongKim commented on src/main/java/com/example/voucher/io/Console.java
> +    }
3f92917cdfae87b1e5c833142ef1c2fb457372b3 커밋 피드백 반영 
- 동일하게 불필요한 null값 반환을 제거하고 콘솔에서 예외를 던지고 콘솔 호출부분에서 처리하는 방식으로 변경했습니다.

2023-07-17 23:10 UTC, JuwoongKim commented on src/main/java/com/example/voucher/constant/ServiceType.java
> +    Voucher;
피드백 반영 
- 구두로 피드백을 진행했습니다.

2023-07-17 23:12 UTC, JuwoongKim commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +public class QueryBuilder {
671174f3a1a560ade665a0b0c5ea84ed101d8587 커밋 피드백 반영 
- satic inner class를 사용해  타입안정성을 보장하는 방향으로 개선해봤습니다.

2023-07-19 01:35 UTC, JuwoongKim commented
PR 리뷰 반영 완료 했습니다.

추가 내용

- 미션 요구사항인 customer, wallet 도메인 기능구현을 완료했습니다. 

리뷰 반영 및 추가구현사항 리뷰 부탁드립니다.  감사합니다!!

2023-07-19 01:47 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/response/Response.java
> +            resultMessage.deleteCharAt(resultMessage.length() - 2);
controller에서 ResponseEntity 클래스를 보고 구현해봤는데 , 리뷰를 보며 문자열 데이터 생성 부분을 response의 역할이 맞냐에 대해서 고민이 됩니다.

현재까진 책임 할당이 적절한가에대한 문제가 떠오르는데 한번 더 고민해보고 리뷰 요청드리겠습니다.

2023-07-20 03:48 UTC, Jo-GyuHyeon reviewed
간단하게 리뷰 드렸어요.
중복되는 내용이 있을 수 있지만, 각 라인마다 달진 않았어요.
쿼리 빌더 같은 경우에 각각 Root 레벨로 쪼개서 각 빌더를 만들어 보시는것을 제안 드리고 싶어요.
협력 관계를 이용해보시면서 타입언어의 장점을 잘 살려 컴파일어의 도움을 받을수 있도록 해보시면 좋을것 같아요.
고생하셨어요.

2023-07-20 03:48 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            case SEARCH_BY_VOUCHER -> searchWallet("VOUCHER_ID");
하드코딩을 사용하진 이유가 궁금해요.

2023-07-20 03:48 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +        } catch (Exception e) {
모든 코드라인이 try 구문 안에 있어야 될까요???
비슷한 내용들이 있어서 각 라인마다 코멘트를 남기진 않을게요.

2023-07-20 03:48 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/controller/response/Response.java
> +    }
리플랙션을 사용 하는 이유가 무엇일까요?? 
왜 사용하게 되었나요?
다른 방법도 있을까요?

들여쓰기 (인덴트) 가 깊어지는것 같아요.

2023-07-20 03:48 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +    public DeleteBuilder delete(String table) {
table 을 String 이 아니라 다른 타입으로 받으면 어떨까요?
타입언어의 장점을 이용하여 컴파일러의 도움을 받아 볼까요?
String 은 타입이 없는 것 처럼 보든 값이 들어 갈 수 있다고 생각해요.

2023-07-20 03:48 UTC, Jo-GyuHyeon commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +        }
DeleteBuilder 에서 WhereBuilder 타입만 사용하고 있는것 같아요. WhereBuilder 협력 하고 있을 까요?

2023-07-20 03:48 UTC, Jo-GyuHyeon requested changes
간단하게 리뷰 드렸어요.
중복되는 내용이 있을 수 있지만, 각 라인마다 달진 않았어요.
쿼리 빌더 같은 경우에 각각 Root 레벨로 쪼개서 각 빌더를 만들어 보시는것을 제안 드리고 싶어요.
협력 관계를 이용해보시면서 타입언어의 장점을 잘 살려 컴파일어의 도움을 받을수 있도록 해보시면 좋을것 같아요.
고생하셨어요.

2023-07-23 08:06 UTC, HyoungUkJJang reviewed
주웅님 간단히 코멘트 남겼습니다 쿼리빌더를 조금 더 고민하고 수정해보시면 좋을 것 같아요 :) 

추가적으로 이야기 나누고 싶은 부분이 있으시다면 게더에서 구두로 이야기 나눠봐요 !

2023-07-23 08:06 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +public class QueryBuilder {
@JuwoongKim 

정적 이너 클래스 보다는 별도의 클래스로 만드는게 더 좋을 것 같은데 주웅님의 생각은 어떠신가요?

2023-07-23 08:06 UTC, HyoungUkJJang commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +        }
네이밍이 적절할까요?

2023-07-23 16:11 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            case SEARCH_BY_VOUCHER -> searchWallet("VOUCHER_ID");
동일한 기능에 where 조건만 다르기 때문에 변화의 부분을 파라미터로 주었습니다. 
파라미터는 where 조건입니다. 

하드코딩을 사용한 이유는 제 부주의 입니다. 불변 상수로 빼는 방법, enum 값을 사용하는 방법으로 수정하려 하는데 괜찮을까요??

2023-07-23 16:23 UTC, JuwoongKim commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +public class QueryBuilder {
네 멘토님!! JDBC 익숙해지기를 통해 분리하였고, 바우처 과제에 반영해보록 하겠습니다.

2023-07-23 16:39 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +        } catch (Exception e) {
콘솔로 부터 입력을 받는 부분만 try catch로 감싸려고 하는데 괜찮은 방법일까요? 

출력부분인 예외 발생가능성이 없고  
서비스 부분은 query 메서드를 사용해 빈 리스트 값을 반환해도 괜찮을 것 같습니다.

다만 입력 부분은 예외로 한번에 처리하는게 더 깔끔하다고 생각합니다. 기존에 예외처리후 널 값 반환 방법을 사용했는데 null이 너무 무분별하게 쓰였습니다.

2023-07-23 16:45 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/response/Response.java
> +    }
서비스가 여러개 생기면서 서비스마다 DTO값을 받아 새로운 console 메서드를 만드는 것이 비효율적이라 생각했습니다. 
당시 responseEntity<T>에 꽂히고 requset 객체를 만들고 대응하고 싶게 하고 싶어 만들었던 것 같습니다.

혹시 저 response의 기능을 콘솔에게 넘기고 콘솔 내부에서 재내릭 메서드를 만들어 리플랙션을 사용해 문자열을 만들고 Writer에게 전달해주는 건 어떨까요???

애초에 접근이 이상한가요??

.

2023-07-23 16:46 UTC, JuwoongKim commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +    public DeleteBuilder delete(String table) {
자바 익숙해지 쿼리빌더 컴토 후 함께 피드백 반영해보도록 하겠습니다.

2023-07-23 16:46 UTC, JuwoongKim commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +        }
자바 익숙해지 쿼리빌더 컴토 후 함께 피드백 반영해보도록 하겠습니다.

2023-07-23 17:00 UTC, JuwoongKim commented on src/main/java/com/example/voucher/domain/customer/Customer.java
> +    }
저도 멘토님과 동일하게 생각합니다.  진행해보곘습니다!

2023-07-25 05:02 UTC, JuwoongKim commented on src/main/java/com/example/voucher/domain/customer/Customer.java
> +    }
fcf44fd697a93700dee251418bb778f1069744fd 커밋 피드백 반영
- 내부 inner static 클래스로 빌더를 만들어서 생성자를 줄였습니다.
- 다만 빌더 맴버 변수의 초기화를 클래스 맴버변수의 초기화로 하였는데 적절한 것인지 모르겠습니다.
  - 예를 들어 DB에서 customer 테이블의 모든 컬럼이 not null인데 클래스에서 null로 초기화하는 것이 적절한지 궁금합니다.그렇다고 빈문자열을 넣자니 맘에 걸리고요.
- 우선은 빈문자열보단 클래스 맴버변수의 초기화가 더 일반적이라고 생각합니다.

2023-07-27 22:27 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +            case SEARCH_BY_VOUCHER -> searchWallet("VOUCHER_ID");
3100f5d989dd959c437dbf3f00b12964703feedf 커밋 피드백 반영 
- 고객 기준, 바우처 기준 조회의 파라미터가 같더라도 다른 요청이기 때문에 별도의 메서드로 분리했습니다.

2023-07-27 23:21 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/response/Response.java
> +    }
037808974aac7885b8361db584a8a76bc6861d9c 커밋 피드백 반영 
- 각 도메인별 Response 객체를 생성하고 도메인별 출력 메서드를 추가했습니다.
- 이유는 기존 리플랙션을 사용한 Response는 DTO 값 저장 이외에 메세지를 만들어 console과의 책임이 모호했고, 출력시에도 단순 String을 주어 메서드의 잘못된 사용을 유발할 수도 있기 때문입니다.
- 또한 별도의 Response를 통해 도메인별 서비스에서 어떤 값을 출력할 것 인지 의도파악도 쉬웠습니다.

2023-07-28 02:14 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/ApplicationController.java
> +        } catch (Exception e) {
0b67b8fce674080b73269e70822c862a0c0a2d2e dcefe9a20669bcca088ade632dac97df859e4b90 커밋 피드백 반영
- 입력에 대한 예외처리를 잘못된 값을 재요청하는 방식을 사용해 콘솔로 위임
- 서비스에 대한 예외처리를 Response 객체에 상태값을 전달하는 방식을 사용해 컨트롤러로 위임

2023-07-28 02:16 UTC, JuwoongKim commented on src/main/java/com/example/voucher/controller/response/Response.java
> +            resultMessage.deleteCharAt(resultMessage.length() - 2);
037808974aac7885b8361db584a8a76bc6861d9c 커밋 피드백 반영 
- 쓸데없이 복잡하고 의도파악이 어렵기 때문에 각 도메인 별로 Response를 생성하고 이에 맞게 출력 메서드를 생성했습니다.

2023-07-28 02:16 UTC, JuwoongKim commented on src/main/java/com/example/voucher/repository/QueryBuilder.java
> +    public QueryBuilder() {
쿼리 빌더를 적용하며 피드백을 반영하겠습니다.

2023-07-28 02:23 UTC, JuwoongKim commented
쿼리빌더 적용을 제외한 PR 리뷰 반영 완료 했습니다.
- 리플랙션을 사용해 모든 도메인에 사용하는 Response 객체를 각 도메인별로 분리했습니다.
- ApplicatoinController에서 수행한 예외처리를, 콘솔과 도메인별 컨트롤러로 분리했습니다.
- 하나의 메서드에 하드코딩 파리미터로 다양한 조건 조회 처리를 각 메서드로 분리했습니다.
- 빌더패턴을 상용해 Customer 도메인의 많은 생성자 사용을 줄였습니다.
- 패키지 구조가 난잡하여 도메인별로 정리했습니다.

추가 구현 기능 없습니다.

2023-08-07 14:19 UTC, Jo-GyuHyeon reviewed
지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-07 14:19 UTC, Jo-GyuHyeon approved these changes
지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-07 14:19 UTC, Jo-GyuHyeon approved these changes
지금까지 미션 진행 하시느라 고생 많으셨어요.
PR merge 로 해당 PR 을 종료 하시면서 마무리 하시면 좋겠어요.
다시 한번 고생 많으셨어요.

2023-08-09 04:45 UTC, merged