Week2 2
prgrms-be-devcourse/springboot-basic pull request #853
Opened 2023-07-18 16:27 UTC by charlesuu

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-07-21 03:30 UTC, hanjo8813 reviewed
현호님 수고하셨습니다~!

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/validate/CommandValidator.java
> +    }
유틸성 클래스는 다음과 같이 변경가능성을 막아주세요~

```suggestion
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public final class CommandValidator {

    private static final Pattern IS_NUMBER_ONE_TO_THREE = Pattern.compile("^[1-3]{1}$");
    private static final Pattern IS_NUMBER_ONE_TO_FOUR = Pattern.compile("^[1-4]{1}$");

```

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/java/com/example/demo/service/CustomerService.java
> +    }
롬복 사용해주세요.
코딩 스타일을 통일시키면 더 좋을것 같습니다~

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/validate/CustomerValidator.java
> +        }
여기도 로깅 두번 찍힐것 같네요
이런 부분이 좀 많긴해서.. 이제 리뷰 생략하도록 하겠습니다!
꼭 다른 부분도 신경써서 봐주세요~

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/validate/CustomerValidator.java
> +    }
메소드가 분리될 이유가 없는것 같습니다.

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/validate/CustomerValidator.java
> +public class CustomerValidator {
이 유틸성 클래스도 똑같이! 다른 비슷한 경우도 반드시 신경써주세요

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/validate/NumberValidator.java
> +        if (inputAmount < 1 || inputAmount > 100) {
매직넘버~

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/voucher/VoucherView.java
> +    }
지금 view들을 bean으로 등록하는 기준이 어떻게 되는건가요?

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/resources/application.yml
> +    open-in-view: false
이 설정은 어떤걸 뜻하나요?

2023-07-21 03:30 UTC, hanjo8813 commented on src/main/resources/schema.sql
> +);
테이블명 네이밍 복수 vs 단수
참고 : https://github.com/prgrms-be-devcourse/springboot-basic/pull/789#discussion_r1263265423

2023-07-21 03:30 UTC, hanjo8813 commented on src/test/java/com/example/demo/repository/customer/CustomerJdbcRepositoryTest.java
> +        assertThat(customerActual).isEqualTo(customerExpect);
동등성을 비교해주세요~

2023-07-21 03:30 UTC, hanjo8813 commented on src/test/java/com/example/demo/service/CustomerServiceTest.java
> +        then(customerRepository).should(times(1)).deleteById(customerId);//mock객체의 메서드를 호출했다는 것을 검증하는데 의미를 두어도 괜찮은가?
저번에 말씀드렸듯 행위검증과 상태검증 둘다 해주는게 베스트입니다~
하지만 특별한 경우가 아니면.. 보통 상태검증만 수행하는것 같습니다

2023-07-22 14:30 UTC, charlesuu reviewed
@hanjo8813 재원님 늦었지만 2주차 반영 끝냈습니다~!
몇 몇 리뷰에 대해 질문이 있어서 멘션드렸는데 확인해주시면 너무 감사하겠습니다~!

2023-07-22 14:30 UTC, charlesuu commented on src/main/java/com/example/demo/view/validate/NumberValidator.java
> +        if (inputAmount < 1 || inputAmount > 100) {
상수화해서 PERCENT_MAX_VALUE라는 이름을 붙여주었습니다~!!

2023-07-22 14:30 UTC, charlesuu commented on src/main/java/com/example/demo/view/voucher/VoucherView.java
> +    }
도메인 별로 main뷰에 input뷰, output 뷰가 하나 씩 붙어있는 구조입니다. 이때 main뷰만 등록되도록 만들었습니다.
main뷰 전체가 교체되는 경우는 있을 수 있지만, 그 하위의 input뷰, output 뷰가 교체될 경우는 없다고 판단되어서 이렇게 작성했습니다~!

2023-07-22 14:30 UTC, charlesuu commented on src/main/resources/application.yml
> +    open-in-view: false
예전에 해두었던 프로젝트에서 복사하다가 실수로 들어갔습니다..ㅎㅎ (JPA에서 영속성 컨텍스트의 생존 범위에 대한 설정이라고 합니다)

2023-07-22 14:30 UTC, charlesuu commented on src/main/resources/schema.sql
> +);
테이블명에 대해 생각해본적이 없었는데, 생각보다 많은 고민들이 있군요!
참고해서 적용해보겠습니다~!!

2023-07-22 14:30 UTC, charlesuu commented on src/test/java/com/example/demo/repository/customer/CustomerJdbcRepositoryTest.java
> +        assertThat(customerActual).isEqualTo(customerExpect);
넵 동등성 비교하도록 수정했습니다~!

2023-07-22 18:03 UTC, hanjo8813 requested changes
지금 수정한 커밋이 보이지 않고 있는데 아마 push를 까먹으신것 같네요~
PR에도 반영시켜주세요!

2023-07-22 18:38 UTC, hanjo8813 commented on src/main/java/com/example/demo/controller/CustomerController.java
> +    public CustomerDto read(UUID id) {
컨벤션은 중요하지만, 절대적인건 없습니다. 항상 유연한 자세를 가지고 상황에 맞는 선택을 해야합니다.

현재는 콘솔에서만 사용되기에 `customerController.getCustomer()`와 같이 어디선가 컨트롤러를 호출하게 되는데, 사실 웹 환경에서는 해당 메소드를 코드상에서 직접 호출하는 경우는 없습니다.

그리고 보통 웹 환경의 컨트롤러는 여러 api를 구현해야하기 때문에 메소드 네이밍을 자세히 명시해줄 필요가 있습니다.

repository와 비교해보면, repository 계층과 같이 특정 도메인 엔티티를 가져오는 경우엔 어떤 값을 가져오는지 명확합니다. 
CustomerRepository에선 Customer를 가져올 것이고, VoucherRepository에선 Voucher를 가져오겠죠?
따라서 이렇게 리턴값이 클래스명과 명확히 동일한 경우엔 굳이 메소드에 도메인을 추가해서 네이밍을 길게 만들지 않는것입니다.

하지만 controller에서는 복잡한 요구사항의 api가 생겨나게 됩니다.
예를들어 CustomerController에서 특정 voucher를 소유한 고객 리스트를 조회하는 api를 추가해야한다고 해볼게요.
그럼 api를 다음과 같이 만들어줄겁니다.

```http
GET /vouchers/{id}/customers
```

이 api와 매핑되는 메소드명은 어떻게 지어줘야할까요?
getCustomersByVoucher 혹은 find... 이런식으로 지어주게 됩니다.
이렇게 어떤 요구사항이 추가될지 모르니 메소드명에 단건조회인지 다건조회인지, 어떤 조건인지 명확히 명시해주는것입니다.

지금은 잘 이해되지 않을것 같은데요, 더 많은 경험을 하다보면 자연스레 습득하게될 습관이라고 생각해주시면 될것 같습니다.
이건 나중에 라이브로 다시 설명해드리도록 하겠습니다.

2023-07-22 18:42 UTC, hanjo8813 commented on src/main/java/com/example/demo/repository/voucher/VoucherJdbcRepository.java
> +    public boolean isVoucherNotExist(UUID id) {
repository에서는 굳이 다른 쿼리를 만들지 않고 existById를 사용하되, service에서 새로운 메소드를 만들어주는게 좋을것 같습니다~

2023-07-22 18:49 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/validate/CommandValidator.java
> +    }
제가 suggestion 예시에 남긴것처럼 final class로 선언해서 상속을 막으면 메소드 overriding까지 막을 수 있겠죠?

다만 실제로 상속까지 막을 필요는 없습니다. (지금은 최대한 이상적인 방식으로 리뷰를 드리고 있을 뿐) 
apache common langs와 같은 유틸 라이브러리의 코드를 보면 생성자나 상속을 막지 않고 있습니다.

2023-07-22 18:51 UTC, hanjo8813 commented on src/main/java/com/example/demo/view/validate/CustomerValidator.java
> +    }
제가 타입이 다른걸 자세히 안보고 리뷰를 달았네요;;; 죄송합니다;;
두개 모두 제공해도 괜찮을것 같습니다.

2023-07-23 07:56 UTC, charlesuu commented
> 
ㅁ

2023-07-23 07:57 UTC, charlesuu commented
@hanjo8813 헙.. push 까먹었네요.. 반영했습니다~!!

2023-07-23 07:57 UTC, charlesuu commented
ㅇ

2024-03-17 19:18 UTC, merged