Byeolhaha/week3
prgrms-be-devcourse/springboot-basic pull request #856
Opened 2023-07-22 07:49 UTC by byeolhaha

## 📌 과제 설명 
- 타임리프는 `v1`, Rest Api는 `v2`로 구동되도록 분리하였습니다.
- 조건별 검색의 경우 필터가 있다고 생각하여 동적 쿼리로 만들었습니다.
- 그래서 사용자가 아무런 필터 조건을 걸지 않는 경우 모든 목록을 검색합니다. (부분 필터 가능)
   `http://localhost:8080/v1/vouchers?voucherType=PERCENT_DISCOUNT_VOUCHER&createdAt=2023-07-20T10:30:00`
   `http://localhost:8080/v2/vouchers?voucherType=PERCENT_DISCOUNT_VOUCHER` 
   `http://localhost:8080/v2/vouchers`
   `http://localhost:8080/v2/vouchers?createdAt=2023-07-20T10:30:00`
- Controller test의 경우 
`@WebMvcTest`와 `MockMvc`을 사용하여 슬라이스 테스트로 구현하였습니다.
  
- 글로벌 Exception을 적용하여 `@RestControllerAdvice`를 사용하였습니다.
## 👩‍💻 요구 사항과 구현 내용
**(기본) 바우처 서비스 관리페이지 개발하기**
Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - ✅  조회페이지
    - ✅  상세페이지
    - ✅ 입력페이지
    - ✅ 삭제기능
    
**(기본) 바우처 서비스의 API 개발하기**
    - ✅ 전체 조회기능
    - ✅  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - ✅ 바우처 추가기능
    - ✅  바우처 삭제기능
    - ✅  바우처 아이디로 조회 기능

## ✅ 피드백 반영사항  
- BDDMokito 사용하여 given-when-then  가독성 높이기
- 작동되지 않았던 `JdbcCustomerRepository`의  `existsById `메서드 수정 및 테스트 코드 추가
  ```java
  @Override
    public boolean existsById(int customer_id) {

        return jdbcTemplate.queryForObject(
               "SELECT 1 " +
                "FROM customers "+
                "WHERE EXISTS (SELECT 1 FROM customers WHERE customer_id = :customer_id)"
                , Collections.singletonMap("customer_id"
                        , customer_id), Boolean.class);
     }
  ```

- double brace는 안티패턴이므로 수정 
   ```java
  private Map<String, Object> toParamMap(Customer customer) {
        Map<String, Object> map = new HashMap<>();
        map.put("customer_id", customer.getCustomerId());
        map.put("name", customer.getName().getValue());
        map.put("email", customer.getEmail());
        map.put("created_at", Timestamp.valueOf(customer.getCreatedAt()));
        map.put("last_login_at",
                customer.getLastLoginAt() != null ? Timestamp.valueOf(customer.getLastLoginAt())
                        : null);

        return map;
    }
   ```
- impot를 살펴보며 Service가 Controller를 알고 있지는 않을까 고민하였고 패키지 구조를 재설계하여 Service만의 dto, converter를 따로 분리하였습니다.
## ✅  pr 포인트
동적 쿼리로 구현하려고 하다 보니
그 부분에 대해서 **절차 지향적 코드**가 발생한 것 같습니다. 
- `JdbcVoucherRepository`
```java
 @Override
    public Vouchers getAllVoucher(VoucherType voucherType, LocalDateTime createdAt) {
        StringBuilder queryBuilder = new StringBuilder(
                "SELECT voucher_id, voucher_type, discount, created_at FROM vouchers WHERE deleted = false");
        MapSqlParameterSource parameters = new MapSqlParameterSource();

        if (voucherType != null) {
            queryBuilder.append(" AND voucher_type = :voucherType");
            parameters.addValue("voucherType", voucherType.name());
        }

        if (createdAt != null) {
            queryBuilder.append(" AND created_at >= :created_at");
            parameters.addValue("created_at", createdAt);
        }

        List<Voucher> vouchers = jdbcTemplate.query(
                queryBuilder.toString(),
                parameters,
                getVoucherRowMapper());

        return new Vouchers(vouchers);
    }
  ```  
- `MemoryVoucherRepository`
```java
 public Vouchers getAllVoucher(VoucherType voucherType, LocalDateTime createdAt) {
        return new Vouchers(storage.values()
                .stream()
                .filter(voucher -> {
                    boolean typeMatch = containsType(voucherType, voucher.getVoucherType());
                    boolean createdAtMatch = isCreatedLaterThan(createdAt, voucher.getCreatedAt());

                    return typeMatch && createdAtMatch;
                })
                .toList());
    }

    private boolean containsType(VoucherType voucherType, VoucherType targetVoucherType) {
        if (voucherType == null) {
            return true;
        }
        return voucherType.equals(targetVoucherType);
    }

    private boolean isCreatedLaterThan(LocalDateTime createdAt, LocalDateTime targetCreatedAt) {
        if (createdAt == null) {
            return true;
        }
        return createdAt.compareTo(targetCreatedAt) <= 0;
    }
```

2023-07-22 12:21 UTC, devYSK approved these changes
안녕하세요 별님 과제하느냐 고생 많으셨어요


전반적으로 코드가 엄청 깔끔해서 읽기 쉬웠습니다.
다만 특정 행위 또는 행동에 대해서 더 고민해보면 좋을법한 내용들이 있어 리뷰에 남겼습니다. 


—
작동되지 않았던 JdbcCustomerRepository의 existsById 메서드 수정 및 테스트 코드 추가
-> 서브쿼리대신 다른 방법도 존재할것 같습니다! 


—
동적 쿼리로 구현하려고 하다 보니
그 부분에 대해서 절차 지향적 코드가 발생한 것 같습니다.

-> jdbcTemplate에서 어쩔 수 없이 이런 방식으로 동적 쿼리 절차지향적으로 사용하곤 해요.
VoucherQueryBuilder라는 클래스를 따로 빼서 사용할 수 있는 방법이 있긴 합니다.
다만 빌더 패턴이므로, 잘못된 사용시에는 예외가 팡팡 터질 수 있으니 주의해야 하며, 관리포인트가 늘어나고 테스트도 필요하겠지요! 

이렇게 사용한다면, 인스턴스마다 메소드 호출간에 공유 상태를 가지지 않고 스레드마다 메소드 내에서 별도의 VoucherQueryBuilder 인스턴스를 사용해서 스레드 세이프하게 사용할 수 있다고 생각해요.

```java
public class VoucherQueryBuilder {

    private StringBuilder queryBuilder = new StringBuilder(
            "SELECT voucher_id, voucher_type, discount, created_at FROM vouchers");
    private MapSqlParameterSource parameters = new MapSqlParameterSource();
    private boolean isFirstCondition = true;

    private void addCondition(String condition, String paramName, Object paramValue) {
        if (isFirstCondition) {
            queryBuilder.append(" WHERE ");
            isFirstCondition = false;
        } else {
            queryBuilder.append(" AND ");
        }
        queryBuilder.append(condition);
        parameters.addValue(paramName, paramValue);
    }

    public VoucherQueryBuilder createdAt(LocalDateTime createdAt) {
        if (createdAt != null) {
            addCondition("created_at >= :created_at", "created_at", createdAt);
        }
        return this;
    }

    public VoucherQueryBuilder isDelete(Boolean deleted) {
        if (deleted != null) {
            addCondition("deleted = :deleted", "deleted", deleted);
        }
        return this;
    }

    public String getQuery() {
        return queryBuilder.toString();
    }

    public MapSqlParameterSource getParameters() {
        return parameters;
    }
}
,,,,


@Override
public Vouchers getAllVoucher(boolean isDelete, LocalDateTime createdAt) {
    VoucherQueryBuilder queryBuilder = new VoucherQueryBuilder()
      …추가 가능
      … 추가 가능
        .isDelete(isDelete)
        .createdAt(createdAt);

    List<Voucher> vouchers = jdbcTemplate.query(
            queryBuilder.getQuery(),
            queryBuilder.getParameters(),
            getVoucherRowMapper());

    return new Vouchers(vouchers);
}

```

2023-07-22 12:21 UTC, devYSK commented on src/main/java/com/prgrms/wallet/service/dto/WalletServiceResponse.java
> +}
`@JSonProperty` 어노테이션도 있어요!

2023-07-22 12:21 UTC, devYSK commented on src/main/resources/templates/views/create.html
> +<form th:action="@{/v1/vouchers/new}" method="post">
v1 ...

2023-07-22 12:21 UTC, devYSK commented on src/test/java/com/prgrms/vouhcer/controller/VoucherV1ControllerTest.java
> +    void getVouchers_FilterWithVoucherTypeAndCreatedAt_ㅡModelAndView() throws Exception {
- 오타난거같아요

2023-07-22 12:21 UTC, devYSK commented on src/test/java/com/prgrms/vouhcer/controller/VoucherV1ControllerTest.java
> +
KeyGenerator가 interface이면 
테스트시 내가 원하는 값을 반환하는 TestKeyGenerator Class를 Bean으로 등록할수도 있어요

2023-07-22 12:21 UTC, devYSK commented on src/test/java/com/prgrms/vouhcer/repository/MemoryVoucherRepositoryTest.java
> +    private final LocalDateTime today = LocalDateTime.now();
!?

2023-07-24 08:33 UTC, WooSungHwan requested changes
별이님 3주차 과제하시느라 수고 많으셨습니다 ㅎㅎ 오프라인에서의 리뷰를 위해 우선적으로 정리될 부분만 말씀드렸고 나머지는 오프때 이야기나눠봐요 ㅎㅎ

2023-07-24 08:33 UTC, WooSungHwan commented on src/main/java/com/prgrms/voucher/controller/VoucherV2Controller.java
> +        return "redirect:/v1/vouchers";
redirect 라는 행위가 직접적으로 나타내기보다 이 요청으로 voucher는 생성되었으니 생성된 voucher의 접근경로를 전달해주는 게 좀더 restful한 api 개발방법입니다.
restful에 대한 키워드를 서치해보시고 201 에 대해서 알아봅시당.

2023-07-30 04:18 UTC, byeolhaha commented on src/main/java/com/prgrms/voucher/service/VoucherService.java
> +            double discountAmount, LocalDateTime createdAt) {
Service 테스트를 위해서 밖에서 만들도록 했습니다!

2023-07-30 04:30 UTC, byeolhaha commented on src/main/java/com/prgrms/voucher/controller/VoucherV1Controller.java
> +    @GetMapping("/delete/{voucherId}")
API를 사용한 통신의 경우엔 `@DeleteMapping`을 통한 삭제가 가능하지만
 `form 태그`나 `uri`로 직접 접근하는 경우엔 @DeleteMapping 사용이 불가능하였습니다.
 물론  hidden 타입의 input 태그를 이용하면 쓸 수는 있지만 잘 사용하지 않는다고 합니다.

2023-07-30 04:34 UTC, byeolhaha commented on src/main/java/com/prgrms/voucher/controller/VoucherV2Controller.java
> +@RequestMapping("/v2/vouchers")
이미 사용중인 API에 대해서 서비스가 중단되면 안된다고 생각하여 버저닝을 사용하게 되었습니다.

2023-07-30 05:58 UTC, byeolhaha commented on src/main/java/com/prgrms/voucher/controller/VoucherV2Controller.java
> +    public int deleteVoucher(@PathVariable("voucherId") int voucherId) {
body에는 삭제된 바우처 아이디만 응답됩니다.
그러나 `@RestController`의 경우 기본으로 Json 형태의 응답을 주며 응답 Header를 확인해본 결과 Content-Type이 `application/json`이었습니다. 

따라서 VoucherDeleteResponse와 관련된 Dto를 만들어 Json 형태로 바꾸도록 하겠습니다
```
{"deletedVoucherId": ""}
```

2023-07-30 06:32 UTC, byeolhaha commented on src/main/java/com/prgrms/voucher/controller/VoucherV2Controller.java
> +        return new ResponseEntity<>(voucherService.detailVoucher(voucherId), HttpStatus.OK);
생성자 패턴보다 빌더 패던을 이용하는 방법이 더 명시적이라는 것을 알게 되었어요
이 빌더 패턴을 메서드 체이닝 방식이며 정적 패토리 메서드였습니다.
수정하도록 할게요.

2023-08-01 09:06 UTC, byeolhaha commented on src/main/java/com/prgrms/voucher/controller/VoucherV2Controller.java
> +    public String createVoucher(@RequestParam("voucherType") VoucherType voucherType,
```java
 URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(id)
                .toUri();

 return ResponseEntity.created(location)
                .body(voucherService.createVoucher(id, createRequest, LocalDateTime.now()));
```          
위와 같이 하여 header location에 hateoas를 제공하는 방법으로 수정하였습니다

2023-08-01 11:25 UTC, byeolhaha commented on src/main/java/com/prgrms/voucher/controller/VoucherV2Controller.java
> +            @RequestParam("discountAmount") double discountAmount) {
RequestBody로 수정하도록 하겠습니다. 
Post 요청인데 쿼리 파라미터로 받고 있었네요 😂

2023-08-01 14:24 UTC, byeolhaha commented on src/main/java/com/prgrms/exception/VoucherExceptionHandler.java
> +        return new ResponseEntity<>(errorResult,  HttpStatus.BAD_REQUEST);
ErrorCode Enum 클래스를 따로 만들어서 status, divisionCode, message를 담았습니다 💡

2023-08-01 23:20 UTC, byeolhaha commented on src/main/java/com/prgrms/presentation/command/voucher/CreateCommand.java
> +        LocalDateTime createdAt = LocalDateTime.now();
둘 다 인터페이스로 만들어서 테스트 할 때 특정 값을 설정할 수 있도록 수정할게요 ✏️

2023-08-02 14:09 UTC, byeolhaha commented
###  3주차 리뷰 반영하여 제출합니다.
## 리뷰 반영 사항
- KeyGernerator 인터페이스로 만들어 테스트할 때 고정 값으로 등록할 수 있도록 하였습니다.
  따라서 ```@TestConfiguration```을 이용하여 클래스를 분리하였습니다
- sequential UUID를 이용해 key를 만들어 재정렬의 단점을 보완하였습니다
- ErrorCode와 ErrorResponse, ApiResponse를 이용하여 응답 값을 통일하였습니다
- 기존 Post 요청시 Restful 하지 않았던 부분을 개선하였습니다.
   - 쿼리파라미터로 받던 요청 -> RequestBody로 수정
   - hateoas 제공
 - 컨트롤러에서 생성하던 id를 도메인 객체에서 생성하도록 수정하였습니다.
 - LocalDate 타입의 경우 양식이 까다로워 String으로 받고 LocalDateTime으로 변경하는 클래스를 추가하였습니다.
 -  명확한 의미와 보안적인 부분을 해결하여 버저닝을 사용하지 않고 `api'와 'view'로 분리하였습니다. 
 - 쿼리 파라미터의 개수가 늘어나면 코드의 가독성이 떨어져 이를 `@ModelAttribute`로 해결하였습니다.

2023-08-10 14:08 UTC, WooSungHwan approved these changes
별이님 과제하시느라 수고 많으셨습니다. 지금 JPA까지 온 시점에서 이 voucher 과제를 한번 돌이켜보는 것도 좋다고 생각합니다. 이땐 왜이렇게 생각했지? jpa가 없어서 좀 힘들었었는데 그래도 나름대로 잘 했었네 등등 자기 스스로의 피드백이 어떨때는 자신감을 좀더 많이 채워주기도 하니까요. 끝까지 따라가시는 모습 보기좋고 이후에는 다음 과제에 좀더 집중해서 성장된 모습과 코드로 보여주셨으면 좋을 것 같습니다. 

수고 많으셨습니다.

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/common/util/TestGeneratorImp.java
> +}
테스트면 테스트 패키지 쪽에 있어야될것 같은데요?

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/common/util/TestGeneratorImp.java
> +}
테스트할때는 Generator에 의존해서 하기보다는 임의의 id값 넣어주고 그 id인지 체크하면 되지 않나 싶습니다!

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/common/exception/handler/RestControllerExceptionHandler.java
> +    private final HttpStatus HTTP_STATUS_OK = HttpStatus.OK;
왜 얘만 따로 변수로 빼둔걸까요? 이미 HttpStatus라는 상수가 있는데 그럴 필요는 없어보여요.

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/common/exception/handler/RestControllerExceptionHandler.java
> +
이 위치정도에 RuntimeException 하나 러프하게 잡아주면 좋을 것 같습니다.

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/common/exception/handler/RestControllerExceptionHandler.java
> +    }
null pointer exception은 명백한 서버개발자 과실인데 ok 보다는 500 대 에러가 맞는 것 같습니다~

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/common/exception/handler/RestControllerExceptionHandler.java
> +public class RestControllerExceptionHandler {
해당 클래스 전체적으로 ErrorResponse 에 있는 HttpErrorCode를 바라볼 것인지 ResponseEntity 의 status를 바라볼것인지 애매하게 짜여있는 것 같습니다.
- http status가 모두 200 이어서 이를 무시하고 error response의 상태코드를 본다거나
- http status와 error response의 상태코드를 맞춘다거나

두가지 경우의수가 나와야하는데 어떤건 맞춰있고 어떤건 맞춰있지않고 좀더 짜임새 있게 구성해야 하지 않나 싶어요.

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/voucher/model/VoucherCreator.java
> +    //private VoucherCreator() { }
주석 삭제!

2023-08-10 14:08 UTC, WooSungHwan commented on src/main/java/com/prgrms/voucher/model/voucher/Voucher.java
> +        this.createdAt = generator.makeDate();
아하 ㅎㅎ 좋습니다. 직접 구현해보시면 나중에 이해하는데 확실히 도움이 되실겁니다.

2023-08-16 07:08 UTC, merged