[4기 - 윤영운] SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #857
Opened 2023-07-22 12:00 UTC by young970

## 📌 과제 설명 
- (GET)    /api/vouchers : 모든 바우처들 조회
- (POST) /api/vouchers : 바우처 생성
- (GET)   /api/vouchers/{id} : id로 바우처 조회
- (GET)   /api/vouchers/type/{type} : 바우처 타입으로 바우처 조회
- (DELETE) /api/vouchers/{id} : id로 바우처 삭제

## 👩‍💻 요구 사항과 구현 내용 
**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
    - [x]  조회페이지
    - [x]  상세페이지
    - [x]  입력페이지
    - [x]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 REST API를 개발
    - [x]  전체 조회기능
    - [x]  조건별 조회기능
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능

## ✅ PR 포인트 & 궁금한 점 
이번 팀미팅 때 멘토님께서 말씀하신 것을 3주차 미션에 반영해 보았습니다. 
controller와 service의 request dto를 따로 만들어 의존 방향을 맞추고자 하였습니다. response DTO는 원래 controller가 service를 의존하는 것이 맞다고 생각하여 따로 분리하지 않았습니다. 
제가 제대로 이해하고 적용한게 맞는지 궁금합니다. 혹시 response DTO도 따로 분리를 해야 할까요??

2023-07-23 06:11 UTC, devYSK requested changes
안녕하세요 영운님 과제하느냐 고생 많으셨습니다


* controller와 service의 request DTO를 따로 만들어 의존 방향을 맞추고자 하였습니다.
 response DTO는 원래 controller가 service를 의존하는 것이 맞다고 생각하여 따로 분리하지 않았습니다.
제가 제대로 이해하고 적용한게 맞는지 궁금합니다. 혹시 response DTO도 따로 분리를 해야 할까요??

-> 그렇게 생각할수도 있습니다만, 응답 스펙이 바뀌었을때도 생각해보면 좋을거같아요
결국 컨트롤러와 서비스의 dto를 다르게 운용한다는것은 의존과 관련이 있는데 그 둘도 같이 사용한다면 서로 변경에 취약해지지 않을까 생각합니다.
현재는 일단 이대로 사용하다가 분리가 필요하다면 그때 가서 분리해도 된다고 생각합니다



* 저번 흑구멘토님의 코멘트를 통해 Nested Loop join 알고리즘에 대해 알게 되었습니다. 해당 알고리즘에 대해 알게 되며 들었던 생각은 join을 사용하는 것 보다 트랜잭션으로 묶어 쿼리를 여러번 날리는 것이 성능이 더 좋을 것 같다는 생각이 들었습니다. 혹시 이 생각이 맞을까요??

일단 DBMS마다 조인 알고리즘을 지원하는 방식이 달라요.
그리고 쿼리를 여러번 날리게 된다면 비용에 대해 고려해봐야합니다.
네트워크 오버헤드, 메모리, 쿼리 파싱 및 최적화 후 결과 전송 후 다시 반복하게 되겠죠

반면에 조인은 잘 사용한다면 데이터베이스 자체에서 테이블간에 효율적으로 처리할 수 있어요

때문에 일반적으로는 간단한 조인이라면 데이터베이스에 조인을 맡기는게 더 효율적일 수 있지요 
매우 큰 테이블 또는 여러 테이블들을 join해야 하는경우에는 쿼리를 쪼개 여러번 날리는것이 더 효율적일때도 있어요
항상 트레이드 오프라고 생각해요

그러니 여러 요인을 고려해서 상황에 맞게 최적의 방법을 고려해보세요

2023-07-23 06:11 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/service/mapper/ServiceVoucherMapper.java
> +    Voucher serviceDtoToVoucher(ServiceCreateVoucherRequest request);
java코드를 String으로 집어넣으면 어떤 단점이 있을까요?

2023-07-23 06:11 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/controller/dto/CreateWalletControllerRequest.java
> +        this(UUID.randomUUID(), memberId, voucherId);
여기서 왜 UUID를 생성하는지 궁금합니다!

2023-07-23 06:11 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/service/WalletService.java
>      @Transactional
```java
@Transactional(readonly=true)
```
라는 옵션에 대해서도 알아보세요

2023-07-24 06:50 UTC, WooSungHwan requested changes
영운님 코드가 많이 좋아졌군요 ㅎㅎ
하지만 3주차는 오프라인으로 만나기전까진 approve를 드릴순 없을 것 같습니다 ㅎㅎ
그때 좀더 이야기할 수 있는 부분이 있을 것 같습니다. 우선 영수님과 제가 드린 리뷰내용 토대로 수정해보고 계시고 수요일에 뵈어요 ㅎㅎ

2023-07-24 06:50 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherApiController.java
> +    @GetMapping("/type/{type}")
(첨언)
API로 만든순간부터 이 조건을 다른 api의 기능으로 포함할 수 있는지에 대한 검토가 필요합니다.

2023-07-24 06:50 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherApiController.java
> +    }
api 이렇게 열어두면 rest controller라서 endpoint에 요청 도착하면 repository findAll까지 바로 실행될겁니다.
해당 이슈를 어떻게 제한할 수 있을지 고민해보시기 바랍니다. (hint: 검색필터)

hint를 토대로 저 위에 있는 이슈도 함께 해결해보세요.

2023-07-24 06:50 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherApiController.java
> +    }
보통 이렇게 만들면 ok(200)을 내려주기도 하지만 created(201)을 내려다주기도 합니다.
여기서 200과 201에 어떤 차이가 있는지 확인해보시고
ReponseEntity.created() 안에 들어가는 파라미터에 대해서 한번 보시면 좋을 듯 합니다.

2023-07-24 06:50 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherApiController.java
> +    }
CreateVoucherControllerRequest 해당 클래스에 대한 유효성 검사가 전혀 없습니다. API 엔드포인트로 기능을 노출했을 경우에는 최대한 많은 예외케이스에 대해서 고민해봐야합니다. 어떤 요청이 무작위로 날라올지도 모르거든요. 최악의 요청은 HTTP method, uri가 일치하지만 유효성 검증이 전혀 없어 null과 double의 기본값인 0.0이 디비로 들어가버릴 수 있겠네요.

2023-07-24 06:50 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherApiController.java
> +    @GetMapping("/type/{type}")
참고로 pathVariable에 들어갈 수 있는 변수는 식별자로 구성되어야 좋습니다.

2023-07-24 06:50 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/voucher/controller/VoucherApiController.java
> +    @GetMapping("/type/{type}")
fixed로 어떤 바우처인지 특정할 수 있을까요?

2023-07-24 06:50 UTC, WooSungHwan commented on src/main/java/org/prgrms/kdt/global/ApiExceptionHandler.java
> +public class ApiExceptionHandler extends ResponseEntityExceptionHandler {
전반적으로 RuntimeException을 상속한 커스텀 클래스만 선언되어있는데요. 실행중에 발생할 수 있는 Unchecked 와 Checked모두 기재해주는게 좋아요.
Exception과 RuntimeException까지 설계해봅시다. 그거 터지면 나 자바 스프링으로 개발했다고 티내는 에러 납니다. 어쩌면 디비 뭐쓰는지까지 노출됩니다.

2023-07-29 13:32 UTC, young970 commented on src/main/java/org/prgrms/kdt/global/ApiExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(getErrorResponse(500, e));
NotUpdateException은 클라이언트의 요청은 올바르나 데이터 베이스의 update가 제대로 수행되지 않을 경우 발생하는 커스텀 예외로 서버쪽 오류라고 판단되어 500으로 처리하였습니다.

2023-07-29 13:34 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/service/mapper/ServiceVoucherMapper.java
> +    Voucher serviceDtoToVoucher(ServiceCreateVoucherRequest request);
createDiscountPolicy 등의 메서드 이름을 rename 시 인텔리제이가 String 부분은 인식하지 못해 
변경 사항이 제대로 반영되지 않아 문제가 될 것 같습니다.

2023-07-30 04:53 UTC, devYSK commented on src/main/java/org/prgrms/kdt/global/ApiExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(getErrorResponse(500, e));
@young970 

한번 더 고민해볼 포인트가 생겼네요.
500에러를 사용자에게 보여줘야할지? 감춰야할지? 어떤것들을 더 고려해볼 수 있을까요?

2023-08-01 14:11 UTC, young970 commented
# 피드백 반영사항
- 에러 핸들링 케이스 추가
- ErrorResponse 상세화
- 서버 에러 발생시 로그 남기기
- DTO 이름변경
- Mapper에 존재하던 String으로 표시하던 자바 코드들 제거
- 전체 조회 API 페이징 조회로 변경 (findAllBy)
- 바우처 타입 조회 API를 findAllBy에 적용 (검색 필터)
- createVoucher 응답 상태코드 201로 변경
- PK값 순차적으로 생성되는 UUID로 변경

2023-08-02 04:51 UTC, devYSK approved these changes

2023-08-02 04:51 UTC, devYSK commented on build.gradle
> +    //타입리프
오타나신거같아용

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/global/ApiExceptionHandler.java
> +        int statusCode = HttpStatus.BAD_REQUEST.value();
메서드로 뺄 수 있을것 같습니다

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/global/ApiExceptionHandler.java
> +    @ExceptionHandler({NullPointerException.class, InvalidInputException.class, InvalidDiscountException.class, MissingRequestHeaderException.class, HttpMessageNotReadableException.class,
NPE는 서버측 잘못일수도 있다고 생각해요

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/global/ErrorResponse.java
> +public record ErrorResponse(int statusCode, String detail, String instance, String time) {
필드가 많아지니 개행할 위치가 애매해지죠.

가독성을 위해
```java
public record ErrorResponse(
    int statusCode, 
    String detail, 
    String instance, 
    String time
) { }
```
로 둬도 좋을것 같아요.

instance라는 필드는 애매모호해보입니다. 명확하게 바꾸는건 어떨까요?

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/global/GeneratorImp.java
> +public class GeneratorImp implements Generator{
Imp는 무엇인가용

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/member/service/mapper/ServiceMemberMapper.java
> +}
이 클래스는 왜 Mapstruct를 사용하지 않은건지 궁금합니다~

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/controller/dto/CreateVoucherApiRequest.java
> +                                      @NotNull double discountAmount) {
primitive type은 null을 가질 수 있을까요?
그렇다면 `@Notnull`이 필요할까요? 
초기화 되지 않는다면 어떤 값을 가질까요?

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/controller/dto/SearchApiRequest.java
> +    @Min(0)
클라이언트에 대해 예외를 반환한다면, 메세지도 같이 적어주면 좋을거같아요

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/controller/dto/SearchApiRequest.java
> +        this.offset = (page - 1) * recordSize;
page가 음수가 들어온다면 ..!?

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/dao/JdbcVoucherRepository.java
> +        return jdbcTemplate.query(query.toString(), voucherRowMapper, queryArgs.toArray());
querybuilder라는 객체를 만들어보는것은 어떨까요?

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/dao/MemoryVoucherRepository.java
> +        throw new RuntimeException("지원이 중지된 기능입니다.");
RunTimeException말고 명확한 예외를 만들어 써주는것이 더 좋을거같아요.
팀원들끼리 약속도 될 수 있구요. 

`@Deprecated` 어노테이션에 대해서도 알아보세요

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/service/dto/SearchRequest.java
> +        this.offset = (page - 1) * recordSize;
```java
new SearchRequest(-999999, -10, ~,~)
```

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/service/dto/SearchRequest.java
> +public class SearchRequest {
Pageable 객체에 대해 알아보세용

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/voucher/service/mapper/ServiceVoucherMapper.java
> +        return new Voucher(generator.generateId(),
한칸 개행해주면 더 읽기 좋을것같아요

2023-08-02 04:51 UTC, devYSK commented on src/main/java/org/prgrms/kdt/wallet/dao/WalletCommandRepository.java
> +    Wallet insert(Wallet wallet);
Wallet을 집어넣는다?

Voucher랑 target을 집어넣는것도 어색하진 않을거같은데용

2023-08-02 04:51 UTC, devYSK commented on src/test/java/org/prgrms/kdt/voucher/dao/MemoryVoucherRepositoryTest.java
> +        Voucher savedVoucher2 = new Voucher(UUID.randomUUID(), VoucherType.FIXED, VoucherType.FIXED.createPolicy(30.0), LocalDateTime.now());
voucherSource를 이용할 수 있을것 가아용

2023-08-02 05:08 UTC, young970 commented on src/main/java/org/prgrms/kdt/member/service/mapper/ServiceMemberMapper.java
> +}
Mapstruct에서 generator를 주입받아 사용하기 위해 해당 클래스를 추상 클래스로 만들어 시도하였으나
런타임에 자동으로 생성되는 해당 추상 클래스의 구현체에서 기본 생성자 외에는 만들어지지가 않아서 (한마디로 주입을 못받아서) 

이 부분만 Mapstruct를 사용하지 않는 방식으로 결정했습니다...

2023-08-02 05:28 UTC, young970 commented on src/main/java/org/prgrms/kdt/voucher/controller/dto/SearchApiRequest.java
> +        this.offset = (page - 1) * recordSize;
해당 page필드에 @Min(1) 어노테이션을 달아두었기에 음수가 들어오는 것을 막아두었습니다!!

2023-08-10 13:28 UTC, WooSungHwan approved these changes
영운님 과제하시느라 수고 많으셨습니다. 해당 과제는 merge 해주시고 리뷰가 좀더 필요하다고 생각되는 부분이 있으시면 짚어주세요. 근데 개인적으로는 voucher 과제는 여기서 닫고 이후 과제에서의 포커스를 좀더 집중하는게 좋다고 생각합니다. 이 부분은 이해하셨으리라 생각합니다. voucher 과제하시느라 수고 많으셨어요 ㅎㅎ 이제 좀더 쉽게 쉽게 결정하고 코드를 작성하실 수 있을 거라고 생각이 됩니다. 많이 성장하셨네요. 바우처 과제는 처음 내가 스스로의 지식으로 짰던 첫번째 코드라고 인식하고 가져가시고 이후 많이 돌아보세요. 시공간을 초월한 코드리뷰를 해보면서 스스로의 성장을 느껴보셨으면 좋겠습니다.

수고 많으셨습니다.

2023-08-10 13:57 UTC, merged