[5기 - 이한나] SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #874
Opened 2023-10-13 23:26 UTC by annahxxl

## 📌 과제 설명 

(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을  만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 

### config
- 프로퍼티들을 세팅하고 있습니다
### controller
- shell을 통해 command에 따라 적절한 서비스를 실행시킵니다
### domain
- 리소스 객체입니다
### infra
- 앱 실행 시 실행 가능한 commands 출력 및 입력을 위한 클래스가 선언되어 있습니다
### repository
- 지정된 스토리지로 데이터를 읽고 씁니다
### service
- 비지니스 로직이 작성되어 있습니다
### util
- 로깅, 아이디 주입기, CSV 맵퍼 등이 선언되어 있습니다

## ✅ PR 포인트 & 궁금한 점 
- 스프링 프레임워크로 프로젝트 한 경험이 없습니다. 그래서 전반적으로 안좋은 습관이나 잘못 사용한 어노테이션, 일반적인 컨벤션이 존재하는데 안지켜진 부분 등등도 함께 피드백 주시면 감사하겠습니다.
- 테스트 작성이 아직 미숙한데, 간단한 예제지만 테스트코드에 대해서도 도움 주시면 감사하겠습니다.

감사합니다!

2023-10-15 16:26 UTC, cloudwi commented on build.gradle
> +    implementation 'org.springframework.shell:spring-shell-starter:3.0.6'
spring-shell을 사용 하셨군요.

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/controller/VoucherController.java
> +        log.info(LoggingUtil.createRunLogMessage("exit"));
매서드가 실행될때 log를 남기는 작업이 중복되고 있다고 생각해요. 
관심사를 분리할 수 있을까요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/controller/VoucherController.java
> +public class VoucherController {
VoucherController보단 VoucherShellController 조금더 명확한 이름이지 않을까요?
한나님은 어떻게 생각하시나요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/controller/VoucherController.java
> +        List<Voucher> vouchers = voucherService.getAll();
getAll 과 getAllVouchers 중 어떤 이름이 명확해 보이시나요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +        return new Customer(UUID.fromString(parts[0]), parts[1], parts[2].equals("1"));
csv 파일 순서에 종속적이라고 생각하지 않나요?

csv 파일 입력 순서에 종속적이지 않으려면 어떻게 하면 좋을까요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
> +    private final long amount;
과제 요구사항에는 없지만 PercentDiscountVoucher에 amount가 100을 초과할 수 있나요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
> +    private final UUID id;
id에 final이 붙어 있어요. 

PercentDiscountVoucher 가 생성됨과 동시에 id가 할당되어야 할까요?
id 값은 객체각 저장공간에 저장될때 할당되어도 좋다고 생각해요.

한나님은 어떻게 생각하나요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
> +            System.out.println((vt.ordinal() + 1) + ". " + vt.description + (vt.ordinal() == 0 ? " (default)" : ""));
enum의 vouchType순서에 종속적이라고 생각해요.

위와 동일하게 순서에 종속적이지 않으려면 어떻게 해야할까요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
> +    public abstract Voucher createVoucher(UUID id, Long amount);
VoucherType enum이 createVoucher하는 기능을 가지고 있는것이 적절할까요?

제 생각은 다른 VoucherType은 Voucher의 하나의 Type인데 생성하는 것은 더 넓은 범위를 담당하는 것으로 보여요.

한나님은 어떻게 생각하나요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
> +    public abstract Voucher createVoucher(UUID id, Long amount);
위의 new 코드도 한번 봐주세요!

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
> +                .filter(vt -> vt.id == id)
vt.id를 꺼내서 확인하는 방법보단 vt.isSameId(id) 처럼 캡슐을 유지하고 처리하는 방법은 어떤가요?

한나님의 생각을 알려주세요!

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/repository/customer/FileCustomerRepository.java
> +            throw new RuntimeException("Failed to initialize customer repository", e);
IOException은 체크드 예외인것 같아요. 따라서 catch 로그를 남기는 방법은 어떤가요?

사용자의 어떤 입력에서 예외가 발생했어요! 라던지 

이슈를 잡을 수 있는 구체적인 증거를 남기는건 어떤가요?

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +        Voucher voucher = voucherType.createVoucher(idProvider.generateId(), amount);
위에서 말씀드린것 처럼 VoucherId는 언제 부여하면 좋을까요? 라는 질문을 하고 싶어요!

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +    public List<Voucher> getAll() {
네이밍은 위에서 말씀 드린 것 처럼 이야기 해보아요!

2023-10-15 16:26 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/util/CsvMapper.java
> +            throw new RuntimeException("Failed to read CSV file", e);
이곳에서도 로그를 남겨보는 건 어떤가요?

상세한 리뷰는 위에 참고 부탁드립니다.

2023-10-15 16:26 UTC, cloudwi commented on src/test/java/com/programmers/vouchermanagement/VoucherManagementAppTests.java
> +    @Test
불필요한 Test는 삭제하는 것이 어떨까요?

2023-10-15 16:26 UTC, cloudwi commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
> +    @Test
어떤것을 테스트하기 위해서 테스트하는 것인가요? 이름을 작성해보세요!

2023-10-15 16:26 UTC, cloudwi commented on src/test/java/com/programmers/vouchermanagement/service/VoucherServiceTest.java
> +        assertThat(createdVoucher.getAmount()).isEqualTo(amount);
바우처의 id와 금액으로 검증하는 것은 좋으나 create가 잘되었는지 보다 제대로 검증하기 위해서는 Type과 비교해야한다고 생각해요.

한나님은 어떻게 생각하나요?

2023-10-15 16:30 UTC, cloudwi commented
한나님 과제 하신다고 고생하셨습니다.😀

전반적으로 잘 작성된 코드라고 생각합니다.

`스프링 프레임워크로 프로젝트 한 경험이 없습니다. 그래서 전반적으로 안좋은 습관이나 잘못 사용한 어노테이션, 일반적인 컨벤션이 존재하는데 안지켜진 부분 등등도 함께 피드백 주시면 감사하겠습니다.`

답변 : 
lombok의존성이 높아보이세요. 다음에는 lombok없이 코딩해보시는 건 어떤가요?

list.get하는 코드가 많이 보였던것 같아요. 이러한 코드는 가독성이 굉장히 떨어진다고 생각해요. list보단 객체를 활용하는 것이 어떤가요?

enum이 굉장히 많은 책임을 가지고 있는 것 같아요. 왜 enum이 많은 기능을 소화하고 있는지 고민해보고 이야기 해봐요!

`테스트 작성이 아직 미숙한데, 간단한 예제지만 테스트코드에 대해서도 도움 주시면 감사하겠습니다.`
테스트 케이스를 전반적으로 미숙하다는 생각이 들었어요.

한나님이 생각하는 과제의 핵심기능이 무엇인가요?

저는 핵심기능만 제대로 테스트해도 좋은 테스트라고 생각합니다.

2023-10-16 15:56 UTC, aegis1920 requested changes
안녕하세요 멘토 빙봉입니다 🙂 

코멘트 남겼으니 확인해주세요~

2023-10-16 15:56 UTC, aegis1920 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter'
별건 아니지만 implementation는 implementation끼리 모아두어도 좋을 것 같습니다

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/VoucherManagementApp.java
> +}
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij를 사용하고 계시다면 파일을 저장할 때마다 개행을 자동으로 넣어주도록 할 수 있습니다! (Preferences -> Editor -> General -> Ensure every saved file ends with a line break)

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    public String toString() {
롬복 의존성은 있던데 `@ToString`을 사용하지 않은 이유가 있으실까요?

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    private UUID id;
Customer 객체에서 id에서 UUID를 사용하신 이유가 무엇인가요? UUID를 private key로 사용하면 어떤 점이 좋고 어떤 점이 안 좋을까요?

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +public interface Voucher {
Voucher라는 인터페이스는 id와 amount를 get만 하는 역할을 가진 인터페이스라고 봐도 될까요? 그렇다고 한다면 get 역할만 하는 인터페이스가 의미 있을지 고민해보시면 좋겠습니다!

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
> +            System.out.println((vt.ordinal() + 1) + ". " + vt.description + (vt.ordinal() == 0 ? " (default)" : ""));
ordinal은 Enum 순서에 종속적이라서 가급적 피해야 합니다

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/infra/ApplicationListenerImpl.java
> +public class ApplicationListenerImpl implements ApplicationListener<ApplicationStartedEvent> {
단순히 출력하기 위함이라면 main 시작하기 전에 출력 메서드만 넣었어도 됐을 것 같은데 이벤트로 구성하신 이유가 있을까요? (이와 별개로 SpringApplicationEvent을 상속하는 이벤트 클래스들이 어떤 차이가 있는지 살펴보는 것도 좋을 것 같습니다!)

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
> +@Profile("local")
`@Profile`을 작성하신 이유가 있을까요?

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
> +public class MemoryVoucherRepository implements VoucherRepository {
개발자에 너무 특화된 클래스명이 아닐까 싶습니다ㅎㅎ 다른 걸로 바꿔보는 건 어떨까요?

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/service/CustomerService.java
> +        return customerRepository.findAllBlacklisted();
customerRepository.findAllBlacklisted를 호출하는 것 뿐인데 서비스 레이어가 왜 있어야 할까요? 서비스 레이어가 없으면 안될까요?

2023-10-16 15:56 UTC, aegis1920 commented on src/main/resources/logback.xml
> +    <root level="warn">
root level을 warn으로 지정하신 이유가 있을까요?

2023-10-16 15:56 UTC, aegis1920 commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
> +class CustomerServiceTest {
성공 케이스가 아닌 예외 케이스에 대해서 테스트 코드를 작성해보세요!

Customer의 이름은 무한정 입력해도 될 지, 데이터를 저장하는데 UUID가 중복되지는 않을 지 등등 예외 케이스에 대한 로직 보강도 필요할 것 같습니다!

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
> +            System.out.println((vt.ordinal() + 1) + ". " + vt.description + (vt.ordinal() == 0 ? " (default)" : ""));
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/22311557/d1448c97-2d26-4eaf-a46b-f0453a8477b1)
여러 곳에서 출력을 하고 있는데요. 출력하고 있는 역할을 해당 클래스에서 하는 게 맞는지 생각해보세요!

2023-10-16 15:56 UTC, aegis1920 commented on src/main/resources/customers.csv
> +8f14e45f-ea60-4a45-b2db-efb6c4490a03,John Doe,1
boolean 값을 true, false가 아닌 1과 0으로 저장하신 이유가 궁금합니다!

2023-10-16 15:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
> +        return new ArrayList<>(storage.values());
ArrayList가 아닌 stream()의 toList를 사용하면 불변 리스트가 되어 조회할 때 좀 더 안전하게 조회할 수 있습니다. (조회 후, 리스트 수정 방지)
```suggestion
        return storage.values()
        .stream()
        .toList();
```

2023-10-17 06:32 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/controller/VoucherController.java
> +        List<Voucher> vouchers = voucherService.getAll();
@cloudwi 서비스명에 도메인 객체 이름이 포함되어 있어서 없어도 명확하다 생각했었는데, 다시 생각해 보니 항상 도메인 객체에 대한 것만 조회가 있다고 보장할 수 없는 것 같아요. 그래서 getAllVouchers가 더 명확하다는 생각이 듭니다.

2023-10-17 06:50 UTC, annahxxl commented on src/main/resources/customers.csv
> +8f14e45f-ea60-4a45-b2db-efb6c4490a03,John Doe,1
@aegis1920 자주 사용했던 DBMS가 mysql인데 데이터를 tinyint 값으로 저장해서 1, 0으로 해보았습니다,, true, false가 명확한 것 같아 수정하도록 할게요!

2023-10-17 06:56 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
> +@Profile("local")
@aegis1920 과제 요구사항에 있어서 사용해 보았습니다!

2023-10-17 07:34 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
> +    private final UUID id;
@cloudwi 아이디를 어디서 할당할지는 요구사항에 따라 달라질 수도 있다고 생각합니다! 그렇지만 아이디 값은 최대한 불변일 수 있는 값이 할당되는 게 좋을 것 같다는 생각이 들어요. 그래서 아이디를 할당하는 역할은 레포가 더 적합한 것 같습니다. 멘토님 말씀대로 저장 공간에 저장될 때 할당되어도 좋은 것 같습니다!

2023-10-17 08:54 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/infra/ApplicationListenerImpl.java
> +public class ApplicationListenerImpl implements ApplicationListener<ApplicationStartedEvent> {
@aegis1920 앱 생명주기 어노테이션에 대해 보다가 한 번 사용해 보았습니다! 근데 사실 그냥 출력해도 충분한 거 맞습니다🥹 제가 괜히 복잡성을 높인 것일까요•••? 사용하면서 저는 나름 명시적이라고 생각하였습니다•••

2023-10-17 09:00 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    private UUID id;
@annahxxl 앗 UUID를 사용한 이유는 그냥 강의와 동일하게 필드를 가져가느라 그랬습니다..! private으로 사용할 때의 단점은.. 테스트하기 어려운 것 같습니다?! 🤔

2023-10-17 09:01 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    public String toString() {
@aegis1920 있는지 몰랐습니다!😇

2023-10-17 10:30 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +public interface Voucher {
@aegis1920 다른 타입의 바우처더라도 동일한 메서드를 사용할 수 있다는 걸 명시함으로써 보장하고 싶었습니다..! 저는 이 정도로도 의미가 있다고 생각했는데, 멘토님의 생각이 궁급합니다!

2023-10-17 10:39 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/service/CustomerService.java
> +        return customerRepository.findAllBlacklisted();
@aegis1920 현재 코드로썬 서비스 레이어가 딱히 필요한 이유가 없는 것 같습니다..! 그렇지만 앞으로 추가될 수 있는 비지니스 로직 작성을 고려하여 생성해두긴 했습니다

2023-10-17 10:56 UTC, annahxxl commented on src/main/resources/logback.xml
> +    <root level="warn">
@aegis1920 강의 내용 따라가다가 별도로 수정 못했는데, info 레벨 정도로 찍는게 좋을 것 같습니다!

2023-10-17 11:02 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
> +public class MemoryVoucherRepository implements VoucherRepository {
@aegis1920 메모리말고 어떤 게 있을까요,,? 당장은 안떠오르는데••! 조금 더 고민해보겠습니다.. 그나마 생각난건 테스트레포지토리..?🥲

2023-10-17 11:18 UTC, annahxxl commented
@cloudwi @aegis1920 

리뷰 감사합니다! 리뷰 반영, 코멘트 남겨두었습니다!
여유 있으실 때 확인해 주시고, 또 개선할 게 있다면 알려주세요 🙇‍♀️🙇‍♀️

추가로,
- 테스트 코드 수정 및 리뷰 반영
- 코드 개선 (UX 개선, 동시성 고려, 에러 메세지 카탈로그화..? 등등)

위의 작업들은 아직 반영이 안 되어 있습니다!! 
리뷰 맛집이라 쬐금 걸리네요😋 반영되면 새로 코멘트 남기거나 새로운 PR 날리겠습니다!

2023-10-18 00:55 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    public String toString() {
@aegis1920 롭복 사용하도록 수정해 두었는데,, 순환참조에 대해 주의해야 하는군요..! 다음부턴 신경쓰도록 하겠습니다

2023-10-18 14:01 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    private UUID id;
UUID의 장점과 단점도 함께 말씀해주시면 좋을 것 같습니다. 객체의 id 값으로 사용할 때 타입을 여러 가지로 줄 수 어떤 방법들이 있는지도 보면 좋을 것 같아요

2023-10-18 14:14 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +public interface Voucher {
한나님이 생각하시는 인터페이스란 무엇인가요? 인터페이스가 동일한 메서드를 사용할 수 있다는 걸 명시하기 위해서 쓰는 것인지 생각해보면 좋을 것 같습니다. 지금 이용권이라는 도메인 아래 고정 금액 이용권과 퍼센트 할인 이용권이 있는데요. 이용권이라는 도메인 자체가 인터페이스라는 타입이 되기에는 부적절해보입니다. 타입이 아닌 도메인이 되어야하기에 Voucher를 추상클래스로 만들거나 Voucher 클래스를 따로 생성해서 PercentDiscountVoucher가 Voucher 필드를 갖고 있는 구조가 좀 더 어울려보입니다.

2023-10-18 14:16 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/infra/ApplicationListenerImpl.java
> +public class ApplicationListenerImpl implements ApplicationListener<ApplicationStartedEvent> {
엇 아뇨! 단순히 궁금해서 여쭤봤습니다ㅎㅎ '어노테이션을 보다가 한 번 사용해봤다'는 태도가 멋지군요 👍

2023-10-18 14:16 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
> +@Profile("local")
이 부분은 제가 잘못 이해했던 부분입니다. 설명 감사합니다! 🙇

2023-10-18 14:17 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
> +public class MemoryVoucherRepository implements VoucherRepository {
요구사항에 그대로 메모리라고 나와있어서 메모리라고 적어둬도 될 것 같습니다! 수정하지 않으셔도 됩니다!

2023-10-18 14:19 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/service/CustomerService.java
> +        return customerRepository.findAllBlacklisted();
설명 좋네요!

2023-10-18 14:20 UTC, aegis1920 commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
> +class CustomerServiceTest {
이 부분은 미션2에서 해도 무방할 것 같습니다!

2023-10-19 20:50 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    private UUID id;
@aegis1920 이번 RBF에서 정리해 보았습니다! [UUID vs Sequential ID as Primary key](https://www.notion.so/backend-devcourse/UUID-vs-Sequential-ID-as-Primary-key-8f4acb0d6b45491a8e3f4aac4e89c9d1?pvs=4)

2023-10-19 21:22 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +public interface Voucher {
@aegis1920 아..! 추상클래스 생각을 못했네요.. 이론 공부할 때 분명 인터페이스와 추상클래스 차이점에 대해 학습도 했었는데 정작 코드 작성할 때 적절하게 활용을 못했습니다. 각 바우처들이 공통 필드와 로직을 포함하고 있기 때문에, 멘토님 말씀처럼 인터페이스보단 추상 클래스가 더 적절해 보입니다. 수정했습니다!!

2023-10-22 13:15 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    private UUID id;
잘 정리해주셨네요! 👍

2023-10-22 13:17 UTC, aegis1920 approved these changes
피드백 반영하시느라 고생 많으셨습니다! 이만 머지할게요!

2023-10-22 13:17 UTC, merged