[5기 박영재] SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #880
Opened 2023-10-15 18:01 UTC by park0jae

## 📌 과제 설명 
## SpringBoot Part1 Weekly Mission

(기본) **바우처 관리 애플리케이션**

- [X]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [X]  바우처 관리 Command-line Application을  만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [X]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [X]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [X]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [X]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
- [X]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [X]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [X]  고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [X]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
### common
- MessageConverter : messages.properties 로 관리하는 메시지 정보를 반환
- Response : 컨트롤러 반환 포맷 형식
- MenuHandler : 컨트롤러의 메서드 호출 및 출력 부분 담당

### controller
- VoucherController : VoucherService 로직 호출
- CustomerController : Customerservice 로직 호출 

### domain
- customer : 회원 
- customerType : 회원의 타입 enum
- Voucher 인터페이스와 Percent , FixedVoucher 구현체 클래스
- VoucherType : 바우처 타입 enum

### dto
- 계층 간 데이터 전송을 위해 도메인 모델 대신 사용되는 객체

### exception
- ExceptionHandler : 예외처리를 위한 클래스

### repository
- CustomerRepository
- VoucherRepository 인터페이스와 File, MemoryVoucherRepository 구체 클래스

### validator
- 입력 값 검증을 위한 클래스

## ✅ PR 포인트 & 궁금한 점 
1. 패키지 구조 관련하여, 추후 이어지는 미션을 위해 코드가 추가되는 것을 고려하면 계층형보다 도메인형의 패키지 구조가 좋을지 궁금하고, 기능별로 패키지를 잘 나눈 것인지 궁금합니다.
2. yml 파일에 어떤 설정을 할 수 있을지 고려해보라는 요구사항이 있었는데 Profile과 messages.properties를 적용해보는 것 외에 생각이 잘 나지 않았습니다. 추가로 적용하면 좋은게 있을까요 ?
3. 로깅 설정을 하였지만, 예외 부분에서만 error 로그를 설정한 것이 전부여서 혹시 다른 부분에도 로그를 적용한다면 어느 부분에 어떤 레벨로 적용해야 할까요 ?
4. 요구사항들을 구현하다보니, 회원 추가나 회원 타입 (일반 회원, 블랙리스트 회원)등 요구사항을 넘어서 추가 구현한 부분들이 꽤 있는데, 요구사앙을 너무 멀리까지 본 것인지... 궁금합니다 
5. 컨트롤러에서 도메인에 의존하지 않고자 Dto 객체를 이용했는데 적절한지 궁금하고, 바우처나 회원의 정보를 문자열로 반환해주는 getInfo() 메서드를 기존의 도메인 내에 작성했다가 컨트롤러에서 Response 타입으로 반환해줄때 해당 메서드를 사용하게 되면 domain 패키지를 의존하게 된다고 생각해서 Dto 객체로 getInfo 메서드를 옮겼는데, 이러한 방식이 괜찮은지 궁금합니다.
6. 검증하는 부분에서, 입력값에 대한 잘못된 타입의 입력(숫자를 입력해야 하는데, 문자를 입력하는 경우)에 대한 검증은 InputValidator에서 진행하고 값(discount 가 음수인 경우 X)에 대한 검증은 컨트롤러에서 진행하며 enum에 대한 검증은 enum 자체에서 예외를 던지도록 작성했는데 잘못된 부분이 있는지 궁금합니다. 
7. 파일에 Voucher를 저장할 때 필드값들을 저장하기 위해 getter 메서드들을 사용하는데 Repository에서는 Voucher 인터페이스를 의존하고 있어 구현체 내부의 getter는 사용할 수 없다고 판단하여 Voucher 인터페이스 내의 getter 메서드들을 선언해주고 오버라이딩 하는 방식으로 작성했는데 괜찮은 방법인지, 아니라면 파일에 다른 방식으로 저장해야하는지 ? 궁금합니다.
8. 메시지를 출력할 때 메시지 자체를 넘기는 것이 아니라 messages.properties 파일을 통해 메시지들을 관리하고 MessageSource를 통해 가져오도록 구현했는데 불필요한 작업인지 아니면 좋은 방법인지 궁금합니다.

추가적으로 컨벤션 관련 잘못된 부분이 있거나, 어노테이션이 적절하지 못하게 사용된 부분이 있다면 지적해주시면 감사하겠습니다 !

2023-10-16 16:16 UTC, aegis1920 requested changes
안녕하세요~ 멘토 빙봉입니다 🙂 
리뷰어 입장에서 clone 하자마자 실행할 수 있도록 해주시면 감사하겠습니다! (root voucher 디렉토리가 되지 않도록 해주세요. 이후에 다시 피드백하겠습니다! 가장 먼저 반영해주세요! 이때 PR 및 궁금한 점도 함께 답변하겠습니다!)
그리고 PR 및 코멘트도 가급적이면 코드에 직접 코멘트 남겨주시면 감사하겠습니다ㅎㅎ

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/common/MenuType.java
> +    private static final Logger logger = LoggerFactory.getLogger(MenuType.class);
개행에 신경써주세요~

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/common/ProgramRunner.java
> +    private boolean executeVoucherCommand() {
boolean 리턴일 경우 보통 isXX가 관례입니다!

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/common/response/Response.java
> +public class Response<T> {
규격화 멋지군요 👍

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/controller/voucher/VoucherController.java
> +        if(voucherRequest.getDiscount() < 0) {
0을 상수화해주시면 좋을 것 같네요!

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +        this.customerId = UUID.randomUUID();
UUID를 사용하신 이유가 있을까요?
UUID가 중복될 가능성은 없을까요?

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/UseStatusType.java
> +    USED("사용 불가능");
의미를 좀 더 명확히 하는 게 좋지 않을까요? 사용됨 혹은 Unavailable

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/dto/customer/CustomerResponse.java
> +@EqualsAndHashCode
`@EqualsAndHashCode`가 쓰인 이유가 있을까요? 테스트를 위해서 일까요?

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/exception/ExceptionHandler.java
> +public class ExceptionHandler extends RuntimeException{
클래스명의 역할을 하고 있는지 확인부탁드려요! 이 클래스에서 예외를 핸들링하고 있나요?

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/repository/voucher/FileVoucherRepository.java
> +    private String getVoucherInfo(Voucher voucher) {
단순히 출력을 위한 메서드라고 보면 될까요? 출력이 Repository에 있어도 될까요?

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/repository/voucher/MemoryVoucherRepository.java
> +        return vouchers.values().stream().toList();
불변 👍

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/resources/application.yml
> +    basename: message/messages
spring.messages.basename은 dev와 prod가 같으니 퉁칠 수 있을 것 같습니다.

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/common/response/Response.java
> +    private List<T> data;
data를 List로 받는 이유가 있을까요?

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +        this.customerId = UUID.randomUUID();
기존 생성자를 그대로 사용해도 될 것 같습니다. new Customer(UUID.randomUUID(), customerName, customerType)

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/PercentDiscountVoucher.java
> +public class PercentDiscountVoucher implements Voucher{
전반적으로 포매팅 확인 부탁드립니다~
```suggestion
public class PercentDiscountVoucher implements Voucher {
```

2023-10-16 16:16 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/Voucher.java
> +public interface Voucher {
get 역할만 가지고 있는 인터페이스는 어떤 의미일까요? 인터페이스가 꼭 필요할까요?

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +            throw ExceptionHandler.err(e.getMessage());
err 보단 명확한 이름을 사용해주세요!

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    public MenuType showAndSelectCommand(){
selectCommand로도 충분히 설명할 수 있는 함수 같아요!

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    public MenuType selectedVoucherProgram(){
굳이 함수로 나누어야할까요? 함수를 사용하는 궁극적인 목표는 중복의 제거인데 
중복이 제거 되지 않은것 같아요.

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +        }catch (ExceptionHandler e){
로그를 남겨보는 건 어떤가요? 어떤 입력에 의해서 어떤 예외가 발생한것인지 구체적으로 남겨두면 향후 디버깅에 큰 도움이 됩니다.

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/common/ProgramRunner.java
> +                        continueRun = false;
continueRun해당 변수를 while(continueRun)로 사용하지 않은 이유가 있나요?

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/common/message/MessageConverter.java
> +    private static MessageSource messageSource;
Static으로 정의한 의도가 있을까요?

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/controller/voucher/VoucherController.java
> +        if(voucherRequest.getDiscount() < 0) {
voucherRequest 내부에서 검증 할 순 없을까요?

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/domain/customer/CustomerType.java
> +            logger.error("Error Message = {}", e.getMessage());
로그 레벨이 error로 남겨지고 있어요!

레벨 마다 대중적으로 사용되는 경우가 있어요.

따라서 현재 상황에서는 과하다고 생각해요.

사용자의 입력에 따라 error로그가 생길 수 있다?

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/domain/voucher/VoucherType.java
> +            return VoucherType.valueOf(voucherType.toUpperCase());
네이밍에 신경을 조금만 써주세요.

voucherType과 VoucherType 사이의 괴리감이 들어요.

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/domain/voucher/VoucherType.java
> +            return VoucherType.valueOf(voucherType.toUpperCase());
오히려 input이 조금 더 명확한것 같아요.

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/repository/customer/CustomerRepository.java
> +                logger.error("Error Message = {}", e.getMessage());
로그 레벨을 한번 더 확인해주세요. 

error 레벨은 많은 스트레스를 유발할 수 있어요!

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/repository/customer/CustomerRepository.java
> +                UUID customerId = UUID.fromString(customerInfo[0]);
csv파일에 어느 위치에 무엇이 있는지 종속적인 코드가 되었어요. 

위치와 무관하게 코드를 구성 할 수 있나요?

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/repository/voucher/FileVoucherRepository.java
> +        Map<UUID, Voucher> loadedVouchers = new ConcurrentHashMap<>();
인상적이네요

2023-10-16 19:50 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +            Customer customer = new Customer(customerRequest.getCustomerName(), customerRequest.getCustomerType());
get()로 값을 꺼내서 넘기는 것 보단 팩토리 매서드를 사용하는건 어떤가요?

2023-10-17 07:35 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/common/MenuType.java
> +    private static final Logger logger = LoggerFactory.getLogger(MenuType.class);
신경 써서 반영 하겠습니다 !

2023-10-17 07:35 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/common/ProgramRunner.java
> +    private boolean executeVoucherCommand() {
관례에 맞게 수정해보겠습니다 !

2023-10-17 07:42 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/controller/voucher/VoucherController.java
> +        if(voucherRequest.getDiscount() < 0) {
반영하겠습니다 !

2023-10-17 07:45 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +        this.customerId = UUID.randomUUID();
UUID를 사용했을 때 중복되지 않을 정도로 고유하다고 생각했습니다. 랜덤하게 생성되는 4버전의 UUID는 예측이 어렵기 때문에 보안적으로도 좋다고 생각했고 중복 가능성이 희박하다고 생각했습니다 !

2023-10-17 07:45 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/UseStatusType.java
> +    USED("사용 불가능");
다시 보니 의미가 명확하지 않은 것 같습니다. 수정 하겠습니다 !

2023-10-17 07:47 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/dto/customer/CustomerResponse.java
> +@EqualsAndHashCode
테스트를 위해 선언 했던 기억이 있는데, 막상 살펴보니 사용하지 않고 있었던 것 같습니다. 아직은 불필요한 부분이라고 생각해서 지우도록 하겠습니다 !

2023-10-17 07:47 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/exception/ExceptionHandler.java
> +public class ExceptionHandler extends RuntimeException{
역할에 맞는 클래스명을 좀 더 고려해보겠습니다 !

2023-10-17 07:49 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/repository/voucher/FileVoucherRepository.java
> +    private String getVoucherInfo(Voucher voucher) {
getVoucherInfo() 메서드 같은 경우 출력을 담당한다기 보다 Voucher의 정보들을 파일에 저장하기 위한 형태로 변환해서 반환해주는 역할을 하고 있습니다.

2023-10-17 07:49 UTC, park0jae commented on voucher/src/main/resources/application.yml
> +    basename: message/messages
수정 하겠습니다 !

2023-10-17 07:52 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/common/response/Response.java
> +    private List<T> data;
findAll() 과 같은 메서드를 호출했을 때 List형태로 반환해주기 때문에 반환 받은 데이터를 List<T>형태로 담아서 반환하고자 하여 List를 사용했습니다. 지금 상황에서는 단순히 바우처나 회원의 정보를 문자열로서 변환해서 반환하기 때문에 큰 의미가 없다고 생각하지만, 추후에 커맨드라인으로 출력하는 요구사항에서 다른 요구사항으롤 변경되었을 때 그 의미가 발현될 것 같습니다.

2023-10-17 07:54 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +        this.customerId = UUID.randomUUID();
해당 생성자가 불필요하다고 생각되어, 기존의  new Customer(UUID.randomUUID(), customerName, customerType) 생성자를 이용해서 생성시에 UUID.randomUUID()를 넘겨주라는 것으로 이해하면 될까요?

2023-10-17 07:55 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +        this.customerId = UUID.randomUUID();
반영 하겠습니다 !

2023-10-17 07:55 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/PercentDiscountVoucher.java
> +public class PercentDiscountVoucher implements Voucher{
확인하고 반영 하겠습니다 !

2023-10-17 08:01 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/Voucher.java
> +public interface Voucher {
get 메서드 자체는 구체 클래스에서 각 구현이 변경될 가능성이 낮아 인터페이스가 굳이 필요한가 라는 생각이 들기도 하지만, 추후에 할인율을 적용하는 메서드 같은 추가적인 메서드가 필요할 때 인터페이스가 좀 더 의미 있어진다고 생각 했습니다.

2023-10-17 08:04 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +            throw ExceptionHandler.err(e.getMessage());
반영 하겠습니다 !

2023-10-17 08:15 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    public MenuType showAndSelectCommand(){
수정 하겠습니다 !

2023-10-17 08:15 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    public MenuType selectedVoucherProgram(){
중복 제거해서 하나로 합쳐보도록 하겠습니다 !

2023-10-17 08:49 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +        }catch (ExceptionHandler e){
추가 해보도록 하겠습니다 !

2023-10-17 08:49 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/ProgramRunner.java
> +                        continueRun = false;
다시 살펴보니 while(continueRun)으로 수정하는 쪽이 더 가독성이 좋을 것 같습니다 !

2023-10-17 08:50 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/message/MessageConverter.java
> +    private static MessageSource messageSource;
이 부분은 static 메서드를 작성하다가 필드까지 static으로 잘못 작성한 것 같습니다 수정하겠습니다 !

2023-10-17 08:54 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/message/MessageConverter.java
> +    private static MessageSource messageSource;
static 메서드인 getMessage 에서 messageSource를 사용하고자 했는데,  messageSource가 static 이 아닌 경우 사용이 불가능한 부분 때문에 static으로 정의한 것 같습니다 !

2023-10-17 08:55 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/voucher/VoucherController.java
> +        if(voucherRequest.getDiscount() < 0) {
Dto 클래스 자체는 계층 간 데이터 전송에만 집중한다고 생각해서 따로 검증로직을 작성하지 않았는데 컨트롤러가 아닌 Dto 내부에서 검증하는 것이 바람직한 방법일까요 ?

2023-10-17 09:02 UTC, park0jae commented on src/main/java/com/zerozae/voucher/domain/customer/CustomerType.java
> +            logger.error("Error Message = {}", e.getMessage());
넵 알겠습니다 ! 고려해서 수정해보겠습니다

2023-10-17 09:03 UTC, park0jae commented on src/main/java/com/zerozae/voucher/domain/voucher/VoucherType.java
> +            return VoucherType.valueOf(voucherType.toUpperCase());
저도 다시 코드를 보니까.. 헷갈리네요 수정하도록 하겠습니다 👍🏻

2023-10-17 16:19 UTC, park0jae commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +            Customer customer = new Customer(customerRequest.getCustomerName(), customerRequest.getCustomerType());
팩토리 메서드 적용 해보겠습니다 !

2023-10-17 17:36 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +        this.customerId = UUID.randomUUID();
중복 가능성을 배제할 순 없기에 추후 미션에서 중복 방지도 한 번 고려해봐주세요!

2023-10-17 17:39 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/repository/voucher/FileVoucherRepository.java
> +    private String getVoucherInfo(Voucher voucher) {
아 넵! 그렇군요! 확인 감사합니다!

2023-10-17 17:42 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/common/response/Response.java
> +    private List<T> data;
음.. 잘 이해가 안 갔는데요. 어차피 제네릭이라 타입을 List가 아닌 T로 받아도 되는 거 아닐까 싶어서 코멘트드렸습니다. 굳이 List로 제한할 필요가 있을까 싶었어요.

2023-10-17 17:44 UTC, aegis1920 commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/Voucher.java
> +public interface Voucher {
넵, 변경 가능성이 낮기도 하고 get만 하는 역할을 가진 인터페이스가 필요한가 싶었습니다.
지금 상황에서는 추상 클래스가 좀 더 적절해보이네요

2023-10-17 18:23 UTC, aegis1920 reviewed
궁금한 점에 대한 답변 남겨두었습니다! 다음에는 PR 자체가 아닌 코멘트로 남겨주시면 감사하겠습니다! 🙇

2023-10-17 18:23 UTC, aegis1920 commented on .gitignore
> 패키지 구조 관련하여, 추후 이어지는 미션을 위해 코드가 추가되는 것을 고려하면 계층형보다 도메인형의 패키지 구조가 좋을지 궁금하고, 기능별로 패키지를 잘 나눈 것인지 궁금합니다.

추후 미션이 이어지더라도 도메인 자체가 복잡하지 않아서 계층형이든 도메인형이든 상관없어보입니다. 도메인이 작아서 도메인 패키지 구조로 나누고 Controller Service 등은 패키지 구분없이 통째로 넣어도 될 정도라고 생각되네요.

지금 충분히 잘 나누셨습니다 👍

2023-10-17 18:23 UTC, aegis1920 commented on src/main/resources/application.yml
> +---
> yml 파일에 어떤 설정을 할 수 있을지 고려해보라는 요구사항이 있었는데 Profile과 messages.properties를 적용해보는 것 외에 생각이 잘 나지 않았습니다. 추가로 적용하면 좋은게 있을까요 ?

어떤 설정을 더 해볼 수 있을까요..? 저도 딱히 더 생각나는 부분은 없습니다ㅎㅎ;; 음.. 굳이 하자면 다른 active 설정을 넣었을 때 에러 반환(dev나 prod가 아니니)하는 정도 떠오릅니다.

2023-10-17 18:23 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/validator/InputValidator.java
> +            logger.error("Error Message = {}", message);
> 로깅 설정을 하였지만, 예외 부분에서만 error 로그를 설정한 것이 전부여서 혹시 다른 부분에도 로그를 적용한다면 어느 부분에 어떤 레벨로 적용해야 할까요 ?

유효성 검증의 경우 에러보다는 사용자가 다시 입력할 수 있는 정도니 warn 정도가 좋겠습니다. 로그는 다양하게 적용될 수 있는데요. 지금은 마땅히 적용할 부분이 보이지 않네요. 굳이 더 하자면 voucher 생성했을 때 간단하게 info 로그로 생성한 voucher를 표시해주는 정도가 될 것 같습니다. 추후 미션을 진행하면서 좀 더 세세한 구분이 필요할 때가 올 거예요. 그때 좀 더 적용해보시면 좋을 것 같습니다.

2023-10-17 18:23 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/domain/customer/CustomerType.java
> +public enum CustomerType {
> 요구사항들을 구현하다보니, 회원 추가나 회원 타입 (일반 회원, 블랙리스트 회원)등 요구사항을 넘어서 추가 구현한 부분들이 꽤 있는데, 요구사앙을 너무 멀리까지 본 것인지... 궁금합니다

이 정도까지 보신 건 실무에서도 추가 구현되는 정도라 잘 보셨다고 판단됩니다! 👍

2023-10-17 18:23 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/dto/customer/CustomerResponse.java
> +    public String getInfo(){
> 컨트롤러에서 도메인에 의존하지 않고자 Dto 객체를 이용했는데 적절한지 궁금하고, 바우처나 회원의 정보를 문자열로 반환해주는 getInfo() 메서드를 기존의 도메인 내에 작성했다가 컨트롤러에서 Response 타입으로 반환해줄때 해당 메서드를 사용하게 되면 domain 패키지를 의존하게 된다고 생각해서 Dto 객체로 getInfo 메서드를 옮겼는데, 이러한 방식이 괜찮은지 궁금합니다.

넵, 개인적으로는 제일 베스트인 방법이지 않나 싶어요. 간단하기도 하고 다른 레이어에서 도메인에 의존하게 하지도 않게 되니까요. 저는 좋다고 생각하빈다.

2023-10-17 18:23 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/validator/InputValidator.java
> +        if (input != null && input.matches("\\d+")) {
> 검증하는 부분에서, 입력값에 대한 잘못된 타입의 입력(숫자를 입력해야 하는데, 문자를 입력하는 경우)에 대한 검증은 InputValidator에서 진행하고 값(discount 가 음수인 경우 X)에 대한 검증은 컨트롤러에서 진행하며 enum에 대한 검증은 enum 자체에서 예외를 던지도록 작성했는데 잘못된 부분이 있는지 궁금합니다.

입력에 대한 검증, Enum 값에 대한 검증 등 각 의미에 맞게 잘 해주셨지만... discount가 음수인 경우는 Voucher의 할인 값이 음수가 될 수 없음을 의미하기에 도메인에 대한 검증이라고 생각돼서 컨트롤러가 아닌 도메인 단에서 검증해야된다고 생각들긴 합니다.

2023-10-17 18:23 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/validator/InputValidator.java
> +        if (input != null && input.matches("\\d+")) {
정규표현식은 보기가 어려워서 의미를 잘 나타내는 상수로 빼면 좋습니다.

2023-10-17 18:23 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/domain/voucher/Voucher.java
> +public interface Voucher {
> 파일에 Voucher를 저장할 때 필드값들을 저장하기 위해 getter 메서드들을 사용하는데 Repository에서는 Voucher 인터페이스를 의존하고 있어 구현체 내부의 getter는 사용할 수 없다고 판단하여 Voucher 인터페이스 내의 getter 메서드들을 선언해주고 오버라이딩 하는 방식으로 작성했는데 괜찮은 방법인지, 아니라면 파일에 다른 방식으로 저장해야하는지 ? 궁금합니다.

코멘트 드리긴 했는데 저는 getter만 있는 인터페이스의 존재 이유를 잘 모르겠습니다. getter가 Voucher의 역할이라고 보기도 어렵고요. 그래서 추상 클래스가 더 괜찮은 방법이라고 생각됩니다.

2023-10-17 18:23 UTC, aegis1920 commented on src/main/resources/message/messages.properties
> +EXIT_PROGRAM.MSG = \uD504\uB85C\uADF8\uB7A8\uC744 \uC885\uB8CC\uD569\uB2C8\uB2E4.
> 메시지를 출력할 때 메시지 자체를 넘기는 것이 아니라 messages.properties 파일을 통해 메시지들을 관리하고 MessageSource를 통해 가져오도록 구현했는데 불필요한 작업인지 아니면 좋은 방법인지 궁금합니다.

상황에 따라 다를 것 같은데요. 지금 도메인이 작기도 작고 메시지 자체로 의존성이 생기기도 해서 불필요하다고 생각들어요. 만약에 메시지가 바뀌어서 의미가 바뀌면 messages.properties에서도 변경이 생기고 이를 사용하는 곳에서도 변경이 생길테니까요.

2023-10-18 07:47 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +        this.customerId = UUID.randomUUID();
추후 미션에서는 중복 검사 로직을 추가해보도록 하겠습니다 !

2023-10-18 07:49 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/common/response/Response.java
> +    private List<T> data;
제가 잘못 이해하고 있었던 것 같습니다 !.. 그냥 T로 받도록 수정해도 결국 동일한 것 같습니다. T로 수정하고 컨트롤러에서는 데이터를 문자열로 가공하지 않고 그대로 넘기고 출력단 부분에서 문자열로 가공하여 출력하는 방식으로 수정 하겠습니다.

2023-10-18 07:50 UTC, park0jae commented on voucher/src/main/java/com/zerozae/voucher/domain/voucher/Voucher.java
> +public interface Voucher {
추상 클래스로 교체 해보겠습니다. get 역할을 가진 메서드 이외의 메서드들이 추가되었을때 다시 인터페이스를 고려해보도록 하겠습니다 !

2023-10-18 07:51 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/customer/CustomerRepository.java
> +                UUID customerId = UUID.fromString(customerInfo[0]);
이 부분은 아직도 감이 잘 오지 않는데.. 직렬화 해서 객체 자체를 저장하는 것도 괜찮을까요 ? 직렬화해서 저장하면 파일을 열어 보았을 때 데이터를 한눈에 보기 힘들다라고 생각하는데 아니면 다른 방법이 있을까요 ? 헤더를 지정해서 저장하는 방법도 고려하고 있습니다.

2023-10-18 07:52 UTC, park0jae commented on src/main/java/com/zerozae/voucher/validator/InputValidator.java
> +        if (input != null && input.matches("\\d+")) {
도메인 단으로 검증하는 부분을 옮겨 보겠습니다 !..

2023-10-22 13:22 UTC, aegis1920 requested changes
피드백이 많았는데 고생 많으셨습니다! 빌드 수정 건만 반영해주시면 바로 머지하겠습니다!

2023-10-22 13:22 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/customer/FileCustomerRepository.java
> +public class CustomerRepository {
혹시 빌드해보셨으까요? java 파일명과 클래스명이 달라서 수정이 필요합니다! (e.g. CustomerRepository)

2023-10-22 14:19 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/customer/FileCustomerRepository.java
> +public class CustomerRepository {
죄송합니다 ! 수정했습니다

2023-10-22 15:30 UTC, aegis1920 approved these changes
빠른 피드백 반영 감사합니다 👍  머지하겠습니다!

2023-10-22 15:30 UTC, merged