[5기 김별이] SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #885
Opened 2023-10-16 15:40 UTC by byulcode

## 📌 과제 설명 
## SpringBoot Part1 Weekly Mission

(기본) **바우처 관리 애플리케이션**

- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을  만들어본다.
    - 참고: https://dzone.com/articles/interactive-console-applications-in-java
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

## 👩‍💻 요구 사항과 구현 내용 
+ common
    + VoucherRunner : 입력된 메뉴 타입에 따라 필요한 핸들러 메소드 호출
    + MenuHandler : command line 값 입출력 관리 및 컨트롤러 메소드 호출
    + MenuType : 메뉴 타입 enum
+ domain
    + 도메인 별로 컨트롤러, 서비스, 엔티티, 레파지토리 로직 구현
    + dto : controller 레이어에서 엔티티를 의존하지 않도록 dto 생성
+ io
    + ConsoleMessage : 콘솔 메시지 enum
    + Console : 콘솔 메시지 입출력 로직
+ util
    + CsvFileUtil : 파일 입력 및 파일 읽어오는 기능 담당

## ✅ PR 포인트 & 궁금한 점 
1. 동일한 필드가 많아서 voucher을 추상클래스로 구현했는데, 인터페이스가 더 나은 선택일지 궁금합니다
2. 로깅을 어느 부분에 해야하는지 잘 모르겠습니다. 예외 메시지를 출력할 때 로그 메시지도 생성 한다면 메시지가 중복되는게 아닌지, 에러가 아닌 상황에도 로깅을 하는지 궁금합니다.
3. 과제 참고 링크에 text-io 라이브러리가 있어 참고하여 입출력을 구현했습니다. 해당 라이브러리를 사용하면 입출력 받을 수 있는 문자와 자료형을 제한할 수 있어서 따로 예외 처리를 하지 않았는데, 맞는 구현인지 잘 모르겠습니다.
4. voucher 생성시 validation을 하고 싶어 voucher을 팩토리 메서드 패턴으로 구현했습니다. 이 방법보다 따로 validation용 클래스를 만드는게 더 좋은 선택일지 궁금합니다.
5. id는 도메인에서 디폴트 값이 들어가게 하는게 좋다는 이야기를 들어서 voucher 생성시 id값을 입력받지 않도록 구현했습니다. 그런데 파일에서 읽어올 경우에는 기존에 존재하는 voucher을 읽어와야 해서 생성자를 오버로딩 해야했습니다. Id를 언제 생성하는게 좋을지 궁금합니다.

2023-10-17 17:32 UTC, aegis1920 requested changes
안녕하세요~ 멘토 빙봉입니다 🙂 

코멘트 드렸으니 확인해주세요!4

2023-10-17 17:32 UTC, aegis1920 commented on build.gradle
> +    implementation 'org.beryx:text-io:3.4.1'
가급적이면 implementation를 모아서 작성해주세요~

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/common/MenuType.java
> +        return MenuType.valueOf(menu.toUpperCase());
menu 인자로 들어온 것을 기반으로 MenuType을 찾는 역할인데요. MenuType에서 UpperCase로 바꾸기보다 다른 곳에서 바꾸는 게 좋지 않을까요?

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/dto/CustomerResponse.java
> +    public String toString() {
제가 이펙티브 자바를 읽으면서 작성한 toString 관련 글인데 도움이 될 것 같아 링크 남겨두겠습니다 🙇 ([링크](https://github.com/Meet-Coder-Study/book-effective-java/blob/70d36f6940a7b1b99b74e430951c22981722af9d/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md))

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/entity/Customer.java
> +    public Customer(String name) {
쓰이지 않는 로직일까요?

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
> +        if(discountValue < 0 || discountValue > 100) {
상수화해서 좀 더 명확해주면 좋을 것 같습니다!

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
> +        this.voucherId = UUID.randomUUID();
UUID를 사용하신 이유가 있을까요?

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
> +@Profile("default")
이쪽 [코멘트](https://github.com/prgrms-be-devcourse/springboot-basic/pull/887#discussion_r1362464506)가 도움이 될 것 같습니다.

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
> +    public FileVoucherRepository(@Value("${repository.voucher.filePath}") String filePath) {
필드에 `@Value` 선언을 하는 건 어떨까요?

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/service/VoucherService.java
> +        logger.info("Voucher service findAll run..");
> 로깅을 어느 부분에 해야하는지 잘 모르겠습니다. 예외 메시지를 출력할 때 로그 메시지도 생성 한다면 메시지가 중복되는게 아닌지, 에러가 아닌 상황에도 로깅을 하는지 궁금합니다.

로깅은 상황에 따라 적절하게 하는 것이 중요합니다. 따라서 에러가 아닌 상황에서도 적용합니다. 예외 메시지는 예외가 발생할 때 나오는 메시지이며 로그 메시지는 로깅으로 남기는 거라 중복되는 거라고 볼 수 없습니다. (예외를 throw하지 않고 로깅만 하고 넘길 수도 있습니다)

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/io/Console.java
> +    TextIO textIO = TextIoFactory.getTextIO();
> 과제 참고 링크에 text-io 라이브러리가 있어 참고하여 입출력을 구현했습니다. 해당 라이브러리를 사용하면 입출력 받을 수 있는 문자와 자료형을 제한할 수 있어서 따로 예외 처리를 하지 않았는데, 맞는 구현인지 잘 모르겠습니다.

- 오.. 이런 라이브러리가 있군요. 넵 라이브러리를 사용했고, 바깥 호출하는 곳에서 catch해서 잡고있으므로 하지 않아도 될 것 같습니다.
- 싱글톤으로 떠있는 녀석이라 상수 취급을 해줘도 좋을 것 같습니다.

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/util/CsvFileUtil.java
> +    private static final Logger log = LoggerFactory.getLogger(CsvFileUtil.class);
어떤 건 private static final이고 어떤 건 아니네요. 일관성있게 맞춰주면 좋을 것 같습니다!

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/util/CsvFileUtil.java
> +        Map<UUID, Voucher> vouchers = new ConcurrentHashMap<>();
이 로직은 어떤 용도일까요? ConcurrentHashMap가 생성되는 게 맞을까요?

2023-10-17 17:32 UTC, aegis1920 commented on src/main/resources/application.yml
> +    active: default
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij를 사용하고 계시다면 파일을 저장할 때마다 개행을 자동으로 넣어주도록 할 수 있습니다! (Settings → Editor → General → Ensure line feed at file end on Save)

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/common/MenuType.java
> +public enum MenuType {
Menu보단 Command가 더 어울려보입니다.

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/dto/CustomerResponse.java
> +public record CustomerResponse(
record 👍

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        return (discountAmount < 0) ? 0 : discountAmount;
정책에 따라 다를 것 같긴한데 개인적으로는 0보다 작으면 에러를 던져야한다고 생각들긴하네요?

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
> +public abstract class Voucher {
> 동일한 필드가 많아서 voucher을 추상클래스로 구현했는데, 인터페이스가 더 나은 선택일지 궁금합니다

추상클래스 좋습니다! 오히려 지금 인터페이스의 역할이 애매해서 추상클래스가 더 나은 선택이라고 생각됩니다.

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        }
필요없는 로직같은데 맞을까요?

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        if(discountValue < 0) {
> voucher 생성시 validation을 하고 싶어 voucher을 팩토리 메서드 패턴으로 구현했습니다. 이 방법보다 따로 validation용 클래스를 만드는게 더 좋은 선택일지 궁금합니다.

지금 Validation 클래스를 만든다고 하면 어떤 게 더 나아보이나요? 큰 Validation이 있는 것도 아니라서 개인적으론 불필요하다고 여겨집니다.

2023-10-17 17:32 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
> +    public PercentDiscountVoucher(UUID voucherId, String discountType, long discountValue) {
> id는 도메인에서 디폴트 값이 들어가게 하는게 좋다는 이야기를 들어서 voucher 생성시 id값을 입력받지 않도록 구현했습니다. 그런데 파일에서 읽어올 경우에는 기존에 존재하는 voucher을 읽어와야 해서 생성자를 오버로딩 해야했습니다. Id를 언제 생성하는게 좋을지 궁금합니다.

상황에 따라 다를 것 같은데요. 지금은 voucher라는 객체가 생성될 때 ID를 생성해도 상관없어보입니다. 논리적으로 가장 맞는 방법이라고 생각들기도 하고요. 

`id는 도메인에서 디폴트 값이 들어가게 하는게 좋다는 이야기를 들어서` 이건 왜 좋다고 하던가요?

2023-10-18 16:27 UTC, cloudwi commented on src/main/java/com/prgrms/springbasic/common/MenuHandler.java
> +    private CreateVoucherRequest makeCreateVoucherRequest() {
MenuHandler 보단 voucherController에 있어야 조금 더 명확하지 않을까요?
별이님은 어떻게 생각하시나요?

2023-10-18 16:27 UTC, cloudwi commented on src/main/java/com/prgrms/springbasic/common/VoucherRunner.java
> +        MenuType menuType;
while문 밖에 선언한 이유가 있을까요?

저는 가독성을 생각해 보았을때 while문 내부에 선언하는 것이 더 좋다고 생각해요.

별이님의 생각을 말해주세요!

2023-10-18 16:27 UTC, cloudwi commented on src/main/java/com/prgrms/springbasic/domain/customer/dto/CustomerResponse.java
> +public record CustomerResponse(
record 엄청 납니다.!

2023-10-18 16:27 UTC, cloudwi commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +            logger.error("discount value should be positive. Inserted discount value : {}", discountValue);
사용자 입력으로 발생하는 예외 사항을 Error 레벨로 만드는 것은 좋을까? 라는 고민을 같이 했으면 좋겠어요.

현재는 알림이나 영향력이 적겠지만 향후 습관적으로 error 레벨을 뿌린다면 문제가 있을 것 같아요.

2023-10-18 16:27 UTC, cloudwi commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +            logger.error("discount value should be positive. Inserted discount value : {}", discountValue);
이곳도 동일합니다.

2023-10-18 16:27 UTC, cloudwi commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        if(discountValue < 0) {
생성자에서 동일한 작업을 하는 것으로 보입니다. 혹시 2번 반복하는 의미가 있을까요?

2023-10-18 16:27 UTC, cloudwi commented on src/test/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucherTest.java
> +class FixedAmountVoucherTest {
테스트가 많이 부족해보요.

비즈니스 핵심 로직은 테스트 코드로 작성해 보시는게 어떨까요?

2023-10-19 12:59 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/common/MenuType.java
> +        return MenuType.valueOf(menu.toUpperCase());
입력을 받을 때 바꾸는게 더 좋을 것 같아서 수정했습니다!

2023-10-19 13:28 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/customer/entity/Customer.java
> +    public Customer(String name) {
customer 생성 로직을 구현할 생각으로 만든 로직인데, 요구사항에 없어서 사용하지 않게 되었습니다.! 일단 제거하고 추후 필요할 때가 생기면 다시 생성하겠습니다.

2023-10-19 14:19 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
> +        this.voucherId = UUID.randomUUID();
저번 과제를 할 땐 id값을 1씩 증가하는 방식으로 구현을 했습니다!
이때, 생성자에 1씩 증가하는 로직이 있을 경우 프로그램을 재실행하면 id값이 다시 1부터 시작하는 문제가 있어서 아이디 생성 로직을 repository에서 구현해 생성자로 id값을 넣어주는 방식으로 진행했었습니다.

이후에 id는 도메인에서 디폴트 값이 들어가게 하는게 좋다라는 이야기를 들어서 변경하려고 했는데, repository에 id 생성 로직이 있다 보니 이를 도메인에서 이용해도 되는 게 맞는지 의문이 들어서 적절한 방법을 찾지 못했습니다🥹

그래서 이번엔 UUID를 사용해서 id값을 더 쉽게 생성할 수 있도록 구현해봤습니다!

2023-10-19 14:46 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
> +    public FileVoucherRepository(@Value("${repository.voucher.filePath}") String filePath) {
처음에 필드로 선언했더니 filePath가 null이 되어 오류가 발생했었습니다. [[링크](https://docs.spring.io/spring-framework/reference/core/beans/factory-extension.html#beans-factory-extension-factory-postprocessors)] 를 참고하니  @Value 어노테이션을 처리하는 BeanPostProcessor가 수행되는 순서 때문이라고 해서 생성자로 주입을 했었습니다!
그런데 더 찾아보니 @PostConstruct를 활용하는 방법이 있다고 하네요😅 수정해보겠습니다

2023-10-20 10:13 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/util/CsvFileUtil.java
> +        Map<UUID, Voucher> vouchers = new ConcurrentHashMap<>();
다시보니 불필요한 로직같습니다! 블랙리스트 파일 관련 로직도 함께 리팩토링 하게습니다

2023-10-20 10:28 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        return (discountAmount < 0) ? 0 : discountAmount;
최소 주문 금액 같은 제한이 없어서 위처럼 구현했습니다! 말씀하신대로 쿠폰 정책에 따라 다를 것 같아요. 바우처보다 적은 금액을 구매하면 0원으로 결제되며 차액은 소실되는 서비스도 이용한 적이 있고, 바우처를 사용하기 위한 최소 주문 금액이 존재하는 서비스도 이용한 경험이 있어서요. 이처럼 정해진 기준이 없는 경우에는 예외를 던지는게 좋을까요?

2023-10-20 10:30 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        }
validation이 중복되어 있는걸 확인 못했습니다 수정하겠습니다!

2023-10-20 10:42 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
> +    public PercentDiscountVoucher(UUID voucherId, String discountType, long discountValue) {
1. 생성자를 무조건적으로 열면 나중에 누군가 실수할 수 있다
2. 데이터베이스 연결시 여러 아이디 생성 기법이 있기 때문에, 이를 대비하는 방법일 수 있다
두 가지 의견을 들었습니다! 상황에 맞게 잘 선택할 수 있도록 고민해보겠습니다😊

2023-10-20 10:50 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/common/MenuHandler.java
> +    private CreateVoucherRequest makeCreateVoucherRequest() {
percent/fixed 선택 여부에 따라서 콘솔로 입력받을 수 있는 값의 범위가 달라져서 위처럼 구현했습니다! 
값을 입력 받는 부분이 뷰의 영역이라고 생각해서요. controller로 옮길 경우 console 입출력을 컨트롤러에서 제어하게 되는데, 그래도 상관 없는걸까요? 아니면 다른 방법이 있을까요?

2023-10-20 14:17 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/common/VoucherRunner.java
> +        MenuType menuType;
넵 while문 안에 있어야 할 것 같습니다 수정하겠습니다!

2023-10-20 14:19 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        if(discountValue < 0) {
깜박하고 삭제를 안했습니다 수정하겠습니다!

2023-10-20 15:23 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
> +    }
파일에 쓰기 위한 문자열을 반환하도록 하기 위해서 toString을 재정의했습니다. 하지만 저번 리뷰에서 보내 주신 toString() 관련 링크를 참고하니 toString을 이럴 때 재정의 하는 게 아니라는 생각이 듭니다.

CsvFileUtil에 자바 reflection을 사용해서 클래스의 필드를 원하는 문자열로 만드는 메서드를 정의하는 방법도 생각해 봤는데, 보안적으로 문제가 있을 것 같았습니다. 혹시 다른 방법은 없는지 궁금합니다!

2023-10-22 04:50 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
> +        this.voucherId = UUID.randomUUID();
그런 이유가 있었군요ㅎㅎ ID 값을 부여하는데는 다양한 방식이 있는데요. 어떤 선택을 하든 트레이드 오프가 존재합니다. 상황에 맞게 전략을 잘 구성하는 것이 중요하니 한 번 살펴봐주세요~

2023-10-22 04:55 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +        return (discountAmount < 0) ? 0 : discountAmount;
`0원으로 결제 시, 차액을 소실된다`라는 정책이 있다고 한다면 굳이 예외를 던지진 않아도 될 것 같습니다. 다만 흔한 경우는 아니라서 Noti를 위해 info 로그 혹은 warn 로그 정도는 남겨두면 좋을 것 같아요. (나중에 로그로도 해당 정보를 찾아보고 활용할 수 있도록)

2023-10-22 04:58 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
> +    public PercentDiscountVoucher(UUID voucherId, String discountType, long discountValue) {
말씀대로 상황에 따라서 혹은 정책에 따라서 디폴트 값이 들어가는 것이 좋은지 좋지 않은지 달라지게 되고,
Application 단에서 기본값을 넣는 게 좋은지, DB에서 디폴트 값을 넣는 게 좋은지 등등 달라지게 됩니다. 고민해보시고 반영해주세요!

2023-10-22 05:01 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
> +    }
Voucher 클래스에서 toString을 오버라이딩하지 말고 이를 사용하는 Console 클래스에서 voucher의 정보를 get해서 만들어보시죠. 이게 좀 더 명확할 것 같습니다. 만약 특정 객체의 정보를 get하는 것이 마음에 들지 않으신다면 [이 글](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)을 참고해보는 것도 좋을 것 같아요!

2023-10-22 05:07 UTC, aegis1920 approved these changes
고생 많으셨습니다! 1단계는 여기서 머지할게요! 👍

2023-10-22 05:07 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
> +    private static final Logger logger = LoggerFactory.getLogger(PercentDiscountVoucher.class);
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(FixedAmountVoucher.class);
```

2023-10-22 05:07 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/dto/CreateVoucherRequest.java
> +    private long discountValue;
재할당되지 않도록 final을 붙여도 될 것 같습니다!

2023-10-22 05:07 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/util/CsvFileUtil.java
> +import com.prgrms.springbasic.domain.voucher.entity.Voucher;
CsvFileUtil의 역할만 가질 수 있도록 domain 패키지에 의존하지 않도록 바꿔보는 것도 추천드립니다!

2023-10-22 05:07 UTC, merged