[5기 - 조은비] SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #887
Opened 2023-10-17 04:27 UTC by eunbc

안녕하세요! 빙봉팀의 조은비입니다 😃 

## 📌 과제 설명 
- [x]  Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
- [x]  바우처 관리 Command-line Application을  만들어본다.
    - [x]  스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x]  프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x]  create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
    
- [x]  적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
- [x]  실행가능한 `jar` 파일을 생성한다.

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x]  메모리 관리가 아닌  파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x]  고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x]  YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다
## 👩‍💻 요구 사항과 구현 내용 
<프로젝트 구성도>
![스크린샷 2023-10-17 오후 1 05 32](https://github.com/prgrms-be-devcourse/springboot-basic/assets/69096886/3b35de4e-7c9b-4692-937f-08ad76b1cc08)

## ✅ PR 포인트 & 궁금한 점 

* 코드에 코멘트로 달아 놓겠습니다~!

2023-10-17 04:37 UTC, eunbc commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +				command.execute();
앞으로 기능이 더 추가되는 것을 대비하여 메뉴별 실행 로직에 커맨드 패턴을 적용하였습니다.

2023-10-17 04:46 UTC, eunbc commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +				command.execute();
앞으로 기능이 더 추가되는 것을 대비하여 메뉴별 실행 로직에 커맨드 패턴을 적용하였습니다.

장점
- 메뉴가 추가될 경우, Command 구현 클래스만 추가하면 되어서 OCP 원칙을 따르는 효과가 있습니다.
- 각각의 기능을 캡슐화 할 수 있습니다.

단점
- 각각의 동작에 대해 개별 커맨드 클래스를 생성해야 하기 때문에 클래스가 많아져 복잡할 수 있습니다.
- switch문으로 작성하는 것이 오히려 코드를 쉽게 읽기에는 더 좋을 수 있습니다.

2023-10-17 05:15 UTC, eunbc reviewed
안녕하세요! 빙봉팀 조은비입니다 😸 

PR 포인트 및 궁금한 점을 코멘트로 남겨두었습니다.
감사합니다!

2023-10-17 05:15 UTC, eunbc commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +				command.execute();
앞으로 기능이 더 추가되는 것을 대비하여 메뉴별 실행 로직에 커맨드 패턴을 적용하였습니다.


장점

- 메뉴가 추가될 경우, Command 구현 클래스만 추가하면 되어서 OCP 원칙을 따르는 효과가 있습니다.
- 각 기능을 캡슐화 할 수 있습니다.

단점
- 각 동작에 대해 개별 커맨드 클래스를 생성해야 하기 때문에 클래스가 많아져 복잡할 수 있습니다.
- switch문으로 작성하는 것이 오히려 코드를 쉽게 읽기에는 더 좋을 수 있습니다.

2023-10-17 05:15 UTC, eunbc commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +		}
프로그램 실행 중 발생하는 예외를 catch 하여 로그를 남깁니다. (Spring의 @ControllerAdvice와 비슷한 역할)

2023-10-17 05:15 UTC, eunbc commented on src/main/java/com/programmers/springbasic/entity/voucher/Voucher.java
> +}
아직은 getter밖에 없기는 하지만 다음 주차 과제에서 다른 메소드가 추가될 예정입니다!

2023-10-17 05:15 UTC, eunbc commented on src/main/java/com/programmers/springbasic/repository/voucher/FileVoucherRepository.java
> +	private final Map<UUID, Voucher> storage;
메모리 캐시용 Map입니다!

2023-10-17 05:15 UTC, eunbc commented on src/main/java/com/programmers/springbasic/repository/voucher/MemoryVoucherRepository.java
> +@Profile("default")
@Profile("default") 는 사실 없어도 되는 것 같은데

profile = dev로 설정 후 실행할 때, @Profile("default") 가 없으면
 VoucherService required a single bean, but 2 were found:.... 
 
라는 에러가 나오면서 실행이 중단됩니다. 혹시 비슷한 경험 있으실까요? 
꼭 디폴트 프로파일 어노테이션이 있어야 하는지 더 찾아보겠습니다ㅠ

2023-10-17 05:15 UTC, eunbc commented on src/main/java/com/programmers/springbasic/utils/FileUtils.java
> +
블랙리스트와 바우처 정보를 파일로부터 읽어오는 util 클래스 입니다!
checkFileExistAndCreate 라는 메소드가 중복되어 한 클래스에 블랙리스트와 바우처 관련 기능을 모두 넣었습니다.

나중에 entity가 더 추가된다면
각 entity 별로 FileUtils(CustomerFileUtils,VoucherFileUtils)를 생성하는 것도 괜찮을 것 같은데 의견이 궁금합니다 :)

2023-10-17 05:15 UTC, eunbc commented on src/main/resources/application.yml
> +
profile이 default이든, dev이든 현재는  filePath가 같지만 profile에 따라 파일 경로가 달라질 수도 있다고 생각되어 각각 파일을 작성했습니다!

2023-10-17 16:48 UTC, aegis1920 requested changes
안녕하세요 멘토 빙봉입니다 🙂 

코멘트 남겼으니 확인해주세요~

2023-10-17 16:48 UTC, aegis1920 commented on .gitignore
idea 디렉토리는 ignore 시켜주세요~

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/configuration/CommandExecutorConfig.java
> +		return args -> commandExecutor.executeCommands();
단순히 commandExecutor에서 executeCommands를 실행시키는 역할이라면 아래 방식은 어떨까요? 

CommandExecutor에서 CommandLineRunner를 구현하고 executeCommands를 run 메서드로 치환, CommandExecutorConfig 클래스는 삭제

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/console/ConsoleInputHandler.java
> +		String value = scanner.nextLine().trim();
trim보다는 더 많은 유니코드를 지원하는 strip을 추천드립니다!

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/console/ConsoleOutputHandler.java
> +	public <T> void printList(List<T> list) {
인자 명이 좀 더 명확했으면 좋겠네요. 어떤 리스트일까요?

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/controller/CustomerController.java
> +	public List<ListBlacklistCustomerResponse> listBlacklistCustomer() {
함수명은 동사가 되어야하지 않을까요?

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/dto/ListBlacklistCustomerResponse.java
> +	public String toString() {
- 가급적이면 다른 곳에 의존하지 않도록 java.text.MessageFormat 없이 String만으로 작성해보세요.
- 제가 이펙티브 자바를 읽으면서 작성한 toString 관련 글인데 도움이 될 것 같아 링크 남겨두겠습니다 🙇 ([링크](https://github.com/Meet-Coder-Study/book-effective-java/blob/70d36f6940a7b1b99b74e430951c22981722af9d/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md))

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/entity/customer/Customer.java
> +	public Boolean getBlacklisted() {
boolean return은 isXXX 함수명이 관례입니다!

2023-10-17 16:48 UTC, aegis1920 commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/macos,intellij,java,gradle
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij를 사용하고 계시다면 파일을 저장할 때마다 개행을 자동으로 넣어주도록 할 수 있습니다! (Settings → Editor → General → Ensure line feed at file end on Save)

2023-10-17 16:48 UTC, aegis1920 commented on HELP.md
요것도 없어도 되겠네요

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +	private static final Logger logger = org.slf4j.LoggerFactory.getLogger(CommandExecutor.class);
개행 부탁드립니다!

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/dto/ListVouchersResponse.java
> +	private final UUID voucherId;
UUID를 사용한 이유가 있을까요?

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/entity/customer/Customer.java
> +	private Boolean isBlacklisted;
- final 필드가 될 수 있을 것 같습니다.
- 앞에서 boolean을 받고 있는데 여기선 Boolean 래퍼 객체로 받고 있습니다. Boolean으로 받으신 이유가 있을까요?

2023-10-17 16:48 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/enums/MenuType.java
> +public enum MenuType {
Menu보단 Command에 더 가까워보이네요

2023-10-17 16:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +				command.execute();
장점과 단점을 잘 설명해주셨네요! 👍

2023-10-17 16:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +		}
👍

2023-10-17 16:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/entity/voucher/Voucher.java
> +}
넵 설명 감사합니다!

2023-10-17 16:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/repository/voucher/FileVoucherRepository.java
> +	private final Map<UUID, Voucher> storage;
넵 설명 감사합니다! 궁금한 점이 있는데요.
InitializingBean을 사용해서 afterPropertiesSet을 사용하신 이유는 어떤 이유에서 사용하신 걸까요?
afterPropertiesSet안에 있는 로직들은 FileVoucherRepository를 생성할 때 넣어주면 동일한 부분 아닐까 싶어서요!

2023-10-17 16:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/repository/voucher/MemoryVoucherRepository.java
> +@Profile("default")
일단 왜 그렇게 나오는지부터 이해해야하는데요. `@Profile` 없이 실행을 시키면 아래 설명에 나와있듯이 잘 설명해주고 있습니다.

```
Description:

Parameter 0 of constructor in com.programmers.springbasic.service.VoucherService required a single bean, but 2 were found:
	- fileVoucherRepository: defined in file /springboot-basic/build/classes/java/main/com/programmers/springbasic/repository/voucher/FileVoucherRepository.class]
	- memoryVoucherRepository: defined in file /springboot-basic/build/classes/java/main/com/programmers/springbasic/repository/voucher/MemoryVoucherRepository.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

VoucherService에서 싱글 빈이 필요한데 2개가 발견됐다고 나옵니다. 스프링은 타입을 기반으로 빈 이름을 가지는데요. 2개의 빈 이름을 가지면 어떤 빈을 선택할 지 알 수 없어 발생한 에러입니다.

타입을 기반으로 빈 이름을 가지기 때문에 FileVoucherRepository와 MemoryVoucherRepository 모두 VoucherRepository로 인식하기 때문에 에러가 발생했습니다. 그 아래 액션도 정말 잘 설명해주고 있습니다. 둘 중 하나로 선택하게 해줄 수 있는 Primary 어노테이션을 사용하거나, Qualifier 어노테이션을 통해 직접 지정해줄 수 있습니다.

그러면 말씀해주신 상황(`@Profile("default")`은 없고 profile = dev는 설정한 상황)에서는 왜 에러가 나올까요? `@Profile("default")`가 없으면 기본적으로 MemoryVoucherRepository 빈이 올라가게 되고, 마찬가지로 `@Profile("dev")`로 설정된 FileVoucherRepository 빈도 올라가게 되기 때문에 위의 에러가 발생하게 됩니다. 

`@Profile("default")`가 있다면 profile이 dev라서 MemoryVoucherRepository 빈이 해당되지 않기 때문에 올라가지 않습니다. FileVoucherRepository만 올라가서 FileVoucherRepository이 선택됩니다.

참고로 현재 Profile을 알고 싶다면 org.springframework.core.env.Environment의 getActiveProfiles를 활용해보세요.

현재 요구사항에는 `기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.` 라는 요구사항이 있으므로`@Profile("default")` 없이 작성하고, `spring.profiles.active`를 통해 기본값을 작성해주시면 될 것 같습니다.

2023-10-17 16:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/utils/FileUtils.java
> +
현재 이름이 FileUtils 잖아요? 그러면 유틸성 클래스로 어떤 entity가 들어오든지 상관없이 파일 읽기 혹은 쓰기가 가능해야하는 거 아닐까요?

2023-10-20 05:55 UTC, cloudwi commented on src/main/java/com/programmers/springbasic/dto/CreateFixedAmountVoucherRequest.java
> +		if (amount <= 0) {
해당 유효성 검사는 어떤 관점에서 관리해야할까요?

저의 생각은 amount가 0보다 작거나 같으면 안됩니다.  라는 규칙은 비즈니스 규칙이라고 생각해요.

사용자의 입력은 정상적인 형식이지만 그 값의 범위가 비즈니스에 적합하지 않기 때문이죠 따라서 Request보단 상위에서 처리해줘야 한다고 생각해요!

은비님 생각은 어떤가요?

2023-10-20 05:55 UTC, cloudwi commented on src/main/java/com/programmers/springbasic/dto/CreatePercentDiscountVoucherRequest.java
> +		if (percent < MINIMUM_PERCENT || percent > MAXIMUM_PERCENT) {
이곳도 동일합니다.

2023-10-20 05:55 UTC, cloudwi commented on src/main/java/com/programmers/springbasic/entity/voucher/FixedAmountVoucher.java
> +	public FixedAmountVoucher(UUID voucherId, long amount) {
실제 바우처를 생성할때는 유효성 검사를 하지 않고 있어요.

비즈니스가 커지고 확장 되었을때 값 -1이 되면 어떻게 될까요?

방어적인 코드를 한번 생각해보면 좋을 것 같아요.

하지만 지금은 필요 없을지도 모르겠군요 

은비님 생각을 말해주세요!

2023-10-21 05:59 UTC, eunbc reviewed
1차 리뷰 반영 완료하였습니다!
꼼꼼히 봐주셔서 감사합니다 👍

2023-10-21 05:59 UTC, eunbc commented on .gitignore
반영 완료하였습니다!

2023-10-21 05:59 UTC, eunbc commented on src/main/java/com/programmers/springbasic/entity/voucher/FixedAmountVoucher.java
> +	public FixedAmountVoucher(UUID voucherId, long amount) {
코드 작성할 때 '입력 받을 때 어떤 범위의 값만 받아야 하지?' 에 집중하다 보니 
범위 체크 로직을 dto 쪽에 넣어줬었는데요,

주영님 말씀처럼 범위 체크는 비즈니스 로직이 맞는 것 같습니다.
예리한 지적 감사드려요! 👍

2023-10-21 05:59 UTC, eunbc commented on src/main/java/com/programmers/springbasic/entity/voucher/Voucher.java
> +}
인터페이스를 추상 클래스로 변경하였습니다!

2023-10-21 05:59 UTC, eunbc commented on src/main/java/com/programmers/springbasic/repository/voucher/FileVoucherRepository.java
> +	private final Map<UUID, Voucher> storage;
넵 맞습니다! 제가 afterPropertiesSet 사용법을 잘못 이해하고 있었습니다.
afterPropertiesSet을 사용할 필요없이 생성자 초기화만으로도 가능한 부분이라 수정 반영하였습니다 :)

2023-10-21 05:59 UTC, eunbc commented on src/main/java/com/programmers/springbasic/utils/FileUtils.java
> +
FileUtils 를 파일 읽기, 쓰기 전용으로만 사용하고, Mapper클래스를 따로 만들어 엔티티로 변환해줄 수 있도록 수정하였습니다!

2023-10-21 05:59 UTC, eunbc commented on src/main/java/com/programmers/springbasic/entity/customer/Customer.java
> +	private Boolean isBlacklisted;
- 변경 가능성이 없는 필드를 final 로 수정하였습니다!
- Boolean 래퍼 객체를 사용한 이유는, 데이터베이스의 컬럼이 null 일 가능성이 있을 수도 있다고 생각하였기 때문입니다만.. 데이터베이스 컬럼 설정을 (not null혹은 default 값이 있는 상태)로 지정하면 래퍼 객체일 필요는 없다고 생각은 됩니다 :)

2023-10-21 06:01 UTC, eunbc commented on src/main/java/com/programmers/springbasic/enums/MenuType.java
> +public enum MenuType {
반영 완료하였습니다!

2023-10-21 06:01 UTC, eunbc commented on src/main/java/com/programmers/springbasic/command/CommandExecutor.java
> +	private static final Logger logger = org.slf4j.LoggerFactory.getLogger(CommandExecutor.class);
반영 완료하였습니다!

2023-10-21 06:01 UTC, eunbc commented on HELP.md
반영 완료하였습니다!

2023-10-21 06:01 UTC, eunbc commented on src/main/java/com/programmers/springbasic/controller/CustomerController.java
> +	public List<ListBlacklistCustomerResponse> listBlacklistCustomer() {
반영 완료하였습니다!

2023-10-21 06:02 UTC, eunbc commented on src/main/java/com/programmers/springbasic/dto/ListBlacklistCustomerResponse.java
> +	public String toString() {
반영 완료하였습니다!

2023-10-21 06:02 UTC, eunbc commented on src/main/java/com/programmers/springbasic/repository/voucher/MemoryVoucherRepository.java
> +@Profile("default")
완벽 이해하였습니다. 감사합니다 👍 
반영 완료하였습니다!

2023-10-21 06:03 UTC, eunbc commented on src/main/java/com/programmers/springbasic/configuration/CommandExecutorConfig.java
> +		return args -> commandExecutor.executeCommands();
반영 완료하였습니다!

2023-10-21 06:03 UTC, eunbc commented on src/main/java/com/programmers/springbasic/console/ConsoleInputHandler.java
> +		String value = scanner.nextLine().trim();
반영 완료하였습니다!

2023-10-21 06:03 UTC, eunbc commented on src/main/java/com/programmers/springbasic/console/ConsoleOutputHandler.java
> +	public <T> void printList(List<T> list) {
반영 완료하였습니다!

2023-10-21 06:03 UTC, eunbc commented on src/main/java/com/programmers/springbasic/entity/customer/Customer.java
> +	public Boolean getBlacklisted() {
반영 완료하였습니다!

2023-10-21 06:03 UTC, eunbc commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/macos,intellij,java,gradle
반영 완료하였습니다!

2023-10-21 06:11 UTC, eunbc commented on src/main/java/com/programmers/springbasic/dto/ListVouchersResponse.java
> +	private final UUID voucherId;
외부 시스템 없이 독립적으로 생성 가능하고, 손쉽게 생성할 수 있어 사용하였습니다!

하지만 단점으로는 다른 ID 체계와 비교했을 때 더 큰 저장 공간을 차지하고, 대량의 UUID를 생성할 경우 충돌 가능성이 있을 수 있습니다. 

시스템 요구 사항에 따라 ID를 순차 번호, 해시, 데이터베이스 시퀀스 등 다양한 방법으로 생성할 수 있을 것 같습니다!

2023-10-22 05:24 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/entity/customer/Customer.java
> +	private Boolean isBlacklisted;
설명 감사합니다! nullable한 데이터라면 Customer를 만드는 쪽에서도 타입을 Boolean으로 지정해주세요!

2023-10-22 05:28 UTC, aegis1920 approved these changes
코드리뷰가 많았는데 잘 반영해주셨군요! 고생 많으셨습니다! 1주차는 여기서 마무리하겠습니다~

2023-10-22 05:28 UTC, merged