[5기 김대휘] SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #889
Opened 2023-10-17 14:41 UTC by marooo326

## 📌 과제 설명 
## SpringBoot Part1 Weekly Mission

(기본) **바우처 관리 애플리케이션**

- [x] Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다.
    
- [x] 바우처 관리 Command-line Application을 만들어본다.
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x] 스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.)
    - [x] 프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x] create / list 커맨드를 지원한다.
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [ ] 적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다.
    
- [ ] 실행가능한 `jar` 파일을 생성한다.
    

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [x] 메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [x] 고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [x] YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.
## 👩‍💻 요구 사항과 구현 내용 
### console
프로젝트에서 전반적으로 쓰이는 MessageEnum을 담았습니다.

### domain
도메인인 customer와 voucher를 작성하였습니다.
voucher 패키지에는 두 가지의 Voucher와 VoucherType Enum, VoucherFactory를 작성하였습니다.

### repsoitory
메모리나 파일에 저장하는 역할의 Repository 클래스를 작성하였습니다.
인터페이스를 이용하여 추상화하였으며, CustomerRepository는 추후 확장을 위해 인터페이스를 미리 구현해놓았습니다.

### service
Voucher관련 주요로직이 수행되는 VoucherService 클래스를 작성하였습니다.

### view
입/출력과 관련된 Console 클래스 및 명령어 Enum인 Command Enum을 작성하였습니다.

## ✅ PR 포인트 & 궁금한 점

2023-10-17 14:47 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
> +public class VoucherFactory {
전략패턴을 사용하기 위해 VoucherFactory를 이용해 Voucher 객체를 생성하도록 구현하였습니다. 다만, domain 패키지에 VoucherFactory를 위치시키는 것이 올바른 방식인지 궁금합니다.

2023-10-17 14:59 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/view/Console.java
> +        logger.info("VoucherManagementApplication started");
로그의 경우에도 로그 메세지를 전부 Enum으로 묶어서 관리하는게 맞는지 궁금합니다! 현재는 어떤 부분에서 어떤 로그가 기록되는지 직관적으로 보이지 않는다고 생각해 Enum을 사용하지 않았습니다.

2023-10-17 15:10 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +    }
우선 fixed/percent 중 선택된 바우처를 생성하는 과정은 서비스 로직의 일부분이라고 생각하여 voucherService에서 처리하였습니다. (정확히는 값과 타입을 console에서 입력만 받아서 service로 전달하였습니다.)

다만, voucher의 종류를 선택하는 과정이 서비스 로직의 일부분인지 궁금합니다. 그렇다면 service에서 입/출력에 관여를 해야하는데 이를 어떻게 분리해야되는지 모르겠습니다.

2023-10-17 15:16 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
> +    }
try-with-resources 부분과 forEach안의 write하는 부분에서 CheckedException이 발생해서 try-catch를 두 번 감싸주었는데, 이를 개선할 방법을 모르겠습니다.

2023-10-17 15:25 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
> +        } catch (FileNotFoundException e) {
read의 경우 파일이 없다는 건 저장한 데이터가 존재하지 않는 것이라고 생각해 로그만 찍고 별다른 예외처리를 하지 않았는데, 프로그램 동작에 문제가 없는 경우 로그만 작성하여도 상관없는지 궁금합니다.

2023-10-19 16:41 UTC, aegis1920 requested changes
안녕하세요! 멘토 빙봉입니다 🙂 

코멘트 남겼으니 확인해주세요~

2023-10-19 16:41 UTC, aegis1920 commented on settings.gradle
> +rootProject.name = 'VoucherManagement'
프로젝트 명으로는 보통 소문자와 대시를 사용해서 작성하는 것으로 보입니다 ([링크](https://docs.gradle.org/current/userguide/multi_project_builds.html))

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/common/ConsoleMessage.java
> +public enum ConsoleMessage {
메시지를 Enum으로 관리하면 어떤 점이 좋고 어떤 점이 안 좋을까요?

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/common/ErrorMessage.java
> +    INVALID_COMMAND_MESSAGE("[System] Invalid command."),
콘솔 메시지와 개행이 다른데 일관성을 지켜주시면 좋을 것 같습니다!

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +public interface Voucher {
인터페이스로 뺀 이유를 설명해주실 수 있을까요?

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/customer/CustomerRepository.java
> +    // 추후 고객 추가, 삭제, 수정 기능이 필요 시 추가
👍

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
> +@Profile("file")
profile은 보통 개발하는 환경을 의미하는데요. (e.g. local, dev, prod...) 요구사항에도 개발 프로파일이라고 명시해뒀으니 좀 더 명확하게 작성해주는 게 좋을 것 같습니다. (e.g. dev)

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
> +        } catch (FileNotFoundException e) {
네! 예외를 잡고 아무런 처리 없이 알려주기만 해도 됩니다! 잘 작성해주셨어요 👍

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
> +public class VoucherFactory {
VoucherFactory 👍 현재 voucher 도메인이 그리 크지 않기 때문에 domain 패키지에 넣어둬도 괜찮을 것 같습니다. 너무 커진다면 domain > factory라는 패키지로 분리해도 좋을 것 같구요

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/MemVoucherRepository.java
> +public class MemVoucherRepository implements VoucherRepository {
클래스명을 줄이지 않아도 될 것 같습니다!ㅎㅎ

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +
개행 제거 부탁드립니다!

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +    public List<Voucher> voucherList() {
함수명은 동사로 시작해주세요!

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +    }
> voucher의 종류를 선택하는 과정이 서비스 로직의 일부분인지 궁금합니다. 그렇다면 service에서 입/출력에 관여를 해야하는데 이를 어떻게 분리해야되는지 모르겠습니다.

voucher의 종류를 선택하는 건 사용자이므로 Console에서 이뤄지고, 선택 자체도 Console의 역할로 봐야된다고 생각합니다! 지금 잘 작성해주셨습니다!

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/view/Console.java
> +    private final int VOUCHER_NAME_MIN_LENGTH = 1;
상수를 의미하신거라면 static을 붙여주고 코드 위치 또한 맨 위로 올리고 개행도 추가해야할 것 같습니다!

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/view/Console.java
> +        logger.info("VoucherManagementApplication started");
상황에 따라 다를 것 같긴한데요. 로그의 메시지는 보통 단발성으로 이뤄지기 때문에 중복으로 사용되는 경우가 적습니다. 또한 말씀대로 흐름을 보여주는 로깅의 용도이기 때문에 묶어서 관리하지 않습니다.

2023-10-19 16:41 UTC, aegis1920 commented on build.gradle
> +    targetCompatibility = '17'
👍

2023-10-19 16:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
> +        float afterDiscount = beforeDiscount - (beforeDiscount * discountAmount / 100);
퍼센트 단위인데 어느정도 검증이 있었으면 좋겠네요. 100%면 0원이니 100% 이하와 같은 검증같이요

2023-10-19 16:41 UTC, aegis1920 commented on src/main/resources/application.yml
> +  separator: ","
구분자를 외부 파일로 뺀 이유가 있을까요? 개인적으론 상수로 만들어도 충분하다고 생각되네요

2023-10-20 08:40 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/FixedAmountVoucher.java
> +        return afterDiscount < 0 ? 0 : afterDiscount;
0보다 작으면 0 이 반환되는 비즈니스는 명확할까요?

0보다 작다는 말은 이상하다고 생각해요.

따라서 예외처리가 필요 할 것으로 보여요.

2023-10-20 08:40 UTC, cloudwi commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
> +    public static Voucher createVoucher(UUID voucherId, String voucherName, float discountAmount, VoucherType voucherType) {
매개변수가 4개 인데 객체로 묶어보시는게 어떨까요?

가독성 이랑 관리측면에서 효율적이라고 생각해봐요!

2023-10-21 02:52 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/common/ConsoleMessage.java
> +public enum ConsoleMessage {
Enum으로 관리할 시, 메세지를 한 곳에서 관리할 수 있고, 잘못된 메세지를 입력하는 실수를 줄일 수 있다고 생각합니다.
안 좋은 점으로는 상황에 따라 동적으로 메세지를 출력하기 어렵고, 단발성 메세지의 경우 불필요한 공간을 차지한다는 점이 있을 것 같습니다!
여기서는 한 번에 Console에 출력되는 메세지를 관리하고자 Enum을 이용하였습니다.

2023-10-21 02:53 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +public interface Voucher {
필드를 상속받아서 사용한다는 것, Voucher가 특정한 역할을 가진다고 보기 어렵다는 점(어제 팀미팅 때 말씀해주신 내용)을 바탕으로 abstract class로 변경하여 리팩토링 하였습니다!

2023-10-21 02:54 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +
감사합니다! 여기저기 불필요한 개행이 많은 것 같아 제거하였습니다.

2023-10-21 02:59 UTC, marooo326 commented on src/main/resources/application.yml
> +  separator: ","
Path를 외부 파일로 분리하면서 csv 파일 읽기/쓰기와 관련된 구분자도 분리하면 좋을 것 같다는 생각에 분리하였습니다!
멘토님의 리뷰대로 상수로 바꿔놓긴 하였는데, 상수와 외부파일을 어떤 경우에 적절히 활용하는지 기준을 잘 모르겠습니다.
멘토님께서는 외부파일로 분리하는 경우와 상수로 놓는 경우에 대한 기준이 있으신지 궁금합니다!

2023-10-21 03:00 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
> +    public static Voucher createVoucher(UUID voucherId, String voucherName, float discountAmount, VoucherType voucherType) {
리뷰 남겨주셔서 감사합니다!
제가 이해하기로는 DTO를 통해 Factory에서 DTO 객체를 전달받아 Voucher를 생성한다고 이해했는데 멘토님이 생각하신 방향이 맞을까요??

2023-10-21 04:45 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/FixedAmountVoucher.java
> +        return afterDiscount < 0 ? 0 : afterDiscount;
voucher 객체가 생성될 때, 유효성을 검증하도록 구현하였습니다!

2023-10-21 04:45 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
> +        float afterDiscount = beforeDiscount - (beforeDiscount * discountAmount / 100);
voucher 객체가 생성될 때, 유효성을 검증하도록 구현하였습니다!

2023-10-22 05:14 UTC, aegis1920 commented on src/main/resources/application.yml
> +  separator: ","
상수는 변하지 않는 값을 선언할 때 사용하고, 외부 파일은 특정 값들을 한곳에 관리 및 환경에 따라 분리되는 값을 적용할 때 사용합니다. 그런 이유로 CSV_SEPARATOR의 경우 확정적인 값이기 때문에 상수가 맞다고 생각해서 코멘트 드렸고, 경로의 경우 환경에 따라 달라질 수 있기 때문에 코멘트 드리지 않았습니다. (지금은 로컬 환경뿐이라 괜찮지만 서버로 올리게 된다면 서버 내에 파일을 저장할 수 있으며 개발환경 상용환경 등 나눠질 수 있습니다)

2023-10-22 05:18 UTC, aegis1920 approved these changes
고생 많으셨습니다! 1주차는 여기서 마무리할게요!

2023-10-22 05:18 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/customer/FileCustomerRepository.java
> +import com.programmers.vouchermanagement.domain.customer.Customer;
추후 domain 패키지에 의존하지 않도록 CsvFileUtils 같은 클래스로 분리해도 좋을 것 같습니다!

2023-10-22 05:18 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +    public abstract float discount(float beforeDiscount);
Voucher가 discount의 역할을 갖고 있는게 맞는지 생각해보시면 좋을 것 같습니다! 할인과 같이 계산하는 역할을 VoucherCalculator과 같은 클래스로 분리하면 더 명확해지지 않을까요?

2023-10-22 05:18 UTC, merged