Dev
prgrms-be-devcourse/springboot-basic pull request #893
Opened 2023-10-18 10:39 UTC by KarmaPol

## 📌 과제 설명 
(기본) **바우처 관리 애플리케이션**

- [x] Maven / Gradle 로 프로젝트를 실제로 구성하고 이때 Spring Boot CLI를 개발PC에 설치해서 명령어들을 사용해보고 프로젝트를 만든다. 그리고 IDE (IntelliJ)에서 실행시켜 본다. ✅ 2023-10-18
    
- [x] 바우처 관리 Command-line Application을 만들어본다.
    
    - 참고: [https://dzone.com/articles/interactive-console-applications-in-java](https://dzone.com/articles/interactive-console-applications-in-java)
    - [x] 스프링부트 애플리케이션으로 만든다. (Web기능이 없이 만듭니다. 즉, 서버가 띄지 않고 커맨드라인 애플리케이션으로 동작해야한다.) ✅ 2023-10-18
    - [x] 프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다. ✅ 2023-10-18
    
    ```bash
    === Voucher Program ===
    Type **exit** to exit the program.
    Type **create** to create a new voucher.
    Type **list** to list all vouchers.
    ```
    
    - [x] create / list 커맨드를 지원한다. ✅ 2023-10-18
        - create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
        - list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
        - this바우처 정보를 메모리에 관리한다. 어플리케이션이 종료가 되어 데이터가 모두 사라져도 괜찮습니다. (나중에 영속성을 가지도록 변경할거에요 걱정마세요!)
- [x] 적절한 로그를 기록하고 `logback` 설정을 해서 에러는 파일로 기록된다. ✅ 2023-10-18
    
- [x] 실행가능한 `jar` 파일을 생성한다.
    

(심화) 파일을 통한 데이터관리 기능과 고객 블랙 리스트 명단 관리기능

- [ ] 메모리 관리가 아닌 파일로 관리가 되는 Repository를 한번 만들어보세요.
    - 기존 메모리 레포지토리는 지우지 말고 개발 프로파일에서만 동작하게 해보세요.
- [ ] 고객 블랙 리스트 명단을 작성한다.
    - customer_blacklist.csv 파일을 만들고 스프링 애플리케이션에서 해당 파일을 읽을 수 있고 블랙 리스트조회 할 수있다 (추가할 필요는 없어요. 블랙리스트는 파일로만 관리된다고 가정합니다.)
- [ ] YAML 프라퍼티를 만들고 어떤 설정을 만들수 있을지 고민해본다.

기본 요구사항은 구현 완료하였고, 심화 요구사항은 추가할 예정입니다.

## 👩‍💻 요구 사항과 구현 내용 
- ConsoleView : console을 통해 input, output을 입출력합니다. text.io를 사용했습니다
- VoucherController : view를 호출하고 이를 통해 입력받은 dto를 검증하거나 service단의 메서드를 실행합니다
- Vocher : 겹치는 필드가 많아 FixedAmountDiscount, PercentDiscountVoucher가 상속받도록 추상 클래스로 정의하였습니다.  
정적팩토리메서드를 통해 discount policy에 맞게 각 인스턴스를 생성하도록 했습니다.
- VoucherRepository : Voucher을 저장하고, list를 불러오는 메서드를 갖고 있고, 기본적인 메모리 구현체를 구현했습니다.
- VoucherService : Voucher을 생성해 Repository에 저장하거나 불러오는 로직을 담당합니다

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
-  다른 분들 코드를 봤을때 Controller을 굳이 만들지 않고 Console에서만 처리한 경우도 있었는데
View, Controller로 나누는 것이 적절한지 궁금합니다
- VoucherController에서 커맨드에 따라 switch문으로 분기하였는데 이러한 방식이 적절한지 궁금합니다
- VoucherController에서 invalid한 입력을 검증하는 메서드를 두었는데, Controller에서 처리하는 것이 적절한지 그리고 검증한 방식을 개선할 수 있을지 궁금합니다

2023-10-19 16:59 UTC, aegis1920 requested changes
안녕하세요 멘토 빙봉입니다 🙂 
새벽까지 열심히 하고 계시는군요ㅎㅎ 
clone시 바로 작동되는 상태가 되도록 만들어주시면 감사하겠습니다! 🙇 

> 다른 분들 코드를 봤을때 Controller을 굳이 만들지 않고 Console에서만 처리한 경우도 있었는데 View, Controller로 나누는 것이 적절한지 궁금합니다

나누면 어떤 점이 좋고 어떤 점이 안 좋을까요? 지금 상황에서는 나누지 않고 Console에서만 처리해도 무방하다고 생각해요. Controller가 따로 하는 역할이 없어보이기도 하고, 만약 있다고 해도 단순히 View와 Service를 연결시켜준다는 것 뿐이라고 생각이 들었습니다. Controller 레이어에서 뭔가 로직이 들어가거나 한다면 그때 나눠줘도 될 것 같습니다!

> VoucherController에서 커맨드에 따라 switch문으로 분기하였는데 이러한 방식이 적절한지 궁금합니다

커맨드에 따라 어떤 함수를 실행하는 것은 여러 방법으로 진행할 수 있습니다. (단순 if, switch, Map, Enum 등등..) 구현 방법에 따라 크게 차이가 있는 건 아니라 switch로 한 것도 충분하다고 생각듭니다!

위에 Controller 없이 Console에서만 처리해도 무방하다고 이야기했는데요. 보니까 커맨드에 따라 어떤 로직을 실행해주는 역할은 Controller에서 하는 게 적절해보이는군요ㅎㅎ Controller가 있으면 더 좋은 로직이 될 것 같습니다! (지금 잘해주셨어요! 👍 )

> VoucherController에서 invalid한 입력을 검증하는 메서드를 두었는데, Controller에서 처리하는 것이 적절한지 그리고 검증한 방식을 개선할 수 있을지 궁금합니다

검증은 여러 곳(Console, Controller, Service, Domain)에서 할 수 있는데요. discount 값이 특정 값보다 크고 작은 건 도메인 자체(Voucher)에 대한 내용이라고 생각듭니다. 도메인 내에 구현해도 좋을 것 같아요. Voucher.isDiscountable 이런 식으로요

코멘트 남겼으니 확인 부탁드려요!

2023-10-19 16:59 UTC, aegis1920 commented on .DS_Store
ignore에 추가해주세요~

2023-10-19 16:59 UTC, aegis1920 commented on basic/logs/basic-2023-10-18.log
이것도 ignore해야겠군요

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/DemoApplication.java
> +public class DemoApplication {
Demo 보다는 좀 더 어플리케이션 이름에 맞게 지어보는 건 어떨까요?

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/view/ConsoleView.java
> +    private TextIO textIO = TextIoFactory.getTextIO();
final을 붙여줘도 좋을 것 같습니다!

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/view/ConsoleView.java
> +    public void error(RuntimeException e){
런타임 잡아도 될까요? 전체를 잡아야하지 않을까요?

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +    private final int FIXED_VOUCHER_CREATE = 1;
- 1로 고정할거라면 상수로 만들어줘도 될 것 같습니다! (static 추가)
- enum을 사용하는 방법이 더 직관적일 것 같아요!

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +    private boolean validateDiscountAmount(VoucherCreateRequestDto voucherCreateRequestDto) {
boolean 리턴은 함수명 isXXX로 시작하는 것이 관례입니다!

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/dto/VoucherCreateRequestDto.java
> +public record VoucherCreateRequestDto(Integer command, Integer discount) {
👍

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/entity/FixedAmountDiscountVoucher.java
> +}
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij를 사용하고 계시다면 파일을 저장할 때마다 개행을 자동으로 넣어주도록 할 수 있습니다! (Settings → Editor → General → Ensure line feed at file end on Save)

2023-10-19 16:59 UTC, aegis1920 commented on .DS_Store
맥을 쓰시나보군요ㅎㅎ gitignore에 추가해야할 것 같습니다!

2023-10-19 16:59 UTC, aegis1920 commented on basic/logs/basic-2023-10-18.log
이 부분도 ignore 시켜줘야할 것 같아요!

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/ProgramRunner.java
> +    public void run(String... args) throws Exception {
예외가 발생해서 이곳까지 throw된다면 프로그램은 어떻게 되나요?

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/customer/controller/CustomerController.java
> +    public void blackList(){
함수명은 동사로 시작해주세요!

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/customer/repository/CustomerFileRepository.java
> +    private String FILE_PATH;
- 상수가 아닌데 왜 대문자일까요?
- 외부 값 주입이라면 final을 붙여도 될 것 같습니다

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +                return voucherCreateRequestDto.discount() >= 0;
단순히 0만 큰 게 아니라 max도 있었으면 좋겠네요

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/repository/VoucherFileRepository.java
> +@Profile("file")
profile은 보통 개발하는 환경을 의미하는데요. (e.g. local, dev, prod...) 요구사항에도 개발 프로파일이라고 명시해뒀으니 좀 더 명확하게 작성해주는 게 좋을 것 같습니다. (e.g. dev)

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/repository/VoucherFileRepository.java
> +            throw new RuntimeException("can not create file!!");
- 파일을 생성하다가 에러가 발생하면 어떻게 되나요?
- 만약 서버라고 가정해본다면 에러가 발생했을 때 서버가 죽지 않을까요?
- 죽지 않게 하려면 어떻게 해야할까요?

2023-10-19 16:59 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/customer/repository/CustomerFileRepository.java
> +    private void loadfile() {
함수명을 카멜케이스로 만들어주세요!

2023-10-20 08:49 UTC, cloudwi commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +        VoucherMenuRequestDto voucherMenuRequestDto = consoleView.init();
consoleView.init()의 정확한 의도가 무엇인가요?

초기화 하는 것 인가요? VoucherMenuRequestDto 생성하는 것 인가요?

2023-10-20 08:49 UTC, cloudwi commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +                consoleView.error(new RuntimeException("Please Enter Again!!"));
사용자의 잘못된 입력에 error 레벨 로그를 남기는 것은 불필요한 파장을 불러일으킬 수 있어요!

2023-10-20 08:49 UTC, cloudwi commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +            log.error("Invalid Create Input");
위와 동일 합니다. Error 레벨의 로그는 불필요한 사이드 이팩트를 발생 시킬 수 있어요.

2023-10-22 10:17 UTC, KarmaPol reviewed
피드백에 맞게 코드를 수정하였습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/DemoApplication.java
> +public class DemoApplication {
VoucherApplication으로 수정했습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/ProgramRunner.java
> +    public void run(String... args) throws Exception {
프로그램이 죽을 것 같습니다
spring web의 경우, @ControllerAdvice로 전역 예외 처리를 해줄 것 같은데
이번 과제의 경우에는 try catch문으로 감싸줘야 할 것 같습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/customer/controller/CustomerController.java
> +    public void blackList(){
네 동사형으로 수정했습니다!

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +    private final int FIXED_VOUCHER_CREATE = 1;
static 추가해서 상수로 고정했습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +        VoucherMenuRequestDto voucherMenuRequestDto = consoleView.init();
Controller가 View의 시작 페이지를 불러오는 메소드입니다
의도에 맞게 getMenu()로 수정했습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +                consoleView.error(new RuntimeException("Please Enter Again!!"));
확실히 사용자 콘솔의 잘못된 입력마다 에러를 출력하는 건 이상하다고 생각이 드네요
warn이나 info로 수정하는 게 좋을것 같습니다!

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +    private boolean validateDiscountAmount(VoucherCreateRequestDto voucherCreateRequestDto) {
관례에 맞게 수정했습니다!

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/voucher/repository/VoucherFileRepository.java
> +@Profile("file")
dev, local로 수정했습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/view/ConsoleView.java
> +    public void error(RuntimeException e){
전체 exception을 잡도록 수정했습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/view/ConsoleView.java
> +    private TextIO textIO = TextIoFactory.getTextIO();
final 키워드를 붙여줬습니다!

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/domain/voucher/repository/VoucherFileRepository.java
> +            throw new RuntimeException("can not create file!!");
- 지금 코드에서는 파일 생성시 에러가 발생하면 에러메시지만 출력하고 그대로 죽어버릴 것 같습니다
- 네 exception이 발생하면 서버가 죽을 것 같습니다
- 전역 예외 처리를 하면 깔끔할 것 같습니다. Spring web의 @ControllerAdvice로 처리를 해줄수 있을 것 같은데
이번 과제에서는 web기능을 사용하지 않으므로 java의 try-catch문을 사용하였습니다

2023-10-22 10:17 UTC, KarmaPol commented on basic/src/main/java/com/pgms/part1/ProgramRunner.java
> +    public void run(String... args) throws Exception {
에러가 터져도 초기화면으로 갈수 있도록 while문을 추가하고
try catch문으로 에러 로그를 찍어주도록 처리했는데, java application은 exception을 이렇게 처리해주는게 맞을까요?

2023-10-22 13:11 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/domain/voucher/controller/VoucherController.java
> +    private final int FIXED_VOUCHER_CREATE = 1;
Controller에서 관리되는 상수보다는 Enum으로 생성되는 게 더 낫다고 판단됩니다!

2023-10-22 13:11 UTC, aegis1920 commented on basic/src/main/java/com/pgms/part1/ProgramRunner.java
> +    public void run(String... args) throws Exception {
넵! 이 정도면 충분합니다!

2023-10-22 13:14 UTC, aegis1920 commented
@KarmaPol 
고생 많으셨습니다! [이쪽](https://github.com/prgrms-be-devcourse/springboot-basic/pull/893#pullrequestreview-1687459433)에서 언급했다시피 git repo clone시 바로 작동되는 상태가 되도록 만들어주세요! (현재 root가 basic 디렉토리라 인식되지 않고 있습니다) 이것만 반영되면 바로 머지하겠습니다!

2023-10-22 14:38 UTC, KarmaPol commented
git상에는 spring-basic 폴더가 root이고, 제 프로젝트 root는 하위 폴더인 basic이어서 clone시 자동 인식이 안되었네요..🥲
basic 폴더를 삭제하고 spring-basic 폴더를 프로젝트 root로 하도록 수정 후 clone하여 확인했습니다!

2023-10-22 15:31 UTC, aegis1920 approved these changes
빠른 피드백 반영 감사합니다 👍  머지하겠습니다!

2023-10-22 15:31 UTC, merged