[5기 - 이세희] SpringBoot Part1 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #900
Opened 2023-10-19 14:57 UTC by Sehee-Lee-01

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 

## ✅ PR 포인트 & 궁금한 점 
각 클래스에서 필요한 메세지들을 각 클래스 내에서 직접 관리하도록 저장을 했는데 따로 클래스를 분리해서 사용을 하는 것이 나을지 저렇게 일일이 클래스 안에 넣을지 고민이 들었습니다. 나은 방법이 있을까요? 
예외룰 던지는 곳과 받는 곳을 즁점으로 피드백을 받고 싶숩니다.
콘솔 패키지 내의 클래스들의 역할 분담을 중심우로 피드백을 받고 싶숩니다.
레포지토리에서 제이슨 정보를 바우처로 변환할 때 디티오가 필뇨할까요? 
서비스 부분에서만 바우처를 쓰는것이 나을지 레포지토리까지 바우처를 끌고가는 것이 나을 지 궁금합니다.
바우처 타입의 네임은 콘솔 부분을 위한 값인데 이 바우처타입은 컨트롤러. 서비스. 레포지토리 부분에서도 사용하는 타입입니다. 콘솔에서 쓰이는 정보만을 가진 타입과 컨트롤러.서비스,레포지토리에서 쓰이는 정보만으로 가진 타입을 분리하는 것이 나을지 이를 한 곳에 모아서 지금처럼 전역으로 쓰이게 하는 것이 나을지 궁금합니다.

2023-10-21 15:58 UTC, ksy90101 requested changes
1. 그레들로 변경하기.
2. 상속 또는 조합을 사용해보기.

를 진행해보세요 :)

2023-10-21 15:58 UTC, ksy90101 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
요즘엔 메이븐이 아니라 그레들을 쓰는 추세입니다.
한번 그레들로 마이그래이션 해보시겠어요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/configuration/AppConfig.java
> +public class AppConfig {
👍

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/domain/Customer.java
> +    private final boolean isBlack;
validate를 할게 없을지 고민해보시면 좋을거 같습니다.

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +                .toList();
외부에서 변경하면 쉽게 변경 가능해지지 않을까요?
https://lts0606.tistory.com/133
불변을 한번 해보면 어떨까요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +                String[] line = str.split(", ");
", "를 상수로 처리하면 어떨까요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/properties/AppProperties.java
> +@ConfigurationProperties(prefix = "file")
@Value 방식과 ConfigurationProperties 방식중에 이걸 선택한 이유가 있나요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/properties/AppProperties.java
> +    public void setResources(Resources resources) {
가변이 아니라 불변으로 처리해보면 어떨까요?
https://woodcock.tistory.com/18

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/FixedAmountVoucher.java
> +    }
validate가 굿굿입니다 👍

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/FixedAmountVoucher.java
> +    }
근데 혹시~ 라도 long보다 더 큰값이 들어오면 어떻게 될까요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
과연 inteface가 어울릴까요?
모델은 inferface보단 상속 또는 조합방식이 전 더 어울린다고 생각해요.
지금같이 중복 코드들이 존재하니깐요.

상속과 조합을 알아보고 그 둘중에 더 맞다고 생각하는 방식으로 변경하면 어떨까요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/PercentVoucher.java
> +        return (long) (priceBeforeDiscount * (1 - discountPercent / 100D));
매직넘버들은 상수화를 하면 좋겠습니다.

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/PercentVoucher.java
> +        if (discountPercent <= 0 || discountPercent > 100) {
매직넘버들은 상수화를 하면 좋겠습니다.

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherType.java
> +    public static Optional<VoucherType> findCreateMenu(String input) {
(질문)
optional로 처리한 이유가 있나요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/dto/CreateVoucherRequestDTO.java
> +public record CreateVoucherRequestDTO(VoucherType voucherType, long discountValue) {
👍 
모델에서도 validate가 중요하지만 DTO도 validate가 중요하다고 생각합니다.

spiring validation을 이용해 한번 해보면 어떨까요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +//    private static final String FILE_PATH="src/main/resources/voucher.json";
사용하지 않는 주석은 제거해주세요

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
👍

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +    private Map<UUID, Voucher> vouchers;
불변인 final을 안해도 될까요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +        System.out.println(filePath);
로그성으로 남긴거 같은데요. 제거하면 어떨까요?

2023-10-21 15:58 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +        return vouchers.values().stream().toList();
불변을 위해 이것도 불변 리스트로 하면 어떨까요?

2023-10-23 06:30 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +                .toList();
```
    default List<T> toList() {
        return (List<T>) Collections.unmodifiableList(new ArrayList<>(Arrays.asList(this.toArray())));
    }
```

말씀해주신 것을 보고 리팩토링을 해보다가, `toList()`가 `Collections.unmodifiableList`를 반환 하기에 불변이 되는 것 같습니다! 불변리스트 라는 것을 명시 해줘야 한다는 뜻으로 생각하면 될까요?

2023-10-23 06:32 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/properties/AppProperties.java
> +@ConfigurationProperties(prefix = "file")
스프링 부트에서 제공해주는 어노테이션을 활용해 더욱 간편하게 해보고자 하는 의미로 선택했습니다!

2023-10-23 06:32 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/FixedAmountVoucher.java
> +    }
그러한 값을 처리하기 위해 `BigDecimal`로 변경해서 처리하도록 하겠습니다!

2023-10-23 06:33 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/FixedAmountVoucher.java
> +public class FixedAmountVoucher implements Voucher {
강의에서 알려주는 내용을 어느정도 따라가다보니 인터페이스를 사용했던 것 같습니다. 추상클래스를 이용하거나 조합을 이용하는 방식으로 변경하겠습니다

2023-10-23 06:35 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherType.java
> +    public static Optional<VoucherType> findCreateMenu(String input) {
맞는 바우처를 리턴해주기만 하는 역할을 부여하고 해당하는 바우처가 없음에 관한 처리를 외부에서 하려고 했습니다!

2023-10-23 06:36 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +    private Map<UUID, Voucher> vouchers;
final로 변경하도록 하겠습니다!

2023-10-23 06:36 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +        System.out.println(filePath);
마지막에 급하게 하다보니 이런 실수가 있었습니다. 죄송합니다! 제거하겠습니다

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/configuration/AppConfig.java
> +    // Static logger to be used in wherever willing to use
이 주석은 필요없을꺼 같애요.

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandler.java
> +    // ConsoleAppRunner --> Menu <-- MenuHandler
주석도 유지보수 리소스가 들어갑니다. 로직이 바뀌면 주석도 바뀌어야 하기 때문입니다. 코드와 관련있고 잘 설명하는 경우에만 주석을 달면 좋을 것 같습니다.

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +    private void loadBlacklist() throws UncheckedIOException {
throws가 필요한 이유가 있나요??

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/customer/service/CustomerService.java
> +            throw new NoSuchElementException(NO_BLACKLIST);
모든 블랙리스트를 조회하는데 블랙리스트가 없는 경우는 예외 상황이 아니라고 생각합니다. 그냥 빈 리스트를 반환해줄 수 있을 것 같습니다.

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/voucher/service/VoucherService.java
> +            throw new NoSuchElementException(VOUCHER_NOT_FOUND_MESSAGE);
여기도 모든 바우처를 조회할 때 바우처가 없는 경우는 예외 상황이 아니라고 생각합니다.

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/voucher/dto/VoucherResponse.java
> +public record VoucherResponse(UUID voucherId, BigDecimal discountValue, VoucherType voucherType) {
record를 이용하여 dto를 만드는 것이 class로 dto를 만드는 것에 비해 이점이 뭐가 있나요??

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherType.java
> +    private static BiFunction<BigDecimal, BigDecimal, BigDecimal> getFixedBiFunction() {
이 아래 static function들은 지금 쓰이지 않는 function들이라서 오버 엔지니어링인거 같애요! 요구사항이 어떻게 변할지 모르는 상황에서 미래를 예측해서 추가적인 개발은 굳이 필요하지 않는 것 같습니다!

2023-10-23 14:58 UTC, twotwobread commented on src/main/java/com/programmers/vouchermanagement/consoleapp/menu/Menu.java
> +        return Objects.equals(menuName, input);
👍

2023-10-24 01:25 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
> +        return vouchers.values().stream().toList();
질문에 대한 비슷한 [답변](https://github.com/prgrms-be-devcourse/springboot-basic/pull/900#discussion_r1368182137)입니다!

2023-10-24 01:28 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/customer/service/CustomerService.java
> +            throw new NoSuchElementException(NO_BLACKLIST);
반영하겠습니다!

2023-10-24 01:29 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/voucher/service/VoucherService.java
> +            throw new NoSuchElementException(VOUCHER_NOT_FOUND_MESSAGE);
넵!! 이것도 반영 했습니다!

2023-10-24 12:01 UTC, IjjS commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
메이븐을 써보지 않았으니 써보자는 의미로 써봤습니다. 반영하겠습니다!

2023-10-24 12:02 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/domain/Customer.java
> +    private final boolean isBlack;
사실 어떤 것을 validate 해야할지 감이 잘 안 잡힙니다. 조언을 주신다면 감사히 받겠습니다!

2023-10-24 12:02 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +                String[] line = str.split(", ");
반영하겠습니다!

2023-10-24 12:03 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/properties/AppProperties.java
> +    public void setResources(Resources resources) {
이런 방법이 있었는지 몰랐습니다. 배운 방식대로면 setter사용은 어쩔 수 없는걸까 싶었는데 도움이 되었습니다. 감사합니다!

2023-10-24 12:06 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +    private void loadBlacklist() throws UncheckedIOException {
막바지에 급하다보니 실수한 것 같습니다. 제거하겠습니다!

2023-10-24 12:23 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherType.java
> +    private static BiFunction<BigDecimal, BigDecimal, BigDecimal> getFixedBiFunction() {
맞습니다. 강의를 보며 진행하다보니 강의에서 나왔던 내용을 반영했던 것도 있는 것 같습니다. 제거해놓도록 하겠습니다!

2023-10-24 12:50 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/configuration/AppConfig.java
> +    // Static logger to be used in wherever willing to use
인재, 세희 반영했습니다!!

2023-10-24 12:50 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandler.java
> +    // ConsoleAppRunner --> Menu <-- MenuHandler
인재, 세희 반영했습니다!!

2023-10-24 12:51 UTC, Sehee-Lee-01 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
인재, 세희 반영했습니다!!

2023-10-24 13:23 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +    private void loadBlacklist() throws UncheckedIOException {
인재, 세희 반영했습니다!!

2023-10-24 16:35 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/voucher/dto/CreateVoucherRequestDTO.java
> +public record CreateVoucherRequestDTO(VoucherType voucherType, long discountValue) {
spiring validation을 활용해보진 못했지만 validate는 반영했습니다!

2023-10-24 16:47 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/voucher/dto/VoucherResponse.java
> +public record VoucherResponse(UUID voucherId, BigDecimal discountValue, VoucherType voucherType) {
Dto는 계층 간 데이터를 전달할 때 쓰이는 클래스인데 이를 보통은 불변으로 만들고 Getter를 놓는 것으로 알고 있습니다! 이런 과정이 많아지고 이를 class로 두면 반복적인 코드가 생성돠는데, 이를 더 간편하게 해주는 것이 record로 알고 있습니다!

2023-10-24 16:48 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/voucher/dto/VoucherResponse.java
> +public record VoucherResponse(UUID voucherId, BigDecimal discountValue, VoucherType voucherType) {
아무래도 가독성 측면에서, 코드 관리 측면에서 이점이 있지 않나 생각이 듭니다!

2023-10-26 07:10 UTC, ksy90101 approved these changes
고생많으셨습니다 :) 2단계에서 추가적으로 이야기 나눌게요~

2023-10-26 07:10 UTC, merged