[5기 - 박영재] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #911
Opened 2023-10-25 15:50 UTC by park0jae

## 📌 과제 설명 

**(기본)** **바우처 관리 애플리케이션**

- [X] 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [X] 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [X] (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [X] 특정 고객에게 바우처를 할당할 수 있습니다.
- [X] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [X] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [X] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 

### domain
- wallet : 바우처와 회원 사이에서 지갑의 역할을 갖고 있습니다.

</br> 

### Repository (Profile : prod)

- JdbcCustomerRepository : NamedParameterJdbcTemplate을 이용한 CRUD 기능의 회원 리포지토리 구현
- JdbcVoucherRepository : NamedParameterJdbcTemplate을 이용한 CRUD 기능의 바우처 리포지토리 구현
- JdbcWalletRepository : NamedParameterJdbcTemplate을 이용한 지갑 기능의 Wallet 리포지토리 구현

</br>

### util

- FileUtil : 기존 FileRepository 내의 파일 관련 로직을 FileUtil 클래스 내로 분리했습니다.
- UuidConverter : UUID와 바이트 배열 간의 변환을 수행하는 유틸리티 클래스입니다.

</br>

---

### 도커로 MySQL 세팅 (실제 애플리케이션에서 MySQL사용을 위해 세팅 했습니다.)

```bash
docker run -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=1234 --name test-mysql mysql

docker exec -it test-mysql bash

# 도커 컨테이너에 접속
mysql -u root -p

# 1234를 입력하여 DB에 접속
Enter passowrd :

mysql> create database VoucherProgram;

```

</br>

### 데이터베이스 테이블 정보

```mysql
CREATE TABLE IF NOT EXISTS customers (
      customer_id BINARY(16) PRIMARY KEY,
      customer_name VARCHAR(255) NOT NULL,
      customer_type VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS vouchers (
      voucher_id BINARY(16) PRIMARY KEY,
      discount BIGINT NOT NULL,
      voucher_type ENUM('FIXED', 'PERCENT') NOT NULL,
      use_status_type VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS wallets (
      wallet_id   INT PRIMARY KEY AUTO_INCREMENT,
      customer_id BINARY(16) NOT NULL,
      voucher_id  BINARY(16)  NOT NULL,
      FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE,
      FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE
);
```

## ✅ PR 포인트 & 궁금한 점 

- 일부 궁금한 사항은 코멘트로 남겨놓겠습니다 !
- 전반적으로 궁금한 사항은 테스트 코드에 대한 메서드 네이밍이나 테스트 로직이 적합한지 궁금합니다. 또 추가할만한 테스트가 있을지 궁금합니다 !

2023-10-25 15:59 UTC, park0jae commented on src/main/resources/schema.sql
> +      use_status_type VARCHAR(255) NOT NULL
DB 테이블에 ENUM 타입을 지정했다가, 변경 가능성이 존재하면 ENUM의 사용을 지양하는 것이 좋다고 생각하여 VARCHAR 타입으로 대체하였는데, TINYINT나 다른 타입으로 바꾸는 것이 좋을까요 ?

2023-10-25 15:59 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/wallet/WalletController.java
> +    private final CustomerService customerService;
현재 WalletController 에서 wallet, voucher, customer 서비스들을 의존하고 있습니다. 로직을 구현하다 보니 지갑으로 부터 회원과 바우처의 아이디를 반환 받고 각각 서비스들을 통해 적절한 반환타입을 다시 가져오는데 이렇게 의존해도 괜찮을까요 ?

ex) 회원이 보유한 바우처 리스트 조회
- WalletService를 통해 회원 아이디와, 바우처 아이디가 담겨 있는 WalletResponse 객체를 반환 받습니다.
- 바우처 리스트 조회를 위해 바우처 아이디들을 바우처 서비스의 find 메소드를 통해 반환 해옵니다.
- 마지막으로 WalletController가 VoucherReponse 객체들을 반환해주고 MenuHandler 쪽에서 출력해줍니다.

2023-10-25 15:59 UTC, park0jae commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +    }
현재 CustomerService에서 update 메소드 같은 경우 CustomerRequest 객체와 필드값이 동일하다고 생각하여 업데이트 요청에 대한 CustomerUpdateRequest 객체를 따로 만들어 사용하고 있지 않습니다. 이런 경우에도 그냥 생성과 업데이트에 대한 각각 DTO 클래스를 만들어주는 것이 좋을까요 ?

2023-10-25 15:59 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +        }
예외 메세지를 던질 때 문자열 자체를 해당 클래스 내에서 한 부분에서만 사용한다면 굳이 상수로 빼주지 않았습니다. 한 클래스 내에서 여러 부분에서 사용되는 경우에만 빼주었는데 혹시 전자의 경우에도 다 빼주는게 좋을까요 ?

2023-10-27 00:25 UTC, park0jae commented on src/test/java/com/zerozae/voucher/service/customer/CustomerServiceTest.java
> +        verify(customerRepository, times(1)).findAll();
서비스 레이어 테스트 시 Mocking을 통해 테스트를 진행했는데, 특정 값을 리턴값으로 지정해놓고 테스트 하다보니 결국은 assertEquals 와 같은 검증은 의미가 없나? 라고 생각이 들기도 합니다. 서비스 레이어처럼 Mocking을 통해 테스트를 진행하는 부분에서는 verify로 메소드가 호출되는지만 검증하면 될 지 궁금합니다 !

2023-10-27 01:10 UTC, park0jae commented on src/main/resources/schema.sql
> +      deleted CHAR(1) DEFAULT 'N'
멘토님께서 말씀 해주셨던 외래키 제약조건을 두지 않고 별도의 컬럼을 설정하여 soft delete로 구현하기 위해 테이블을 수정했습니다 !

2023-10-27 01:12 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/wallet/WalletRepository.java
> +    }
soft delete를 위해 deleted 컬럼을 추가하고 난 이후 save시 기존에 삭제된 레코드가 존재하는지 즉, deleted 필드가 'Y'인 레코드가 존재하는지 먼저 확인하고 존재하면 update를 진행하고 존재하지 않으면 insert를 하도록 구현해줬는데 해당 로직이 적절한지 궁금합니다 !

2023-10-27 09:01 UTC, annahxxl commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +    }
저는 분리하여 작성하는 것이 중복 코드가 좀 발생하더라도 더 명확하다고 생각이 되어 선호하긴 합니다,, 저도 멘토님들은 어떠신지 궁금하네요

2023-10-27 09:08 UTC, annahxxl commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +@Transactional(readOnly = true)
사소한 거긴 한데, 현재 클래스 내 메서드는 읽기 전용 트랜잭션이 필요하지 않은 메서드가 더 많은데 클래스 레벨에 @Transactional을 디폴트 옵션으로 달지 않고 읽기 전용 옵션을 포함하여 달아준 이유가 있으신가요? 궁금하여 여쭤봅니다!

2023-10-27 09:24 UTC, annahxxl commented on src/test/java/com/zerozae/voucher/service/customer/CustomerServiceTest.java
> +        verify(customerRepository, times(1)).findAll();
저도 verify로 메서드 호출하는 것만 의미 있겠다 싶어서 verify만 작성하긴 했습니다! 근데 생각해 보니 다음부터는 넘겨주어야 할 파라미터가 있다면 이것들도 함께 검증해 주면 좋을 것 같다는 생각이 듭니다!

2023-10-27 09:34 UTC, annahxxl commented on src/test/java/com/zerozae/voucher/domain/customer/CustomerTest.java
> +        assertEquals(createdCustomer.getCustomerName(), username);
해당 프로젝트에서만 junit 메서드를 사용하신지 모르겠으나 assertj도 많이 활용해 보시면 좋을 것 같습니다! assertj에서 제공해 주는 메서드들이 명확하고 가독성이 좋다고 느껴져서요! ++추가로 복잡한 테스트 케이스에서도 이를 간결하게 진행할 수 있도록 도와준다고 하네요(저도 사용해 본 경험은 없음ㅎㅎ🥹)

2023-10-27 09:36 UTC, annahxxl commented on src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +    private CustomerType customerType;
오호 저는 그냥 boolean 값으로 지정해 줬는데, 확장성 생각하면 타입으로 빼는게 좋은 것 같네요 👍

2023-10-27 09:38 UTC, annahxxl commented on src/test/java/com/zerozae/voucher/service/customer/CustomerServiceTest.java
> +        assertEquals(normalCustomer.getCustomerName(), customerResponse.getCustomerName());
해당 프로젝트에서만 junit 메서드를 사용하신지 모르겠으나 assertj도 많이 활용해 보시면 좋을 것 같습니다! assertj에서 제공해 주는 메서드들이 가독성이 되게 좋다고 느껴져서요! 추가로 복잡한 테스트가 필요하더라도 이를 편하게 진행할 수 있도록 도와준다고 하네요(저도 사용해 본 경험은 없음ㅎㅎ🥹)

2023-10-27 09:48 UTC, annahxxl commented on src/main/resources/schema.sql
> +      use_status_type VARCHAR(255) NOT NULL
enum 관련해서 해당 아티클 한 번 읽어보셔도 좋을 것 같습니다! [[번역] MySQL의 ENUM 타입을 사용하지 말아야 할 8가지 이유](https://velog.io/@leejh3224/%EB%B2%88%EC%97%AD-MySQL%EC%9D%98-ENUM-%ED%83%80%EC%9E%85%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-8%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0)
저는 그래도 tinyint보다는 varchar 타입으로 저장하는 것이 명확하지 않나 싶습니다

2023-10-27 10:23 UTC, annahxxl commented
영재님 너무 고생 많으셨습니다! 보면서 정말 꼼꼼히 작성하신 게 잘 느껴졌습니다.. (성실 그 자체) 영재님 코드 보면서 제가 놓친 예외도 발견했습니다ㅋㅋ🥹, 저도 많이 배우고 갑니다!

2023-10-27 13:39 UTC, park0jae commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +@Transactional(readOnly = true)
당장은 가독성 측면에서 클래스 레벨에 읽기전용 옵션을 달아주는 것보단 조회하는 메서드에 직접 readOnly 옵션을 부여하는 것이 더 좋을 것 같네요 ! 감사합니다.🙂

2023-10-27 15:40 UTC, aegis1920 commented on src/main/resources/schema.sql
> +      use_status_type VARCHAR(255) NOT NULL
TINYINT로 지정하면 INT 값만 저장할 수 밖에 없어서 voucher_type을 명확하게 표현하기가 어려울 것 같습니다. 잘 이야기해주신대로 VARCHAR 타입으로 지정하고 voucher_type을 넣어주는 방식이 더 유연해보입니다.

2023-10-27 15:47 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/wallet/WalletController.java
> +    private final CustomerService customerService;
필요한 서비스들을 의존하는 것이므로 문제는 없어보입니다! 다만 조회할 때 쿼리에서 조인을 안 쓰신 것 같은데 안 쓰신 이유가 궁금하네요!

2023-10-27 15:50 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +    }
필드값이 동일하더라도 CRUD에 대한 구분은 해주는 것이 좋아보입니다. 구분한다고 해서 리소스가 크게 들지 않고 하나만 있는 것보다 좀 더 명확해지며 추후 변경되더라도 좀 더 빠르게 대응할 수 있습니다.

2023-10-27 15:53 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +        }
말씀해주신대로 예외 메시지는 매직 넘버의 의미가 크지 않아서 굳이 상수로 빼지 않습니다.

2023-10-27 16:03 UTC, aegis1920 commented on src/test/java/com/zerozae/voucher/service/customer/CustomerServiceTest.java
> +        verify(customerRepository, times(1)).findAll();
customerService.findAllCustomers() 메서드를 테스트해야하는데 findAllCustomers() 내부 로직에는 customerRepository.findAll()만 있고 그걸 또 mocking하고있는지라 그리 의미있는 테스트가 되진 않을 것 같습니다. customerService.findAllCustomers() 내부 로직에서 customerRepository.findAll() 이외에 다른 로직이 있고 조회 후 조회한 것들의 상태를 변경한다던가 한다면 의미가 있어질 것 같네요. assertEquals 와 같은 검증이 의미가 없다기보단.. 지금은 어쩔 수 없이 verify 정도만 의미가 있다고 보시면 될 것 같습니다.

2023-10-27 16:04 UTC, aegis1920 commented on src/main/resources/schema.sql
> +      deleted CHAR(1) DEFAULT 'N'
넵! 고생하셨습니다 👍

2023-10-27 16:12 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/wallet/WalletRepository.java
> +    }
정책에 따라 다릅니다. 예를 들어, `지갑 생성 시 기존에 삭제한 이용권이 있으면 그걸 사용한다`라는 정책이 있으면 영재님이 말씀해주신 게 맞습니다. 그런데 `지갑 생성 시 기존에 삭제한 이용권이 있으면 복구시켜서 이용권을 사용한다` 라는 정책이 맞는 진 잘 모르겠어요ㅎㅎ 지갑을 생성하면 기존에 삭제한 이용권과 상관없이 빈 지갑이 생성되어야할 것 같은 느낌이긴 합니다.

2023-10-27 16:14 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/domain/customer/Customer.java
> +    private CustomerType customerType;
타입으로 명시될 수 있는 거라면 가급적 타입으로 혹은 ENUM으로 빼시는 게 좋습니다! 👍

2023-10-27 17:02 UTC, aegis1920 requested changes
docker 설정 상세하게 적어주셔서 감사합니다 👍 테스트도 인상깊게 잘 봤습니다.

코멘튼 추가했으니 확인해주세요~

2023-10-27 17:02 UTC, aegis1920 commented on build.gradle
docker를 사용하셨다면 docker-compose를 활용해보시면 좋을 것 같습니다.
up 커맨드로 한 번에 실행할 수 있도록 만들어보시죠!

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    private static final String WALLET_PROGRAM = "walletProgram";
개행 추가해주세요! (상수와 분리)

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    private static final String WALLET_PROGRAM = "walletProgram";
이 상수들은 어떤 의미가 있나요? 그냥 String으로 넣어도 될 것 같아서 이야기해봅니다~

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    public void voucherList() {
아래 코드 제안해봅니다~
```suggestion
    public void findVoucherList() {
```

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +}
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij를 사용하고 계시다면 파일을 저장할 때마다 개행을 자동으로 넣어주도록 할 수 있습니다! (Settings → Editor → General → Ensure line feed at file end on Save)

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/customer/CustomerController.java
> +    public Response findAllCustomers() {
raw Type을 반환하기보단 타입을 확실하게 명시해주세요! (e.g. Response<List<CustomerResponse>>)

Response 파일에는 아래 처럼 수정이 필요하겠네요
```
public static <T> Response<T> success(T data) {
    return new Response<>(true, data);
}
```

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/domain/wallet/Wallet.java
> +public class Wallet {
record 키워드를 쓸 수 있는 상황으로 보이는데 한 번 사용해보세요!

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/customer/JdbcCustomerRepository.java
> +            String SAVE_FAILED_MESSAGE = "저장에 실패했습니다.";
따로 뺀 이유가 있으실까요?

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +    private static final String VOUCHER_ID = "voucherId";
상수로 빼지 않아도 충분히 의미가 전달되어 보이는데요. 상수로 빼신 이유가 있을까요?

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/exception/ErrorMessage.java
> +    public static ErrorMessage error(String message) {
명백하게 RuntimeException을 상속하고 있으므로 클래스명에 Exception임을 나타내주면 좋을 것 같습니다.

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/util/UuidConverter.java
> +public class UuidConverter {
유틸 클래스라면 다른 곳에서 인스턴스를 만들지 못하도록 private 생성자를 추가해주세요!

2023-10-27 17:02 UTC, aegis1920 commented on src/test/java/com/zerozae/voucher/repository/customer/MemoryCustomerRepositoryTest.java
> +    CustomerRepository customerRepository;
접근제한자는 테스트에서도 유효합니다! 가급적이면 적용해주세요!

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/validator/InputValidator.java
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/22311557/26cf2635-d768-4e31-acd8-7190d4f69daa)

UUID를 입력할 때 검증이 있으면 좋을 것 같습니다.

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/customer/FileCustomerRepository.java
> +import java.nio.charset.StandardCharsets;
사용되지 않는 import는 지워주세요!

2023-10-27 17:02 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/wallet/WalletRepository.java
> +public class WalletRepository {
여기만 Profile이 없는데요. 그러면 WalletRepository는 빈은 항상 올라가게 될테고 WalletRepository는 항상 실제 DB에 저장되지 않을까요?

2023-10-28 04:22 UTC, park0jae commented on src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
> +    }
따로 분리해서 생성하여 적용했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/6685b99bae0f67d7e26756db2af302dea30478e8

2023-10-28 04:29 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/wallet/WalletRepository.java
> +    }
그렇군요.. 지갑을 생성하면 기존에 삭제한 이용권과 상관없이 빈 지갑을 생성하는 방안이 더 좋을 것 같네요 ! 

﹢ 수정 했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/4a4eb2f59826b06e5323d112a65d764cc45d5ec5

2023-10-28 09:18 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    private static final String WALLET_PROGRAM = "walletProgram";
아래 코멘트로 남겨주신 상수의 의미를 생각해봤을 때 불필요하다고 생각되어 제거했습니다 !

2023-10-28 09:19 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    private static final String WALLET_PROGRAM = "walletProgram";
굳이 상수로 빼주지 않아도 될 것 같습니다 ! 

﹢ 반영 했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/f4172646869a086da4750fb090d00e9112581414

2023-10-28 09:19 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +    public void voucherList() {
네이밍이 좀 더 명확한 것 같습니다 ! customer 쪽에도 함께 반영 했습니다 !  https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/fc8ac07386f5c1f06b00cf3a9a3691eb12585362

2023-10-28 09:31 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/MenuHandler.java
> +}
이 부분은 잘 모르고 있었던 것 같습니다 ! 인텔리 제이 설정까지 알려주셔서 감사합니다.

+ 반영하다보니 이전에 수정하던 부분에서 일부 수정해주지 않은 부분이 발견되어 함께 커밋내역에 들어가게 되었습니다 ㅠ  https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/6e7cc410e034c1082dae9060fb611ba5a1b30c0c

2023-10-28 09:39 UTC, park0jae commented on src/main/java/com/zerozae/voucher/domain/wallet/Wallet.java
> +public class Wallet {
record 키워드를 알고는 있었지만 적용해본 경험은 없었는데 이번에 적용해보니 코드가 굉장히 깔끔해진 것 같습니다 ! 감사합니다. 

﹢ https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/4c87895ca659a285d73d8b77162f34abe9d0a236

2023-10-28 09:45 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/customer/JdbcCustomerRepository.java
> +            String SAVE_FAILED_MESSAGE = "저장에 실패했습니다.";
기존에 상수로 빼줬는데, 다시 문자열 자체로 넣어주는 방식으로 바꾸다가 option + enter로 자동 수정 하다가 따로 빠진 것 같습니다 😓

2023-10-28 09:51 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +    private static final String VOUCHER_ID = "voucherId";
멘토님 말씀대로 굳이 상수로 빼지 않아도 충분히 의미 전달이 가능한 것 같습니다. 여러 곳에서 사용되는 만큼 혹시나 수정가능성을 고려하여 상수로 빼준 것인데 변경 가능성도 없을 것 같습니다 ! 

﹢ https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/45d19027a30a6af5f8ab4a521130215bba26aa89

2023-10-28 10:06 UTC, park0jae commented on src/main/java/com/zerozae/voucher/exception/ErrorMessage.java
> +    public static ErrorMessage error(String message) {
+ https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/972e9ab1b38f41f2b59cbdb091e93f9703b8dcbc

2023-10-28 10:08 UTC, park0jae commented on src/main/java/com/zerozae/voucher/util/UuidConverter.java
> +public class UuidConverter {
https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/baaaa735acd01ab42db4d7a7d5b031d959490590

2023-10-28 10:18 UTC, park0jae commented on src/test/java/com/zerozae/voucher/repository/customer/MemoryCustomerRepositoryTest.java
> +    CustomerRepository customerRepository;
반영 했습니다 !https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/1b8b3b433c6acbb2c1d9d7e3746306abeaec6a87

2023-10-28 10:23 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/wallet/WalletRepository.java
> +public class WalletRepository {
WalletRepository 에 Profile 설정 반영 했습니다. https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/55537ad34f467a08c1b5703cc3800202ab8a7834

2023-10-28 12:41 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/customer/CustomerController.java
> +    public Response findAllCustomers() {
반영 했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/1a5979ef5235bce6d00ad3e555ee55038e976dca

2023-10-28 12:50 UTC, park0jae commented on src/main/java/com/zerozae/voucher/validator/InputValidator.java
반영 했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/1449c1193b585a5b17d9d4c7c95214afa7f21560

2023-10-28 12:57 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/wallet/WalletController.java
> +    private final CustomerService customerService;
기존에 1:N으로 요구사항을 정해놓고 구현했을 당시에는 바우처에 회원의 외래키를 두고 조인하는 방식으로 데이터를 가져왔었는데 이후 N:M의 관계가 더 적합하다고 판단하여 지갑이라는 테이블을 따로 생성하는 방향으로 구현하다보니 조인이 필요할까? 라는 생각을 못했던 것 같습니다.

2023-10-29 05:56 UTC, park0jae commented on build.gradle
﹢ docker-compose up 커맨드로 MySQL이 실행되도록 구성하고, 스프링 애플리케이션에 대한 yml 설정은 그대로 두었습니다. 
 docker-compose.yml 내의 스프링 애플리케이션 설정까지 한번에 할까 고민했지만 jar 파일이 아닌 인텔리제이로 만약 실행한다면 별개로 두어야 하지 않을까 생각해서 분리했습니다. 그냥 docker-compose.yml 파일 내에 스프링 애플리케이션 설정까지 한번에 하는 것이 나을까요 ? 제가 잘못 인지하고 있는 부분이 있을수도 있다고 생각하여 의견주시면 감사하겠습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/911/commits/53346f74149fc61c47aeac163ecd8f3a94873b09

2023-10-29 13:39 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/wallet/WalletController.java
> +    private final CustomerService customerService;
설명 감사합니다. 조인이 필요할 때도 있고 말씀대로 필요하지 않을 때도 있습니다. (Application에서 조인을 해결) 각자 트레이드 오프가 있는데 지금 요구사항에서는 둘 중 어느 것이든 상관없을 것 같습니다.

2023-10-29 13:43 UTC, aegis1920 commented on build.gradle
docker-compose.yml 내에 스프링 애플리케이션 설정이란 어떤 걸까요?

2023-10-29 13:44 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/exception/ErrorMessage.java
> +    public static ErrorMessage error(String message) {
ExceptionMessage의 역할이 아니라 예외의 역할을 하고 있으므로 XXXException으로 나타내야할 것 같다는 의미였습니다!

2023-10-29 14:57 UTC, aegis1920 approved these changes
2단계 구현하시느라 고생 많으셨습니다! 3단계 바로 진행해주세요~

2023-10-29 14:57 UTC, merged