[5기 김별이] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #915
Opened 2023-10-26 11:54 UTC by byulcode

## 📌 과제 설명 
- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x] 특정 고객에게 바우처를 할당할 수 있습니다.
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 
**(기본)** **바우처 관리 애플리케이션**
+ wallet : voucher와 customer 사이를 연결해주는 도메인
+ UUIDUtils : UUID와 바이트 배열 간 변환 수행

**MySQL 세팅 Docker 명령어**
```
docker run --name springBasic -e MYSQL_PORT_HOST=% -e MYSQL_ROOT_PASSWORD=root1234! -e MYSQL_DATABASE=voucher_mgmt -d -p 3306:3306 mysql
```

**테이블 정의**
```
CREATE TABLE IF NOT EXISTS customers
(
    customer_id BINARY(16) PRIMARY KEY,
    name        VARCHAR(20)           NOT NULL,
    email       VARCHAR(50) UNIQUE    NOT NULL,
    isBlackList BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS vouchers
(
    voucher_id     BINARY(16) PRIMARY KEY,
    discount_type  VARCHAR(10) NOT NULL,
    discount_value LONG        NOT NULL
);

CREATE TABLE IF NOT EXISTS wallet
(
    wallet_id   BINARY(16) PRIMARY KEY,
    customer_id BINARY(16) NOT NULL,
    voucher_id  BINARY(16) NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE,
    FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id) ON DELETE CASCADE
);
```

## ✅ PR 포인트 & 궁금한 점 
저번 피드백 반영한 부분, 궁금한 코멘트로 남겨놓겠습니다!

2023-10-26 17:32 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
> +    }
+ discountType에 따라 생성되는 voucher의 종류를 구분하는 로직 위치를 서비스 -> 엔티티로 변경했습니다. 
+ 기존에 voucherId를 default값으로 지정했었는데, 생성자 호출시 id값을 생성하도록 변경했습니다. 이 방법이 id를 직접 제어할 수 있어 객체를 더 유연하게 다룰 수 있어 이번 프로그램과 맞는 것 같습니다!

2023-10-26 17:36 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
> +    }
CsvFileUtil이 도메인 패키지를 의존하게 하지 않기 위해 파일의 각 행을 읽어온 문자열을 반환하도록 구현했습니다. 
위 로직은 반환 된 문자열을 voucher 객체로 만들기 위한 로직입니다

2023-10-26 17:41 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/wallet/service/WalletService.java
> +    }
FK를 지정하지 않고 id를 이용해 customer와 voucher을 각각 조회하도록 구현했습니다!

2023-10-26 17:45 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/wallet/service/WalletService.java
> +    }
예외 메시지를 위처럼 그냥 써도 괜찮은지, 상수화 하는 것이 좋은지 궁금합니다. 
또한, 프로그램 전반적으로 이미 존재하는 exception을 이용했는데, custom exception을 사용하는게 나은 선택일지 궁금합니다.

2023-10-26 17:47 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/io/Console.java
> +
기존에 toString() 재정의로 구현했던 객체 출력을 console에서 하도록 변경했습니다!

2023-10-26 17:49 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/util/CsvFileUtil.java
>                  String[] parts = line.split(",");
저번 피드백을 반영해 CsvFileUtil이 도메인 패키지를 의존하지 않도록 수정했습니다!

2023-10-26 17:51 UTC, byulcode commented on src/test/java/com/prgrms/springbasic/domain/wallet/service/WalletServiceTest.java
> +
join을 사용하지 않다 보니 조회 메서드가 여러 번 호출되게 됩니다. 이러한 로직이 괜찮은지 궁금합니다.

2023-10-27 01:00 UTC, KarmaPol reviewed
코드 잘 읽었습니다~

2023-10-27 01:00 UTC, KarmaPol commented on src/main/java/com/prgrms/springbasic/common/MenuHandler.java
Front Controller 역할을 하는 MenuHandler를 만들었네요👍

2023-10-27 01:00 UTC, KarmaPol commented on src/main/java/com/prgrms/springbasic/common/VoucherRunner.java
> +    }
menuHandler와 voucherRunner의 메뉴 선택 메소드로 나눈 이유가 궁금합니다 :D

2023-10-27 01:00 UTC, KarmaPol commented on src/main/java/com/prgrms/springbasic/domain/customer/repository/CustomerJdbcRepository.java
> +            logger.warn("Customer not found");
data가 없으면 warn 레벨로 로그를 찍어주는게 적절할지 고민되네요
단순 정보 조회면 더 아래 레벨로 처리해도 될것 같고, 유저 정보가 필수적인 경우엔 warn으로 찍어주는게 좋을까요?

2023-10-27 01:00 UTC, KarmaPol commented on src/main/java/com/prgrms/springbasic/domain/customer/service/CustomerService.java
> +    }
👍👍

2023-10-27 17:37 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
> +    }
> discountType에 따라 생성되는 voucher의 종류를 구분하는 로직 위치를 서비스 -> 엔티티로 변경했습니다.

엔티티로 변경하신 이유가 있을까요?

> 기존에 voucherId를 default값으로 지정했었는데, 생성자 호출시 id값을 생성하도록 변경했습니다. 이 방법이 id를 직접 제어할 수 있어 객체를 더 유연하게 다룰 수 있어 이번 프로그램과 맞는 것 같습니다!

ID 같은 경우는 오히려 직접 제어하는 게 좋지 않습니다. ID를 생성하는 전략이 바뀌면 안되기 때문에 가급적 숨겨야 합니다.

이와 별개로 DiscountType.find(discountType)는 변수로 빼도 되겠습니다.

2023-10-27 17:39 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
> +    }
위에 import 구문(`import com.prgrms.springbasic.domain.voucher.entity.Voucher;`)을 보시면 아시겠지만 이미 도메인 패키지에 의존하고 있는 상황입니다. 해당 import 구문이 없어야하며 그러기 위해선 반환값 자체에 Voucher가 없어야 합니다.

2023-10-27 17:44 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/wallet/service/WalletService.java
> +    }
예외 메시지를 상수화하면 어떤 점이 좋을까요? 따로 활용하는 곳도 없어서 개인적으로는 그럴 필요가 없다고 생각합니다. CustomException이냐 이미 존재하는 Exception이냐는 상황에 따라 다릅니다. 이미 존재하는 예외를 사용하려면 잘 알려진 예외를 사용하면 좋을 것 같은데 이쪽 [코드](https://github.com/JetBrains/kotlin/blob/1.2.30/libraries/stdlib/jvm/runtime/kotlin/TypeAliases.kt)를 참고하면 좋을 것 같습니다.

2023-10-27 17:45 UTC, aegis1920 commented on src/test/java/com/prgrms/springbasic/domain/wallet/service/WalletServiceTest.java
> +
join을 사용하지 않은 이유가 있을까요?

2023-10-27 18:27 UTC, aegis1920 requested changes
몇 가지 코멘트 드렸습니다! 확인해주세요~

2023-10-27 18:27 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/common/CommandType.java
> +import java.util.EnumSet;
👍

2023-10-27 18:27 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/repository/CustomerJdbcRepository.java
> +    private static final String INSERT_QUERY = "INSERT INTO customers(customer_id, name, email) VALUES(UUID_TO_BIN(?), ?, ?)";
여기마나 QUERY라는 말이 들어가있네요? 일관성을 맞춰주시면 좋을 것 같습니다.

2023-10-27 18:27 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/service/CustomerService.java
> +        Optional<Customer> existingCustomer = customerRepository.findCustomerByEmail(email);
여기서 바로 orElseThrow()를 하지 않으신 이유가 있을까요?

2023-10-27 18:27 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
> +        System.out.println("dho");
??

2023-10-27 18:27 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/util/UUIDUtils.java
> +public class UUIDUtils {
유틸 클래스라면 다른 곳에서 인스턴스를 생성하지 않도록 private 생성자를 추가해주세요~

2023-10-27 18:27 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/util/UUIDUtils.java
> +        return new java.util.UUID(byteBuffer.getLong(), byteBuffer.getLong());
패키지명은 지워도 될 것 같습니다!

2023-10-27 18:27 UTC, aegis1920 commented on build.gradle
docker를 사용해보셨다면 docker-compose도 사용해보세요!

2023-10-27 18:27 UTC, aegis1920 commented on src/main/resources/schema.sql
> +    isBlackList BOOLEAN DEFAULT FALSE NOT NULL
스키마 컬럼 컨벤션을 맞춰주세요!

2023-10-27 18:27 UTC, aegis1920 commented on src/main/resources/application.yml
> +  datasource:
sql.init.mode를 활성화시켜줘야 처음 실행했을 때 schema.sql이 실행됩니다. 해당 설정이 필요해보여요

2023-10-27 18:27 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerController.java
Customer는 조회 기능이 없나요? 직접 커맨드로만 테스트가 불가하네요ㅠ

2023-10-27 18:27 UTC, aegis1920 commented on src/main/resources/schema.sql
> +    customer_id BINARY(16) PRIMARY KEY,
UUID인데 BINARY로 저장하는 이유가 있나요?

2023-10-29 12:35 UTC, byulcode commented on src/test/java/com/prgrms/springbasic/domain/wallet/service/WalletServiceTest.java
> +
입력받은 id에 해당하는 customer, voucher가 존재하는지 여부를 확인하려고 했던 것 같은데, 다시 생각해보니 join을 사용해도 충분히 가능할 것 같습니다. 수정하겠습니다!

2023-10-29 12:40 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
> +        System.out.println("dho");
앗 삭제하는걸 깜박했습니다😓 수정하겠습니다!

2023-10-29 13:37 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerController.java
추가하도록 하겠습니다!

2023-10-29 15:06 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerController.java
commit [d41a0cc](https://github.com/prgrms-be-devcourse/springboot-basic/pull/915/commits/d41a0ccb159e0fa80311b4bff0b4231a39711e6d)

2023-10-29 15:07 UTC, aegis1920 approved these changes
고생 많으셨습니다~ 3단계에서 함께 반영해주세요!

2023-10-29 15:07 UTC, merged