[5기 - 김경훈] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #920
Opened 2023-10-26 15:28 UTC by KarmaPol

## 📌 과제 설명 
**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.
## 👩‍💻 요구 사항과 구현 내용 
- ConsoleView : 콘솔로 출력하는 view 클래스를 도메인 별로 Customer, Voucher, WalletConsoleView로 나눠서 구현했습니다.
- CommonController : 프로그램의 메인 메뉴 화면, 종료 등 공통 기능을 담당하고, 메뉴 커맨드에 따라 각 콘트롤러를 호출합니다.
- Wallet : Customer이 Voucher을 소유하는 관계를 Wallet 도메인으로 구현하였고, 다대다 관계를 고려하였습니다.
- Customer/Voucher/WalletController : 각 도메인 별로 뷰와 서비스를 호출합니다. 기본적인 추가, 삭제, 조회, 변경 기능을 제공합니다.
- Customer/Voucher/WalletService : 각 도메인 별 서비스를 제공합니다. 기본적인 예외처리를 적용하였습니다.
- Customer/Voucher/WalletJdbcRepository : 각 도메인 별 JDBC template 코드를 작성하였습니다.
- AppConfig : DataSource Bean 설정을 해주었습니다. 로컬 MySql 서버와 테스트가 용이하도록 h2 DB mysql mode를 사용하였습니다.
- KeyGenerator : 전역적으로 Long Id 값을 관리할 수 있습니다.

테스트 코드는 추가 예정입니다.
## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- JdbcTemplate을 쓸 때, 엔티티 생성 후 직접 쿼리를 조회해서 id값을 가져와야할지 자바 코드 상에서 id를 관리하는게 좋은지 고민이 됐습니다.
- JdbcTemplate에서 발생하는 예외를 경우를 나눠 각각 catch문으로 처리해야할지 궁금합니다.
- Dto <-> Entity 변환 코드를 mapper class로 따로 빼거나 Dto 내부에, 혹은 그대로 코드로 쓰는 것을 봤는데 일반적으로는 어디에 두는 것이 적절할까요?
- Wallet 엔티티의 경우, Voucher, Customer에 의존적이기때문에 외래키를 참조하여 Delete on Cascade 옵션으로 Voucher가 삭제되면 Wallet도 삭제되도록 하였습니다. 하지만 외래키 자체가 무겁기 때문에 설정하지 않아도 좋은 것 같은데, 이런 경우에 외래키 옵션을 어떻게 하는게 적절한지 멘토님들의 의견을 듣고 싶습니다.

2023-10-26 15:28 UTC, KarmaPol commented on src/main/resources/data.sql
> +    foreign key(customer_id) references customers(id) on delete cascade
Wallet 엔티티의 경우, Voucher, Customer에 의존적이기때문에 외래키를 참조하여 Delete on Cascade 옵션으로 Voucher가 삭제되더라도 Wallet도 삭제되도록 하였습니다. 
하지만 외래키 자체가 무겁기 때문에 설정하지 않아도 좋은 것 같은데, 이런 경우에 외래키 옵션을 어떻게 하는게 적절한지 멘토님들의 의견을 듣고 싶습니다.

2023-10-27 04:03 UTC, KarmaPol commented on src/main/java/com/pgms/part1/domain/wallet/controller/WalletController.java
> +            walletConsoleView.listVoucher(voucherResponseDtos);
굳이 여러번 서비스를 호출하는 것보다 SQL에서 join문을 사용하는게 좋은 것 같습니다
이 부분은 join문을 사용해 메소드 하나로 처리하도록 고치겠습니다

2023-10-27 04:59 UTC, byulcode reviewed
코드 잘 봤습니다~~많이 배워갑니다!

2023-10-27 04:59 UTC, byulcode commented on src/main/java/com/pgms/part1/domain/customer/entity/CustomerBuilder.java
> +}
빌더 패턴을 직접 구현한 것을 처음봐서 신기하네요👍
경훈님이 생각하시는 빌더 패턴의 장점이 궁금합니다!

2023-10-27 04:59 UTC, byulcode commented on src/main/java/com/pgms/part1/domain/customer/service/CustomerService.java
> +                .collect(Collectors.toList());
customers에 대한 수정 로직이 따로 없다면 jdk16 부터 도입된 Stream.toList() 메서드를 사용하는 것도 좋을 것 같습니다😊

2023-10-27 04:59 UTC, byulcode commented on src/main/java/com/pgms/part1/domain/voucher/repository/VoucherJdbcRepository.java
> +    }
discount_type에 따라 생성될 바우처를 구분하는 로직을 도메인에 넣는 방법은 어떨까요? 
물론 도메인에 비즈니스 로직이 들어가도 되는지에 대해서는 저도 고민스럽습니다🥹

2023-10-27 04:59 UTC, byulcode commented on src/main/java/com/pgms/part1/util/keygen/KeyGenerator.java
> +}
시퀀셜 아이디를 쓸 때 이런 방법이 있군요👍👍

2023-10-27 04:59 UTC, byulcode commented on src/main/java/com/pgms/part1/view/CommonConsoleView.java
> +}
개행이 필요할 때 System.lineSeparator()을 사용하셔도 좋을 것 같습니다!

2023-10-27 04:59 UTC, byulcode commented on src/main/java/com/pgms/part1/view/CustomerConsoleView.java
> +        );
가독성을 위해 String formatted()등을 사용하는건 어떨까요?

2023-10-27 04:59 UTC, byulcode commented on src/main/java/com/pgms/part1/domain/wallet/service/WalletService.java
> +        return walletByCustomerId;
addWallet 메서드는 dto를 인자로 받는데, listWalletsByCustomer에서는 wallet을 그대로 반환하는 이유가 궁금합니다!

2023-10-27 17:07 UTC, aegis1920 commented on src/main/resources/data.sql
> +    foreign key(customer_id) references customers(id) on delete cascade
말씀드렸다시피 외래키는 성능 상의 이유로 사용하지 않는데요. 외래키에 옵션까지 달게 되면 그 자체로 DB에 너무 의존적이게 됩니다. delete cascade의 경우는 application에서도 해결할 수 있습니다. 외래키 옵션은 가급적 작성하지 않는 게 좋습니다.

2023-10-27 17:13 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/voucher/repository/VoucherJdbcRepository.java
> +    }
도메인에 discount_type 인지 묻는 정도는 비즈니스 로직이라고 보기 애매할 것 같습니다. `VoucherDiscountType.isFixedAmount(resultSet.getString("discount_type"))` 정도로 작성해보시면 어떨까 싶네요?

2023-10-27 17:16 UTC, aegis1920 commented on src/main/java/com/pgms/part1/util/keygen/KeyGenerator.java
> +}
단순히 static으로 올려져있으면 여러 스레드에서 접근할 수 있어서 멀티스레드 환경에서 쓰기 어렵습니다. AtomicInteger를 사용하는 게 나아보입니다.

2023-10-27 17:21 UTC, aegis1920 requested changes
실행이 안되는 부분이 있어서 수정 후 다시 요청주시면 좋을 것 같습니다. 그리고 이번 미션이 테스트인 만큼 테스트도 작성해주시면 감사하겠습니다. 🙇 

> JdbcTemplate을 쓸 때, 엔티티 생성 후 직접 쿼리를 조회해서 id값을 가져와야할지 자바 코드 상에서 id를 관리하는게 좋은지 고민이 됐습니다.

JdbcTemplate을 사용하신다면 [GeneratedKeyHolder](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/support/GeneratedKeyHolder.html)를 한 번 사용해보세요. auto increment되는 id를 만들 수 있습니다.



> JdbcTemplate에서 발생하는 예외를 경우를 나눠 각각 catch문으로 처리해야할지 궁금합니다.

넵 각각 catch 문으로 처리해주셔야 합니다.

> Dto <-> Entity 변환 코드를 mapper class로 따로 빼거나 Dto 내부에, 혹은 그대로 코드로 쓰는 것을 봤는데 일반적으로는 어디에 두는 것이 적절할까요?

Dto 내부에 쓰기도 하고 Mapper 클래스로 따로 빼기도 합니다. Entity 그대로 쓰는 것은 캡슐화도 깨지고 가장 안쪽에 있어야할 레이어가 바깥으로 나오는 것이기 때문에 좋지 않습니다. 지금 상황에서는 DTO 내부에서 변환해도 충분하다고 생각합니다.

> Wallet 엔티티의 경우, Voucher, Customer에 의존적이기때문에 외래키를 참조하여 Delete on Cascade 옵션으로 Voucher가 삭제되면 Wallet도 삭제되도록 하였습니다. 하지만 외래키 자체가 무겁기 때문에 설정하지 않아도 좋은 것 같은데, 이런 경우에 외래키 옵션을 어떻게 하는게 적절한지 멘토님들의 의견을 듣고 싶습니다.

코멘트로 남겨주셔서 그쪽에 답변달았습니다.

2023-10-27 17:21 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/customer/controller/CustomerController.java
> +        customerService.isAvailableCustomer(id);
이 코드로 인해서 실행이 안되는데 확인 부탁드립니다.

2023-10-28 17:06 UTC, KarmaPol reviewed
피드백 반영하였습니다!

2023-10-28 17:06 UTC, KarmaPol commented on src/main/java/com/pgms/part1/domain/voucher/repository/VoucherJdbcRepository.java
> +    }
타입 추정이 반복되어서 도메인 내부에 넣도록 수정했습니다

2023-10-28 17:06 UTC, KarmaPol commented on src/main/java/com/pgms/part1/domain/customer/entity/CustomerBuilder.java
> +}
빌더 패턴의 장점은 가독성, 유연함 등이 있지만 
정보 입력 시 선택 사항이 많은 경우에 유용하다고 생각합니다

2023-10-28 17:06 UTC, KarmaPol commented on src/main/java/com/pgms/part1/domain/wallet/service/WalletService.java
> +        return walletByCustomerId;
wallet은 관계를 나타내는 엔티티라서 해당 메소드는 다른 서비스에서 특정 사용자의 바우처를 추적할 수 있는 기능을 합니다
따라서 그대로 엔티티로 넘긴 뒤 다른 서비스에서 dto로 변환하도록 했습니다
이 부분은 join문으로 바꾸면 수정될 예정입니다!

2023-10-28 17:06 UTC, KarmaPol commented on src/main/java/com/pgms/part1/util/keygen/KeyGenerator.java
> +}
AtomicInteger로 멀티 쓰레드 동시성 문제를 해결할 수 있네요 감사합니다!

2023-10-28 17:06 UTC, KarmaPol commented on src/main/java/com/pgms/part1/view/CustomerConsoleView.java
> +        );
formatted 식을 쓰고 메소드로 추출하면 더 깔끔할 것 같네요!

2023-10-28 17:06 UTC, KarmaPol commented on src/main/resources/data.sql
> +    foreign key(customer_id) references customers(id) on delete cascade
무겁고 DB에 의존적이게 되는군요 감사합니다!

2023-10-28 17:06 UTC, KarmaPol commented on src/main/java/com/pgms/part1/domain/customer/controller/CustomerController.java
> +        customerService.isAvailableCustomer(id);
네 확인해서 반영했습니다

2023-10-28 17:08 UTC, KarmaPol commented
테스트 코드는 추가해서 반영하겠습니다!

2023-10-29 08:00 UTC, KarmaPol commented
피드백을 반영하고, 일부 테스트에 대해 코드를 추가하였습니다
이때 든 고민은 validation 처리가 controller에 있다보니 service 코드의 unit test는 validation을 적용하기 까다롭다는 점이었습니다
이런 경우, controller의 test code를 짜 validation을 검증하고 service에서는 따로 validation 검증 test를 짤 필요는 없을까요?

2023-10-29 13:31 UTC, aegis1920 requested changes
간단하게 코멘트 좀 더 남겼습니다! 확인해주세요~

2023-10-29 13:31 UTC, aegis1920 commented on src/main/java/com/pgms/part1/config/AppConfig.java
> +        return DataSourceBuilder.create()
docker-compose로 쉽게 mysql을 띄워보시는 걸 추천드립니다!

2023-10-29 13:31 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/customer/repository/CustomerJdbcRepository.java
> +@Primary
👍

2023-10-29 13:31 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/customer/repository/CustomerJdbcRepository.java
> +    public List<Customer> listCustomersByWallets(List<Wallet> wallets) {
함수명은 동사로 시작하는 것이 관례입니다!

2023-10-29 13:31 UTC, aegis1920 commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> 이때 든 고민은 validation 처리가 controller에 있다보니 service 코드의 unit test는 validation을 적용하기 까다롭다는 점이었습니다. 이런 경우, controller의 test code를 짜 validation을 검증하고 service에서는 따로 validation 검증 test를 짤 필요는 없을까요?

유효성 검증 처리가 Controller에 있는데 Service 코드의 단위테스트에서 유효성 검증을 적용하기 까다롭다는 게 어떤 뜻인지 잘 이해하지 못했습니다. 조금 더 구체적으로 말씀해주실 수 있을까요? 이와 별개로 검증이 있을 때 컨트롤러에서 해야하는 검증인지, 도메인에서 해야하는 검증인지 생각해볼 필요가 있다는 점 참고 부탁드립니다.

2023-10-29 13:31 UTC, aegis1920 commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +@DirtiesContext(classMode = AFTER_EACH_TEST_METHOD)
테스트 데이터를 초기화하기 위한 방법은 어떤 방법들이 있을까요? @DirtiesContext를 선택하신 이유가 있을까요?

2023-10-29 13:31 UTC, aegis1920 commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +@ActiveProfiles("test")
이 부분은 왜 있는 건가요?

2023-10-29 13:31 UTC, aegis1920 commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +class CustomerServiceTest {
예외 케이스에 대해서 테스트가 추가되었으면 좋겠군요!

2023-10-29 15:08 UTC, aegis1920 approved these changes
고생 많으셨습니다! 2단계 코멘트는 3단계에서 함께 반영해주세요!

2023-10-29 15:08 UTC, merged

2023-10-29 17:25 UTC, KarmaPol reviewed
피드백은 3차 과제에 반영하겠습니다~

2023-10-29 17:25 UTC, KarmaPol commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
도메인에 대한 검증인데 만약 컨트롤러 테스트에서 이미 검증을 했다면 서비스 테스트 코드에서도 할 필요는 없을까요?

2023-10-29 17:25 UTC, KarmaPol commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +@ActiveProfiles("test")
CommandLineRunner가 테스트 코드에서도 돌아가는 걸 방지하고자
profile("!test")로 테스트 시 무시되게 하였습니다

2023-10-29 17:25 UTC, KarmaPol commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +@DirtiesContext(classMode = AFTER_EACH_TEST_METHOD)
- Mock객체로 repo를 서비스에 주입하고, @Beforeeach로 매번 repo를 초기화해주는 방식을 많이 사용할 것 같습니다
- jdbc template의 경우, 모든 데이터를 delete해주는 메소드를 만들어서 @Beforeeach로 호출할 수 있을 것 같습니다
저는 실제 객체를 사용하고자 하였고, 매 메소드 마다 컨텍스트가 새로 생기길 의도해서 사용하였습니다

2023-10-29 17:25 UTC, KarmaPol commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +class CustomerServiceTest {
네 예외 케이스에 대해서도 추가하겠습니다!

2023-10-29 17:25 UTC, KarmaPol commented on src/main/java/com/pgms/part1/config/AppConfig.java
> +        return DataSourceBuilder.create()
도커 컴포즈로 미리 yml을 작성해두면 더 편하게 구동할 수 있을 것 같습니다!

2023-10-30 16:12 UTC, aegis1920 commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
도메인에 대한 검증이라면 도메인 테스트 코드가 있어야합니다. 도메인에 대한 검증을 컨트롤러 테스트에서 이뤄지는 게 부적절해보입니다! 만약 도메인 테스트 코드가 있어서 이미 검증이 되었다면 서비스 테스트 코드에서 굳이 도메인 검증을 위한 테스트가 필요하진 않습니다. 서비스 테스트 코드에서는 비즈니스 로직에 대한 테스트를 위주로 해주시면 좋을 것 같습니다.

2023-10-30 16:12 UTC, aegis1920 commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +@DirtiesContext(classMode = AFTER_EACH_TEST_METHOD)
매 메소드마다 새로운 컨텍스트가 생긴다는 건 그만큼 느려진다는 뜻도 됩니다. 매 테스트 시 새로운 컨텍스트를 띄울 필요가 있을지도 고민해봐주세요! 아래 글도 좋으니 한 번 읽어보시면 좋을 것 같습니다!

- https://tecoble.techcourse.co.kr/post/2020-09-15-test-isolation/
- https://tecoble.techcourse.co.kr/post/2022-10-15-test-code-optimization/

2023-10-30 16:12 UTC, aegis1920 commented on src/test/java/com/pgms/part1/domain/customer/service/CustomerServiceTest.java
> +@ActiveProfiles("test")
profile을 통해 분리하기보단 특정 property를 하나 만들어서 실행되지 않도록 하는 게 좋아보이긴 합니다. 3단계에서는 어차피 제외될 거 같긴한데 `@conditionalonproperty`라는 걸 사용해서 분기처리해줄 수도 있으니 추후 한 번 확인해봐주세요!