[5기 - 이한나] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #923
Opened 2023-10-27 05:17 UTC by annahxxl

## 📌 과제 설명 
## SpringBoot Part2 Weekly Mission

**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요. (+ AssertJ도 한번 맛보세요.)
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- 특정 고객에게 바우처를 할당할 수 있습니다.
- 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 

컨트롤러는 아직 구현하지 못했습니다.. 🥲

### 앱 실행 전
```
docker run --name db -e MYSQL_ROOT_PASSWORD=rootpassword -e MYSQL_DATABASE=app -p 3306:3306 -d mysql:latest
```
### 테스트 실행 전
```
# 컨테이너 접속
mysql -u root -p

# 비밀번호 입력
rootpassword

# 테스트용 데이터베이스 생성
create database test;
```

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-10-27 07:43 UTC, park0jae reviewed
코드 잘 봤습니다 ! 여러모로 많이 배우고 갑니다 😄

2023-10-27 07:43 UTC, park0jae commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
>          if (amount < 0 || amount > 100) {
매직 넘버는 상수로 빼주는게 어떨까요 ?? 🙂

2023-10-27 07:43 UTC, park0jae commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +        return "Voucher{id=" + id + ", amount=" + amount + ", type=" + type + '}';
가독성을 고려해서 String.format() 이나 jdk17의 """ 문법을 사용해보는건 어떨까요 ? 🙂

2023-10-27 07:43 UTC, park0jae commented on src/main/java/com/programmers/vouchermanagement/service/WalletService.java
> +    }
서비스에서 도메인을 반환하게 된다면 프레젠테이션 계층까지 도메인이 노출된다고 생각하는데 한나님 생각은 어떠신가요 ? 🙂

2023-10-27 07:43 UTC, park0jae commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/JdbcTemplateVoucherRepository.java
> +                .addValue("amount", voucher.getAmount());
한 클래스 파일 내에서 여러 번 사용되는 문자열("id", "amount") 같은 경우에는 상수로 빼주는거에 대해 어떻게 생각하시나요 ? 🙂 이 부분은 저도 과제하면서 고민이 되었어서 한나님 생각도 궁금하네요 !

 ﹢ 이 부분은 저도 멘토님께 피드백을 받고 고민을 해봤는데 상수화하지 않아도 의미전달이 충분하다면 굳이 상수화를 하지 않아도 될 것 같네요 !

2023-10-27 07:43 UTC, park0jae commented on src/main/java/com/programmers/vouchermanagement/service/WalletService.java
> +        walletRepository.save(new Wallet(customer, voucher));
wallet을 생성하고, 이후에 같은 customer와 같은 voucher를 통해 다시 wallet을 생성했을 때 기존에 존재하는 wallet에 대한 중복 검증 로직이 추가되면 좋을 것 같아요 ! 🙂

2023-10-27 07:43 UTC, park0jae commented on src/main/java/com/programmers/vouchermanagement/service/WalletService.java
> +
저는 조회가 이루어지는 부분에서는 읽기전용 트랜잭션이 걸리면 성능적인 부분이 더 향상되지 않을까? 라고 생각해서 옵션을 부여했는데, 한나님께서는 서비스 레이어 전체에 기본 값으로 @Transactional 어노테이션을 적용하신 이유가 궁금합니다 ! 🙂

2023-10-27 07:43 UTC, park0jae commented on src/main/java/com/programmers/vouchermanagement/dto/customer/GetCustomersRequestDto.java
> +    private Boolean blacklisted;
해당 DTO 객체를 살펴보면,  기본 생성자를 만들어주는 @NoArgsConstructor와 @AllArgsConstructor 어노테이션이 사용되었는데 둘 다 붙여준 이유가 궁금해요 !

2023-10-27 10:06 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/repository/wallet/JdbcTemplateWalletRepository.java
> +            Voucher voucher = voucherRepository.findById(voucherId).orElseThrow(() -> new InternalError("Not found voucher"));
해당 로직을 고객, 바우처 레포를 import 하여 find 메서드를 통해 찾아오도록 하였습니다. 근데 그냥 private 으로 find하는 메서드를 따로 추출하는게 나을지, 아니면 다른 더 좋을 방법이 있을지 궁금합니다!

2023-10-27 10:13 UTC, annahxxl commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
> +    @MockBean
@MockBean을 사용했는데, 해당 어노테이션은 ```스프링 애플리케이션 컨텍스트 내의 빈을 목 객체로 자동 교체하는 역할```을 한다고 합니다. 그래서 테스트 시 앱이 여러번 실행되는 현상이 있었네요! 그래서 Mockito.mock은 순수 mock 객체를 만들어준다고 하여 수정하려고 합니다. 단위 테스트 목적에는 순수 mock객체를 생성해주는게 더 적합하다는 생각이 들어서요!

2023-10-27 13:40 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/repository/wallet/JdbcTemplateWalletRepository.java
> +            Voucher voucher = voucherRepository.findById(voucherId).orElseThrow(() -> new InternalError("Not found voucher"));
근데 지갑 레포에서 해당 로직을 수행하는게 적절한지 의문이 들기도 합니다,, Wallet 필드 정의로는 Customer, Voucher 객체가 포함되어 있기는 한데.. 고민이 되네요🤔

2023-10-28 15:03 UTC, aegis1920 requested changes
Wallet 쪽 코드가 많이 작성된 것 같은데요. 심화로 들어가기 전에 기본 구현부터 먼저 살펴봐주세요. voucher CRUD 기능이 없는데 작성해주시면 좋을 것 같고 테스트 또한 성공 케이스보다는 엣지, 예외 케이스 위주로 작성해주시면 좋을 것 같습니다. 더불어 사용자가 입력하고 출력 한 뒤에 메뉴를 출력하는 게 없는데 있도록 출력하면 좋겠습니다. (그래야 사용자 입장에서 명령어 파악이 쉬울 것 같아요)

구현된 후 다시 코드리뷰 남기거나 3단계에서 코드리뷰를 한꺼번에 받거나 온라인으로 따로 코드리뷰 드리거나 하겠습니다.

2023-10-28 15:03 UTC, aegis1920 commented on build.gradle
docker compose를 사용해서 up 커맨트를 통해 쉽게 띄워보세요. 프로젝트에 docker-compose 파일을 넣어주시면 좋을 것 같습니다

2023-10-28 15:03 UTC, aegis1920 commented on src/main/resources/schema.sql
> +    FOREIGN KEY (customer_id) REFERENCES customers (id),
외래키가 있는 게 더 좋다고 느끼셨을까요?ㅎㅎ 어떤 점에서 더 좋게 느꼈는지 궁금합니다!

2023-10-28 15:03 UTC, aegis1920 commented on src/test/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucherTest.java
테스트용 데이터베이스를 직접 설정하지 않는 이상 테스트가 터져버리는데요. 바로 docker로 띄워서 DB를 실행할 수 있도록 [TestContainer](https://java.testcontainers.org/)를 활용해보세요!

2023-10-28 15:03 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/VoucherShellController.java
> +        CreateVoucherRequestDto request = CreateVoucherRequestDto.builder()
create하고 나서 list를 뽑을 때 개행이 하나 남는 거 같아요. 바로 `shell >` 이 뜨도록 해주셔야할 것 같습니다.

![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/22311557/39e723f5-adef-47a8-a9d2-a457e80463f3)

2023-10-28 15:03 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +    private String email;
- email로 바꾼 이유가 있을까요?
- email에 대한 검증은 필요 없을까요?

2023-10-28 15:03 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
> +    public static PercentDiscountVoucher fixture() {
테스트를 위한 코드가 프로덕션에 있어도 될까요?

2023-10-28 15:03 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
> +            default -> new FixedAmountVoucher(id, amount);
case 별로 명확하게 구분지어주는 것이 좋습니다. fixed가 디폴트라고 한다면 명시적으로 모두 적어준뒤에 default를 다시 적어주세요
```
return switch (type) {
    case PERCENT_DISCOUNT -> new PercentDiscountVoucher(id, amount);
    case FIXED_AMOUNT -> new FixedAmountVoucher(id, amount);
    default -> new FixedAmountVoucher(id, amount);
};
```

2023-10-28 15:03 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/dto/wallet/GetWalletsRequestDto.java
> +public class GetWalletsRequestDto {
Request 분리 👍

2023-10-28 15:03 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/customer/FileCustomerRepository.java
> +//@Repository
이전 버전으로 사용되지 않아서 주석처리하신 거라면 `@Deprecated`를 쓰셔도 좋을 것 같습니다.

2023-10-28 15:09 UTC, aegis1920 commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
> +    @MockBean
넵 잘 설명해주셨네요! CustomerServiceTest에서 CustomerService을 Mocking하고 있는 게 아니라서 `@MockBean`을 사용할 이유가 없어보입니다!

2023-10-29 15:08 UTC, aegis1920 approved these changes
고생 많으셨습니다! 2단계 코멘트는 3단계에서 함께 반영해주세요!

2023-10-29 15:08 UTC, merged