[5기 - 이세희] SpringBoot Part2 Weekly Mission 제출합니다.(작성중입니다.)
prgrms-be-devcourse/springboot-basic pull request #925
Opened 2023-10-27 08:48 UTC by Sehee-Lee-01

## 📌 과제 설명 
<img width="503" alt="스크린샷 2023-10-27 173200" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/85275893/c584921c-5a0c-41b7-af67-29f4ef01e374">

## 👩‍💻 요구 사항과 구현 내용 
### **(기본)** **바우처 관리 애플리케이션**

- 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - [ ] 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - [ ] 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - [ ] Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - [ ] customers 테이블 정의 및 추가
    - [ ] CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - [ ] 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - [ ] 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - [ ] 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

### **(심화)** **바우처 지갑을 만들어보세요.**

- [ ] 특정 고객에게 바우처를 할당할 수 있습니다.
- [ ] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [ ] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [ ] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## ✅ PR 포인트 & 궁금한 점 
-

2023-10-28 07:11 UTC, ksy90101 requested changes
제가 실행해볼수 있게 도커파일과 실행방법을 작성해주시면 좋을거 같습니다.

2023-10-29 08:11 UTC, ksy90101 requested changes
말씀하신대로 실행해봣자 실행이 안됩니다.
실행시켜주세요.
DB sql쪽의 문제가 있어보여용

2023-10-29 08:56 UTC, Sehee-Lee-01 commented
> 말씀하신대로 실행해봣자 실행이 안됩니다. 실행시켜주세요. DB sql쪽의 문제가 있어보여용
git pull 한 번 해주시고 다시 시도해주시면 감사하겠습니다!!!

2023-11-05 09:12 UTC, ksy90101 approved these changes
일단 늦어서 죄송합니다.
전반적으로 2단계의 필수인 테스트 코드가 부족하네요.
테스트 코드를 어떻게 하면 추가할수 있을지 고민해보세요.

<img width="938" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/53366407/9d9c48f5-42b1-42c0-b063-c6c65bdb3815">
이런 기능을 사용해서 커버리지를 보고 채워나가도 좋을거 같습니다 👍

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/configuration/AppConfig.java
> +                .password("20231028")
이렇게 비밀번호가 노출되어도 될까요?
코드상에서 이렇게 관리하기 보단 applicartion.yml에서 관리하는 방식으로 https://rutgo-letsgo.tistory.com/93 이글을 읽어보고 적용해보면 어떨까요?

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/constant/Constant.java
>  public class Constant {
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/4_%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%ED%99%94%EB%A5%BC_%EB%A7%89%EC%9C%BC%EB%A0%A4%EA%B1%B0%EB%93%A0_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

이글을 한번 참고해보시면 어떨까요?

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/VoucherJDBCRepository.java
> +            throw new RuntimeException(NOT_INSERTED);
RunTimeException이 아니라 더 의미있는 예외를 사용해보면 어떨까요?

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/VoucherJDBCRepository.java
> +    public void save(Voucher voucher) {
일반적으로 save라는 단어는 id가 없을때 insert, id가 존재하면 update를 하는 용도로 사용합니다.
따라서 이름을 변경하거나, 위와 같은 로직으로 적용해보면 어떨까요?

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepositoryTest.java
> +        customerJDBCRepository.save(new Customer(UUID.randomUUID(), "고객4"));
assert문이 없다는건 검증이 안된다는 의미에요.
save와 같은 경우에 저장하고, 실제 그 저장한게 DB에 있는지 assert로 검증하면 되지 않을까요?

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepositoryTest.java
> +        assertThat(customers.stream().filter(customer -> !customer.isBlack()).toList()).isEmpty();
여기서 비지니스 로직이 있는거 아닌가요?

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepositoryTest.java
> +        assertThat(customers.stream().filter(customer -> !customer.isBlack()).toList()).isEmpty();
단 블랙 고객이 없는 경우 빈 리스트라는데 여기서 그게 어디에 검증되는건지..?

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepositoryTest.java
> +        assertThat(customers.isEmpty()).isFalse();
```suggestion
        assertThat(customers).isEmpty();
```
이런식으로도 사용 가능합니다

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/constant/Message.java
> +    public static final String IO_EXCEPTION = "Error raised while reading file!";
컨벤션을 맞춰주세요.

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/Validator.java
>          }
다른 vouckerType이 있을 경우가 있을수도 있을텐데, 그런 경우 에러를 반환함으로써 안전하게 하면 어떨까요?

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/Validator.java
> +    public static void validateDiscountValue(VoucherType voucherType, String discountValueStr) {
공통 validator인거 같은데 이런 경우엔 추상화를 제대로 해야 할거 같습니다.

즉, 현재 해당 부분은 voucher에 의존적인데, 이걸 다른 모델에서 재사용을 할수 있을꺼라고 혹시 생각하시나요?

차라리 이런 경우엔 모델에 넣는게 더 좋을거 같아요..
 
추상화라는건 모든 모델에서 공통으로 쓰일 로직을 이렇게 util로 빼두는것을 의미한다고 생각합니다.

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/VoucherFileRepository.java
>      private Voucher objectToVoucher(Map voucherObject) {
제네릭을 통해 타입을 고정하시면 좋을거 같습니다.

2023-11-05 09:12 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepository.java
> +import static com.programmers.vouchermanagement.customer.repository.CustomerQuery.FIND_ALL_BLACK_CUSTOMER;
(그냥 질문) 굳이 쿼리를 다른 파일로 넣은 이유가 혹시 있나요?
한눈에 보기가 어려울거 같은데... 이 파일만 보고 어떤 쿼리가 날라가고, 이게 한눈에 보이는게 훨씬 좋을거 같아서요.

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/TestConfig.java
> +                .password("20231028")
여기도 비밀번호와 이메일이 너무 노출되는거 같습니다.

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/TestConfig.java
> +}
NOF를 지켜주세요.

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepositoryTest.java
> +@ContextConfiguration(classes = TestConfig.class, loader = AnnotationConfigContextLoader.class)
@JdbcTest를 사용해보면 어떨까요?

2023-11-05 09:12 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepositoryTest.java
> +    }
이 로직은 중복인거 같은데 한번 중복로직을 제거하면 어덜까요?
(질문) FOREIGN_KEY_CHECKS 이건 왜 써야 하나요?

2023-11-05 09:12 UTC, merged

2023-11-05 09:14 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/configuration/AppConfig.java
> +                .password("20231028")
넵! 저번에 급하게 제출하느라 정리를 제대로 못했던 것 같습니다ㅠㅠㅠ 
참고해서 수정하겠습니다!

2023-11-05 11:18 UTC, Sehee-Lee-01 commented on src/test/java/com/programmers/vouchermanagement/TestConfig.java
> +                .password("20231028")
https://github.com/prgrms-be-devcourse/springboot-basic/pull/925#discussion_r1381488753
위의 피드백과 함께 수정하겠습니다!

2023-11-05 11:23 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/constant/Constant.java
>  public class Constant {
넵! 반영하겠습니다!

2023-11-05 11:28 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepository.java
> +import static com.programmers.vouchermanagement.customer.repository.CustomerQuery.FIND_ALL_BLACK_CUSTOMER;
맞습니다,,, 분리를 하니 쿼리에 전달할 키를 전달할 때 키에 오타가 난 것인지, 쿼리에 오타가 난 것인지 확인할 때는 어려운 점이 있는 것 같습니다..!!
작성 당시에는 jdbc repository 코드가 길어지다 보니, 해당 파일에서 쿼리를 직접 작성하다가 실수의 여지가 생길 것 같아 쿼리를 분리했습니다!

2023-11-05 11:42 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/constant/Message.java
> +    public static final String IO_EXCEPTION = "Error raised while reading file!";
반영하겠습니다!

2023-11-05 11:55 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/VoucherJDBCRepository.java
> +    public void save(Voucher voucher) {
넵! 시간 상 우선 이름을 변경하는 방향으로 반영하겠습니다!

2023-11-05 14:02 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/util/Validator.java
> +    public static void validateDiscountValue(VoucherType voucherType, String discountValueStr) {
공통 validator기 Voucher에 의존한 상태로 만들다 보니 뷰 부분이나 서비스 부분에서 검증하는 것이 조금 어려웠던 것 같기도 합니다!  Voucher나 VoucherType을 리팩토링하여 개선해보겠습니다!

2023-11-05 14:03 UTC, Sehee-Lee-01 commented on src/main/java/com/programmers/vouchermanagement/util/Validator.java
>          }
https://github.com/prgrms-be-devcourse/springboot-basic/pull/925#discussion_r1381502395
피드백과 함께 반영해보겠습니다!

2023-11-06 02:53 UTC, Sehee-Lee-01 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/CustomerJDBCRepositoryTest.java
> +    }
현재 customers, vouchers, ownership 이라는 세개의 테이블이 있는데 ownership 이라는 테이블이 customers, vouchers를 참고하고 있습니다.
그래서 바로  "TRUNCATE TABLE test.customers"를 실행할 경우 경고가 뜨기 때문에 FOREIGN_KEY_CHECKS 를 해제하고 지운 다음 다시 돌려놓았습니다!

2023-11-06 09:15 UTC, Sehee-Lee-01 commented on src/test/java/com/programmers/vouchermanagement/TestConfig.java
> +}
앗 혹시 EOF를 말씀하시는 것일까요!! 반영하겠습니다!