[5기 - 조은비] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #926
Opened 2023-10-27 08:51 UTC by eunbc

## 📌 과제 설명 

**(기본)** **바우처 관리 애플리케이션**

- [x]  바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x]  바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x]  (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**

- [x] 특정 고객에게 바우처를 할당할 수 있습니다. (고객) - (고객 id, 바우처 id)
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다. (고객) (고객 id)
- [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.  (고객) (고객 id, 바우처 id)
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다. (바우처) (바우처 아이디)

## ✅ PR 포인트 & 궁금한 점 

코멘트로 남겨놓겠습니다!

2023-10-28 02:21 UTC, marooo326 reviewed
.

2023-10-28 02:21 UTC, marooo326 commented on build.gradle
>  }
Java 버전을 정확히 명시해주면 더 좋을 것 같습니다!

2023-10-28 03:07 UTC, marooo326 reviewed
코드 잘 봤습니다!! 덕분에 많이 배웠습니다 😀

2023-10-28 03:07 UTC, kimday0326 commented on build.gradle
>  }
Java 버전을 정확히 명시해주면 더 좋을 것 같습니다!

2023-10-28 03:07 UTC, kimday0326 commented on src/main/java/com/programmers/springbasic/config/DatabaseConfig.java
> +}
application.yml에 dataSource에 대한 설정을 해주었다면, 이 부분은 제거해주셔도 될 것 같습니다!

https://ksh-coding.tistory.com/88

2023-10-28 03:07 UTC, kimday0326 commented on src/main/java/com/programmers/springbasic/command/MainCommandExecutor.java
>  				command.execute();
applicationContext를 활용하신 부분이 인상깊었습니다👍

2023-10-28 03:07 UTC, marooo326 commented on src/main/java/com/programmers/springbasic/constants/MessageConstants.java
> +public final class MessageConstants {
여기서 Enum 대신 class를 사용하신 이유가 있는지 궁금합니다😃

2023-10-28 03:07 UTC, marooo326 commented on src/main/java/com/programmers/springbasic/utils/FileUtils.java
>  public class FileUtils {
static 메서드를 잘 활용하신 것 같습니다👍

2023-10-28 15:49 UTC, aegis1920 requested changes
코드가 깔끔하네요 👍 아주 약간의 코멘트 남겼습니다 확인 부탁드려요~

2023-10-28 15:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/command/customer/UpdateCustomerCommand.java
> +
일관성 맞춰주세요! (개행 삭제)

2023-10-28 15:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/command/wallet/GetCustomersByVoucher.java
> +public class GetCustomersByVoucher implements Command {
일관성을 위해 Command를 붙여주는 게 좋아보입니다.
```suggestion
public class GetCustomersByVoucherCommand implements Command {
```

2023-10-28 15:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/constants/ErrorCode.java
> +	INVALID_UUID("uuid 입력이 잘못되었습니다"),
여기 메시지들은 중복을 줄이기 위해서 enum으로 빼신 걸까요?

2023-10-28 15:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/utils/FileUtils.java
> +	private FileUtils() {
👍

2023-10-28 15:49 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/repository/voucher/JdbcVoucherRepository.java
> +		jdbcTemplate.update(sql, voucher.getVoucherId(), voucher.getVoucherType().name(), percentValue, amountValue);
jdbcTemplate.update는 어떤 걸 반환할까요?

2023-10-29 15:09 UTC, aegis1920 approved these changes
고생 많으셨습니다! 2단계 코멘트는 3단계에서 함께 반영해주세요!

2023-10-29 15:09 UTC, merged