[5기 김대휘] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #927
Opened 2023-10-27 08:55 UTC by marooo326

## 📌 과제 설명 
**(기본)** **바우처 관리 애플리케이션**

- [ ] 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [ ] 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [ ] (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**
- [ ] 특정 고객에게 바우처를 할당할 수 있습니다.
- [ ] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [ ] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [ ] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 
### message
프로젝트에서 전반적으로 쓰이는 Message를 담아놓은 패키지입니다.
도메인별로 Enum을 구분하였으며, 예외 발생시에 사용하는 메세지는 ErrorMessage에 모아두었습니다.

### domain
도메인인 customer, voucher, wallet을 작성하였습니다.
voucher 패키지에는 두 가지의 Voucher와 VoucherType Enum, VoucherFactory를 작성하였습니다.

### repsoitory
JDBC나 파일에 저장하는 역할의 Repository 클래스를 작성하였습니다.
인터페이스를 이용하여 추상화하였으며, 도메인별로 레포지토리를 작성하였습니다.

### service
도메인별로 주요한 서비스로직을 구현하였습니다.

### util
프로젝트에서 전반적으로 사용되는 메서드를 정의해놓은 패키지입니다.
ConsoleUtil에는 입/출력 시, 자주사용되는 메서드를 static 메서드로 정의해놓았습니다.

### view
입/출력과 관련된 Console 클래스인 console을 작성하였습니다.

## ✅ PR 포인트 & 궁금한 점 
코멘트로 남기겠습니다!

2023-10-28 02:58 UTC, eunbc reviewed
코드 잘 읽었습니다! 많이 배우고 갑니다 😀

2023-10-28 02:58 UTC, eunbc commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/JdbcVoucherRepository.java
> +    @Transactional
@Transactional 의 용도는 무엇일까요? 
Repositoy에서 사용한 이유가 있는지 궁금합니다!

2023-10-28 02:58 UTC, eunbc commented on src/main/java/com/programmers/vouchermanagement/service/WalletService.java
> +        if (affectedRow == 0) {
delete 문을 실행하기 전에
id로 먼저 찾고, 없으면 예외를 발생시키는 방식을 사용해도 좋을 것 같습니다! (fail-fast) 😀

2023-10-28 02:58 UTC, eunbc commented on src/main/java/com/programmers/vouchermanagement/dto/VoucherDto.java
> +    public static class Create {
클래스 내부에 static 클래스를 사용하여 그룹화 할 수 있겠군요!👍

2023-10-28 02:58 UTC, eunbc commented on src/main/java/com/programmers/vouchermanagement/message/VoucherMessage.java
> +
메세지를 꼼꼼하게 남겨주어서 사용자가 편하게 사용할 수 있겠네요 👍

2023-10-28 02:58 UTC, eunbc commented on src/main/java/com/programmers/vouchermanagement/view/Console.java
> +        Voucher voucher = voucherService.findByVoucherId(getUUID());
서비스가 도메인을 반환하면, 도메인 계층이 프레젠테이션 계층에 노출된다고 생각하는데 대휘님은 어떻게 생각하는지 궁금합니다!

2023-10-29 13:05 UTC, aegis1920 requested changes
고생 많으셨습니다! 코멘트 남겼으니 확인해주세요~

2023-10-29 13:05 UTC, aegis1920 commented on build.gradle
> +    testImplementation "org.testcontainers:mysql:1.19.1"
나중에 쓰이는 의존성인걸까요?

2023-10-29 13:05 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/FixedAmountVoucher.java
> +//    public float discount(float beforeDiscount) {
사용하지 않는 코드라면 삭제해주세요!

2023-10-29 13:05 UTC, aegis1920 commented on src/main/resources/database/docker-compose.yml
order_mgmt database를 생성하거나 스키마 DB를 실행시키거나 모두 docker-compose에서 가능하니 적용해보면 좋을 것 같습니다.

2023-10-29 13:05 UTC, aegis1920 commented on src/main/resources/database/schema.sql
> +    CONSTRAINT unq_user_name UNIQUE (name)
유니크 조건을 넣으신 이유가 있을까요?

2023-10-29 13:05 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
> +        if (createDto.createdAt == null) createDto.createdAt = LocalDateTime.now();
null일 때 넣어주는 방법은 의도하신 걸까요?

2023-10-29 13:05 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/dto/VoucherDto.java
> +    public static class Create {
static class는 public이 아닌 default 접근 제한자로 작성해서 접근 제한을 최소화시켜주세요!

2023-10-29 13:05 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +                "############# Customer #############" + System.lineSeparator() +
String.format이 나은 거 같기도 하고 현재 방법이 나은 거 같기도 하고 그러네요ㅎㅎ

2023-10-29 13:05 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/wallet/Wallet.java
> +        return "============= Wallet =============" +
- 이 toString()은 어떤 역할인가요?
- Wallet 자체를 나타내는 toString이라기보단 출력을 위한 toString()으로 보이는데요. 출력을 위한 거라면 get해서 출력하는 것이 나을 것 같습니다.

2023-10-29 13:05 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/wallet/Wallet.java
> +public class Wallet {
record class가 될 수 있겠네요

2023-10-29 13:05 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
> +                .filter(voucher -> voucher.getName().contains(name))
get해서 비교하지 않고 Voucher에게 물어보는 건 어떨까요?

2023-10-29 13:05 UTC, aegis1920 commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
> +class CustomerServiceTest {
예외 케이스에 대한 테스트가 더 추가되면 좋을 것 같습니다!

2023-10-29 15:09 UTC, aegis1920 approved these changes
고생 많으셨습니다! 2단계 코멘트는 3단계에서 함께 반영해주세요!

2023-10-29 15:09 UTC, merged