[5기 - 이중원] SpringBoot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #928
Opened 2023-10-27 10:01 UTC by shoeone96

## 📌 과제 설명 + 요구 사항과 구현 내용

![스크린샷 2023-10-27 오후 6 59 01](https://github.com/prgrms-be-devcourse/springboot-basic/assets/85065626/1cf851d5-d7d6-4b8e-bf70-228bc3359cb0)

## Todolist
- [x]  Customer Table 설계하기
- [x]  Voucher Table 설계하기(고객 테이블을 외래키로 갖게 하기)
- [x]  JdbcCustomerRepository 생성 및 연결
- [x]  JdbcVoucherJdbcRepository 생성 및 연결
- [x]  고객 바우처 할당 api 만들기
`giveVoucher()`
    - [x]  고객 바우처 할당 controller 만들기
    - [x]  고객 바우처 할당 service 만들기
    - [x]  고객 바우처 할당 service test 만들기
    - [x]  고객 바우처 할당 repository 만들기
    - [x]  고객 바우처 할당 repository test 만들기
- [x]  고객 바우처 조회 api 만들기
`getVouchersOfOwner()`
    - [x]  고객 바우처 조회 controller 만들기
    - [x]  고객 바우처 조회 service 만들기
    - [x]  고객 바우처 조회 service test 만들기
    - [x]  고객 바우처 조회 repository 만들기
    - [x]  고객 바우처 조회 repository test 만들기
- [x]  고객 바우처 제거 api 만들기
`deleteVoucher()`
    - [x]  고객 바우처 제거 controller 만들기
    - [x]  고객 바우처 제거 service 만들기
    - [x]  고객 바우처 제거 service test 만들기
    - [x]  고객 바우처 제거 repository 만들기
    - [x]  고객 바우처 제거 repository test 만들기
- [x]  특정 바우처 소유 고객 조회 api 만들기
`getVoucherOwner()`
    - [x]  고객 바우처 조회 controller 만들기
    - [x]  고객 바우처 조회 service 만들기
    - [x]  고객 바우처 조회 service test 만들기
- [x]  전체 api 점검하기

## ✅ 피드백 반영사항  
- 기능별 테스트 코드 작성
- stream filter 사용 시 getter 이외의 전용 메서드를 사용
- nested를 이용해 테스트 가독성을 높이려고 노력

## ✅ PR 포인트 & 궁금한 점 
1. 테스트를 돌리다 보니 너무 무거워져서 효과적인 테스트 작성 방법(가벼우면서 효과적인)으로 참고할만한 reference가 있는지 궁금합니다!

2. controller 앞에 input 계층을 두어 실제 web에서 컨트롤러처럼 주입 받는 방식을 생각해봤는데 방법이 떠오르지 않아 혹시 조언이나 의견 남겨주시면 감사드리겠습니다.

2023-10-28 07:41 UTC, ksy90101 requested changes
이 프로젝트는 아예 실행이 안됩니다.

```
Parameter 1 of constructor in org.programmers.springorder.voucher.service.VoucherService required a bean of type 'org.programmers.springorder.customer.repository.CustomerRepository' that could not be found.


Action:

Consider defining a bean of type 'org.programmers.springorder.customer.repository.CustomerRepository' in your configuration.
```

cf) 
1. (질문) bin폴더는 무엇을 위한 것인가요?
2. 로그 파일이 잘못 올라가 있는거 같아요.

2023-10-29 06:05 UTC, shoeone96 commented
실행이 안되는 이유: 
1. 제가 deafult 프로파일 설정을 해놓지 않아 프로파일 설정을 하지 않으면 작동하지 않는 문제가 발생했습니다.
2. db 설정을 별도로 하지 않아 제 로컬에서는 작동했지만 mysql dabase, table 설정이 안된 환경에서는 작동하지 않는 문제가 발생했습니다.

해결방법:
1. mysql 을 띄우고 기본 테이블까지 한번에 설정될 수 있게 Dockerfile을 작성 후 docker로 접근할 수 있게 만들었습니다.
2. 프로파일을 설정하지 않아도 기본적으로 jdbc Repository에 접근할 수 있게 설정했습니다.

사용방법
1. 전체 프로젝트를 pull 받습니다.
2. 프로젝트 내 mysql 폴더에 접속합니다. 프로젝트 폴더 바로 아래 directory가 존재합니다.
-> project 경로에서 cd mysql
3. docker image를 build 합니다.
`docker build -t mysql-image .`
4. docker 컨테이너를 실행합니다.
`docker run -dit --name mysql-container -p 3000:3306 mysql-image`
5. 이후 프로젝트를 실행합니다.


* bin과 로그파일의 경우 `.gitignore`에 이후 추가했으나 이전에 이미 올라간 파일이 남아있었던 것으로 추정되어 파일 삭제 후 다시 로컬에서 pull 받고 push를 진행하였습니다.

2023-10-29 07:08 UTC, ksy90101 requested changes
```
Description:

Parameter 0 of constructor in org.programmers.springorder.voucher.service.VoucherService required a single bean, but 2 were found:
	- jdbcVoucherRepository: defined in file [/Users/marco/workspace/prgrms-be/springboot-basic/build/classes/java/main/org/programmers/springorder/voucher/repository/JdbcVoucherRepository.class]
	- memoryVoucherRepository: defined in file [/Users/marco/workspace/prgrms-be/springboot-basic/build/classes/java/main/org/programmers/springorder/voucher/repository/MemoryVoucherRepository.class]


```

해당 에러로 인해 실행이 안됩니다. 실행시켜주세요

2023-10-29 07:48 UTC, shoeone96 commented
<img width="1031" alt="스크린샷 2023-10-15 오후 2 10 36" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/85065626/16428fd7-288a-44e2-8e4a-00cb8f227ce7">

1. intellij  접속
1. modify options에서 active profile을 추가
2. `defualt`를 기입하고 실행해주시면 정상 작동합니다.

2023-10-29 08:29 UTC, ksy90101 requested changes
테스트 코드에서 임베드가 아니라 Docker를 사용해서 할수 있게 해보시겠어요?

2023-11-05 09:31 UTC, ksy90101 approved these changes
일단 늦어서 죄송합니다 😢 
간단한 피드백을 남겼으니 확인해주세요~
고생많으셨어요 마지막 3단계에서 파이팅해요!

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/customer/service/CustomerService.java
>      public List<CustomerResponseDto> getBlackList() {
해당 테스트 코드가 존재하지 않네요 ㅎㅎ

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/customer/service/CustomerService.java
> +            throw new RuntimeException("해당 voucher는 주인이 존재하지 않습니다.");
RuntimeException보다 더 의미잇는 예외를 사용하세요.
지금 모두다 RuntimeExcetpion으로 도배되어 있네요.
니중에 핸들링을 하게 될때 어떻게 될지 고민해보시면 좋을거 같습니다.

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/utils/MenuType.java
>      MenuType(String menuNum) {
해당 클래스도 간단히 테스트를 작성해보시면 어떨까요?

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/console/Console.java
>  import org.programmers.springorder.utils.Validation;
1. validation 테스트 코드가 필요합니다.
2. 살펴보니, 이렇게 공통으로 두기 위해선 추상적으로 작성해야 한다고 생각합니다. 지금은 각 도메인에 의존적이고 그게 그냥 util로 바쪄있는거 같아요. 과연 각 메서드들이 재사용성이 가능한지 고민해보시면 좋을거 같고, 좀더 응집도를 높혀보면 어떨까요?

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/customer/repository/JdbcCustomerRepository.java
>          return new HashMap<>() {{
https://stackoverflow.com/questions/1958636/what-is-double-brace-initialization-in-java

해당글을 참고해보세요~

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/customer/repository/FileCustomerRepository.java
> +        }
구현이 재댜로 안된거 같아요?

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/voucher/dto/GiveVoucherRequestDto.java
> +    private final UUID VoucherId;
변수명은 카멜케이스!

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/voucher/dto/GiveVoucherRequestDto.java
> +        this.customerId = customerId;
```suggestion
    private final UUID customerId;
    
    public GiveVoucherRequestDto(UUID voucherId, UUID customerId) {
        VoucherId = voucherId;
        this.customerId = customerId;
```

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/customer/repository/JdbcCustomerRepository.java
> +    private final String FIND_BLACKLIST = "SELECT * FROM customers where customer_type = 'BLACK'";
type을 하드코딩해두면 차후에 변경될때 어려움이 있지 않을까요?
어떻게 해결해볼수 있을까요? enum으로 해결해보면 어떨까요?

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/customer/repository/JdbcCustomerRepository.java
> +    private final String FIND_BLACKLIST = "SELECT * FROM customers where customer_type = 'BLACK'";
static화 해야 하지 않을까요?

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/utils/Properties.java
> +    private static final String customerFilePath = "src/main/resources/csv/customerList.csv";
상수 이름 컨벤션은 무엇일까요?

아울러 상수인데 굳이 getter를 만들 이유가 무엇이 있을까요?

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/voucher/service/VoucherServiceTest.java
> +        assertThat(beforeSaveVoucher).hasSize(0);
```suggestion
        assertThat(beforeSaveVoucher).isEmpty();
```
아예 이렇게 써도 됩니다!

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/voucher/service/VoucherServiceTest.java
> +                .isTrue();
```suggestion
assertThat(rs).containsAll(uuids);
```

2023-11-05 09:31 UTC, ksy90101 commented on build.gradle
> +    testImplementation 'com.wix:wix-embedded-mysql:4.6.1'
이제 안쓰는 의존성 아닌가요?

2023-11-05 09:31 UTC, ksy90101 commented on mysql/init.sql
> +CREATE DATABASE IF NOT EXISTS vouchers;
테스트 DB는 어떻게 만들수 있을까요?

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/customer/repository/FileCustomerRepository.java
> +                .findFirst();
이건 개인적으로 성능적인 부분인데요.
현재는 List이다보니 filter로 완탐을 해야 하기 떄문에 O(n)일꺼 같아요.
그러나 Map으로 만들어서 UUID를 한다면 O(1)이 될수도 있답니다 :) 

그냥 참고만 해주세요~

2023-11-05 09:31 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/voucher/repository/FileVoucherRepository.java
> +    }
과연 Repository에서 이렇게 서로 가지는게 맞을까요?
이런 로직은 Service의 역할이 아닐까 해서요.

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/config/jdbc/JdbcConfig.java
> +                .password("1234")
https://rutgo-letsgo.tistory.com/93를 이용해서 한번 관리해보면 어떨까요?

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/customer/repository/FileCustomerRepositoryTest.java
> +        assertThat(all).containsAll(insertedCustomers);
(질문) 이걸 3개나 만들어서 체크하는 이유는 무엇인가요?

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/customer/repository/FileCustomerRepositoryTest.java
> +        List<Customer> findall = customerRepository.findAll();
이거 있는 이유가 무엇인가요?

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/customer/service/CustomerServiceTest.java
> +}
```suggestion
    }
}
```

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/customer/service/CustomerServiceTest.java
> +//            voucherService.update(voucherId, customerId);
사용하지 않은 주석은 제거해주세요.

2023-11-05 09:31 UTC, ksy90101 commented on src/test/java/org/programmers/springorder/voucher/repository/FileVoucherRepositoryTest.java
> +    }
여기도 3개나 만들어서 검증하는 이유가 무엇인가요?

2023-11-05 09:31 UTC, merged