[5기 - 송인재] Spring Boot Part2 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #929
Opened 2023-10-27 11:33 UTC by IjjS

## 📌 과제 설명

## 👩‍💻 요구 사항과 구현 내용

## ✅ 피드백 반영사항

## ✅ PR 포인트 & 궁금한 점

2023-10-29 07:24 UTC, ksy90101 requested changes
안녕하세요 인재님
고생많으셨어요~
몇가지 리뷰를 남겼으니 확인해주세요

아울러 심화적인 내용에 대해서 이번에 마무리 하고 싶다면 화요일까지 마무리 해주시면 추가 리뷰 진행할게요~

이번 미션의 메인은 DB를 쓰는것과 테스트 코드 작성입니다.

테스트 코드작성이 아직 좀 없는거 같아요.

<img width="1030" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/53366407/ac6e50e0-e100-4562-982e-6d4720f67874">

위에 옵션을 사용해서 한번 내가 놓친 테스트 코드가 무엇일지 생각해보면 어떨까요?

마지막으로 단위테스트도 좋지만 통합테스트라는 개념을 한번 고민해보면 좋겠어요~

2023-10-29 07:24 UTC, ksy90101 commented on build.gradle
> +    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-jdbc
해당 주석이 필요할까요?

2023-10-29 07:24 UTC, ksy90101 commented on build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-jdbc', version: '3.1.4'
다른 의존성과 동일하게 규칙을 지켜서 작성하면 어떨까요?

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/configuration/DBConfig.java
> +    public DataSource dataSource(DataSourceProperties dataSourceProperties) {
DataSourceProperties 👍

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/CustomerRepository.java
> +    default List<Customer> loadBlacklist(String blacklistFilePath) {
(질문) 이게 왜 default method인가요?

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +        int savedCustomer = findById(customer.getCustomerId()).isEmpty() ? insert(customer) : update(customer);
👍

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +        final UUID customer_id = UUIDConverter.from(resultSet.getBytes("customer_id"));
자마 컨벤션에 맞게 적으면 어떨까요?

```suggestion
        final UUID customerId = UUIDConverter.from(resultSet.getBytes("customer_id"));
```

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandler.java
> +    private static final String INCORRECT_MESSAGE = "This menu is not executable.";
실제로 이 두값은 안쓰이는거 같아요!

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/consoleapp/menu/VoucherMenu.java
> +    public static VoucherMenu findVoucherMenu(String input) {
이번 미션의 메인은 테스트 코드 작성입니다.

간단해보이지만, 한번 테스트 코드를 작성해보면 어떨까요?

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/controller/CustomerController.java
>  public class CustomerController {
이번 미션에 메인은 테스트코드 작성인데요.

Controller도 테스트 코드를 작성해보면 어떨까 해요.

해당 메서드를 실행한 뒤에 데이터가 변경되었다면 잘 동작하는게 아닐까요?

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/service/CustomerService.java
>  public class CustomerService {
저는 개인적으로 핵심은 서비스라고 생각합니다.
서비스에 대한 테스트 코드가 아직 부족해요~
서비스 테스트 코드를 더 작성해보면 어떨까요?

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/Formatter.java
> +                .formatted(customerResponse.customerId(), customerResponse.name(), customerResponse.customerType().name());
Formaater에 대한 테스트 코드도 작성해보면 어떨까요?

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/Validator.java
> +    public static void validateCustomerName(String name) {
해당 테스트 코드가 있으면 어떨까요?

2023-10-29 07:24 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/Validator.java
> +    private static final String NAME_LENGTH_EXCESSIVE = "Name is too long.";
이건 개인적인 생각인데요.
Validator가 이렇게 공통으로 있을꺼면, 추상적이여야 한다고 생각이 들어요.

지금은 Name이 25자라고 하지만, Custom에 대해서

그러나 새로운 Content의 글이라는 값이 추가되고 그게 Name이라는걸 가지고 50자라고 한다면, 또 validateContentName이 생기겠죠?

즉, 결국 각 도메인에 맞게 측정이 될텐데 이렇게 공통으로 빼는게 좋은가? 라는 생각이 들어요.

마지막으로 도메인을 보면 도메인의 모든 걸 알아야 할텐데 지금은 Name의 Validate를 알려면 결국 이 클래스까지 있어야 할거 같지 않나요?

즉, 도메인에 맞게 validate코드가 있는게 더 어울려 보인다는 의미입니다

2023-10-29 07:24 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandlerTest.java
>          verify(consoleManager).printException(exception);
전 개인적으로 verify보다 실제 데이터를 확인하는걸 선호하는데요.
실제 데이터가 정상적으로 변경되었는지를 체크하는게 어떨까요?

아니라면 통합테스트같은 느낌으로

https://velog.io/@penrose_15/Scanner%EC%99%80-System.out.println-%EC%97%90-%EB%8C%80%ED%95%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8

이걸 써서 해도 될거 같구요 ㅎㅎ

2023-10-29 07:24 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +    @Order(1)
테스트의 기본 원칙중에
FIRST라는 원칙이 있는데요.
거기서 I라는게 독립성입니다.

즉, 각 테스트 케이스는 독립성을 시켜야 한다는 것인데, 지금처럼 Order가 있다는것은 각각에 대한 독립적이지 않고 순서가 필요하다는 의미러고 생각합니다.

https://rutgo-letsgo.tistory.com/355

해당 원칙을 한번 확인해주세요~

2023-10-29 07:24 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/service/CustomerServiceTest.java
> +        voucherRepository = mock(VoucherRepository.class);
(그냥 인재님의 생각이 궁금했다고 생각해주시면 좋을거 같아요.)

Service Test에 Repository를 mocking 한 이유가 있나요?

2023-10-29 09:09 UTC, IjjS commented on build.gradle
> +    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-jdbc
제거하겠습니다!

2023-10-29 09:10 UTC, IjjS commented on build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-jdbc', version: '3.1.4'
하나의 규칙으로 동일하게 바꾸겠습니다!

2023-10-29 09:11 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/CustomerRepository.java
> +    default List<Customer> loadBlacklist(String blacklistFilePath) {
블랙리스트는 저장소의 형태에 상관없이 기본적으로 읽는 것이 맞지 않을까 생각해서 default로 해놓았습니다

2023-10-29 09:13 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +        final UUID customer_id = UUIDConverter.from(resultSet.getBytes("customer_id"));
꼼꼼했어야 했는데 놓쳤던 부분인 것 같습니다. 반영하겠습니다!

2023-10-29 09:14 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandler.java
> +    private static final String INCORRECT_MESSAGE = "This menu is not executable.";
제거하거나 사용하도록 수정하겠습니다!

2023-10-29 09:20 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/util/Validator.java
> +    private static final String NAME_LENGTH_EXCESSIVE = "Name is too long.";
Validator를 없애고 도메인에서 validate를 하도록 넣어두겠습니다.

바우처에 대한 validate은 타입마다 검증해야 할 것이 달라서 바우처보다는 타입 안에 들어가야 할 것 같다고 생각이 드는데, VoucherType enum에다가 넣어두면 괜찮을까요? enum보다는 바우처 도메인이나 DTO에서 검증하는 것이 낫지 않을까 하는 생각이 밖으로 빼두려다 이렇게 공통으로 두는 결과가 나왔던 것 같습니다.

2023-10-29 09:25 UTC, IjjS commented on src/test/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandlerTest.java
>          verify(consoleManager).printException(exception);
알려주신 링크를 참고해 변경해보겠습니다

2023-10-29 09:29 UTC, IjjS commented on src/test/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +    @Order(1)
각 테스트 케이스는 독립적으로도 테스트가 가능하도록 만들었지만, Order는 테스트가 한 번에 수행이 된다면 '이런 순서여야 하지 않을까?' 하는 생각에 Order를 붙인 것도 있었습니다.
특히, 기존에 존재하는 블랙리스트나 바우처의 csv나 json파일을 로드 했을 때 한 번에 수행한다면 제일 앞에 있어야 하지 않을까 생각을 해서 Order를 사용했는데, 지금 생각해보니 없이도 가능할 것 같다는 생각이 듭니다. 변경하도록 하겠습니다!

2023-10-29 09:34 UTC, IjjS commented on src/test/java/com/programmers/vouchermanagement/customer/service/CustomerServiceTest.java
> +        voucherRepository = mock(VoucherRepository.class);
레포지토리 객체에 문제가 있더라도 서비스의 로직이 잘 작동하는 것과는 별개라고 생각하지만, 서비스가 레포지토리를 의존하고 있어 서비스가 독립적으로 테스트 가능하도록 만드려고 모킹했습니다.
테스트 작성 경험이 부족해 처음엔 stub 객체를 만드려고 했는데, 스프링에서 제공해주는 모키토를 활용해보고자 한 이유도 있습니다.

2023-11-01 00:57 UTC, IjjS commented
이리 저리 수정해보다가 이제야 전부 반영했습니다. 늦어서 죄송합니다!! 말씀해주신 화요일보다 하루 지나서 리뷰가 어렵다 하시더라도 괜찮습니다! 단지 리뷰해주셨던 부분을 반영하고 고민하면서 생긴 궁금한 점들에 대해서 여쭙고 싶습니다.

2023-11-01 01:32 UTC, IjjS commented
이리 저리 수정해보다가 이제야 전부 반영했습니다. 늦어서 죄송합니다!! 말씀해주신 화요일보다 하루 지나서 리뷰가 어렵다 하시더라도 괜찮습니다! 단지 리뷰해주셨던 부분을 반영하고 고민하면서 생긴 궁금한 점들에 대해서 여쭙고 싶습니다.

우선 피드백 반영사항입니다.
* 불필요한 주석 제거
* gradle.build 의존성 규칙 통일
* validation의 위치를 도메인으로 옮김
* 테스트 시 verify 대신 테스트용 파일에서 실제 데이터의 변경 확인

테스트 부분에서 제가 멘토님께서 의도하신 피드백을 잘 수용한건지 모르겠습니다. verify보다는 실제 데이터의 변경을 확인하기 위해서 테스트용 파일을 이용해 테스트를 진행했습니다. 이 과정에서 들었던 고민은 객체들 간의 의존이 테스트 시에 남아있는 것 같아 마음에 걸렸습니다. 예를 들어, 만약 서비스 테스트를 할 때 레포지토리에 잘못된 점이 있다면 서비스 테스트는 실패하게 되어서 독립적이지 못 한 것이지 않을까 생각이 들었습니다. 이 고민은 구글링을 해보며 여러가지를 찾아보다 멘토님이 슬랙에 올려주신 링크를 보고 어느정도 해소가 되었다고 생각이 드는데, 제가 이해한 바가 맞는지 잘 모르겠습니다.

제가 이해한 바로는, 애플리케이션을 유지보수 하면서 변경되는 점들이 있다면 이러한 단위 테스트들은 대상이 과거에 머물러 있기 때문에 실패하지 않을 수도 있습니다. 그러면 단위 테스트의 유지 관리에 리소스가 더 들어가고 결과적으로 단위 테스트가 전체적인 리소스의 낭비를 유발하고 릴리스를 늦출 수도 있습니다. 그래서 완전하고 빠른 단위 테스트들을 통한 무차별적인 기능 테스트에 많은 시간을 쏟는 것보단, 정확한 테스트에 초점을 두어 다른 유형의 테스트들과의 밸런싱을 해서 추후의 테스트의 유지 관리 리소스에 초점을 두는 것이 바람직하다고 이해했습니다.

저는 객체를 모킹을 하는 것이 단위 테스트 할 때 객체들 간의 의존성을 해소해준다고 생각하여 모킹은 단위 테스트에 어울린다고 생각해서 사용했습니다. 하지만 공유해주신 글을 타고 들어가 마틴 파울러의 글을 보니 모킹은 오히려 외부 의존성을 모킹해서 실제 외부 의존성과의 결과를 비교해 테스트하는 것이 더 적합하다는 말에 동의하게 되었습니다. 그래서 피드백 주신 것처럼 verify를 사용하기보다 실제 데이터를 확인하기 위해 SpringBootTest를 이용해서 테스트를 변경했습니다. 하지만 제가 멘토님이 의도하신 바를 잘 이해하고 변경한 것인지 잘 모르겠고 테스트에 대한 개념이 여전히 어렵게 느껴지는 것 같긴 합니다..

추가적인 질문으로, 저는 상수와 메세지들을 사용하는 곳에서 private으로 두었습니다. 만약 이 상수와 메세지들이 테스트에서 쓰이면 public으로 모아두는 것이 더 괜찮겠다는 생각이 드는데 이게 맞는 생각인지 궁금합니다!

바쁘신데도 시간 내주셔서 감사합니다!!

2023-11-01 12:15 UTC, ksy90101 approved these changes
고생많으셨습니다.

간단한 리뷰를 남겼는데 3주차 미션을 하면서 같이 수정해주세요~

👍

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +        customerObject.put("customerType", customer.getCustomerType().name());
위에 key가 상수로 되어 있네요!

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/JSONFileManager.java
> +    public List<T> loadFile(String filePath, Function<Map, T> mapObjectToDomain) {
Map에 대한 제네릭으로 타입을 지정하면 어떨까요?

2023-11-01 12:15 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/util/FormatterTest.java
> +    void testFormatNoContent_Voucher() {
아래 2개까지 같은 로직인거 같아요.
이런 경우엔 @parameterizedTest를 사용해볼수 있는데요.
한번 사용해보면 어떨까요?

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/InMemoryCustomerRepository.java
> +    }
이렇게 비어두지 말고, 예외를 덜져서 구현되지 않음이라고 명시해두면 어떨까요?

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/JSONFileManager.java
> +            throw new RuntimeException(FILE_EXCEPTION);
RuntimeException보다 더 의미잇는 예외 클래스를 사용해보면 어떨까요?

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/JdbcVoucherRepository.java
> +    }
여기도 구현해줘야 하지 않을까요?
각 테스트 마다 독립성을 지키기 위해 롤백이 필요하니깐요.

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/CustomerRepository.java
> +    default List<Customer> loadBlacklist(String blacklistFilePath) {
JDBC인 경우엔 파일에 있는거랑 싱크를 맞춰야 할지?
그게 궁금했습니다.

블랙리스트는 무조건 파일로 관리한다라는게 인재님이 생각하신 정책이실까요?

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/InMemoryCustomerRepository.java
> +        }
어차피 customers가 비어있다면 아래서 빈 리스트가 리턴되지 않나요?

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/InMemoryCustomerRepository.java
> +        }
````
		Map<String, String> map = new HashMap<>();

		System.out.println(map.values().stream().toList());
		if (map.isEmpty()) {
			System.out.println( Collections.emptyList());
		}
````

<img width="379" alt="image" src="https://github.com/prgrms-be-devcourse/springboot-basic/assets/53366407/78d5cd96-2933-4c02-967d-a613b1ca072a">

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +    }
이건 한번 고민해보면 좋을거 같아요.
차후 customers가 많앗을때 이 쿼리를 호출하면 어떻게 될까요?
full table scan이 되지 않을까요? 
인덱스가 없다면요. ㅎㅎ

(지금 인덱스를 고려하라는게 아니라, 이런 관점에서도 쿼리를 한번 바라보면 좋겠다~! 라는 의미입니다)

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +    }
blacklist를 forEach로 save를 호출했다고 하면.

리스트에 100개가 있으면 쿼리가 100개가 날라가니깐 통신이 계속 일어나면서 부하가 발생하지 않을까요?

그리고 DB의 데이터가 이미 있는 상테에서 계속 불러오면 동일한 데이터가 계속 들어가는(혹은 업데이트)되는게 아닐까요?

파일과 DB를 둘다 유지해야하는 이유가 무엇알까요?

마지막으로 bluk insert를 고민해보면 좋겠어요~

https://dev.dwer.kr/2020/04/mysql-bulk-inserting.html

(지금처럼 유지햐야 한다면.)

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepository.java
> +        String updateSQL = "UPDATE customers SET name = :name, customer_type = :customerType WHERE customer_id = UUID_TO_BIN(:customerId)";
이것도 그냥 이야기 드려봐요. 이런 관점도 고민해봣으면 좋겟다~ 라는 개념입니다.

실제 name과 customer_type이 실제 DB에 있는것과 변경되지 않고 그냥 쿼리를 날리면 그 쿼리 통신비용은 의미가 없죠? 그런식으로도 성능 튜닝을 라이브러리에선 하기도 합니다 :)

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/util/JSONFileManager.java
> +            });
1depth를 유지했으면 좋겠다. 라고 요구사항을 드렸는데 람다도 결국 1depth가 더 되는것입니다.

그렇다면 지금 try 1depth, forEach에 2depth가 되는거라서요!

한번 수정해보면 어떨까요?

2023-11-01 12:15 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherType.java
> +            logger.error(INVALID_DISCOUNT_AMOUNT_MESSAGE);
validate가 걸리는걸 error로 찍히면 차후 error로그를 볼때 에러 로그가 도배될수도 잇지 않나요?
이런게 로그로 찍어야 하는 에러인지 한번 고민해보면 좋을거 같아요.
아울러 아래에서 이미 로그가 찍힐꺼 같은데..ㅎㅎ

2023-11-01 12:15 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/consoleapp/menu/CustomerMenuTest.java
> +    void testFindMenuSuccessful() {
이런건 이렇게 한번에 하기보단 @parameterziedTest를 사용하면 훨씬 깔끔하게 할수 있어요~

2023-11-01 12:15 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepositoryTest.java
> +@SpringBootTest
SpringBootTest는 모든 빈을 다 불러오는데요.
이렇게 Repository와 같이 하위 레이어를 테스트 할땐 방법이 또 있습니다.

@jbdcTest와 같은 키워드를 알아보시면 어떨까요?

2023-11-01 12:15 UTC, ksy90101 commented on src/test/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepositoryTest.java
> +@SpringBootTest
아 여기가 @jdbcTest가 되어야 겠군요.

2023-11-01 12:15 UTC, merged

2023-11-01 12:31 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
> +        customerObject.put("customerType", customer.getCustomerType().name());
상수로 사용하도록 하겠습니다!

2023-11-01 12:36 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/util/JSONFileManager.java
> +    public List<T> loadFile(String filePath, Function<Map, T> mapObjectToDomain) {
어차피 Map으로 변환해야하니 List가 아니라 Map으로 하는게 맞다고 생각합니다. 왜 이런 부분을 생각 못 하고 넘어갔을까요..수정하겠습니다!

2023-11-01 12:38 UTC, IjjS commented on src/test/java/com/programmers/vouchermanagement/util/FormatterTest.java
> +    void testFormatNoContent_Voucher() {
오 감사합니다! 이런 어노테이션의 존재를 잘 몰랐는데, 반영하겠습니다!!

2023-11-01 12:42 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/InMemoryCustomerRepository.java
> +    }
명시 하는 것을 항상 습관화 해야 하는데 그러지 못했던 것 같습니다. 항상 염두에 두겠습니다!

2023-11-01 12:50 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/util/JSONFileManager.java
> +            throw new RuntimeException(FILE_EXCEPTION);
최대한 존재하는 예외 클래스를 사용하려고 했는데, 이에 맞는 예외를 찾지 못 했어서 RuntimeException으로 남겨두었었습니다. 커스텀 예외를 만들어 처리하도록 하겠습니다!

2023-11-01 12:54 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/JdbcVoucherRepository.java
> +    }
데이터 저장소가 외부에 있을 땐 deleteAll 같은 전체의 변화를 유발하는 존재는 어쩔 수 없는 경우가 아니면 아예 없는 것이 낫다고 생각해 구현하지 않았었습니다. 그래서 `Order`와 테스트 컨테이너를 사용해 테스트마다 독립성을 지키려고 했는데, 이제는 필요할 것 같습니다. 구현하고 테스트에 적용하겠습니다!

2023-11-01 13:00 UTC, ksy90101 commented on src/main/java/com/programmers/vouchermanagement/voucher/repository/JdbcVoucherRepository.java
> +    }
그렇다면 NotImplementedException 이런 예외를 발생시켜 차후 문제가 안되게 하면 어덜까요?

2023-11-01 13:06 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/CustomerRepository.java
> +    default List<Customer> loadBlacklist(String blacklistFilePath) {
사실 큰 의미 없이 블랙리스트 관리는 요구사항이 새롭게 생긴 것이 없어서 1주차 요구사항에 충실하려고 했었습니다. DB를 사용할 땐 불필요하게 복잡하니 이 메서드는 없는 것이 낫다는 것에 동의합니다. 반영하겠습니다!

2023-11-01 13:10 UTC, IjjS commented on src/main/java/com/programmers/vouchermanagement/customer/repository/InMemoryCustomerRepository.java
> +        }
불변 리스트로 반환하기 위해 emptyList를 사용했습니다!