[5기 - 박영재] SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #945
Opened 2023-11-01 01:31 UTC by park0jae

## 📌 과제 설명 
## SpringBoot Part3 Weekly Mission

**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용 해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [X]  조회페이지
    - [X]  상세페이지
    - [X]  입력페이지
    - [X]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [X]  전체 조회기능
    - [X]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [X]  바우처 추가기능
    - [X]  바우처 삭제기능
    - [X]  바우처 아이디로 조회 기능

**(보너스) 바우처 지갑용 관리페이지를 만들어보세요.**

## 👩‍💻 요구 사항과 구현 내용 
Docker Setting : docker-compose.yml이 위치하는 곳에서 아래의 명령어를 통해 docker로 mysql을 실행 시킵니다.
```
docker-compose up -d
```

### Controller
- web : 타임리프를 통한 바우처, 회원, 지갑 관리 페이지 컨트롤러
- api : JSON과 XML을 지원하는 바우처, 회원, 지갑 REST API

### advisor
- WebExceptionAdvisor : WebController 에서 발생하는 예외를 전역으로 처리하기 위한 advisor 클래스
- ApiExceptionAdvisor : ApiController 에서 발생하는 예외를 전역으로 처리하기 위한 advisor 클래스

### Deprecated
- 기존 메모리, 파일 관련 레포지토리나 콘솔 프로그래밍 관련 클래스들은 Deprecated 어노테이션으로 처리 했습니다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 테스트 코드 관련하여 WebController 같은 경우에는 테스트 코드를 어떤식으로 짜야할 지 어려움을 겪고 있습니다. 해당 테스트 코드가 굳이 필요한가? 라는 생각도 드는데 필요성과 방향성에 대한 멘토님의 의견이 궁금합니다 !
- ApiController에 대한 테스트 코드를 처음 작성해봤는데, 로직이 적절한지 궁금합니다. 데이터를 담아서 반환하는 부분은 전부 데이터를 검증해주는게 좋을까요 ? 우선은 verify로 호출 관련 검증을 주로 작성 했습니다. 
- 추가로 코드 관련 궁금한 점들은 코멘트로 남겨놓겠습니다 !

2023-11-01 14:10 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +            sql.append(" where created_at = :createdAt");
Repository 내에서 검색 조건에 따라 쿼리를 동적으로 만들어주도록 구현했는데, 적절한 방안인지 아니라면 더 좋은 방안이 있을지 궁금합니다 !

2023-11-01 16:42 UTC, aegis1920 requested changes
빠르게 PR을 제출했음에도 불구하고 정말 잘 작성해주셨네요 👍 몇 가지 코멘트 드렸습니다! 
확인해주세요~

> 테스트 코드 관련하여 WebController 같은 경우에는 테스트 코드를 어떤식으로 짜야할 지 어려움을 겪고 있습니다. 해당 테스트 코드가 굳이 필요한가? 라는 생각도 드는데 필요성과 방향성에 대한 멘토님의 의견이 궁금합니다 !

이 부분은 구두로 이야기나눈 것으로 대체하겠습니다!

> ApiController에 대한 테스트 코드를 처음 작성해봤는데, 로직이 적절한지 궁금합니다.

모두 mocking한 단위 테스트군요? 잘 작성해주셨습니다만.. 테스트가 터집니다! 확인 한 번 부탁드려요 [이 글](https://tecoble.techcourse.co.kr/post/2021-05-25-unit-test-vs-integration-test-vs-acceptance-test/)도 좋으니 한 번 읽어보시고 시간될 때 통합테스트 혹은 인수테스트도 적용해보시면 좋을 것 같아요~

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +        log.warn("Error Message ={}", e.getMessage());
최상위 클래스인 Exception이라면 warn 로그가 아니라 error 이어야 개발자가 심각하게 인지하지 않을까요?

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +    public Response exceptionMessage(Exception e){
- 이때도 raw 타입이 아닌 타입을 명확하게 해주세요!
- 보통 Error는 ErrorResponse 클래스를 만들어서 공통 규격으로 응답하기도 합니다!

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/api/ApiCustomerController.java
> +@RequestMapping("/api/customers")
api에 대한 버전도 명시하면 좋습니다
```suggestion
@RequestMapping("/api/v1/customers")
```

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +        UseStatusType.of(voucherUpdateRequest.getUseStatusType());
삭제해도 되는 코드일까요?

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +    public ResponseEntity deleteAllVouchers() {
ResponseEntity도 Raw 타입이 아닌 타입을 명시해주세요!

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +        return new ResponseEntity(voucherService.update(UUID.fromString(voucherId), voucherUpdateRequest), OK);
ResponseEntity를 new 하신 것도 있고 ResponseEntity.ok를 사용하신 것도 있는데 일관성을 위해 맞춰보는 건 어떨까요?

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/dto/voucher/VoucherCreateRequest.java
Request 쪽에 final을 붙여도 됩니다. record class가 될 수 있겠군요ㅎㅎ

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/advisor/WebExceptionAdvisor.java
> +@ControllerAdvice(annotations = Controller.class)
Controller로 구분해서 에러 페이지를 내보내기보단 ErrorController를 상속하는 걸 고려해보시면 좋을 것 같습니다! ([링크](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/api/org/springframework/boot/web/servlet/error/ErrorController.html))

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +    public ResponseEntity updateVoucher(@PathVariable("voucherId") String voucherId, @Valid @RequestBody VoucherUpdateRequest voucherUpdateRequest) {
웹에서 수정은 안되는 것 같은데 확인 한 번 부탁드려요!

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/domain/voucher/FixedDiscountVoucher.java
> +        this.createdAt = LocalDate.now();
보통 생성일자를 만들면 시간까지 나타내는 LocalDateTime을 활용하는데요. LocalDate만 사용하신 이유가 있을까요?

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +    public List<Voucher> findVoucherByCondition(VoucherCondition condition) {
검색 조건 Dto(VoucherCondition)가 아래처럼 되어야 좀 더 유동적으로 개발이 가능할 것 같아요. 보통은 검색하고자 하는 입력 값이 따로 있고, 날짜 조건은 함께 들어가기 때문에 아래처럼 구성됩니다. 날짜 조건은 기간으로 오는 경우가 많습니다.

```
private final SearchType searchType;
private final String value;
private final LocalDateTime startCreateAt;
private final LocalDateTime endCreateAt;
...
```

2023-11-01 16:42 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +            sql.append(" where created_at = :createdAt");
동적으로 만들어주는 건 좋은 선택으로 보입니다! where 절이 조금 중복되는 거 같은데 맨 앞에 where String을 하나만 넣어주고 그 다음에 and 조건으로 붙여주는 형식은 어떤가요?
```
where(searchValue가 null이면 그냥 실행) + 조건 + and + 조건 ...
```

2023-11-02 11:19 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +        log.warn("Error Message ={}", e.getMessage());
최상위 예외라면 error 로그가 좀 더 적합할 것 같습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/a5d1a01752ed061e6ec7d0b94a71a6a3123980db

2023-11-02 11:20 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +    public Response exceptionMessage(Exception e){
ErrorResponse를 통해 타입을 명시하고, 반환하도록 수정했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/d811d9b20117845507a7e7c71119e3914a3a7204

2023-11-02 11:21 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/api/ApiCustomerController.java
> +@RequestMapping("/api/customers")
https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/8895499ecf29864792bcc6c2d95bbbab9aad3d3c

2023-11-02 11:22 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +        return new ResponseEntity(voucherService.update(UUID.fromString(voucherId), voucherUpdateRequest), OK);
new 키워드를 사용하지 않는 방향으로 일관성을 적용했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/d6035f9bedea167f3ccf5de09036e6c6ddf0593f

2023-11-02 11:23 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +    public ResponseEntity deleteAllVouchers() {
ResponseEntity에도 구체적인 반환 타입을 명시했습니다. https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/d6035f9bedea167f3ccf5de09036e6c6ddf0593f

2023-11-02 11:23 UTC, park0jae commented on src/main/java/com/zerozae/voucher/dto/voucher/VoucherCreateRequest.java
https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/44e0aa63546f83767e44e989938967466edbe469

2023-11-02 11:24 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +    public ResponseEntity updateVoucher(@PathVariable("voucherId") String voucherId, @Valid @RequestBody VoucherUpdateRequest voucherUpdateRequest) {
한번 더 확인 부탁드립니다 !

2023-11-02 11:25 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +            sql.append(" where created_at = :createdAt");
Voucher 검색 조건 Dto에 대해 제시해주셨던 필드들에 대한 수정은 추후에 적용해보겠습니다 ! 우선은 중복되는 where 절을 빼고, 조건 검색이 모두 비어 있을 경우 모든 바우처를 리턴하는 방향으로 수정했습니다. https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/a7e8e13a58ed6aaa1103bca1075bfe8b09e95bd2

2023-11-02 11:28 UTC, park0jae commented on src/main/java/com/zerozae/voucher/domain/voucher/FixedDiscountVoucher.java
> +        this.createdAt = LocalDate.now();
검색할 때 보통 yyyy-MM-dd 형식으로 검색을 한다고 생각해서 검색조건만을 고려하여 LocalDateTime 대신 LocalDate를 사용했는데, 바우처에 대한 생성 시간까지 저장되도록 하는 것이 좋을 것 같습니다 ! 수정 하겠습니다.

2023-11-02 12:22 UTC, park0jae commented on src/main/java/com/zerozae/voucher/repository/voucher/JdbcVoucherRepository.java
> +    public List<Voucher> findVoucherByCondition(VoucherCondition condition) {
바우처의 discount나, 검색하고자 하는 기간 범주를 지정할 수 있도록 start, end 날짜를 추가하고 repository 내의 로직도 수정했습니다 ! https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/b42b770aa8dd8dd2e25abb48a493e0263da25b2c  https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/0b4a77c52e7af75c025b6ac8782c5a58f9df6a4f

2023-11-02 12:25 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/api/ApiVoucherController.java
> +        UseStatusType.of(voucherUpdateRequest.getUseStatusType());
수정 했습니다. https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/028c9269c0746749061ff4437585ee4a5f093ed3

2023-11-04 07:23 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/domain/voucher/FixedDiscountVoucher.java
> +        this.createdAt = LocalDate.now();
넵! 검색 조건 자체는 그렇게 들어갈 수 있는데요. 기본적으로 테이블을 생성할 때 row에 대한 생성 시간은 꼭 들어갑니다. 생성 시간은 `yyyy-MM-dd HH:mm:ss`를 많이 사용하는데요. 시간에 조금 더 민감한 데이터라면 `yyyy-MM-dd HH:mm:ss:SSS`를 활용하기도 합니다! 참고해주세요!

2023-11-04 07:25 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +public class ApiExceptionAdvisor {
ResponseEntity 형태로 리턴한다면 [ResponseEntityExceptionHandler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/ResponseEntityExceptionHandler.html)를 활용해보세요!

2023-11-04 07:25 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/api/ApiWalletController.java
> +        return ResponseEntity.status(OK).body("완료 되었습니다.");
204 no content http status를 사용해보는 건 어떨까요? ([링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
))

2023-11-04 07:25 UTC, aegis1920 commented on src/main/java/com/zerozae/voucher/controller/api/ApiWalletController.java
> +    public ResponseEntity<WalletResponse> createWallet(@Valid @RequestBody WalletCreateRequest walletCreateRequest) {
201 created http status에는 어떤 게 들어가야 할까요? ([링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201))

2023-11-05 22:26 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
예외를 처리하는 로직이 굉장히 복잡해 보입니다.
 구체적으로 말씀드리자면 ErrorResponse에 HttpStatus의 value가 들어가고 또 HttpStatus.BAD_REQUEST를 사용하고 있는 모습을 보면서 생각했어요.
 
 결과적으론 리턴되고 있는 Entity에 Http status가 2개 들어가는 모습입니다.
 
 제 의견이 맞을까요?

2023-11-05 22:26 UTC, cloudwi commented on src/main/java/com/zerozae/voucher/controller/api/ApiCustomerController.java
> +    public ResponseEntity<CustomerResponse> createCustomer(@Valid @RequestBody CustomerCreateRequest customerCreateRequest) {
이곳 @Valid 수행 중 예외가 발생하면 핸들링을 해주면 좋을 것 같아요!

여기서 예외가 발생하고 Advisor에서 핸드링하게 된다면 깊이가 깊어진다고 생각해요.

2023-11-06 04:51 UTC, park0jae commented on src/main/java/com/zerozae/voucher/controller/api/ApiWalletController.java
> +    public ResponseEntity<WalletResponse> createWallet(@Valid @RequestBody WalletCreateRequest walletCreateRequest) {
https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/5a4fcbc112365b6067a144c143c802f1bff5a103 

201 created http status 리턴 시 url을 함께 리턴해줘야 한다는 것을 처음 알게 되었습니다. 감사합니다 !

2023-11-06 04:52 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +public class ApiExceptionAdvisor {
https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/57ad5c6df3141fe807a3f1c919786ff1ebbfc16d

2023-11-08 01:13 UTC, park0jae commented on src/main/java/com/zerozae/voucher/common/advisor/ApiExceptionAdvisor.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
아 주영멘토님 말씀이 맞는것 같습니다. 다시 보니 HttpStatus가 중복해서 들어가고 있네요 ! 
https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/4c727dc861abe00b710eb141cef03590dd51543a https://github.com/prgrms-be-devcourse/springboot-basic/pull/945/commits/3dc3e772508bdf690650bb9da8c3312b88c22a72

2023-11-12 16:47 UTC, aegis1920 approved these changes
3단계까지 고생 많으셨습니다! 미션은 여기서 머지할게요~

2023-11-12 16:47 UTC, merged