[5기 김대휘] SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #950
Opened 2023-11-02 01:31 UTC by marooo326

## 📌 과제 설명 
**(기본)** **바우처 관리 애플리케이션**

- [x] 바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
    - customers 테이블 정의 및 추가
    - CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- [x] 바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
    - 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
    - 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
    - Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- [x] (1주차엔 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
    - 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
    - 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
    - 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.

**(심화)** **바우처 지갑을 만들어보세요.**
- [x] 특정 고객에게 바우처를 할당할 수 있습니다.
- [x] 고객이 어떤 바우처를 보유하고 있는지 조회할 수 있어야 합니다.
- [x] 고객이 보유한 바우처를 제거할 수 있어야 합니다.
- [x] 특정 바우처를 보유한 고객을 조회할 수 있어야 합니다.

## 👩‍💻 요구 사항과 구현 내용 

### 📌 프로젝트 DB 세팅방법
> ***docker-compose.yml*** 파일이 있는 디렉토리에서
> `docker-compose up -d` 명령어를 실행하시면, mysql 컨테이너가 동작하고 기본 스키마가 구성됩니다.
> 이 후, http://localhost:8080/ 으로 접속하시면 됩니다.

### controller
view를 반환하는 controller와 rest api를 위한 rest controller가 담긴 패키지입니다.

### domain
도메인인 customer, voucher, wallet을 작성하였습니다.
voucher 패키지에는 두 가지의 Voucher와 VoucherType Enum, VoucherFactory를 작성하였습니다.

### dto
Customer와 Voucher에 대한 DTO를 담은 패키지입니다.
레코드와 중첩 static 클래스를 활용하였습니다.

### exception
예외처리를 위한 exceptionHandler를 작성하였습니다.

### message
프로젝트에서 전반적으로 쓰이는 Message를 담아놓은 패키지입니다.
도메인별로 Enum을 구분하였으며, 예외 발생시에 사용하는 메세지는 ErrorMessage에 모아두었습니다.

### repsoitory
JDBC나 파일에 저장하는 역할의 Repository 클래스를 작성하였습니다.
인터페이스를 이용하여 추상화하였으며, 도메인별로 레포지토리를 작성하였습니다.

### service
도메인별로 주요한 서비스로직을 구현하였습니다.

### utils
프로젝트에서 전반적으로 사용되는 메서드를 정의해놓은 패키지입니다.
ConsoleUtil에는 입/출력 시, 자주사용되는 메서드를 static 메서드로 정의해놓았습니다.
CsvFileUtil에는 FileRepository에서 활용할 수 있도록 파일 입/출력의 주요한 로직을 묶어 놓았습니다.

### view
입/출력과 관련된 Console 클래스인 console을 작성하였습니다.

## ✅ PR 포인트 & 궁금한 점 
코멘트로 남기겠습니다!

2023-11-02 01:57 UTC, marooo326 reviewed
궁금한 점 질문드립니다!

2023-11-02 01:57 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/dto/VoucherDto.java
> +        private final float discountAmount;
중첩클래스로 여러 DTO를 묶어서 관리하고자 public 접근제한자를 이용하였습니다.
Week 2 리뷰에서 중첩 클래스의 접근 제한자를 default로 사용하라는 리뷰를 남겨주셨었는데, 이 경우 default 접근제한자를 사용하면 다른 패키지에서 접근이 되지 않아 DTO를 생성할 수 없게됩니다.
다른 해결방법이 떠오르지 않아 이대로 제출하였는데, 이런 방식으로 DTO를 작성하면 생길 수 있는 문제점이 궁금합니다!

2023-11-02 01:57 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
>      }
Service의 반환값(엔티티 or DTO)에 대한 멘토님의 의견이 궁금합니다!
현재는 다른 위치에서 해당 서비스를 사용하기 편리하게 하고자(불필요한 변환 로직이 많이 사용된다고 생각하여) 엔티티를 반환하였는데, 일반적으로는 캡슐화를 위해 DTO를 반환하는 것이 바람직한지 궁금합니다.

2023-11-03 06:38 UTC, aegis1920 requested changes
안녕하세요 멘토 빙봉입니다~ 코멘트 남겼으니 확인해주세요!

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/rest/RestCustomerController.java
> +@RequestMapping("/api/v1/customer")
REST 규칙을 따른다면 복수 형태가 되어야하지 않을까요?
```suggestion
@RequestMapping("/api/v1/customers")
```

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/rest/RestCustomerController.java
> +        return new ResponseEntity<>(customers, HttpStatus.OK);
ResponseEntity.ok() 라는 정적 빌더 메서드도 있으니 참고해주세요! 개인 취향으로 보여서 따로 적용하지 않으셔도 되긴 합니다!

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/rest/RestCustomerController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
응답에 Body가 없으면 content가 없다는 의미로 204 상태 코드를 return 하는 것이 좋습니다. ([링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204))

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/rest/RestCustomerController.java
> +        return new ResponseEntity<>(customer, HttpStatus.CREATED);
Created Status는 어떤 것을 반환해야 할까요? ([링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201))

2023-11-03 06:38 UTC, aegis1920 commented on src/main/resources/database/schema.sql
>      created_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
- 일반적으로 DB에 들어가는 생성일자 (created_at)은 `yyyy-MM-dd HH:mm:ss` 형식입니다!
- 만약 위 리뷰로 바꾼다면 요청을 받는 DTO에서도 LocalDateTime을 사용해야할 필요가 있어보입니다.

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/dto/VoucherDto.java
> +        private final float discountAmount;
간혹가다 Controller 내부에 public static class Response로 작성하신 분이 계셔서 착각했었던 것 같습니다! 문제는 없으며 수정하지 않으셔도 됩니다 🙇 

대휘님처럼 하나의 DTO 파일 안에 Response 및 Request를 다 넣는 방식이 있고 하나하나 별개의 자바 파일로 분리하는 방식이 있을텐데요. 이런 부분은 개인 취향으로 느껴집니다. 둘 다 괜찮아보여요!

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/exception/WebExceptionHandler.java
> +public class WebExceptionHandler {
ErrorController를 상속하는 것도 고려해보시면 좋을 것 같습니다! ([링크](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/api/org/springframework/boot/web/servlet/error/ErrorController.html))

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/exception/RestExceptionHandler.java
> +@ControllerAdvice(basePackages = "com.programmers.vouchermanagement.controller.rest")
Rest 응답이면 `@RestControllerAdvice`를 써야하지 않을까요?

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
> +                            !voucher.getCreatedAt().isAfter(endDate.atTime(23, 59, 59))
`endDate.atTime(23, 59, 59)` 이 부분은 함수로 빼서 더 명확하게 만들어주는 게 좋을 것 같아요. atEndOfDay() 처럼요

2023-11-03 06:38 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
> +    @Transactional(readOnly = true)
클래스에서 true로 설정해주셨는데 함수에도 true로 설정되어있습니다!

2023-11-03 06:38 UTC, aegis1920 commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
도메인에 대한 테스트 및 통합 테스트도 진행해봐주시면 좋을 것 같습니다!

2023-11-03 06:41 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
>      }
넵! 엔티티는 애플리케이션의 가장 안쪽에 있어야하는 레이어입니다. 조심히 다뤄져야 하고 변경에도 매우 민감한 부분이라 가급적이면 엔티티를 바로 반환하지 않고 DTO로 변환해서 반환해야합니다. 지금은 괜찮겠지만 추후 서비스가 매우 커질 때를 생각해봐주시면 좋을 것 같아요!

2023-11-05 07:49 UTC, marooo326 commented on src/main/java/com/programmers/vouchermanagement/controller/rest/RestCustomerController.java
> +        return new ResponseEntity<>(customer, HttpStatus.CREATED);
리뷰 남겨주셔서 감사합니다! API 관련해서 남겨주신 리뷰들을 아래 커밋에서 적용해보았습니다.
08376aacb35a513801a7ed65fb8d43872da675e3

ResponseEntity.ok()와 같은 방식이 좀 더 직관적이라고 느껴져서, 정적 빌더 메서드도 적용해 보았습니다!

2023-11-12 16:48 UTC, aegis1920 approved these changes
3단계까지 고생 많으셨습니다! 피드백은 추후 미션에서 반영해주세요!
이번 미션은 여기서 머지할게요~

2023-11-12 16:48 UTC, merged