[5기 이한나] SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #954
Opened 2023-11-02 05:09 UTC by annahxxl

## 👩‍💻 요구 사항과 구현 내용 

**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [x]  조회페이지
    - [x]  상세페이지
    - [x]  입력페이지
    - [x]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x]  전체 조회기능
    - [x]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능

**(보너스) 바우처 지갑용 관리페이지를 만들어보세요.**

### DB 세팅
```
docker-compose up -d
```

## ✅ 피드백 반영사항  
## ✅ PR 포인트 & 궁금한 점 
코멘트로 남기겠습니다!

2023-11-02 08:43 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
>      }
업데이트 요청 http 메서드를 put으로 생각하고 작성해서 지금은 현재 로직이 유효한데, 만약 patch 메서드를 사용하게 된다면 dto에 필드들이 많아짐에 따라 모두 분기 처리가 들어가야 하는 것인가요?

2023-11-02 09:12 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +
개발하다 보니 constructor가 계속 계속 늘어나고 있습니다. 번거롭게 느껴지기도 하고 조금 유연하게 도메인 객체를 생성하고 싶었는데요, 이와 같은 경우를 해결하기 위해 빌더 패턴을 고려하고 있습니다. 여기서 멘토님이 생각하시는 주의할 점이나 또 다른 대안이 있는지 궁금합니다.

2023-11-02 12:24 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/dto/voucher/request/UpdateVoucherRequestDto.java
> +}
해당 dto가 put 요청을 위한 dto라면 모든 바우처 필드들을 선언하는 것이 맞는 것일까요? 아니면 필요한 필드들만 선언해도 될까요?

2023-11-03 07:24 UTC, aegis1920 requested changes
멘토 빙봉입니다! 코멘트 남겼으니 확인해주세요! 그리고 기능이 Voucher 밖에 없는데 Customer 관리나 Wallet은 추후 추가되는 걸까요? 아니면 예정에 없는 걸까요?

2023-11-03 07:24 UTC, aegis1920 commented on build.gradle
![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/22311557/b20fca98-df0b-4bd1-bd46-a291f7b2f6a7)

어떤 이유에서 invalid인지 나타내주면 좋을 것 같습니다!

![image](https://github.com/prgrms-be-devcourse/springboot-basic/assets/22311557/2d74ca9d-2576-4561-aa5d-47252bd2222b)

fixed로 1000이라는 value는 왜 안될까요?

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/api/VoucherApiController.java
> +@RequestMapping("/vouchers")
api인지와 버전까지 명시해주면 좋습니다.
```suggestion
@RequestMapping("api/v1/vouchers")
```

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/api/VoucherApiController.java
> +        return ResponseEntity.created(URI.create("/vouchers/" + id.toString())).body(id);
👍

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/api/VoucherApiController.java
> +    @PostMapping()
괄호가 없어도 되지 않을까요?
```suggestion
    @PostMapping
```

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/command/VoucherShellController.java
> +        //! 고민 - param id vs dto id
코멘트로 남겨주시면 좋을 것 같습니다.

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
상수로 표현 가능할 것 같습니다.

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
> +        if (!Pattern.matches(regex, email)) {
Pattern.matches 안에 Pattern.compile을 보시면 매번 new Pattern을 통해 객체를 새로 생성하는데요. Pattern.compile 선언한 것을 상수로 만들면 매번 호출하지 않을 수 있습니다.

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
> +    private final long MIN_AMOUNT = 0L;
static이 빠진 것 같습니다!
```suggestion
    private static final long MIN_AMOUNT = 0L;
```

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
> +
빌더 패턴도 좋긴한데요. 지금 상황에서는 테스트에서 쓰이고 있는 코드가 많아보여요. 테스트만을 위한 코드가 프로덕션에 있으면 안됩니다. 확인해서 삭제해주시고, 기존에 있는 생성자를 활용해보셔도 좋을 것 같아요.

FixedAmountVoucher 클래스에서 아래처럼 null을 넣고 인자가 4개인 생성자를 그대로 활용할 수 있도록이요.

```
public FixedAmountVoucher(long amount, LocalDateTime createdAt) {
    super(null, VoucherType.FIXED_AMOUNT, amount, createdAt);
}
```

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/dto/customer/request/GetCustomersRequestDto.java
> +public class GetCustomersRequestDto {
여기는 record 클래스가 될 수 없나요?

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/dto/voucher/request/UpdateVoucherRequestDto.java
> +}
정말 REST를 엄격하게 본다면 모든 바우처 필드를 선언할 때 PUT으로 해야하고, 일부 필요한 필드만 선언하면 PATCH가 되어야할 것 같습니다. 지금 상황에서는 PATCH가 더 어울려보이네요.

2023-11-03 07:24 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/exception/ApiExceptionHandler.java
> +public class ApiExceptionHandler {
ResponseEntity 형태로 리턴한다면 [ResponseEntityExceptionHandler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/ResponseEntityExceptionHandler.html)를 활용해보세요!

2023-11-03 07:24 UTC, aegis1920 commented on src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
TestContainer도 적용하셨으니 Service에서도 통합 테스트를 해보는 걸 추천드립니다!

2023-11-05 06:35 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/controller/command/VoucherShellController.java
> +        //! 고민 - param id vs dto id
@aegis1920 앗 제가 작성해두고 놓쳤네요!

만약 update를 put 메서드를 이용하게끔 구현하도록 한다면,
엔드포인트는 PUT /vouchers/{voucherId} 일 경우
dto는 { id, type, amount } or { type, amount } 중에서 후자로 선언되면 되는것이 맞을까요?!

2023-11-05 10:31 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/dto/customer/request/GetCustomersRequestDto.java
> +public class GetCustomersRequestDto {
@aegis1920 record로 사용하는 게 더 적절한 것 같습니다! 8f738ea20b10b39f8447b1de607e211e6cc410e9, fc19f39b48500925758222c6b5b89c446a293bcb 반영했습니다. 그런데 자바에서는 별도로 필드들에 대해서 null 값이 들어온다고 표현을 못 해주는 것일까요? 그리고 필드들에 대해선 Optional을 사용하는 경우를 잘 못 보았는데 왜 그런 것인가요?! 제가 뭔가 null 처리 관련하여 부족한 부분이 있는 것 같은데 뭔가 참고할 만한 게 있을까요?

2023-11-05 10:57 UTC, annahxxl commented
@aegis1920 멘토님 리뷰 감사합니다!! 고객, 지갑 관리 기능은 추가 예정이 없습니다.. 🥲 아직 모든 리뷰 반영은 못했는데, 내일까지는 반영해 보겠습니다! 추가 코멘트 달아두었는데 확인해 주시고 도움 주시면 감사하겠습니다 🙇‍♀️

2023-11-05 10:58 UTC, annahxxl commented
+ ErrorController

2023-11-06 01:16 UTC, annahxxl commented on src/main/java/com/programmers/vouchermanagement/dto/customer/request/GetCustomersRequestDto.java
> +public class GetCustomersRequestDto {
@aegis1920 우선은 이번 RBF에서 정리 해 보았는데요, 혹시 보완해야하거나 잘못된 내용이 있으면 알려주시면 감사하겠습니다!! [Java Optional in class fields? Why not.](https://www.notion.so/backend-devcourse/Java-Optional-in-class-fields-Why-not-e160b9b17f6247f8a6092f874b69764a?pvs=4)

2023-11-12 16:50 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/controller/command/VoucherShellController.java
> +        //! 고민 - param id vs dto id
정답은 없지만 REST API는 path에 리소스를 나타내야하므로 후자로 선언되는 것이 더 나아보입니다!

2023-11-12 16:56 UTC, aegis1920 commented on src/main/java/com/programmers/vouchermanagement/dto/customer/request/GetCustomersRequestDto.java
> +public class GetCustomersRequestDto {
`@Nullable`을 사용해 null값이 들어올 수 있다고 표현해줄 수 있습니다. (Nullable을 사용하는 패키지는 다를 수 있습니다)
DTO의 경우 필드를 Optional하게 다룰 이유가 없기도 하고 RBF에서 이야기해주신대로 직렬화 문제도 있습니다! Optional로 감싸는 만큼 비용도 비용이구요

Optional 관련해서 이 글을 읽어보셔도 좋을 것 같습니다! ([링크](https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/))

2023-11-12 16:56 UTC, aegis1920 approved these changes
3단계까지 고생 많으셨습니다! 피드백은 추후 미션에서 반영해주세요!
이번 미션은 여기서 머지할게요~

2023-11-12 16:57 UTC, merged