[5기 김경훈] SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #956
Opened 2023-11-02 13:05 UTC by KarmaPol

## 📌 과제 설명 
**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용 해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [x] 조회페이지 ✅ 2023-11-01
    - [x] 상세페이지 ✅ 2023-11-01
    - [x] 입력페이지 ✅ 2023-11-01
    - [x] 삭제기능 ✅ 2023-11-01

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x] 전체 조회기능 ✅ 2023-11-01
    - [x] 조건별 조회기능 (바우처 생성기간 및 특정 할인타입별) ✅ 2023-11-02
    - [x] 바우처 추가기능 ✅ 2023-11-01
    - [x] 바우처 삭제기능 ✅ 2023-11-01
    - [x] 바우처 아이디로 조회 기능 ✅ 2023-11-01

**(보너스) 바우처 지갑용 관리페이지를 만들어보세요.**
- [x] 바우처 지갑용 관리 페이지  ✅ 2023-11-01
## 👩‍💻 요구 사항과 구현 내용 
- CustomerWebController, VoucherWebController : thymeleaf 페이지를 호출하는 컨트롤러입니다, Customer에서 사용자 Wallet을 관리합니다
- VoucherRestController : 요구사항에 맞게 전체 조회, 조건별 조회, 바우처 추가 및 삭제, 바우처 아이디로 조회 시 JSON, XML로 응답합니다
- ExceptionController : 전역 exception을 처리하여 thyme leaf페이지를 호출합니다
- util/validator/EnumNamePatternValidator : Enum값 VoucherDiscountType을 웹 요청 시 바로 검증합니다
- resources/templates : 타임리프 페이지들을 기능에 맞게 구현하였습니다
## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 테스트 코드 작성시, 단순히 id로 단건 조회, 삭제 등 비즈니스 로직이 없는 경우엔 의미가 없다는 생각이 들었습니다.
이전 멘토링때도 말씀해주셨듯이 필수적인 로직에만 테스트 코드를 짜는게 좋은 것 같은데, 다른 분들의 과제를 봤을때는 거의 모든 메소드에 대해 테스트를 짠 경우가 많았습니다. 이러한 단위 테스트가 갖는 이점이 있을까요?
- 예상하지 못하거나 의도하지 못한 Exception은 exception.class 핸들러를 만들어 일괄적으로 처리해주면 될까요?
이런 경우 어떻게 처리하시는지 궁금합니다!
- Enum이나 custom 객체를 request dto로 받아 argument resolver에서 바로 validation을 하고자, ConstraintValidator를 implement하는 custom validator를 만들어줘서 dto에서 어노테이션으로 validation을 할 수 있게 구현하였습니다.
이런 식으로 어노테이션을 만들어서 validation을 많이 하는지 궁금합니다.
- Enum이 Request로 들어올때 Argument Resolver의 Enum 기본 컨버터에 의해 Enum.valueof(String)으로 변환됩니다.
이때 들어오는 값이 Enum type 중 하나가 아니라면 오류가 터지는데, 
1. 새로운 Converter를 Spring에 등록, 일단 받아서 Default Enum으로 처리
2. Enum 값으로 받지 않고 Dto에서 String으로 받은 뒤, 검증 후 Enum으로 변환
3. 그냥 Exception 받아서 처리 (Exception 통제 어려움)
정도를 생각했습니다. Dto에 Enum을 넣는다면 어떤 식으로 처리하는게 좋을지 여쭤보고 싶습니다!

2023-11-02 13:07 UTC, KarmaPol commented on src/main/java/com/pgms/part1/util/validator/EnumNamePattern.java
> +    Class<? extends java.lang.Enum<?>> enumClass();
Enum이나 custom 객체를 request dto로 받아 argument resolver에서 바로 validation을 하고자, ConstraintValidator를 implement하는 custom validator를 만들어줘서 dto에서 어노테이션으로 validation을 할 수 있게 구현하였습니다.
이런 식으로 어노테이션을 만들어서 validation을 많이 하는지 궁금합니다.

2023-11-02 13:07 UTC, KarmaPol commented on src/main/java/com/pgms/part1/domain/voucher/dto/VoucherWebCreateRequestDto.java
> +
Enum이 Request로 들어올때 Argument Resolver의 Enum 기본 컨버터에 의해 Enum.valueof(String)으로 변환됩니다.
이때 들어오는 값이 Enum type 중 하나가 아니라면 오류가 터지는데,
1. 새로운 Converter를 Spring에 등록, 일단 받아서 Default Enum으로 처리
2. Enum 값으로 받지 않고 Dto에서 String으로 받은 뒤, 검증 후 Enum으로 변환
3. 그냥 Exception 받아서 처리 (Exception 통제 어려움)      

정도를 생각했습니다. Dto에 Enum을 넣는다면 어떤 식으로 처리하는게 좋을지 여쭤보고 싶습니다!

2023-11-03 15:43 UTC, aegis1920 requested changes
안녕하세요 멘토 빙봉입니다! 

> 테스트 코드 작성시, 단순히 id로 단건 조회, 삭제 등 비즈니스 로직이 없는 경우엔 의미가 없다는 생각이 들었습니다. 이전 멘토링때도 말씀해주셨듯이 필수적인 로직에만 테스트 코드를 짜는게 좋은 것 같은데, 다른 분들의 과제를 봤을때는 거의 모든 메소드에 대해 테스트를 짠 경우가 많았습니다. 이러한 단위 테스트가 갖는 이점이 있을까요?

말씀대로 지금 상황에서는 단위 테스트가 갖는 이점이 없어보입니다! 단순히 voucher 조회면 단순하게 voucher만 조회하고 끝나니까요. 다만 여기에서 외부 연동을 거치는 등  좀 더 복잡한 로직이 추가된다면 이야기가 달라지겠지요. 그때를 위해서 단위테스트를 작성해준다고 생각하시면 좋을 것 같습니다. (+ 단위테스트 작성을 연습한다고 봐도 좋을 것 같아요)

> 예상하지 못하거나 의도하지 못한 Exception은 exception.class 핸들러를 만들어 일괄적으로 처리해주면 될까요?
이런 경우 어떻게 처리하시는지 궁금합니다!

ExceptionController.handelCommonException을 말씀하신 게 맞을까요? 맞다면 잘 작성해주셨습니다!  실무에서도 그렇게 작성하는데요. 이와 관련해서 추가 코멘트는 해당 코드에 남길게요!

코멘트 확인 부탁드리며 궁금한 점이 생겼을 시 PR 궁금한 점에 남기기 보단 PR을 올린 후 코멘트로 따로 남겨주시면 감사하겠습니다. 🙇

2023-11-03 15:43 UTC, aegis1920 commented on src/main/resources/templates/vouchers/vouchersCreatePage.html
> +      <label for="discount">할인률</label>
오타 확인해주세요!
```suggestion
      <label for="discount">할인율</label>
```

그리고 FIXED 타입도 있으니 할인 값이 되어야하지 않을까요?

2023-11-03 15:43 UTC, aegis1920 commented on src/main/resources/templates/vouchers/vouchersCreatePage.html
> +      <input type="text" name="voucherDiscountType" placeholder="FIXED_AMOUNT_DISCOUNT or PERCENT_DISCOUNT">
input이 아닌 dropbox 형태로 나타내주면 사용자 입장에서 편할 것 같습니다!

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/voucher/entity/Voucher.java
> +        if(voucherDiscountType.equals(VoucherDiscountType.PERCENT_DISCOUNT)){
PERCENT_DISCOUNT와 FIXED_AMOUNT_DISCOUNT 조건이 바뀐 건 아닌지 확인 부탁드려요~

2023-11-03 15:43 UTC, aegis1920 commented on src/main/resources/application.yml
지금 docker로 띄운 mysql과 연결되지 않는 상태인데요. 확인 한 번 부탁드려요~

2023-11-03 15:43 UTC, aegis1920 commented on schema.sql
> +create table vouchers(
테이블 명이 왜 복수일까요?

2023-11-03 15:43 UTC, aegis1920 commented on schema.sql
> +    discount int,
단순히 discount가 아닌 값이라는 의미도 나타내면 좋을 것 같습니다! e.g. discount_value

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/config/AppConfig.java
> +    @Profile("prod")
docker를 실행하고 profile을 prod로 설정한 뒤 실행했을 때 잘 되실까요? 확인 한 번 해주세요!

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/customer/service/CustomerService.java
> +    public void isEmailNull(String email){
특정 예외 메시지를 나타내는 게아니라면 DTO 클래스에 `@Nonnull`을 붙여줘도 괜찮을 것 같네요

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/voucher/controller/VoucherRestController.java
> +@RequestMapping("/api")
버전도 명시해주면 좋습니다!
```suggestion
@RequestMapping("/api/v1")
```

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/voucher/dto/VoucherWebCreateRequestDto.java
> +
이 부분은 정책에 따라 다릅니다. 

만약에 정의한 Enum이 들어오더라도 기본 Enum으로 처리하고 싶다면 1번 처럼 처리하시면 됩니다. 

2번의 경우, 검증 후 Enum으로 변환한다고 하셨는데요. 검증할 때 맞지 않다면 Exception을 다시 던질 거기 때문에 3번과 비슷하지만 예외를 직접 정의해서 핸들링할 수 있으므로 3번보다 좀 더 유연하게 느껴집니다.

3번은 따로 핸들링하지 않았다면 Exception.class를 핸들링하는 ExceptionHandler에서 예외 응답이 반환되겠죠. 

정의한 Enum이 아니라면 클라이언트가 잘못 보낸 게 맞으므로 1번은 아니라고 생각되고, 2번 아니면 3번인데 둘 다 괜찮은 방법 같습니다. 특별하게 예외 메시지를 다르게 줄 게 아니라면 3번으로 처리하는 게 좋아보입니다.

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/domain/voucher/repository/VoucherJdbcRepository.java
> +                sql.append(" DATE(created_at) =?");
포맷팅 맞춰주세요!

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/exception/ErrorCode.java
> +    ErrorCode(int i, String s) {
인자명 명확하게 주면 좋을 것 같습니다.

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/exception/ErrorCode.java
> +public enum ErrorCode {
👍

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/exception/ExceptionController.java
> +public class ExceptionController {
예외 페이지를 핸들링 하기 위한 [ErrorController](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/api/org/springframework/boot/web/servlet/error/ErrorController.html)도 활용해보세요!

2023-11-03 15:43 UTC, aegis1920 commented on src/main/java/com/pgms/part1/util/validator/EnumNamePattern.java
> +    Class<? extends java.lang.Enum<?>> enumClass();
필요하면 구현하긴 할텐데 validation 자체는 비즈니스 로직에서 많이 해서요. 따로 어노테이션을 만들어서 하진 않습니다! 지금 하시는 validation도 어노테이션을 뺄 만한 가치가 있는지 고민해보시는 것도 좋을 것 같아요!

2023-11-12 16:57 UTC, aegis1920 approved these changes
3단계까지 고생 많으셨습니다! 피드백은 추후 미션에서 반영해주세요!
이번 미션은 여기서 머지할게요~

2023-11-12 16:57 UTC, merged