[5기 김별이] SpringBoot Part3 Weekly Mission 제출합니다
prgrms-be-devcourse/springboot-basic pull request #959
Opened 2023-11-02 16:34 UTC by byulcode

## 👩‍💻 요구 사항과 구현 내용 

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용 해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [x]  조회페이지
    - [x]  상세페이지
    - [x]  입력페이지
    - [x]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x]  전체 조회기능
    - [x]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능

**DB 세팅**
```
docker-compose up -d
```

## ✅ PR 포인트 & 궁금한 점 
리뷰로 남기겠습니다!

2023-11-02 17:08 UTC, byulcode commented on docker-compose.yml
> +      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
2차 피드백 주신 대로 docker-compose 설정했습니다!

2023-11-02 17:08 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
> +            case PERCENT -> new PercentDiscountVoucher(voucherId, DiscountType.find(discountType), discountValue, createdAt);
> discountType에 따라 생성되는 voucher의 종류를 구분하는 로직 위치를 서비스 -> 엔티티로 변경했습니다.
해당 로직이 서비스와 레포지토리에서 중복되어 이를 없애고자 변경했습니다!

2023-11-02 17:08 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/service/VoucherService.java
> +
조회 조건에 따라 구분하는 로직을 서비스단에 두었는데, 레파지토리에서 동적 쿼리로 조절하는 것이 더 나은 선택일지 궁금합니다!

2023-11-02 17:08 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/common/handler/ApiExceptionHandler.java
> +    }
에러 핸들러 사용에 익숙하지 않아서 예외와 핸들러에 대해 전반적인 피드백 부탁드립니다!

2023-11-04 06:41 UTC, aegis1920 requested changes
안녕하세요 멘토 빙봉입니다! 코멘트 남겼으니 확인 부탁드려요~

2023-11-04 06:41 UTC, aegis1920 commented on docker-compose.yml
> +      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
👍

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/SpringBasicApplication.java
> +    public HiddenHttpMethodFilter hiddenHttpMethodFilter() {
- 해당 필터는 어떤 이유에서 빈으로 등록해주셨을까요?
- main 메서드가 있는 곳은 main 메서드에 관련된 부분만 실행되어야합니다. Filter는 main과 관계가 없으므로 따로 Config 클래스를 만들어서 Bean으로 등록해주는 게 좋지 않을까요?

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/common/handler/ApiExceptionHandler.java
> +    }
- 잘 구현해주셨습니다!
- 보통 에러 응답은 ErrorResponse라는 클래스로 따로 공통 규격으로 만들어주므로 공통 규격이 있으면 좀 더 좋을 것 같고
- ResponseEntity 형태로 리턴한다면 [ResponseEntityExceptionHandler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/ResponseEntityExceptionHandler.html)를 활용해보시는 걸 추천드립니다!

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/common/handler/WebExceptionHandler.java
> +@ControllerAdvice(annotations = Controller.class)
Controller로 구분해서 에러 페이지를 내보내기보단 ErrorController를 구현하는 걸 고려해보시면 좋을 것 같습니다! ErrorController를 구현하는 AbstractErrorController나 BasicErrorController를 살펴봐주세요! ([링크](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/api/org/springframework/boot/web/servlet/error/ErrorController.html))

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerApiController.java
> +        return ResponseEntity.ok(customer);
201 created http status를 사용해보는 건 어떨까요? ([링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201))

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerApiController.java
> +@RequestMapping("/api/customers")
버전도 명시해주면 좋을 것 같습니다!
```suggestion
@RequestMapping("/api/v1/customers")
```

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerApiController.java
> +    public ResponseEntity<List<CustomerResponse>> findBlackLists() {
```suggestion
    public ResponseEntity<List<CustomerResponse>> findBlackList() {
```

2023-11-04 06:41 UTC, aegis1920 commented on src/main/resources/schema.sql
column 명은 항상 소문자여야합니다! ([링크](https://medium.com/@centizennationwide/mysql-naming-conventions-e3a6f6219efe))

e.g. is_blacklist or is_black_list or is_banned

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/controller/VoucherApiController.java
> +        return ResponseEntity.ok("Voucher deleted");
204 no content를 알아볼까요? ([링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204))

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
> +            case PERCENT -> new PercentDiscountVoucher(voucherId, DiscountType.find(discountType), discountValue, createdAt);
어떤 말을 해주고 싶으셨던 걸까요? 이전 코멘트에서 좀 더 말씀드리면 Voucher에서 자신을 만들지 않고 VoucherFactory 같이 역할이 좀 더 명확한 클래스에서 Voucher를 생성하는 건 어떨까요?

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/repository/JdbcVoucherRepository.java
> +    private static final String FIND_BY_DISCOUNT_TYPE = "SELECT * FROM vouchers WHERE discount_type = ?";
쿼리를 상수로 뺀 것은 어떤 이점이 있어서 빼신 걸까요?

2023-11-04 06:41 UTC, aegis1920 commented on src/main/java/com/prgrms/springbasic/domain/voucher/service/VoucherService.java
> +
Application에서 로직을 작성하냐 DB에서 로직을 작성하냐인데요. 상황에 따라 다릅니다. (성능, 유지보수에 차이가 있습니다.) 지금은 쿼리가 복잡하지 않아서 서비스 로직에서 작성하는 것도 괜찮아보입니다. 다만 나중에 성능이 필요한 복잡한 쿼리를 작성할 때도 있으실텐데 그때를 대비해서 동적 쿼리를 작성해보는 것도 추천드립니다.

2023-11-04 06:41 UTC, aegis1920 commented on src/test/java/com/prgrms/springbasic/domain/voucher/service/VoucherServiceTest.java
테스트 전체 실행 해보셨을까요? 터지는 테스트가 있습니다. 확인 부탁드립니다. 그리고 예외 테스트 케이스 추가 및 서비스 레이어에서 통합 테스트하는 것도 해보시면 좋을 것 같습니다!

2023-11-05 09:36 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/SpringBasicApplication.java
> +    public HiddenHttpMethodFilter hiddenHttpMethodFilter() {
html form에서 patch와 delete 메소드를 지원하기 위해 사용했었습니다. 다시 찾아보니 스프링5 이전에서만 필요한 필터이고, yml의 hidden-method 활성화 만으로도 지원 가능하다고하여 해당 필터는 제거하겠습니다!

2023-11-05 12:14 UTC, byulcode commented on src/main/java/com/prgrms/springbasic/domain/voucher/controller/VoucherApiController.java
> +        return ResponseEntity.ok("Voucher deleted");
http 응답 수정했습니다! [acee548](https://github.com/prgrms-be-devcourse/springboot-basic/pull/959/commits/acee5489761aac6d0342e1ae043ae595e554de99)

2023-11-05 12:38 UTC, byulcode commented on src/test/java/com/prgrms/springbasic/domain/voucher/service/VoucherServiceTest.java
테스트코드가 커밋이 안됐었던 것 같습니다. 수정했습니다! [af4a4d0](https://github.com/prgrms-be-devcourse/springboot-basic/pull/959/commits/af4a4d075c830c53ce4bbb2e4195472f76d0c705)
추후 통합테스트 추가해서 올리겠습니다

2023-11-12 16:58 UTC, aegis1920 approved these changes
3단계까지 고생 많으셨습니다! 피드백은 추후 미션에서 반영해주세요!
이번 미션은 여기서 머지할게요~

2023-11-12 16:58 UTC, merged