[5기 - 조은비] SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #962
Opened 2023-11-03 04:01 UTC by eunbc

## 📌 과제 설명 
**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용 해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [x]  조회페이지
    - [x]  상세페이지
    - [x]  입력페이지
    - [x]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x]  전체 조회기능
    - [x]  조건별 조회기능 (바우처 생성기간 및 특정 할인타입별)
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능

**(보너스) 바우처 지갑용 관리페이지를 만들어보세요.**

## ✅ PR 포인트 & 궁금한 점 

코멘트로 남겨놓겠습니다!

2023-11-03 04:32 UTC, eunbc reviewed
궁금한 내용을 코멘트로 남겼습니다!
감사합니다 🙌

2023-11-03 04:32 UTC, eunbc commented on src/main/java/com/programmers/springbasic/advice/GlobalRestControllerAdvice.java
> +		);
개발자가 보는 로그는 자세하게 남기되, 클라이언트에게 보내는 에러 메세지는 간결하게 기록하였습니다.

개인적으로는 클라이언트에게 기술적인 세부 사항을 자세하게 공유하기 보다는 간결한 메세지만 나타내어야 한다고 생각하는데, 
클라이언트에게 예외 상황에 관한 메세지를 어느 정도까지 자세하게 알려야 하는지 멘토님 의견이 궁금합니다!

2023-11-03 04:32 UTC, eunbc commented on src/main/java/com/programmers/springbasic/VoucherApplication.java
> +})
콘솔 관련 패키지를 @ComponentScan에서 제외하였습니다!

2023-11-03 04:32 UTC, eunbc commented on src/main/java/com/programmers/springbasic/repository/dto/customer/CreateCustomerRequest.java
> +	@NotBlank @Email String email
dto에 대한 validation을 할 때, 어느 정도까지 자세하게 검증해야 할까요?
null, blank, 데이터 타입, 정규식을 통한 유효값 검증 등 다양한 검증을 할 수 있는데 멘토님은 어떤 범위까지 하는 것을 선호하는지 궁금합니다!

2023-11-03 04:32 UTC, eunbc commented on src/main/java/com/programmers/springbasic/controller/CustomerRestController.java
> +	public ResponseEntity<CustomerResponse> getCustomerById(@PathVariable UUID customerId) {
PathVariable 값에 대한 validation 처리를 해주어야 할지 고민이 됩니다.
빈 값 체크나 타입 체크를 서버 단에서 검증해주어야 할지...
프로젝트마다 많이 다르겠지만, 실무에서는 어떤 방식을 많이 사용하는지 궁금합니다!

2023-11-04 07:19 UTC, aegis1920 requested changes
안녕하세요 멘토 빙봉입니다! 코멘트 남겼으니 확인해주세요~

2023-11-04 07:19 UTC, aegis1920 commented on src/main/resources/application.yml
h2도 DB긴 DB라서 따로 말씀은 안드렸는데요! 시간되실 때 인메모리 DB가 아닌 docker-compose를 사용해서 mysql DB를 띄워보시면 좋을 것 같습니다!

2023-11-04 07:19 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/VoucherApplication.java
> +})
처음부터 분리를 잘 해놓으셔서 컴포넌트 스캔에서 제외시켜주기만 하면 되는군요 👍

2023-11-04 07:19 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/advice/ErrorResponse.java
> +public record ErrorResponse(int status, String message) {
공통 규격 👍

2023-11-04 07:19 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/advice/GlobalRestControllerAdvice.java
> +		);
> 클라이언트에게 기술적인 세부 사항을 자세하게 공유하기 보다는 간결한 메세지만 나타내어야 한다고 생각하는데,

상황에 따라 다르긴 하지만 대개 사용자 입장에서 잘 이해할 수 있도록 작성해야합니다. UX 적으로도 그렇고요. 예외 메시지에 대한 이야기는 제가 따로 슬랙 채널에 올리겠습니다!

2023-11-04 07:19 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/advice/GlobalRestControllerAdvice.java
> +public class GlobalRestControllerAdvice {
``
ResponseEntity 형태로 리턴한다면 [ResponseEntityExceptionHandler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/ResponseEntityExceptionHandler.html)를 활용해보세요!

2023-11-04 07:19 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/controller/CustomerRestController.java
> +		return new ResponseEntity<>(customerResponse, HttpStatus.CREATED);
201 created 메시지는 어떤 걸 리턴해야될까요? ([링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201))

2023-11-04 07:19 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/controller/CustomerRestController.java
> +	public ResponseEntity<CustomerResponse> getCustomerById(@PathVariable UUID customerId) {
FE에서 체크를 하더라도 검증 자체는 백엔드에 꼭 있어야 합니다! 보통 `@Nonnull`로 널 체크를 하고 빈 값이나 타입 체크의 경우 서비스 레이어 혹은 커스텀 Validator를 사용합니다.

2023-11-04 07:19 UTC, aegis1920 commented on src/main/java/com/programmers/springbasic/repository/dto/customer/CreateCustomerRequest.java
> +	@NotBlank @Email String email
할 수 있다면 최대한 다양하게 검증하면 좋습니다! 👍 저도 가능하면 많은 범위를 검증하는 것을 선호합니다.

2023-11-04 07:19 UTC, aegis1920 commented on src/test/java/com/programmers/springbasic/service/CustomerServiceTest.java
Mock이 아닌 서비스 레이어에서 `@TestContainer`를 활용해 통합 테스트도 작성해보시면 좋을 것 같습니다!

2023-11-05 10:08 UTC, eunbc commented on src/main/resources/application.yml
적용 완료하였습니다! [9c42363](https://github.com/prgrms-be-devcourse/springboot-basic/pull/962/commits/9c42363d9a9627b3bf7ecd9c3087455fb64cb484)

2023-11-05 10:09 UTC, eunbc commented on src/main/java/com/programmers/springbasic/advice/GlobalRestControllerAdvice.java
> +public class GlobalRestControllerAdvice {
적용 완료하였습니다! [2a8675a](https://github.com/prgrms-be-devcourse/springboot-basic/pull/962/commits/2a8675aaec29e8c058228221ba1c5a8e0bc463e4)

2023-11-05 10:11 UTC, eunbc commented on src/main/java/com/programmers/springbasic/controller/CustomerRestController.java
> +		return new ResponseEntity<>(customerResponse, HttpStatus.CREATED);
생성된 리소스의 URI인 Location 헤더 값을 추가하였습니다! [36f0385](https://github.com/prgrms-be-devcourse/springboot-basic/pull/962/commits/36f0385d82bde145c5e135220ac30874fb51ac81)

2023-11-05 10:18 UTC, eunbc commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS wallet;
실행 편의를 위하여 어플리케이션을 실행할 때마다 도커 컨테이너를 삭제하는 대신 테이블을 초기화해주도록 작성했습니다!

2023-11-05 10:28 UTC, eunbc commented on src/test/java/com/programmers/springbasic/service/CustomerServiceTest.java
통합 테스트는 다음 과제에서 꼭 작성해보도록 하겠습니다! 🙇‍♀️

2023-11-05 22:32 UTC, cloudwi commented on src/main/java/com/programmers/springbasic/advice/GlobalRestControllerAdvice.java
> +		ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_REQUEST.value(), errorMessages.toString());
HTTP Status가 중복으로 들어가지 않나요?

즉 errorResponse 에 HTTP Status 포함되고 ResponseEntity를 생성할때 한번더 넣어주고 있는 것으로 보입니다.

2023-11-05 22:32 UTC, cloudwi commented on src/main/java/com/programmers/springbasic/repository/voucher/FileVoucherRepository.java
> +		return null;
무조건 null이 반환되는 건 어떤 이유인가요?

2023-11-12 16:59 UTC, aegis1920 approved these changes
3단계까지 고생 많으셨습니다! 피드백은 추후 미션에서 반영해주세요!
이번 미션은 여기서 머지할게요~

2023-11-12 16:59 UTC, merged