[5기 - 엄예림] SpringBoot Part3 Weekly Mission 제출합니다.
prgrms-be-devcourse/springboot-basic pull request #967
Opened 2023-11-05 11:11 UTC by yenzip

## 👩‍💻 요구 사항과 구현 내용 
**(기본) 바우처 서비스 관리페이지 개발하기**

- Spring MVC를 적용해서 thymeleaf 템플릿을 설정해보세요.
- 커맨드로 지원했던 기능을 thymeleaf를 이용해서 관리페이지를 만들고 다음 기능을 지원가능하게 해보세요
    - [x]  조회페이지
    - [x]  상세페이지
    - [x]  입력페이지
    - [x]  삭제기능

**(기본) 바우처 서비스의 API 개발하기**

- Spring MVC를 적용해서 JSON과 XML을 지원하는 REST API를 개발해보세요
    - [x]  전체 조회기능
    - [x]  조건별 조회기능 (특정 할인타입별)
    - [x]  바우처 추가기능
    - [x]  바우처 삭제기능
    - [x]  바우처 아이디로 조회 기능

 - [ ] (보너스) 바우처 지갑용 관리페이지를 만들어보세요.
 <br/>

## ✅ 피드백 반영사항  

- static 메서드와 인스턴스 메서드 올바르게 적용
- 객체지향 생활체조 원칙 중 메서드 내 1 depth 원칙 적용
- H2에서 MySQL로 DB 변경
- @ParameterizedTest 적용
- Service에서 ID 생성을 도메인에게 위임
- 조회 관련 메서드 @Transactional(readOnly = true) 적용
- 사용하지 않은 주석 및 공백 제거
<br/>

## ✅ PR 포인트 & 궁금한 점 
해당 커밋 [186e46e](https://github.com/yenzip/springboot-basic/commit/186e46e1d23020f2af1a95ee393a071ac3db6dea) 이후부터 피드백 해주시면 감사하겠습니다!

### 실행 방법
docker 폴더로 이동해 아래 명령어를 입력하면 MySQL을 실행시킬 수 있습니다.

> docker-compose up -d

### 궁금한 점
- 데이터를 바인딩하기 위해 RequestDto에 setter를 추가했습니다. 하지만 Dto에서 setter는 값이 변경될 위험이 있기에 지양하는 것이 맞다는 생각이 들었습니다. Dto에서 setter를 사용하는 것이 적절한지 궁금합니다.
- Thymeleaf에서 사용하기 위해 RequestDto에 기본 생성자를 추가하는 것이 적절한지 궁금합니다.
- 컨트롤러 레이어만 테스트하기 위해 @WebMvcTest를 사용해 API Controller 테스트를 수행했습니다. 바우처나 고객 생성 관련 테스트에서는 Controller만으로 테스트가 불가능한 문제가 발생했습니다. 따라서 생성과 관련된 테스트를 수행하려면 모든 빈을 등록하는 @SpringBootTest를 사용하는 것이 더 적절한지 궁금합니다.

2023-11-05 11:28 UTC, ksy90101 requested changes
게더에서 동기 리뷰를 하기 전에 몇개 남겨봤어요 :)
DTO와 REST API규칙을 좀더 고민해보셨으면 좋겠어요.

2023-11-05 11:28 UTC, ksy90101 commented on docker/docker-compose.yml
> +      TZ: 'Asia/Seoul'
(질문) UTC로 안한 이유가 따로 있나요?

2023-11-05 11:28 UTC, ksy90101 commented on docker/db/mysql/init/init.sql
> +insert into vouchers(voucher_id, voucher_type, discount_value) values(UUID_TO_BIN("b1badc1d-be2a-454a-b85b-f01e44ef8ad6"), "PERCENT", 10);
차후 프로덕션에 실행될때도 이게 계속 들어갈꺼 같은데, 이러면 문제가 되지 않을까요?
기본으로 값이 들어가게 만든건 좋지만 이렇게 관리하기보단 각자 관리하는게 더 좋을거 같아요.

2023-11-05 11:28 UTC, ksy90101 commented on logs/error_2023-10-19.log
> +21:39:34.178 [main] ERROR o.p.springorder.console.Console -- errorMessage = 잘못된 입력 값입니다. 100 ~ 10000 사이의 값을 입력해주세요.
로그는 과연 git에 올릴만한 파일일까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/controller/customer/CustomerViewController.java
> +    }
/customers/new-customers
이런 형태가 될거 같은데, new-customers와 같은 형태가 더 어울리지 않을까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/controller/customer/CustomerViewController.java
> +    public String newCustomer(@ModelAttribute CustomerRequestDto request) {
(질문) 해당 부분은 rest api로 만들지 않은 이유가 무엇인가요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/controller/customer/CustomerViewController.java
> +    }
위에 reset api와 충돌 아닌가요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/controller/customer/CustomerApiController.java
> +                .body(response);
return  ResponseEntity.created(URI.create("/Member/"+id)).build();
이런식으로 많이 작성하는 편인데요. 한번 이런 코드를 알아보면 어떨까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/controller/customer/CustomerApiController.java
> +    }
위에선 DTO가 나오는데, 아래에선 Customer 자체가 나오는데 혹시 의도한게 무엇일까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/controller/voucher/VoucherApiController.java
> +    }
type별로 다른 값을 내려주고 싶은거 같은데, rest api의 url엔 resource가 들어가게 됩니다.
이렇게 필터링을 할 경우엔 QuesyString을 사용해서 필터링을 많이 하는거 같아요.
즉, findAll와 해당 API가 통합해서 재사용성을 한번 해보면 어떨까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/dto/voucher/VoucherRequestDto.java
> +    }
https://mosei.tistory.com/entry/DTO-%EB%A5%BC-%EB%8D%94%EC%9A%B1-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

이글을 참고해서 setter를 없애고 더 안전하게 dto를 사용해보면 어떨까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/global/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
404 NotFound 와 같은 에러는 필요 없을까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/global/utils/UUIDUtil.java
> +    ;
잘못들어간거 가탕요~

2023-11-05 11:28 UTC, ksy90101 commented on src/main/java/org/programmers/springorder/model/voucher/Voucher.java
> +    private long discountValue;
여기엔 validate가 없네요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/resources/logback.xml
> +        <!--        <file>log/access.log</file>&lt;!&ndash; 2021-07-01 &ndash;&gt;-->
안쓰는 주석은 제거하면 어떨까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/resources/templates/customer/addForm.html
> +    </style>
css 파일로 관리해보시겠어요?
백엔드라고해서 프론트를 조금이라도 이해해두면 좋아요.

2023-11-05 11:28 UTC, ksy90101 commented on src/main/resources/templates/customer/customer.html
> +    </style>
위의 css와 주옵ㄱ이네요.
중복을 어떻게 제거해볼수 있을까요?

2023-11-05 11:28 UTC, ksy90101 commented on src/main/resources/templates/customer/customer.html
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
https://dev-overload.tistory.com/25

이런식으로 공통으로 관리해보면 어떨까요?

2023-11-09 11:37 UTC, twotwobread commented on src/main/java/org/programmers/springorder/controller/voucher/VoucherApiController.java
> +    @DeleteMapping("{id}")
path를 구분할 수 있게 /를 넣어주면 좋을 것 같습니다.

2023-11-09 11:37 UTC, twotwobread commented on src/main/java/org/programmers/springorder/controller/voucher/VoucherViewController.java
> +    @PostMapping("/{id}")
DELETE method를 사용하면 더 좋을 것 같습니다.

2023-11-09 11:37 UTC, twotwobread commented on src/main/java/org/programmers/springorder/dto/customer/CustomerRequestDto.java
> +    public String getName() {
record를 통해서 dto에서 발생하는 보일러 플레이트 코드들을 해결할 수 있을 것 같습니다.

2023-11-09 11:37 UTC, twotwobread commented on src/main/java/org/programmers/springorder/service/CustomerService.java
> +        this.findById(customerId);
현재 클래스의 메서드를 사용한다면 this가 필요없을 것 같습니다.

2023-11-09 11:37 UTC, twotwobread commented on src/main/java/org/programmers/springorder/service/VoucherService.java
> +            throw new IllegalArgumentException(voucherType.name() + ErrorMessage.VOUCHER_TYPE_NOT_EXIST_MESSAGE);
다른 리스트들을 찾을 때는 exception을 발생시키지 않는데 여기서는 exception을 발생시키는 이유가 있나요?? type 자체가 잘못된 값이 들어오는 경우가 아니라 해당 타입의 바우처가 없는 경우는 다른 리스트 조회랑 같은 로직아닐까요?

2024-04-18 20:21 UTC, closed without merging